### ISSUE TITLE
Default promiseFactory is ReactorPromiseFactory NOT Gpars

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-core#10004]
The [documentation states](http://docs.grails.org/latest/guide/async.html#promises) that the default promise factory is a GPars promise factory.  This is not true.  The default is a ReactorPromiseFactory.  Not sure if this is intentional and what side effects this may cause or how Reactor differs in implementation from the GPars one.

The first time the code asks for a factory it has already been set by the [ControllersAsyncGrailsPlugin](https://github.com/grails/grails-core/blob/master/grails-plugin-async/src/main/groovy/org/grails/plugins/web/async/ControllersAsyncGrailsPlugin.groovy#L45) below.

<img width="1372" alt="screen shot 2016-06-21 at 10 56 17 am" src="https://cloud.githubusercontent.com/assets/691357/16236684/d5c1f3a2-379e-11e6-9497-84a3cd256fa3.png">

This sets default promise factory to Reactor one.  It is done via [this line](https://github.com/grails/grails-core/blob/master/grails-plugin-async/src/main/groovy/org/grails/plugins/web/async/ControllersAsyncGrailsPlugin.groovy#L45).

<img width="1378" alt="screen shot 2016-06-21 at 10 54 04 am" src="https://cloud.githubusercontent.com/assets/691357/16236683/d5c18462-379e-11e6-9671-a0a27cb6708b.png">

The code during boot of the application that is defaulting the PromiseFactory

<img width="1381" alt="screen shot 2016-06-21 at 10 53 44 am" src="https://cloud.githubusercontent.com/assets/691357/16236682/d5c109c4-379e-11e6-9131-971ffc7b52ef.png">

**Comment by ctoestreich** [comment]
It does actually set the promiseFactory to the gpars one before the controller plugin runs, but it is overwritten by the controller plugin.

**Comment by graemerocher** [comment]
This is a error on the documentation

**Comment by ctoestreich** [comment]
@graemerocher Perhaps, but the way it goes about first constructing the gpars one, then replaces it seems like a side effect.  If the default is Reactor, then the controller class shouldn't be forcing it to Reactor, the call to the Promises.getFactory should switch the default from Gpars when null to Reactor.  The Controller async plugin could then simply ask for a factory and not cause a side effect of overwriting the already set factory.

Either way if Reactor is the new preferred, the docs should be updated.

**Comment by graemerocher** [comment]
Documentation updated
