### ISSUE TITLE
Grails 2.5.4 using an old grails-datastore version dependency

### ISSUE THREAD

**Issue by mburak** [grails/grails-core#10001]
We are having a conflict when building the war for our project because we have 2 versions of grails-datastore-xxx. It's trying to use 3.1.5 version when it should use 5.0.8.  

For example, this is why we get running a dependency-report:

+--- org.grails:grails-plugin-testing:2.5.4
|    \--- org.grails:grails-plugin-converters:2.5.4
|    \--- cglib:cglib:2.2.2
|         \--- asm:asm:3.3.1
|    \--- org.grails:grails-plugin-mimetypes:2.5.4
|    \--- org.grails:grails-plugin-domain-class:2.5.4
|         \--- org.grails:grails-datastore-gorm:3.1.5.RELEASE
|         \--- org.grails:grails-datastore-simple:3.1.5.RELEASE
|         \--- org.grails:grails-datastore-core:3.1.5.RELEASE
|              \--- javax.transaction:jta:1.1

### Environment Information

- **Operating System**: OS X
- **Grails Version:** 2.5.4
- **JDK Version:** 1.8

**Comment by mburak** [comment]
Btw, if you see this file: https://github.com/grails/grails-core/blob/2.5.x/build.gradle, it says:
    `datastoreVersion = "3.1.5.RELEASE"`

Shouldn't that be the new one?

**Comment by jeffbrown** [comment]
I have created https://github.com/jeffbrown/newgorm to try and recreate the problem.  I will go through the dependency report that you emailed and see if we can chase it down.

Thanks for the feedback and I will keep you posted.

**Comment by jeffbrown** [comment]
The only 3.1.5 dependencies I see in your dependency report are test scoped dependencies.  Is that what you are seeing?
