### ISSUE TITLE
Ship with Actuator Metrics Off by Default

### ISSUE THREAD

**Issue by beckje01** [grails/grails-core#10002]
Currently path variables are not taken into account when collecting endpoint metrics this is caused by a bug in actuator https://github.com/spring-projects/spring-boot/issues/5875 Once that is fixed Grails could add a request attribute of `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` if it isn't already.

Until actuator if fixed I propose we start configuring metrics in actuator off by default.

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/faee52a77163b5cd22be6645bc19704fa379edf7

**Comment by beckje01** [comment]
Nice thanks!
