### ISSUE TITLE
Reactor Promise fails silently when using get method with no timeout specified

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-core#10003]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use a long running task
2. Call .get() with no timeout
3. When task times out there is no exception thrown and the value is returned as null
4. Task still continues

### Expected Behaviour

When calling .get() with no timeout specified the method should probably do at least one of the following:

1. throw a TimeoutException when it times out, even when using the default value
2. Log that a timeout occurred to add some clarity as to the null return value
3. Add docs on the grails ReactorPromise to clarify the behavior and add to the grails docs to avoid confusion on behavior of silent fail and the the default timeout of 30000 ms.

The java docs from the underlying Promise do state that a null is returned if not completed, so the original intent may be to null out the value:

``` java
/**
* Returns the value that completed this promise. Returns {@code null} if the promise has not been completed. If the
* promise is completed with an error a RuntimeException that wraps the error is thrown.
*
* @return the value that completed the promise, or {@code null} if it has not been completed
* @throws RuntimeException if the promise was completed with an error
*/
```

The code in grails reactor promise currently looks like the following:

``` groovy
   @Override
    T get() throws Throwable {
        internalPromise.await()
    }

    @Override
    T get(long timeout, TimeUnit units) throws Throwable {
        T res = (T)internalPromise.await(timeout, units)
        if(!internalPromise.success) {
            throw new TimeoutException()
        }
        else {
            return res
        }
    }
```

### Actual Behaviour

The .get() method does not timeout.

### Environment Information

- **Operating System**: Mac OSX
- **Grails Version:** 3.1.8
- **JDK Version:** 1.8u72

### Example Application

https://github.com/ctoestreich/grails-reactor-issue

**Comment by ctoestreich** [comment]
Before submitting a PR I will await feedback from grails core team on what direction they want to take on this action.

**Comment by graemerocher** [comment]
From the Reactor javadoc: https://projectreactor.io/old/api/reactor/rx/Promise.html#await--

"the value of this Promise or null if the timeout is reached and the Promise has not completed"

As far as I can see it is behaving as designed.
