### ISSUE TITLE
Backport getRootEntityFix

### ISSUE THREAD

**Issue by oshwardo** [grails/grails-core#10014]
The issue reported in #9429 was fixed in the 3.1.x branch, and I need it for 3.0.x.
The prime reason is because of the move away from hibernate classes in java (which is not possible for us to ever do because of a shared model layer).

The same fix still applies.

**Comment by graemerocher** [comment]
There may not be another release in the 3.0.x line, so there are no guarantees.

**Comment by oshwardo** [comment]
Understood, but will the 3.0.x line have an End of Life announced if there will be no more releases?

**Comment by graemerocher** [comment]
It is not considered End of Life yet.. just considered stable. There may be another 3.0.x, there may not be.. depends if anything super critical comes up. In the meantime I have assigned this to 3.0.18 so it is not forgotten if there is one.

**Comment by jameskleeh** [comment]
Related commit: https://github.com/grails/grails-data-mapping/commit/4c0aa86646c7ed54401ab89f1999aa5b7766e52e

**Comment by graemerocher** [comment]
Please upgrade
