### ISSUE TITLE
grails 3.1.9 default .gitignore should include classes directory

### ISSUE THREAD

**Issue by wmacgyver** [grails/grails-core#10019]
using grails 3.1.9
grails create-app now produces a default .gitignore

but it doesn't include classes. 

I would think the default behavior is to not commit classes directory

**Comment by burtbeckwith** [comment]
Ideally whatever is creating the classes directory in the root of the project should create it (with a different name) in the build directory.

**Comment by jeffbrown** [comment]
What is creating the `classes/` directory?

**Comment by wmacgyver** [comment]
I saw that you already added it to gitignore. but the answer to your question is

I think it's to run the war

the only thing in it are

classes/artifacts/<app-name>/exploded/<app-name>-0.1.war/
