### ISSUE TITLE
Profiles: repositories and credentials

### ISSUE THREAD

**Issue by sebDK** [grails/grails-core#10013]
Hi,

I host a couple of plugins and profiles on our internal repository(artifactory) protected by credendials (username / password).
There are 2 different situations where credentials make trouble.

1. Add a repository in a profile
Here what should be written in profile.yml
```
repositories:
    - "https://myrepo.org/artifactory/plugins-release-local/"
```
But it is not possible to add any credentials. 

2.To use a profile hosted on my internal repository(artifactory) protected by credendials, it is suggested to add in `USER_HOME/grails/.settings.groovy`:

```
grails {
  profiles {
    web-sso {
      groupId = "org.grails.profiles"
      version = "1.0.0"
    }
    repositories {
       artifactory{
			url="http://myrepo.org/artifactory/plugins-release-local/"
		}
    }
  }
}

```
But again by having a look inside the [source code](https://github.com/grails/grails-core/blob/04948057fbc36e68bff5c3f8888fcefd306bf339/grails-shell/src/main/groovy/org/grails/cli/GrailsCli.groovy#L319), it looks like not possible to add credentials.

Any plan to add credentials support?

### Environment Information

- **Operating System**: Windows 7 64 bits
- **Grails Version:** grails-3.2.0.M1
- **JDK Version:** jdk1.8.0_92

Thanks for your help.

Sébastien

**Comment by Schlogen** [comment]
@sebDK You would just pass a username and password? Or are you using a different authentication type?

**Comment by sebDK** [comment]
Hi,
Yes a username and a password would be great.
It was I used in my `build.gradle`:
```
 maven {
        credentials {
            username 'u'
            password 'p'
        }
        url "http://myserver:8081/artifactory/libs-release-local/"
    }
``´
Thanks for your help.

S.
