### ISSUE TITLE
[3.1.8] Command "grails create-plugin myplugin --profile=plugin" results in "Error No valid plugin profile found for name [plugin]"

### ISSUE THREAD

**Issue by Tim-Jordison** [grails/grails-core#10015]
The command "grails create-plugin myPlugin --profile=plugin" results in "Error No valid plugin profile found for name [plugin]".

Is profile=plugin no longer supported?

**Comment by Schlogen** [comment]
Duplicate of https://github.com/grails/grails-core/issues/9988
