### ISSUE TITLE
Grails CLI generate-controller throws "Domain class not found" on multi-project

### ISSUE THREAD

**Issue by a200612** [grails/grails-core#10016]
### Steps to Reproduce
1. mkdir mymultiproject
2. cd mymultiproject
3. grails create-app myapp
4. grails create-plugin myplugin
5. echo "include 'myapp', 'myplugin'" >>  settings.gradle
6. cd myplugin
7. grails create-domain-class com.example.Person
8. cd ../myapp
9. grails generate-controller com.example.Person
### Expected Behaviour

A controller should be generated in the myapp project using the domain class from myplugin.
### Actual Behaviour

| Error Domain class not found for name com.example.Person
### Environment Information
- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.1.7
- **JDK Version:** OpenJDK 1.8.0_91

**Comment by sdelamo** [comment]
Before Step 9.  you need to add the dependency between `myapp` and `myplugin`. 

example repository: 

https://github.com/grails-core-issues-forks/github-issue-10016
