### ISSUE TITLE
Cannot set readonly property: properties

### ISSUE THREAD

**Issue by martyychang** [grails/grails-core#10027]
My team relies on the support in Grails for live code editing and testing with `grails run-app`. However, trying to use the `obj.properties = params` syntax [shown intermittently in the Grails docs](http://docs.grails.org/2.5.4/guide/theWebLayer.html#commandObjects) causes a strange error, "Cannot set readonly property: properties". This error does not appear when the project is first built, but only on subsequent builds or live code edits.

Yes, `grails clean` is a workaround. But `grails clean` coupled with a full re-compilation takes a significant amount of time and significantly reduces our productivity.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Grails 2.5.4 project.
Create a `SearchIndexCommand` class in src/groovy, with a `String comments` property
2. `grails create-controller Search`
3. Modify `SearchController.index()` to take a `SearchIndexCommand cmd` parameter
4. Inside the `index(SearchIndexCommand)` method, set `cmd.properties = params`, then print something witty followed by `render status: 501`.
5. `grails run-app`
6. Open Terminal and use `curl` to send a request to the /search/index endpoint. Verify that an HTTP 501 response is returned. Check the IDE console and verify that something witty was printed.
7. Replace the witty message in `index(SearchIndexCommand)` with a naive message.
8. Wait for Grails to detect and compile the change.
9. Repeat the same `curl` command in Terminal. Now you will get the "Cannot set readonly property: properties" error.
10. After `grails clean`, you can reproduce the issue by starting again from step 5.

Sample curl command.

```bash
curl -v -XGET \
    "http://localhost:8080/com.example.grails/search/index?comments=foo"
```

### Expected Behaviour

No errors should be generated, and the naive message should be printed in the IDE console.

### Actual Behaviour

The operation fails and the IDE prints a stack trace like the following.

```txt
| Error 2016-07-05 04:06:17,058 [http-bio-8090-exec-4] ERROR errors.GrailsExceptionResolver  - ReadOnlyPropertyException occurred when processing request: [GET] /com.example.grails/search/index
Cannot set readonly property: properties for class: com.example.grails.SearchIndexCommand. Stacktrace follows:
Message: Cannot set readonly property: properties for class: com.example.grails.SearchIndexCommand
```

### Environment Information

- **Operating System**: Mac OS X El Capitan
- **Grails Version:** 2.5.4
- **JDK Version:** 1.8.0_77
- **Container Version (If Applicable):** n/a

### Example Application

https://github.com/martyychang/grails-issue-10027

**Comment by jeffbrown** [comment]
I don't think this is a bug.  This is standard Groovy behavior.

The `.properties` property is made writeable for domain classes in particular, but not for objects in general.

**Comment by jeffbrown** [comment]
```
demo $ cat Test.groovy 
class Test {
    static void main(args) {
        def t = new Test()
        t.properties = [:]
    }
}
demo $ groovy Test
Caught: groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: properties for class: Test
groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: properties for class: Test
	at Test.setProperty(Test.groovy)
	at Test.main(Test.groovy:4)
demo $ 
```

**Comment by injecteer** [comment]
I'm facing this error, if I have a domain @Entity class in an external project and use scaffolded controller

**Comment by graemerocher** [comment]
No in that case you should use `bindData`

**Comment by injecteer** [comment]
Ah, I heard already, that scaffolded controllers are flawed. nvm
