### ISSUE TITLE
Grails 3 - Data Binding Error During Setting of Inherited Bi-Directional OneToMany Association 

### ISSUE THREAD

**Issue by MauiMana** [grails/grails-core#10028]
I apologize for not necessarily providing ALL of the artifacts requested but (Grails Support) please read through my brief bug report and perhaps just verify that the Grails logic at the line I specify is actually coded as intended.

DESCRIPTION:
When setting values in an inherited **'bi-directional'** oneToMany association (FWIW association is defined 2 levels up the inheritance chain) I get an incompatible type error where a java.lang.String is given instead of the desired java.util.Set ('Set' being the internal data type for a oneToMany property). In my debugger I've tracked this issue down to the code at line # 580 of GrailsWebDataBinder.groovy which reads:

propertyValue[otherSide.name] = obj

If the call originated as a RESTful request then 'propertyValue IS a resolved domain object. **However**, if the call originated as an HTTP request then 'propertyValue' is a String representation of the **ID** of the domain object (i.e., not resolved into a domain object yet) currently being added to the association, thus causing the exception. If I follow the logic correctly then I believe the intention is to set the object at the other end of the association we're forming, back to the main object (the object where the oneToMany association property is declared). This would lead me to believe that the 'ID' value mentioned above should have first be resolved into the domain object being added...

- **Operating System**: OS X (10.11.5)
- **Grails Version:** 3.1.5
- **JDK Version:** 1.8.0._77
- **Container Version (If Applicable):** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by Schlogen** [comment]
@MauiMana Please upload an example project that demonstrates the issue with steps to reproduce
