### ISSUE TITLE
Messages located in external libraries are not resolved in development mode

### ISSUE THREAD

**Issue by gregopet** [grails/grails-core#10020]
Grails' i18n system handles development and production enviroments differently to support reloading. Thus i18n messages from dependency JARs do not get resolved in development mode.

Steps to reproduce:

- Create a JAR file containing a resource bundle, include it in project as a dependency (not a plugin)
- Create a GSP containing a message from that JAR file's resource bundle
- Run the app in development mode: the message will not get resolved and the code will be displayed
- Run the app in production mode: the message will get resolved correctly

**Comment by graemerocher** [comment]
FWIW it isn't to support reloading, it is to optimise startup time, since scanning the whole classpath is expensive

**Comment by gregopet** [comment]
We managed to get around the problem by putting this into a Bootstrap class:

    def messageSource

...

	if (Environment.isDevelopmentMode()) {
		Field f = ReloadableResourceBundleMessageSource.getDeclaredField("basenames")
		f.setAccessible(true)
		String[] basenames = f.get(messageSource)
		f.set(messageSource, (basenames + ["ourBundleName"]) as String[])
	}

..the above code would be a bit cleaner if `ReloadableResourceBundleMessageSource` didn't keep everything private, explaining why users would have to do that, though... One solution would probably be to wrap our library as a Grails plugin, right?

Anyway, if a proper fix causes longer startup times, I'm pretty sure I don't want it fixed :)
