### ISSUE TITLE
Bean couldn't be autowired using grails optimization

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#10021]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Description
Before I describe the issue, I will describe the relation of domains. There is a `Customer` domain with a one-to-many relation to `Address`. The `Customer` is an abstract class with two derivations `PrivateCustomer` and `BusinessCustomer`.

Everytime grails is fetching an entity of the many side (e.g. with `Address.findById()` or databinding like in the example) there is the following error in the log:

    ERROR org.grails.spring.beans.factory.OptimizedAutowireCapableBeanFactory - Bean couldn't be autowired using grails optimization: org.springframework.beans.BeanInstantiationException: Failed to instantiate [at.byte_code.businessSuite.customer.Customer]: Is it an abstract class?; nested exception is java.lang.InstantiationException
    ERROR org.grails.spring.beans.factory.OptimizedAutowireCapableBeanFactory - Retrying using spring autowire

The strange thing is that there is no exception thrown and the code is working fine. If I access the customer field, the object gets fetched from the database like it should be.

I think the problem is that the `Customer` object is lazy loaded and at the point of creating the `Address` object a proxy object for custoner is created.

### Steps to Reproduce
1. start demo application
2. open /address/edit/1 or /address/edit/2

### Expected Behaviour
There are no errors in the log

### Actual Behaviour
There are errors in the log as described above

### Environment Information
- **Operating System**: Mac OS X 10.11.5
- **Grails Version:** 3.1.9 (and also tested with 3.1.7)
- **JDK Version:** 1.8.0_72

### Example Application
https://github.com/andreasschiestl/grailsDomainInheritanceIssue

**Comment by andreasschiestl** [comment]
Any feedback? Is this a bug? is my code wrong? why is it working and produces ERROR logs?

**Comment by graemerocher** [comment]
probably ERROR log is a bit high of a log level and this could be regarded as a bug. Generally I would disable auto wiring in domain classes unless you need it as it is a performance bottleneck in many Grails applications.

You can disable it in your domain classes using 

```groovy
static mapping = {
    autowire false
}
```

**Comment by andreasschiestl** [comment]
Thank you for the response.

I have tried to add this to Address, Customer, PrivateCustomer and BusinessCustomer but the error message still appears.

Where is this feature documentated?

**Comment by immutability** [comment]
Is there any update on this? @andreasschiestl did you find a satisfying solution?

I'm migrating a Grails 2.5.x app (using Grails 3.1.9 right now) and we aren't using the `@Autowired` annotation anywhere, so it must be the lazy-loading of those inheritance hierarchies based on the abstract classes (we have 2 such trees in the application). Right now the solution that wouldn't affect the behavior in any way seems to be to suppress the logging for the `OptimizedAutowireCapableBeanFactory` logger, to avoid log clutter, but that's probably not ideal.

**Comment by andreasschiestl** [comment]
Unfortunately we have currently no solution but our application is still under development so the error annoy only the developers ;)

As I wrote `autowire false` didn't solve the problem.

How did you supress the logging? Supress the error is maybe not the best solution but I can not see any wrong behaivor of the application.

**Comment by immutability** [comment]
Thanks for getting back. This is the line I added to our logback configuration today to suppress all logging of OptimizedAutowireCapableBeanFactory (it seems to be working so far): `logger('org.grails.spring.beans.factory.OptimizedAutowireCapableBeanFactory', OFF)`

We're using the root logger set to ERROR and a set of fine-tuning loggers set to DEBUG/INFO as needed for individual packages.

**Comment by andreasschiestl** [comment]
@graemerocher It seems the error message does not appear with Grails 3.2.1. What was the solution for this issue?
