### ISSUE TITLE
Profile angular: main page does not work if project name is written with snake case 

### ISSUE THREAD

**Issue by sebDK** [grails/grails-core#10033]
If I create the following project `my_todo` by doing:
`grails create-app --profile angular -features hibernate,json-views my_todo`
and running:
`grails run-app`

When I browse to http://localhost:8080/, I get the following error:
`angular.js?compile=false:68 Uncaught Error: [$injector:nomod] Module 'myTodo.index' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=myTodo.index(anonymous function) @ angular.js?compile=false:68(anonymous function) @ angular.js?compile=false:2075ensure @ angular.js?compile=false:1999(anonymous function) @ index.js?compile=false:1
angular.js?compile=false:11881 GET http://localhost:8080/my_todo/index/index.html 404 (Not Found)(anonymous function) @ angular.js?compile=false:11881sendReq @ angular.js?compile=false:11642serverRequest @ angular.js?compile=false:11352processQueue @ angular.js?compile=false:16170(anonymous function) @ angular.js?compile=false:16186$digest @ angular.js?compile=false:17257$apply @ angular.js?compile=false:17552bootstrapApply @ angular.js?compile=false:1754doBootstrap @ angular.js?compile=false:1752angularInit @ angular.js?compile=false:1657(anonymous function) @ angular.js?compile=false:31468trigger @ angular.js?compile=false:3198defaultHandlerWrapper @ angular.js?compile=false:3488eventHandler @ angular.js?compile=false:3476
`

If I create an other project `todo` by doing:
`grails create-app --profile angular -features hibernate,json-views todo`
and running:
`grails run-app`

Everything is fine.

The problem is coming from how `/assets/my_todo/index/templates/index.js?compile=false` is built.
It points to `angular.module('myTodo.index')` that does not exists. I guess it should be `my_todo.index`

- **Operating System**: Windows 7 64 bits
- **Grails Version:** grails-3.2.0.M1
- **JDK Version:** jdk1.8.0_92

**Comment by Schlogen** [comment]
The issue is with the template asset pipeline plugin. Please create an issue here https://github.com/craigburke/angular-template-asset-pipeline
