### ISSUE TITLE
URL mapping is ignored due to controller name

### ISSUE THREAD

**Issue by shiranr** [grails/grails-core#10038]
Hi,

It seems in grails 3.0.17, when URL mapping is defined for example:
"/$username"(controller: 'user', action: 'index')
and we have a controller named BlaController, if we try to access "http://localhost:8080/bla", the URL mapping will be ignored and we will be redirected to controller: 'bla' with actionName null.

You can see this issue in project:
https://github.com/shiranr/bug2

run the application and insert:
1. http://localhost:8080/graeme - In the console, you will be able to see we got to controller user with action index and params: username=graeme
2. http://localhost:8080/bla - In the console, you will be able to see we got to controller bla with action name null.

Thanks,
Shiran

**Comment by gubespam** [comment]
Is this really a bug? A URL like "/bla" matches both URL mappings you have defined, so perhaps Grails is just picking the first matching one listed in the URL mappings, which is the `"/$controller/$action?/$id?(.$format)?"` one.

**Comment by Schlogen** [comment]
@shiranr I think this is working as intended. Since you have URL mappings for controllers and the `bla` controller exists, it should take precedence. You can either remove the default url mappings or do something like this:

```
"/$controller/$action?/$id?(.$format)?"{
   constraints {
        controller(notEqual: 'bla')
    }
}
```
