### ISSUE TITLE
RestfulController doesn't bind object after calling request.JSON

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-core#10035]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Start sample application

Works
``` bash
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: c48c2524-a7a0-c098-2b78-2225e0d9ab7a" -d '{
    "name": "person name"
}' "http://localhost:8080/persons?foo=foo"
```

Does Not Work
``` bash
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 67cfa64e-5b9e-8bf7-3a5c-3e8a1b104a31" -d '{
    "name": "place name"
}' "http://localhost:8080/places?foo=foo"
```

### Expected Behaviour

Two controllers that extend the RestfulController and override the save method.

By actually calling request.JSON.foo in the controller action, it stops the subsequent binding to the request.

Works
``` bash
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: c48c2524-a7a0-c098-2b78-2225e0d9ab7a" -d '{
    "name": "person name",
    "foo": "foo"
}' "http://localhost:8080/persons"
```

Does Not Work
``` bash
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 67cfa64e-5b9e-8bf7-3a5c-3e8a1b104a31" -d '{
    "name": "place name",
    "foo": "foo"
}' "http://localhost:8080/places"
```

The addition of this line `println 'FOO=' + request.JSON.foo` causes it to break

```
 @Transactional
    def save() {
        if(handleReadOnly()) {
            return
        }

        println 'FOO=' + request.JSON.foo

        def instance = createResource()

        instance.validate()
        if (instance.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond instance.errors, view:'create' // STATUS CODE 422
            return
        }

        saveResource instance

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: "${resourceName}.label".toString(), default: resourceClassName), instance.id])
                redirect instance
            }
            '*' {
                response.addHeader(HttpHeaders.LOCATION,
                        grailsLinkGenerator.link( resource: this.controllerName, action: 'show',id: instance.id, absolute: true,
                                namespace: hasProperty('namespace') ? this.namespace : null ))
                respond instance, [status: CREATED, view:'show']
            }
        }
    }
```

- **Operating System**: Mac OSX 
- **Grails Version:** 3.1.x
- **JDK Version:** 1.8.x

### Example Application

https://github.com/ctoestreich/rest-controller-issue

**Comment by ctoestreich** [comment]
The same is true if you use an actual property on the object like `request.JSON.name`

**Comment by jeffbrown** [comment]
> By actually calling request.JSON.foo in the controller action, it stops the subsequent binding to the request.

It is arguable, but I don't think this is a bug.  `RestfulController` is using the `request` as the binding source.  When you do that, if the request has a body, the body is read and used as the binding source.  If the request does not have a body, then the request parameters are used as the binding source.  When you refer to `request.JSON.foo`, that causes the body to be consumed so later if the system attempts to read the body (like when data binding happens), the body is gone and cannot be read again.

**Comment by ctoestreich** [comment]
#arguable I think the ability to override this save method and so something based on the json passed in should stop the ability of the createResource() to actually create the resource.  If the body has been consumed, there is no way to check that this has happened and interrogate if request.getJSON() consumed it and them hydrate object from the json directly?  Seems like a very odd side-effect.  How would one be expected to interrogate the data and still use the restfulcontroller?

**Comment by ctoestreich** [comment]
Is the request body like ice cream cake?  Once you eat it, it is gone?

**Comment by jeffbrown** [comment]
> How would one be expected to interrogate the data and still use the restful controller?

The same way you would in any other controller.  If you have something like this:

```
class SomeController {
    def index() {
        println request.JSON

        def p = new Person()
        bindData p, request
    }
}
```

Even if the request has a JSON body, the body will not be used during that call to `bindData` because the body has already been consumed.

> Is the request body like ice cream cake? Once you eat it, it is gone?

Yes.

**Comment by ctoestreich** [comment]
My work around is simple, but involves me creating my own save method that just does a manual JSON binding.  For simple things, no issue.  For complex things, PITA.

**Comment by ctoestreich** [comment]
Ironically this works fine in this scenario:

```
  def save() {
        if(handleReadOnly()) {
            return
        }

        println 'NAME=' + request.JSON.name
        println new Place(request.JSON)
        ....
}

```

Where the place is constructed from the JSON directly.

**Comment by jeffbrown** [comment]
There are some relevant notes at http://docs.grails.org/3.1.9/guide/theWebLayer.html#commandObjects including the following:

> Note that the body of the request is being parsed to make that work. Any attempt to read the body of the request after that will fail since the corresponding input stream will be empty. The controller action can either use a command object or it can parse the body of the request on its own (either directly, or by referring to something like request.JSON), but cannot do both.

Note that the issue reported here isn't using command objects, but the challenge is really the same.

**Comment by jeffbrown** [comment]
I think the example you cited above works because the JSON is being cached.  Some of the relevant code is at https://github.com/grails/grails-core/blob/06221a86d3f49ae51b00e3c96ae3846f337cf784/grails-plugin-converters/src/main/groovy/grails/converters/JSON.java#L284.

We might be able to improve the default data binding stuff around this so that reading the body doesn't prevent data binding from the body working from that point forward.  There was some talk about that and we decided against it because of potential performance issues, but it has been so long ago that I don't recall the details.  I think we could at least consider adding it as an option that is off by default.

**Comment by ctoestreich** [comment]
Fair enough.

**Comment by pain400** [comment]
Can I reset input stream after read request.JSON
