### ISSUE TITLE
Taglibs do not work with namespaced controllers

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#10031]
Using a taglib in a view rendered from a namespaced controller will fail.

### Steps to Reproduce

1. Create a new project
2. Create a namespaced controller and a taglib
3. Create a view rendered by that controller and using your new taglib

### Expected Behaviour

Page should render without any errors.

### Actual Behaviour

Exception:
```
Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/administration/administration/index.gsp:14] [views/administration/administration/index.gsp:14] Tag [isAdministrator] does not exist. No tag library found for namespace: permission
```

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.1.9
- **JDK Version:** openjdk version "1.8.0_91"

### Example Application

- https://github.com/olavgg/taglib_bug

**Comment by jeffbrown** [comment]
The code at https://github.com/olavgg/taglib_bug/blob/190fb0fa6e4d2ac418cde652dae3568d1d20a76d/grails-app/views/administration/administration/index.gsp#L15 is invoking `<permission:isAdministrator>` which is commented out at https://github.com/olavgg/taglib_bug/blob/190fb0fa6e4d2ac418cde652dae3568d1d20a76d/grails-app/taglib/taglib_bug/PermissionTagLib.groovy#L26.  If I add an `isAdministrator` tag to `PermissionTagLib`, it appears to work as expected.

**Comment by olavgg** [comment]
Sorry, my mistake for commenting that out. 

I tested again. It seems like I get an error if I declare the closure as def isAdministrator = { attrs, TagBodyClosure body ->

It works fine with def isAdministrator = { attrs, body ->

The reason for this is maybe because body.class is null ?

**Comment by jeffbrown** [comment]
A separate problem you have in your code is that you are statically typing the second argument to your custom tags to be a `TagBodyClosure` which will be a problem with the runtime type of the argument is `TagOutput.ConstantClosure` (see https://github.com/grails/grails-core/blob/06221a86d3f49ae51b00e3c96ae3846f337cf784/grails-taglib/src/main/groovy/org/grails/taglib/TagOutput.java#L149) which does not extend `TagBodyClosure`.

**Comment by olavgg** [comment]
Thanks Jeff! That fixed it :-)
