### ISSUE TITLE
Include a generic run-command to run any ApplicationCommand that might not be in the gradle classpath

### ISSUE THREAD

**Issue by yvesf** [grails/grails-core#10032]
Hello,
I propose to include a Application command in grails that is able to start other Application commands.

Currently you need to put the project that contains your command in the gradle buildscript classpath so that gradle can detect the command and create a gradle-task to start it.

In some circumstances it could be helpful to have a ApplicationCommand in grails-core, this way it's recognized by gradle. From there it can run other commands that are not known to gradle or even plain scripts as it was possible with grails 2.x.

Such a situation could be if you want to define command directly in your main-project.

The command could look like:

```groovy
@Commons
class RunCommandCommand implements ApplicationCommand {
  @Override
  boolean handle(ExecutionContext executionContext) {
    def args = GradlecommandsGrailsPlugin.getArguments(executionContext)
    assert args.size() > 0: 'Need at least a command name'

    final command = ApplicationContextCommandRegistry.findCommand(args.first())
    assert command: "Failed to find command with name ${args.first()}. Available commands are: ${availableCommands}"

    executionContext.commandLine.remainingArgs.clear()
    executionContext.commandLine.remainingArgs.addAll(Arrays.asList(args).drop(1))
    command.setApplicationContext(applicationContext)

    try {
      return command.handle(executionContext)
    } catch (Exception e) {
      e.printStackTrace()
      throw e
    }
  }

  private static String getAvailableCommands() {
    return ApplicationContextCommandRegistry.findCommands().collect { it.name }.join(', ')
  }
}
```

From gradle you invoke it like: `./gradlew run-command -Dgrails.command.args="actual-command arg1 arg2.."`

If I don't get any negative feedback here then I will open a pull-request for it.
Regards, yves

**Comment by graemerocher** [comment]
Another one you can maybe look at for 3.2 @Schlogen

**Comment by yvesf** [comment]
I believe that I've found something that could work, see https://github.com/yvesf/grails-core/commit/e9317b50562e0eee3c93c96ae31f8ab99a245e3b

- Create a new command in grails-console that delegates to other commands known at runtime
- Since grails-console is not known to the gradle-plugin, statically register this command in GrailsGradlePlugin

Please let me know what you think of this approach.

**Comment by Schlogen** [comment]
@yvesf I am working on this feature for 3.2. Thank you for offering to contribute, however I'm pretty far along so no PR will be necessary. Thanks!

**Comment by alex-shamshurin** [comment]
+1

**Comment by yvesf** [comment]
@jameskleeh Could you please add some kind reference to your change, so that it's more visible how you implemented it (and then how we can use it). Thanks!

**Comment by jameskleeh** [comment]
Done by https://github.com/grails/grails-core/commit/8cfdfb1dc77015b0b87ddd7dc8573763dcee7ee1
