### ISSUE TITLE
Following symbolic link in Grails 3

### ISSUE THREAD

**Issue by sagrawal14** [grails/grails-core#10045]
### Steps to Reproduce

1. Clone [this](https://github.com/sagrawal14/symbolic) repository `git clone git@github.com:sagrawal14/symbolic.git && cd symbolic` 
2. Create a symbolik link `ln -s $PWD/external/app2.js $PWD/src/main/webapp/js/.`
3. Use Grails 3.1.8 `sdk use grails 3.1.8`
4. `grails run-app`
5. Browse to `http://localhost:8080/static/index.html`

### Expected Behavior

When you open the above URL, currently, you will see the following behavior:

![image](https://cloud.githubusercontent.com/assets/1804514/16865575/6d48326c-4a83-11e6-9ea5-c39a860d8f15.png)

The `app2.js` file is not being loaded since it is a symbolic link but it should be loaded i.e. Grails should follow the symbolic link.

### Actual Behavior

The `app2.js` file in `src/main/webapp/app2.js` is a symbolic link of file located in `external/app2.js` and is included in `index.html` page. The Grails 3 unable to load that resource and results in 404. This behavior works in Grails 2 by adding following lines in `scripts/_Events.groovy`:

```groovy
eventConfigureTomcat = { tomcat ->
    def ctx = tomcat.host.findChild("")
    ctx.allowLinking = true     // Follow soft links
}
```

### Environment Information

- **Operating System**: OS X El Capitan (10.11.5)
- **Grails Version:** 3.1.8
- **JDK Version:** JDK 1.8.0_91-b14

### Example Application

- https://github.com/sagrawal14/symbolic

Question posted on [StackOverflow](http://stackoverflow.com/questions/38268498/following-symbolic-link-in-grails-3).

**Comment by graemerocher** [comment]
You will have to enable this feature in Tomcat which requires a TomcatEmbeddedServletContainerFactory 

See https://gist.github.com/SlyDen/9408539#file-application-java-L33 for an example

**Comment by sagrawal14** [comment]
Thanks @graemerocher for replying. After a few hours of understanding of the context and resource, I figured out the solution with the help of example you mentioned and one test case ([EmbeddedContainerWithGrailsSpec](https://github.com/grails/grails-core/blob/639d7039d24031dbc1353f95b6d2c88a100da850/grails-web-boot/src/test/groovy/grails/boot/EmbeddedContainerWithGrailsSpec.groovy)) you had written about how to override `containerFactory` bean.

The following needs to be added to the `./grails-app/init/<package>/Application.groovy`:

```groovy
@Bean
EmbeddedServletContainerFactory containerFactory() {
    TomcatEmbeddedServletContainerFactory containerFactory = new TomcatEmbeddedServletContainerFactory()

    containerFactory.addContextCustomizers(new TomcatContextCustomizer() {
        @Override
        void customize(Context context) {
            StandardRoot root = new StandardRoot(context)
            root.setAllowLinking(true)
            context.setResources(root)
        }
    });

    return containerFactory
}
```

Packages:

```groovy
import org.apache.catalina.Context
import org.apache.catalina.webresources.StandardRoot
import org.springframework.boot.context.embedded.EmbeddedServletContainerFactory
import org.springframework.boot.context.embedded.tomcat.TomcatContextCustomizer
import org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory
import org.springframework.context.annotation.Bean
```

I was customizing connector using `addConnectorCustomizers()` but later I realized, we need to customize the context 😄
