### ISSUE TITLE
Can't save entity with unique constraint and getter for same fields

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10040]
In example, domain Test has unique username with getter. Withoud getter or unique everifing works well

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create domain like this
```
package test
class Test {
    String username
    static constraints = {
        username blank: false, unique: true, email: true
    }

    def setUsername(String username) {
        this.username = username
    }
}
```
2. evaluate 
`new Test(username: '1111').save(flush:true)`
3. get error during saving

> Caused by: org.hibernate.QueryException: could not resolve property: username of: test.Test
> 	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:83)
> 	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:77)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.getSubclassPropertyTableNumber(AbstractEntityPersister.java:1995)
> 	at org.hibernate.persister.entity.BasicEntityPropertyMapping.toColumns(BasicEntityPropertyMapping.java:61)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.toColumns(AbstractEntityPersister.java:1970)
> 	at org.hibernate.loader.criteria.CriteriaQueryTranslator.getColumns(CriteriaQueryTranslator.java:518)
> 	at org.hibernate.loader.criteria.CriteriaQueryTranslator.findColumns(CriteriaQueryTranslator.java:534)
> 	at org.hibernate.criterion.SimpleExpression.toSqlString(SimpleExpression.java:83)
> 	at org.hibernate.loader.criteria.CriteriaQueryTranslator.getWhereCondition(CriteriaQueryTranslator.java:417)
> 	at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:123)
> 	at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:92)
> 	at org.hibernate.loader.criteria.CriteriaLoader.<init>(CriteriaLoader.java:97)
> 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1699)
> 	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
> 	at org.grails.orm.hibernate.validation.UniqueConstraint$2.call(UniqueConstraint.java:209)
> 	at org.grails.orm.hibernate.validation.UniqueConstraint$2.call(UniqueConstraint.java:148)
> 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
> 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
> 	at com.sun.proxy.$Proxy83.doInHibernate(Unknown Source)
> 	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:196)
> 	... 60 common frames omitted

### Expected Behaviour

entity should be saved

### Actual Behaviour

fail

### Environment Information

- **Operating System**: TODO
- **Grails Version:** 3.1.9
- **JDK Version:** 7,8
- **Container Version (If Applicable):** TODO

### Example Application

https://github.com/demon101/grails-bug-10040

**Comment by graemerocher** [comment]
As per Groovy rules on setters and getters if you define a setter you also have to define the getter otherwise the property is regarded as readonly

**Comment by purpleraven** [comment]
if you add getter nothing will be changed
in grails 2.4.5 it works
Please, reopen the issue

**Comment by purpleraven** [comment]
> As per Groovy rules on setters and getters if you define a setter you also have to define the getter otherwise the property is regarded as readonly

No, following code executed without errors
```
 class Person {    
   private String name     
   String getName() { return name }     
   
}

def p = new Person()
p.name = "1"

assert p.name == '1'
```

The problem can be fixed be changin 
`def setUsername(String username) {`
to

`def void setUsername(String username) {`

**Comment by graemerocher** [comment]
Either way it isn't a valid setter nor a valid property and a bug in user code that is the problem.

**Comment by purpleraven** [comment]
@graemerocher yes, but your statement about groovy setter/getter not a truth =)

**Comment by graemerocher** [comment]
```groovy
class Test {
    private String username
    void setUsername(String username) {
        this.username = username
    }
}

Test.methods.find { it.name == "getUsername" }
```

The above prints `null`. Setting the property may work but that is because Groovy doesn't implement privacy properly.

**Comment by purpleraven** [comment]
@graemerocher yes, because of private
