### ISSUE TITLE
Can't render template that lives in a plugin

### ISSUE THREAD

**Issue by danleahy** [grails/grails-core#10047]
Duplicate to 9406 that i can't reopen, 9406 was never fixed.

Attempting to render a template that lives in a plugin (inline) results in a 500 error stating that the template cannot be found, doesn't matter if the plugin name is camelCase or has a dash

same if app is called my-app
and plugin is called  my-plugin

Grails: 3.1.9
Java: 1.8.0_66
OS: Win 10 64-bit

To Reproduce:

> grails create-plugin myplugin
> grails create-app myapp
> echo include 'myplugin', 'myapp' > settings.gradle
> echo TemplateBodyHere > myplugin/grails-app/views/_fromplugin.gsp
Edit mypp\build.gradle and add:

dependencies {
  compile project(":myplugin")
  
}
Edit mypp\grails-app\views\index.gsp and add:

<g:render plugin="myplugin" template="fromplugin" />

somewhere you can see it
delete everything else in index.gsp if needs be.

Run the application:

> cd mypp
> grails
grails> run-app
Load the default index page: http://localhost:8080/

Will result in a 500 error:

getting rid of plugin attribute will allow template to find the plugin template, but this is not acceptable as you can have naming collisions.

Error 500: Internal Server Error

URI
/
Class
org.grails.taglib.GrailsTagException
Message
Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/index.gsp:78] Template not found for name [/fromplugin] and path [/_fromplugin.gsp]
Caused by
[views/index.gsp:78] Template not found for name [/fromplugin] and path [/_fromplugin.gsp]
Around line 78 of grails-app\views\index.gsp

75:        </section>76:    </div>77:78:    <g:render plugin="myplugin" template="/fromplugin" />79:80:</body>81:</html>
Trace

    Line | Method
->>   78 | createGroovyPageException    in D:\Projects\chess3\myapp\grails-app\views\index.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by GrailsTagException: [views/index.gsp:78] Template not found for name [/fromplugin] and path [/_fromplugin.gsp]
->>   78 | doCall                       in views/index.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by danleahy** [comment]
[renderbug.zip](https://github.com/grails/grails-core/files/367338/renderbug.zip)

adding zip file of project that demonstrates the issue, 
problem seems to be in the DefaultGroovyPageLocator.java
package org.grails.gsp.io

**Comment by Schlogen** [comment]
@danleahy Your sample project is missing the dependency between the project and plugin. After adding that it worked as I expected. No exception. I'm using the exact same OS, JDK, and Grails version.

![image](https://cloud.githubusercontent.com/assets/1583789/17011631/d1dec94e-4edd-11e6-9818-bd1bae8d135c.png)

**Comment by danleahy** [comment]
Hi, in build.gradle of myapp in the sample zip i referenced the plugin

line 43 build.gradle inside myapp
compile project(":myplugin")

What reference did you add to get it to work for you?

**Comment by Schlogen** [comment]
@danleahy You are right - I missed that it was there. I tested again with the example project with no changes on my end and it works for me.

**Comment by danleahy** [comment]
HI Schlogen, I tested it again this morning and it wasn't working.
I have tried on my work pc with windows 10 and on my home pc also running windows 10, same grails, different jvms, same behaviour, it can't find the template in the plugin.

**Comment by danleahy** [comment]
I installed grails using gvm on windows, i don't know if that is an issue?

**Comment by pereiss** [comment]
I can perfectly reproduce this. Same issue in Grails 3.1.10. Ubuntu 16.04, Java 1.8.0_92.
Same issue when trying to render a view in an action: 
`render(view: '/index', plugin: 'myplugin')`
The error here is a bit more elaborate:
`Could not resolve view with name '/plugins/myplugin-0.1/index' in servlet with name 'grailsDispatcherServlet'`
Is it because of the plugin version that is somehow put into the path?

**Comment by Schlogen** [comment]
@pereiss Upload an example and I'll be happy to try again

**Comment by pereiss** [comment]
Here you are:
[renderbug.zip](https://github.com/grails/grails-core/files/427409/renderbug.zip)
It is danleahy's project with an additional controller.
- `unzip renderbug.zip`
-  `cd renderbug/myapp/`
- `grails run-app`

`http://localhost:8080/` produces `[views/index.gsp:9] Template not found for name [fromplugin] and path [//_fromplugin.gsp]`
`http://localhost:8080/renderbug` produces `Could not resolve view with name '/plugins/myplugin-0.1/index' in servlet with name 'grailsDispatcherServlet'`

**Comment by Schlogen** [comment]
@pereiss Thanks - I was able to reproduce it, however only when executing the application with `grails run-app`. Previously I was using `./gradlew bootRun` and that works.

**Comment by pereiss** [comment]
I found:
if line 9 of `myapp/grails-app/views/index.gsp` is changed from 
`<g:render plugin="myplugin" template="fromplugin" />`
to 
`<g:render plugin="myplugin-0.1" template="fromplugin" />`
the template is rendered as expected.

This does not help, however, for rendering the view:
`render(view: '/index', plugin: 'myplugin-0.1')`
produces no error, but seems not to use the plugin's gsp but the one from the application.

**Comment by Schlogen** [comment]
@graemerocher `-Dgrails.run.active` is causing this
