### ISSUE TITLE
Default sitemesh layout is not applied anymore since 3.1.6

### ISSUE THREAD

**Issue by trettstadtos** [grails/grails-core#10059]
Since version 3.1.6 the default sitemesh layout is not applied anymore.

### Steps to Reproduce

* Create a simple test controller:
``` groovy
// grails-app/controllers/TestController.groovy
class TestController {
    def index () {
         render template: 'myview'
    }
}
```
* Create a simple view in `grails-app/views/test/_myview.gsp`
```
<h3>Test</h3>
```
* Create a layout in `grails-app/views/layouts/mylayout.gsp`
* Set the layout as the default layout in `application.yml`:
```
grails:
    sitemesh:
        default:
            layout: mylayout
```
* `grails run-app` or `gradle bootRun`
* Go to `/test/index` in the browser.

### Expected Behaviour

The layout "mylayout" should be applied to "myview". This was working in version 3.1.5, but stopped working in 3.1.6.

### Actual Behaviour

The view is rendered as is, i.e. without the layout.

### Environment Information

- **Operating System**: Windows 7 Professional SP 1
- **Grails Version:** 3.1.6
- **JDK Version:** 1.7.0_80

### Example Application

- https://github.com/trettstadtos/grails-default-view-not-applied-bug

**Comment by graemerocher** [comment]
Probably due to https://github.com/grails/grails-core/issues/9902

However, I'm not sure that layouts should be applied automatically too templates. If you want a layout use a view. That is what it is for. If we fix this we will have another report complaining layouts are applied to templates.

**Comment by trettstadtos** [comment]
You're right, of course. In our case we cannot use views because we want to render content into Angular UI views and wanted to apply a layout to all our templates. We will use the layout attribute for the render method in each controller as a workaround. Thanks for your help.
