### ISSUE TITLE
importFrom constraints are not respected at schema generation

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#10052]
If you use the `importFrom` feature (http://docs.grails.org/latest/ref/Constraints/Usage.html) to share constraints between domain classes these contraints (like nullable, maxSize, etc.) are not respected for the schema generation.

Maybe the `shared` feature is also affected, I don't use this feature.

### Steps to Reproduce

1. Create a domain with constraints that effect the schema generation
```
class TestB {

    String name

    static constraints = {
        name (nullable: true, maxSize: 150)
    }
}
```

2. Create a domain that shares constraints with `importFrom`
```
class TestA {

    String name

    static constraints = {
        importFrom(TestB)
    }
}
```
3. run `schema-export`

### Expected Behaviour
schema-export generates (maxSize and nullable respected)
```
    create table testa (
        id bigint not null auto_increment,
        version bigint not null,
        name varchar(150),
        primary key (id)
    );
```

### Actual Behaviour
schema-export generates (maxSize and nullable NOT respected)
```
create table testa (
        id bigint not null auto_increment,
        version bigint not null,
        name varchar(255) not null,
        primary key (id)
    );
```

### Environment Information

- **Operating System**: Mac OS X 10.11.5
- **Grails Version:** 3.1.9
- **JDK Version:**  1.8.0_72

**Comment by andreasschiestl** [comment]
Any information about this issue? Manual correcting is very time consuming especially during development when you change many things in the domain classes.

**Comment by andreasschiestl** [comment]
Still an issue with grails 3.2 :( Is there nobody else effected by this issue?

**Comment by andreasschiestl** [comment]
@graemerocher thank you for your effort.

But there is one problem with the code you commited:

In the HibernateMappingBuilder.groovy you added the following code to get the contraints closure from the class:
```
ClassPropertyFetcher cpf = ClassPropertyFetcher.forClass((Class)args[0]);
List<Closure> constraintsToImports = cpf.getStaticPropertyValuesFromInheritanceHierarchy(GormProperties.CONSTRAINTS, Closure)
```

For comparison in the DefaultConstraintEvaluator.groovy (used for validation purposes) this code is used:
```
List<Closure> constraintsClosureList = new ArrayList<>();
for (Object aClassChain : GrailsDomainConfigurationUtil.getSuperClassChain(theClass)) {
    Class<?> clazz = (Class<?>) aClassChain;
    Closure<?> c = (Closure<?>) GrailsClassUtils.getStaticFieldValue(clazz, ConstraintsEvaluator.PROPERTY_NAME);
    if (c == null) {
        c = getConstraintsFromScript(theClass);
    }
    if (c != null) {
        constraintsClosureList.add(c);
    } else {
        LOG.debug("User-defined constraints not found on class [" + clazz + "], applying default constraints");
    }
}
```

The major difference (and for us important because we use this feature) is the abillity that the contraints could be obtained from a script via getConstraintsFromScript. I know the main purpose of this feature is to have Java domain classes, but we use this feature to add contraints to our traits. Here one Exapmle:

DeletableDomainObject.groovy
```
trait DeletableDomainObject {
    Date deletedDate
    Long deletedUser
}
```
DeletableDomainObjectContraints.groovy (in resources folder)
```
constraints = {
    deletedDate (nullable: true)
    deletedUser (nullable: true)
}
```
And used like:
```
class AnyObject implements DeletableDomainObject {
    String name
    static constraints = {
        importFrom DeletableDomainObject
    }
}
```

Sorry that I don't provide that example in the first place, the goal was to keep the example as simple as possible.

**Comment by graemerocher** [comment]
That won't be added back. Specifying constraints in a script was like you say to support Java, and hence is unnecessary. The solution is to move them out of the script.

**Comment by andreasschiestl** [comment]
@graemerocher I'm not asking to add any feature back. Constraint script are actually available and working in 3.2.1, but the feature is useless if the imported constraints aren't evaluated at schema creation.

You wrote that the solution is to move them out of the script, but adding the constraints to the trait itself is not working at all. And having multiple traits to add different properties and features is way better than extending a class since you can only extend one class.

But maybe you can give a hint how to accomplish constraints for traits :)

**Comment by andreasschiestl** [comment]
we managed to get the constraints out of the script and tested our code with the 3.2.2 snapshot version. the constraints now work as expected, but unfortunately the app crashes sometimes at the start. We will wait for the final 3.2.2 release and create an issue if the problem still exists.

**Comment by graemerocher** [comment]
it would be better if you tell us why it crashes, what exception are you seeing?

**Comment by andreasschiestl** [comment]
Unfortunately the app does not crash after I switched again from 3.2.1 to 3.2.2.BUILD-SNAPSHOT. Maybe there was a bug and is now solved with the snapshot or I messed up something.

Looks like all is now working as expected :thumbsup: Thank you for the great work.
