### ISSUE TITLE
Add the ability to override behaviour for deleting a resource in RestfulController

### ISSUE THREAD

**Issue by mrhaki** [grails/grails-core#10054]
Currently the RestfulController has the `saveResource` and `updateResource` methods that can be overridden by subclasses. 
We can also add a `deleteResource` method that is used from the `delete` method, that subclasses can override to define a different implementation for deleting a resource.
I can create a pull request for this if this feature is approved.

**Comment by jeffbrown** [comment]
> I can create a pull request for this if this feature is approved.

I think it is a good idea.

**Comment by kktec** [comment]
I also think it's a good idea. We are not currently using RestfulController
but if we do, we will want to implement a soft delete.

**Comment by mrhaki** [comment]
I created pull request #10055 for this issue

**Comment by graemerocher** [comment]
Thanks for the pull request!
