### ISSUE TITLE
Grails 3.0.15 - Upload file size limit (128000)

### ISSUE THREAD

**Issue by vibhor-webonise** [grails/grails-core#10058]
Hi Team ,
Looked at the repo, and tried to find a solution to have a size defined for file upload using ,
upload:
maxFileSize: 9999999999
maxRequestSize: 9999999999

But as in Grails 3 default size is 128000 (~128KB). It is not allowing us to get over it even after defining a bigger value in the yml file.

Please suggest.
Vibhor Kansal
git id : vibhor-webonise.

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)

They're defined here https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L74

The issue tracker is not for questions.
