### ISSUE TITLE
Method in Trait can't call private method when using withForm

### ISSUE THREAD

**Issue by antondelpiero** [grails/grails-core#10060]
Hi,
I don't know whether this is an open bug or not. I've googled it and try to find anything like this in the issues, but have found nothing.
Like the title said, it seems that when calling private method inside of a withForm block, the private method that supposed to be called is not the right one.

Simple example:
Trait:

    trait TestControllerTrait {
    //some import stuffs

      @Action
      def testMethod() {
          withForm {
             //do something
          }.invalidToken {
            handleError(someObject)
          }
       }

       private handleError(someObject) {
           //do something like write some log
       }
    }

This trait is implemented in RealTestController.
If i remove the withForm block, everything are going just fine and handleError is called just like expected.

### Expected Behaviour

The private method should be called

### Actual Behaviour

No signature of method: com.myController.RealTestController.handleError() is applicable for argument types: ( com.myController.RealTestController, com.myObject.SomeObject) values: ...

It seems like grails trying to call the private method with parameters enriched with the real controller that implementing that traits.

### Environment Information

- **Operating System**: Win 7
- **Grails Version:** 2.5.4
- **JDK Version:** 1.7.0_25 Oracle JDK

**Comment by jeffbrown** [comment]
I don't think this has much to do with Grails or with `withForm` in particular.  I think this is standard Groovy behavior.

```
trait SomeTrait {

    void somePublicMethod() {
        def someClosure = {
            somePrivateMethod()
        }
        someClosure()
    }

    private void somePrivateMethod() {}
}
```

```
class Demo implements SomeTrait {
    static void main(args) {
        new Demo().somePublicMethod()
    }
}
```

```
$ groovy Demo
Caught: groovy.lang.MissingMethodException: No signature of method: Demo.somePrivateMethod() is applicable for argument types: (Demo) values: [Demo@2473d930]
groovy.lang.MissingMethodException: No signature of method: Demo.somePrivateMethod() is applicable for argument types: (Demo) values: [Demo@2473d930]
	at SomeTrait$Trait$Helper$_somePublicMethod_closure1.doCall(SomeTrait.groovy:5)
	at SomeTrait$Trait$Helper$_somePublicMethod_closure1.doCall(SomeTrait.groovy)
	at SomeTrait$Trait$Helper.somePublicMethod(SomeTrait.groovy:7)
	at SomeTrait$Trait$Helper$somePublicMethod.call(Unknown Source)
	at Demo.somePublicMethod(Demo.groovy)
	at SomeTrait$somePublicMethod.call(Unknown Source)
	at Demo.main(Demo.groovy:3)
```

**Comment by antondelpiero** [comment]
Hi Jeff,

Thx for the explanation, but is there any suggestion/ work around to call any method inside closure?

**Comment by jeffbrown** [comment]
https://issues.apache.org/jira/browse/GROOVY-7891

**Comment by graemerocher** [comment]
Fixed required in Groovy, please track that issue
