### ISSUE TITLE
grails Resolving Dependencies stuck forever but gradle bootRun works

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10063]
So, just created a sample app using grails 3.2.0.M2. 
And when i run the grails command ```>> grails ``` its stuck forever, on "Resolving Dependencies" and doesnt even show what dependencies it is downloading

So, i killed it, and run ```gradle bootRun``` - it downloaded all dependencies and application run successfully. So after that all deps should have been dowloaded to local maven cache.

But still when i run any commands using grails console ``` grails or grails compile`` its still stuck forever on "Resolving Dependencies" without telling what deps are being downloaded.

### Environment Information
- **Operating System**: OSX EL Capitan
- **Grails Version:** 3.2.0.M2
- **JDK Version:** 1.7.0_79
- **Gradle** sdkman gradle version 2.10

**Comment by snimavat** [comment]
@graemerocher @jeffbrown any idea what deps is it trying to download (even if all deps are already downloaded when gradle bootRun was done). And why doesnt it show me what deps it is downloading

**Comment by graemerocher** [comment]
The gradle dependencies. Will see if we can improve the messages for 3.2 RC1

**Comment by eddyx** [comment]
i met the same issue, i am new to grails. Don't know what happened there, spent whole night to resolve dependency, but now result. Tried different versions like 2.4.4 and latest version and sts. Please help, thank you.

**Comment by graemerocher** [comment]
Upgrading to Gradle 3.0 improved the output to show the jars being downloaded https://github.com/grails/grails-core/commit/bd378e83b671c2c6b6ac2b597bab57d98ddd8c18
