### ISSUE TITLE
Controller traits with arguments is called with wrong argument inputs

### ISSUE THREAD

**Issue by antondelpiero** [grails/grails-core#10064]
I hope that my title is understandable enough.
The situation is that, i need to make a controller trait. This is just a plain simple controller. If i create a method, lets say saveImage() without any arguments, this method can be called in the implementating controller, but as soon as i need to give this method any parameters, it seems that grails can't find the right method.

### Task List

E.g:
Trait controller that's working:

    trait ImageControllerTrait {
       ...
       
       @Action
       def saveImage() {
           //do something with the image and save it
       }
    }

What i want to do is modify/enrich the saveImage() with arguments.
e.g:
      
     @Action
     def saveImage(ImageCommand command) {
         //do something
      }

This is my stacktrace:
```
No signature of method: static com.ImageControllerTrait$Trait$Helper.saveImage() is applicable for argument types: (com.TestController) values: [com.TestController@5befb851]
Possible solutions: saveImage(com.ImageControllerTrait, com.ImageCommand). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: static com.ImageControllerTrait$Trait$Helper.saveImage() is applicable for argument types: (com.TestController) values: [com.TestController@5befb851]
.....
```

Infos: TestController is the implementing controller. ImageCommand is a command object

### Environment Information

- **Operating System**: Win 7
- **Grails Version:** 2.5.4
- **JDK Version:** 1.7.0_25 Oracle JDK

**Comment by jeffbrown** [comment]
This is the result of the way the AST transformations work.  In a typical controller when you define a method like `def saveImage(ImageCommand command)`, there is a transformation that generates `def saveImage()` and code is put inside of that method which will create the `ImageCommand` instance, subject it to data binding, subject it to dependency injection, validate it and then pass it to the original `saveImage(ImageCommand command)` method.  The framework always invokes the no-arg method.  I haven't debugged it but from your description I can guess that what is happening is that the transformation which does all of that is running early enough that the trait methods aren't there yet, or something like that is happening which causes the trait methods to not have corresponding no-arg methods created.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-core/pull/10126/files
