### ISSUE TITLE
HTTP POST method not recognized by controller

### ISSUE THREAD

**Issue by acrive82** [grails/grails-core#10067]
After create a Grails 3.1.9 app with _rest-api_ profile and using the static method _allowedMethods_ to bind the _POST_  to _save_ action, the request will not mapped to the action. Go directly to _index_.

Debugging the application I found the correct request method (POST), but will never respond the _save_ action.

If I try to call the action directly (following the conventions) _POST http://localhost:8080/mymodel/save_, all work!

### Steps to Reproduce

1. Create application with rest-api profile
2. Generate model and controller
3. Map an action to POST with _allowedMethods_ map
4. Execute a request (POST) 

### Expected Behaviour

Call mapped POST action (default _save_)

### Actual Behaviour

Respond _index_

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.1.9
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
You are almost certainly missing the necessary URL mapping in `UrlMappings.groovy`. Example:

      "/foos"(resources:"foo")

**Comment by acrive82** [comment]
Oops. Thank for your time.
