### ISSUE TITLE
grails 3.1.9 Composition in GORM 

### ISSUE THREAD

**Issue by xiaolianghu** [grails/grails-core#10073]
According to guide:
If you define the Address class in a separate Groovy file in the grails-app/domain directory you will also get an address table. If you don't want this to happen use Groovy's ability to define multiple classes per file and include the Address class below the Person class in the grails-app/domain/Person.groovy file.

But the database is wrong!

![qq 20160728160715](https://cloud.githubusercontent.com/assets/20347953/17205383/692d8e34-54dd-11e6-8e01-79dc48dd22c8.png)
![qq 20160728160603](https://cloud.githubusercontent.com/assets/20347953/17205384/698ce74e-54dd-11e6-9bb1-f14d825a4af7.png)

**Comment by graemerocher** [comment]
Move the class to `src/main/groovy`
