### ISSUE TITLE
update table when recompiling

### ISSUE THREAD

**Issue by zscgrhg** [grails/grails-core#10076]
### Steps to Reproduce

domain class below:

class Nose {
}
class Face {
    Nose nose
}

produce 2 tables,DDL below(its ok):
CREATE TABLE face
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    version BIGINT(20) NOT NULL,
    nose_id BIGINT(20) NOT NULL,
    CONSTRAINT FK_22kbo6e72yu3hftdkvig9k3rm FOREIGN KEY (nose_id) REFERENCES nose (id)
);
CREATE INDEX FK_22kbo6e72yu3hftdkvig9k3rm ON face (nose_id);

CREATE TABLE nose
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    version BIGINT(20) NOT NULL
);

its Expected.

but modify the Nose class:

class Nose {
    static belongsTo = [face:Face]
}

and  recompiling..(This is the key,its recompiling,not reboot)

i got a column 'face_id' in table nose:
the DDL below
CREATE TABLE nose
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    version BIGINT(20) NOT NULL,
    face_id BIGINT(20),  //this is not Expected
    CONSTRAINT FK_jg7dhhdtn4kbn22qltwnesxjl FOREIGN KEY (face_id) REFERENCES face (id)
);
CREATE INDEX FK_jg7dhhdtn4kbn22qltwnesxjl ON nose (face_id);

reboot the whole app, i got the Expected result：
CREATE TABLE nose
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    version BIGINT(20) NOT NULL
);

It occurs only when recompiling

### Environment Information
mysql 5.7
- **Operating System**: win10 
- **Grails Version:** 3.1.9
- **JDK Version:** 1.8.0_102
- **Container Version (If Applicable):** TODO

**Comment by Schlogen** [comment]
For as long as I've been involved with Grails this has never been supported. You must reboot for domain changes to be reflected in the schema.

**Comment by zscgrhg** [comment]
OK,thank u
