### ISSUE TITLE
Grails Central Repo appears to be down

### ISSUE THREAD

**Issue by liftyourgame** [grails/grails-core#10080]
I have installed Grails 3.1.10 on OSX using SDKMAN.

When I run just the grails command at the command prompt I get:

| Error Error occurred running Grails CLI: Could not find artifact org.grails:grails-bom:pom:3.1.10 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

I am not behind a proxy.

When I browse to:
https://repo.grails.org/grails/core

I get just a blank page.

**Comment by ifhayz** [comment]
I got the same issue when trying to deploy from Bamboo. It happens since last night Jakarta time.

**Comment by madiflannery** [comment]
Same issue for me also

**Comment by burtbeckwith** [comment]
It's down for everyone and being worked on; more "votes" and me-too comments aren't going to make anything resolve faster.

**Comment by salmanhasni** [comment]
yes it not working for me either

**Comment by weili0677** [comment]
me too...

**Comment by jprabawa** [comment]
I'm receiving a different error; Is this the same issue? Seems like an SNI issue.

`| Error Resolve error obtaining dependencies: Could not transfer artifact org.grails.plugins:tomcat:zip:7.0.55.2 from/to grailsCentral (https://repo.grails.org/grails/plugins): hostname in certificate didn't match: <repo.grails.org> != <*.jfrog.io> OR <*.jfrog.io> OR <jfrog.io> (Use --stacktrace to see the full trace)`

**Comment by gianlucagenga** [comment]
I'm facing the same issue @jprabawa explained!

**Comment by graemerocher** [comment]
This seems to impact Grails 2.5.x but not 3.x, we are investigating the issue

**Comment by graemerocher** [comment]
If you are still having problems due to the certificate issue please use https://grails.jfrog.io/grails/core/ until they are resolved.

JFrog have moved their servers from Amazon to Google Cloud and the change caused some hickups. Sorry for the inconvenience.

**Comment by salmanhasni** [comment]
having the same issue
hostname in certificate didn't match: <repo.grails.org> != <*.jfrog.io> OR <*.jfrog.io> OR <jfrog.io>

**Comment by salmanhasni** [comment]
@graemerocher Thanks it worked :-)

**Comment by jbaruch** [comment]
Grails 2 clients should work now wit hrepo.grails.org as well.

**Comment by jbaruch** [comment]
Sorry, repo.grails.org

**Comment by jeffbrown** [comment]
@jbaruch Thanks for all of your help!

**Comment by graemerocher** [comment]
Thanks @jbaruch !

**Comment by zdtsw** [comment]
repo.grails.org is down
