### ISSUE TITLE
g:link tag should automatically detect the namespace of target controller

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10086]
See https://github.com/grails/grails-core/issues/10062 for more details

Given the Example url mappings

```
"/admin/$controller/$action?/$id?(.$format)?"(namespace:"admin")
"/secure/$controller/$action?/$id?(.$format)?"(namespace:"secure")
"/$controller/$action?/$id?(.$format)?"(namespace:"secure")

class SettingsController {
 static namespace = "admin"
}

class UserController {
 static namespace = "secure"
}

//controller without namespace
class SimpleController {

}
```

`<g:link controller="user" action="xx">User</g:link>` The generated link should be /secure/user/xx 
`<g:link controller="settings" action="xx">` should generate /admin/settings/xx
`<g:link controller="simple" action="xx">` should generate /simple/xx

> just like doing forward url mapping, Grails will findout which controller to use based on the name space in url mapping... the same should happen based on reverse url mapping... if controller is in name space, use that name space... if there are two controllers with same name in differnt name space, thn namespace must be provided, if one of the controller is in default namespace, that gets picked up.

**Comment by olavgg** [comment]
I guess this wasn't in the 3.1.11 release? Are there plans to have this for 3.1.12?
Currently the changes introduced in 3.1.10 breaks g:link for our admin pages.

**Comment by jameskleeh** [comment]
@olavgg a bug introduced in 3.1.10 related to this is fixed in 3.1.11. This is issue is to further improve the feature

**Comment by andreasschiestl** [comment]
What is the duplicated issue?

**Comment by snimavat** [comment]
@andreasschiestl @graemerocher -- this is not actually a duplicate issue, this is an ehnacement

**Comment by andreasschiestl** [comment]
@snimavat I'm watching this issue for a while now because I'm also interested in this feature. Maybe you recreate the issue to get the attention of the grails team?

**Comment by snimavat** [comment]
@andreasschiestl i think it will need a PR to be considered...

**Comment by snimavat** [comment]
@jameskleeh do u think this as a valid request ? -- should we have a new issue for this ?

**Comment by jameskleeh** [comment]
I have concerns about the performance implications, however I think it is a valid thing to want

**Comment by snimavat** [comment]
I will add new issue, not sure how much performance hit it will be to lookup controllers to find namespaces... given that we have caching link generator...
