### ISSUE TITLE
NullPointerException when saving a domain object with uniquness constraint

### ISSUE THREAD

**Issue by sjparsons** [grails/grails-core#10084]
I'm encountering a very similar problem to #9887. In my application when adding a uniqueness constraint I encounter a NullPointerException when attempting a `save()`.

Here's an abbreviated version of my domain class.

```
class Hotel {
    Integer id
    Integer userId
    String code
    String name

    static constraints = {
        name blank: false
        code blank: false, unique: 'userId'
    }

}
```

Here's the code that fails. The first time it runs it's fine since it doesn't hit the uniqueness constraint, the second time it throws a NullPointerException. 

        def instance = new Hotel( name: "Sheraton", code: 123)
        instance.validate()
        if (instance.hasErrors()) {
            return instance.errors
        }
        instance.save( flush: true )
        return instance

### Steps to Reproduce

1. Setup a domain class like above with uniqueness constraint
2. Try to add and save an instance that violates the uniqueness constraint

### Expected Behaviour

Return a meaningful validation error

### Actual Behaviour

Encounter a null pointer exception

### Environment Information

- **Operating System**:  Win 7
- **Grails Version:** 3.1.9
- **JDK Version:** 1.8.0u91

**Comment by Schlogen** [comment]
In the example you gave above `userId` is not set and would fail validation due to the field not being allowed to be null. 

With your same domain class I was able to execute the following without an exception. Upload an example project that reproduces the issue

```
def instance = new Hotel( name: "Sheraton", code: 123, userId: 1)
        instance.validate()
        if (instance.hasErrors()) {
            println instance.errors
        }
        instance.save( flush: true )

        instance = new Hotel( name: "Sheraton", code: 123, userId: 1)
        instance.validate()
        if (instance.hasErrors()) {
            println instance.errors
        }
        instance.save( flush: true )
```

**Comment by jameskleeh** [comment]
Closing this due to lack of feedback. Open a new issue with an example project if you are still facing this issue.
