### ISSUE TITLE
Grails 2.5.x and Spring 4.2.x or 4.3.x?

### ISSUE THREAD

**Issue by basejump** [grails/grails-core#10089]
Is upgrading the underlying spring version on the docket any time soon? Is there a reason its at 4.1.x?

**Comment by jeffbrown** [comment]
> Is upgrading the underlying spring version on the docket any time soon?

No.  2.5.x is in maintenance mode.  I do not anticipate that we will upgrade any dependencies back there.

Please ask questions on the mailing list at https://groups.google.com/forum/#!forum/grails-dev-discuss or in our Slack channel at https://grails.slack.com/.

**Comment by jeffbrown** [comment]
Grails 3.0.x is using Spring 4.1.  Grails 3.1.x is using Spring 4.2.  Grails 3.2.x is using Spring 4.3.

**Comment by basejump** [comment]
Thanks
