### ISSUE TITLE
"Content-Type: application/json" header breaks data binding

### ISSUE THREAD

**Issue by martyychang** [grails/grails-core#10095]
The Grails 2.5.x and [3.1.x docs](http://docs.grails.org/3.1.10/guide/webServices.html) both say the following.

> By default the `getObjectToBind()` method returns the `request` object. When the `request` object is used as the binding source, if the request has a body then the body will be parsed and its contents will be used to do the data binding, otherwise the request parameters will be used to do the data binding.

But in practice, Grails make it unnecessarily difficult to build a REST API that is easy for clients to consume. The problem is that the presence of a "Content-Type: application/json" header causes Grails to look for data in the request body, even for GET requests that have no request body.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. `grails create-app com-example-grails3`
2. `grails create-domain-class org.bookstore.Hello` and add a property `String dialect`
2. `grails create-controller com.example.grails3.hello` and extend `RestfulController`
3. Modify the `index()` method to take a `HelloIndexCommand cmd` parameter, and then to simply `respond cmd` in the method.
4. Create the `HelloIndexCommand` class in **src/main/groovy/** with a `long userId` property
5. Add mappings for the nested "/users/$userId/hellos" resource (sample syntax below) in **UrlMappings.groovy**.

```groovy
        "/users"(resources:"user") {
            "/hellos"(resources:"hello")
        }
```

Now at this point we can `grails run-app`. And the following cURL command will succeed with HTTP 200.

```bash
curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 341b082b-72b8-f0d3-763f-0883c9ee9a42" "http://localhost:8080/users/1/hellos"
```

But the following cURL command will fail with HTTP 422, even tough I expect it to succeed since _there is no request body_.

```bash
curl -X GET -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: aa4d76c5-5a0b-79e0-3893-8352273aed9b" "http://localhost:8080/users/1/hellos"
```

### Expected Behaviour

Given the simple setup, both commands above _should_ succeed with HTTP 200.

### Actual Behaviour

The latter command that has the Content-Type header but _no_ request body failed with HTTP 422.

### Environment Information

- **Operating System**: Mac OS X El Capitan
- **Grails Version:** 3.1.10
- **JDK Version:** 1.8
- **Container Version (If Applicable):** n/a

### Example Application

- [link to github repository](https://github.com/martyychang/grails-issue-10095) with example that reproduces the issue

**Comment by graemerocher** [comment]
If the request is sending a content type of `application/json` and the body does not contain JSON then that is an invalid request since the content type is in fact not `application/json`. I don't see how this is a Grails issue personally.

**Comment by martyychang** [comment]
Hi @graemerocher I checked the [HTTP/1.1 header specs](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) and found no requirement that there must be content in the request body when the "Content-Type" header is specified. Also, the following quote from the spec highlights that zero-length content (i.e., empty body) is okay.

> Any Content-Length greater than or equal to zero is a valid value.

In terms of facilitating REST API _client_ implementation, it's much easier to build a client to always send a consistent Content-Type header vs. customizing the header for different requests. And if the goal of Grails as a framework is to help developers work faster by focusing on unique business logic, I ask the Grails team to seriously consider this (dare I say "simple"?) change to only serialize the body when the body is _not_ empty (Content-Length > 0).

**Comment by Schlogen** [comment]
@martyychang We will implement a change to check the content length. After that change is applied, the example you have in the issue will still fail because no content length header is provided. The change is: The request body will not be parsed if the content length header is present and equals 0. The size of a request body is not known before it's read, therefore the header is necessary.

**Comment by martyychang** [comment]
Sounds good @Schlogen and thank you guys for the quick updates. Can you confirm my understanding of the new business logic?

* If "Content-Type: application/json" and no Content-Length header, the body will be parsed.
* If "Content-Type: application/json" and Content-Length > 0, the body will be parsed.
* If "Content-Type: application/json" and Content-Length is 0, the body will _not_ be parsed _and_ instead URL route and query parameters _will_ be parsed. This is equivalent to the current behavior when the Content-Type header is absent for a GET request.

**Comment by Schlogen** [comment]
@martyychang That is correct

**Comment by gschueler** [comment]
if it is a `GET` request, why is the content-type/content-length and body being used at all?  I would expect those parts of the request to be ignored, or if it's really necessary a 400 Bad Request indicating the reason it is not valid.

quoting the rfc section 4.3 "if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request."

more rfc ref <https://tools.ietf.org/html/rfc7231#section-4.3.1> "A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request."

I take it to mean it should be ignored for GET.

**Comment by Schlogen** [comment]
@gschueler See http://stackoverflow.com/a/983458/1264846. Valid arguments that request bodies of `GET` requests shouldn't be used for data binding. Thoughts @jeffbrown ?

**Comment by martyychang** [comment]
If the implementation goes down the path of looking at the request method, I'd also ask that the team consider `DELETE` in the same category as `GET` where the request body is ignored.

**Comment by graemerocher** [comment]
Seems reasonable to ignore the body for the HTTP `GET` and `DELETE` request types to me which can be an additional improvement over and above the content length handling

**Comment by Schlogen** [comment]
Thanks for the feedback @martyychang and @gschueler 

https://github.com/grails/grails-core/pull/10111
