### ISSUE TITLE
i18n  Resource Bundles cannot be resolved in binary plugin

### ISSUE THREAD

**Issue by thomasguo** [grails/grails-core#10093]
I created a grails binary plugin and used some resource bundles files in it.  This works well in dev enviroment of this plugin.  But when I package it as a jar file and put it in a normal grails app's lib subdirectory,  These resource files cannot be accessed from any code any more.  In fact I have seen the i18n folder and those messages files in the packaged plugin jar file(in META-INF/grails-app/i18n/**).   Please help to solve this issue.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 2.4.4 or  2.5.5
- **JDK Version:**   JDK7

**Comment by graemerocher** [comment]
For 2.x you will have to use a source plugin, otherwise upgrade to Grails 3.x which will resolve this issue

**Comment by thomasguo** [comment]
Does Grails 3.x support binary plugin?  I did not find anything about that in the users guide of Grails 3.x .

**Comment by jeffbrown** [comment]
> Does Grails 3.x support binary plugin?

Yes.  All Grails 3.x plugins are binary when they are published.
