### ISSUE TITLE
Slim .war is not working when deployed since Grails 3.1.4

### ISSUE THREAD

**Issue by injecteer** [grails/grails-core#10090]
Originally described here http://stackoverflow.com/questions/37659196/building-a-slim-war-in-grails-3-1-7

Using Grails 3.1.9.

The war file is built using `provided` dependencies and 

> bootRepackage.enabled = false

All dist and dependency .jar files are copied into tomcat8/lib folder before deployment.

When the slim war file is deployed into Tomcat8 and I try to access the index or any other page, the error appears:

`javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet' org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1229) org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029) org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:973) org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)`

I downgraded the Grails to 3.1.4, and then it worked like charm.

**Comment by tircnf** [comment]
Probably related

```
grails create-app foo
cd foo
grails package
 java -jar build/libs/foo-0.1.war
```

has the identical problem.

**Comment by injecteer** [comment]
It still doesn't work... 
I changed

`grailsVersion=3.1.11`

and

`bootRepackage.enabled = false`

assembled a .war file, deployed in tomcat, copied the jars from WEB-INF/lib-provided into tomcat/lib, then changed back to 

`bootRepackage.enabled = true`

assembled and deployed the (slim) war file again.

The tomcat and app started fine:

12:25:55.368 [localhost-startStop-1] INFO o.g.w.s.mvc.GrailsDispatcherServlet - FrameworkServlet 'grailsDispatcherServlet': initialization completed in 17 ms
08-Sep-2016 12:25:55.383 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /opt/tomcat/webapps/ROOT.war has finished in 26,399 ms
08-Sep-2016 12:25:55.400 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 26488 ms

but upon visiting the index page I got the exception:

`12:44:48.851 [http-nio-8080-exec-1] ERROR o.s.boot.context.web.ErrorPageFilter - Forwarding to error page from request [/] due to exception [Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet']
javax.servlet.ServletException: Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1229)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:973)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:281)`

Another thing, the static resources are not fetched. the code for the head section doesn't contain any js/css/meta tags:

`<head>
	<title>Show UserAccount</title>
        <meta name="layout" content="main"/>
</head>`

**Comment by graemerocher** [comment]
Not sure, works fine for me. I followed these steps:

1) Create an application

```
$ grails create-app deploy-test
$ cd deploy-test
```
2) Change `build.gradle` to use `provided` for tomcat and `bootRepackage=false`:

```groovy
bootRepackage.enabled = false
...
dependencies {
   ...
    provided "org.springframework.boot:spring-boot-starter-tomcat"
}
```
3) Build a war file and copy JARs to tomcat/lib

```
$ gradle assemble
$ unzip build/libs/deploy-test-0.1.war -d tmp
$ cp -rf tmp/WEB-INF/lib/* ~/oss/tomcat-8.0.24-shared-libs/lib/
```

4) Exclude JARs in `build.gradle:

```groovy
war {
  rootSpec.exclude "**/*.jar"
}
```

5) Rebuild WAR file and copy to Tomcat

```
$ gradle clean assemble
$ cp build/libs/deploy-test-0.1.war ~/oss/tomcat-8.0.24-shared-libs/webapps
```

Once I started Tomcat the index page was successfully rendered and all functioned as expected

**Comment by injecteer** [comment]
I followed your foot-steps and at 1st it worked, I got the index page as expected. 

Then I stripped the some dependencies off - mostly hibernate & h2 & tests - at some point later I want to switch over to mongo:

    dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    provided "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"
    compile "org.grails.plugins:cache"
    compile "org.grails.plugins:scaffolding"		
    //compile 'org.grails.plugins:mongodb:5.0.8'    
    console "org.grails:grails-console"
    profile "org.grails.profiles:web"
    runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.8.2"
    }

Then I assembled, copied the jars from war into tomcat/lib, then activated `rootSpec.exclude "**/*.jar"`, assembled again and copied the war into tomcat/webapps. 

After starting the app and accessing the  /index, the exception is there:

>12:31:45.070 [http-nio-8080-exec-1] ERROR o.s.boot.context.web.ErrorPageFilter - Forwarding to error page from request [/] due to exception [Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet']
javax.servlet.ServletException: Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1229)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029)

What I also noticed, in the war file there was a file called `tomcat-jdbc-8.0.36.jar`, although there's a file `tomcat-jdbc.jar` which comes originally with tomcat (in my case it was `apache-tomcat-8.5.5`). The files are different in size.

**Comment by injecteer** [comment]
as a follow-up: if I repeat the same manipulations with Grails 3.1.4, it's working just fine

**Comment by graemerocher** [comment]
Please provide clear steps to reproduce. The comment:

```"Then I stripped some dependencies off - mostly hibernate & h2 & tests - at some point later I want to switch over to mongo"```

doesn't exactly clarify how to reproduce the issue

**Comment by injecteer** [comment]
I attached my test project
[tst.zip](https://github.com/grails/grails-core/files/466963/tst.zip)

**Comment by graemerocher** [comment]
Sample app works fine for me. I would suggest you make sure that the version of the tomcat being used by Grails and the version you plan to deploy to are the same by enforcing version 8.5.5 for all tomcat dependencies on `build.gradle`.

Most likely reason for the issue is a tomcat dependency conflict.

**Comment by injecteer** [comment]
can you please share your test app?

**Comment by graemerocher** [comment]
My test app is your test app, so I'm not sure what is to share?

**Comment by injecteer** [comment]
then how is it not working by me?

**Comment by injecteer** [comment]
As a workaround I'm doing the following now:

1. unzip the slim .war-file into ~/ROOT/
2. copy the lib folder with all 3.1.11 jars into ~/ROOT/WEB-INF/lib
Note: sym-link didn't work...
3. move the ~/ROOT folder to /opt/tomcat/webapps

This way no classloading issues appear
