### ISSUE TITLE
Incomplete default scaffolding with fields plugin

### ISSUE THREAD

**Issue by manseekingknowledge** [grails/grails-core#10092]
### Steps to Reproduce

1. Create two domain classes where class "A" hasMany of class "B"
2. Run the generate-all command

### Expected Behaviour

1.) The scaffolding generated for every controller action should be usable, but it is not.  If attempting to create a new "A" object the create/save view should have a multi-select field which lists all instances  of "B".  Instead we are shown a link that reads "Add B" which takes us to the create view of the "B" domain class.

2.) The default scaffolding generated for the show view for "A" inserts the following:

`<f:display bean="a" />`

The documentation (which indicates it is on version 1.5 even though the plugin is on version 2.1.2) indicates that "property" is a required attribute of the `<f:display>` tag.  Without the "property" attribute it appears an individual field of an object cannot be overwritten.  Than means anyone who wants to overwrite an individual field in a show view will have to update the scaffolding templates to loop through the properties of the bean using a `<g:each>` tag and also means they have to have their constraints defined:

`
<g:each in="${a.constrainedProperties}">
    <f:display bean="${a}" property="${it.key}"/>
</g:each>`

3.)
<rant>
The way scaffolding worked in Grails 2 was in my opinion far superior to what Grails 3 has given us.  Reading on Stackoverflow it seems many others share this opinion.  Besides the fact that it actually worked correctly by default, it was also much easier to _work with_.  Overrides needed to fields object being created, edited, or saved are often identical.  With the fields plugin this means that I have to maintain 3 "_wrapper.gsp" files for a single field.  If there is a lot of stuff to override this becomes a real bear to manage.  There is a lot of goodness in Grails 3 that I want to take advantage of, but I want/need the default scaffolding to work correctly and be easily modified for admin interfaces.  They fact that they don't/aren't has me seriously considering rolling back to Grails 2.5.5.
</rant>

### Actual Behaviour

See "Expected Behaviour" section.

### Environment Information

- **Operating System**: Linux Mint 17.3 Cinnamon 64-bit
- **Grails Version:** 3.2.0.M2
- **JDK Version:** 1.7.0_101 (OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1))

### Example Application

https://github.com/manseekingknowledge/example

**Comment by jeffbrown** [comment]
I don't think this is an issue for `grails-core`.  This should be discussed as an issue for the `scaffolding` plugin.  The issue tracker for that is at https://github.com/grails3-plugins/scaffolding/issues.
