### ISSUE TITLE
Grails 2.5.1 'Map<String, String>' Domain Mapping Issue

### ISSUE THREAD

**Issue by pvangeel** [grails/grails-core#10103]
I'm encountering a problem that doesn't seem to be reproducable, but does occur from time to time

I have a domain class, with a Map of Strings as attributes

```
class DomainClass {

    Map<String, String> attrs  

}

```

99% of time this works, and I can address the attrbutes by name

domainClassInstance.attr.attrName == 'expectedValue'

However, sometimes (I haven't been able to figure out when), the attrs will just resolve to a Map that has domainClassInstance.id for all 'values'

restarting the application 'solves' this issue (postpones it to a random moment in time)

### Environment Information

- **Operating System**:  Linux
- **Grails Version:** 2.5.1
- **JDK Version:** 1.7.0_85, 1.7.0_95 (openJDK)

Is this a known bug in this version of grails (I haven't been able to locate it)
Any ideas on debugging this would be greatly appreciated

**Comment by pvangeel** [comment]
also happens on 1.7.0_71 (Oracle) occasionally

**Comment by graemerocher** [comment]
Upload an example that reproduces the problem with steps reproduce

**Comment by pvangeel** [comment]
I tried a couple of things to reproduce the issue with no luck so far, so I'm guessing it doesn't occur with a simple domain

This is the output from one of the failing tests, which shows the problem:

`            junit.framework.AssertionFailedError: Condition not satisfied:

sub.token == expectedAttributes.token
|   |     |  |                  |
|   1     |  |                  8989++1601++---
|         |  [amount:100, documentId:5a51b4f5-da14-4014-a41a-7f439410bd1f, authorizationNumber:authn_1, subscriberNumber:subsn_1, cardType:EUROCARD_MASTERCARD, cardExpires:1601, card2LastDigits:44, card6FirstDigits:111122, cardHolderEnrollment3dSecure:Y, txResponseCode:00000, authResult:Y, ipCountryCode:BEL, transactionTimestamp:15:45:02, externalTransactionId:28032015, externalTransactionDate:26032015, token:8989++1601++---, attr1:1, attr2:b]
|         false
|         14 differences (6% similarity)
|         (------)1(--------)
|         (8989++)1(601++---)
com.b2boost.payment.payer.paybox.Subscription@47c7214b`

**Comment by pvangeel** [comment]
Unfortunately all attempts of creating a simple project that reproduces the issue did not appear to be succesful... 
Any pointers on extracting information about the system at runtime (hibernate mapping?) that could help investigating this problem as it occurs? It only appears every couple of reboots or in some automated (functional) tests

**Comment by pvangeel** [comment]
Is it possible to turn on hibernate (sql) logging at runtime? Running it all the time would have an impact on the production application, but if I could enable it through the grails console, that would allow me to retrieve more information.

**Comment by graemerocher** [comment]
yes using the `hibernate.show_sql=true` settings

**Comment by pvangeel** [comment]
I'm aware, but is there a way to enable this on a running system? I'd like to only turn it on when things go all goofy.

**Comment by graemerocher** [comment]
You would have to enable debug logging via logback at runtime for the `org.hibernate.SQL` package. See http://stackoverflow.com/questions/18102898/how-can-i-change-log-level-of-single-logger-in-runtime
