### ISSUE TITLE
Grails 3: gradle  - can install executable WAR to remote repository

### ISSUE THREAD

**Issue by markandirene** [grails/grails-core#10109]
Hello

**build.gradle**

apply plugin: "maven-publish"

ext {
:
    artifactoryBaseUrl = 'http://my.repo.com/nexus/content/repositories'
    artifactorySnapshotRepoUrl = "$artifactoryBaseUrl/my-snapshots/"
    artifactoryReleaseRepoUrl = "$artifactoryBaseUrl/my-releases/"
}

publishing {
    publications {
        mavenWeb(MavenPublication) {
            from components.web
        }
    }

    repositories {
        maven {
            name **'remoteNexus'**
            url project.version.endsWith('-SNAPSHOT') ? artifactorySnapshotRepoUrl : artifactoryReleaseRepoUrl
            credentials {
                username = 'username'
                password = 'password'
            }
        }
    }
}

This almost works but it doesn't publish the executable WAR:

gradlew publishMavenWebPublicationTo**RemoteNexus**Repository

I tried:

publishMavenWebPublicationToRemoteNexusRepository.dependsOn assemble

but the _publishMavenWebPublicationToRemoteNexusRepository_ task is not recognized.

Any ideas?

Thanks

Mark

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
