### ISSUE TITLE
request.JSON doesn't compile with @GrailsCompileStatic annotation

### ISSUE THREAD

**Issue by zeesulehria** [grails/grails-core#10106]
I should be able to annotate controller action methods with @GrailsCompileStatic, however I get following compilation error:

[Static type checking] - No such property: JSON for class: javax.servlet.http.HttpServletRequest

- **Grails Version:** 2.5.3

**Comment by jeffbrown** [comment]
Related to #643

**Comment by Schlogen** [comment]
Confirmed this works as expected in Grails 3
