### ISSUE TITLE
Grails 3: grails install - Task 'install' not found in root project

### ISSUE THREAD

**Issue by markandirene** [grails/grails-core#10108]
Grails Version: 3.1.10
Groovy Version: 2.4.7
JVM Version: 1.8.0_71

grails install

Task 'install' not found in root project 'MyTest'.

I tried adding (build.gradle):

apply plugin: "maven"

A WAR file was created (of smaller size than the one created by 'grails war') but it wouldn't run:

java -jar MyTest-1.0.0-SNAPSHOT.war

no main manifest attribute, in MyTest-1.0.0-SNAPSHOT.war

**Comment by jeffbrown** [comment]
What is it that you are trying to do?  If you are just trying to build the war, `./gradlew assemble` is probably what you want.  If you are trying to do something else, please clarify.

**Comment by markandirene** [comment]
I managed to get it working by updating build.gradle:

apply plugin: "maven"
:
install.dependsOn assemble


grails install

Now deploys the executable WAR to my local Maven repository.

**Comment by jeffbrown** [comment]
If you are trying to publish to local Maven repository, you probably want `apply plugin: 'maven-publish'` and `./gradlew publishToMavenLocal` (or `./gradlew pTML` for short).

In any case, none of this looks like a bug.  I am going to close the issue.

**Comment by markandirene** [comment]
My only quibble is that 'grails help' lists:

install Installs a Grails application or plugin into the local Maven cache

It doesn't work 'out-of-the-box' as you have to modify build.gradle.

**Comment by jeffbrown** [comment]
I didn't realize that.  I will open the issue for now pending investigation.

Thanks for the feedback.

**Comment by sdelamo** [comment]
I've created a pullrequest which removes `install` command from `base` profile and leave it in `plugin` profile. 

https://github.com/grails/grails-profile-repository/pull/90
