### ISSUE TITLE
bindData() --- Experiencing nullPointerException in use case where all domain associations are excluded

### ISSUE THREAD

**Issue by MauiMana** [grails/grails-core#10101]
When controller issues explicit call to bindData() with a specified 'black list' but not a 'white list' (i.e., the 'whiteList' variable will be null), the grails function 'isOkToBind() will throw an exception. As you can see from the body of this method (see below) 'blackList' is null-protected but 'whiteList' isn't (and I confirmed that with my use case, going into this line of code 'whiteList' is null).

Line 267 of SimpleDataBinder.groovy reads...
`           'metaClass' != propName && !blackList?.contains(propName) && (!whiteList || whiteList.contains(propName) || whiteList.find { it -> it?.toString()?.startsWith(propName + '.')})`

### Steps to Reproduce
1. Define a domain class that inherits a few properties from some base class (one of which is a 'required' manyToOne association), AND then define a hasMany association in the sub subclass. So i the subclass you only have the one 'hasMany' property and no others. I'm not sure if this is significant but I just wanted to be thorough because my feeling is that the case where 'whiteList' can be null is somewhat of an edge case and not the norm.
2. In the save() action of a domain class controller, issue an explicit call to bindData() with a list of properties to 'exclude' that contains both associations (i.e., the one defined in the base class and the one defined in the subclass).
3. attempt to create an instance of the specific domain class (please see  'Actual Behavior' section) 

### Expected Behavior
All arguments not referenced within the 'exclude' list will be bound to the newly created domain object

### Actual Behavior
As bindData() processes each property, 'whiteList' will be null going into isOkToBind() (SimpleDataBinder.groovy). However, the 'null' exception is apparently only thrown when the property being processed is the inherited association referenced within the 'exclude' list (aka 'blackList'). This is just speculation but although there is a '!whiteList' check in the compound condition (see line of code above), the other references to 'whiteList' in the condition are not null-protected and perhaps, as with many other languages, order isn't guaranteed. Again, just speculation... 

### Environment Information

- **Operating System**: OS X Mavericks
- **Grails Version:** 3.1.10
- **JDK Version:** 1.8

**Comment by Schlogen** [comment]
Please upload an example application that reproduces the issue

**Comment by jeffbrown** [comment]
I may be misunderstanding the report but I don't see what the problem is.  I think the code at https://github.com/grails/grails-core/blob/v3.1.10/grails-databinding/src/main/groovy/grails/databinding/SimpleDataBinder.groovy#L267 should operate fine if `whiteList` is `null` because of the `!whiteList` at the beginning...

   'metaClass' != propName && !blackList?.contains(propName) && (!whiteList || whiteList.contains(propName) || whiteList.find { it -> it?.toString()?.startsWith(propName + '.')})

**Comment by MauiMana** [comment]
Is there a guarantee that the various elements of the compound condition will be processed in a left-to-right order? As you know, this is not the case in many languages and I myself do not know if there is such a guarantee in Grails (and the various layers underneath). If there is no such guarantee then it would appear that an attempt can be made to call a function on whiteList (e.g., contains, find, etc.) in situations where it is null. During some of the cases when whiteList is null I'm getting a null pointer exception during the execution of this line of code (and at those times all other values look fine to me). I apologize for perhaps being too focused in my title about whiteList not being null-protected (like blackList is) but this is what immediately jumped out at me from experience with other languages. Again, possible randomnous of condition execution order may not be an issue with grails. If its not then I am stumped...

**Comment by jeffbrown** [comment]
> Is there a guarantee that the various elements of the compound condition will be processed in a left-to-right order?

Yes.  If that isn't being respected, I think that would be a bug in Groovy.

> During some of the cases when whiteList is null I'm getting a null pointer exception during the execution of this line of code (and at those times all other values look fine to me). 

Send us a sample app which demonstrates the problem and we can chase it down.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
If the order wasn't respected, there would be no way to take advantage of operator short-circuiting.

**Comment by MauiMana** [comment]
'Agreed' regarding the assurance of operator short-circuiting. When I get a break I'll see if I can put together an example use case...

**Comment by MauiMana** [comment]
Feel free to close this issue report. I believe I've found the issue that was causing the exception, although it was strange that in my debugger, the exception really appeared to be thrown while executing the condition statement I highlighted in my original description. But with a fix in another section of my code I no longer experience the exception. Thank you for hanging in there with me :)
