### ISSUE TITLE
Cannot target an individual unit test in Grails 3.1.10

### ISSUE THREAD

**Issue by markandirene** [grails/grails-core#10119]
Hello

Grails Version: 3.1.10
Groovy Version: 2.4.7
JVM Version: 1.8.0_71

I have a tag lib class: **mypackage.AddressTagLib**

I have a corresponding unit test: **mypackage.AddressTagLibSpec**

grails test-app mypackage.AddressTagLib
grails test-app mypackage.AddressTagLibSpec
grails test-app AddressTagLib
grails test-app AddressTagLibSpec

I've tried all the above combinations to target to an individual unit test, to no avail.

"> No tests found for given includes: ....."

_grails test-app_ works fine.

Mark

**Comment by jeffbrown** [comment]
Does this work?...

    ./gradlew test --tests *AddressTagLib*

**Comment by markandirene** [comment]
Yes. This works.

Thanks

**Comment by jameskleeh** [comment]
`grails test-app mypackage.AddressTagLibSpec` works for me in 3.2.0.BUILD-SNAPSHOT
