### ISSUE TITLE
YAML File sucks in Grails 3

### ISSUE THREAD

**Issue by satan1999** [grails/grails-core#10112]
In Grails 2, we can put the expression and variables into DSL Groovy File.

But in Grails 3, YAML is too weak to have all our existing configuration.

My suggestion is that Enable the Groovy configuration file as default instead of YAML

**Comment by Schlogen** [comment]
Thank you for the suggestion

**Comment by snimavat** [comment]
@satan1999 we can already have application.groovy - how does it make any difference, if default is yaml or groovy ?

**Comment by rpalcolea** [comment]
Sorry but... why use 'sucks' on an issue description? imo is disrespectful for all the people involved on making grails an awesome framework
