### ISSUE TITLE
Feature Request: Provide way to disable auto timestamp temporarily

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-core#10129]
The use case is integration tests where it is sometimes necessary to simulate data that was entered in the past. There should be a provided way to disable the setting of dateCreated or lastUpdated or both.

**Comment by hamza3202** [comment]
We need this too, With the introduction of multiple datasources we decided to split our main db into multiple regional databases, Our use case is to fulfill some data privacy requirements but others may include faster database access etc.
And now when we are migrating data then fields like date_created are being reset to current date and thus corrupting our data

**Comment by jameskleeh** [comment]
Will be included in the next 6.0.x and 6.1.x release of GORM. Snapshot documentation is here: http://gorm.grails.org/snapshot/hibernate/manual/index.html#eventsAutoTimestamping. Section 8.1.9.
