### ISSUE TITLE
Where queries doesn't respect class as variable, while findBy works as expected

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-core#10139]
### Setup
class Book {
    String title
}

new Book(title:'title1').save()
new Book(title:'title2').save()
new Book(title:'title3').save()

### Find By 
Book.findAllByTitle('title1') <-- first item, correct
def clazz = Book
clazz.findAllByTitle('title1') <-- first item, correct

### Where Queries
Book.where { title == id }.findAll() <-- first item, correct
def clazz = Book
clazz.where { title == id }.findAll() <-- all 3 items, incorrect

### Env
$ grails -version
|Grails Version: 3.1.11
|Groovy Version: 2.4.7
|JVM Version: 1.8.0_102

**Comment by graemerocher** [comment]
Where queries rely on the type and when you use `def` you are losing type information, hence why this doesn't work. If you change `def` to `Class<Book>` then the `where` query will work.

IMO In general with Groovy `def` should be used sparingly as it makes later conversion to `@CompileStatic` more difficult
