### ISSUE TITLE
Grails 3.1.9 "Could not resolve view" exceptions when running deploying war to tomcat

### ISSUE THREAD

**Issue by bilalsha** [grails/grails-core#10138]
When i run the app using the `run-app` command, everything works fine, but when running the same app via a Runnable JAR (or deploying a WAR file to a TOMCAT) generates the following exceptions given in url.

Stacktrace : http://pastebin.com/CnRF940d

### Steps to Reproduce

- grails run-app
- Navigate in browser to http://localhost:8080/
- See that it runs properly
- gradle assemble 
- deploy to tomcat
- Navigate in browser to http://localhost:8080

### Environment Information

```
OS: mac
| Grails Version: 3.1.9
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_25, 1.8.0_102
| Tomcat: 8.0.14, 8.0.36, 8.5.4
```

### Example Application

https://github.com/bilalsha/tomcat-grails.git

P.S: I have read all the issue on github but nothing worked.

**Comment by graemerocher** [comment]
Works fine for me, make sure your JVM version is the same as the Tomcat version

**Comment by sharma-gaurav** [comment]
Worked for me with:  
| Grails Version: 3.1.9
| Groovy Version: 2.4.7
| JVM Version: 1.7.0_79
and  apache-tomcat-9.0.0.M9;

**Comment by mletynski** [comment]
I'm getting same error on my grails 3.0.15. Everything works with run-app but while deploying it to tomcat i'm getting same error.

**Comment by hussainanjar** [comment]
I get the same error but with following behaviour

My jenkins job runs a shell script as a last step which copies was file and restarts tomcat and when I access the site I get this error
`Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'`
And if I run the same shell script from command line all works fine.
I tried this with different grails versions 3.1.5, 3.1.11, 3.1.12 without any luck

**Comment by graemerocher** [comment]
probably a permissions issue with your shell script vs when you do it manually i imagine

**Comment by afeilulu** [comment]
@graemerocher 
you are right.
I deploy with powershell(on windows), the same error show, while manually generating war file and starting tomcat everything works fine.

My enviroment
Grails Version:3.2.0
Groovy Version:2.4.7
JVM Version:1.8.0_102
Tomcat:8.5.4

**Comment by angstream555** [comment]
update grails version at last 3.2.6

**Comment by carlosorrego** [comment]
i am getting this error in grails 3.3.11
only in tomcat as a war
as run-app no problem

**Comment by mimmotecno** [comment]
Same error on grails 4.0.5,
both deployed in tomcat or runnable war or jar.
Everything working with run-app.
How did you solve?
