### ISSUE TITLE
Error when creating a new app

### ISSUE THREAD

**Issue by bitsnaps** [grails/grails-core#10132]
I was using Grails 2.4.4, than I wanted to try 3.2.0 RC1, I've got this error message when creating a new app using: "grails create-app HelloGrails32"

Error Error occurred running Grails CLI: Bad <init> method call from inside of
a branch
xception Details:
 Location:
   org/grails/cli/interactive/completers/AllClassCompleter.<init>()V @123: invo
especial
 Reason:
   Error exists in the bytecode
 Bytecode:
   0000000: b800 144c 04bd 0016 5903 2b12 1732 2b12
   0000010: 1832 2b12 1932 121b 2b12 1c32 121e b900
   0000020: 2402 0012 26b9 002a 0400 b900 2d02 00bb
   0000030: 002f 5912 0212 02b7 0032 b900 3503 0012
   0000040: 37b8 003d c000 3712 37b8 0041 5359 10ff
   0000050: 1204 b800 452a 5fab 0000 003f 0000 0002
   0000060: 1374 8337 0000 0019 4ad1 f42c 0000 002a
   0000070: 5f5a 0312 37b8 004b c000 37b7 004e a700
   0000080: 225f 5a59 0332 121b b800 51c0 001b 5f57
   0000090: b700 54a7 000d bb00 5659 1258 b700 5bbf
   00000a0: 572a b600 5f4d 2c2a 5fb5 0061 2c57 b1
 Stackmap Table:
   full_frame(@112,{UninitializedThis,Object[#101]},{Object[#103],Uninitialized
his})
   full_frame(@129,{UninitializedThis,Object[#101]},{Object[#103],Uninitialized
his})
   full_frame(@150,{UninitializedThis,Object[#101]},{Object[#103],Uninitialized
his})
   full_frame(@160,{Object[#2],Object[#101]},{Object[#103]})
(Use --stacktrace to see the full trace)

### Steps to Reproduce

1. After downloading Grails 3.2.0 RC1 I made fixed grails_home system variable then I created a new app

### Environment Information

- OS: Windows 7 (64 bit)
- **Grails Version:** 3.2.0 RC1
- **JDK Version:** 1.7
- **Container Version (If Applicable):** NA
- Groovy version: 2.4.4

**Comment by bitsnaps** [comment]
For some reason it just worked when I set `GRAILS_OPTS` environment variable to `-XX:-UseSplitVerifier -Xverify:none`
This fixes the issue for grails >= `3.x`, it looks like an [issue](http://stackoverflow.com/questions/32316076/cannot-run-grails-cli-grails-cli-bad-init-method-call-from-inside-of-a-branc) related to JVM.

**Comment by graemerocher** [comment]
Please upgrade your JVM to a newer version
