### ISSUE TITLE
Grails scaffolding throws exception on delete when deployed on WebSphere

### ISSUE THREAD

**Issue by leleFc** [grails/grails-core#10133]
### Steps to Reproduce
1. Create a simple app
2. Create a simple domain (1 text field is enough)
3. Using scaffolding, create controller and views
4. Deploy war on WebSphere 8.5
5. Run application and create a record using the "create" page
6. Try to delete the record using the CRUD delete page/action
### Expected Behaviour

The record is correctly deleted (it happens running application on Tomcat)
### Actual Behaviour

On Websphere is impossible to delete records and exceptions are thrown (see 
[log.txt](https://github.com/grails/grails-core/files/451654/log.txt) )
### Environment Information
- **Operating System**: Windows Server 2012 R2
- **Grails Version:** 3.1.8
- **JDK Version:** 1.7
- **Container Version (If Applicable):** WebSphere 8.5.5.5

**Comment by graemerocher** [comment]
I tested with Grails 3.1.11, JDK 1.7, on OS X with WebSphere 8.5 downloaded from here https://www-01.ibm.com/marketing/iwm/tnd/preconfig.jsp?id=2012-06-14+11%3A09%3A34.913019R&S_TACT=&S_CMP=

And it worked fine for me. Could you please test with the latest Grails 3.1.11 release

**Comment by effrafax** [comment]
Hi, 
I encountered exact the same issue today here. 
WAS 8.5.5.9, JDK 8, grails 3.1.8 on Linux

I will try to build a reproducable test.

**Comment by leleFc** [comment]
Hi @graemerocher, I tried with Grails 3.1.11 but unfortunately the problem happens again..
My WAS version is Full Profile 8.5.5.5 (My customers use this version, so I can't use different releases)

Attached to this post you can find [testdelete.zip](https://github.com/grails/grails-core/files/451809/testdelete.zip) wich contains the sources of my test case, and [Was_logs.zip](https://github.com/grails/grails-core/files/451808/Was_logs.zip) which contains websphere logs about this error

**Comment by graemerocher** [comment]
Can you confirm the JDK type, is it Oracle JDK? JRocket?  or OpenJDK?

**Comment by leleFc** [comment]
When I create war I use Oracle JDK 1.7 update 79, but WebSphere uses his JDK which is IBM's 1.7 (both are 64 bits)

**Comment by graemerocher** [comment]
The most likely reason is a JDK bug, since it isn't reproducible in other JVMs. There was a similar issue which existed in JRocket before they fixed it. However looking at the byte code that the `delete` method produces:

```
    public void delete() {
        CallSite[] var1 = $getCallSiteArray();
        void var10000 = (void)var1[121].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, this);
    }
```

It seems that `void` is used as a variable type which is not valid and what happens is that IBMs JVM don't like this. We will look to see if anything can be delete to improve this byte code.

**Comment by graemerocher** [comment]
Reported https://issues.apache.org/jira/browse/GROOVY-7926 to open the discussion in Groovy

**Comment by graemerocher** [comment]
I have submitted a pull request for this issue https://github.com/apache/groovy/pull/416

It is pending review.

**Comment by leleFc** [comment]
Hi @graemerocher, thank you for your support!!

**Comment by sdelamo** [comment]
@leleFc could we consider this issue solved?

**Comment by leleFc** [comment]
@sdelamo problem solved
