### ISSUE TITLE
Make @CrossOrigin annotation work with grails controllers

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-core#10148]
Currently, it's easier to setup cors in spring mvc, than in grails http://spring.io/guides/gs/rest-service-cors/

There are some tip to write custom filter\intercepter, but I think, it should be just an option in config file.

**Comment by graemerocher** [comment]
Is this necessary given the existence of https://github.com/appcela/grails3-cors-interceptor ?

**Comment by allnightlong** [comment]
With this plugin it is not possible to provide cors headers on per controller/method level.
For example, I want this header only apply to `/api` controllers, and not to others.

**Comment by graemerocher** [comment]
That would be a matter of making https://github.com/appcela/grails3-cors-interceptor/blob/master/grails-app/controllers/grails3/cors/interceptor/CorsInterceptor.groovy#L17 configurable, seems pull request worthy

**Comment by allnightlong** [comment]
If I would modify this plugin the right way&trade;, code should respect origins, headers, methods, credentials and maxAge of `@CrossOrigin` annotation. Sooner or later, I will end up with something like [`RequestMappingHandlerMapping.initCorsConfiguration()`](https://github.com/spring-projects/spring-framework/blob/06395f41cbe22c8f52d2c95b157059b8a60bad9b/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.java#L294).

Using copy-paste here just feels wrong, but at the same time, I don't know how to apply RequestMappingHandlerMapping to grails controllers (if it's even possible).

**Comment by graemerocher** [comment]
It would be a matter of extending and customizing https://github.com/grails/grails-core/blob/master/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/mvc/UrlMappingsHandlerMapping.groovy

Which is registered here https://github.com/grails/grails-core/blob/master/grails-plugin-url-mappings/src/main/groovy/org/grails/plugins/web/mapping/UrlMappingsGrailsPlugin.groovy#L72
