### ISSUE TITLE
added WebMvcConfigurerAdapter not working

### ISSUE THREAD

**Issue by xmlking** [grails/grails-core#10147]
I am trying to enable CORS as documented at [Spring Boot](https://spring.io/guides/gs/rest-service-cors/) for Grails 3.x application. 
looks like it not effective. The only way it is working so far is through `CorsFilter >> OncePerRequestFilter` 
Can Grails 3 app  take advantage of `@CrossOrigin(origins = "http://localhost:3000")` annotation ? 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try the provided sample app below 

### Expected Behaviour

I should be able to enable CORS using Spring Boot approach 

### Actual Behaviour

CORS is not working. 

### Environment Information

- **Operating System**: MacOS
- **Grails Version:** 3.2
- **JDK Version:** 1.8
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/xmlking/grails-angular-jwt/blob/master/grails-app/init/grangular/Application.groovy#L17 

https://github.com/xmlking/grails-angular-jwt/blob/master/grails-app/controllers/grangular/BookController.groovy#L8

```groovy
class Application extends GrailsAutoConfiguration {
    static void main(String[] args) {
        GrailsApp.run(Application, args)
    }

    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                //registry.addMapping("/**/*").allowedOrigins("*");
                registry.addMapping("/api/**")
                        .allowedOrigins("http://localhost:3000")
                        .maxAge(3600);
            }
        };
    }
}
```

```groovy
@CrossOrigin(origins = "http://localhost:3000")
@Secured('ROLE_USER')
class BookController extends RestfulController {
    static responseFormats = ['json', 'xml']
    BookController() {
        super(Book)
    }
}
```

**Comment by graemerocher** [comment]
Probably won't work no, since it is designed for use with Spring MVC controllers, have a look at https://github.com/appcela/grails3-cors-interceptor for an alternative. Eitherway this is something better handled via a plugin.
