### ISSUE TITLE
bug with transients and inheritance

### ISSUE THREAD

**Issue by lgrignon** [grails/grails-core#10142]
### Steps to Reproduce
1. Create a base class AbstractModel outside domain directory (so it is not mapped to a real table)
2. Declare some transients fields in AbstractModel using static transients
3. Create a model class MyModel extends  AbstractModel
4. Declare additional transients fields specific to MyModel using static transients = AbstractModel.transients + ['mySpecificField1', ...]
5. Run the example
6. See that the fields are not all transient => fields generated in database, etc... (in my original case, I had an EOFException due to a complex transient field in my AbstractModel which should never have been mapped, which hibernate tried to deserialize, causing this exception)
### Expected Behaviour

In a perfect world, grails should be able to sum up transients fields up through the class hierarchy, but in the real world, this simple case should work `static transients = Parent.transients + ['....']`
### Actual Behaviour

the fields are not all considered transient => fields are generated in database, read when object is fetched etc...
### Environment Information
- **Operating System**: Windows 10
- **Grails Version:** 3.1.11 (same problem with 3.1.10)
- **JDK Version:** 1.8.0_65
- **Container Version (If Applicable):** launched with bootRun
### Example Application

https://github.com/lgrignon/grails-bug-transients

**Comment by graemerocher** [comment]
Seems to work fine in GORM 6, see test https://github.com/grails/grails-data-mapping/commit/19ab5870802cc1d5ca43972784ef04fdaee0afe1
