### ISSUE TITLE
Improve command object documentation when you want to bind a list of objects.

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#10143]
Command objects are one of my favorite things in Grails. However documentation is quite sparse, especially about how binding for List of objects works. Please improve this.

For example for binding multiple books to an author you can do the following

Command Object:
```java
class AuthorCommand {
    String fullName
    List<BookCommand> books = []
}

class BookCommand {
    String title
    String isbn
}
```
gsp:
```html
<g:form name="submit-author-books" controller="author" action="save">
    <g:fieldValue name="fullName" value=""/>
    <ul>
        <li>
            <g:fieldValue name="books[0].title" value=""/>
            <g:fieldValue name="books[0].isbn" value=""/>
        </li>

        <li>
            <g:fieldValue name="books[1].title" value=""/>
            <g:fieldValue name="books[1].isbn" value=""/>
        </li>
    </ul>
</g:form>
```

There is also support for JSON, so you can submit the following with correct databinding
```json
{
	"fullName": "Graeme",
	"books": [{
		"title": "Grails in Action",
		"isbn": "1111-343455-1111"
	}, {
		"title": "Grails Cook Book",
		"isbn": "1111-343455-1112"
	}],
}
```

**Comment by olavgg** [comment]
Also note that there are a lot of old examples out there in the wild that do no longer work and are confusing.

**Comment by jeffbrown** [comment]
If anyone is interested in contributing updates to the notes at http://docs.grails.org/3.1.11/guide/theWebLayer.html#commandObjects, the relevant source code is at https://github.com/grails/grails-doc/blob/f60bc735791d89ddfc7134f6c8882f8b3dd82ed3/src/en/guide/theWebLayer/controllers/commandObjects.gdoc.

**Comment by rpalcolea** [comment]
@olavgg are you planning to do this? otherwise I can do it :)

**Comment by olavgg** [comment]
@rpalcolea 

I can do this tomorrow. No worries and thanks! And thank you to @jeffbrown for pointing me documentation source.

**Comment by rpalcolea** [comment]
Oh sorry I jumped in before your response... I opened the PR but I put you as the original reporter and the examples creator, hope that doesn't create a conflict.

**Comment by olavgg** [comment]
Oh I see, things move fast in the Grails community! :-) I'm fine with that, please note that there was a typo in my first example with double double quotes.

**Comment by jeffbrown** [comment]
I am closing this as https://github.com/grails/grails-doc/issues/487 is being addressed.

Thanks for the feedback!

**Comment by rpalcolea** [comment]
Thanks @jeffbrown and @olavgg 

I updated the pull request with the fixes for the typos.
