### ISSUE TITLE
@GrailsCompileStatic in a command object breaks importFrom method call

### ISSUE THREAD

**Issue by Macoshark** [grails/grails-core#10157]
### Steps to Reproduce

1. Define a base command object that other command objects extend.

    @Validateable
    @GrailsCompileStatic
    class ApiCommandBase {
        String param
        ...

        static constraints = {
            param nullable: true
            ...
        }
    }

2. The extended command object imports the constraints from ApiCommandBase by calling the importFrom method.

    @Validateable
    @GrailsCompileStatic
    class AccountCmd extends ApiCommandBase {
        String username

        static constraints = {
            importFrom ApiCommandBase
            username blank: false
        }
    }

### Expected Behaviour

The code compiles normally.

### Actual Behaviour

This results in the following compilation error:

    Compilation error: startup failed:
    AccountCmd.groovy: 15: [Static type checking] - Cannot find matching method AccountCmd#importFrom(java.lang.Class <ApiCommandBase>). Please check if the declared type is right and if the method exists.
    @ line 15, column 9.
               importFrom ApiCommandBase
               ^
    1 error

### Environment Information

- **Operating System**:  Mac OSX El Capitan
- **Grails Version:** 2.5.5
- **JDK Version:** 1.7
- **Container Version (If Applicable):** N/A

**Comment by graemerocher** [comment]
Not sure it supports the `constraints` block yet. @jeffbrown ?

**Comment by rpalcolea** [comment]
I had this issue a couple of days ago, forgot to open the ticket. From the docs http://docs.grails.org/latest/guide/staticTypeCheckingAndCompilation.html

> Code that is marked with GrailsCompileStatic will all be statically compiled except for Grails specific interactions that cannot be statically compiled but that GrailsCompileStatic can identify as permissible for dynamic dispatch. These include things like invoking dynamic finders and DSL code in configuration blocks like constraints and mapping closures in domain classes.

it mentions constraints.

**Comment by jeffbrown** [comment]
@graemerocher Yes, `constraints` is supported.  The issue is that the type checking extension is being too strict in that it only allows calls to methods who's name matches the name of a field in the class.  Will be a simple fix.  https://github.com/grails/grails-core/blob/246b7264e8a638ada188ddba7a7a8812ba153399/grails-core/src/main/groovy/org/grails/compiler/ValidateableTypeCheckingExtension.groovy#L60
