### ISSUE TITLE
Quartz2 lib contains the issue related to the default initialize() method in class LocalDataSourceJobStore

### ISSUE THREAD

**Issue by kaushik-doshi2007** [grails/grails-core#10154]
I have used the Quartz2 lib v0.2.3. When I build the war of my project it generates the following exception:

`
[groovyc] /home/kaushik/grails-apps/com/plugins/quartz2-2.1.6.2/src/java/grails/plugin/quartz2/LocalDataSourceJobStore.java:103: error: <anonymous grails.plugin.quartz2.LocalDataSourceJobStore$1> is not abstract and does not override abstract method initialize() in ConnectionProvider
  [groovyc] 				new ConnectionProvider() {
  [groovyc] 				                         ^
  [groovyc] /home/kaushik/grails-apps/com/plugins/quartz2-2.1.6.2/src/java/grails/plugin/quartz2/LocalDataSourceJobStore.java:120: error: <anonymous grails.plugin.quartz2.LocalDataSourceJobStore$2> is not abstract and does not override abstract method initialize() in ConnectionProvider
  [groovyc] 				new ConnectionProvider() {
  [groovyc] 				                         ^
  [groovyc] Note: /home/kaushik/grails-apps/com/plugins/quartz2-2.1.6.2/src/java/grails/plugin/quartz2/LocalDataSourceJobStore.java uses unchecked or unsafe operations.
`

To fixed it, I just add the default initialize() method to the said line and built the war successfully.
![1](https://cloud.githubusercontent.com/assets/22188881/18502501/23c3f37a-7a75-11e6-9df4-ca17b570d41f.png)

It's only worked in version (groupId:org.grails.plugins) quartz2:0.2.3-SNAPSHOT. I think this method should be include in the class LocalDataSourceJobStore.java to overcome the issue.

**Comment by graemerocher** [comment]
Please raise an issue with the plugin, this has nothing to do with grails core
