### ISSUE TITLE
In a unit test, promises are executed twice

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-core#10152]
Within unit tests, Grails configures a `SynchronousPromiseFactory`. This is fine.

However, that makes promises to be executed twice:
1. When the `Promises.task{}` method is called.
2. When `Promises.waitAll` is called.

The workaround is to set `Promises.promiseFactory = new GparsPromiseFactory()` within the test setup.

**Comment by jameskleeh** [comment]
@alvarosanchez Are your closures returning null?

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-core/commit/4d18ef1fb9adcadf4ba0b02c6ecf9af87cda64be
