### ISSUE TITLE
Compilation error when using generic as property type

### ISSUE THREAD

**Issue by ZacharyKlein** [grails/grails-core#10159]
### Steps to Reproduce

1. Define abstract domain class that takes a generic and uses it as a property
2. Run the app

### Expected Behaviour

Application should start up w/o compilation error.

### Actual Behaviour

Startup fails with the following error:
```The class java.lang.Object refers to the class java.lang.Object and uses 1 parameters, but the referred class takes no parameters
 @ line -1, column -1.````

### Environment Information

- **Operating System**: OS X 10.11.6
- **Grails Version:** 3.1.10
- **JDK Version:** 1.8

### Example Application

- [Sample project](https://github.com/ZacharyKlein/GenericsDomainClassError)
- Sample application includes two classes with different compilation errors (one using a bound generic)

**Comment by graemerocher** [comment]
A potential fix for this has been committed https://github.com/grails/grails-data-mapping/commit/06a37105192ec1b63bc6da1f50e47304dbbef127
