### ISSUE TITLE
Wrong JDBC URL for H2 database in documentation

### ISSUE THREAD

**Issue by javafx-dev** [grails/grails-core#10153]
When going through documentation (http://docs.grails.org/latest/guide/single.html) there is a statement that says:
"you just need to change the JDBC URL to jdbc:h2:mem:devDB."

but there should be:
url: jdbc:h2:mem:devDb

small 'B' at the end.

**Comment by jameskleeh** [comment]
Fixed https://github.com/grails/grails-doc/commit/1066f6d853412a0e1b7eaf7e3929c34617ae31d9
