### ISSUE TITLE
Do not like the New Grails 3 scaffolding template

### ISSUE THREAD

**Issue by satan1999** [grails/grails-core#10156]
I am migrating my Grails 2 applications to Grails 3.1.9

I got the same problems as the following comment:

ow with grails 3, install-templates does not create _form.gsp. As per this documentation, we can achieve customization by creating _wrapper.gsp, _widget.gsp etc under view/_fields/default directory. But I am not able to find the example of such custom GSPs.

Also, let's say if I customize all the four GSPs (_wrapper.gsp, _widget.gsp, _displayWrapper.gsp, _displayWidget.gsp) will it generate actual code when we run generate-view command? I mean will it replace, f:all, f:table etc tag with actual code? If not then there is quite amount of work to do I guess. Because after we are confident about our domain class and tested all CRUD operation, we run generate-view command for creating all the domain specific GSPs. Then in most cases, we need to do some changes according to our requirement, like re-ordering the fields, hiding some of the fields

### Expected Behaviour

1. Able to copy all customized gsps in template folders

2. When I run generate-view, I do not want f:all, f:table etc abstract tags. I need actual fields in place so that I can customize generated views of domain.

### Actual Behaviour

1   .  In 3.1.9, I added new template pages like ( Search.gsp and _search.gsp).

After executed command generate-view au.com.bglcorp.sso.auth.SsoUser -force

It only created standard pages.
| Rendered template edit.gsp to destination grails-app/views/ssoUser/edit.gsp
| Rendered template create.gsp to destination grails-app/views/ssoUser/create.gsp
| Rendered template index.gsp to destination grails-app/views/ssoUser/index.gsp
| Rendered template show.gsp to destination grails-app/views/ssoUser/show.gsp
| Views generated for grails-app/domain/au/com/bglcorp/sso/auth/SsoUser.groovy

2.  We have to rely on the field plugin and all existing templates don't work any longer.

The Field plugin is not good enough to achieve what we used to have.

### Environment Information

- **Operating System**: MAC OS
- **Grails Version:Grails 3.1.9
- **JDK Version:1.8
- **Container Version (If Applicable):** TODO

**Comment by graemerocher** [comment]
Whilst I appreciate the concern, the scaffolding plugin in 3.x is easier to maintain, less hacky and provides more best practice code. Since scaffolding is primarily a learning tool the code that is generated represents more how applications should be constructed.

That doesn't exclude creating a different plugin that does what you want however, so feel free to fork the scaffolding plugin and customize it to your needs. What Grails provides is the default, but it is completely customizable to your needs through plugins and profiles.

**Comment by zbubric** [comment]
Hi,
I have similiar concern as Satan (this sound a bit wierd :-) ) but, for me it would be enough to replace f:all with f:each and then generate individual f:field items. By using this, I would still have a clean code but with possibility to easily override fields when needed (e.q. add special widget in particular page). 
Is there any way to access list of domain object properties in template files?

**Comment by snimavat** [comment]
@zbubric domainClass.persistentProperties will give u list of persistent properties

**Comment by zbubric** [comment]
@snimavat: Do you have any code snippet that show exact usage? I was googling for half a day on this topic and it seems that, from Grails 3, Grails app context is not exposed to template files, meaning that I can not reach domain class this way. In meanwhile I founded issue explaining exacly what I meant but, conversarion on that one is also a bit unclear to me: https://github.com/grails3-plugins

**Comment by jameskleeh** [comment]
@zbubric @snimavat It is not possible to get domain properties in the templates

**Comment by bitsnaps** [comment]
@zbubric  the idea to get domainClass properties is to use Holders, I do not if this is good practice or not but it works well, so you could write in the scaffolding template some thing like this:
`            def grailsApplication = grails.util.Holders.grailsApplication
            def domainObjetc = grailsApplication.domainClasses.find { it.clazz.simpleName == className }.clazz.newInstance()
            def domainClass=  grailsApplication.getDomainClass(domainObjetc.getClass().name)`
tested with grails 3.1, hope this helps.

**Comment by zbubric** [comment]
@bitsnaps Thx, I will give it a try ...

**Comment by kakavi** [comment]
@zbubric i tried out you code but throws the error below;
Error rendering template [create.gsp] to destination grails-app\views\TestDomain\create.gsp: No such property: grails for class: groovy.lang.Binding

**Comment by leopinho** [comment]
> @zbubric i tried out you code but throws the error below;
> Error rendering template [create.gsp] to destination grails-app\views\TestDomain\create.gsp: No such property: grails for class: groovy.lang.Binding

I have the same issue - Grails 3.3.5

**Comment by leopinho** [comment]
> @zbubric the idea to get domainClass properties is to use Holders, I do not know if this is good practice or not but it works well, so you could write in the scaffolding template something like this:
> 
> ```groovy
> def grailsApplication = grails.util.Holders.grailsApplication
> def domainObjetc = grailsApplication.domainClasses.find { it.clazz.simpleName == className }.clazz.newInstance()
> def domainClass=  grailsApplication.getDomainClass(domainObjetc.getClass().name)
> ```
> 
> tested with grails 3.1, hope this helps.

It doesn`t work in grails 3.3: "no such property: grails for class: groovy.lang.Binding"

**Comment by bitsnaps** [comment]
@leopinho I've switched to use [Grails Fields Plugin](http://grails-fields-plugin.github.io/grails-fields/latest/guide/index.html) as suggest by @graemerocher everything's ok with grails 3.5.
