### ISSUE TITLE
GRAILS_GRADLE_HOME does not work with 3.2.0.RC2

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#10168]
### Task List

- [* ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. set environment variable GRAILS_GRADLE_HOME = D:\program\gradle\gradle-3.1
2. grails create-app test
3. cd test
4. grails

### Expected Behaviour

Use gradle 3.1

### Actual Behaviour

Still use gradle 3.0
```
| Resolving Dependencies. Please wait...
Downloading https://services.gradle.org/distributions/gradle-3.0-bin.zip
```

It works in Grails 3.1.x.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** Grails 3.2.0.RC2
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
You need to update the wrapper used that is configured in the project's `gradle.properties`. Just run `gradle wrapper` when 3.1

**Comment by todoubaba** [comment]
Still does not work, grails download gradle 3.0 as described.

**Comment by graemerocher** [comment]
Using 3.2.0.RC2 if I create a new project and run `gradle wrapper` with 3.1:

```
grails create-app gradle-test
cd gradle-test
gradle wrapper
```

I get the output:

```
| Resolving Dependencies. Please wait...
Downloading https://services.gradle.org/distributions/gradle-3.1-bin.zip
.
```

When running the `grails` command.

**Comment by todoubaba** [comment]
Sorry, the ouput is coming from a multi-project build. Works fine with a normal grails project.

settings.gradle:
```
rootProject.name = 'test'

include 'test-api'
include 'test-web'
```

```
cd test-web
gradle wrapper
grails
```
output:
```
| Resolving Dependencies. Please wait...
Downloading https://services.gradle.org/distributions/gradle-3.0-bin.zip
```

**Comment by todoubaba** [comment]
I need run `gradle wrapper` in upper level directory. Thanks for your support.

**Comment by todoubaba** [comment]
Bug I still think it's a bug, if `GRAILS_GRADLE_HOME` environment  variable exists, grails should not download gradle from network.

**Comment by amcclain** [comment]
Thanks for this thread - we ran into Gradle 3.0 unexpectedly (and transparently) being used in a multi-project Grails 3.3.1 build where we expected to be using Gradle 4.2.1 (4.2.1 being the version our sub-projects all pointed to in their gradle.properties and what IntelliJ's gradle settings all specified). 

Our build was throwing on a reference we had in our build.gradle to `sourceSets.main.output.classesDirs` - where `getClassesDirs()` is a 4.x method. Still unclear to me why (presumably) Grails is falling back to 3.0 at some level, but installing the wrapper in the top-level directory of our multi-project setup indeed got the entire build properly using the desired version.
