### ISSUE TITLE
Tomcat Redeploy Database locked

### ISSUE THREAD

**Issue by PhilG** [grails/grails-core#10165]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate new Grails Project
2. Run `grails war`
3. Move the resulting war file into Tomcats' `./webapp` directory
4. Start Tomcat via `bin/startup.sh`
5. Change application code
6. Run `grails war`
7. Move the resulting war file into Tomcats' `./webapp` directory and overwrite the old one

### Expected Behaviour
Tomcat should redeploy the war application and get it back into a functioning state within a couple seconds.

### Actual Behaviour
The application does not get redeployed and accessing the URL where it should be available returns a 404.

### Environment Information

- **Operating System**: OSX 10.11.6
- **Grails Version:** 3.1.11
- **JDK Version:** 1.8u102
- **Container Version (If Applicable):** Tomcat 8.5.5

### Stacktrace
https://gist.github.com/PhilG/468785ac1545c7b56e4b03a135b2c709

### Example Application

https://github.com/PhilG/GrailsTest

**Comment by graemerocher** [comment]
In your database URL can you try modify 

```yaml
    url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```
to

```yaml
    url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
```

**Comment by PhilG** [comment]
I did, same result still. I need to restart Tomcat with the `shutdown.sh` and `startup.sh` to actually have Tomcat use the new *.war file.

**Comment by graemerocher** [comment]
For deployment to production you should use a real database and not h2, nothing we can do about this behaviour in h2 itself
