### ISSUE TITLE
includeFlat Gradle directive interpretation misbehave

### ISSUE THREAD

**Issue by claudiocarcaci** [grails/grails-core#10160]
Hi all,
I'm here to describe a subtle issue about Grails and his import feature supplied by Gradle.

OS Ubuntu 16.04 LTS
My Grails version is 3.2.0.M2
Java version is jdk1.8.0_31
And I'm using Intellij 2016

TODO. I have created a project (Foo) with a module (Bar)
TODO. Bar module exists under Foo main project and has his CallMeController
TODO. Running Foo app and calling the url http://localhost:8080/CallMe will result in a correct controller call

TODO. Now I move the Bar folder outside the Foo folder project
TODO. I change the settings.gradle file using an includeFlat in place of include directive which should be supported without any problem as reported here
https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:hierarchical_layouts
TODO. Intellij recognize the project structure correctly
TODO. Running the application and calling the url http://localhost:8080/CallMe will result into a 404 Not found

In the attached files there are the two simple projects which reproduce the issue.
The working one is related with include directive, the second (not working) one is related with includeFlat directive.

Is this a normal behavior?

[Foo-working.zip](https://github.com/grails/grails-core/files/476972/Foo-working.zip)
[Foo-not-working.zip](https://github.com/grails/grails-core/files/476973/Foo-not-working.zip)

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
