### ISSUE TITLE
Can't override grails default messages in messages.properties -- grails 3.2.0.M2

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#10161]
### Task List

 Steps to reproduce provided

- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the [example application](https://github.com/ejaz-ahmed/grails-messages) which has a domain class with single field with [unique constraint](https://github.com/ejaz-ahmed/grails-messages/blob/master/grails-app/domain/demo/User.groovy#L6). Its unique message is being overridden [here](https://github.com/ejaz-ahmed/grails-messages/blob/master/grails-app/i18n/messages.properties#L59)
2. Run the sample app
3. Use this curl command to create one user
```
curl -i -X POST \
   -d \
'{
  "username":"ejaz"
}' \
 'http://localhost:8080/signup/signup'
```

4. Once above user is created, send this command again and the following error message appears instead of custom message in message.prop file

```
"defaultMessage": "Property [{0}] of class [{1}] with value [{2}] must be unique",
```

### Environment Information

- **Operating System**: Mac
- **Grails Version:** 3.2.0.M2
- **JDK Version:** 8

### Example Application

https://github.com/ejaz-ahmed/grails-messages

**Comment by graemerocher** [comment]
You are using 

```groovy
respond user.errors.allErrors as JSON
```

Which essentially uses marshals each `FieldError` java object dynamically to JSON, which is not the way to do this. If I do:

```groovy
respond user.errors
```

The resulting JSON is:

```json
{"message":"User with this username already exists","path":"/signup/signup","_links":{"self":{"href":"http://localhost:8080/signup/signup"}}}
```
Which uses the `grails-app/views/errors/_errors.gson` template which is the behaviour you want. If you want to customize how the error is rendered simply modify this template.
