### ISSUE TITLE
Adding responseFormats to Controller causes nulls in JSON View

### ISSUE THREAD

**Issue by kastone** [grails/grails-core#10175]
When a Controller uses the respond method, passing a map as the object parameter, and rendering to a JSON view, any map values are rendered as null after `static responseFormats = ['json']` is added to the Controller. Without this line in the controller, the respond method works correctly and the map values are correctly rendered in the JSON output.

Given this Controller:
```Groovy
package demo

import org.springframework.http.HttpStatus

class DemoController {

    // this line breaks something...
    // the model variables in the view don't get populated
    //static responseFormats = ['json']

    def index() {
        respond([firstName: 'Jeff', submissionPackageId: 42l], status: HttpStatus.CREATED)
    }
}
```

and this JSON View:

```
import org.springframework.http.HttpStatus
model{
    Long submissionPackageId
    String firstName
}
json {
    name firstName
    id submissionPackageId
    status HttpStatus.CREATED
}
```
I expect that the JSON will render {"name":"Jeff","id":42,"status":"CREATED"}

### Steps to Reproduce
Run the example app at https://github.com/jeffbrown/kastone

Issue a call to the index action in the DemoController. It should, by convention, render JSON using /demo/index.gson.

curl -i http://localhost:8080/demo

### Expected Behaviour
The JSON rendered is correct:
{"name":"Jeff","id":42,"status":"CREATED"}

### Actual Behaviour
the JSON rendered has null values:
{"name":null,"id":null,"status":"CREATED"}

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.1.10
- **JDK Version:** 1.8.0_101

### Example Application
https://github.com/jeffbrown/kastone

**Comment by jeffbrown** [comment]
I have updated the project at https://github.com/jeffbrown/kastone to indicate that this now works as expected in Grails 3.2.0.

@graemerocher I don't see the relevant commit(s) that fixed this problem.  @kastone has asked me what the change was.  Can you respond here with a link to whatever it was that changed when you have a chance?  Thanks!
