### ISSUE TITLE
Changes in 'grails-app/i18n/*.properties' doesn't trigger recompilation in development mode

### ISSUE THREAD

**Issue by xger** [grails/grails-core#10172]
- **Operating System**: Mac OS X 1.8.5
- **Grails Version:** 3.1.11 and 3.1.12
- **JDK Version:** 1.8.0_101

**Comment by graemerocher** [comment]
A workaround is to add the following to `build.gradle`:

```
provided 'org.codehaus.groovy:groovy-ant:2.4.7'
```
