### ISSUE TITLE
Security Vulnerability with Apache Commons FileUpload

### ISSUE THREAD

**Issue by dewaynemcnair** [grails/grails-core#10176]
grails-web-fileupload depends on commons-fileupload 1.3.1.  A [security vulnerability](https://commons.apache.org/proper/commons-fileupload/security-reports.html) was recently found / addressed. 1.3.2 is the current version.

grails-web-fileupload should be updated to use commons-fileupload 1.3.2

**Comment by graemerocher** [comment]
Thanks.. by default Grails 3 doesn't use commons fileupload and uses the standard servlet API implementation. commons fileupload is only an optional dependency, so I don't believe this is a serious issue for current applications.

**Comment by dewaynemcnair** [comment]
@graemerocher - I understand your response, but it's being pulled in as a transitive dependency and when projects are scanned for vulnerabilities, it shows up.  So, I think it's important to address this.  It's an easy fix - please reconsider.

**Comment by jameskleeh** [comment]
@dewaynemcnair Looks like it was done https://github.com/grails/grails-core/commit/b5501dfb37fd6e93a784ee1ebfda98a2ec5600f1

**Comment by dewaynemcnair** [comment]
@jameskleeh ah - thanks - assumed that since my PR was closed without merging it was not going to be done.
