### ISSUE TITLE
Correct location of java source?

### ISSUE THREAD

**Issue by davidklebanoff** [grails/grails-core#10178]
In the [User Guide](http://docs.grails.org/latest/guide/upgrading.html) under the "Upgrading from previous versions of Grails" section, in the table in the "File Location Differences" subsection - there is a row that states code within `src/java` should be moved to `src/main/groovy` (The same folder as the groovy code). Is this a typo, or are we suppose to, in fact, be mix groovy and java code in Grails 3?

If not a typo:

- Why? Is this to assist in joint compilation issues? If so, I believe this can be achieved by simply running the groovy compiler across both a src/main/groovy and src/main/java folder. No separate compilers for groovy and java necessary.
- If it remains as is perhaps the description column should give a little footnote as to why, as it seems a bit unintuitive.

If a typo:

- We should update the documentation. :)

**Comment by jeffbrown** [comment]
> Is this a typo, or are we suppose to, in fact, be mix groovy and java code in Grails 3?

It is not a typo, it just a path left over from previous versions of Grails.  The typical thing is for folks to put their Java and Groovy source under `src/main/groovy/`.  Gradle is flexible with respect to this and you could really put your Java source in any directory you like.

**Comment by jeffbrown** [comment]
Gradle of course supports `src/main/java/`.

**Comment by jeffbrown** [comment]
> Is this to assist in joint compilation issues?

No.

**Comment by jeffbrown** [comment]
As far as I can tell, the reference docs are all correct.  There are some other places where `src/java` is incorrect though.  See https://github.com/grails/grails-doc/commit/8307e3b8780519bcd10623bfb2447ff6d2edb773 and https://github.com/grails/grails-doc/commit/30cbe8f0381f7b461cfc85028d358d0e67cda9b7.

**Comment by jeffbrown** [comment]
Above I said "No." to the question about assisting joint compilation, which isn't really correct.  It is to assist joint compilation.  It isn't necessary for joint compilation, but if separating the Java and Groovy source files, Gradle needs to be configured to know about that in order for joint compilation to work correctly.  That can be done, but the custom config isn't required when everything is in `src/main/groovy/`.  Apps are free to separate them if they like, but we don't impose the custom config by default.
