### ISSUE TITLE
Upgrade v2.5.3 to v2.5.5 didn't upgraded the wrapper.

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#10173]
I upgraded grails to 2.5.5 a couple of weeks ago and just realize the wrapper is still referencing 2.5.3. Under my project's /wrapper folder I have: grails-wrapper-runtime-2.5.3.jar

That is causing my CI to fail because is configured to 2.5.5.

The docs say: " When the application is upgraded to the next version of Grails, the wrapper is updated and checked in to the source code control system and the next time developers update their workspace and run the wrapper, they will automatically be using the correct version of Grails." http://docs.grails.org/2.5.5/guide/single.html#wrapper

Clearly this didn't happened.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a grails 2.5.3 project
2. set version to 2.5.5

### Expected Behaviour

Find grails-wrapper-runtime-2.5.5.jar instead grails-wrapper-runtime-2.5.3.jar in the wrapper folder

### Actual Behaviour

grails-wrapper-runtime-2.5.3.jar is in the wrapper folder instead of grails-wrapper-runtime-2.5.5.jar

### Environment Information

- **Operating System**: tested on win and debian
- **Grails Version:** 2.5.5
- **JDK Version:** 1.7.x

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jeffbrown** [comment]
Setting the version to 2.5.5 doesn't (and isn't intended to) cause the wrapper to be updated.  You will need to generate the wrapper using 2.5.5.  Where the docs say the following:

> When the application is upgraded to the next version of Grails, the wrapper is updated and checked in to the source code control system...

That is describing something that a human needs to initiate.  Grails doesn't automatically update the wrapper and it doesn't automatically check anything into the source code control system.
