### ISSUE TITLE
Grails 3.2.0.RC2 schema-export fails due to running Bootstrap.groovy

### ISSUE THREAD

**Issue by jknudsen** [grails/grails-core#10185]
### Task List

After adding a BootStrap.groovy to a DB when the schema does not exist.  The schema-export fails running the BootStrap.groovy.  The schema-export command should skip the BootStrap.groovy when doing the default action of generate. 

### Steps to Reproduce

1. Add a domain object
2. Add a BootStrap.groovy that tries to add rows to that DB
3. Configure the dataSource to a DB without permission to generate a schema
4. run: grails schema-export

### Expected Behaviour

Export should succeed on DB other then the Embedded H2

### Actual Behaviour

Export fails when running BootStrap.groovy because the DB does not exist

### Environment Information

- **Operating System**: Windoze 7
- **Grails Version:** 3.2.0.RC2
- **JDK Version:** 1.8.0_101

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/gorm-hibernate4/commit/d8d9bb3062a8fc5231ef8245c860e68908b7689f and https://github.com/grails/gorm-hibernate5/commit/b3cf2793f3ac89732da88efe379b4983e6635fad
