### ISSUE TITLE
Alert for when a plugin is being used for a version, of Grails/Java that's not supported

### ISSUE THREAD

**Issue by virtualdogbert** [grails/grails-core#10195]
I would be nice to have a feature where a plug-in developer could specify a min/max version of Grails/Java. Then when a user tries to use that plug-in with a version of Grails/Java, that is not supported they would get and error/warning message.

**Comment by graemerocher** [comment]
This is already possible, see `grailsVersion` property at http://docs.grails.org/latest/guide/plugins.html#creatingAndInstallingPlugins

**Comment by jeffbrown** [comment]
The title says "Groovy/Java" but the body says "Grails/Java".  Dealing with Java and Groovy version issues is separate from dealing with Grails versions.  I think the `grailsVersion` property should deal with the Grails version.

**Comment by jeffbrown** [comment]
I see the title has been changed now so the issue isn't concerned with Groovy versions.  That leaves Grails and Java.  I believe that `grailsVersion` deals with the Grails version.  Allowing plugin authors to express a Java version would be a new feature.  If a plugin requires a certain version of Java, they could deal with that in the same way that any Java library could.  We could conceivably add explicit support for specifying Java versions but I don't think it is needed.

Thoughts?

**Comment by virtualdogbert** [comment]
The Java version was something someone else brought up on slack. I'm using Java 8, so it's not really a big deal for me, right now. Not sure about the future with Java 9...

With the Grails version, you're right there is a place to specify the version, but when you try to compile or run the app, there is no warning, or error message, indicating the incompatibility.

**Comment by jeffbrown** [comment]
> With the Grails version, you're right there is a place to specify the version, but when you try to compile or run the app, there is no warning, or error message, indicating the incompatibility.

Will get that straightened out.  Thanks for the feedback.

**Comment by jeffbrown** [comment]
Never mind the title and description of this issue.  We will treat this as relating only to Grails version and not relating to Java versions.
