### ISSUE TITLE
Code in application.js no longer valid for jQuery 2.2

### ISSUE THREAD

**Issue by jknudsen** [grails/grails-core#10206]
After running create-app a JS file is generated called application.js and contains entries to include other JS files including jquery-2.2.0.min plus code for providing a spinner to fade in and out on an ajax call.  

That code for the spinner is no longer working due to jquery 2.2.0 per the statement below from the jQuery documentation:

As of jQuery 1.9, all the handlers for the jQuery global Ajax events, including those added with the .ajaxStart() method, must be attached to document.

[jQuery documentation](https://api.jquery.com/ajaxStart/)

I replaced that code with the following (note I am far from an expert with JavaScript code):

```
if (typeof jQuery !== 'undefined') {
    (function($) {
        $(document).ajaxStart(function() {
            $('#spinner').fadeIn();
        }).ajaxStop(function() {
            $('#spinner').fadeOut();
        });
    })(jQuery);
}

```

And now it semms to work again.

### Environment Information

- **Operating System**: Windoze 7
- **Grails Version:** 3.2.0
- **JDK Version:** 1.8.0_101
- **Container Version (If Applicable):** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
@jknudsen Could you submit a PR to https://github.com/grails-profiles/web ?

This is the file in question: https://github.com/grails-profiles/web/blob/master/skeleton/grails-app/assets/javascripts/application.js

**Comment by jknudsen** [comment]
Create a pull request.

[](https://github.com/grails-profiles/web/pull/2)
