### ISSUE TITLE
URL Mappings don't check for excludes

### ISSUE THREAD

**Issue by rpalcolea** [grails/grails-core#10203]
### Steps to Reproduce

1. Execute the app
2. Open in your browser http://localhost:8080/stomp/info

### Expected Behaviour

Should hit stomp and return a JSON as follows:

```json
{"entropy":-540329649,"origins":["*:*"],"cookie_needed":true,"websocket":true}
```

### Actual Behaviour

It's hitting the UrlMapping `'/**'(controller:"index")` instead of hitting the spring websockets endpoints.

I took a look at https://github.com/grails/grails-core/blob/639d7039d24031dbc1353f95b6d2c88a100da850/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/UrlMappingsHolderFactoryBean.java#L101 and I'm able to see the `excludedPatterns` array while debugging.

 I was expecting the `URLMappings` to exclude ` ["/stomp/", "/stomp/*", "/topic/*"]`

This worked on Grails `2.5.x`

### Environment Information

- **Operating System**: OSX 10.11.2 (El Capitan)
- **Grails Version:** 3.2.0 (it happens on 3.1.11 too)
- **JDK Version:** 1.8.0_101
- **Container Version (If Applicable):** Tomcat 8 (embedded one)

### Example Application

- https://github.com/rpalcolea/url-mappings-exclude 

Please take a look in https://github.com/rpalcolea/url-mappings-exclude/blob/master/grails-app/controllers/url/mappings/exclude/UrlMappings.groovy

**Comment by rpalcolea** [comment]
Hi, 

This issue happens with a brand new app using Grails 3.2.0

When I add the  plugin `compile "org.grails.plugins:grails-spring-websocket:2.3.0"` for spring websocket I'm able to see the expected result. 

As soon as I add a catch all URLMapping like `'/**'(controller:"index")` and the `excludes` property `static excludes = ["/stomp/", "/stomp/*", "/topic/*"]` it stops working. `/stomp` is taking to `IndexController` instead of the stomp endpoints.

**Comment by rpalcolea** [comment]
Hi @graemerocher 

Any suggestion to workaround this for now? :)

**Comment by graemerocher** [comment]
I imagine with a `matches` constraint on the catchall URL mapping it would work

**Comment by rpalcolea** [comment]
Thanks @graemerocher 

interesting... I'll give it a try. I thought the `matches` only worked for Variables inside it's `constraints`. Didn't know you can apply a matches to a wildcard (in this case the catch all).

Or am I missing something?

**Comment by rpalcolea** [comment]
I'm getting 500s in https://localhost.virtualphone.com/features#linkIVR

**Comment by rpalcolea** [comment]
Hi @graemerocher 

I saw that this is targeted for https://github.com/grails/grails-core/milestone/176 

Will this be included on https://github.com/grails/grails-core/milestone/177?
