### ISSUE TITLE
grails tries to download gradle even when gradle 3.0 is installed 

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10207]
Why does not grails 3.2.0 use local gradle 3.0 installed using sdkman, but instead always try to download the cradle-bin-3.0

Looks like it was not the case earlier and it happyly used the local gradle.

**Comment by graemerocher** [comment]
We're just using the tooling API from Gradle so if this worked before it is something that changedin the tooling API for Gradle

**Comment by snimavat** [comment]
is there some thing that we can do to use local gradle and still use grails console ? without grails trying to download the gradle? - (its same version, 3.0)

**Comment by snimavat** [comment]
Here' it says setting the GRAILS_GRADLE_HOME should work, but it does not seem to work - http://mrhaki.blogspot.in/2016/01/grails-goodness-changing-gradle-version.html

**Comment by graemerocher** [comment]
I will take a look.

**Comment by snimavat** [comment]
Thanks.

It would be nice if grails can detect local gradle in path, and dont force download it.
Helps when building on CI server, or when we want to manage the gradle centrally using sdkman.

For now, i just created symlink to gradle zip in .gradle/wrapper/dists/gradle-3.0-bin and it extracted and installed it.

**Comment by snimavat** [comment]
@graemerocher thanks for the quickly fixing it..  just had a suggestion, instead of always checking for the USER_HOME/.sdkman - cant we check if GRADLE_HOME is set, and use that ?

**Comment by graemerocher** [comment]
I'm not sure about that, the version of Gradle defined there may be incompatible.

**Comment by snimavat** [comment]
That could happen with ~/.sdkman/current too ... not sure if grails can programmatically check the gradle version found in GRADLE_HOME

**Comment by graemerocher** [comment]
Sure, but it is easy to switch your sdk man Gradle version, monkeying around with system properties is not so much fun.

**Comment by snimavat** [comment]
Yup, the change would work just great for me... the suggestion was to make it more flexible if possible. Anyway we always use grails/gradle using sdkman so its good for our case.

**Comment by todoubaba** [comment]
But why `GRAILS_GRADLE_HOME` do not work? see https://github.com/grails/grails-core/issues/10168

**Comment by codex22** [comment]
I do have an issue with this change, since 3.2.1 I get:

Error initializing classpath: The specified Gradle installation directory 'C:\Users\micha\.sdkman\candidates\gradle\current' is not a directory. (Use --stacktrace to see the full trace)

The path exists and links to a valid gradle version. A quick check shows that file.isDirectory() returns false. I'm not familiar with linking under Windows, but this seems to be the culprit here.

**Comment by codex22** [comment]
Ok, I realize that the symbolic link is only available inside babun (something on top of Cygwin), whereas on the Windows side it's just a regular file. I'm only using grails/gradle from a bash shell inside babun, but I guess that the JVM started is on the Windows side of things ... confusing

**Comment by codex22** [comment]
So this definitely doesn't work when using Cygwin/Babun under Windows. I had to physically create a "current" directory and copy my current gradle installation into it.

This is just a hack and will possibly break sdkman as well.

I find it unfortunate that Grails hardcodes the path to "current" (symbolic link) whereas sdkman itself sets the install directory of the current version directly (e.g. "3.1") in the PATH environment variable. At least it should not be used under Cygwin etc.

**Comment by snimavat** [comment]
@codex22 you should report a new issue for your problem, and this one is closed its not going to get attention.
