### ISSUE TITLE
WebLogic looks for "grailsDispatcherServlet-servlet.xml" when starting Grails application

### ISSUE THREAD

**Issue by leleFc** [grails/grails-core#10204]
I created a simple Grails 3 application (just only "create-app test") and when I deployed it on WebLogic 12c (configured in developement mode) I got this error: java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/grailsDispatcherServlet-servlet.xml]

### Steps to Reproduce

1. Create a simple Grails 3 application
2. Create and put the "weblogic.xml" in the /src/main/webapp/webinf" folder
3. Set to "provided" the "spring-boot-starter-tomcat" inside build.gradle
4. Create war file and put it in the "autodeploy" folder on WebLogic

### Expected Behaviour

The application starts correctly

### Actual Behaviour

WebLogic looks for a "grailsDispatcherServlet-servlet.xml" inside the "WEB-INF" folder, but it doesn't exists

### Environment Information

- **Operating System**: Windows Server 2012 R2
- **Grails Version:** 3.1.11
- **JDK Version:** 1.8.0 update 101
- **Container Version (If Applicable):** WebLogic 12c (12.2.1)

[base_domain.txt](https://github.com/grails/grails-core/files/511106/base_domain.txt)
[AdminServer.txt](https://github.com/grails/grails-core/files/511107/AdminServer.txt)
[weblogic.xml.txt](https://github.com/grails/grails-core/files/511131/weblogic.xml.txt)

**Comment by graemerocher** [comment]
Following these instructions I was able to deploy to Weblogic no problem http://stackoverflow.com/questions/25571843/problems-accessing-fresh-deploy-of-springboot-sample-app-on-weblogic12c
