### ISSUE TITLE
war produced by grails 3.2 does not start in Tomcat 8.5.5

### ISSUE THREAD

**Issue by arysin** [grails/grails-core#10208]
### Steps to Reproduce

with grails 3.2:
- grails create-app --profile=rest-api test
- run `grails war` in the folder
- copy build/libs/test-0.1.war to tomcat/webapps

### Expected Behaviour

The app would start and provide content

### Actual Behaviour

The app context is registered by tomcat but any url returns 404
Also the app is loaded much faster: war from 3.1.2 takes ~12 sec, the war from 3.2 takes 2.5 sec

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.2
- **JDK Version:** 1.8.102
- **Container Version (If Applicable):** Tomcat 8.5.5

**Comment by graemerocher** [comment]
Did you modify the `spring-boot-starter-tomcat` dependency to be `provided`?

**Comment by graemerocher** [comment]
Also please comment out 

```
provided "org.codehaus.groovy:groovy-ant"
```

**Comment by graemerocher** [comment]
Duplicates  #10196

**Comment by arysin** [comment]
Thanks, commenting out groovy-ant line helped
