### ISSUE TITLE
Domain property of type BigDecimal with minValue constraint causes precision to be ignored

### ISSUE THREAD

**Issue by magnomp** [grails/grails-core#10209]
Consider this domain:
`class Customer {

    BigDecimal someValue

    static constraints = {
        someValue minValue: 0.01
    }

    static mapping = {
        someValue precision: 18, scale: 2
    }
}`

The ddl generated for this table considers someValue precision = 19 instead of 18 which was set on mapping.
You can confirm this by checking the generated database schema or by puttin a breakpoint at org.hibernate.tool.schema.internal.SchemaCreatorImpl:314.
Although it's Hibernate code, the generation is based on values populated by grails' org.grails.orm.hibernate.cfg.GrailsDomainBinder

While one could consider this a minor issue, it might be a breaking issue depending on rdbms used. For instance, H2 does allow precision=19, while Firebird doesn't.

If you don't use the constraint, then precision=18 is considered.

If there's a techinical reason for this behaviour, then Grails should generate an exception in this case or at least a log warn

This is a Grails 3.2.0RC2 fresh project.
JDK 1.8.0_92

Sample for this: https://drive.google.com/file/d/0B46ZtLPlE4d0OWVQMWpBQi1tT00/view?usp=sharing

**Comment by rpalcolea** [comment]
The `scale` isn't a `mapping`, it is a `constraint`... More info here http://docs.grails.org/latest/ref/Constraints/scale.html

**Comment by jeffbrown** [comment]
@rpalcolea is correct.  `scale ` is a `constraint`.

Also, bug reports against 3.2.0.RC2 will just have to be revalidated against 3.2.0.  I would suggest reporting issues against 3.2.0.

**Comment by jeffbrown** [comment]
@magnomp Should this be closed or are you also seeing problems when `scale` is used as a `constraint`?

Thanks for the feedback.
