### ISSUE TITLE
Grails 3.2.0 run-command returns command not found if args provided

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#10212]
**Steps to reproduce provided**

Create a grails 3.2.0 app

`grails create-app commandtest`

Create a command object:
````
grails > create-command My
````

with source as:

````
package commandtest

import grails.dev.commands.*

class MyCommand implements GrailsApplicationCommand {

    boolean handle() {
        println getArgs()
        true
    }
}
````

### Expected Behaviour

If I execute the command with 

`./gradlew runCommand -Pargs="my 222"`

I get the args `[222] List<String>` as expected. 

### Actual Behaviour

However, I I run: 

`grails run-command my 222`

I get: 

````
Command not found for name: my 222
:runCommand FAILED
````

### Environment Information

- **Operating System**: OSX
- **Grails Version:** 3.2.0
- **JDK Version:** 1.8

**Comment by jeffbrown** [comment]
It looks like the problem may only happen when args are provided.  I think this works:

    grails run-command my

And this does not:

    grails run-command my 42

**Comment by sdelamo** [comment]
Yes. With no args it works
