### ISSUE TITLE
JSON views link creation

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#10216]
Hi!

In views and controllers you can create with `g.link` an anchor tag (http://docs.grails.org/latest/ref/Tags/link.html) and with `g.createLink` the link itself (http://docs.grails.org/latest/ref/Tags/createLink)

but in JSON views `g.link` create the link instead of the anchor tag and `g.createLink` is not working (http://views.grails.org/latest/#_creating_links).

This is a little bit confusing and not consistent. Is it possible to change this?

best regards
Andreas

**Comment by graemerocher** [comment]
I don't understand, why would you want an anchor tag in a JSON view?

**Comment by andreasschiestl** [comment]
I don't want a anchor tag in a JSON view. But it is confusing if things with the same name do something other. At least g.createLink should be added that this works the same way as in controllers, gsp-views and json-views.

**Comment by graemerocher** [comment]
So you want 2 methods that do the same thing?

**Comment by andreasschiestl** [comment]
If two methods with the same name are a good solution is your decision. I only want to point out that the naming is different and maybe confuse somebody else like me in the first moment :) Maybe a note that this has nothing todo view the taglib is also sufficient.

I also noticed today that thing like g.formatNumber and g.formatDate also not working. Or did I miss something?

**Comment by jeffbrown** [comment]
I kind of see where the confusion would come from, but the current behavior seems reasonable to me.  In a JSON view having `g.link` create a url without an anchor tag makes sense, but is inconsistent with the way things work in a GSP.  I think they are 2 different contexts and there shouldn't be much confusion.  I suppose we could also provide `g.createLink` in JSON views and just have it call `g.link`, but that doesn't really add much value.

**Comment by jeffbrown** [comment]
In any case, this request is probably better suited for https://github.com/grails/grails-views/issues.
