### ISSUE TITLE
Where do you put reuseable custom helper classes?

### ISSUE THREAD

**Issue by BardiaAfshin** [grails/grails-core#10214]
I have a method that I would like to share across multiple controllers, I can put this in a class named say... "MyCutstomHelperClass", what are the best practices or convention used to store this class? What's the recommended path?

**Comment by graemerocher** [comment]
Generally you should put such functionality in services. Please don't use the issue tracker for questions. Thanks.

For questions please try Slack (https://grails.signup.team)  or StackOverflow (http://stackoverflow.com/tags/grails)
