### ISSUE TITLE
pry for grails?

### ISSUE THREAD

**Issue by BardiaAfshin** [grails/grails-core#10215]
There's a very handy gem in Rails called pry, is there such a feature for Grails, which would allow you to pause the execution of your program in order to evaluate console execution?

link to pry for Rails
https://github.com/pry/pry

**Comment by rpalcolea** [comment]
First at all I think pry is a Ruby gem which could be use outside of Rails. Are you trying to debug grails apps? If that's the case you can run a grails app on debug mode as follows:

```
grails run-app --debug-jvm
```

You will notice the following in the output:

```
Listening for transport dt_socket at address: 5005
```

## Debug with IntelliJ

* Create a "Remote" configuration. On the "Run/Debug" dialog, click the + symbol and select "Remote" from the list. Name it "Debug" and save.
* Select your "Run" config from the config dropdown at the top and then click the green arrow to run the app. Monitor the console output until you see the message  Listening for transport dt_socket at address: 5005.
* Select the remote debug profile you created in step 2 and click the debug button. In a few moments the console output will say  Grails application running at http://localhost:8080 in environment: development.

## Debug outside of the IDE

You can debug grails applications outside of an IDE with the `jdb` debugger that comes with the JDK.

```
jdb -attach localhost:5005
```

I've no experience on using the `jdb` but you can take a look on the docs: http://docs.oracle.com/javase/7/docs/technotes/tools/windows/jdb.html

**Comment by rpalcolea** [comment]
I forgot something: I suggest you to ask these type of questions in the slack channel or in stackoverflow with the grails tag. The purpose of the GitHub issues is report unexpected behavior / potential bugs
