### ISSUE TITLE
Grails 3.0 Proxy cannot synchronize I/O data

### ISSUE THREAD

**Issue by testorubel** [grails/grails-core#10218]
**Task List**

Create endpoint in API Application with Roles. Create service in proxy to check roles that can access that endpoint and reject early. Cannot do it without duplication of data.

Example: all annotations create bindings at the controllers and resource. Cannot synchronize this data with proxy or resource for distributed services; creates cross cutting concern

**Expected Behaviour**

Data must be duplicated in the proxy but then cannot be synchronized. Similarly with all services and all data related to communication.

Tell us what should happen:
Data should be able to be synchronized across all services, reloaded and pushed to all services from a SVOT. That SVOT would be where the request/response meet thus providing all data for the 'single version of truth'

**Actual Behaviour**

Data is duplicated. Is not synchronized. Services fall into different states. This creates issues with:

Synchronization
Real-time constraints
Error detection and correction
Product features
Memory management
Data validation
Persistence
Transaction processing
Internationalization and localization which includes Language localisation
Information security
Caching
Logging
Monitoring
Business rules
Code mobility
Domain-specific optimizations

**Environment Information**

Operating System: Ubuntu Linux
Grails Version: 3.1
JDK Version: 8
Container Version (If Applicable): embedded Tomcat

**Comment by jeffbrown** [comment]
The following 3 issues appear to have the exact same description and the description does not make sense.

https://github.com/grails/grails-core/issues/10217
https://github.com/grails/grails-core/issues/10218
https://github.com/grails/grails-core/issues/10219
