### ISSUE TITLE
Option to fix variable name when using controller's respond method

### ISSUE THREAD

**Issue by gregopet** [grails/grails-core#10229]
The way Grails auto-generates the name of the variable passed into the model by the controllers `render` method is very confusing and easily leads to bugs. Some conventions are especially troublesome, for example 'emptyList' instead of 'bookList'. I propose a config variable that would force the model variable to always be the same.

In `application.yml`: `grails.views.respondVariableName: bob`

In `BookController.groovy`: `respond books`

In `index.gsp`: `<% assert bob instanceof List<Book> %>`

I always start my GSPs with an assert of the expected data model (GSON files have this by default now) and I still just lost another 15 minutes to a naming bug. I'd be happy to try to implement this myself, together with unit tests and documentation, if the Grails team is open to considering this feature.

**Comment by graemerocher** [comment]
I don't understand how the model variable name always being the same is useful.

**Comment by gregopet** [comment]
1. the first obvious difference is between `bookList` and `emptyCollection`
2. In case of refactoring I don't want my views to start failing because I changed a class name
3. If I pass more than one type of object (say inherited types) in a list, my variable name now depends on the exact ordering of the list 
4. Same thing with `Map`, only worse because most maps are unordered and/or tend to contain nulls: I currently have an `Optional<Map<..>>` in my production code because then I know my variable will be named `optional`
5. The documentation is not easily discoverable, I currently keep the `resolveModelVariableName` method in a file so I can look it up quickly

Other than that I work with Grails a lot and have a bad feeling whenever using `respond`.. very subjective I know, but true in my case never the less..

**Comment by graemerocher** [comment]
1. Shouldn't matter because you can use the Groovy truth `[] == null`
2. This doesn't seem like the right solution to refactoring
3. This I agree with and sounds like a bug and a worthy issue report, we should use the root super class
4. The behaviour of respond with `Map` I agree with too, but in this case the behaviour should be that the map becomes the model
5. I have tried to improve this with:

https://github.com/grails/grails-doc/commit/13cacbdce73ca431619362634321ba5f0be570a1

So yes in total I am an agreement that some behaviour is non-obvious and we either need to improve or document that, but I don't see how using a fixed model name for all response types is the solution to that.

**Comment by graemerocher** [comment]
Related to https://github.com/grails/grails-views/issues/66

**Comment by graemerocher** [comment]
For `Map` if a `Map` is passed to respond it should be the model. That behavior us defined in:

https://github.com/grails/grails-core/blob/master/grails-plugin-rest/src/main/groovy/org/grails/plugins/web/rest/render/html/DefaultHtmlRenderer.groovy#L84

And for JSON views

https://github.com/grails/grails-views/blob/1.1.x/core/src/main/groovy/grails/views/mvc/renderer/DefaultViewRenderer.groovy#L96

If you are not seeing this behavior then that is a bug

**Comment by gregopet** [comment]
I see - well responding with a map absolutely works for me, and the extra documentation will be very helpful as well, I for one certainly didn't know maps could be used like that (it fact, not expecting it probably confused me)  :+1:

I do think `emptyCollection` and `emptyMap` should be included in the table explaining the naming convention though, some people check a collection's `size()` instead of using the Groovy truth and that would fail (or, like me, use `assert` to 'statically type' their GSP files).

BTW, thanks for all your work, I've been using grails for exactly 7 years now (I checked my first Grails project out of curiosity and today's an anniversary of that `First commit!` :smile: )

**Comment by graemerocher** [comment]
I'm going to re-open because the issue you pointed out related to inheritance is still outstanding and so is documenting the behaviour of empty collections.

**Comment by gregopet** [comment]
The inheritance problem seems very hard to solve because we seem to be limited by Java's type erasure on one hand and the unpredictable contents of a collection on the other (it could sometimes only contain the child type). Plus scanning a whole collection trying to determine the class used seems very inefficient in any case. Perhaps simply documenting this case (and suggesting the `Map` alternative) would be best?

If I can be of any help with the documentation, let me know!

**Comment by graemerocher** [comment]
Ok yes you are right, seems reasonable. I will leave this open until I have further refined the documentation.
