### ISSUE TITLE
Validate on nested command object ignores static constraints

### ISSUE THREAD

**Issue by a200612** [grails/grails-core#10222]
```
class SomeController {
  
  def updatePerson(PersonCommand cmd) {
    def person = new Person(cmd.properties)
    person.address = new Address(street: "bar")
    person.address.validate()
  }
  
}

@grails.validation.Validateable
class PersonCommand {
  String name
  AddressCommand address
}

@grails.validation.Validateable
class AddressCommand {
  String street
  String city

  static constraints = {
    city nullable: true
  }
}
```

ERROR com.SomeController - person.address.errors=grails.validation.ValidationErrors: 1 errors
Field error in object 'com.AddressCommand' on field 'city': rejected value [null]; codes []

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md
