### ISSUE TITLE
Error loading App with grails 3.2.1

### ISSUE THREAD

**Issue by miguelabautista** [grails/grails-core#10235]
I am getting this Exception only for grails 3.2.1. before I was working with 3.2.0.

[Error.txt](https://github.com/grails/grails-core/files/536608/Error.txt)

my dependencies:

[dependencies.txt](https://github.com/grails/grails-core/files/536620/dependencies.txt)

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8.0_91

**Comment by graemerocher** [comment]
Could you provide an example that reproduces the issue. I copied your dependencies from the dependencies.txt file into a new app and there was no exception starting the app.

**Comment by AlexKovynev** [comment]
I am see something similar. How can i write a tag library? If i locate it to package i receive
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

but all work else 404 without errors in console.
