### ISSUE TITLE
3.2.1 ERROR grails.boot.config.tools.ClassPathScanner

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#10236]
It seems all fine but what is it (after upgrade from 3.2.0 to 3.2.1 )?

How can i determine which class? 

ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

**Comment by AlexKovynev** [comment]
I found, false alert, bootstrap

**Comment by AlexKovynev** [comment]
Please exclude Tag libraries from error message in ClassPathScanner.groovy.

**Comment by graemerocher** [comment]
No, all sources should be in a package
