### ISSUE TITLE
Rendering json using render method fails testing

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#10232]
Following the exact wording of the docs here:
http://docs.grails.org/latest/guide/single.html#unitTestingControllers

The sample app includes snippets taken directly from this document.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller action that renders json using `render(contentType: 'application/json') {...}`
2. Test that controller using a unit test specification, testing `response.json` as mentioned in the official docs
3. Observe the result

### Expected Behaviour

`response.json` contains the fields specified in the closure passed to `render`

### Actual Behaviour

The app throws a groovy.lang.MissingPropertyException, causing the test to fail.

### Environment Information

- **Operating System**: Ubuntu MATE 16.10
- **Grails Version:** 3.1.12
- **JDK Version:** OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

### Example Application

https://github.com/joemccall86/render-json-test

**Comment by jeffbrown** [comment]
I don't think this has anything to do with testing.  I think that controller action will fail with the same error even in the running application.

**Comment by jeffbrown** [comment]
I think the docs may be incorrect in describing how to use the builder.  Will investigate.  I think this would work:

            render(contentType:"application/json") {
                book "Great"
            }

**Comment by jeffbrown** [comment]
At https://github.com/grails/grails-doc/blob/4808ff2289406ebb4b53b072c057785424e6ac82/src/en/guide/theWebLayer/controllers/moreOnJSONBuilder.gdoc#L18-L20 is that supposed to be `hello = 'world'` or `hello 'world'`?

**Comment by jeffbrown** [comment]
See https://github.com/grails/grails-core/blob/991ef0074b2eecfabaf4c770084ebb9bb1bfcd64/grails-test-suite-uber/src/test/groovy/grails/test/mixin/ControllerUnitTestMixinTests.groovy#L513-L517

**Comment by joemccall86** [comment]
Understood. It sounds like the resolution on this ticket should be updating the docs. I'll set up a PR referencing this issue.
