### ISSUE TITLE
Grails 3.2.0 GORM does not create sequences for PostgreSQL

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#10234]
### Example

```java
class Book {
    String title

    static constraints = {
    }

    static mapping = {
        version false
        id generator:'sequence', params:[sequence:'book_seq']

        id index:'book_id_idx'
    }
}
```

### Steps to Reproduce

1. Start the app
2. Login with psql
3. list sequences with \ds

### Expected Behaviour

A sequence should be created,this works in Grails 3.1.x

### Actual Behaviour

![pgadmin4](https://i.imgur.com/43RVHuD.png "pgadmin4")

### Environment Information

- **Operating System**: OS X, Linux
- **Grails Version:** 3.2.0
- **JDK Version:** 1.8.0_92

### Example Application

- https://github.com/olavgg/grails-sequence-bug

**Comment by burtbeckwith** [comment]
Unrelated, but all you're doing by creating an index on the primary key is wasting disk space and cpu cycles. Postgres (and every other database) already handles checking PK uniqueness, indexing for fast lookups, etc.

**Comment by olavgg** [comment]
Thanks @burtbeckwith . I didn't know that. I see that pgadmin will not show that index, but psql will.

**Comment by Guigoz** [comment]
Same problem here with Grails 3 / Postgresql.
Grails doesn't use my created sequences and always uses hibernate_sequence instead

**Comment by graemerocher** [comment]
Seems to only impact GORM for Hibernate 5. Something changed in Hibernate 5 internals that broke this. I am investigating...

**Comment by graemerocher** [comment]
Basically the parameter has been renamed from `sequence` to `sequence_name` in Hibernate 5. Changing the following:

```groovy
id generator:'sequence', params:[sequence:'book_seq']
```

To

```groovy
id generator:'sequence', params:[sequence_name:'book_seq']
```

I have implemented a fix to improve backwards compatibility.

**Comment by cbmarcum** [comment]
I have found that in Grails 4.0.5 with Hibernate5 7.0.4  if I create a global setting in conf/application.groovy like:
`grails.gorm.default.mapping = { id generator: 'identity' }`
That I get a sequence per table named <table-name>_id_seq in PostgreSQL. I'm using v.12.
No id mapping in the domains at all.
Not sure if it matters but I manually create the database (no tables) and use dbCreate: update.
