### ISSUE TITLE
Grails 3.1.6 with MongoDB 5.0.5-withDatabase with authentication does not work

### ISSUE THREAD

**Issue by brittma** [grails/grails-core#10237]
When upgrading from Grails 2.4.4 using the MongoDB plugin 3.0.2 to Grails 3.1.6 using the MongoDB plugin version 5.0.5 the withDatabase closure no longer works when authentication is required for the database and the following authentication error is received:

com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized for query on itemtest.item' on server testdb3:27017
	at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:102)

The application.groovy is configured as follows:
grails {
                mongodb {
                     replicaSet = ["testdb3", "test2db3"]
                     port = 27017
                     username = "xxxxxx"
                     password = "xxxxxx"
                     databaseName = "testdb"
                     databaseName_item = "itemtest"
              }
        }
The code is as follows:
Item.withDatabase(grailsApplication.config.grails.mongodb["databaseName_item"]) {
                    //query
                    c.list().iterator() //receive error
                }
        })

After debugging, in MongoClientFactoryBean.afterPropertiesSet, only one MongoCredential is created with the default database:
if (username != null && password != null) {
            credentials.add(MongoCredential.createCredential(username, database,  password.toCharArray()));
}
And then the MongoClient is created using that one MongoCredential:
mongo = new MongoClient(replicaSetSeeds, credentials, mongoOptions);

When withDatabase is called, the current MongoClient is retrieved which only had credentials for the default database, not the one we are switching too, thus the authentication error occurs.  

It seems that when creating the MongoClient, a MongoCredential should be created for each database listed in the application.groovy file so that when you switch databases with the withDatabase closure the new database is already authenticated.

**Comment by graemerocher** [comment]
Please report to https://github.com/grails/gorm-mongodb/issues
