### ISSUE TITLE
Angular 2 profile build and docs improvement

### ISSUE THREAD

**Issue by musketyr** [grails/grails-core#10239]
### Steps to Reproduce

1. create new application with Angular 2 profile

### Expected Behaviour

1. The docs should mention that the Node and NPM is installed in the proper versions itself
2. E2E tests should run the server automatically and kill it after the task is finished

### Actual Behaviour

1. The docs says that you need to have Node and NPM installed already
2. Running the server is not handled by the integration test task

### Environment Information

- **Operating System**: any
- **Grails Version:** 3.2.1
- **JDK Version:** any

### Example Application

This is a very simple build script I've actually created couple of days ago to achieve something very similar with the ng cli you're doing. Maybe something between your and my script is the ideal one:

```
import com.wiredforcode.gradle.spawn.*

buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
    maven { url 'http://dl.bintray.com/vermeulen-mp/gradle-plugins' }
  }

  dependencies {
    classpath "com.moowork.gradle:gradle-node-plugin:0.13"
    classpath 'com.wiredforcode:gradle-spawn-plugin:0.6.0'
  }
}

apply plugin: 'com.moowork.node'
apply plugin: 'com.wiredforcode.spawn'

node {
  // Version of node to use.
  version = '4.6.0'

  // Version of npm to use.
  npmVersion = '3.10.9'

  // If true, it will download node using above parameters.
  // If false, it will try to use globally installed node.
  download = true
}

task startNgServe(type: SpawnProcessTask, dependsOn: 'npmInstall') {
  command "node_modules/angular-cli/bin/ng serve"
  ready 'webpack: bundle is now VALID.'
}

task stopNgServe(type: KillProcessTask)

task ngLint(type: Exec, dependsOn: 'npmInstall') {
  commandLine 'node_modules/angular-cli/bin/ng', 'lint'
}

task ngTest(type: Exec, dependsOn: 'npmInstall') {
  commandLine 'node_modules/angular-cli/bin/ng', 'test', '--watch=false'
}

task ngServe(type: Exec, dependsOn: 'npmInstall') {
  commandLine 'node_modules/angular-cli/bin/ng', 'serve'
}

task ngE2E(type: Exec, dependsOn: ['npmInstall', 'startNgServe']) {
  commandLine 'node_modules/angular-cli/bin/ng', 'e2e'
}

ngE2E.finalizedBy stopNgServe

test.dependsOn('ngTest')

check.dependsOn('ngLint')
```

**Comment by jameskleeh** [comment]
Can you point me to where it says Node and NPM are required? The profile instructions say "To get started with this profile, you will need to install the Angular CLI (npm install -g angular-cli). Currently the CLI requires Node 4.x.x and NPM 3.x.x. https://github.com/angular/angular-cli" and the docs say "you should have Node, NPM, and the Angular CLI installed."

Are you saying the e2e tests are being run in watch mode and not stopping?

**Comment by musketyr** [comment]
Maybe I'm misreading it but when I go to http://docs.grails.org/latest/guide/webServices.html#angular2Profile there is following

```
Prerequisites
To use this profile, you should have Node, NPM, and the Angular CLI installed. Node should be at least version 5 and NPM should be at least version 3.
```

From this I would acknowledge that I need to install these manually.

I actually couldn't run the E2E thanks to  #10240

**Comment by musketyr** [comment]
but no the E2E tests are not running in watch mode (if they work)

**Comment by musketyr** [comment]
what I wanted to say with the E2E tests was that they should start the webserver before running the tests themselves and than kill it when the tests are finished (similar how Geb integration tests first starts the Grails app and then kills it after that)

**Comment by musketyr** [comment]
also the Gradle script I've pasted was working with version 2.14.1. I'm trying to do same with the 3.1 but it looks like something has changed with how the working dir is evaluated.

**Comment by jameskleeh** [comment]
@musketyr I don't think the e2e process should start the grails server. One of the reasons is that some people don't use the real backend while doing their tests, instead a mock one is used. Thanks for your feedback regarding the wording on the docs, however I prefer to keep it as is.

**Comment by musketyr** [comment]
same do I. that's the reason why I run **webpack** server with `ng serve` not the grails backend.

now when we're on the same page it would be nice to reopen the issue again 😄 (but the choice is on your side of course).
