### ISSUE TITLE
3.2.1 Tag Library in package produce 404

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#10245]
Error message is clean.  If I return from package all ok.
Maybe there is some way to find out what's going on? On the test projects can not repeat unfortunately only the production project falls.

**Comment by jeffbrown** [comment]
I am not sure what the issue is that you are reporting.  It looks like you are saying that if a tag library is in a package that somehow results in a  404.  I can't reproduce that.

See the project at https://github.com/jeffbrown/issue10245.

The tag lib at https://github.com/jeffbrown/issue10245/blob/master/grails-app/taglib/com/demo/CustomTagLib.groovy is in a package and is used from https://github.com/jeffbrown/issue10245/blob/d26b756e12a5d82b11e8ec3a02d241d23ffd5e32/grails-app/views/index.gsp#L59 and that appears to work.

Can you elaborate on whatever problem you are experiencing?

Thank you for the feedback.

**Comment by AlexKovynev** [comment]
Jeff i confirm it in my message. New project with tag library working as expecting. In which object and fields i can find something detail about problem? I upgrade my project from 1.1 to 3.2 incrementally all this time, maybe i have some old code. Last error.gsp from 3.2 give me 

    An error has occurred
    Exception:
    Message: No message available
    Path: /

**Comment by jeffbrown** [comment]
@AlexKovynev I expect that there may be something wrong in the project but without an example which demonstrates the problem, it will be very difficult to diagnose.

**Comment by jeffbrown** [comment]
Confirm that the package name matches the directory structure under `grails-app/taglib/`.

**Comment by AlexKovynev** [comment]
I understood, pity. Return tag library as was. Be awaiting miracle in future versions.:)

**Comment by jeffbrown** [comment]
If you can show the source code for the tag library in question, maybe there will be hint there that could be helpful.

**Comment by AlexKovynev** [comment]
Something i can find, i change gsp on fly (append static defaultEncodeAs = [taglib:'html'] to code
) and see errors in console. I loose transaction. withTransaction will help partially. I can see my layout. Now i blind again. How can i set transaction globally for lib? I use some my services in code, maybe exception deeply.

**Comment by graemerocher** [comment]
Is your tag library in a different package to your application? If so you will need to override `Application.packageNames()` and return the packages or move your tag library into the same package or a subpackage within of your Application classes' package

**Comment by AlexKovynev** [comment]
Unfortunately no. Package is identical.
The number one problem is that when throwing the library in the package I can not work with the database without creating a new session or transaction. It is well conceived? 

For second problem later create issue. Try to reproduce in small project. g:include hide exception messages.

**Comment by graemerocher** [comment]
We will need an example that reproduces your issue, otherwise no progress can be made on this issue unfortunately.

**Comment by AlexKovynev** [comment]
Well, the last question, can help? there is a chance to learn how and why I get to 404?

**Comment by AlexKovynev** [comment]
Funny it was not tag lib, tag lib was a last class without package besides UrlMappings on which classloader was not alert.  If i move tag lib to package UrlMappings silently stop working:)
