### ISSUE TITLE
@Rollback in integration testing doesn't rollback

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#10262]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run integration test with @Rollback annotation.
2. Observe that database is not rollbacked after Spec execution. 

### Expected Behaviour

It should rollback all changes after each Spec method execution.

### Actual Behaviour

It doesn't rollback database changes.

### Environment Information

- **Operating System**: OS X 10.11.6
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8.0_77

### Example Application

- https://github.com/kuceram/test-rollback

**Comment by graemerocher** [comment]
`@Rollback` only impacts changes within the test method. By using a REST client you are sending requests to the server which run the changes in a completely different thread, thus the same transaction management doesn't apply

**Comment by kuceram** [comment]
I see, I was not sure about that. Maybe documentation can mention that. :-)
