### ISSUE TITLE
Grails 3.2.1 Angular2 profile fail with  Security Authentication failed: No Session found for current thread

### ISSUE THREAD

**Issue by xmlking** [grails/grails-core#10261]
Created  fresh **Grails** with **Angular2** profile. Getting following error when tried to invoke */api/login* 

The same setup works when using with **Mongo DB** but failed when using H2/hibernate5

`grails create-app orangedollar --profile rest-api --features  mongodb,json-views,security` **works**
 `grails create-app orangedollar --profile angular2 -features hibernate5,json-views,security` **fail**

Root Cause 
`DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Authentication failed: No Session found for current thread`

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `grails create-app orangedollar --profile angular2 -features hibernate5,json-views,security`
2. `curl -i -H "Content-Type: application/json" --data '{"username":"basic3","password":"basic123"}' 0:8080/api/login`
 

### Expected Behaviour

Should return JWT

### Actual Behaviour

Stacktrace 
```
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/assets/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/**/js/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/**/css/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/**/images/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/**/favicon.ico'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/api/guest/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/api/**'
DEBUG org.springframework.security.web.FilterChainProxy - /api/login at position 1 of 7 in additional filter chain; firing Filter: 'SecurityRequestHolderFilter'
DEBUG org.springframework.security.web.FilterChainProxy - /api/login at position 2 of 7 in additional filter chain; firing Filter: 'MutableLogoutFilter'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/login'; against '/logoff'
DEBUG org.springframework.security.web.FilterChainProxy - /api/login at position 3 of 7 in additional filter chain; firing Filter: 'RestAuthenticationFilter'
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Actual URI is /api/login; endpoint URL is /api/login
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Applying authentication filter to this request
DEBUG grails.plugin.springsecurity.rest.credentials.DefaultJsonPayloadCredentialsExtractor - Extracted credentials from JSON payload. Username: admin, password: [PROTECTED]
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Trying to authenticate the request
INFO org.springframework.security.core.SpringSecurityCoreVersion - You are running with Spring Security Core 4.1.3.RELEASE
DEBUG org.springframework.security.authentication.ProviderManager - Authentication attempt using org.springframework.security.authentication.dao.DaoAuthenticationProvider
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Authentication failed: No Session found for current thread
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - Looking for bearer token in Authorization header, query string or Form-Encoded body parameter
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - No token found
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - Token: null
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenAuthenticationFailureHandler - Sending status code 401 and header WWW-Authenticate: Bearer
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Not authenticated. Rest authentication token not generated.
``` 

### Environment Information

- **Operating System**: MacOS
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8

### Example Application

https://github.com/xmlking/grails321-angular2-security-issue

**Comment by jameskleeh** [comment]
You have 2 variables here (the profile and the database):

`grails create-app orangedollar --profile rest-api --features mongodb,json-views,security`
`grails create-app orangedollar --profile angular2 -features hibernate5,json-views,security`

Does this work as you would expect?
`grails create-app orangedollar --profile rest-api --features hibernate5,json-views,security`

**Comment by xmlking** [comment]
sorry, I forgot to uncomment `User.withTransaction { status ->` in my [CustomUserDetailsService](https://github.com/xmlking/grails321-angular2-security-issue/blob/master/server/src/main/groovy/orangedollar/CustomUserDetailsService.groovy#L24) when I switiched from MongoDB to Hibernate/H2 which caused this issue. Please close this issue.
