### ISSUE TITLE
Using executeQuery on domain instance results in UnsupportedOperationException within a unit test (Grails 3.2)

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10265]
The following test throws an `UnsupportedOperationException` when using `executeQuery` within a unit test.

```
java.lang.UnsupportedOperationException: String-based queries like [executeQuery] are currently not supported in this implementation of GORM. Use criteria instead.
	at org.grails.datastore.gorm.GormStaticApi.unsupported(GormStaticApi.groovy:1124)
	at org.grails.datastore.gorm.GormStaticApi.executeQuery(GormStaticApi.groovy:1028)
	at org.grails.datastore.gorm.GormStaticApi.executeQuery(GormStaticApi.groovy:1024)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.executeQuery(GormEntity.groovy:1030)
	at grails.issues.Season.between(Season.groovy:45)
	at grails.issues.SeasonSpec.Find all season between #aDate and #bDate (Cannot executeQuery)(SeasonSpec.groovy:43)
```

The following [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonSpec.groovy#L34) reproduces the reported issue.

### Steps to Reproduce

1. Run this [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonSpec.groovy#L34) to reproduce the problem

### Expected Behaviour

Test should run without exception

### Actual Behaviour

UnsupportedOperationException gets thrown.

### Environment Information

- **Operating System**: macOS Sierra
- **Grails Version:** Grails 3.2.1
- **JDK Version:** 1.8

### Example Application

- [Example application](https://github.com/saw303/grails-issues/)

**Comment by graemerocher** [comment]
You had already reported this issue in https://github.com/grails/grails-core/issues/10242

Is there is a reason you opened it again?

**Comment by saw303** [comment]
Yes there ist. Issue #10242 did describe a simple [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/IndividualPersonSpec.groovy#L14). This one is fixed with Grails 3.2.1

With Grails 3.2.1 I run into a problem with this [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/SeasonSpec.groovy#L34) that I might have missed in Grails 3.2.0. The test uses `@Unroll` and a Spock data table in a `where` section.

**Comment by graemerocher** [comment]
https://github.com/grails/grails-core/commit/6c64326a712960f68456144e2bf97c60ed040161

Fixes this issue. If you want to verify just change `grailsVersion` to `3.2.2.BUILD-SNAPSHOT` in your `gradle.properties` and do `gradle clean test`

**Comment by saw303** [comment]
Perfect. That does the job!

**Comment by fabiankoebel** [comment]
Is this still present in grails v3.2.8? I'm currently facing that issue in the mentioned grails version.

**Comment by beechovsky** [comment]
I'm seeing this issue in v3.3.10 as well. Not extending HibernateSpec, extending Specification.
