### ISSUE TITLE
Unit testing transactional controller fails due to missing transaction manager

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10266]
Within a unit test I am testing a controller that is annotated with `@Transactional`. The following [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/BecomeMemberControllerSpec.groovy#L10) fails in Grails 3.2.0 and 3.2.1.

```
java.lang.IllegalStateException: No transactionManager was specified. Using @Transactional or @Rollback requires a valid configured transaction manager. If you are running in a unit test ensure the test has been properly configured and that you run the test suite not an individual test method.

	at grails.transaction.GrailsTransactionTemplate.<init>(GrailsTransactionTemplate.groovy:60)
	at grails.issues.BecomeMemberControllerSpec.Apply for a new membership with one season ticket(BecomeMemberControllerSpec.groovy:71)
```
### Steps to Reproduce

1. Run [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/BecomeMemberControllerSpec.groovy#L10)

### Expected Behaviour

Test should not fail

### Actual Behaviour

Test fails

### Environment Information

- **Operating System**: macOS Sierra
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8

### Example Application

- [Example Application](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/BecomeMemberControllerSpec.groovy#L10)

**Comment by graemerocher** [comment]
See the documentation on the subject https://github.com/grails/grails-doc/commit/d3ea48fd539eef33a83383150da220af4951eeee#diff-981956ea072b26685e05c26e5509487dR451
