### ISSUE TITLE
flyway integration does not work

### ISSUE THREAD

**Issue by gregopet** [grails/grails-core#10272]
The Flyway integration does not work automatically the way it should according to the manual. Besides installing the Flyway dependency (`compile "org.flywaydb:flyway-core:4.0.3"`) I had to put the following into `resources.groovy` to get it working under Grails 3.2.1 (most of it came from [this](http://krisrichardson.com/flyway-with-grails-3/) blog post):

	if (grailsApplication.config?.flyway?.enabled != false) {
		flyway(Flyway) { bean ->
			bean.initMethod = 'migrate'
			dataSource = ref('dataSource')
			baselineVersionAsString = "1"
			baselineOnMigrate = true
			cleanDisabled = true
			locations = "classpath:db/migrations"
		}

		def sessionFactoryBeanDef = getBeanDefinition('sessionFactory')
		if (sessionFactoryBeanDef) {
			// make it depend on flyway
			sessionFactoryBeanDef.dependsOn = ['flyway'] as String[]
		}
	}
I also had to put the migrations into the `conf` folder or they wouldn't get found.

I tried wiring Spring Boot's `FlywayAutoConfiguration` via `resources.groovy` but it failed resolving the `DataSource` using its `ObjectProvider<DataSource>` so that way didn't work (it would enable me to configure Flyway using `application.yml` among other things).

**Comment by graemerocher** [comment]
I didn't know we had documented flyway support in the manual. Can you point me to where this is documented? As far as I'm aware no official support exists

**Comment by gregopet** [comment]
Huh, you're right, the section is not present anymore in the 3.2 docs, I only found it for the 3.1 branch: http://docs.grails.org/3.1.12/guide/conf.html#automaticDatabaseMigration 

I do remember having problems in that version as well, but I'll double check and open a new issue. Sorry for the noise, then!

**Comment by gregopet** [comment]
No, wait, I'm going blind apparently, it's still in the docs: http://docs.grails.org/3.2.1/guide/conf.html#automaticDatabaseMigration

**Comment by graemerocher** [comment]
I think the reason it doesn't work is because by default we disable `DataSourceAutoConfiguration` from Spring Boot since we need control over the datasource in order to support GORM and multiple data sources.

**Comment by gregopet** [comment]
What would be the best way to tackle this? Trick Spring Boot into somehow still activating Flyway (and Liquibase I presume)? Delegate database migration back to plugins? Or simply update the the documentation, with maybe an example on how people can do this themselves?

**Comment by graemerocher** [comment]
The plugin would be minimal, and there already seems to be one http://plugins.grails.org/plugin/org.grails.plugins:grails-flyway

Seems like a documentation issue to me.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-doc/commit/1fa8756c381439a2d46ab87333897bcc411d1039
