### ISSUE TITLE
2.5.5 default error handler may pass exception text unencoded (XSS vulnerability)

### ISSUE THREAD

**Issue by brycechasm** [grails/grails-core#10277]
**Steps to Reproduce**
1. create a controller action that will throw an exception: `def index() { throw Exception('hi')}`
2. reference a user-supplied value in the code for error.gsp:
   `<g:message code="default.error" locale="${params.locale}" />`
3. run the app in prod mode: `grails prod run-app`
4. Pass a parameter to that controller action with some arbitrary html code:
   `http://localhost:8080/defaultXSS/simple/index?locale="<script>alert(1);</script>`

**Expected Behavior**

Any error text should be be escaped so that it's rendered literally:

> Error 500 - Internal Server Error.
> Error processing GroovyPageView: Error executing tag &lt;g:message&gt;: Locale part ""&lt;script&gt;alert(1);&lt;/script&gt;" contains invalid characters`

**Actual Behaviour**

Observe that the value from the parameter is included verbatim into the html output so you get:

> Error 500 - Internal Server Error.
> Error processing GroovyPageView: Error executing tag : Locale part """ contains invalid characters

An exception is thrown as follows:

> | Error 2016-10-27 00:32:55,218 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [GET] /defaultXSS/simple/index
> Locale part ""<script>alert(1);</script>" contains invalid characters. Stacktrace follows:
> Message: Error processing GroovyPageView: Error executing tag <g:message>: Locale part ""<script>alert(1);</script>" contains invalid characters
>    Line | Method
> ->>  528 | doFilter  in /home/bnichols/defaultXSS/grails-app/views/error.gsp
> ---
> 
> Caused by GrailsTagException: Error executing tag <g:message>: Locale part ""<script>alert(1);</script>" contains invalid characters
> ->>   15 | doCall    in /home/bnichols/defaultXSS/grails-app/views/error.gsp
> ---
> 
> Caused by IllegalArgumentException: Locale part ""<script>alert(1);</script>" contains invalid characters
> ->>   48 | doCall    in home_bnichols_defaultXSS_grails_app_views_error_gsp$_run_closure2
> ---
> 
> |     53 | run       in home_bnichols_defaultXSS_grails_app_views_error_gsp
> |    198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
> |     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
> |   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
> |    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
> ^    745 | run . . . in java.lang.Thread
> | Error 2016-10-27 00:32:55,232 [http-bio-8080-exec-4] ERROR [/defaultXSS].[grails]  - Servlet.service() for servlet grails threw exception`

Additionally, a javascript alert pops up with the message "1".  This indicates a XSS attack is possible in these circumstances.
### Environment Information
- **Operating System**: Linux RHEL 6.8
- **Grails Version**: 2.5.5
- **JDK Version**: 1.8.0_92
- **Container Version**: tomcat 7.0.57
### Example Application
- https://github.com/brycechasm/defaultXSS

**Comment by ColinHarrington** [comment]
I'm getting this HTML back on a sample app.
```
<HTML>
<HEAD>
<TITLE>Error 500 - Internal Server Error</TITLE>
<BODY>
<H2>Error 500 - Internal Server Error.</H2>
Error processing GroovyPageView: Error executing tag <g:message>: Locale part ""<script>alert(1);</script>" contains invalid characters<BR/>
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
<!-- Padding for IE                  -->
</BODY>
</HTML>
````

Basically it looks like the [Exception's message isn't properly escaped.](
https://github.com/grails/grails-core/blob/2.5.x/grails-web/src/main/groovy/org/codehaus/groovy/grails/web/servlet/ErrorHandlingServlet.java#L167) and [just written as-is](https://github.com/grails/grails-core/blob/2.5.x/grails-web/src/main/groovy/org/codehaus/groovy/grails/web/servlet/ErrorHandlingServlet.java#L197) in the ErrorHandlingServlet.

**Comment by brycechasm** [comment]
Submitted pull request for ce06edb4cfab70534aaf1abbc0834b5678462ae8
