### ISSUE TITLE
Grails 3.2.2 log message deprecation warning String interpolation issue

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#10283]
A Grails Log in 3.2.2 has a DEPRECATION warning with what looks to be a String Interpolation issue:

```
[2016-10-28 10:03:54,800] [main] WARN  g.u.GrailsUtil - [DEPRECATED] The ${RESOURCE} syntax is deprecated and will be removed in a future release. Use ${SINGLE} instead.
```

NOTE the `${RESOURCE}` and `${SINGLE}`

**Comment by jeffbrown** [comment]
I think this is the result of a Groovy string in a  .java source file.  https://github.com/grails/grails-core/blob/6ffdf8b0a13868e9f99178be966ece627a248355/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingEvaluator.java#L648
