### ISSUE TITLE
Grails 3.2.2: Interceptor not executed

### ISSUE THREAD

**Issue by itpragmatik** [grails/grails-core#10284]
### Steps to Reproduce
1. install grails 3.2.2
2. grails -v to confirm i am running 3.2.2
3. grails create-app myapp
4. add an interceptor myapp/grails-app/controllers/myapp/AuthenticationInterceptor.groovy
5. grails clean && grails war
6. java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 build/libs/myapp.war
7. From my IntelliJ IDEA, set a breakpoint in the before() method of AuthenticationInterceptor
8. Start debug from IDE
9. Access http://localhost:8080/
### Expected Behaviour
1. Execution suspends at the breakpoint 
### Actual Behaviour
1. Grails default index.html welcome page is shown; interceptor breakpoint is not hit.
### Environment Information
- **Operating System**: macOS Sierra Version 10.12.1
- **Grails Version:** 3.2.2
- **JDK Version:** java version "1.8.0_102", Java(TM) SE Runtime Environment (build 1.8.0_102-b14),  Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
### Example Application

https://github.com/itpragmatik/myapp.git
### Note

The breakpoint is hit when I do: grails run-app --debug-jvm

**Comment by jeffbrown** [comment]
I can't reproduce this problem.

How are you launching the project from within the IDE?

**Comment by jeffbrown** [comment]
I am using IntelliJ IDEA 2016.2.4

**Comment by itpragmatik** [comment]
IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016

**Comment by itpragmatik** [comment]
<img width="1066" alt="screen shot 2016-10-28 at 10 58 08 am" src="https://cloud.githubusercontent.com/assets/9458969/19816767/7accea3c-9cfd-11e6-8562-14f9b688b65a.png">

**Comment by jeffbrown** [comment]
My mistake.  I see now that you are running with `java -jar...`.  I had overlooked that.  Sorry for the noise.

**Comment by olavgg** [comment]
I can confirm this as I just ran into this problem. Interceptors will not run when running with java -jar 
Happens in Grails 3.2.0 and Grails 3.2.2

I've have not tried to deploy the war file on a Tomcat server yet.

**Comment by appcela** [comment]
`grails-app/conf/BootStrap.groovy` seems to suffer the same problem, not executed when running with `java -jar` since Grails 3.2.0.

**Comment by jameskleeh** [comment]
I looked at the `grails.factories` for the interceptor plugin that was bundled with the war and it contained:

```
grails.compiler.traits.TraitInjector=grails.compiler.traits.InterceptorTraitInjector
grails.core.ArtefactHandler=org.grails.plugins.web.interceptors.InterceptorArtefactHandler
```

When the classloader gets the factories, the result of `url.text` for the interceptor `grails.factories` is:

```
#Grails Factories File
#Thu Oct 27 15:24:17 UTC 2016
grails.compiler.traits.TraitInjector=grails.compiler.traits.InterceptorTraitInjector
```

So something is not being read correctly. I verified the URL path was the same path of the file I inspected.

**Comment by graemerocher** [comment]
Workaround is to use `grails-plugin-interceptor` from 3.2.1 for the moment:

```groovy
compile "org.grails:grails-plugin-interceptors:3.2.1"
```
