### ISSUE TITLE
Gails 3.2.2: Unit tests using HibernateSpec won't run when application.yml & application.groovy is present

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10281]
The following [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/GameControllerSpec.groovy#L10) extends `HibernateSpec` using Grails 3.2.2 and the Grails app has both `application.yml` and `application.groovy`.

```
org.grails.core.exceptions.GrailsConfigurationException: Error loading application.groovy due to [java.lang.ClassCastException]: org.grails.io.support.DefaultResourceLoader$ClassPathContextResource cannot be cast to org.springframework.core.io.Resource

	at org.grails.core.cfg.GroovyConfigPropertySourceLoader.load(GroovyConfigPropertySourceLoader.groovy:80)
	at org.grails.core.cfg.GroovyConfigPropertySourceLoader.load(GroovyConfigPropertySourceLoader.groovy:45)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:127)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:102)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:88)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:76)
	at grails.test.hibernate.HibernateSpec.setupSpec(HibernateSpec.groovy:43)
Caused by: java.lang.ClassCastException: org.grails.io.support.DefaultResourceLoader$ClassPathContextResource cannot be cast to org.springframework.core.io.Resource
	at org.grails.core.cfg.GroovyConfigPropertySourceLoader.load(GroovyConfigPropertySourceLoader.groovy:71)
	... 6 more
```

### Steps to Reproduce

1. Run  [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/GameControllerSpec.groovy#L10)
2. Remove [application.groovy](https://github.com/saw303/grails-issues/blob/master/grails-app/conf/application.groovy)
3. Rerun  [test](https://github.com/saw303/grails-issues/blob/master/src/test/groovy/grails/issues/GameControllerSpec.groovy#L10)

### Expected Behaviour

It should work with both `application.yml` and `application.groovy`

### Actual Behaviour

Since Grails 3.2.2 it does not

### Environment Information

- **Operating System**: macOS Sierra
- **Grails Version:** 3.2.2
- **JDK Version:** 1.8

### Example Application

- see above

**Comment by saw303** [comment]
Would it be possible to release a Grails 3.2.2.1 or 3.2.3 only containing a bugfix for this? I'm quite stuck migrating from Grails 3.1.12 to 3.2.x.

**Comment by graemerocher** [comment]
Specify 

```groovy
compile "org.grails.plugins:hibernate5:6.0.2"
```

In `build.gradle` until 3.2.3 is out

**Comment by saw303** [comment]
`org.grails.plugins:hibernate5:6.0.2` forces me to implement `getDomainClasses` of `HibernateSpec`.

I will then wait for 3.2.3...

**Comment by graemerocher** [comment]
Since the ability to not have to to implement `getDomainClasses` is new in 3.2.2 and wasn't present in 3.2.0 or 3.2.1 I don't see how that stops you from upgrading, but anyway whatever you want.

In general it is better to isolate to test to a set of domain classes anyway to improve performance of the test, rather than load every domain in your project, which will just slow down test execution

**Comment by graemerocher** [comment]
I also don't recall 3.1.x having any domain class scanning features that would prevent you from upgrading.

**Comment by saw303** [comment]
I agree. That does not stop me from upgrading. Currently it is the amount of unit test that I would have to migrate (I'm not refering to the grails-issue repository). In 3.1.x and below I used the `package-info.groovy` with the `@Domain` annotation. That has been a quite nice feature when you got plenty of domain objects and you don't what to repeat yourself in every unit test class.

Thank you by the way for the tip about the performance of test and not loading all domain classes. I will take a look into that. May be that would improve the test execution time of my current project.

**Comment by graemerocher** [comment]
I had no idea you could use `package-info.groovy` with `@Domain` that is news to me. Must be a secret undocumented feature.

**Comment by graemerocher** [comment]
I see it was documented, interesting.. you learn new things everyday. @lhotari must have implemented that 😄

**Comment by saw303** [comment]
Actually it has been there for a while. You find it in the Grails [documentation](http://docs.grails.org/3.1.12/guide/testing.html) and then goto `Configuring domain classes for HibernateTestMixin tests`. It says:

> The grails.test.mixin.gorm.Domain annotation is used to configure the list of domain classes to configure for Hibernate sessionFactory instance that gets configured when the unit test runtime is initialized.
> 
> Domain annotations will be collected from several locations:
> 
> the annotations on the test class
> the package annotations in the package-info.java/package-info.groovy file in the package of the test class
> each super class of the test class and their respective package annotations
> the possible SharedRuntime class
> Domain annotations can be shared by adding them as package annotations to package-info.java/package-info.groovy files or by adding them to a SharedRuntime class which has been added for the test.
> 
> It's not possible to use DomainClassUnitTestMixin's Mock annotation in HibernateTestMixin tests. Use the Domain annotation in the place of Mock in HibernateTestMixin tests.

It seems that it has been introduced in Grails 2.5.0. It is the first time it appears in the documentation.

Anyway. I really like the `HibernateSpec` approach and to me it is good to say goodbye to the `HibernateTestMixin`. I will continue to migrate my unit test using 3.2.3.BUILD-SNAPSHOT. Thank you for your time and support.

**Comment by saw303** [comment]
This might now get a bit off topic but I was wondering if it would make sense to use a "reference grails project" containing some unit test (like the ones I use to report these issues) within the build process to verify that a new release does not break existing Grails unit test features.

In my project these functionality is fundamental to me and I invest quite some time. Such a checkpoint within the Grails build (or release) process could find these problems before you release a version.

What do you think of this? I willing to contribute if it make sense to you guys.

**Comment by graemerocher** [comment]
We already have some tests here https://github.com/grails/gorm-hibernate5/tree/master/grails-plugin/src/test/groovy/grails/test/mixin/hibernate

However what it lacks and the reason why this wasn't picked up is that project contains no `application.yml`
