### ISSUE TITLE
Plugin trouble going from Grails 3.1.11 to 3.2.2

### ISSUE THREAD

**Issue by namgang** [grails/grails-core#10288]
### Description

Depending on how you build a plugin jar, you may end up with a runnable jar (Boot repackaged) which cannot be loaded from an app. The problem is that you won't notice because it only results in a warning log message on app startup (using defaut log levels).

- This possibility should be mentioned in the Guide
- `org.grails.plugins.CorePluginFinder` should issue an error message, not just a warning, if it cannot load a plugin. Presumably, the app has declared a compile-time dependency to it, so it's a conflict.

Even better, `org.grails.plugins.CorePluginFinder` could actually detect that the jar is Boot repackaged and say so (and barf). Curiously this class does not appear in the 3.2.2 api doc.

The remainder of this issue was written before I knew what the problem is. It is still useful for demonstrating the issue.

Summary: Grails plugin could not be upgraded from 3.1.11 to 3.2.2. In 3.2.2 it is not loaded because the format of the jar has been changed and the loader doesn't look in the right place.

I was working on a plugin and an app under Grails 3.1.11 and decided to upgrade to Grails 3.2.2.
After the upgrade the plugin seemed very absent from the app, but there were no diagnostics.
Finer grained logging showed that `org.grails.plugins.CorePluginFinder` issued a warning that the plugin could not be loaded because it couldn't find the plugin descriptor (...Plugin.groovy).

Examining plugin jar contents, I found that there is a new BOOT-INF hierarchy. It seems *CorePluginFinder* does not look into that hierarchy. Thus it does not find the plugin descriptor and cannot load the plugin.

I recrafted the plugin jar, moving classes and libs to the root level. Then copied the modified plugin jar to the local Maven cache. Lo and behold, the plugin loads and behaves normally.

See also my confused question on [Stackoverflow](http://stackoverflow.com/questions/40363308/upgrading-a-plugin-fails-going-from-grails-3-1-11-to-3-2-2/).

### Steps to Reproduce

1. Get example code from [GitHub](https://github.com/namgang/grails322-plugin-issue)
2. You will need Grails 3.2.2
3. Run the example, building and running it the normal way, as per its README
4. Copy the included handcrafted plugin jar to your local Maven cache
5. Run the example again (don't build), as per the README

### Expected Behaviour

Referring to the example application.

At startup there is some printout on standard out from the plugin. The output shows that the `doWithSpring` and `doWithApplicationContext` are executed, i.e. the plugin is loaded.

The `show.gsp` of the example app has an extra tag inserted that invokes the taglib defined by the plugin.
After creating a new instance of the only domain of the example app, the *show* view should contain some output from the extra tag.

### Actual Behaviour

No output during startup. The plugin is not loaded.

Since the plugin is not loaded the extra tag in `show.gsp` is silently ignored because the taglib is not available.

### Environment Information

- **Operating System**: Ubuntu 14.04.5 LTS
- **Grails Version:** 3.2.2
- **JDK Version:** 1.8.0_102 (Oracle Corporation 25.102-b14)
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/namgang/grails322-plugin-issue

**Comment by graemerocher** [comment]
See my answer on the question http://stackoverflow.com/a/40376746/259167
