### ISSUE TITLE
Grails Gson Mapped List

### ISSUE THREAD

**Issue by Vigneshwaran22** [grails/grails-core#10289]
how can i write gson for this action
i use _user.gson template but is showing error

this is my code:

User.groovy

class User{
String name
String status
   static constraints = {
   status (inList:["Active","InActive"])
    }
}

UserController.groovy
def list()
{
def list = [all:User.list(),active:User.findAllByStatus("Active"),inactive:User.findAllByStatus("InActive")]
respond list
}

Thanks in Advance

**Comment by rakesanug** [comment]
i  also having same problem.

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
