### ISSUE TITLE
Plugin jar generation and loading

### ISSUE THREAD

**Issue by namgang** [grails/grails-core#10297]
A Grails app may declare a compile-time dependency to a plugin. At run-time, if the plugin cannot be loaded, this fact is announced with a WARN log message by org.grails.plugins.CorePluginFinder. With default logging settings the message is not visible, the app fails silently.

Case in point, the plugin jar may accidentally be generated with Boot repackaging. In such case the plugin loader logs a warning that the plugin descriptor cannot be found. (It is actually present in the jar, but not in the expected place.) The jar should not be loaded, of course, but if the plugin descriptor had occurred in a different place in the file hierarchy the plugin loader would have attempted it anyway.

One or more of the following design-level improvements would be valuable for a smooth developer experience.

* A plain plugin jar and a Boot repackaged one get different file names
* If CorePluginFinder cannot load a plugin, this is logged as an ERROR.
* Make Grails plugin jars distinctly recognizable by adding attributes to the Manifest. (This is what Boot repackaging does.) For instance, `Grails-Plugin-Descriptor-Class: my.organization.WhateverGrailsPlugin` (A similar `…-Version` attribute would be a natural complement.) The current architecture relies on the presence of a class with a particular name pattern, a more brittle mechanism.
* If a loadable Grails plugin jar is distinctly recognizable, the plugin loader can react with an exception that stops the app if a plugin cannot be loaded, rather than starting a non-functional app.

### Steps to Reproduce
1. Clone or download samples provided on [GitHub](https://github.com/namgang/grails322-plugin-issue). (Please disregard the Grails version number, it is not relevant.) It contains a minimal app using a minimal plugin.
2. Set up a suitable Grails environment. Use the included `setup.sh` or use your own conventions.

A complete description is available in the README.

### Expected Behaviour
Generate the plugin with `gradle clean install`. Build and run the app. Messages should appear on standard out on startup, the app should echo your input when you create a new "Ping".

See the README for details.

### Actual Behaviour
Generate the plugin with `gradle clean build install`. Build and run the app. The plugin is silently discarded because it is generated as a Boot repackaged jar (with the same file name).

This is not exactly a bug, but the design invites mistakes.

### Environment Information

- Ubuntu 14.04.5 LTS
- Tested with Grails 3.1.11 and 3.2.2 with identical outcome
- Oracle Java SE 1.8.0_102-b14

### Example Application

- On GitHub: [grails322-plugin-issue](https://github.com/namgang/grails322-plugin-issue)

**Comment by graemerocher** [comment]
I have disabled repackaging by default, this should address the concerns expressed here
