### ISSUE TITLE
Since Grails 3.2.0 the Hibernate second level cache is not used for reading entities.

### ISSUE THREAD

**Issue by typical-nerd** [grails/grails-core#10307]
Since Grails 3.2.0 the Hibernate second level cache is not used for reading entities.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the application with `grails run-app
[GrTestCache3.zip](https://github.com/grails/grails-core/files/580824/GrTestCache3.zip)
`
2. Query the app with curl 2 times. 
    `curl -i -H "accept: application/json" -X GET http://127.0.0.1:8080/grTestCache?id=1`
3. Check the log output.

### Expected Behaviour

On the first request an entity is read from the database and then written to the second level cache. The second request should then fetch the entity from the cache instead of executing another database query.

Log excerpt from a Grails 3.1.13 version of the application:

    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - begin
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - initial autocommit status: true
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - disabling autocommit
    DEBUG org.hibernate.SQL - select grtestcach0_.id as id1_0_0_, grtestcach0_.version as version2_0_0_, grtestcach0_.date_created as date_cre3_0_0_, grtestcach0_.last_updated as last_upd4_0_0_, grtestcach0_.name as name5_0_0_ from gr_test_cache grtestcach0_ where grtestcach0_.id=?
    DEBUG org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl - Starting ResultSet row #0
    DEBUG org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl - On call to EntityIdentifierReaderImpl#resolve, EntityKey was already known; should only happen on root returns with an optional identifier specified
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Resolving associations for [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Adding entity to second-level cache: [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Done materializing entity [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader - Done entity load : com.digithurst.GrTestCache#4
    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - committing
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Processing flush-time cascades
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Dirty checking collections
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 (re)creations, 0 updates, 0 removals to 0 collections
    DEBUG org.hibernate.internal.util.EntityPrinter - Listing entities:
    DEBUG org.hibernate.internal.util.EntityPrinter - com.digithurst.GrTestCache{lastUpdated=2016-11-09 12:00:07.023, dateCreated=2016-11-09 12:00:07.023, name=Dog, id=4, version=0}
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - committed JDBC Connection
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - re-enabling autocommit
    DEBUG org.hibernate.internal.SessionImpl - Disconnecting session
    ...
    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - begin
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - initial autocommit status: true
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - disabling autocommit
    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - committing
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Processing flush-time cascades
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Dirty checking collections
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 (re)creations, 0 updates, 0 removals to 0 collections
    DEBUG org.hibernate.internal.util.EntityPrinter - Listing entities:
    DEBUG org.hibernate.internal.util.EntityPrinter - com.digithurst.GrTestCache{lastUpdated=2016-11-09 12:00:07.023, dateCreated=2016-11-09 12:00:07.023, name=Dog, id=4, version=0}
    ...

### Actual Behaviour

On the first request an entity is read from the database and then written to the second level cache (according to the log file). The second request results in exactly the same behavior. In the log you can see that a SQL statement is generated, other than in previous Grails versions until 3.1.13. There the second request does not generate a SQL statement and serves the item from the cache.

Log excerpt from a Grails 3.2.0 version of the application:

    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - begin
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - initial autocommit status: true
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - disabling autocommit
    DEBUG org.hibernate.SQL - select this_.id as id1_0_0_, this_.version as version2_0_0_, this_.date_created as date_cre3_0_0_, this_.last_updated as last_upd4_0_0_, this_.name as name5_0_0_ from gr_test_cache this_ where this_.id = ?
    DEBUG org.hibernate.loader.Loader - Result set row: 0
    DEBUG org.hibernate.loader.Loader - Result row: EntityKey[com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Resolving associations for [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Adding entity to second-level cache: [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Done materializing entity [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - committing
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Processing flush-time cascades
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Dirty checking collections
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 (re)creations, 0 updates, 0 removals to 0 collections
    DEBUG org.hibernate.internal.util.EntityPrinter - Listing entities:
    DEBUG org.hibernate.internal.util.EntityPrinter - com.digithurst.GrTestCache{lastUpdated=2016-11-09 14:20:55.619, dateCreated=2016-11-09 14:20:55.619, name=Jake, id=4, version=0}
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - committed JDBC Connection
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - re-enabling autocommit
    DEBUG org.hibernate.internal.SessionImpl - Disconnecting session
    ...
    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - begin
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - initial autocommit status: true
    DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction - disabling autocommit
    DEBUG org.hibernate.SQL - select this_.id as id1_0_0_, this_.version as version2_0_0_, this_.date_created as date_cre3_0_0_, this_.last_updated as last_upd4_0_0_, this_.name as name5_0_0_ from gr_test_cache this_ where this_.id = ?
    DEBUG org.hibernate.loader.Loader - Result set row: 0
    DEBUG org.hibernate.loader.Loader - Result row: EntityKey[com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Resolving associations for [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Adding entity to second-level cache: [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.internal.TwoPhaseLoad - Done materializing entity [com.digithurst.GrTestCache#4]
    DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl - committing
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Processing flush-time cascades
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Dirty checking collections
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
    DEBUG org.hibernate.event.internal.AbstractFlushingEventListener - Flushed: 0 (re)creations, 0 updates, 0 removals to 0 collections
    DEBUG org.hibernate.internal.util.EntityPrinter - Listing entities:
    DEBUG org.hibernate.internal.util.EntityPrinter - com.digithurst.GrTestCache{lastUpdated=2016-11-09 14:20:55.619, dateCreated=2016-11-09 14:20:55.619, name=Jake, id=4, version=0}
    ...

### Environment Information

- **Operating System**: Windows 7 64 Bit
- **Grails Version:** 3.2.0, 3.2.2
- **JDK Version:** 8 Update 101
- **Container Version (If Applicable):** Embedded Tomcat through run-app

### Example Application

[GrTestCache3.zip](https://github.com/grails/grails-core/files/580826/GrTestCache3.zip)

**Comment by graemerocher** [comment]
So the logic for `get` has been changed to use a query. This was done to facilitate multi-tenancy and event listeners. I guess one options is if multi tenancy is not in use to not use a query, but instead use `session.get(..)` which would restore the previous behaviour, however one would never be able to register an event listener for non multi-tenant entities in that case.

**Comment by graemerocher** [comment]
See https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateGormStaticApi.groovy#L70
