### ISSUE TITLE
failOnError defined on a package in application.yml is not honored 

### ISSUE THREAD

**Issue by YouriAckx** [grails/grails-core#10303]
### Summary

`failOnError` defined on a package in `application.yml` is not honored in Grails `3.2.2`

### Steps to Reproduce

1. In `application.yml`, set `failOnError` for your company package

```
grails:
    gorm:
        failOnError:
            - com.mycompany
```

2. Create an entity with a basic validation (e.g. `value min:10`)

3. In an integration test, create and `save()` an instance of that entity that does not pass valiation

### Expected Behaviour

Calling `save()` on the entity triggers a `ValidationException` and the entity is not saved

### Actual Behaviour

No error is trigged, and the entity is not saved.

### Environment Information

- **Operating System**: OSX El Capitan 10.11.6 (15G1108)
- **Grails Version:** 3.2.2
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
- **Container Version (If Applicable):** n/a

### Example Application

See https://github.com/YouriAckx/grails-failonerror

`grails test-pp -integration`

**Comment by graemerocher** [comment]
The setting was renamed to `failOnErrorPackages` I have updated the upgrade docs to reflect that.

**Comment by YouriAckx** [comment]
A bit confused here. I've retested with v. `3.2.4` and the setting is apparently not taken into account. Are we talking about the same version, and the same config file: `application.yml` rather than `application.groovy` ?
