### ISSUE TITLE
Using g.message in RestfulController with rest-profile raise error 500

### ISSUE THREAD

**Issue by OlivierGuilloux** [grails/grails-core#10302]
Using g.message as describe http://docs.grails.org/latest/guide/single.html#readingMessages cause error 500 because the g attribute is not inject for the rest-api profile.

### Steps to Reproduce

1. grails create-app testapi --profile=rest-api
2. grails create-domain-class Test
3. grails create-restful-controller Test
4.  sed -e "s/^}$/def index(){render g.message('test.message')}}/" grails-app/controllers/idc_emtpy/Test3Controller.groovy -i
5. echo test.message="Message test" >> grails-app/i18n/messages.properties
6. grails run-app
7. display http://localhost:8080/test

### Expected Behaviour

Display the message "Message test"

The same with profile=web with a controller that extend RestfulController work fine. 

### Actual Behaviour

ERROR org.grails.web.errors.GrailsExceptionResolver - MissingPropertyException occurred when processing request: [GET] /test/index
No such property: g for class: testapi.TestController. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingPropertyException: No such property: g for class: testapi.Test3Controller
	at testapi.Test3Controller$$EQ1xch6W.index(TestController.groovy:12)
	... 3 common frames omitted

### Environment Information

- **Operating System**: Fedora 23
- **Grails Version:** 3.1.10
- **JDK Version:** OpenJDK Runtime Environment (build 1.8.0_111-b16)

**Comment by graemerocher** [comment]
With `g.message(..)` you are using the `<g:message>` tag, GSP is not included in the `rest-api` profile hence the error. You can use `@Autowired MessageSource messageSource` and use the `getMessage(..)` method of the message source.
