### ISSUE TITLE
Profiles: Make binary file extensions customizable

### ISSUE THREAD

**Issue by andrzejbiedrzycki** [grails/grails-core#10315]
Size of xlsm file is different then original file from "profile" project
### Steps to Reproduce

1. add any xlsm file to e.g. src/docs dir in a profile project (mycustom)
2. create-app apptest --profile mycustom
3.  
original file:  43760 translations.xlsm
corrupted file 76147 Nov 14 14:56 translations.xlsm

### Expected Behaviour
file translations.xlsm should have original size in new created project

### Actual Behaviour
File xlsx,xlsm ,doc ...etc in new project is corrupted with different size
Please note that files with image extenstion i.e ico are copying without corruption.

### Environment Information

- **Operating System**:  Windows7
- **Grails Version:** 3.2.1 , 3.2.2
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

**Comment by graemerocher** [comment]
This is because need to make this list extensible https://github.com/grails/grails-core/blob/master/grails-shell/src/main/groovy/org/grails/cli/profile/commands/CreateAppCommand.groovy#L70
