### ISSUE TITLE
Exception after render() call results in "double rendering"

### ISSUE THREAD

**Issue by peh** [grails/grails-core#10318]
### Task List

- [✓] Steps to reproduce provided
- [✓] Stacktrace (if present) provided
- [✓] Example that reproduces the problem uploaded to Github
- [✓] Full description of the issue provided (see below)

### Steps to Reproduce

1. render anything in a controller action
2. force an exception afterwards (e.g. in an interceptor or simply after the actual render() call)
3. check the resulting response

### Expected Behaviour

The "error page" or whatever is defined in the "500" UrlMapping should be rendered.

### Actual Behaviour

The initial render rendered, the response come with status 200 and then the default error page (if it exists) is being rendered.

### Environment Information

- **Operating System**: Windows, MacOS, Linux (Debian&Ubuntu)
- **Grails Version:** 3.1.11 & 3.2.3 (i guess everything in between to)
- **JDK Version:** 1.8u91
- **Container Version (If Applicable):** run-app & tomcat 8.0.32

### Example Application

https://github.com/peh/grails3-exception-test

**Comment by graemerocher** [comment]
Whilst I appreciate this may be confusing to solve this we would need to buffer the response in memory which would be bad for performance.
