### ISSUE TITLE
Constraint problems with domain property names starting with single lowercase letter 

### ISSUE THREAD

**Issue by warwren** [grails/grails-core#10310]
### Steps to Reproduce

1. Do "grails create-app simple" and go into simple directory
2. grails create-domain-class MyStuff
3. edit MyStuff.groovy to have a property starting with single lowercase letter like xValue, yValue, iNode, etc. and add a constraint like blank: false.  I used:
`
class MyStuff {
    String xValue
    static constraints = {
        xValue(blank: false)
    }
}
`
4. grails create-scaffold-controller MyStuff
5. grails run-app
6. Visit http://localhost:8080/myStuff/create

### Expected Behaviour

Get a create page with an xValue field to fill in.

### Actual Behaviour

Get a grails runtime exception page complaining about "object is not an instance of declaring class" highlighting the xValue constraint line in the domain class.  Can work around with a property name with more than just one lowercase character at the beginning (like xyValue).

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.2.2
- **JDK Version:** 1.8

### Example Application

- https://github.com/warwren/single-lowercase

**Comment by zyro23** [comment]
maybe/hopefully related to and fixed already with #10343 ?

**Comment by graemerocher** [comment]
Duplicates #10343
