### ISSUE TITLE
Migration 2.2.1 to 3.2.3 multi datasource optional

### ISSUE THREAD

**Issue by Apofis82** [grails/grails-core#10320]
I am migrating my web application from grails 2.2.1 to 3.2.3 and I get an exception when running grails run-app with my domains.
My domains are configured to use multiple datasources.

Windows XP SP2 32bit
jdk 1.7.40

On Grails 3.2.3
grails create-app app1
add file domain to app1/grails-app/domain/test/Test0.groovy

Test0.groovy:

package test
class Test0 {
	static mapping = {
		datasources([ 'app1','superapp','superapp_app1','test_app1','test_superapp','test_superapp_app1','DEFAULT' ])
	}
}

grails run-app
throw exception:
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to insta
ntiate [org.grails.orm.hibernate.HibernateDatastore]: Constructor threw exceptio
n; nested exception is org.grails.datastore.mapping.core.exceptions.Configuratio
nException: DataSource not found for name [app1] in configuration. Please ch
eck your multiple data sources configuration and try again.

On Grails 2.2.1
grails create-app app1
add same file domain Test0.groovy
grails run-app
All OK

My intention is to migrate a super application and its 3 mini application for the development and testing environments.
The super application configured with default, test_app1, test_app2 and test_app3 dataSources
The 3 mini apps configured with default datasource.
And to be able to move the domains of the 3 mini applications to the super application without modifying the mapping

How to do not have to modify the mapping of the domains or datasources of the application.yml?

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
