### ISSUE TITLE
2.5.5 IllegalStateException in URLMappingsFilter on REST request

### ISSUE THREAD

**Issue by ChrisDavis8** [grails/grails-core#10326]
I am getting an IllegalStateExeption in the URLMappings filter on requests when using Spring security REST with spring security core but I suspect it could be more general to using custom filters

I also think this is the same issue as asked here on [StackOverflow](http://stackoverflow.com/questions/40128037/grails-2-5-2-spring-security-custom-filter-error-cannot-set-request-attribute)

The error does not happen on every request and only sparodically on prod but is more likely to occur when multiple requests are sent at the same time. When running locally in dev environment I can reproduce much more easily just be sending a few requests at once, could that indicate it is thread re-use related? does dev allocate a smaller pool of threads?

### Expected Behaviour
The request should be handled without error

### Actual Behaviour
The following exception thrown from URLMappingsFilter
```
2016-11-22 12:40:09,529 [][ERROR][http-bio-8080-exec-5][][][UrlMappingsFilter] Error when matching URL mapping [/call/clear]:Cannot set request attribute - request is not active anymore!
java.lang.IllegalStateException: Cannot set request attribute - request is not active anymore!
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:118)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:84)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.java:59)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

### Environment Information

- **Operating System**: Both Windows & linux
- **Grails Version:** 2.4.4,  2.5.5, 2.5.4 
- **JDK Version:** 1.7.0_79, 1.8.0_102, 1.8.0_25
- **Container Version (If Applicable):** Tomcat 7

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)

**Comment by ChrisDavis8** [comment]
Just in case anyone else has this issue I found the cause was from using grails Async functionality to create background processing threads that finish after the request as ended using onComplete(taskname){}  

When the async block completes it calls request.onComplete() on the thread that created it so if that thread has already been re-used by another request it will complete the new request instead.

**Comment by galenodemelo** [comment]
Thanks to @ChrisDavis8, we managed to fix the problem.

The best approach for us was to override the default `WebRequestPromiseDecoratorLookupStrategy` class, [removing all `WebUtils.storeGrailsWebRequest` calls](https://github.com/grails/grails-core/blob/2.5.x/grails-plugin-async/src/main/groovy/org/codehaus/groovy/grails/plugins/web/async/WebRequestPromiseDecoratorLookupStrategy.groovy#L55) and using `RequestContextHolder.setRequestAttributes` directly. This might cause bugs on `Async Controllers`, which we don't use and aren't willing to use soon.

For some unknown reason, [this line](https://github.com/grails/grails-core/blob/2.5.x/grails-web-common/src/main/groovy/org/codehaus/groovy/grails/web/util/WebUtils.java#L431) seems to create a copy of the current request, which in some place will be closed, affecting another request.

Our override class got like this:

```groovy
package org.codehaus.groovy.grails.plugins.web.async

import groovy.transform.CompileStatic
import org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequest
import org.grails.async.decorator.PromiseDecorator
import org.grails.async.decorator.PromiseDecoratorLookupStrategy
import org.springframework.web.context.request.RequestContextHolder

/**
 * Workaround by ASAAS
 */
@CompileStatic
class WebRequestPromiseDecoratorLookupStrategy implements PromiseDecoratorLookupStrategy {

    @Override
    List<PromiseDecorator> findDecorators() {
        final GrailsWebRequest currentWebRequest = GrailsWebRequest.lookup()
        if (!currentWebRequest) return Collections.emptyList()

        WebRequestPromsiseDecorator decorator = new WebRequestPromsiseDecorator(currentWebRequest) {

                @Override
                <D> Closure<D> decorate(Closure<D> c) {
                    return (Closure<D>) { args ->
                        GrailsWebRequest newWebRequest = new GrailsWebRequest(
                            this.webRequest.currentRequest,
                            this.webRequest.currentResponse,
                            this.webRequest.servletContext,
                            this.webRequest.applicationContext
                        )

                        try {
                            newWebRequest.addParametersFrom(this.webRequest.params)
                            RequestContextHolder.setRequestAttributes(newWebRequest)

                            return invokeClosure(c, args)
                        } finally {
                            newWebRequest.requestCompleted()
                            RequestContextHolder.setRequestAttributes(this.webRequest)
                        }
                    }
                }
            }

        return [decorator] as List<PromiseDecorator>
    }
}

```
