### ISSUE TITLE
Grails 3.2.3 does not work with Java 9

### ISSUE THREAD

**Issue by vbaarda** [grails/grails-core#10323]
### Steps to Reproduce
```
$ echo $JAVA_HOME
/usr/java/jdk-9

$ /usr/java/jdk-9/bin/java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+144)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+144, mixed mode)

$ grails -version | cat
| Grails Version: 3.2.3
| Groovy Version: 2.4.7
| JVM Version: 9-ea

$ grails create-app my-project | cat
| Application created at /root/my-project

$ cd my-project

$ grails create-domain-class org.example.Book | cat
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

Total time: 1.811 secs
| Created grails-app/domain/org/example/Book.groovy
| Created src/test/groovy/org/example/BookSpec.groovy

$ cat > grails-app/domain/org/example/Book.groovy
package org.example

class Book {
    String title
    String author

    static constraints = {
        title(blank: false)
        author(blank: false)
    }
}

$ grails create-controller org.example.Book | cat
| Created grails-app/controllers/org/example/BookController.groovy
| Created src/test/groovy/org/example/BookControllerSpec.groovy

$ cat > grails-app/controllers/org/example/BookController.groovy
package org.example

class BookController {
    def scaffold = Book // Note the capital "B"
}

$ grails run-app | cat
| Running application...
java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
```

### Expected Behaviour

Application should run.

### Actual Behaviour

java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira

### Environment Information

- **Operating System**: SUSE Linux Enterprise Server 12 SP1
- **Grails Version:** 3.2.3
- **JDK Version:** 9-ea
- **Container Version (If Applicable):** None

### Example Application

Entire application is included above.

[stacktrace.txt](https://github.com/grails/grails-core/files/601149/stacktrace.txt)

**Comment by jeffbrown** [comment]
@vbaarda 

Does the problem also happen if you use `static scaffold = Book`?

There is a comment above that says `Note the capital "B"`.  The value is supposed to be the name of a class, which typically would begin with an upper case letter.  Can you clarify why you pointed out the capital B?

Thanks for the feedback.

**Comment by vbaarda** [comment]
> Does the problem also happen if you use static scaffold = Book?

Yes. The stacktrace is the same.

> There is a comment above that says Note the capital "B". The value is supposed to be the name of a class, which typically would begin with an upper case letter. Can you clarify why you pointed out the capital B?

Heh -- that's just my lazy copy-n-paste from https://grails.org/wiki/Quick%20Start#Create%20a%20controller

Here's the new controller:
```
$ cat my-project/grails-app/controllers/org/example/BookController.groovy
package org.example

class BookController {
	static scaffold = Book
}
```

**Comment by jeffbrown** [comment]
Thanks for the feedback.

**Comment by jeffbrown** [comment]
I don't know what, if any, testing the Spring Loaded guys have done against the early access JDK 9 releases.

**Comment by vbaarda** [comment]
A new problem with the latest jdk9 and the latest grails:
```
$ /usr/lib/jvm/jdk-9/bin/java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+163)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+163, mixed mode)

$ grails -version
| Grails Version: 3.2.8
| Groovy Version: 2.4.10
| JVM Version: 9-ea

lani$ grails create-domain-class org.example.Book --stacktrace
Resolving Dependencies. Please wait...
Error initializing classpath: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @1a1d6a08 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)$
java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @1a1d6a08$
    at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:34)$
    at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:38)$
    at org.gradle.internal.reflect.JavaReflectionUtil.method(JavaReflectionUtil.java:224)$
    at org.gradle.internal.classloader.MultiParentClassLoader.<clinit>(MultiParentClassLoader.java:42)$
    at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createImplementationClassLoader(DefaultToolingImplementationLoader.java:123)$
    at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:73)$
    at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:43)$
    at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:42)$
    at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:95)$
    at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:78)$
    at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)$
    at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)$
    at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)$
    at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)$
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)$
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)$
Error initializing classpath: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @1a1d6a08
```

**Comment by jessewriter** [comment]
grails run-app
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/portlandia/.sdkman/candidates/grails/3.3.2/lib/org.codehaus.groovy/groovy/jars/groovy-2.4.13.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Error Error initializing classpath: Could not determine java version from '9.0.1'. (Use --stacktrace to see the full trace)

my env:
| Grails Version: 3.3.2
| Groovy Version: 2.4.13
| JVM Version: 9.0.1
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          9.0.1 (Oracle Corporation 9.0.1+11)
OS:           Linux 4.13.0-26-generic amd64

**Comment by jessewriter** [comment]
I believe this problem stems from the fact that JavaEE libraries are no longer included in the Java Core library and must be added as modules.  Not sure how to do that from Grails.   see https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-F640FA9D-FB66-4D85-AD2B-D931174C09A3 Modules Shared with Java EE Not Resolved by Default

**Comment by rscorer** [comment]
`| Error Error initializing classpath: Could not determine java version from '9.0.1'. (Use --stacktrace to see the full trace)`

This means the version of gradle is not recent enough to understand JDK 9, you need something like Gradle 4.6.

But don't expect that to work either. 

Grails uses Spring Boot 1.5.x, and that will never be supporting anything more recent than Java 8 - [according to the Spring Boot team](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9)

They suggest moving to Spring Boot 2, so now we wait for Grails to seamlessly migrate to Spring Boot 2!

**Comment by jeffbrown** [comment]
> ...so now we wait for Grails to seamlessly migrate to Spring Boot 2!

FYI... Spring Boot 2 is on the Grails 4 Roadmap.

**Comment by erichelgeson** [comment]
Closing as Grails 4 is on Spring-boot 2
