### ISSUE TITLE
Persistence events are not triggered in integration tests

### ISSUE THREAD

**Issue by gherolyants** [grails/grails-core#10328]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

* Create a grails app
* Add a persistence event listener subclassed from AbstractPersistenceEventListener 
* Make it handle PreInsert and PreUpdate events to update a field of an entity
* Create an integration test
* Add a domain entity class using @Entity annotation and @Domain annotation
* Add a test method which saves this entity
* Assert that a field updated in the event listener has a value

### Expected Behaviour

I expect events like:
* org.grails.datastore.mapping.engine.event.PreInsertEvent
* org.grails.datastore.mapping.engine.event.PreUpdateEvent
* etc.

to be triggered.

### Actual Behaviour

When I run integration tests I notice that persistence events handled by a subclass of AbstractPersistenceEventListener are not triggered at all. The events that are triggered are:

* org.springframework.boot.context.embedded.EmbeddedServletContainerInitializedEvent
* org.springframework.boot.context.event.ApplicationReadyEvent
* class org.springframework.context.event.ContextClosedEvent

### Environment Information

- **Operating System**: Windows 7/MacOS X
- **Grails Version:** 3.1.5
- **JDK Version:** 1.8.0_25/1.8.0_101

### Example Application

- https://github.com/gherolyants/grails-persistence-events-issue-example

**Comment by Luxor** [comment]
Also reproduced on Grails 3.1.14

**Comment by graemerocher** [comment]
Works fine for me, you just weren't configuring the integration test correctly. See 
[changes.diff.txt](https://github.com/grails/grails-core/files/660829/changes.diff.txt)
