### ISSUE TITLE
Taglib closure name and bean with same name causes ConversionNotSupportedException

### ISSUE THREAD

**Issue by mugren** [grails/grails-core#10330]
Having a Taglib with closure which name equals an id of some registered bean definition causes autowiring to come in place and an exception is thrown:

org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type [org.grails.bug.demo.DemoBean] to required type [groovy.lang.Closure] for property 'someTagName'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.grails.bug.demo.DemoBean] to required type [groovy.lang.Closure] for property 'someTagName': no matching editors or conversion strategy found

Pretty easy to reproduce:
 - Create taglib;
 - add closure with some name;
 - register bean with same name

### Environment Information

- **Grails Version:** 3.2.3

### Example Application
[https://github.com/mugren/taglib-bean-conversion](https://github.com/mugren/taglib-bean-conversion)

**Comment by jeffbrown** [comment]
I don't think this is really a bug.  The tag lib class has a property named `someTagName`.  There is a bean named `someTagName`.  Tab libs (like all Grails artifacts) are subjected to auto wire by name so Spring is attempting to inject the bean into that property reference.  I understand why it is surprising, but I am not sure this is really a bug.

Thoughts?

**Comment by mugren** [comment]
@jeffbrown Yes you are right it's natural expected behavior since the closures are properties. However with the plugin based system of Grails this situations cannot be controlled so easily and avoid situations like this by simple refactoring of things.
Example plugin A defines bean _someName_, plugin B defines taglib closure name _someName_ . I actually met myself in this kind of situation by using public repo plugins.

Is it necessity taglib 'tags' to be closures? Why not changed in methods like the controller artefacts were, in the end method pointer operator can be used for referencing methods in objects.

**Comment by jeffbrown** [comment]
> Is it necessity taglib 'tags' to be closures?

Adding support for tags as methods is a possibility, but there are some complexities around that.
