### ISSUE TITLE
AbstractPersistenceEvent.getEntityAccess() is always null

### ISSUE THREAD

**Issue by Luxor** [grails/grails-core#10331]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run application provided in 
2. add debug point to https://github.com/gherolyants/grails-persistence-events-issue-example/blob/master/src/main/groovy/test/PersistenceEventListener.groovy (onPersistenceEvent) 
3. see that entityAccess is null

### Expected Behaviour

entityAccess should be populated to have similar behavior with org.grails.datastore.gorm.events.AutoTimestampEventListener

To avoid problems described http://stackoverflow.com/questions/33571553/grails-creating-a-custom-persistenceeventlistener
 
### Actual Behaviour

entityAccess is null, no good way to update entity without triggering additional events

### Environment Information

- **Operating System**: window 10
- **Grails Version:** 3.1.13
- **JDK Version:** 1.8.0_71 

### Example Application

- https://github.com/gherolyants/grails-persistence-events-issue-example

### Linked
- https://github.com/grails/grails-core/issues/10328

**Comment by jameskleeh** [comment]
The application provided here executes just fine. What steps should I be taking to trigger a persistence event?

**Comment by Luxor** [comment]
Hi, 
The application is little bit unrelated (sry)

You can create own domain model similar to https://github.com/gherolyants/grails-persistence-events-issue-example/blob/master/src/integration-test/groovy/test/PersistenceEventsSpec.groovy *SuperBro*

With a rest api controller. Any change of model from the controller should trigger https://github.com/gherolyants/grails-persistence-events-issue-example/blob/master/src/main/groovy/test/PersistenceEventListener.groovy
and see that entityAccess is nul in this case

Thanks

**Comment by jameskleeh** [comment]
@Luxor Please update the example application with what is necessary and provide steps to reproduce the problem.

**Comment by jameskleeh** [comment]
Closing due to lack of feedback
