### ISSUE TITLE
Pull in Spring Boot 1.4.2 for launcher script fix

### ISSUE THREAD

**Issue by gubespam** [grails/grails-core#10335]
Recently there were a couple fixes to spring boot's launcher script that it uses with executable war files. These fix a problem where relative paths for PID_FOLDER and LOG_FOLDER didn't work correctly.

These should be pulled in to the latest version of Grails:
https://github.com/spring-projects/spring-boot/issues/7092
https://github.com/spring-projects/spring-boot/issues/7093

It looks like these were fixed in spring boot 1.4.2.

**Comment by jeffbrown** [comment]
Is this something that needs to be changed in Grails or something that Grails will just benefit from when upgrading to Boot 1.4.2?

**Comment by gubespam** [comment]
Pulling in the newer version would fix the current bug in handling relative paths, as I mentioned above, so that the workaround is not needed.

The workaround in the mean time is to specify this in build.gradle:
    bootRepackage {
        embeddedLaunchScript = new File("src/main/spring-boot/launch.script")
    }

And then [download the latest script](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script) to your workspace at the location shown above.
