### ISSUE TITLE
Transient properties validated two times

### ISSUE THREAD

**Issue by skorikovdm** [grails/grails-core#10347]
GrailsDomainClassValidator.java was refactored in grails 3 (and 2) and it seems that now there is an error in validate method:
In grails 1 validate method validates persistent properties first, and all properties except persistent after.
In grails 3 validate method validates all properties, and all properties except persistent after.

This results in calling validators on transient fields two times during object validation

### Steps to Reproduce

1. Create new domain class
2. Add transient field to this class
3. Add custom validator to this field
4. Add some output (println) from custom validator
5. Call validate method on object of this class
6. Check the output

### Expected Behaviour

Custom validator called one time for one validate call

### Actual Behaviour

Custom validator called two times for one validate call

### Example Application
https://github.com/skorikovdm/GrailsValidationErrorExample

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

**Comment by skorikovdm** [comment]
Added information

**Comment by skorikovdm** [comment]
Can you merge fix to 2.5.x branch ?
