### ISSUE TITLE
Unit test fails to default not nullable constraints

### ISSUE THREAD

**Issue by bruno-lopes** [grails/grails-core#10343]
This is my first issue to Grails, so I'll try my best to follow the issue guidelines.

### Steps to Reproduce

1. Create a new grails plugin (**grails create-plugin grails323**)
2. Create a domain class with some fields and no user defined contraintsTODO
3. Create a test that tries to save an empty instance of this class
4. Run **grails test-app** command

### Expected Behaviour

The test should fail if an ValidationException, because by default Grails defines that fields with no user defined constraints should be not nullable.

### Actual Behaviour

The test passes with success.

### Environment Information

- **Operating System**: Mint 18
- **Grails Version:** 3.2.3
- **JDK Version:** 
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

- **Container Version (If Applicable):** No container

### Example Application

- Link in GitHub: https://github.com/vaidegrails/grails-validation-error

### Full Description
Grails is not validating default not null constraint in tests. The test that passes (and should not) is the following:
```groovy
@TestFor(TestDomain)
class TestDomainSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }

    void "An empty instance should not be saved"() {
        when:
        new TestDomain().save(failOnError: true, flush: true)
        then:
        true
    }
}
```
The domain classes under test is:
```groovy
package grails323

class TestDomain {
    String aString
    Integer aNumber
    Date aDate

    static constraints = {
    }
}
```

**Comment by jeffbrown** [comment]
I expect this has something to do with a problem with processing camel casing with properties that begin with only 1 lower case letter.  If you change `aString` to `someString` or change `aNumber` to `someNumber`, you will see different behavior.

**Comment by jeffbrown** [comment]
Btw... Something like this is a better way to test this:

```groovy
package grails323

import grails.test.mixin.TestFor
import grails.validation.ValidationException
import spock.lang.Specification

@TestFor(TestDomain)
class TestDomainSpec extends Specification {

    void "An empty instance should not be saved"() {
        when:
        new TestDomain().save(failOnError: true)

        then:
        thrown ValidationException
    }

    void "An empty instance does not validate"() {
        expect:
        !new TestDomain().validate()
    }
}
```

**Comment by bruno-lopes** [comment]
@jeffbrown, thanks for your response. I changed the property names, and now it works as expected. Also, thanks for the test tips. I updated the test code in Github according to your tips.
