### ISSUE TITLE
databinding of collection fails if one element has constraints violation

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#10349]
We have a view where the user can create and object (Invoice) and add several elements (InvoiceItem) to a collection of the object.

```
class Invoice {

    String subject

    static hasMany = [
            items: InvoiceItem
    ]

    static constraints = {
    }
}

class InvoiceItem {

    String name

    String description

    static belongsTo = [invoice: Invoice]

    static constraints = {
    }
}
```

Now if we want to update the invoice and/or some of the items we send all inputs in one request. Something like:

id=1
subject=Network
items[0].id=1
items[0].name=USG
items[0].description=Ubiquiti Unifi Security Gateway
items[1].id=2
items[1].name=UAPACPRO
items[1].description=Ubiquiti Unifi AccessPoint AC Pro

This works perfekt, even if we add new items to the collection. But if one of the item has a constraints violation (e.g. name is null), all values of the following items are not bound to the objects anymore.

We inspected the invoice object and noticed some validation errors:

> Illegal attempt to update element in [items] Set with id [2]. No such record was found.

I debugged a little bit through `GrailsWebDataBinder` and discovered that there is an excpection thrown in `getPersistentInstance` called by `processIndexedProperty`:
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'name' cannot be null

After activating SQL log we see this log when `getPersistentInstance` is called:

> Hibernate: update bs_accounting_invoice_item set version=?, deleted=?, deleted_date=?, deleted_user=?, description=?, invoice_id=?, name=?, position=?, quantity=? where id=? and version=?
> ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Column 'name' cannot be null

Is this behavior (the update to the DB) expect or is this maybe a bug? The action looks like this:
```
def save(Invoice invoice, CustomerSelectCommand customerSelectCommand) {
    // ...
}
```

### Environment Information

- **Operating System**: MacOS Sierra 10.12.1 (16B2555)
- **Grails Version:** 3.2.3
- **JDK Version:** 1.8.0_72

**Comment by jeffbrown** [comment]
> But if one of the item has a constraints violation (e.g. name is null), all values of the following items are not bound to the objects anymore.

That surprises me, in part because constraints are not inspected until after all of the data binding is complete.  

Can you create a small sample project which demonstrates that behavior and provide a link to that project?  That will help is track down the specifics.  Thanks for your feedback.

**Comment by jeffbrown** [comment]
I just re-read the report and I see now that the update is happening as part of data binding.  As suggested above, having a sample app which demonstrates the behavior will help identify the specifics, but this does look like a bug.

Thanks again for the feedback.

**Comment by andreasschiestl** [comment]
@jeffbrown I am busy this week, but i will create a demo app next week
