### ISSUE TITLE
Problem With Build Script dependencies

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#10341]
When creating a 3.2.3 application using the `rest-api` profile and requesting the `markup-views` feature, multiple `views-gradle` dependencies are generated in `build.gradle`.

```
grails create-app someapp --profile rest-api --features markup-views
```

`build.gradle` in the generated project will include the following:

```
buildscript {
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "org.grails.plugins:views-gradle:1.1.1"
        classpath "org.grails.plugins:views-gradle:1.1.2"
    }
}

...
```

This may be observed by creating a project using the command shown above and may also be observed when generating an application using The Grails Application Forge site.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails-profiles/base/commit/d6c55b421b1a46303f1e48925aeb9589ad7cb368
