### ISSUE TITLE
Integration Spec injected "serverPort" incorrect during setupSpec

### ISSUE THREAD

**Issue by abobwhite** [grails/grails-core#10357]
### Steps to Reproduce

1. Create an integration spec with `@Integration` annotation
2. Access injected `serverPort` within static context of `setupSpec`, port is not correct (i.e. 8080 vs random port actually assigned)
4. Change `setupSpec` to `setup` and accessing `serverPort` is correct

### Expected Behaviour

I would expect `serverPort` to be correct anywhere it is referenced within the spec. In my case, I am invoking an authentication call which only need be done once per spec (i.e. `setupSpec`)

### Actual Behaviour

`serverPort` is incorrect within `setupSpec`

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.1.14
- **JDK Version:** 1.8.0_101

This should be easily reproducible but I can take the time to create a sample repo if absolutely needed.

**Comment by jeffbrown** [comment]
@abobwhite I know why this is and will look into possible solutions.

Are you using the port number in `setupSpec` to instantiate a REST client?

**Comment by abobwhite** [comment]
@jeffbrown That is correct. We are calling `/api/login` once during `setupSpec` in order to get an access token that is stored for each test in the spec to test authenticated API endpoints. For now, doing this during `setup` is sufficient but as our tests grow, the redundant logins will add up in test execution time.

**Comment by graemerocher** [comment]
@jeffbrown how do you plan to solve this? Tricky to solve because `setupSpec` is run before Spring is initialised and since Spring injects the value of the property it is too early to have this resolved.

**Comment by jeffbrown** [comment]
> @jeffbrown how do you plan to solve this?

I don't know if it is solvable, at least without some hackery.  It may be the case that we just need to document the behavior.

There is an issue that could be improved and that is the fact that the port number is being assigned in the test constructor but it is being assigned a value that may or may not be valid by the time the tests run.  I don't think that is useful and is potentially confusing.

**Comment by abobwhite** [comment]
> There is an issue that could be improved and that is the fact that the port number is being assigned in the test constructor but it is being assigned a value that may or may not be valid by the time the tests run. I don't think that is useful and is potentially confusing.

@jeffbrown Agreed. This is what I was seeing and confused me for hours thinking I was doing something incorrectly in a base class and then in a trait (attempting different methods - i.e. spit-balling). The value for `serverPort` kept getting set to `8080` in `setupSpec`

**Comment by jeffbrown** [comment]
@abobwhite 

> For now, doing this during setup is sufficient but as our tests grow, the redundant logins will add up in test execution time.

You may have a number of options for dealing with that.  One thing that might work is you could have your test implement `org.springframework.beans.factory.InitializingBean` and then make the call from the `afterPropertiesSet()` method.  Can you give that a spin and let me know if that does what you need?

**Comment by jeffbrown** [comment]
Actually, that might not help.  That might get executed multiple times too.

**Comment by jeffbrown** [comment]
I think this has been addressed via `@OnceBefore`.  Code that otherwise might have been in `setupSpec` which relies on DI should instead be implemented in an instance method which is marked with `@OnceBefore`.

I think this can be closed.

**Comment by abobwhite** [comment]
Yes, `@OnceBefore` worked for us beautifully. Thanks
