### ISSUE TITLE
GroovyCastException when invoking TestFor generated getters in tests

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-core#10363]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails artefact (domain, controller, or service) with a property of `name`, or a `getName()` method.
2. Create a test that references the artefact as the class under test with the `@TestFor` annotation.
3. Invoke the generated getter for the artefact in the test (`getDomain()`, `getController()`, `getService()`).

### Expected Behaviour

For artefacts that don't have a `name` property there are no problems and an instance of the artefact is returned by the getter. I would expect the same to hold true if there is a `name` property.

### Actual Behaviour

Instead, the getter throws a `GroovyCastException`. For a domain class, `Bar`:
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'class foo.Bar' with class 'java.lang.Class' to class 'foo.Bar'
	at foo.BarSpec.class under test getter throws exception(BarSpec.groovy:11)
```

From what I can tell, the exception is thrown in the getter method in the process of checking if the bean exists in the application context. I've tried decompiling the compiled test and for an artefact _without_ a `name` property, the AST generated code looks something like this:

```groovy
applicationContext.containsBean(Bar.class.getName())
```

For an artefact _with_ the `name` property, the AST generated code looks like this:

```groovy
applicationContext.containsBean(((Bar)ScriptBytecodeAdapter.castToType((Object)Bar.class, (Class)Bar.class)).getName())
```

This seems to be the cast that is throwing the exception. The relevant source code seems to be in [TestForTransformation](https://github.com/grails/grails-core/blob/master/grails-plugin-testing/src/main/groovy/org/grails/compiler/injection/test/TestForTransformation.java#L466), but I'm honestly not sure if this is actually more of an issue with the Groovy AST transform api itself.

### Environment Information

- **Operating System**: macOS Sierra 10.12.1
- **Grails Version:** 3.2.3
- **JDK Version:** 1.8.0_101

### Example Application

This bug report has three test classes (one for each kind of artefact). The tests pass if an exception is thrown when invoking the getter.
[foo-bug-report-17122016.zip](https://github.com/grails/grails-core/files/659110/foo-bug-report-17122016.zip)

**Comment by jeffbrown** [comment]
The .zip file linked above is not runnable in its current state.

Would you test the project at https://github.com/jeffbrown/issue10363 and let me know if the problem occurs for you there?  I can't reproduce the problem.

Thanks for the feedback.

**Comment by dpcasady** [comment]
Sorry about that .zip file. Yeah it still happens on that project.

Are the tests failing for you? Maybe it's a bit counter-intuitive, but they should _pass_ if the exception is thrown:

```groovy
void "class under test getter throws exception"() {
    when:
    getDomain()

    then:
    thrown(ClassCastException) // test should pass if the bug is present
}
```

**Comment by jeffbrown** [comment]
> Maybe it's a bit counter-intuitive, but they should pass if the exception is thrown

Ok.  I was looking for failing tests.  I see now.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
See https://github.com/jeffbrown/issue10363/commit/d71e0240b606f3754378076a144033d6a597baf6.  That makes more sense to me as the tests now describe how the system is supposed to behave.
