### ISSUE TITLE
domain classes and loggers

### ISSUE THREAD

**Issue by Philip-Wu** [grails/grails-core#10362]
When trying to run the grails application using the command "grails run-app", I encountered the following error:

 FAILURE: Build failed with an exception.  
 * What went wrong:  
 Execution failed for task ':bootRun'.  
 > Process 'command '/usr/java/jdk1.8.0_101/bin/java'' finished with non-zero exit value 1  

Even after looking at the stacktrace, it wasn't clear what was causing this error. And it seems from many google searches, that there are multiple reasons for getting such an error. But none of the solutions helped me.

As it turns out, it seems Grails 3.x doesn't like having Loggers declared in domain classes.

For example, I had the following class definition:

 class MyDomainClass {  
   Logger logger = Logger.getLogger(MyDomainClass.class)  
 }  

Once I removed the Logger declaration, then my application ran successfully. I know from experience, that previous versions of Grails 2.x allowed loggers in domain classes, but it seems it's not supported anymore?

**Comment by jeffbrown** [comment]
In Grails 3 there should be a `log` property automatically added to your domain classes.

**Comment by jeffbrown** [comment]
If you really wanted to declare your own logger (you probably shouldn't, you can do it with something like this:

```
import org.slf4j.Logger
import org.slf4j.LoggerFactory

class Foo {
    static Logger myLogger = LoggerFactory.getLogger(Foo)

    // ...
}
```
