### ISSUE TITLE
Replacing configuration @@ placeholders breaks html5 audio element

### ISSUE THREAD

**Issue by lploom** [grails/grails-core#10370]
After a horrible debugging session I have found out that this line in build.gradle is responsible for breaking the html5 audio element. I have no idea if this is actually grails or browser/tomcat/gradle issue. Neither did I feel like digging deeper.
```
processResources {
    filter(ReplaceTokens, tokens: ['info.app.name': 'test']) // this line breaks html5 audio element
}
```
This line was probably used to replace the @info.app.name@ in configuration files. 

### Steps to Reproduce
1. clone this repo https://github.com/lploom/grails-bug
2. comment out the filter(ReplaceTokens ... ) line in build.gradle
3. gradle clean war deploy
4. open app, click the toggleAudio button on the main page. The audio is correctly played.
5. undo the comment in build.gradle
6. gradle clean war deploy
7. audio no longer works

### Environment Information
- **Operating System**: arch-linux
- **Grails Version:** 3.2.3
- **JDK Version:** 1.8.112
- **Container Version (If Applicable):** run-app through intellij 2016.3 ide, using the provided gradle wrapper

**Comment by graemerocher** [comment]
I don't understand, why did you add that line to your build and why is this a Grails problem?

**Comment by jeffbrown** [comment]
I also don't know why that `processResources` is being added to the build file but I expect what is happening is token substitution is fouling up the `.wav` file.  

With your `processResources`:

```
$ ls -l build/resources/main/public/sounds/ring6.wav 
-rw-r--r--  1 jeff  staff  403654 Dec 20 16:46 build/resources/main/public/sounds/ring6.wav
```

Without your `processResources`:

```
 $ ls -l build/resources/main/public/sounds/ring6.wav 
-rw-r--r--  1 jeff  staff  200044 Dec 20 16:46 build/resources/main/public/sounds/ring6.wav
```

> I have no idea if this is actually grails or browser/tomcat/gradle issue.

I don't think it is a browser bug or a Tomcat bug or a Gradle bug or a Grails bug.  I think the problematic behavior is the result of the way `ReplaceTokens` is being used in that project.
