### ISSUE TITLE
Release gdm 5.0.13

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#10380]
The 3.1.x branch current depends on gdm 5.0.13.BUILD-SNAPSHOT.

https://github.com/grails/grails-core/commit/41b7c3b7028bb127d0dc58e9edab6165533e6596#diff-c197962302397baf3a4cc36463dce5eaR35

This should be addressed before releasing 3.1.15.

Related to #9986.

**Comment by demon101** [comment]
@jeffbrown Any estimation? 
We are waiting for release of 3.1.16 version
