### ISSUE TITLE
Data binding: request for configuration option to disable lenient date parsing

### ISSUE THREAD

**Issue by krond** [grails/grails-core#10387]
### Steps to Reproduce

1. Create a command object with a java.util.Date property
2. Create an action with this command object as a parameter
3. POST Request to this action with a date property value outside the allowed range (e.g. with month 15)

### Expected Behaviour

In most business environments, a date which is outside the expected range (month between 1-12), is considered an invalid date. So I expect a date with the input value 2016-15-05 to be rejected as an invalid date.

### Actual Behaviour

The date is always parsed lenient. This is a problem, because invalid date like 2016-15-05 are always accepted by the grails databinding. There is also no configuration option to change this behavior.

The implementation is found in the class _org.grails.databinding.converters.DateConversionHelper_. As I can see in the source code, the SimpleDateFormat uses the default configuration and doesn't explicitly set the "lenient" property. There should be a configuration option to set this property.

### Environment Information

- **Grails Version:** 3.x
- **JDK Version:** 1.8

**Comment by snimavat** [comment]
This is inconsistent with FormattedDateValueConverter -- which always does lenient = false

**Comment by snimavat** [comment]
I think probably no one intentionally wants to allow lenient date and so probably no need to make it configurable. FormattedDateValueConverter sets lenient to false always anyway.

I have given a PR for this.

**Comment by jeffbrown** [comment]
Related to #9667

**Comment by snimavat** [comment]
@jeffbrown i have made change to cache the configured formats, if we can incorporate that change as well that would be a good performance improvement.. we import thousands of records in batch, and not parsing all the formats each time for each date field would be nice.

**Comment by jeffbrown** [comment]
> i have made change to cache the configured formats, if we can incorporate that change as well that would be a good performance improvement

I am pretty sure that what is currently in the PR is not thread safe and would work for your batch imports but would break concurrent request handling.  Am I mistaken about that?

**Comment by snimavat** [comment]
You are right, what are your thoughts, should we not cache at all ? what do you think abt synchronizing ?
