### ISSUE TITLE
Improvement: Make grailsPublish block not mandatory when publishing plugins & profiles to internal repository

### ISSUE THREAD

**Issue by pawelhalasa** [grails/grails-core#10398]
In order to publish plugins and profiles to internal maven repo, I have tried to use `grails-plugin-publish` and `grails-profile-publish` plugins respectively. They do their work well, but display an error if `grailsPublish` block with all its attributes is not defined in `build.groovy`. Even though I don't plan to publish plugins to Grails Central Repository, I need to add `grailsPublish` block with number of fake values. Can we make it optional instead?

### Steps to Reproduce

1. Create a new plugin or profile
2. Remove `grailsPublish` block from `build.config` (since we don't plan to publish to Grails Central Repository)
3. Define your nexus repo in build.config
```
publishing {
    repositories {
        maven {
            credentials {
                username "foo"
                password "bar"
            }
            url "http://foo.com/repo"
        }
    }
}
```
4. Run `gradle publish`

### Expected Behaviour

Plugin/Profile is published to respective maven repo

### Actual Behaviour

```
:generatePomFileForMavenPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generatePomFileForMavenPublication'.
> Could not apply withXml() to generated POM
   > No 'websiteUrl' was specified. Please provide a valid publishing configuration. (...)
```

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_111

**Comment by graemerocher** [comment]
The validation is important if you plan to publish to Grails central.

However we can maybe add a configuration value to like `central = false` to disable certain validation if you are not publishing to central

**Comment by pawelhalasa** [comment]
This would be nice. Alternatively I could even imagine simpler option without separate config value (if only possible)
- If `grailsPublish` block is included, then publish task should validate all of the attributes as it does today. 
- Otherwise, it should not try to publish to Grails central, thus don't need to validate.
