### ISSUE TITLE
Endless exception loop in GrailsExceptionResolver when uploading files and using an error controller

### ISSUE THREAD

**Issue by benorama** [grails/grails-core#10391]
### Task List

- [ x] Steps to reproduce provided
- [ x] Stacktrace (if present) provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an `ErrorsController`

```groovy
class ErrorsController {

    def error() {
        response.status = 500
        render 'ERROR'
    }

    def notFound() {
        response.status = 404
        render 'NOT FOUND'
    }
}
```
2. Replace default URL mappings  to use the `ErrorsController`

```groovy
"/"(view:"/index")
"500"(controller: 'errors', action:'error')
"404"(controller: 'errors', action:'notFound')
```
3. Upload a file bigger than 200Ko

### Expected Behaviour

It should call the `error` action of the `ErrorsController`.

### Actual Behaviour

It creates an exception loop in `GrailsExceptionResolver`

### Environment Information

- **Operating System**: MacOSX 10.12.2
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_25

### Example Application

- https://github.com/benorama/grails-mapping-errors

**Comment by snimavat** [comment]
there's a loop of exception GrailsDispatcherServlet.checkMultipart -> GrailsExceptionResolver -> forward request to error controller ->  GrailsDispatcherServlet.checkMultipart
