### ISSUE TITLE
Suggestion: replace grails-specific logging AST transformation with the one shipped with Groovy

### ISSUE THREAD

**Issue by davidkron** [grails/grails-core#10392]
I would like to suggest, that the grails-specific logging AST transformation should be replaced with the `@Slf4j` annotation, which is by default shipped with Groovy.

I see the following advantages:
- standardized logging between Grails and Groovy
- Grails developers don't have to maintain a separate implementation
- performance improvements (see code below)

I don't know Grails deep enough to know, if there are technical limitations with the Groovy solution, which are preventing using it. But from a user's point of view I can see only advantages with the suggested solution.

### Expected Code (Groovy)
The following code can be written in a class using the Groovy `@Slf4j` annotation:
```
// a simple log message
log.debug 'e-mail notification sent'

// complex log message, which could cause performance bottlenecks
log.debug "sending e-mail notifications to addresses: ${calculateRecipients()}"
```
The advantage of this variant is that the AST transformation wraps the second log call automatically with an if statement which checks if DEBUG level logging is enabled (similar to the given code below).

### Actual Code (Grails)
In Grails I have to write boilerplate code to check if the logging is enabled:
```
// a simple log message
log.debug 'e-mail notification sent'

// complex log message, which could cause performance bottlenecks
if (log.debugEnabled) {
    // this line has to be wrapped with debugEnabled, or else the performance intensive 
    // call to calculateRecipients() will always be called, even if DEBUG level is not activated!
    log.debug "sending e-mail notifications to addresses: ${calculateRecipients()}"
}
```

### Environment Information

- **Grails Version:** 3.x

**Comment by snimavat** [comment]
@graemerocher does [this](https://github.com/grails/grails-core/commit/1d1fd9412979bd1f8e19546347c91cb05d5ce064#diff-1ce98bcb8e6d7a2763e5e9943c3b8c08R63) mean that the logger name for artefacts would change from "grails.app.xx" to class names ?

**Comment by graemerocher** [comment]
@snimavat good point, maybe we should retain the logger name convention of before

**Comment by snimavat** [comment]
yeah, I think we should have the logger name conventions as before... 
Slf4j annotation supports specifying category value, we can use it i guess.

**Comment by graemerocher** [comment]
I think by default we want to use more standard logging names. I think for new comers the old conventions are confusing.

If you wish to use the logger name conventions from before you can always do that by adding your own annotation. The new approach provides that flexibility.

I will update the upgrade notes for the change.

**Comment by snimavat** [comment]
the old standard convention made it quite easy to turn logging on/off for entire app, and selective artefact types.... including artefacts provided by plugins/third party, the change will be non backward compitible, and each app will need to adjust their logging configurations..

Given, that we have the ability to explicitely put annotation on the class..
Cant we keep the default as it was earlier, and if user wants the different category name, he can manually annotate the class.

**Comment by jameskleeh** [comment]
Typically applications have a common package, so turning on/off for the whole app is not an argument against the new behavior. The same goes for plugins.

The only feature lost is the ability to log by artefact types out of the box, however making it easier for people new to the framework to understand by changing the convention to be simpler is a bigger win. If you want to log by artefact types, you could always move your artefacts into a different package (`com.foo.controllers`).

Note that this is for 3.3.x and above.

**Comment by snimavat** [comment]
Moving artefacts to different package to turn logging on/off doesnt sound good.. 

Also not all plugins follow the standard package conventions, and we wont have control on new plugins either...

When it was done on the first place, i am sure the grails developers would have thought that doing it this way would be better

I am not against the change, its just thoughts.
but i am not sure its difficult for new comers ? -- did we have tickets that say its confusing... how did we conclude that it was difficult ?

**Comment by graemerocher** [comment]
It is confusing that for example plugins like spring-security-core and spring-security-rest use `@Slf4j` from Groovy and therefore logging cannot be enabled for this plugins by the `grails.app` convention, whilst for other plugins it works.

Most of the arguments against this change can be resolved by good package naming conventions. You will have control over new plugins by configuring loggers for their package names.

**Comment by snimavat** [comment]
Alright, lets go with this, i think a community consensus would have been great before it goes into a release, but not many ppl would care i guess...

The only main thing is, ability to configure loggers based on artefact types, regardless of package.

**Comment by hakanernam** [comment]
"The only main thing is, ability to configure loggers based on artefact types, regardless of package."

I think this would be the loss of a very nice feature. Since moving artefacts to special packages just because of logging would effect code organisation negatively,  I cannot see it as a solution.  

So this is a negative the reporter did not foresee. I guess if it will really save framework developers, we can live with more complicated logger configuration file.

**Comment by graemerocher** [comment]
In terms of using Groovy's transforms, they already accept a category argument, so we can of course still support the current behaviour.

The debate on here is whether the current behaviour is the correct behaviour or confusing to new users. 

The current behaviour was added at a time when Grails was very much more a scripting framework and often you wouldn't even have your controllers within a package. So it made sense to add a package.

Since then Grails has evolved from those Groovy scripting to be more robust and structured, calling that original design decision into question. However, we are interested to hear user input on this issue. IMO a well structured codebase in terms of packages would provide you with the same benefit, but I'm willing to be convinced otherwise.
