### ISSUE TITLE
TagLib: pageScope.hasVariable doesn't see variables from parent scope

### ISSUE THREAD

**Issue by krond** [grails/grails-core#10402]
When I try to check if a variable exists in the pageScope with `pageScope.hasVariable(name)` inside a taglib, the parent pageScope is not considered, e.g. when I put the taglib call inside a template rendered by `<g:render>`

I discovered this problem by using the fields-plugin, which internally uses the pageScope to access its bean stack (`<f:with>`). I have posted an in-depth analysis of the error in case of the fields-plugin in their issue tracker: https://github.com/grails-fields-plugin/grails-fields/issues/194

Other discoveries:
- `pageScope.setVariable` seems to consider the parent scope
- `pageScope.variables.containsKey(name)` works with parent scope

### Steps to Reproduce

- create a tag which calls `pageScope.hasVariable(name)`
- create a template which calls this tag
- render template with `<g:render>`

MyTagLib.groovy
```
class MyTagLib {

    static namespace = "my"

    def scopeTest = {
        // doesn't work in sub-scope
        def a = pageScope.hasVariable('myVar') 
   
        // does work in sub-scope
        def b = pageScope.variables.containsKey('myVar')

        out << a << ' ' << b
    }
}
```

_test.gsp
```
<my:scopeTest/>
```

index.gsp
```
<g:set var="myVar" value="test"/>
<g:render template="test"/>
```

### Expected Behaviour
Taglib will print the string "true true".

### Actual Behaviour
Taglib prints the string "false true".

### Environment Information
- **Grails Version:** 3.1.x

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues
