### ISSUE TITLE
Error on use hasMany map

### ISSUE THREAD

**Issue by wgaalves** [grails/grails-core#10409]
This bug occurred today when I was upgrading my application from version 2.5.5 to 3.2.4 I think because I used hasMany with 2 classes ex:

static Hasmany = [ item1:Item1, item2:Item2]

on my app 2.5.5 its works with no problems,Should work the same, right?

here stacktrace  [stacktrace.txt](https://github.com/grails/grails-core/files/711459/stacktrace.txt)
### Steps to Reproduce

1.  create 3 domains  Room,PointX,PointY
2.  on PointX and PointY  use static belongsTo = [room:Room] and on PointX  write a atribute Room destiny 
3.  on Room  use hasMany = [pointX:PointX, pointy:PointY]

It will stay like this

```
class Room {
    static hasMany = [pointx:PointX,pointy:PointY]
    String name
    static constraints = {
    }
}

class PointY {
    static  belongsTo = [room:Room]
    Room destiny
    static constraints = {
    }
}

class PointY {
    static  belongsTo = [room:Room]
    Room destiny
    static constraints = {
    }
}
```

### Expected Behaviour

run  app  with no errors

### Actual Behaviour

Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Constructor threw exception; nested exception is org.hibernate.MappingException: Foreign key (FKs5pmycas388de5bjcr8k2a002:pointy [])) must have same number of columns as the referenced primary key (room [id])
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.2.4
- **JDK Version:** java version "1.8.0_111"

### Example Application

https://github.com/wgaalves/BugHasManyGrails3.2.4

**Comment by jeffbrown** [comment]
This isn't mentioned in the description but the code includes the following:

```
package org.grails.bug

class PointY {

    static  belongsTo = [room:Room]

    Room destiny

    static constraints = {
    }
}
```

I think that `Room destiny` is relevant.

**Comment by wgaalves** [comment]
Sorry 
I just improved the description.

**Comment by theleancoder** [comment]
Why do you want to use an instance of Room in PointY?

**Comment by wgaalves** [comment]
Its only on example !!!

My real case is 

I have one House , these house have rooms , in the rooms have portals 
Portal BelongTo Room  and have destiny other room.

Each room have one portal when you click  you go to destiny room!!!

Sorry my bad english.

**Comment by theleancoder** [comment]
I could understand and help well if you post the original code.

**Comment by wgaalves** [comment]
no problem , i already used an "workaround" 

but   the same code  run com  grails 2.5.5  it is bug. i will wait   fixes .

for now i using

```
class Portal{
    Room room
    Room destiny
    static constraints = {
    }
}
```

this works for now.

**Comment by graemerocher** [comment]
You can resolve the issue in your application with this in `Room`:

```groovy
static mappedBy = [pointx: 'room', pointy: 'room']
```

I have committed a change which fixes the problem, although the mapping is still slightly ambiguous so you are better off using an explicit `mappedBy` IMO
