### ISSUE TITLE
Cannot find OLD JIRA ticket

### ISSUE THREAD

**Issue by hamza3202** [grails/grails-core#10413]
HI
I am having an issue with using multiple criteria queries in a function with multiple data sources.
[Here](http://grails.1312388.n4.nabble.com/Connection-is-closed-question-td4641804.html) somebody was facing a similar issue and according to him, He opened a ticket [here](http://grails.1312388.n4.nabble.com/Connection-is-closed-question-td4641804.html) but that is a link to the Old JIRA based issue tracker. I tried searching for it but couldn't find it at GIT. Was it ever resolved? What was the solution?

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
