### ISSUE TITLE
circular service references work in 2.x, fail in 3.2

### ISSUE THREAD

**Issue by kgeis** [grails/grails-core#10417]
I am upgrading an application from Grails 2.5.0 to 3.2.4.

### Steps to Reproduce

Service `identityService` references service `investigatorStatusService`, and vice versa. Beans are explicitly specified in `resources.groovy`. Logging in to the application exercises the `identityService`.

### Expected Behaviour

Circular references are valid in Spring, and in Grails 2.5.0, the application starts without complaints.

### Actual Behaviour

> Error creating bean with name 'identityService': org.springframework.beans.factory.FactoryBeanNotInitializedException: FactoryBean is not fully initialized yet

### Environment Information

- **Operating System**: macOS 10.12.2
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_111
- **Container Version (If Applicable):** n/a

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by jeffbrown** [comment]
> Beans are explicitly specified in resources.groovy. 

Why is that?

**Comment by jeffbrown** [comment]
See the project at https://github.com/jeffbrown/issue10417.  That demonstrates circular references between services in a Grails 3.2.4 app.

```
package demo

class DemoController {

    IdentityService identityService

    def index() {
        int result = identityService.firstMethod()

        render "The Result: $result"
    }
}
```

```
package demo

class IdentityService {

    InvestigatorStatusService investigatorStatusService

    int firstMethod() {
        investigatorStatusService.secondMethod()
    }

    int thirdMethod() {
        42
    }
}
```

```
package demo

class InvestigatorStatusService {

    IdentityService identityService

    int secondMethod() {
        identityService.thirdMethod()
    }
}
```

**Comment by kgeis** [comment]
Thanks, Jeff, for creating a minimal example. Because your example works, I see that my problem is deeper than what I described. I’ll look into it for a few days and try to get more detail about why I am getting the exception.

**Comment by kgeis** [comment]
Thanks again for your attention and sorry for the noise. I had a confusing storm of misconfiguration that gave me this error.
