### ISSUE TITLE
Grails - Cannot get property 'id' on null object

### ISSUE THREAD

**Issue by cihanzengin** [grails/grails-core#10418]
here is i have some problem.

I have 2 domain class and i want to pass some parameter from one to second domain class and save on second.

Here is first domain class Car

```
package carrentco

class Car {

    String brand
    String model
    String fuelType
    BigDecimal pricePerDay

    static constraints = {
        brand(inList:["AUDI", "BMW", "MERCEDES", "NISSAN", "HONDA", "FORD"])
        model()
        fuelType(inList:["FUEL", "DIESEL", "AUTOGAS"])
        pricePerDay(min:0.0, max:1000.0)

    }
}
```

And here is second one Registration

```
package carrentco

class Registration {

    String firstName
    String lastName
    Date dateOfBirth
    String phoneNumber
    String email
    Date startOfRentDate
    Date endOfRentDate
    Car rentedCar

    static constraints = {
        firstName(nullable: false)
        lastName(nullable: false)
        dateOfBirth()
        phoneNumber(phoneNumber: true, nullable: false)
        email(blank:false, email:true)
        startOfRentDate()
        endOfRentDate()
    }
}
```

```
What i wanna do; I create some cars list and i added to cars/index.gsp some button to each car (RENT CAR) when user click to this button he go to registration/create.gsp here user add some details of himself like name surname etc. I want to get here Car id which one he select from car/index.gsp automatically and save this form. When admin will look to this registration record he will see to Which car user want to rent.

here is my cars/index.gsp
```

```
<g:each in="${carList}" var="car">
                <p>${car.id} </p>
                <g:link action="create" controller="registration" params="${[carId : car.id ]}">
                    Rent Car
                </g:link>

            </g:each>
```

and here is my registration/create.gsp

```
<g:form action="save">
    <div><p>Car ID : ${car.id} </p></div>
    <fieldset class="form">
        <f:all bean="registration"/>
    </fieldset>
    <fieldset class="buttons">
        <input type="hidden" name="carId" id="carId" value="${car?.id}"/>
        <input type="text" name="yourName" required>
        <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
    </fieldset>
</g:form>
```

when i write this code i get this error,

> URI
> /registration/create
> Class
> java.lang.NullPointerException
> Message
> Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/registration/create.gsp:38] Error executing tag <g:form>: Error evaluating expression [car.id] on line [29]: Cannot get property 'id' on null object
> Caused by
> Cannot get property 'id' on null object

When i tried this one in registration/create.gsp

```
<g:form action="save">
                <fieldset class="form">
                    <f:all bean="registration"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
```

Everything is okey. I can save the registration form with car id, But here i need to select from list which car id. So i don't want this i want this was selected automatically because if i click to rent car button from car list example car id 2 why i need to select in registration form again car id it's not good.

here is my registration controller.

```
package carrentco

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RegistrationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Registration.list(params), model:[registrationCount: Registration.count()]
    }

    def show(Registration registration) {
        respond registration
    }

    def create() {
        respond new Registration(params)
        def selectedCar = Car.get(params.carId)
        [car: selectedCar]
    }

    @Transactional
    def save(Registration registration) {

        if (registration == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return

        }

        if (registration.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond registration.errors, view:'create'
            return
        }

        registration.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'registration.label', default: 'Registration'), registration.id])
                redirect registration
            }
            '*' { respond registration, [status: CREATED] }
        }
    }

    def edit(Registration registration) {
        respond registration
    }

    @Transactional
    def update(Registration registration) {
        if (registration == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (registration.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond registration.errors, view:'edit'
            return
        }

        registration.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'registration.label', default: 'Registration'), registration.id])
                redirect registration
            }
            '*'{ respond registration, [status: OK] }
        }
    }

    @Transactional
    def delete(Registration registration) {

        if (registration == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        registration.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'registration.label', default: 'Registration'), registration.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'registration.label', default: 'Registration'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}
```

i can't understand what i need to do for solve this problem.

**Comment by theleancoder** [comment]
In your `index.gsp` file, you've used params like this:

`<g:link action="create" controller="registration" params="${[carId : car.id ]}">`

The `params` attribute accepts a **map** of request parameters that you can send to a controller action. The correct syntax is:

`<g:link action="some action" controller="some controller" params="[key1 : 'value1, key2: 'value2, key3: 'value3',... ]">`

Try this and then tell me.

**Comment by cihanzengin** [comment]
@theleancoder thank you, i tried that but nothing changed, you sure that problem is that? 

When i click to rent car button under Car2 in registration form page not select the 2.car id automatically 
![screen shot 2017-01-22 at 18 06 37](https://cloud.githubusercontent.com/assets/1409879/22183369/a9c4c846-e0cd-11e6-8cfd-f344ae13a29c.png)

**Comment by theleancoder** [comment]
Check if you're getting the params parameter in the `create` action of `RegistrationController`.

`log.debug(params: params)`

**Comment by cihanzengin** [comment]
@theleancoder , if in registration/create.gsp i see in rented car field car id and can save this mean yes i get parameters. I'm asking about how in rented car field i can show that id which one user selected.

**Comment by theleancoder** [comment]
Okay, I understand. I think the statements after this line in the `create` action are not executed. Check if there even being executed?

`respond new Registration(params)`

I think the problem is that the `create` action returns when `respond` is called leaving the other statements not executed. That's why `car.id` is null in `create.gsp`.

**Comment by cihanzengin** [comment]
Need to modified like that?
```
def create() {
        respond new Registration(params)
        def selectedCar = Car.get(params.carId)
        [car: selectedCar]
        return
    } 
```

**Comment by theleancoder** [comment]
Try this:

```
def create() {
        def selectedCar = Car.get(params.carId)
        respond new Registration(car: selectedCar)
    }
```

**Comment by cihanzengin** [comment]
@theleancoder i tried but. 
again get this error. 

in case my registration/create.gsp
```
  <g:form action="save">
                <div><p>Car ID : ${car.id} </p></div>
                <fieldset class="form">
                    <f:all bean="registration"/>
                </fieldset>
                <fieldset class="buttons">
                    <input type="hidden" name="carId" id="carId" value="${car?.id}"/>
                    <input type="text" name="yourName" required>
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
```


```
[URI
/registration/create
Class
java.lang.NullPointerException
Message
Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/registration/create.gsp:38] Error executing tag <g:form>: Error evaluating expression [car.id] on line [29]: Cannot get property 'id' on null object
Caused by
Cannot get property 'id' on null object](url)
```

**Comment by theleancoder** [comment]
Remove these lines from `create.gsp` and then check.

`<div><p>Car ID : ${car.id} </p></div>`
`<input type="hidden" name="carId" id="carId" value="${car?.id}"/>`

You don't need these lines now.

**Comment by cihanzengin** [comment]
@theleancoder  yes when add these line everything is working but again i'm saying problem is this ; 

this is my cars/index.gsp . when i click to rent car button under id2 

![screen shot 2017-01-22 at 18 06 24](https://cloud.githubusercontent.com/assets/1409879/22184538/ce986940-e0e4-11e6-9e13-5a48de6549ad.png)


in registration/create.gsp i need change again car id 2 so i want if i click to rent car under car id 2 this will be automatically selected.  It's possible? 
![screen shot 2017-01-22 at 20 54 31](https://cloud.githubusercontent.com/assets/1409879/22184560/1860de9a-e0e5-11e6-96e6-265c80be99fc.png)

**Comment by theleancoder** [comment]
What you can do is create separate form fields for each of the properties of `Registration` class and then fetch the car id from the params.

The `fieldset` tag is used for creating form fields for a domain class. It does't not accept class properties dynamically at run time. That's why it is showing all the cars from the `car` table in the database.

**Comment by cihanzengin** [comment]
@theleancoder i understand logic a little bit but i can't realise it on code i think :/

**Comment by theleancoder** [comment]
This can help.
[https://grails-fields-plugin.github.io/grails-fields/](url)

**Comment by cihanzengin** [comment]
@theleancoder  page not found :)

**Comment by theleancoder** [comment]
Please check again.

**Comment by cihanzengin** [comment]
@theleancoder Okey i'll check now thank u
