### ISSUE TITLE
Reload and Class not found exception raised while using MyBatis

### ISSUE THREAD

**Issue by chaitanya9249** [grails/grails-core#10415]
I am using Mybatis plugin version 0.0.3.Its installed successflly in grails 2.4.2.Now the problem is I am working on Mybatis plugin as follow with this doc:
**http://fzilic.github.io/Grails-MyBatis/guide/workingWithMyBatis.html**
But While I was executing the application with run-app command I am getting below exceptions:

Error |
Caused by: org.springsource.loaded.ReloadException: Problem defining class org.grails.mybatis.example.person__I

Error |
Caused by: java.lang.NoClassDefFoundError: org/grails/mybatis/example/person__I
(wrong name: org/grails/mybatis/example/Person__I)

I have checked with this github also : https://github.com/fzilic/Grails-MyBatis-Test
But exceptions are not resolved.Please help me anyone to resolve these issues...

If you can please fwd your answers to mail "chaitu.modela99@gmail.com"

**Comment by graemerocher** [comment]
Please report to https://github.com/spring-projects/spring-loaded/issues
