### ISSUE TITLE
JSONObject toString() does not cope with arrays properly

### ISSUE THREAD

**Issue by frangarcia** [grails/grails-core#10412]
The class org.grails.web.json.JSONObject does not seem to represent the String of an instance properly when talking about arrays (not JSONArray). I have created a project in github with this issue at https://github.com/frangarcia/jsonobject, but basically this is the problem:

```
import org.grails.web.json.JSONObject

org.grails.web.json.JSONObject jsonObject1 = new JSONObject([id:1, tags:['tag13333', 'tag2231']])
render "tags field is a ${jsonObject1?.get('tags').class.name}<br/><br/>"//tags field is a java.util.ArrayList which is fine

render "but then the string representation of the jsonobject is not represented as an array list"
render "${jsonObject1.toString()}<br/><br/>"//It renders {"id":1,"tags":"[tag13333, tag2231]"} where tags is represented as a quoted string

render "Generating org.grails.web.json.JSONObject for the string ${jsonObject1.toString()} as the variable jsonObject2<br/><br/>"//If we take that string representation and try to create another JSONObject

org.grails.web.json.JSONObject jsonObject2 = new JSONObject(jsonObject1.toString())
render "tags field is a ${jsonObject2?.get('tags').class.name}<br/><br/>"//tags field is a java.lang.String
```

Steps to reproduce it:

1. Check out the project https://github.com/frangarcia/jsonobject
2. The project uses grails 3.1.10
3. grails create-app
4. Go to http://localhost:8080/demo

### Expected Behaviour

The String representation of the json object is proper for array fields

### Actual Behaviour

The String representation of the json object renders Strings where Arrays should be

### Environment Information

- **Operating System**: Mac OS Sierra
- **Grails Version:** 3.1.10, 3.1.14, 3.2.4
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

### Example Application

https://github.com/frangarcia/jsonobject

https://gist.github.com/frangarcia/12e8a9872e25fa6af2e8ae4845c81c19

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-core/commit/e7a6472dc2d27dafdea79cc45e270e8ba5dc2707
