### ISSUE TITLE
AntBuilder is not getting recognized in grails 3.2.4

### ISSUE THREAD

**Issue by imadi** [grails/grails-core#10419]
### Steps to Reproduce

Please add `def ant = new AntBuilder()`

### Expected Behaviour

Class should get complied without any errors

### Actual Behaviour

 unable to resolve class AntBuilder
 @ line 145, column 35.
                       def builder = new AntBuilder()

 When I have seen externalLibraries I don't see AntBuilder class in groovy 2.4.7 that got added. Is this expected behaviour?

### Environment Information

- **Operating System**: MAC OS
- **Grails Version:** 3.2.4
- **JDK Version:** 1.7

**Comment by graemerocher** [comment]
You need to add `groovy-ant` to your classpath in Grails 3

**Comment by patrick0927** [comment]
graemerocher, 
I am new in Grails 3. Can you show me more detail about what you said "You need to add groovy-ant to your classpath in Grails 3".
Thanks!

**Comment by ricardogobbo** [comment]
> graemerocher,
> I am new in Grails 3. Can you show me more detail about what you said "You need to add groovy-ant to your classpath in Grails 3".
> Thanks!

Just add groovy-ant dependency on build.gradle file

    compile group: 'org.codehaus.groovy:groovy-ant:2.4.7'
