### ISSUE TITLE
Grails 3.2.4: Http header "Cache-Control:no-store" on static resources causes slow response and high http traffic

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#10410]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Full description
All static resources located in src/main/webapp are served with Http header "Cache-Control:no-store",
this causes a slow response and a high http traffic as the browser does not use cache and downloads these resources every time.
I've tried to set the header (response.setHeader('Cache-Control', 'max-age=600')) using an Interceptor or a Filter with no luck,
it is set to 'no-store' later in the response chain.

Is it possible to change this behaviour?

### Steps to Reproduce

1. create an empty 3.2.4 app
2. add some static resource to src/main/webapp for example src/main/webapp/css/style.css
3. run-app
4. Open http://localhost:8080/static/css/style.css
5. Check the Http response header

### Actual Behaviour

All static resources are served with Http header "Cache-Control:no-store"

### Environment Information

- **Operating System: Linux 64 bit
- **Grails Version: 3.2.4
- **JDK Version: 1.8.0_111
- **Container Version: Tomcat 8

### Example Application
[myapp.zip](https://github.com/grails/grails-core/files/711479/myapp.zip)

**Comment by graemerocher** [comment]
You can configure `grails.resources.cachePeriod` and set it to whatever you want in `application.yml`

**Comment by barcelona23** [comment]
Is there any documentation? It's hard to find it.
`grails:
    resources:
        cachePeriod: 120`
It's not working for me.

![image](https://cloud.githubusercontent.com/assets/221474/25723727/74c08d0c-30d6-11e7-8665-1bf54ce664ae.png)

**Comment by ginchauspe** [comment]
On 3.3.9 add `grails.resources.cachePeriod=number` in your `application.groovy`

**Comment by erichelgeson** [comment]
I was a bit curious about this so dug in a bit - as a work around you can add your own no-cache ResourceHandler for index.html and then have the static resources use the cachePeriod - Though I think it'd be worth while to add this in as an option in grails as SPA's being used more often.

```groovy
@Configuration
class SpaResolverConfig implements WebMvcConfigurer {
    private static final String[] CLASSPATH_RESOURCE_LOCATIONS = ["classpath:/public/"]
    
    @Override
    void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler('/static/index.htm*') // needs to be an antmatcher
                .addResourceLocations(CLASSPATH_RESOURCE_LOCATIONS)
                .setCachePeriod(0)
    }
}
```
