### ISSUE TITLE
Domain object Map constructors do not work properly during intgration tests

### ISSUE THREAD

**Issue by R-Mark** [grails/grails-core#10420]
I am in the process of building a Grails 3.2.4 rest api plugin. The plugin is to be populated with quite a few GORM objects migrated from a Grails 2.3.11 project. In the end, we wish to use this plugin to provide a common domain object backbone as we break up the original application into several micro-services.

We have security service that is accessible from each of the domain classes to perform auditing.  It works by looking for a user name on the remote header.  As part of our integration test initialization, we have been performing the following:

```
MockHttpServletRequest httpRequest = new MockHttpServletRequest()
httpRequest.addHeader('remote_user', getUserName())
GrailsWebRequest webRequest = new GrailsWebRequest(httpRequest, new MockHttpServletResponse(), new MockServletContext())
WebUtils.storeGrailsWebRequest(webRequest)

```
When I store the web request, we notice all our domain objects Map constructors do not properly assign values to their appropriate properties.  This issue https://github.com/grails/grails-core/issues/9755 seems to note a very similar problem.

**Comment by jeffbrown** [comment]
Please provide a sample project which demonstrates the problem.

Why are you registering your own request (`WebUtils.storeGrailsWebRequest(webRequest)`)?

**Comment by R-Mark** [comment]
May of our domain objects are required to perform auditing on insert/update.  We have a security service that looks for a header entry on the HTTP request called 'remote_user'.  The security service  uses that header entry to look up who you are so that any updates to the entity are attributed to the correct person.

For us to prevent exceptions in our integration tests with the security service, I need to bind a http request prior with the correct header.

Attaching a sample project to demonstrate the problem.  Please see OrderIntegrationSpec.

[domain-map-constructor.zip](https://github.com/grails/grails-core/files/727092/domain-map-constructor.zip)
