### ISSUE TITLE
Grails 3.2.4 Interceptors are not working as expected

### ISSUE THREAD

**Issue by imadi** [grails/grails-core#10425]
### Steps to Reproduce

Include ` matchAll().except(controller:'home')` in the interceptor constructor
PFB, full snippet
`package com.adi.interceptor

class FirstInterceptor {

    def springSecurityService

    public FirstInterceptor() {
        matchAll().except(controller:'home')
    }

    boolean before() {
        println "hello"
        true
    }

    boolean after() {
        true
    }

    void afterView() {}
}
`

### Expected Behaviour

It should match all controllers except home

### Actual Behaviour

It's matching home controller also

### Environment Information

- **Operating System**: Mac
- **Grails Version:** 3.2.4
- **JDK Version:**1.7

**Comment by graemerocher** [comment]
Can't reproduce this personally, please provide an example that reproduces the issue

**Comment by imadi** [comment]
Please find sample code [here](https://github.com/imadi/InterceptorTest)

**Comment by jeffbrown** [comment]
I ran the linked project and it appears to be working as designed.  I don't think the interceptor is running when requests are sent to the `home` controller.

**Comment by imadi** [comment]
My Bad. Can you please change  `matchAll().except(controller: 'home')` to `matchAll().excludes(controller: 'home')` and try :) also It didn't match test controller too :)

**Comment by imadi** [comment]
Closing the issue. Got the mistake I have done :)

**Comment by imadi** [comment]
However I load some static resources and give something like `matchAll().excludes(controller: 'static')` its is not working. I need to write something like this inorder to escape static controller 
`if (controllerName != "static"){}`

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
