### ISSUE TITLE
Domain class map constructor don't work  after upgrade to Grails 3

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10422]
Can't instantiate properly domain class in async code  after upgrade to Grails 3, usual map constructor not works.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

```
Domain1.async.task {
    //...... long processing
    Domain1.withTransaction {
....
       def d =  new Domain2(field:'value')
       assert d.field  // -- fail, filed is empty 
    }
}
```

### Expected Behaviour

Domain class instantiated properly

### Actual Behaviour

1. Domain class instantiated without field values.
2. And in errors of domain just after creation I see following error:   

> Error in object 'xxx.domain': codes []; arguments []; default message [null]
3. Nothing written to the log. Please, add log.debug at DataBindingUtils line 245 

 Same code works well in grails 2.4.5

### Environment Information

- **Grails Version:** 3.1.14
- **JDK Version:** 8

### Example Application

- TODO: Not simple to reproduce in a test app, If you realy need it, will provide it tomorrow 

> java.lang.NullPointerException
> 	at org.apache.catalina.connector.Request.getServletContext(Request.java:1618)
> 	at org.apache.catalina.connector.RequestFacade.getServletContext(RequestFacade.java:1024)
> 	at javax.servlet.ServletRequestWrapper.getServletContext(ServletRequestWrapper.java:408)
> 	at javax.servlet.ServletRequestWrapper.getServletContext(ServletRequestWrapper.java:408)
> 	at javax.servlet.ServletRequestWrapper.getServletContext(ServletRequestWrapper.java:408)
> 	at javax.servlet.ServletRequestWrapper.getServletContext(ServletRequestWrapper.java:408)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
> 	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
> 	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:64)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
> 	at org.grails.web.mime.HttpServletRequestExtension.getMimeTypes(HttpServletRequestExtension.groovy:70)
> 	at sun.reflect.GeneratedMethodAccessor930.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
> 	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
> 	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
> 	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
> 	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:64)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
> 	at org.grails.web.mime.DefaultMimeTypeResolver.resolveRequestMimeType(DefaultMimeTypeResolver.groovy:53)
> 	at org.grails.web.mime.DefaultMimeTypeResolver.resolveRequestMimeType(DefaultMimeTypeResolver.groovy:51)
> 	at grails.web.mime.MimeTypeUtils.resolveMimeType(MimeTypeUtils.groovy:34)
> 	at grails.web.databinding.DataBindingUtils.resolveMimeType(DataBindingUtils.java:339)
> 	at grails.web.databinding.DataBindingUtils.getMimeType(DataBindingUtils.java:321)
> 	at grails.web.databinding.DataBindingUtils.createDataBindingSource(DataBindingUtils.java:308)
> 	at grails.web.databinding.DataBindingUtils.bindObjectToDomainInstance(DataBindingUtils.java:234)
> 	at grails.web.databinding.DataBindingUtils.bindObjectToDomainInstance(DataBindingUtils.java:152)
> 	at org.grails.plugins.web.controllers.api.ControllersDomainBindingApi.initialize(ControllersDomainBindingApi.java:68)
> 	at xxxxxxxxx.<init>(Page.groovy)
> 	at sun.reflect.GeneratedConstructorAccessor123.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>

**Comment by demon101** [comment]
Hi @graemerocher , I hope, fix also will be included in grails 3.1.x branch

**Comment by demon101** [comment]
looks simular to #10420

**Comment by graemerocher** [comment]
And  #9755

**Comment by graemerocher** [comment]
Also relates to #10436

**Comment by demon101** [comment]
@graemerocher I got this NPE in the service method, not in a controller

**Comment by graemerocher** [comment]
The root cause is the same

**Comment by demon101** [comment]
@graemerocher , now I see it, agree
