### ISSUE TITLE
ConfineMetaClassChanges + TestFor + FreshRuntime cause static method metaclass change to leak

### ISSUE THREAD

**Issue by berdario** [grails/grails-core#10427]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/secretescapes/grails-test-bug , use grails2 to run the following command
2. run `grails test-app unit: spock.bug.FooSpec spock.bug.BarSpec spock.bug.BazSpec`

### Expected Behaviour

The test in BazSpec should pass

### Actual Behaviour

The test fails, due to the `LocaleContextHolder` metaClass change leaking through, despite `ConfineMetaClassChanges`

### Environment Information

- **Operating System**: Linux
- **Grails Version:** Grails 2.5.5
- **JDK Version:** openjdk version "1.8.0_111"

### Example Application

- https://github.com/secretescapes/grails-test-bug : link to github repository with example that reproduces the issue

I witnessed this issue on Grails 2.5.4, I reproduced it with Grails 2.5.5. Grails 3 (I tested 3.2.3) doesn't seem to be affected. I originally thought that this would be a Spock bug (hence the name of the example project), but since Grails 2 and Grails 3 are using the same version of Spock at the moment, the answer is not as clear cut.

To clearly see the minimal example, [this is the commit](https://github.com/secretescapes/grails-test-bug/commit/a65fa39f8db2179a14ca8e5b95b3e7ad1fe0fab7) you'd want to have a look at

I'm not sure if Grails 2 is still supported: the last release was in June, but it doesn't seem to be clearly stated anywhere if that version is now unsupported.

Since the end result is that `ConfineMetaClassChanges` doesn't properly confine the changes, there might be an underlying Spock bug that they'd want to fix, but the Grails core developers are the ones best placed to understand what's causing Grails to trigger this behavior.

Any small change will make this bug disappear: if you run the tests in a different order, if you remove the `TestFor` annotation, if you remove the `FreshRuntime` annotation(!!!), if you merge `FooSpec` and `BarSpec`... the bug will not show up

**Comment by graemerocher** [comment]
Grails 2.x is in maintenance mode and only blocking bugs and bugs reported by OCi support customers are being fixed. Please upgrade to Grails 3.x.
