### ISSUE TITLE
In Grails >=3.2.1 domain class properties with certain names cause IllegalArgumentException 

### ISSUE THREAD

**Issue by michaelkanis** [grails/grails-core#10428]
### Description

In Grails 3.2.1 through 3.2.4 certain names for domain class properties cause a problem, if used with a constraint. 3.2.0 is the last version that doesn't show the problem. It seems that the problem is triggered by property names with a single leading small letter (aTitle).

### Steps to Reproduce

1. grails create-app helloworld
2. grails create-domain-class book
3. Add a property "String aTitle" to Book
4. Add constraint "aTitle nullable true"
5. In BootStrap.groovy create an instance of domain class and call save()
6. grails run-app

### Expected Behaviour

App starts up normally.

### Actual Behaviour

Throws <pre>java.lang.IllegalArgumentException: object is not an instance of declaring class</pre>
Stacktrace: https://gist.github.com/michaelkanis/0355c3051ee994de7f77f89775548cfe

### Environment Information

- **Operating System:** Mac OS X 10.11
- **Grails Version:** 3.2.1, 3.2.2, 3.2.3, 3.2.4
- **JDK Version:** Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### Example Application

[helloworld.zip](https://github.com/grails/grails-core/files/729368/helloworld.zip)

**Comment by JanKanis** [comment]
This is the same issue as I reported in #10403
