### ISSUE TITLE
NPE when saving nested domain instances in a non web environment

### ISSUE THREAD

**Issue by tkvw** [grails/grails-core#10436]
- [V] Steps to reproduce provided
- [V] Stacktrace (if present) provided
- [V] Example that reproduces the problem uploaded to Github
- [V] Full description of the issue provided (see below)

### Steps to Reproduce
1. Save a nested domaininstance in Bootstrap, i.e.: new Company(relation: new CompanyRelation(address: new RelationAddress()))
### Expected Behaviour
The instance should be saved entirely regardless of webrequest availability. 

### Actual Behaviour
NullpointerException

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.1.12
- **JDK Version:** 1.8

### Example Application

- https://github.com/tkvw/grails-plugin-controller-bug

// Added @see github README: 
Bugreport example

BugSpec contains two tests, with the same nested save on a domain object.

Test one fails, because it can't setup bidirectional associations because it can't find the domainclass of the entity it needs to save. This fails on org.grails.plugins.web.controllers.apiControllersDomainBindingApi '@' getDomainClass. @see: https://github.com/grails/grails-core/blob/6ffdf8b0a13868e9f99178be966ece627a248355/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/api/ControllersDomainBindingApi.java

Test two succeeds, because there is a webrequest available.

I use situation one on Bootstrap initialization and in Quartz jobs, I think this should work regardless of webrequest.

**Comment by tkvw** [comment]
For a possible solution: https://github.com/grails/grails-core/pull/10437

**Comment by tkvw** [comment]
Shouldn't this be abstracted away from the controller plugin and added to Gorm?

**Comment by graemerocher** [comment]
GORM should not include any web specific extensions so no
