### ISSUE TITLE
The message method in controllers should work without GSP

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-core#10439]
### Expected Behaviour

```
class FooController {
    def index() {
        mesage(...)
        ...
    }
}
```
   
should work

### Actual Behaviour

No signature of method: Controller.message() is applicable for argument types

### Environment Information

- **Operating System**: macOS
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8

**Comment by jeffbrown** [comment]
This is not a duplicate of #10302, but is related.
