### ISSUE TITLE
Vertical tab "\v" is not allowed in JSON

### ISSUE THREAD

**Issue by Guigoz** [grails/grails-core#10438]
Grails BasicJsonEncoder is converting the Unicode Vertical Tabulation (\u000B) to the \v notation : https://github.com/grails/grails-core/blob/master/grails-encoder/src/main/groovy/org/grails/encoder/impl/BasicJSONEncoder.java#L64

However, the \v is not allowed by JSON specs (rfc 7159) AS you can see on : 
- http://www.json.org/  ('char' part in the right panel)
- https://tools.ietf.org/html/rfc7159#section-7

As a result, lot of JSON parsers are crashing.

Thanks for your help,
Greetings,
Guillaume.

**Comment by graemerocher** [comment]
Do you know whether simply removing the check is the appropriate fix or whether it should be encoded as another escape sequence?

**Comment by Guigoz** [comment]
Hi Graeme,

It should be kept with the \u000B notation.
So I think you'll need to escape the backslash like the two other unicode caracters escaped in this method.

**Comment by Guigoz** [comment]
I'm currently using grails 2.X on the impacted project.
Will you provide this fix to the 2.X branch too?
We don't have lots of options or workarounds to fix this bug.

**Comment by graemerocher** [comment]
Unlikely, Grails 2.x is in maintenance mode and only blocking bugs and bugs reported by OCi support customers are being fixed.

**Comment by Guigoz** [comment]
Do you know a simple/possible workaround for grails 2.X ?
We can't use metaclasses because it's Java code.

I don't ask you to include this in 2.X, juste an idea on how to resolve this problem. This bug is critical for us, because the JSON returned by the controller is invalid, and the JS code is crashing because of this.

Thanks for your help

**Comment by graemerocher** [comment]
There are multiple ways to render JSON in Grails 2.x pick the one that works for your use case

**Comment by vojtechruz** [comment]
@Guigoz What workaround did you end with for Grails 2.x please? Thank you.

**Comment by Guigoz** [comment]
Hi @vojtechruz
We haven't found any workaround =/
We just haven't encounter this evil \v sign since the last time, but the problem is not solved.
Feel free to post your solution here if you find one. ;)

**Comment by vojtechruz** [comment]
@graemerocher Could you please point me to the alternative JSON rendering which should work for 2.x you mentioned above? Thank you.
