### ISSUE TITLE
View gets rendered 2 times when forwarding

### ISSUE THREAD

**Issue by selbin01** [grails/grails-core#10443]
View gets rendered 2 times when forwarding 

### Steps to Reproduce
1. Run sample program
2. Click save link in sample - in foo controller
3. Look at console log - it forwards and renders then renders a second time.

### Expected Behavior
render once

### Actual Behavior
renders twice
1st time from RequestForwarder - dispatcher.forward(request, response);
2nd time as it leaves RequestForwarder - return fowardURI

### Environment Information
- **Operating System:** Windows
- **Grails Version:**  3.1.15
- **JDK Version:** Java 8

### Example Application
https://github.com/selbin01/sample

**Comment by ColinHarrington** [comment]
@selbin01 this is what I'm seeing the log:
```
In new save going to forward to save
In save going to render view
Hits taglib to build body
Hits taglib to build body
```
and the response coming back is correct only containing one set of output from the `<il:body>` tag

**Comment by ColinHarrington** [comment]
It does appear that the view layer is being engaged twice there.  I'm seeing that the `forward(..)` is being dispatched via the [RequestForwarder](https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/grails/artefact/controller/support/RequestForwarder.groovy#L111) which returns the `fowardURI` as you identified and the first controller action is resolving the result of the downstream `ModelAndView` in the [UrlMappingsInfoHandlerAdapter.groovy](https://github.com/grails/grails-core/blob/master/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/mvc/UrlMappingsInfoHandlerAdapter.groovy#L100)
