### ISSUE TITLE
Grails 3.2.5 Springloaded Issue

### ISSUE THREAD

**Issue by ahmedmorad** [grails/grails-core#10456]
After Upgrade from Grails 2.5.5 to 3.2.x
## 
i face issue that new controller not reloaded

i try two tway 

**1- using intellij 16.3.4**

-           using run-app
-           using bootRun

       both of them only reload any modification to exist controller
       and make issue when modify a domain class and make the application stop

**2 - using Terminal**

-      grails run-app
-      gradle bootRun

   and the result is the same like intellij

i tried to use spring-dev-tools but it make the application restart at any modification , the application take around 3 minutes to restart and this issue waste more time

i use in build.gradle :

```
bootRun {
    jvmArgs = ['-Dspring.output.ansi.enabled=always', '-Dgrails.reload.enabled=true', '-Ddisable.auto.recompile=false', "-Xms4048m", "-Xmx4048m"]
}

grails {
    pathingJar = true
    exploded = true
}

grails {
    agent {
        enabled = true
    }
}
```

_**I also try JRebel and i get the same results**_

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.5
- **JDK Version:** jdk1.8.0_121

**Comment by ibmsoft** [comment]
i have the same problem

**Comment by demon101** [comment]
for me, in Idea 2016 everything works well with

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
}

**Comment by ibmsoft** [comment]
@demon101 which grails version you use? i use grails 3.2.8,idea 2017
