### ISSUE TITLE
Event handlers for non-default-datasource domain objects are not called

### ISSUE THREAD

**Issue by JanKanis** [grails/grails-core#10451]
Event handlers on domain classes for non-default datasources are not called. In my particular case the default datasource is a Postgres db and the alternate one an H2 file, so it could be that that is important too but I haven't checked.

So far I have discovered that only a single `EventTriggeringInterceptor` is registered, only the one for the default datasource. Therefore the event handlers on domain classes for the other datastore are not called. I have not had time to dig further to see why this is the case.

In grails 3.1.10 this still worked, in 3.2.3 it does not.

### Steps to Reproduce

1. Create a project with a postgres and an H2 datasource, make the postgres the default.
2. Create a domain class that uses the H2 datasource with a `beforeInsert()` event handler method.
3. Create and save an instance of the domain class.

### Expected Behaviour

The `beforeInsert()` method is called.

### Actual Behaviour

The `beforeInsert()` method is not called

### Environment Information

- **Operating System**: Ubuntu 16.10
- **Grails Version:** 3.2.3
- **JDK Version:**  OpenJDK 1.8.0_91
- **Container Version (If Applicable):** n/a

**Comment by graemerocher** [comment]
I pushed a test for this and tried an example app with 3.2.6 and cannot reproduce (see attached
[events-test.zip](https://github.com/grails/grails-core/files/786818/events-test.zip)
)
and cannot reproduce it
