### ISSUE TITLE
Miscall of Interceptor under heavy load

### ISSUE THREAD

**Issue by SouadHadjiat** [grails/grails-core#10458]
Since upgrade from Grails 2 to 3 (actual version 3.2.4), we are facing some issue with one application which gets lot of requests (5000 rpm). We have one Interceptor that matches by controller name (admin), and denies access to unauthorized users. We now get more and more requests that are bloqued by this intercetor although it should not match (~1 for 10000). Can't reproduce it locally, it seems to happen only when app gets lots of requests, we have multiple similar applications with same interceptors and we don't get these errors.

We suspected regex matcher, and changed it to string matcher without luck.

### Example Application

```
class AdminInterceptor {

    Raven raven

    AdminInterceptor() {
        match(controller: 'admin')
    }

    boolean before() {
        raven?.sendMessage("User IP '${InetAddressUtil.getAddress(request)}' is not allowed to access $controllerName $actionName")
        true
    }
    
    boolean after() {
        true
    }
}
```

**Comment by benorama** [comment]
We also notice that this issue slowly grows with time, here are 403 errors growing after each deployment: 
<img width="1218" alt="capture d ecran 2017-02-09 a 17 24 32" src="https://cloud.githubusercontent.com/assets/394356/22792345/b8008fa8-eeec-11e6-8a3b-02714d9f2382.png">

There is clearly an issue here.

**Comment by ColinHarrington** [comment]
@benorama @SouadHadjiat These types of issues that happen under load can be difficult to reproduce and diagnose.    Even though you're unable to reproduce it locally, can you put together a small example application that you believe would show the issue under heavy load? 

There are some things we can try by tuning threadpools & load tests that might help expose an issue if ends up being a concurrency issue with the framework.

**Comment by benorama** [comment]
Hi Colin,

Indeed, these use case is probably going to be difficult to reproduce/analyze...
So I tried to create a very basic app that mimics the behaviour of the interceptor that have the issue on our production app.

Here it is:
https://github.com/benorama/grails-interceptors-issue

You might try to run it under load and access public views (/index, /foo, /monitor) and see if you get errors in the logs coming from the `AdminInterceptor` (that should never be matched for the above paths).

Thanks!

**Comment by jeffbrown** [comment]
> We now get more and more requests that are bloqued by this intercetor although it should not match

What do you mean by "bloqued"?  Are you saying that all of those requests are being handled synchronously by the interceptor so they are queuing up?  Are you saying that your interceptor is returning `false` when you expect it to return `true`, effectively blocking requests from getting through?  Something else?

Thanks for any clarification.

**Comment by benorama** [comment]
We suppose that the issue is linked to interceptors matchers that are incorrectly executed under heavy load, probably because of some race condition issue.
On our app, it is blocking some requests because it incorrectly executes an `AdminInterceptor` that send 403 and log the incorrect access with user IP.
We have added the `controllerName` and `actionName` in the logs to check what kind of path where denied and we saw that it was public `controllerName` / `actionName` that should not be intercept by this `AdminInterceptor` (which should only match 3 of our controllers).
In the provided sample app, it mimics the behaviour of this interceptor.
Other interceptors might be impacted, but we could only identified the issue on this one because of the logs.

This issue is not very frequent, that's why we mainly only see it on our most loaded app (with peaks at 5000 rpm across 3 servers).
I hope this helps.

**Comment by benorama** [comment]
If that helps, we could also try to add logging (checking the match) to other app interceptors, in order to check if this issue on other interceptors as well.

**Comment by graemerocher** [comment]
So I tried to reproduce the issue with siege and JMeter and was not able to so far. Looking at the code we cache the result of the interceptor match in the request object:

https://github.com/grails/grails-core/blob/master/grails-plugin-interceptors/src/main/groovy/grails/artefact/Interceptor.groovy#L83

This is to avoid having to match multiple times in the life time of the same request. If something is going wrong I can only think that what is happening is that a thread is being re-used by the JVM whilst its request state has not been fully cleaned up.

This would be a race condition at the container level. We could remove the caching and take the extra performance hit in the case of multiple matches. However, we would need to know of removing the caching would actually solve the problem and that would require feedback from someone that is actually able to reproduce the problem.

**Comment by benorama** [comment]
Hi Graeme, we can definitely reproduce and monitor the issue with NewRelic (checking 403 errors) or logging an error in Sentry.
I can also confirm that we have the issue on other Interceptors in other Grails3 apps.
What could we do to help you to test a fix?

**Comment by graemerocher** [comment]
@benorama I have pushed a potential fix to a branch, but it is a bit like shooting in the dark. It removes the caching to avoid potential cache misses in a concurrent scenario. Please try it out by adding:

```groovy
compile "org.grails:grails-plugin-interceptors:3.2.7-interceptor-fix.BUILD-SNAPSHOT"
```

To `build.gradle` in your 3.2.6 application. I would be interested to know:

1. Does it fix this issue
2. If you notice any performance regressions for the change.

**Comment by benorama** [comment]
We are going to try this, most probably before the end of the week.
We must first test the upgrade of our apps from 3.2.4 to 3.2.6.
I'll let  you know, thanks!

**Comment by graemerocher** [comment]
@benorama you can probably test within a 3.2.4 application as well by declaring the dependency above

**Comment by benorama** [comment]
FYI, the fix is running on one of our prod app since yesterday.
It looks like it solved the issue.

In terms of performance, we did not see any significant impact, as you can see on this graph (blue line at 14h00 is the release with the fix).
![capture d ecran 2017-02-23 a 09 16 25](https://cloud.githubusercontent.com/assets/394356/23252501/56f048e6-f9b1-11e6-880b-81d5f92d9484.png)

Today, we are going to do another release with the fix on our most high-traffic app to confirm all of that.

**Comment by graemerocher** [comment]
@benorama Great, I will merge the changes shortly

**Comment by jvdrean** [comment]
@graemerocher Hi ! Just to confirm 3.2.7-interceptor-fix.BUILD-SNAPSHOT is doing well performance-wise, we deployed it on our most heavily charged service 2 hours ago.

![facebook_agorapulse_com_-_new_relic](https://cloud.githubusercontent.com/assets/61268/23267241/6fe93c98-f9ea-11e6-9856-b34aab7459bd.png)

No error about interceptors being mismatched in the meantime either.

Thanks,
JV.

**Comment by graemerocher** [comment]
@jvdrean thanks for the feedback
