### ISSUE TITLE
Groovy sql.rows returns org.postgresql.util.PSQLException: No hstore extension installed

### ISSUE THREAD

**Issue by clessiomendes** [grails/grails-core#10455]
### Steps to Reproduce

1. create a simple sql string with no where clause
2. pass an empty **Map** `[:]` as `params` to `groovySql.rows(sql, params)`
(as workargound, passing an empty **List** to `params` behaves like expected)

### Expected Behaviour

call postgres and run the sql passing no parameters

### Actual Behaviour

No hstore extension installed.. Stacktrace follows:
org.postgresql.util.PSQLException: No hstore extension installed.
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setMap(AbstractJdbc2Statement.java:1707)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setObject(AbstractJdbc2Statement.java:1910)
	at org.postgresql.jdbc3g.AbstractJdbc3gStatement.setObject(AbstractJdbc3gStatement.java:36)
	at org.postgresql.jdbc4.AbstractJdbc4Statement.setObject(AbstractJdbc4Statement.java:47)

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 2.5.4
- **JDK Version:** 1.7
- **Container Version (If Applicable):** N/A
- **Database:** Postgres 9.3.13

### Probable fix
Method `singletonList(Object item)` at `groovy.sql.SQL`

### More information
http://stackoverflow.com/q/39245870/1916198

**Comment by graemerocher** [comment]
Groovy SQL is part of Groovy not Grails. Please report to https://issues.apache.org/jira/browse/GROOVY
