### ISSUE TITLE
g:img tag renders two src properties

### ISSUE THREAD

**Issue by dSquadAdmin** [grails/grails-core#10450]
### Steps to Reproduce

1.
```
 <g:img dir="somedir" file="somefile">
```
2.
 ```
<img src="${resource(dir:'somedir', file:'file')}">
```

### Expected Behaviour

 Output should be as below 
```
<img src="/assets/somedir/somefile">
 <img src="static/somedir/file">
```

### Actual Behaviour

```
<img src="/assets/somedir/fsomefile" src="somedir/somefile" alt="" />
<img src="/static/images" src="/static/somedir/file" alt="" />
```
### Environment Information

- **Operating System**: Ubuntu 16.10
- **Grails Version:** 3.2.5
- **JDK Version:** 1.8

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
Please provide an example application. I added the two tags exactly as you have above in a fresh Grails application with the exception of correctly closing the tags and I see the following:

```
<img src="/static/somedir/somefile">
<img src="/static/somedir/file">
```
