### ISSUE TITLE
rendering JSON not supporting printing root objects

### ISSUE THREAD

**Issue by mizzack** [grails/grails-core#10461]
I'm currently upgrading a 2.4.4 app to 3.2.5, and rendering JSON is no longer working as expected when trying to print already constructed objects.

Using the JSON converter (_test3_ action below) works fine and is more terse, but I'm reporting the regression for posterity.

### Steps to Reproduce

Attempt the following in a controller action:
`

    //doesn't work. - prints {}
    def test1() {
        def jsonObj = [
            foo: "bar",
            blah: "bleh"
        ]

        render(contentType: "application/json") {
            jsonObj 
        }
    }
    
    //works as expected, prints jsonObj as JSON wrapped by "wrapped" object
    def test2() {
        def jsonObj = [
            foo: "bar",
            blah: "bleh"
        ]

        render(contentType: "application/json") {
            wrapped(jsonObj)
        }
    }

    //works as expected. prints an object with foo and blah as keys of the root object
    def test3() {
        def jsonObj = [
            foo: "bar",
            blah: "bleh"
        ]

        render jsonObj as JSON
    }
`

### Expected Behaviour

Should print the object.

### Actual Behaviour

Prints an empty object.

### Environment Information

- **Operating System**: OS X 10.11.6
- **Grails Version:** 3.2.5
- **JDK Version:** 1.8.0_31

**Comment by graemerocher** [comment]
See http://docs.grails.org/latest/guide/upgrading.html#upgrading3x

Topic "JSON Builder Groovy Alignment". The `render` method now uses JSON builder instead.
