### ISSUE TITLE
Interceptor called twice when a controller action has render(status: NOT_FOUND)

### ISSUE THREAD

**Issue by nardhar** [grails/grails-core#10467]
Hi, a grails fan here with a problem

As indicated in the Grails User Guide when creating a rest api step by step, exactly in the "Implementing the **delete** action" the last step for json/xml response is to render a NOT_FOUND http status, but when an interceptor  matches the request the before method executes twice, this only happens when the render() method is used and not with respond()

Here is the required data for reproducing the error

### Steps to Reproduce
1. Create simple rest-api profile app with
```bash
$ grails create-app render-error --profile rest-api
```
2. Created controller action that only renders NO_CONTENT as:
```groovy
package sample
import static org.springframework.http.HttpStatus.*
class RenderErrorController {
    static responseFormats = ['json', 'xml']
    def index() {
        println 'entering index'
        render(status: NO_CONTENT)
    }
}
```
3. Created simple interceptor for all urls
```groovy
package sample
class RenderErrorInterceptor {
    RenderErrorInterceptor() { matchAll() }
    boolean before() {
        println "intercepting: ${controllerName}/${actionName}"
        true
    }
    boolean after() { true }
    void afterView() { }
}
```

### Expected Behaviour
When calling the ```http://localhost:8080/renderError``` through curl it should output:
```
intercepting: renderError/index
entering index
```
and the response should be NO_CONTENT (204)

### Actual Behaviour
In grails 3.2.5 and 3.2.6 (just tested) the output is:
```
intercepting: renderError/index
entering index
intercepting: renderError/index
```
and the response is NO_CONTENT (204) which is ok but the interceptor is executed twice.

In this sample application there is no apparent problem, but as I understand it should just call the interceptor once.

The problem (obviously) is in my real app because I use the render method on a delete action (after successful deletion) and my interceptor uses a service which in turn makes a database query, so in the second interceptor execution it throws a *No Session Found* hibernate error because of the Transactional method on the Service and the response is INTERNAL_SERVER_ERROR (500).

Maybe a workaround would be to use ```respond([:], [status: NO_CONTENT])``` but it just feels wrong.

### Environment Information

- **Operating System**: Linux Ubuntu 16.10 x64
- **Grails Version:** 3.2.5, 3.2.6
- **JDK Version:** 1.8.0_101

### Example Application

- [GitHub repo with the error](https://github.com/nardhar/GrailsRenderError)

I guess that I will follow the respond approach but hope this is fixed soon. Thanks in advance

**Comment by AlexKovynev** [comment]
You make my day. I see another problem with "withNewSession" but root exactly same.

**Comment by graemerocher** [comment]
The reason for this is you have `matchAll` which matches error requests as well, and by returning a status you are instructing the contain to produce a error request using `response.sendError(..)` 

A workaround is to do:

```groovy
        matchAll()
        .except(uri:'/error')
```

This will make sure the interceptor ignores forwards produced by the container.
