### ISSUE TITLE
Static resources under src/main/resources/public not reloading

### ISSUE THREAD

**Issue by mtgleeson** [grails/grails-core#10468]
In Grails 2.X the static html files lived under /web-app/html and would changes would be reloaded without restarting the application. In Grails 3.2.4 the html files (according to the docs) live under /src/main/resources/public/html but changes to the files aren't reloaded and require a restart of the application. 

### Steps to Reproduce

1. grails create-app Dummy
grails run-app
2. navigate to the running app http://localhost:8080
3. create a testing.html file under src/main/resources/public/html
4. try to load the page in the browser http://localhost:8080/static/html/testing.html - get a 404 not found.
5. Restart grails and navigate to http://localhost:8080/static/html/testing.html - now the page loads.
Try edit the html file and reload the page in the browser, no changes are seen.

### Expected Behaviour

Changes to the html files should be reloaded without requiring a restart of the application. 

### Actual Behaviour

The file isn't reloaded. Restart of the app required.

### Environment Information

- **Operating System**: Mac Sierra 10.12.3
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_112
- **Container Version (If Applicable):** Embedded tomcat, running locally.

See for an example https://github.com/mtgleeson/grails-static-resources-issue

**Comment by graemerocher** [comment]
By default they do not, but this can be changed by adding `addResources = true` to `build.gradle`:

```groovy
bootRun {
    ...
    addResources = true
}
```

It could be argued this should be the default, but not every project has static resources that aren't processed through asset pipeline or GSP
