### ISSUE TITLE
Grails 3.2.3 not recognizing or serving JSPs

### ISSUE THREAD

**Issue by tkmilbaugh** [grails/grails-core#10466]
I am working on upgrading an existing Grails version 2.3.7 application to Grails version 3.2.3.

This application, among other things, serves JSPs that are created in a CMS. However, Grails 3.2.3 does not seem to recognize any JSPs and always returns 404.

I have an example project, and have moved the test.jsp to different directories such as src/main/resources, src/main/resources/public, but it made no difference.

### Steps to Reproduce

1. Run example project (https://github.com/tkmilbaugh/jsp-test)
2. Browse to project JSP (http://localhost:8080/jsp-test/test.jsp)
3. Observe 404

### Expected Behaviour

I would expect the JSP to display

### Actual Behaviour

Error: Page Not Found (404)
Path: /jsp-test/test.jsp

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.3
- **JDK Version:** 1.7
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/tkmilbaugh/jsp-test

**Comment by tkmilbaugh** [comment]
ZIP file with example project
[jsp-test.zip](https://github.com/grails/grails-core/files/767463/jsp-test.zip)

**Comment by tkmilbaugh** [comment]
In Grails 2.3.7, all of the JSPs were in web-app, but that was removed for Grails 3, and the upgrade directions indicated that such files should be moved to /src/main/resources, that is why I put the JSPs in that directory (see "File Location Differences" on page "https://docs.grails.org/latest/guide/upgrading.html")

**Comment by bitsnaps** [comment]
I'm afraid this is because IntelliJ Community Edition doesn't support gsp pages, so developers would use jsp pages instead to get a syntax highlighter...

**Comment by burtbeckwith** [comment]
That's a terrible reason to use JSPs in Grails.

**Comment by tkmilbaugh** [comment]
The issue has been solved, JSPs have to be located in src/main/webapp for them to be recognized.
