### ISSUE TITLE
Multipart upload is not working properly

### ISSUE THREAD

**Issue by imadi** [grails/grails-core#10469]
I was uploading a file but instead of CommonMultipart I am getting StandardMultipartFile on the server. I have given maxFileSize and maxRequestSize also in application.yml

### Environment Information

- **Operating System**: MAC
- **Grails Version:** 3.2.4
- **JDK Version:**1.7

**Comment by graemerocher** [comment]
This is a by design, the default resolve is now the `StandardMultipartResolver` in Grails 3
