### ISSUE TITLE
getting 404 after deploying grails war-file profile:web to tomcat 8

### ISSUE THREAD

**Issue by Veeramanikandan1493** [grails/grails-core#10479]
I am having problems with the web profile in grails, when deploying war to tomcat-server I get 404.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. install Grails 3.2.6 & Gradle 3.3
2. install apache-tomcat-8.5.11
3. install Java(TM) SE Runtime Environment (build 1.8.0_111-8u111)
4. grails create-app sampleApp --profile web --features asset-pipeline,json-views,markup-views,mongodb
5. change: compile "org.springframework.boot:spring-boot-starter-tomcat" in build.gradle to provided
6. gradle war
7. copy sampleApp-0.1 to apache-tomcat-8.5.11/webapps
8. restart tomcat
9. navigate browser to http://localhost:8080/sampleApp-0.1/

### Expected Behaviour

- Visual of index page

### Actual Behaviour

1. Apache Http status 404 is shown (not the internel 404 page of the application)
2. I have tried to look through all tomcat logs. 
3. I have found

> 15-Feb-2017 18:38:48.731 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war
15-Feb-2017 18:38:57.438 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.6
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_111-8u111)
- **Container Version (If Applicable):** apache-tomcat-8.5.11

### Example Application

Follow the steps to create example application

[https://github.com/Veeramanikandan1493/sampleApp](https://github.com/Veeramanikandan1493/sampleApp)

**Comment by Veeramanikandan1493** [comment]
If this is an issue, a workaround will be very much appreciated. Thanx in advance.

**Comment by jameskleeh** [comment]
This has been reported multiple times. Try searching the closed issues before creating a new one

https://github.com/grails/grails-core/issues/10196
https://github.com/grails/grails-core/issues/10285

**Comment by Veeramanikandan1493** [comment]
For #9901 & #9676 As I menthioned, I am using Tomcat 8 with Java 8 with Grails on web profile.

#10196 has been mentioned with `provided "org.codehaus.groovy:groovy-ant"` but while creating the app under **web profile** build.gradle doesn't contain it and including it doesn't make any change in behaviour

I am using web profile where #10285 has been raised with **profile:rest-api** have gson visual instead of gsp.

[https://github.com/Veeramanikandan1493/sampleApp](url) here is the sampleApp I have mentioned. Please Somebody take look at this and tell me where did I go wrong. Thanks in advance.

**Comment by jameskleeh** [comment]
@Veeramanikandan1493 Your sample app is not a complete Grails application. It simply has a `build.gradle` and some wrapper files

**Comment by Veeramanikandan1493** [comment]
@jameskleeh I have updated the grails application files.

**Comment by jameskleeh** [comment]
You have marked too many dependencies as provided:
https://github.com/Veeramanikandan1493/sampleApp/blob/master/build.gradle#L38
https://github.com/Veeramanikandan1493/sampleApp/blob/master/build.gradle#L39
https://github.com/Veeramanikandan1493/sampleApp/blob/master/build.gradle#L41

Changing those lines back to `compile` causes it to work correctly.

**Comment by Veeramanikandan1493** [comment]
I had tried them with `compile` but tomcat getting LifeCycleException. so only I have changed all of `"org.springframework.boot` to `provided`. If you have sample application that created with grails 3 web profile kindly share the link.

**Comment by jameskleeh** [comment]
@Veeramanikandan1493 I literally changed those 3 lines and it worked for me. I'm not sure what is causing the LifeCycleException, but that isn't related to this issue

**Comment by Veeramanikandan1493** [comment]
I have tried. Can share the war file and external tomcat version that used to deploy the war file.

**Comment by jameskleeh** [comment]
The war file was produced with `./gradlew clean war` JDK 1.8.0_101 on Tomcat 8.5.11

**Comment by Veeramanikandan1493** [comment]
This is the tomcat log I got while changed those 3 lines and generated war file using `./gradlew clean war` command 
`17-Feb-2017 11:06:00.176 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/ard-l012/Libraries/apache-tomcat-8.5.11/temp
17-Feb-2017 11:06:00.176 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
17-Feb-2017 11:06:00.311 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
17-Feb-2017 11:06:00.331 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
17-Feb-2017 11:06:00.334 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
17-Feb-2017 11:06:00.336 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
17-Feb-2017 11:06:00.337 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 756 ms
17-Feb-2017 11:06:00.399 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
17-Feb-2017 11:06:00.399 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.11
17-Feb-2017 11:06:00.445 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war
17-Feb-2017 11:06:08.611 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17-Feb-2017 11:06:09.209 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/sampleApp-0.1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	... 17 more

17-Feb-2017 11:06:09.212 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/sampleApp-0.1]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

17-Feb-2017 11:06:09.214 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/sampleApp-0.1.war has finished in 8,768 ms
17-Feb-2017 11:06:09.215 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/ROOT
17-Feb-2017 11:06:09.287 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/ROOT has finished in 71 ms
17-Feb-2017 11:06:09.287 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/examples
17-Feb-2017 11:06:09.558 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/examples has finished in 271 ms
17-Feb-2017 11:06:09.558 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/docs
17-Feb-2017 11:06:09.582 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/docs has finished in 24 ms
17-Feb-2017 11:06:09.583 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/host-manager
17-Feb-2017 11:06:09.633 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/host-manager has finished in 51 ms
17-Feb-2017 11:06:09.633 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/manager
17-Feb-2017 11:06:09.672 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/ard-l012/Libraries/apache-tomcat-8.5.11/webapps/manager has finished in 39 ms
17-Feb-2017 11:06:09.682 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-8080]
17-Feb-2017 11:06:09.696 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-8009]
17-Feb-2017 11:06:09.701 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 9363 ms`

**Comment by jameskleeh** [comment]
Right that is a completely different error. Please create a new issue as I think this is legitimate

**Comment by jameskleeh** [comment]
The short of it is that it is missing an implementation of slf4j. If you add an slf4j jar to tomcat/libs or add a compile dependency on an slf4j impl, that will fix the problem. Having said that, it should work out of the box.
