### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by petertulala** [grails/grails-core#10476]
### Steps to Reproduce

I'm using `react` profile, since the CORS is enabled by default there:

```
> grails create-app cors --profile=react
> cd cors/server
> gradle bootRun
```

Make sure that the CORS option is set in configuration file:
```
> cat grails-app/conf/application.yml | grep -n cors
```

Test for CORS headers:
```
> curl -i -X OPTIONS -H "X-Requested-With: XMLHttpRequest" http://localhost:8080
```

### Expected Behaviour

HTTP headers should contain entry `Access-Control-Allow-Origin: *`

### Actual Behaviour

No CORS header in HTTP response.

### Environment Information

```
> grails --version
| Grails Version: 3.2.6
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_102
```

**Comment by jameskleeh** [comment]
You're request is not formed correctly. Ask questions on slack or stackoverflow. You can put a breakpoint here to determine what is missing from your request: https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/filter/CorsFilter.java#L86
