### ISSUE TITLE
Bidirectional relationship with dateCreated on entity throws an exception with save

### ISSUE THREAD

**Issue by tkvw** [grails/grails-core#10485]
Given two entities:

      class User {
            Address address    

            static constraints = {
                  address cascade:'all'
            }
       }
      class Address {
            User user 
            Date dateCreated
            Date lastUpdated

            static constraints = {
                  user nullable:true
            }
      }
And calling:

      new User(address:new Address()).save(flush:true)

Grails will throw an Exception:
org.springframework.dao.InvalidDataAccessApiUsageException: object references an unsaved transient instance - save the transient instance before flushing: test.User; nested exception is org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: test.User

This only happens if you have the dateCreated and lastUpdated properties defined.
I've created a test project to see this behaviour:
https://github.com/tkvw/issue-bidirectional

Furthermore: why does grails think this is a bidirectional relationship?

**Comment by graemerocher** [comment]
I imagine you need to correctly associate both ends of the association. Try:

```groovy
Address addr = new Address()
User user = new User(address:addr)
addr.user = user
user.save()
```

**Comment by graemerocher** [comment]
As for your second question it believes it is bidirectional because you have `User` associated with `Address` and `Address` associated with `User`, not sure why there is any doubt there. Really this use case is better mapped as:

```groovy
  class User {
        static hasOne = [address:Address]
   }
  class Address {
        User user 
        Date dateCreated
        Date lastUpdated

        static constraints = {
              user nullable:true
        }
  }
```

**Comment by tkvw** [comment]
To your first answer: this still fails. 
I refactored the example a bit (to what I actually want to accomplish): 

    class User {
        Address homeAddress
        Address shippingAddress
    
        Date dateCreated
        Date lastUpdated
        
        static hasMany = [alternativeAddresses:Address]
    }
    class Address {
        User user
        
        Date dateCreated
        Date lastUpdated
    }

Calling

    test.User user = new test.User(homeAddress:new Address(),shippingAddress: new Address())
    user.save(flush:true)

Throws: 
    org.springframework.dao.InvalidDataAccessApiUsageException: object references an unsaved transient instance - save the transient instance before flushing: test.Address; nested exception is org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: test.Address

With the User class changed to (removed dateCreated and lastUpdated): 

    class User {
        Address homeAddress
        Address shippingAddress
    
        static hasMany = [alternativeAddresses:Address]
    }

The save is successful. 

To your second answer: I think I made a brain fart, in the example above if grails didn't make homeAddress and shippingAddress bidrectional, they wouldn't appear in the alternativeAddresses list, because the address has a null value for the user for homeAddress and shippingAddress, but not for the alternativeAddresses.
