### ISSUE TITLE
Issue with Promises.task() in service method tries to render 2 responses from the controller

### ISSUE THREAD

**Issue by sarbogast** [grails/grails-core#10486]
In a service method, we try to send some email in a background task using Promises and have the service method return right away so that the controller that calls it can return to the user. This used to work fine in Grails 3.2.3 but it doesn't work anymore in 3.2.6, as apparently tasks are now bound to the request thread.

There is a sample project that reproduces the issue here: https://github.com/sarbogast/AsyncTest

When you load `http://localhost:8080/test` the page doesn't stop to load until the aync task is done and then 2 responses are rendered. 

Here is the Slack conversation I just had with @graemerocher about this:

> **sarbogast**
> Hey guys, we have an issue with Promises that seems to have popped up since we upgraded to 3.2.6 for some reason. We managed to reproduce it in a sample project there (https://github.com/sarbogast/AsyncTest). The problem is that when we launch an asynchronous task in a service with Promises.task(), it seems to block anyway and then the server responds with both the result and an error.
> There might be a problem with the way we are using Promises, that still worked with 3.2.3 and is now failing in 3.2.6
> FYI, what we are doing in the real app inside this task is sending an email, so we would like to have the service return directly while the email sending process continues in the background
> 
> **graeme**
> @sarbogast  the issue is to get these invocations to `task` working the same for controllers and services
> I think the changes that broke your use case are that we create an async request for tasks now if a request is found
> probably you can workaround the issue in your service by doing
> 
>  ```    def serviceMethod() {
>         Thread.start {
>                  sleep(10000)
>         }
>         return "42"
>     }
> ```
> 
> **sarbogast** 
> or use the executor plugin?
> 
> **graeme** 
> right
> the issue is that the `task` method finds an active request
> bound to the thread
> I think to solve both use cases fully we would need to have a `grails.async.web.Promises` class that is distinct from `grails.async.Promises`
> the former for use in controllers and the latter for services
> anyway sounds like it is worth an issue report

So I am hereby reporting the issue.
And in the meantime we are going to try and use the executor plugin.

**Comment by hbogaards** [comment]
This solution doesn't work for us.

When I use the `WebPromises.task` from the Controller to call a Service, I still get this issue.
When I use the `Promises.task` from the Controller or from the Service, I run into issue #9755

**Comment by graemerocher** [comment]
Will take a look

**Comment by hbogaards** [comment]
I'm going to upgrade my example in [hbogaards/grails3-databinding](https://github.com/hbogaards/grails3-databinding) to 3.2.7 and try to demonstrate both cases

**Comment by hbogaards** [comment]
I have upgraded the example in [hbogaards/grails3-databinding](https://github.com/hbogaards/grails3-databinding).

The behaviour of the test app is not identical to our big application (the domain class constructors still work), but you can still see that things go wrong in the logging

**Comment by graemerocher** [comment]
Thanks

**Comment by hbogaards** [comment]
What surprises me was that when I use `Promises.tasks` in a Service that the Closure get wrapped in a `org.grails.plugins.web.async.WebRequestPromiseDecorator`.

I would have only expected that when using the `WebPromises.tasks`

**Comment by graemerocher** [comment]
I pushed a fix for `Promises` still using the web related decorator. Unfortunately there is no way to fix the `addWithPromise` example because the request data is gone by the time data binding gets to happen due to the request being async.

So you would need to read the parameters from the request prior to binding in the async case.

**Comment by hbogaards** [comment]
I will test this Monday or Tuesday, but I think it will work as documented/expected
