### ISSUE TITLE
Environment.warDeployed returns always false

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#10496]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. create new app
2. Use `grails.util.Environment.warDeployed` somewhere
3. make a war
4. run with embedded tomcat or deploy to a standalone tomcat

### Expected Behaviour

that method should return `true` in case  a war was build and deployed/run

### Actual Behaviour

it returns `false`

### Additional
works fine on `grails 3.0.17` !

### Environment Information

- **Operating System**: macOS, Ubuntu 16
- **Grails Version:** 3.1.15, 3.2.5
- **JDK Version:** 1.8
- **Container Version (If Applicable):** Tomcat7/8

**Comment by snimavat** [comment]
looks like it works as expected. Tried with 3.2.7-snapshot
Environment.warDeployed returns true when deployed to tomcat. returns false when running as standalone jar (embedded jar) --

**Comment by jameskleeh** [comment]
Can't reproduce

Grails 3.2.6
Java version "1.8.0_101"
Tomcat 8.5.11
macOS

**Comment by jameskleeh** [comment]
Either upload an example project or **_exact_** steps to reproduce and I'll re-open the project

**Comment by jglapa** [comment]
Hmm I see 2 people were not able to reproduce this thing. 
That's the simplest case I could came up is as follows:

```
jglapa@wolf: grails --version 
| Grails Version: 3.2.6
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_121

jglapa@wolf: grails create-app testWarDeployed
jglapa@wolf: cd testWarDeployed
jglapa@wolf: vim grails-app/init/testwardeployed/BootStrap.groovy
# add println grails.util.Environment.warDeployed to init closure
jglapa@wolf: grails war
jglapa@wolf: java -jar build/libs/testWarDeployed-0.1.war
false
Grails application running at http://localhost:8080 in environment: production
```

**Comment by snimavat** [comment]
when you run the war as standalone jar, warDeployed will not return true.. i think this is behavior

**Comment by jameskleeh** [comment]
@jglapa `isStandaloneDeployed` will return true in that case

**Comment by jglapa** [comment]
As it seems I'm not able to reproduce this with a simple project. My app is quite large, the resulting war is ~`300MB` so I cannot give it as an example. I also don't know how to strip it down to show what's happening.
Is there an other way I could detect if the app is running as war in a container? Based on this I'm loading resources from different places and this now stopped working.
So far this was sufficient:
```
//resources.groovy
...
if (grails.util.Environment.warDeployed) {
         importBeans 'classpath:springSecuritySAMLBeanConfig.xml'   
} else {
         importBeans 'file:grails-app/conf/springSecuritySAMLBeanConfig.xml'
}
....
```

**Comment by jameskleeh** [comment]
@jglapa I would remotely debug the tomcat server and determine why `warDeployed` is returning false
