### ISSUE TITLE
Action show in a RestfulController returns [ null ] when id is instance of a subclass

### ISSUE THREAD

**Issue by ilmoralito** [grails/grails-core#10495]
Trying grails rest-api profile and having the classes Copy and ExtraCopy where ExtraCopy extend of Copy, when calling the action show in the CopyController the ExtraCopy instances return [ null ]. If i call index Baseclass and subclass instances are properly displayed.

This link to github repository reproduces the issue: https://github.com/ilmoralito/simple-example

Scenario 1: curl -i -H "Accept: application/json" localhost:3000/copies
Returns the correct values

Scenario 2: curl -i -H "Accept: application/json" localhost:3000/copies/1
Returns the correct values. Here 1 is instance of the Baseclass

Scenario 3: curl -i -H "Accept: application/json" localhost:3000/copies/3
Returns **[null]**. Here 3 is instance of Subclass ExtraCopy

Operating system: Ubuntu
Grails Version: 3.1.5
Groovy Version: 2.4.6
JVM Version: 1.8.0_121

**Comment by jameskleeh** [comment]
The default show action is

```
    def show() {
        respond queryForResource(params.id)
    }
```

This relies on the default naming conventions when passing data to views. In this case the variable `extraCopy` will be available in the view, however you are only expecting `copy`. I'm not sure anything could be done to make this work better.

To get this to behave correctly regardless of subclass you can override the show action to look like:

```
    def show() {
        [copy: queryForResource(params.id)]
    }
```
