### ISSUE TITLE
How to save foreign keys in grails controller?

### ISSUE THREAD

**Issue by chaitanya9249** [grails/grails-core#10508]
Hi
I have used foreign keys in my application.Here in this EmploySalary is parent table and department is the child table.I have used department as the foreign key  in EmploySalary.But I am not understanding how to save that foreign key in controller in grails.

**domain:
=======
class EmploySalary {

	double salary
	Department department
	
    static belongsTo = [department : Department]

    static mapping = {
    }

	static constraints={
		salary blank:false
	}
}

Save in controller
===============
			empSalary = new EmploySalary()				
			empSalary.department = params.department
			empSalary.salary = params.salary as double
			empSalary.save(flush:true)
If you have any idea..please let me know...

**Comment by jeffbrown** [comment]
Please ask questions in our Slack channel or on the Grails mailing list.

Thanks!
