### ISSUE TITLE
Cannot use withNewSession in integration test with Grails @Rollback annotation

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-core#10503]
I'm moving a project from Grails 2.5.4 to Grails 3.2.6, and having an issue with some integration tests that use withNewSession. I've attached a project with two integration tests that both fail:

BookSpec: Uses Grails' @Rollback and withNewSession. The withNewSession block does not see the data created in the same test outside of the block.

SpringRollbackBookSpec: Uses Spring's @Rollback annotation, as shown in the [Grails user guide](http://docs.grails.org/latest/guide/testing.html#integrationTesting). Receives a HibernateException in the setup block. This looks similar to #9448, which the comments imply should be fixed in 3.2.6.

Do I have the wrong expectation that either of these should work? Is there any way to use withNewSession in a @Rollback-annotated integration test?

### Steps to Reproduce

1. Run Grails test-app -integration or Gradle integrationTest on this project:
[test-rollback.zip](https://github.com/grails/grails-core/files/804860/test-rollback.zip)

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.6
- **JDK Version:** 1.8.0_101

**Comment by graemerocher** [comment]
The `SpringRollbackBookSpec` issue is the same as #10504

With regards to the actual report this is due to previous erroneous behaviour whereby `withNewSession` used the same physical database connection. Now that that has been corrected the transaction is isolated from the secondary connection which has no visibility so the behaviour is as expected.

**Comment by timbonicus** [comment]
Thanks for the quick reply, @graemerocher. Adding the Spring @Transactional annotation makes the SpringRollbackBookSpec behave the same way as the Grails-based example. This behavior makes sense, and was a bit illogical that it worked before.

We're using withNewSession for isolated PostgreSQL session variables, but still want visibility into the data created outside this block. It seems like the logical way to achieve this with rollback is with nested transactions:

```groovy
package test.rollback

import grails.test.mixin.integration.Integration
import grails.transaction.Rollback
import org.springframework.transaction.TransactionDefinition
import spock.lang.Specification

@Integration
@Rollback
class BookSpec extends Specification {
    def testNestedTransaction() {
        given:
        def numberOfBooks = 0
        new Book(name: "Test1").save(flush: true)

        when:
        Book.withTransaction([propagationBehavior: TransactionDefinition.PROPAGATION_NESTED]) {
            numberOfBooks = Book.count()
        }

        then:
        numberOfBooks == 1 // true
    }
}
```

This also requires setting `transactionManager.nestedTransactionAllowed = true` in BootStrap.groovy.

I'll try this approach, let me know if you see any red flags.
