### ISSUE TITLE
grails cli are removed in windows

### ISSUE THREAD

**Issue by jo2012** [grails/grails-core#10518]
since grails 2.3.11, running grails in Windows cmd or powershell hide/remove the command from the prompt.

in grails.bat, the instruction echo. should be added before running java
we should have in grails.bat :
`echo.`
`"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRAILS_OPTS%  -classpath "%CLASSPATH%" org.grails.cli.GrailsCli %CMD_LINE_ARGS%`

could someone update the windows script grails.bat

I have tried to find the code source, but I cannot find how the file is generated.

### Environment Information

- **Operating System**: Window
- **Grails Version:** 3.2.6
- **JDK Version:** 1.8.0_121
- **Container Version (If Applicable):** default

**Comment by jameskleeh** [comment]
I don't understand what the issue here is, or what version of Grails is being discussed. Can you clarify if this is Grails 2.3.11 or Grails 3.2.6?

**Comment by jo2012** [comment]
both, the first time have seen the issu was on grails 2.3.11.
I just updated to grails 3.2.6 and the issue is still there.

the issue is simple.
for exemple when I run th command : `grails -version` 
the text "grails -version" is removed from the prompt and the version info is displayed at the same line as my command.

**Comment by jameskleeh** [comment]
@graemerocher I found commenting this line out resulted in the desired behavior: https://github.com/grails/grails-core/blob/7534a790d2295a3253acf38db343796d99231953/grails-bootstrap/src/main/groovy/grails/build/logging/GrailsConsole.java#L598

**Comment by graemerocher** [comment]
yeah, but that would probably break the current behaviour of `updateStatus` which is to erase the previous line and update the message. The fix would need to include some logic so that the console can know it is the first line being output so as not to erase the terminal input line

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-core/commit/82a84229d0d6b4c2fab5723846d38dfab1d6ae22

**Comment by jo2012** [comment]
a precision : 
this issue is only on the Windows version of grails.
in linux/ubuntu. I dont have this issue.

**Comment by jameskleeh** [comment]
I was able to reproduce in macOs

**Comment by jo2012** [comment]
ok, thanks for the quick reply/fix 
I will be waiting on the release of 3.2.8
:+1:
