### ISSUE TITLE
Grails Central Repo appears to be down

### ISSUE THREAD

**Issue by seanhastings** [grails/grails-core#10513]
I am attempting to run (also clean) a Grails app on 2.4.4 and I'm getting a series of errors like the following: 

`CLIENT ERROR: Not Found url=https://repo.grails.org/grails/plugins/org/grails/plugins/gmetrics/0.3.1/gmetrics-0.3.1-javadoc.jar`

Navigating to that link or https://repo.grails.org/grails/core results in a 404.

**Comment by markusu49** [comment]
I can confirm this.

**Comment by graemerocher** [comment]
We're aware of the issue and it is being worked out. We recommend setting up a local artifactory mirror in your development environments for cases when this happens.

**Comment by jagiro** [comment]
Appears down 
http://repo.grails.org/grails/core

**Comment by giovanniumboh** [comment]
http://repo.grails.org/grails/core down again ??
