### ISSUE TITLE
Flexible controller action argument binding like spring mvc

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10512]
Currently grails supports binding action argument and value objects with request parameters / json
Howerver it is not as flexible as spring MVC and there's no support to extend/hook into this functionality as grails does AST magic and does not support extensions here.

For example Spring MVC supports HandlerMethodArgumentResolver and very flexible with what can be bind to action arguments (eg cookies, session variables, headers etc)

I would like to see the similar flexibility with grails.

**Comment by jameskleeh** [comment]
"there's no support to extend/hook into this functionality as grails does AST magic and does not support extensions here"

I don't believe that is true. You can register a DataBindingSourceCreator bean to do most anything you like.

**Comment by snimavat** [comment]
Ah ok, thanks for pointing it out, i would look into this and update here

**Comment by jameskleeh** [comment]
Closing this. If your investigation needs to specific improvement opportunities, please create another issue
