### ISSUE TITLE
Problems starting grails application in cluster environment

### ISSUE THREAD

**Issue by leleFc** [grails/grails-core#10524]
I have a Grails 3 (3.1.11) application installed on a cluster environment built with 2 IBM WebSphere 8.5.5.5 with IBM JDK 1.7 64 bit

When we try to start the application it often fails raising this error: "Identity property not found, but required in domain class" (see the error log attached). 
We have to try many times before have them started correctly on both application servers.
This error never happens when we run the same application on a single WebSphere instance.

- **Operating System**: IBM z/os
- **Grails Version:** 3.1.11
- **JDK Version:** IBM 1.7
- **Container Version (If Applicable):** WebSphere 8.5.5.5

[error_log.txt](https://github.com/grails/grails-core/files/827313/error_log.txt)

**Comment by antonevane** [comment]
Hi @leleFc, Your issue has been recently fixed in Grails 3.1.X branch.

https://stackoverflow.com/questions/41616489/grailsdomainexception-identity-property-not-found-but-required-in-domain-clas

**Comment by leleFc** [comment]
Hi @antonevane, I created my application with Grails 3.1.11, the problem doesn't occur on single WebSphere environment, but only in a cluster infrastructure

**Comment by antonevane** [comment]
Do you use WebSphere ND for a single profile, or Liberty? I would still to consider to upgrade to the latest 3.2.7

**Comment by leleFc** [comment]
My customer has WebSphere Full Profile 8.5.5.5 on a Z mainframe.
I have a full profile to, but not a cluster environment so I can't directly replicate and test the situation
I can't upgrade to 3.2.x

**Comment by graemerocher** [comment]
Already fixed
