### ISSUE TITLE
Wrong Scaffolding in grails 3.2.7

### ISSUE THREAD

**Issue by MLoenhardt** [grails/grails-core#10520]
It seems, that dynamical scaffolding tries to display allways the previously visited domain class and not the actual class. 

### Steps to Reproduce

1. Start the attached project 
2. visit http://localhost:8080/d1/index, (displays the correct item)
3. visit http://localhost:8080/d2/index, (displays no items)

### Expected Behaviour

http://localhost:8080/d2/index should display the correct bootstraped item

### Environment Information

- **Operating System**: Win10
- **Grails Version:** 3.2.7
- **JDK Version:** 1.8.102
- **Container Version (If Applicable):** development (Intellij)

### Example Application

 https://github.com/MLoenhardt/g_3_2_7_scaffold_Issue

**Comment by jameskleeh** [comment]
You can upgrade to scaffolding 3.3.1 to resolve this problem

**Comment by MLoenhardt** [comment]
Thanks, works for me!
