### ISSUE TITLE
New Promises Factory - Single (RxJava)

### ISSUE THREAD

**Issue by aaloise** [grails/grails-core#10528]
I would like to suggest the creation of a new Promise Factory, this time based on RxJava Singles.

Current Factories based on Reactor 2 and Gpars seems a bit oudated. Reactor 2 is almost dead and GPars isn't updated in a while know.

**Comment by graemerocher** [comment]
https://github.com/grails-plugins/grails-rxjava would be a more appropriate place for this

**Comment by aaloise** [comment]
Should I raise an issue there?
