### ISSUE TITLE
redirect doesnt consider current url/mapping when redirecting to relative action url

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10530]
### Steps to Reproduce

Given the url mapping
```

        "/admin/$domain/$action?/$id?" {
            controller = "genericAdmin"
        }

```
And the index action of GenericAdminController is like this
```

	def index() {
		redirect action:"list"
	}


```

As per the url mapping above `/admin/book/index ` would match the index action of genericAdmin controller. but when the index action redirects to list action, grails actually redirects to url /genericAdmin/list instead of /admin/book/list

### Expected Behaviour
redirect should consider current url/resolved mapping for the controller and redirect to /admin/book/list when doing redirects relative to current controller

Same controller can be mapped to multiple urls using url mapping, in this case, the redirect should honour the current url when doing redirect to a relative url

- **Grails Version:**  Grails 3.2.4

**Comment by jameskleeh** [comment]
Is the default url mapping also configured? (/controller/action/id)

**Comment by snimavat** [comment]
Yes, but it is after the admin/ mapping

**Comment by snimavat** [comment]
Explicitely passing params when doing redirect would redirect to correct url... eg `redirect action:"list", params:params`

But shouldnt it automatically pass whtever params are needed for url mapping (when not explicitely specified) when doing a redirect relative to current controller, so that url doesnt change ?

@jameskleeh Thoughts ?

**Comment by jeffbrown** [comment]
> Yes, but it is after the admin/ mapping, so admin mapping would take precedence

I don't think order in the source file is relevant.

**Comment by jeffbrown** [comment]
> But shouldnt it automatically pass whtever params are needed for url mapping

No, I don't think so.

**Comment by jeffbrown** [comment]
This looks like it is not a bug.  A call to `redirect action:"list"` should to match a url mapping like t    he following because `domain` isn't accounted for in the `redirect` call:

```
"/admin/$domain/$action?/$id?" {
    controller = "genericAdmin"
}
```

**Comment by snimavat** [comment]
Alright, yeah, thn its not a bug...
