### ISSUE TITLE
Grails 3.2 domain.get for null argument

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10538]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. SomeDomain.get(null)

### Expected Behaviour
null should be returned. This behavior was in all grails versions before 3.2

### Actual Behaviour

IllegalArgumentException thrown

> java.lang.IllegalArgumentException: id to load is required for loading
>         at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:93)
>         at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:63)
>         at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2759)
>         at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2741)
>         at org.hibernate.internal.SessionImpl.get(SessionImpl.java:978)
>         at org.grails.orm.hibernate.GrailsHibernateTemplate$2.doInHibernate(GrailsHibernateTemplate.java:349)
>         at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:286)
>         at org.grails.orm.hibernate.GrailsHibernateTemplate.get(GrailsHibernateTemplate.java:346)
>         at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.get(AbstractHibernateGormStaticApi.groovy:89)
>         at org.grails.datastore.gorm.GormEntity$Trait$Helper.get(GormEntity.groovy:518)
>         at org.grails.datastore.gorm.GormEntity$Trait$Helper$get$5.call(Unknown Source)
>         at SomeDomain.get(SomeDomain.groovy)

With new behavior we have to write more dummy code =)

### Environment Information

- **Grails Version:** 3.2.7

**Comment by graemerocher** [comment]
We already have https://github.com/grails/grails-data-mapping/blob/6.0.x/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateGormStaticApi.groovy#L71 so your `id` must in fact not be null but be a blank string containing `null` and failing conversion

**Comment by demon101** [comment]
@graemerocher yes, it can be empty string. 
Is if possible to change 
```
if (id == null) {
            return null
}
```

to 

```
if (!id) {
            return null
}
```

In the case of back compatibility it's a good change. 

For example, in my small app after upgrade 3.1-> 3.2 I get errors in really different place.
