### ISSUE TITLE
Grails 3.2.7 "command not found" with --profile angular2

### ISSUE THREAD

**Issue by danielritter** [grails/grails-core#10544]
The most commands like "clean" or "create-domain-class" do not work with grails 3.2.7. With profile angular they work.

**Error:** 

```
grails> clean
| Error Command not found [clean]
grails> create-domain-class
| Error Command not found [create-domain-class]
```

```| Error Error occurred loading commands: grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
```

### Task List

- Create new angular2 grails project

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.7
- **JDK Version:** jdk1.7.0_80

**Comment by jameskleeh** [comment]
Are you executing the commands in the server folder?

**Comment by danielritter** [comment]
I see. I tried it in the server/grails-app/domain folder. It works under server. Thanks!
But I still get there following error messages:
```
| Error Error occurred loading commands: org/hibernate/tool/schema/TargetType (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: Could not initialize class grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: Could not initialize class grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
| Created grails-app/domain/crm/Client.groovy
| Created src/test/groovy/crm/ClientSpec.groovy
```

**Comment by jameskleeh** [comment]
I can't reproduce that

**Comment by danielritter** [comment]
Here in the "Creating your first Grails App" guide: http://guides.grails.org/creating-your-first-grails-app/guide/index.html#applicationProfile I see the same error under "Provided Commands:"

**Comment by kevintanhongann** [comment]
I believe this could be related to whether or not you have included the hibernate-core dependency in your Grails project. Though you have the "org.grails.plugins:hibernate" dependency, you would still need to include the hibernate-core dependency in so that you can start your Grails console successfully.

**Comment by kevintanhongann** [comment]
I may be wrong. The cause could be anything. Just try ./grailsw --stacktrace to look for any clues.
