### ISSUE TITLE
g:include tag does not appear to include params with a dot

### ISSUE THREAD

**Issue by vahidhedayati** [grails/grails-core#10545]
Created a SO question which shows step to reproduce here

http://stackoverflow.com/questions/42866821/trying-to-use-g-include-tag-under-3-1-10

Tried on 3.2.7 and behaves same as 3.1.10.

Controller : 
```groovy
       def index() { }

        def test1() {
                println "params are $params"
                render params
        }

````
Gsp:
```gsp 
<g:include action="test1" params="${[id:1L]}"/>
<g:include action="test1" params="[id:2L]"/>
----<br>
<g:include action="test1" params="${['field.id':3L]}"/>
<g:include action="test1" params="['field.id':4L]"/>
```

No params on 2 bottom lines:
```
params are [id:1, action:test1, format:null, controller:test]
params are [id:2, action:test1, format:null, controller:test]
params are [action:test1, format:null, controller:test]
params are [action:test1, format:null, controller:test]
```

**Comment by snimavat** [comment]
I can reproduce this on 3.2.x branch -- the issue is here https://github.com/snimavat/grails-core/blob/3.2.x/grails-web-common/src/main/groovy/org/grails/web/util/WebUtils.java#L354

PR https://github.com/grails/grails-core/issues/10548 would fix it

**Comment by graemerocher** [comment]
@snimavat Thanks for the PR
