### ISSUE TITLE
[ 3.2.6 ] Promises seem to be broken

### ISSUE THREAD

**Issue by Zewkin** [grails/grails-core#10543]
### Steps to Reproduce

Run:
```
	def getFormOptions() {
		def map = new PromiseMap()
		map['one'] = { 2 * 2 }
		map['two'] = { 4 * 4 }
		map['three'] = { 8 * 8 }
		map.onComplete { Map results ->
		  render results as JSON
		}
	}
```

### Expected Behaviour

Expect results to be the same every time:

`{"one":4,"two":16,"three":64}`

### Actual Behaviour

The result is unpredictable every time. 

`{"one":4,"two":16,"three":64}`

Next action call:

`{"one":16,"two":64,"three":4}`

Next:

`{"one":16,"two":4,"three":64}` and so on.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.6
- **JDK Version:** 1.7.0_80

**Comment by graemerocher** [comment]
Please use `WebPromises.tasks` instead. Raw promises are not safe.. see https://github.com/grails/grails-core/issues/9755
