### ISSUE TITLE
Upgrade to Spring Boot 1.5.x to fix launcher issue

### ISSUE THREAD

**Issue by matthew-long** [grails/grails-core#10542]
The Spring Boot launcher creates a PID subfolder within the configured PID directory (/var/run by default) when invoked via an init script. This subfolder is erroneously not chown'd to the owner of the spring boot JAR.
This bug was introduced when upgrading to Spring Boot 1.4.2. See comments on https://github.com/spring-projects/spring-boot/commit/93ab01263c2f819962346555d3d199e9751ab8a2

It has been fixed in the 1.5.x release stream. See https://github.com/spring-projects/spring-boot/commit/75cb5453619f4561af939c84d57d38f0c7419edf

### Steps to Reproduce

1. Create simple grails application
2. Install to a linux environment and make sure ownership is a non-root user
3. Create symlink in /etc/init.d directory pointing to newly installed grails JAR file
4. Start the grails app via the service script

### Expected Behaviour

A directory within /var/run should be created with the same name as the init script symlink created in step 3 that is owned by the user that owns the grails application.

### Actual Behaviour

A directory is created within /var/run with the same name as the init script symlink created in step 3 that is owned by root.

### Environment Information

- **Operating System**: Redhat 6.8
- **Grails Version:** 3.2.6
- **JDK Version:** 1.8.0_112
- **Container Version (If Applicable):** N/A

**Comment by graemerocher** [comment]
The Spring Boot 1.5 is breaking as they used that release to remove deprecated classes that break some plugins like asset pipeline, cache, spring-security-core etc. 

So this can only go into 3.3 branch at the moment.

**Comment by erichelgeson** [comment]
You can provide your own launch script (or grab the one from 1.5) and use it with Grails 3.2.x  http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-repackage-configuration

Just set the `embeddedLaunchScript` in the `bootRepackage` task in your gradle file.

Script from 1.5.x branch: 
https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script
