### ISSUE TITLE
"grails list-plugins" does not work in Grails 3 (3.2.4)

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#10540]
### Steps to Reproduce

1. Open a command prompt
2. Enter "grails list-plugins"

### Expected Behaviour

Available grails plugins should be listed, as specified in the Grails 3 docs:
http://docs.grails.org/3.2.4/ref/Command%20Line/list-plugins.html

### Actual Behaviour

The "grails" usage information is displayed:

> Usage:
>          create-app [NAME] --profile=web
>          create-plugin [NAME] --profile=web-plugin
...etc.

### Environment Information

- **Operating System**: Win7 x64
- **| Grails Version**: 3.2.4
- **| Groovy Version**: 2.4.7
- **| JVM Version**: 1.8.0_66
- **Container Version (If Applicable):** N/A

### Example Application

N/A

**Comment by jeffbrown** [comment]
Does it work as expected if you execute the command from the top level directory of a Grails project?

**Comment by graemerocher** [comment]
Works fine from within a project, which is as designed
