### ISSUE TITLE
java.lang.IllegalArgumentException: This Dispatcher has been shut down.

### ISSUE THREAD

**Issue by psurolia** [grails/grails-core#10557]
After upgrading grails from 2.5.5 to Grails 3.2.7, getting below exception while running integration test cases
`java.lang.IllegalArgumentException: This Dispatcher has been shut down.
build	30-Mar-2017 07:25:00	        at reactor.core.support.Assert.isTrue(Assert.java:61)
build	30-Mar-2017 07:25:00	        at reactor.core.dispatch.AbstractLifecycleDispatcher.dispatch(AbstractLifecycleDispatcher.java:111)
build	30-Mar-2017 07:25:00	        at reactor.bus.EventBus.notify(EventBus.java:368)
build	30-Mar-2017 07:25:00	        at grails.events.Events$Trait$Helper.notify(Events.groovy:111)
build	30-Mar-2017 07:25:00	        at org.grails.events.spring.SpringEventTranslator.notify(SpringEventTranslator.groovy)
build	30-Mar-2017 07:25:00	        at org.grails.events.spring.SpringEventTranslator.onApplicationEvent(SpringEventTranslator.groovy:66)
build	30-Mar-2017 07:25:00	        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
build	30-Mar-2017 07:25:00	        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
build	30-Mar-2017 07:25:00	        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
build	30-Mar-2017 07:25:00	        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)`

Command Run : gradle clean integrationTest

- **Operating System**: Linux
- **Grails Version:** 3.2.7
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
As specified in 

https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

Issues should provide:

* Steps to reproduce
* Stacktrace (if present) provided
* Example that reproduces the problem uploaded to Github
* Full description of the issue provided

If the issue report is not submitted correctly it will be rejected.

**Comment by graemerocher** [comment]
No feedback provided.

Either way the issue can likely be resolved by setting `grails.gorm.reactor.events` to `false` in `application.yml`
