### ISSUE TITLE
Suggestion for Grails 3.3: type checked view references

### ISSUE THREAD

**Issue by krond** [grails/grails-core#10551]
Hello

As I understand, the next Grails version 3.3 will have support for type checked GSPs, which I think is a great feature and I can't wait to use it!

I don't know if this is possible from a technical point of view, but I think this "type checked views" idea could be even better, if it could expand throughout the whole framework and not only the view layer: My idea would be to also provide type checked references to views. Currently, views in controllers are rendered by providing a string in the render method, like `render(view: 'myView')`. It would be great if such calls could also be used in a type checked manner (find missing views before runtime).

I have seen something like this implemented in the Play framework:
`Content html = views.html.Application.index.render(customer, orders);`

I don't know if this is possible, but at least for me, this would be a very useful addition.

**Comment by graemerocher** [comment]
Please report GSP feature requests to https://github.com/grails/grails-gsp/issues
