### ISSUE TITLE
Generating settings.gradle causing problem in multi-project builds

### ISSUE THREAD

**Issue by ibmsoft** [grails/grails-core#10552]
i follow the http://docs.grails.org/latest/guide/plugins.html also the  video on https://www.youtube.com/watch?v=yNA0ce5fG9s 
grails create-app myapp
grails create-plugin myplugin
create settings.gradle file ,config 
`include "myapp","myplugin"
`

config the `grails {
    plugins {
        compile project(':myplugin')
    }
}`
in the build.gradle in myapp

then 
$ cd myapp
$ grails run-app -verbose

 Error Error initializing classpath: Project with path ':myplugin' could not be found in root project 'myapp'.
org.gradle.api.UnknownProjectException: Project with path ':myplugin' could not be found in root project 'myapp'.

### Environment Information

- **Operating System**: mac
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8

**Comment by jeffbrown** [comment]
Does the problem go away if you replace this:

```groovy
grails {
    plugins { 
        compile project(':myplugin') 
    } 
}
```

With this?...

```groovy
dependencies {
    // ...
    compile project(':myplugin')
}
```

**Comment by sbortman** [comment]
Jeff,

The answer to your question is yes and no.  ;-)

If you run gradle commands from the top level directory (i.e.  gradle assemble or gradle :myapp:bootRun)   it works.   But if you try to run grails run-app from myapp project directory,  it fails as if it doesn't know anything about the settings.gradle in the parent directory.

Hope that helps,
--scottie

PS:   Grails 3.1.x works just fine.

**Comment by jeffbrown** [comment]
> But if you try to run grails run-app from myapp project directory, it fails as if it doesn't know anything about the settings.gradle in the parent directory.

Does `./gradlew bootRun` work from the `myapp` project directory?

**Comment by jeffbrown** [comment]
The project at https://github.com/jeffbrown/multiproj demonstrates the problematic behavior.

**Comment by sbortman** [comment]
Jeff,

No sir,  gradlew,  grailsw,  and their native installed counterparts
don't work in the app directory.

--scottie

On Wed, Mar 29, 2017 at 12:41 PM, Jeff Scott Brown <notifications@github.com

**Comment by sbortman** [comment]
Oh,  and:

grails {
    plugins {
        compile project(':myplugin')
    }
}


Works with top level gradle as well

**Comment by graemerocher** [comment]
@jeffbrown @sbortman It may be because we now generate a `settings.gradle` for each project. Try remove these files from the subprojects

**Comment by graemerocher** [comment]
Also see https://github.com/graemerocher/grails-multi-project-build-example for a working example

**Comment by sbortman** [comment]
Graeme,  Jeff,

Okay,  just to recap:

1.  don't use the:

    grails {
       plugins {
          compile project(':myplugin')
      }
   }

   but instead use:

   dependencies {
        compile project(':myplugin')
        ....
    }

2.   Whack the settings.gradle files from the subdirectories,  should only
appear at top level.

Doing these steps gets me a working project.    Now,  the follow up
question (not to kick a
dead horse)   When reading:   Section 18.1 of the Users's Guide
<http://docs.grails.org/latest/guide/plugins.html#creatingAndInstallingPlugins>
,
it talks about subproject
reloading,  Is that still and issue?

Thanks to both or you fro your help,
--scottie

**Comment by ibmsoft** [comment]
@graemerocher  rename settings.gradle  in sub project ,now it work ,thanks

**Comment by ricardogobbo** [comment]
Should `settings.gradle` file be renamed to `"app-name".gradle` during `"create-app"` or `"create-plugin"` script?
