### ISSUE TITLE
Strange GparsPromise error in logs

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10555]
Sometimes one-two times per day, I see in production log error, can't reproduce in dev:

> 28/03 22:48:58.394 ERROR org.grails.async.factory.gpars.LoggingPoolFactory - Async execution error: null
> java.lang.NullPointerException: null
>         at org.apache.catalina.connector.Request.notifyAttributeAssigned(Request.java:1528)
>         at org.apache.catalina.connector.Request.setAttribute(Request.java:1514)
>         at org.apache.catalina.connector.RequestFacade.setAttribute(RequestFacade.java:540)
>         at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:252)
>         at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:252)
>         at org.grails.web.util.WebUtils.storeGrailsWebRequest(WebUtils.java:448)
>         at org.grails.plugins.web.async.WebRequestPromiseDecorator$_decorate_closure1.doCall(WebRequestPromiseDecorator.groovy:28)
>         at org.grails.plugins.web.async.WebRequestPromiseDecorator$_decorate_closure1.call(WebRequestPromiseDecorator.groovy)
>         at org.grails.async.factory.gpars.GparsPromise$_onError_closure2.doCall(GparsPromise.groovy:100)
>         at org.grails.async.factory.gpars.GparsPromise$_onError_closure2.call(GparsPromise.groovy)
>         at groovyx.gpars.dataflow.DataCallback$1.run(DataCallback.java:62)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

Any idea what can be a reason?

- **Operating System**: Ubuntu 14
- **Grails Version:** 3.1.16
- **JDK Version:** Oracle 8.0.121
- **Container Version (If Applicable):** Tomcat 8

**Comment by graemerocher** [comment]
Duplicates #10486 and #9755
