### ISSUE TITLE
WebPromises block response's thread if used with waitAll()

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#10558]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the attached project
2. Open http://localhost:8080/test/index 

### Expected Behaviour

The controller should render 'ok'

### Actual Behaviour

The response is never completed/flushed

### Environment Information

- **Operating System: Linux 64 bit
- **Grails Version: 3.2.8
- **JDK Version: 1.8.0_121

### Example Application

[WebPromises.zip](https://github.com/grails/grails-core/files/881912/WebPromises.zip)

**Comment by graemerocher** [comment]
In that case you should use `Promises` instead. `WebPromises` intended to be used for creating async responses that don't block. You're blocking, so hence not using it as intended.

**Comment by atasc** [comment]
Since Grails 3.2.7 promises are general purpose and not web specified. What about if I need to access controller methods, web session, web request etc inside a task?

**Comment by graemerocher** [comment]
It was "working" but unsafe since at any moment the request could return and be recycled. Consider:

```groovy
def foo() {
  Promises.task {
         sleep 2000
         render "foo ${params.something}"
  }
  render "bar"
}
```

If the request terminated before 2 seconds is up you will get a NPE at `params.something`. A safe way to write this would be:

```groovy
def foo() {
  String something = params.something
  Promises.task {
         sleep 2000
         render "foo ${something}"
  }
  render "bar"
}
```

Here you have no problem because the request data is read outside of the task. Alternatively using `WebPromises` also creates an async request which keeps the request open.

**Comment by atasc** [comment]
May be I've found a solution using response.getWriter().close(). The following code makes what I need but I don't know if the response thread is properly closed.



```
package webpromises

import static grails.async.web.WebPromises.*

class TestController {

  def index() {

    session.setAttribute('MessageForTask', 'Hello I am a message for task')

    def p1 = task { 2 * 2 }
    def p2 = task { 4 * 4 }
    def p3 = task { 8 * 8 }
    def p4 = task {
      sleep 5000
      
      //I can access session without problems
      println session.getAttribute('MessageForTask')
      
      return 10 * 10
    }

    def results = waitAll(p1, p2, p3, p4)

    assert [4, 16, 64, 100] == results

    println 'results size = ' + results.size()
    
    //render the response
    render new Date().time + ': results size = ' + results.size()

    //Flush and close response. Don't know if the response thread is correctly shut down and cleared
    response.flushBuffer()
    response.getWriter().close()
  }

}


```
