### ISSUE TITLE
REST: Domain resource class should not be accessible twice

### ISSUE THREAD

**Issue by danielritter** [grails/grails-core#10565]
**How to reproduce:** 

1. Create a rest-api app (e.g. with profile angular2)
2. Create a domain resource class (e.g. Comment) with an uri (e.g. "/comments", (plural: not "/comment"))
3. Domain resource class is accessible twice via http://localhost:8080/comment and http://localhost:8080/comments

**How it should be:** 
Domain resource class should only be accessible by the specified uri in the @Resource annotation. In this example: http://localhost:8080/comments and not via http://localhost:8080/comment.

**Code:**

```
@Resource(uri = "/comments", readOnly = false, formats = ['json'])
class Comment {

    String title
    String comment
    String author

    static constraints = {
        title blank: false, nullable: true, size: 1..128
        comment blank: false, nullable: false, size: 1..512
        author blank: false, nullable: true, size: 1..128
    }
}
```

**Grails-Version:** 3.2.8

**Comment by graemerocher** [comment]
This is by design, the default `UrlMappings` are:

https://github.com/grails-profiles/rest-api/blob/master/skeleton/grails-app/controllers/%40grails.codegen.defaultPackage.path%40/UrlMappings.groovy#L6

Simply remove lines 6 to 10 to resolve the issue if you don't want the defaults to kick in.
