### ISSUE TITLE
No documentation for upgrading 2.x integration tests for 3.x

### ISSUE THREAD

**Issue by chriserickson** [grails/grails-core#10568]
We are working to upgrade a 2.x app to 3.2.8, but there is no documentation stating what we have to do to our legacy integration tests, which used the IntegrationTestMixin syntax.

E.G.
```
@TestMixin(IntegrationTestMixin)
class ExternalApiTests {
```

Doesn't run anymore. I'm assuming we have to convert them all to Spock tests, but it would be nice if there was a way to migrate them without rewriting them. Unfortunately I've not found anything in the documentation saying either.

**Comment by jeffbrown** [comment]
> ...but it would be nice if there was a way to migrate them without rewriting them

If by "without rewriting them" you mean a tool that will change the source code for you, that does not exist.  The tests will need to be edited.  The 3.x user guide describes how 3.x integration tests work.

**Comment by chriserickson** [comment]
Previously we could have mixed tests, with a mixture of the older IntegrationTestMixin-based-tests and the newer Spock tests. I wasn't sure if there was still a latent ability to keep the old tests.

What would be really helpful is something in the migration guide stating that the older style tests are no longer supported and must be rewritten. A lack of documentation doesn't clearly communicate that something is no longer supported.

**Comment by jeffbrown** [comment]
> Previously we could have mixed tests, with a mixture of the older IntegrationTestMixin-based-tests and the newer Spock tests.

btw... those are not mutually exclusive.  Most of the mixin based tests are Spock tests.

**Comment by chriserickson** [comment]
Sorry, I'm not sure of the correct nomenclature of the older style tests, aside from the fact that they had to have test____() as the name, didn't extend Specification, and manually asserted their expectations.

**Comment by jeffbrown** [comment]
The upgrade section of the user guide does contain the following:

> Integration tests will need to be annotated with the Integration annotation...

More details could be included there.  If you would like to submit a PR, click the "Improve this doc" link at http://docs.grails.org/latest/guide/upgrading.html#upgradingApps.

**Comment by ilopmar** [comment]
And a more complete guide can be found here: https://grails.github.io/grails-upgrade/latest/guide/index.html
