### ISSUE TITLE
Suggestion for improvement: Renaming angular profiles

### ISSUE THREAD

**Issue by danielritter** [grails/grails-core#10561]
I would rename the angular profiles for consistency reasons. Today, Angular 2 is just called Angular and now available in version 4 (see: https://angular.io/docs/ts/latest/).

**My suggestion:**

- Rename the angular profile to angularJS
- Rename the angular2 profile to angular

Grails Version: 3.2.8

**Comment by jeffbrown** [comment]
These should probably reported at https://github.com/grails-profiles/angular/issues and https://github.com/grails-profiles/angular2/issues.

**Comment by danielritter** [comment]
Ok, there are two new tickets: 
- https://github.com/grails-profiles/angular/issues/2
- https://github.com/grails-profiles/angular2/issues/9
