### ISSUE TITLE
angular2 profile creates app with missing gormVersion and gradleWrapperVersion setting 

### ISSUE THREAD

**Issue by danielritter** [grails/grails-core#10562]
Like in this ticket mentioned https://github.com/grails/grails-core/issues/10536 for the react profile the same error occurs in the angular2 profile. The `gormVersion` and the `gradleWrapperVersion` are missing when creating a new app with profile angular2.

**Grails Version:** 3.2.8

**Comment by jameskleeh** [comment]
This was fixed already, just not released yet. https://github.com/grails-profiles/angular2/commit/a3b1440b765825e3eec385104a783cfff9afdcb3

**Comment by mgkimsal** [comment]
version 1.0.5 of what?

**Comment by jameskleeh** [comment]
The profile https://github.com/grails-profiles/angular

**Comment by danstadler-ensighten** [comment]
Last night built a grails app with the angular2 profile, grails version is 3.2.8. I am seeing the above problem. Do I need to update my version of the angular2 profile to get the latest fix? Appreciate any advice.

**Comment by jameskleeh** [comment]
@danstadler-newrelic The application is already created, so you simply need to add the `gormVersion=6.0.9.RELEASE` to your `gradle.properties`

**Comment by danstadler-newrelic** [comment]
Thanks! that did the trick.

**Comment by danstadler-newrelic** [comment]
OK, no idea if this also belongs in this thread, but when I then run:
./gradlew client:bootRun

I run into this:

ERROR in [path redacted]/client/src/app/nav/nav.service.ts (19,12): Property 'cache' does not exist on type 'Observable<any>'.

Did some googling, suggested fixes haven't helped so far...

(just fyi, I'm trying this out: https://docs.grails.org/latest/guide/webServices.html#angular2Profile )

**Comment by danielritter** [comment]
I've got the same error. I resolved it by removing the cache property from nav.service.ts. But this is just a workaround. I think with the new angular profile this problem is solved.

**Comment by danstadler-newrelic** [comment]
@danielritter  can you give me a quick diff of your change - I'm pretty new to the Angular side of this, just looking for a quick path to a bootable/runnable, app so I can learn basic working examples of Grails and Angular talking to each other. - thx

**Comment by danielritter** [comment]
Use Grails 3.2.9, there the problem should be fixed.
