### ISSUE TITLE
Missing JSP feature: dynamic attributes

### ISSUE THREAD

**Issue by sti0007** [grails/grails-core#10576]
### Steps to Reproduce

1. Use any JSP taglib that utilizes dynamic attributes

### Expected Behaviour

The JSP tag is properly rendered.

### Actual Behaviour

The actual error depends on the tag implementation, but the issue is that Grails doesn't pass the dynamic attributes to the tag implementation through the DynamicAttributes interface.

A possible fix is to extend [JspTagImpl#applyAttributes](https://github.com/grails/grails-core/blob/5728b2b772aeba9857cfd848a62fcfb762abac08/grails-web-jsp/src/main/groovy/org/grails/gsp/jsp/JspTagImpl.groovy#L155) method with this functionality.

### Environment Information

- **Operating System**: Windows 10 Version 1607
- **Grails Version:** 3.0.16
- **JDK Version:** 1.8.0_74

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues
