### ISSUE TITLE
Creating new grails 3 app with angular2 profile does not include gormVersion property in gradle.properties

### ISSUE THREAD

**Issue by GSamuel** [grails/grails-core#10575]
### Steps to Reproduce

grails create-app my-app --profile angular2 -features hibernate,json-views
try to run the server with 
* gradlew bootRun:server
gradle does not recognise gormVersion

### Expected Behaviour
gormVersion should be present in gradle.properties file

### Actual Behaviour
gormVersion property does not exist in gradle.properties

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.2.8
- **JDK Version:** dk1.8.0_40

**Comment by jagedn** [comment]
as workarround if you include security feature then gradle.properties it's ok

**Comment by jameskleeh** [comment]
Already fixed for 3.2.9

**Comment by jagedn** [comment]
angular2 version 4.0.0 fix the issue:

grails create-app my-app --profile org.grails.profiles:angular:4.0.0 -features hibernate5,json-views
