### ISSUE TITLE
g:render with body and g:set bug

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10577]
### Task List

- [X] Steps to reproduce provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

index.gsp:
```
<g:render template="someTemplate">
    <g:set var="someVariable" value="Yes!"/>
    value: ${someVariable}
</g:render>
```

someTemplate.gsp
```
<%@ page contentType="text/html;charset=UTF-8" %>
Bla bla!
${raw(body())}
End
```

### Expected Behaviour

render 

> Bla bla!
> value: Yes
> End

### Actual Behaviour

> Bla bla!
> value: 
> End

Variable value is missing, null

Can be fixed by moving set out of render:

```
<g:set var="someVariable" value="Yes!"/>
<g:render template="someTemplate">
    value: ${someVariable}
</g:render>
```

### Environment Information

- **Grails Version:** 3.1.15, 3.2.8

### Example Application

https://github.com/demon101/grails-trigers/tree/master/grails-app/views/test

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues

**Comment by demon101** [comment]
https://github.com/grails/grails-gsp/issues/1
