### ISSUE TITLE
Session timeout for standalone tomcat

### ISSUE THREAD

**Issue by sagrawal31** [grails/grails-core#10571]
### Task List

- [x] Steps to reproduce provided
- [ ] ~Stacktrace (if present) provided~
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails app `grails create-app test-app` (Using **3.2.8**)
2. Increase the session timeout in `application.yml`
3. Print the `session.getMaxInactiveInterval()` in a controller
4. Run the app (`grails run-app`) and print the above value
4. Create WAR (`grails war`) & deploy it to a tomcat (Using **apache-tomcat-8.5.9**)
5. Now print the value of `session.getMaxInactiveInterval()`

See the changes here https://github.com/wizpanda/session-timeout/commit/db0468a52880790cd08ac5f17db1df85fb01338d

### Expected Behaviour

When you print the value of `session.getMaxInactiveInterval()` while running in the development mode, the value is same as what we defined in the `application.yml` but when we deploy it on a standalone tomcat, the value is set to 1800s (which is the default value).

### Actual Behaviour

When deployed to standalone tomcat, the value should be same as what is defined in the `application.yml`

### Environment Information

- **Operating System**: CentOS7/MacOS
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_91

### Example Application

GitHub repo to reproduce this issue: [wizpanda/session-timeout](https://github.com/wizpanda/session-timeout)

One of the SO user [suggested](http://stackoverflow.com/questions/43215649/grails-3-session-timeout-not-working-when-deployed-to-tomcat#comment73576051_43253522) me to use the spring configuration to increase the session timeout but is that solution really needed? The settings that are used in `application.yml` (for increasing session timeout) is really used only when used with embedded tomcat and it won't work when we deploy it on a standalone tomcat?

**Comment by snimavat** [comment]
@sagrawal31  I think this is a springboot concern, not related to grails. the session timeout config will apply to just embedded tomcat. when deployed to tomcat, you have to resort to otherways to set session timeout

**Comment by graemerocher** [comment]
This is how Boot is designed, when you deploy standalone Boot can control the Tomcat configuration. When you deploy to Tomcat you have to configure Tomcat separately
