### ISSUE TITLE
Domain field modification in beforeValidate lose

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10573]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

In beforeValidate domain method
1. Modify some field
2. Do some query, for example SomeDomain.countByLinkNameAndIdNotEqual(...)
3. Modify the same field again

Simple example: 
For blog post unique link stored in db. Links generates by post name in beforeValidate. In same place, we check link for the uniqueness. If link already presented, we add salt to the new link

### Expected Behaviour

Last value of field changed in beforeValidate stored to db
(It was in this way in grails 2.4.5)

### Actual Behaviour
First value (before in between query) stored to DB,  unique DB constraint throws error

### Environment Information

- **Grails Version:** 3.1.15, 3.2.8
- **JDK Version:** 8.0.101

### Example Application

https://github.com/demon101/grails-trigers

grails run-app, open / 

I have found strange behaviour: during beforeValidate SomeDomain.countByLinkNameAndIdNotEqual(...) call causes beforeUpdate, from beforeUpdate it again call beforeValidate. Value stores to DB before end of first beforeValidate method

From test app logs:
> beforeValidate(id=2)
> beforeUpdate(id=2)
> beforeUpdate end(id=2)
> beforeValidate(id=2)
> linkName 'name1' already exist, new link name is name1 1
> beforeValidate end(id=2)
> 2017-04-07 16:21:18.658 ERROR --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unique index or primary key violation: "UK_PCGGJFRG9XE0EQQ4HQ59FYEEW_INDEX_5 ON PUBLIC.SOME_DOMAIN(LINK_NAME) VALUES ('name1', 1)"; SQL statement:

**Comment by demon101** [comment]
StackTrace: beforeValidate -> beforeUpdate -> beforeValidate

> at XXXX.beforeValidate(XXXX.groovy:168)
> at sun.reflect.GeneratedMethodAccessor495.invoke(Unknown Source:-1)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
> at org.grails.datastore.gorm.support.EventTriggerCaller$MethodCaller.call(EventTriggerCaller.java:147)
> at org.grails.datastore.gorm.support.EventTriggerCaller.call(EventTriggerCaller.java:90)
> at org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller.call(BeforeValidateHelper.java:45)
> at org.grails.orm.hibernate.support.ClosureEventListener.onValidate(ClosureEventListener.java:383)
> at org.grails.orm.hibernate.EventTriggeringInterceptor.onValidate(EventTriggeringInterceptor.java:178)
> at org.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:93)
> at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:51)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
> at org.grails.datastore.gorm.events.ConfigurableApplicationContextEventPublisher.publishEvent(ConfigurableApplicationContextEventPublisher.groovy:30)
> at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.fireEvent(AbstractHibernateGormValidationApi.groovy:132)
> at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:76)
> at org.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:52)
> at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:65)
> at org.grails.datastore.gorm.GormValidateable$Trait$Helper$validate$3.call(Unknown Source:-1)
> at XXXX.validate(XXXX.groovy:-1)
> at org.grails.orm.hibernate.support.ClosureEventListener.doValidate(ClosureEventListener.java:370)
> at org.grails.orm.hibernate.support.ClosureEventListener$7.call(ClosureEventListener.java:323)
> at org.grails.orm.hibernate.support.ClosureEventListener$7.call(ClosureEventListener.java:312)
> at org.grails.orm.hibernate.support.ClosureEventListener.doWithManualSession(ClosureEventListener.java:337)
> at org.grails.orm.hibernate.support.ClosureEventListener.onPreUpdate(ClosureEventListener.java:312)
> at org.grails.orm.hibernate.EventTriggeringInterceptor.onPreUpdate(EventTriggeringInterceptor.java:147)
> at org.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:68)
> at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:51)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
> at org.grails.datastore.gorm.events.ConfigurableApplicationContextEventPublisher.publishEvent(ConfigurableApplicationContextEventPublisher.groovy:30)
> at org.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.publishEvent(ClosureEventTriggeringInterceptor.java:148)
> at org.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.onPreUpdate(ClosureEventTriggeringInterceptor.java:124)
> at org.hibernate.action.internal.EntityUpdateAction.preUpdate(EntityUpdateAction.java:244)
> at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:118)
> at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
> at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
> at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
> at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:50)
> at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1264)
> at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1780)
> at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
> at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResultViaListCall(AbstractHibernateQuery.java:785)
> at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResult(AbstractHibernateQuery.java:775)
> at org.grails.datastore.gorm.finders.CountByFinder.invokeQuery(CountByFinder.java:55)
> at org.grails.datastore.gorm.finders.CountByFinder$1.doInSession(CountByFinder.java:49)
> at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
> at org.grails.datastore.gorm.finders.AbstractFinder.execute(AbstractFinder.java:42)
> at org.grails.datastore.gorm.finders.CountByFinder.doInvokeInternal(CountByFinder.java:46)
> at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:174)
> at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:374)
> at org.grails.datastore.gorm.finders.FinderMethod$invoke$0.call(Unknown Source:-1)
> at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:169)
> at sun.reflect.GeneratedMethodAccessor346.invoke(Unknown Source:-1)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
> at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
> at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
> at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
> at groovy.lang.Closure.call(Closure.java:414)
> at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:62)
> at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
> at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
> at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
> at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
> at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:96)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
> at XXXX.beforeValidate(XXXX.groovy:185)
> at sun.reflect.GeneratedMethodAccessor495.invoke(Unknown Source:-1)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
> at org.grails.datastore.gorm.support.EventTriggerCaller$MethodCaller.call(EventTriggerCaller.java:147)
> at org.grails.datastore.gorm.support.EventTriggerCaller.call(EventTriggerCaller.java:90)
> at org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller.call(BeforeValidateHelper.java:45)
> at org.grails.orm.hibernate.support.ClosureEventListener.onValidate(ClosureEventListener.java:383)
> at org.grails.orm.hibernate.EventTriggeringInterceptor.onValidate(EventTriggeringInterceptor.java:178)
> at org.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:93)
> at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:51)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
> at org.grails.datastore.gorm.events.ConfigurableApplicationContextEventPublisher.publishEvent(ConfigurableApplicationContextEventPublisher.groovy:30)
> at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:114)
> at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:116)
> at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:98)
> at org.grails.datastore.gorm.GormEntity$Trait$Helper$save$7.call(Unknown Source:-1)
> at XXXX.save(XXXX.groovy:-1)

**Comment by demon101** [comment]
Without unique constraints, I think, last value will be stored by second query

**Comment by graemerocher** [comment]
You should run the logic in `withNewSession`

**Comment by demon101** [comment]
@graemerocher  nothing written about withNewSession in the documentation. 
For me it looks like regression

**Comment by graemerocher** [comment]
see http://gorm.grails.org/latest/hibernate/manual/index.html#eventsAutoTimestamping

Quote:
"Notice the usage of withNewSession method above. Since events are triggered whilst Hibernate is flushing using persistence methods like save() and delete() won’t result in objects being saved unless you run your operations with a new Session."

Generally `withNewSession` should always be used with events, because they occur during `flush()` so you should never do persistence logic within them.

If you wish to improve the documentation, please feel free. Contributions welcome.

**Comment by demon101** [comment]
@graemerocher  Thx!

**Comment by demon101** [comment]
@graemerocher I was confused because I have only read operation in beforeValidate

**Comment by demon101** [comment]
@graemerocher I was confused because I have only read operation in beforeValidate
As I understand, after any modifications of same domain entities in session read operation on same domain in beforeValidate method will cause flush with beforeUpdate and second beforeValidate call inside
Is it expected behavior?
