### ISSUE TITLE
forward() loses parameters used in UrlMappings

### ISSUE THREAD

**Issue by rogovskiy** [grails/grails-core#10583]
The parameters used in UrlMappings get lost during forward(). This is important 

See demo application here -
https://github.com/rogovskiy/grailsForwardIssue2

Simple HomeController prints passed in parameter "id". If another parameter forward is passed it forwards to another action doing similar.

```
class HomeController {
  def index() {
    if (params.forward) {
       forward(action: 'imForwardedTo')
    } else {
       render(text: "ID is ${params.id}")
    }
  }

  def imForwardedTo() {
    render(text: "Forward ID is ${params.id}")
  }
}

... 
UrlMappings.groovy

 "/forward/$id"(controller: 'home', action: 'index')
```

### Results

http://localhost:8080/home/index?id=31                             ==> ID = 31 (GOOD)
http://localhost:8080/home/index?id=31&forward=true     ==> Forwarded ID = 31 (GOOD)

http://localhost:8080/forward/31                                        ==> ID = 31 (GOOD)
http://localhost:8080/forward/31?forward=true                  ==> Forwarded ID = null (BAD)

### Expected Behaviour

All parameters gets passed to the next action using forward().

### Actual Behaviour

All parameters EXCEPT the ones used in the URL mapping passed to the next action.

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.1.15
- **JDK Version:** 1.8

### Example Application
https://github.com/rogovskiy/grailsForwardIssue2

**Comment by jeffbrown** [comment]
At https://github.com/grails/grails-core/issues/9539#issuecomment-170843088 @graemerocher said the following:

> I don't believe this is a bug, using forward without specifying the params argument will only forward the original request parameters as present in the URL, not those that are present when mutating the params object.

...and followed that with an example to achieve the desired behavior.

**Comment by rogovskiy** [comment]
Is there a good way to find out which parameters are "original" and which are added by URLMappings plugin? 

What we've been doing and what worked in Grails 2 is forward(params: params). But as of Grails 3 the application is duplicating the original parameters which causes lots of issues down stream. 

For example "aciton?contract=123" if you forward(params: params) now results to action?contract=123&contract=123 and the result of the binding would be an array [123,123].

**Comment by jeffbrown** [comment]
> But as of Grails 3 the application is duplicating the original parameters which causes lots of issues down stream.

I think that is discussed at #10231

**Comment by rogovskiy** [comment]
In #10231 Graeme said he won't fix what I thought was an issue. I don't see a way to distinguish between original and "url mapping" parameters in that discussion.  

All I am trying to understand is how to make forward() work with UrlMappings in general sense. I'll be happy to explain our situation over webex if it is easier.

**Comment by sdelamo** [comment]
Grails 2.x branch verifying behaviour it is different in Grails 3 in comparison with Grails 2x.

https://github.com/grails-core-issues-forks/grailsForwardIssue2/tree/grails2x
