### ISSUE TITLE
Default action view not resolved when handling error

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#10582]
### Steps to Reproduce

1. start the example app: https://github.com/jglapa/errorHandlingGrails328
2. hit localhost:8080/test/deny
3. you don't get the expected error page

### Expected Behaviour

UrlMappings has the following entry:
`"403"(controller: 'error', action: 'handleDenied')`

after `test/deny` is accessed a `403` is returned, this should resolve the `error/handleDenied` and eventually render the `handleDenied.gsp`

### Actual Behaviour

Grails doesn't render anything. I get a 403 browser specific page.

### Environment Information

- **Operating System**: MacOS
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8

### Example Application

- https://github.com/jglapa/errorHandlingGrails328

**Comment by graemerocher** [comment]
The issue is down to this line https://github.com/grails/grails-core/blob/master/grails-web-common/src/main/groovy/org/grails/web/servlet/mvc/GrailsWebRequest.java#L363

This is in place because so that when you use for example `render status:403` it doesn't attempt to render view, even though there is potentially no return type from the method.

Changing this logic would likely incur side effects. A simply workaround is to be just be explicit:

```
render view:'handleDenied'
```

Or to map directly to a view in your `UrlMappings`

**Comment by tkvw** [comment]
I have a similar issue with gson: 

In UrlMappings I have:
```"401"(controller: 'error',action: 'unauthorized')
```
and in views I have: 
`error\unauthorized.gson`

the controller:
```class ErrorController {
    static Logger log401 = LoggerFactory.getLogger("${ErrorController.name}.401")
    
    def unauthorized(){
        log401.error("Unauthorized {}",request.remoteAddr)
        [ip:request.remoteAddr]
    }
}
```
But it does not render the gson view. Error: 
`javax.servlet.ServletException: Could not resolve view with name 'unauthorized' in servlet with name 'grailsDispatcherServlet'`
It does work without the controller mapping:
```"401"(view:'/error/unauthorized')```

Pulled from question on slack: https://grails.slack.com/archives/C07M0GTDE/p1501061767191689

**Comment by tkvw** [comment]
for reference: I use Graeme's solution, which works; 

```
class ErrorController {
    static Logger log401 = LoggerFactory.getLogger("${ErrorController.name}.401")
    
    def '401'(){
        log401.error("Unauthorized {}",request.remoteAddr)
        respond([view:'/error/401'],[ip:request.remoteAddr])
    }
}
```
This serves 401.gsp with Accept:text/html and 401.gson with Accept:application/json

**Comment by ilopmar** [comment]
@tkvw Can you please share a sample application that reproduces the issue? I've done some progress but I would like to have your sample project to make sure everything will work.
