### ISSUE TITLE
Hibernate sessions set to FlushMode.AUTO despite configuration settings with gorm-hibernate5

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-core#10586]
We have a data-intensive application that we're upgrading from Grails 2.5.4 to Grails 3.2.8. There is a serious performance degradation in this upgrade that we've narrowed down to an interaction between service calls and GORM/Hibernate object loading.

The attached project creates sample data of 50,000 records. The TestController endpoint then makes the same call to a dummy service method before and after a findAll on the test data. The subsequent service calls after the findAll are dramatically slowed down (50ms vs 2ms in this example, but more significant in our application).

This appears to be caused by a Hibernate flush operation across the Transactional service boundary. This occurs even though the application has `grails.gorm.flushMode: MANUAL` and `hibernate.flush.mode: manual` in the application.yml file. I also tried setting `hibernate.transaction.flush_before_completion: false` without any luck.

I can breakpoint in Hibernate's SessionImpl.flushBeforeTransactionComplete and see that this.flushMode shows AUTO instead of the desired MANUAL. This causes an undesired flush that hits AbstractFlushingEventListener.prepareEntityFlushes with all the loaded GORM entities.

Is the documentation incorrect on how to set flushMode, or is this inadvertently being overridden? Is there something else going on that we haven't figured out? Thanks for any help you can provide.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_112

### Example Application
[test-hibernate.zip](https://github.com/grails/grails-core/files/923009/test-hibernate.zip)

**Comment by timbonicus** [comment]
This seems similar to #2556 from Grails 2; the OSIV flushMode is set correctly, but not for the session initiated at the end of the transaction. Should GrailsHibernateTransactionManager be paying attention to these settings?

**Comment by jeffbrown** [comment]
@timbonicus Thanks for the feedback.  We will investigate.

**Comment by demon101** [comment]
I don't know, is it same problem, but after update from 3.1.15 to 3.2.8 CPU load was increased:

![tomcat-time-day](https://cloud.githubusercontent.com/assets/1362920/25101332/2ace1284-23b4-11e7-94ba-7683f4c579c2.png)

**Comment by timbonicus** [comment]
I tried overriding the GrailsHibernateTransactionManager with my own implementation to set the flushMode:
```groovy
beans = {
    transactionManager(FlushModeAwareTransactionManager) {
        sessionFactory = ref("sessionFactory")
        nestedTransactionAllowed = true
    }
}

class FlushModeAwareTransactionManager extends GrailsHibernateTransactionManager {
    @Override
    protected void doBegin(Object transaction, TransactionDefinition definition) {
        super.doBegin(transaction, definition)
        setFlushModeManual(transaction) // test; hard-core to manual
    }
}
```

This works well and SessionImpl shows the right flushMode at transaction complete. However, once I use withTransaction, the templateManager is incorrect. The root cause of this seems to be HibernateDatastore, which hard-codes its transactionManager to the Grails implementation instead of using the Spring bean. This pollutes GormEnhancer.STATIC_APIS that withTransaction eventually uses.

Is there any suitable way to override the transactionManager that would affect GormEnhancer as well?

**Comment by graemerocher** [comment]
Same as #10593
