### ISSUE TITLE
Grails 3.2.8 - i18n issue in test and prod environment

### ISSUE THREAD

**Issue by scurow** [grails/grails-core#10588]
### Steps to Reproduce

```
$ grails create-app translationissue
$ cd translationissue

# Set Welcome Messages
$ echo "com.translationissue.welcome=Welcome Ladies and Gentlemen" >> grails-app/i18n/messages.properties && echo "com.translationissue.welcome=Willkommen Damen und Herren" >> grails-app/i18n/messages_de.properties

# Use Welcome g:message On Start Page Instead Of The Standard
$ sed -i "s/Welcome to Grails/<g:message code='com.translationissue.welcome' \/>/g" grails-app/views/index.gsp
```

When running in dev environment `grails dev run-app` the welcome message is correctly translated on http://localhost:8080?lang=de and http://localhost:8080?lang=en. But when running in _test_ | _prod_ environment `grails dev run-app` | `grails prod run-app` it renders the code _com.translationissue.welcome_ and not the translation on the start page.

### Expected Behaviour

Translations should work in all environments.

### Actual Behaviour

Translations are only working in _dev_ environment.

### Environment Information

- **Operating System**: Tested on Mac OS X 10.12.4 and in Debian Docker Container
- **Grails Version:** 3.2.8
- **Groovy Version:** 2.4.10
- **Oracle JDK Version:** 1.8.0_121

### Example Application

https://github.com/scurow/translationissue

**Comment by jameskleeh** [comment]
Similar to https://github.com/grails/grails-core/issues/10559

**Comment by jameskleeh** [comment]
The fix in the linked issue also fixes this issue

**Comment by apandichi** [comment]
For some reason, I still have this problem with:
 Grails Version: 3.2.9
 Groovy Version: 2.4.10
 JVM Version: 1.8.0_101

**Comment by jameskleeh** [comment]
@apandichi I can't reproduce the issue if I upgrade that sample application to 3.2.9. If you have an example project that reproduces the problem, file a new issue.

**Comment by apandichi** [comment]
@jameskleeh I totally forgot to upgrade the Grails version in the gradle.properties file. Apologies for wasting your time! :smile:
