### ISSUE TITLE
Domain propertyId returns null 

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10595]
```
class Domain1 {
   Domain2 field
}
```

@graemerocher  Previusly, for example in Grails 2.4, 3.1.15, was possible to get field Id by simple call
`domain1.fieldId`
Now in Grails 3.2.8 this call return null, but **domain1.field.id** works well

Is it bug?

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

**Comment by demon101** [comment]
@graemerocher no issue -- no problem, cool! Thx for the help
