### ISSUE TITLE
Case-insensitive sorting in a criteria 

### ISSUE THREAD

**Issue by MiguelAngel82** [grails/grails-core#10590]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

In a criteria is possible to do a case-insensitive sort passing a Query as an argument of `order` criterion, such as:

`order(new Query.Order('<propertyName>', Query.Order.Direction.ASC).ignoreCase()) `

1. You have a domain A with a relationship with B, for instance: 
```
class A {
    B b
}

class B {
    String property1
}
```
2. You do a criteria over A domain, create an alias inside this criteria and order it by B's property with ignore case :
```
A.createCriteria().list() {
    createAlias('b', 'bAlias')
    order(new Query.Order('b.property1', Query.Order.Direction.ASC).ignoreCase()) 
}
```
### Expected Behaviour

The criteria works without exception and a case-insensitive order is done.

### Actual Behaviour

An exception is thrown:
`could not resolve property: 'b.property1' of: A`

### Environment Information

- **Operating System**: Ubuntu 16
- **Grails Version:** 3.1.8
- **JDK Version:** 1.8

### Example Application

https://github.com/MiguelAngel82/criteriaOrderCaseInsensitiveG3

This example has two domains classes and an integration test to reproduce the behaviour. An integration test is done because an unit test does not work with `createAlias`.

**Comment by sdelamo** [comment]
You can use a [derived property](http://gorm.grails.org/latest/hibernate/manual/index.html#derivedProperties) to do such a case insensitive sorting: 

```
class A {
    B b
}

class B {
    String property1
    String sortproperty1
    static mapping = {
        sortproperty1 formula: 'UPPER(property1)'
    }
}

A.createCriteria().list() {
      createAlias('b', 'bAlias')
       order('bAlias.sortproperty1', 'asc')
}
```

**Comment by MiguelAngel82** [comment]
Thanks for the workaround @sdelamo! I really appreciate your help ;)

**Comment by sdelamo** [comment]
Please, close this issue if you consider it resolved.
