### ISSUE TITLE
embedded changes not saved if only embedded attributes are changed

### ISSUE THREAD

**Issue by crudolf** [grails/grails-core#10602]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Consider following domain classes:

```groovy
class Person {

    static mapping = {
        version false
    }

   String anotherString
   Address address
   static embedded = ['address']
}
class Address {
   String anotherString
   boolean someBoolean
}
```

2. Do the following:

```groovy
Person person = Person.get(1) // get existing one
person.address.someBoolean = !person.address.someBoolean
person.save(flush: true)
```

### Expected Behaviour

someBoolean should be inverted

### Actual Behaviour

someBoolean is not updated. 
Note that if another property (not an embedded one) of Person is changed, the change is written to DB.

### Environment Information

grailsVersion=3.2.8
gormVersion=6.1.1.RELEASE
gradleWrapperVersion=3.4.1

Also tested with: 
gormVersion=6.1.2.RELEASE

- **Operating System**: sierra 10.12.4
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
If you annotate that embedded class with `@DirtyCheck` does it change the behaviour?

**Comment by crudolf** [comment]
No it doesn't change the behaviour.

**Comment by crudolf** [comment]
I just realized you added a target release. I can do tests at any time, if grails-data-mapping gets a new release. Thank you so much for your great effort!

**Comment by crudolf** [comment]
The current workaround is:

```
Person person = Person.get(1) // get existing one
person.address.someBoolean = !person.address.someBoolean
person.markDirty("address")
person.save(flush: true)
```

Note that 

```
Person person = Person.get(1) // get existing one
person.address.someBoolean = !person.address.someBoolean
person.address.markDirty("someBoolean")
person.save(flush: true)
```

DID not worked!

**Comment by graemerocher** [comment]
I have resolved this, but note that if the embedded classes is defined in `src/main/groovy` you will need to add the `@DirtyCheck` annotation. I have updated the upgrade docs to reflect this:

https://github.com/grails/gorm-hibernate5/commit/cd7df4089e0c350af7a1d3f230a8855221b7fd20#diff-61ea76109d46579fd48657f70eab2e40R127
