### ISSUE TITLE
JSON.parse(String) doesn't parse deeply nested structure

### ISSUE THREAD

**Issue by zatziky** [grails/grails-core#10601]
### Task List

**Steps to reproduce**

```
String jsonAsString = '''
{
  lvl1a: 1,
  lvl1b: {
    lvl2: 2
  }
}
'''
JSONElement json = JSON.parse(jsonAsString)
assert json.lvl1b == '{"lvl2":2}' 
```

**Result Expected**
```
assert json.lvl1b == new JSONObject([lvl2: 2])
assert json.lvl1b.lvl2 == 2
```

**Result Actual**
`assert json.lvl1b == '{"lvl2":2}' `

### Expected Behaviour

I want to use a dot notation to access deeply nested elements. `JSON#parse(String)` should result to deeply converted `JSONElement`.

### Actual Behaviour

`JSON#parse(String)` converts only the 1st level keys.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_111

**Comment by jameskleeh** [comment]
I can't reproduce this. Please upload an example project.

<img width="616" alt="screen shot 2017-04-25 at 3 39 26 pm" src="https://cloud.githubusercontent.com/assets/1583789/25404313/6f43b206-29cd-11e7-80a7-4f151302cc17.png">

**Comment by zatziky** [comment]
Sorry @jameskleeh, I will not create an example project as we solved the issue in another way.

However, the error exists. I tried to make a simple case omitting some complexities. To tell you more, the problem arises when a `JSONElement` is serialized to the database using GORM and deserialized back:

```
JSONElements content

def setContent(String contentAsString){
  content = JSON.parse(contentAsString)
}

static constraints = {
   content sqlType: 'text'
}
```
