### ISSUE TITLE
Domain save, flush:true needed (3.2.8)

### ISSUE THREAD

**Issue by senty** [grails/grails-core#10615]
Hi,
i have upgraded grails into 3.2.8 from 3.1.14. Now i have problem with saving of domains.

### Steps to Reproduce
following code:

     final Card card = Card.findById(id)

     card.setTitle(requestCard.getTitle())
     card.setDescription(requestCard.getDescription())
     ... 
     if(card.validate()) {
        card.save()
     
        card.getAdmins()?.clear()
        requestCard.getAdmins().each { final Admin admin ->
           final User user = User.findById(admin.getId())
           if(user){
              card.addToAdmins(user)
              card.save()
           }
         }
     
         render(text: mapperService.objectToJSON(card.toResponseObject(ResponseCard.class)),
            contentType: "application/json",
             encoding: "UTF-8"
         )
     }

### Expected Behaviour

Used to save without any problems CARD instance (and also admins).

### Actual Behaviour

Now CARD instance is not saved (no error raised). When i change 'card.save()' to 'card.save(flush: true)' - card is again saved.
It would not be problem to add flush:true but search for whole application code - thats not cool i guess :-(

### Environment Information

- **Operating System**: masOs Siera 10.12.4
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_101
- **Container Version (If Applicable):** 

Thank you very much for your help !

**Comment by senty** [comment]
Maybe related to https://github.com/grails/grails-core/issues/10602 ?

**Comment by crudolf** [comment]
I have seen this behaviour as well. After upgrading I added `flush: true` to save wherever I added entities to relations via addTo*.

**Comment by jeffbrown** [comment]
There isn't enough code shown in your sample to know in what context that code is executing.  Is a transaction running while that code is executing?  Is there an open Hibernate session (assuming you are using Hibernate)?

Thanks for the feedback.

**Comment by crudolf** [comment]
This happens in a simple controller action:

```
def index(Long id) {
   Card card = Card.get(id)
   User user = User.get(1)
   card.addToAdmins(user)
   card.save()
}
```

Will NOT work. Only works in combination with save(flush: true).

**Comment by senty** [comment]
Hi,
i also provide whole code :

     customUpdate(final Long id){
        final Card card = Card.findById(id)
        if (card == null) {
            return response.sendError(422,
                    errorFormatterService.getErrorMessage("error.card.not.found")
            )
        }

        if (card == null) { ... do smthgn }

        final JSONObject request = request.JSON
        try {
            final RequestCard requestCard = mapperService.mapToObject(request, RequestCard.class)

            // save fields
            card.setTitle(requestCard.getTitle())
            card.setDescription(requestCard.getDescription())

            if(card.validate()){
                card.save(flush: true)

                // save admins
                requestCard.getAdmins().each { final Admin admin ->
                    final User user = User.findById(admin.getId())
                    if(user){
                        card.addToAdmins(user)
                        card.save(flush: true)
                    }
                }

                render(text: mapperService.objectToJSON(card.toResponseObject(ResponseCard.class)),
                        contentType: "application/json",
                        encoding: "UTF-8"
                )
            } else {
                log.error(card.getErrors())
                return response.sendError(HttpStatus.UNPROCESSABLE_ENTITY.value(), card.getErrors().toString())
            }
        } catch (MarshallingException e){
            return response.sendError(HttpStatus.UNPROCESSABLE_ENTITY.value(), e.toString())
        }
    }

Thank you very much

**Comment by jeffbrown** [comment]
Is the code shown above inside of a class that is marked with `@Transactional`?

**Comment by jeffbrown** [comment]
I expect that the code you show will persist as expected if the code you show is executed within a transaction and would not persist as expected if the code is not executed within a transaction.

**Comment by jeffbrown** [comment]
Possibly related to flush mode.  See section 1.2.3 at http://gorm.grails.org/latest/hibernate/manual/index.html#upgradeNotes.

**Comment by crudolf** [comment]
Note that this would break all default examples form the documentation like this:

```
new Author(name:"Stephen King")
        .addToBooks(new Book(title:"The Stand"))
        .addToBooks(new Book(title:"The Shining"))
        .save()
```

**Comment by jeffbrown** [comment]
> Only works in combination with save(flush: true)

I don't think that is true.  I think `flush: true` is just one way to make it work.  Another would be to execute the code inside of a transaction.

**Comment by jeffbrown** [comment]
> Note that this would break all default examples form the documentation like this...

I don't think that is correct.  I think the code you show would work fine if executed inside of a transaction.

**Comment by jeffbrown** [comment]
In general you really shouldn't be modifying the database outside of a transaction anyway.

**Comment by crudolf** [comment]
OK so what you are saying is, that controller actions do not automatically flush and all changes are lost, even when you have called `save()` before?

**Comment by jeffbrown** [comment]
> OK so what you are saying is, that controller actions do not automatically flush and all changes are lost, even when you have called save() before?

It depends.  If the flush mode is set to `COMMIT` and the code is executed outside a transaction, then I think the answer is "yes".

I don't think the solution is to use `flush: true` everywhere `save(...)` is invoked though.  That is going to be unnecessarily expensive for a lot of apps.  A more reasonable approach is to modify the database inside of a transaction and if you were doing that, the answer to your question would be "no".  If you really do want the old Hibernate session to automatically flush, you could add this to your `application.yml`:

```
---
hibernate:
    flush:
        mode: AUTO
```

Does that make sense?

**Comment by jeffbrown** [comment]
See the project at https://github.com/jeffbrown/issue10615.

Clicking links on the main `index.gsp` page will invoke the controller action at https://github.com/jeffbrown/issue10615/blob/548c922ef3abd0399d09273a3a08f1af4d94cd12/grails-app/controllers/issue10615/DemoController.groovy#L4-L11...

```groovy
def index(Long id) {
    Card card = Card.get(id)
    User user = User.get(1)
    card.addToAdmins(user)
    card.save()

    redirect action: 'show', controller: 'card', params: [id: id]
}
```

You will see that the code behaves as expected (the changes are persisted). 

The application has flush mode set to `AUTO` at https://github.com/jeffbrown/issue10615/blob/548c922ef3abd0399d09273a3a08f1af4d94cd12/grails-app/conf/application.yml#L1-L4.

```
---
hibernate:
    flush:
        mode: AUTO
```

Another way to make it work is to leave the flush mode to `COMMIT` (the default now) and then execute the database modifying code inside of a transaction.  The simple way to do that is to mark the controller action (or the whole controller) with `@Transactional`, or even better is to have the controller invoke a transactional service which does the work.

I hope that is all making sense.

**Comment by crudolf** [comment]
Thank you very much for the explanation. I just think, that this behaviour could be error-prone, and there should be some kind of notification or exception if save is called outside of a transaction. But I am not 100% sure, whether I understand the issue and the background behind this completely.

I will stick to the recommended flush mode (COMMIT) and change my code. Thank you!

**Comment by senty** [comment]
Thanks also for explanation.

My controllers / methods does not have transactional annotation and code is not in transaction.

Maybe put into "migration doc" that after 3.2.x(?) "transactional behaviour" changed (in 3.1.14 entities could be saved without transaction annotation or inside transaction).

Thanks !

**Comment by jeffbrown** [comment]
> in 3.1.14 entities could be saved without transaction annotation or inside transaction

FYI... The same is true in 3.2.8.  The sample I linked above demonstrates that.  One thing to consider is what value the flush mode has.

**Comment by jeffbrown** [comment]
> My controllers / methods does not have transactional annotation and code is not in transaction.

In general, I think that is a good thing.  I think that controllers and their actions generally shouldn't be transactional and if request processing needs to modify the database, that should happen in a transactional service (or something else that is transactional in some cases).

**Comment by senty** [comment]
@jeffbrown i agree :-)

**Comment by graemerocher** [comment]
Added documentation to the GORM 6.1 upgrade notes
