### ISSUE TITLE
asset-pipeline FileNotFoundException due to bug in Spring 4.3.8

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#10616]
cause is a spring-core-4.3.8 issue (so this is more or less just for reference):
* spring-projects/spring-boot#8986
* https://jira.spring.io/browse/SPR-15485

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a fresh 3.2.9 app (with asset-pipeline)
2. build a non-development war file (e.g. production)
3. run the war file (e.g. `java -jar myapp.war`)

### Expected Behaviour

http://localhost:8080 should display index page including assets without errors

### Actual Behaviour

```
java.io.FileNotFoundException: Jar URL cannot be resolved to absolute file path because it does not reside in the file system: war:file:/app/app.war*/assets/application-5b03a8ffbc33a9d0a6338728ac19c718.css
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:215)
        at org.springframework.core.io.AbstractFileResolvingResource.getFileForLastModifiedCheck(AbstractFileResolvingResource.java:67)
        at org.springframework.core.io.AbstractResource.lastModified(AbstractResource.java:153)
        at org.springframework.core.io.AbstractFileResolvingResource.lastModified(AbstractFileResolvingResource.java:169)
        at asset.pipeline.AssetPipelineFilter.doFilterInternal(AssetPipelineFilter.groovy:131)
```

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.2.9
- **JDK Version:** oracle 8u121
- **Container Version (If Applicable):** embedded

### Example Application

n/a

**Comment by graemerocher** [comment]
Please report to https://github.com/bertramdev/asset-pipeline/issues

**Comment by graemerocher** [comment]
I'll leave open as we await a third party fix

**Comment by graemerocher** [comment]
Downgraded to Spring 4.3.7 in the meantime

**Comment by todoubaba** [comment]
Spring Framework 4.3.9 is released, https://github.com/spring-projects/spring-boot/issues/9280
