### ISSUE TITLE
grails taglib html builder mix tags

### ISSUE THREAD

**Issue by koctob** [grails/grails-core#10617]
Using TagLibs for grails 3.1 with HTML tag - object:

```
def objectImage = { attrs, body ->
        def mb = new groovy.xml.MarkupBuilder(out)
        mb.object(data: attrs.data, class: attrs.class, type: attrs.type) {
            asset.image(src: attrs.src, class: attrs.class) {}
        }
        mb.span() { mkp.yield attrs.text }
    }
```

Produce:

`<object>text</object>`

instead of 
`
<object></object>text`

Adding quotes to the taglib value: 'object or " object" doesn;t work too.
Even if the usage is 

`<g:objectImage ... ></objectImage><span>text</span> `

the result is the same.

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues

Also make sure to follow the issue template or your issue will be invalidated. Thank you.
