### ISSUE TITLE
Grails hot swap not working

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10611]
### Task List

- [X] Steps to reproduce provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new app with simple controller action (line _render text: "ok"_)
2. start by **grails run-app** (from console or IDEA)
3. application return "ok"
4. Change code (to _render text: "ok new"_)
5. Wait for message in log: TestController.groovy changed, recompiling...
6. Request page again  

### Expected Behaviour

application return "ok new"

### Actual Behaviour

application return "ok" (old value)

### Environment Information

- **Grails Version:** 3.2.9
- **JDK Version:** Java 8

**Comment by graemerocher** [comment]
Working fine for me

**Comment by demon101** [comment]
For second simple app hot swap working. Magic!

**Comment by fsogni** [comment]
I have experienced the same behaviour with 3.2.8, but only if the environment is NOT "development".

**Comment by demon101** [comment]
@fsogni for non-development env hot swap deactivated by default

**Comment by fsogni** [comment]
@demon101, thanks. do you know how to activate it for specific environments?

**Comment by demon101** [comment]
```
disable.auto.recompile=false
grails.gsp.enable.reload=true
```

**Comment by fsogni** [comment]
Unfortunately this doesn't work, but it pointed me to the right direction:
http://mrhaki.blogspot.de/2015/11/grails-goodness-enable-hot-reloading.html

Problem solved. Thanks!

**Comment by mikhalchenko-alexander** [comment]
Same problem in "development" environment. "Reloading active" is "true" in "Application status". I'm using Grails CLI to run the application.

Grails Version: 3.2.4 / 3.2.11 / 3.3.0.RC1
Groovy Version: 2.4.12
Gradle Version: 4.0.1
JVM Version: 1.8.0_131

Please help.

**Comment by igoraguiar** [comment]
Same here. Using Gradle 4 I get the message "File /path/to/file.groovy changed, recompiling..." when a file is changed, but the changes do not take effect. 
Using Gradle 3 solves the problem.

Environment: development
App profile: web
App version: 1.0-SNAPSHOT
Grails version: 3.3.0
Groovy version: 2.4.11
JVM version: 1.8.0_92
Reloading active: true
Linux 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by frangelh** [comment]
Updating to JAVA 1.8.0_144 fixed this to me 

I had
 Grails Version: 3.2.9
Gradle Version: 3.4.1
JVM Version: 1.8.0_77
Windows 10

**Comment by alekhyasivva** [comment]
@fsogni  May i know how you resolved the problem?
When i use 

disable.auto.recompile=false
grails.gsp.enable.reload=true  

in application.yml its only refreshing gsp pages but when i do changes in controller/service it is not changing.

**Comment by fsogni** [comment]
@alekhyasivva 
> in application.yml its only refreshing gsp pages but when i do changes in controller/service it is not changing.

For which enviroment? If it works in development and not in other environments then I had the same problem.
Did you follow the link i mentioned above? I have solved the problem adding these lines to build.gradle:

    // File: build.gradle
    import grails.util.Environment
    ...
    bootRun {
        final Boolean reloadEnabled =
                Boolean.valueOf(
                        System.properties[Environment.RELOAD_ENABLED])
     
        if (reloadEnabled) {
            systemProperty Environment.RELOAD_ENABLED, reloadEnabled
        }
 
    }
    ...

and starting the application with:

    > grails run-app -Dgrails.env=<environment> -Dgrails.reload.enabled=true

I have hot swap for everything, including domain classes where with previous version didn't work all the time.

**Comment by alekhyasivva** [comment]
Thanks @fsogni . It's working now in any environment.
