### ISSUE TITLE
Caused by: org.gradle.api.InvalidUserDataException: Cannot add task ':client:test' as a task with that name already exists

### ISSUE THREAD

**Issue by MadsHLund** [grails/grails-core#10610]
I can't make grails app run with anuglar2. I have created the app with following command:

    grails create-app <NAME> --profile angular2

And when I try to start it up with ./gradlew bootRun --parallel, without any changes, I got following error:

    FAILURE: Build failed with an exception.

    * Where:
    Build file '/*********/client/build.gradle' line: 15
    
    * What went wrong:
    A problem occurred evaluating project ':client'.
    > Cannot add task ':client:test' as a task with that name already exists.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED

Or more specific:

    Caused by: org.gradle.api.InvalidUserDataException: Cannot add task ':client:test' as a task with that name already exists.

I am currently running:

 - Gradle 3.5 
 - Grails 3.2.8

I have tried updating node.js and npm

Does the error relates to Grails or does relate to setup of node?

**Comment by jameskleeh** [comment]
Please try `grails create-app <NAME> -profile angular` with Grails 3.2.9.

**Comment by MadsHLund** [comment]
grails create-app TESTERBARE2 --profile angular2 in 3.2.9 
gives:
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:angular2:jar: in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

**Comment by jameskleeh** [comment]
The command you executed and the command I indicated to run are not the same

`angular2` / `angular`

**Comment by MadsHLund** [comment]
Sorry almost the same...:

FAILURE: Build failed with an exception.

* Where:
Build file '/***/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':client'.
> Cannot add task ':client:test' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jameskleeh** [comment]
What OS? Can you take a screenshot of the folder structure? Is there actually a `build.gradle` file in a `***` folder?

**Comment by MadsHLund** [comment]
I am using macOS the folder is ~/Projects/TestOfGrailsAngular2

If I rename client:test to client:test2 in runs ok.

**Comment by graemerocher** [comment]
Upload an example that reproduces the problem

**Comment by MadsHLund** [comment]
I have uploaded the project here:
[https://drive.google.com/file/d/0B45-JefFM4JnX2UySVpLTGNoOU0/view?usp=sharing](url)

**Comment by MadsHLund** [comment]
@jeffbrown is the example not good enough?

**Comment by MadsHLund** [comment]
Sorry, @jameskleeh but what duplicated content are we talking about here? I haven't changed anything from initialized project.

**Comment by jameskleeh** [comment]
@MadsHLund 

1. Inspect `client/build.gradle`
2. View that it has the same content listed twice
3. Remove the extra content
4. Tell me about the environment in which the application was created

**Comment by MadsHLund** [comment]
@jameskleeh there is no form duplicated content. Besides that the build.gradle is exact the same as the template.

I am using:
macOs
grails 3.2.9 
gradle 2.9 (tried other versions)
groovy


```
plugins {
    id "com.moowork.node" version "1.0.1"
}

node {
    version = '6.9.1'
}

task bootRun(type: YarnTask, dependsOn: 'npmInstall') {
    group = 'application'
    description = 'Start client side server'
    args = ['run', 'start']
}

task test(type: YarnTask, dependsOn: 'npmInstall') {
    group = 'verification'
    description = 'Execute unit tests'
    args = ['run', 'test']
}

task integrationTest(type: YarnTask, dependsOn: 'npmInstall') {
    args = ['run', 'e2e']
}
```

**Comment by jameskleeh** [comment]
When I downloaded your project the entire contents of the `client/build.gradle` file was repeated

**Comment by MadsHLund** [comment]
I see that... seems like the google drive have destroyed the file... 
In the original project there is no duplicates. I tried to make a new file as well.

**Comment by MadsHLund** [comment]
The problem was related to gradle cache.
