### ISSUE TITLE
3.2.9: dependencies missing in pom file

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#10619]
### Steps to Reproduce

1. Clone this multi project sample app: https://github.com/mhuebner/grails329-pom-issue
2. sub1 is a non-grails app, sub2 is a grails app (gradle-grails-plugin applied)
3. run gradlew clean publishToMavenLocal
4. look into the resulting locally published pom file of the project's modules (sub1 and sub2)
5. these missing dependencies are completely breaking our automated builds. So upgrading to Grails 3.2.9 is not possible. We use all these pom stuff in a ton of pipeline builds.

The sample app is a multi project app just so demonstrate the different behaviour of a grails and a non-grails project.

### Expected Behaviour

Modules sub1 **and** sub2 should contain the correct dependencies in their locally published pom files.
**I do not want to publish to grails central or bintray. Just to a plain old maven repo (local or remote).**

### Actual Behaviour

pom file of sub1 (non-grails submodule) **contains every definied compile-dependency**
pom file of sub1 (grails submodule) **does NOT contain the compile dependencies**

When applying the grails-gradle-plugin, this strange behaviour can be seen.

**Some more details:**

sub1 contains the following dependency-block:

```
dependencies {    
    compile "joda-time:joda-time:2.1"
}
```

and the resulting pom contains this dependency as expected:

```
  <dependencies>
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>2.1</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```
sub2 contains these dependencies:

```
dependencies {
    compile "org.codehaus.groovy:groovy:2.4.10"
    compile "org.mindrot:jbcrypt:0.3m"
}
```

The resulting pom file of sub2 misses these dependencies. Just the dependencyManagement block is defined. Groovy and jbcrypt are missing.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.test</groupId>
  <artifactId>sub2</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.6.RELEASE</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
      <dependency>
        <groupId>org.grails</groupId>
        <artifactId>grails-bom</artifactId>
        <version>3.2.9</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

### Environment Information

- **Operating System**: Win64
- **Grails Version:** 2.3.9
- **JDK Version:** OpenJDK 1.8

### Example Application
https://github.com/mhuebner/grails329-pom-issue

**Comment by jameskleeh** [comment]
I can't assemble the project. If sub2 is a grails app, where are the grails dependencies (other than gradle) ?

```Jamess-MacBook-Pro:sample-projects jameskleeh$ cd grails329-pom-issue/
Jamess-MacBook-Pro:grails329-pom-issue jameskleeh$ ./gradlew clean assemble
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.pom
Download https://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.jar
:clean UP-TO-DATE
:sub1:clean UP-TO-DATE
:sub2:clean
:compileJava NO-SOURCE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar
:assemble
:sub1:compileJava NO-SOURCE
:sub1:processResources NO-SOURCE
:sub1:classes UP-TO-DATE
:sub1:jar
:sub1:assemble
:sub2:compileAstJava NO-SOURCE
:sub2:compileAstGroovy NO-SOURCE
:sub2:processAstResources NO-SOURCE
:sub2:astClasses UP-TO-DATE
:sub2:compileJava NO-SOURCE
:sub2:configScript
:sub2:compileGroovy
startup failed:
/Users/jameskleeh/IdeaProjects/sample-projects/grails329-pom-issue/sub2/grails-app/init/sub2/Application.groovy: 3: unable to resolve class grails.boot.GrailsApp
 @ line 3, column 1.
   import grails.boot.GrailsApp
   ^

/Users/jameskleeh/IdeaProjects/sample-projects/grails329-pom-issue/sub2/grails-app/init/sub2/Application.groovy: 4: unable to resolve class grails.boot.config.GrailsAutoConfiguration
 @ line 4, column 1.
   import grails.boot.config.GrailsAutoConfiguration
   ^

2 errors

:sub2:compileGroovy FAILED```

**Comment by mhuebner** [comment]
@jameskleeh I was not able to reproduce your assembling issue. Even a clean repo clone assembles successfully.  Nevertheless I added some core dependencies. Hopefully it will assemble now.

**Comment by graemerocher** [comment]
FWIW I see the same behaviour as @jameskleeh and had to add the core dependencies

**Comment by jameskleeh** [comment]
In the `sub2` module, it does not contain those dependencies:

```
dependencies {
    compile "org.codehaus.groovy:groovy:2.4.10"
    compile "org.mindrot:jbcrypt:0.3m"
}
```

**Comment by graemerocher** [comment]
This seems to be an issue with how you have structured your build. Attached a patch that demonstrates how to get it working.

[10619.patch.txt](https://github.com/grails/grails-core/files/983668/10619.patch.txt)

**Comment by mhuebner** [comment]
@graemerocher thank you for clarifiying. The bahaviour seems to have changed. In 3.2.3 it was ok to apply jave/grails plugins in the subprojects. Now you have to apply them after the maven-plugin is applied. The reason why the publications defined in the subprojects as well as in the root project is that we need to publish the complete build together with all submodules. 

Here is the working example:
```
```
