### ISSUE TITLE
An empty beforeInsert on a domain object corrupts the dirty properties list

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#10613]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a domain class with an empty beforeInsert() method
2. Change a property on an instance of that domain class
3. Observe the value of isDirty(property name) and dirtyPropertyNames

### Expected Behaviour

isDirty(property name) is true and dirtyPropertyNames contains the property name that was changed

### Actual Behaviour
A different property name is in the dirtyPropertyNames list. Might be alphabetical. I originally had my test app with a `name` and `age` field, and when I changed the `name` field the dirty property name was `version`. I replaced the `age` field with `occupation` and the dirty property name was `occupation`.

Tell us what happens instead

### Environment Information

- **Operating System**: Ubuntu MATE 17.04
- **Grails Version:** 3.2.9
- **JDK Version:** 1.8.0_131
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/joemccall86/before-insert-v329

Run `grails test-app -integration`. Observe the failure. In `Person.groovy` delete the `beforeInsert()` method. Run `grails test-app -integration`. Observe that the test passes.

### NOTE
I believe this is an issue introduced by the Hibernate 5 plugin for GORM 6.0.x. I changed the example app to use Hibernate 4 and the test passed.

**Comment by joemccall86** [comment]
I just noticed. This is most likely related to https://github.com/grails/grails-core/issues/10609

**Comment by graemerocher** [comment]
Most likely yes. Note you can revert to hibernate dirty checking with 

```
hibernate.hibernateDirtyChecking = true
```

Which will likely resolve the issue, otherwise you should use `hasChanged(..)`, `getOriginalValue(..)` and `listDirtyPropertyNames()` instead

**Comment by graemerocher** [comment]
This appears to be down to a change in the internal representation of Hibernate state in more recent Hibernate versions. The `getPropertyNames()` method of the `EntityPersister` interface no longer stores these names in the order of the entity model index. I have resolved this and added a test.

**Comment by graemerocher** [comment]
Until 3.2.10 is out you can update your `gormVersion` in `gradle.properties` to either `6.0.11.RELEASE` or `6.1.3.RELEASE` to resolve this issue.
