### ISSUE TITLE
No angular2 profile for 3.2.9?

### ISSUE THREAD

**Issue by mpkerry** [grails/grails-core#10618]
No angular2 profile for 3.2.9?

Used SDK to install grails 3.2.9 - switched to 3.2.9 to test creation of angular2 application

$ grails create-app ng329 -profile=angular2
Resolving dependencies..
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:angular2:jar: in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

### Expected Behaviour
(Using grails 3.2.8)
$ grails create-app ng328 -profile=angular2
| Application created at /Users/extension/Documents/ng328
| 
To get started with this profile, you will need to install the Angular CLI (npm install -g angular-cli).
Currently the CLI requires Node 4.x.x and NPM 3.x.x. https://github.com/angular/angular-cli

To start the Grails application separately, execute "./gradlew server:bootRun"
To start the client side application separately, execute "./gradlew client:bootRun"

To start both the client and server applications simultaneously, execute "./gradlew bootRun --parallel"

### Actual Behaviour

Failure with error message:
Resolving dependencies..
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:angular2:jar: in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

### Environment Information

- **Operating System**: Mac OS X 10.12.4
- **Grails Version:** 3.29
- **JDK Version:**  1.8.0_131
- **Container Version (If Applicable):** N/A

### Example Application

COULD NOT CREATE APPLICATION

**Comment by jameskleeh** [comment]
http://grailsblog.objectcomputing.com/posts/2017/04/12/angular-profiles.html

**Comment by mpkerry** [comment]
Thank you for the quick response - nice to see the blog entry, makes sense  - just would have been helpful to have a note to this effect in the release notes for 3.2.9 https://github.com/grails/grails-core/releases

**Comment by jameskleeh** [comment]
Thanks for pointing that out. I've added it

**Comment by mpkerry** [comment]
Thank you! And btw, this looks really cool: https://grails-plugins.github.io/grails-angular-scaffolding/latest/ <https://grails-plugins.github.io/grails-angular-scaffolding/latest/>

Looking forward to trying it out

Best,
Michael

**Comment by jameskleeh** [comment]
You can try it out now. Any feedback before release is always good
