### ISSUE TITLE
Feature Request - Support params when generating HAL links

### ISSUE THREAD

**Issue by ZacharyKlein** [grails/grails-core#10627]
Currently HAL links don't support URL mappings that include parameters (see sample project), and fallback to default URLs that don't honor URL mappings. 

This request is to allow users to pass in a map of link parameters to be used when generating HAL resource links. Example:

```
hal.render( linkParams: [:] )
```

Sample project: https://github.com/ZacharyKlein/hal-url-mapping-issue

**Comment by ravinatesan** [comment]
Hi Zach, 
Do we have a timeline to fix this issue?
Thanks, Ravi

**Comment by graemerocher** [comment]
Should be reported https://github.com/grails/grails-views/issues

**Comment by sdelamo** [comment]
I've moved it to https://github.com/grails/grails-views/issues/143
