### ISSUE TITLE
lazily loaded beans introduction

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10633]
Due to performance reason, dependencies @Lazy support would be useful in domains and non-singleton controllers

For example for case described in http://grailsblog.objectcomputing.com/posts/2017/05/09/injecting-a-service-into-a-domain-class.html

As I understand, lazily loaded beans implemented in String 4
http://www.tomaszezula.com/2014/01/26/spring-series-part-4-lazy-on-injection-points/

it would be great if Grails will support it

**Comment by jeffbrown** [comment]
I am pretty sure this already works.

**Comment by jeffbrown** [comment]
See the project at https://github.com/jeffbrown/issue10633.

https://github.com/jeffbrown/issue10633/blob/d51a76678765c308dda7844b3354b32e5b5172ec/grails-app/domain/demo/Person.groovy contains the following:

```groovy
package demo

class Person {

    @Lazy
    SomeHelper helper

    String name

    static transients = ['helper']

    void doSomething() {
        helper.doSomething()
    }
}
```

https://github.com/jeffbrown/issue10633/blob/d51a76678765c308dda7844b3354b32e5b5172ec/grails-app/conf/spring/resources.groovy contains the following:

```groovy
// Place your Spring DSL code here
beans = {

    helper(demo.SomeHelper) { bean ->
        bean.scope = 'prototype'
    }
}
```

https://github.com/jeffbrown/issue10633/blob/d51a76678765c308dda7844b3354b32e5b5172ec/grails-app/init/issue10633/BootStrap.groovy contains the following:

```groovy
package issue10633

import demo.Person

class BootStrap {

    def init = { servletContext ->
        10.times {
            new Person(name: 'Good One').save()
            new Person(name: 'Bad One').save()
        }
    }
    def destroy = {
    }
}
```

https://github.com/jeffbrown/issue10633/blob/d51a76678765c308dda7844b3354b32e5b5172ec/src/main/groovy/demo/SomeHelper.groovy contains the following as a simple way to see when the helpers are being constructed:


```groovy
package demo

class SomeHelper {

    SomeHelper() {
        println 'SomeHelper is being instantiated...'
    }

    void doSomething() {
        println 'SomeHelper.doSomething was called'
    }
}
```

When you run the app you should not see any of the "SomeHelper is being instantiated" because they are instantiated lazily.  If you remove the `@Lazy`, they will be eagerly instantiated.

Sending a request to `/demo` will invoke a controller action which forces the helpers to be instantiated because they are used.

I hope that makes sense.

**Comment by jeffbrown** [comment]
That is using Groovy's `@Lazy`.

**Comment by jeffbrown** [comment]
I think you are still paying the price of having the domain class subjected to DI, even if DI isn't happening.

My opinion is that lazily injecting isn't really a great option for most apps.  I think turning the injection off makes more sense.

**Comment by demon101** [comment]
@jeffbrown really cool. It's just working. I like Grails =)
I have made a short check, but I think I get wrong results because of initializing by a debugger.    

> I think turning the injection off makes more sense.
It causes really big changes in application and plugins logic.
For example, Spring security use DI in a domain by default.    

Also, Grails users like magic. Don't switch off this magic for a domain.
Does half solution possible: don't include domain objects to the contexts, but resolve service dependencies?

**Comment by jeffbrown** [comment]
>  Don't switch off this magic for a domain.

We already did, and I think that was the right thing to do.  It is really simple to turn it back on, but off by default I think is the best thing.

**Comment by jeffbrown** [comment]
If you really want the old behavior (DI for domain classes) and are willing to pay the price, you can just add this to your `application.yml`...

```
grails:
    gorm:
        autowire: true
```

**Comment by jeffbrown** [comment]
Just to be clear (I hope), the sample project I mentioned above doesn't really deal with the problem.  Your domain classes are still being subjected to DI and most of the price associated with that is being paid.  What is being deferred is the price of actually instantiating the dependency.

**Comment by demon101** [comment]
>  but off by default I think is the best thing.

It depends on point of view: For simple applications better to switch it on. Disabling make sense only for performance tuning. In this case, big boys can deactivate this feature. But it only my opinion

**Comment by graemerocher** [comment]
@demon101 in 3.3 M1 you can enable it on a per domain basis with:

```groovy
static mapping = {
     autowire true
}
```

Thus you only pay the performance cost for the domains you choose. This change unfortunately cannot be backported to 3.2.x

**Comment by demon101** [comment]
@graemerocher I think current functionality is sufficient. Thx! The issue can be closed.
I will add performance test result to the issue in the future

**Comment by demon101** [comment]
@graemerocher 
Really big overhead on DI in grails 3 (50% on our application !!!!). Will provide more details in https://github.com/grails/grails-core/issues/10589

<img width="795" alt="screen shot 2017-05-11 at 11 04 34" src="https://cloud.githubusercontent.com/assets/1362920/25954347/4ae15602-3666-11e7-931c-341d28d51f56.png">

Black and blue line at right part -- after replacing DI in domains by a simple static facade.

**Comment by lhotari** [comment]
The performance degration can be related to https://github.com/grails/grails-core/commit/3433ecef change. I made a feature request a long time ago to get the optimization included in Spring: https://jira.spring.io/browse/SPR-11864 , however that has never been resolved.
Without the optimization (after 3433ecef), DI has a relatively high overhead. This overhead doesn't really matter if DI isn't used during request processing time. If it is, I'm not surprised by the results that @demon101  is showing.

**Comment by graemerocher** [comment]
Yes and that optimisation was really a hack working around the issue that caused other complications and issues for users. So in reality whilst the issue remains unresolved in Spring we cannot recommend using DI
