### ISSUE TITLE
JAR app don't have resources files added on Grails 3.2.8 and 3.2.9

### ISSUE THREAD

**Issue by nelcab** [grails/grails-core#10637]
I'm doing a deployment of an app for a customer. It's build using Grails *3.2.8* or *3.2.9* as a *fat JAR*.  Everything its going OK, but I got a problem with some files I want to add to it.  I'm putting those files into `src/main/resources` (also tested putting those on `src/main/resources/public`), but it seems that Gradle (I think so) is not adding those files to the JAR file and when I run the app from the JAR it fails to found the files. 
I have checked on its respective `/tmp/tomcat-docbase<number><port>/` and the dir its empty and my app couldn't found those files it needs from this location.  At the beginning it happens to me that I have those files located in `src/main/webapp`, but I read the documentation and find out that when you use the JAR option for deployment, that dir is ignored.  But right now it happens to me the same using the other dir too.  
The files I want to add are some JRXML (jasper) files and its images, which we use to generate some PDF reports for our customers, and we wanted to be included within the JAR file for easier deployment and portability.
Also, other user (@giangio) on the Slack channel is reporting the same issue, using Grails 3.2.8 and didn't happen to him before with 3.2.6.

My gradle.properties is:

`grailsVersion=3.2.9
gormVersion=6.1.0.RELEASE
gradleWrapperVersion=3.5
`

I try to change the graddleWrapper from 3.0, 3.4, 3.5 and 2.14.1, but I have the same result. I'll changing the grailsVersion to 3.2.6 to test on that release.

I'm using the *rest-api* profile for this application.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try to build a JAR instead of a WAR file using Grails 3.2.8

2. Running it from the console.  I'm using this sequence 
` java -Dserver.ssl.enabled=true -Dserver.ssl.key-store=keystore.jks -Dserver.port=8443 -Dgrails.env=prod -Dserver.ssl.key-password="KeyStore Password" -Dserver.ssl.key-store-password="KeyStore Password" -Dserver.tomcat.basedir=./tomcat -jar server.jar >server.stdout.out 2>server.stderr.out &`

3. Check the embedded Tomcar DocBase dir on /tmp to check that the resources files are there.

### Expected Behaviour

Files added into `src/main/resources` should be available for the app on its respective Tomcat DocBase dir. 

### Actual Behaviour

Files are not included, the Tomcat DocBase dir is complety empty. 

### Environment Information

- **Operating System**: Windows & Linux
- **Grails Version:** 3.2.8 and 3.2.9
- **JDK Version:** 1.8.131 and 1.8.121

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
So these are the steps I took.

```
grails create-app res-test --profile rest-api
cd res-test/
mkdir -p src/main/resources/public
echo "hello" > src/main/resources/public/test.html
grails run-app
```

If I go to http://localhost:8080/static/test.html the resource is available.

I then commented out the `war` plugin from `build.gradle` and built a JAR file and did:

```
cd build/libs/
java -jar res-test-0.1.jar
```

The resource was again available at http://localhost:8080/static/test.html

If you are able to provide an example that does reproduce the issue we can take another look.
