### ISSUE TITLE
grails.gorm.autoFlush not working

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#10636]
Hi!

The documentation under http://docs.grails.org/latest/guide/conf.html describes the setting `autoFlush` as the following:

> grails.gorm.autoFlush - If set to true, causes the merge, save and delete methods to flush the session, replacing the need to explicitly flush using save(flush: true).

This seems to be no longer working correct. I debugged the grails code and could discover the following:

- In `AbstractHibernateGormInstanceApi.save()` `shouldFlush(arguments)` get called, this checks if the property `flush `is set in the argument map or not. If the property is not set it returns the member `autoFlush`
```
    protected boolean shouldFlush(Map map) {
        if (map?.containsKey(ARGUMENT_FLUSH)) {
            return ClassUtils.getBooleanFromMap(ARGUMENT_FLUSH, map)
        }
        return autoFlush
    }
```
- The member `autoFlush` is set in the constructor of `AbstractHibernateGormInstanceApi` during startup from the passed datastore.
```
    protected AbstractHibernateGormInstanceApi(Class<D> persistentClass, AbstractHibernateDatastore datastore, ClassLoader classLoader, IHibernateTemplate hibernateTemplate) {
        ...
        this.autoFlush = datastore.autoFlush
        this.failOnError = datastore.failOnError
    }
```
- `AbstractHibernateDatastore.autoFlush` is true if the `defaultFlushMode` equals `FlushMode.AUTO.level`
```
    public boolean isAutoFlush() {
        return defaultFlushMode == FlushMode.AUTO.level;
    }
```
- `AbstractHibernateDatastore.defaultFlushMode` is set in the constructor:
```
    protected AbstractHibernateDatastore(ConnectionSources<SessionFactory, HibernateConnectionSourceSettings> connectionSources, HibernateMappingContext mappingContext) {
        ...
        HibernateConnectionSourceSettings settings = defaultConnectionSource.getSettings();
        HibernateConnectionSourceSettings.HibernateSettings hibernateSettings = settings.getHibernate();
        ...
        this.failOnError = settings.isFailOnError();
        FlushMode flushMode = FlushMode.valueOf(hibernateSettings.getFlush().getMode().name());
        this.defaultFlushModeName = flushMode.name();
        this.defaultFlushMode = flushMode.getLevel();
        ...
    }
```

And this is the actual problem. `grails.gorm.autoFlush` is represented in `settings.isAutoFlush()` (like for `failOnError`) and not `hibernateSettings.getFlush().getMode()`. So the conclusion is that either the code is wrong or the documentation needs to be updated.

**Comment by graemerocher** [comment]
Documentation probably, you should use `hibernate.flush.mode=AUTO` instead

**Comment by andreasschiestl** [comment]
Thank you for the info. Are there possible side effects? Because the hibernate documentation says:

> AUTO
> The Session is sometimes flushed before query execution in order to ensure that queries never return stale state.

This sounds like the change from MANUAL (the default value) to AUTO also effects the flush behavior for queries.

**Comment by graemerocher** [comment]
Yes it does, but it can improve your query performance as flushing the session before every query can become expensive if you are mixing writes and reads.

After considering this issue for a while the best thing to do is deprecate `autoFlush` setting to avoid confusion which is what I have done https://github.com/grails/grails-data-mapping/commit/a39cfc7fefc6b5ceeebf6a819cb08b2979495c0b

Enabling this setting will almost certainly produce undesirable performance for all but the most simple of cases so it doesn't make sense to keep it or fix it.
