### ISSUE TITLE
Command Line Arguments Ignored if passing Java Argument

### ISSUE THREAD

**Issue by busches** [grails/grails-core#10645]
Attempt to start Grails with `-https` and a Java argument.

`grails run-app -https` -> Starts as https
`grails run-app -https -DencryptionPassword=moo` -> Starts as http
`grails run-app -DencryptionPassword=moo -https` -> Starts as http
`grails -DencryptionPassword=moo run-app -https` -> Starts as http

### Expected Behaviour

Grails should pass both the java variable and starts as https.

### Actual Behaviour

`-https` flag is ignored.

### Environment Information

- **Operating System**:  Windows 7x64
- **Grails Version:** `3.2.9`
- **JDK Version:** `1.8.0_131`

**Comment by sdelamo** [comment]
I am not able to reproduce it: I followed the next steps and it started in **`https://localhost:8443`**

```
$ mkdir issue-10645
$ cd issue-10645/
$ grails --version
| Grails Version: 3.2.9
| Groovy Version: 2.4.10
| JVM Version: 1.8.0_121
$ grails create-app demo --inplace
| Application created at /Users/sdelamo/git/github-issues/issue-10645
$ grails -DencryptionPassword=moo run-app -https
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

| Running application...
Grails application running at https://localhost:8443 in environment: development
```

**Comment by busches** [comment]
The root cause is that we have the following setting in our `build.gradle` file.
```
bootRun {
    systemProperties = System.properties
}
```

Which is what we need to do to get our System Properties to persist per the documentation here: http://docs.grails.org/latest/guide/conf.html#ymlOptions

**Comment by zyro23** [comment]
maybe you should consider using
```groovy
bootRun {
    systemProperties System.properties
}
```
without `=`?
that would set the system properties without removing all existing ones.

**Comment by busches** [comment]
@zyro23 Thanks, that worked.
@graemerocher Shouldn't we keep this open to fix the documentation to prevent future issues like this in the future?

**Comment by graemerocher** [comment]
@busches No since it isn't a bug, but of course contributions to the documentation are welcome.
