### ISSUE TITLE
Apostrophe "strange behavior" in message.properties i18n

### ISSUE THREAD

**Issue by jjchiw** [grails/grails-core#10644]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

Giving some properties using apostrophe  it behaves strange...... 
it seems that if we have a message with arguments we have to use two apostrophe  but if we are not using arguments  it works with just one apostrophe, is this how it should work?
```
some.text.one=We'll rock you :P
some.text.two=We''ll rock you :P
some.text.three=We'll rock you {0} :P
some.text.four=We''ll rock you {0} :P
```
```
def index(){
        def one = message(code:"some.text.one")
        def two = message(code:"some.text.two")
        def three = message(code:"some.text.three", args:["yay"])
        def four = message(code:"some.text.four", args:["yay"])

        render text: ["one":one, "two":two, "three":three, "four":four] as JSON
}
```

### Expected Behaviour

```
[
 one:We'll rock you :P,  
 two:We''ll rock you :P, 
 three:We'll rock you yay :P, 
 four:We''ll rock you yay :P
]
```

### Actual Behaviour

```
 [
 one:We'll rock you :P, 
 two:We''ll rock you :P, 
 three:Well rock you {0} :P,
 four:We'll rock you yay :P
]
```

```
/foo/index

Condition not satisfied:
response.json.three == "We'll rock you yay :P"
|        |    |     |
|        |    |     false
|        |    |     4 differences (80% similarity)
|        |    |     We(-)ll rock you ({0}) :P
|        |    |     We(')ll rock you (yay) :P
|        |    Well rock you {0} :P
|        [four:We'll rock you yay :P, one:We'll rock you :P, two:We''ll rock you :P, three:Well rock you {0} :P]
grails.plugins.rest.client.RestResponse@119d59c5

	at sample.FooControllerSpec.$tt__$spock_feature_0_0(FooControllerSpec.groovy:39)
	at sample.FooControllerSpec./foo/index_closure3(FooControllerSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:70)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:67)
	at sample.FooControllerSpec./foo/index(FooControllerSpec.groovy)
```

### Environment Information

- **Operating System**: Win10
- **Grails Version:** 3.2.9
- **JDK Version:** 1.8.0_121

### Example Application

https://github.com/jjchiw/sample-properties-grails-3.2.9

It has a controller integration test :)

**Comment by jameskleeh** [comment]
I don't think anything can be done here as that is just how `java.text.MessageFormat` works. Since there is a single quote, it assumes the rest of the string is part of the quote, so variable substitution doesn't work.

**Comment by jameskleeh** [comment]
https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html

**Comment by vsachinv** [comment]
For anyone looking for solution, should use double single quotes in messages.properties for single quote.

https://stackoverflow.com/questions/17544794/escaping-single-quotes-for-java-messageformat
https://tonnygaric.com/blog/escape-single-quotes-when-using-java-messageformat
