### ISSUE TITLE
migrate version 2.5 to 3.18 grails and hibernate 4 to hibernate 5

### ISSUE THREAD

**Issue by JJAM2014** [grails/grails-core#10648]
Hi,
environment
S.O Ubuntu 16.04
Grails version 3.1.8
DB mySql 5.7.18

I had a project in 2.5 version grails, with these domains,

```
class Padre {
    String name
    static hasOne =    [hija:Hija, hijaPol:HijaPol]
    static constraints = {
        hija nullable:true
        hijaPol nullable:true
    }
}
class Hija {
    String name
    static belongsTo =[padre:Padre]
    static constraints = {
    }
}
class HijaPol {
    String name
    static belongsTo =[padre:Padre]
    static constraints = {
    }
}  
```
data of DB mysql
Padre
id | name
1 | nameFather

Hija
id | name                | Padre_id
1  | nameDaughter | 2 

When I  use 2.5 version Grails and Hibernate 4 all run OK, and Padre class has relationship with other class for example Padre.id=1 Padre.hija=2
but when I use 3.1.8 version grails and hibernate 5 

Padre.id=1  ----> Padre.hija=1 the relationship  is perform with id of child
 thanks you

best regards

José

**Comment by JJAM2014** [comment]
the problem is that the class father has relation with the id class child and not with foreing_key

**Comment by sdelamo** [comment]
@JJAM2014 Could you please link to a public repository where I could see the differences between Grails 2 and Grails 3 applications for your domain classes?

**Comment by JJAM2014** [comment]
I have uploaded a zip file with grails 3 project 
[pruebarelaciones.zip](https://github.com/grails/grails-core/files/1029067/pruebarelaciones.zip)

**Comment by JJAM2014** [comment]
I will attached the grails 2.5 project  and dump of DB
[db_grails25.zip](https://github.com/grails/grails-core/files/1029169/db_grails25.zip)

**Comment by JJAM2014** [comment]
if I list the  Padre class and his reslationship with  Hija class with 2.5 id:4 for Padre relation with id:2 of  Hija, but if I list with grails 3 id:5 for Padre with id:2 of Hija

![db](https://cloud.githubusercontent.com/assets/8511038/26453578/82e3dc7e-4164-11e7-9909-2476b6f75ec6.jpg)

**Comment by sdelamo** [comment]
I don't understand the issue @JJAM2014 I configured your domain classes and started the app with the Bootstrap configuration in Grails 3.2.9. 

I get the expected database entries as illustrated in the next image: 

![issue-10648_hija_pol_-_datagrip_2017_1_2_and_issue-10648_padre_-_datagrip_2017_1_2_and_issue-10648_hija_-_datagrip_2017_1_2_and_issue_10648_sql_-_issue-10648_and_bootstrap_groovy_-_issue-10648_-____git_github-issues_issue-10648_issue-10648_](https://cloud.githubusercontent.com/assets/864788/26537413/9efad344-443f-11e7-8c07-b01827cc0ea3.png)

I am going to close the issue. If you find it still unresolved, open it again and comment about what is your expected output and how it differs from the screenshot attached above.

**Comment by JJAM2014** [comment]
Hi

Igualmente I'm going send a new grails versión bit the problem isn't data else how read the data

**Comment by sdelamo** [comment]
Ok, please if you have a different issue, create a pullrequest with at much information as possible
