### ISSUE TITLE
Grails 3.2.x: rollback behavior for `Exception` is changed.

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#10659]
I've found the issue related this.

> Regression in DomainClass.withTransaction WRT rollback on checked exception
> https://github.com/grails/grails-core/issues/9998

If limited only to a programmatic transaction, the fix might be valid. However, the fix has affected not only to a programmatic transaction, but a declarative transaction by `@grails.transaction.Transactional`.

Additionally, this change of a rollback behavior is too big, but there is no notice and documentation on the release.

To tell the truth, I can accept the new behavior because in my almost usecase, I want to do rollback for ANY EXCEPTION (including a checked exception).

In that case, the problem is just a documentation error:

> The result is that all methods are wrapped in a transaction and automatic rollback occurs if a method throws a runtime exception (i.e. one that extends RuntimeException) or an Error. The propagation level of the transaction is by default set to PROPAGATION_REQUIRED.
>
> Checked exceptions do not roll back transactions. Even though Groovy blurs the distinction between checked and unchecked exceptions, Spring isn’t aware of this and its default behaviour is used, so it’s important to understand the distinction between checked and unchecked exceptions.
>
> http://docs.grails.org/latest/guide/services.html#declarativeTransactions

and

> In this example we rollback the transaction if the destination account is not active. Also, if an unchecked Exception or Error (but not a checked Exception, even though Groovy doesn’t require that you catch checked exceptions) is thrown during the process the transaction will automatically be rolled back.
>
> http://gorm.grails.org/6.0.x/hibernate/manual/index.html#programmaticTransactions

-------------------

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. throw `Exception` from a programmatic transaction (or from a Declarative transaction by `@grails.transaction.Transactional`)
2. The transaction is rolled back, although the documentation wrote as "Checked exceptions do not roll back transactions".

### Expected Behaviour (based on documentation)

| Method | thrown RuntimeException | thrown Error | thrown Exception (w/ throws) | thrown Exception (w/o throws) |
|--|--|--|--|--|
| Programmatic transaction | rollback | rollback | -- | commit |
| Declarative transaction by `@grails.transaction.Transactional` | rollback | rollback | commit | commit |
| Declarative transaction by `@org.springframework.transaction.annotation.Transactional` | rollback | rollback | commit | commit |

### Actual Behaviour

| Method | thrown RuntimeException | thrown Error | thrown Exception (w/ throws) | thrown Exception (w/o throws) |
|--|--|--|--|--|
| Programmatic transaction | rollback | rollback |-- | rollback |
| Declarative transaction by `@grails.transaction.Transactional` | rollback | rollback | rollback | rollback |
| Declarative transaction by `@org.springframework.transaction.annotation.Transactional` | rollback | rollback | commit | commit (wrapped by `UndeclaredThrowableException`) |

### Environment Information

- **Grails Version:** 3.2.10
- **Groovy Version:** 2.4.10
- **JVM Version:** 1.8.0_131

### Example Application

* https://github.com/nobeans/grails-issues/tree/master/g3210-transaction-rollback-for-exception/src/integration-test/groovy/transaction/sample

**Comment by nobeans** [comment]
Which one is wrong, current behaviors or documentation?

**Comment by graemerocher** [comment]
Documentation is incorrect

**Comment by sdelamo** [comment]
Thanks for submitting @nobeans We have fixed the docs.

**Comment by nobeans** [comment]
OK. Thanks.
