### ISSUE TITLE
Feature request: Add command to generate wrapper for upgraded projects

### ISSUE THREAD

**Issue by tlefevre** [grails/grails-core#10667]
The grails wrapper has been re-introduced, but the wrapper script has not been re-introduced. Can we please have it back?

**Comment by jameskleeh** [comment]
I don't understand this request. Can you clarify what you mean by "wrapper script" ?

**Comment by tlefevre** [comment]
I would like to be able to run "grails wrapper" much the same as I can run "gradle wrapper" and have it create the wrapper for me.

**Comment by jameskleeh** [comment]
The wrapper comes with all new projects by default. What is the use case?

**Comment by tlefevre** [comment]
When I am upgrading grails from a version that had no wrapper to a version that has.

**Comment by jeffbrown** [comment]
I don't think adding the script is terribly valuable.  It is simple enough to create a new project and copy the files from that.  I do that for every app I upgrade anyway.  I create a new empty project with the new version and copy config files from there.
