### ISSUE TITLE
FindAllBy* NotInList not working

### ISSUE THREAD

**Issue by Gnuko** [grails/grails-core#10661]
### Steps to Reproduce

1. Call in domain class: Domain.findAllByXY**Not**InList

### Expected Behaviour

Should return all domain that XY is **not** in provided list.

### Actual Behaviour

Return all domains that XY is in provided list.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.9
- **JDK Version:** jdk1.8.0_131

**Comment by jeffbrown** [comment]
FYI... As a workaround, instead of doing this:

    Domain.findAllByXYNotInList(['val1', 'val2'])

You could do something like this:

    Domain.where {
        !(name in ['val1', 'val2'])
    }.list()

**Comment by jameskleeh** [comment]
https://github.com/grails/grails-core/issues/9718

**Comment by jeffbrown** [comment]
If `*NotInList` isn't going to be supported then I think invoking it should result in an exception, not returning incorrect data.

**Comment by graemerocher** [comment]
Duplicates https://github.com/grails/grails-data-mapping/issues/828
