### ISSUE TITLE
Running create-app in HOME creates app in wrong dir.

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#10668]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
```
$ sdk use grails 3.2.10
$ cd ~
$ grails create-app t4
| Application created at /Users/erichelgeson/.sdkman/candidates/grails/3.2.10/bin/t4
```
### Expected Behaviour

App should be created in cwd - `/Users/erichelgeson/t4`

### Actual Behaviour

App created here instead `/Users/erichelgeson/.sdkman/candidates/grails/3.2.10/bin/t4`

Non home dirs do work as expected:
```
$ cd ~/source
$ source grails create-app t3
| Application created at /Users/erichelgeson/source/t3
```

### Environment Information

Tested on 2 macs, both with zsh and bash shells.

- **Operating System**: Mac 10.12.5
- **Grails Version:** 3.2.10
- **JDK Version:** 8u131

**Comment by jameskleeh** [comment]
I think this has something to do with sdkman since `new File('.')` and `System.getProperty('user.dir')` both point to sdkman in the CLI

**Comment by jameskleeh** [comment]
I'm checking it inside of the Grails CLI execution via a remote debugger

**Comment by erichelgeson** [comment]
@marc0der any idea if sdkman may be causing this behavior?

**Comment by marc0der** [comment]
Not as far as I know.

I do have a question regarding this report: does this only happen when using the sdk use command? What happens if you are using the default version without the sdk use command? 

Are you are seeing the same behaviour in both cases?

**Comment by jameskleeh** [comment]
Perhaps this isn't an issue with sdkman

```
Jamess-MacBook-Pro:~ jameskleeh$ Downloads/grails-3.2.9/bin/grails create-app foo
| Application created at /Users/jameskleeh/Downloads/grails-3.2.9/bin/foo
Jamess-MacBook-Pro:~ jameskleeh$ mkdir temp
Jamess-MacBook-Pro:~ jameskleeh$ cd temp
Jamess-MacBook-Pro:temp jameskleeh$ ../Downloads/grails-3.2.9/bin/grails create-app foo
| Application created at /Users/jameskleeh/temp/foo
```

**Comment by erichelgeson** [comment]
Thanks @marc0der, should have tried that first. I get the same results as you @jameskleeh

**Comment by graemerocher** [comment]
Seems to be a bug in the Gradle `application` plugin. It is caused by this line in the `grails` script:

https://github.com/gradle/gradle/blob/master/gradlew#L168

The `grails` script is generated by Gradle's `application` plugin. Not sure what we can do about this. Needs a report to the Gradle issue tracker I guess.

**Comment by jameskleeh** [comment]
We could supply our own https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt

**Comment by okc0mputer** [comment]
I still experience this behavior, is there any news regarding this issue?

**Comment by jameskleeh** [comment]
@okc0mputer The news is the issue is resolved and will be included in the next release
