### ISSUE TITLE
Grails 3.3.0.M2: blank angularjs profile application raise exeption

### ISSUE THREAD

**Issue by ykanomata** [grails/grails-core#10672]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create-app --profile=angularjs myapp
2. run-app
3. open http://localhost:8080/

### Expected Behaviour

Show index page.

### Actual Behaviour

Show error:  {"message":"Internal server error","error":500}
Console output: ERROR --- [nio-8080-exec-1] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'] with root cause

### Environment Information

- **Operating System**: Windows10
- **Grails Version:** 3.3.0.M2
- **JDK Version:** 1.8.0.92

**Comment by jameskleeh** [comment]
Fixed. You can do `-profile org.grails.profiles:angularjs:1.1.0` in the meantime before a new release of Grails
