### ISSUE TITLE
dbProperties set on dataSource no longer works when deployed to tomcat

### ISSUE THREAD

**Issue by lbwexler** [grails/grails-core#10673]
### Steps to Reproduce
1) Upgrade to Grails 3.3.0 M2

2) Include in your application.groovy a dataSource spec of the following form. 

```groovy
dataSource {
     pooled = true
     jmxExport = true
     driverClassName = "com.mysql.jdbc.Driver"
     dialect = org.hibernate.dialect.MySQL5InnoDBDialect
     username = 'user'
     password = 'password'
     dbCreate = "update" 
     url = "jdbc:mysql://localhost/piq?useUnicode=yes&characterEncoding=UTF-8"
     properties {
            dbProperties {
                     useSSL = false
              }
     }
 }
```

3) See exception preventing app startup  
[out.txt](https://github.com/grails/grails-core/files/1066801/out.txt)

4) Remove the 'dbProperties' block, and see that all works fine again.

### Expected Behaviour
App Should start normally when run in a tomcat container

### Actual Behaviour
Receive the Stacktrace attached instead.   Note the key lines at the very end

> Caused by: java.lang.NullPointerException: null
> 	at java.util.Hashtable.put(Hashtable.java:459)
> 	at java.util.Properties.setProperty(Properties.java:166)
> 	at com.mysql.jdbc.NonRegisteringDriver.parseURL(NonRegisteringDriver.java:808)
> 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:321)
> 	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310)

### Environment Information
- **Operating System**:  Mac 10.12.4/Windows 7/Linux
- **Grails Version**: 3.3.0.M2 
- **JDK Version**: 1.8.0_131
- **Container Version (If Applicable)**: Tomcat 8.5.15

**Comment by graemerocher** [comment]
driver properties need to be strings so can be worked around with:

```groovy
     properties {
            dbProperties {
                     useSSL = "false"
              }
     }
```

But yes this is a regression and we should be doing this coercion automatically
