### ISSUE TITLE
gorm.autowire not working in unit tests

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#10678]
Given the domain class: 

```
package demo

import groovy.transform.CompileStatic

@CompileStatic
class Person {
    PersonService personService
    String name

    static transients = ['personService']

    String hi() {
        personService.sayHello(name)
    }
}
```

and the service: 

```
package demo

import groovy.transform.CompileStatic

@CompileStatic
class PersonService {

    String sayHello(String name) {
        "Mr $name"
    }
}
```

With `gorm.autowired` turn on in `application.yml`

```
---
grails:
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: true
```

The next Integration Tests passes:

```
package demo

import grails.test.mixin.integration.Integration
import spock.lang.Specification

@Integration
class PersonIntegrationSpec extends Specification {

    def "service is injected"() {
        when:
        def person = new Person(name: 'Sergio')
        def text = person.hi()

        then:
        noExceptionThrown()
        text == 'Mr Sergio'
    }
}
```

while the next Unit test fails; throwing a null pointer exception because the service is not wired. 

```
package demo

import grails.test.hibernate.HibernateSpec

class PersonSpec extends HibernateSpec {

    List<Class> getDomainClasses() { [Person] }

    def "service is injected"() {
        given:
        def domain = new Person()

        when:
        domain.name = 'Sergio'
        def text = domain.hi()

        then:
        noExceptionThrown()
        text == 'Mr Sergio'
    }
}
```

### Expected Behaviour

I expected services to be injected in Unit tests

### Actual Behaviour

Services are not injected in unit tests. 

### Environment Information

- **Operating System**: MacOS
- **Grails Version:** Grails 3.2.10
- **JDK Version:** 1.8.0_121"

### Example Application

https://github.com/grails-core-issues-forks/grails-core-issue-10678

**Comment by sdelamo** [comment]
Actually services should not be injected in Unit tests so I think it is behaving properly

**Comment by saw303** [comment]
This is new to me. At least this was working for ages (even in Grails 2).

The service is actually the Spring Security Service (of the Grails 3 plugin) that encodes the plain text password before inserting or updating the user entity. I also use to in Domain custom validators.

Is there a new strategy to solve these problems? Can you recommend some other approach?

**Comment by graemerocher** [comment]
See http://docs.grails.org/3.3.x/guide/upgrading.html 

Section "Domain Autowiring Disabled"

**Comment by saw303** [comment]
Thank you very much. I missed this.
