### ISSUE TITLE
Grails 3.3.0.M2 - RestfulController @Transactional not working

### ISSUE THREAD

**Issue by bysouleater** [grails/grails-core#10684]
### Steps to Reproduce

1. Create Grails app with Grails 3.3.0.M2 with rest-api profile
2. Connect with MySQL database
3. Create a Domain Resource
3. Make a POST request to created Domain Resource

### Expected Behaviour

A row is inserted to the MySQL Database.

### Actual Behaviour

500 - Internal Server Error.

An error about having a ReadOnly connection is printed in the console.

### Workaround

I found that RestfulController now uses a different @Transactional annotation. The whole controller is annotated with ReadOnly true and overwritten with @Transactional in save, patch, update, delete. Seems this is not enough. But if you create a subclass of this Controller, and annotate those methods correctly with @Transactional(readOnly = false) they now work.

### Environment Information

- **Operating System**: Mac OSX - Sierra
- **Grails Version:** 3.3.0.M2
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/4ccc0aa280b7d56f8b532e51ef4956c004179d96
