### ISSUE TITLE
Gorm 6.1.4: Stackoverflow error when extending a Transactional generic base class

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10681]
This issue is supposed to be fixed in Gorm 6.1.2. but it is not, and still, in some situations, it will cause stackoverflow error.

See attached sample app, which is a grails **3.2.8 app with Gorm 6.1.4** and uses **grails.gorm.transactions.Transactional** annotation.. but still fails with stackoverflow errors

Steps to reproduce:
run `gradle check` on the sample app

[bugwork1-bug-report-16062017.zip](https://github.com/grails/grails-core/files/1080645/bugwork1-bug-report-16062017.zip)

Related issue https://github.com/grails/grails-core/issues/10088

**Comment by graemerocher** [comment]
This issue is slightly different than the original and is due to the use of generics in `BaseService`.

**Comment by snimavat** [comment]
So a valid issue right, and need a  fix...

**Comment by graemerocher** [comment]
I applied a fix for this. It requires that you add `@Override` to the child method. Since the complexity of resolving super methods for generics is too much

**Comment by snimavat** [comment]
Thanks for the quick fix.
