### ISSUE TITLE
meta tag for "info.app.version" not working if systemProperties = System.properties added in bootRun task 

### ISSUE THREAD

**Issue by aminul2050** [grails/grails-core#10690]
I've created a new Grails project (3.2.10) and run. The default index page showing correctly app name and version meta tag. Then i added systemProperties in bootRun task (build.gradle) as below: 
bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    addResources = true
    systemProperties = System.properties
}

Now, <g:meta name="info.app.version"/> meta tag in index.gsp page shows as "@info.app.version@".
Comment out systemProperties working fine again.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.10
- **JDK Version:** 1.8.0_122

### Example Application
- https://github.com/aminul2050/metaNameTest

**Comment by zyro23** [comment]
```groovy
bootRun {
    systemProperties System.properties
}
```
use the `systemProperties` method (without `=`). that appends the system properties instead of replacing all existing ones.

ref. https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html
