### ISSUE TITLE
Map constructor does not assign String to Object

### ISSUE THREAD

**Issue by chris13524** [grails/grails-core#10692]
Originally asked here: https://stackoverflow.com/questions/44742434/map-constructor-does-not-assign-string-to-object-in-grails

Given the following domain class:

    class Dog {
        Object name // changing the type to String fixes it
    }

And this unit test:

    import grails.test.mixin.Mock
    import grails.test.mixin.TestMixin
    import grails.test.mixin.support.GrailsUnitTestMixin
    import spock.lang.*
    
    /**
     * See the API for {@link grails.test.mixin.support.GrailsUnitTestMixin} for usage instructions
     */
    @TestMixin(GrailsUnitTestMixin)
    @Mock([Dog])
    class DogSpec extends Specification {
    
        def setup() {
        }
    
        def cleanup() {
        }
    
        void "test something"() {
            Dog dog = new Dog(name:"sparky")
            // dog.name = "sparky" // adding this line also fixes it
            expect:"fix me"
                dog.name == "sparky"
        }
    }

Running `grails test-app` fails, but if you change the type of `Dog.name` to `String`, it works fine. Debugging brings me to realize that `Dog.name` never gets assigned and is `null`. If I were to set `dog.name` via regular assignment after constructing it as above, the test passes.

This issue does not occur in Groovy Script using the same map constructor assignment.

I want my type to be `Object` as it varies depending on the use case.

### Expected Behaviour

`Dog.name` is assigned to "sparky"

### Actual Behaviour

`Dog.name` never gets assigned and is null.

### Environment Information

- **Operating System**: Ubuntu 17.04
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_131
- **Container Version (If Applicable):** TODO

### Example Application

https://github.com/chris13524/grails-no-object-assignment

**Comment by graemerocher** [comment]
Binding to object types is disallowed by default to avoid injection attacks. You have to apply `bindable: true` see http://docs.grails.org/latest/ref/Constraints/bindable.html
