### ISSUE TITLE
JSONObject.toString() doesn't work for Map constructor

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#10694]
There is a strange behaviour of `new JSON(Map)` constructor when calling `.toString()` afterwards.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `new JSONObject([some: [nesting: "test"]]).toString()`

### Expected Behaviour

It should build proper JSON with nested elements.

### Actual Behaviour

It cannot build nested elements.

### Environment Information

- **Operating System**: OSX
- **Grails Version:** 3.2.8
- **JDK Version:** 8

### Example Application
```
import org.grails.web.json.JSONObject

def test1 = new JSONObject('{some: {nesting: "test"}}')
def test2 = new JSONObject([some: [nesting: "test"]])

test1.toString()
// output: '{"some":{"nesting":"test"}}'
test2.toString()
// output: '{"some":"{nesting=test}"}'
```

**Comment by anti43** [comment]
how is this a grails bug ?

**Comment by kuceram** [comment]
As this is class from grails-core, I guess it is a Grails bug.

https://github.com/grails/grails-core/blob/master/grails-web-common/src/main/groovy/org/grails/web/json/JSONObject.java

**Comment by jameskleeh** [comment]
Pretty sure this class is not designed to be used that way. You should new `new JSON(map).toString()`

**Comment by graemerocher** [comment]
Like @jameskleeh said: don't use `JSONObject` directly, use `JSON`
