### ISSUE TITLE
Gorm data service @Where method not supporting association queries

### ISSUE THREAD

**Issue by ilmoralito** [grails/grails-core#10707]
Gorm data service @Where method not supporting association queries

In a service annotated with @service(DomainName) and having Band and Album domain classes with a one to many relationship when i try a query like

`@Where({ name == bandName && albums { name == albumName } })`

or

`@Where({ name == bandName && albums.name == albumName })`

I am getting a java.lang.ClassCastException

I want to implement a where query that look like this

`
    List<Band> bandList = Band.where {
        name == 'Band1' && albums { name == 'Album1' }
    }.list()
`

### Steps to Reproduce

1. Clone repo https://github.com/ilmoralito/issue-gorm-data-service-where-method
2. Run the app and go to http://localhost:8080/band/index

### Expected Behaviour

It should render a list of bands

### Actual Behaviour

Getting a java.lang.ClassCastException
Caused by
    org.grails.datastore.gorm.query.criteria.DetachedAssociationCriteria cannot be cast to groovy.lang.Closure

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.2.9
- **GORM Version:** 6.1.5.RELEASE
- **JDK Version:** Using java version 8u121

### Example Application

- https://github.com/ilmoralito/issue-gorm-data-service-where-method

**Comment by zyro23** [comment]
dup. grails/grails-data-mapping#968 ?
