### ISSUE TITLE
Null variables in url mapping when using resources and collection

### ISSUE THREAD

**Issue by ilmoralito** [grails/grails-core#10711]
### Steps to Reproduce

Having the following code in UrlMappings.groovy file

![code](https://user-images.githubusercontent.com/928920/27810118-9f2e8a3c-6013-11e7-9eb1-4a46ac6df31c.png)

When running url-mappings-report command variables in collection are null 

### Expected Behaviour

![excpected](https://user-images.githubusercontent.com/928920/27809937-b6b95bde-6011-11e7-8103-173b14f35afe.png)

### Actual Behaviour

![actual](https://user-images.githubusercontent.com/928920/27809906-5905f524-6011-11e7-807b-91f6d69c1b80.png)

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** Using grails version 3.2.9
- **JDK Version:** Using java version 8u121

### Example Application

- SO Question: https://stackoverflow.com/questions/44837744/null-variables-in-url-mapping-when-using-resources-and-collection
- https://github.com/ilmoralito/Null-variables-resources-collection

**Comment by theleancoder** [comment]
@ilmoralito Looking into the issue.

**Comment by theleancoder** [comment]
@ilmoralito Looks like ```collection``` with ```resources``` doesn't support variables. If you're using a resource with GET, you'll always have a ```${ticketId}``` appended to the ```"/tickets/``` url.

I guess, in this example, you want to get history of a given ticket. If that's the case, you can do this:
```
'/tickets'(resources: 'ticket') {
    "/history/"(controller: 'ticket', action:'history', method: 'GET')
}

**Comment by ilmoralito** [comment]
@theleancoder Thanks for your time and help.

For the time being what I am doing is to place the URL definitions with variables outside of the resource statement

![untitled](https://user-images.githubusercontent.com/928920/27839657-37d6de46-60b0-11e7-92a0-2f9bdb7df1d2.png)

Again thanks for the recommendation. Is there any plan to add variable support within the collection?

**Comment by theleancoder** [comment]
@ilmoralito Welcome. You can always suggest any new feature in the issue tracker or make a pull request if you can figure out a solution.
