### ISSUE TITLE
conf/runtime.groovy isn't loaded if application.groovy doesn't exist

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#10719]
When `conf/application.groovy` exists, `conf/runtime.groovy` is loaded expectedly. But if not exists, `conf/runtime.groovy` isn't loaded.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create `grails-app/conf/runtime.groovy` with some logging code and throwing an exception (like [this](https://github.com/nobeans/grails-issues/blob/master/g3211-runtimegrooy/grails-app/conf/runtime.groovy))
2. Run the application.
3. Create `grails-app/conf/application.groovy` with some logging code (like [this](https://github.com/nobeans/grails-issues/blob/master/g3211-runtimegrooy/grails-app/conf/application.groovy))
4. Run the application.

### Expected Behaviour

- `2.` -> There is the log lines on console and failed to `run-app`.
- `4.` -> There is the log lines on console and failed to `run-app`.

### Actual Behaviour

- `2.` -> There is **no log lines** on console and **the application started up without any problem** even though an exception is thrown in `runtime.groovy`.
- `4.` -> There is the log lines on console and failed to `run-app`, expectedly.

### Environment Information

Operating System: macOS 10.12.5
Grails Version: 3.2.11
JDK Version: 1.8.0_131

### Example Application

- https://github.com/nobeans/grails-issues/tree/master/g3211-runtimegrooy

**Comment by demon101** [comment]
Not reproduced in my grails 3.2.11 app.
@nobeans does application.yml presented in your app?

**Comment by nobeans** [comment]
Did you use the example application?
> https://github.com/nobeans/grails-issues/tree/master/g3211-runtimegrooy

application.yml is [here](https://github.com/nobeans/grails-issues/blob/master/g3211-runtimegrooy/grails-app/conf/application.yml).

**Comment by jameskleeh** [comment]
@nobeans The whole point of having a `runtime.groovy` is to place configuration that requires classes on your projects classpath. The entire configuration should not be placed there as none of it is read during any commands, scripts, etc. Due to that and technical reasons, I think the current behavior is correct.

**Comment by nobeans** [comment]
The reason that my sample is using `conf/` directory is simplicity just for a sample. I don't intend to use the directory in production runtime environment.

My question is "why the behaviors are different between `application.groovy` exists and not."
Is it really the correct behavior?
