### ISSUE TITLE
Configure ast sourceset for applications too not just plugins

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10717]
Currently, GrailsPluginGradlePlugin configures AST sourceset for plugin projects see [here](https://github.com/snimavat/grails-core/blob/3442db5e34ad1a1f43dae647ded5a8e8c42779a9/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy#L121-L121)

This makes it easy to have @Enhances and other AST in the same project under src/ast/groovy, and still have it applied. however the ast sourceset isnt available for applications.

**Comment by graemerocher** [comment]
transforms have to be within a JAR for them to work correctly because otherwise they may be compiled at the same time as the target class hence why this only applies to plugins.

**Comment by snimavat** [comment]
@graemerocher ast is a seperate sourceset which gets compiled before the main sources and is in classpath of main sourceset, wouldnt it work ? -- it already works for plugins. If i have a transform in src/ast directory within plugin, the transform will apply to the classes in same plugin too.. The same way it can apply for application, if there was an ast sourceset

**Comment by graemerocher** [comment]
Only for Gradle, for Intellij everything gets compiled together and besides that Intellij also doesn't place build resources on the classpath for compilation which causing further problems. So right now adding this would simply confuse users.

**Comment by snimavat** [comment]
Wouldnt expect intellij to work, anyway gradle is going to be used to package jar or war.

Will you consider this if there is a PR @graemerocher ?

**Comment by jameskleeh** [comment]
@snimavat Perhaps this would be better served as a guide to show how to implement this. It would also include the warnings about IntelliJ, etc

**Comment by snimavat** [comment]
@jameskleeh do you mean, a guide that explains how to setup the ast sourceset ?
Yeah will work, but i was just wondering, if we did this for plugins why not applications.

**Comment by snimavat** [comment]
if some one hit this ticker -- Here's how to do it http://nimavat.me/blog/apply-groovy-ast-in-same-project-with-custom-gradle-ast-sourceset

**Comment by jeffbrown** [comment]
https://twitter.com/nulleric/status/885867179689869312
