### ISSUE TITLE
Calling stop-app in interactive mode reports an error in Grails 3.3.0.RC1

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10724]
### Steps to Reproduce

1. Use Grails 3.3.0.RC1 and create a brand new app `grails create-app helloworld`
2. Then chance into directory `helloworld` and execute `grails`
3. Then run `start-app`
4. After the app has started run `stop-app`

### Expected Behaviour

The app should stop without any errors

### Actual Behaviour

```
grails> stop-app
| Shutting down application...
| Error Application not running.
```

### Environment Information

- **Operating System**: macOs
- **Grails Version:** 3.3.0.RC1
- **JDK Version:** 1.8.0_131

**Comment by fsogni** [comment]
The same with 3.2.8:

| Application not found via JMX, attempting remote shutdown.
| Shutting down application...
| Error Application not running.
