### ISSUE TITLE
findAll NotInList works wrong

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10727]
### Task List

- [X] Steps to reproduce provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1.  Create domain with enum field
2.  Enum should have id field (not sure, can be optional step)  
3.  Do Domain.findAllByTypeNotInList([TYPE1, TYPE2])

### Expected Behaviour

Domains with type != (TYPE1, TYPE2)  returns

### Actual Behaviour

Domains with type == (TYPE1, TYPE2)  returns
 Domain.findAllByTypeNotInList([TYPE1, TYPE2])  works same with  Domain.findAllByTypeInList([TYPE1, TYPE2])

It works well in grails 2

### Environment Information

- **Grails Version:** 3.2.11
- **Gorm Version:** 6.0.12

### Example Application

- see attachment, bootstrap code
[testinlist.zip](https://github.com/grails/grails-core/files/1152859/testinlist.zip)

**Comment by jameskleeh** [comment]
A quick search of previous issues would have returned 

https://github.com/grails/grails-core/issues/9718
https://github.com/grails/grails-core/issues/10661
