### ISSUE TITLE
Per-plugin encoding is ignored

### ISSUE THREAD

**Issue by danduke** [grails/grails-core#10722]
There appears to be no way to change per-plugin gsp encoding in Grails 3.x.  (I have tried in 3.2.various anyway.)  

Section 17.1 of the grails documentation indicates that per plugin encoding is possible, and this discussion: https://github.com/grails/grails-core/wiki/Default-Codecs appeared to be where it was originally designed.  However, setting encoding as described in those documents, and also changing in various other ways does not work.

Please reference https://stackoverflow.com/questions/44935007/how-to-change-per-plugin-codec-in-grails-3 for additional examples of what does not work.

I will be happy to upload an example if necessary, but it's basically:
* create an application
* create a plugin with a gsp that includes some html (or other) encoded expression
* try to change the encoding in the plugin
* see that the encoding did not change
I figure anybody reading this will probably understand the situation just from this explanation, but if not, comment back and I will upload an example application and plugin.

There are no stacktraces.  The encoding simply does not change.

### Expected Behaviour

Per plugin encoding should be respected.

### Actual Behaviour

Per plugin encoding is not respected.

### Environment Information

- **Operating System**: OS X; happens in Linux deployment environment as well
- **Grails Version:** 3.2.8, 3.2.10 tested
- **JDK Version:** 1.8.0_65

**Comment by kdpeders** [comment]
This seems to be a bug.  Should the application encoding be enforced in the plugins?  That doesn't seem correct either, but I think there should be a way to set the encoding of GSPs in a plugin.

**Comment by danduke** [comment]
I'd definitely prefer to not go back to enforcing application encoding in the plugins, unless there is no good way around it.  Splitting those up per plugin seems like the right architectural choice.  Making it work seems even better!  It's very likely that I'm just doing it wrong (though, I tried everything the docs said, and everything that I could think that was remotely close to that too) so maybe there is already a way to make this work and I just haven't been able to find it yet.

**Comment by graemerocher** [comment]
Please provide an example and we can look into this

**Comment by danduke** [comment]
It looks like this is actually working, and I forgot to close the issue.  Closing now, but adding some explanations and cautions in case anybody else hits problems with this.

The plugin(s) that had problems with this had some (in some cases, all) codecs set to "raw".  This is not valid, as far as I can tell; the valid setting is "none".  Apparently if *any* codec is invalid, an exception is thrown when parsing the codecs and the defaults are used for *all* codecs.  This seems not-so-bad to me, but was the underlying cause of the confusion.

To complicate matters, our internal plugin publishing was not cleaning the plugins before publishing.  I do not know if publish plugin publishing has a "clean" command as part of the publishing process.  As a result, even after changing the codecs to valid options, the precompiled gsps (that had not changed, and were therefore still compiled) were still present with the old, incorrect encodings.  This made it appear that the codecs were not respected, even after set to valid options.

If anyone else is seeing problems with this, make sure to set *all* codecs to valid options (don't just check the ones you care about) and clean before publishing.
