### ISSUE TITLE
Broken backward compatibility for plugins with interceptors

### ISSUE THREAD

**Issue by musketyr** [grails/grails-core#10723]
### Steps to Reproduce

If you have Grails application with version lower than `3.2.11` and you want to use a plugin which was created with version `3.2.11` and which defines any interceptor an exception is thrown.

### Expected Behaviour

Plugin created with version `3.2.11` should be usable with previous versions.

### Actual Behaviour

An exception is thrown if a plugin is created with version `3.2.11` but the application has not upgraded yet. This is a problem as we don't want to force users to upgrade to latest Grails if not really necessary.

### Environment Information

- **Operating System**:  Darwin
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_92

### Example Application
For more details, please see demo application at https://github.com/musketyr/grails-plugins-backward-compatibility-issue

**Comment by graemerocher** [comment]
It is not possible to support backwards binary compatibility this way I'm afraid. You have to create you plugins with an earlier version of Grails. Different versions of Groovy produce different byte code for traits, which makes this kind of issue more of a Groovy problem than a Grails problem.

**Comment by danduke** [comment]
For anyone hitting this or similar issues, be aware that per Graeme's comments on https://github.com/grails/grails-core/issues/10693, plugins that define gorm objects are not compatible across different change versions (third digit) of Grails (in the 3.2 branch anyway).

So just out of curiosity, what happened?  In grails 2, this was not a problem for plugins from what I remember, and there were different versions of groovy used across minor and change versions of grails there.  I'm just curious about why this is such a significant problem now in grails 3, when it was virtually unheard of in grails 2.

**Comment by jameskleeh** [comment]
@danduke Because plugins are pre-compiled in Grails 3. In Grails 2 they were compiled with your application

**Comment by danduke** [comment]
I thought they were compiled, and just released in a zip file, in grails 2.  I guess I never actually looked!  Thanks for the info.  I don't suppose there's any option to release a plugin uncompiled in grails 3?

**Comment by jeffbrown** [comment]
> I thought they were compiled, and just released in a zip file, in grails 2.

That was not the default behavior in Grails 2.

**Comment by jeffbrown** [comment]
> I don't suppose there's any option to release a plugin uncompiled in grails 3?

Correct.  There is not an option to do that.  You can publish source jars, but those won't be sufficient to make use of the plugin.
