### ISSUE TITLE
Interceptor match is inconsistent with UrlMapping (case-sensitive)

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#10725]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller called MyData with a "process" method
2. Add the following UrlMapping:
`  post "/MyData"(controller: "MyData", action: "process")`
3. Create an interceptor "TestInterceptor"
4. Add the following code to the interceptor constructor:
 ` match controller: 'MyData'`
5. Run the app
6. Send a test POST request to /MyData

### Expected Behaviour

The interceptor should be executed.

### Actual Behaviour

The interceptor is ignored, because the interceptor controller name match is case-sensitive. The controller method is still executed (because the UrlMapping is case-insensitive).

### Environment Information

- **Operating System**: Win7 x64
- **Grails Version:** 3.3.0.M2
- **JDK Version:** 1.8.0_66

### Example Application

- [https://github.com/rmorrise/interceptor-match-bug](https://github.com/rmorrise/interceptor-match-bug)

**Comment by graemerocher** [comment]
Debatable whether this is actually a bug. Controller name references are always in property name form. i.e.. `myData`

**Comment by rmorrise** [comment]
Currently the UrlMapping supports this... IMHO the interceptor pattern should be consistent with what is supported in UrlMapping. If you want, consider it as a feature enhancement request. If you think this usage should not be allowed, then support for it should be removed in the UrlMapping.

**Comment by jeffbrown** [comment]
> Currently the UrlMapping supports this...

It may be that it works, but I don't think it is really a supported feature.  The documented supported syntax always uses property name versions of the controller name (`myData`, not `MyData`).
