### ISSUE TITLE
Changes in the default grails-app/views/errors/_errors.gson are not reflected in the error response.

### ISSUE THREAD

**Issue by zverbatim** [grails/grails-core#10729]
I modify the `grails-app/views/errors/_errors.gson`, yet the response layout of the json does not change.  
It changes though if I add a 'modified' `_error.gson` in the view folder of the respective controller.

Controller code:
```
@CompileStatic
class ProductController extends RestfulController {
    static responseFormats = ['json', 'xml']
    ProductController() {
        super(Product)
    }
}
```

OS:
Using a osx 10.12.4

Versions:
$ grails --version
| Grails Version: 3.2.10
| Groovy Version: 2.4.10
| JVM Version: 1.8.0_131

**Comment by jameskleeh** [comment]
This issue belongs in https://github.com/grails/grails-views, however upload an example project with steps to reproduce

**Comment by zverbatim** [comment]
Found a quick fix.  
- Stop the app
- Do a `grails clean`
- Restart the app.
