### ISSUE TITLE
Grails version >= 3.3.0 ,not support disable concurrent of quartz plugin

### ISSUE THREAD

**Issue by puwanatfx** [grails/grails-core#10738]
Hello 
I'm testing grails 3.3.0.M1 and 3.3.0RC1
and found it's not support disble concurrent job of quartz 

`compile 'org.grails.plugins:quartz:2.0.12'`

disable concurrent job didn't work

`  def concurrent = false`

I test with code

`class TestJob {

    def concurrent = false

    static triggers = {
        cron name: 'myTrigger', cronExpression: "0/5 * * * * ?"
    }

    def execute() {
        // execute job
        log.error('Start:' + new Date())
        sleep(8000)
        log.error('End:' + new Date())
    }
}
`

When I run with grails 3.2.9 , it run fine , but if I run with newer version , 
I can not disable concurrent job

**Comment by jeffbrown** [comment]
This should be reported at https://github.com/grails-plugins/grails-quartz/issues.

Thanks for the feedback!
