### ISSUE TITLE
Performance degradation for GORM get vs read

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#10731]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. I'm observing performance degradation (from Grails 2) when it comes to using the `read` method in Grails3
2. it appears that the `read` method overhead is much bigger in Grails3

The following [repository](https://github.com/jglapa/grail3-performance) contains two identical projects with different Grails versions.
Grails 2.4.5 and Grails 3.2.6 (both were configured to used Hibernate4).

the apps were packaged with `grails war` (Gr2) and `./graldew war` (GR3)
Both were deployed to tomcat7 (with mem databases)

The apps are using `get`/`read` methods to load all the objects created in `Bootstrap`. 2nd level cache is enabled.

The following tests were performed with a warm-up beforehand (Apache Bench was used, no concurrency, just 100 requests)
```
ab -c 1 -n 100 http://localhost:8090/gr3-perf-degradation-0.1/test/loadWithRead
ab -c 1 -n 100 http://localhost:8090/gr3-perf-degradation-0.1/test/loadWithGet
ab -c 1 -n 100 http://localhost:8090/gr2-perf-degradation-0.1/test/loadWithRead
ab -c 1 -n 100 http://localhost:8090/gr2-perf-degradation-0.1/test/loadWithGet
```

On my machine the results were as follows:

TPR(mean)  | GET | READ
------------ | ------------- | ---------------
GR2 | 21.400ms | 25.099ms
GR3 | 24.702ms | 39.777ms

### Expected Behaviour

should match Grails2 performance characteristic

### Actual Behaviour

`read` method perfomance in grails3 has degraded  when comparing to grails2.
The `get` performance in grails3 is also slower.

### Environment Information

- **Operating System**: Ubuntu 16
- **Grails Version:** 3.2.6, 2.4.5 (hibernate 4)
- **JDK Version:** jdk8(G3), jdk7(G2

### Example Application

- https://github.com/jglapa/grail3-performance

**Comment by demon101** [comment]
Have you tried to disable reactor events?

```
grails:
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
```

Also, fresher versions of grails 3.2 has many fixes. I think, better to compare performance with 3.2.11

**Comment by jglapa** [comment]
indeed, the performance looks better after upgrading to 3.2.11 and disabling the gorm reactor events

TPR(mean)  | GET | READ
------------ | ------------- | ---------------
GR2 | 22.105ms | 27.118ms
GR3 | 11.404ms | 22.761ms

I guess this can be closed
