### ISSUE TITLE
After n+1 queries Grails starts to use 'deep' for JSON mapping.

### ISSUE THREAD

**Issue by wolandec** [grails/grails-core#10740]
```Groovy
class State {

    static mapping = {
        table 'states'
        version false
        graph fetch: 'lazy'
        type column: 'type'
        id generator:'sequence', sqlType: 'integer', type: 'integer', params: [sequence: 'states_id_seq']
    }

    static belongsTo = [graph:Graph, pointBegin:Point, pointEnd:Point]

    Integer id
    Short route
    Short train
    Integer timeBegin
    Integer timeEnd
    Short type
}
```
```Groovy
class Graph {

    static mapping = {
        version false
        id generator: 'sequence', sqlType: 'serial', type: 'long', params: [sequence: 'graph_id_seq']
        activationDate type: 'date'
        creationDateTime type: 'timestamp'
        modificationDateTime type: 'timestamp'
        layout column: 'graph_layout_id'
        routes sort: 'number', order: 'asc'
        routes fetch:'lazy'
    }
    static constraints = {
        comment nullable: true
    }
    static hasMany = [
            routes: Route
    ]

    Long id
    Short type
    String comment
    Date activationDate
    Date creationDateTime
    Date modificationDateTime
    Integer beginTime
    Integer endTime
    Short season
    GraphLayout layout
}
```

```Groovy
def getNgRouteByNumberAndGraphId(Short route, Long id) {
        render State.executeQuery('select s from State as s where s.route=:route and s.graph.id = :id and type in (:types) order by s.timeBegin',
                ["route": route, "id": id, types: [(Short) 102, (Short) 113]]) as JSON
    }

```
### Expected Behaviour

I expect that grails will return from the controller method only State with graph and other fields filled by ids only.

### Actual Behaviour

I don't expect grails to load all subfields of Graph. But after several counts of http requests, this code in controller starts to get all subfields of Graph, mainly it is about routes, that is a very big stuff.

There is no such problem with grails.converters.XML !!!

### Environment Information

- **Operating System**: Mageia 6 x64
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.141

**Comment by ensurconnect** [comment]
@wolandec if possible, attach an example application which reproduces the issue

**Comment by wolandec** [comment]
@ensurconnect no, it is not possible. I can take additional information. It is interesting, that another controller, which get another domain, having the Graph entity as a field, works perfect, until I make a request to getNgRouteByNumberAndGraphId. Then they both go mad.

**Comment by wolandec** [comment]
I switched to using JSON views and it works fine.

**Comment by graemerocher** [comment]
If in the future you get time to provide an example we can re-open
