### ISSUE TITLE
StackOverflowError in org.grails.web.json.parser.JSONParser

### ISSUE THREAD

**Issue by analbandyan** [grails/grails-core#10757]
### Steps to Reproduce

1. Create input stream for json objects containing arrays, like:
{
        "key1": "value1",
        "key2": "value2",
        ...
        "longArrayKey": [
            12,
            -25,
            0,
            5,
            115,
            34,
            0,
            79,
            ...
            112
        ]
    }
2. use org.grails.web.json.parser.JSONParser#parseJSON() to parse json objects using the above input stream

### Expected Behaviour

org.grails.web.json.parser.JSONParser should be able to parse objects containing arrays of any length

### Actual Behaviour

Currently if tha array size is big, it throws StackOverflowError because of recursion in JSONParser#Elements

### Environment Information

- **Operating System**: Fedora
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_112

**Comment by jeffbrown** [comment]
Can you attach a simple sample project which demonstrates the issue?

**Comment by analbandyan** [comment]
Here is the example project https://github.com/analbandyan/JSONParserStackOverflowExample
TestJSONParserSpec test demonstrates the issue.

**Comment by jeffbrown** [comment]
The issue is around https://github.com/grails/grails-core/blob/1cf41df1ebfa5a19c4667f3945a63c1dffc5b14b/grails-web-common/src/main/groovy/org/grails/web/json/parser/JSONParser.java#L146.

You can get around it by increasing your max stack size.  To do that for your tests, you could do something like this in `build.gradle`...

```groovy
test {
    jvmArgs '-Xss4m'
}
```

For your running application you will need to set up similar in your deployment environment.

**Comment by analbandyan** [comment]
Thanks for the hint Jeff. Yes there is a workaround, but in any cases, in case of any stack size there is still a possibility that it will fail for larger arrays. So I think it'd be better to switch from recursion to iteration. BTW I have applied a pull request for it (#10758).

**Comment by analbandyan** [comment]
Updated the fix for 3.3.x: #10950
