### ISSUE TITLE
Grails 3.2.9 not passing AJAX PUT parameters to controller action

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#10752]
### Steps to Reproduce

On a view this JS makes the params be: [uid:43e87631-d721-4b03-afd0-0a6da7930dd6, start:2017-07-27T12:00:00.000Z, end:2017-07-27T13:30:00.000Z, controller:timeSlot, format:null, action:update]

$.ajax({
            type: "POST",
            url: '${createLink(action:"update")}',
            data: {uid: event.id, start: event.start.toISOString(), end: event.end.toISOString()}
});

While this using PUT makes: [controller:timeSlot, format:null, action:update]

$.ajax({
            type: "PUT",
            url: '${createLink(action:"update")}',
            data: {uid: event.id, start: event.start.toISOString(), end: event.end.toISOString()}
});

### Expected Behaviour

Parameters should reach the controller action. Wanted to use PUT since that is the method associated to update.

### Actual Behaviour

Params don't reach controller action

### Environment Information

- **Operating System**: MacOs 10.11.6
- **Grails Version:** 3.2.9
- **JDK Version:** 1.8

**Comment by sdelamo** [comment]
Can you provide a sample application?

**Comment by jeffbrown** [comment]
This is likely a problem in the application.

**Comment by ppazos** [comment]
@sdelamo 

[sample_put-bug-report-02082017.zip](https://github.com/grails/grails-core/files/1194919/sample_put-bug-report-02082017.zip)

**Comment by jeffbrown** [comment]
@ppazos The linked project is incomplete.  `build.gradle` references `$grailsVersion` which isn't defined so the build won't work.  It would be better if you included the whole project, including `gradle.properties` which is the default place where `$grailsVersion` would typically be defined, and also include the `grailsw` and `gradlew` wrappers.

**Comment by ppazos** [comment]
@jeffbrown the project was exported via bug-report and working OK when run locally. Will ZIP the project manually later.

Basically what I did was:

1. create-app
2. create-controller
3. added view with ajax call
4. added action to receive the ajax call 
5. run-app to test the behavior, app runs OK and shows the described behavior
6. bug-report

If something was not set, it is an issue on grails itself.

**Comment by jeffbrown** [comment]
If the project is working for you locally, I expect you have a `gradle.properties` which defines `grailsVersion`.  As far as I can tell, the attached project is unbuildable.  It may be that bug-report isn't capturing everything it should.  I never use it for anything.  I put sample projects in a GitHub repo, which is a better idea for a variety of reasons.

Thanks for all of the feedback.

**Comment by jeffbrown** [comment]
```
$ grails run-app
| Resolving Dependencies. Please wait...
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jeffbrown/Downloads/sample_put-bug-report-02082017/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating root project 'sample_put-bug-report-02082017'.
> Could not get unknown property 'grailsVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED

Total time: 3.499 secs
| Error Error initializing classpath: Could not get unknown property 'grailsVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. (Use --stacktrace to see the full trace)
```

**Comment by jeffbrown** [comment]
I have put your code in a buildable/runnable project at https://github.com/jeffbrown/issue10752.

**Comment by jameskleeh** [comment]
Thanks for reporting this issue. This is indeed a bug. To work around this issue and as a general piece of advice, you can send the data in the request body by adding `contentType: "application/json"` to your ajax call. Then you can retrieve the data in the controller with `request.JSON`.

Thanks

**Comment by ppazos** [comment]
@jeffbrown this is the project zipped manually. The project has indeed gradle.properties. If it wasn't on the previous zip is because bug-report command didn't included it. It might be a bug on that command. Hope this helps.

[sample_put.zip](https://github.com/grails/grails-core/files/1196168/sample_put.zip)

**Comment by ppazos** [comment]
@jameskleeh thanks for your comment. My intent was not submit a JSON body, but individual params. Frequently I use explicit param names on the action like def action(String myparam), on this case myparams was submitted via AJAX PUT.

BTW, in the browser's network console, each param appears individually in the request, not as one JSON object.

**Comment by jeffbrown** [comment]
> The project has indeed gradle.properties. If it wasn't on the previous zip is because bug-report command didn't included it. It might be a bug on that command. 

That is correct.  https://github.com/grails-profiles/base/blob/fd8d38232a25ed3b9c31a0b588a763a3f10e057c/commands/bug-report.groovy#L12-L16

**Comment by ppazos** [comment]
thanks for checking @jeffbrown should I raise another issue for that?
