### ISSUE TITLE
Latest Grails documentation misses quick reference links to taglibs and tags

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10751]
### Steps to Reproduce

1. Browse to http://docs.grails.org/latest/
2. Compare Quick Reference links with http://docs.grails.org/3.2.11/

### Expected Behaviour

Quick reference should have links for `Tag Libraries` and `Tags`

### Actual Behaviour

The links for `Tag Libraries` and `Tags` are missing

**Comment by sdelamo** [comment]
GSP Documentation ( including Tag Libraries and Tags) is now available in:

http://gsp.grails.org

**Comment by saw303** [comment]
Okay, but where is the entry point to it?

**Comment by sdelamo** [comment]
The new website is linked from the Groovy Server Pages section of the 3.3.0 documentation  http://docs.grails.org/latest/guide/single.html#gsp
