### ISSUE TITLE
Grails 3.3.0: Failed deployment in JBOSS Wildfly

### ISSUE THREAD

**Issue by jarantes17** [grails/grails-core#10761]
I am migrating my application with grails 3.2.8 to new version 3.3.0, however it is not possible to perform deploy on wildfly 11.0.0.Alpha1.

### Steps to Reproduce

1. Create a grails-app with profile = rest-api
2. Set tomcat dependency to "provided"
3. Clean and generate war file

### Expected Behaviour

Deploy and usually run the application in JBOSS as grails 3.3.0.

### Actual Behaviour

Failed deployment

### JBOSS LOG ERROR:
`
2017-08-01 15:29:45,940 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 2) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "test-api.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"test-api.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"test-api.war\".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"test-api.war\"
    Caused by: java.lang.IllegalArgumentException: WFLYEE0083: @Resource injection target is invalid.  Only setter methods are allowed: void setTargetEventBus(grails.events.bus.EventBusAware, grails.events.bus.EventBus)"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"test-api.war\".POST_MODULE"]
}`

### Environment Information

- **Operating System**: Windows 10/Linux CentOS
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8
- **Container Version (If Applicable):** wildfly 11.0.0.Alpha1

### Example Application

- Default rest-api application, no changes.

**Comment by jeffbrown** [comment]
Does the info at http://grails.io/post/142674392718/deploying-grails-3-to-wildfly-10 help?

**Comment by jarantes17** [comment]
So the problem is that I was already running the application in a version higher than this example. And the mistake is another too. As I said in version 3.2.8 is working.

**Comment by jarantes17** [comment]
I solved this problem by commenting on the following plugins in gradle:
`// compile "org.grails.plugins: async"
// compile "org.grails.plugins: events" `
