### ISSUE TITLE
Grails 3.3 (hibernate plugin) dataSource bean is populated after the HibernateDatastore

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#10769]
I am trying to declare a Flyway Spring bean that get initialized just before Hibernate starts to validate the underlying database schema in order to apply database migration scripts.

**Expected behaviour**

Here is what I like to do. I want to register Flyway as a Spring bean and inject the `dataSource` into it. In order to have Flyway run its db migrations before Hibernate starts to validate the underlying database schema I add the `flyway` bean as a dependency onto the `hibernateDatastore` bean. The expected bean creation order should then be as follows:

1. dataSource
2. flyway
3. hibernateDatastore

**Actual behaviour**

The problem is that the Grails Hibernate plugin defines first a bean called `hibernateDatastore`. This is triggering Hibernate to validate the underlying database schema. After creating the `hibernateDatastore` the plugin tells Spring to execute the `BeanDefinitionRegistryPostProcessor` of `org.grails.orm.hibernate.support.HibernateDatastoreConnectionSourcesRegistrar` registers a `dataSource` bean. For my use case this should be the other way around as it was in previous versions of Grails.

The following question at [Stackoverflow](https://stackoverflow.com/questions/45572338/determine-springs-bean-instantiation-order-in-grails-3-3-with-gorm-6-1-x) provides further code listings that were running in Grails <= 3.2.x

**Comment by saw303** [comment]
Maybe related to https://github.com/grails/grails-core/issues/10760

**Comment by graemerocher** [comment]
#10760 is unrelated

Previous versions of Grails created the `dataSource` bean separately from the session factory. We would need to restore this behaviour I guess so the `dataSource` can be referenced without triggering the creation of the `sessionFactory`
