### ISSUE TITLE
hibernate use Oralce Database 12c and  config `dbCreate: update` throw an exception when second startup 

### ISSUE THREAD

**Issue by hujchen** [grails/grails-core#10768]
alter table security_user_role 
        add constraint FKl8py64m9hq59c97qfdxj6w6l 
        foreign key (user_id) 
        references security_user

Caused by: java.sql.SQLSyntaxErrorException: ORA-02275: 此表中已经存在这样的引用约束条件

	at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:91)
	at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:133)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:206)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1034)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:183)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:942)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1222)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1770)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1739)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:299)
	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy77.execute(Unknown Source)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 75 common frames omitted

appliction.yml
# 应用信息配置项。
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

# Spring配置项。
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints配置项。
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

# Hibernate配置项。
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

# Grails配置项。
grails:
    profile: web
    codegen:
        defaultPackage: security.rest.app
    spring:
        transactionManagement:
            proxies: false
    gorm:
        autowire: true
        reactor:
            events: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
        json:
            default:
                deep: true
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    # Spring Security配置项。
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: 'security.rest.app.User'
                authorityJoinClassName: 'security.rest.app.UserRole'
            authority:
                className: 'security.rest.app.Role'
            requestMap:
                className: 'security.rest.app.RequestMap'
            securityConfigType: 'Requestmap'
            useSecurityEventListener: true
            rest:
                token:
                    storage:
                        useJwt: false
                validation:
                    enableAnonymousAccess: true
            chainMap:
                - {pattern: '/assets/**', filters: 'none'}
                - {pattern: '/**/js/**', filters: 'none'}
                - {pattern: '/**/css/**', filters: 'none'}
                - {pattern: '/**/images/**', filters: 'none'}
                - {pattern: '/**/favicon.ico', filters: 'none'}
                - {pattern: '/**', filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'}
                - {pattern: '/api/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'}
                - {pattern: '/user/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'}
                - {pattern: '/role/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'}
                - {pattern: '/userRole/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'}
                - {pattern: '/requestMap/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'}
                - {pattern: '/oauth/access_token', filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'}
# 数据源配置项。
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: oracle.jdbc.driver.OracleDriver
    dialect: org.hibernate.dialect.OracleDialect
    username: app_db
    password: qwerpoiu
    logSql: true
    formatSql: true

# 环境配置项。
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:oracle:thin:@//192.168.2.201:1521/orcl
    test:
        dataSource:
            dbCreate: update
            url: jdbc:oracle:thin:@//192.168.2.201:1521/orcl
    production:
        dataSource:
            dbCreate: none
            url: jdbc:oracle:thin:@//192.168.2.201:1521/orcl
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2

#系统公共参数配置
app:
    server:
        phoneAuthCode:
            timeout: 30

**Comment by graemerocher** [comment]
Please provide your example configuration

**Comment by graemerocher** [comment]
Duplicates #10760
