### ISSUE TITLE
Requested format is overridden by (optional) URLMapping variable format

### ISSUE THREAD

**Issue by tkvw** [grails/grails-core#10765]
Grails 3.2.x

Consider this (default) URLMapping: 
```
get "/$controller(.$format)?"(action:"index")
```
This request does not resolve with the expected result: 
```
curl -H "Accept: application/json" http://localhost:8080/foo 
```
This will return the default format configured instead of the requested json (unless default == json). 

Grails first sets up the requested format in the webRequest params then it will allow AbstractURLMappingInfo to override these values, even if the URL Mapping variable is optional. 

Is this by design or is this a bug/unwanted feature? I think the requested format should always win.

**Comment by jeffbrown** [comment]
I cannot reproduce that.  

See the project at https://github.com/jeffbrown/issue10765.  At https://github.com/jeffbrown/issue10765/blob/b0c9079144914e710ce5e55dcf28d8ea65328799/grails-app/controllers/issue10765/UrlMappings.groovy#L12 you will see that app is using your url mapping...

    get "/$controller(.$format)?"(action:"index")

That appears to work...

```
issue10765 master $ 
issue10765 master $ curl -H "Accept: application/xml" http://localhost:8080/foo
<?xml version="1.0" encoding="UTF-8"?><list><person id="1"><firstName>Chris</firstName><lastName>Squire</lastName></person><person id="2"><firstName>Robert</firstName><lastName>Fripp</lastName></person></list>issue10765 master $ 
issue10765 master $ 
issue10765 master $ 
issue10765 master $ curl -H "Accept: application/json" http://localhost:8080/foo
[{"id":1,"firstName":"Chris","lastName":"Squire"},{"id":2,"firstName":"Robert","lastName":"Fripp"}]issue10765 master $ 
issue10765 master $ 
```

**Comment by jeffbrown** [comment]
If you show what is in the `index` action of your `FooController`, that might end up being relevant.

**Comment by tkvw** [comment]
Sorry Jeff, I am so used to writing the "Accept: " that I made a mistake submitting the issue, what I meant was: 
```
curl http://localhost:8080/foo?format=json
```
The docs say this is the safest way to guarantee format, but it does not work because the param is overridden by the format variable of the URLMappingInfo (which is null in this example).

**Comment by jeffbrown** [comment]
Why would you want http://localhost:8080/foo?format=json instead of http://localhost:8080/foo.json.  The way you expressed the url mapping, the latter should work.

Thanks again for the feedback.

**Comment by tkvw** [comment]
I was reading up and testing content-negotiation and read this in the docs: 

> Content Negotiation using the format Request Parameter
Let’s say a controller action can return a resource in a variety of formats: HTML, XML, and JSON. What format will the client get? The easiest and most reliable way for the client to control this is through a format URL parameter.

So I was using this while testing/learning content-negotiation and then didn't get the expected result. After digging in I discovered this was due to the format being overridden by the URLMappingInfo. 
I don't really have an explicit use case for it, it is confusing if you expect one thing and get a different result. 
Maybe a note with the docs should suffice.

**Comment by jeffbrown** [comment]
Maybe we could clarify it in the docs but http://localhost:8080/foo.json is the sensible way to take advantage of the `format` url parameter.

**Comment by jeffbrown** [comment]
If someone really did want to support  http://localhost:8080/foo?format=json instead of  http://localhost:8080/foo.json, a simple way to do that is to map the following:

    get "/$controller"(action:"index")

...instead of this:

    get "/$controller(.$format)?"(action:"index")

**Comment by tkvw** [comment]
Yeah, thanks for your help. I will remind myself to create a PR for the docs for this.
