### ISSUE TITLE
StringIndexOutOfBoundsException if URL path segment ends with a dot

### ISSUE THREAD

**Issue by chrkv** [grails/grails-core#10767]
### Task List

- [v] Steps to reproduce provided
- [v] Stacktrace (if present) provided
- [v] Example that reproduces the problem uploaded to Github
- [v] Full description of the issue provided (see below)

### Steps to Reproduce

1. Access any URL that contains dot in the end of path segment. For example `/index.`

### Expected Behaviour

It should be processed according to `UrlMappings` or 404 should be received

### Actual Behaviour

500 is received with exception `java.lang.StringIndexOutOfBoundsException: String index out of range: 1`
```    Line | Method
->> 1963 | substring                      in java.lang.String
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    256 | getPropertyNameRepresentation  in grails.util.GrailsNameUtils
|    215 | getPropertyName . . . . . . .  in     ''
|     33 | toUrlElement                   in grails.web.CamelCaseUrlConverter
|    191 | getControllerName . . . . . .  in org.grails.web.mapping.DefaultUrlMappingInfo
```

### Example Application

Empty application to ensure no side effects - https://github.com/chrkv/grails-dot-url-problem

**Comment by jknudsen** [comment]
I am also seeing this behavior in 3.2.11.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-core/pull/10788

**Comment by jknudsen** [comment]
Sweet thanks James

**Comment by kuchar90** [comment]
Hi, I have a question, when version 3.2.12 will be released?
