### ISSUE TITLE
Grails 3.3.0 widget:'textarea' no longer works

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#10763]
https://docs.grails.org/latest/ref/Constraints/widget.html

The following works fine in grails 3.0.15, 3.1.12, 3.2.11, but fails by rendering an input field instead of a textarea in 3.3.0

    grails create-app website
    cd website
    grails create-domain-class Sample
    create-scaffold-controller website.Sample 

update Sample.groovy

    package website
    class Sample {
        String description
        static constraints = {
             description widget:'textarea'
        }
    }

then run

    grails run-app

http://localhost:8080/sample/create

This is not a problem with the fields or scaffolding plugins because they both resolve the same version

Working configuration: 
$ grails -v
| Grails Version: 3.2.11
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_91
$ dependency-report runtime|grep fields
|    \--- org.grails.plugins:fields:2.0.3 -> 2.1.5
$ grails dependency-report runtime|grep scaffolding
+--- org.grails.plugins:scaffolding: -> 3.3.3

Non-working configuration
$ grails -v
| Grails Version: 3.3.0
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_91
$ grails dependency-report runtime|grep fields
|    \--- org.grails.plugins:fields:2.0.3 -> 2.1.5
$ grails dependency-report runtime|grep scaffolding
+--- org.grails.plugins:scaffolding: -> 3.3.3

**Comment by codeconsole** [comment]
This is also not a problem with gorm.  If I take the working 3.2.11 app and update gorm to the same version, it still works.

change gradle.properties
gormVersion=6.1.6.RELEASE

$ grails dependency-report runtime|grep gorm
|    |    |    |         +--- org.grails:grails-datastore-gorm-validation:6.0.12.RELEASE -> 6.1.6.RELEASE
|    |    |    |         +--- org.grails:grails-datastore-gorm:6.0.12.RELEASE -> 6.1.6.RELEASE
|    |    |    |         |    +--- org.grails:grails-datastore-gorm-validation:6.1.6.RELEASE (*)
|    |    |    |         +--- org.grails:grails-datastore-gorm-support:6.0.12.RELEASE -> 6.1.6.RELEASE
|    |    |    |         |    +--- org.grails:grails-datastore-gorm:6.1.6.RELEASE (*)
|    +--- org.grails:grails-datastore-gorm-support:6.1.6.RELEASE (*)
|    +--- org.grails:grails-datastore-gorm-hibernate5:6.1.6.RELEASE
|    |    +--- org.grails:grails-datastore-gorm-hibernate-core:6.1.6.RELEASE
|    |    |    +--- org.grails:grails-datastore-gorm:6.1.6.RELEASE (*)

**Comment by jeffbrown** [comment]
> This is also not a problem with gorm.

That makes sense to me.  There isn't anything in the bug report that looks like it has anything to do with GORM.

**Comment by codeconsole** [comment]
Any ideas on what difference between 3.2.x and 3.3.0 is causing the problem?
