### ISSUE TITLE
Quotes added twice when  rendering HTML attributes with GSP code: data=""value""

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#10762]
Adding HTML attributes this way:

`<input type="email" ${'data="value"'}  />
`
Generates:

`<input type="email" data=""value""  />
`
Note extra quotes on value.

### Steps to Reproduce

1. create a GSP view with this <input type="email" ${'data="value"'}  />

### Expected Behaviour

Output to be <input type="email" data="value"  />

### Actual Behaviour

Output is <input type="email" data=""value""  />

### Environment Information

- **Operating System**: MAcOS 10.11.6
- **Grails Version:** 3.2.9
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
You should wrap the output in the `raw(...)` method
