### ISSUE TITLE
Gradle 4.x: No such property: serverPort error on @Integration specs

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-core#10771]
When using Gradle 4.x, all the `@Integration` specs that reference the `serverPort` property (which is added by an AST transform), throw the following exception:

```
groovy.lang.MissingPropertyException: No such property: serverPort for class: com.acme.foo.MySpec`
```

**Comment by jeffbrown** [comment]
The project at https://github.com/jeffbrown/testissue demonstrates the issue.  The test worked before upgrading the wrapper at https://github.com/jeffbrown/testissue/commit/417b550762a5dd33db4227314eb153a6ae528efc.

**Comment by graemerocher** [comment]
Was a bug in the testing support library. Can be worked around now with 3.3.0 by adding:

```groovy
testCompile "org.grails:grails-testing-support:1.0.1-SNAPSHOT"
```

**Comment by luisjba** [comment]
I fixed setting the value with the local.server.port as motioned in [Ted Vinke's Blog](https://tedvinke.wordpress.com/2017/12/04/x-mas-musings-4-do-not-use-random-server-port-in-grails-integration-tests/) . You have to use the @Value annotation to set the value for serverPort variable.

`
import grails.testing.web.controllers.ControllerUnitTest
import spock.lang.Specification
import org.springframework.beans.factory.annotation.Value
import grails.plugins.rest.client.RestBuilder
class SomeControllerSpec extends Specification implements ControllerUnitTest\<SomeController\>  {
  @Value('${local.server.port}')
  Integer serverPort
  def setup() {
  }
  def cleanup() {
  }
  void "test /api/method  "() {
      given:
      RestBuilder rest = new RestBuilder()

      when:
      def resp = rest.get("http://localhost:${serverPort}/api/method") {
          accept('application/json')
          contentType('application/json')
      }

      then:
      resp.status == 200
  }
}
`
