### ISSUE TITLE
Grails not picking production url

### ISSUE THREAD

**Issue by aslamhirani** [grails/grails-core#10770]
Grails version 3.2.4
Groovy version 2.4.7
JVM Version: 1_8_0_111
Windows version - Windows 10

Steps to reproduce - 
1. grails prod war
2. java -Dgrails.env=prod -jar build/libs/myjar.war
Grails application running at http://localhost:8080 in environment: production

Expected Output -- 
grails application should be deployed on mysite as mentioned in application.yml rather localhost:8080

Application.yml ---
environments:
    development:
        grails:
            serverURL: http://localhost.com
        dataSource:
            dbCreate: create-drop
            url: jdbc:sqlserver://localhost:3306/ABCD
    test:
        grails:
            serverURL: http://localhost.com
        dataSource:
            dbCreate: update
            url: jdbc:sqlserver://localhost:3306/ABCD
    production:
        grails:
            serverURL: http://mysite.com/
        dataSource:
            dbCreate: none
            url: jdbc:sqlserver://localhost:3306/ABCD

**Comment by sdelamo** [comment]
> grails.serverURL - A string specifying the server URL portion of absolute links, including server name e.g. grails.serverURL="http://my.yourportal.com". See createLink. Also used by redirects.

`grails.serverURL` is a configuration parameter. It does not trigger any deployment. 

it is used for example by the [createLink](http://gsp.grails.org/latest/ref/Tags/createLink.html) tag when you use `absolute`

You can have different configuration parameter values depending on the environment: 

If you have an app with these settings: 

`grails-app/conf/application.yml`

```
---
environments:
    development:
        grails:
           serverURL: http://localhost:8080
    production:
        grails:
           serverURL: http://mysite.com

```

And you output the value of the configuration parameter in `BootStrap.groovy`

```
import grails.core.GrailsApplication

class BootStrap {

    GrailsApplication grailsApplication

    def init = { servletContext ->
        println "Grails Server URL: " + grailsApplication.config.getProperty('grails.serverURL')
    }
    def destroy = {
    }
}
```

If you run the app in dev environment.

```
$ ./gradlew -Dgrails.env=prod bootRun
Grails Server URL: http://localhost:8080
Grails application running at http://localhost:8080 in environment: development
```


If you run the app in prod environment.

```
$ ./gradlew -Dgrails.env=prod bootRun
Grails Server URL: http://mysite.com
Grails application running at http://localhost:8080 in environment: production
```
