### ISSUE TITLE
Groovy 2.4.11 has breaking SQL changes please upgrade to 2.4.12

### ISSUE THREAD

**Issue by vijaysl** [grails/grails-core#10797]
Hi,
We are using Grails 3.2.11 on JDK 8 and running into another groovy sql breaking change similar to the one fixed by #10685.
https://issues.apache.org/jira/browse/GROOVY-8174

Can you please upgrade Grails 3.2.11 to use Groovy 2.4.12?
Are we able to use an older version of groovy by adding the following or is it not recommended?
compile 'org.codehaus.groovy:groovy-all:2.4.8'

**Comment by jeffbrown** [comment]
> Are we able to use an older version of groovy by adding the following or is it not recommended?

I think in this particular case you will likely get away with using the older version.

**Comment by ilopmar** [comment]
Grails 3.2.13 uses the latest Groovy 2.4.15: https://github.com/grails/grails-core/blob/v3.2.13/build.gradle#L39
