### ISSUE TITLE
Error when calling GORM Data Services method in interceptor

### ISSUE THREAD

**Issue by ilmoralito** [grails/grails-core#10793]
I am using GORM Data Services and i need to call a service method in an Interceptor. But I am getting a NullPointerException.

If on the other hand, I call a method from a traditional service in an Interceptor the method call works as expected

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Download and run the demo app
2. Go to http://localhost:9090/person/index

### Expected Behaviour

Should print to the console a list of person type objects

### Actual Behaviour

Error 500: Internal Server Error

**URI** /person/index
**Class** java.lang.NullPointerException
**Message** Cannot invoke method list() on null object

### Environment Information

- **Operating System**: UBUNTU 16.04
- **Grails Version:** Using grails version 3.3.0.M2
- **JDK Version:** Using java version 8u121

### Example Application

- https://github.com/ilmoralito/issue-GORM-Data-Services-Interceptors

**Comment by graemerocher** [comment]
Specifying `@Autowired` in the interceptor resolves the issue

**Comment by ilmoralito** [comment]
`@Autowired` Only works if the application is running. If in the Interceptor in the service injection is marked by @Autowired and the application stops to start again I get the following message

```
stop-app
| Shutting down application...
| Application shutdown.
grails> rA
| Running application...
2017-08-28 11:36:00.259 ERROR --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field personService in demo.PersonInterceptor required a bean of type 'demo.PersonService' that could not be found.


Action:

Consider defining a bean of type 'demo.PersonService' in your configuration.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/home/sherlock/.sdkman/candidates/java/8u121/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
| Error Failed to start server (Use --stacktrace to see the full trace)
grails> 

```
