### ISSUE TITLE
Inject a session scoped service to a scheduled service

### ISSUE THREAD

**Issue by silviaIT** [grails/grails-core#10803]
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1) Create a basic application on Grails 3.1.16
2) Create two services: a first asynch and scheduled Service (ex. 'FirstService') and a second Service that must be session scope (ex. 'SessionScopeService')
3) Try to inject the second session scoped service to the first service, like below:

"FirstService.groovy":
import org.springframework.scheduling.annotation.Async
import org.springframework.scheduling.annotation.Scheduled
    class FirstService {
        def sessionScopeService
        boolean lazyInit
        @Async
        @Scheduled(cron="*/10 * * * * MON-FRI") 
        void firstServiceMethod() {
            sessionScopeService.serviceMethod()
        }
    }

"SessionScopeService.groovy":
    class SessionScopeService {
        static scope = "session"
        def serviceMethod() {
            println("test OK")
        }
    }

4) Run application

### Expected Behaviour
I'm expecting the application starts correctly, returning on console the text 'test OK' every 10 seconds, as scheduled.

### Actual Behaviour
The application fails to start, reporting scope session error: 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firstService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionScopeService': **Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.**

### Environment Information

- **Operating System**: Win7 x64
- **Grails Version:** 3.1.16
- **JDK Version:** 1.8 update 131 x64
- **Container Version (If Applicable):** Embedded tomcat

**Comment by graemerocher** [comment]
Duplicates #10687

**Comment by silviaIT** [comment]
Excuse me, but I do not think it's a duplicate. In my case the calling service is scheduled and I think it is a different problem. In fact, the error persists even though the proxy is manually created.

**Comment by graemerocher** [comment]
In that case it doesn't look like a bug at all since you are trying to execute a session scoped service outside the scope of an available HTTP session, hence the error
