### ISSUE TITLE
GrailsCompileStatic on domain class fails if inner enum 

### ISSUE THREAD

**Issue by Taack** [grails/grails-core#10808]
When using GrailsCompileStatic on domain classes that do contains enum definitions in, compilation fails with the following message:

> General error during canonicalization: Cannot get property 'initialExpression' on null object
>>    java.lang.NullPointerException: Cannot get property 'initialExpression' on null object
	at org.grails.compiler.ValidateableTypeCheckingExtension$_run_closure4.doCall(**ValidateableTypeCheckingExtension.groovy:50**)

**Step to reproduce**

1. create an empty web project
2. add domain class that contains enum class in
3. add GrailsCompileStatic class annotation
4. in the root of the project, launch build: 
> $ ./gradlew build
=> Compilation fails

**Comment by AdrienGuichard** [comment]
[test.tar.gz](https://github.com/grails/grails-core/files/1311082/test.tar.gz)

**Comment by snimavat** [comment]
@jameskleeh this is still an issue with grails 3.3.2

**Comment by jameskleeh** [comment]
@snimavat Likely whatever you are experiencing is a different issue. Please file a new issue with an example project.

**Comment by jamesdh** [comment]
@jameskleeh I pushed an example project to https://github.com/jamesdh/gorm-static-inner-enum-bug that exposes this bug. Specifically https://github.com/jamesdh/gorm-static-inner-enum-bug/blob/master/grails-app/domain/test/User.groovy

It's the combination of `@GrailsCompileStatic`, an inner enum, and a static mapping block (even if that mapping block is empty) which exposes it. Remove any of those three, and compilation works fine.

**Comment by darxriggs** [comment]
@jameskleeh do you already have an idea when this might be fixed?

**Comment by sagrawal31** [comment]
This happened for me because I was using Groovy annotation `@Sortable(includes = ["day", "start"])` on top of the domain class. As soon as I removed it, the error is gone. Weird!

Although, I use Java's `DayOfWeek day` enum in my domain class.

**Comment by jpozorio** [comment]
For me, it fails with one property mapped as jsonb

**Comment by darxriggs** [comment]
@puneetbehl can you provide an indication when this might be fixed? It is still assigned to milestone "grails-3.12.2" which was already closed in 2018.

**Comment by puneetbehl** [comment]
There will be no 3.12.2 release. The change should be included in Grails 3.3.14. Please reopen if this is still an issue with Grails 3.3.14 or Grails 4.

**Comment by darxriggs** [comment]
@puneetbehl It still fails with Grails 4.0.12. Can you therefore please reopen it?

As stated by @jamesdh in https://github.com/grails/grails-core/issues/10808#issuecomment-655582363 this is exposed by a *static mapping* block in addition to an inner enum.

The fix & test from @jameskleeh in commit d9444e3803a230d850ca8bbee00d2dc96b7e0532 does not contain such a *static mapping* block but a *static constraints* block.

**Comment by puneetbehl** [comment]
I would request you to please file a new issue with sample application. I think it must be a different issue because `constraintsProperty.initialExpression` should not `null`.
