### ISSUE TITLE
Grails 3.3.0 - multiple hasManys referencing the same domain -> columns not nullable

### ISSUE THREAD

**Issue by DaguMW** [grails/grails-core#10811]
The problem is very simple but a real dealbreake because it worked like a charm under grails 2.4.4 and our application is no longer able to create its database from scratch since we upgraded to grails 3.3.0:

1) create a domain with multiple hasManys referencing the same domain:
```
class EcmMask {
  String name
  static hasMany = [createUsers:User,updateUsers:User]
}
```

2) .. starting the application and trying to add a User to only one of those lists results in a database error because gorm creates the following table:
```
ecm_mask_user {
  user_id bigint NULL
  ecm_mask_create_users_id bigint **NOT NULL**
  ecm_mask_update_users_id bigint **NOT NULL**
}
```

**Cause:** grails tries to insert an entry which includes the user_id and the mask_id for one of the two cols (depending on which list you put the user in) and fails because the other column would become null which is not allowed.

I already tried:
```
static constraints = {
  createUsers(nullable:true)
  updateUsers(nullable:true)
}
```

.. als well as:
```
grails.gorm.default.constraints = {
	'*'(nullable: true)
}
```
(inside application.groovy) but without any effect.

**Expected Behaviour:** the columns should get created as nullable true as under grails 2.4.4.
Any workaround would be appreciated!

thanks in advance!

**Comment by shahin-it** [comment]
This problem is so pathetic!

**Comment by graemerocher** [comment]
This is not a bug in GORM. Hibernate does not allow the creation of nullable foreign keys with hbm2ddl. If you were using migrations you could alter the schema that Hibernate generates to ensure the foreign key column is nullable.

Alternatively you can use the better approach of mapping to two distinct join tables:

```groovy
class EcmMask {
    String name
    static hasMany = [createUsers:User,updateUsers:User]

    static mapping = MappingBuilder.orm {
        property('createUsers') {
            joinTable { name"created_users" }
        }
        property('updateUsers') {
            joinTable { name "updated_users" }
        }
    }
}
````

**Comment by graemerocher** [comment]
For reference see https://github.com/hibernate/hibernate-orm/blob/1c915087a1231688c9745336492e24965aaaf1cf/hibernate-core/src/main/java/org/hibernate/mapping/PrimaryKey.java#L34

Which is where Hibernate enforces `nullable:false` for foreign key references.

**Comment by DaguMW** [comment]
Thanks for your time!
But unfortunately I'm not sure, that this is a hibernate problem because:

a) the column user_id in table ecm_mask_user IS nullable but is a foreign key to user:id
b) the hibernate code you mentioned says "Forcing column [%s] to be non-null as it is part of the primary key for table [%s]" .. but those columns are not part of the primary key (the mapping table has no primary key at all)

I'm well aware that I can use different mapping tables, but I need this to be backwards compatible with the old client (the one running grails 2.4.4) and the structure mentioned is exactly what worked under grails 2.4.4 and what is live on many many customer systems.

We use the migration approach at the moment to get the columns nullable again on new systems but in my eyes, it clearly IS a bug. You can define multiple hasManys referencing the same domain and GORM is supposed to create a table it can never insert to? It worked under grails 2.4.4 and now its supposed not to fail without manually defining new mapping tables?

**Comment by graemerocher** [comment]
You may regard it is as a bug, but the bug is in Hibernate, which is beyond our control. You can see the exact same behaviour with the following JPA mapping

```groovy
@Entity
class EcmMaskJpa {
    @Id
    @GeneratedValue
    Long id

    String name

    @OneToMany(cascade = CascadeType.ALL)
    Set<User2> createdUsers = []

    @OneToMany(cascade = CascadeType.ALL)
    Set<User2> updatedUsers = []
}

@Entity
class User2 {
    @Id
    @GeneratedValue
    Long id
    String name
}
```

Feel free to report an issue to the Hibernate team and reference this one here.
