### ISSUE TITLE
g:sortableColumn generates wrong links when used with a controller with a specific mapping

### ISSUE THREAD

**Issue by cseewald** [grails/grails-core#10819]
The issue was reported [before](https://github.com/grails/grails-core/issues/9400), but was closed because the issue was not described properly.

Fortunately it is very straightforward ...

### Steps to Reproduce

1. Create a controller with a mapping like this: `"/somepath/mycontroller/$action?/$id?" controller: 'mycontroller'`
2. use sortable column tag on a GSP rendered by _mycontroller_: `<g:sortableColumn property="prop" title="Title"/>`

### Expected Behaviour

The generated link should be "/somepath/mycontroller/index?sort=...".

### Actual Behaviour

The link misses the "/somepath" part. Wrong URL: "/mycontroller/index?sort=...".

### Environment Information

- **Grails Version:** 3.3.0
- **JDK Version:** 8

### Fix

As described [here](https://github.com/grails/grails-core/issues/9400), replace `def namespace = attrs.namespace ? attrs.remove("namespace") : ""` with `def namespace = attrs.remove("namespace")` in org.grails.plugins.web.taglib.UrlMappingTagLib#sortableColumn

**Comment by malundstrom** [comment]
I just encountered the same problem with Grails 2.4.5, is the only workaround to edit org.grails.plugins.web.taglib.UrlMappingTagLib#sortableColumn other than going through the pain of having a namspace in all g:sortableColumn places?

**Comment by robertoschwald** [comment]
same here on Grails 3.3.9.

**Comment by codeconsole** [comment]
same in Grails 4.0.0.RC1

**Comment by fuxx** [comment]
I made a pull request on gsp for 3.3.x which gets hopefully merged.
https://github.com/grails/grails-gsp/pull/45

**Comment by bobbywarner** [comment]
GSP has moved to the following repo: https://github.com/grails/grails-gsp

The pull request mentioned above has been merged on the `3.3.x` branch and manually applied to the `master` branch as well:

grails/grails-gsp#45

grails/grails-gsp@7367699
