### ISSUE TITLE
Unit tests ignore global failOnError setting

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-core#10810]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new app
2. Create Book domain with single required field title
3. Add `failOnError: true` to application.yml
4. Check for this setting in unit test (see BookSpec) and bootRun (see BootStrap)

### Expected Behaviour

ValidationException should thrown in both cases

### Actual Behaviour

ValidationException is thrown only in BootStrap not in BookSpec

### Environment Information

- **Operating System**: Win10
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8

### Example Application
https://github.com/allnightlong/fail-on-error-bug

**Comment by bp-FLN** [comment]
happens for me too when upgrading from 3.1.15 to 3.3

i also tried `grails.gorm.failOnError = true` in `application.groovy` without luck

**Comment by jameskleeh** [comment]
Version 1.1.2 of the testing framework, when released, will use the failOnError setting from config by default. Until then, you can override the `getFailOnError` method. https://github.com/grails/grails-testing-support/blob/fda71fcf7354aff7036ada0273b778eef4292083/grails-gorm-testing-support/src/main/groovy/grails/testing/gorm/DataTest.groovy#L53
