### ISSUE TITLE
Flushing inside a @Transactional method does not do anything

### ISSUE THREAD

**Issue by AlexBoulyga** [grails/grails-core#10816]
Hello!
I have noticed an interesting behaviour for saving in grails which might be a bug, or might be intended (but lacking direct documentation).
When creating a long running function (f.e. querying some external database) and declaring it as @Transactional, no domain object created in this function cannot be flushed/saved.
However, we need the rollback behaviour of the @transactional for most of the domain object instances we create, but some objects still should be saved (for overview/reporting purposes) permanently (when we try to flush them).

This has been working with
withNewTransaction
as a workaround, but in some cases we run into errors where those objects saved in a new transaction are inconsistent between the threads.

Anyways, if this behaviour (of not beeing able to flush inside an @transactional method) is intended, it would be great to see that somewhere in the documentation (for example here http://docs.grails.org/3.3.0/ref/Domain%20Classes/save.html )

If I have misunderstood the behaviour I would be glad for someone to clear it up for me!

Thank you very much!

### Steps to Reproduce

1. Create a long lasting method that is @Transactional
2. Create an Instance of a domain Object inside it, save and flush it
3. Verify if the Object has been flushed

### Expected Behaviour

The flushed object is accessible by other threads/seen in the database

### Actual Behaviour

The object does not exist outside of the thread that created it

### Environment Information

- **Operating System**: Ubuntu 14
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8.0_144

**Comment by graemerocher** [comment]
That is what `REQUIRES_NEW` propagation setting is for. https://stackoverflow.com/questions/5789788/what-exactly-propagation-requires-new-means-using-spring-transaction-managemen
