### ISSUE TITLE
gradle pathingJar task/command incompatible with gradle-4.0+

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#10813]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. fresh 3.3.1 app
2. `build.gradle`: `wrapper.gradleVersion = "4.2"` 
3. `gradlew wrapper`, `gradlew wrapper`
4. `build.gradle`: `grails.pathingJar = true`
5. `gradlew bootRun`

### Expected Behaviour

`bootRun` works

### Actual Behaviour

`Could not find or load main class myapp.Application`

i added this to the gradle `bootRun` task:

```groovy
doFirst {
    println classpath.files
}
```

which shows that it is always `build/classes/main` that is used as classpath (and `resources` and the pathing jar itself)

however, checking the build directory and switching gradle versions you can see the following:
* up to gradle-3.5.1, the sources get compiled into `build/classes/main`
* from gradle-4.0 up, the sources get compiled into `build/classes/groovy/main`

ref. https://docs.gradle.org/4.0/release-notes.html#multiple-class-directories-for-a-single-source-set
vs. https://github.com/grails/grails-core/blob/v3.3.1/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy#L636

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.3.1
- **JDK Version:** oracle 8u131
- **Container Version (If Applicable):** n/a

### Example Application

n/a

**Comment by jeffbrown** [comment]
See the project at https://github.com/jeffbrown/issue10813.

https://github.com/jeffbrown/issue10813/commit/434cda8b4d9ada3b42f77c902af16bb4976fd65b may be a valid workaround.
