### ISSUE TITLE
Grails Environment - Recognize GRAILS_ENV environment variable

### ISSUE THREAD

**Issue by mikemassa84** [grails/grails-core#10820]
Some environments like Kubernetes and Beanstalk allow environment variables to be set and accessed by applications running in them. The current environment key, grails.env, is not a valid environment variable name for those environments. It would be very beneficial if grails could check for a property called GRAILS_ENV when the grails.env property is not set.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Kubernetes cluster or Beanstalk application
2. Set environment variable GRAILS_ENV=dev in Kubernetes or Beanstalk
3. Deploy a grails application to the environment
4. You will see in the log that environment is prod

### Expected Behaviour

Ideally, grails would see grails.env is not set and check for GRAILS_ENV before defaulting to the prod environment.

### Actual Behaviour

Only grails.env is checked.

### Environment Information

- **Operating System**: Any. (Kubernetes or Beanstalk)
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8
- **Container Version (If Applicable):** Kubernetes 1.7.5 (master)

### Example Application

- Any grails application will show the problem.

**Comment by graemerocher** [comment]
Thanks for the pull request

**Comment by xpusostomos** [comment]
Oh... so this was implemented?? Would be nice if it was also documented, which as far as I see, it isn't.
