### ISSUE TITLE
grails install-templates does not install artifacts directory

### ISSUE THREAD

**Issue by jpgagnebmc** [grails/grails-core#10827]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

grails install-templates

### Expected Behaviour

Previous versions created a directory under src/templates called artifacts that would contain templates including DomainClass.groovy

### Actual Behaviour

Artifacts directory is not created.  I can find no way to override DomainClass.groovy.

### Environment Information

- **Operating System**: Ubuntu
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8.0_144
- **Container Version (If Applicable):** TODO

**Comment by jeffbrown** [comment]
This should be reported at https://github.com/grails-plugins/grails-scaffolding/issues.

**Comment by jpgagnebmc** [comment]
done https://github.com/grails-plugins/grails-scaffolding/issues/33
