### ISSUE TITLE
grails central repo down:404

### ISSUE THREAD

**Issue by mamunsardar** [grails/grails-core#10822]
Grails central repo appears to be down (404) again. I've tried below list:
https://repo.grails.org/grails/core
https://grails.jfrog.io/grails/core

Error in CLI:
Error occurred running Grails CLI: Could not find artifact org.grails:grails-bom:pom:3.3.1 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

**Comment by mamunsardar** [comment]
Repo is up again.closing this issue. thanks for all your hard work

**Comment by giovanniumboh** [comment]
It happen again, grails central repo down:404

**Comment by giovanniumboh** [comment]
Anyone can help on this? thank you

**Comment by davidbairdala** [comment]
This is affecting me as well.

**Comment by m4rc77** [comment]
Have a look at  #11825 it seems as the repo URL has changed. See comment from @puneetbehl (https://github.com/grails/grails-core/issues/11825#issuecomment-855607250). But there is no real solution/workaround available yet.
