### ISSUE TITLE
Make it possible to access nested config with dot systax for NavigableMap

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10826]
Given the config:

```
widget {
  shape {
   width = 100
   height = 100
 }
}
```
 

Given a cofig object (grailsApplication.config): 
`We can do config.getProperty("widget.shape.width, Integer)`

However, if we have reference to widget object, and want to access its sub properties with dot systax, its not possible.

Eg.
`NavigableMap widget = config.widget`

Expected:
`widget.getProperty("shape.width", Integer)`

This is not possible.

Cant we have similar getProperty(key, type) methods supported for navigable map, making it easy to navigate to sub config of given config block.

Some time, we have just a reference of a config object, and code knows just the paths of the child keys reardless of full path of keys from root of config.

**Comment by zyro23** [comment]
maybe this helps (sure it is one line more instantiating the `PropertySourceConfig` but id say thats ok):
```groovy
import grails.core.GrailsApplication
import org.grails.config.PropertySourcesConfig
import org.springframework.beans.factory.annotation.Value

class MyService {

	// example for @Value injection
	@Value('#{@grailsApplication.config.getProperty("grails", T(java.util.Map))}')
	Map grailsMap

	// example for programmatic lookup
	GrailsApplication grailsApplication

	void verify() {
		// verify @Value injection
		assert grailsMap in NavigableMap
		PropertySourcesConfig grailsPropertySourcesConfig = new PropertySourcesConfig(grailsMap)
		assert grailsPropertySourcesConfig.getProperty("urlmapping.cache.maxsize", Integer) == 1000

		// verify programmatic lookup
		Map grailsMap2 = grailsApplication.config.getProperty"grails", Map
		assert grailsMap in NavigableMap
		PropertySourcesConfig grailsPropertySourcesConfig2 = new PropertySourcesConfig(grailsMap2)
		assert grailsPropertySourcesConfig2.getProperty("urlmapping.cache.maxsize", Integer) == 1000
	}
```

**Comment by graemerocher** [comment]
You can cal `flatten()` if necessary
