### ISSUE TITLE
Generate-all for a domain class still adds @TestFor and @Mock annotations on the controller spec

### ISSUE THREAD

**Issue by kousen** [grails/grails-core#10821]
Say you have a domain class `Person`:

class Person {
   String first
   String last
}

If you run `grails generate-all Person`, Grails creates a `PersonController` and a `PersonControllerSpec`. Unfortunately, the `PersonControllerSpec` includes `@TestFor` and `@Mock` annotations (which are not resolved) and only extends `Specification`. It also does not implement `ControllerUnitTest<PersonController>` as it should.

The test does not compile as a result, and doesn't run properly until the annotations are deleted and the implements clause is added.

### Environment Information

- **Operating System**: OS X 10.11.6
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8

**Comment by jameskleeh** [comment]
Fixed in scaffolding 3.4.1
