### ISSUE TITLE
No validation message on update with dynamic-scaffold-controller

### ISSUE THREAD

**Issue by fbartnitzek** [grails/grails-core#10837]
Dynamic scaffolding controller and static scaffolding controller behaves differently for updates

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new app with domain class EntityA and EntityB (just different name)
```
package org.grails.test

class EntityA {
    String name
    Integer number

    static constraints = {
	name 		maxSize: 255
	number		min: 1900, validator: {val -> val < 2019 && val >= 1900 }
    }
}
```

2. update BootStrap
```
def init = { servletContext ->
	new EntityA(name: 'A', number: 2000).save()
	new EntityB(name: 'B', number: 2000).save()
}
```

3. Create scaffold-controller for EntityA and generated controller and views for EntityB
```
create-scaffold-controller org.grails.test.EntityA
generate-controller org.grails.test.EntityB
generate-views org.grails.test.EntityB
```

4. start-app and try to update existing entities in UI with invalid number *3000*

### Expected Behaviour

for both domains the controller should stay at the edit-page and show the validation message:
```
Property [number] of class [class org.grails.test.EntityB] with value [3,000] does not pass custom validation
```
![2017-10-23_120214-edit_entityb](https://user-images.githubusercontent.com/12848727/31883421-27953d2a-b7ea-11e7-97c3-4457b8c4aaa5.jpg)

### Actual Behaviour

- for the scaffold-controller of EntityA:
  - the invalid entered number is ignored and remains at value *2000*
  - the view redirects to entityA/show with the successful info message `EntityA 1 updated`
![2017-10-23_115458-show_entitya](https://user-images.githubusercontent.com/12848727/31883196-63a82922-b7e9-11e7-81b5-7e039af7621f.jpg)

- the other validations (generated-controller/create, scaffold-controller/create, generated-controller/edit) work as expected above

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.8 and 3.3.1
- **JDK Version:** 1.8.0_144

### Example Application
- https://github.com/fbartnitzek/grails3-no-scaffold-validation-msg

**Comment by jeffbrown** [comment]
This should probably be reported at https://github.com/grails-plugins/grails-scaffolding/issues.

**Comment by fbartnitzek** [comment]
That must be the wrong plugin, its latest release is grails-scaffolding v2.1.2 from 2014.

But gradle dependencies reveals another scaffolding plugin:
+--- org.grails.plugins:scaffolding: -> 3.3.2
That might be the following: https://github.com/grails3-plugins/scaffolding

There I found another issue with the same problem:
https://github.com/grails3-plugins/scaffolding/issues/24
It's 1.5 years old, without any comment or fix...

IMHO its quite a huge bug if the standard validation of a domain class does not work properly and should not be ignored for more than a year (plugin or not).

**Comment by jeffbrown** [comment]
> That must be the wrong plugin, its latest release is grails-scaffolding v2.1.2 from 2014.

You are correct.  I copied the wrong url.  Use https://github.com/grails3-plugins/scaffolding/issues

**Comment by jeffbrown** [comment]
Closing as this is already being tracked at https://github.com/grails3-plugins/scaffolding/issues/24.
