### ISSUE TITLE
DomainClassArtefactHandler.isDomainClass() returns false for proxies

### ISSUE THREAD

**Issue by gsartori** [grails/grails-core#10830]
We use `DomainClassArtefactHandler.isDomainClass()` in our plugin, it statred returning `false` just for fome records after upgrading Grails from `3.2.6` to `3.2.11`.

**Further analysis proved that it works on 3.2.9, it stops working on 3.2.10.**

Debugging we found the following:
![strangeclassnames](https://user-images.githubusercontent.com/8895933/31483757-07b7d54a-af2e-11e7-887b-41128fe23342.png)

I know I should add a test case but I'm currently handling a peak of work I won't be able to do it soon, sorry for that. I hope this is better than nothing.

### Expected Behaviour
`DomainClassArtefactHandler.isDomainClass()` should return `true` for all objects in the resultset.

### Actual Behaviour
`DomainClassArtefactHandler.isDomainClass()` returns `false` for some objects in the resultset.  Such objects are of a different class (as seen in the picture above). After a quick chat with james.kleeh on slack I understood they should be proxyes.

### Environment Information
- **Operating System**: Linux Fedora 25
- **Grails Version:** 3.2.11 (it works on 3.2.9, it stops working on 3.2.10)
- **JDK Version:** 1.8

**Comment by jameskleeh** [comment]
Try executing `DomainClassArtefactHandler.isDomainClass(class, true)`

**Comment by jameskleeh** [comment]
See https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/core/artefact/DomainClassArtefactHandler.java#L109

**Comment by gsartori** [comment]
All right, it's working with the above suggestions.
Thank you James for the time you dedicated me, it's much appreciated.
