### ISSUE TITLE
Save - flush not flushing inside a transaction in grails 3.3.0

### ISSUE THREAD

**Issue by AlexBoulyga** [grails/grails-core#10836]
Hi!
We have upgraded our project from grails 3.1.15 to 3.3.0, and since then we have an issue with save(flush: true).

### Steps to Reproduce

1. Create a transactional function ( f.e. a service function) that gets an existing domain object to work with
2. Change some parameter (f.e. the status to "Validating") of the object and save it with flush: true
3. Do some other calculations (or simply wait)
4. Fetch the objects status from another function while the first is still running.

### Expected Behaviour

Regarding the documentation step 4 should return the updated status (f.e. "Validating")

### Actual Behaviour

Step 4 returns the old, not updated status

### Environment Information

- **Operating System**: Ubuntu 14.04
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8.0_144

### Full explanation

In our case we have some long-running validations going on, and need to set the status so the users know something is happening in the UI. Since the upgrade however, all changes are only flushed when the transactional function is finished, and the flush parameter is beeing ignored.
Defining a subfunction for saving the status with propagation requires_new doesnt work (even after the bug fix in gorm 6.1.7) and throws an error that the domain object has two open sessions.
However, the documentation states:
http://docs.grails.org/latest/ref/Domain%20Classes/save.html

flush (optional) - When set to true flushes the persistence context, persisting the object immediately and updating the version column for optimistic locking

This doesnt seem to work anymore.

**Comment by jameskleeh** [comment]
The behavior you're describing is correct. Flushing the session simply executes the actions in the database and they are not committed (visible to other transactions) until the end of the transaction.

"Defining a subfunction for saving the status with propagation requires_new doesnt work (even after the bug fix in gorm 6.1.7) and throws an error that the domain object has two open sessions."

If you feel that is a bug, feel free to file an issue at github.com/grails/grails-data-mapping

**Comment by AlexBoulyga** [comment]
Hi!
Could you please update the documentation here atleast:

http://docs.grails.org/latest/ref/Domain%20Classes/save.html
as
"flush (optional) - When set to true flushes the persistence context, persisting the object immediately and updating the version column for optimistic locking"
sounds very different of the actual behaviour (especially the phrase 'persisting the object immediately')
Thank you!

**Comment by jameskleeh** [comment]
@AlexBoulyga The description is correct. The object is persisted immediately. One could argue that it could be expanded to include information about the behavior inside a transaction. If you'd like to submit a pull request for that change I'd be happy to review
