### ISSUE TITLE
GrailsDomainClass and GrailsDomainClassProperty return value differences in 3.3

### ISSUE THREAD

**Issue by jharlan-nextcentury** [grails/grails-core#10843]
### Description
In Grails 3.3, several of the method return values of the `GrailsDomainClass` and `GrailsDomainClassProperty` classes are not consistent with the values from older version (tested with 3.2.4).

### Steps to Reproduce
- Run the integration tests for each of the projects in the following repository:
https://github.com/jharlan-nextcentury/grails-domain-class-examples

Note: Each project was created using the Grails CLI `create-app` command, using the 3.2.4 and 3.3.1 SDKs.

### Noted Differences
- `GrailsDomainClass.getAssociationMap`
- `GrailsDomainClass.getRelatedClassType`
  - Throws `NullPointerException` for transient or computed properties.
- `GrailsDomainClassProperty.getReferencedPropertyType`
- `GrailsDomainClassProperty.isAssociation`

### Environment Information
- **Operating System**: Windows 10
- **Grails Version:** 3.2.4 and 3.3.1
- **JDK Version:** 1.8.0u144

### Notes
- The test cases are not comprehensive, but I will update them (and the issue) if I find any other inconsistencies. Thanks!
- Example domain classes taken from the [elasticsearch-grails-plugin](https://github.com/noamt/elasticsearch-grails-plugin) test suite.

**Comment by jharlan-nextcentury** [comment]
Updated the example repository and description; missed a test for a property, and added test for `GrailsDomainClass.getRelatedClassType`.

**Comment by jameskleeh** [comment]
Regarding the `GrailsDomainClass.getAssociationMap` test for `Team`. The properties are transient and therefore are not associations. There isn't anything we can do to change the functionality to make that test pass.

**Comment by jameskleeh** [comment]
For `Palette`, you are asserting that `colors` and `tags` are not assocations, however they are. That seems to me to be a bug in the old implementation and the new implementation is correct.

**Comment by jameskleeh** [comment]
For `Spaceship`, both the `associationMap` test and the `getRelatedClassType` were incorrect in the old implementation. `captain` is an association with a related type of `Person`

**Comment by jameskleeh** [comment]
@jharlan-nextcentury I've made the changes that were appropriate. There are still test failures due to the reasons I have indicated above. https://github.com/grails/grails-core/commit/97a67f93da23ade898e14a8ace522b49384bad30
