### ISSUE TITLE
Dirty checking does not work for changes to properties of a superclass that is not a domain class

### ISSUE THREAD

**Issue by sascharitter** [grails/grails-core#10847]
Let's assume that there is a domain class which extends an abstract class. Both classes define properties. The expectation is that changes to properties of the superclass are recognized by Grails' dirty checking mechanism and persisted. This is currently not the case in some circumstances.

The sample app defines a simple domain class `CityAddress` which extends the abstract class `Address`. Both classes have one property each. The app includes two integration tests and a controller to demonstrate the problem.

The domain class test `CityAddressIntegrationSpec` shows that changing a property of a superclass is not recognized by Grails' dirty checking mechanism when using `domainClass#hasChanged(String propertyName)`.

Additionally you can start the app and open http://localhost:8080/address/index which should initially display `Street: Street, City: City` (the data is created in BootStrap). The controller contains a few actions to set the properties of the domain class.

1. Calling http://localhost:8080/address/street?value=NewStreet should set the value for street which is a property of the superclass `Address`. But the value is not persisted and remains "Street".
2. Calling http://localhost:8080/address/city?value=NewCity sets the value for city which is a property of the domain class `CityAddress`. This works and so the result is `Street: Street, City: NewCity`.
3. Calling http://localhost:8080/address/bind?street=NewStreet sets the values using bindData which also does not work if trying to just set the value of a superclass property.
4. Calling http://localhost:8080/address/bind?street=SomeStreet&city=SomeCity works as expected and sets both values. The result is `Street: SomeStreet, City: SomeCity`.

Finally there is the service test `AddressServiceIntegrationSpec` for a service which pretty much does what the controller does but works as expected and persists the changes.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.11
- **GORM Version:** 3.1.8
- **JDK Version:** 1.8.0_102

### Example Application

https://github.com/sascharitter/grails-issue-dirty-check

**Comment by jameskleeh** [comment]
Add `@DirtyCheck` to the abstract class

**Comment by jameskleeh** [comment]
This is documented here: http://gorm.grails.org/latest/hibernate/manual/index.html#upgradeNotes "1.2.13. Dirty Checking for Abstract Base Classes"
