### ISSUE TITLE
Adding war to embedded tomcat results in starting Spring boot twice

### ISSUE THREAD

**Issue by daknetcompany** [grails/grails-core#10854]
### Steps to Reproduce

1. Create default Grails 3.3.1 web-app
2. Add bean to Application.groovy for adding another war file to the embedded tomcat container (see example below)
3. See that the Spring context is starting twice when booting up

### Expected Behaviour

Expect that the Spring context is only starting for the actual app. The documentation for the function `addWebapp(...)`, says that 
```
This is equivalent to adding a web application to Tomcat's webapps directory.
```
I know this is the Grails implementation, but using Spring functionality, should still work as intended.

### Actual Behaviour

Exception: `No Session found for current thread` is thrown, when working with domain objects (`myDomian.findBy(...)`), when we add another war file to the embedded tomcat container, like so:

```
class Application extends GrailsAutoConfiguration implements EnvironmentAware {
static void main(String[] args) {
    GrailsApp.run(Application, args)
}

@Bean
EmbeddedServletContainerFactory servletContainerFactory() {
     return new TomcatEmbeddedServletContainerFactory() {

        @Override
        protected TomcatEmbeddedServletContainer getTomcatEmbeddedServletContainer(Tomcat tomcat) {
              try {
                    // Ensure that the folder exists
                    tomcat.getHost().getAppBaseFile().mkdir()
                    String projektrod = System.getProperty('user.dir')
                    // Add external Orbeon war file
                    Context context = tomcat.addWebapp("/blanketdesigner/orbeon", "${projektrod}\\..\\blanket-orbeon-plugin\\orbeon\\orbeon.war")
                    context.setParentClassLoader(getClass().getClassLoader())
              } catch (ServletException ex) {
                    throw new IllegalStateException("Failed to add webapp", ex)
              }
              return super.getTomcatEmbeddedServletContainer(tomcat)
        }
    }
}
```

By debugging further, I found out that the whole Spring Boot environment is started twice, when adding an external war file by calling "`.addWebapp(...)`".

These means the following is set twice and causes issues:

```
public GrailsSessionContext(SessionFactoryImplementor sessionFactory) {
    this.sessionFactory = sessionFactory;
}
```

When Grails calls `getCurrentSession()`, the above seems to cause the problem, because it's set by another thread.

When working with domain objects, the `TransactionSynchronizationManager.getResource(sessionFactory);` returns `null`, and the exception is thrown.

```
public Session currentSession() throws HibernateException {
    Object value = TransactionSynchronizationManager.getResource(sessionFactory);
    if (value instanceof Session) {
        return (Session) value;
    }

    if (value instanceof SessionHolder) {
        SessionHolder sessionHolder = (SessionHolder) value;
        Session session = sessionHolder.getSession();
        if (TransactionSynchronizationManager.isSynchronizationActive() && !sessionHolder.isSynchronizedWithTransaction()) {
            TransactionSynchronizationManager.registerSynchronization(createSpringSessionSynchronization(sessionHolder));
            sessionHolder.setSynchronizedWithTransaction(true);
            // Switch to FlushMode.AUTO, as we have to assume a thread-bound Session
            // with FlushMode.MANUAL, which needs to allow flushing within the transaction.
            FlushMode flushMode = HibernateVersionSupport.getFlushMode(session);
            if (flushMode.equals(FlushMode.MANUAL) && !TransactionSynchronizationManager.isCurrentTransactionReadOnly()) {
                HibernateVersionSupport.setFlushMode(session, FlushMode.AUTO);
                sessionHolder.setPreviousFlushMode(flushMode);
            }
        }
        return session;
    }

    if (jtaSessionContext != null) {
        Session session = jtaSessionContext.currentSession();
        if (TransactionSynchronizationManager.isSynchronizationActive()) {
            TransactionSynchronizationManager.registerSynchronization(createSpringFlushSynchronization(session));
        }
        return session;
    }

    if (allowCreate) {
        // be consistent with older HibernateTemplate behavior
        return createSession(value);
    }

    throw new HibernateException("No Session found for current thread");
} 
```

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8.0

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by vir2610** [comment]
@daknetcompany Have you found the solution for above issue ? because I am kinda stuck with same behavior.

**Comment by daknetcompany** [comment]
@vir2610 no, I have not :(

We end up with starting 2 separate instances instead.

**Comment by bobbywarner** [comment]
Closing as there is nothing to fix in `grails-core` for this issue.  This is an issue that would have to be resolved directly with Spring Boot.  Please create an [issue with Spring Boot](https://github.com/spring-projects/spring-boot/issues) if you want to continue pursuing this change.

Also, just a note that a lot of these classes were changed / moved from Spring Boot 1.5 (Grails 3.3) and Spring Boot 2.0 (Grails 4) -- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#embedded-containers-package-structure
