### ISSUE TITLE
Unittesting Domains with different datasource

### ISSUE THREAD

**Issue by gsigmund** [grails/grails-core#10856]
Hi,

We have upgraded from grails 3.2 to 3.3.1
Now we have a problem with some unit tests.

When we @Mock Domain classes which uses another Datasource than the default, we get the following error. 

org.grails.datastore.mapping.core.exceptions.ConfigurationException: Invalid connection [otrs] configured for class [class at.dig.domain.otrs.CustomerUser]

Do you know how to tell SimpleMapDatastore to add the second datasource?

The test looks the following way

TestMixin(DomainClassUnitTestMixin)
@Mock([Customer, CustomerUser, Ticket])
class ExtOtrsReplicatorJobTest extends Specification {

Thanks for your ideas

I have attached a sample project. 

just run gradle test to execute the class "TestSpec"
[Archiv.zip](https://github.com/grails/grails-core/files/1472066/Archiv.zip)

**Comment by gsigmund** [comment]
I have attached an example now

**Comment by graemerocher** [comment]
There is a way to test multiple data sources with the in-memory datasource but not via the now deprecated `TestMixin` APIs. See https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-test/src/test/groovy/grails/gorm/tests/MultipleDataSourceSpec.groovy#L18

For example.

**Comment by bdbogjoe** [comment]
@gsigmund did you solve your issue ?

**Comment by gsigmund** [comment]
Hi, 
Yes that really solved my problem. 
thanks

**Comment by bdbogjoe** [comment]
can you look at my example ? how did you solve ? In my case the domain use only one datasource, but not the default one

**Comment by bdbogjoe** [comment]
https://github.com/bdbogjoe/unit-test-multiple-datasource

**Comment by anthonyMoreira** [comment]
The answer proposed here by @graemerocher  is lackluster in the way that the domain won't be mocked correctly. Indeed the validators won't be registered so all validation will pass, the mapping context won't be set correctly etc as @bdbogjoe demonstrated in his project...So it's very likely that using real world logic your unit test wont work at all.

It is also pretty invasive as it requires to mock/modify all request to use a different transactional service just to make a request to a different datasource where in previous version it was working transparently.

Please advise if you found a better solution so we can use full-featured mocked domains with different datasources in unit test
