### ISSUE TITLE
validate() on command objects treat getter methods without properties as constrained

### ISSUE THREAD

**Issue by jtkays** [grails/grails-core#10859]
### Task List

- [X] Steps to reproduce provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Download project and run.
2. Go to http://localhost:8080/demo/index

### Expected Behaviour

Validation shouldn't treat getter methods without properties as constrained properties. If so, then demo/index should respond with "Validation successful".

### Actual Behaviour

A "nullable" validation error on demoAmountAsLong is returned, even though there is no such property in the command object. This seems similar to  #9754.

### Environment Information

- **Operating System**: macOS Sierra, 10.12.6
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_151

### Example Application

- https://github.com/jtkays/grails-core-issue-10859

**Comment by jtkays** [comment]
Link to sample project: https://github.com/jtkays/grails-core-issue-10859

**Comment by jeffbrown** [comment]
> Validation shouldn't treat getter methods without properties as constrained properties

Why is that?

**Comment by jeffbrown** [comment]
We have tests that specifically (and intentionally) assert that properties without fields are validated.  That is by design.  https://github.com/grails/grails-core/blob/f0851718e8820470bd0f108a7d2ccf0cbdbe33fb/grails-plugin-validation/src/test/groovy/grails/validation/ValidateableTraitSpec.groovy#L126

**Comment by jeffbrown** [comment]
> A "nullable" validation error on demoAmountAsLong is returned, even though there is no such property in the command object. 

I don't think the "even though there is no such property in the command object" is correct.  There is a property named `demoAmountAsLong` defined in the class.  The getter represents the property accessor.  The fact that there isn't a corresponding field isn't relevant.

**Comment by jtkays** [comment]
Sorry, poor wording on my part, I used "property" where maybe I should have used "field". 

As to why I am making the assertion that a getter method without a corresponding field shouldn't be constrained, this came about as I was upgrading a project from Grails 2.3.11 to 3.2.11, and started having unit tests fail due to this change. So this behavior is new in Grails 3. And from reading issue #9754, it looked like that was describing a similar situation. I may have completely mis-read that issue, but the question was asked:
> should getters without setters be automatically considered as constrained properties? Any difference between Domain and Command Object?

To which the answer (the way I read it) was "no", they shouldn't be considered constrained. But maybe I've misunderstood, and if this behavior change is intentional (and since I can workaround it by creating a constraint for the getter), then I'd agree there is no issue.
