### ISSUE TITLE
Hot reloading of model changes breaks dynamic scaffolding

### ISSUE THREAD

**Issue by jamesdh** [grails/grails-core#10865]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce
- Create a domain class "Example", add property "blah" to it
- Create a matching controller with `static scaffold = Example`
- `./grailsw run-app`
- Browse to http://localhost:8080/example/create, verify it renders correctly
- Remove the property "blah", let app recompile
- Reload http://localhost:8080/example/create

### Expected Behaviour

Create view is rendered with the "blah" property removed

### Actual Behaviour

> org.springframework.beans.NotReadablePropertyException: Invalid property 'blah' of bean class [com.example.Example]: Bean property 'blah' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?

### Environment Information

- **Operating System**: OSX 10.13.1
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8.0_152
- **Container Version (If Applicable):** development runtime

### Example Application

Probably not worthwhile to create this as it's so easy to reproduce, but here it is anyways just in case:
https://github.com/jamesdh/grails3-reload-scaffold

**Comment by jeffbrown** [comment]
I don't think this is necessarily a problem with scaffolding per se.  I think the same behavior would happen if you were using `f:all` without the scaffolding (the scaffolding uses `f:all`).

**Comment by jamesdh** [comment]
@jeffbrown so you're suggesting I file this w/ grails-fields-plugin?

**Comment by jeffbrown** [comment]
>  so you're suggesting I file this w/ grails-fields-plugin?

No.  It is arguable where the bug is.  The scaffolding uses the fields plugin which gets the persistent properties from the `DomainModelService`, which gets the persistent properties from the `PersistentEntity` which comes from GORM and that entity contains out of date information.

I was simply pointing out that the problem isn't peculiar to scaffolding.  The bug report here is fine.
