### ISSUE TITLE
Build option grails.pathingJar = true does not work with Gradle 4+

### ISSUE THREAD

**Issue by davidkron** [grails/grails-core#10864]
### Problem description

I'm trying to use Gradle 4.3.1 with a Grails 3.3.1. project. As the project should be runnable on a windows machine, I'm setting the option `grails.pathingJar = true`  in the build.gradle file. When I disable the option, the build works fine. It seems that the grails-gradle-plugin overrides the classpath when the option is set, but sets it to a hard-coded value. Gradle has changed the default output format from `build/classes/main` to `build/classes/groovy/main` with version 4.0.

The problem seems to be a change in gradle 4.0:
https://docs.gradle.org/4.0/release-notes.html#multiple-class-directories-for-a-single-source-set

### Gradle output
```
|Resolving Dependencies. Please wait...
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy NO-SOURCE
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
	at build_bevvs8fqxmnab9slqz9j6thl4.run(C:\Users\David\IdeaProjects\demo\build.gradle:19)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)

CONFIGURE SUCCESSFUL in 4s
|Running application...
Error: Could not find or load main class demo.Application

FAILURE: Build failed with an exception.

```

### Steps to Reproduce

1. Create grails 3.3.1 application
2. Change gradle version to 4.3.1
3. Configure option `grails.pathingJar = true` in build.gradle
4. Run project

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.3.1
- **JDK Version:** Java 8

**Comment by jeffbrown** [comment]
I think this is a dup of #10813
