### ISSUE TITLE
Domain class compiled output file keep changing without modification

### ISSUE THREAD

**Issue by yokewang** [grails/grails-core#10868]
I have observed that the domain class compile output file(.class file) keep changing without modification to the source file(.groovy).

### Steps to Reproduce
1. grails create-app demo
2. cd demo
3. grails
4. create-domain-class Book
5. compile and get the Book.class and save it as Book1.class
6. clean 
7. compile and get the Book.class and save it as Book2.class

### Expected Behaviour
The Book1.class and Book2.class should be identical.

### Actual Behaviour
The Book1.class is different from Book2.class. The comparation of decompiled codes shows some 
TraitBridge locations are changing. 
    ------Book1.class----
```
    ....
    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "()V"
    )
    public void discard() {
        CallSite[] var1 = $getCallSiteArray();
        var1[87].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, this);
    }

    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "()Lorg/grails/datastore/gorm/GormStaticApi;"
    )
    private static GormStaticApi<Book> currentGormStaticApi() {
        CallSite[] var0 = $getCallSiteArray();
        return (GormStaticApi)ScriptBytecodeAdapter.castToType(var0[90].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, Book.class), GormStaticApi.class);
    }

    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "(Ljava/lang/Iterable;)Ljava/util/List;"
    )
    public static List<Book> getAll(Iterable<Serializable> arg1) {
        CallSite[] var1 = $getCallSiteArray();
        return (List)ScriptBytecodeAdapter.castToType(var1[91].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, Book.class, arg1), List.class);
    }

    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "(Ljava/util/Map;Ljava/util/Map;)Ljava/util/List;"
    )
    public static List<Book> findAllWhere(Map arg1, Map arg2) {
        CallSite[] var2 = $getCallSiteArray();
        return (List)ScriptBytecodeAdapter.castToType(var2[92].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, Book.class, arg1, arg2), List.class);
    }
    ....
```
 
-------Book2.class-----
```
...
@TraitBridge(
        traitClass = GormEntity.class,
        desc = "()Lorg/grails/datastore/gorm/GormStaticApi;"
    )
    private static GormStaticApi<Book> currentGormStaticApi() {
        CallSite[] var0 = $getCallSiteArray();
        return (GormStaticApi)ScriptBytecodeAdapter.castToType(var0[87].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, Book.class), GormStaticApi.class);
    }

    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "()V"
    )
    public void discard() {
        CallSite[] var1 = $getCallSiteArray();
        var1[88].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, this);
    }

    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "(Ljava/util/Map;Ljava/util/Map;)Ljava/util/List;"
    )
    public static List<Book> findAllWhere(Map arg1, Map arg2) {
        CallSite[] var2 = $getCallSiteArray();
        return (List)ScriptBytecodeAdapter.castToType(var2[91].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, Book.class, arg1, arg2), List.class);
    }

    @TraitBridge(
        traitClass = GormEntity.class,
        desc = "(Ljava/lang/Iterable;)Ljava/util/List;"
    )
    public static List<Book> getAll(Iterable<Serializable> arg1) {
        CallSite[] var1 = $getCallSiteArray();
        return (List)ScriptBytecodeAdapter.castToType(var1[92].call(org.grails.datastore.gorm.GormEntity.Trait.Helper.class, Book.class, arg1), List.class);
    }
    ....

```

### Environment Information
Operating System: OSX
Grails Version: 3.3.1
JDK Version: 1.8

**Comment by jameskleeh** [comment]
@yokewang What problematic behavior are you observing as a result of this?

**Comment by yokewang** [comment]
@jameskleeh We use VCS to track the change of both source codes and compiled classes. And it is confusing if the compiled classes keep changing while the source codes are unchanged. 
eg. When I see some classes is changed, I have to check the code to confirm if someone changed code.

**Comment by jameskleeh** [comment]
@yokewang That is very unusual. I'm not aware of any good reasons to keep version control history of compiled classes. If you would like to find the root cause and submit a PR, we would be glad to review it.

**Comment by jeffbrown** [comment]
It is interesting that this is happening but I don't necessarily think it is a bug.  The compiler doesn't make promises about things like order of methods in the bytecode, order of entries in the constant pool etc.  I don't know what is causing the change described here but it may be that this is not really a bug or anything we can practically do anything about.

**Comment by khelenek** [comment]
I believe this causes cache misses when using the Gradle Build Cache. 

If you have a multi-project build (A depends on B), then if B's resulting jar file checksum keeps changing due to the described behavior and A's compilation classpath fingerprint will look different every time.
