### ISSUE TITLE
Default contstraints does not work for embedded components

### ISSUE THREAD

**Issue by ivo-k** [grails/grails-core#10867]
### Abstract

GORM default constrains seems to be ignored for embedded components of an entity class. In grails 2, default constrains where applied to all properties, whether embedded or not.

### Steps to Reproduce

1. Add a default constraint for all properties into grails configuration

```
    grails.gorm.default.constraints = {
        '*'(nullable: true)
    } 
```

2. Create a class that can be used as embedded component of a GORM domain class

```
    class Address {
        String street
        String zipCode
        String city
    } 
```

3. Create a domain entity and use the embedded component

```
    class User {
        String username
        String password
        String comment
        Address address = new Address()
    
        static embedded = ['address']
    }
```

4. Validate an instance of the domain class with some properties being `null`

```
    User u = new User()

    u.username = 'admin'
    u.address.city = 'Berlin'

    boolean valid = u.validate()
    assert valid
```

### Expected Behaviour

The entity should be valid, since the default constraint allows it for all properties.

### Actual Behaviour

The validation fails. The properties of the embedded class that are null raising a field error.

```
    Property [street] of class [class grails.embedded.nullables.Address] cannot be null
    Property [zipCode] of class [class grails.embedded.nullables.Address] cannot be null
```

### Environment Information

- **Operating System**: Win 7
- **Grails Version:** 3.3.1
- **GORM Version: ** 6.1.8
- **JDK Version:** 1.8

### Example Application

- [Example](https://github.com/ivo-k/grails-embedded-nullables)

**Comment by ilopmar** [comment]
As a workaround you can move `Address` to the same `User` class or keep it under `src/main/groovy` and annotate it with `@grails.persistence.Entity`

**Comment by ilopmar** [comment]
Fixed by https://github.com/grails/grails-data-mapping/pull/1056
