### ISSUE TITLE
ArrayIndexOutOfBoundsException when implementing GrailsUnitTest generated by create-unit-test

### ISSUE THREAD

**Issue by rwin336** [grails/grails-core#10861]
Env:
 grails --version
| Grails Version: 3.3.1
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_151

Using Grails in Action book.  Trying to run unit test in Chap6.

Created unit test using
 grails create-unit-test com.cisco.hubbub.PostController

The unit test created by Grails implements GrailsUnitTest when using this I get the following error when running the test.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor': Initialization of bean failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: 0

Removing the "implements GrailsUnitTest" everything works as expected.

Both the book and docs don't seem to indicate the need to implement GrailsUnitTest why does the create-unit-test add it?

Thanks
===================================================
```
package com.cisco.hubbub

import grails.test.mixin.Mock
import grails.test.mixin.TestFor
import org.grails.testing.GrailsUnitTest
import spock.lang.Specification


@TestFor(PostController)
@Mock([User, Post])
class PostControllerSpec extends Specification implements GrailsUnitTest {

    def setup() {}

    def cleanup() {}

    def "Get a users timeline given there id"() {
        given: "A user with posts in the db"

        User chuck = new User(loginId: "chuck_norris", password: "password")
        chuck.addToPosts(new Post(content: "A first post"))
        chuck.addToPosts(new Post(content: "A second post"))
        chuck.save(failOnError: true)

        and: "A loginId parameter"
        params.id = chuck.loginId

        when: "the timeline is invoked"
        def model = controller.timeline()

        then: "the user is in the returned model"
        model.user.loginId == "chuck_norris"
        model.user.posts.size() == 2
    }
    
}
```
===================================================

**Comment by jameskleeh** [comment]
You should have have a test annotated with `@TestFor` and `@Mock` while also implementing `GrailsUnitTest`. The `create-unit-test` command in Grails 3.3.1 does not create a test with those annotations.

If you can upload an example application that reproduces the issue, we can look at it

**Comment by jeffbrown** [comment]
You probably want something like this (I haven't run it, I just copied and pasted your example and made changes).

```groovy
package com.cisco.hubbub

import org.grails.testing.*
import spock.lang.Specification


class PostControllerSpec extends Specification implements ControllerUnitTest<PostController>, DataTest {

    def setupSpec() {
        mockDomains User, Post
    }

    def "Get a users timeline given there id"() {
        given: "A user with posts in the db"

        User chuck = new User(loginId: "chuck_norris", password: "password")
        chuck.addToPosts(new Post(content: "A first post"))
        chuck.addToPosts(new Post(content: "A second post"))
        chuck.save(failOnError: true)

        and: "A loginId parameter"
        params.id = chuck.loginId

        when: "the timeline is invoked"
        def model = controller.timeline()

        then: "the user is in the returned model"
        model.user.loginId == "chuck_norris"
        model.user.posts.size() == 2
    }
}
```

**Comment by rwin336** [comment]
First - thanks for the quick response.

I took out the TestFor and Mock annotations and used the ControllerUnitTest as indicated above and it all works.  

Thanks again
