### ISSUE TITLE
3.3.1 Integration Tests Hanging

### ISSUE THREAD

**Issue by DeanGaffney** [grails/grails-core#10863]
I attempted to run some integration tests in my project but the command line seems to hang at the 'integrationTestClasses' stage on 86%. The tests never finish, and I must kill the process to stop them.

I have been working on two different git branches in my project, the older branch runs integration tests fine, but the newer branch hangs while running them. Unfortunately there are no errors, and I understand this may not be reproducible, but I still find the behavior unusual which is why I am posting it here. I must also mention that if I do 'run-app' the application functions perfectly, integration tests seem to be the issue. 

The issue occurs consistently on my Linux and Windows machines on the same branch. 

I have created a second application and copied over integration tests to try and narrow down the issue to a specific test, however it appears that all integration tests cause the task to hang. Due to this I am starting to think it could be a dependency issue or a gradle issue.

I would really appreciate some feedback on how to try and narrow this issue down further.

### Steps to Reproduce

1. View/ Download project here [https://github.com/DeanGaffney/GrailsTest](https://github.com/DeanGaffney/GrailsTest)
2. Run the './gradlew clean integrationTest'

### Expected Behaviour

Integration tests to run and complete/fail

### Actual Behaviour

The integration tests completed remain at 0, and never increase.

### Environment Information

- **Operating System**:  Linux Mint 18 Sarah & Windows 10
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8.0_144

**Comment by jeffbrown** [comment]
I think the problem is with your logging config.  At https://github.com/DeanGaffney/GrailsTest/blob/f9f52c4f5aa166e6f63ce76c9385771f5551782f/grails-app/conf/logback.groovy you have the following:

```groovy
import grails.util.BuildSettings
import grails.util.Environment
import org.springframework.boot.logging.logback.ColorConverter
import org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter

import java.nio.charset.Charset

conversionRule 'clr', ColorConverter
conversionRule 'wex', WhitespaceThrowableProxyConverter

// See http://logback.qos.ch/manual/groovy.html for details on configuration
appender('STDOUT', ConsoleAppender) {
    encoder(PatternLayoutEncoder) {
        charset = Charset.forName('UTF-8')

        pattern =
                '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} ' + // Date
                        '%clr(%5p) ' + // Log level
                        '%clr(---){faint} %clr([%15.15t]){faint} ' + // Thread
                        '%clr(%-40.40logger{39}){cyan} %clr(:){faint} ' + // Logger
                        '%m%n%wex' // Message
    }
}

def targetDir = BuildSettings.TARGET_DIR
if (Environment.isDevelopmentMode() && targetDir != null) {
    appender("FULL_STACKTRACE", FileAppender) {
        file = "${targetDir}/stacktrace.log"
        append = true
        encoder(PatternLayoutEncoder) {
            pattern = "%level %logger - %msg%n"
        }
    }
    logger("StackTrace", ERROR, ['FULL_STACKTRACE'], false)

    appender("IRIS_DEBUG", FileAppender){
        file = "${targetDir}/debug.log"
        append = true
        encoder(PatternLayoutEncoder) {
            pattern = "%level %logger - %msg%n"
        }
    }
    logger("com.wit.iris", DEBUG, ['IRIS_DEBUG'], false)
}
root(ERROR, ['STDOUT', 'IRIS_DEBUG'])
```

If you change that `root(ERROR, ['STDOUT', 'IRIS_DEBUG'])` to `root(ERROR, ['STDOUT'])` I think your tests will work.  The problem may be that you are defining the `IRIS_DEBUG` appender only if `Environment.isDevelopmentMode()` is `true` but you are trying to use it even if `Environment.isDevelopmentMode()` is not `true`.

**Comment by DeanGaffney** [comment]
@jeffbrown that has solved the issue, really appreciate it.

**Comment by jeffbrown** [comment]
Right.  You probably want to either define the appender outside of the `if(Environment.isDevelopmentMode() ...)` block, or organize the logic so you only associate that appender with the `root` logger if `Environment.isDevelopmentMode()` is true.

**Comment by DeanGaffney** [comment]
Thanks, I have already fixed the logic and it works perfectly.
