### ISSUE TITLE
grails run-app executes the code in application.groovy twice

### ISSUE THREAD

**Issue by RobertStroud** [grails/grails-core#10876]
The code in application.groovy is executed twice if you start your program with "grails run-app" but only once if you start your program with "gradlew bootRun".

### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Grails application 
2. Create "grails-app/init/application.groovy"
3. Add "println 'hello world'" to "application.groovy
4. Type "grails run-app"

### Expected Behaviour

I would expect "hello world" to be printed once

### Actual Behaviour

"hello world" is printed twice

### Environment Information

- **Operating System**: MacOS X 10.11.6
- **Grails Version:** Grails 3.1.1
- **JDK Version:** JDK 1.8.0_152-ea

### Example Application

- https://github.com/RobertStroud/GrailsApplicationRunsTwice/

**Comment by jameskleeh** [comment]
If you move the `println` to a file called `runtime.groovy` in the same folder, does it get executed twice?

**Comment by RobertStroud** [comment]
I left the `println` in `application.groovy` and added a new file called `runtime.groovy` with its own `println`. The `println` in `application.groovy` was executed twice as before, but the `println` in `runtime.groovy` was only executed once.

The output sequence is as follows:

```
Hello world from application.groovy
| Running application...
Hello world from application.groovy
Hello world from runtime.groovy
```

In other words, `application.groovy` runs before and after Grails prints `| Running application...` but `runtime.groovy` only runs after `application.groovy` has run for the second time.

**Comment by graemerocher** [comment]
`application.groovy` is read by the CLI once and later by the runtime.
