### ISSUE TITLE
Iternationalize routes via messages.properties

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [grails/grails-core#10881]
This is a feature request. 

It would be nice, if it were possible to define routes in UrlMappings.groovy and messages.properties like this:

In messages.properties:
`controller.citiesTo="/cities/$cityname"`

In messages_de.properties:
`controller.citiesTo="/staedte/$cityname"`

In messages_es.properties:
`controller.citiesTo="/ciudades/$cityname"`

In urlMappings.groovy:
`def citynameUrl = getGrailsApplication().getMainContext().getMessage('controller.citiesTo', ['$cityname'] as Object[], 'cities', LCH.getLocale())`

`name cityname: "/${citynameUrl}/"  {`
`      controller = "cities"`
`      action = "showCityDetails"`
`      constraints {`
`        cityname(matches:"^[^A-z ].+")`
`      }`
`}`

**Comment by jameskleeh** [comment]
This is likely possible today if you were to support a predefined set of locales.

**Comment by jameskleeh** [comment]
For example, inside your url mappings block:

```
        MessageSource messageSource = getGrailsApplication().mainContext.getBean("messageSource", MessageSource)
        [Locale.GERMAN, new Locale("es", ""), Locale.ENGLISH].each { Locale locale ->
            String controllerUrl = messageSource.getMessage("controller.cities", [] as Object[], locale)

            "/${controllerUrl}/$cityName" {
                controller = "cities"
                action = "showCityDetails"
            }

        }
```

**Comment by jameskleeh** [comment]
Closing this issue as I believe the code in my response meets your needs

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
Thank you for your response. I agree that this is a workaround. However, it has a few drawbacks on which you could improve :

1. You solution will create duplicate routes, if you are using a domain based locale solution. If I have an english and german site, the english URL's will also be accessible via the german domain and vice versa. People will say that's not a problem, Maybe some people even want this behaviour. However, it might create duplicate content issues whith google.

2. There is quite some boiler plate code involved. If you have a large site with a lot of routes, then this is not very elegant and easy to use for grails beginners. It would be nice, if you could directly reference the translations in messages.properties in the blocks, where you define the routes. For example:

`"/${contact}/$cityName" {`

In the absence of a variable like contact, grails could try to look for the corresponng key in the message property file for the locale of the current request. This would be very convenient for sites, which have a lot of URL's and want each URL to be localized. 

It would require that urlMappings.groovy is invoked for each request and that the current locale is accessible OR that the routes are generated for each locale (like you did in your example) and stored in a map so that when a request comes in you can retrieve the routes for the locale of the CURRENT request.

The workings of urlMappings.groovy is such, that the Locale is fixed and does not depend on the current request, which I find confusing. I would have thought that a call to LCH.getLocale() gets the current locale OR ist not accessible, because what's the point of calling it, when it's always the same.

**Comment by jameskleeh** [comment]
> In our project we don't want the localized english routes to be accessible through the german domain. So mysite.de/cities should return a 404. This is currently not easily implementable. A switch in config/application.grooy to configure the behaviour would be nice.


You can access configuration through `getGrailsApplication()` and apply any logic you like.

The other changes you suggest (having the variables automatically look up i18n, have the mappings evaluated on a per request level) are not something we are willing to consider at this time. The changes are either not a good idea for any number of reasons or are too much of a breaking change.

Thanks for submitting the issue and making me aware of this type of use case!
