### ISSUE TITLE
Startup-Error when using grails plugins compile syntax in the build.gradle on mac

### ISSUE THREAD

**Issue by dularion** [grails/grails-core#10887]
So here is the deal. We got a couple of programmers working in Windows and a couple of programmers working on Mac. Also, we have a project structure with plugins alongside our main server-application. As per the documentation, we include these plugins like so: 

```yaml
// build.gradle
grails {
  exploded = true
  plugins {
    compile project(":es-grails-plugin")
    compile project(":basex-core")
    compile project(":basex-utility")
  }
}

```

When using it this way, the Windows Developers have no issues, and hot-swapping works great. But for the two Mac Developers (and on the linux machine that deploys the application), this syntax causes startup errors: 
```bash
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/antonia/dev/projects/basex/basex-core-grails-plugin/build.gradle' line: 85
```
Full stacktrace is here: https://pastebin.com/AqU6152s  

However, if we move the plugins into the `dependencies` block, it works (including hot-swapping) for the OSX users and it works for Windows users, but without hotswapping. 

### Environment Information

- **Operating System**: macOS Sierra 10.12.6 (for both mac environments)
- **Grails Version:** 3.3.1
- **JDK Version:** 1.8_144

**Comment by sdelamo** [comment]
Could you try to workaround it by detecting the operating system in your build.gradle file. 

Eg. 
```

import org.gradle.internal.os.OperatingSystem;

if (OperatingSystem.current().isMacOsX()) {
// Do stuff
}
```

**Comment by dularion** [comment]
Yep this is a good workaround! 
However, do you know why this problem occurs on mac? as per the grails docs (chapter about plugins) the syntax below should be correct 

```
grails {
  exploded = true
  plugins {
    compile project(":somePlugin")
  }
}
```

**Comment by jameskleeh** [comment]
I can't reproduce the issue. Please upload an example project.

**Comment by jeffbrown** [comment]
@dularion Are you able to reproduce this problem in a sample project that you can share?

Thanks for any feedback.

**Comment by dularion** [comment]
Actually, thanks to the workaround I kinda solved it for me. So for my part you can close the issue. but If you prefer to investigate I can set some time aside next weekend and try to create a sample project

**Comment by jeffbrown** [comment]
>  ...but If you prefer to investigate I can set some time aside next weekend and try to create a sample project

That would be awesome.  Thanks for your help!
