### ISSUE TITLE
Transient domain class properties are persisted in Grails 3.3.2

### ISSUE THREAD

**Issue by dustindclark** [grails/grails-core#10895]
### Steps to Reproduce
1. Create domain class with transient properties
2. Save instance of that domain class
3. Confirm that transient properties are not persisted

### Expected Behaviour
Transient properties should not be persisted.

### Actual Behaviour
Transient properties should *are* persisted.

### Environment Information

- **Operating System**: Mac OS High Sierra
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8u65
- **Container Version (If Applicable):** N/A

### Example Application
Run the unit test to recreate the issue.  The same behavior occurs at runtime.
https://github.com/dustindclark/grails-transient-bug

**Comment by sdelamo** [comment]
If you run your example app and, open dbconsole to check the H2 database created. You will see there is no column for the transient property.

![h2_console](https://user-images.githubusercontent.com/864788/34245548-a112eb84-e62a-11e7-9620-e1cb928a51e1.png)

If you want to test this you could write an integration test: 


```
package demo

import grails.testing.mixin.integration.Integration
import spock.lang.Specification
import transients.bug.Somethin

@Integration
class SomethingIntegrationSpec extends Specification {

    void "test transients are not persisted"() {
        given:
        Integer id
        Somethin.withTransaction {
            Somethin somethin = new Somethin(persisted: "complete", notPersisted: 'wut')
            somethin.save()
            id = somethin.id
        }

        when:
        Somethin something
        Somethin.withTransaction {
            something = Somethin.get(id)
        }

        then: "Transient property should not be persisted"
        something.notPersisted != 'wut'
    }
}
```

In the unit test, it uses 

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-test/src/main/groovy/org/grails/datastore/mapping/simple/SimpleMapSession.java

which uses a HashMap as datastore.

**Comment by dustindclark** [comment]
Thanks @sdelamo .  The example project failed to properly illustrate the problem that I'm having, but I will open a new issue when I'm able to fully reproduce in a sample app.  In my application (that's being upgraded from 2.5.1 to 3.3.2), I have a plugin domain class that implements a trait.  In that trait, there's a property that is defined as transient.  The application will not start because the generated SQL looks for the transient property in the generated SELECT statement that executes in the plugin's doWithApplicationContext.  That's all I know at this point, but I'll post more info when I have it.

**Comment by dustindclark** [comment]
@sdelamo the problem appears to be with traits.  We have a trait that several domain classes implement called `Versionable`, which prevents updates if the effective date is in the past.  The definition for `static transients = ['ignorePriorEffectiveDate']` is in that trait.  GORM does not generate that column in the DDL, but looks for that column in SELECT statements.  The workaround is to move the transients declaration to each domain class that implements `Versionable`.  Even if this approach is not recommended, I would think the behavior between DDL generation and SELECT statements should be consistent (and this worked in 2.5.1).  Let me know your thoughts on re-opening a new issue.  Thanks.

**Comment by sdelamo** [comment]
If you are able to create a sample project with a reproducible example, upload it to Github and I can take look. Maybe we can repopen this issue or create a new one.

**Comment by dustindclark** [comment]
@sdelamo I've updated the original repo with the trait and an integration test that recreates the issue.  The behavior is slightly different based on the `dbCreate` setting, but if you run the project, you'll see that the FORCE_UPDATE column is created and that the integration test fails:

https://github.com/dustindclark/grails-transient-bug

**Comment by bcfisher** [comment]
I was noticing this today as well when trying to use the Taggable plugin. It was mentioned it might get re-opened and fixed. For now I'll use the workaround as well.
