### ISSUE TITLE
propName parameter is not used in AbstractGrailsClass.getPropertyValue(String propName, Class<T> type)

### ISSUE THREAD

**Issue by moskauerst** [grails/grails-core#10892]
**propName** parameter is not used in AbstractGrailsClass.getPropertyValue(String **propName**, Class<T> type)

AbstractGrailsClass.java:
```
    public <T> T getPropertyValue(String propName, Class<T> type) {
        return ClassPropertyFetcher.getStaticPropertyValue(getClazz(), name, type);
    }
```

### Environment Information

- **Grails Version:** 3.3.2

**Comment by jeffbrown** [comment]
Probably just a mistake at https://github.com/grails/grails-core/commit/716f3eeb0e732a408f3aa93b72faacf2ec422171#diff-01e675dad45cfd167162befd183085aaR250.

**Comment by jeffbrown** [comment]
Fixed
