### ISSUE TITLE
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:   [groovyc] Compile error during compilation with javac.

### ISSUE THREAD

**Issue by avinashpandit382** [grails/grails-core#10890]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] Compile error during compilation with javac.

**Comment by jeffbrown** [comment]
Is this a Grails app?

**Comment by avinashpandit382** [comment]
BatchCPRUPdateJob  is a groovy file which will use to update some information

**Comment by jeffbrown** [comment]
> BatchCPRUPdateJob is a groovy file which will use to update some information

1. Is that Groovy file in a Grails App?
2. Can you show what that file looks like?

**Comment by avinashpandit382** [comment]
So the error is throwing like this : 
 [groovyc]   found:    Object
  [groovyc] C:\Users\AVINAS~1.PAN\AppData\Local\Temp\groovy-generated-4640617315081417842-java-source\com\wmdata\as2007\batchrunner\BatchCPRUpdateJob.java:23: error: package Batchjob does not exist
  [groovyc] public  Batchjob.Status getStatus() { return (Batchjob.Status)null;}

**Comment by avinashpandit382** [comment]
and groovy file contains the code : 

class BatchCPRUpdateJob extends AS2007JobRunner {
    static Logger logger = Logger.getLogger(BatchCPRUpdateJob.class);

    static final String NEWLINE = "\r\n";

    String logText;
    Batchjob.Status status = null;

    String getJobName() {
        return "BatchCPRUpdateJob";
    }

    String getLogText() {
        return logText
    }

    void runJob() {
        CprLogFiler logFiler = getCPRBeanLocal().opdaterAlleYdelsesModtagere();
        Collection<CprOpdateringsBesked> opdateringsListe = logFiler.getLogfil();
        Collection<CprOpdateringsBesked> aendringsListe = opdateringsListe.findAll {!it.isFejl()}
        Collection<CprOpdateringsBesked> fejlListe = opdateringsListe.findAll {it.isFejl()}.findAll {it.getBesked() != ""};

        if (!fejlListe) {
            setStatus(Batchjob.Status.OK);
            logText = new String("CPR batchopdatering gennemført med succes!" + NEWLINE + NEWLINE);
        } else {
            setStatus(Batchjob.Status.Log);

**Comment by avinashpandit382** [comment]
Adding that this tag is throwing error  from build.xml : 
 <groovyc destdir="${build.dir}/classes"  srcdir="${src.dir}" classpathref="build.classpath" encoding="ISO-8859-1" >
            <javac debug="on" encoding="ISO-8859-1" >
                <compilerarg value="-Xlint:deprecation"/>
                <compilerarg value="-Xlint:unchecked"/>
            </javac>
        </groovyc>

**Comment by jeffbrown** [comment]
Is that Groovy file in a Grails App?

**Comment by jeffbrown** [comment]
It looks like @avinashpandit382 edited the initial comment and deleted subsequent comments.

It is unclear if there is an issue here or not.  I am going to close the request and if there is an issue, please feel free to leave a comment and we can re-open or create a new issue.

Thanks for the feedback.

**Comment by sachintiwari-reachlocal** [comment]
[groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
[groovyc] /Users/sachintiwari/.grails/2.5.0/projects/cts-admin-api/plugins/console-1.2/grails-app/taglib/org/grails/plugins/console/ConsoleTagLib.groovy: 3: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder
  [groovyc]  @ line 3, column 1.
  [groovyc]    import org.codehaus.groovy.grails.plugins.PluginManagerHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] /Users/sachintiwari/.grails/2.5.0/projects/cts-admin-api/plugins/jquery-1.7.1/grails-app/taglib/JQueryResourceTagLib.groovy: 19: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]  @ line 19, column 1.
  [groovyc]    import org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] /Users/sachintiwari/.grails/2.5.0/projects/cts-admin-api/plugins/jquery-1.7.1/src/groovy/org/codehaus/groovy/grails/plugins/jquery/JQueryConfig.groovy: 19: unable to resolve class org.codehaus.groovy.grails.commons.ApplicationHolder
  [groovyc]  @ line 19, column 1.
  [groovyc]    import org.codehaus.groovy.grails.commons.ApplicationHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] /Users/sachintiwari/.grails/2.5.0/projects/cts-admin-api/plugins/resources-1.1.6/grails-app/taglib/org/grails/plugin/resource/ResourceTagLib.groovy: 6: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]  @ line 6, column 1.
  [groovyc]    import org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] /Users/sachintiwari/.grails/2.5.0/projects/cts-admin-api/plugins/resources-1.1.6/src/groovy/org/grails/plugin/resource/ResourceProcessor.groovy: 20: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder
  [groovyc]  @ line 20, column 1.
  [groovyc]    import org.codehaus.groovy.grails.plugins.PluginManagerHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] /Users/sachintiwari/.grails/2.5.0/projects/cts-admin-api/plugins/resources-1.1.6/src/groovy/org/grails/plugin/resource/util/HalfBakedLegacyLinkGenerator.groovy: 3: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]  @ line 3, column 1.
  [groovyc]    import org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]    ^
  [groovyc] 
  [groovyc] 6 errors



encountered while running a project with Grails 2.5.0 and JDK 8u131
