### ISSUE TITLE
GrailsDatabinder fails to bind to List<Date>

### ISSUE THREAD

**Issue by sbglasius** [grails/grails-core#10894]
### Steps to Reproduce

When binding a params map to a `List<Date>` it fails.

With an Entity like below:
```
@Entity
class RecurringEvent {
    String name
    List<Date> dates
    static hasMany = [dates: Date]
}
``` 
And binding data to it:
``` 
def params = [
    'name'          : 'Groovy & Grails User Group',
    'dates[0]'      : 'struct',
    'dates[0]_day'  : '09',
    'dates[0]_month': '11',
    'dates[0]_year' : '2012',
    'dates[1]'      : 'struct',
    'dates[1]_day'  : '13',
    'dates[1]_month': '12',
    'dates[1]_year' : '2012',
]
def event = new RecurringEvent()
grailsWebDataBinder.bind(event, params as SimpleMapDataBindingSource)
```
### Expected Behaviour

I would expect it to return the two dates bound

### Actual Behaviour
```
event.dates == null
``` 

### Environment Information

- **Operating System**: Ubuntu 17.10
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8

### Example Application

Example application with integration test cases can be found here:

https://github.com/sbglasius/bind-date-array-bug

This is a bug that has the test in *joda-time* plugin marked with `@Ignore`: https://github.com/gpc/joda-time/blob/master/src/integration-test/groovy/grails/plugins/jodatime/binding/StructuredBindingSpec.groovy#L106

**Comment by jameskleeh** [comment]
Fixed with https://github.com/grails/grails-core/commit/bdad419ac1ff6c7dbb819d256ef6d4d694edc8a5
