### ISSUE TITLE
Grails doesn't support Spring Boot's multi-profile YAML documents

### ISSUE THREAD

**Issue by timic** [grails/grails-core#10897]
I want to use multu-profile configurations provided by spring boot - https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-multi-profile-yaml. But grails doesn't support it. It always uses properties from latest document section in `application.yml`.

### Steps to Reproduce

1. Configure specific spring profile in `application.yml`.
For example:
```
---
# default profile config
hello.message: Default hello!

---
# profile configuratuion
spring.profiles: sample-profile
hello.message: Hello from sample profile!
```
2. Start grails application.

### Expected Behaviour

By default `grailsApplication.config.hello.message` must return `"Default hello!"`

### Actual Behaviour

But it returns `"Hello from sample profile!"`.

### Environment Information

- **Operating System**: Linux 4.9.68-1
- **Grails Version:** 3.2.11
- **JDK Version:**
```
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### Example Application

https://github.com/timic/sample-grails-spring-boot-multi-profile-configuration

**Comment by ilopmar** [comment]
With this configuration defined in `application.yml`:

```yaml
---
# default profile config
hello:
    message: Default hello!
---
spring:
    profiles: sample
hello:
    message: Hello from SAMPLE profile!
---
spring:
    profiles: demo
hello:
    message: Hello from DEMO profile!
```

I've found that adding `environment.addActiveProfile('sample')` after this line https://github.com/grails/grails-core/blob/43dc5c5ed4ed6f710c1af869ed0812559216a141/grails-core/src/main/groovy/grails/boot/GrailsApp.groovy#L117 makes it work and the application show the message *"Hello from SAMPLE profile!"*

Now I have two problems:

1.- I start the application with `grails -Dspring.profiles.active=sample run-app` but the option `spring.profiles.active=sample` is not passed from `GroovyScriptCommand` to the new application run here: https://github.com/grails/grails-core/blob/a71c7728279472ff2b263561096ac1b4f0c3bbe4/grails-shell/src/main/groovy/org/grails/cli/profile/commands/script/GroovyScriptCommand.groovy#L152

You can see here that before calling `run()`, `executionContext.commandLine.systemProperties` contains `spring.profiles.active = sample`, but this value is never passed to the application (or at least I can't find a way to get it from the running app).

![groovyscriptcommand](https://user-images.githubusercontent.com/559192/36035561-89f4acd0-0db7-11e8-973f-0fa548607861.png)


2.- When only `grails.env` is set here as a profile, i.e. the current code:
 https://github.com/grails/grails-core/blob/43dc5c5ed4ed6f710c1af869ed0812559216a141/grails-core/src/main/groovy/grails/boot/GrailsApp.groovy#L117 
then when parsing the yml configuration and returning the properties here: https://github.com/grails/grails-core/blob/f5d068dd5726d0285501fecba4226140fac4be1f/grails-core/src/main/groovy/org/grails/config/yaml/YamlPropertySourceLoader.groovy#L69 
the last configuration wins, in this case for the profile `demo`, so the message returned is _"Hello from DEMO profile!"_. Even if no profile is set.
I'm not really sure how to fix this.

**Comment by graemerocher** [comment]
Grails doesn't automatically pass CLI system properties. See http://mrhaki.blogspot.com.es/2015/09/grails-goodness-passing-system.html

**Comment by ilopmar** [comment]
Adding
```groovy
configure(bootRun) {
    systemProperties System.properties
}
```
To `build.gradle` makes the following code work in `GrailsApp.groovy`:

```groovy
    @Override
    protected void configureEnvironment(ConfigurableEnvironment environment, String[] args) {
        configurePropertySources(environment, args)

        String[] springProfile = environment.getProperty('spring.profiles.active', String[])
        if (springProfile) {
            environment.setActiveProfiles(springProfile)
        }

        def env = Environment.current
        environment.addActiveProfile(env.name)
    }
```

So now it is possible to pass `spring.profiles.active` and they are applied. 

We still have the issue when no profile is pass because the latest configuration on `application.yml` is applied (instead of the default one). Do you have any hints about how to fix this here https://github.com/grails/grails-core/blob/f5d068dd5726d0285501fecba4226140fac4be1f/grails-core/src/main/groovy/org/grails/config/yaml/YamlPropertySourceLoader.groovy#L69 or any other place?
