### ISSUE TITLE
Strings containing just whitespace are interpreted as blank

### ISSUE THREAD

**Issue by chris13524** [grails/grails-core#10906]
When a JSON object is sent and validated by a command object, a string containing just whitespace is being interpreted as blank.

### Steps to Reproduce

1. Download and run the [test program](https://github.com/grails/grails-core/files/1640165/jsonstrings.zip).
2. POST a JSON object containing just whitespace: `curl -X POST localhost:8080/test -H "Content-Type: application/json" -d '{"hello":"  "}'`
3. POST the same thing, but print out the request body instead of passing it to a command object: `curl -X POST localhost:8080/test/fine -H "Content-Type: application/json" -d '{"hello":"  "}'`

### Expected Behaviour

`blank: false` should only apply to strings who's lengths are 0.

### Actual Behaviour

`blank: false` applies to any string that is either length==0 or contains only whitespace.

### Environment Information

```
$ grails --version
| Grails Version: 3.3.1
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_151
```

### Example Application

[Example Application](https://github.com/grails/grails-core/files/1640165/jsonstrings.zip)

**Comment by jameskleeh** [comment]
The actual behavior you described is how it should work. The blank constraint should only pass if the string contains a non whitespace character.

**Comment by chris13524** [comment]
I suggest tweaking the documentation to indicate that. Because "blank" makes me think of "empty" which in the Java world, [`isEmpty()`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#isEmpty--) tests the length.
