### ISSUE TITLE
Wrong URL mapping if namespace contains dot symbols

### ISSUE THREAD

**Issue by gtors** [grails/grails-core#10904]
Wrong URL mapping if namespace contains dot (`.`) symbols

Controller:
```
class ExampleController {
    static namespace = 'example.v1'
    static allowedMethods = [
            index: 'GET',
     ]
    def index() { respond [] }
}
```

Url mapping:
```
"/some/rest/resource" (resources: "example", namespace: "example.v1", include: ["index"])
```

When internal url-mapping is generated, then namespace truncated from `example.v1` to `v1`:
https://github.com/grails/grails-core/blob/master/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/mvc/AbstractGrailsControllerUrlMappings.groovy#L133
```
def namespace = hasUrlConverter ? urlConverter.toUrlElement( controller.namespace ) : controller.namespace
```

### Expected Behaviour

Namespace stay unchanged.

### Actual Behaviour

`grails.web.CamelCaseUrlConverter` truncates namespace up to `v1`

### Environment Information

- **Operating System**: Arch Linux
- **Grails Version:** 3.2.11 
- **JDK Version:** 1.8

**Comment by ilopmar** [comment]
@gtors I'm able to reproduce the issue debugging the application but I would like to know how this affects your application. 
Can you please provide me an example or even better create a simple grails app that reproduces the issue?

**Comment by gtors** [comment]
Sure. This is simplified illustration of my situation:

myorg.customer.CompanyController
```
package myorg.customer

class CompanyController {
      static namespace = 'customer.v1'
      // other code
}
```
and 

myorg.manager.CompanyController
```
package myorg.manager

class CompanyController {
      static namespace = 'manager.v1'
      // other code
}
```

UrlMapping:
```
"/v1/customers/$customerId/companies/" (resources: "company", namespace: "customer.v1")
"/v1/managers/$managerId/companies" (resources: "company", namespace: "manager.v1")
```

That solution works perfectly on 2.x, but after upgrading to 3.x all requests to "/v1/managers/.../companies" forwarded to customer controller (because in both cases  namespace truncated to `v1`). 

I was bypass it by replacing all `.`  to `_`, but for figure out what is going wrong I spent 2-days, and I don't want that somebody  will fall into the same trap.

**Comment by ilopmar** [comment]
Sorry for my quick reply, I've should have tried to reproduced first. I've created this sample project that reproduces the issue in Grails 3.3.2: https://github.com/grails-core-issues-forks/grails-issue-10904

**Comment by gtors** [comment]
As you can see (in your example project), if you request a `localhost:8080/some/rest/resourceV1` you will get `index - v2`,  but there should be `index - v1`
