### ISSUE TITLE
3.2.4 unable to resolve class for Holders.grailsApplication classes in runtime.groovy

### ISSUE THREAD

**Issue by anti43** [grails/grails-core#10919]
see 

https://github.com/grails/grails-core/issues/10131

the same applies for Holders with the extend that in application.groovy or runtime.groovy, Holders.grailsApplication is not available so I cannot find a way to set config properties with values related to the context path.

Now I try to find a way to get our deployment scenario (same webapp deployed on same server, but each has another datasource)

**Comment by benrhine** [comment]
Im not 100% clear on what your getting at as what your referring to is a bit different than [#10131](https://github.com/grails/grails-core/issues/10131). 10131 is dealing with application objects not being available in `application.groovy`, you can read more specifically on the differences between `application.groovy` and `runtime.groovy` [here](https://docs.grails.org/latest/guide/conf.html#config) in the doc.

What I think your saying is that your specific issue is that you cant access holders in `application.groovy`. As per the above linked documentation _"configuration values defined in application.groovy are available to the Grails CLI, which needs to be able to load application.groovy **before the application has been compiled**"_ Thus values in `Holders` will not be available at this point yet. `Holders` are for application configuration (ie. I need to reference a config value in a service), not so much deployment or system config.

If your looking to access system (application) properties, or environment variables for dynamic config in `runtime.groovy`, `application.groovy`, `application.yml` or even your `build.gradle` you can access environment variables using `System.getenv("MY_ENV_VAR")`  or `System.getProperty("testProperty")`. You can view the system properties in the `gradle.properties` file.  Here is a simple example that pulls in both system and environmental variables using all four of the above mentioned files and shows that `Holders` are not available until the app has started enough to run the `BootStrap.groovy`.

https://github.com/benrhine/gradleSystemAndEnvAccessExample

**Comment by anti43** [comment]
Hm I am unsure but I need is the context path. Maybe it's to tomcat specific. System properties are JVM wide, so they don't help here if I'm right. I need application properties where multiple applications are deployed in the same tomcat container

**Comment by jeffbrown** [comment]
> ...so I cannot find a way to set config properties with values related to the context path

I expect that if you articulate what you really want to accomplish that the solution almost certainly wouldn't require referencing `Holders` in `runtime.groovy` even if that were possible.  I suggest asking in Slack how to accomplish your goal and don't presume that `runtime.groovy` is part of the recommended solution.
