### ISSUE TITLE
Grails 3.3.2: Stylesheet has identical foreground and background colors

### ISSUE THREAD

**Issue by namgang** [grails/grails-core#10911]
As downloaded, Grails 3.3.2 stylesheets main.css and grails.css use identical colors for links and highlighted background in the index GSP view. Any links in the index view become invisible.

This is quite a minor issue, still an undesirable gotcha for newcomers.

### Steps to Reproduce

1. Download test app from https://github.com/namgang/grails332-stylesheet-issue
2. Build it with Grails 3.3.2, run it.
3. The app has two domains, Ping and Pong. At startup it populates the database with one Ping having a couple of Pongs. The initial view is an index view of Ping.

### Expected Behaviour

You see a list containing just one Ping having a number Pongs. Move your pointer there. Out of the box the contents should be readable regardless if the row is highlighted or not.

### Actual Behaviour

When you move the pointer there contents disappear because the font color is identical to the (highlight) background color.

### Environment Information

- **Operating System**: Ubuntu 16.04.3 LTS
- **Grails Version:** 3.3.2
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
- **Container Version (If Applicable):** n/a

### Example Application

https://github.com/namgang/grails332-stylesheet-issue

### Source pointers

In a fresh Grails 3.3.2 download the problem lines are:
./grails-app/assets/stylesheets/main.css lines 448..450
./grails-app/assets/stylesheets/grails.css lines 383..391

In my opinion the highlighting color is too garish. Something more washed-out like #FEE4B5 would do (main.css:449). Some contrasting colors (for grails.css:384,389) are #2B6E65 (green) or 9E7C3E (brown). But then someone is doing an overall color scheme I guess.

Sorry, haven't been able to locate the project of the sources...

**Comment by benrhine** [comment]
This has been fixed since Grails 3.3.3
