### ISSUE TITLE
Grails 3.3.2 create-profile command creates unusable profile

### ISSUE THREAD

**Issue by laujorpan** [grails/grails-core#10927]
Hello,

I'm having again issue https://github.com/grails/grails-core/issues/10736 but I'm in linux distribution with an OpenJDK and grails version 3.3.2

### Steps to Reproduce
1. Install Grails 3.3.2 via sdkman
2. grails create-profile "oneprofile"
3. cd "oneprofile"
4. ./gradlew clean assemble

### Expected Behaviour
Profile should be built to build/libs in the project folder

### Actual Behaviour
Gradle refuses to build the profile with the following output:

What went wrong:
A problem occurred evaluating root project 'oneprofile'.
> Failed to apply plugin [id 'org.grails.grails-profile']
   > Cannot add extension with name 'defaultArtifacts', as there is an extension already registered with that name.

### Environment Information
- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.3.2 (I've been testing with 3.3.0.RC1 too)
- **JDK Version:** openjdk version "1.8.0_151"
- **Container Version (If Applicable):** None

### Related issue:
https://github.com/grails/grails-core/issues/10736

If you need some extra info I'm glad to help you

Regards

**Comment by ilopmar** [comment]
I use Linux Mint 18.3 (which is based on Ubuntu) and I can't reproduce the issue:

```bash
ivan@nobita ~ $ cd /tmp
ivan@nobita /tmp $ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

ivan@nobita /tmp $ sdk default grails 3.3.2

Default grails version set to 3.3.2

ivan@nobita /tmp $ grails create-profile oneprofile
| Application created at /tmp/oneprofile

ivan@nobita /tmp $ cd oneprofile/

ivan@nobita /tmp/oneprofile $ ./gradlew clean assemble
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
:clean UP-TO-DATE
:compileProfile
:processResources
:jar
:assemble

BUILD SUCCESSFUL

Total time: 4.678 secs
ivan@nobita /tmp/oneprofile $ ls -l build/libs/
total 4
-rw-rw-r-- 1 ivan ivan 2101 Feb  7 18:15 oneprofile-1.0.0-SNAPSHOT.jar
```

As you can see everything is working as expected.

**Comment by laujorpan** [comment]
I tried again and I have the same error. This is my project:
https://github.com/laujorpan/oneprofile
I have a gradle installation out of the project (versionGradle 4.2), could it be a problem?

**Comment by ilopmar** [comment]
I've tried with your project and it also works. Officially Grails supports only Gradle 3.5 and that's the gradle wrapper version included in your project. As long as you use `./gradlew` and not `gradle` you should be fine. In any case you can try to:

```
$ sdk install gradle 3.5
```

And set the version as default.

**Comment by laujorpan** [comment]
Hi,

I found my problem now. Although I use gradle or ./gradlew, it takes my init.gradle configuration and, in my working laptop I have in allproject config an "apply plugin: maven" line, which is not a problem for Java Gradle projects but it is for grails plugins, I don't know why.

In my personal laptop it works and in my working laptop too, if I remove that line.

Sorry for the inconveniences. Should I close this issue or are your team who control it?

Thanks at all.

**Comment by ilopmar** [comment]
Glad you found it.
