### ISSUE TITLE
3.3.2: Scaffolding, German locale bug with double and float -> multiplies value by 10 upon saving

### ISSUE THREAD

**Issue by martinfrancois** [grails/grails-core#10923]
### Example Application

- https://github.com/martinfrancois/TestApp

### Steps to Reproduce

Use the provided example application and see `src/integration-test/groovy/testapp/FoodSpec.groovy` and run `grails test-app` to see the test fail. The steps are provided in the test.

### Expected Behaviour

When I edit an item and save it as is without changing anything, the values should all stay the same. In this case, the amount which was "100" should stay at "100".

### Actual Behaviour

When I edit an item with amount "100" and save it as is without changing anything, the amount is "1000" after saving.

### Further information

Scaffolding is being used.
The value is always multiplied by 10 when saving. It can even be done repeatedly.
This only happens with the locale "de". It does NOT happen with "de_CH" or "en" for whatever reason. Also, when pressing edit, the field "amount" includes a value of "100.0". If the value is changed to "100" before saving, this effect doesn't happen.
It does NOT happen with int, **only with double and float**.

### Environment Information

- **Operating System**: Windows 10 & macOS High Sierra
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.121

**Comment by ilopmar** [comment]
The bug was due to the fields plugin. I've submitted a PR so once it's merged and released a new version we can upgrade Grails to use that new version.
