### ISSUE TITLE
Compilation error when including a domain type in property accessor method signature for Grails 3.2.12

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#10931]
### Task List

- [*] Steps to reproduce provided
- [*] Stacktrace (if present) provided
- [*] Example that reproduces the problem uploaded to Github
- [*] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a test application using Grails 3.2.12
2. Create a domain class `User`
3. Create a service class `User` (to create `UserService.groovy`
4. Change the method signature of `def serviceMethod()` to `User getAUser()` in `UserService.groovy`
5. Run `grails compile`

### Expected Behaviour

The code compiles

### Actual Behaviour

The code fails to compile with the following exception 
([stacktrace.txt](https://github.com/grails/grails-core/files/1712584/stacktrace.txt)):
```
> BUG! exception in phase 'canonicalization' in source unit '/home/joe/code/sandbox-v3212/grails-app/services/sandbox/v3212/UserService.groovy' ClassNode#getTypeClass for sandbox.v3212.User is called before the type class is set
```

### Environment Information

- **Operating System**: Ubuntu 17.10
- **Grails Version:** 3.2.12
- **JDK Version:** 
```
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (Zulu 8.27.0.7-linux64) (build 1.8.0_162-b01)
OpenJDK 64-Bit Server VM (Zulu 8.27.0.7-linux64) (build 25.162-b01, mixed mode)
```
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/joemccall86/sandbox-v3212

### Observations:

* @jeffbrown observed that this only happens with property accessors. If we have the method left as `serviceMethod` the code compiles
* If the class is not marked as `@Transactional` the code compiles
* If the class is marked as `@Transactional` and the method is marked as `@NotTransactional` the code compiles

**Comment by joemccall86** [comment]
More observations:
This compiles:
```
import grails.transaction.Transactional

@Transactional
class UserService {

    User retrieveSomeProperty() {
    }
}
```

This does not:
```
import grails.transaction.Transactional

@Transactional
class UserService {

    User getFirstUser() {
    }
}
```

**Comment by joemccall86** [comment]
It may have been introduced with https://github.com/grails/grails-core/commit/8364fb21e0d5a5e15b16d4fce31e0f27cd1d5e46.

The workaround could be to rename the affected method or (like in our case) mark it as `@NotTransactional` if it doesn't need to be transactional.

**Comment by joemccall86** [comment]
Forgive me, but this only appears to work around the issue. The 3.2.x series is still supported and this bug will still exist out of the box. I hope this can be addressed in a 3.2.13 release before it is closed.

**Comment by jameskleeh** [comment]
@joemccall86 I have a fix in place

**Comment by puneetbehl** [comment]
There will no 3.2.x release. I believe the change should already be in Grails 3.3.14.
