### ISSUE TITLE
Fix instructions for setting up a Grails project in IntelliJ

### ISSUE THREAD

**Issue by donalmurtagh** [grails/grails-core#10945]
In section 2.6 of the docs, the instructions for adding a Grails project to IntelliJ say:

> To get started with Intellij IDEA and Grails 3.0 simply go to File / Import Project and point IDEA at your build.gradle file to import and configure the project.

However, in the current version of IntelliJ there is no "Import Project" item in the File menu. IMO, it would be more useful to provide instructions on how to add a Grails app as a new module to an IntelliJ project.

**Comment by jameskleeh** [comment]
For future reference, this should be filed in https://github.com/grails/grails-doc.

**Comment by donalmurtagh** [comment]
@jameskleeh thanks, should I close this issue and open it in the other repo instead?
