### ISSUE TITLE
replaced config values are not honored @ runtime in domain unit tests

### ISSUE THREAD

**Issue by kszymko** [grails/grails-core#10967]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Replaced config values **are not honored** during data binding. 
Instead values from config **(application.yml)** are used altough **given&expect** passes.

1. Create domain class:

```
package com.sandbox

class Processing {

    String name

}
```

2. Add config to `application.yml`:

```
 grails:
    databinding:
        convertEmptyStringsToNull: true
        trimStrings: true
```

3. Write tests:

```
class ProcessingSpec extends Specification implements DomainUnitTest<Processing> {

    @Unroll('create Processing with name: [#name]')
    void 'should preserve original data while data binding'() {
        given: 'convertEmptyStringsToNull is set to false'
            config.grails.databinding.convertEmptyStringsToNull = false
            config.grails.databinding.trimStrings = false

        expect: 'convertEmptyStringsToNull is set to false'
            config.grails.databinding.convertEmptyStringsToNull == false
            config.grails.databinding.trimStrings == false

        when:
            Map properties = [name: name]
            Processing pd = new Processing(properties)

        then:
            pd != null
            pd.name == expected

        where:
            name     || expected
            null     || null
            ''       || ''     // empty string
            '    '   || '    ' // blank string
            'test'   || 'test'
    }

}
```

4. Run unit tests:

gradle test

### Expected Behaviour

All tests should pass using values from overriden config entries 

### Actual Behaviour

```
com.sandbox.ProcessingSpec > create Processing with name: [null] PASSED

com.sandbox.ProcessingSpec > create Processing with name: [] FAILED
    Condition not satisfied:

    pd.name == expected
    |  |    |  |
    |  null |  ""
    |       false
    com.sandbox.Processing : (unsaved)
        at com.sandbox.ProcessingSpec.should preserve original data while data binding(ProcessingSpec.groovy:32)

com.sandbox.ProcessingSpec > create Processing with name: [    ] FAILED
    Condition not satisfied:

    pd.name == expected
    |  |    |  |
    |  null |
    |       false
    com.sandbox.Processing : (unsaved)
        at com.sandbox.ProcessingSpec.should preserve original data while data binding(ProcessingSpec.groovy:32)

com.sandbox.ProcessingSpec > create Processing with name: [test] PASSED
```

### Environment Information

- **Operating System**: Win x64
- **Grails Version:** 3.3.3
- **JDK Version:** 1.8.0_162

**Comment by jeffbrown** [comment]
I don't think this is a bug.  You are changing the config values after the corresponding bean has been initialized so changing the config value has no effect.

The project at https://github.com/jeffbrown/issue10967 shows how you can override config in a unit test.

https://github.com/jeffbrown/issue10967/blob/master/src/test/groovy/com/sandbox/ProcessingSpec.groovy

```groovy
package com.sandbox

import grails.testing.gorm.DomainUnitTest
import spock.lang.Specification
import spock.lang.Unroll

class ProcessingSpec extends Specification implements DomainUnitTest<Processing> {

    Closure doWithConfig() {{ config ->
        config.grails.databinding.convertEmptyStringsToNull = false
        config.grails.databinding.trimStrings = false
    }}

    @Unroll('create Processing with name: [#name]')
    void 'should preserve original data while data binding'() {
        when:
        Map properties = [name: name]
        Processing pd = new Processing(properties)

        then:
        pd != null
        pd.name == expected

        where:
        name     || expected
        null     || null
        ''       || ''     // empty string
        '    '   || '    ' // blank string
        'test'   || 'test'
    }
}
```

The "Manipulating Configuration" section at https://testing.grails.org/latest/guide/index.html describes the `doWithConfig` method.

This test is dubious as it doesn't really test anything other than the framework, but the above shows how to carry out the test you represented in the bug report.

**Comment by kszymko** [comment]
Jeff,

you are right it is not a bug then - I just thought that setting config values 

`config.grails.databinding.convertEmptyStringsToNull = false`

**inside** the test was the right way to override configuration.

Thanks for pointing to the relevant part of the documentation.
