### ISSUE TITLE
Configuration got overridden by environment variables after updating to 3.3.3

### ISSUE THREAD

**Issue by jjballano** [grails/grails-core#10976]
Hi,

According to https://github.com/grails/grails-core/pull/10937/commits/65f7bc6b82103841106a52bb9d35947d2d19662d if I have a environment variable with same name as the configuration param, it will take the environment variable instead of the one configured in application.yml.

I have an environment variable called "username" with one value and I have rabbitmq plugin which also have a config property called username with a different value. I don't want to environment variable override the rabbitmq configuration.

Is there any workaround to this not happing anymore? I mean, some configuration properties such us username, password, host, etc could be defined in many plugins/database/whatever with different values and it is also possible to have some environment variables with same names.

Thanks!

**Comment by jeffbrown** [comment]
I don't think this is a bug and I think https://grails-community.slack.com is a better forum for asking questions.

**Comment by jjballano** [comment]
I've created an issue because I think it's a breaking change in a minor version update and you might not thought in this problem when you have changed the code.

Anyway, if you think you have nothing to do with it, I can close the issue.

**Comment by jeffbrown** [comment]
> Anyway, if you think you have nothing to do with it, I can close the issue.

I don't think that I have nothing to do with it.  I didn't mean to suggest that.  I was pointing out 2 things...

1.) I don't think this is a bug
2.) Our Slack is a better forum for asking questions

Sorry for the confusion.

**Comment by jjballano** [comment]
Sorry, I could sound rude but that wasn't what I want (I'm better writing Grails than English ;) ).
I'll ask in Slack then.
