### ISSUE TITLE
Dirty detection in relationships

### ISSUE THREAD

**Issue by mangelo123** [grails/grails-core#10977]
I've upgraded my application from Grails 3.1.8 to 3.3.3. I've just noticed that edits done on individual 'hasMany' related entities are not being persisted. I went back and tested the 3.1.8 version and it works as expected. 

Any simple change to a related 1->M entity is not being saved to the database. isDirty() reports false.

I've also tried parent.markDirty('children') and this did not work.

**Comment by mangelo123** [comment]
I should clarify.  Here is example code that is making a change to a related collection:

```
def match = wo.projects[0].projectOtherResourceExpenses.find { orig ->
                            orig.id == data.id.toLong()
}
if (match) {
    match.copyFrom(data)
}
.
.
.
wo.save(flush: true)
```

This code worked in grails 3.1.8. With 3.3.3, no sql update is generated.

**Comment by jameskleeh** [comment]
@mangelo123 You will need to upload an example project that demonstrates the issue. What you have reported thus far isn't enough to get started

**Comment by mangelo123** [comment]
Creating an example project is not practical. I am showing the exact code snippet that worked in 3.1.8 and stopped working in 3.3.3

**Comment by jameskleeh** [comment]
@mangelo123 Without something to debug, I'm afraid there is nothing we can do

**Comment by mangelo123** [comment]
I will try to create an example project using derby.

**Comment by mangelo123** [comment]
I could not get an example application to behave the same way. I know not much can be done for this issue without an example, but here is a snippet of code from our system and the 'fix'. I did not have to add this line using Grails 3.1.8:

```
                if (params.edit) {
                    def match = wo.milestones?.find { orig ->
                        orig.id == params.id.toLong()
                    }
                    if (match) {
                        match.copyFrom(data)

                        // Did not have to call this for Grails 3.1.8. If we had lists vs sets for relationships,
                        // this could possibly duplicate the entity. 
                        wo.addToMilestones(match)
                    }
                }
                else {
                    def ms = new Milestone()
                    ms.copyFrom(data)
                    wo.addToMilestones(ms)
                }

```

**Comment by demon101** [comment]
@mangelo123 as workaroud try to disable new dirty checking by
> hibernate:
>    hibernateDirtyChecking: true
