### ISSUE TITLE
GSP StreamCharBuffer ConcurrentModificationException

### ISSUE THREAD

**Issue by okoskine** [grails/grails-core#10996]
We ran into a reproducible ConcurrentModificationException with GSP rendering when migrating a Grails 1.3 project to Grails 3.3. The issue is present only in certain rendering flows but the root problem is not clear. Here is a minimal patch on top of a clean Grails 3.3.5 application that demonstrates the problem: [0001-Bug.patch.txt](https://github.com/grails/grails-core/files/1942690/0001-Bug.patch.txt) or you can clone the same application from github.

### Steps to Reproduce

1. grails create-app gspbugtest
2. cd gspbugtest
3. patch -p1 < 0001-Bug.patch.txt
4. grails run
5. load http://localhost:8080/bugtest/index

### Expected Behaviour

The page should load successfully every time and show "Hello, world".

### Actual Behaviour

About half the time it loads successfully and half the time a ConcurrentModificationException occurs.
Stack trace: [stacktrace.txt](https://github.com/grails/grails-core/files/1942727/stacktrace.txt)

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.3.5
- **JDK Version:** 1.8.0_161

### Example Application
- https://github.com/okoskine/gsp-concurrency-issue

**Comment by lhotari** [comment]
@okoskine Thanks for the accurate issue report and repro app.

**Comment by lhotari** [comment]
I created a simple fix. Creating an unit test that reproduces the issue is more work and should be part of a complete fix.

**Comment by okoskine** [comment]
Thanks for the quick response. This fixed our issues.
