### ISSUE TITLE
Grails 3.3.5 integration tests are not working, facing org.hibernate cannot create session exception

### ISSUE THREAD

**Issue by Kadambari87** [grails/grails-core#10999]
As per discussion in 10959, I upgraded to grails 3.3.5. However, I am still unable to run integration test cases. I get the below error: 

Caused by:
        org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.core.feed.service]: Constructor threw exception; nested exception is org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread

1. Use gradle wrapper version 4.6 and grails version 3.3.5
2. Create integration test cases as guided by https://docs.grails.org/latest/guide/testing.html#integrationTesting
3. Also, mark testcases as @Transactional (grails.gorm.transactions.Transactional).

Test case should have run successfully, however, it doesn't. Throws the above exception.

Operating System: Windows 7 (64 Bit)
Grails Version:3.3.5
Groovy Version:2.4
Gradle Wrapper Version: 4.6

Command to run test cases - gradlew -Dgrails.env=test integrationTest

Below is a sample integration test I created:

@Slf4j
@Integration(applicationClass = Application.class)
@Rollback
class X extends class Y {
def setupSpec() {  // code to read data from excel }

def cleanupSpec() {
//		close open instances
}
@Transactional
	def "Integration Test Case Method 1"() {
}

}

Please let me know if I'm missing something or if this is a grails issue?

**Comment by benrhine** [comment]
Unfortunately I am unable to reproduce this issue. I spent time with the app you reference from #10959 and while running that app as a grails 3.3.3 does produce an error (not the error you describe [Also this error occurred when using 3.3.4]), the error is corrected by upgrading to grails 3.3.5 and runs integration tests fine using a gradle wrapper of version 4.6. To make sure I was not getting a false positive I created a simple example app along the same lines as the one in the aforementioned issue and you can take a look at it [here.](https://github.com/benrhine/threeThreeFiveIntTests) Following is the process I used to create the linked app and upgrade it to use a gradle wrapper of version 4.6.

From local install of grails 3.3.5 (or use the grails forge) `grails create-app NAME` and create 3 integration specs.

- A base integration test created by `grails create-integration-test DefaultTest`
- A integration test using Gorm Rollback `grails create-integration-test GormRollbackTest`
- Integration test exactly as described in ticket

All 3 test variants pass without issue when using the default gradle wrapper of 3.5
Tried both
- ./gradlew integrationTest
- ./gradlew -Dgrails.env=test integrationTest

Upgrade gradle wrapper to 4.6

- update gradle.properties to gradleWrapperVersion=4.6
- execute `./gradlew wrapper --gradle-version 4.6`

All 3 test variants pass without issue when using the upgraded gradle wrapper of 4.6
Tried both
- ./gradlew integrationTest
- ./gradlew -Dgrails.env=test integrationTest

As a side note you should not need to use `@Transaction` inside in integration test as integration test are transactional by default. Refer to the doc [here](https://docs.grails.org/latest/guide/testing.html#integrationTesting) Section 15.2 Under the heading of "Transactions".
