### ISSUE TITLE
Object stored into request in interceptor is not present in controller

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#10998]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Store any arbitrary object into `request` in interceptor.
2. Load this object in controller.

### Expected Behaviour

The object should be stored in request object. This was working with Grails 3.3.2.

### Actual Behaviour

The object is not present.

### Environment Information

- **Operating System**: OsX
- **Grails Version:** 3.3.5
- **JDK Version:** 1.8

### Example Application

https://github.com/kuceram/grails-request-store-error

**Comment by puneetbehl** [comment]
Yes, for the interceptor with a namespace matcher. The namespace information should be present in the request. So, in this case, the interceptor will only match namespaced URLs. For example, if you have following URL Mappings:
```
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/$namespace/$controller/$action?"()
``` 
And, the interceptor with the following match rule:
```
MyInterceptor() {
     match(namespace: 'space')
}
```

It will only match request coming from `/space/my/index` and will NOT be called for the request `/my/index`.

**Comment by kuceram** [comment]
Well, the example I've shared (https://github.com/kuceram/grails-request-store-error/blob/master/grails-app/controllers/store/request/UrlMappings.groovy) shows something else. There is URL Mapping:
```
static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        ...

        "/test"(controller: 'my', namespace: 'space', action: 'index', method: 'GET')
    }
```
And interceptor with:
```
MyInterceptor() {
    match(namespace: 'space')
}
```

Which, according to my understanding, should match but in reality doesn't. Also, it was working for previous Grails version of 3.3.2. So apparently it's a bug.

**Comment by puneetbehl** [comment]
@kuceram Do you mean it does not work when you hit `/test` endpoint?

**Comment by kuceram** [comment]
yep

**Comment by puneetbehl** [comment]
I am sorry but I am little confused as I can see that interceptor `MyInterceptor` does execute when you hit http://localhost:8080/test

<img width="628" alt="screen shot 2018-05-29 at 12 43 52 pm" src="https://user-images.githubusercontent.com/2108607/40643607-53053f1e-633e-11e8-8dff-dc45ac6d7579.png">

**Comment by kuceram** [comment]
I see, I've updated my demo. Could you check it again. It seems that what doesn't work is the exclude part:

```
        // this row breaks the call of GET http://localhost:8080/test
        match(namespace: 'space', controller: 'myNext').excludes(namespace: 'space', controller: 'myNext', action: 'index')
        match(namespace: 'space', controller: 'my', action: 'index')
```

![screen shot 2018-05-29 at 16 24 08](https://user-images.githubusercontent.com/1298671/40665173-deb3e79a-635c-11e8-9b9b-3f2dc39e8783.png)


I'd like to also mention that this bug appears in our production app after I upgrade to Grails 3.3.5. So it's obvious that something has changed in grails...

**Comment by puneetbehl** [comment]
@kuceram please check now
