### ISSUE TITLE
Wrong Location header from RestfulController POST

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#10995]
When you POST a new REST resource, the endpoint returns a Location header, but the value of the header is wrong:
```http://localhost:8080/foo/show/1```
should be:
```http://localhost:8080/foo/1```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Check out sample project:
https://github.com/rmorrise/location-test
2. Run the app locally
3. POST a new record:
```
POST http://localhost:8080/foo
Content-Type application/json
{
	"bar": "baz"
}
```

### Expected Behaviour

```Location →http://localhost:8080/foo/1```

### Actual Behaviour

```Location →http://localhost:8080/foo/show/1```

### Environment Information

- **Operating System**: Win7 x64
- **Grails Version:** 3.3.4
- **JDK Version:** 1.8.0_66

### Example Application

- [https://github.com/rmorrise/location-test]

**Comment by ilopmar** [comment]
Finally, as the behavior was broken we decided to fix this in `3.3.x` branch.
