### ISSUE TITLE
grailsw -version lists Groovy v2.4.7, expected 2.4.15

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11018]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. install Grails
```
$ sdk install grails 3.3.5
```
2. verify Grails `-version`
```
$ grails -version
| Grails Version: 3.3.5
| Groovy Version: 2.4.15
| JVM Version: 1.8.0_141
```
3. create plugin
```
$ grails create-plugin my-plugin --profile=plugin
$ cd my-plugin
```
4. verify Grails wrapper `-version`
``` 
my-plugin$ ./grailsw -version
| Grails Version: 3.3.5
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_141
```
Note: `dependency-report` for both `grails` and `grailsw` lists Groovy v2.4.15 as expected - I suspect this is a cosmetic bug :-)

### Expected Behaviour

Output from `-version` flag expected to match across `grails` and `grailsw`.

### Actual Behaviour

The Grails `-version` output, specifically the Groovy version is different for `grails` vs. `grailsw` (wrapper).

### Environment Information

- **Operating System**: Ubuntu 16.04.4 LTS (Linux 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
- **Grails Version:** 3.3.5
- **JDK Version:** java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by dlehammer** [comment]
Symptom also present in Grails v3.3.6, v3.3.7 & v3.3.8.

**Comment by graemerocher** [comment]
I think the Groovy version listed should just be removed.. it is confusing for the user and is not indicative of the Groovy version used in the running application

**Comment by ilopmar** [comment]
Ok, I'll remove it.

**Comment by dlehammer** [comment]
@graemerocher I'm curious - why not delegate to the Grails executable the wrapper is wrapping?

**Comment by jameskleeh** [comment]
@dlehammer It is delegating

**Comment by jameskleeh** [comment]
@dlehammer That isn't true. Every command gets delegated to the normal grails cli. The difference is because the JVM is started with a different environment ,the groovy dependency included with the normal CLI is not overriding the one provided by the wrapper.

Graeme is suggesting to remove it because it doesn't provide any useful information. Back in the days where the Groovy version was fixed for a particular version of Grails it made sense. Now that you can use a different version of Groovy, the one output by the CLI doesn't necessarily match the one used by your application. No one cares what version is used by the CLI

**Comment by dlehammer** [comment]
> Every command gets delegated to the normal grails cli.

@jameskleeh if the `-version` command was delegated - would it then reflect the actual Grails environment?

(Something along those lines was fix I had expected - not the introduction of more inconsistent output from the (wrapped) CLI)

**Comment by dlehammer** [comment]
@jameskleeh I'm curious, does the change in #11110 affect both the wrapped and unwrapped invocation of Grails `-version` ?

If that's the case I stand corrected, and applaud your effort :)

**Comment by jameskleeh** [comment]
@dlehammer Yes, the wrapper delegates all functionality to the real CLI so this change affects both.
