### ISSUE TITLE
gormVersion=6.1.10.BUILD-SNAPSHOT in gradle.properties

### ISSUE THREAD

**Issue by mano3567** [grails/grails-core#11033]
### Steps to Reproduce

1. grails create-app someappname
2. cat someappname/gradle.properties
3. note the generated gomrVersion

### Expected Behaviour
I expected i release-version of gorm

### Actual Behaviour

my gradle.properties contains:
grailsVersion=3.3.6
gormVersion=6.1.10.BUILD-SNAPSHOT
gradleWrapperVersion=3.5

### Environment Information

- **Operating System**: ubuntu 18:04
- **Grails Version:** 3.3.6
- **JDK Version:** 1.8.0_172
- **Container Version (If Applicable):** TODO

**Comment by sdelamo** [comment]
@mano3567 Thanks for reporting. 3.3.6 accidentically sets 6.1.10.BUILD-SNAPSHOT as GORM version. When it should have set 6.1.10.RELEASE

 You can manually set 6.1.10.RELEASE by modifying gradle.properties

**Comment by ilopmar** [comment]
I'll keep it open until we release 3.3.7 with the fix.

**Comment by ilopmar** [comment]
Gorm version updated in https://github.com/grails/grails-core/commit/b3209d957f8b55760d95b40763f7471d68da12f2
