### ISSUE TITLE
Custom Datasource not injected to GORM or Hibernate Session Factory 

### ISSUE THREAD

**Issue by ravikovour** [grails/grails-core#11039]
We have a requirement to create a custom datasource instead of specifying datasource details in application.grooy So that we can get custom database connection and set some custom properties.

Eg:
```
import javax.sql.DataSource
import java.sql.Connection
import java.sql.SQLException
public class CustomDataSource implements DataSource {
               public Connection getConnection() throws SQLException {
               }
               public Connection getConnection(String username, String password) throws SQLException {
               }
}
```

In Grails-2.5.0 this used to work by specifying bean with name 'dataSource'
Eg: `dataSource(CustomDataSource)`
This is not working in Grails-3.3.2 and GORM-6.1.8.Release. 
It always looks for the dataSource properties specified in grails-app/conf/application.groovy

### Steps to Reproduce
create a grails app 
create a custom data source and custom connection classes
create a bean dataSource(CustomDataSource)

### Expected Behaviour
Grails Runtime should able to inject the custom dataSource and this custom dataSource and custom connection life cycle methods should be called similar to Grails-2.5.0.
So that no need to specify datasource properties in application.groovy 

This custom datasource should be used in GORM initialization 
When sessionFactory is injected in Grails service – in the code sessionFactory.getSession().getConnection() should execute CustomDataSource.getConnection and return connection
GORM Api calls should get the connection from this custom datasource
Eg: domain.findAll() 
It should work for GORM doamins and JPA entities
### Actual Behaviour
Currently it creates datasource with properties specified in application.groovy
if dataSource part is removed it fails.
The custom datasource and custom connection life cycle methods are not getting called
### Environment Information
Grails : 3.3.2
GORM : 6.1.8.RELEASE
Hibernate:5.1.5 FINAL
JDK:1.8

### Example Application

Attached sample code
https://github.com/ravikovour/grails-3-issues/tree/master/custom_datasource_issue

**Comment by ilopmar** [comment]
@ravikovour Please for the future keep in mind to provide full sample applications that help to reproduce the issue. Currently you're pointing to a repo with different sample applications that are not complete and doesn't work, so we need to build a sample app based on the files you provide in the repo.
Thanks for your cooperation :)

**Comment by ilopmar** [comment]
Also please provide a sample application that uses H2 database instead of Oracle.

**Comment by ravikovour** [comment]
Added sample application. Hope this will help. 
https://github.com/ravikovour/grails-3-issues/tree/master/custom_datasource_issue/Sample-Application
I feel the way it has to used changed in grails-3.

**Comment by jameskleeh** [comment]
For reference, this can be accomplished by creating a `dataSourceConnectionSourceFactory` bean of type `org.grails.datastore.gorm.jdbc.connections.DataSourceConnectionSourceFactory`

**Comment by gstroup** [comment]
@jameskleeh Do you have any examples on how to create and use a `dataSourceConnectionSourceFactory` ?
We were using multiple datasources in a grails 2 app, but after upgrading to grails 4, we can't get it working.  We've extended the `AbstractRoutingDataSource` but it seems like our routing data source is not being used.  We always get the default datasource.
