### ISSUE TITLE
Externalizing logback.groovy will not work in some cases with gradle bootRun

### ISSUE THREAD

**Issue by ravikovour** [grails/grails-core#11041]
Externalizing logback.groovy not working with the following command as suggested in the Grails documentsion for bootRun
http://docs.grails.org/3.3.2/guide/single.html#externalLoggingConfiguration 
   
gradlew -Dlogging.config=/Users/me/config/logback.groovy bootRun

### Steps to Reproduce

1.	Create a app in grails 3
2.	Add one controller and few log message inside the controller.
3.	Enable the logging for the controller in logback.groovy
4.	Run the app and ensure the log message is getting printed when we access the controller.
5.	Then move the logback.groovy outside of the project folder. 
6.	Then pass as runtime argument as given in this link and  execute the bootRun. 

http://docs.grails.org/3.3.2/guide/single.html#externalLoggingConfiguration    
gradlew -Dlogging.config=/Users/me/config/logback.groovy bootRun

7. bootRun is not considering the external  logback.groovy and log will not happen. 
8. Try setting as environment variable, is not working.
9.  grails run-app with -Dlogging.config=/Users/me/config/logback.groovy is not working

This works fine in following cases:
1) If we specify the external path in grails-app/conf/application.groovy 
logging.config="/Users/me/config/logback.groovy " 
2) When we add the below highlighted line change in the build.gradle 
bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    **systemProperties = System.properties**
    addResources = true
}

Then -Dlogging.config=C:/externallog/custom_logback.groovy bootRun 
works fine

### Environment Information
Grails - 3.3.2
Java - 1.8

**Comment by graemerocher** [comment]
By using ` -Dlogging.config` you are passing system properties to the Gradle build but not to the JVM that runs the application. If you want this behaviour then doing `systemProperties = System.properties` is correct
