### ISSUE TITLE
NavigableMapConfig.getProperty does not resolve environmental variables

### ISSUE THREAD

**Issue by ddelponte** [grails/grails-core#11042]
Calling `getProperty` on a config object is not resolving injected environmental variables the same as Groovy's dot notation.

For example:
**application.yml**
```
myApp:
    value: '${PID ?: foo}'
```

**ReadConfigService.groovy**
```
class ReadConfigService implements GrailsConfigurationAware {

    String value1
    String value2

    @Override
    @CompileDynamic
    void setConfiguration(Config co) {
        value1 = co.getProperty('myApp.value') // ${PID ?: foo} is not evaluated properly
        value2 = co.myApp.value
    }

    def serviceMethod() {

        log.info "value1 = $value1"
        log.info "value2 = $value2"

        assert value1 == value2

        log.info 'service method called'
    }
}
```

### Steps to Reproduce

1. Run the sample app linked to above.  It will fail on startup.

Expected Behavior
===
Both property values are equal, regardless of where `SpringSecurityUtils.loadSecondaryConfig` is called in the application lifecycle (Please see `SecondaryConfigLoader` for implementation details). 

I expect the application runs without any error because config values are the same rather loaded via groovy dot notation or` getProperty()`

Actual Behavior
===
The assertion fails inside the `ReadConfigService` method because `getProperty()` does not evaluate myApp.value properly:
```
org.codehaus.groovy.runtime.powerassert.PowerAssertionError: assert value1 == value2
       |         |
       |         foo
       ${MY_APP_VALUE:foo}
```

This can be tracked down to calling `SpringSecurityUtils.loadSecondaryConfig` inside `doWithApplicationContext`. Commenting out that line makes the assertion pass.

### Environment Information

- **Operating System**: macOS 10.13.5
- **Grails Version:** 3.3.6
- **JDK Version:** 1.8.0_171-b11
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/ddelponte/grails-spring-security-core-issue492

### Related issues
- https://github.com/grails-plugins/grails-spring-security-core/issues/492
- https://github.com/bluesliverx/grails-spring-security-oauth2-provider/issues/138

**Comment by ddelponte** [comment]
# Possible Solution

The existing code in [`NavigableMapConfig.getProperty(String key, Class<T> targetType, T defaultValue)`](https://github.com/grails/grails-core/blob/3.3.x/grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java#L210):

```
    @Override
    public <T> T getProperty(String key, Class<T> targetType, T defaultValue) {
        Object value = findInSystemEnvironment(key);
        if (value == null) {
            value = configMap.get(key);
        }

        return convertValueIfNecessary(value, targetType, defaultValue);
    }
```

should be:

```
    @Override
    public <T> T getProperty(String key, Class<T> targetType, T defaultValue) {
        Object value = findInSystemEnvironment(key);
        if (value == null) {
            value = configMap.getProperty(key.toString());
        }

        return convertValueIfNecessary(value, targetType, defaultValue);
    }
```

**Comment by ilopmar** [comment]
Dean, for Grails 3.3.3 I fixed something related to this, take a look at this PR: https://github.com/grails/grails-core/pull/10942/files

**Comment by graemerocher** [comment]
NOTE: the dot notation is largely deprecated and all usages of it should be removed

**Comment by ddelponte** [comment]
A PR has been created at #11325

**Comment by joemccall86** [comment]
I believe this is resolved. I tested the sample application attached to https://github.com/bluesliverx/grails-spring-security-oauth2-provider/issues/138 with Grails 4.0.11 and things worked properly.

**Comment by puneetbehl** [comment]
Thank you @joemccall86 for verifying this.
