### ISSUE TITLE
Upgrade to Spring Boot 1.5.15.RELEASE

### ISSUE THREAD

**Issue by ilopmar** [grails/grails-core#11043]
Upgrade to Spring Boot 1.5.15.RELEASE

**Comment by ilopmar** [comment]
Spring Boot `1.5.15` hasn't been released yet

**Comment by donbeave** [comment]
Spring Boot 1.5.15 already released: https://github.com/spring-projects/spring-boot/releases/tag/v1.5.15.RELEASE
