### ISSUE TITLE
Command defaultNullable() ignored from parent during importFrom  (3.3.6)

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11059]
Symptom discovered during migration of web-application from Grails v2.4.4 to v3.3.5, symptom still present in Grails v3.3.6.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. checkout [example application](https://github.com/dlehammer/grails3-default-nullable-command-inheritance).
2. 
```
def-nul-web-app$ ./grailsw run-app
```
3. Open browser http://localhost:8080/ohMy/showSymptom?enumVal=VAL_2
4. Open http://localhost:8080/ohMy/noSymptom

This should result in something like this
![screenshot from 2018-08-06 19-07-52](https://user-images.githubusercontent.com/17439718/43763577-5e816e5c-9a2b-11e8-90ca-3acc8278aed0.png)

### Expected Behaviour

`ChildSymptomCommand` is expected to respect `ParentCommand.defaultNullable()` during `importFrom`.
This worked in Grails 2.

### Actual Behaviour

`ChildSymptomCommand` enables null-constraint on `ParentCommand` fields during `importFrom`, regardless of `ParentCommand.defaultNullable()` or `ChildSymptomCommand.defaultNullable()` or both are overridden.

Screenshot 1 from debugger during `org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.evaluate(...)` where `defaultNullable` is `true` for `ChildSymptomCommand` (as expected).
![screenshot from 2018-08-06 19-13-36](https://user-images.githubusercontent.com/17439718/43763945-66d901d6-9a2c-11e8-9647-a812baa6f86d.png)

Screenshot 2 from debugger during `org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.evaluate(...)` where `defaultNullable` is `false` for `ParentCommand` (unexpected). Notice also that evaluation contradicts the method argument.
![screenshot from 2018-08-06 19-13-57](https://user-images.githubusercontent.com/17439718/43763947-68ac0972-9a2c-11e8-9285-9b006e349b82.png)

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.3.6
- **JDK Version:** OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)

### Example Application
I've attempted to create a web-app closely resembling the web-app where the symptom was discovered. 
- https://github.com/dlehammer/grails3-default-nullable-command-inheritance

**Comment by jameskleeh** [comment]
@dlehammer The `importFrom` has no knowledge of the `defaultNullable` static method because that is something specific to `Validateable`. It doesn't make sense to execute `importFrom` in this case at all because the child command extends the parent.

Does your use case involve calling `importFrom` in a class that doesn't extend the one being imported?
