### ISSUE TITLE
bindData behavior has been changed in grails 3.3

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#11054]
After upgrate to grails 3.3.6 bindData stop copying of Domain fields with another Domains types. String fields copying as before. Same code works well with grails 3.2.11  

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create domain structure with one-to-one relation (SomeCompany domain has fields String name and Address address)
2. Create command with same fields inside (String name and Address address)
3. bindDate(command, entity)

### Expected Behaviour

fields in command contain same values with entity

### Actual Behaviour

address field is empty

### Environment Information

- **Grails Version:** 3.3.6
- **JDK Version:** 8
- **Container Version (If Applicable):** TODO

### Example Application

[testB.zip](https://github.com/grails/grails-core/files/2253682/testB.zip)

**Comment by jeffbrown** [comment]
This behavior is related to the way that keys are managed in `LazyBeanMap` which looks like it probably needs improvement.

In your particular case, replacing `bindData(command, cc)` with `bindData(command, cc.properties)` should yield the desired behavior.

**Comment by demon101** [comment]
As one time hot fix the solution is useful. But I hope the bug can be fixed in coming releases. I don't want to fix all projects and plugins code

I'm not sure about my time,  next days I will be accupied with testing and fixing another minor upgrading issues. I still has many failed integration tests

Can I hope that the Grails team will fix this problem in grails 3.3.7? I would be very grateful.

**Comment by jeffbrown** [comment]
For the benefit of whoever has some time to look into a fix...

A breakpoint at https://github.com/grails/grails-core/blob/fe933d400b3a0f5fe2184fdb1c83ac30d19562bb/grails-databinding/src/main/groovy/grails/databinding/SimpleDataBinder.groovy#L214 will demonstrate that "address" is not in the keys and as such won't participate in data binding.  The keys are coming from the `SimpleMapDataBindingSource` created at https://github.com/grails/grails-core/blob/fe933d400b3a0f5fe2184fdb1c83ac30d19562bb/grails-web-databinding/src/main/groovy/org/grails/web/databinding/bindingsource/DefaultDataBindingSourceCreator.groovy#L55.

**Comment by jameskleeh** [comment]
@jeffbrown @demon101 I think marking this as #wontfix is the right choice here. The data binding code doesn't currently have a dependency on `grails-datastore-gorm` to check if the source is an instance of `GormEntity`. The mapping context could be used to search for an entity for the source object, however that would require a breaking change to the `DefaultDataBindingSourceCreator` to require that to be passed via the constructor since the class is not currently registered as a bean.

This can be solved simply with a user defined bean registered in the user's application.

```
@CompileStatic
class DomainBindingSourceCreator extends DefaultDataBindingSourceCreator {

    @Override
    DataBindingSource createDataBindingSource(MimeType mimeType, Class bindingTargetType, Object bindingSource) throws DataBindingSourceCreationException {
        if (bindingSource instanceof GormEntity) {
            new SimpleMapDataBindingSource(bindingSource.properties)
        } else {
            super.createDataBindingSource(mimeType, bindingTargetType, bindingSource)
        }
    }
}
```

I think this particular use case is not very common and the changes required to support it are not worth the benefit, especially given that it is solvable for the user without changes to core.

Let me know your thoughts

**Comment by demon101** [comment]
@jameskleeh for me, the bug looks like big regression: GormEntity is a main artifact in grails app. Without GormEntity support bindData become useless (IMHO). 
I hope, the dependency problem can be solved by inversion of control and groovy language power =)

Please, don't mark the issue as wontfix.

**Comment by demon101** [comment]
@jameskleeh @jeffbrown Could you, please, reopen the issue, I will fix it by my own.

**Comment by jameskleeh** [comment]
@demon101 If you can find a way to allow this behavior without adding additional dependencies to GORM, or introduce any breaking change, you're welcome to submit a PR

**Comment by demon101** [comment]
@jameskleeh is it a good idea to put custom DataBindingSourceCreator to  grails-plugin-domain-class plugin and check  **bindingSource instanceof DomainClass** instead of **bindingSource instanceof GormEntity** ? As I can see, this plugin created as a putty between grails and gorm, is it?

**Comment by jameskleeh** [comment]
@demon101 The `grails-plugin-domain-class` doesn't have a dependency on `grails-web-databinding`, so that isn't possible.

**Comment by demon101** [comment]
After few minutes of debugging, I found the root of the problem.
Due to last changes in gorm (I think because of new dirty checking logic) class LazyBeanMap stop working properly. It can't see domain's domain fields.

https://github.com/demon101/bind-data-bug , see IndexController

```
    def lazyBeanMap = new LazyBeanMap(cc)
    println lazyBeanMap.keySet()
```
prints: 

> [dirty, dirtyPropertyNames, name, attached, id, version, errors, addressId] // no address

In the code of grails-core I have found LazyMetaPropertyMap class. It works well.
I hope, the bug can be fixed by replacing line in

grails-core/grails-web-databinding/src/main/groovy/org/grails/web/databinding/bindingsource/DefaultDataBindingSourceCreator.groovy

`dataBindingSource = new SimpleMapDataBindingSource(new LazyBeanMap(bindingSource))`
to

`dataBindingSource = new SimpleMapDataBindingSource(new LazyMetaPropertyMap(bindingSource)) `
LazyBeanMap class can be deprecated.

I have no idea how to run tests of grails core and make PR on github, I hope, grails team will help me and finish the issue

**Comment by jeffbrown** [comment]
> I have no idea how to run tests of grails core

@demon101 The "How Can I Contribute To Grails Code?" section at http://grails.org/faq.html is a good starting point.  If you find anything there which is out of date or doesn't make sense, feel free to flag that.  

Thanks for your help.

**Comment by demon101** [comment]
@jeffbrown  what do you think about fix? Is it acceptable? 
If yes, I will try to create PR with fix and tests

**Comment by jeffbrown** [comment]
> @jeffbrown what do you think about fix? Is it acceptable?

@demon101 I have no idea.  I haven't seen it.  We need a failing test which describes the problem, a fix to address that test, verify that the rest of the unit and functional tests still work with the change, and review the code.

**Comment by demon101** [comment]
@jeffbrown I have started development of fix, and has few troubles:
1. Where I can communicate with grails developers. Slack looks like abandoned. Only google group (https://groups.google.com/forum/#!forum/grails-dev-discuss)? 
2. How to add an integration test? The bug is between gorm and data-binding. I have no idea how to make a unit test for this case without real gorm entity.
3. Where is a border between  grails-databinding and grails-web-databinding?
4. Where can I find documentation for developers of grails? (a common practice, modules descriptions, lessons, howto...).

THX!

Draft, without tests:
https://github.com/demon101/grails-core/pull/1/files

**Comment by demon101** [comment]
@jeffbrown I have pushed fix with tests for grails/grails-data-mapping#1145 too.
Could you have a look on PR, please?

**Comment by jeffbrown** [comment]
> Where I can communicate with grails developers. Slack looks like abandoned.

Our Slack has not been abandoned.  There is quite a bit of traffic there every day.  In which channel(s) were you looking?

**Comment by demon101** [comment]
@jeffbrown now I see slack activity. I have applied for grails community two weeks ago and didn't receive an acceptance message. Just because of I already in grails slack community from 2015 =)

**Comment by demon101** [comment]
@jeffbrown could you reopen the issue, please? What should I do for the merging of the PR?

**Comment by demon101** [comment]
@jameskleeh could you reopen the issue, please? I have provided PR with tests https://github.com/grails/grails-core/pull/11080 , what should I do for including my fix to coming release?
