### ISSUE TITLE
web-plugin UrlMappings are skipped or ignored (3.3.5)

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11057]
I'm unable to provide public steps to reproduce, as the symptom is located in a proprietary-system that currently is being upgraded from Grails v2.4.4 to v3.3.5.

I've added log.info to all `UrlMappings.mapping` closures in each module and can then via log verify which `UrlMappings` was executed.
The symptom is quite frustrating as it seems there's app. 20% chance that all web-plugin `UrlMappings` are loaded, the rest of the time only some or no `UrlMappings` are loaded from web-plugins :/
Ex. just restarting the web-app gives a different result...

I've also tried creating a small v3.3.5 sample project with a web-app and 2 web-plugins - but that setup consistently loads all `UrlMappings` ~ which is nice to know :) , but doesn't help in pinning down why this symptom is present in a real web-app.
The symptom is non-existent in Grails 2, all `UrlMappings` are loaded consistently.

I've downloaded `grails-core` in an attempt to figure out where `UrlMappings` are loaded - so far no luck - so I would really appreciate some pointers from a Grails guru - as to where I should be hooking in a debugger in-order to determine where Grails determines which `UrlMappings` it intends to execute **?**

Best regards a frustrated developer :)

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
N/A

### Expected Behaviour

All URL-mappings in included web-plugins should be executed consistently.

### Actual Behaviour

Some/all URL-mappings in included web-plugins are ignored.

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.3.5
- **JDK Version:** OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
- **Container Version (If Applicable):** Tomcat 8.5.24

### Example Application

N/A

**Comment by jameskleeh** [comment]
@dlehammer The mappings are evaluated here https://github.com/grails/grails-core/blob/ac58914a1e6e55dd5342590aac2b37cc12377de0/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/UrlMappingsHolderFactoryBean.java#L89

**Comment by sbglasius** [comment]
I also get inconsistent Url mappings. If I have multiple plugins in an application defining 
```
"500"(view: '/someView')
```
The order they come in my `url-mappings-report` is random (and not very saying):

This is one run:
``` 
Dynamic Mappings
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /systemfejl                     |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
```
and a new run just after:
```
Dynamic Mappings
 |    *     | ERROR: 500                                                      | View:   /systemfejl                     |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 |    *     | ERROR: 500                                                      | View:   /error                          |
 ```
Making it very difficult to trace what plugin provided the url-mapping and trusting the correct mapping is in place for the application.

**Comment by sbglasius** [comment]
In the app that I work with, I have a breakpoint here: https://github.com/grails/grails-core/blob/3.3.x/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/UrlMappingsHolderFactoryBean.java#L83 - and the mappings.length comes out with a different count every time I restart the application.

**Comment by sbglasius** [comment]
After lots of debugging I found the culprit of this issue. A plugin that defines `UrlMapping` in root scope (without a package name).

It happens in `/org/grails/plugins/AbstractGrailsPluginManager.java:309`m if a plugin provides a `UrlMappings` without a package, this check will ignore the rest of the plugins `UrlMappings` as in line #318 `app.getClassForName(shortName)` will return `true`

I think this behavior should continue to be so, but instead I would recommend a big fat warning inserted below #308:

```
log.warn("WARNING: Plugin "+plugin.getName()+" has an UrlMapping in root scope (without a package name). This WILL eventually break your applications UrlMappings");
```

**Comment by sbglasius** [comment]
The behavior can be studied in this project: https://github.com/sbglasius/issue-11057

Two of the plugins has an `UrlMappings` file in root scope (no package) and the debug output shows that not all plugins are loaded, and that the output is random on subsequent runs

**Comment by niravassar** [comment]
Took a look at this today and I am just summarizing what i found some debugging:

Explanation
============================	
- If all urlmappings for plugins are in a package then it all works
- if one is not in a package then it is randomly leaving 1 or more out because they will not all register as artefacts
	- when this occurs the url-mappings-report is meaningless this does not reflect which atrefacts are registered 
- when the plugin loader is seeing UrlMappings without a package it registers the artifact and then subsequent UrlMappings in plugins get skipped over because the shortName is extracted and checked for everything. Thus, the subsequent UrlMappings, even when in a package get deemed as "isAlreadyRegistered". 
- see and debug AbstractGrailsPluginManager:309

**Comment by sbglasius** [comment]
The issue behavior can be shown here: https://github.com/sbglasius/issue-11057

**Comment by niravassar** [comment]
@sbglasius I took out what was an unnecessary check to shortname and used the sample app to verify. I also added specific log statements for the scenario of artefacts being defined without proper package names. Well done, and thank you
