### ISSUE TITLE
@Integration spec not working with custom application class

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#11050]
Trying to slice an application (especially component-scan-wise) for partial integration-testing, I tried to use a custom `TestApplication` class with `@Integration(applicationClass = TestApplication)`.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app `FooIntegrationSpec` from ide or `gradle(w) integrationTest`

### Expected Behaviour

integration testing should work with custom application classes when running from ide as well as via grails/gradle.

if artefact handling for application class artefacts is necessary, it should work with an artefact suffix of `Application`, not requiring the application class to be named exactly `Application(.groovy)`.

### Actual Behaviour

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
```

looking a bit into the code, i guess the custom application class is not properly processed by the grails ast xforms because the application class is expected to be named exactly `Application(.groovy)`:
* https://github.com/grails/grails-core/blob/v3.3.6/grails-core/src/main/groovy/org/grails/core/artefact/ApplicationArtefactHandler.groovy#L42-L50
* https://github.com/grails/grails-core/blob/v3.3.6/grails-core/src/main/groovy/org/grails/compiler/injection/ApplicationClassInjector.groovy#L135-L141

### side-note

looks like `@Integration` without an `applicationClass` attribute does only work when running via `gradle(w) integrationTest` and not when running from ide, regardless of the application class (can be the default one too). that may be because only the `build/classes` compilation target directory seems to be searched, ref.:
* https://github.com/grails/grails-testing-support/blob/v1.1.4/grails-testing-support/src/main/groovy/org/grails/compiler/injection/testing/IntegrationTestMixinTransformation.groovy#L88
* https://github.com/grails/grails-core/blob/v3.3.6/grails-bootstrap/src/main/groovy/org/grails/io/support/MainClassFinder.groovy#L56

not sure if this should go into a separate issue or could be improved on-the-fly with this one.

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.3.6
- **JDK Version:** oracle 8u151
- **Container Version (If Applicable):** n/a

### Example Application

sample app will be referenced any minute

**Comment by jeffbrown** [comment]
See https://github.com/zyro23/grails-core-11050/pull/1

**Comment by puneetbehl** [comment]
@zyro23 Now, you should be able to create a custom application name ending with "Application". For example: "TestApplication", "MyCustomApplication" etc.

Also, please note that if you are creating the custom application class in `src` folder then you need to annotate the class with `@Artefact` as:
```
import grails.artefact.Artefact
import grails.boot.GrailsApp
import grails.boot.config.GrailsAutoConfiguration

@Artefact('Application')
class TestApplication extends GrailsAutoConfiguration {
 	static void main(String[] args) {
		GrailsApp.run(Application, args)
	}
 	Collection<String> packageNames() {
		super.packageNames()
	}
}
```

**Comment by zyro23** [comment]
thank you! much appreciated. do you maybe got a little feedback reg. my side-note as well? its just so ..very.. convenient to be able to run the integration specs from the ide as well :)

**Comment by puneetbehl** [comment]
@zyro23 I am sorry for the delayed response, but I am able to run the Integration test using IntelliJ Idea.

**Comment by zyro23** [comment]
great, thx for confirmation! can be closed, i guess.
