### ISSUE TITLE
Migration guide for Gradle 4 from Gradle 3

### ISSUE THREAD

**Issue by zatziky** [grails/grails-core#11058]
Hi Grails team,

can you please create a migration guide so that we can upgrade to Gradle 4 from Gradle 3? Or are there some existing resources? I cannot find anything that would reliably help you with the overall migration process.

Kind regards,

Nobo

**Comment by jameskleeh** [comment]
@zatziky I think this is outside of our scope. If you'd like a guide on upgrading Gradle, I suggest looking in the Gradle community. The Gradle 4 release notes have a good amount of information. https://docs.gradle.org/4.0/release-notes.html
