### ISSUE TITLE
File reading vulnerability

### ISSUE THREAD

**Issue by RicterZ** [grails/grails-core#11068]
Hi, grails has a file reading vulnerability which can read source code (java bytecode) of affected applications. This flaw needs the grails packed to war, and the application is running on the jetty.

###  Reproduce

1. Create a helloworld application and a helloworld controller.
2. Modify build.gradle line 34, from `compile "org.springframework.boot:spring-boot-starter-tomcat"` to `compile "org.springframework.boot:spring-boot-starter-jetty"`.
3. Build a war file.
4. Deploy the application to jetty.
5. Send a crafted request: `/helloworld-0.1/assets/..%5cWEB-INF/classes/helloworld/HelloController.class`.

### Expected Behaviour

404 or 403

### Actual Behaviour

![image](https://user-images.githubusercontent.com/5282759/44259789-1bf0a900-a245-11e8-8c43-d9d9ba5a82ab.png)

### Environment Information

- **Operating System**: Windows
- **Grails Version:** the latest version
- **JDK Version:** 1.8.0_181

**Comment by jameskleeh** [comment]
@RicterZ This would be an issue with Spring Boot. Also for future reference it's a bad idea to report security vulnerabilities to a public issue tracker.

**Comment by jameskleeh** [comment]
I'm closing this to reduce visibility, however I have contacted the pivotal security team and sent them this issue.

**Comment by RicterZ** [comment]
Thanks for your response, I removed the details
