### ISSUE TITLE
Documentation missing for auto-generated Domain Service classes

### ISSUE THREAD

**Issue by anti43** [grails/grails-core#11062]
### Steps to Reproduce

- Create a grails3 project with one domain class name `SomeDomain`
- Run command `generate-all SomeDomain`

### Actual Behaviour

A service _interface_ is generated:

```
import grails.gorm.services.Service

@Service(SomeDomain)
interface SomeDomainService {

    SomeDomain get(Serializable id)

    List<SomeDomain> list(Map args)

    Long count()

    void delete(Serializable id)

    SomeDomain save(SomeDomain someDomain)
}
```

Neither 

`https://docs.grails.org/latest/guide/services.html`

nor 

`https://docs.grails.org/latest/guide/scaffolding.html`

talk about theses interfaces and how to use them or where the actual implementation is.
Adding methods to this interface ends up nowhere because its not clear where to implement the interfaced methods. Adding a method `test ` will cause the application to fail:

> startup failed:
> C:\Users\User\IdeaProjects\test\grails-app\services\test\SomeDomainService.groovy: 18: No implementations possible for method 'void test()'. Please use an abstract class instead and provide an implementation.
>  @ line 18, column 5.
>        void test()
>        ^
> 
> 1 error

Problematic imo: now the service name `someDomainService` is taken. If I want to have a real service implementation with that CoC name, I have to remove the generated one

### Environment Information

- **Operating System**: WIN10
- **Grails Version:** 3.3.6
- **JDK Version:** 1.8

**Comment by anti43** [comment]
Ok, thank you!

Will this link be added to 

https://docs.grails.org/latest/guide/scaffolding.html

at some point?

**Comment by ilopmar** [comment]
Feel free to submit a PR to update the documentation :)

**Comment by nutmix** [comment]
I agree, this is very confusing as these interfaces, how to use them, how to extend them etc. is not mentioned anywhere in the documentation or anywhere I can find - its a complete mystery.  Replacing them with a real service (as per documentation) is also non trivial, at least for beginners.  I had to re-install grails 2.5, generate some dummy services and cut and paste the code into grails 3 project, which is a step backwards.

**Comment by ilopmar** [comment]
As we already have mentioned before, GORM Data Services are documented and explained here: http://gorm.grails.org/latest/hibernate/manual/index.html#dataServices

And, of course, you don't have to use them if you don't want.
