### ISSUE TITLE
Groovy v2.4.15 dependency upgrade is listed in release notes for separate releases

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11073]
### Task List
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Open [v3.3.6](https://github.com/grails/grails-core/releases/tag/v3.3.6) release notes, compare "Dependencies upgraded" section with v3.3.5.

### Expected Behaviour

Groovy v2.4.15 is only expected to be listed as an upgraded dependency once.
(I believe the Groovy v2.4.15 upgrade belong solely in v3.3.5)

### Actual Behaviour

Groovy v2.4.15 is listed as an dependency upgrade in both [v3.3.5](https://github.com/grails/grails-core/releases/tag/v3.3.5) and [v3.3.6](https://github.com/grails/grails-core/releases/tag/v3.3.6).

### Environment Information

- **Operating System**: N/A
- **Grails Version:** N/A
- **JDK Version:** N/A
- **Container Version (If Applicable):** N/A

### Example Application

- N/A

**Comment by jameskleeh** [comment]
Fixed, thanks
