### ISSUE TITLE
When releasing a new version, snapshot documentation keeps pointing to old version

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#11072]
Although current version was 3.3.8, current snapshot documentation still points to 3.3.6. 

UPDATE: I reviewed some documentation PR's which triggered travis republish. Snapshot is currently 3.3.8

**Comment by bobbywarner** [comment]
SNAPSHOT docs appear to be working as expected now (correctly referencing 4.1.0.BUILD-SNAPSHOT):

http://docs.grails.org/snapshot/guide/single.html
