### ISSUE TITLE
Grails 3.3.8: Inline plugin reloading does not work

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#11079]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Extract the attached project
2. Open a terminal in the directory "multiproject1/myapp"
3. Run the command "grails run-app" or "../gradlew  bootRun -Dgrails.run.active=true"
4. Open the url "http://localhost:8080/home/index"
5. Apply a change to the method "HelloWorld.sayHello()" in "multiproject1/myplugin/src/main/groovy/myplugin/HelloWorld.groovy" for example "int i = 1234"
6. Reload the url "http://localhost:8080/home/index"
7. The changes to "HelloWorld.sayHello()" should be reloaded but are not.

### Expected Behaviour

Auto reloading of code changes in inline plugins should work.

### Actual Behaviour

Inline plugin reloading does not work.

### Environment Information

- **Operating System:** Linux 64bit - Kernel 4.15.0-33-generic
- **Grails Version:** 3.3.8
- **JDK Version:** 1.8.0_171
- **Container Version (If Applicable):** TODO

### Example Application
[multiproject1.zip](https://github.com/grails/grails-core/files/2318666/multiproject1.zip)

**Comment by atasc** [comment]
With Grails 3.3.6 and previous versions auto reloading works without exploded=true.
I've tried to add exploded=true to the plugin but it does not work.

**Comment by jameskleeh** [comment]
@atasc You added `exploded=true` to a `gradle.properties` file in the plugin directory?

**Comment by atasc** [comment]
@jameskleeh no I added 

grails {
  exploded = true
}
to build.gradle of myplugin

You can refer to the attached project.
Auto reloading in the same project works with Grails 3.3.6.

**Comment by jameskleeh** [comment]
@atasc I understand that it worked as you expected in 3.3.6. I think if you find that it will work if you were to do what I described above.

**Comment by atasc** [comment]
@jameskleeh adding a gradle.properties with exploded = true to each project directory makes auto reloading in inline plugin work.

Does "exploded = true" affect the war file to deploy in production? 

Thank you very much jameskleeh.

**Comment by jameskleeh** [comment]
@atasc No it should not behave any differently with regards to the war file compared to 3.3.6.

This was documented in the release notes of 3.3.7: https://github.com/grails/grails-core/releases/tag/v3.3.7
The documentation was also updated http://docs.grails.org/latest/guide/plugins.html#creatingAndInstallingPlugins under "Plugins and Multi-Project Builds"

**Comment by jlstrater** [comment]
First, the biggest issue I had getting this to run was adding the property in too many places. For everyone else coming across this, only add the property to the plugins NOT the main app! 🤦‍♀️ 

However, I'm still having trouble when I run the app using the gradle wrapper instead of grails run-app. 😞 [example project](https://github.com/jlstrater/grails-reloading-tests)
