### ISSUE TITLE
Deprecated grails.transaction.NotTransactional?

### ISSUE THREAD

**Issue by sbglasius** [grails/grails-core#11086]
If `grails.transaction.Transactional` is `@Deprecated` should `grails.transaction.NotTransactional` also be deprecated?

**Comment by donalmurtagh** [comment]
According to [the docs](http://docs.grails.org/3.3.x/guide/upgrading.html#_grails_transactional_ast_transforms_deprecated) `grails.transaction.Rollback` should also be marked `@Deprecated`

**Comment by jeffbrown** [comment]
> According to the docs grails.transaction.Rollback should also be marked @Deprecated

@donalmurtagh I think `grails.transaction.Rollback` was deprecated in February of 2017.  It was marked as such with javadoc at https://github.com/grails/grails-core/commit/bcae0972ef5a968504dc0429a12b6f4b0ceca569 (the `@Deprecated` annotation was not used).
