### ISSUE TITLE
Restful service receives null JSON object when it is embedded inside a more complex JSON object

### ISSUE THREAD

**Issue by el-duderino5** [grails/grails-core#11107]
- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use Postman to create a complex JSON object that has an embedded JSON object, for example, this one: {
	"id": null,
	"idCliente": 1,
	"nombre": "Pedro Ramírez",
	"direccion": "Calle 27, La Esmeralda",
	"telefono": "(809) 585-9509",
	"cedulaRNC": "393-4949493-9",
	"ciudad": "Santiago",
	"parajeProvincia": "Santiago",
	"nombreContacto": "José Gómez",
	"telefonoContacto": "(489) 129-3903",
	"nombreEncargado": "Carlos Alberto",
	"telefonoEncargado": "(393) 203-2039",
	"plazoPago": 6,
	"metaEnLitros": 4859.59,
	"frecuenciaVisita": 10,
	"secuenciaVisita": 3,
	"ruta": {
		"id": null,
		"descripcion": "Guzmancito",
		"cuotaEnLitros": 3849.32,
		"activa": true
	},
	"tipoGanadero": { "id": 1 },
	"tipoComprobante": { "id": 1 },
	"tipoNomina": { "id": 1 }
}
2. Send the JSON to the Grails Restful endpoint via POST method

### Expected Behaviour
The received JSON object should be received in its entirety
### Actual Behaviour
The above JSON is received, but the property "ruta", which is an embedded JSON object, is null when received in the restful endpoint. The method in my controller that receives the JSON has as an argument an object of the class that has all the properties in the above JSON. Strangely enough, the embedded JSON (ruta) is not null and is received if I provide an Id for its id property.
### Environment Information

- **Operating System**: Debian Stretch
- **Grails Version:** 3.3.8
- **JDK Version:** 8

My intention is to construct an object graph from the JSON object, and then call the .save method on it so that it is persisted. In a normal Grails application, you do not have to specify an Id for an object in a relationship, and it gets persisted and populated with an Id when persisted. With JSON objects that I receive in requests, it appears that the Id MUST be present in order to persist the whole object.

**Comment by jeffbrown** [comment]
Does the same thing happen if you eliminate `"id": null` from the `ruta` object map in your JSON?

**Comment by el-duderino5** [comment]
> Does the same thing happen if you eliminate `"id": null` from the `ruta` object map in your JSON?

Yes. The same thing happens. The Id must exist and its value must not be null for it to work.

**Comment by el-duderino5** [comment]
One question: the main object that contains "ruta" (which means route in English) used to have a many-to-one relationship with the main object that contains it (which is the cattleman). The idea that I had in my head is that a route belonged to the cattleman, and that the relationship had to be that many cattleman could be located in one route. That meant putting a Route object in my cattleman domain, and a cattleman in my Route domain (with a [belongsTo] to have a bidirectional relationship plus cascade saves and possibly deletes). Do you think that may had something to do with it? Although, I can not see how that could possibly cause the route to be a null object in my REST endpoint. Something else must be causing a deserialization problem when there are embedded objects in a JSON object.

In the end I had to settle for a one-to-many relationship between Routes and Cattlemen, as that made the most sense, and save the route first, so that it could have an id, so that I could later send a request to my endpoint with an embedded Route with just one property (the Id of the route), so that I could persist the whole object graph.

Despite this, it would be sweet if could construct the whole graph first, and then make it persist by sending it to my rest endpoint, following, of course, the rules of cascades saves and deletes. For now I would just like to know why the route is arriving as a null route unless I give it a non-null Id (even if said Id doesn't even exist in the database yet).

**Comment by jeffbrown** [comment]
> Yes. The same thing happens.

I can't recreate that.

See the project at https://github.com/jeffbrown/issue11107.

The test at https://github.com/jeffbrown/issue11107/blob/31d4a1b45d0edaac20bc103d1127a8825aa995ee/src/integration-test/groovy/demo/DemoControllerSpec.groovy. Which indicates that the `ruta` property is being properly populated.

If I uncomment the line at https://github.com/jeffbrown/issue11107/blob/31d4a1b45d0edaac20bc103d1127a8825aa995ee/src/integration-test/groovy/demo/DemoControllerSpec.groovy#L43 then the test will fail.

**Comment by el-duderino5** [comment]
I ran your test project and, indeed, the route reaches the rest endpoint but, only as long as I don't have a null Id property in the route. Do you have any knowledge as to why, despite the fact that the Contact JSON has a null Id on the Contact JSON object, I still get an empty Route if it has a null Id when they are embedded in the JSON file?

I used this JSON as payload for your rest endpoint of your application (I sent it through POST): 
{
	"id": null,
	"nombre": "John Smith",
	"Telefano": "908-293-3998",
	"ruta": {
		"descripcion": "Guzmancito"
	}
}
This one's route reaches the endpoint just fine and I get back as a response the description of the route, as you coded it. Now, in this one: 

{
	"id": null,
	"nombre": "John Smith",
	"Telefano": "908-293-3998",
	"ruta": {
                "id": null,
		"descripcion": "Guzmancito"
	}
}
The route does not reach the endpoint, and I get a 500 status code for the response

**Comment by jeffbrown** [comment]
> The route does not reach the endpoint, and I get a 500 status code for the response

I can't recreate that and it doesn't make sense that the payload would affect whether or not the endpoint is reached.  The payload isn't even interrogated until after the endpoint has been identified.

I do know what the problem is with the `id: null` causing the reference to be `null` and I will address that.

Thanks for the feedback.

**Comment by el-duderino5** [comment]
Mr. Brown. I think I have found a bug that may or may not have to do with the original issue.

My intention with the Grails restful services I am implementing is to minimize the amount of data that I put on the wire. My goal is to not send entire object graphs in order to persist or query information, if I can afford to do so.

Having this in mind, let's go back to the Route object. I have established a many-to-one relationship from an entity called RouteType to Route. Let's imagine that this RouteType object has about 100 properties and many collections. So, what I do, is that the very first time, I decide to construct this JSON object:
```
{
    "id": null,
     "routeName": "Los Albinos",
     "routeType": {
          "description": "Most beautiful route in the world",
           .
           .
           .
           .
           .          
      }
}
```
The dots represent numerous properties.

Let's say I send this JSON to my restful endpoint, it gets persisted, and the RouteType object gets one (1) as its ID in the database. Now, I would also like to be able to re-use this same RouteTypein another Route. So I send this time another Route JSON to my endpoint - one like this:
```
{
    "id": null,
     "routeName": "The Ruskies",
     "routeType": {
          "id": 1   
      }
}
```
With this, I do not have to send every property of the RouteType, just its ID, so that when it reaches my restful endpoint, GORM can associate this new Route with the already existing RouteType.

I have created an scenario like this, though at a much lesser scale, and the issue is this: the first time, the entire object graph is persisted and, after both objects of the relation are persisted (Route and RouteType), I can successfully use the id as in the second JSON I posted to have GORM persist the new Route and make the relation with the RouteType through its id. The problem is that when I do it a three or five times, it blows up. I get "Entity is in an invalid state" message in my stacktrace. After that, it only works if I actually fill all the properties of the RouteType embedded object. I can make new RouteTypes along with the Routes, but I have not yet tested if supplying the id of the persisted RouteType in the json file, along with its other properties, does not result in my server blowing up.

By the way, I am using IntelliJ and the H2 database and tomcat that comes in the template for the gradle.build file for a new Grails project, if it can throw some light into the matter.

**Comment by jeffbrown** [comment]
> Mr. Brown. I think I have found a bug that may or may not have to do with the original issue.

Feel free to file a separate issue and provide a simple sample project which demonstrates the problematic behavior.

**Comment by jeffbrown** [comment]
I have looked into this and I think the issue described here is actually intended behavior.  When the nested `Map` (JSON or otherwise) includes an `id` value that is `null`, the system is supposed to bind `null` to the corresponding property.  That is, if you have these:

```groovy
class Contact {
    String nombre
    String telefano
    Ruta ruta
}
```

```groovy
class Ruta {
    String descripcion
}
```

And you bind JSON like this to an instance of `Contact`:

```javascript
{"nombre": "Jeff",
 "telefano": "12345678",
 "ruta": {"id": null,
          "descripcion": "Some Description"}}
```

... the `ruta` property in the `Contact` instance is supposed to be `null`.  We have explicit test coverage to make sure that happens.

Some of the relevant test coverage is at https://github.com/grails/grails-core/blob/3.3.x/grails-test-suite-persistence/src/test/groovy/grails/web/databinding/GrailsWebDataBinderSpec.groovy#L256-L287.

If you want the data binder to create the `Ruta` instance, the `"id": null` should not be included in the posted JSON.

**Comment by el-duderino5** [comment]
That makes sense. Thank you for your efforts, Mr. Brown
