### ISSUE TITLE
Consider removing redundant session registration code from GrailsFlashScope

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#11108]
We have a situation where we need to customize the `GrailsFlashScope` so that it's not stored in the session. The TLDR is that it's difficult to ensure that everything in the flash is serializable and we are using JDBC backed spring-session.

In the case of the `flash`, it's sort of transient by nature, so there's not really any need for us to write that data to the database just to facilitate the next request.

I'm able to easily create my own custom `DefaultGrailsApplicationAttributes` implementation using the factories (very nice) and override the `getFlashScope` method to do exactly what we want in a tiny amount of code. However, one annoying thing is there's some super-old code in the `GrailsFlashScope` that I don't think is even needed which does `registerWithSessionIfNecessary` on each put and will actually create a new session and put the flash map in there. This causes the session to have a modification and thus the empty flash is written to the database anyway, which is inefficient.

https://github.com/grails/grails-core/blob/d4e190165bb85cbe36fb0f673d7357abfbaae2a8/grails-web-common/src/main/groovy/org/grails/web/servlet/GrailsFlashScope.java#L201

It seems like the `GrailsFlashScope` shouldn't really know or care where it's stored (sometimes it's in the request already) and let the `getFlashScope` worry about that.

At a minimum, if the method could be made `protected`, I could at least extend the `GrailsFlashScope` and override it to be a no-op.

I'm not convinced removing `registerWithSessionIfNecessary` will have any consequences at all with Grails 3.3.x and later.

**Comment by longwa** [comment]
Since this code was already creating a session and putting the flash in the session (I think this was mostly useful for unit tests), you can also cleanup the code in the `DefaultGrailsApplicationAttributes` to just always get/create from the session instead:

```

    public FlashScope getFlashScope(ServletRequest request) {
        if (!(request instanceof HttpServletRequest)) {
            return null;
        }

        HttpServletRequest servletRequest = (HttpServletRequest) request;
        HttpSession session = servletRequest.getSession(true);
        FlashScope fs = (FlashScope)session.getAttribute(FLASH_SCOPE);
        if (fs == null) {
            fs = new GrailsFlashScope();
            session.setAttribute(FLASH_SCOPE,fs);
        }
        return fs;
    }
```
This would have the same effect and decouple the `GrailsFlashScope` itself from where it is stored.

**Comment by puneetbehl** [comment]
@longwa I have created a field `isRegisterWithSession` which is `true` by default. But, you can override the value to `false` by calling `new GrailsFlashScope(false)` which not try to register in the session with every `put`.
