### ISSUE TITLE
UrlMappings with resource inside group breaks subsequent controller mappings

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#11104]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define a `resources`-style mapping inside a group in UrlMappings
2. Define a standard controller mapping with a variable in the GString

### Expected Behaviour

The mappings are correct

### Actual Behaviour

A mapping of "/foo/${id}" is evaluated as "/foo/null" and the mappings are incorrect.

### Environment Information

- **Operating System**: Fedora Workstation 28
- **Grails Version:** 3.3.8
- **JDK Version:** openjdk version "1.8.0_181"
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/joemccall86/grails-core/blob/326f2cfb769a309eebcdb0ada0509427492e7a1e/grails-web-url-mappings/src/test/groovy/grails/web/mapping/CollectionWithVariableUrlMappingSpec.groovy

I already have a potential fix for this. PR inbound.

**Comment by ddelponte** [comment]
Closing.  This was fixed by PR https://github.com/grails/grails-core/pull/11105
