### ISSUE TITLE
Grails stop-app does not shut down a running app in 3.3.8

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#11119]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a vanilla Grails project (or sample linked below)
2. Start the interactive Grails shell via `./grailsw`
3. `run-app`
4. `stop-app`

### Expected Behaviour

```
| Application shutdown.
```

### Actual Behaviour

```
| Shutting down application...
| Error Application not running.
```

### Environment Information

- **Operating System**: Fedora 28 Workstation
- **Grails Version:** 3.3.8
- **JDK Version:** openjdk version "1.8.0_181"
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/joemccall86/test-stop-app-v33x

### Notes

Appears to be similar to https://github.com/grails/grails-core/issues/10791, but that issue was closed since it could not be reproduced. It also included some other symptoms. This issue has an example attached and should be reproducible at will.

This is caused by the upgrade to Spring Boot 1.5.x, when the `MvcEndpointSecurityInterceptor` was added to secure actuator endpoints. When the stop-app script attempts to call shutdown, the returned status is 401 Unauthorized due to this interceptor.

My sample application has a workaround commented out in https://github.com/joemccall86/test-stop-app-v33x/blob/master/grails-app/conf/application.yml#L85 that allows the shutdown actuator endpoint to be accessed anonymously in development mode, which matches the behavior from before. Unfortunately this has the side-effect of not working when using `grails prod run-app`.

**Comment by graemerocher** [comment]
Normally it should not get to invoking the endpoint over HTTP and should shutdown the app via JMX locally https://github.com/grails-profiles/base/blob/master/commands/stop-app.groovy#L52

Note sure why that is not working...

**Comment by joemccall86** [comment]
If it helps I tested back to 3.0.17 and it fell back to the HTTP endpoint strategy since no JMX addresses were found.

**Comment by joemccall86** [comment]
Update on this: the `stop-app` command relies on the `tools.jar` being present in the classpath from the local JVM. The only place it checks is the environment variable `JAVA_HOME`. My test setup did not have that variable set up. 

When `JAVA_HOME` is set the `stop-app` command works properly. My next test will be on MacOS to see if it is detected properly.

**Comment by joemccall86** [comment]
Confirmed that macOS _must_ have `JAVA_HOME` set up properly. This can be addressed in the documentation.

**Comment by bobbywarner** [comment]
Closing as docs PR was merged and no other changes are needed.

**Comment by treyturner** [comment]
I am struggling with this on Windows 10 and my `JAVA_HOME` is set correctly:

```
D:\dev\grodcast>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_261

D:\dev\grodcast>java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

D:\dev\grodcast>dir "%JAVA_HOME%\lib\tools.jar"
 Volume in drive C is Windows 10
 Volume Serial Number is 5CE2-8C51

 Directory of C:\Program Files\Java\jdk1.8.0_261\lib

07/24/2020  10:25 PM        18,265,129 tools.jar
               1 File(s)     18,265,129 bytes
               0 Dir(s)  97,360,777,216 bytes free
```
