### ISSUE TITLE
Integration tests not generating HTML file

### ISSUE THREAD

**Issue by mangelo123** [grails/grails-core#11125]
From interactive Grails, enter test-app --integration

All XML files are generated, but the main html file is missing. The XML files are not practical for error review.

Windows 10
Grails 3.3.3
JDK 1.8.0_181-b13

**Comment by ilopmar** [comment]
I've pushed the code.

**Comment by mangelo123** [comment]
I was mistaken. The files are getting generated. The issue is when using the open test-report command. It is looking in build\reports\tests\test and the files are located in build\report\tests. Is there a setting to stop the last directory from being appended to the path?

**Comment by ilopmar** [comment]
Thanks for the info, I'll take a look

**Comment by ilopmar** [comment]
@mangelo123 I've submitted a PR to fix the issue: https://github.com/grails/grails-core/pull/11127
Thanks for your help :)
