### ISSUE TITLE
Eclipse JDT Compiler creates grails-plugin.xml in wrong directory

### ISSUE THREAD

**Issue by sosguthorpe** [grails/grails-core#11138]
### Task List

- [x] Steps to reproduce provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Set up multi project build, with at least 1 plugin as a linked project.

### Expected Behaviour

grails-plugin.xml produced in `{project-root}/bin/META-INF`. This was the case in an earlier version of eclipse.

### Actual Behaviour

grails-plugin.xml produced in `{current-user-home}/bin/META-INF`

### Environment Information

- **Operating System**: Kubuntu 18.04
- **Grails Version:** 3.3.6 (Also seems to happen with 3.3.8)
- **JDK Version:** Currently using GraalVM 1.8.0_172, but also tested with Oracle JDK1.8 and OpenJDK8)

### Eclipse info
Eclipse IDE for Java Developers
Version: 2018-09 (4.9.0)
Build id: 20180917-1800
OS: Linux, v.4.18.16-041816-generic, x86_64 / gtk 3.22.30, WebKit 2.22.2
Java version: 1.8.0_172

### More info
I believe the problem to be in this file:
[GroovyEclipseCompilationHelper.groovy](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/compiler/injection/GroovyEclipseCompilationHelper.groovy)
resolving to the incorrect directory with the latest JDT in eclipse, but am unsure on how I might be able to properly debug this. I'd be happy to help fix/test if someone has any advice on how I might go about this.

**Comment by graemerocher** [comment]
Maybe this hack is no longer needed after https://github.com/groovy/groovy-eclipse/issues/575 was fixed

**Comment by sosguthorpe** [comment]
Thanks for the quick response! Yes it looks like that might make that helper redundant for latest versions. SO I guess it needs to be more specific in targeting lower versions. Thanks for the pointer, I'll try and set a little time aside to make this helper function more picky.

**Comment by sosguthorpe** [comment]
So after doing some digging I found that groovy-eclipse sets the targetDirectory relative to the project root, and so the helper needed tweaking to resolve none-absolute files against the project.

**Comment by jameskleeh** [comment]
@sosguthorpe Changes are merged up

**Comment by sosguthorpe** [comment]
@jameskleeh Thank you. Does this mean it will be in the 3.3.9 release? I'm going to build a custom pre-release for our development, but wondered if it would make it in to next release?

**Comment by jameskleeh** [comment]
@sosguthorpe If it's merged into 3.3.x before 3.3.9 is released, then yes
