### ISSUE TITLE
Multiple datasources isn't working (DataSource not found for name [qa] in configuration)

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#11136]
### Steps to Reproduce

1. Clone my sample application at https://github.com/olavgg/simple_multi_data_source_failed_sample
2. Start the application with `grails run-app`
3. Invoke http://localhost:8080/intent/show-intent-titles

### Expected Behaviour

The titles from the QA schema should be printed

### Actual Behaviour
 I get an error:
DataSource not found for name [qa] in configuration. Please check your multiple data sources configuration and try again..

### Environment Information

- **Operating System**: Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Grails Version:** 3.3.8
- **GORM Version:** 6.1.10.RELEASE
- **JDK Version:** 1.8.0_181
- **Database:** PostgreSQL 10.5 (Ubuntu 10.5-0ubuntu0.18.04)

### Description
I have a strong feeling that this is a configuration error, but I cannot figure out why this is failing. I am following the guide found here http://guides.grails.org/grails-multi-datasource/guide/index.html

In org.grails.orm.hibernate.HibernateDatastore I can see that when starting the application I have 2 datastores as seen in this picture

![image](https://raw.githubusercontent.com/olavgg/simple_multi_data_source_failed_sample/master/Screenshot_20181031_141412.png)

But when I invoke the service method it looks like this:
![image](https://raw.githubusercontent.com/olavgg/simple_multi_data_source_failed_sample/master/Screenshot_20181031_141437.png)

I also have a slightly more advanced sample project which uses postgresql here:
https://github.com/olavgg/multi_data_sources_not_working_with_grails

**Comment by olavgg** [comment]
Just an update to this issue. If I rewrite the service into the following then it works.
```
import grails.gorm.transactions.Transactional

@Transactional('qa')
class IntentService {

    def printTitle() {
        Intent intent = Intent['qa'].get(1)
        println intent.title
    }
}
```

If I do without a specified environment for example like `Intent.get(1)` I get the Intent from the default data source. It this supposed to be correct behavior?

**Comment by graemerocher** [comment]
Your mapping indicates the default data source is the default (it is first in the list) https://github.com/olavgg/simple_multi_data_source_failed_sample/blob/master/grails-app/domain/ai/boost/Intent.groovy#L15

Therefore everything seems to be working as expected.

**Comment by olavgg** [comment]
I was hoping that when I used the @Transactional annotation with a specific data source as argument, all my queries would default to it. But now I have to specify the data source two places. That is the confusing part :-)
But I see how this works now and the example by Sergio makes sence!
