### ISSUE TITLE
data binding doesn't convert Integer to Long

### ISSUE THREAD

**Issue by bp-FLN** [grails/grails-core#11140]
There is some odd binding behaviour:
A command object has a property that is declared as `List<Long>`. Grails properly binds this property if it has been send as either a String or as a list of Integer's. However, if the property is send as Integer, the value is _not_ converted to Long and the property in the command object essentially becomes a `List<Integer>`.

### Task List

- [x ] Steps to reproduce provided
- [] Stacktrace (if present) provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

* run the intellij http files from the Example Application

### Expected Behaviour

* all 3 requests should result in the property in the command object to be a list of Long's

### Actual Behaviour

* the Integer request sets the property in the command object to a list of Integer's

### Environment Information

- **Operating System**:  MacOS
- **Grails Version:** 3.3.4 & 3.1.15
- **JDK Version:** 1.8.0_121

### Example Application

- https://github.com/bp-FLN/commandObject

**Comment by jeffbrown** [comment]
If you leave Grails, command objects and the data binder out of it altogether and do something like this in Groovy...

```groovy
List<Long> someLongs = [1, 1, 2, 3, 5]
println someLongs*.class
```

```
[class java.lang.Integer, class java.lang.Integer, class java.lang.Integer, class java.lang.Integer, class java.lang.Integer]
```

You will see that each of the values in the list are of type `Integer`.

Is that the behavior you are reporting?

**Comment by ilopmar** [comment]
This is a bug and I think I've found the cause. I'm working on a test case and a fix and submit a PR once it's done.

**Comment by bp-FLN** [comment]
the http files can be found there: https://github.com/bp-FLN/commandObject/tree/master/http

actually passing a List of Integer's works.
the only case that is weird is when the value is send as a _single_ Integer (so _without_ a List)

**Comment by ilopmar** [comment]
@bp-FLN This weird behavior happens because the code used is not the same for list and single values.

**Comment by ilopmar** [comment]
PR sent: https://github.com/grails/grails-core/pull/11142

**Comment by jeffbrown** [comment]
> the only case that is weird is when the value is send as a single Integer (so without a List)

Got it.  Thanks for the clarification.
