### ISSUE TITLE
Update Grails build and Gradle plugins to use Gradle 5

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#11147]

**Comment by sdelamo** [comment]
I've created a branch to migrate to Gradle 5. 

https://github.com/grails/grails-core/tree/gradle-5

**Comment by sdelamo** [comment]
`grails-core` and plugins have been upgraded to Gradle 5. 

See: https://github.com/grails/grails-core/wiki/Grails-4-Upgrade

**Comment by supsup** [comment]
hi Sergio i notice in your gradle files and in a lot of grails documentation you guys still use compile with dependencies, i think that is going to be removed?

https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

https://github.com/aldoKelvianto/ImplementationVsCompile

should we be using compile still with G3 / G4 going forward?

**Comment by davidkron** [comment]
I think @supsup holds some valid concerns about the usage of deprecated dependency declarations instead of the modern versions (api, implementation, ...). The new variation was introduced in Gradle 3.4 which is over 2 (!) years old.

**Comment by jameskleeh** [comment]
@supsup @davidkron There are issues with the new versions with IDE support. Related https://github.com/micronaut-projects/micronaut-profiles/issues/124
