### ISSUE TITLE
Grails 4: Release GORM 7.0 Milestone

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#11150]

**Comment by ilopmar** [comment]
Upgraded to Grails 4 snapshot, Gradle 5, jdk8 & jdk11 and publishing snapshot artifacts and documentation (only for jdk8 executor)

https://travis-ci.org/grails/grails-data-mapping/builds/461331176

**Comment by sdelamo** [comment]
I've created a milestone in `gorm5-hibernate` to track the pending tasks there: 

https://github.com/grails/gorm-hibernate5/milestone/4
