### ISSUE TITLE
Grails 4: Fix Functional Tests

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#11152]
The functional tests should also run on Java 11 on Travis

**Comment by ilopmar** [comment]
I've created a milestone to group related tasks in `grails3-functional-tests` project:

https://github.com/grails/grails3-functional-tests/milestone/1

**Comment by sdelamo** [comment]
Test are now passing. 

There is one test that I have annotated with `@PendingFeature` which verifies a fixed that has been commited to GORM but no GORM release with the fix has been yet published. 

https://github.com/grails/grails3-functional-tests/commit/19c34209a06239da49d42e29dd8450490fa7177f
