### ISSUE TITLE
Grails 4: Upgrade and verify Spring Security plugins work

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#11154]

**Comment by theiosdevguy** [comment]
Hello Grails Team,

Could you please provide any update on this? I am using Spring Security Rest with Grails 3.3.9 and want to upgrade to Grails 4. This depends on whether Spring Security Rest and Core are completely supported by Grails 4. Could you please confirm.

Thanks

**Comment by jameskleeh** [comment]
core and rest have been updated
