### ISSUE TITLE
ControllerUnitTest NullPointerException for service-call in private method (3.3.9)

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11198]
Symptom discovered during migration of web-application from Grails v2.4.4 to v3.3.5, symptom still present in Grails v3.3.9.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. clone example repo.
```
git clone git@github.com:dlehammer/grails-core-issues-11198.git
```

2. run `test-app`
```
my-webapp$ ./grailsw test-app --stacktrace --info
```

3. open test-report, notice how unit-test using direct invocation of `private` method `MyController.commonLogic()` has failed with NPE.
The unit-test using indirect invocation via `MyController.index()` succeeds.

### Expected Behaviour

The `ControllerUnitTest` is expected to be consistent during invocation, regardless of method modifier on controller method.
As it's sensible to unit-test logic in the smallest possible unit.

Ie. in the application where this symptom was discovered, the `commonLogic()`-method equivalent is shared across multiple entry-points in the Controller.
And having only 1 unit-test covering `commonLogic()` eases maintainability.

### Actual Behaviour

`MyControllerSpec.test commonLogic` unit-test fails with NPE, as `fooService` unexpectedly is `null`.

```
java.lang.NullPointerException: Cannot invoke method serviceMethod() on null object
	at my.webapp.MyController.commonLogic(MyController.groovy:12)
	at my.webapp.MyControllerSpec.test commonLogic(MyControllerSpec.groovy:35)
```

During debugging it's possible to see the symptom, as `fooService` is `null`.
![screenshot from 2018-12-06 18-23-00](https://user-images.githubusercontent.com/17439718/49601668-c3295580-f986-11e8-9f82-bf6594d48d0d.png)

Further analysis seems to suggest that the controller-instance isn't the same depending on invocation of controller method.
Notice how `controller.handler.controller.fooService` is a mock as expected.
![screenshot from 2018-12-06 18-23-31](https://user-images.githubusercontent.com/17439718/49601683-cd4b5400-f986-11e8-8a75-d9ee47d58053.png)

(I've tried, unsuccessfully, to access `controller.handler.controller` in-order to workaround the NPE and test isolated)

### Workaround

Call `private` method indirectly through a `public` method.

### Environment Information

- **Operating System**: Ubuntu 16.04 (64-bit)
- **Grails Version:** 3.3.9
- **JDK Version:** OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/dlehammer/grails-core-issues-11198

**Comment by jameskleeh** [comment]
Where is the test?

**Comment by dlehammer** [comment]
@jameskleeh my apologies, I linked to the wrong repo by mistake.

This [repo](https://github.com/dlehammer/grails-core-issues-11198) contains the symptom.

**Comment by jameskleeh** [comment]
Try overriding this method and returning true

https://github.com/grails/grails-testing-support/blob/master/grails-web-testing-support/src/main/groovy/grails/testing/web/controllers/ControllerUnitTest.groovy#L90

**Comment by dlehammer** [comment]
Overriding `ControllerUnitTest.disableControllerProxy()` to return `true` adresses NullPointerException symptom for private method invocation.

Ie. [workaround](https://github.com/dlehammer/grails-core-issues-11198/commit/7aa3a1f0c1343db0a73af5719a510c157796f68d) looks like this.

```
...

class MyControllerSpec extends Specification implements ControllerUnitTest<MyController> {

...

    @Override
    boolean disableControllerProxy() {
        return true
    }

...

    /**
     * Direct invocation works as expected
     */
    void 'test commonLogic'() {
        given:
            String bar = 'bar'

        when:
            controller.commonLogic()

        then: "expect commonLogic return value to be present"
            response.text == bar

            1 * fooService.serviceMethod() >> bar
            0 * _._
    }

}
```

The `disableControllerProxy` doesn't have any Javadoc documentation, and as such I assumed it was for internal Grails usage.

Searching for `disableControllerProxy` revaled a duplicate [Issue Testing Non Public Controller Methods](https://github.com/grails/grails-testing-support/issues/16), where somebody comments

> Yes - I've already updated the docs locally

`disableControllerProxy` is also metioned in the [documentation](http://testing.grails.org/1.1.5/guide/index.html#unitTestingControllers), but only in regards to JSON unit-test.

So perhaps this isn't a bug, but a documentation issue :)

**Comment by jameskleeh** [comment]
Well the only reason to implement the feature was related to JSON views. The documentation already has a blurb about it https://testing.grails.org/latest/guide/index.html#unitTestingControllers
