### ISSUE TITLE
grails 3.3.x (x=0..9) fails with Maps on domain objs

### ISSUE THREAD

**Issue by chka** [grails/grails-core#11195]
I've created a test project to demo this strange behavior. The demo is here: https://github.com/chka/failsMaps

It's a very simple domain object:

```
package com.example
class Person {
    String name
    Map prefs = [:]

    static constraints = {
	     name nullable: true, blank: true
       prefs nullable: true, blank: true
    }
}
```
Up to here, everything works perfectly but if a single entry is entered via bootstrap (or otherwise):

```
def init = { servletContext ->
      Person p = new Person()
      p.name = "John Doe"
      p.prefs = ["v":'{"fname": "John", "lname": "Doe"}']
      p.save()
    }
```
and you can't even see the index of that controller. It gives an exception like this:

`Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/person/index.gsp:21] Error executing tag <f:table>: [views/templates/_fields/_table.gsp:18] Error executing tag <f:display>: Cannot get property 'propertyName' on null object] with root cause`

**Comment by jameskleeh** [comment]
This issue belongs to the fields plugin. Please file an issue there https://github.com/grails-fields-plugin/grails-fields
