### ISSUE TITLE
Release gorm-graphql for GORM 7

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#11197]
https://github.com/grails/gorm-graphql

**Comment by dashingly** [comment]
Is this the only thing blocking Grails 4.0?
Is it being worked on?
Do you need new contributors?

**Comment by jameskleeh** [comment]
@dashingly Grails 4 has been released so this did not block the release. It is not being worked on right now. Your contributions are welcome!

**Comment by bobbywarner** [comment]
This has been released (currently 2.0.0) -- http://plugins.grails.org/plugin/grails/gorm-graphql-plugin
