### ISSUE TITLE
Resolve errorGrails: obtaining dependencies: Could not transfer artifact org.grails.plugins:tomcat:zip:8.0.22

### ISSUE THREAD

**Issue by swaroopsg** [grails/grails-core#11203]
Hi am on grails.2.5.0 and trying to synchronize plugins with grails sdk. am facing the following issue,

Resolve error obtaining dependencies: Could not transfer artifact org.grails.plugins:tomcat:zip:8.0.22 from/to grailsCentral (https://repo.grails.org/grails/plugins): Received fatal alert: protocol_version (Use --stacktrace to see the full trace)

looks like it is unable to access https://repo.grails.org/grails/plugins. I am not on a firewall or anything and through browser i can access this repo but if i ping the same through terminal am getting error.

Can anybody help me resolving this issue.

**Comment by smakela** [comment]
This is just an ssl issue (TLS 1.2). TLS 1.2 is not on by default in JDK 1.7.0_130 and below.

https://www.oracle.com/technetwork/java/javase/7u131-relnotes-3338543.html

Easy fix would be to upgrade your java version to 1.7.0_131 or above where TLS 1.2 is on by default.
But to get that JDK you need to have support from Oracle.

Also adding -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 as parameter for example compile process works for me (I have older 1.7 JDK) .

grails compile -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

Or just upgrade to Java 8

@graemerocher or someone in the Grails team can close this issue
