### ISSUE TITLE
Grails 4: Upgrade webpack and react-webpack profiles

### ISSUE THREAD

**Issue by ilopmar** [grails/grails-core#11219]
The Node gradle plugin is not compatible with Gradle 5 (or Gradle 4.x):
- https://github.com/grails-profiles/react-webpack/issues/4
- https://github.com/grails-profiles/webpack/issues/4

**Comment by iorabi** [comment]
I don't see react-webpack profile in Grails 4. Will it be available in the future?

**Comment by clessiomendes** [comment]
Profiles Deprecation
A few of the profiles supported in Grails 3.x will no longer be maintained going forward and as a result it is no longer possible to create applications when them in the shorthand form. When upgrading existing projects, it will be necessary to supply the version for these profiles.

org.grails.profiles:angularjs → org.grails.profiles:angularjs:1.1.2
org.grails.profiles:webpack → org.grails.profiles:webpack:1.1.6
org.grails.profiles:react-webpack → org.grails.profiles:react-webpack:1.0.8

https://docs.grails.org/4.0.3/guide/upgrading.html
