### ISSUE TITLE
Grails gradle integration with enabled option "pathingJar" breaks custom JavaExec tasks

### ISSUE THREAD

**Issue by davidkron** [grails/grails-core#11222]
I created some custom gradle task based on **JavaExec with the classpath configured to a custom configuration**. This task is used in other non-grails gradle projects and works flawlessly.

The problem is caused by the grails gradle integration, strictly speaking by the enabled pathingJar option. It seems that the option overrides the classpath of **every (!) JavaExec task**. In my option this not an expected behavior and might even be dangerous and break 3rd party plugins.

These are the relevant parts of this Gradle task:
```
ext {
    cxfVersion = '3.2.7'
}

configurations {
    cxf
}

dependencies {
    ...
	
    cxf "org.apache.cxf:cxf-tools-common:$cxfVersion"
    cxf "org.apache.cxf:cxf-tools-wsdlto-core:$cxfVersion"
    cxf "org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:$cxfVersion"
    cxf "org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:$cxfVersion"
}

grails {
    pathingJar = true
}

task wsdl2java(type: JavaExec) {
    main = 'org.apache.cxf.tools.wsdlto.WSDLToJava'
	
    // this configuration gets overriden by the grails gradle integration
    classpath = configurations.cxf
}
```

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `grails create-app`
2. set grails option `pathingJar = true`
3. create a custom gradle configuration with dependencies
4. create custom gradle task based on JavaExec
5. set classpath based on the custom configuration

### Expected Behaviour

Task should execute flawlessly like in any non-grails gradle project.

### Actual Behaviour

```
gradlew wsdl2java
:pathingJar UP-TO-DATE
:wsdl2java
Fehler: Hauptklasse org.apache.cxf.tools.wsdlto.WSDLToJava konnte nicht gefunden oder geladen werden
:wsdl2java FAILED
```

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.3.9
- **JDK Version:** JDK 8

**Comment by jameskleeh** [comment]
@davidkron What is your suggestion to resolve the issue? 

https://github.com/grails/grails-core/blob/2484f24b1eccce3b42a3b3a04ebe067dfdeb7be9/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy#L632 Is the code in question

**Comment by davidkron** [comment]
I'm not a gradle expert, but I tried the following to see the affected tasks in a newly created Grails 3.3.9 application:

```
project.tasks.withType(JavaExec) {
    println "${it} -> ${it.class.canonicalName}"
}
```
which gives the following output:
```
task ':bootRun' -> org.springframework.boot.gradle.run.BootRunTask_Decorated
task ':console' -> org.gradle.api.tasks.JavaExec_Decorated
task ':runCommand' -> org.grails.gradle.plugin.commands.ApplicationContextCommandTask_Decorated
task ':runScript' -> org.grails.gradle.plugin.commands.ApplicationContextScriptTask_Decorated
task ':schemaExport' -> org.grails.gradle.plugin.commands.ApplicationContextCommandTask_Decorated
task ':shell' -> org.gradle.api.tasks.JavaExec_Decorated
task ':urlMappingsReport' -> org.grails.gradle.plugin.commands.ApplicationContextCommandTask_Decorated
```

As far as I understand the code from GrailsGradlePlugin, the if bracket has all tasks covered except bootRun:
https://github.com/grails/grails-core/blob/2484f24b1eccce3b42a3b3a04ebe067dfdeb7be9/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy#L632-L644

The problem seems to be the else bracket, where every other JavaExec-Task gets configured with the pathingJar. Could a solution be to just configure the **bootRun** task? Or would that break something else?

Another solution would be an option to explicitly mention the tasks which should be processed by the grails plugin, like:
```
grails {
    pathingJar = true
    pathingJarTasks = ['bootRun', 'myCustomTask']
}
```

**Comment by davidkron** [comment]
Another approach seems to be a solution like:
https://github.com/virgo47/gradle-classpath-jar-plugin

Here the classpath is modified by a TaskActionListener. This solution seems to be more stable, as it takes the effective classpath used by a Task and not a hard-coded value of compile and runtime like Grails does.

**Comment by satamas** [comment]
When pathing jar is enabled `bootRun.sourceResources` property is ignored and assets hot reload doesn't work. If I'm not mistaken, this is the same bug.
A've spent quite a lot of time solving this problem, so I'm leaving here my workaround, maybe it will help someone 
```
bootRun {
  sourceResources(sourceSets.main)
  if(Os.isFamily(Os.FAMILY_WINDOWS)) {
    dependsOn 'pathingJar'
    setClasspath(
      getProject()
        .files(new File(libsDir, "plugins-pathing-SNAPSHOT.jar"), getClasspath())
        .filter { !configurations.runtime.files.contains(it) }
    )
  }
}
```

**Comment by davidkron** [comment]
On newer projects I managed to get this to work by disabling the pathingJar feature from Grails completely and upgrading to Gradle 6+. Gradle has this featue now built-in when running on Windows and it works much better than the implementation from the grails-gradle-plugin.

So I am closing this issue.
