### ISSUE TITLE
karmaRun errors in blank angularjs profile application

### ISSUE THREAD

**Issue by mrobinet** [grails/grails-core#11227]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails create-app --profile=angularjs angularjs-app
2. cd angularjs-app
3. ./gradlew check

### Expected Behaviour

Tests produced by profile can be executed successfully.

### Actual Behaviour

An error is received:
```
$ ./gradlew check
:compileJava NO-SOURCE
:compileGroovy
:buildProperties
:processResources
:classes
:clientInstall
:karmaInit UP-TO-DATE
:nodeSetup
:karmaDependencies
:karmaGenerateConfig
:karmaRunE:\Projects\angularjs-app\node_modules\karma\lib\utils\json-utils.js:2
const {stringify} = require('flatted/cjs')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\Projects\angularjs-app\node_modules\karma\lib\server.js:14:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\Projects\angularjs-app\node_modules\karma\lib\cli.js:8:16)
    at Module._compile (module.js:435:26)
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':karmaRun'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 4.161 secs
```

### Environment Information

- **Operating System**: Windows 10 10.0 amd64
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8.0_181 (Azul Systems, Inc. 25.181-b02)
- **Container Version (If Applicable):** N/A

### Example Application

- N/A as it is easily reproducible with `grails create-app --profile=angularjs <app name>`

### Additional information

I'm running this with Git Bash, but get the same result with Powershell and Command Prompt. I've also tested on OS X with the same results:
- **Operating System**: Mac OS X 10.14 x86_64
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8.0_192 (Azul Systems, Inc. 25.192-b01)

I dug into the karma-gradle plugin a bit and it looks like it is doing [karma start &lt;karma config&gt; --single-run](https://github.com/craigburke/karma-gradle/blob/master/src/main/groovy/com/craigburke/gradle/KarmaPlugin.groovy#L84). The interesting thing is that I can run this command just fine directly:
```
$ node_modules/karma/bin/karma start build/karma.conf.js --single-run
PhantomJS 2.1.1 (Windows 8.0.0): Executed 7 of 7 SUCCESS (0.041 secs / 0.058 secs)
TOTAL: 7 SUCCESS
```

**Comment by bobbywarner** [comment]
This is not an issue with Grails 4.0.3 and the `angular` (https://github.com/grails-profiles/angular) profile.  

The `angularjs` (https://github.com/grails-profiles/angularjs) profile is no longer maintained.
