### ISSUE TITLE
[FEATURE REQUEST] upgrade to groovy 3

### ISSUE THREAD

**Issue by ayZagen** [grails/grails-core#11238]
Is it possible to upgrade groovy to version 3 ?

**Comment by graemerocher** [comment]
Groovy 3 is at alpha stage so no

**Comment by ayZagen** [comment]
that makes sense. Would it be implemented if it goes to stable ? Because there are lots of improvements that we are keen to use such as lambda syntax.

**Comment by graemerocher** [comment]
Yes once it is stable will be the time to upgrade
