### ISSUE TITLE
Grails 4 dbconsole ui not working

### ISSUE THREAD

**Issue by niravassar** [grails/grails-core#11232]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a grails 4 application: grails create-app sample-grails-upgrade
2. run grails run-app
3. Get the error:
    Error: Page Not Found (404)
    Path: /dbconsole

### Expected Behaviour

h2 dbconsole should occur on a runtime database

### Actual Behaviour

no page is found

### Environment Information

```
Operating System: Win 10
Grails Version: 4.0.0.BUILD-SNAPSHOT
JDK Version: 1.8.0_191
Container Version (If Applicable): none
```

**Comment by graemerocher** [comment]
Seems like Spring Boot now already includes H2 so I have removed our integration. It is available at `/h2-console` now. See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-sql-h2-console

We may wish to add this to the upgrade notes
