### ISSUE TITLE
grails 4 scaffold not rendering

### ISSUE THREAD

**Issue by niravassar** [grails/grails-core#11234]
On a fresh grails app with only one domain, the scaffold on the controller has an error in rendering in the html

http://localhost:8080/student

See sample app

https://github.com/niravassar/yourkit-grails-four

```
XML Parsing Error: undefined entity Location: http://localhost:8080/student Line Number 9, Column 75:
        <a href="#list-student" class="skip" tabindex="-1">Skip to content&hellip;</a>
--------------------------------------------------------------------------^
```

**Comment by graemerocher** [comment]
This seems to be a recent breaking change as the Hibernate tests that were previously passing are now failing due to this bug https://travis-ci.org/grails/gorm-hibernate5/builds/487484475
