### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [grails/grails-core#11230]
### Steps to Reproduce

1. Add the key value

cookies="Exptected Outcome is this sentence" 

to messages.properties

2. In some view output the value using 

${message(code: 'cookies')}

### Expected Behaviour

You would expect the view to display "Exptected Outcome is this sentence"

### Actual Behaviour

You will see "cookies"

### Environment Information

- **Operating System**: Debian Jessie
- **Grails Version:** 3.3.9
- **JDK Version:** 
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

- **Container Version (If Applicable):** The default Tomcat that ships with Grails 3.3.9

**Comment by jameskleeh** [comment]
Please upload an example project that reproduces the issue

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback
