### ISSUE TITLE
grails 4 spring boot development tools classloads two entities

### ISSUE THREAD

**Issue by niravassar** [grails/grails-core#11233]
create a plain jane grails 4 app and the devTools clause in build.gradle interferes with GORM

For a simple domain Student, when placed in the controller with @Transactional, I get errors for insert and find. I created the most simple app with a domain and Dataservice, and all the methods do not work.

However, I also created integration test and also unit test and the data service method works fine. I created a sample app that shows these errors. Note that this code when copied directly into a grails 3.3.9 app works fine and no errors.

See the sample app. 

https://github.com/niravassar/yourkit-grails-four

spring-boot-devtools is getting in the way by loading the class twice somehow. If you comment out the dependency in build.gradle all works fine

----
*from James*
```
from james
James Kleeh [3:36 PM]
There are 2 `demo.Student` classes on the classpath

You can put a breakpoint at `UnsafeFieldAccessorImpl` line 31
One is on the `RestartClassLoader`
One is on the `Launcher$AppClassLoader`
so this looks related to spring-boot-devtools
I verified it works with devtools commented out
```

**Comment by graemerocher** [comment]
Duplicates #11159 requires the snapshot of GORM 7
