### ISSUE TITLE
GRAILS-8463: Problems with BigDecimals having a scale higher then 3 (#1939)

### ISSUE THREAD

**Issue by nutmix** [grails/grails-core#11241]
The major issue in grails raised here in "GRAILS-8463: Problems with BigDecimals having a scale higher then 3 #1939" raised in 2011 has been closed without resolution or workaround.  

The problem is stll there in grails 3.3.8 (3.3.9 is not usable due to multi-module projects not working)

This problem is a show stopper - grails standard gsp tags and scaffolding has a bug which gets the number of decimal places wrong, and truncates data in the DB if the scale is greater than 3.

 ETH has 18 decimal places. BTC has 8. I can't find any way to support them without some major work.

The domain class has this:

```
    BigDecimal balance
    static constraints = {
        balance nullable: false, scale: 18, precision: 50
```

After setting the balance with say:
  
`  myDomain.balance = new BigDecimal("12345.12345678")`

If I print it, e.g.:

`  log.error "balance:" + myDomain.balance`

It comes out as "balance: 12345.12345670000000000" which is correct.

However, in the scaffolded or generated show, list and edit, it comes out as "12345.123"

If you submit an edit form, without even modifying the balance, it will overwrite the correct value in the DB with truncated value.

This is a show stopper for our entire project - 10 man months of work could be down the drain 

Note: by default grails was showing 2 DP. When I increased he scale to 18, it switched to showing 3 DP. This means there is some code in grails to read the scale, but it is broken (a bug?)

The issues is presumably in the code grails uses to implement the tags such as <f:table> and <f:display>, which we use everywhere.  To replace every view with every column done manually is man months of work, including all the testing.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

See code above, or issue #1939

### Expected Behaviour
Grails <f:table> and <f:display> etc. should honour the correct scale (number of decimal places), and certainly not truncate correct data.
.
Tell us what should happen
Grails <f:table> and <f:display> etc. should honour the correct scale (number of decimal places), and certainly not truncate correct data.

### Actual Behaviour
see description above.

Tell us what happens instead

### Environment Information

- **Operating System**: Mac OSX
- **Grails Version:** 3.3.8
- **JDK Version:** 1.8.0_131
- **Container Version (If Applicable):** No idea.

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jeffbrown** [comment]
> I can't find any way to support them without some major work.

FYI... The fields plugin does allow you to customize renders and input generators by providing your own templates.  For example, if you define a template at `grails-app/views/_fields/bigDecimal/_displayWidget.gsp`, the fields plugin will recognize that template and use it for generating display widgets for all `BigDecimal` properties.

**Comment by jeffbrown** [comment]
> The issues is presumably in the code grails uses to implement the tags such as <f:table> and <f:display>, which we use everywhere

You should file feature requests and bug reports for the `fields` plugin at https://github.com/grails-fields-plugin/grails-fields/issues.  

Thanks for your feedback!

**Comment by nutmix** [comment]
Thanks for the suggestions.  I found a workaround [here](https://devhobbs.wordpress.com/2019/02/11/grails-3-3-how-to-fix-rounding-and-truncation-of-bigdecimal-in-fields-plugin-with-scale-of-more-than-3/):

**Comment by jeffbrown** [comment]
@nutmix That article is suggesting the technique I mentioned above.  I am glad you have a solution.
