### ISSUE TITLE
Grails 4 create-controller errors on OpenJDK 11.0.2

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#11247]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

```bash
$ sdk use java 11.0.2-open
$ sdk use grails 4.0.0.M1
$ grails create-app foo && cd foo

$ grails create-controller Mail
| Error Error initializing classpath: Could not determine java version from '11.0.2'. (Use --stacktrace to see the full trace)
$ grails -v
| Grails Version: 4.0.0.M1
| JVM Version: 11.0.2
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### Expected Behaviour

Controller should be created.

### Actual Behaviour

Could not determine java version from '11.0.2'.

### Environment Information

- **Operating System**: MacOSX 10.14.3
- **Grails Version:** 4 M1
- **JDK Version:** OpenJDK 11.0.2
- **Container Version (If Applicable):** n/a

### Example Application

- n/a

**Comment by puneetbehl** [comment]
I think we might need to update the `gradleToolingApiVersion` to something `5.1.1` [here](https://github.com/grails/grails-core/blob/master/grails-shell/build.gradle#L11)
