### ISSUE TITLE
one line of css in main.css  breaks correct rendering of bootstrap views that use site mash (the default)  

### ISSUE THREAD

**Issue by woodmawa** [grails/grails-core#11240]
this is where i started from - issue posted to stackoverflow 
[issue ]](https://stackoverflow.com/questions/54592622/bootstrap-table-header-color-only-shows-when-cell-is-hovered-over)

see new comment below as i've created a new  dumbed down basic project that shows the problem 

### Steps to Reproduce

1. create new project 
2. add some div with boostrap table using coloured headers in bootstrap view e.g. 

`    <div class="row">
    <%--<div class="container-fluid col-sm-6" >--%>
    <div class="col-xs-4">

        <table class='table table-bordered table-striped table-condensed ' >

            <thead >
            <tr>
                <th class="bg-info text-white" scope="col">Tag</th>
                <th class="bg-info text-white" scope="col">Value</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td scope="row">hello</td>
                <td scope="row">william</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>`
3.page doesnt behave as expected, colours on headers dont render and js behaviour doesnt work as expected for bootstrap and date picker etc 

### Expected Behaviour

if i configure  table and colour headers i expect the page to work.  with default config in grails it doesnt 

### Actual Behaviour

behavior in css/js is weird or doesn't work.  Table header looks grey not coloured.  js doesn't fire to date time picker etc 

### Environment Information

- **Operating System**: windows10
- **Grails Version:3.3.9
- **JDK Version:v1.8.1
- **Container Version (If Applicable):n/a

### Example Application

[project](https://github.com/woodmawa/LCM-network-app)

added a plain view on one of controllers and removed all site mesh - this works see here 
[plain.gsp](https://github.com/woodmawa/LCM-network-app/blob/master/grails-app/views/maintenanceAgreement/plain.gsp)

then have an ordinary view with same html - but engages the site mesh - see 
[site mesh enabled ](https://github.com/woodmawa/LCM-network-app/blob/master/grails-app/views/maintenanceAgreement/ldt.gsp)

to make this work i tracked it down to one line in the main.css 

i've commented this out here - if you do that rendering works.  if you uncomment the line all the rendering starts to break 

`th {
    background-color: #efefef;
    background-image: -moz-linear-gradient(top, #ffffff, #eaeaea);
    /*background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #ffffff), color-stop(1, #eaeaea));*/
    filter: progid:DXImageTransform.Microsoft.gradient(startColorStr = '#ffffff', EndColorStr = '#eaeaea');
    -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#ffffff', EndColorStr='#eaeaea')";
    color: #666666;
    font-weight: bold;
    line-height: 1.7em;
    padding: 0.2em 0.6em;
}`

tomorrow i'll fix the bsf-main and using the <asset.  this seemed to stop working so locall include all the required cdn libraries directly in the head for now 

not sure why, its taken 4 days to narrow it down to this one line of css

**Comment by woodmawa** [comment]
I have created a stripped down version of grails project just to show the problem.  

see [simplified project](https://github.com/woodmawa/GrailsBootstrapProblemApp)

in this there is one controller, and two views, plain and smesh.

i've touched main.css at line 420 and 421 - at present line 421 is commented out so running the app and going to either problem/plain or problem/smesh both work as expected (smesh adds the headers/footers ) 

now remove the comments at line 421 and rebrowse problem/smesh and see what happens to the rendered output 

hope this simplified projects lets you see the problem more readily.

**Comment by jameskleeh** [comment]
I fail to see what any of this has to do with Grails.. The CSS is clearly being sent to the browser as you have it. Any issues with how it is rendering is between your CSS and the browser.

**Comment by jeffbrown** [comment]
> I fail to see what any of this has to do with Grails

It might not have anything to do with Grails.  I haven't looked into what is going wrong but the CSS mentioned in the bug report does exist in our default generated `main.css` file at https://github.com/grails-profiles/web/blob/e4edcf9e276928ac93d021fb0ab0863dd2954af3/skeleton/grails-app/assets/stylesheets/main.css#L420.  If it turns out that code is problematic for some reason, we may need to change that.

**Comment by jameskleeh** [comment]
@jeffbrown Agreed. If it can be determined that the line of CSS has no valid use today then we can remove it. That line has been there since 2014 so my assumption is that it is causing an issue specific to the users environment and is not a problem overall
