### ISSUE TITLE
main.css .property-list style clips bootstrap popups etc 

### ISSUE THREAD

**Issue by woodmawa** [grails/grails-core#11244]
Was seeing clipping on bootstrap forms pop ups/dropdowns 

see [stackoverflow](https://stackoverflow.com/questions/54619736/grails-fields-plugin-fdisplay-is-chopping-off-bootstrap-dropright-action-wit)

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. produce any standard grails v 3.3.p application.  
2. add domain class items for which you want to do dropdown rendering for (e.g. map entries ) as last entry in the domain class (ie will be bottom of form )
3. create controller, and standard scaffolded views 
4. render page in browser (with and see how the drop down is clipped

### Expected Behaviour

your drop downs should not be clipped 

### Actual Behaviour

drop down is clipped and wont render all details 

### Environment Information

- **Operating System**: windows 10
- **Grails Version:** 3.3.9
- **JDK Version:** v1.8.181
- **Container Version (If Applicable):** n/a
### Example Application

- TODO: [sample project](https://github.com/woodmawa/LCM-network-app)

took a long time but eventually traced to one line of style in main.css at line 215.  Fields plugin provides a default _list.gsp that renders a list of attributes as an <ol class="property-list">

when you look in main.css you can see the there is a line at 217 that has overflow:hidden; as default.

that single line stops the dropdown/pop up from rendering fully.  if you comment that out your bootstrap templates with dropdowns etc will start to work correctly - see stackoverflow for more detail 

recommend that this default is removed.  This was really hard to trace.

also think the fields plugin needs lot better words on concepts and how its structured.  I just lost two days trying to get through all this, including having to clone fields plugin - so i could trigger out what was calling what in what order.  also <f;all action is very different from <f:display they dont use the same decision logic so the behaviours are consistent.

**Comment by jeffbrown** [comment]
> ...think the fields plugin needs lot better words on concepts and how its structured.

That doesn't really have much to do with `grails-core`.  Feature requests and bug reports for the plugin should be reported at https://github.com/grails-fields-plugin/grails-fields/issues.  Pull requests are welcome at https://github.com/grails-fields-plugin/grails-fields/pulls.

Thanks for your feedback.

**Comment by bobbywarner** [comment]
Closing.  As mentioned above, please report the issue with the `grails-fields` plugin.
