### ISSUE TITLE
Missing Jars in repo.grails.org

### ISSUE THREAD

**Issue by HybridProgrammer** [grails/grails-core#11252]
The splunk-library-javalogging dependency used to be in repo.grails.org, I noticed a lot of empty directories too. Is the sync off?

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

http://repo.spring.io/plugins-release/com/splunk/logging/splunk-library-javalogging/1.5.4/ (populated)

vs

https://repo.grails.org/grails/core/com/splunk/logging/splunk-library-javalogging/1.5.4/ (empty)

1. sdk use grails 3.3.9
2. grails create-app grepoissue
3. vi build.gradle
4. dependencies { compile 'com.splunk.logging:splunk-library-javalogging:1.5.4' }

### Expected Behaviour

BUILD SUCCESSFUL

### Actual Behaviour

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'grepoissue'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not find com.splunk.logging:splunk-library-javalogging:1.5.4.

### Environment Information

- **Operating System**: macOs
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8.0_181
- **Container Version (If Applicable):** n/a

### Example Application

- https://github.com/HybridProgrammer/grepissue

### Workaround
add maven { url "http://repo.spring.io/plugins-release/" } to repo list

`repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "http://repo.spring.io/plugins-release/" }
}`

**Comment by davydotcom** [comment]
plan is to move things to `jcenter()` by default instead of relying on a dedicated `repo.grails.org`
