### ISSUE TITLE
gradle assemble produces jar that causes stacktrace when UI accessed

### ISSUE THREAD

**Issue by sbortman** [grails/grails-core#11251]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails create-app foobar
2. cd foobar
3. remove war plugin from build.gradle
4. gradle assemble
5. java -jar build/libs/foobar-0.1.jar
6. open http://localhost:8080 in browser

### Expected Behaviour

See standard Grails page for any new app

### Actual Behaviour

HTTP Status 500  - Internal Error page in browser
Stacktrace in console (attached)

### Environment Information

- MacOSX Mojave
- 4.0.0.M1
- JDK 8u201 and 11.0.2
[stacktrace.txt](https://github.com/grails/grails-core/files/2886707/stacktrace.txt)

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
Seems to be a bug in the GSP gradle plugin because the compiled GSPs are not in the JAR
