### ISSUE TITLE
4.0.0.M1 / gradle 5 - global configuration excludes leak into plugin maven pom

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#11257]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a plugin
2. add a dependency (e.g. `compile "org.springframework:spring-messaging:5.1.5.RELEASE"`)
3. run `gradle(w) generatePomFileForMavenPublication`
4. check `build/publications/maven/pom-default.xml`

### Expected Behaviour

the dependency should not have any exclusions in the pom file, i.e.:
```xml
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-messaging</artifactId>
  <version>5.1.5.RELEASE</version>
  <scope>compile</scope>
</dependency>
```

### Actual Behaviour

the dependency has grails-specific exclusions that are not related to the actual dependency:
```xml
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-messaging</artifactId>
  <version>5.1.5.RELEASE</version>
  <scope>compile</scope>
  <exclusions>
    <exclusion>
      <artifactId>grails-plugin-async</artifactId>
      <groupId>org.grails</groupId>
    </exclusion>
    <exclusion>
      <artifactId>grails-plugin-events</artifactId>
      <groupId>org.grails</groupId>
    </exclusion>
    <exclusion>
      <artifactId>grails-plugin-converters</artifactId>
      <groupId>org.grails</groupId>
    </exclusion>
    <exclusion>
      <artifactId>grails-plugin-gsp</artifactId>
      <groupId>org.grails</groupId>
    </exclusion>
    <exclusion>
      <artifactId>grails-plugin-testing</artifactId>
      <groupId>org.grails</groupId>
    </exclusion>
  </exclusions>
</dependency>
```

### possible cause

i think the exclusions are defined here: https://github.com/grails/grails-core/blob/v4.0.0.M1/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy#L186-L189

and i would guess this is likely due to a change of behavior by gradle(-5)?

### workaround

what i am currently doing is this (`build.gradle`) :(
```groovy
publishing {
    publications.first().pom.withXml {
        asNode().dependencies.dependency.exclusions*.replaceNode {}
    }
}
```

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 4.0.0.M1
- **JDK Version:** 8u131
- **Container Version (If Applicable):** n/a

### Example Application

- `grails-spring-websocket-2.5.0.M1` is using the described workaround here: https://github.com/zyro23/grails-spring-websocket/commit/a305117037f26e0c56ea9dafe871eb8a2c1b3362#diff-c197962302397baf3a4cc36463dce5eaR44

**Comment by graemerocher** [comment]
The code in question was put in place to make it easier to upgrade from 3.1.x to 3.3.x. Since the expectation is most people will upgrade from 3.3.x to 4.x I have simply removed it

**Comment by zyro23** [comment]
thank you!
