### ISSUE TITLE
Grails 3 run-command unable pass arguments with "-" option

### ISSUE THREAD

**Issue by vineeln** [grails/grails-core#11258]
### Steps to Reproduce

1. grails create-controller sample
2. Here is the SampleCommand.groovy

```
import grails.core.GrailsApplication
import grails.dev.commands.GrailsApplicationCommand

class SampleCommand implements GrailsApplicationCommand {
    GrailsApplication grailsApplication
    boolean handle() {
        grailsApplication.config.mydomains

        System.out.println("Raw args:" + executionContext.commandLine.getRawArguments())
        System.out.println("RemainingArgs: " + args);
        System.out.println("RemainingArgs with Options:" + executionContext.commandLine.getRemainingArgsWithOptionsString() )
        System.out.println("Undeclared Options:" + executionContext.commandLine.getUndeclaredOptions() )
        System.out.println("System properties:" + executionContext.commandLine.getSystemProperties() )

       // **this doesn't work ..**
        if( executionContext.commandLine.hasOption('db') ) {
            String dbName=executionContext.commandLine.optionValue(db);

            // doWithDBName
        }
        return true;
    }
}
```
```
3. grails run-command sample arg1 arg2 -db=localdb arg4
```

### Expected Behaviour

I was hoping to be able to check if **"-db**" was passed using **"hasOption()"** api and access the value of "-db" option using **"optionValue( )"**

### Actual Behaviour

Can't see the "-db=localdb" in either "Raw Args" or "Args" or "Declared Options", "System.properties". Here is the output, i can access all the arguments except the ones that were passed with "-"

```
Raw args:[sample, arg1, arg2, arg4]
Remaining Args: [arg1, arg2, arg4]
Remaining Args with Options:arg1 arg2 arg4
Undeclared Options:[:]
System properties:[:]
```

### Environment Information

- **Operating System**: MAC
- **Grails Version:**3.3.7
- **JDK Version:**1.8
- **Container Version (If Applicable):**

**Comment by jacobmarcus** [comment]
The following works when I tested directly with the CommandLineParser. So I think this may be bug?

`       CommandLineParser p1 = new CommandLineParser();
        CommandLine cl = p1.parseString("sample", "arg1 arg2 -db=localdb arg4");
        Map<String, Object> map = cl.getUndeclaredOptions();
        for(String option: map.keySet()){
            System.out.println((String)map.get(option));
        }`

**Comment by vineeln** [comment]
any thoughts on when this might be fixed?  are there any workarounds ?

**Comment by appu-wavelabs** [comment]
Any updates on this?

**Comment by ravikovour** [comment]
This is an high priority defect as we can not read a system property like System.getProperty("foo")
Is there any workaround for this ?

**Comment by niravassar** [comment]
I am looking at this issue and I see that when executing a command such as this:

`grails run-command simple -db=myDatabase` 

along with the line in a command:

`println "**** EXECUTION CONTEXT:" + executionContext.commandLine.dump()`

the output is 

```**** EXECUTION CONTEXT:<org.grails.build.parsing.DefaultCommandLine@49b9ba6a systemProperties=[:] undeclaredOptions=[:] declaredOptions=[:] remainingArgs=[] environment=null commandName=simple rawArguments=[simple]>```

I agree this means that the options are not being parsed and it may be a bug, i will look into it further.

in the meantime, to address the workaround question, you can always just pass in an arguments and get it from the arguments list. Another option is just place a configuration item in `application.yml` and retrieve it like this: `String value = grailsApplication.config.getProperty('foo')`.  

```
package grails.command

import grails.core.GrailsApplication
import grails.dev.commands.*

class SimpleCommand implements GrailsApplicationCommand {

    GrailsApplication grailsApplication

    boolean handle() {
        String value = grailsApplication.config.getProperty('foo')
        println "**** VALUE:" + value
        println "**** EXECUTION CONTEXT:" + executionContext.commandLine.dump()
        return true
    }
}
```

**Comment by niravassar** [comment]
I found that if you run this the option will be read. I am looking into why the `grails` command does not capture the option:

`gradlew runCommand -Pargs="simple arg1 arg2 -something=vats"
