### ISSUE TITLE
MongoSpec and GrailsWebUnitTest confiict

### ISSUE THREAD

**Issue by mortensoby** [grails/grails-core#11270]
### Steps to Reproduce

1. Create a new Grails 4 project with rest-api profile and MongoDb feature (grails create-app mongodb-example --profile rest-api --features mongodb)
2. Create a controller
3. Create a controller unit test - class `FilingControllerSpec extends MongoSpec implements ControllerUnitTest<FilingController>`  

### Expected Behaviour

The project can be compiled and the test executed

### Actual Behaviour

A compilation error occurs 
` -1: The return type of org.springframework.mock.web.MockHttpSession getSession() in dk.mydomain.FilingControllerSpec is incompatible with org.grails.datastore.mapping.core.Session in grails.test.mongodb.MongoSpec
. At [-1:-1]  @ line -1, column -1.
1 error`

I can se why this happens since the class gets the `grails.testing.web.GrailsWebUnitTest#getSession` from the unit test trait and the `grails.test.mongodb.MongoSpec#session` from the MongoSpec class. 
This works fine i grails 3.3.0 for some reason.
### Environment Information

- **Operating System**: Ubuntu 18.04.02 LTS
- **Grails Version:** 4.M1
- **JDK Version:** Zulu 8.34.0.1-CA-linux64

### Example Application
https://github.com/mortensoby/mongo-bug

**Comment by niravassar** [comment]
This the same problem encountered in the guide for grails upgrade: https://github.com/grails-guides/rest-mongodb/pull/5

**Comment by graemerocher** [comment]
Seems like Groovy is not stricter about checking return types and the libraries will have to be changed. Most likely `MongoSpec`'s method signature needs to change

**Comment by mortensoby** [comment]
I copied the MongoSpec and changed the name of the session-field to mongoSession and it works fine.

**Comment by mortensoby** [comment]
I created a pull request which solves the problem here: https://github.com/grails/gorm-mongodb/pull/96

**Comment by graemerocher** [comment]
Thanks
