### ISSUE TITLE
Redos attack happens when JSON parsing thrown exception

### ISSUE THREAD

**Issue by kevinclcn** [grails/grails-core#11271]
With Grails 3.3.7, when I post a huge one line JSON which contains syntax error, the request.JSON will hang forever. 

```json5
{"id":0 waitfor delay'0:0:20'-- ,"status":"draft","name":"test","description":"","dateCreated":"2019-02-25T18:08:27Z","createdByName":"me".............
```

After debugging, I found it hangs at this line 

https://github.com/grails/grails-core/blob/3a0957ad5e31632a0f49d8b7f1a9fd9f332acd0a/grails-web-common/src/main/groovy/org/grails/web/errors/GrailsWrappedRuntimeException.java#L114

[This regex pattern](https://github.com/grails/grails-core/blob/3a0957ad5e31632a0f49d8b7f1a9fd9f332acd0a/grails-web-common/src/main/groovy/org/grails/web/errors/GrailsWrappedRuntimeException.java#L63) causes the [Redos attack](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS)

**Comment by graemerocher** [comment]
Please provide an example that reproduces the problem with steps to reproduce

**Comment by rvanderwerf** [comment]
I have a fix for this in progress at https://github.com/grails/grails-core/pull/11304
