### ISSUE TITLE
GrailsCompileStatic fails with lock method in Criteria Closure

### ISSUE THREAD

**Issue by neilabdev** [grails/grails-core#11272]
Thanks for the great work! Basically, for a plugin I was writing, I noticed that @GrailsCompileStatic doesn't work in criteria DSL closure when lock is specified. While not a show stopper, just thought I'd take the time to log it.

### Steps to Reproduce

Using any criteria statement where you want to lock the results, such as provided in your example in grails documentation:

```
def airport = Airport.createCriteria().get {
    eq('name', 'Heathrow')
    lock true
}
```

Though in my case, its more like:

```
def airports = Airport.createCriteria().list(order: "desc",  {
    eq('name', 'Heathrow')
    lock true
})
```

### Expected Behavior

The service method should be statically compiled without issue.

### Actual Behavior

You receive error:

```
[Static type checking] - Cannot find matching method com.package.MyService#lock(boolean). Please check if the declared type is right and if the method exists.
 @ line 46, column 17.
                   lock true  
```
 
### Environment Information

- **Operating System**: Mac Mojava
- **Grails Version:** 3.2.13
- **JDK Version:** 1.8.0_191 

### Example Application

See: http://gorm.grails.org/6.0.x/hibernate/manual/index.html#locking

**Comment by niravassar** [comment]
Can you attach an example application to demonstrate the problem

**Comment by niravassar** [comment]
I have verified that the @GrailsCompileStatic doesnt cover the `lock` in gorm.  I did it in 3.2.13, 3.3.9 and also grails 4.0.0.BUILD-SNAPSHOT. 

The easy workaround is to just use @GrailsCompileStatic where necessary on methods and avoid it on GORM dsls. You could also opt for an hql query, a dynamic query with the lock variable passed in, or also just use the Criteria API.

I dont think this is a high priority item or has much impact. Thank you for the notice however. I will leave it open if someone wants to look into it further.

**Comment by neilabdev** [comment]
@niravassar  Please forgive my delay in getting back with you, as I meant to create a new project to recreate the issue as it occurred in my client code, but had had an opportunity as yet. Thanks for verifying this, and offering your suggestions, which I believe a workable alternative. Thx!
