### ISSUE TITLE
Add null safety for any use of ReaderSource.getURI()

### ISSUE THREAD

**Issue by AntonPanikov** [grails/grails-core#11278]
### Task List

- [ ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Environment Information

- **Grails Version:** 3.2.x

I am helping troubleshooting GRECLIPSE plugin issue: https://github.com/groovy/groovy-eclipse/issues/850

It looks like [MainClassFinder.groovy](https://github.com/grails/grails-core/blob/3.2.x/grails-bootstrap/src/main/groovy/org/grails/io/support/MainClassFinder.groovy) is not null safe enough. URI path is coming from [ReaderSource.java](https://github.com/apache/groovy/blob/master/src/main/java/org/codehaus/groovy/control/io/ReaderSource.java)
from
[IntegrationTestMixinTransformation.groovy](https://github.com/grails/grails-core/blob/3.2.x/grails-plugin-testing/src/main/groovy/org/grails/compiler/injection/test/IntegrationTestMixinTransformation.groovy)

and for example this two implementations of ReaderSource:
[StringReaderSource.java](https://github.com/apache/groovy/blob/master/src/main/java/org/codehaus/groovy/control/io/StringReaderSource.java)
and
[InputStreamReaderSource.java](https://github.com/apache/groovy/blob/master/src/main/java/org/codehaus/groovy/control/io/InputStreamReaderSource.java)
is returning null, the first one at some conditions, the second one - always.

Missing null safety causing NPE in GRECLIPSE current implementation

Partial stack trace will look like this:
```groovy
Caused by: java.lang.NullPointerException
	at org.grails.io.support.MainClassFinder.searchMainClass(MainClassFinder.groovy:38)
	at org.grails.compiler.injection.test.TestMixinTransformation.visit(TestMixinTransformation.java:113)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:197)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:258)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1143)
	... 8 more
```

**Comment by ddelponte** [comment]
@AntonPanikov, the last comment on the ticket at https://github.com/groovy/groovy-eclipse/issues/850 is:

> Verified on:
> 3.3.0.xx-201903212137-e1809
> 
> No issue, no errors. Thanks!

Can this ticket be closed or is it still an issue?

**Comment by AntonPanikov** [comment]
The other issue was fixed in: https://github.com/groovy/groovy-eclipse/issues/850
But I think it was a workaround about the fact that MainClassFinder.groovy may throw NPE, while it should not. This issue was about providing more null safe code for the future versions of grails, that might or might not bite back at some point, see my original comment. It is up to you guys to do something about it or not.

Thanks!

**Comment by ddelponte** [comment]
PR created: #11323
