### ISSUE TITLE
Grails Scaffolding Update Constraint UI Bug

### ISSUE THREAD

**Issue by pleonar3** [grails/grails-core#11280]
### Steps to Reproduce

1. Create a grails app, or clone the repo.
2. Create a domain class with a unique constraint property.
3. Create two objects with different property values. Now, update one of the objects to have the same value as the other. Observe what happens when the object is persisted.

### Expected Behaviour

You should receive the standard grails property constraint error message when the web response is received.

### Actual Behaviour

The update errors silently. The property is flipped back to its original value, the user is not notified of the error at all.

### Environment Information

- **Operating System**: Ubuntu 18
- **Grails Version:** 3.3.8
- **JDK Version:** openjdk version "1.8.0_172"

### Example Application

- [repo](https://github.com/pleonar3/grails-constraint-bug-scaffold-update)

**Comment by niravassar** [comment]
i did the exact same thing in 3.2.13 and we go the correct response in the error message. This means somewhere in between it broke. i will look further

**Comment by niravassar** [comment]
**WORKAROUND**

In the sample project, if you delete `ConstraintUpdateHeadacheController`, then run `grails generate-all app.ConstraintUpdateHeadacheController`, it will generate the Controller code and also the gsp pages, along with a DataService interface. Run the steps again to create two objects with different values and save them. Then again change one object to the unique value. This will generate the correct message.  Use this as a workaround.

The issues seems to be with the runtime generation of the gsps of teh scaffold. I have tests this with service methods and when a unique value is saved, the error is generated properly in the domain object. when i render the errors back manually to the screen it will appropriately display the unique property error generated by the Gorm exception.

We will look to see what the error is in the scaffold code.

**Comment by niravassar** [comment]
This issue is not a pressing issue, although it is a bug. I recommend we go with the workaround. I'll keep this issue open if someone wants to look into it further. Thank you
