### ISSUE TITLE
Grails 4 missing grails-plugin-testing dependency

### ISSUE THREAD

**Issue by sjrd218** [grails/grails-core#11293]
There seems to be a missing dependency in the grails maven repo for the dependency `org.grails:grails-plugin-testing:` for grails 4.0.0.M2

### Steps to Reproduce

Create a gradle multi project with a grails app and a grails plugin.
Write a test in the plugin.

Try to run a gradle build
For full debug run `gradle build --scan`

### Expected Behaviour

Dependency should resolve

### Actual Behaviour

Gradle can't find the dependency for: org.grails:grails-plugin-testing:
Gradle build fails

### Environment Information

- **Operating System**: OS X
- **Grails Version:** Grails 4.0.0 M2
- **JDK Version:** JDK 1.8.181

### Example Application

https://github.com/sjrd218/BigProject

**Comment by graemerocher** [comment]
That module is no longer supported / needed and has been replaced by https://testing.grails.org/latest/guide/index.html

**Comment by sjrd218** [comment]
@graemerocher  Then the `grails create-plugin` command needs to stop creating plugins with that dependency in the `build.gradle`

**Comment by graemerocher** [comment]
Good point. I see the issue is with https://github.com/grails-profiles/plugin/blob/master/profile.yml
