### ISSUE TITLE
findAllByInList Sql more(grails3.3.9 )WHY

### ISSUE THREAD

**Issue by zhangjiayu139** [grails/grails-core#11299]
![NAH@K6R~Y6 ~0)}XIGM1AUP](https://user-images.githubusercontent.com/30860538/56073446-a4284d80-5dd6-11e9-9882-9f296ffc8fc6.png)

**Comment by graemerocher** [comment]
As specified in 

https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

Issues should provide:

* Steps to reproduce
* Stacktrace (if present) provided
* Example that reproduces the problem uploaded to Github
* Full description of the issue provided

If the issue report is not submitted correctly it will be rejected.
