### ISSUE TITLE
Grails 3.3.7 internal forward to a controller and action without url-mapping causing 404

### ISSUE THREAD

**Issue by appu-wavelabs** [grails/grails-core#11296]
###  Grails 3.3.7
When we are using internal forward to a controller and action without UrlMapping causing 404.
sample code 
```
package com.grails

class UrlMappings {
    static mappings = {
        "/home/$action"(controller:"home")
        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}
```
```
package com.grails

class HomeController {

    static defaultAction = 'index'

    def index() {
        render view: 'index'
    }

    def doForward(Integer max) {
       // doesn't forwarding to the given controller and action. Bcz we don't having URL mapping
        forward(controller: 'some', action: 'index')
    }

}
```
```
package com.grails

class SomeController {

    static defaultAction = 'index'

    def index() {
        render view: 'index'
    }
}
```

### Expected Behaviour
 - http://localhost:8080/home/index **should work and it is working** 
- http://localhost:8080/home/doForward **should forward to some/index.gsp not working**

### Actual Behaviour

- http://localhost:8080/home/doForward 
- causing 404

### Environment Information

- **Grails Version:** 3.3.7
- **Groovy Version**: 2.4.15
- **JDK Version:** 1.8.0_191

### Grails 2.2.4
- Same above example working in grails 2.2.4
- **Grails Version:** 2.2.4
- **JDK Version:** 1.7

**Comment by appu-wavelabs** [comment]
are there any workarounds ?

**Comment by jeffbrown** [comment]
The behavior may be the result of a bug and we can investigate but why would you ever want a controller action with no url mapping associated with it?  If it is just a helper to forward to and requests are never sent directly to it, it probably shouldn't be a controller action.

**Comment by appu-wavelabs** [comment]
Thank you Jeff for response.

As we are not expose the few controllers and actions to browser url, So that we are avoiding to add url mappings. Created repository with example https://github.com/appu-wavelabs/grails3-forward-sample

**Comment by jeffbrown** [comment]
> As we should not expose the few controllers and actions to browser url, So that we are avoiding to add url mappings.

If you don't want to expose it to a url, why do you want it to be a controller action?

**Comment by jeffbrown** [comment]
The docs at http://docs.grails.org/3.3.7/guide/theWebLayer.html#understandingControllersAndActions mention the following:

> A controller can have multiple public action methods; each one maps to a URI

Controller actions have URIs associated with them.  I think that if you have logic that you do not want to associate with a URI, that logic shouldn't be in a controller action.  The details of what that logic needs to do may dictate what the right solution is.  For some of those scenarios, a service method might make the most sense.  For some of those scenarios, a helper method in the controller may make sense.  That helper method could be in a trait or a base class or simply authored in the controller.

**Comment by appu-wavelabs** [comment]
> > As we should not expose the few controllers and actions to browser url, So that we are avoiding to add url mappings.
> 
> If you don't want to expose it to a url, why do you want it to be a controller action?

- I don't want expose my controller and action bcz these are SEO urls for google.
- There is regex url mapping in my URLMapping.groovy with helper controller and action. 
- This controller will take care to forward request to correct controller and action.
- In Grails 2.2.4 forward(..) method converting my url into dispatch url and this helps us to calling controller and action directly without urlmapping.

**Comment by jeffbrown** [comment]
> In Grails 2.2.4 forward(..) method converting my url into dispatch url and this helps us to calling controller and action directly without urlmapping

I understand that but I am asking why you want to do that.  From the info above I don't see any good reason for the code you are trying to forward to to be in a controller action.

Thanks for the feedback.

**Comment by davydotcom** [comment]
This is not a bug and generally bad practice. If you don't want a method to have a url mapping yet still want to call it. Just call it. No point in using forward as a method invokation proxy

**Comment by vinayabhyankar** [comment]
@jeffbrown Did you managed to find the workaround for the issue?
