### ISSUE TITLE
Missing bootstrapImportSelectorConfiguration

### ISSUE THREAD

**Issue by beckje01** [grails/grails-core#11298]
With grails 4 I'm trying to use slueth and getting errors about a missing bootstrapImportSelectorConfiguration bean. That should be part of boot, is there something special I should be doing to make this available?

**Comment by graemerocher** [comment]
Please provide an example

**Comment by graemerocher** [comment]
Nevermind I can reproduce

**Comment by beckje01** [comment]
Thanks sorry I had meant to push an example app. With this fixed grails and slueth should be able to work.
