### ISSUE TITLE
How to make method POST ?

### ISSUE THREAD

**Issue by manoj4php** [grails/grails-core#11290]
I have created one method and calling from Postman client (POST) call , but its not recognized it , i have no param in URL i am passing data to body, but still its considering as GET call. 
Any help appreciated
i have define below code on controller action ,
`@RestApiMethod(verb = RestApiVerb.POST)` 
What other changes i have to do to make my method as POST ?

**Comment by Jokuni** [comment]
This one should help you: https://docs.grails.org/3.3.9/ref/Controllers/allowedMethods.html

**Comment by manoj4php** [comment]
I tried to add allowmethods and POST for my aciton but still its not working.

**Comment by delfianto** [comment]
@manoj4php what is that `@RestApiMethod`? I don't recall that as part of grails framework. Google search leads me to rest-api-doc plugin, which is a *very* old plugin that haven't seen any commit in five years.

Unless you can give more details on what you are trying to achieve, what grails version you are using, how to reproduce the issue, etc than it is not really a bug report and more suited for question at stackoverflow.com.

**Comment by niravassar** [comment]
please post this on stackoverflow or the slack  channel for the grails community. 

In short you should use a curl call to test your controller method call to be a post, or you could use a unit test in grails, or grails-datastore-rest-client class. 

this is a good guide that can help also
https://guides.grails.org/command-objects-and-forms/guide/index.html
