### ISSUE TITLE
Grails 4.0.0.RC1 - Scaffolding does not work numeric fields. Unable to edit.

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11305]
I have created a very basic grails 4.0.0.RC1 app to demonstrate the problem:

https://github.com/codeconsole/grailsnumberbug

```
package numberbug

class Bug {

    int num = 123456789

    static constraints = {
    }
}
```

Using generate-all or create-scaffold-controller results in an edit page that does not fill in the value.

It creates an input field 
`<input type="number" name="num" value="123,456,789" required="" id="num">`

which is not valid markup in either Chrome or Safari  You can not have type="number" and have a value with commas.

I would imagine a bug like this would be very confusing for a new user to Grails as extremely basic functionality such as editing a number does not work out of the box.

The default behavior should be to not put commas in numbers due to the fact it breaks everything.

**Comment by rvanderwerf** [comment]
So this appears to be a bug in the fields plugin which is supplying the tag "<f:all>" on the create/edit pages.

**Comment by rvanderwerf** [comment]
@codeconsole I see you opened a bug in the fields plugin repository. I'm going to close this as the fields plugin is the place to address this.

**Comment by codeconsole** [comment]
@rvanderwerf I am not sure if it is 100% originating from the plugin because it seems like PropertyEditors are part to blame?

**Comment by codeconsole** [comment]
I take it back, it looks like it is 100% to blame. 

https://github.com/grails-fields-plugin/grails-fields/blob/master/grails-app/taglib/grails/plugin/formfields/FormFieldsTagLib.groovy#L729

Not sure why they are formatting a number for an input value?
