### ISSUE TITLE
Using dbCreate: create-drop makes no sense as default for development with Grails 4

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#11301]
In my opinion doing development where you need to reinitialize your database for every code change is just painful. The default should be none, my suggestion is that instead we should have a gradle task that sync changes in the domain classes to your database. For example application:dbUpdate and application:dbDropCreate

**Comment by jameskleeh** [comment]
@olavgg You can change it to be `dbCreate: update`, however that doesn't work for many of the changes you can make. `create-drop` allows for the database to always be correct, so it does make sense.

What you're asking for is database migrations, which you can enable for development, however most users find the time involved in setting that up during the initial prototyping stages to be time prohibitive.

**Comment by jameskleeh** [comment]
Closing this for now. If you want to provide some further arguments as to why its not a sensible default I'll reopen if they lead to a change
