### ISSUE TITLE
Grails 3.3.9: grails install doesn't put the plugin in the local Maven cache

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#11300]
From the documentation: https://docs.grails.org/3.3.x/guide/plugins.html#creatingAndInstallingPlugins

On section "Installing Local Plugins": 

> To make your plugin available for use in a Grails application run the install command:
> 
> grails install
> 
> This will install the plugin into your local Maven cache.

### Steps to Reproduce

1. create a plugin
2. grails install
3. check $USER/.m2/repository/org/grails/plugins
4. the plugin folder and jar is not there
5. install the plugin on a grails app, and the resolution fails, in my case:

```
| Error Error initializing classpath: Could not find org.grails.plugins:grails-simple-auth:0.1.
Searched in the following locations:
    file:/home/pablo/.m2/repository/org/grails/plugins/grails-simple-auth/0.1/grails-simple-auth-0.1.pom
    file:/home/pablo/.m2/repository/org/grails/plugins/grails-simple-auth/0.1/grails-simple-auth-0.1.jar
    https://repo.grails.org/grails/core/org/grails/plugins/grails-simple-auth/0.1/grails-simple-auth-0.1.pom
    https://repo.grails.org/grails/core/org/grails/plugins/grails-simple-auth/0.1/grails-simple-auth-0.1.jar
```

### Expected Behaviour

The plugin folder and jar file should be on the Maven local repo as documented on the Grails docs.

### Actual Behaviour

Plugin is not copied to local Maven repo.

The jar appears OK in the build/libs folder in the plugin project.

### Environment Information

- **Operating System**: Linux Mint 17.3
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8.0_161 (oracle)

### Example Application

- https://github.com/ppazos/grails-simple-auth

**Comment by niravassar** [comment]
If you use grails install it delegates to the `gradlew publishToLocalMaven` command.

`grails install` works but it is failing on javadoc due to `BCrypt` javadoc errors

use the `gradlew pTML -x javadoc` command (that is shorthand) 

it will place it here `C:\Users\Nirav Assar\.m2\repository\grails` - I was using windows.

once the javadoc is corrected or avoided it works for me. Try it thanks.

**Comment by ppazos** [comment]
@niravassar please use mentions or is not possible to follow up.

I fixed the javadoc and the install finished successfully.

Now I see the files were actually copied on .m2/repository/grails/... but the app that uses the plugin is actually looking in .m2/repository/org/grails/plugins/... by default.

Shouldn't the path were the plugins are installed to by default and the default folder path were apps look for plugins be the same?

**Comment by ppazos** [comment]
@niravassar nevermind, found the issue, took the package of the dependency from a guide and was different than the one generated when I did the grails install.

BTW, how can I choose the package for my plugin so grails install copies the files to the correct folder?

**Comment by niravassar** [comment]
@ppazos edit this in `bul'd.gradle`: group "grails.simple.auth"

**Comment by ppazos** [comment]
@niravassar  +1 thanks!
