### ISSUE TITLE
4.0.0.RC1 - Groovy Date Enhancements No Longer Working

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11313]
`System.out.println "${new Date().dateString}"` works fine in previous versions of Grails and does not work in 4.0.0.RC1

Grails 3.3.9 uses Groovy 2.4.15 (Works fine)
http://docs.groovy-lang.org/docs/groovy-2.4.15/html/groovy-jdk/java/util/Date.html#getDateString()

Grails 4.0.0.RC1 uses Groovy 2.5.6 (Should work fine)
http://docs.groovy-lang.org/docs/groovy-2.5.6/html/groovy-jdk/java/util/Date.html#getDateString()

Example code here:
https://github.com/codeconsole/grails4bugs

Setup:
```
sdk use grails 4.0.0.RC1
grails create-app date
cd date
# add System.out.println "${new Date().dateString}" to Bootstrap.groovy init method
grails run-app
```
results in
```
groovy.lang.MissingPropertyException: No such property: dateString for class: java.util.Date
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
```

```
package date

class BootStrap {

    def init = { servletContext ->
    	System.out.println "${new Date().dateString}"
    }
    def destroy = {
    }
}
```

**Comment by codeconsole** [comment]
Alternatively, run 
`grails console`

and notice all the methods are missing:
`println ((new Date()).metaClass.methods.name.unique().collect { "${it}();"; }.join('\n'))`

**Comment by jameskleeh** [comment]
See http://groovy-lang.org/releasenotes/groovy-2.5.html Under "Breaking Changes"

**Comment by codeconsole** [comment]
@jameskleeh Thanks for pointing that out.
