### ISSUE TITLE
4.0.0.RC1 - server.contextPath incorrect documentation

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11317]
1. Confirmed configuration works with grails 3.3.9
2. Confirmed configuration DOES NOT work in grails 4.0.0.RC1

From:
https://docs.grails.org/latest/guide/gettingStarted.html

"Note that in previous versions of Grails the context path was by default the name of the application. If you wish to restore this behavior you can configure a context path in grails-app/conf/application.yml:"

```
server:
    contextPath: /helloworld
```

Broken Quick Setup:
```
sdk use grails 4.0.0.RC1
grails create-app helloworld
cd helloworld
echo -e '\nserver:\n    contextPath: /helloworld\n' >> ./grails-app/conf/application.yml
grails run-app
```
Result:
`Grails application running at http://localhost:8080 in environment: development`

Previously Working Quick Setup:
```
sdk use grails 3.3.9
grails create-app helloworld
cd helloworld
echo -e '\nserver:\n    contextPath: /helloworld\n' >> ./grails-app/conf/application.yml
grails run-app
```
Result:
`Grails application running at http://localhost:8080/helloworld in environment: development`

**Comment by jameskleeh** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#servlet-specific-server-properties

**Comment by codeconsole** [comment]
@jameskleeh 
https://docs.grails.org/latest/guide/gettingStarted.html documentation should be updated?

**Comment by jameskleeh** [comment]
Yeah I think you're right - I'll re-open for the docs update

**Comment by codeconsole** [comment]
@jameskleeh I am not finding a working configuration.
```
server:
    servlet:
        contextPath: /helloworld
```
does not work either.

Note that 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#servlet-specific-server-properties

states 
`server.context-path` is now` server.servlet.context-path`

but `server.context-path` was not the previous configuration as the previous configuration was camelCase to support application.yml

**Comment by codeconsole** [comment]
@jameskleeh 
perhaps there is some special configuration mapping going on?
https://github.com/grails/grails-core/issues/9020#issuecomment-112777220
that swithes
`server.contextPath `to `server.context-path`
?

**Comment by codeconsole** [comment]
@jameskleeh looks like it needs to be switched back to camelCase

https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/boot/GrailsApp.groovy#L421

**Comment by codeconsole** [comment]
```
server:
    servlet:
        context-path: /helloworld
```

confirmed working.  I made the assumption you couldn't have dashes because the previous configuration was camel case.   I prefer non camel case to match the Spring Boot configuration.   So this is just a documentation fix.

Working quick setup:

```
sdk use grails 4.0.0.RC1
grails create-app helloworld
cd helloworld
echo -e '\nserver:\n    servlet:\n        context-path: /helloworld\n' >> ./grails-app/conf/application.yml
grails run-app
```


Is there any way to -D this from the command line?  That would be useful.

`grails run-app -Dserver.servlet.context-path=/helloworld`

**Comment by codeconsole** [comment]
Documentation update ready to be merged: https://github.com/grails/grails-doc/pull/711
