### ISSUE TITLE
Grails 3.3.9 commang grails list-plugins -installed lists all plugins available

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#11329]
This is not listing plugins installed but plugins available.

`$ grails list-plugins -installed`

Ref: http://docs.grails.org/3.3.9/ref/Command%20Line/list-plugins.html

**Comment by niravassar** [comment]
I believe you are correct in this observation. i tried to run this command on grails 3.3.9, grails 2.5.6 and grails 1.3.7. It only worked on 1.3.7.

I think the `-installed` flag only worked in tandem with the `install-plugin` command. However, `install-plugin` was deprectated in grails 2.4.x in favor of the gradle declarative way of adding a plugin .

I believe this flag is not needed anymore and we can simply look at the `build.gradle` file and see the plugins section. I will change the documentation.

**Comment by ppazos** [comment]
@niravassar thanks for having a look at this.
