### ISSUE TITLE
Grails 4: Request For Alternative to create Angularjs Profile

### ISSUE THREAD

**Issue by LamaBimal** [grails/grails-core#11328]
Currently, We are using the AngularJs 1.x  and grails 2.5.2 in our project. We are upgrading the Grails Version to 4.0.0.RC1. And I couldn't create the angularjs profile any more. Could you please provide any alternative to create the profile?

**Comment by jameskleeh** [comment]
@LamaBimal The AngularJS profile is deprecated. Profiles are just to provide an easy starting point. Given that AngularJS has been superseded by Angular, it's not worth the time investment to maintain the profile

**Comment by jameskleeh** [comment]
You could create a Grails 3 application with the AngularJS profile and simply move the client side specific parts to a Grails 4 app
