### ISSUE TITLE
isDirty on many-to-many relationship doesn't work

### ISSUE THREAD

**Issue by albertodeavila** [grails/grails-core#11321]
### Steps to Reproduce

1. Create a domain class A that hasMany B and it's the owner of the relationship
2. Create a domain class B that hasMany A
3. Create an A instance with multiple B instances and save them.
4. Then, create a new B instance and add it to A. 
5. Check if the domain class is dirty and is false.

### Expected Behaviour

When a Many-to-many relationship is edited, the `isDirty()`method should return true in relation field

### Actual Behaviour

The `isDirty()` method returns false with any change made at relationship

### Environment Information

- **Operating System**: Linux Mint 18
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0.192

### Example Application

- [Sample app reproducing the bug](https://github.com/albertodeavila/manyToManyDirty)

**Comment by albertodeavila** [comment]
It's also happening with one-to-many relationship. If you need an example, I can upload it ;)

**Comment by ddelponte** [comment]
@albertodeavila, I believe this is functioning as designed and is not a bug.

Per the documentation at http://gorm.grails.org/6.0.x/hibernate/manual/#modificationChecking:

> isDirty() does not currently check collection associations, but it does check all other persistent properties and associations.

**Comment by albertodeavila** [comment]
Oh, that's true! :disappointed:

**Comment by xpusostomos** [comment]
Sorry to resurrect this issue, but how is this not a bug? It's all very well to say Gorm doesn't check associations, but it's a many to many relationship, how does one in fact get the relationship to save? The middle table in the M:M relationship is invisible to the programmer, it's dealt with somewhere in the depths of the infrastructure. And from experimentation, marking one side of the relationship with markDirty() does not in fact work [ A.markDirty()  in the above example ]. The collection itself does not have a markDirty method. The result being that if you have object a, (already a saved object) and object b (already a saved object), and I call a.addToCollectionOfB(b), nothing is dirty, and hibernate does not save it. Calling a.markDIrty() doesn't help. Am I to assume many to many relationships are completely broken? If not, how do I make gorm save my new relationship?
