### ISSUE TITLE
Domain Controller Binding Not Working on update() Method

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11337]
When using another method of persistence other than GORM within a service the update method no longer binds to the person object.  

For example, if I use generate-all on a Person domain object, it creates a PersonService.
If I change the implementation of PersonService to as follows, all the controller methods work fine EXCEPT update:

```
class Person {
    String name
    static constraints = {
    	name minSize:2, blank: false
    }
}
```

```
class PersonService {
    Map<Long, Person> database = [:]
    long idGenerator = 0

    Person get(Serializable id) { database[id] }
    List<Person> list(Map args) { database.values().collect { it } }
    Long count() { database.size() }
    void delete(Serializable id) { database.remove(id) }
    Person save(Person person) {
    	person.id = person.id?:++idGenerator
    	database[person.id] = person
    }
}
```
The PersonController update method receives person == null.  If I inspect the params object, the expected params are there, they are just not bound. Even adding the asserts, notFound() is still executed every time.

```
class PersonController {
    def update(Person person) {
        if (person == null) {
            assert params.id
            assert params.name
            notFound()
            return
        }
```
I am assuming what is happening is some sort of gorm entity binding is happening prior to update, but this is unexpected behavior as no service methods are called.  It would make no sense to use a service for the controller if the controller is going to attempt to access the datastore directly, but maybe this is not the root cause?

Controllers should function independent of gorm.  I created a very simple grails app here that reproduces the behavior and includes all the steps done in creating the very simple app.

https://github.com/codeconsole/gormless

**Comment by codeconsole** [comment]
Upon further inspecting,  by adding logSql:true I found that a Person.get() call is attempted prior to calling the update(Person person) controller method.  This is unexpected behavior as personService was completely bypassed.  personService.get() should have been called instead.

This is a bug.  A Controller should not access Gorm directly when a service class is used.  The appropriate service method should be called instead.

**Comment by codeconsole** [comment]
The problem code is here:
https://github.com/grails/grails-core/blob/948bf681ece30322e7bd5e63bf734fbf0ce68ec0/grails-plugin-controllers/src/main/groovy/grails/artefact/Controller.groovy#L384

**Comment by graemerocher** [comment]
That code has been that way for some time. It is as you say arguable wrong that an explicit query is done, but the controller method cannot be invoked without first retrieving the entity.

**Comment by codeconsole** [comment]
@graemerocher  So what do you think the best way is to solve this?  It seems completely wrong that generate-all creates a service with CRUD methods and the read/get method is never used.

I would imagine one of the following should be done:
1. change generate-all to not use a service as it is incredibly misleading as is.
2. or modify the Controller.groovy artifact to not be hardcoded to do this (preferred).

I am more than happy to help with this, but I would prefer if you came up with the idea on the best way to implement it which could be:

1. check if a service exists and if so use this first.
2. come up with some sort of abstraction that does not rely on hardcoded code and the default abstraction implementation is to use the Entity.get method.
3. something entirely different and genius thought up by you and coded by me.

**Comment by graemerocher** [comment]
The update template for the controller should probably be altered to just receive the ID not the full entity to avoid the query outside the context of the service and then the service updated to do the lookup by ID. This would be the correct fix.

**Comment by jameskleeh** [comment]
I don't think we should be changing anything here. To make it work as you request would require either the binding to the domain to happen after the controller is executed (breaking change) or change the controller binding code to look up a data service. Unfortunately we can't make any assumptions about the name of the method to retrieve the entity so that would be brittle.

I don't think any breaking changes in this area would be worth the outcome

**Comment by jameskleeh** [comment]
You are free to change the generated controller to instead retrieve the id and do the lookup and binding in your code

**Comment by codeconsole** [comment]
Hi @jameskleeh 

As is it is completely counter intuitive.  Why would you create a service only to not use it at all?  This is **EXTREMELY confusing**.   `generate-all `should not generate a service if it is going to be only used 90% of the time and bi-passed in some secret binding that is not intuitive at all.

What is the point of `generate-all` in creating the service to being with?  If we are trying to implement Software Engineering design principals such as Separation of Concerns SoC.  Then this is in direct violation.

What end user would reasonably expect that a front end web layer is going to completely bi-pass the service layer?  Why should a web layer be doing database calls to being with?   

This really needs to be addressed and fixed.  I am not saying that grails has to follow software engineering design principals.  I am saying it should not create an implementation that appears to use them, but then does the opposite. 

The easiest fix here would be to have `generate-all` **not generate a service** which would be a very simple fix.  @graemerocher's suggestion would also work.  Simply do the binding in the update method.  You are only adding a couple lines of code. 

Or come up with a better solution such as adding some sort of annotation or static property that aids in the binding.  The whole reason why Spring came up with a web controllers in the first place was to decouple a software application from the web layer. 

No breaking changes are required as `generate-all` is independent of the framework.

**Comment by jameskleeh** [comment]
> Why would you create a service only to not use it at all
The service is used

I agree with you in general that the way it works is not ideal, however it has worked this way for a very long time and changing the behavior would mean breaking applications that rely on the behavior. I'm not willing to break those existing uses for what seems to me like a minor inconvenience. 

Changing `generate-all` to not generate a service is how it used to be. I still think it's valuable to have a service be used and generated, even if it is not used in its entirety. I'm not sure why you thought the service methods were being used. They aren't executed as part of the generated code.

I'm not against changing the `generate-all` command to just accept and id and do the binding in the controller, however that enhancement would be an issue with the scaffolding plugin. https://github.com/grails3-plugins/scaffolding/blob/master/src/main/templates/scaffolding/Controller.groovy

If you'd like to submit a PR there for the change, I'll review and merge it

**Comment by codeconsole** [comment]
Any solution should definitely be non-breaking.

> I'm not sure why you thought the service methods were being used. They aren't executed as part of the generated code.

What do you mean by that? As far as I see, the service methods are executed.  You mean because they are and interface and not implemented?  I was using `generate-all` as a template. You can change it from an interface to abstract class and expand on methods as needed.  

In my current case, I can't use GORM at all because I am using an unsupported datastore (Google Cloud Datastore).  So I provide a different implementation to the service methods.  Unfortunately, I had to throw a method like this on all my domain classes to keep things working:

`static Domain get(Serializable id) { Holders.grailsApplication.getMainContext().getBean('domainService').get(id as Long) }`

**Comment by jameskleeh** [comment]
@codeconsole You can just change the controller:

```
def update(Long id) {
        Person person = personService.get(id)
        if (person == null) {
            notFound()
            return
        }

        person.properties = params

        try {
            personService.save(person)
        } catch (ValidationException e) {
            respond person.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'person.label', default: 'Person'), person.id])
                redirect person
            }
            '*'{ respond person, [status: OK] }
        }
    }
```
