### ISSUE TITLE
fix typo in @infoappgrailsersion@ to @infoappgrailsversion@

### ISSUE THREAD

**Issue by Dierk** [grails/grails-core#11330]
### Steps to Reproduce

1. Run any kind of test with `grails test-app` with Grails-4.0.0-RC1

### Expected Behaviour

Test should run without excessive log output

### Actual Behaviour

Log shows many lines of:
`2019-05-17 11:16:11.185 ERROR --- [           main] g.plugins.DefaultGrailsPluginManager     : For input string: "@infoappgrailsersion@"`

It appears to be a typo in `@infoappgrailsersion@` missing a "v" and should be `@infoappgrailsversion@`

### Environment Information

- **Operating System**: Max OSX
- **Grails Version:** Grails-4.0.0-RC1
- **JDK Version:** Java 12.0.1-open

**Comment by puneetbehl** [comment]
@Dierk I am not able to see the above error. Can you please share the sample application?

Also, here is the application I am testing [hellog4.zip](https://github.com/grails/grails-core/files/3198225/hellog4.zip)

**Comment by graemerocher** [comment]
It seems to be originating from some plugin

**Comment by Dierk** [comment]
repo: https://github.com/Dierk/four

most likely the testing plugins since it only appear when testing, no when starting the app

**Comment by zyro23** [comment]
https://github.com/grails/grails-core/blob/v4.0.0.RC2/grails-core/src/main/groovy/grails/plugins/DefaultGrailsPluginManager.java#L424

if `@info.app.grailsVersion@` is not replaced, that regex strips the dots and uppercase letter and then throws a `NumberFormatException` resulting in the described error log.

token replacement and/or systemProperty setup for `Metadata` - afaik - happens via gradle (`GrailsGradlePlugin`?).

i am seeing the same thing when running tests with the IDEs platform runner (i.e. junit).

workaround: running via gradle directly or configuring idea to run the test(s) with gradle makes those log go away (file -> settings -> build, execution, deployment -> build tools -> gradle -> runner).

**Comment by jsturnio** [comment]
I'm seeing the same error message making tests in Grails 3.3.10
