### ISSUE TITLE
Sorting with PostgreSQL doesn't work

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#11338]
### Steps to Reproduce

1. Download project example
2. Open Book controller "/book/index"

### Expected Behaviour

No error when sorting on dateCreated

### Actual Behaviour

Get following error message
ERROR: function upper(timestamp without time zone) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts.

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Grails Version:** 4.0.0RC1
- **JDK Version:** Java 11.0.3

### Example Application
https://github.com/olavgg/sortingbug

**Comment by olavgg** [comment]
![Screenshot_20190602_205749](https://user-images.githubusercontent.com/2189601/58765967-39df8e00-8579-11e9-912f-0ae40e5abbb0.png)

**Comment by zyro23** [comment]
grails/grails-data-mapping#1240, grails/gorm-hibernate5#134

**Comment by jameskleeh** [comment]
Duplicate
