### ISSUE TITLE
Domain class not being translated into a table in Grails 3.3.10 but works properly in 3.3.9

### ISSUE THREAD

**Issue by jksaunders** [grails/grails-core#11348]
Running the only test in the project shows that the `RecurrenceRule` domain class is not being created as a database table. This domain class works as expected in Grails 3.3.9 but not in 3.3.10.

It seems as though having a property named `interval` makes things go wrong. Renaming the property to anything else seems to resolve the issue.

`RecurrenceRule.groovy`
```
@EqualsAndHashCode(includes = "publicId")
class RecurrenceRule {

    String publicId = ""
    int interval = 1
}
```

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "RECURRENCE_RULE" not found; SQL statement:
select count(*) as y0_ from recurrence_rule this_ [42102-199]
```

My Hibernate-related dependencies in `build.gradle` are:

```
    compile "org.hibernate:hibernate-core:5.2.17.Final"
    compile "org.grails.plugins:hibernate5:6.1.12"
    compile "org.hibernate:hibernate-ehcache"
```

and `gradle.properties`:

```
grailsVersion=3.3.10
```

### Steps to Reproduce

1. Run `grails test-app`

### Expected Behaviour

Test runs (does nothing, passes).

### Actual Behaviour

Error (copy/pasted above) suggesting that the `RecurrenceRule` domain class is not being translated into a database table.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.3.10
- **JDK Version:** 8.151

### Example Application

[grails-issues-4.zip](https://github.com/grails/grails-core/files/3294982/grails-issues-4.zip)

Thanks so much for any help!

**Comment by bobbywarner** [comment]
`interval` is a reserved word in H2 -- http://www.h2database.com/html/grammar.html#interval

So, it can't be used as a property name.
