### ISSUE TITLE
Grails 3: Not able to set configuration inside plugin specific application.groovy file

### ISSUE THREAD

**Issue by 1HzAkLAT** [grails/grails-core#11346]
I am trying to set the below config properties inside `myapp/plugins/myPlugin/conf/application.groovy` file, it seems to be not picking up the values

```
grails.controllers.upload.maxFileSize = 90000000 //9MB
grails.controllers.upload.maxRequestSize = 90000000 //9MB
```

But if i move this to app level application.groovy file, it works fine.

How to get this working inside plugin specific application.groovy file

**Comment by jameskleeh** [comment]
If you want configuration to be passed to the app it has to be in a `plugin.groovy` file
