### ISSUE TITLE
Issue: Grails 3.3.9 compatibility with openjdk 11

### ISSUE THREAD

**Issue by ksgraghav** [grails/grails-core#11359]
Hi,

We are currently working on Grails 3.3.9 Project. 
Now that we have been asked to upgrade Java from Java 8 to Open JDK 11.

1) Is Grails 3.3.9 compatible with Open JDK11.
2)Any upgrade in Grails is required to accommodate Open JDK 11.

We require your valuable suggestion which would enable us to proceed further.

Thank you,
Ganesh

**Comment by ilopmar** [comment]
Grails 3.3.x does not support JDK 9+, mostly because Spring Framework 4.3 (in which it's based) doesn't support it either.
If you want to use JDK 9+ you need to use Grails 4.
