### ISSUE TITLE
Could not use mySql database while testing app

### ISSUE THREAD

**Issue by kapilthakkar2912** [grails/grails-core#11356]
I have added following code in `application.yml`.

```
test:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://10.210.22.234:3306/devdocs_unit_test
            username: *****
            password : *****
```
Still its use in-memory db.

### Expected Behaviour

It should use mySql Database

### Environment Information

- **Operating System**:  Windows 10
- **Grails Version:** Grails 3
- **JDK Version:** 8
- **Container Version (If Applicable):** TODO

**Comment by bobbywarner** [comment]
There is not enough information here to troubleshoot the reported issue.  In general, Grails supports many different databases and using different databases in each environment without issues.  

Please provide an example application so the issue can be reproduced.
