### ISSUE TITLE
Domain class not saved after internal modification

### ISSUE THREAD

**Issue by deroffal** [grails/grails-core#11362]
### Task List

- [x ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x ] Example that reproduces the problem uploaded to Github
- [x ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a domain class with a internal function modifying the value of one field
2. Create an instance of this object, save it with a first value for the field
3. In a controller, get this object, call this function to modify the value of the field and save the object

### Expected Behaviour

The value should be modified

### Actual Behaviour

The value is not modified, but there isn't actually any error.

### Environment Information

- **Operating System**:  WIndows
- **Grails Version:** Not happening on Grails 3.1.16, but found in Grails 3.3>9
- **JDK Version:** 8

### Example Application

- [Demo here](https://github.com/deroffal/grails_domain_not_saved) - steps to reproduce in the README.

Thank you

**Comment by zyro23** [comment]
http://gorm.grails.org/6.1.x/hibernate/manual/index.html#_new_dirty_checking_implementation

**Comment by deroffal** [comment]
OK, thank you for the information, i can close the issue!

**Comment by niravassar** [comment]
Try calling the setter for the attribute from the internal method.
