### ISSUE TITLE
grails 3.3.9 stuck with  Resolving Dependencies

### ISSUE THREAD

**Issue by saxihuangxing** [grails/grails-core#11379]
when i compile grails app, i run the  command  grails clean , it stay with  '| Resolving Dependencies. Please wait...'  for all the time , i wait a day but it still show this.  the same  grails project my college can complete it in their ubuntu vm machine.  but in my machine it always stuck with Resolving Dependencies.  i have compare any enviroment i can thought and tried every means for one week. but i really can't resolve this problem , because i get anymore information for the compile log. i am sure my network is ok , because my college internet enviroment is same with  me .

**Comment by tylervz** [comment]
Hi @saxihuangxing 

If you want an answer to your issue, you'll need to be more specific. You need to give steps to reproduce the issue and a link to code on GitHub that demonstrates the issue.

**Comment by saxihuangxing** [comment]
Hi @tylervz 
   my items is from https://github.com/bigbluebutton/bigbluebutton/tree/master/akka-bbb-apps,but it depend on https://github.com/bigbluebutton/bigbluebutton/tree/master/bbb-common-message,so it should commit ./deploy.sh in bbb-common-message directory first.  when i in akka-bbb-apps commit build.sh it will stuck in resolving Dependencies.  i use sdkman to intall gradle and grails. my gradle version is 5.1.1 and grails version is 3.3.9. i am not sure if you can reproduce this issue , because my colleges don't meet this issue . i am newer with garils so i have no idea about this issue.  thank you for your help .

**Comment by delfianto** [comment]
Perhaps it is an issue with your gradle version? As far as I know grails 3.x is not compatible with gradle 5. You might try installing gradle 4.3.x using sdkman or using the gradle wrapper and run grails clean on your project.

**Comment by saxihuangxing** [comment]
Hi @delfianto 
  Maybe it's not the issue for versison.  because my collegue use the gradle 5.1.1,grails 3.3.9 have completed compile this prj, but i am always stuck in resolving dependency....

**Comment by jameskleeh** [comment]
This is certainly an issue on your end. I would suggest trying to use Gradle directly
