### ISSUE TITLE
Grails 3.3.10: grails install command not working due to dependencies

### ISSUE THREAD

**Issue by tylervz** [grails/grails-core#11378]
According to the [Grails documentation](http://docs.grails.org/3.3.10/guide/plugins.html#creatingAndInstallingPlugins), 

> To make your plugin available for use in a Grails application run the install command:

> `grails install`

> This will install the plugin into your local Maven cache. 

The command works as expected on my machine for basic plugins created with `grails create-plugin <plugin name>`. However, the plugin I'm trying to install has a dependency on `org.grails.plugins:spring-security-oauth2:1.3.+`

### Steps to Reproduce

1. Create a plugin with `grails create-plugin example-plugin`
2. Add these two lines in the `dependencies` section of `build.gradle`:
```
provided "org.grails.plugins:spring-security-core:3.+"
provided "org.grails.plugins:spring-security-oauth2:1.3.+"
```
3. Run `grails install`
4. Check $USER/.m2/repository/example/plugin
5. The plugin folder and jar is not there

### Stacktrace

It's not really a stacktrace, but this is the output of `grails install`:

```
$ grails install

*********************************************************************
* You've installed the Spring Security OAuth2 plugin.               *
*                                                                   *
* Next run the "grails init-oauth2" script to configure plugin.     *
*                                                                   *
*********************************************************************

Process finished with exit code 0
```

### Expected Behaviour

The plugin folder and jar file should be on the Maven local repo as documented in the Grails docs.

### Actual Behaviour

Plugin is not copied to local Maven repo.

### Environment Information

- **Operating System**: Mac OS 10.14.6
- **Grails Version:** 3.3.10
- **JDK Version:** 8.0.212 AdoptOpenJDK HotSpot

### Example Application

https://github.com/tylervz/grails-plugin-spring-oauth-dependency

**Comment by jeffbrown** [comment]
Does `./gradlew publishToMavenLocal` work?

**Comment by tylervz** [comment]
@jeffbrown yes, `./gradlew publishToMavenLocal` does work! I was trying to find what the corresponding Gradle command was but I couldn't find it in the docs or by looking over the Grails source code.

**Comment by jeffbrown** [comment]
> I was trying to find what the corresponding Gradle command was but I couldn't find it in the docs...

FYI... `pTML` is documented at https://docs.gradle.org/current/userguide/publishing_maven.html.

**Comment by tylervz** [comment]
Is there any way I can help fix this issue? Where should I start debugging the `grails install` command?

**Comment by jameskleeh** [comment]
@tylervz You would have to tell the author of the spring security oauth2 plugin to rename his script

https://github.com/MatrixCrawler/grails-spring-security-oauth2/blob/master/src/main/scripts/_install.groovy
