### ISSUE TITLE
Race condition between Grails and Micronaut init

### ISSUE THREAD

**Issue by Sabst** [grails/grails-core#11371]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Our Grails 4 application listens to Kafka events through Micronaut.

New received events are processed using Grails code (conversion, storage into DB...).

When the application starts and if events are already pending, an error occurs, for example, when converting one of the event fields to JSON (`event.value as JSON`):

```
java.lang.RuntimeException: org.grails.web.converters.exceptions.ConverterException: Unconvertable Object of class: java.util.LinkedHashMap
        at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:120)
        at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:659)
        at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:148)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:231)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2744)
        at groovy.lang.ExpandoMetaClass.setProperty(ExpandoMetaClass.java:1185)
     (...)
        at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:513)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.grails.web.converters.exceptions.ConverterException: Unconvertable Object of class: java.util.LinkedHashMap
        at grails.converters.JSON.value(JSON.java:182)
        at grails.converters.JSON.render(JSON.java:119)
        at org.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:118)
        ... 62 common frames omitted
```

If the exception is caught and ignored, the error will disappear (once Grails initialization is complete) after a short while.

It looks like Grails startup was not complete when the event processing started.

As a side note, exactly the same pattern occurs when Grails/Spring Services are "injected" into Micronaut beans (more exactly "accessed" through the grails.util.Holders class).

### Expected Behaviour

No random error at startup when Grails APIs are called from Micronaut

### Actual Behaviour

See above

### Environment Information

- **Operating System**: Linux mint 19
- **Grails Version:** 4.0.0
- **JDK Version:** openjdk version "1.8.0_212"
- **Container Version (If Applicable):** N/A (grails run-app)

### Example Application

N/A

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by Sabst** [comment]
I will probably not have the time for that. I tried to capture as many details as possible and the stack trace is pretty clear. I'll see what I can do but please read it again.

**Comment by Sabst** [comment]
Ok, I do not see the problem JSON conversion problem anymore with Micronaut 1.2.0 (it looks like I forgot to mention the initial issue was with Micronaut 1.1.4 or 1.2.0.RC1) and Grails 4.0.0 using this same Micronaut version.

Now, when a Micronaut method calls a Grails Service at startup (say kafka messages are received), is there anything better than this kind of hack to make sure the service is injected ? On my system, the service becomes available about 3 seconds after the messages have started firing ;(
```
   MyService getMyService() {
        MyService result = getBaseMyService()
        while (!result) {
            result = getBaseMyService()
            sleep 1000
        }
        return result
    }

    private MyService getBaseMyService() {
        MyService result
        try {
            result = Holders.grailsApplication.mainContext.getBean('myService')
        } catch(e) {
            // Ignore
        }
        return result
    }
```

**Comment by jameskleeh** [comment]
@Sabst I would move `MyService` into the Micronaut context so its no longer a concern

**Comment by Sabst** [comment]
@jameskleeh Yes I use that shortcut when I can but I do not think that works for all services (think gorm-related, transactional...). Maybe over time that will work for all kinds of Grails services but - as far as know - this is not the case yet, right?

**Comment by jameskleeh** [comment]
@Sabst I'm not aware of a case where it wouldn't work. Micronaut has its own transactional annotation you can use that has feature parity with the Gorm one

**Comment by Sabst** [comment]
@jameskleeh Ok but you need to rewrite the code that is not always under your control : It could be part of a Grails plugin or part of an existing Grails app.
Is there a "plan" to make that transition transparent (if feasible!)? I mean make your statement work (*"move it into the Micronaut context"*) without changing the Grails code and replace - by configuration - the legacy context by Micronaut's? Who needs two contexts anyway?

**Comment by jameskleeh** [comment]
@Sabst Many pieces of most grails plugins could be moved into the Micronaut context and I would encourage you to raise issues to those plugins to do so. The spring context is obviously still necessary to integrate with spring based libraries
