### ISSUE TITLE
"gradle war" does not produce any .war file in Grails 4.0.0

### ISSUE THREAD

**Issue by andersaaberg** [grails/grails-core#11372]
# Task List

- [x] Steps to reproduce provided
- [n/a] Stacktrace (if present) provided
- [n/a] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. Generate a grails app with grails version 4.0.0:
```
sdk u grails 4.0.0
grails create-app myApp
cd myApp
```
2. Try to generate a war file
```
./gradlew war
```

### Expected Behaviour
Grails should have created a .war file in build/libs/ like what happens in Grails 3.3.10. 

### Actual Behaviour
Grails has not created any .war file in build/libs/

### Environment Information

- **Operating System**: Ubuntu 18.04 LTS
- **Grails Version:** 4.0.0
- **JDK Version:** JDK8u212
- **Container Version (If Applicable):** n/a

**Comment by jameskleeh** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#spring-boot-gradle-plugin

It's `./gradlew bootWar`

**Comment by rmorrise** [comment]
If this is the case, the WAR task should throw an error by default explaining the change. Having a successful build that produces no output is not an OK behavior.
