### ISSUE TITLE
pathingJar = true seems to be breaking UTF-8 i18n messages

### ISSUE THREAD

**Issue by diegocosteira** [grails/grails-core#11374]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Description

After creating a simple application, i18n messages work fine. When pathingJar is set to true, message resolution doesn't seem to be resolving messages in UTF-8.

### Steps to Reproduce

1. Clone the repository from
`https://github.com/diegocosteira/utf8messages.git`
2. Run the application
`grails run-app`
3. Open [http://localhost:8080](http://localhost:8080) in your browser
4. The output should be
`ÁÉÍÓÚáéíóú`
5. Stop the application
6. Change the pathingJar option in build.gradle to true
7. Repeat steps 2 and 3
8. Output shows
`�?É�?ÓÚáéíóú`

### Expected Behaviour

The output read from the properties file should be the same whether pathingJar is true or false.

### Actual Behaviour

Seems like pathingJar = true is somehow breaking the message resolution encoding.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.0
- **JDK Version:** 11

### Example Application

- https://github.com/diegocosteira/utf8messages.git

**Comment by jameskleeh** [comment]
Can you try setting `org.gradle.jvmargs='-Dfile.encoding=UTF-8'` in the `gradle.properties` ?

**Comment by mauroinagoki** [comment]
> 
> 
> Can you try setting `org.gradle.jvmargs='-Dfile.encoding=UTF-8'` in the `gradle.properties` ?

It is working! Thanks!

**Comment by jameskleeh** [comment]
OK I'll see about making that the default

**Comment by diegocosteira** [comment]
It works, thank you!

**Comment by niravassar** [comment]
We are going to try and find a solution.

*Notes*
- we tried to edist :589 in GrailsGradlePlugin.groovy with `task.setDefaultCharacterEncoding("UTF-8")`. That did not work

- possible need to add this property to be handled by grails
`grails { pathingJarEncoding = x }`, where x could be `UTF-8`. Then if thats set, pass the JVM arg in the javaexec task to whatever the value is
