### ISSUE TITLE
[Grails 4.0.0] application.groovy is ignored if spring.config.location is set when deploying

### ISSUE THREAD

**Issue by Taack** [grails/grails-core#11380]
### Task List

- [* ] Steps to reproduce provided
- [ *] Example that reproduces the problem uploaded to Github
- [ *] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an applcation.groovy file and an alternative application.yml like application2.yml
2. use gradle assemble to produce a war
3. launch the war with spring.config.location set to the alternative application2.yml

### Expected Behaviour

The application.groovy file must be executed (as in Grails 3.3.9)

### Actual Behaviour

The application.groovy is ignored

### Environment Information

- **Operating System**: Linux Mageia 7.1
- **Grails Version:** 4.0.0
- **JDK Version:** OpenJDK 8 & OpenJDK 11
- **Container Version (If Applicable):** TODO

### Example Application

- Execute gradle bootWar
- cd build/libs

Then 
```
$ java -jar deploy-0.1.war 
This must be printed, at least it was with Grails 3.3.9
Grails application running at http://localhost:8080 in environment: production
$

```
But 
```
$ java -Dspring.config.location=../../grails-app/conf/application-c1.yml -jar deploy-0.1.war
Grails application running at http://localhost:8080 in environment: production
$

```

**Comment by Taack** [comment]
[deploy.zip](https://github.com/grails/grails-core/files/3447681/deploy.zip)

Test case to unzip. 
application.groovy contains a single line of code:
`println "This must be printed, at least it was with Grails 3.3.9"
`

and application-c1.yml as a copy of application.yml

**Comment by zyro23** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#configuration-location

**Comment by Taack** [comment]
@zyro23 
Thanks, I close this bug report.
