### ISSUE TITLE
Grails 3.3.10 on WAS: impossible to start applications containing domain classes

### ISSUE THREAD

**Issue by leleFc** [grails/grails-core#11383]
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create an app using Grails 3.3.10
2. annotate the main class with "@EnableAutoConfiguration"
3. create a simple domain class, with just one or two fields
4. deploy to Websphere 8.5.5.13 and try to start the application

### Expected Behaviour

The application starts correctly

### Actual Behaviour

The application did not start raising "org.springframework.beans.factory.UnsatisfiedDependencyException" error (see stacktrace for the error) , but if you remove the domain class it starts correctly

### Environment Information

- **Operating System**: Windows Server 2012 R2
- **Grails Version:** 3.3.10
- **JDK Version:** Compiled with Oracle x64 1.8 update 121, Runtime using IBM 1.8 x64
- **Container Version (If Applicable):** IBM WAS 8.5.5.13

### Example Application

- link to github: https://github.com/leleFc/TestWas

[stacktrace.txt](https://github.com/grails/grails-core/files/3461287/stacktrace.txt)

**Comment by graemerocher** [comment]
Maybe try upgrade the version of javassist. See https://stackoverflow.com/questions/30313255/reflections-java-8-invalid-constant-type

**Comment by leleFc** [comment]
Hi @graemerocher, thanks a lot for your quick reply!
I tried your suggestion adding "compile group: 'org.javassist', name: 'javassist', version: '3.18.2-GA'" inside "build.gradle",  but it's not enough, the problem still exists..
PS: class loader is set to "parent last"

**Comment by leleFc** [comment]
Hi @graemerocher, I solved by creating a shared library with the new javassist version linked to my application (configure the class loader with "parent_last" seems not enough), but now another error occours: "java.lang.RuntimeException: org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer: frozen class (cannot edit)"
