### ISSUE TITLE
@Client annotation for micronaunt HttpClient not finding parameters with caps 

### ISSUE THREAD

**Issue by rboyddavis** [grails/grails-core#11391]
Put how to replicate in comment: 

Basically use:
import io.micronaut.http.annotation.Get
import io.micronaut.http.client.annotation.Client

and put a Grails property call out in them with camel case --> won't be found.  Lower case is found.  

Tell us what should happen

Should find the camel case property value. 

### Actual Behaviour

Tell us what happens instead:

Get a cannot resolve placeholder exception since it can't resolve the uppercase/camel case property name.  

### Environment Information

- **Operating System**:                   Windows 10 (64) 
- **Grails Version:**                                4.0.0
- **JDK Version:**                                   JDK 1.8_221
- **Container Version (If Applicable):** 

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by rboyddavis** [comment]
From the User manual: https://docs.grails.org/4.0.0/guide/REST.html#callingRestServices

More investigating of this - it seems to be a case issue for the yml property.   

-) myprop.aprop  - works when all lowercase 
-) myprop.aProp - does not in either the @Get or @Client annotations 

application.yml: 

itunes:
    url: "https://itunes.apple.com/"
    urlWithCamel: "https://wasp.dev.ats.cloud.huit.harvard.edu/config"
    limit: "25"
    limitUp: "25"



package example.grails

import io.micronaut.http.annotation.Get
import io.micronaut.http.client.annotation.Client

// Change the root url to use a application.yml property  with some caps - does not get resolved  
// This works: 
@Client('${itunes.url}')
interface ItunesClient {

    // Props work here in the @Get  
   // Simplified to just return the body 
    @Get('/search?limit=${itunes.limit}&media=music&entity=album&term={term}')
    String searchWithLimitProp(String term)

    @Get("/search?limit=25&media=music&entity=album&term={term}")
    String search(String term)
}

Autowire this interface to a service and call the search 


Change @Client to 
@Client('${itunes.urlWithCamel}')  
...

 get: 
URI
/
Class
io.micronaut.context.exceptions.ConfigurationException
Message
null
Caused by
Could not resolve placeholder ${itunes.urlWithCamel}

**Comment by jameskleeh** [comment]
Properties must be kebab case `ituns.url-with-camel`

**Comment by rboyddavis** [comment]
Doh! - sorry.
