### ISSUE TITLE
Grails 4: Number of services wrong at ApplicationController with rest-api profile

### ISSUE THREAD

**Issue by zbubric** [grails/grails-core#11399]
### Task List

- [ x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new grails app with rest-api profile
2. Add some domain classes
3. Use generate-all script to generate controllers and services
4. Validate that controllers and services are generated and count them
5. Run app
6. Fetch home path response (or open it in browser)
7. Check section with number of Domains, controllers and services

### Expected Behaviour

In provided example app, artefacts section should contain:
```
"artefacts": {
"controllers": 5,
"domains": 4,
"services": 4
},
```

### Actual Behaviour

```
"artefacts": {
"controllers": 5,
"domains": 4,
"services": 0
},
```

### Environment Information

- **Operating System**: Win 10-64
- **Grails Version:** 4.0.0
- **JDK Version:** 1.8

### Example Application
https://github.com/zbubric/grails4-rest-sample

**Comment by jameskleeh** [comment]
Gorm data services are not service artefacts. Just because you have put them in grails-app/services does not make them what Grails considers to be services.
