### ISSUE TITLE
Springloaded cache disabled

### ISSUE THREAD

**Issue by phejl** [grails/grails-core#11394]
### Steps to Reproduce

1. Run grails app with `grails run-app`

### Expected Behaviour

Springloaded cache is used

### Actual Behaviour

Springloaded cache is not used

### Environment Information

- **Operating System**: Manjaro; Linux 5.2.8
- **Grails Version:** 3.2.9
- **JDK Version:** 1.8.0_222

###

The `grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/agent/AgentTasksEnhancer.groovy` does not append either `profile=grails` or `caching=true`. This means although the `cacheDir` is configured no caching is actually happening.

**Comment by davydotcom** [comment]
Good find, fixing for 4.0.5 seems to help reload performance a bit more
