### ISSUE TITLE
Facing Communication "pool.ConnectionPool Unable to create initial connections of pool. com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure" issue in my grails application while able to connect normally using mysql command prompt

### ISSUE THREAD

**Issue by gagandeepchhabda12305** [grails/grails-core#11403]
I am facing a communication link failure issue while connecting to datasources, although the same works when using mysql command line 
Also, verified the connections using telnet

**Comment by graemerocher** [comment]
Please ask questions on Slack https://grails-slack.cfapps.io/

Thanks
