### ISSUE TITLE
Grails 4: BigDecimal ValueConverter convert method not called

### ISSUE THREAD

**Issue by Taack** [grails/grails-core#11404]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `ValueConverter` class for BigDecimal (`NotLocalizedBigDecimalConverter`)
2. Insert into the Spring DSL into resources.groovy `defaultGrailsBigDecimalConverter(NotLocalizedBigDecimalConverter)`
3. Create a domain with a `BigDecimal` 
4. Create the form setting the domain
5. Create 2 actions for displaying the form and to save it

### Expected Behaviour

The `convert` method of the `ValueConverter` is called. This was the behaviour for Grails 3.3.9.

### Actual Behaviour

The `convert` method in the `ValueConverter` is never called.

### Environment Information

- **Operating System**: Mageia release 7 (Official) for x86_64
- **Grails Version:** Grails 4.0.0
- **JDK Version:** java full version "11.0.4+10-LTS"

### Example Application

Example application is provided in comments.

**Comment by Taack** [comment]
[vc.zip](https://github.com/grails/grails-core/files/3596664/vc.zip)

Here is a sample application:
1. Access to [http://localhost:8080/root/index?lang=fr](http://localhost:8080/root/index?lang=fr)
2. enter 123.45
3. click on save
`OK` is printed if no errors
`NOK` is printed if the domain has errors

Thanks for your support

**Comment by puneetbehl** [comment]
Please use `Order(value = -1)` on your `NotLocalizedBigDecimalConverter` which should prioritize your implementation over the standard Grails implementation. 

Fixed with #11479
