### ISSUE TITLE
g:datepicker aria label incorrect

### ISSUE THREAD

**Issue by kroellbe16** [grails/grails-core#11402]
**Grails version:** 3.3.10
Pretty much the same issue as in [GRAILS-11655](https://github.com/grails/grails-core/issues/757)

GSP Code:
`<g:datePicker name="buyDate" precision="day" default="${new Date()}" value="${book.buyDate}"/>`

Resulting HTML Code:
Sadly, I cannot show the code due to github, therefore I added it as an image. 
![image](https://user-images.githubusercontent.com/27058228/64458688-4cc4aa00-d0f6-11e9-9bef-fd859ac2d919.png)

**Comment by bobbywarner** [comment]
Closing as the corresponding PR on `grails-gsp` is merged -- https://github.com/grails/grails-gsp/pull/56
