### ISSUE TITLE
?format= does not work unless response.format is referenced

### ISSUE THREAD

**Issue by jjelliott** [grails/grails-core#11406]
Using `?format=` does not work all of the time using default mappings. However, it does work if you reference `response.format` before you `respond`. 

Related issues: 
    https://github.com/grails/grails-core/issues/10765 - This says that `?format=` is supposedly disabled when using default mappings but it appears that is not the case. 
    https://github.com/grails/grails-core/issues/5414 - There isn't any information on what the resolution was here.

### Task List

- [ x ] Steps to reproduce provided
- [ x ] Example that reproduces the problem uploaded to Github
- [ x ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a default Grails app. 
2. Have both a JSON view and GSP for a controller action that uses `respond`.
3. Attempt to retrieve the JSON view via the `?format=json` parameter.

### Expected Behaviour

The content negotiation will return the view corresponding to the format parameter OR the format parameter will always be ignored.

### Actual Behaviour

The format parameter is ignored, but only if `response.format` is not referenced prior to the "respond" command. 

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.0
- **JDK Version:** 8

### Example Application

https://github.com/jjelliott/grails-format-param-bug

**Comment by davydotcom** [comment]
this is due to your url mapping having 
```
"/$controller/$action?/$id?(.$format)?"
```

It is expecting a .json not a ?format=json.  The response.format getter causes a fallback and temporary cache to the mime type cache which was loaded before the link processor swapped params.format with null from the lack of a .json

**Comment by davydotcom** [comment]
Removing the `(.$format)?` should resolve your issue.

**Comment by davydotcom** [comment]
Closing as consistent behavior was merged in PR #11580 . Also description of above issue should suffice.
