### ISSUE TITLE
fix typo in @infoappgrailsersion@ to @infoappgrailsversion@ (Now in 3.3.10)

### ISSUE THREAD

**Issue by jsturnio** [grails/grails-core#11417]
I saw that this issue: https://github.com/grails/grails-core/issues/11330# was Closed for 4.0.0-RC1, but I'm seeing the same error message making tests in Grails 3.3.10, may be that need the same fix here?

**Comment by erichelgeson** [comment]
Cherry-picked the commit to the 3.3.x branch https://github.com/grails/grails-core/commit/97124a04b5d794d1d4fa1bfd04797f0f6e69b4a4
