### ISSUE TITLE
@BindUsing not working for attributeless transients

### ISSUE THREAD

**Issue by xpusostomos** [grails/grails-core#11424]
Grails 4.0.0: Let's say I add a getter and setter to my domain class that is not backed by its own variable:

```groovy
class MyDomainClass {
    String nslId
...
    URI getNslUri() {
        return nslId ? new URI("${Holders.config.getProperty('biodiversityIDURL')}${nslId}") : null
    }

    void setNslUri(URI uri) {
        nslId = uri.path
    }
}
```

We can fix it with this:

```groovy
    static transients = ['nslUri']
```

Now how do I add @BindUsing to this, since there is no attribute to attach it to? I tried adding it to the getter and setter, to no avail. I know you can add a class binder, but that seems potentially inefficient, and not very nice both from a code layout point of view, and also the point of view the pattern is completely different.

Expected result:

I think @BindUsing should work when they occur before the setter as well as how they work now on the attribute.

**Comment by erichelgeson** [comment]
Could you just add `URI nslUri` property to your domain? I believe that will allow binding. Also please follow the issue template when opening issues on this repo - thanks.

**Comment by xpusostomos** [comment]
Yes adding a fake variable, or should I say an unused variable works, but I don't think creating unused memory can be ideal.

bindable: is only for disabling binding, so that is not important here.

**Comment by xpusostomos** [comment]
So... you consider allocating junk variables as a good design is it?
