### ISSUE TITLE
Grails 4.0.1 : Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'

### ISSUE THREAD

**Issue by bradconor** [grails/grails-core#11421]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

- grails create-app helloworld
- cd helloworld
- grails run-app

### Expected Behaviour

Homepage should appears

### Actual Behaviour

**Http status 500**

`javax.servlet.ServletException: Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1352)
	org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)`

I just followed this guide https://docs.grails.org/4.0.1/guide/single.html?fbclid=IwAR0plEW9OH2mhvonuG4JFvsmVc7LWh-XyDLVR2mJto59ClMsiW-TcO24jhM#requirements

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.1
- **JDK Version:** 1.8.0_231

Best Regards,
Brad

**Comment by erichelgeson** [comment]
I can not reproduce this. I see you're on windows - please make sure there's no spaces in your paths to grails, java, or your project.

**Comment by bradconor** [comment]
There is indeed a space in my project paths. Thanks.

**Comment by devravi** [comment]
After upgrade from 3.3.1 to 4.0.2 I'm receiving same issue, if I run old application (3.3.1) It works fine. 

I'm running it on osx 10.13.6
Grails Version: 4.0.2
JVM Version: 1.8.0_171

.gson files present (also working for older version), I tried debug and found it is looking for .tpl file instead of .gson.

Am I missing something?

**Comment by graemerocher** [comment]
@devravi Provide an example that reproduces the issue

**Comment by devravi** [comment]
Hi @graemerocher 

Here is link to repo for example,
https://github.com/devravi/grails_view_index_issue

I created a fresh application with "--profile=rest-api",
Copied application controller from old app and adjusted directory structure as per that.
Edited "UrlMappings".

I checked **namespace** (in controller) present in old application.  Can that cause issue with not finding views?

**Comment by abrahaj** [comment]
having the same problem on openjdk version "11.0.8" 2020-07-14

**Comment by jagritiS** [comment]
This error occurs when the method has not any view or redirected to any gsp page. So there are two solutions for it 
1. Generate a gsp page of that method or 
2. Redirect to any other method containing gsp page from that method like this 
```
def index(){
//your code 
redirect(action:'test')
}
```
`test.gsp` page must exist.

**Comment by davydotcom** [comment]
a view is needed for rendering unless explicitly stated otherwise via the render method. this is correct behavior. not sure what you are expecting

**Comment by tjrafferty** [comment]
In addition to Davids comment about needing a view, you may want to check your `build.gradle` to verify you have the following dependency` compile "org.grails.plugins:gsp"  ` ...if you plan on rendering gsp views. This could be a case where you generated the application with a profile that did not include gsps and then later decided you wanted them as part of the app.
