### ISSUE TITLE
Upgrade Tomcat to 9.0.27

### ISSUE THREAD

**Issue by jnunderwood** [grails/grails-core#11433]
Grails 4.0.1 uses Spring Boot 2.1.9, which uses Tomcat 9.0.25. Unfortunately, that version of Tomcat has a regression that prevents configuration files from being loaded from the classpath. Thus, Grails 4.0.1 projects have this problem too. 

My project, specifically, tries to configure SSL. The keystore, which is on the classpath, is not getting loaded. My project works if I downgrade to Grails 4.0.0.

This problem is supposed to be fixed in Tomcat 9.0.27, which is included in Spring 2.1.10.

Can the next release of Grails 4.0.x include an upgrade to Spring 2.1.10 and Tomcat 9.0.27? Thank you.

Relevant Links:

- https://tomcat.apache.org/tomcat-9.0-doc/changelog.html
- https://github.com/spring-projects/spring-boot/releases/tag/v2.1.10.RELEASE
- https://stackoverflow.com/a/58198805/2766128

**Comment by erichelgeson** [comment]
Fixed in https://github.com/grails/grails-core/pull/11437
