### ISSUE TITLE
Grails 4.0.1 - URLMappings - keepParamsWhenRedirect mixes params from multiple requests

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11451]
Some strange behavior:

URLMappings.groovy
```
'/images/publish'(redirect:[uri:'/v2/images/publish', permanent:true, keepParamsWhenRedirect: true])
```

2 users visit the url:
User 1:
/images/publish?ids=1,2,3
Experiences redirect to
/v2/images/publish?ids=1,2,3

User 2
/images/publish?ids=3,4,5
Experiences redirect to
/v2/images/publish?ids=1,2,3,3,4,5

if User 1 then visits again
/images/publish?ids=7,8,9
they get a redirect to
/v2/images/publish?ids=1,2,3,3,4,5,7,8,9

1. Why is it sharing  parameters between multiple users?  Is this expected behavior?
2. Is this known to behave this way? 
3. Can it be fixed so that it simply just passes the parameters specific to the request if I provide an example app?

**Comment by puneetbehl** [comment]
@codeconsole I am not able to reproduce the same behavior but a different error where given an `ImageController` as: 
```
class ImagesController {
    static namespace = "v2"

	static responseFormats = ['json', 'xml']
	
    def index() {
        String imageUrl = grailsLinkGenerator.link([uri: request.requestURI, params: params, absolute: true])
        respond(imageUrl: imageUrl)
    }
}
```
and the `URLMappings.groovy` with following mappings:
```
...
 '/images'(redirect:[uri:'/v2/images', permanent:true, keepParamsWhenRedirect: true])
 "/v2/$controller"(namespace: "v2")
```

When I request using CURL with query param `ids` as:

```
curl -L localhost:8080/images?ids=1,2,3 -H "Content-Type: application/json"
curl -L localhost:8080/images?ids=3,4,5 -H "Content-Type: application/json"
```
The response is correct each time. However, when change the query parameter to `foo=bar` as:
```
curl -L localhost:8080/images?foo=bar -H "Content-Type: application/json"
```
The response URL also contains previous parameter i.e. `ids=1%2C2%2C3` i.e. `http://localhost:8080/v2/images?ids=1%2C2%2C3&foo=bar` 

Here is the [sample application](https://github.com/puneetbehl/grails4urlmappingissue)

**Comment by puneetbehl** [comment]
@codeconsole I believe the problem is with caching `DefaultUrlMappingInfo` in [DefaultUrlMappingsHolder.java#L537](https://github.com/grails/grails-core/blob/4.0.x/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingsHolder.java#L537 ). Since, we are doing matches so caching makes sense but somehow we are also storing user request query parameters in the `DefaultUrlMappingsHolder.java:redirectInfo` which doesn't make sense and the root of the problem. 

I will continue to debug and fix the problem.

**Comment by codeconsole** [comment]
Sorry I never replied to the original comments. I never saw the email.
