### ISSUE TITLE
GrailsUnitTest not usable in PluginProjects with integration test workarounds from issues 11016 / 11074

### ISSUE THREAD

**Issue by boardbloke** [grails/grails-core#11453]
Issue https://github.com/grails/grails-core/issues/11016  and https://github.com/grails/grails-core/issues/11074 suggests that async should be excluded from plugin projects with integration tests as a workaround.

However if the same project has a unit test that implements GrailsUnitTest then that is not possible because GrailsUnitTest imports grails.async.Promises.  The async plugin is required to get unit tests to run..

Indeed to have a Plugin project that uses GrailsUnitTest (which requires async), and integration tests the only solution is to pull in the dependencies of async.

I managed to get it working not excluding async, and including the following in build.gradle.

   testRuntime "org.springframework.boot:spring-boot-starter-tomcat"
    testRuntime "org.grails:grails-web-boot"
    testRuntime "org.grails:grails-plugin-i18n"

Not sure if that is the minimum required and whether that works in all cases, but it did for the unit and integration tests I have.

This is a problem on Grails 3.3.11.  I have not tried Grails 4 yet.

**Comment by puneetbehl** [comment]
@boardbloke It seems like `org.grails:grails-async` is fetched as a transitive dependency of `org.grails.plugins:async`. Therefore, excluding the plugin `async` also removes `grails-async`. I believe the problem should be resolved once you include the following in your build.gradle file dependencies block:

```
testCompile "org.grails:grails-async:3.3.1"
```
