### ISSUE TITLE
Grails 4.0.1 does not respect server.compression.mime-types configuration for additional mime types other than default ones.

### ISSUE THREAD

**Issue by ChiranjibKarn** [grails/grails-core#11489]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. In `application.yml` the compression setting `server.compression.mime-types` add additional mime types e.g. `image/jpeg` .
2. Restart the application. 
3. Examine the response header in browser's network tab.

### Expected Behaviour

The newly added mime type should also get `gziped`.

### Actual Behaviour

It only compresses the default mime types that Spring Boot support but not the newly added (additional) mime types. The response header for jpeg images should also be like `content-encoding: gzip`.

### Environment Information
- **Grails Version:** 4.0.1
- **JDK Version:** 8
- **Container Version (If Applicable):** NA

**Comment by puneetbehl** [comment]
@ChiranjibKarn I am not able to replicate the issue. It might be that you need to configure `min-response-size` as the default value `2048B`. In any case please share a sample application.

**Comment by puneetbehl** [comment]
Closing due to lack of feedback
