### ISSUE TITLE
HTMLCodec (encodeAsHTML()) randomly fails

### ISSUE THREAD

**Issue by Trebla7th** [grails/grails-core#11488]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

When encoding a String as HTML, randomly and rarely (1/100,000 times?) the encoding fails to encode, leaving bad characters in the resulting String.  Only seems to be noticeable when encoding a large number of items.  But that's likely due to the rarity.

In the example project, do the following
1. Run the project (this will create 10,000 objects by default)
2. Navigate to the example controller: "/example"
3. Any values in the data set that failed to encode are listed here

Sometimes 10,000 was enough for me to get failures, sometimes I had to add a few more sets
4. Navigate to "/example/generateExamples" - repeat as necessary, this will generate 10,000 new records each time.

By the time I had 50,000 records, I would get a failure almost every time I refreshed the test page.

### Expected Behaviour

someString.encodeAsHTML() should work

### Actual Behaviour

Sometimes it doesn't.

Using the linked example, the following code:
```groovy
examples.each { example ->
    String name = example.name.encodeAsHTML()
    String value = example.value.encodeAsHTML()

    if(name.contains("&") && !name.contains("&amp")) {
        println("Name ${name} failed to encode")
        println("Unencoded name: ${example.value}  ---- Encoded name: ${value}")
        failures.add(new Example(name: name, value:value))
    }

    if(value.contains("&") && !value.contains("&amp")) {
        println("Value ${value} failed to encode")
        println("Unencoded value: ${example.value}  ---- Encoded Value: ${value}")
        failures.add(new Example(name: name, value:value))
    }
}
```

Produced the following output (note that the output was generated over the course of multiple times executing the path on the same dataset - 50000 example objects):

    Value value_&d325518d-eea1-4015-88f4-e59a0774bec0 failed to encode
    Unencoded value: value_&d325518d-eea1-4015-88f4-e59a0774bec0  ---- Encoded Value: 
    value_&d325518d-eea1-4015-88f4-e59a0774bec0
    Value value_&fac91fb0-4d8b-4d76-a5e7-6ffdf0c4863b failed to encode
    Unencoded value: value_&fac91fb0-4d8b-4d76-a5e7-6ffdf0c4863b  ---- Encoded Value: 
    value_&fac91fb0-4d8b-4d76-a5e7-6ffdf0c4863b
    Value value_&8171bfeb-9e7f-45f4-b96a-8f0dfa0baa46 failed to encode
    Unencoded value: value_&8171bfeb-9e7f-45f4-b96a-8f0dfa0baa46  ---- Encoded Value: 
    value_&8171bfeb-9e7f-45f4-b96a-8f0dfa0baa46
    Value value_&0de7da18-ffd8-43a4-840f-c3c56b2058b9 failed to encode
    Unencoded value: value_&0de7da18-ffd8-43a4-840f-c3c56b2058b9  ---- Encoded Value: 
    value_&0de7da18-ffd8-43a4-840f-c3c56b2058b9

### Environment Information

- **Operating System**: MacOS Mojave, RHEL
- **Grails Version:** Confirmed in 3.3.2 and 4.0.1
- **JDK Version:** Observed on both:
    OpenJDK Runtime Environment (build 1.8.0_242-b07)
    OpenJDK Runtime Environment (Zulu 8.33.0.1-macosx) (build 1.8.0_192-b01)

### Example Application

https://github.com/Trebla7th/html-codec-fail

**Comment by lhotari** [comment]
Hi @puneetbehl , 
I haven't been active in Grails development for some time, but this issue caught my eye.
I have written most of the implementation in grails-encoder which has a fairly complex solution for preventing double encoding and ensuring that all output is safely encoded. 
I did some checks and it seems that there's a bug in org.grails.encoder.DefaultEncodingStateRegistry class. The way it tracks whether a String is already encoded or not is by enlisting the String's System.identityHashCode value. However TIL, that there isn't a uniqueness guarantee for System.identityHashCode (https://stackoverflow.com/a/1063098). It would be better to rewrite  org.grails.encoder.DefaultEncodingStateRegistry without using System.identityHashCode at all. 
I hope this helps in fixing the issue. This is just my best guess of what the issue could be. It's possible that it's something else too. However, the randomness of the issue reproducing itself hints to the direction of a hash collision bug like there is in  org.grails.encoder.DefaultEncodingStateRegistry class.

**Comment by lhotari** [comment]
Thanks @Trebla7th for good work in reproducing the issue.

**Comment by lhotari** [comment]
(continuing the explanation of what could go wrong because of the buggy DefaultEncodingStateRegistry)
The way how the HTML encoding could get skipped is here: https://github.com/grails/grails-core/blob/2bc86905648799a192884d85d11668d0b36022f1/grails-plugin-codecs/src/main/groovy/org/grails/commons/DefaultGrailsCodecClass.java#L205-L207

**Comment by lhotari** [comment]
I made a small modification to the html-codec-fail repro app to verify the theory of the identityHashCode collision.
```
  if(name.contains("&") && !name.contains("&amp")) {
          println("Name ${name} failed to encode")
          println("Unencoded name: ${example.value}  ---- Encoded name: ${value}")
          println("Encoding state: " + webRequest.getEncodingStateRegistry().getEncodingStateFor(name))
          failures.add(example)
        }

        if(value.contains("&") && !value.contains("&amp")) {
          println("Value ${value} failed to encode")
          println("Unencoded value: ${example.value}  ---- Encoded Value: ${value}")
          println("Encoding state: " + webRequest.getEncodingStateRegistry().getEncodingStateFor(value))
          failures.add(example)
        }
```

It verifies the theory since each time the problem occurs, the encoding state is invalid (it shows that the value has already been encoded with HTML encoder):
```
Name key_&1d26d76d-6d26-43fd-b922-bf30969c46c1 failed to encode
Unencoded name: value_&e9414490-3b1d-4ade-b8b3-2140fcbbb072  ---- Encoded name: value_&amp;e9414490-3b1d-4ade-b8b3-2140fcbbb072
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
Value value_&9dd1c7a9-151c-4d9c-8fdd-43f3d957469c failed to encode
Unencoded value: value_&9dd1c7a9-151c-4d9c-8fdd-43f3d957469c  ---- Encoded Value: value_&9dd1c7a9-151c-4d9c-8fdd-43f3d957469c
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
Name key_&1d2ee103-e652-4020-8ad8-d0fade10fb79 failed to encode
Unencoded name: value_&0da4f9cc-f197-4969-b413-8ff8c50ab042  ---- Encoded name: value_&amp;0da4f9cc-f197-4969-b413-8ff8c50ab042
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
Name key_&e1a72fb0-9bd9-44d8-87a1-91d196e8ddac failed to encode
Unencoded name: value_&4040813d-ea19-452a-a79e-f172c9cad367  ---- Encoded name: value_&amp;4040813d-ea19-452a-a79e-f172c9cad367
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
Value value_&a191a4bf-5bb6-4056-9bab-2d964a29fd3e failed to encode
Unencoded value: value_&a191a4bf-5bb6-4056-9bab-2d964a29fd3e  ---- Encoded Value: value_&a191a4bf-5bb6-4056-9bab-2d964a29fd3e
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
Name key_&23c96a2e-3d46-4f8b-a78a-bb46ace0ff18 failed to encode
Unencoded name: value_&f9e043e7-ade8-43c0-ac70-da72060f8261  ---- Encoded name: value_&amp;f9e043e7-ade8-43c0-ac70-da72060f8261
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
Name key_&2213671c-6759-4970-8c5d-7437d6371fe1 failed to encode
Unencoded name: value_&27fa803d-afd7-47c4-8099-e758e12d34dc  ---- Encoded name: value_&amp;27fa803d-afd7-47c4-8099-e758e12d34dc
Encoding state: EncodingStateImpl [encoders=[@483588880 HTML safe:true apply to safe:false]]
```

**Comment by lhotari** [comment]
This is an unit test that reproduces the issue:
```
package org.grails.encoder

import org.grails.encoder.impl.HTMLEncoder
import spock.lang.Specification

class DefaultEncodingStateRegistrySpec extends Specification {

    void "should not have previous encoding state"() {
        given:
        DefaultEncodingStateRegistry encodingStateRegistry = new DefaultEncodingStateRegistry()
        HTMLEncoder htmlEncoder = new HTMLEncoder()

        expect:
        for (int i = 0; i < 100000; i++) {
            String value = "value_&${UUID.randomUUID()}"
            EncodingState encodingState = encodingStateRegistry.getEncodingStateFor(value)
            assert encodingState == EncodingStateImpl.UNDEFINED_ENCODING_STATE
            encodingStateRegistry.registerEncodedWith(htmlEncoder, value)
        }
    }
}
```

**Comment by lhotari** [comment]
Hi @puneetbehl , I created #11492 to fix the issue.

**Comment by lhotari** [comment]
Some tests are failing, checking

**Comment by Trebla7th** [comment]
Wow, you guys are fantastic!  Way to jump on it
