### ISSUE TITLE
Grails 4.0.2 - Micronaut ConfigurationException on startup

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-core#11495]
When upgrading from Grails 4.0.1 to Grails 4.0.2, references to undeclared variables in `application.groovy` cause `io.micronaut.context.exceptions.ConfigurationException` on app startup.

#### Example

_application.groovy_

    my.local.var = undefinedVar

With Grails 4.0.1, `my.local.var` value is computed successfully at compile time, while With Grails 4.0.2 Micronaut's ConfigurationException is thrown
`io.micronaut.context.exceptions.ConfigurationException: Exception occurred reading configuration [application]: No such property: undefinedVar for class: Script1`

#### Notes
- The issue does not seem to be related to a specific version of Micronaut
- Breaking change ([commit](https://github.com/grails/grails-core/commit/b3123a54ab7fdd07f153c4ff1fbf5364aa98d1e2)): by removing `micronaut-runtime-groovy` dependency from compile dependencies (in `build.gradle`) the app startup is successful

#### Example Application

https://github.com/ilPittiz/grails402ConfigurationException

#### Environment Information

- **Operating System**: MacOS 
- **Grails Version:** 4.0.2
- **JDK Version:** 11.0.5

**Comment by jameskleeh** [comment]
@ilPittiz Can you explain the purpose of having `my.local.var = undefinedVar` in your config?

**Comment by ilPittiz** [comment]
@jameskleeh My Grails project uses [External Config plugin](https://github.com/sbglasius/external-config/) to load external configuration properties.
Under certain circumstances some variables may not be defined, and unfortunately we cannot change this situation.

For this issue I reduced my use-case to a simpler scenario using only `application.groovy` as the outcome is the same.
