### ISSUE TITLE
Grails 4.0.2: empty form fields are not binded as NULL in params map

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#11506]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the attached project and navigate to http://localhost:8080/home/index
2. Click the 'Send' button

### Expected Behaviour

params['message'] should be NULL as in Grails 3.3.9

### Actual Behaviour

params['message'] is an empty string.

I've tried to set 

grails.databinding.trimStrings = true
grails.databinding.convertEmptyStringsToNull = true

in application.groovy but it did not work

### Environment Information

- **Operating System**: Linux
- **Grails Version**: 4.0.2
- **JDK Version**: 1.8.0_131
- **Container Version (If Applicable):** TODO

### Example Application
[app1.zip](https://github.com/grails/grails-core/files/4345185/app1.zip)

**Comment by puneetbehl** [comment]
@atasc I think it would only be null when doing data-binding to a command object. For example: if you modify the action as:
```
def index(DataCo dataCo) {
		def model = [:]
		String diplayMessage

		String message = dataCo.message

		if (message == null) {
			println "params.message is null!!!"
		} else {
			println "params.message is not null!!!"
		}
...
```

I believe the behavior would be the same in Grails 3.3.x.
