### ISSUE TITLE
URLMappings assets files

### ISSUE THREAD

**Issue by pangeaos** [grails/grails-core#11515]
Hi,

I'm upgrading my app 3 to Grails 4 but I have an issue into urlmappings.groovy.

```groovy
class UrlMappings {

	static mappings = {
		"/$controller/$action?/$id?(.$format)?"{
			constraints {
				// apply constraints here
			}
		}

		"/"(view:"/index")
		"500"(view:'/error')
		"404"(view:'/notFound')

		"/service-worker.js" (uri: '/assets/service-worker.js')
	}
}
```

The line **"/service-worker.js" (uri: '/assets/service-worker.js')** is not working on Grails 4.

Error: 404 not found

Any idea? Do something change between versions?

**Comment by pangeaos** [comment]
I have understood that for PWA apps, the server-worker.js has to be in the root, Any idea how locate that file in the root /?

**Comment by davydotcom** [comment]
If this worked in grails 3 that would have been an error. The AssetPipelineFilter happens early and should be happening before it even hits the Grails URL Mappings filter. This is for performance as well as just how static assets are handled. IT is possibly to change the default mapping for asset-pipeline to '' via 

```
grails:
  assets:
    mapping: ''
```

This will force all assets to default to the root path and if not found automatically chain down to controller/actions.

**Comment by davydotcom** [comment]
One can also place the file in src/main/webapp and it will be rendered at the root url mapping as well.
