### ISSUE TITLE
Plugin and lifecycle shutdown should be reverse order from startup

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#11517]
In Grails 4, plugins are sorted based on loadAfter, etc. dependencies to ensure that they are initialized in the correct order.

However, when the plugins are shutdown, they are shutdown in the same order. The order should actually be reversed such that, if plugin B must loadAfter A, then it will shutdown before A.

The order should be:

A.startup()
B.startup()
B.shutdown()
A.shutdown()

This causes us an issue because our custom plugin must loadAfter `dataSources`. However, on shutdown it needs to use the database in order to check for running jobs and do a cleanup shutdown. The dataSources shutdown is called first, destroying the connection pool and causing a failure.

The fix is simply to call `pluginList.reverse()` on the shutdown at:

https://github.com/grails/grails-core/blob/86305c733a00f5e2ce33b4c6506fe36228ff5fc5/grails-core/src/main/groovy/org/grails/plugins/AbstractGrailsPluginManager.java#L353

A similar problem exists for the lifecycle startup and shutdown, which invokes the BootStrap methods.

https://github.com/grails/grails-core/blob/86305c733a00f5e2ce33b4c6506fe36228ff5fc5/grails-core/src/main/groovy/grails/boot/config/GrailsApplicationPostProcessor.groovy#L273

The plugins are initialized first, then the lifecycle callbacks. On shutdown, the order should be reversed. Lifecycle shutdowns called first, then plugin shutdowns. This bug causes us to be unable to use any dataSources in the `BootStrap.destroy` closure since again it's called after the dataSources plugin is shutdown.

Unless there are objections, I will submit a PR.

**Comment by longwa** [comment]
https://github.com/grails/grails-core/pull/11518

**Comment by puneetbehl** [comment]
Thank you for the PR 👍
