### ISSUE TITLE
Groovy Date extensions seem to be missing in Grails 4.x.x

### ISSUE THREAD

**Issue by sk8geek** [grails/grails-core#11513]
In Grails 4.x.x is seems as though Groovy Date extensions are missing. In particular `Date().toCalendar()` is absent.

### Steps to Reproduce

1. grails create-app
2. add a test to use `Date().toCalendar()`
3. fails with `MissingMethodException`

### Expected Behaviour
A `Calender` object is returned.

### Actual Behaviour
`MissingMethodException` is thrown

### Environment Information
- **Operating System**: Fedora 31
- **Grails Version:** 4.0.2
- **JDK Version:** openjdk version "1.8.0_242"

### Example Application
- https://gitlab.com/sk8geek/ungroovy_dates

**Comment by erichelgeson** [comment]
See "Breaking Changes" in groovy 2.5 https://groovy-lang.org/releasenotes/groovy-2.5.html

>The extension methods for the java.util.Date class are now in a separate `groovy-dateutil` module which isn’t included by default when using the `groovy-all` pom dependency. Add the additional module as a dependency if you need it or consider migrating to the java.time JSR-310 classes (similar Groovy extension methods exist for those classes and they are included by default when using the groovy-all pom dependency).

**Comment by sk8geek** [comment]
Thank you @erichelgeson
