### ISSUE TITLE
Grails 4: How to test code that depend on Converters (like "as JSON")

### ISSUE THREAD

**Issue by johan313** [grails/grails-core#11521]
Please provide documentation on how to test a class that contains a Grails converter or update the test framework to support testing of such classes at least for integration testing.

Example: The following line in any class works fine in production, but fails in both unit-tests and integration tests:

`def json= "{}" as JSON`

with GroovyCastException: Cannot cast object '{}' with class 'java.lang.String' to class 'grails.converters.JSON'. Expected outcome is that a JSON type is returned.

I'm using Grails version 4.0.3. There seems to be the same problem with earlier versions in GRAILS-4715, however its been closed so I assume it was fixed. In Grails 3.X this issue could be circumvented like this https://stackoverflow.com/questions/11785708/how-do-i-unit-test-a-grails-service-that-uses-a-converter/15485593#15485593

**Comment by johan313** [comment]
I will update this with a valid example. Seems I simplified too much.

**Comment by bobbywarner** [comment]
JSON has two data structures: objects and arrays.  Your example is not working because you are trying to render invalid JSON (a string).  You can easily test the JSON converter using standard Grails unit tests.

Here is a simple controller:
```
package testing

import grails.converters.JSON

class HomeController {

    def map() {
        Map foobar = [a: 1, b: 2]
        render foobar as JSON
    }

    def list() {
        List foobar = [1, 2, 3]
        render foobar as JSON
    }
}
```

And here are a couple unit tests that demonstrate testing the converters:
```
package testing

import grails.testing.web.controllers.ControllerUnitTest
import spock.lang.Specification

class HomeControllerSpec extends Specification implements ControllerUnitTest<HomeController> {

    void "test render json converter with map"() {
        when:
        controller.map()

        then:
        status == 200
        response.json.size() == 2
    }

    void "test render json converter with list"() {
        when:
        controller.list()

        then:
        status == 200
        response.json.size() == 3
    }
}
```
