### ISSUE TITLE
RestfulController limits max=100, but accepts -1 to return all records

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#11538]
RestfulController.index() contains code that limits your page size to 100 records, but it also allows returning all records by setting ```max=1```.

If returning all records is allowed behavior, there is no reason to limit the page size, and the limit should be removed. If the intent is to limit the max # of results the client can query, the current behavior is buggy and should be fixed.

### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/rmorrise/grails-negative-max
2. ```grails run-app```
3. Visit ```localhost:8080?max=200```
4. Visit ```localhost:8080?max=-1```

### Expected Behaviour

**Either:**
Both should return 200 records

**Or:**
Both should return 100 records

**Or:**
```?max=-1``` should respond with an HTTP 400.

### Actual Behaviour

```?max=200``` returns 100 records

```?max=-1``` returns all records

### Environment Information

- **Operating System**: Win10 x64
- **Grails Version:** 4.0.2 (and earlier)
- **JDK Version:** openjdk version "1.8.0_252"

### Example Application

https://github.com/rmorrise/grails-negative-max

**Comment by niravassar** [comment]
@puneetbehl i created a PR for this, please verify

**Comment by niravassar** [comment]
@puneetbehl I rebased on a proper branch
