### ISSUE TITLE
Autoreload for mirconaut declarative client not working

### ISSUE THREAD

**Issue by kbachl** [grails/grails-core#11543]
#Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create new grails app
2. add implementation("io.micronaut:micronaut-http-client")
3. create an interface annotated like

`@Client("http://xxx:1234/b1s/v1/")`
`interface MicroNautClient {`
`@Post("/Logout")`
    `void logout()`
`}`

4. create a service and inject the client like this:
` @Autowired`
   ` MicroNautClient client`
and use it in any method that gets called like this `client.logout()`

5. change the name of the method for demo purpose in both service and interface to logout2()
6. save file and wait for reload messages
7. on browser reload u get stack trace complaining method not found

### Expected Behaviour

The micronaut client file should get recreated with the newly added method, this hot reloaed

### Actual Behaviour

No hot reload working

### Environment Information

- **Operating System**: ubuntu 18.04 LTS 
- **Grails Version:** 4.0.3
- **JDK Version:** openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
- **Container Version (If Applicable):** grails run-app

**Comment by niravassar** [comment]
*Reproduced Problem*

https://github.com/niravassar/mn-reload

I was able to reproduce the problem with a sample app. do `run-app`. go to 

http://localhost:8080/sample/index

Then change the `MicronautClient.getCall()` to `getCall2`. Wait for reload and you get the error

**Comment by kbachl** [comment]
any ETA for 4.0.4 and a fix of this? - its quite unusable without this for us

**Comment by puneetbehl** [comment]
The Grails 4.0.4 would probably be released next week without a fix for this issue. I will take a look at this issue before the release and try to include the fix.
