### ISSUE TITLE
application-development.groovy is not loaded

### ISSUE THREAD

**Issue by jagedn** [grails/grails-core#11553]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create an empty application with grails 4.0.3
2. create a development configuration file at grails-app/conf/application-development.groovy
3. put a trace into Bootstrap to print it
4. run the application

### Expected Behaviour

a console message with the value of the configuration

### Actual Behaviour

the value of the configuration is empty

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 4.0.3
- **JDK Version:** 1.8

### Example Application

- https://github.com/jagedn/grails4-test

**Comment by puneetbehl** [comment]
It seems to be happening because of the check for`loaded` in [GroovyConfigPropertySourceLoader.groovy](https://github.com/grails/grails-core/blob/4.0.x/grails-core/src/main/groovy/org/grails/core/cfg/GroovyConfigPropertySourceLoader.groovy#L53) which is set when `application.groovy` is processed, so prevent loading configuration from the `application-development.groovy`.

I think the solution would be to update the check with the name.

**Comment by puneetbehl** [comment]
Meanwhile, if you can use YAML instead of Groovy configuration then I think it would work fine.

**Comment by jagedn** [comment]
yes, I tested with `application-development.yml` and it works

we are upgrading from 3.x to 4.x and we have several configurations in groovy style but we can try to move them.

Thanks

**Comment by puneetbehl** [comment]
I think as a workaround you could create a `CustomGroovyConfigPropertySourceLoader` which updates the check and registers it using the spring.factories. However, I think you also need to prevent loading `application.groovy` multiple times maybe exclude it using `if` condition in your custom implementation.

**Comment by niravassar** [comment]
I am looking at this ticket. I experimented and it will also work if you have an `application.yml`, with a `application-development.groovy` file.

I will be looking into the fix for the original issue.

**Comment by niravassar** [comment]
@puneetbehl I created a PR and wrote some nows in their for a review. Please take a look. I directed some questions toward graeme also

**Comment by sagrawal31** [comment]
Oh! I didn't know that `application-*.groovy` can be used for environment-specific files. So is it like `application-development.groovy` can have development environment config and `application-staging.groovy` can have staging environment config without declaring `environments` block?

(We have been using files like `application-sms.groovy` or `application-redis.groovy`)

**Comment by niravassar** [comment]
you can define another section in the `environments` in `application.yml` if you want to define some configuration. In addition, you can define groovy files with the environment name appended like you mentioned above.  To tell grails which environment configuration to use you can pass in the clause `-Dgrails.env=staging` for example.

**Comment by sagrawal31** [comment]
Thanks for the clarification, @niravassar. I just wanted to know about the append pattern.
