### ISSUE TITLE
Grails 4.1.0.M1: Groovy version conflict in tests

### ISSUE THREAD

**Issue by davidkron** [grails/grails-core#11564]
I'm upgrading a Grails 3 application to 4.1.0.M1 and I have problems running a lot of our tests. I am getting exceptions like these:

```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]

Reported exception:

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

Could not instantiate global transform class org.spockframework.compiler.SpockTransform specified at jar:file:/C:/Users/david/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/2.0-M2-groovy-3.0/396867de1bbbe11e85e197c22f0e6de07643185a/spock-core-2.0-M2-groovy-3.0.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception org.spockframework.util.IncompatibleGroovyVersionException: The Spock compiler plugin cannot execute because Spock 2.0.0-M2-groovy-3.0 is not compatible with Groovy 2.5.9. For more information, see http://docs.spockframework.org

Spock artifact: file:/C:/Users/david/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/2.0-M2-groovy-3.0/396867de1bbbe11e85e197c22f0e6de07643185a/spock-core-2.0-M2-groovy-3.0.jar

Groovy artifact: file:/C:/Users/david/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.3/4cdb30d88ce52f489f1d7de2b001cb04d867224b/groovy-3.0.3.jar
```

What I discovered in IntelliJ was that there were multiple versions of "groovy-test" listed under "External Libraries" (3.0.3 and 2.5.9). This is the output of gradle dependencyInsight:

`gradlew dependencyInsight --configuration testCompileClasspath --dependency "org.codehaus.groovy:groovy-test:2.5.9"`
```
> Task :dependencyInsight
org.codehaus.groovy:groovy-test:2.5.9 (selected by rule)
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]

org.codehaus.groovy:groovy-test:3.0.3 -> 2.5.9
\--- org.grails:grails-test:4.1.0.M1
     \--- org.grails:grails-testing-support:2.2.0.M1 (requested org.grails:grails-test:4.0.0)
          +--- org.grails:grails-web-testing-support:2.2.0.M1
          |    \--- testCompileClasspath (requested org.grails:grails-web-testing-support)
          \--- org.grails:grails-gorm-testing-support:2.2.0.M1
               \--- testCompileClasspath (requested org.grails:grails-gorm-testing-support)
```

Unfortunately I currently can't reproduce the exception with a fresh Grails application and some simple test. And I can't provide a project since this is an internal application of my company.

What I can say is that the above dependencyInsight report from Gradle also reports groovy-test:2.5.9 in a newly created Grails 4.1.0.M1 application.

### Task List

- [ ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Can't reproduce with a fresh Grails application and a simple test.

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 4.1.0.M1
- **JDK Version:** JDK 11
- **Container Version (If Applicable):** TODO

**Comment by puneetbehl** [comment]
Please define `groovyVersion` property in the gradle.properties file. I think that would fix the issue.

**Comment by davidkron** [comment]
You are right, that was the problem. Thank you!
