### ISSUE TITLE
grailsApplication.getArtefacts("Domain") returns empty list during integration test

### ISSUE THREAD

**Issue by xqliu** [grails/grails-core#11574]
grailsApplication.getArtefacts("Domain") returns empty list during integration test

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a minimal application
2. Create a domain class and control class
3. Create an integration test for the controller

### Expected Behaviour

grailsApplication.getArtefacts("Domain") should return list of domains defined

### Actual Behaviour

grailsApplication.getArtefacts("Domain") returns an empty list during integration test of a controller

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 4.0.3
- **JDK Version:** 11
- **Container Version (If Applicable):** N/A

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by bobbywarner** [comment]
I can't reproduce this issue.  I created a new Grails 4.0.3 application and added two domain classes and an integration test.  
```
grails create-domain-class book
grails create-domain-class author
grails create-integration-test sample
```

I then added an integration test as follows to `SampleSpec`:

```
    void "test domain count"() {
        when:
        List domains = grailsApplication.getArtefacts("Domain")
        println domains

        then:
        2 == domains.size()
    }
```

The test passes as expected and the following is printed out from the `println` in the test:
```
[Artefact > Author, Artefact > Book]
```

Please reopen or create a new issue with an example application that reproduces the issue for you.

**Comment by xqliu** [comment]
Have found the issue is because I have  implements `ControllerUnitTest<DomainMetaController> `

Confirmed if remove this interface implementation, then it was injected successfully
