### ISSUE TITLE
Grails and JDK 11 warning

### ISSUE THREAD

**Issue by mmcedora** [grails/grails-core#11605]
### Task List

- [ x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x ] Full description of the issue provided (see below)

### Steps to Reproduce

Install OpenJDK 11
Install Grails 4.04
Run "Grails" from command line (on Windows)

### Expected Behaviour

Grails command should work without warnings

### Actual Behaviour

grails --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/........../JavaTools/grails-4.0.4/lib/org.codehaus.groovy/groovy/jars/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Grails Version: 4.0.4
| JVM Version: 11.0.8

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 4.04
- **JDK Version:** 11.0.8

**Comment by puneetbehl** [comment]
Could you please try with Grails 4.1.0.M1?
