### ISSUE TITLE
Services in Command Objects are null when accessed from BindUsing closures.

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [grails/grails-core#11608]
### Steps to Reproduce

1. Create a command object with a service and access it in a BindUsing closure, like

```
class WebRequest implements grails.validation.Validateable {
def databaseService

@BindUsing({ obj, source ->
return databseService.findMyDomainByLatLng(source['latitude'],source['longitude'])
})
MyDomain myDomain

}
```

### Expected Behaviour

I would expect to be able to access the service in the BindUsing closure, like I can access it in the constraints section (creating a custom validator). 

Why? Because I execute a database query and I would like to cache it. 

In my case I want to look up myDomain by latitude and longitude and find the closest myDomain to the coordinates. This operations takes long and I would like to move the SQL out of the BindUsing closure into the service in order to cache it. 

That's currently not possible.

### Actual Behaviour

The service is not being injected at the time of data binding. It's value is null.

### Environment Information

- **Operating System**: Debian Buster
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8

### Example Application

- See above

**Comment by davydotcom** [comment]
I'm not sure on command objects but I know this default behavior was phased out of domain classes as it's a bit heavy to inject Beans on so many instanced objects.

**Comment by davydotcom** [comment]
Did you happen to try obj.databaseService?

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
Yes, makes no difference.

**Comment by davydotcom** [comment]
Hmm, wait the above isn't even a CommandObject its just Validateable.

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
That makes it a command object according to the docs. If its in the same source controller file, you dont even have to implement Validateable. So that's not the problem.

**Comment by ng-druid** [comment]
Same issue grails 3.2

**Comment by jeffscottbrown** [comment]
Dependency injection, by design, happens after data binding.  Because of that you cannot access DI'd properties during data binding.

**Comment by jeffscottbrown** [comment]
> That makes it a command object according to the docs. If its in the same source controller file, you dont even have to implement Validateable. So that's not the problem.

That is not really correct.  It is not the case that marking something as Validateable makes it a command object.  Any arbitrary Groovy class can be made Validateable.  Command objects are parameters controller action methods.

**Comment by jeffscottbrown** [comment]
>  I understand what you mean, but then why is it injected when contraints are being checked. That's inconsistent behavior.

Constraint checking is done later in the process.  DI, binding, and constraint checking can't all happen before the other 2.
