### ISSUE TITLE
Static pages are intercepted, without consistency in handling

### ISSUE THREAD

**Issue by jonmor51** [grails/grails-core#11629]
In Grails 4.0.4, URLs for e.g. CSS and images, beginning with '/static/', are being picked up by an interceptor set to 'matchAll', even when specifically excluded with "excludes(controller:'static')". A simple example below:

```
package myapp
class SecurityInterceptor {
    SecurityInterceptor() {
      matchAll().excludes(controller:'static')
     }
    boolean before() {
        log.info "${controllerName}:${actionName}"
        if(controllerName=="static"){
            log.info "Static page, should not be intercepted"
         }
        return true
    }
    boolean after() { true }
    void afterView() {
    }
}
```

Now, if I call a URL like 'http://localhost:8080/static/blah', I would expect that this would be excluded by the exclusion clause in the constructor (given that Grails apparently sees the 'static' bit as a controller). But it isn't. It prints this to the log:

```
2020-10-06 12:13:22.485  INFO --- [  XNIO-4 task-1] myapp.SecurityInterceptor              : static:blah
2020-10-06 12:13:22.485  INFO --- [  XNIO-4 task-1] myapp.SecurityInterceptor              : Static page, should not be intercepted
2020-10-06 12:13:22.494  INFO --- [  XNIO-4 task-1] myapp.SecurityInterceptor              : static:blah
2020-10-06 12:13:22.495  INFO --- [  XNIO-4 task-1] myapp.SecurityInterceptor              : Static page, should not be intercepted
```

2 points to note here: the use of 'controller' in the excludes is clearly not working, yet 'controllerName' in the before method is; and I would suggest that '/static/*' pages generated by the Grails build process probably shouldn't be handled by interceptors anyway, but if they are it would be good if there were some consistency.  I can work around this by simply having this at the beginning of the before method: 

`if( controllerName=="static"|| controllerName=="null" || !controllerName) return true`

But it would be better if this were not necessary.

**Comment by davydotcom** [comment]
static assets are not rendered by a controller. They are rendered by a filter. This is something you want to potentially exclude by a uri pattern

The below may work
```
matchAll()
    .excludes(uri:~/static\/*/)
```

Please refer to the docs on different match pattern capabilities regarding controllers, actions, and URIs. It is important to note that not all URIs tie directly to a controller as some are higher level system Uris or spring ones.

**Comment by jonmor51** [comment]
This 'excludes' does not work. The interceptor still runs, and I have to use `if (controllerName == "static") return true` in the before to stop security kicking in. Try it.
