### ISSUE TITLE
Not able to map groovy class or domain class with hibernate xml mapping.

### ISSUE THREAD

**Issue by upretiprabin** [grails/grails-core#11633]
I am using grails 4.0.3 with gorm version 7.0.4.RELEASE
I have a hibernate config file hibernate.cfg.xml in location : grails-app/conf
which is this :
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE hibernate-configuration PUBLIC
        '-//Hibernate/Hibernate Configuration DTD 3.0//EN'
        'http://www.hibernate.org/dtd/hibernate-configuration-3.0.dtd'>

<hibernate-configuration>

    <session-factory>
        <mapping resource='com.prabin.Prabin.hbm.xml'/>
    </session-factory>

</hibernate-configuration>
```

mapping file com.prabin.Prabin.hbm.xml is located at some location grails-app/conf which is :
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hibernate-mapping PUBLIC "-//Hibernate/Hibernate Mapping DTD//EN" "http://hibernate.org/dtd/hibernate-mapping-3.0.dtd">
<hibernate-mapping>
    <class name="com.prabin.Prabin" table="prabin_table">
        <id name="id" column="prabin_edited_id">
            <generator class="identity"/>
        </id>
    </class>
</hibernate-mapping>
```

My domain class:

```
package com.prabin
class Prabin {
    Integer id;
    static constraints = {
    }
}
```

I am just not able to use hibernate xml mapping. I have tried with groovy class and also with java class.
I have also tried changing the location from grails-app/conf to grails-app/hibernate for keeping mapping files. Non of these seems to work.

My requirement is i need to use xml mappings.

**Comment by puneetbehl** [comment]
Here is the sample application https://github.com/puneetbehl/grails-hibernate-xml-config-example
