### ISSUE TITLE
serverBaseURL contains the port 80 automatically

### ISSUE THREAD

**Issue by ecruiser** [grails/grails-core#11634]
Using grailsLinkGenerator.serverBaseURL to get the URL has the port 80 at the end. This is not expected. In production, https is enabled so port 80 at the end creates an issue. 

### Task List

- [ ] See the steps to reproduce below
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. add the codes like: 
            def baseUrl = grailsLinkGenerator.serverBaseURL

NOTE: grails.serverURL is not defined in application.yml when doing this. After adding this entry, baseUrl is equal to grails.serverURL. I don't want this as it becomes a static definition. 

### Expected Behaviour

The baseUrl should be like https://domain.com

### Actual Behaviour

It's displayed like https://domain.com:80

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Grails Version:** 4.0.3
- **JDK Version:** 1.8.201
- **Container Version:** Tomcat 9.0.16

**Comment by puneetbehl** [comment]
@ecruiser I am not sure if I understand the use case as I think we should be using the `grails.serverURL` configuration for the production environment.

**Comment by ecruiser** [comment]
@puneetbehl Thank you for your reply. My understanding is that grailsLinkGenerator.serverBaseURL can obtain the site's URL dynamically, which means if it's deployed to www.A.com, it should get www.A.com, or if it's deployed to www.B.com, it should be www.B.com. I don't want to define a static URL in the application, which uses grails.serverURL. 

However, I find they are related. I'm not sure how grailsLinkGenerator.serverBaseURL works. But if I define grails.serverURL: www.A.com in the app and even deployed to www.B.com, serverBaseURL=www.A.com; if I don't define this entry and the it's deployed to www.B.com, serverBaseURL=www.B.com.

**Comment by davydotcom** [comment]
be mindful if you don't define grails.serverURL, link generators for email templates will not behave correctly. just as a side note. but the port should not be getting included here if its the standard protocol port

**Comment by davydotcom** [comment]
are you doing SSL termination at the VIP?

**Comment by davydotcom** [comment]
it appears your listening on port 80 on the request with protocol https which is non standard. please provide more information.
