### ISSUE TITLE
 Application at context path [/root] could not be started Grails 4.0.4 tomcat deploy

### ISSUE THREAD

**Issue by jagritiS** [grails/grails-core#11646]
I am using grails 4.0.4 and trying to upload the war file in tomcat 9 but everytime it show following error 
 Application at context path [/root] could not be started
The task i have done 
This is my datasource:
[](production:
        dataSource:
            dbCreate: update

            url: jdbc:mysql://url/ems
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: myusername
            password: mypassword
            properties:
                    jmxEnabled: true
                    initialSize: 5
                    maxActive: 50
                    minIdle: 5
                    maxIdle: 25
                    maxWait: 10000
                    maxAge: 600000
                    timeBetweenEvictionRunsMillis: 5000
                    minEvictableIdleTimeMillis: 60000
                    validationQuery: SELECT 1
                    validationQueryTimeout: 3
                    validationInterval: 15000
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: false
                    jdbcInterceptors: ConnectionState
                    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
)

and after creating war file i have renamed the war file as root.war and uploaded it in tomcat/webapps
but wheneve i start the server i get this error 
FAIL - Application at context path [/root] could not be started
I am in need of help. Please help will be appreciated. Thanks

**Comment by puneetbehl** [comment]
@jagritiS  Please share the complete stack trace of the error. It could be happening due to multiple reasons so it is difficult to figure out what is wrong.

**Comment by jagritiS** [comment]
Its fixed

**Comment by paulosilva** [comment]
Hi @jagritiS can you share the solution ?
