### ISSUE TITLE
Proxy setting is not working in windows 10

### ISSUE THREAD

**Issue by learning** [grails/grails-core#11644]
In Windows 10, grails with proxy not works

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. First of all, I have some proxy settings in `~/.gradle/gradle.properties` and I'm sure it works
```
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
```
2. Follow [this instruction](https://docs.grails.org/4.0.5/guide/single.html#proxyConfig) to setting proxy for `grails`, in Windows' Environment Variables setting

| Name | Value |
| --- | --- |
| GRAILS_OPTS | -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 |

3. Create a new project with `grails`
```
D:\Projects\> grails create-app demo
```
4. Run this new project
```
D:\Projects\demo> grails run-app
```

### Expected Behaviour

Run a dev-server on http://localhost:8080

### Actual Behaviour

Request timeout when gradle update dependencies, **but `./gradlew bootRun` works perfectly**

### Environment Information

- **Operating System**: Windows 10 20H2
- **Grails Version:** 4.0.5
- **JDK Version:** 11.0.2

### Example Application

Just a empty project from `grails create-app demo`

**Comment by learning** [comment]
I changed the environment variable to


Name | Value
-- | --
GRAILS_OPTS | -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890


**`grails run-app` still with error**

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'demo'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jboss:jandex:2.1.1.Final.
     Required by:
         project : > org.grails.plugins:hibernate5:7.0.4 > org.hibernate:hibernate-core:5.4.10.Final
      > Could not resolve org.jboss:jandex:2.1.1.Final.
         > Could not get resource 'https://repo.grails.org/grails/core/org/jboss/jandex/2.1.1.Final/jandex-2.1.1.Final.pom'.
            > Could not GET 'https://repo.grails.org/grails/core/org/jboss/jandex/2.1.1.Final/jandex-2.1.1.Final.pom'.
               > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1m 9s
| Error Error initializing classpath: peer not authenticated (Use --stacktrace to see the full trace)
```

```
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL in 1m 7s
| Error Could not resolve all dependencies for configuration ':testRuntime'. Type 'gradle dependencies' for more information
```

**But, after running `./gradlew bootRun` once, everything works well..**

**Comment by puneetbehl** [comment]
Are you sure that the proxy server is running? It may happen when your proxy server is down. Please verify that you are able to successfully use proxy outside of Grails as well.

**Comment by learning** [comment]
@puneetbehl  Yes, I'm sure it is running, beacuse my gradle is running behide it and `./gradlew bootRun` works well in a grails project

**Comment by puneetbehl** [comment]
FYI, I was able to test it on the Windows VM and only see this error when the proxy is down otherwise everything was working fine.
