### ISSUE TITLE
Removal from the Grails Jira 

### ISSUE THREAD

**Issue by loeschg** [grails/grails-core#11656]
Somehow I got associated with the Grails Jira, and I'd love to be removed. I'm unable to manually leave and would love to get some help. There are a few other people who are also in the same situation from what I can tell looking at recent activity (see https://grails.atlassian.net/browse/ADMIN-26).

I was told to contact @graemerocher or Trevor Marshall who no longer seems to be a part of this project. https://grails.atlassian.net/secure/Dashboard.jspa

Sorry to clutter up this project, but I haven't been able to get in contact any other way. Any help would be awesome!

**Comment by puneetbehl** [comment]
@loeschg I have asked Graeme to do it.

**Comment by loeschg** [comment]
Thank you! Hope to get this sorted out.

**Comment by graemerocher** [comment]
I am not involved greatly with Grails at the moment but as far as I am concerned the whole JIRA instance can be shutdown since I don't believe it is used

**Comment by loeschg** [comment]
@graemerocher would you be ok with being added to an Atlassian support thread I have going? Sounds like they already have an associated gmail account of yours and need confirmation coming from that email to move forward with getting me removed.

**Comment by graemerocher** [comment]
sure

**Comment by loeschg** [comment]
Looks like I'm all sorted out here. Thanks!
