### ISSUE TITLE
What's news link is broken

### ISSUE THREAD

**Issue by bitsnaps** [grails/grails-core#11703]
Hello folks,

The [What's new](https://docs.grails.org/4.1.0.M4/guide/introduction.html#whatsNew) link in [release-page](https://github.com/grails/grails-core/releases/tag/v4.1.0.M4) page is (many times) broken, could you just fix a link pattern?

Thanks

**Comment by puneetbehl** [comment]
I have published the docs for 4.1.0.M3 and 4.1.0.M4, the links should be working in a few hours.

**Comment by bitsnaps** [comment]
This should fix it, Thanks!
