### ISSUE TITLE
Outdated Favicon

### ISSUE THREAD

**Issue by osscontributor** [grails/grails-core#11723]
For newly created apps (with 4.0.7 and many previous versions) the favicon is https://raw.githubusercontent.com/grails/grails-core/a5ea36df9f1136dfbfdf7b24ff493afa696929b8/media/icons/favicon.ico.  i think that should be updated to be a copy of https://raw.githubusercontent.com/grails/grails-static-website/f10b0001069cb27f0134a1653c2674ebb93d2483/assets/images/favicon.ico.

**Comment by jeffbrown** [comment]
A relevant pull request is available at https://github.com/grails/grails-core/pull/11747.

**Comment by imranmir** [comment]
Currently the favicon in a newly created 4.0.8 and 4.0.7 app looks like : 
![Screenshot from 2021-03-29 20-31-04](https://user-images.githubusercontent.com/382918/112857213-4037e600-90ce-11eb-9b53-1c6d9c868505.png) and it is different than the one mentioned above.
Does this need to me changed?

**Comment by jeffbrown** [comment]
https://github.com/grails/grails-core/blob/cc3b14755c927bb30dc1bccf2912820cf6b1078d/media/icons/favicon.ico also points to the green favicon (that is currently the latest code in the `master` branch).

**Comment by jeffscottbrown** [comment]
@ZacharyKlein @puneetbehl Do you think this issue should be closed?
