### ISSUE TITLE
Grails multi-project: Unable to render template from a plugin

### ISSUE THREAD

**Issue by Taack** [grails/grails-core#11731]
in a service, in a plugin, implementing `Controller` trait, `render` do not look at the `plugin` parameter if passing `template` into the parameter map:

```groovy
render template: "/my/block.gsp", layout: "my", plugin: "my", model:[:]
```
is equivalent to 
```groovy
render template: "/my/block.gsp", layout: "my", model:[:]
```
The `plugin` parameter has no effects..

A work around seems to use view instead of template, but not sure about customizing layout using view parameter. I prefer to stick with template.

Seeing trait `ResponseRenderer`, line 265: I do not see any code watching at `ARGUMENT_PLUGIN`. Do not really know the best way to fix this..

Thanks for your support,
Adrien

**Comment by jeffbrown** [comment]
Are you using a Grails service which implements `grails.artefact.Controller`?

**Comment by Taack** [comment]
yes

**Comment by Taack** [comment]
Just one additional information: the code

```groovy
@GrailsCompileStatic
class SomeService {

    @Autowired
    PageRenderer g

   def someMethod() {
           // [. . .]
           String html = g.render template: "/common/block-pdf", model: [
                block           : blockStream.toString(),
                css             : css.toString(),
                headerHeight    : htmlPdf.headerHeight
                ]
           // [. . .]
   }
}
```
Seems to resolve  `/common/block-pdf` into the plugin ...

**Comment by jeffbrown** [comment]
Why do you want a service to implement `Controller`?  Is that because you want the `render` method from `ResponseRenderer`?

**Comment by Taack** [comment]
Yes, in our case, we do not use GSP into our controller (I know, this looks strange). The raw html code is generated via a DSL. The controller only contains the DSL and a service is responsible to translate the DSL and to call `render`. This way, we just have 1 line of code to render the DSL into the controller... The code is more compact this way.

**Comment by Taack** [comment]
Anyway, there is a work around using the second approach, we just need the template in the plugin to be called. We can avoid the `plugin` parameter. If the fix is too much of a headache, I can close this bug report.

**Comment by jeffbrown** [comment]
I don't know if adding the render method to a service is really the right thing to do but if you do want to do that, I would try to implement `ResponseRenderer` instead of `Controller`.  If you implement `Controller` you are bringing in a bunch of stuff that you don't need and creating a problem for any code that every expects all `Controller` beans in the context to actually be a controller.

**Comment by Taack** [comment]
Ok, I will try to do that. 

Many thanks for your time and your work. I close this bug report, it is kind of a corner "use-case".

**Comment by Taack** [comment]
FYI, everything enter in order, the `build.gradle` was missing `apply plugin: "org.grails.grails-gsp"` line ...
