### ISSUE TITLE
Feature request: Document how to know which features are available for create-app command

### ISSUE THREAD

**Issue by jarl-dk** [grails/grails-core#11751]
According to https://docs.grails.org/latest/ref/Command%20Line/create-app.html the grails command `create-app` takes an optional flag `--features`, however there is no list of possible feature to give as argument to `--features`.

It would make much sense to have argument `--list-features` to `create-app`. Or at least document on https://docs.grails.org/latest/ref/Command%20Line/create-app.html how you can know what features that are available

I have later figures out that features are dependent on the profile, and a list of features seem available for a given profile using
```
grails profile-info <<PROFILE>>
```
But then at least that should be documented, both on web and in command line help message.

See also https://github.com/grails/grails-doc/issues/778

**Comment by jamesfredley** [comment]
This changed with grails-forge in Grails 6 and was resolved. https://docs.grails.org/latest/ref/Command%20Line/create-app.html
