### ISSUE TITLE
Domain not marked dirty when modified internally (no abstract base class involved)

### ISSUE THREAD

**Issue by LuisMuniz** [grails/grails-core#11752]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails 4.0.6 Application in start.grails.org (rest-api profile)
2. Add the following grails Artifacts and classes:

AuthorProperties abstract class
```groovy
package dirtybug

abstract class AuthorProperties {
    String name
}
```
Author Domain class:
```groovy
package dirtybug

class Author {
    String name

    static constraints = {
        name nullable: false, unique: true, maxSize: 100
    }

    //LMU: this does not mark the domain object dirty,
    //so the object is not persisted to the DB at the end of the transaction :(
    //Note that in the Hibernate session the object remains updated
    Author updateFromBuggy(AuthorProperties other) {
        this.name = other.name
        this
    }

    //this works
    Author updateFrom(AuthorProperties other) {
        this.name = other.name
        markDirty()
        this
    }
}

```
AuthorService:

```groovy
package dirtybug

import grails.gorm.transactions.Transactional

@Transactional
class AuthorService {

    Author update(Long id, AuthorProperties props) {
        def existing=Author.get(id)
        existing.updateFromBuggy(props)
        existing.save(flush:true)
    }
}

```

AuthorController:

```groovy
package dirtybug

class AuthorController {
	static responseFormats = ['json', 'xml']
    AuthorService authorService
	
    def index() {
        respond Author.list()
    }

    def show(Long id) {
        respond Author.get(id)
    }

    def save(Author newAuthor) {
        respond newAuthor.save()
    }

    def update(Long id) {
        respond authorService.update(id,new UpdateAuthorCommand(request.JSON))
    }
}
```
UpdateAuthorCommand

```groovy
package dirtybug

import grails.validation.Validateable

class UpdateAuthorCommand extends AuthorProperties implements Validateable {
    static constraints = {
        importFrom(Author)
    }
}
```

3. Create http scratch (on idea), you can use curl too

```http
POST http://localhost:8080/author
Content-Type: application/json

{
  "name": "one"
}
###

PUT http://localhost:8080/author/1
Content-Type: application/json

{
  "name": "oneone"
}
###

GET http://localhost:8080/author/1
```

### Expected Behaviour

After creating an Author with the first request, and updating its name to `"oneone"` with the second request, one expects the GET request to return the following structure:

```json
{
  "id": 1,
  "name": "oneone"
}
```

### Actual Behaviour

The GET request returns the following JSON structure:

```json
{
  "id": 1,
  "name": "one"
}
```

### Environment Information

- **Operating System**: linux
- **Grails Version:** 4.0.6
- **JDK Version:** jdk 11
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/LuisMuniz/grails4-dirtybug

**Comment by arixmkii** [comment]
Try this instead.

```groovy
    Author updateFromBuggy(AuthorProperties other) {
        this.setName(other.name)
        this
    }
```

Background. This is just how groovy's sugar syntax works inside the class. `this.fieldname = newValue` will stay unchanged, but `otherObject.fieldname = newValue` is translated to `otherObject.setFieldname(newValue)`.

In case of Domain object it bypasses proxied method call, so, there is no change to dirty flag. I don't think it is a bug (or especially Grails bug as it is related to Groovy language), but just some specifics how groovy works. And I don't see a reasonable fix here, as you have to provide means to access fields w/o using getters and setters inside the same class. And it maps to how Java works (Groovy tries to be compatible drop-in for compiling Java sources).

**Comment by LuisMuniz** [comment]
Thanks, i guess we can classify this as not being a bug, but is there a section in the documentation that points out this behavior?

That would be helpful, in the GORM documentation.

**Comment by gelleouet** [comment]
This is due to a change in GORM v6.1
http://gorm.grails.org/6.1.x/hibernate/manual/#upgradeNotes, 1.2.13. New Dirty Checking Implementation

> The implementation modifies all setters of your class so that dirty checking is tracked per field. However, there is one corner case where you do name = "blah" in a method internal to the class, the setter will not be called and property will not be marked as dirty. Hence, changing it to setName("blah") resolves the issue.

You can retrieve old behavior with 
```
hibernate:
    hibernateDirtyChecking: true
```
