### ISSUE TITLE
define grails memory settings while testing

### ISSUE THREAD

**Issue by jostheron** [grails/grails-core#11773]
I have a grails 4.0.2 application with a integration test that requires a large amount of memory.

Currently when I run the test it fails with: java.lang.OutOfMemoryError: GC overhead limit exceeded. In older grails you could define grails.project.fork in build.config.

Additionally,I've tried specifying GRAILS_OPTS with desired memory configurations but this gives me the message -> ignoring option MaxPermSize=512m; support was removed in 8.0

I've also tried adjusting build.gradle to the below

```groovy
bootRun {
    ignoreExitValue true
    jvmArgs(
        '-Dspring.output.ansi.enabled=always', 
        '-noverify', 
        '-XX:TieredStopAtLevel=1',
        '-Xmx2048m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx2048m']
    }
}
```
What is the correct way of specifying memory settings for testing grails 4?

**Comment by jeffbrown** [comment]
Sorry about that... I intended to label it `notabug`, but did not mean `closed`.  Tag removed.

**Comment by arixmkii** [comment]
@jostheron try this
```groovy
tasks.withType(GroovyCompile) {
  groovyOptions.forkOptions.memoryInitialSize = "4096m"
  groovyOptions.forkOptions.memoryMaximumSize = "4096m"
}
````

**Comment by jeffbrown** [comment]
@arixmkii I think that is only going to affect the compiler.

**Comment by jeffbrown** [comment]
@jostheron  Does this work?

```
test {
    jvmArgs('-Xmx2048m')
}

integrationTest {
    jvmArgs('-Xmx2048m')
}
```

**Comment by arixmkii** [comment]
@jeffbrown but the author tried to adjust settings for compile step, so, I provided the solution for this.

If one needs it for test task it is even simpler:

```groovy
test {
  maxHeapSize = "2048M"
}
```

**Comment by jostheron** [comment]
> @jostheron Does this work?
> 
> ```
> test {
>     jvmArgs('-Xmx2048m')
> }
> 
> integrationTest {
>     jvmArgs('-Xmx2048m')
> }
> ```

This works thanks!
