### ISSUE TITLE
When generating an application zip on start.grails.org a 301 status is returned.

### ISSUE THREAD

**Issue by LuisMuniz** [grails/grails-core#11775]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an app on start.grails.org and copy resulting curl command:
curl -O start.grails.org/myapp.zip -d version=4.0.9

### Expected Behaviour
The zip file should contain the grails application

### Actual Behaviour

Look into the contents of the downloaded zip file
$head myapp.zip

```
<html>
<head><title>301 Moved Permanently</title><script src="/cdn-cgi/apps/head/3cOPSgo5Omz84ycX7CvigfX4cpw.js"></script></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>

```

To fix this, the curl command should be 

```curl -LO start.grails.org/myapp.zip -d version=4.0.9```

### Environment Information

- **Operating System**: linux (ubuntu 20.10)

**Comment by puneetbehl** [comment]
Please either use https://start.grails.org or use CURL command with option to follow redirects, as:

```
curl -L -O start.grails.org/myapp.zip -d version=4.0.9
```
