### ISSUE TITLE
Grails3.3.9 Hot deployment doesn't work for MacBook Pro M1 Idea

### ISSUE THREAD

**Issue by zhangjiayu139** [grails/grails-core#11782]
Grails3.3.9 Hot deployment doesn't work for MacBook Pro M1 Idea，I am now using the JRebel plugin to solve the hot deployment problem, is there a solution?

### Environment Information

- **Operating System**:  MacOS Big sur
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8

**Comment by jeffbrown** [comment]
What version of IntelliJ?

**Comment by zhangjiayu139** [comment]
@jeffbrown 2021.1

**Comment by sdelamo** [comment]
Grails 3.3.9 ships with gradle 3.5. 

Gradle compatible with Apple silicon is Gradle 7

> This release enables file system watching by default to make your incremental builds faster, expands support for building projects with Java 16, and adds support for building on Macs using Apple Silicon processors (such as M1).

https://docs.gradle.org/7.0/release-notes.html


However, I seem to get hot reloading fine. 

In a MacBook Air (M1, 2020) with MacBook Air (M1, 2020). 

I created a Grails 3.3.9 app. 

```bash
% grails create-app example
% ./gradlew bootRun
...
http://localhost:8080 in environment: development
```

I edited the  `grails-app/views/index.gsp` and the app reloaded without restart. 

Have you tried delegating to [Gradle in Intellij IDEA](https://www.jetbrains.com/help/idea/gradle.html#gradle_settings_access)

**Comment by sdelamo** [comment]
I tested with a Controller and hot reload worked fine as well: 

```
Grails application running at http://localhost:8080 in environment: development
File /Users/sdelamo/github/issues/grails339/example/grails-app/controllers/example/HelloController.groovy changed, recompiling...
```

**Comment by sdelamo** [comment]
Java version: 
```
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)
```

**Comment by jeffbrown** [comment]
> Grails3.3.9 Hot deployment doesn't work for MacBook Pro M1 Idea

@zhangjiayu139 Which type(s) of artifact are not reloading successfully for you?

**Comment by puneetbehl** [comment]
Closing due to lack of feeback.
