### ISSUE TITLE
Grails 5.0.0.M2: plugin creation does not work

### ISSUE THREAD

**Issue by davidkron** [grails/grails-core#11885]
I was testing with Grails 5.0.0.M2 today and I could not create a new plugin using the CLI, because the command results in an error.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. use sdkman to install Grails: `sdk install grails 5.0.0.M2`
2. create a new Grails plugin using CLI `grails create-plugin myplugin`

### Expected Behaviour

A new plugin project is created successfully.

### Actual Behaviour

Plugin creation is not possible and results in the following error:
```
$ grails --version
| Grails Version: 5.0.0.M2
| JVM Version: 11.0.11
$ grails create-plugin myplugin
Resolving dependencies..
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:plugin:jar:5.0.0.M1 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)
```

### Environment Information

- **Operating System**: Ubuntu
- **Grails Version:** 5.0.0.M2
- **JDK Version:** 11.0.11

**Comment by puneetbehl** [comment]
It seems like Grails plugin profile 5.0.0.M1 was not published earlier. You should be able to resolve 5.0.0.M1 now.
