### ISSUE TITLE
Failed to read artifact descriptor for xalan: serializer

### ISSUE THREAD

**Issue by akshatmathur04** [grails/grails-core#11891]
I am observing the issue with grails version 2.4.0. I am getting the below error during generation of WAR file:

![image](https://user-images.githubusercontent.com/83985182/127176324-5a436174-412b-457c-8bde-1300c234e2f8.png)

The error is observed immediately after the execution of "grails clean" command.

I have followed all the suggestions mentioned in various comments and modified the BuildConfig.groovy file, but the result is same and everytime I am getting this issue in downloading the grails dependencies.
Attaching the BuildConfig.groovy.docx for reference.

I even tried adding the maven repos - mavenRepo "https://repo.grails.org/artifactory/core/" and mavenRepo "https://repo.grails.org/artifactory/plugins/" as mentioned in https://github.com/GMOD/Apollo/pull/2624/files; but no luck.

Even configured the proxy on docker but still the xalan related dependencies are not getting downloaded.

BuildsConfig.groovy file attached here: 
[BuildConfig.groovy.docx](https://github.com/grails/grails-core/files/6886506/BuildConfig.groovy.docx)

**Comment by jeffbrown** [comment]
Which JDK are you using?

**Comment by puneetbehl** [comment]
Closing due to lack of feedback.
