### ISSUE TITLE
Grails 4.0.11 unable to run new plugins, existing plugins can't be upgraded

### ISSUE THREAD

**Issue by Trebla7th** [grails/grails-core#12007]
When creating or upgrading a plugin to grails 4.0.11, the plugin cannot compile or download dependencies due to the following error:

    A problem occurred evaluating root project 'whatever'.
    > Plugin with id 'org.grails.grails-plugin-publish' not found.

This is the entirety of the error.  This works fine in grails 4.0.10

### Task List

- [/] Steps to reproduce provided
- [/] Stacktrace (if present) provided
- N/A - Example that reproduces the problem uploaded to Github

### Steps to Reproduce

1. Run "grails create-plugin whatever"
2. Attempt to compile or download dependencies in any way

### Expected Behaviour

Dependencies should update, plugin should compile

### Actual Behaviour

Error occurs and process exits:

    A problem occurred evaluating root project 'whatever'.
    > Plugin with id 'org.grails.grails-plugin-publish' not found.

### Environment Information

- **Operating System**: macOS Big Sur version 11.02
- **Grails Version:** 
  | Grails Version: 4.0.11
  | JVM Version: 1.8.0_192
- **Container Version (If Applicable):** N/A

### Example Application

N/A

**Comment by puneetbehl** [comment]
@Trebla7th The `grails-publish-plugin` was used to publish your artifacts to Bintray which is already shutdown. So, the publishing plugin would not work in 4.0.10 as well. We have removed this from 4.0.11 as this functionality is already broken. 

Please read the following blog post if you want to publish the artifacts to Maven Central.
https://grails.org/blog/2021-04-07-publish-grails-plugin-to-maven-central.html

**Comment by jeffbrown** [comment]
@puneetbehl I do think there is a bug in the project creation system.  Newly created 4.0.11 plugins have the problem.

```~ $ grails --version
| Grails Version: 4.0.11
| JVM Version: 1.8.0_202
~ $ 
~ $ grails create-plugin plugindemo
| Plugin created at /Users/jeffscottbrown/plugindemo
~ $ 
~ $ cd plugindemo 
plugindemo $ grep org.grails.grails-plugin-publish build.gradle
apply plugin:"org.grails.grails-plugin-publish"
plugindemo $ 
plugindemo $ 
plugindemo $ ./gradlew check
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
Cannot resolve reloading agent JAR: Failed to resolve imported Maven boms: Cannot resolve external dependency org.springframework.boot:spring-boot-dependencies:2.1.18.RELEASE because no repositories are defined.
Required by:
    project :

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jeffscottbrown/plugindemo/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating root project 'plugindemo'.
> Plugin with id 'org.grails.grails-plugin-publish' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

**Comment by puneetbehl** [comment]
I assumed that it was fixed in 4.0.11 where we removed `grails-publish-plugin` from the plugin profile in `4.0.1` but the BOM was updated after 4.0.11 release. 

See https://github.com/grails/grails-core/blob/4.0.x/grails-bom/profiles.properties

**Comment by danduke** [comment]
This plugin was the basis for gradle-based publishing in general, not only for publishing to Bintray.  By removing it, it's no longer possible to use gradle to publish plugins to a private repository either.  Was that intended?

**Comment by puneetbehl** [comment]
I am not sure if I fully understand but I think it was only used for Bintray or Grails Central Repo. Please note that you can still use any Gradle plugin such as `maven-publish` in your project to publish to a private artifactory.

**Comment by jeffbrown** [comment]
> This plugin was the basis for gradle-based publishing in general, not only for publishing to Bintray. By removing it, it's no longer possible to use gradle to publish plugins to a private repository either. Was that intended?

@danduke As Puneet indicated, it isn't the case that it is no longer possible to use gradle to publish plugins to a private repository.  That is definitely possible and we do it routinely.  We just don't need the custom Grails plugin to do that any longer.

**Comment by Trebla7th** [comment]
I understand the need to move forward, but this is an undocumented, breaking change that would have been more appropriate for a major version release and adds no value, simply removes functionality.  This is not a drop-in change, converting plugins that publish to local repositories are completely broken without significant (??) updating.  I mean for crying out loud, "grails install" task no longer exists with this change...  And yet "grails help" still reports it as an option.  This change just seems like it was a last minute addition with no real forethought.

I appreciate what you're doing by trying to simplify and improve grails, I do.  This is just one additional frustration on top of many others (unrelated to grails) so I'm a bit snippy.

**Comment by davydotcom** [comment]
I believe our hands were forced on the matter unfortunately due to the shutdown of bintray. We had to figure out an alternative solution and while it is a "breaking" change none of us wanted to give to users we had to move on due to this end of life announcement that was unexpected

**Comment by Trebla7th** [comment]
That's fair, I appreciate the explanation.  We all have to deal with the unexpected from time to time and there's often no "good" solution.
