### ISSUE TITLE
Hibernate5 plugin incorrectly resolves own dependencies with the version specific for generic Gorm

### ISSUE THREAD

**Issue by arixmkii** [grails/grails-core#12047]
Hibernate5 plugin was not released with RC3 and stays with RC2, but after bumping Grails to 5.0.0.RC2 and Gorm to 7.1.0.RC3 the build is failing stating that it can't find a needed dependency of version 7.1.0.RC3. 

The dependency in question `grails-datastore-gorm-hibernate5` resides in `gorm-hibernate5` repo, so, it obviously could be bumped only with hibernate5 release. Seems, that some adjustments should be made to version resolution for hibernate5 related modules.

```
* What went wrong:
A problem occurred configuring root project 'projectname'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find org.grails:grails-datastore-gorm-hibernate5:7.1.0.RC3.
     Searched in the following locations:
// content removed
     Required by:
         project : > org.grails.plugins:hibernate5:7.1.0.RC2
```

Current workaround is to add this to `build.gradle`:

```groovy
  implementation "org.grails:grails-datastore-gorm-hibernate5:$gormHibernateVersion" // FIXME override should not be needed after Grails release
```

It might be that this issue has to be moved/copied to https://github.com/grails/gorm-hibernate5 project.

**Comment by puneetbehl** [comment]
This should be fixed now. See https://repo1.maven.org/maven2/org/grails/grails-datastore-gorm-hibernate5/7.1.0.RC3/
