### ISSUE TITLE
Grails 4.0.12  Could not find org.grails:grails-gradle-plugin:4.0.12

### ISSUE THREAD

**Issue by fco271292** [grails/grails-core#12043]
### Task List

- [ ] Create app and run, show message  Could not find org.grails:grails-gradle-plugin:4.0.12

### Steps to Reproduce

1. grails create-app test
2. grails run-app

### Expected Behaviour

Show message  Could not find org.grails:grails-gradle-plugin:4.0.12, search dependency in url  https://repo.grails.org/grails/core/org/grails/grails-gradle-plugin but no found the version 4.0.12

### Actual Behaviour

No run app

### Environment Information

- **Operating System**:  Windows 10
- **Grails Version:** 4.0.12
- **JDK Version:** 1.8.0_301
- **Container Version (If Applicable):** N/A

**Comment by kiranburra92** [comment]
Getting the same issue.

**Comment by puneetbehl** [comment]
This should be resolved in few minutes once Maven Central syncs Grails Gradle Plugin 4.0.12 (https://repo1.maven.org/maven2/org/grails/grails-gradle-plugin/)
