### ISSUE TITLE
Invalid reloading agent check -  Found spring-loaded on classpath but JVM is not 1.8 - skipping

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#12103]
"Found spring-loaded on classpath but JVM is not 1.8 - skipping"

The warning message always displays when running on production.

https://github.com/grails/grails-core/blame/master/grails-bootstrap/src/main/groovy/grails/util/Environment.java#L726
The code should be like this instead so the check actually works.
```
            try {
                String jvmVersion = System.getProperty("java.specification.version");
                Class.forName("org.springsource.loaded.TypeRegistry");
                if(jvmVersion.equals("1.8")) {
                    LOG.get().debug("Found spring-loaded on the class path");
                    reloadingAgentEnabled = Environment.getCurrent().isReloadEnabled();
                } else {
                    LOG.get().warn("Found spring-loaded on classpath but JVM is not 1.8 - skipping");
                }
            }
            catch (ClassNotFoundException e1) {
                reloadingAgentEnabled = false;
            }
```

That being said, why are these checks happening in a production environment?  Should the reloading agent be disabled even if it is in the classpath?

**Comment by puneetbehl** [comment]
Is this specific to Grails 5?

**Comment by codeconsole** [comment]
I don't really use 4.x because I need a newer Spring Boot.

[Blame](https://github.com/grails/grails-core/blame/master/grails-bootstrap/src/main/groovy/grails/util/Environment.java#L726) shows it was introduced 2 years ago.

Looks like it is in [4.x as welL](https://github.com/grails/grails-core/blob/v4.0.12/grails-bootstrap/src/main/groovy/grails/util/Environment.java#L726)

I could submit a pull request. It is just a matter of moving 1 line of code
`Class.forName("org.springsource.loaded.TypeRegistry");`
but my concern is there ever a reason why someone would want isReloadingAgentEnabled() return true if the Environment is production?  If reloading agents are supported in production, I think it would be better to just return false.

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/pull/12108

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/issues/12103

**Comment by puneetbehl** [comment]
The spring-loaded only works with JDK 1.8 and it should not be in the classpath if you are using a JDK higher than 1.8. Can you explain why it is in the classpath?

**Comment by codeconsole** [comment]
@puneetbehl, the current code checks if you are using JDK 1.8 and if you are not running JDK 1.8, it displays a *WARNING* `"Found spring-loaded on classpath but JVM is not 1.8 - skipping"` *without* checking to see if it is in the classpath.

The pull requests first checks to see if it is in the classpath, and if it is not, a ClassNotFoundException is thrown, reloadingAgentEnabled is set to false and no warning message is displayd. 
```
            catch (ClassNotFoundException e1) {
                reloadingAgentEnabled = false;
            }
```

**Comment by codeconsole** [comment]
@puneetbehl do you need a separate pull request for master?

**Comment by puneetbehl** [comment]
No, we wil merge 4.0.x to master
