### ISSUE TITLE
Add support for JAVA17 and Groovy 4.X to Grails 5.0.0

### ISSUE THREAD

**Issue by johan313** [grails/grails-core#12105]
Java 17 is the current LTS version for Java and it would be appreciated if Grails could support it as soon as possible or provide workaround details on how to get the current 5.0.0.RC3 build to compile with Java17. This seems to require at least supporting Groovy 4.0 and Gradle 7.2, also.

According to the roadmap (https://github.com/grails/grails-core/wiki/Roadmap) this support is not currently planned.

**Comment by puneetbehl** [comment]
Grails 5 would not support Apache Groovy 4. It is planned for next major release.

**Comment by arixmkii** [comment]
@johan313 @puneetbehl  Grails 5.0.0-RC4 with Groovy 3.0.9 and Gradle 7.2 builds with JDK 17. No need to have Groovy 4.0. 
 
If the application actually can run with this JDK will depend on your application, though.

**Comment by johan313** [comment]
Works fine with 5.0.0 and Gradle 7.X - thank you.
