### ISSUE TITLE
Cannot install custom profile to local repository

### ISSUE THREAD

**Issue by jnunderwood** [grails/grails-core#12137]
As of Grails v4.0.11 release, publishing a custom profile to the local repository no longer works. The documentation says to issue the `gradle install` command. However, that command fails now. It appears that the `grails-profile-publish` plugin was removed and may be the source of the failure.

### Steps to Reproduce

1. `sdk use grails 4.0.11`
2. `grails create-profile temp`
3. `cd temp`
4. `gradle install`

### Expected Behaviour

The `gradle install` task should publish to the local repository. 

### Actual Behaviour

Gradle fails with an error:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'temp/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'temp'.
> Plugin with id 'org.grails.grails-profile-publish' not found.
```

### Environment Information

- **Operating System**: WSL2
- **Grails Version:** 4.0.11
- **JDK Version:** 11.0.11

**Comment by puneetbehl** [comment]
We are no longer controlling how the user publishes a profile. I think the problem is Grails Profile is outdate and still refers to `grails-profile-publish` which is already removed. I have created another issue to track the same #12138

In the previous version of Grails, we used "grails-profile-publish" plugin which was coupled with JFrog Bintray for publishing and the plugin implicitly applies "maven-publish" Gradle Plugin. After the shutdown of Bintray, the Grails team decided to remove the plugin. Here is a blog post about [Publish Grails plugin to Maven Central](https://grails.org/blog/2021-04-07-publish-grails-plugin-to-maven-central.html), I believe the same concept will apply to Grails profile.

**Comment by duxnp** [comment]
Has anyone tried using maven-publish with custom profiles? I believe the maven-publish and org.grails.grails-profile plugins are incompatible. 

The POM file generated by running ".\gradlew publishToMavenLocal" is missing the dependencies node. Is this node required when consuming the custom profile with the "grails create-app" command?

**Comment by puneetbehl** [comment]
The https://github.com/grails-profiles/web is using the Gradle "maven-publish" plugin underneath.

**Comment by duxnp** [comment]
> The https://github.com/grails-profiles/web is using the Gradle "maven-publish" plugin underneath.

You inspired me to give it another go. I was able to replicate the behavior the grails-profile-publish plugin had in Grails 3 with the following added to build.gradle. Hopefully this will help others who stumble upon this from a Google search like I did. This will at least allow you to publish to your local maven repository. I have not yet tried publishing to a remote repo.

After creating a fresh custom profile project with `grails create-profile`, add this plugin:
```
apply plugin: "maven-publish"
```

Add this publishing config (change certain values to your liking):
```
Project project = project

Map<String, String> getExtraArtifact(Project project) {
    [source: "${project.buildDir}/classes/profile/META-INF/grails-profile/profile.yml".toString(),
     classifier: 'profile',
     extension : 'yml']
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'org.mycompany'
            artifactId = 'mycompany-profile'
            version = '5.0.0'

            pom.withXml {
                def dependencies = asNode().appendNode('dependencies')
                def dependency = dependencies.appendNode('dependency')
                dependency.appendNode('groupId', 'org.grails.profiles')
                dependency.appendNode('artifactId', 'web')
                dependency.appendNode('version', baseProfileVersion)
                dependency.appendNode('scope', 'compile')
            }

            pom {
                name = 'My Profile'
                description = 'A concise description of my profile'
                url = 'http://www.example.com/profile'
            }

            artifact jar

            def sourcesJar = project.tasks.findByName("sourcesJar")
            if(sourcesJar != null) {
                artifact sourcesJar
            }

            def javadocJar = project.tasks.findByName("javadocJar")
            if(javadocJar != null) {
                artifact javadocJar
            }

            def extraArtefact = getExtraArtifact(project)
            if(extraArtefact) {
                artifact extraArtefact
            }

        }
    }
}
```

**Comment by puneetbehl** [comment]
@duxnp Thank you for your help. Will you be interested to send a pull-request to update the current version of Grails Official docs at https://github.com/grails/grails-doc/blob/5.3.x/src/en/guide/profiles/publishingProfiles.adoc?

**Comment by duxnp** [comment]
@puneetbehl You're welcome. Sure! I'll be interested in contributing. I think there is some refinement that could be done and I still need to try publishing to a remote repository. I will do that as soon as I can.
