### ISSUE TITLE
Data binding broken for id generator: 'assigned'

### ISSUE THREAD

**Issue by xpusostomos** [grails/grails-core#12160]
When you include this in your domain class:

```
    static mapping = {
        id generator: 'assigned'
    }
```

You are telling Grails that you want to be assigning your own id values. However everything in grails data binding breaks if you were hoping to give the user the ability to enter an id value via a field. If params has a value for id to a newly created object, instead of your save function getting that value:

```
    def save(MyObject myObject) {
   }

```
myObject is null. It's not even that the id is null, the whole object is null.

If one was hoping to manually do data binding:

`        bindData(myObject, params)`

it won't fill in the id value from params either.

As a general rule, I don't see why params coming in that includes an id shouldn't populate as normal, regardless of one's generator='assigned' status... If an object with that id value doesn't exist yet, then the presence of an id surely is indicating you want to create one... but certainly it  should populate when generator=assigned, because the whole point of that is indicating that you expect to populate your own ids.

In my view, stop making so many binding exceptions for 'id' to the normal rules, regardless of generator=assigned.

Grails 4.0.11

**Comment by jeffbrown** [comment]
`id` is `bindable: false` by default.  Have you configured yours with`bindable: true`?

**Comment by jeffbrown** [comment]
> As a general rule, I don't see why params coming in that includes an id shouldn't populate as normal...

There are properties, `id` included`, which are excluded from mass property data binding by default for security reasons.  If `id` participated by default, most mass property data binding code in the application would need to be more tedious.

**Comment by jeffbrown** [comment]
I believe this is basically the same question as https://github.com/grails/grails-core/issues/5762.
