### ISSUE TITLE
Grails 5.0.2: ApplicationContextCommandRegistry.findCommands() list only 1 command at a time

### ISSUE THREAD

**Issue by Taack** [grails/grails-core#12238]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new app: `grails create-app tc-commands`
2. `cd` to the app folder
3.  Create 2 commands: `grails create-command Test1` && `grails create-command Test2`
4. Then try to execute both commands: `./gradlew runCommand -Pargs="test1"`and `./gradlew runCommand -Pargs="test2"`

### Expected Behaviour

The 2 commands should be executed (at least, launched, even if both ends with an error message).

### Actual Behaviour

Only one command is launched, the other will fail with the message:
```bash
% ./gradlew runCommand -Pargs='test1'

> Task :runCommand FAILED
Command not found for name: test1
```

But the other will be found:
```bash
./gradlew runCommand -Pargs='test2 tc.commands.Application'

> Task :runCommand
Grails application running at http://localhost:0 in environment: development

...
```

It is not easy to know which one will execute correctly.

### Environment Information

- **Operating System**: macOS Monterey 12.0.1
- **Grails Version:** Grails 5.0.2
- **JDK Version:** openjdk full version "15.0.5+3-MTS"

### Example Application

The example application further list detected commands calling `ApplicationContextCommandRegistry.findCommands()`. The result is that only 1 command is listed, the other one is ignored.

[tc-commands.tar.gz](https://github.com/grails/grails-core/files/7673382/tc-commands.tar.gz)

Thanks for your support,
Adrien

**Comment by Taack** [comment]
I cleaned up the test case, and relaunch it on Linux machine with java-11, I do obtain the same error.

[tc-commands_1.tar.gz](https://github.com/grails/grails-core/files/7674396/tc-commands_1.tar.gz)

Thanks

**Comment by jeffscottbrown** [comment]
FYI... I have put the contents of the latest linked `tc-commands_1.tar.gz` at [github.com/jeffbrown/tc-commands](https://github.com/jeffbrown/tc-commands).
