### ISSUE TITLE
Grails 5.1.1 - comand create-app (rest-api) doesn't work

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-core#12274]
### Steps to Reproduce

```
$ grails create-app myApp -profile rest-api

| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:rest-api:jar:5.0.1 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

```

### Expected Behaviour

Create a rest-api application

### Actual Behaviour

An exception is thrown

### Environment Information

- **Operating System**: Manjaro Linux 21.2rc2
- **Grails Version:** 5.1.1
- **JDK Version:** openjdk version "11.0.11" 2021-04-20

**Comment by puneetbehl** [comment]
Duplicate of #12279
