### ISSUE TITLE
Grails 5.1.1 war deploys on Tomcat causes error

### ISSUE THREAD

**Issue by ghostfox911** [grails/grails-core#12288]
### Environment Information
- Windows10 & CentOS
- Grails 5.1.1
- jdk-8u281
- Tocmat 9.0.56

### Steps to Reproduce
- Creates a new project with rest-api profile
- Generates war file
- Puts war file (plain.war or war) to tomcat.
- Starts tomcat

### Error Info
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'characterEncodingFilter' could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/HttpEncodingAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

### Extra Info
- Even you may follow the advice to set spring.main.allow-bean-definition-overriding=true. It even causes more errors.
- Uses java -jar command to run then everything is fine.

**Comment by qvarnis** [comment]
My war cant start either and i've spent christmas trying to investigate this, others also seem to have this problem.
In my case i've had problems with beans "classLoader" and "multipartResolver".
My best guess is that something is amiss in 'implementation "org.grails:grails-web-boot"', but i never figured it out.

I did resolve it so i could start the war by using spring.main.allow-bean-definition-overriding=true and configured beans in Application.groovy. But nothing worked when surfing to my web, problems with tag-librarys so i got nullpointer exceptions when trying to resolve <g:message>-stuff.

I dont think 5.1.1 is ready for production-mode right now.

**Comment by ghostfox911** [comment]
> My war cant start either and i've spent christmas trying to investigate this, others also seem to have this problem. In my case i've had problems with beans "classLoader" and "multipartResolver". My best guess is that something is amiss in 'implementation "org.grails:grails-web-boot"', but i never figured it out.
> 
> I did resolve it so i could start the war by using spring.main.allow-bean-definition-overriding=true and configured beans in Application.groovy. But nothing worked when surfing to my web, problems with tag-librarys so i got nullpointer exceptions when trying to resolve <g:message>-stuff.
> 
> I dont think 5.1.1 is ready for production-mode right now.


Thanks for your time and happy new year.

**Comment by armmen** [comment]
Same issues here

**Comment by lbwexler** [comment]
Running into the same problem, including same behavior with attempts to workaround.  Thanks!

**Comment by jmfdz** [comment]
Same problem here.

**Comment by sagrawal31** [comment]
We are also facing the same challenge.

**Comment by sagrawal31** [comment]
Where to set `spring.main.allow-bean-definition-overriding=true`? Any workaround?

**Comment by qvarnis** [comment]
> Where to set `spring.main.allow-bean-definition-overriding=true`? Any workaround?

application.yml

spring:
   main:
     allow-bean-definition-overriding: true

But it's risky, our web-app did'nt work after i did the above...

**Comment by qvarnis** [comment]
All the problems seem to relate to plugins and resource.groovy!

**Comment by sagrawal31** [comment]
Thanks, @qvarnis. I'll try this. This Grails app is not exposed to the web so I think security-wise, I don't have challenges.

**Comment by sagrawal31** [comment]
Setting

```yml
spring:
    main:
        allow-bean-definition-overriding: true
```

resulted in different issue-

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field viewResolvers in org.grails.web.servlet.view.CompositeViewResolver required a bean named 'classLoader' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=false)


Action:

Consider defining a bean named 'classLoader' in your configuration.
```

**Comment by ghostfox911** [comment]
This issue also affects deployment in docker container.

**Comment by sagrawal31** [comment]
Thanks, @puneetbehl for quick support. Do we have any workaround solution to fix this while this fix is released?

**Comment by puneetbehl** [comment]
I believe the workaround should be to set the following configuration:

```
spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
```

But, I am not sure why it does not work in your case, please check the [example Grails REST API application](https://github.com/puneetbehl/rest-api-demo). 

In any case, I am going to release 5.1.2 today or tomorrow with this change.

**Comment by qvarnis** [comment]
> I believe the workaround should be to set the following configuration:
> 
> ```
> spring:
>     main:
>         allow-bean-definition-overriding: true
>         allow-circular-references: true
> ```
> 
> But, I am not sure why it does not work in your case, please check the [example Grails REST API application](https://github.com/puneetbehl/rest-api-demo).
> 
> In any case, I am going to release 5.1.2 today or tomorrow with this change.

A very big THANK YOU for this  @puneetbehl!!!
Awesome support and well done.

**Comment by sagrawal31** [comment]
Thanks a ton, @puneetbehl 🙏🏻

**Comment by Trinition** [comment]
Did Grails 5.1.2 get released ([see earlier comment](https://github.com/grails/grails-core/issues/12288#issuecomment-1005066193))?  I don't see it in the releases.

**Comment by manojsbp** [comment]
I followed Punit's rest-api demo app config. The only change in my code is profiles:web instead of rest-api. Apllication runs perfectly in Intellij and with bootRun cmd. No issues. But fails to deploy on production Tomcat 9.0.8 with this error.
I think it got introduced to bean-override or cicrular-refrerence.

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jspViewResolver': Cannot create inner bean '(inner bean)#74ccfce3' of type [grails.plugin.scaffolding.ScaffoldingViewResolver] while setting bean property 'innerViewResolver'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#74ccfce3': Cannot resolve reference to bean 'groovyPagesTemplateEngine' while setting bean property 'templateEngine'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'groovyPagesTemplateEngine': Cannot resolve reference to bean 'classLoader' while setting bean property 'classLoader'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'classLoader' available

Eagerly awaiting for 5.1.2.

**Comment by manojsbp** [comment]
Never mind. It worked with 5.1.2-SNAPSHOT. I was able to deploy to tomcat in production.
Thank you very much Punit.
