### ISSUE TITLE
Grails latest docs refer to gradle v 5.0

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#12295]
### Issue description

The grails upgrade guide indicates that version 5.0 of the gradle wrapper should be used:
https://docs.grails.org/latest/guide/upgrading.html

```
To upgrade to Gradle 5 execute:

./gradlew wrapper --gradle-version 5.0
```

This version of gradle is from 2018. The grails guide should indicate the latest version that is supported. It would be ideal to have a table somewhere of grails versions and the corresponding supported gradle version.

Currently our grails 5 app is upgrading to gradle 6.9.2

**Comment by puneetbehl** [comment]
I think that part is for updating from Grails 3 to Grails 4. I have correct the heading to be more clear now. See https://github.com/grails/grails-doc/pull/821
