### ISSUE TITLE
URL mapping for URLs starting with a dot

### ISSUE THREAD

**Issue by jadelomeiri** [grails/grails-core#12354]
### Expected Behavior

In UrlMappings, when I add the following mapping:
`"/.xxx"(view:"/xxx")`
I expect the view to be reachable at localhost:8080/.xxx

### Actual Behaviour

Instead, this view is only currently reachable at:
localhost:8080//.xxx

### Steps To Reproduce

1- In UrlMappings, add:
`"/.xxx"(view:"/xxx")`

2- run app

3- try accessing localhost:8080//.xxx and localhost:8080/.xxx

### Environment Information

Window 10
JDK 16
Groovy 3.0.9
Grails 5.1.2

### Version

5.1.2

**Comment by jadelomeiri** [comment]
Note:
Why would I need to have a URL that starts with a dot?

Cause Apple Pay requires to host a verification file under:
/.well-known/apple-developer-merchantid-domain-association
Apple Pay can't be enabled without that

**Comment by fernando88to** [comment]
I made an example project and it worked with the following url:

http://localhost:8080/.xxx

http://localhost:8080/.well-known/apple-developer-merchantid-domain-association


project : https://github.com/fernando88to/Issue12354

**Comment by jadelomeiri** [comment]
Thank you so much @fernando88to !
I'll give it a try and see how you might have done it differently

**Comment by jadelomeiri** [comment]
Well it works 😶 Thanks again!
