### ISSUE TITLE
Outdated documentation around plugins and multi-project builds

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#12367]
### Issue description

WIth gradle 7.x `compile` configuration was removed

https://github.com/grails/grails-core/blob/c87619489ea67ec71900d1b0b7ac4f1870fb6d87/grails-docs/src/test/resources/docs/guide/pages/creatingAndInstallingPlugins.html#L361

it should be replaced with `implementation` however it might not be a drop in replacement.

If grails app used the dependencies of the plugins directly this will stop working. The transitive dependencies won't resolve.
A step to make it happen is to declare the dependencies in the plugins as `api` configuration (and apply the gradle java-library plugin: https://docs.gradle.org/current/userguide/java_library_plugin.html)

**Comment by puneetbehl** [comment]
Thank you for pointing it out. Would you be interested to send the PR at https://github.com/grails/grails-doc/blob/5.1.x/src/en/guide/plugins/creatingAndInstallingPlugins.adoc

**Comment by jglapa** [comment]
did my best: https://github.com/grails/grails-doc/pull/824
