### ISSUE TITLE
Disabling of reloading does not work

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#12364]
### Expected Behavior

Disabling of the dynamic reloading should be possible.

### Actual Behaviour

removing commenting out of the `org.springframework.boot:spring-boot-devtools` does not do anything
Application continues to issue these messages:
```
File /....gr512-disable-reloading/grails-app/controllers/gr512/disable/reloading/UrlMappings.groovy changed, recompiling...
```

### Steps To Reproduce

sdk install grails 5.1.2
grails create-app grails-reload-disable/
-- remove the `developmentOnly("org.springframework.boot:spring-boot-devtools")` dependency from `build.gradle`
./gradlew bootRun
-- edit file e.g. `UrlMappings.groovy` - change something
-- after a while console will display:
```
File /.../grails-reload-disable/grails-app/controllers/grails-reload-disable/disable/reloading/UrlMappings.groovy changed, recompiling...
```

### Environment Information

MacOS
Java8

### Version

5.1.2 (same on v4)

**Comment by jeffscottbrown** [comment]
> Disabling of the dynamic reloading should be possible.

I think it is possible.

> removing commenting out of the org.springframework.boot:spring-boot-devtools does not do anything

Are you sure that reloading still works after you remove that?  I would expect the class to be recompiled but not reloaded.  If it is being reloaded, is it possible you have a reloading agent configured elsewhere in your project?

Thank you for the feedback!

**Comment by jglapa** [comment]
Sorry I think I mixed up the things: `recompiling` vs `reloading`. 

What is being recompiled when reloading is disabled?

My issue might be be about recompiling then overall.

**Comment by jglapa** [comment]
I'll close the issue and seek answers on SO
