### ISSUE TITLE
Grails 5.1.2 app can't run on Tomcat 9 (JDK 14.0.2)

### ISSUE THREAD

**Issue by ecruiser** [grails/grails-core#12401]
### Expected Behavior

Run on Tomcat 9

### Actual Behaviour

Once it's deployed, Tomcat throws out an error. Please see below. 

_Please note that I have removed the embedded tomcat from build.gradle, which has been a known issue for deployment on standalone Tomcat, so it is not related to that. 
//testImplementation "org.springframework.boot:spring-boot-starter-tomcat"_

It complains about the annotation resource class. I don't know how this **jsr250-api-1.0.jar** was added to the application's lib folder. I searched and it said this is old and has a conflict with others. After I manually deleted it from the war file and deployed it to Tomcat, it worked!

How can I solve this issue? If not, how can I exclude this jar when building the war? 

------Log------------------------
04-Mar-2022 14:55:46.899 INFO [Catalina-utility-2] org.apache.catalina.core.ApplicationContext.log Initializing Spring embedded WebApplicationContext
'2022-03-04 14:55:53.524 ERROR --- [alina-utility-2] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.<init>(CommonAnnotationBeanPostProcessor.java:664)

The following method did not exist:

    'java.lang.String javax.annotation.Resource.lookup()'

The calling method's class, org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement, was loaded from the following location:

    jar:file:/opt/tomcat/websc/ROOT/WEB-INF/lib/spring-context-5.3.15.jar!/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor$ResourceElement.class

The called method's class, javax.annotation.Resource, is available from the following locations:

    jar:file:/opt/tomcat/websc/ROOT/WEB-INF/lib/jsr250-api-1.0.jar!/javax/annotation/Resource.class
    jar:file:/opt/tomcat/websc/ROOT/WEB-INF/lib/javax.annotation-api-1.3.2.jar!/javax/annotation/Resource.class
    jar:file:/opt/tomcat/lib/annotations-api.jar!/javax/annotation/Resource.class

The called method's class hierarchy was loaded from the following locations:

    javax.annotation.Resource: file:/opt/tomcat/websc/ROOT/WEB-INF/lib/jsr250-api-1.0.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement and javax.annotation.Resource

'04-Mar-2022 14:55:53.526 SEVERE [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/opt/tomcat/websc/ROOT.war]
 java.lang.IllegalStateException: Error starting child

### Environment Information

Ubuntu 20.04
JDK 14.0.2
Tomcat 9.0.16
Grails 5.1.2

build.gradle
------------------------------------------------------
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsGradlePluginVersion"
        classpath "org.grails.plugins:views-gradle:2.2.0"
        classpath "org.grails.plugins:hibernate5:7.2.1"
        classpath "gradle.plugin.com.github.erdi.webdriver-binaries:webdriver-binaries-gradle-plugin:2.6"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.3.4"
    }
}
....
....

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    compileOnly "io.micronaut:micronaut-inject-groovy"
    console "org.grails:grails-console"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.grails:grails-web-boot"
    implementation "org.grails:grails-logging"
    implementation "org.grails:grails-plugin-rest"
    implementation "org.grails:grails-plugin-databinding"
    implementation "org.grails:grails-plugin-i18n"
    implementation "org.grails:grails-plugin-services"
    implementation "org.grails:grails-plugin-url-mappings"
    implementation "org.grails:grails-plugin-interceptors"
    implementation "org.grails.plugins:cache"
    implementation "org.grails.plugins:async"
    implementation "org.grails.plugins:scaffolding"
    implementation "org.grails.plugins:views-json"
    implementation "org.grails.plugins:views-json-templates"
    implementation "org.grails.plugins:hibernate5"
    implementation "org.hibernate:hibernate-core:5.6.3.Final"
    implementation "org.grails.plugins:events"
    implementation "org.grails.plugins:gsp"
    profile "org.grails.profiles:web"
    runtimeOnly "org.glassfish.web:el-impl:2.2.1-b05"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    runtimeOnly "javax.xml.bind:jaxb-api:2.3.1"
    runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:3.3.4"
    //testImplementation "org.springframework.boot:spring-boot-starter-tomcat"
    testImplementation "io.micronaut:micronaut-inject-groovy"
    testImplementation "org.grails:grails-gorm-testing-support"
    testImplementation "org.mockito:mockito-core"
    testImplementation "org.grails:grails-web-testing-support"
    testImplementation "org.grails.plugins:geb"
    testImplementation "org.seleniumhq.selenium:selenium-remote-driver:4.0.0"
    testImplementation "org.seleniumhq.selenium:selenium-api:4.0.0"
    testImplementation "org.seleniumhq.selenium:selenium-support:4.0.0"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-chrome-driver:4.0.0"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-firefox-driver:4.0.0"

    implementation 'org.grails.plugins:spring-security-core:4.0.4'
    implementation "mysql:mysql-connector-java:8.0.25"
    implementation group: 'org.freemarker', name: 'freemarker', version: '2.3.31'
    implementation group: 'com.sun.mail', name: 'javax.mail', version: '1.6.2'
    implementation group: 'org.liquibase', name: 'liquibase-maven-plugin', version: '4.7.1'
    implementation "io.micronaut:micronaut-http-client"
    implementation group: 'com.stripe', name: 'stripe-java', version: '20.98.0'

### Version

5.1.2

**Comment by rainboyan** [comment]
@ecruiser you can use Gradle `dependencies` command to check which lib import `jsr250-api-1.0.jar` 

```
./gradlew dependencies --configuration runtimeClasspath | grep jsr250 -C 30
```

**Comment by fernando88to** [comment]
I created a repository with grails + docker. It is working the deployment of grails 5.1.2 on tomcat 9 with jdk 14.

https://github.com/fernando88to/Issue12401

**Comment by ecruiser** [comment]
Thank you, @fernando88to and @rainboyan ! 

I figured out. It was not the Grails issue, but the issue with 'liquibase-maven-plugin', version: '4.7.1'. It contains jsr250-api-1.0.jar, which causes the problem. After I removed it, the project was able to use javax.annotation-api-1.3.2.jar instead. It works fine now.
