### ISSUE TITLE
grails install doesn't work

### ISSUE THREAD

**Issue by xpusostomos** [grails/grails-core#12407]
### Expected Behavior

According to https://docs.grails.org/5.1.2/guide/single.html#creatingAndInstallingPlugins

```
To make your plugin available for use in a Grails application run the install command:

grails install
This will install the plugin into your local Maven cache. Then to use the plugin within an application declare a dependency on the plugin in your build.gradle file and include mavenLocal() in your repositories hash:
```

### Actual Behaviour

```
| Resolving Dependencies. Please wait...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 3s
<-------------> 0% CONFIGURING [348ms]
> root project > Resolve dependencies of :runtimeClasspath

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in root project 'myPlug512'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
<-------------> 0% WAITING
> IDLE
| Error Gradle build terminated with error: Task 'install' not found in root project 'myPlug512'. (Use --stacktrace to see the full trace)

```

### Steps To Reproduce

grails create-plugin myPlug512
cd myPlug512
grails install

### Environment Information

 grails -version
| Grails Version: 5.1.2
| JVM Version: 1.8.0_312

Windows 11

### Version

5.1.2

**Comment by puneetbehl** [comment]
Thank you for reporting the issue. As a workaround, you could use Gradle [Maven Publish Plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) and instead use `./gradlew publishToMavenLocal` command.

**Comment by xpusostomos** [comment]
@puneetbehl I have tried that already, and I can't get it to work. When I include that plugin and use the command above, nothing happens. It doesn't report an error, but neither does it do anything.

**Comment by puneetbehl** [comment]
Please note that you will also need to add basic publishing configurations to the plugin as:
```

publishing {
    publications {
        maven(MavenPublication) {
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            from components.java
        }
    }
}
```

Here is an example application https://github.com/puneetbehl/grails-plugin-local

**Comment by rainboyan** [comment]
@xpusostomos you can use `org.grails.internal.grails-plugin-publish` to publish it to local maven repository.

I create a plugin demo project here [grails-new-plugin-demo](https://github.com/rainboyan/grails-new-plugin-demo)

**Comment by xpusostomos** [comment]
sigh... I don't know, @puneetbehl  and @rainboyan have rather different advice. @puneetbehl 's suggestion seems to work on my machine... but for whatever reason seems to fail in Jenkins. Something gets installed into ~/.m2 but it doesn't work. @rainboyan ... it's not clear to me what goes in githubSlug or other parameters.  I don't know why it needs to be this hard.

**Comment by rainboyan** [comment]
https://github.com/grails/grails-gradle-plugin/blob/5.1.x/src/main/groovy/org/grails/gradle/plugin/publishing/internal/GrailsCentralPublishGradlePlugin.groovy#L49

```
grailsPublish {
    user = 'user'
    key = 'key'
    userOrg = 'my-company' // optional, otherwise published to personal bintray account
    repo = 'plugins' // optional, defaults to 'plugins'


    websiteUrl = 'http://foo.com/myplugin'
    license {
        name = 'Apache-2.0'
    }
    issueTrackerUrl = 'http://github.com/myname/myplugin/issues'
    vcsUrl = 'http://github.com/myname/myplugin'
    title = "My plugin title"
    desc = "My plugin description"
    developers = [johndoe:"John Doe"]
}
```

or

```
grailsPublish {
    user = 'user'
    key = 'key'
    githubSlug = 'foo/bar'
    license {
        name = 'Apache-2.0'
    }
    title = "My plugin title"
    desc = "My plugin description"
    developers = [johndoe:"John Doe"]
}
```

Your publishing user and key can also be placed in PROJECT_HOME/gradle.properties or USER_HOME/gradle.properties. For example:

bintrayUser=user
bintrayKey=key

Or using environment variables:

BINTRAY_USER=user
BINTRAY_KEY=key

**Comment by xpusostomos** [comment]
It turns out I had to set artifactId in publishing.publicaions.maven... otherwise Jenkins sets the artifactId as "workspace" ... I guess because that's the directory it checks it out to.

As for grailsPublish {} ... I thought that was related to org.grails.grails-plugin-publish .... which I thought was obsolete and couldn't be used anymore.

**Comment by rainboyan** [comment]
@xpusostomos yes, grails internal publishing plugin was outdated, but still a lot of plugins use it.
I see the Grails docs has bean already updated, we should use Gradle `maven-publish` plugin now.

**Comment by xpusostomos** [comment]
@rainboyan where does it say to use maven-publish? I can't see it.

**Comment by rainboyan** [comment]
@xpusostomos Grails Docs 5.1.3 **Installing Local Plugins**
[https://docs.grails.org/latest/guide/plugins.html#creatingAndInstallingPlugins](https://docs.grails.org/latest/guide/plugins.html#creatingAndInstallingPlugins)

**Comment by jeffscottbrown** [comment]
Thank you @rainboyan!

The **Installing Local Plugins** section at https://docs.grails.org/5.1.4/guide/plugins.html#creatingAndInstallingPlugins does describe how to configure `maven-publish` to install to your `mavenLocal()` using `publishToMavenLocal`.  That is a common technique that Grails devs use.

**Comment by jeffscottbrown** [comment]
```
~ $ grails -version
| Grails Version: 5.1.4
| JVM Version: 11.0.14
~ $ 
~ $ 
~ $ grails create-plugin --features maven-publish somemavendemo
| Plugin created at /Users/jeffscottbrown/somemavendemo
~ $ 
~ $ cd somemavendemo 
somemavendemo $ 
somemavendemo $ ./gradlew pTML


BUILD SUCCESSFUL in 10s
8 actionable tasks: 8 executed
somemavendemo $ 
somemavendemo $ 
somemavendemo $ find /Users/jeffscottbrown/.m2/repository/somemavendemo/somemavendemo -type f
/Users/jeffscottbrown/.m2/repository/somemavendemo/somemavendemo/maven-metadata-local.xml
/Users/jeffscottbrown/.m2/repository/somemavendemo/somemavendemo/0.1/somemavendemo-0.1-plain.jar
/Users/jeffscottbrown/.m2/repository/somemavendemo/somemavendemo/0.1/somemavendemo-0.1.module
/Users/jeffscottbrown/.m2/repository/somemavendemo/somemavendemo/0.1/somemavendemo-0.1.pom
```

**Comment by jeffscottbrown** [comment]
@puneetbehl Do you think the `install` command should be repaired, or the docs should be updated?

**Comment by jeffscottbrown** [comment]
>  it's not clear to me what goes in githubSlug or other parameters. I don't know why it needs to be this hard.

If all you want to do is publish to maven local, you don't have to do anything with `githubSlug`.

**Comment by puneetbehl** [comment]
I think we should drop the support for `install` command as it might be redundant to what `publishToMavenLocal` would do.

**Comment by puneetbehl** [comment]
@rainboyan I think you should not use the `org.grails.internal.grails-plugin-publish` as it only for Grails Core projects internal use and it might change as the need of those projects which might differ from the needs of community projects or plugins. I would recommend configuring your build manually.

**Comment by rainboyan** [comment]
@puneetbehl I see. Grails profile `plugin` contains [`install` command](https://github.com/grails-profiles/plugin/blob/master/commands/install.yml) which call Gradle task `install`(doesn't actually exist) ,  while `org.grails.internal.grails-plugin-publish` offer `install` task that depends on `publishToMavenLocal`, I think we should keep `install` command, because it's useful and simple. 
We could update the Gradle `build.gradle` in skeleton of `plugin` and `web-plugin` profiles,  use `maven-publish` Gradle plugin inplace of `org.grails.internal.grails-plugin-publish`.
At the same time I see that Grails `plugin` offer `maven-publish` [feature](https://github.com/grails-profiles/plugin/tree/master/features/maven-publish), but [Grails docs](https://docs.grails.org/latest/guide/plugins.html) not mentioned it, I think `maven-publish` should be default profile feature, and move to `base` profile.

**Comment by jeffscottbrown** [comment]
> I think we should keep install command, because it's useful and simple.

Does the `install` command offer something that `publishToMavenLocal` does not?

**Comment by puneetbehl** [comment]
I don't think `install` command offers anything special as compared to `publishToMavenLocal`. With Grails 6, we encourage you to leverage Gradle build system and removed redundand commands such as `run-app`, `install`, etc from the CLI.
