### ISSUE TITLE
service not injected

### ISSUE THREAD

**Issue by FileNotFoundExcetion** [grails/grails-core#12465]
### Expected Behavior

def service is not null 
it should be like 
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/29888589/161417282-a481dd0f-0c44-4b5c-b580-a9caf2e37e37.png">

### Actual Behaviour

service is null
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/29888589/161417223-0413cbf0-1808-45dc-8369-e3129740f60f.png">
is it supported?

### Environment Information

JDK 1.8

### Version

4.0.12

**Comment by jeffscottbrown** [comment]
Does the problem only happen when you us a bean name that begins with a single lower case letter followed by an upper case letter (ex: `aService`, `bService`)?

**Comment by FileNotFoundExcetion** [comment]
at present，i just found this.but if injected by this.  def AService AService,it means success. and can you tell me how the grails automatic assembly..  or the rules?

**Comment by jeffscottbrown** [comment]
I think if you evaluate `grailsApplication.getArtefact('Service', 'grails.micrometer.demo.AService').propertyName` you may see that the expected property name is `AService`, not `aService`.

**Comment by jeffscottbrown** [comment]
@puneetbehl Do you think this is currently behaving as designed?

**Comment by puneetbehl** [comment]
Yes, this is working as designed.
