### ISSUE TITLE
Grails 4 - Domain class in plugin overrides same class in application

### ISSUE THREAD

**Issue by jphiloon** [grails/grails-core#12469]
A plugin defines a skeletal User class for stand-alone testing with a subset of properties of the "real" application User class.

Plugin (edited for brevity):
```
package com.company.project.domainobject

class User implements Serializable {

	private static final long serialVersionUID = 1

	String username
        String email
}

```
build.gradle:
```
    jar {
        exclude "**/com/company/project/domainobject/**"
    }

```
IssueGrailsPluginGrailsPlugin.groovy:

```
class IssueGrailsPluginGrailsPlugin extends Plugin {
    def pluginExcludes = [
        "**/com/penbaymedia/jdeis5/domainobject/**"
    ]
}

```
Main Application (edited for brevity):
```
package com.company.project.domainobject

class User implements Serializable {

	private static final long serialVersionUID = 1

	String username
        String email
        ... more properties, etc
}

```
Problem code in plugin:
```
def user = User.where {
      username == username || email == username
 }.get()

```
Expected behavior:  User object defined in main application will be fetched.

Actual behavior:  Exception is thrown

"Cannot cast object 'com.company.project.domainobject.User : 5265' with class 'com.company.project.domainobject.User' to class 'com.company.project.domainobject.User'"

Running with Grails 4.0.10.   There is no User class defined in the jar file published with the plugin, and no "duplicate class" warning is displayed at runtime.  The above code worked fine with Grail 3.2.13 (and previous Grails 3 versions) prior to upgrading.   Is something missing from my upgrade conversion to prevent this conflict?

**Comment by jphiloon** [comment]
Important note!  This equivalent code in the plugin works fine and does not throw an exception:
````
def` user = User.findByUsernameOrEmail(username, username)

````

**Comment by rainboyan** [comment]
@jphiloon Hi. Could you provide a complete minimal sample that reproduces the issue?

**Comment by jphiloon** [comment]
First attempt at creating a simple app/plugin to illustrate the problem resulted in - no such problem.  It will take further research to find what extenuating circumstance creates the problem situation.

**Comment by puneetbehl** [comment]
@jphiloon I am closing the issue for now. Please feel free to raise a request to reopen the issue once you are able to create a sample application replicating the problem.

**Comment by jphiloon** [comment]
I can, but I won’t have time to do that until next week.  The example would have two projects – one for the plugin, one for the main app.
