### ISSUE TITLE
Newly generated project should run tests with Apple M1 processors without exception

### ISSUE THREAD

**Issue by kurb70** [grails/grails-core#12497]
### Expected Behavior

The project created by the "grails create-app" command should not cause the error "Execution failed for task ':configureChromeDriverBinary'." when running tests (gradle check) under Apple M1. .

### Actual Behaviour

When trying to run tests with `gradle check` the following message appears
```
Execution failed for task ':configureChromeDriverBinary'.
> com.github.erdi.gradle.webdriver.repository.UnsupportedArchitectureException: UNKNOWN
```

### Steps To Reproduce

1. Create Grails App wit Web profile
2. Start App (no problem)
3. Start `./gradlew check` -> FAILURE: Build failed with an exception. -> com.github.erdi.gradle.webdriver.repository.UnsupportedArchitectureException

### Environment Information

- macOS 12.3.1 (21E258)
- Apple M1 Pro
- Azul Zulu version 11.0.13

### Version

5.1.7

**Comment by rainboyan** [comment]
@kurb70 you should use WebDriver binaries Gradle plugin v2.7, this version support macOS ARM64 architecture. But the [default drivers repository-3.0.json file](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/blob/master/repository-3.0.json) is no longer maintained, you can add the drivers which support Apple M1 by yourself.

Please reference here: https://github.com/rainboyan/grails-geb-test-driver-demo

```
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsGradlePluginVersion"
        // (1)
        classpath "gradle.plugin.com.github.erdi.webdriver-binaries:webdriver-binaries-gradle-plugin:2.7"
    }
}

...

webdriverBinaries {
    driverUrlsConfiguration = resources.text.fromFile('repository-3.0.json') // (2)
    if (!System.getenv().containsKey('GITHUB_ACTIONS')) {
        chromedriver {
            version = '101.0.4951.41'
            //architecture = 'ARM64'
            fallbackTo32Bit = true
        }
        geckodriver {
            version = '0.31.0'
        }
    }
}
```

Put the `repository-3.0.json` in your app root,

```
{
    "drivers": [
        {
            "name": "chromedriver",
            "platform": "mac",
            "bit": "arm64",
            "version": "101.0.4951.41",
            "url": "https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_mac64_m1.zip"
        },
        {
            "name": "geckodriver",
            "platform": "mac",
            "bit": "arm64",
            "version": "0.31.0",
            "url": "https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-macos-aarch64.tar.gz"
        },
   ]

}
```

**Comment by kurb70** [comment]
Because it has not been tracked for so long, the issue can be considered obsolete.
