### ISSUE TITLE
Deployed simple Grails 5.1.7 aplication on tomcat gets HTTP 404 error

### ISSUE THREAD

**Issue by vrivon** [grails/grails-core#12547]
### Issue description

Hi all:

After trying to update gradle and my grails application from version 4 to 5.1.7 I got to succesfully run it with run-app but I am unable to run it on Apache 9 server. 

catalina.out shows no errors but it takes 27sec instead of 100sec to desploy. When you try to access to any page, you get 404 error.
I have tried to delete the line: 

`implementation`  "org.springframework.boot:spring-boot-starter-tomcat"

But it doesnt seem to change anything.

I use the same java jdk 11.0.11.

My old .war still works, but I am unable to update my application because I cannt find any solution.

Thanks in advance

REPO: https://github.com/vrivon/grails5

**Comment by jeffscottbrown** [comment]
> catalina.out shows no errors but it takes 27sec instead of 100sec to desploy.

What is 100 seconds referring to?

**Comment by vrivon** [comment]
Hi jeff. Sorry for the delay.

I noticed that my project old built with grails version 4 takes 100sec to be to be deployed on the server. Same project updated to grails 5 takes just 27sec to be deployed on the server... and it returns the 404 error. I mentioned it because it shows that something is not being loaded and fails even if it doesnt show any error message.


As I said, I cannt even run a new fresh clean empty project

**Comment by vrivon** [comment]
I've been doing some test with different Tomcat servers and grails compilations.
Compilation A: compiled with grails 4.0.5 on May 2021 (in production server)
Compilation B: compiled with grails 5.1.7


1. Tomcat 8.5.35 (windows): 
**Compilation A** fails on deployment :(
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ClassInfo
**Compilation B** works :)

2. Tomcat 9.0.44 (my production server on Ubuntu)
**Compilation A** works. :) (100sec deployment)
**Compilation B** fails :( -> No deployment errors. 404 error on requests. (27sec deployment)

3. Tomcat 10.0.10 (windows)
**Compilation A** fails :( No deployment errors. 404 error on requests
**Compilation B** fails :( No deployment errors. 404 error on requests

**Comment by vrivon** [comment]
**As I said before, Tomcat returns no errors and seems to deploy correctly:**

```
08-Jun-2022 23:56:05.886 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Server/Service/Engine/Host/Context] failed to set property [className] to [org.apache.catalina.core.StandardContext]
08-Jun-2022 23:56:05.888 WARNING [main] org.apache.catalina.core.StandardContext.setPath Una ruta de contexto debe de ser o una cadena vacía o comenzar con "/". La ruta [/] no cumple con estos criterios y ha sido cambiada por []
08-Jun-2022 23:56:05.900 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Nombre de la versión del servidor: Apache Tomcat/10.0.10
08-Jun-2022 23:56:05.900 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:                      Jul 30 2021 09:51:27 UTC
08-Jun-2022 23:56:05.900 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Número de versión de servidor:     10.0.10.0
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:                           Windows 10
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Versión de Systema Operativo:      10.0
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Arquitectura:                      amd64
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:                         C:\Program Files\Java\jdk-16.0.2
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:                       16.0.2+7-67
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Vededor JVM:                       Oracle Corporation
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:                     C:\apache-tomcat-10.0.10
08-Jun-2022 23:56:05.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:                     C:\apache-tomcat-10.0.10
08-Jun-2022 23:56:05.902 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             --add-opens=java.base/java.lang=ALL-UNNAMED
08-Jun-2022 23:56:05.902 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             --add-opens=java.base/java.io=ALL-UNNAMED
08-Jun-2022 23:56:05.902 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             --add-opens=java.base/java.util=ALL-UNNAMED
08-Jun-2022 23:56:05.902 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
08-Jun-2022 23:56:05.902 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
08-Jun-2022 23:56:05.903 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Djava.util.logging.config.file=C:\apache-tomcat-10.0.10\conf\logging.properties
08-Jun-2022 23:56:05.903 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
08-Jun-2022 23:56:05.903 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Djdk.tls.ephemeralDHKeySize=2048
08-Jun-2022 23:56:05.903 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
08-Jun-2022 23:56:05.903 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Dignore.endorsed.dirs=
08-Jun-2022 23:56:05.904 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Dcatalina.base=C:\apache-tomcat-10.0.10
08-Jun-2022 23:56:05.904 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Dcatalina.home=C:\apache-tomcat-10.0.10
08-Jun-2022 23:56:05.904 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument:             -Djava.io.tmpdir=C:\apache-tomcat-10.0.10\temp
08-Jun-2022 23:56:05.906 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Cargada la biblioteca nativa APR de Apache Tomcat [1.2.30] con la versión APR [1.7.0].
08-Jun-2022 23:56:05.906 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Capacidades APR: IPv6 [true], enviar fichero [true], aceptar filtros [false], aleatorio [true], UDS [true].
08-Jun-2022 23:56:05.908 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL inicializado correctamente [OpenSSL 1.1.1k  25 Mar 2021]
08-Jun-2022 23:56:06.033 INFO [main] org.apache.coyote.AbstractProtocol.init Inicializando el manejador de protocolo ["http-nio-8080"]

08-Jun-2022 23:56:06.047 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [285] milliseconds
08-Jun-2022 23:56:06.218 INFO [main] org.apache.catalina.core.StandardService.startInternal Arrancando servicio [Catalina]
08-Jun-2022 23:56:06.219 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.10]
08-Jun-2022 23:56:09.091 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars Al menos un JAR, que se ha explorado buscando TLDs, aún no contenía TLDs. Activar historial de depuración para este historiador para una completa lista de los JARs que fueron explorados y de los que nos se halló TLDs. Saltarse JARs no necesarios durante la exploración puede dar lugar a una mejora de tiempo significativa en el arranque y compilación de JSP .
08-Jun-2022 23:56:09.141 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
08-Jun-2022 23:56:09.182 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [3133] milliseconds
```

**Access log shows (for every request.):**
0:0:0:0:0:0:0:1 - - [08/Jun/2022:23:56:38 +0200] "GET / HTTP/1.1" 404 688

Same result with a new clean vanilla Grails 5 made with the basic configuracion and just changing:

`implementation "org.springframework.boot:spring-boot-starter-tomcat"`

to 

`testImplementation "org.springframework.boot:spring-boot-starter-tomcat"`

**Comment by vrivon** [comment]
I added the basic project to github repository: https://github.com/vrivon/grails5

It works on Tomcat 8.5. It doesnt work on Tomcat 9.0.44, Tomcat 10.0.10 , Tomcat 10.0.21

**Comment by fernando88to** [comment]
I forked the project and it worked on tomcat 9

https://github.com/fernando88to/grails5


About tomcat 10, i think grails is not compatible, but i'm looking for that info still.

**Comment by vrivon** [comment]
> I forked the project and it worked on tomcat 9
> 
> https://github.com/fernando88to/grails5
> 
> About tomcat 10, i think grails is not compatible, but i'm looking for that info still.

Hi Fernando. Thanks for answering.

For some reason my project didnt work on Tomcat 9, but after trying again, it works. Perhaps I made a mistake while testing with so many servers and applications.

I have been trying with my application compiled with Grails 4 and Grails 5. Its seems that it is something related to JVM version.

**GRAILS 4**

```
Tomcat 8.5 -- JVM 11 --Grails 4 -- It works
Tomcat 9    -- JVM 11 --Grails 4 -- It works
Tomcat 10   -- JVM 11 --Grails 4 -- Not tested
```

```
Tomcat 8.5 -- JVM 16 --Grails 4 -- It works
Tomcat 9    -- JVM 16 --Grails 4 -- It works
Tomcat 10   -- JVM 16 --Grails 4 -- fails
```
```
Tomcat 8.5 -- JVM 1.8 --Grails 4 -- It works
Tomcat 9    -- JVM 1.8  --Grails 4 -- It works
Tomcat 10   -- JVM 1.8 --Grails 4 -- fails
```

**GRAILS 5**
```
Tomcat 8.5 -- JVM 11 --Grails 5 -- fails 
Tomcat 9    -- JVM 11 --Grails 5 -- fails
Tomcat 10   -- JVM 11 --Grails 5 -- Not tested
```

```
Tomcat 8.5 -- JVM 16 --Grails 5 -- It works
Tomcat 9    -- JVM 16 --Grails 5 -- It works
Tomcat 10   -- JVM 16 --Grails 5 -- fails
```
```
Tomcat 8.5 -- JVM 1.8 --Grails 5 -- fails
Tomcat 9    -- JVM 1.8 --Grails 5 -- fails
Tomcat 10   -- JVM 1.8 --Grails 5 -- fails
```

Summary:
Grails 5 is just working with JVM 16 on Tomcat 8.5 and 9.
Grails 4 works with JVM 11,16 and 1.8 on  Tomcat 8.5 and 9.
Nothing works on Tomcat 10

What is strange is that Grails 5 tells that is compatible with java 1.8 

What is the JVM version you are using?

**Comment by fernando88to** [comment]
No repository has a dockerfile ( https://github.com/fernando88to/grails5/blob/master/Dockerfile ), it has jdk version 11.0.15.

**Comment by fernando88to** [comment]
In README.md there are commands to build the image.

**Comment by vrivon** [comment]
So you managed to run the Grails 5 application with JVM 11. I needed to upgrade to JVM 16. I cannt find an explanation. 

Thank you anyway

**Comment by fernando88to** [comment]
I created a dockerfile for tomcat 9 with jdk 16, it also worked. Look in the repository https://github.com/fernando88to/grails5 and give the following commands that are in readme.md

Build application using command ./gradlew build.
Build Docker image using command docker build -f Dockerfilejdk16 -t issue12547:0.1 ..
Start a new Docker container using command docker run -it --rm -p 8080:8080 issue12547:0.1.
Access http://localhost:8080/

**Comment by fernando88to** [comment]
Even with jdk 17 it worked too

https://github.com/fernando88to/grails5

1. Build application using command `./gradlew build`.
2. Build Docker image using command `docker build -f Dockerfilejdk17 -t issue12547:0.1 .`.
3. Start a new Docker container using command `docker run -it --rm -p 8080:8080 issue12547:0.1`.
4. Access http://localhost:8080

**Comment by puneetbehl** [comment]
Grails 5 does not support Tomcat 10 yet. Please use Tomcat 9 instead. Thanks!
