### ISSUE TITLE
no works .groovy configuration logging file 

### ISSUE THREAD

**Issue by JJAM2014** [grails/grails-core#12567]
### Expected Behavior

I have upgraded my system from 4.x version to 5.x grails version but in the documentation is said

logging:
    config: /Users/me/config/filelogback-logging.groovy

Should recognize .groovy extension

### Actual Behaviour

Logging system failed to initialize using configuration from '/Users/xxx/.grails/filelogback-logging.groovy'
Caused by: ch.qos.logback.core.LogbackException: Unexpected filename extension of file [file:/C:/Users/xxx/filelogback-logging.groovy]. Should be .xml

only recognize .xml extension 

### Steps To Reproduce

./gradle bootRun 

### Environment Information

I have configuration below 

grailsVersion=5.1.7
grailsGradlePluginVersion=5.1.3
groovyVersion=3.0.7
gorm.version=7.2.1
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
windows 10
JDK JAVA 11 

### Version

5.1.7

**Comment by arixmkii** [comment]
Upstream (logback) removed support of groovy config as a security precaution. Version bump happened with this release https://github.com/grails/grails-core/releases/tag/v5.1.2

May be some updates are missing in the docs.

Some hot discussions [here](https://github.com/grails/grails-core/issues/12399)

**Comment by JJAM2014** [comment]
Dear arixmkii,

thanks you very much

best regards,

José
