### ISSUE TITLE
Grails 5.1.8 not compiling filters

### ISSUE THREAD

**Issue by ippezshelby** [grails/grails-core#12573]
### Expected Behavior

Am trying to upgrade grails 2.4 app to latest version of grails (5.1.8). App is able to run normally ( ./grailsw run-app executes without errors)

However data in views (gsp) are not rendered. after digging deeper I have realized my filters are not working. I have filters for Menu, Permissions and SecurityContext and are responsible for rendering what is to be returned based for gsp views based on user rights and Permissions

Expected:
1. if (!session.user) redirect to login
2. if user authentication passes fetch user menu based on roles and return menus in views

### Actual Behaviour

My filters are not compiled. I have placed them in config folder, could this be the problem?

Actual behavior: 
Since filters seem not compiled none of the expected behaviors work

### Environment Information

Windows 11
JDK 11

### Version

5.1.8

**Comment by fernando88to** [comment]
Filters have been replaced by interceptor


https://grails.org/blog/2015-03-01.html

**Comment by ippezshelby** [comment]
Am trying to convert the filters into Interceptors but am still getting no response. Things are not working. How do i convert the below filter into an interceptor! This will give me a clue to do for others

```
package pos
class SecurityContextFilters {
    def userService
    def filters = {
        loginChecker(controller:'*', action:'*', controllerExclude: 'assets|POSInterfaceListener', actionExclude:'login|auth|logout') {
            before = {
                if(!session.user) {
                    redirect(controller:"auth", action:"login")
                    return false
                }
            }
            after = { Map model ->

            }
            afterView = { Exception e ->

            }
        }
        changePwdChecker(controller:'*', action:'*', controllerExclude: 'assets|POSInterfaceListener',  actionExclude:'login|auth|logout|changePwd|savePwd') {
            before = {
                if(userService.checkIfChange()) {
                    redirect(controller:"user", action:"changePwd")
                    return false
                }
            }
        }
    }
}
```

**Comment by puneetbehl** [comment]
Please check https://www.tothenew.com/blog/grails-3-migrating-from-filters-to-interceptors/ maybe it help you.

**Comment by ippezshelby** [comment]
@puneetbehl l, thanks but when I gave it a shot things are still not working.. The above documentation also mentions of ability to still use filters if someone wishes. when I include the plugin in Grails 5.1.8 App (grails-plugin-filters:3.0.17) as mentioned at da last part of the document and moved all the filters in the root directoryof controllers folder, still I can't get user permissions rendered for the logged in user

Any workarounds are highly appreciated

**Comment by olavgg** [comment]
@Ippezrobert check out how to write Spring Boot interceptors if Grails interceptors is not working.
https://www.tutorialspoint.com/spring_boot/spring_boot_interceptor.htm

Grails 3+ interceptors are created in the controllers folder/namespace/package

**Comment by jeffscottbrown** [comment]
> Grails 3+ interceptors are created in the controllers folder/namespace/package

If you use the `create-interceptor` command that is where they are created, but you can define interceptors any number of places.  For example, some folks like to create them in `grails-app/interceptors/`.

**Comment by ippezshelby** [comment]
Thanks everyone! with all your inputs, i was able to convert all the filters to interceptors with exception of one which is to return a model map.

Any suggestions on how i can handle it
**Code Snippets:-**
```
class MenuInterceptor {
    def roleModuleService

    MenuInterceptor() {
        match(controller: "*", action: "*")
        .except(controller: "auth", action: "login|changePwd|logout")
    }

    boolean after () { Map model ->
        model?.gatewayConfigMenu = roleModuleService.getMenu('gatewayConfig')
        model?.smsMenu = roleModuleService.getMenu('sms')
        model?.emailMenu = roleModuleService.getMenu('email')
    }
}
```

Thanks and regards

**Comment by jeffscottbrown** [comment]
Instead of this...

    boolean after () { Map model ->
        model?.gatewayConfigMenu = roleModuleService.getMenu('gatewayConfig')
        model?.smsMenu = roleModuleService.getMenu('sms')
        model?.emailMenu = roleModuleService.getMenu('email')
    }

Try this...

    boolean after () {
        model.gatewayConfigMenu = roleModuleService.getMenu('gatewayConfig')
        model.smsMenu = roleModuleService.getMenu('sms')
        model.emailMenu = roleModuleService.getMenu('email')
        true
    }

See [docs.grails.org/5.1.8/guide/theWebLayer.html#interceptors](https://docs.grails.org/5.1.8/guide/theWebLayer.html#interceptors).

**Comment by ippezshelby** [comment]
> Instead of this...
> 
> ```
> boolean after () { Map model ->
>     model?.gatewayConfigMenu = roleModuleService.getMenu('gatewayConfig')
>     model?.smsMenu = roleModuleService.getMenu('sms')
>     model?.emailMenu = roleModuleService.getMenu('email')
> }
> ```
> 
> Try this...
> 
> ```
> boolean after () {
>     model.gatewayConfigMenu = roleModuleService.getMenu('gatewayConfig')
>     model.smsMenu = roleModuleService.getMenu('sms')
>     model.emailMenu = roleModuleService.getMenu('email')
>     true
> }
> ```
> 
> See [docs.grails.org/5.1.8/guide/theWebLayer.html#interceptors](https://docs.grails.org/5.1.8/guide/theWebLayer.html#interceptors).

@jeffbrown , Thanks that resolved the issue! 
Am closing this as everything works as expected !!! Thanks y'all
