### ISSUE TITLE
Can't run Grails 5.2.1

### ISSUE THREAD

**Issue by jadelomeiri** [grails/grails-core#12609]
### Expected Behavior

Run a Grails 5.2.1 app

### Actual Behaviour

![image](https://user-images.githubusercontent.com/5457472/178728159-4e803a29-4936-41ab-a409-1ff29bb450da.png)

### Steps To Reproduce

1. Create a new app `grails create-app newg`
2. Run app 'grails run-app'

### Environment Information

- Win 11
- JDK 16.0.2
- Grails 5.2.1

### Version

5.2.1

**Comment by puneetbehl** [comment]
Please wait for some time. I think it is taking longer to sync the Grails Gradle Plugin to Maven Central. The artifact is published here https://repo1.maven.org/maven2/org/grails/grails-gradle-plugin/5.2.1/

**Comment by jadelomeiri** [comment]
Fantastic, thanks a lot @puneetbehl !
Just wanted to flag it early in case there was an underlying problem you needed to be aware of
