### ISSUE TITLE
Calling Environment.setCurrentReloadError fails with StackOverflowError

### ISSUE THREAD

**Issue by andresluuk** [grails/grails-core#12627]
### Expected Behavior

Method should work and not fail

### Actual Behaviour

We get a StackOverflowError from inside groovy

### Steps To Reproduce

Use latest grails and call Environment.setCurrentReloadError(null) somewhere like AbstractGrailsPluginManager does.
I reported a groovy bug: https://issues.apache.org/jira/browse/GROOVY-10695
I think the issue is that the method name is the same as the setter name for the field.

### Environment Information

Windows, JDK 11

### Version

5.2.1

**Comment by andresluuk** [comment]
So from the talk in the groovy case you have bug in:
https://github.com/grails/grails-core/blob/5.2.x/grails-bootstrap/src/main/groovy/grails/util/Environment.groovy : 238
Should use Environment.@currentReloadError instead of the current way.

**Comment by davidbairdala** [comment]
FYI this is the same issue as https://github.com/grails/grails-core/issues/12608

**Comment by puneetbehl** [comment]
Closing this as it is a duplicate.
