### ISSUE TITLE
Grails 5.1.8, Always getting SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder" warning, what's wrong ?

### ISSUE THREAD

**Issue by akiesh22** [grails/grails-core#12633]
### Issue description

grails create-app generated scaffolding always produces following errors:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I tried resolving this as described in "SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details."
but this hasn't gone away, tried https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder as suggested here but this didn't resolve it either.

**Comment by mattmoss** [comment]
I ran into this once before, when IntelliJ was running grails commands via the `org.grails.cli.GrailsCli` from the grails-shell project, and I believe it's that class/project generating the SLF4J messages, not your application.

@akiesh22 Can you describe an example situation where you see that error?

**Comment by akiesh22** [comment]
This is seen for every app generated with grails create-app, for grails 5.1.8.

**Comment by mattmoss** [comment]
@akiesh22 So, can you describe a specific CLI command, IntelliJ action, gradle task, etc... something that allows me to reproduce your issue?

**Comment by akiesh22** [comment]
This is all to it.


1. in CLI : grails create-app logger   
2. Go to intellij IDEA and run the app

<img width="661" alt="Screen Shot 2022-08-01 at 23 35 26" src="https://user-images.githubusercontent.com/24637655/182210993-202dc49c-adf0-4406-9d9d-f1b8b9c5d017.png">

**Comment by mattmoss** [comment]
So, it's cut-off at the top, but I'm certain that IntelliJ is launching your app via the `org.grails.cli.GrailsCli` class, and the SLF4J error message is coming from *that* class, not from your application.

I created an app following your step 1 above. Then, running in the same CLI `gradle bootRun` or `grails run-app`, I do not see the SLF4J error message.

**Comment by akiesh22** [comment]
Thank you very much, you are absolutely correct.

**Comment by rlconst** [comment]
So what the fix? Is is IntelliJIDEA bug?

**Comment by mattmoss** [comment]
> So what the fix? Is is IntelliJIDEA bug?

It's an issue with the `org.grails.cli.GrailsCli` from the `grails-shell` module, and would need to be fixed there.
