### ISSUE TITLE
Error deploying war with version 5.2.1

### ISSUE THREAD

**Issue by miguelabautista** [grails/grails-core#12649]
### Actual Behaviour

with this version tomcat is failing because of this:

```
java.lang.IllegalArgumentException: Illegal character in path at index 16: file:/C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/crsfatca/WEB-INF/lib/grails-core-5.2.1.jar
```

now it's complaining about white spaces in the path. is this expected from now on?

### Environment Information

- windows
- java 8

### Version

5.2.1

**Comment by puneetbehl** [comment]
Please provide the steps to replicate or an example application.

**Comment by puneetbehl** [comment]
Please try with Grails 5.2.2 and reopen the issue with a sample application if you still see the problem
