### ISSUE TITLE
Integration Test Fails If App Contains Request Scoped Bean

### ISSUE THREAD

**Issue by jeffscottbrown** [grails/grails-core#12676]
### Issue description

@ppazos report this issue at https://stackoverflow.com/questions/73436018/newly-created-grails-3-integration-test-no-thread-bound-request-found.

> I just wrote some code in the test setup and run it, I got this error then I just commented everything and run the test again, just the empty test as it was created by grails create-integration-test, I got this exception (not sure why Grails tries to load these services I'm not using in the test and why it fails because some are scoped to request).
> 
> This is Grails 3.3.10.

    Error creating bean with name 'xmlService': Scope 'request' is not active

He provided a sample project at [github.com/ppazos/grails_3_3_10_test_service](https://github.com/ppazos/grails_3_3_10_test_service).

**Comment by puneetbehl** [comment]
Grails 3 is EOL, and it is very unlikely to receive any updates. I am unable to replicate the problem in higher Grails version (I tried with Grails 4).
Please read about Grails Support Schedule [here](https://grails.org/support-schedule.html)

**Comment by jeffscottbrown** [comment]
Thanks @puneetbehl.
