### ISSUE TITLE
grails empty app doesn't run in Docker

### ISSUE THREAD

**Issue by xpusostomos** [grails/grails-core#12686]
- [ ] Steps to reproduce provided

It seems to me that an empty shell of a grails app does not start properly in docker.

```
sdk install grails 5.2.3
grails create-app mytest
cd mytest
cat >Dockerfile <<EOF
FROM tomcat:9.0.63-jdk11-temurin
COPY build/libs/mytest-0.1.war /usr/local/tomcat/webapps/ROOT.war
EOF
./gradlew bootWar
docker build -t myself/mytest .
docker run -it --rm -p 8888:8080 myself/mytest
```

and go to http://localhost:8888 ...
HTTP Status 404 – Not Found
Type Status Report
Message The requested resource [/] is not available
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

I am able to access static assets:
http://localhost:8888/assets/spinner.gif

there are no errors in the logs.

I've also tried the whole dance around
      providedCompile "org.springframework.boot:spring-boot-starter-tomcat"
or
     testImplementation "org.springframework.boot:spring-boot-starter-tomcat"

to no avail. (this needs to be documented better, if this is still needed, albeit I have other apps it doesn't seem to be needed for)

It does seem to deploy ok in a non-docker tomcat.

### Expected Behaviour

Should bring up the grails welcome page.

### Actual Behaviour

as above, 404

### Environment Information

- **Operating System**: Windows,
- **Grails Version:** 5.2.3
- **JDK Version:** 11
- **Container Version (If Applicable): Docker desktop 4.11.1

**Comment by jeffscottbrown** [comment]
FYI... I am using macOs and am using Docker Desktop 3.6.0 so those are 2 differences but the instructions described above work in that environment and the app does respond at http://localhost:8888/.

**Comment by jeffscottbrown** [comment]
Another FYI... A colleague has tested using Windows 10 and Docker Desktop 4.3.1 and confirms that he does see the error reported in the issue.

**Comment by xpusostomos** [comment]
It would appear that the problem was that my default java version was java 13 and the docker image I chose was java 11, and therefore somewhere in the depths of processing, it dies due to wrong java class version. However I'm surprised there is no log output for this.

**Comment by jeffscottbrown** [comment]
> However I'm surprised there is no log output for this.

I am too.  Can you share what does show up in your Docker log?

**Comment by jeffscottbrown** [comment]
> It would appear that the problem was that my default java version was java 13

That makes the behavior make sense to me.  I thought you were using 11.  If you are building with 13 and running with 11, that is likely a significant factor.

**Comment by jeffscottbrown** [comment]
I have verified that on macOs if I build with JDK 17 (I don't have 13 installed) and then deploy with the instructions above, that I see the same problematic behavior, which I would consider expected.  I don't know why nothing is being logged, but otherwise the behavior makes sense to me.

**Comment by jeffscottbrown** [comment]
It looks like the fact that the app won't startup probably isn't related to Docker, probably isn't something that Grails could address, and probably would behave the same for any Java app.  @puneetbehl I think this is probably a `not-a-bug`.  What do you think?

**Comment by xpusostomos** [comment]
You're probably right this is not a bug.. the one question mark in my mind is if something in default grails logging stops the error coming out.

**Comment by jeffscottbrown** [comment]
"the one question mark in my mind is if something in default grails logging stops the error coming out" - I think the answer is "no". AFAIK there is nothing in the default grails logging that is affecting that.
