### ISSUE TITLE
Grails framework incorrectly allows data binding to static properties

### ISSUE THREAD

**Issue by mattmoss** [grails/grails-core#12718]
### Issue Description

A bug was found in the Grails framework data binding logic that incorrectly permits data binding to static properties under certain conditions. 

More information is available on the Grails blog at https://grails.org/blog/2022-09-28-static-binding-bug.html

I have opened this issue to facilitate discussion of this bug.

### Status: Fixed

For Grails 5, the bug fix is available in the [5.2.3 release](https://github.com/grails/grails-core/releases/tag/v5.2.3).
Relevant commit: [313fc58d](https://github.com/grails/grails-core/pull/12666/commits/313fc58d099eda61696c4a0d39445c5c9422baaa)

For Grails 4, the bug fix is available in the [4.1.2 release](https://github.com/grails/grails-core/releases/tag/v4.1.2).
Relevant commit: [f44ffd87](https://github.com/grails/grails-core/pull/12665/commits/f44ffd87802e52e9bf0f69f945b35075bb349841)

For Grails 3, the bug fix is available in the [3.3.16 release](https://github.com/grails/grails-core/releases/tag/v3.3.16).
Relevant commit: [43977fbf](https://github.com/grails/grails-core/pull/12664/commits/43977fbfaa9166e29e45fd72e006d0e095a87e62)

**Comment by ice1080** [comment]
Hello! Thanks for identifying this bug.
The blog mentions that this can occur when "manually calling bindData (or one of several variants)"; do you happen to have a list of the other variants that can also cause this issue to occur?

**Comment by boardbloke** [comment]
I am interested to know whether it necessary to update plugins that target Grails 5.x but are built Grails versions prior to 5.2.3.  That is, is it enough to update just the Grails version that pulls in the plugins, or does each plugin that targets Grails 5.x need to be  upgraded as well?

**Comment by mattmoss** [comment]
> Hello! Thanks for identifying this bug. The blog mentions that this can occur when "manually calling bindData (or one of several variants)"; do you happen to have a list of the other variants that can also cause this issue to occur?

The most common variants would come from classes in the `grails.web.databinding` package:
- [DataBinder](https://github.com/grails/grails-core/blob/5.2.x/grails-web-databinding/src/main/groovy/grails/web/databinding/DataBinder.groovy)
  - This trait is applied by Grails to every controller (via the `Controller` trait), so it's not uncommon to see one of these `bindData` variants used in controllers.
- [DataBindingUtils](https://github.com/grails/grails-core/blob/5.2.x/grails-web-databinding/src/main/groovy/grails/web/databinding/DataBindingUtils.java)
  - This class has static utility methods that are often used in places where you need a one-off data binding, typically via `DataBindingUtils.bindObjectToInstance`.
- [GrailsWebDataBinder](https://github.com/grails/grails-core/blob/5.2.x/grails-web-databinding/src/main/groovy/grails/web/databinding/GrailsWebDataBinder.groovy)
  - This class provides the bean `grailsWebDataBinder` that is used by Grails to do data binding as it needs. I don't expect most end-users to use this directly.
- [WebDataBinding](https://github.com/grails/grails-core/blob/5.2.x/grails-web-databinding/src/main/groovy/grails/web/databinding/WebDataBinding.groovy)
  - The most common place to find this trait in Grails is your domain classes: when compiled, they extend this trait, which provides the `getProperties` and `setProperties` methods on all domain objects. Commonly used like: `instance.properties = [a: 1, b: 2, ...]`

**Comment by mattmoss** [comment]
> I am interested to know whether it necessary to update plugins that target Grails 5.x but are built Grails versions prior to 5.2.3. That is, is it enough to update just the Grails version that pulls in the plugins, or does each plugin that targets Grails 5.x need to be upgraded as well?

In the typical case, it should be sufficient to upgrade/update the application using the plugin.

However, I can't answer for all possible build configurations. A review of your gradle (or other build tool) configuration would be a good idea. Using `gradle dependencies` or creating a gradle scan can help to identify exactly what dependencies are being brought in, which are prioritized, etc.
