### ISSUE TITLE
Grails 5.2.3 run-app stuck at 25% Executing on MultiProject MultiTenant Project for over 30 minutes

### ISSUE THREAD

**Issue by Crackpack** [grails/grails-core#12732]
### Expected Behavior

Project should complete smoothly or show any errors for further debugging

### Actual Behaviour

```
grails> run-app
| Running application...
10:45:53,016 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:45:53,017 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at 
[file:/E:/TestUpgrade/et-domain-plugin/build/resources/main/logback.xml]
10:45:53,018 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
10:45:53,019 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at 
[file:/E:/TestUpgrade/et-domain-plugin/build/resources/main/logback.xml]
10:45:53,019 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at
[file:/E:/TestUpgrade/et-views-plugin/build/resources/main/logback.xml]
10:45:53,019 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at 
[file:/E:/TestUpgrade/et-services-plugin/build/resources/main/logback.xml]
10:45:55,350 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:45:55,351 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [org.springframework.boot.logging.logback.ColorConverter]
10:45:55,351 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter]
10:45:55,352 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:45:55,365 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:45:55,373 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:45:55,427 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
10:45:55,427 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:45:55,428 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:45:55,430 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4d8c9af7 - Registering current configuration as safe fallback point

<===----------> 25% EXECUTING [38m 19s]
> :et-controller-plugin:compileGroovy
```
### Steps To Reproduce

In grails 5.2.3, multiproject multitennat project. We are upgrading our grails version from 3.3.9 to grails 5.2.3

I am able to run projects successfully with domain and services plugins only. Having issues when integrating controllers plugin.
We have over 16 plugins and 350 domains.

### Environment Information

- Operating System: Windows 10
- JDK : 1.8.0-333

### Version

5.2.3

**Comment by puneetbehl** [comment]
Sorry that you are facing issues while upgrading the application. However, it is very difficult to identify the problem without a sample application. One possible problem might be insufficient memory settings. I would suggest checking how much JVM Memory is allocated to the Java process.

**Comment by Crackpack** [comment]
I have added memory in grails project in 2 files.
In main build.gradle file, i have added following lines:
```
bootRun {
        jvmArgs(
                '-Dspring.output.ansi.enabled=always',
                '-noverify',
                '-XX:TieredStopAtLevel=1',
                '-javaagent:../lib/springloaded-1.3.0.BUILD-20210404.024037-2.jar',
                '-Xmx8000m')
        sourceResources sourceSets.main
    }
```
and in gradle .properties file:
`org.gradle.jvmargs=-Xms4g -Xmx12g`

Now that, I am using YourKit Java Profiler. I see that the process is being held by GradleWorkerMain.
And its allocated memory is only 488 MB.

I have tracked down to only 2 controllers in the plugin are giving issue. I have tried to split them into smaller controllers, it didnt fix my issue. I dont see any codes that could create such issues. And, if i remove those 2 controllers then, the project is working correctly, but if i re-add them then, it is stuck here.

Issue giving Controller codes are only about 1600 lines. 

I dont think i will be able to simulate it other than in this project.  So, I wont be able to provide any sample for you. Sorry for that.

Specs of my computer :
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
RAM: 32 GB

I have attached my memory status of GradleWorkerMain while it is stuck in 25%

![Memory1](https://user-images.githubusercontent.com/13462855/196781377-069f0f93-c9d5-425e-a695-09ea5bc92322.JPG)
![Memory2](https://user-images.githubusercontent.com/13462855/196781760-21561736-5081-4151-9a60-c935946944d8.JPG)

**Comment by Crackpack** [comment]
In main build.gradle file,I have tried 
```
 bootRun {
        jvmArgs(
                '-Dspring.output.ansi.enabled=always',
                '-noverify',
                '-XX:TieredStopAtLevel=1',
                '-Xmx8000m -XX:MaxMetaspaceSize=2048m  -XX:NewSize=2048m -XX:MaxNewSize=2048m -XX:MaxPermSize=2048m')
        sourceResources sourceSets.main
    }
```

in gradle.properties file, i have tried:
`org.gradle.jvmargs=-Xms4g -Xmx12g -XX:NewSize=2048m -XX:MaxNewSize=2048m -XX:MaxPermSize=2048m`

in gradlew file line 32 I have added GRADLE_OPTS:

```
# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m"'
GRADLE_OPTS="-Xmx4G -Xms12G -XX:NewSize=2048m -XX:MaxNewSize=2048m -XX:MaxNewSize=2048m -XX:MaxPermSize=2048m"

```

nothing seems to increase Memory for "GradleWorkerMain"

**Comment by puneetbehl** [comment]
I believe the settings are correct. Can you try to create a brand new Grails application and verify if you are able to change memory? Also, try setting `org.gradle.daemon=false` in the gradle.properties file of your existing project.

**Comment by Crackpack** [comment]
i added following line in build.gradle file and also set `org.gradle.daemon=false` and` org.gradle.parallel=true`

```
tasks.withType(GroovyCompile) {
        configure(groovyOptions) {
            forkOptions.jvmArgs = ['-Xmx2048m']
        }
    }
```

this did the trick. Thank you for pointing me to right direction. :)
