### ISSUE TITLE
Grails 5.2.5 - Gradle plugin 5.2.4 is referenced but it has not been released yet.

### ISSUE THREAD

**Issue by lynchie14** [grails/grails-core#12758]
### Expected Behavior

Think it needs it's own release as only the 5.2.4 snapshots are available

### Steps To Reproduce

* What went wrong:
A problem occurred configuring root project 'test'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.grails:grails-gradle-plugin:5.2.4.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/grails/grails-gradle-plugin/5.2.4/grails-gradle-plugin-5.2.4.pom
       - https://repo.grails.org/grails/core/org/grails/grails-gradle-plugin/5.2.4/grails-gradle-plugin-5.2.4.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1m
| Error Error initializing classpath: Could not find org.grails:grails-gradle-plugin:5.2.4.
Searched in the following locations:
  - https://plugins.gradle.org/m2/org/grails/grails-gradle-plugin/5.2.4/grails-gradle-plugin-5.2.4.pom
  - https://repo.grails.org/grails/core/org/grails/grails-gradle-plugin/5.2.4/grails-gradle-plugin-5.2.4.pom
Required by:
    project : (Use --stacktrace to see the full trace)

### Version

5.2.5

**Comment by puneetbehl** [comment]
Sorry for the inconvenience, this should be resolved now.

**Comment by lynchie14** [comment]
Thanks, working now.
