### ISSUE TITLE
Downloading old versions of grails doesn't work in sdkman

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-core#12757]
### Expected Behavior

To install a version of grails on the computer.

### Actual Behaviour

When trying to install an old version of grails an exception is thrown.

`Downloading: grails 2.1.0

In progress...

-=O#-   #       #        #                                                                                                                                                                   
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/fernando/.sdkman/tmp/grails-2.1.0.zip or
        /home/fernando/.sdkman/tmp/grails-2.1.0.zip.zip, and cannot find /home/fernando/.sdkman/tmp/grails-2.1.0.zip.ZIP, period.`

### Steps To Reproduce

sdk install grails 2.1.0

### Version

2.0

**Comment by vkissoyan** [comment]
This is happening on everything below 3.0 it seems can reproduce on 2.2.1

**Comment by jeffscottbrown** [comment]
> This is happening on everything below 3.0 it seems can reproduce on 2.2.1

FYI... I don't believe that is true.  I think there are some pre 3.0 releases that look fine...


```
$ sdk install grails 2.5.5

Downloading: grails 2.5.5

In progress...

############################################################################################################################################################################# 100.0%

Installing: grails 2.5.5
Done installing!

Do you want grails 2.5.5 to be set as default? (Y/n): n
```

**Comment by Annie-12** [comment]
Facing the same issue with grails 2.3.4 while installing in WSL2 . 
Tried downloading and extracting the zip for grails 2.3.4 but that also throw exception .
