### ISSUE TITLE
Does grails framework support the scala language

### ISSUE THREAD

**Issue by sunsilong-pacvue** [grails/grails-core#12761]
### Issue description

I want to be able to write scala in the grails framework

**Comment by puneetbehl** [comment]
Please use Grails Slack for questions. https://grails.slack.com. 

I don't think there is any support for Scala with the Grails framework. But, I found some resource which may be useful to you:

https://vilimpoc.org/blog/2014/03/25/grails-groovy-scala-and-akka/
http://www.christianoestreich.com/2011/04/mixing-grails-groovy-scala-java/
https://github.com/ctoestreich/grails-scala
https://stackoverflow.com/questions/4937782/how-to-call-grails-from-scala

**Comment by sunsilong-pacvue** [comment]
think you very mach
