### ISSUE TITLE
I find the grails framework very memory intensive. Is there any way to reduce memory?

### ISSUE THREAD

**Issue by sunsilong-pacvue** [grails/grails-core#12767]
### Issue description

<img width="512" alt="image" src="https://user-images.githubusercontent.com/24616352/201893312-3fe58ffb-4a44-4a89-bb35-c9fa373afb1f.png">

**Comment by olavgg** [comment]
Have you set the Xmx to something? I run medium sized applications with Xmx=512M

**Comment by jeffscottbrown** [comment]
Have you profiled the application to discover what is using most of the memory?

**Comment by jeffscottbrown** [comment]
> Is there any way to reduce memory?

Without knowing more about the application it is difficult to say if the application is effectively optimized for minimal memory consumption or not.
