### ISSUE TITLE
Downloads broken on SDKMAN

### ISSUE THREAD

**Issue by marc0der** [grails/grails-core#12827]
### Issue description

Hi all,

I've recently received complaints that downloads are failing on SDKMAN. On further investigation, it seems the location of your binaries have changed and are no longer hosted in the `dist.springframework.org.s3` bucket. Here is a failure log of the SDKMAN db crawler that I ran. Please advise on how these URLs should be updated to be valid.

Thanks!

```
[main] INFO io.***.Main$ - grails 1.3.5 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.5.zip
[main] INFO io.***.Main$ - grails 1.3.6 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.6.zip
[main] INFO io.***.Main$ - grails 1.3.7 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.7.zip
[main] INFO io.***.Main$ - grails 1.3.8 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.8.zip
[main] INFO io.***.Main$ - grails 1.3.9 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.9.zip
[main] INFO io.***.Main$ - grails 2.0.0 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.0.0.zip
[main] INFO io.***.Main$ - grails 2.0.1 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.0.1.zip
[main] INFO io.***.Main$ - grails 2.0.2 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.0.2.zip
[main] INFO io.***.Main$ - grails 2.0.3 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.0.3.zip
[main] INFO io.***.Main$ - grails 2.0.4 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.0.4.zip
[main] INFO io.***.Main$ - grails 2.1.0 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.1.0.zip
[main] INFO io.***.Main$ - grails 2.1.1 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.1.1.zip
[main] INFO io.***.Main$ - grails 2.1.2 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.1.2.zip
[main] INFO io.***.Main$ - grails 2.1.3 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.1.3.zip
[main] INFO io.***.Main$ - grails 2.1.4 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.1.4.zip
[main] INFO io.***.Main$ - grails 2.1.5 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.1.5.zip
[main] INFO io.***.Main$ - grails 2.2.0 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.0.zip
[main] INFO io.***.Main$ - grails 2.2.1 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.1.zip
[main] INFO io.***.Main$ - grails 2.2.2 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.2.zip
[main] INFO io.***.Main$ - grails 2.2.3 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.3.zip
[main] INFO io.***.Main$ - grails 2.2.4 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.4.zip
[main] INFO io.***.Main$ - grails 2.2.5 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.5.zip
[main] INFO io.***.Main$ - grails 2.3.0 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.0.zip
[main] INFO io.***.Main$ - grails 2.3.1 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.1.zip
[main] INFO io.***.Main$ - grails 2.3.10 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.10.zip
[main] INFO io.***.Main$ - grails 2.3.11 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.11.zip
[main] INFO io.***.Main$ - grails 2.3.2 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.2.zip
[main] INFO io.***.Main$ - grails 2.3.3 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.3.zip
[main] INFO io.***.Main$ - grails 2.3.4 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.4.zip
[main] INFO io.***.Main$ - grails 2.3.5 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.5.zip
[main] INFO io.***.Main$ - grails 2.3.6 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.6.zip
[main] INFO io.***.Main$ - grails 2.3.7 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.7.zip
[main] INFO io.***.Main$ - grails 2.3.8 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.8.zip
[main] INFO io.***.Main$ - grails 2.3.9 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.9.zip
[main] INFO io.***.Main$ - grails 2.4.0 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.0.zip
[main] INFO io.***.Main$ - grails 2.4.1 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.1.zip
[main] INFO io.***.Main$ - grails 2.4.2 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.2.zip
[main] INFO io.***.Main$ - grails 2.4.3 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.3.zip
[main] INFO io.***.Main$ - grails 2.4.4 (UNIVERSAL): http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.4.zip
```

**Comment by marc0der** [comment]
Would you please be able to help with this @puneetbehl?

**Comment by puneetbehl** [comment]
Just an update, I was trying to update the broken Grails links. @marc0der and I coordinate for same and tried to use SDKMan Vendor CURL APIs to update to ZIP from GitHub release but unfortunately there are some challenges right now where I am unable to do so. 

Following is the error message: 
```
{"status":403,"message":"Not authorised to use this service."}
```

Next, we are going to generate new credentials to fix broken releases.

**Comment by puneetbehl** [comment]
Thanks @marc0der for the all the help. I have fixed all the release mentioned above. Please let me know if you still face any challenges.

**Comment by mckenzm** [comment]
Not just SDKMan but if I have not pre-downloaded using SDKMAN.  The answer is that SDKMAN is now the only way.
Downloading http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.9.zip to /home/matthew/.grails/wrapper/grails-2.3.9-download.zip

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.9.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at org.grails.wrapper.RemoteFileHelper.retrieve(RemoteFileHelper.java:49)
	at org.grails.wrapper.GrailsWrapper.configureGrailsInstallation(GrailsWrapper.java:137)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:57)

**Comment by JamesDamour** [comment]
@puneetbehl Like mckenzm, I'm getting an HTTP 403 when trying to download an old version of Grails:
`$ ./grailsw -clover.on=false clean -non-interactive -plain-output
Downloading http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.3.zip to /root/.grails/wrapper/grails-2.4.3-download.zip
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.3.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at org.grails.wrapper.RemoteFileHelper.retrieve(RemoteFileHelper.java:49)
	at org.grails.wrapper.GrailsWrapper.configureGrailsInstallation(GrailsWrapper.java:137)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:57)`
	
Is there any way to remove the authentication on these old ZIP files? If not, is there some way to configure `grails-wrapper.properties` to present credentials?

**Comment by swellhunter** [comment]
I think this is on AWS. Tightening up public access to S3. They need a console button or API method to "make this publicly readable and don't argue". It is work to audit all these so an outage may not be obvious for the older artefacts.
