### ISSUE TITLE
Unable to install grails 2.3.11 SDKMAN

### ISSUE THREAD

**Issue by cvedak22** [grails/grails-core#12930]
### Expected Behavior

I was trying to install grails version 2.3.11 and wasn't able to do so. Below is error log:

![image](https://user-images.githubusercontent.com/35111565/225401843-6329d53d-c315-4bf7-a4a1-a4800cd0ca93.png)

### Steps To Reproduce

Install SDKMAN as per documentation - https://sdkman.io/install

Grails 2.3.11 - sdk install grails 2.3.11 breaks the installation after few seconds

### Environment Information

OS: Ubuntu 
Java Version - openjdk version "1.8.0_362"

### Version

2.3.11

**Comment by mitidiero** [comment]
I see the same issue. 2.3.9 works, but 2.3.10 and 2.3.11 don't.  I also tried to install it locally but says it's an invalid version.

**Comment by puneetbehl** [comment]
It should be resolved now.
