### ISSUE TITLE
Can't run Grails 6.0.0-M2 on WSL2 unbuntu 20.04

### ISSUE THREAD

**Issue by boardbloke** [grails/grails-core#12943]
I am only adding this in case its useful or other people...

I installed the Grails 6.0.0-M2 via sdkman on WSL2 and tried to run 
```grails --version```

I got an error about ['GLIBC_2.34' not found on Ubuntu]

Updating my WSL2 to Ubuntu 22.04 as per - https://askubuntu.com/questions/1428423/upgrade-ubuntu-in-wsl2-from-20-04-to-22-04 fixed it for me

**Comment by guillermocalvo** [comment]
Hi @boardbloke. Thanks for reporting this issue.

You're right. Grails CLI binary is compiled against ubuntu-latest to make sure all the latest security patches are applied. Therefore, it may not run on environments where `libc` is not up to date.
