### ISSUE TITLE
Grails 5.x reload behavoir changed

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#12966]
### Expected Behavior

Each time a service or controller is modified in DEV mode, that piece should be recompiled and the app should stay started. I migrated an app from 3.3.16 to 5.3.2 and with Grails 3.x the app wasn't restarted and the current data wasn't lost.

### Actual Behaviour

Each time a controller or service is modified, the whole application shuts down and restarts, all the test data is gone, and takes a long time to be on the same data state as before the change was introduced. Even adding a comment makes the whole application to restart.

### Steps To Reproduce

1. Create an app in Grails 5.3.2
2. Create a domain
3. Generate all
4. start app
5. Make change in controller, just add a comment or anything small
6. The whole application restarts

### Environment Information

OS: Linux Mint
Grails 5.3.2
JDK 11.0.10

### Version

5.3.2

**Comment by olavgg** [comment]
This is what happens on Spring Boot too, you have to rewrite your application so that you use database migrate scripts ie flyway to apply changes to the database. Don't create table with hibernate, you can create the ddl with it though.

**Comment by ppazos** [comment]
@olavgg this is not about database changes, is about controller and service changes reload the whole app and deletes-regenerates the database schema. Behavior that changed from 3.x to 5.x in Grails.

**Comment by puneetbehl** [comment]
Yes, this is changed in Grails 4 because of the switch to SpringBoot devtools. See https://docs.grails.org/latest/guide/upgrading.html#upgrading33x.

**Comment by ppazos** [comment]
@puneetbehl is there a way to avoid deleting all the data during dev mode run when a controller or service is modified? That grails deletes all the data on small code modifications makes functional testing a living hell... it takes half an hour to test and fix something that in Grails 3 took 5 minutes. I'm actually regretting to have updated our system to Grails 5.

**Comment by puneetbehl** [comment]
I would recommend using the Database Migration scripts instead of initializing the database from scratch every time the application is started in development mode. Also, you would need to change the database configuration from create-drop in the development mode.

**Comment by ppazos** [comment]
@puneetbehl good suggestions, thanks

Though for initializing the DB, for functional testing new features there is no fixed data, just me testing things from scratch to see if everything works, fixed data set loading works when testing existing things or for small changes over existing things, but for full new features, testing and retesting the whole flow from zero is required.

**Comment by puneetbehl** [comment]
Unfortunately, the spring loaded library is no longer maintained and does not support Java 11. I believe @davydotcom made some progress with Spring Loaded and Grails 5. I believe he can shed some light on the same topic.
