### ISSUE TITLE
Grails commands in the documentation (version 6)

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-core#13009]
### Expected Behavior

In version 6 the grails commands are basically

  create-app Creates an application
   create-webapp Creates an application
   create-plugin Creates an Grails Plugin
   create-web-plugin Creates an Grails Web Plugin
   create-restapi Creates an REST API
   create-domain-class Creates a Domain Class
   create-controller Creates a Grails Controller

However, the documentation mentions several others, I suggest that the old command is still included in the documentation but that it makes reference to how it would be using gradle.

For example

before
./grailsw run-app

now
./gradlew bootRun

### Version

6RC1

**Comment by puneetbehl** [comment]
This is already addressed in the latest snapshot documentation at https://docs.grails.org/snapshot/
