### ISSUE TITLE
Grails 6 - BuildInfo info.app.version is 'unspecified'

### ISSUE THREAD

**Issue by matrei** [grails/grails-core#13011]
### Expected Behavior

`info.app.version` in the `META-INF/grails.build.info` file should not be set to 'unspecified'.

### Actual Behaviour

`info.app.version` in the `META-INF/grails.build.info` file is set to 'unspecified'.

### Steps To Reproduce

```bash
grails -V
Grails Version: 6.0.0-RC1

java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

grails create-app g600rc1
cd g600rc1

./gradlew bootRun
```
Open localhost:8080 and check under the **Application Status** menu.
App version: unspecified

```bash
cat ./build/resources/main/META-INF/grails.build.info
#Fri, 26 May 2023 09:55:19 +0200

info.app.version=unspecified
info.app.name=g600rc1
grails.env=production
info.app.grailsVersion=6.0.0-RC1
```

### Environment Information

- Operating System: Kubuntu 22.04
- JDK Version: 11

### Version

6.0.0-RC1

**Comment by codeconsole** [comment]
![unspecified](https://raw.githubusercontent.com/codeconsole/grails4bugs/master/doc/grails6.0.0-RC1.png
)

**Comment by matrei** [comment]
Adding `version=0.1` to gradle.properties fixes the problem.

**Comment by codeconsole** [comment]
@matrei that's interesting. I can confirm adding `version=0.1` to `gradle.properties` fixes the problem.

So
```
version = "0.1"
``` 
in `build.gradle` in the generated app serves no purpose and should be removed.
