### ISSUE TITLE
RBAC not working for grails default action calling

### ISSUE THREAD

**Issue by Tanusiwag02** [grails/grails-core#13021]
### Expected Behavior

I have a restController with a rest end point as list

```
import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured

class MyRestController {

    @Secured(['ROLE_ADMIN'])
    def list() {
        render(['status': 200, 'message': 'Access granted for list'] as JSON)
    }

}
```
I applied RBAC on list for Role 'ROLE_ADMIN' but when I am accessing this controller without specifying action name(default URI for a controller), it's giving me response even when I am not logged in.

Accessing http://localhost:8080/myRest should redirect me to login page or should give 404 but definitely should not respond me with list restAPI response.

### Actual Behaviour

When I am calling API with URL http://localhost:8080/myRest/list, it's redirecting me to login page; which is the expected behaviour. But when I am hitting default url for controller in my browser, I am getting response.

API Calling URL: http://localhost:8080/myRest

Response:` {"status": 200,"message": "Access granted for list"}`

### Version

2.4.5

**Comment by virtualdogbert** [comment]
This seems like a Spring Security Issue, not a Grails issue. However, even in that case, there is not enough information given to diagnose the issue. No version of the spring-security plugin, and no indication, on how it is configured. For something like this providing a sample app might help: https://start.grails.org/. 

One last note Grails 2.x, 3.x, and 4.x are all end-of-life and are not supported, so you'll find little if any support for them, and plugins that are pre 3.x. A lot of the 3.x plugins work in newer versions of Grails, but that varies depending on the plugin. Upgrading from Grails 2 to something more modern can be challenging depending on the size of the code base, how many bad deprecated practices you have in your code, and how many plugins you use that were not maintained.

Here's an accounting on one of the upgrades I did:
https://dev.to/virtualdogbert/grails-2-5-5-to-grails-3-3-10-postmortem-520a
https://dev.to/virtualdogbert/grails-3-3-10-to-4-0-2-postmortem-5kj

Upgrading after version 3 and especially 3.3 becomes a lot easier.
