### ISSUE TITLE
5.3.2 - Update Spring Boot 2.7.8 -> 2.7.13

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13046]
### Expected Behavior

Given that Grails is based on Spring Boot, I would expect a patch release schedule somewhat more regular or document an easier way to keep Spring Boot dependencies in sync.

5.3.2 was released 2/14/23

https://repo1.maven.org/maven2/org/grails/grails-bom/

### Version

5.3.2

**Comment by codeconsole** [comment]
Where/How is 2.7.8 being resolved?

https://repo1.maven.org/maven2/org/grails/grails-bom/5.3.2/grails-bom-5.3.2.pom

https://repo1.maven.org/maven2/io/micronaut/spring/micronaut-spring-boot/4.5.0/micronaut-spring-boot-4.5.0.pom

**Comment by codeconsole** [comment]
Is the 6.0.0 branch the only one being maintained at this point?

https://github.com/grails/grails-core/pull/13048

**Comment by matrei** [comment]
According to https://grails.org/support-schedule.html Grails 4/5 are still in maintenance/development.
In absence of dependency updates in framework, you can override the versions in gradle.properties/build.gradle.
But I agree, these dependency updates ought to be gone over/updated before every new release.

**Comment by andrewcanby-finocomp** [comment]
Interested in this also.

It looks like `2.7.8` comes from the [grails-core-5.3.2.pom](https://repo1.maven.org/maven2/org/grails/grails-core/5.3.2/grails-core-5.3.2.pom) and it's`2.7.9` in [grails-core-5.3.3.pom](https://repo1.maven.org/maven2/org/grails/grails-core/5.3.3/grails-core-5.3.3.pom).

It'd be great to have a property for this in the Grails bom, as they're currently hardcoded.

**Comment by codeconsole** [comment]
+1 on having a property

**Comment by rainboyan** [comment]
You can always do like this，and stop having the illusion of waiting for the next version 

https://github.com/rainboyan/grails-spring-boot-2-7-demo

Last year, I created an issue and submit a PR try to fix this

https://github.com/grails/grails-gradle-plugin/issues/104

**Comment by guillermocalvo** [comment]
Fixed by https://github.com/grails/grails-core/pull/13048
