### ISSUE TITLE
Issue with webdriverBinaries for grails 5.3.2 and java 17

### ISSUE THREAD

**Issue by jostheron** [grails/grails-core#13057]
### Expected Behavior

After upgrading to java 17 my grails 5.3.2 project can no longer run tests via grails test-app. I'm getting the following 2 errors.

1) Task :configureGeckoDriverBinary FAILED
2) Task :configureGeckoDriverBinary FAILED

If I remove the below from build.gradle it works again.
```
chromedriver {
            version = '2.45.0'
            fallbackTo32Bit = true
        }
        geckodriver '0.30.0'
```
java version is: 
```
java --version
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

### Version

5.3.2

**Comment by puneetbehl** [comment]
I'm sorry that you are facing this issue. It is difficult to know what might be the problem with the above information. Please note that Grails 5 does not officially support Java 17. So, I would request you to use Java 8 or 11 and share the complete stacktrace, if you still face an issue?

Here is an [example Grails application](https://github.com/grails/grails-functional-tests/blob/5.3.x/gradle/geb.gradle) which is using Webdriver binaries plugin.
