### ISSUE TITLE
Please Explain Why Groovy 3.0.11 and not 3.0.18

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13088]
### Issue description

Groovy 3.0.11 was released 2022-06-01.

As of 2023-06-29, we are now at Groovy 3.0.18

Please explain why Grails is using a version of Groovy that is over 1 year old and 7 releases behind the latest patch release?

If there is an outstanding Groovy issue, please give a reference?

If there is an issue with Grails performing correctly using the latest version, please advise.

**Comment by puneetbehl** [comment]
Duplicate of #13012
