### ISSUE TITLE
Hot reloading is not working

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-core#13104]
### Expected Behavior

When changing a controller it was expected that Hot reloading would work, however it is not working, I have to stop the application and start again

### Actual Behaviour

Hot reloading is not working

### Steps To Reproduce

1 - curl --location --request GET 'https://grailsforge-latest-cjmq3uyfcq-uc.a.run.app/create/web/com.example.demo?gorm=HIBERNATE&servlet=TOMCAT&test=SPOCK&javaVersion=JDK_11' --output demo.zip
2 - unzip demo.zip
3 - grails create-controller Index
4 - ./gradlew bootRun
5 - I modify the controller
6 - I check the output

### Environment Information

openjdk 11.0.19 2023-04-18
grails 6.0.0

### Version

6.0.0

**Comment by puneetbehl** [comment]
In Grails 4, applications include the [Spring Boot Developer Tools](https://docs.spring.io/spring-boot/docs/2.7.12/reference/html/using.html#using.devtools) dependency. This facilitates the automatic restart of the application when alterations are made to source files. It's important to note that the use of Devtools might introduce challenges related to classloading. To ensure smooth implementation, we recommend a thorough review of the provided documentation.

Unlike its earlier versions, Grails 6 does not include this functionality by default. However, incorporating the subsequent dependency into your project's build.gradle file can reinstate this feature:

```groovy
developmentOnly("org.springframework.boot:spring-boot-devtools")
```

Furthermore, with Grails 6.0.1, the option to include the "Spring Boot DevTools" feature is available during the application creation process.

**Comment by vsachinv** [comment]
@puneetbehl Facing same challenge in Grails 6. Is there option to achieve hot reloading without restart as was in Grails 3? As our application is monolith and having frequent restarts while changing just few lines code here and there. It would slow down development speed.

**Comment by jamesfredley** [comment]
spring-boot-devtools is the route for Grails 4, 5 and 6.  Grails 7 SNAPSHOTS are currently working with https://github.com/HotswapProjects/HotswapAgent 

You also need groovy hotswap:

https://andrewclement.blogspot.com/2010/03/groovy-eclipse-groovy-hotswap-support.html

https://github.com/groovy/groovy-eclipse
