### ISSUE TITLE
Grails 6 can't use classes from test in integration-test

### ISSUE THREAD

**Issue by mattlong-finocomp** [grails/grails-core#13107]
### Expected Behavior

I have a trait in src/test that contains some helper methods that have been useful in classes in src/integration-test.
In previous versions of Grails I could implement the trait on my integration-test Spec classes.

### Actual Behaviour

compileIntegrationTestGroovy failed compilation as it can't resolve the class from src/test

### Steps To Reproduce

1. use a generated rest-api profile (profile might not matter, but rest-api is what i used) project from start.grails.org
2. Create a Trait class in src/test/groovy named TestHelper
3. Create an integration Spec in src/integration-test/groovy and attempt to implement the TestHelper class created previously - This works in Grails 5.3.3 and earlier but not in 6.0.0

### Environment Information

- OS: Pop!OS 22.04
- Java: 11

### Version

6.0.0

**Comment by jeffscottbrown** [comment]
See the project at https://github.com/jeffbrown/integrationtraitdemo.

[src/main/groovy/com/demo/SomeTrait.groovy](https://github.com/jeffbrown/integrationtraitdemo/blob/1faaf0a37a2e189c1df3362970a191272caceadc/src/main/groovy/com/demo/SomeTrait.groovy)

```
package com.demo

trait SomeTrait {
}
```

[src/integration-test/groovy/com/demo/MySpec.groovy](https://github.com/jeffbrown/integrationtraitdemo/blob/1faaf0a37a2e189c1df3362970a191272caceadc/src/integration-test/groovy/com/demo/MySpec.groovy)

```
package com.demo

import grails.testing.mixin.integration.Integration
import spock.lang.Specification

@Integration
class MySpec extends Specification implements SomeTrait {

    void "test something"() {
        expect:
        true
    }
}
```


Does that build and run in your environment?

Thank you for your feedback!

**Comment by jeffscottbrown** [comment]
FYI... At https://github.com/jeffbrown/integrationtraitdemo/commit/50fb864afae3274147b4b10720d7702f819e74ef I renamed the trait to use the name specified in the initial report above in case there was something going on related to the name "*Helper".

**Comment by jeffscottbrown** [comment]
I see now that the report calls for putting the trait in `src/test/`, not `src/main`.  I expect that is the relevant bit.

**Comment by mattlong-finocomp** [comment]
Yes, having the trait in src/main is fine. The regression is only on classes in src/test. This trait in particular is not something i'd want to end up in the production jar so it wouldn't make sense for us to put it in src/main.

**Comment by mattlong-finocomp** [comment]
@puneetbehl Can you provide any estimate on when there might be a 6.0.1 (or 6.1.0) grails release, or at the very least a release of the grails-gradle-plugin so that this fix can be used?
