### ISSUE TITLE
grails 6 "run-app" command not working.

### ISSUE THREAD

**Issue by tircnf** [grails/grails-core#13108]
### Expected Behavior

`grails run-app`
or `run-app` from interactive mode

should run the grails app.

### Actual Behaviour

in grails 5.2 the application starts.

with grails 6

$ grails run-app
Unmatched argument at index 0: 'run-app'
Did you mean: grails create-app or grails create-webapp or grails create-restapi?

### Steps To Reproduce

1.  With grails 6 installed, and either java 11 or 17.
2.  grails create-app gr6
3. cd gr6
4. grails run-app

### Environment Information

Recreated with windows-cygwin and on a mac.

### Example Application

Unmodified default grails application.    `grails create-app gr6`

### Version

6.0.0

**Comment by tircnf** [comment]
The gradle tasks still work and gradle run/bootrun will start the app, but I was unable to get other actions (s2-quickstart) to work after installing spring-security-core.

It responds with the exact same error:

`$ grails s2-quickstart com.test User Role`
Unmatched arguments from index 0: 's2-quickstart', 'com', 'User', 'Role'

**Comment by tircnf** [comment]
I also tried using intellij's grails runner to start the default app.  

`C:\Users\temp\.jdks\openjdk-17.0.2\bin\java.exe -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -Djline.WindowsTerminal.directConsole=false -Dfile.encoding=UTF-8 @C:\Users\temp\AppData\Local\Temp\idea_arg_file328071704 org.grails.cli.GrailsCli run-app --plain-output`

```

|Resolving Dependencies. Please wait...
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar
> Task :buildSrc:assemble
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.2/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 3s
1 actionable task: 1 executed
Error |
Could not resolve all dependencies for configuration ':profile'. Type 'gradle dependencies' for more information

Process finished with exit code 1
```

**Comment by fernando88to** [comment]
In version 6, the "grails run-app" command no longer exists, the "./gradlew bootRun" command must be used. 

An issue has already been opened about intellij idea at https://youtrack.jetbrains.com/issue/IDEA-327614/Idea-Intellij-does-not-recognize-a-project-with-grails-6

**Comment by tircnf** [comment]
How about other commands added by plugins?

is there a gradle command to run other scripts like the `s2-quickstart` command in the spring-security-core plugin?

**Comment by codeconsole** [comment]
> How about other commands added by plugins?
> 
> is there a gradle command to run other scripts like the `s2-quickstart` command in the spring-security-core plugin?

@tircnf A custom ApplicationCommand will need to be done similar to what [was done for the scaffolding plugin](https://github.com/grails/scaffolding/commit/db2ef730a5a0839268f12e244b76254c76870da2)

Previous scaffolding tasks are now available via:
```
./gradlew runCommand "-Pargs=generate-controller website.Sample"
./gradlew runCommand "-Pargs=generate-views website.Sample"
./gradlew runCommand "-Pargs=install-templates"
```

**Comment by codeconsole** [comment]
s2-quickstart https://github.com/grails/grails-spring-security-core/issues/905

**Comment by puneetbehl** [comment]
Starting Grails 6, we are leveraging Gradle build system and there will not be commands to do redundant stuff such as `./grailsw run-app`. Please read more about this in https://grails.org/blog/2023-08-03-introducing-new-grails-forge.html

**Comment by robokaso** [comment]
Note that the [Getting Started Docs](https://docs.grails.org/6.0.0/guide/gettingStarted.html#runningAndDebuggingAnApplication) still refer to `run-app` so the newcomer experience is now completely broken.

**Comment by codeconsole** [comment]
Pull request: https://github.com/grails/grails-doc/pull/861

**Comment by jdaugherty** [comment]
While this ticket specifically addresses `grails run-app`, the refactored command line is a significant downgrade for grails plugin commands that take arguments.  For example, the grails database plugin has the 5.x command `grails dbm-gorm-diff test.groovy` and in 6.x the new syntax is: `gradle runCommand "-Pargs=dbm-gorm-diff test.groovy"`.  Worse, the database migration plugin doesn't even mention this new syntax so it will look like Grails 6.x is broken.  Not to mention that this is not convenient to type on the commandline with the quoting and gradle parameter syntax.  

Can we please consider adding a helper to the grails cli to run these commands?  Maybe `grails plugin <command> <command arguments>`? 

For now, I kept forgetting the syntax so as a work around, I created the below zsh function to make it easier to run plugin scripts like before:

        function _grails() {
    	    local msg="$*"; 
    	    local gradleArgs=`print -l $msg`;
    	    gradle runCommand "-Pargs=$gradleArgs"
        }

Hopefully this helps someone.  You can then run `_grails dbm-gorm-diff test.groovy` instead of remembering the gradle syntax.
