### ISSUE TITLE
unable to create application with rest-api profile

### ISSUE THREAD

**Issue by shrede01** [grails/grails-core#13110]
### Expected Behavior

When creating a new application using command:

grails create-app myapp --profile=rest-api

it should create the app as documented here : https://docs.grails.org/latest/guide/profiles.html

### Actual Behaviour

I am getting following error:

Unknown option: '--profile=rest-api'

### Environment Information

* JDK 11
* macOs ventura 13.0

### Version

6.0.0

**Comment by jeffscottbrown** [comment]
Does `grails create-restapi myapp` work?

**Comment by shrede01** [comment]
@jeffbrown yes that command works. Thanks!
