### ISSUE TITLE
grails 5 uses wrong gradle

### ISSUE THREAD

**Issue by chrisbitmead** [grails/grails-core#13113]
### Expected Behavior

I've seen that grails 5 now officially supports java 17. Except that all grails 5.x releases have gradle 7.2 and java 17 isn't a supported version for gradle 7.2

Rather it requires gradle 7.3.

https://docs.gradle.org/current/userguide/compatibility.html

It seems unnecessarily awkward to me to be requiring a different java for gradle than the one for grails. And therefore I suggest to be fully supporting java 17 the 5.x series create-app create-plugin and documentation should be upgraded to support gradle 7.3 or later so that it runs out of the box with all supported java versions.

And documentation like here:
https://docs.grails.org/5.3.3/guide/upgrading.html

Should suggest 7.3 or later instead of 7.2

### Actual Behaviour

grails and supporting documentation talk about gradle7.2 which isn't compatible with java 17.

### Steps To Reproduce

grasils create-app foo
cd foo
./gradlew -version

### Environment Information

- JDK version 17

### Version

5.3.3

**Comment by puneetbehl** [comment]
> I've seen that grails 5 now officially supports java 17. Except that all grails 5.x releases have gradle 7.2 and java 17 isn't a supported version for gradle 7.2

Can you please point out where have you seen that Grails framework 5 supports Java 17. As, I believe that is wrong because Grails 5 is shipped with Apache Groovy 3.0.11 which I believe current does not completely support Java 17. Also, there might be some applications which might work with Java 17 but Grails framework does not officially support Java 17 yet.

**Comment by puneetbehl** [comment]
Separate from my previous comment, I think we could try to update Grails framework 5 to Gradle 7.3.

**Comment by chrisbitmead** [comment]
@puneetbehl it was announced that grails 5 supports java 17 here:
https://github.com/grails/grails-core/issues/12850

**Comment by chrisbitmead** [comment]
Oh... I misread it, it's not really an annoucement, so my bad on that. Would be nice if it was announced. For example, certain AWS things won't work until you get to java 17, and grails 6.0.0 is not ready for prime time.

Also in a similar vein, full java 17 support should upgrade to a later groovy. Possibly 3.0.18

https://github.com/grails/grails-core/issues/12850
