### ISSUE TITLE
Upgrade H2

### ISSUE THREAD

**Issue by yuri1969** [grails/grails-core#13126]
### Actual Behaviour

The currently used release 1.4.200 of H2 is 4 years old and contains [multiple CVEs](https://mvnrepository.com/artifact/com.h2database/h2/1.4.200) which already trigger auditing scans.

Ideally, H2 should not affect any production built, although it still leaks from various places (see  #11753 or `./gradlew dependencies --configuration productionRuntimeClasspath`).

Can we upgrade the version of H2?

### Version

6.0.0

**Comment by matrei** [comment]
Fixed by #13206
