### ISSUE TITLE
Is there any way of caching dependencies in grails (Packaging Grails application) to speed up tests?

### ISSUE THREAD

**Issue by juanfrilla** [grails/grails-core#13131]
### Issue description

Is there any way of cache dependencies of a grails application to speed up tests and prevent packaging grails application everytime I run `grails test-app`command?

I'm using a docker container as well.
I want to speed up my test process, everytime I run the tests it reload the entire environment and it takes a lot of time.
This are the logs that prints:

```
| Loading Grails 2.1.5
| Configuring classpath
| Configuring classpath.
| Environment set to test
| Environment set to test.
| Environment set to test..
| Environment set to test...
| Environment set to test....
| Environment set to test.....
| Compiling 1 source files
| Compiling 1 source files.
| Compiling 1 source files..
| Compiling 1 source files
| Compiling 1 source files.
| Packaging Grails application
| Packaging Grails application.
| Packaging Grails application..
| Packaging Grails application...
| Packaging Grails application....
| Packaging Grails application.....
| Packaging Grails application
| Packaging Grails application.
| Packaging Grails application..
| Packaging Grails application...
| Packaging Grails application....
| Packaging Grails application.....
```
The stuff that takes more time it's packaging grails application. 
And I'm using grails 2.1.5

**Comment by puneetbehl** [comment]
I believe [Grails Slack](https://grails.slack.com) is the best the place to ask questions like these. I believe in the recent versions of Grails you could leverage Gradle Remote Cache to boost performance.
