### ISSUE TITLE
PENDING UPDATE: grails-boot NEEDS TO BE MERGED

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13140]
### [grails-boot](https://github.com/grails/grails-boot) is a useful dead project that is broken that needs to be updated.

I have my local copy working with Grails 6.x and SiteMesh 3.x, but it will require several merges to get up to sync.

Please merge https://github.com/grails/grails-boot/pull/6

and consider giving me direct commit rights to the repository. I don't mind maintaining the repo.

### Version

6.0.0

**Comment by codeconsole** [comment]
Pending pull requests:

https://github.com/grails/grails-boot/pull/6
https://github.com/grails/grails-gradle-plugin/pull/227
https://github.com/grails/grails-gradle-plugin/pull/228
https://github.com/grails/grails-gsp/pull/379

**Comment by puneetbehl** [comment]
@codeconsole I have given you the direct access to grails-boot project.

**Comment by codeconsole** [comment]
thanks

**Comment by codeconsole** [comment]
@puneetbehl please don't forget about https://github.com/grails/grails-gsp/pull/379
It's necessary for the `grails-web-sitemesh` package to resolve as a transitive dependency of `grails-plugin-gsp`

**Comment by puneetbehl** [comment]
Please check my comment on the PR.

**Comment by codeconsole** [comment]
@puneetbehl sorry, not sure how I missed that.   I just updated the pull request.
