### ISSUE TITLE
Can I skip packaging grails application while grails test-app?

### ISSUE THREAD

**Issue by juanfrilla** [grails/grails-core#13166]
### Issue description

Is there any way of skipping packaging grails application while doing `grails test-app` and going straight on to the tests?
Because everytime I run this command it takes a lot in the "Packaging grails application" step.

Im using grails 2.1.5

Thanks

**Comment by puneetbehl** [comment]
I believe [Grails Community Slack](https://grails.slack.com) is the best place to ask questions like this. Starting Grails 3, I believe you can use `./gradlew test`  command which should not package the application. But, I'm not sure about why executing `grails test-app` command packages the Grails application.
