### ISSUE TITLE
Grails 6.0.0 - Failed to apply plugin 'org.grails.grails-gsp'.

### ISSUE THREAD

**Issue by fco271292** [grails/grails-core#13184]
### Expected Behavior

Create an app with grails 6.0.0 and run with grails run-app or gradle clean bootRun but no working and launch the message:
* What went wrong:
An exception occurred applying plugin request [id: 'org.grails.grails-gsp', version: '6.0.0']
> Failed to apply plugin 'org.grails.grails-gsp'.
   > Could not create task ':compileGroovyPages'.
      > Could not create task of type 'GroovyPageForkCompileTask'.
         > java.lang.InstantiationException (no error message)

### Environment Information

- java version "11.0.20" 2023-07-18 LTS
- Grails Version: 6.0.0

### Version

6.0.0

**Comment by puneetbehl** [comment]
Could you please test it against Grails 6.1.0-SNAPSHOT? and verify if this is still an issue?

**Comment by jeffscottbrown** [comment]
> Create an app with grails 6.0.0 and run with grails run-app or gradle clean bootRun but no working and launch the message:


FYI... This is what I am currently seeing on macOs:

```
brownj@Jeff-Brown-Unity ~ % java --version
openjdk 11.0.15 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % grails --version
Grails Version: 6.0.0
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % grails create-app fcodemo
| Application created at /Users/brownj/fcodemo
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % 
brownj@Jeff-Brown-Unity ~ % cd fcodemo
brownj@Jeff-Brown-Unity fcodemo % 
brownj@Jeff-Brown-Unity fcodemo % ./gradlew clean bootRun

> Task :bootRun
Grails application running at http://localhost:8080 in environment: development
<===========--> 87% EXECUTING [7s]
> :bootRun
```

**Comment by jeffscottbrown** [comment]
> Create an app with grails 6.0.0 and run with grails run-app or gradle clean bootRun but no working and launch the message:

With "grails run-app" I would expect a different error since that is no longer supported.

**Comment by fco271292** [comment]
Thank you for your answer, i share some comments:

- The operating system i used was Windows 11, JDK 11.0.20, Grails 6.0.0 and Gradle 8.1.1, however the version 7.6.x must be used, in my case downgrade the version of gradle to 7.6.3 and i got success when running the application.
- The official documentation https://docs.grails.org/6.0.0/guide/single.html#gettingStarted, shows that it should be run with grails run-app, however, when using spring boot as a base it can be executed with the gradle clean bootRun command, i consider the documentation shoul be updated for this purpouse.

**Comment by codeconsole** [comment]
The documentation was updated a while ago.
I suggest you use the latest documentation https://docs.grails.org/snapshot/guide/single.html#gettingStarted

**Comment by jeffscottbrown** [comment]
> in my case downgrade the version of gradle to 7.6.3 and i got success when running the application

That makes sense to me.  A newly generated Grails 6.0.0 app is configured with Gradle 7.6.2.  It may be that you were running into an incompatibility with Gradle 8.

Thank you for the feedback!
