### ISSUE TITLE
6.0.0/6.1.0 grails create-app and forge generate different build.gradle files

### ISSUE THREAD

**Issue by robertoschwald** [grails/grails-core#13203]
### Expected Behavior

Either using grails create-app or the forge should generate the same code base.  This is currently not happening. If using "grails create-app", an old format build.gradle is created, which btw. leads to errors in Intellij. The forge version works (and has a modern Gradle syntax).

Btw. grails.org still shows 6.0.0 as latest version, while forge is on 6.1.0

### Actual Behaviour

Diff between grails create-app and forge build.gradle start:

```
< buildscript {
<     repositories {
<         maven { url "https://plugins.gradle.org/m2/" }
<         maven { url "https://repo.grails.org/grails/core" }
<     }
<     dependencies {
<         classpath "org.grails:grails-gradle-plugin:$grailsGradlePluginVersion"
<         classpath "gradle.plugin.com.github.erdi.webdriver-binaries:webdriver-binaries-gradle-plugin:2.6"
<         classpath "org.grails.plugins:hibernate5:7.3.0"
<         classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.4.7"
<     }
---
> plugins {
>     id "groovy"
>     id "org.grails.grails-gsp"
>     id "org.grails.grails-web"
>     id "com.github.erdi.webdriver-binaries"
>     id "war"
>     id "idea"
>     id "com.bertramlabs.asset-pipeline"
>     id "application"
>     id "eclipse"
```

### Steps To Reproduce

1. download Grails 6.0.0.zip or 6.1.0.zip and create an app with it
2. Use https://start.grails.org to create the same app
3. the create-app created version seems to be outdated and leads to Gradle errors in Intellij. 
4. The forge version works.

### Environment Information

- macOS 13.6.x
- Irrelevant which JDK to use. I tried 11 and 17

### Version

6.1.0

**Comment by puneetbehl** [comment]
Where did you download the Grails ZIP? I think the problem might be related to it. Please download it from https://grails.org/download.html

**Comment by robertoschwald** [comment]
I downloaded the file last week. Now I retried, same problem. Download is from https://github.com/grails/grails-core/releases/download/v6.0.0/grails-6.0.0.zip

Unpack and perform a grails create-app sample600. build.gradle is different to the forge one and seems to be old Gradle format.

**Comment by puneetbehl** [comment]
In Grails 6, we have created a brand new CLI. So, now you should download it from https://github.com/grails/grails-forge/releases.

**Comment by robertoschwald** [comment]
So https://github.com/grails/grails-core/releases/download/v6.0.0/grails-6.0.0.zip is non-functional?

**Comment by puneetbehl** [comment]
It should not be used for running Grails CLI.
