### ISSUE TITLE
URI appings with URI arguments do not work in Grails 5

### ISSUE THREAD

**Issue by imranmir** [grails/grails-core#13266]
### Expected Behavior

I created a fresh grails version 5 web application. Looks like  using uri argument to map to a different URI is broken in URLMappings. The URI mappings results in the white label error page. For example:
"404"(uri: '/exHandler/index')
"/myUsers"(uri: '/user/list')

Attaching a sample grails app for reference.
[webAppDemo.tar.gz](https://github.com/grails/grails-core/files/13577899/webAppDemo.tar.gz)

Note: This is an issue on Grails 6 as well.

### Steps To Reproduce

Create a fresh grails 5 app. Add URLMapping using uri aguments. e.g., "404"(uri: '/exHandler/index')
"/myUsers"(uri: '/user/list'). They dont work

### Version

5.3.2, 6.0.0

**Comment by guillermocalvo** [comment]
Hi @imranmir. Thanks for taking the time to report the issue.

I've been looking into your sample grails app and I found some configuration errors in your `UrlMappings`:

For instance:

- Mapping: `"404"(uri: '/exHandler/index')`.
  - According to [the guides](https://docs.grails.org/latest/guide/theWebLayer.html#mappingToResponseCodes), response codes can only be mapped to controller actions or views. So `uri` will not work here. This behavior might change in future releases though.
- Mapping: `"/"(uri:"/user/list")`.
  - That mapping is wrong, there's no `list` action in your `UserController`; you probably meant: `"/"(uri:"/user/index")`.
- Mapping: `"/myUsers"(uri: '/user/sayText')`.
  - I'm afraid that's also not right; you probably meant: `"/myUsers"(uri: '/hello/sayText')`.


Apart from the response code mapping, which is not supported yet, the rest of the URL mappings work as expected once you correct the URIs, so I'm going to close this ticket. Please feel free to reopen it if you find something else that is not working properly.
