### ISSUE TITLE
The grails releases since Nov 4 are 'unverified'

### ISSUE THREAD

**Issue by cofiem** [grails/grails-core#13279]
### Issue description

First of all, thanks for your work on Grails!

I am pleased to see new patch releases for v3.3.17, v4.1.3, and v.5.3.4, plus v6.1.0.

However, the commits that are tagged [show as 'unverified' in the GitHub website on the tags list page](https://github.com/grails/grails-core/tags).

I'm unsure exactly what this means in terms of security, but it does make me a little nervous to see those 'unverified' icons there.

![image](https://github.com/grails/grails-core/assets/441771/2ba3f560-731d-48d5-bcb0-47e2e5160ff4)

**Comment by puneetbehl** [comment]
We started using signed commits which give other people confidence about the origin of a change you have made. However,  these commits are made as part of Workflow action with unsigned which displays them as `unverified`. You can read more information at https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

At some point in the future, we will also use signed commits with custom actions.

**Comment by cofiem** [comment]
Ok. Thanks for explaining why the change ocurred.
