### ISSUE TITLE
java.time.LocalDateTime data binding seems to be incorrect in Grails 6.1.0

### ISSUE THREAD

**Issue by monetschemist** [grails/grails-core#13280]
### Expected Behavior

A domain class having a field declared to be `java.time.LocalDateTime` should have default data binding that expects [the standard  ISO-8601 string formats defined in that class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalDateTime.html#toString()).

For example, a `String` value such as `2023-12-11T17:12` should be successfully converted to the corresponding `LocalDateTime` value.

### Actual Behaviour

The default data binding fails to convert such `String` values.  For example, in my class `Scenario` which has a `LocalDateTime` field `dateTime`, the `ScenarioController` `save()` method fails on data binding with a message like:

```
scenario.errors org.grails.datastore.mapping.validation.ValidationErrors: 1 errors
Field error in object 'Scenario' on field 'dateTime': rejected value [2023-12-11T17:12]; codes [Scenario.dateTime.typeMismatch.error,Scenario.dateTime.typeMismatch,scenario.dateTime.typeMismatch.error,scenario.dateTime.typeMismatch,typeMismatch.Scenario.dateTime,typeMismatch.dateTime,typeMismatch.java.time.LocalDateTime,typeMismatch]; arguments [dateTime]; default message [Text '2023-12-11T17:12' could not be parsed at index 10]
```

This problem can be worked around by definining a specific data binding following [the example of the BindUsing annotation](https://docs.grails.org/6.1.0/guide/single.html#dependencyUpgrades) provided in the Grails 6.1.0 docs.  In my case, the following works:

`import grails.databinding.BindUsing`

...

```
    @BindUsing({obj, source ->
        LocalDateTime.parse(source['dateTime'])
    })
    LocalDateTime dateTime
```

I suppose this hints that the default data binding for `LocalDateTime` should use its `parse()` method.

### Steps To Reproduce

Create a domain class with a java.time.LocalDateTime field; create the CRUD for it; run the application and create a new instance of that domain class; enter the desired local date and time and save.

### Environment Information

- Ubuntu 23.10
- OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)

### Example Application

[This application has a single domain class with a LocalDateTime field](https://github.com/monetschemist/grails-localdatetime-binding-problem)

### Version

6.1.0

**Comment by monetschemist** [comment]
I realized I probably should have mentioned that the format including the T between the date and time components of the string is generated in my case by HTML `input type="datetime-local"` and not `g:datePicker`.

**Comment by monetschemist** [comment]
@puneetbehl thank you so much!  a question if I may - is this in 6.1.2 or somewhere down the road?

Again thank you so much!

**Comment by puneetbehl** [comment]
It will be a part of Grails 6.2.0 which we'll release in a few days.

**Comment by monetschemist** [comment]
@puneetbehl thanks very much for that clarification, and thanks again for fixing this!
