### ISSUE TITLE
afterLoad() is not called in subclass if not defined in base class - Grails 5.3.6, Gorm-mongodb 7.3.3  

### ISSUE THREAD

**Issue by mgm7734** [grails/grails-core#13348]
### Expected Behavior

I have a 3 level inheritance hierarchy:  A <- B <-C.     B implements afterLoad() & C overrides it.   I expect it to be called.

### Actual Behaviour

The method was not being called until I also implemented `def afterLoad() {}` in A [and added @Override to B.afterLoad].

### Version

5.3.6

**Comment by guillermocalvo** [comment]
Hi @mgm7734. Thanks for your report!

I recreated the scenario you describe, but everything seems to work as expected: `afterLoad` is invoked, regardless of whether the parent class defines it or not.

Here's a sample Grails 5.3.6 app and the instructions to demonstrate the behavior:

- <https://github.com/guillermocalvo/grails-core-issue-13348>

You can take a look at the demo app and its domain classes to hopefully find something that may not be properly configured in your app.

I will close this issue now, but please feel free to reopen it if your app still doesn't work as expected; in that case, it would be very useful if you could provide a demo app that we can use to reproduce the problem.
