### ISSUE TITLE
Deprecate the old grails-shell project

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-core#13399]
### Issue description

Starting Grails 6, we have introduction the new CLI. So, we would need to deprecate the grails-shell subproject or extract it out from grails-core.

**Comment by guillermocalvo** [comment]
@puneetbehl [Grails Profile Gradle Plugin](https://github.com/grails/grails-gradle-plugin/blob/6.1.x/src/main/groovy/org/grails/gradle/plugin/profiles/GrailsProfileGradlePlugin.groovy#L31) still depends greatly on `grails-shell`. I tried moving classes under `org.grails.cli.profile` from `grails-shell` to `grails-gradle-plugin`, but those classes depend on other packages that are unrelated to profiles, so I don't think it would be a clean move.

Is Grails Profile Gradle Plugin still relevant? In other words, can we deprecate it along with `grails-shell`, or do we need to keep maintaining it for the foreseeable future?

**Comment by puneetbehl** [comment]
Yes, I think it is not used any longer. Since Grails 6, we stopped using/creating Grails profiles. The plugin is used for distribution of Grails Profile. Also, there is GrailsProfilePublishPlugin which may also be removed.

**Comment by guillermocalvo** [comment]
> Yes, I think it is not used any longer. Since Grails 6, we stopped using/creating Grails profiles. The plugin is used for distribution of Grails Profile. Also, there is GrailsProfilePublishPlugin which may also be removed.

Thanks for the info! I created a [PR to remove those legacy plugins from **grails-gradle-plugin**](https://github.com/grails/grails-gradle-plugin/pull/287).

I looked into possible Grails projects that may still depend on the deprecated CLI and found several repositories. Most of them seem obsolete, but I'd like to know your opinion before we remove **grails-shell** from **grails-core**.

1. [**grails-profile-repository**](https://github.com/grails/grails-profile-repository/) ![](https://img.shields.io/github/last-commit/grails/grails-profile-repository/master)
   - According to the README file *"This repository is no longer used. Profiles now live in <https://github.com/grails-profiles>"*.
2. [**grails-profiles**](https://github.com/grails-profiles/) ![](https://img.shields.io/github/last-commit/grails-profiles/base/master)
   - You mentioned that Grails profiles are not used anymore, so I guess we can ignore all repositories under **grails-profiles** that still [depend on **grails-shell**](https://github.com/search?q=org%3Agrails-profiles%20org.grails.cli&type=code).
3. [**grails-wrapper**](https://github.com/grails/grails-wrapper/) ![](https://img.shields.io/github/last-commit/grails/grails-wrapper/master)
   - I believe this is just another legacy project that [used to depend on **grails-shell**](https://github.com/grails/grails-wrapper/blob/master/wrapper/src/main/groovy/grails/init/RunCommand.groovy#L40).
4. [**legacy-grails-doc**](https://github.com/grails/legacy-grails-doc/) ![](https://img.shields.io/github/last-commit/grails/legacy-grails-doc/gh-pages)
   - Although this repository has recent commits, I think we can ignore it too. I guess there may be some scheduled job that pushes changes periodically.
5. [**grails-database-migration**](https://github.com/grails/grails-database-migration/) ![](https://img.shields.io/github/last-commit/grails/grails-database-migration/5.0.x)
   - I'm not so sure about this one. It looks like it's being actively developed but [it still depends on **grails-shell**](https://github.com/grails/grails-database-migration/blob/5.0.x/src/main/groovy/org/grails/plugins/databasemigration/command/ScriptDatabaseMigrationCommand.groovy#L24).

So what do you think about all these legacy repositories @puneetbehl? Would it be possible to [archive them in GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) to make them read-only and indicate that they are no longer maintained?

**Comment by puneetbehl** [comment]
The [legacy-grails-doc](https://github.com/grails/legacy-grails-doc/) is created to surpass GitHub limit for publishing the Grails documentation on gh-pages. So, extracted the older version docs to a different repository. 

I am also not so sure about how [Grails Database Migration](https://github.com/grails/grails-database-migration/) plugin depends on grails-shell. It would be good to investigate the need. 

For the rest of these, I believe it is safe to archive them.

**Comment by guillermocalvo** [comment]
> [!IMPORTANT]
>
> @puneetbehl Please take a look at this PR: https://github.com/grails/grails-database-migration/pull/350
