### ISSUE TITLE
Unable to serve static html

### ISSUE THREAD

**Issue by shrede01** [grails/grails-core#13414]
### Expected Behavior

When placing html files within src/main/webapp  the page should have been accessible at localhost:8080 as per documented here https://gsp.grails.org/6.0.0/guide/resources.html. For example I created a "test/index.html" file with "hello world" content in it, and placed it within src/main/webapp. When hitting localhost:8080/test or localhost:8080/test/indexhtml, I would have expected to see "Hello world" text rendered.

### Actual Behaviour

Instead I am seeing 404 not found.

### Steps To Reproduce

1. sdk use grails 6.0.0
2. grails create-webapp demo
3. create index.html file with some text in src/main/webapp/test folder
4. ./gradlew bootRun
5. browse http://localhost:8080/test/index.html or http://localhost:8080/test

### Environment Information

* jdk 11
* macOs

### Version

6.0.0

**Comment by matrei** [comment]
Your static file is served under http://localhost:8080/static/test/index.html (note the inclusion of the `static` dir in the path)

From the [documentation](https://gsp.grails.org/latest/guide/resources.html):

> For example, if you had a file stored at /src/main/resources/public/images/example.png and your Grails application was running on port 8080, then you could access the file by navigating to http://localhost:8080/static/images/example.jpg.

The default url pattern for serving static resources is `/static/**`, but this can be changed by setting the `grails.resources.pattern` config property.

**Comment by shrede01** [comment]
@matrei thank you so much for the response. I understood the documentation wrong, I thought when files are placed at "src/main/resources/public" then only we needed "static" in the path. 

In application.yml, after setting:

```
grails:
  resources:
    pattern: "/**"
```

I am able to access the content at  http://localhost:8080/test/index.html

thank you!

**Comment by shrede01** [comment]
@matrei thank you so much for the response. I understood the documentation wrong, I thought when files are placed at "src/main/resources/public" then only we needed "static" in the path. 

In application.yml, after setting:

```
grails:
  resources:
    pattern: "/**"
```

I am able to access the content at  http://localhost:8080/test/index.html

thank you!
