### ISSUE TITLE
missing `bin/grails` and `bin/grails.bat` for 6.2.0 release

### ISSUE THREAD

**Issue by chenrui333** [grails/grails-core#13465]
👋 looks like missing couple of bin folder for 6.2.0 release. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/168120

**Comment by puneetbehl** [comment]
Starting Grails 6, You should use the new Grails CLI from https://github.com/grails/grails-forge/releases/download/v6.2.0/grails-cli-6.2.0.zip

Please read https://grails.org/blog/2023-08-03-introducing-new-grails-forge.html for more information

**Comment by chenrui333** [comment]
thanks for the pointer, trying it now.

**Comment by chenrui333** [comment]
Works for us, closing the issue.
