### ISSUE TITLE
Error during @ToString processing: 'includes' property on Extended Object in Grails 6.2.0

### ISSUE THREAD

**Issue by amondel2** [grails/grails-core#13489]
### Expected Behavior

```
class GenericDomainObject implements Serializable {

    String id

    private static final serialVersionUID = 1L

    def beforeValidate() {
        if(!id || id.equals(null)) {
            id  = Utils.getInstance().idGenerator()
        }
    }

    def beforeInsert() {
        if(!id || id.equals(null)) {
            id  = Utils.getInstance().idGenerator()
        }
    }
}
```

```
@ToString(includeNames=true,includes='id,dueDate')
class radmonDomain extends GenericDomainObject {
   Date dueDate
}
```
I have the following radmonDomain in my Domain Objects and GenericDomainObject in src/groovy above in Grails 6.1.2 this worked and the code compiled 

### Actual Behaviour

After upgrading to Grails 6.2.0 I get the following error during complieGroovy step

Error during @ToString processing: 'includes' property 'id' does not exist.
 @ line 8, column 1.
   @ToString(includeNames=true,includes='id,dueDate')
   ^

### Environment Information

OS: Linux
Java: JDK 17 

### Version

6.2.0

**Comment by amondel2** [comment]
The easiest workaround is to just create a toString() method in the domain object but still wanted to report this.

**Comment by tylervz** [comment]
@amondel2 I actually get an error starting a Grails 5.3.5 project (with JDK 8) with the  `radmonDomain` and `GenericDomainObject`  Domain Objects defined as you have them above.
```text
Error during @ToString processing: 'includes' property 'id' does not exist.
 @ line 7, column 1.
   @ToString(includeNames=true,includes='id,dueDate')
```

And I got the same error when trying to run a Grails 6.1.2 project (with JDK 11) with the  `radmonDomain` and `GenericDomainObject`  Domain Objects defined as you have them above.

To fix the error, you can modify the `@ToString` annotation in your `radmonDomain` class to include the `includeSuperProperties=true` attribute. This tells Groovy to also consider properties from superclasses when generating the `toString()` method.

```groovy
@ToString(includeNames=true, includes='id,dueDate', includeSuperProperties=true)
class radmonDomain extends GenericDomainObject {

   Date dueDate
}
```

**Comment by amondel2** [comment]
ahh thanks !
