### ISSUE TITLE
Grails 5.3.6 multi-project log not injected into plugin services

### ISSUE THREAD

**Issue by mgm7734** [grails/grails-core#13508]
Plugin project log statements all cause errors.
This seemed to work with 5.3.2.

I created a simple multi-project using the instructions from https://guides.grails.org/grails-multi-project-build/guide/index.html
```
package pir.domain
class GreetService {
    def greet() {
        log.warn("DEBUG>>> GreetService.greet()")    // <=== this fails at runtime
        return "Hello, World!"
    }
}
```

### Steps to Reproduce

1. Clone https://github.com/mgm7734/multi-proj
2. Run with `./gradlew bootRun`
3. Navigate to http://localhost:8080/hello/index

### Expected Behaviour

Console should output warning "DEUBUG>>> GreetService.greet()"
The page should display.

### Actual Behaviour

You see this error
```
    /hello/index
Class
    groovy.lang.MissingPropertyException
Message
    null
Caused by
    No such property: log for class: pir.domain.GreetService
``
### Environment Information

- **Operating System**: osx
- **Grails Version:** 5.3.2
- **JDK Version:** openjdk version "11.0.17" 2022-10-18 LTS
- **Container Version (If Applicable):** any

### Example Application

- https://github.com/mgm7734/multi-proj

**Comment by matrei** [comment]
I think, if you are using `log` in you plugin, you should add `implementation 'org.grails:grails-logging'` to the plugin dependencies.

**Comment by mgm7734** [comment]
That should be in the docs, like https://guides.grails.org/grails-multi-project-build/guide/index.html

**Comment by mgm7734** [comment]
bye
