### ISSUE TITLE
Java 21

### ISSUE THREAD

**Issue by kovelo** [grails/grails-core#13522]
### Feature description

Where Is Java 21 at on the roadmap?

**Comment by lifeweaver** [comment]
A good question, given the [Grails Future](https://grails.org/blog/2024-06-07-grails-future.html) blog post, I wonder if any existing roadmap is still valid?

**Comment by sdelamo** [comment]
We are working towards [Grails 7 ](https://github.com/orgs/grails/projects/3)which will raise Java baseline to 17 and you will be able to use Java 21.
