### ISSUE TITLE
Updating to latest version of Micronaut or remove the Micronaut Integration

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#13549]
see: https://github.com/orgs/grails/discussions/13517

**Comment by sdelamo** [comment]
There is a work-in-progress PR currently updating to Micronaut 4.5.3 https://github.com/grails/grails-core/pull/13545

**Comment by codeconsole** [comment]
https://github.com/orgs/grails/projects/3?pane=issue&itemId=72248530

**Comment by codeconsole** [comment]
Remove: https://github.com/grails/grails-core/pull/13685

**Comment by jamesfredley** [comment]
Documentation will point Grails users who want to use Micronaut in Grails to https://micronaut-projects.github.io/micronaut-spring/latest/guide/#springBootStarter
