### ISSUE TITLE
Update GORM for org.hibernate:hibernate-core-jakarta:5.6.15.Final

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#13550]
see: https://github.com/orgs/grails/discussions/13521

The latest conversations have been for development to begin around org.hibernate:hibernate-core-jakarta:5.6.15.Final and see how well it will play with Spring Framework 6.1.11 and Spring Boot 3.3.1 within GORM for Grails 7. Whatever functions and is the simplest path is likely what will ship in with Grails 7.

Grace has org.hibernate:hibernate-core-jakarta:5.6.15.Final with springBootVersion=3.0.13, springVersion=6.0.22 and groovyVersion=4.0.22

https://github.com/graceframework/grace-data-hibernate

**Comment by jamesfredley** [comment]
@basejump does your team still have time to take a look at this?

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-data-mapping/pull/1810

https://github.com/grails/gorm-hibernate5/pull/878

**Comment by jamesfredley** [comment]
https://github.com/grails/gorm-mongodb/pull/751

**Comment by basejump** [comment]
@jamesfredley sorry, I missed your ping above. We are coming off a few major fires/scrambles we had over the last 6 or so weeks. It looks like you made some major progress, nice work! Let me know what current status is and will see if we can help.

**Comment by jamesfredley** [comment]
@basejump grails-data-mapping, gorm-hibernate5 and gorm-mongodb are each pretty close.  There are outstanding failing tests which are documented in an issue or a few issues on each repository, if your team wants to take a look.  Some of these issues are waiting on grails plugins to be updated to Grails7 and that should be noted on the issue, such as grails-spring-security-rest, etc.

**Comment by jamesfredley** [comment]
Outstanding failing tests:  https://github.com/grails/gorm-hibernate5/issues/879

**Comment by jdaugherty** [comment]
All remaining grails-data-mapping & gorm-hibernate5 tests except the RxJava ones are fixed.
