### ISSUE TITLE
Make `grails-gradle-plugin` independent of `grails-core`

### ISSUE THREAD

**Issue by matrei** [grails/grails-core#13560]
### From slack discussions:
*davydotcom*:
but really, this should have never been split up like this
now grails-gradle includes grails-core which is groovy 4 now but gradle doesnt like groovy4
and it ONLY needs 2 files from grails-core
Environment.groovy and BuildSettings.groovy
those should be put into a grails-build project
as java classes
no groovy at all
and then we can eliminate the entire grails-core graph from the gradle plugin
it used to need all of it because gsp compile was inline
but i forked that a while ago so it can have an independent classpath for the compiler
oh btw EVERY plugin will need released
and frankly, im fine with that

**Comment by davydotcom** [comment]
i figured some things out on this. the `grails-bootstrap` already is excluding most. if we change groovy to an `implentation` configuration and don't export it with this plugin, we can let gradle use its version just fine.

**Comment by davydotcom** [comment]
Fixed grails-bootstrap for the gradle plugin in #13564
