### ISSUE TITLE
Standardization of groovy-joint-workflow.yml - Build and install groovy (no docs)

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-core#13596]
### Issue description

9 repositories with the groovy joint workflow

- https://github.com/grails/grails-data-mapping
- https://github.com/grails/grails-core
- https://github.com/grails/grails-views
- https://github.com/grails/grails-testing-support
- https://github.com/grails/grails-gsp
- https://github.com/grails/grails-async
- https://github.com/grails/gorm-neo4j
- https://github.com/grails/gorm-mongodb
- https://github.com/grails/gorm-hibernate5 - 9.0.x branch calls publishToMavenLocal instead of install from groovy-joint-workflow.yml

**Comment by jamesfredley** [comment]
@matrei I will be glad to standardize this across these 9 repos.  Do you have an opinion on which approach to use?

**Comment by jamesfredley** [comment]
The above details are not entirely relevant, since `install` is being called on the `groovy` build, which does not call `publishToMavenLocal`.   

The above details may still be relevant for some other purpose.

`groovy-joint-workflow.yml` should likely call `publishToMavenLocal` on the groovy build in all 9 repositories.

**Comment by matrei** [comment]
@jamesfredley Also, `mavenLocal()` must be among the repositories, preferably first. It is not ideal to have `mavenLocal()` in the build files, so I would suggest that we remove it from the build file and add it with a step in the github worflow.
