### ISSUE TITLE
Grails 7: remove org.grails:grails-web-sitemesh from grails-plugin-controllers

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-core#13623]
### Issue description

https://github.com/grails/grails-core/blob/7.0.x/grails-plugin-controllers/build.gradle 

references org.grails:grails-web-sitemesh:$gspVersion which appears to be retired, based on last snapshot from 2023 and the code being removed from [grails-gsp](https://github.com/grails/grails-gsp).

**Comment by codeconsole** [comment]
I believe the idea at the time was to limit some [circular dependencies ](https://github.com/grails/grails-core/commit/ae5144162f7660e64df85fcaf4bc1ea73bffcae4), but in my option grails-controllers should never depend on sitemesh because using a controller should not even require gsp.
