### ISSUE TITLE
Grails 7: Update github workflow git user and email on all repositories

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-core#13697]
GIT_USER_NAME: 'grails-build'
GIT_USER_EMAIL: '[grails-build@users.noreply.github.com](mailto:grails-build@users.noreply.github.com)'

COMMIT_EMAIL: ${{ env.GIT_USER_EMAIL }}
COMMIT_NAME: ${{ env.GIT_USER_NAME }}

Example:  https://github.com/grails/grails-data-mapping/blob/9.0.x/.github/workflows/release.yml

**Comment by jamesfredley** [comment]
The following have already been updated:

https://github.com/grails/grails-doc
https://github.com/grails/gorm-hibernate5
https://github.com/grails/grails-database-migration
https://github.com/grails/gorm-mongodb
https://github.com/grails/grails-async
https://github.com/grails/grails-plugins-metadata
https://github.com/grails/scaffolding
https://github.com/grails/geb
https://github.com/grails/grails-forge
https://github.com/grails/grails-views
https://github.com/grails/grails-wrapper
https://github.com/grails/grails-async
https://github.com/grails/grails-gsp

**Comment by jdaugherty** [comment]
The majority of the repositories have been done as part of the grailsPublish rework.  The following need updated still: 

https://github.com/grails/grails-spring-security-oauth2
https://github.com/grails/grails-spring-security-ui
https://github.com/grails/gorm-docs
https://github.com/grails/grails-spring-security-cas
https://github.com/grails/elasticsearch-grails-plugin
https://github.com/grails/gorm-docs
https://github.com/grails/grails-testing-support
https://github.com/grails/grails-quartz

**Comment by jdaugherty** [comment]
@codeconsole completed this over the weekend
