### ISSUE TITLE
Fix bom generation 

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13753]
The following introduces a lot of confusion and adds an unnecessary check

https://github.com/grails/grails-core/blob/7db9a62b1d12590f9b2a64dd57a4dcf32e2cee78/grails-bom/build.gradle#L95-L99

grails-gradle-plugin should not be part of plugin.properties in the first place 

https://github.com/grails/grails-core/blob/7db9a62b1d12590f9b2a64dd57a4dcf32e2cee78/grails-bom/plugins.properties#L4

Also, it is bad practice to have to add exclusions this way:

https://github.com/grails/grails-core/blob/7db9a62b1d12590f9b2a64dd57a4dcf32e2cee78/grails-bom/build.gradle#L49-L68

The reason for this should be addressed. 

[Current bom](https://repo.grails.org/artifactory/core/org/grails/grails-bom/7.0.0-SNAPSHOT/grails-bom-7.0.0-20241014.150731-91.pom)

**Comment by matrei** [comment]
> grails-gradle-plugin should not be part of plugin.properties in the first place

That is another issue. #13737 sets the correct `groupId`.

**Comment by codeconsole** [comment]
@matrei why does it have the wrong `groupId` in the first place?

**Comment by matrei** [comment]
> why does it have the wrong groupId in the first place?

@codeconsole Looks like an oversight, as it's the only artifact in plugins.xml not using org.grails.plugins.

**Comment by codeconsole** [comment]
> @codeconsole Looks like an oversight, as it's the only artifact in `plugins.xml` not using `org.grails.plugins`.

@matrei what is the best solution for this? It isn't a Grails plugin so it should stay `org.grails`, right?
Is this just a matter of moving the version from plugins.properties?

Please see my PR. Will that fix it?

https://github.com/grails/grails-core/pull/13755
