### ISSUE TITLE
Confirm scaffolding core is being resolved

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13759]
In 6.x. only, fields 5.1.x scaffolding-core old should be resolved by fields and fields should be resolved by the scaffolding plugin.

scaffolding-core is not needed in 6.x because @jamesfredley moved the code from the no longer active repository.

@jdaugherty reported having an issue with 6.2.1/5.1.x and we need to confirm he was able to get things working without having to add the import for scaffolding-core.  If not, scaffolding-core should be added as an api dependency to fields, immediately merged up to 6.x and then removed in 6.x.

**Comment by jamesfredley** [comment]
It looks like fields:5.0.0+ moved scaffolding-core from a compile to a runtime dependency.

https://mvnrepository.com/artifact/io.github.gpc/fields/5.0.0-RC2

This issue only arises if you are using scaffolding-core classes in your code and need it at compile time.

**Comment by jdaugherty** [comment]
@jamesfredley is correct. I was using these classes in the code so I had to add it.  If you aren't using them, it works without issue in 6.2.1

**Comment by jamesfredley** [comment]
https://github.com/gpc/fields/pull/371#event-14741449419
