### ISSUE TITLE
Make Grails Bom extend Spring Boot Bom

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13785]
Since we removed Micronaut and Grails is tied to Spring Boot.  The Grails bom should extend the Spring Boot bom.  That way any versions recommended and tested by the Spring framework will be inherited by the Grails bom.

Versions can also be overridden in the Grails Bom if they need to be newer or held back, but it is a good starting point for for the developer for any dependencies we are currently not using.

https://github.com/grails/grails-core/blob/ba4887816997713d7bf86a4d1b27207f02c307a3/grails-bom/build.gradle#L1-L12

https://docs.spring.io/spring-boot/gradle-plugin/managing-dependencies.html

https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/

https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/3.3.4/spring-boot-dependencies-3.3.4.pom

**Comment by matrei** [comment]
I think this is a good idea!

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/pull/13787
