### ISSUE TITLE
Grails 7: `grails-bom` snapshots not published

### ISSUE THREAD

**Issue by matrei** [grails/grails-core#13800]
### Expected Behavior

`grails-bom` snapshot should be published to repo.grails.org

### Actual Behaviour

https://github.com/grails/grails-core/actions/runs/11466775686/job/31908770468
https://ge.grails.org/s/chb5k3g2v2wgq/timeline#lulthr2ujy2ia
```console
> Task :grails-bom:publish UP-TO-DATE
```

### Version

7.0.0-SNAPSHOT

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/pull/13804
