### ISSUE TITLE
6.2.2 sdkman not available on  Mac OS X aarch64

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13870]
Not avalable via sdkman
```
% sdk list grails
Available Grails Versions
================================================================================
 > * 6.2.1               4.0.8               3.1.13              2.3.11         
   * 6.2.0               4.0.7               3.1.12              2.3.10         
     6.1.2               4.0.6               3.1.11              2.3.9          
     6.1.1               4.0.5               3.1.10              2.3.8          
     6.1.0               4.0.4               3.1.9               2.3.7          
     6.0.0               4.0.3               3.1.8               2.3.6          
```

**Comment by jeffscottbrown** [comment]
FYI... I think this may only apply to Apple Silicon.

**Comment by jeffscottbrown** [comment]
https://gist.github.com/jeffscottbrown/0120eb4babb405830b7302c29bb7d822 was on an Intel Mac.  On M1 Mac I don't think 6.2.2 is currently available via SdkMan.

**Comment by jdaugherty** [comment]
See #13877 so we can change the cli to use a different version of java and thus build with newer versions of graalvm for the cli

**Comment by jdaugherty** [comment]
#13877 is not needed.  It's not worth the complexity to pass the java version since we already have to maintain the java versions in the grails-forge project.  I opened https://github.com/grails/grails-forge/pull/433 to use a default version and not the graalvm version.

**Comment by codeconsole** [comment]
actually, that wouldn't have worked because Spring went from 8 > 17

**Comment by jdaugherty** [comment]
This is now complete
