### ISSUE TITLE
GRAILS-8741: Create Alias In Detached Criteria

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#1727]
Original Reporter: nguyen.lenam
Environment: Not Specified
Version: 2.0 final
Migrated From: http://jira.grails.org/browse/GRAILS-8741

**Comment by graemerocher** [comment]
Although don't use of `createAlias` is not supported, we have added the ability to define an alias during detached criteria construction.

So the following is now valid:

```
        def saleCriteria = new DetachedCriteria(Sale).build {
            employee {
                region('r')
            }

        }.projections {
            groupProperty('r.continent')
            rowCount()
        }
```

I believe this largely solves the requirement of this issue.

**Comment by joaoneves** [comment]
How can I use a CriteriaSpecification.LEFT_JOIN using this notation?
