### ISSUE TITLE
GRAILS-3394: Scaffolding does not work for domain class called "Owner"

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#2033]
Original Reporter: pledbrook
Environment: Not Specified
Version: 1.0.3
Migrated From: http://jira.grails.org/browse/GRAILS-3394

**Comment by houbie** [comment]
This problem is back in grails 3.x: the edit page for an existing 'Owner' instance is broken.
This means that the petclinic sample project cannot be ported to grails 3

**Comment by graemerocher** [comment]
Have you partially ported pet clinic to provide an example that reproduces the issue?

**Comment by houbie** [comment]
I investigated a little further. The problem is not the domain class but the links in the show page:
        `<g:link resource="${owner}">test</g:link>`
renders the closure's owner:
`http://localhost:8080/users_ivo_dev_java_grails_grails3_grails_app_views_index_gsp%24_run_closure2%40d9ed8a2`
