### ISSUE TITLE
GRAILS-8803: validate() always returns true when @Validateable class is nested or embedded in domain object

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#2088]
Original Reporter: pclewis
Environment: Not Specified
Version: 2.0.1
Migrated From: http://jira.grails.org/browse/GRAILS-8803

{code:title=src/groovy/ValidateableObject.groovy}
@grails.validation.Validateable
class ValidateableObject {
	static constraints = { property(nullable: false, blank: false, matches: /test/) }
	String property
}
{code}

If you only have this, {{new ValidateableObject().validate()}} returns false.

If you add this domain class:

{code:title=grails-app/domain/DomainObject.groovy}
class DomainObject {
        ValidateableObject vo
        static embedded = ['vo']
}
{code}

Now {{new ValidateableObject().validate()}} always returns true.

If you trigger a class reload while the app is running, {{.validate()}} will begin to work again.

This also occurs if you define the class as a nested class inside of a domain object, regardless of {{embedded}} and {{@Validateable}}.

The issue does not occur if you embed a {{List<ValidateableObject>}}.

I am using the mongodb plugin in my app and the test but I am not sure if it's relevant.

**Comment by Schlogen** [comment]
Can't reproduce this on 3.1.9
