### ISSUE TITLE
GRAILS-8061: beforeValidate didn't get called in cascade validation

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#2274]
Original Reporter: kcheang
Environment: Not Specified
Version: 1.3.7
Migrated From: http://jira.grails.org/browse/GRAILS-8061

I have two classes: Parent and Child.

     class Parent {
       static hasMany = [children:Child]
     }
     
     class Child {
       static belongsTo = [parent:Parent]
     
       String name
     
       def beforeValidate() {
         name = 'hard coded in beforeValidate'
       }
     }

I use the following code to create a parent instance in ParentController.

     def save = {
       def parentInstance = new Parent(params)
       parentInstance.addToChildren(new Child(name:params.name))
       if (parentInstance.save(flush: true)) {
         ...
       }
       else {
         ...
       }
     }

The child instance will get created with the name passed from HTTP parameter instead of the string hard coded in the beforeValidate() method.

**Comment by jeffbrown** [comment]
I am wondering if we can put the beforeValidate handling inside of the validate method.  That will simplify a number of things and eliminate some duplicate code.

**Comment by tcrossland** [comment]
May be related to https://jira.grails.org/browse/GRAILS-11814

**Comment by graemerocher** [comment]
I implemented this in `HibernateDomainClassValidator` for the moment, this fixes it for GORM for Hibernate, but clearly the issue remains in the rest of the implementations. It is harder to fix generally due to how the Grails core and GORM link together at an API level, and like @jeffbrown said it would be better long term to rework this so all the logic happens in the `validate` method for `GormValidationApi`, but that is a much bigger job.
