### ISSUE TITLE
GRAILS-3086: actionSubmit tags retains default action URL in address bar

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#2550]
Original Reporter: hippyod
Environment: JDK 1.6_03, Vista
Version: 1.0.3
Migrated From: http://jira.grails.org/browse/GRAILS-3086

The predicted behavior for the following code should be to print 'success' to the console and browser after pressing the submit button.  This does work as expected, rendering 'success' in both places, but the url in the location bar reads "http://localhost:8080/test/test/failed".

{noformat}

class TestController {

    def defaultAction = 'failed'

    def failed = {
        println 'failed'
        render('failed')
    }

    def success = {
         println 'success'
         render('success')
     }
 
     def test = {}

}

Test.gsp:

    <g:form controller="test">
        <g:actionSubmit name="testButton" value="Submit" />
    </g:form>
{noformat}

Adding the success action to the form tag sets the url correctly in the browser's location bar.  Also, entering the 'failed' url in location bar correctly works as expected.  Tests with multiple actionSubmit tags with different actions will yield similar results (i.e. the original action will execute, but the location bar will be set to the forms expected url,  overriding the actionSubmit's).

There was other behavior reported and observed where action's were unable to execute in this scenario, but I have been unable to replicate that at this time, and redirect's from the original action behave exactly as expected regardless.  Therefore, I left the priority as 'major'.

**Comment by chuck-wood** [comment]
FYI, this issue seems to be combining with a recent browser update and tons of JavaScript to actually cause some of my `actionSubmit`s to cease working for no apparent reason. Following the workaround at http://stackoverflow.com/questions/12922724/grails-actionsubmit-url fixes the issue.

In brief, it consists of adding `onclick="this.form.action='${createLink(action:'`_action_`')}';" to the input.

**Comment by philboeselager** [comment]
The workaround given by @chuck-wood also works for `actionSubmitImage` (Grails 2.5.6).
