### ISSUE TITLE
Grails 3.0 - Controller actions not reloaded?

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#3355]
I have a very simple controller:

````
class PersonController{
    def test() {
        render 'hello'
    }
}
````

When I run the app, the text 'hello' is displayed. If I now change the text to 'bye' when the app is running, I see that the controller is recompiled, but the text is not updated.

Java version on MacOS:
````
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
````

**Comment by graemerocher** [comment]
Can you clarify how you are running the app? Via Gradle?

**Comment by bodiam** [comment]
I run the Application.main through IntelliJ, not using Gradle.

**Comment by graemerocher** [comment]
You need to make sure you pass `-noverify` as you have to disable the Java verifier to enable the reloading agent

**Comment by bodiam** [comment]
Ah! I didn't know I had to do that. That works indeed!

**Comment by bodiam** [comment]
Thanks!
