### ISSUE TITLE
GRAILS-9521: Attributes for options generated by g:select

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#3360]
Original Reporter: krakonos
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GRAILS-9521

It would nice to be able to add attributes (e.g., custom {{data-}} attributes) to {{option}} elements generated by {{g:select}} taglib.

It can be achieved by adding something like this in FormTagLib.groovy

{noformat}
def optionArgs = attrs.remove('optionArgs')
...
if (optionArgs) {
    optionArgs.each { key, val ->
        writer << " ${key}='${val(el)}'"
    }
}
{noformat}

**Comment by jkolobok** [comment]
+1

**Comment by vonovak** [comment]
I'll make a PR for this

**Comment by vonovak** [comment]
The PR is up. Will document it when it's certain it'll be merged.

BTW. I noticed there is an `optionDisabled` parameter in the g:select tag which is undocumented. Moreover, it works only if the `optionKey` param is passed to g:select - which is an optional param. If you'd like, I could take a look at that too..

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues
