### ISSUE TITLE
Mutable JSONElement returned by grails.converters.JSON#parse(HttpServletRequest) should always be cached

### ISSUE THREAD

**Issue by rgoldberg** [grails/grails-core#3769]
`grails.converters.JSON#parse(HttpServletRequest)` returns a mutable `JSONElement`.

In Grails 2.5.0, it caches the `JSONElement`, unless the request does not have body.  If there is no body, however, it returns a newly constructs mutable empty JSONObject on every call, since it doesn't cache it.

This means that `request.JSON` behaves differently depending on whether the `request` has a body or not.  Modifying `request.JSON` for a non-empty body `request` will remember the modifications across multiple calls to `request.JSON`; whereas modifying `request.JSON` for an empty body `request` will "forget" the modifications.

The following version of the method makes everything consistent by always caching the returned `JSONElement`, regardless if the body is empty or not (the beginning of the method is the same as the released 2.5.0 version; there's a comment in the code, above which the code is unchanged, below which the code is changed):

```
    public static Object parse(HttpServletRequest request) throws ConverterException {
        Object json = request.getAttribute(CACHED_JSON);
        if (json != null) {
            return json;
        }

        String encoding = request.getCharacterEncoding();
        if (encoding == null) {
            encoding = Converter.DEFAULT_REQUEST_ENCODING;
        }
        try {
            PushbackInputStream pushbackInputStream = null;
            int firstByte = -1;
            try {
                pushbackInputStream = new PushbackInputStream(request.getInputStream());
                firstByte = pushbackInputStream.read();
            } catch (IOException ioe) {}

            // code has only been changed from here down
            if (firstByte == -1) {
                json = new JSONObject();
            }
            else {
                pushbackInputStream.unread(firstByte);
                json = parse(pushbackInputStream, encoding);
            }
            request.setAttribute(CACHED_JSON, json);
            return json;
        }
        catch (IOException e) {
            throw new ConverterException("Error parsing JSON", e);
        }
    }
```

**Comment by rgoldberg** [comment]
I saw that this was reopened & closed.  Is there anything that I must do?

Is this still scheduled for release with Grails 2.5.1?

Is there an ETA for Grails 2.5.1?

Thanks for all the work on Grails.

**Comment by jeffbrown** [comment]
> I saw that this was reopened & closed. Is there anything that I must do?

No.  It was re-opened by accident so I recluse it.
