### ISSUE TITLE
GRAILS-8951: Auto reloading does not work when running grails console with -D param

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#5204]
Original Reporter: jojopad
Environment: Not Specified
Version: 2.0.1
Migrated From: http://jira.grails.org/browse/GRAILS-8951

When running the grails console with any system property parameter (-D), the auto reloading feature does not work anymore. To replicate the problem, follow these steps:

1. Run grails console with the -D param. You can use any system property, for example:

grails -Dfoo=foo

2. Run the application using run-app command

grails> run-app

3. Change any codes in the application.

4. Grails console does not show any log message telling that the code change has been compiled. The changes do not get applied also in the running application.

Only after removing the -D param when running Grails console, the auto reloading feature works again.

I have tested this behavior only with Grails 2.0.1.

**Comment by graemerocher** [comment]
related to old build system

**Comment by johannes** [comment]
(Please don't write @Johannes as that will subscribe me, while I love being a hero :-D)

**Comment by graemerocher** [comment]
@johannes I didn't actually write to you here, we migrated our issue tracking system from JIRA to Github using an automated script, it just so happened that the script including comments that referenced your name :D

**Comment by rick** [comment]
Ah.  That explains why I got cc:d as well ;-)  Well, congratulations on getting away from Jira.

Party on.  :tada: :confetti_ball: :metal: :guitar:
