### ISSUE TITLE
Unable to find Grails Plugin Mandrill

### ISSUE THREAD

**Issue by tylerevans** [grails/grails-core#580]
Im trying to add the following grails plugin to my BuildConfig

https://grails.org/plugin/mandrill

However it says cannot find the plugin. I can however see the plugin in the Repo:
https://repo.grails.org/grails/plugins/org/grails/plugins/mandrill/

I've also tried adding this mavenRepo <url> directly to the buildconfig, but still no luck.

Is it possible to find out what the issue is.

Im adding:
compile ":mandrill:0.5"
to my "dependencies".

**Comment by graemerocher** [comment]
If you are referring to Grails 3.0 then the plugin is not yet ported to Grails 3.0, if you are referring to Grails 2.x please ensure your repositories are configured correctly, otherwise please ask usage questions at http://stackoverflow.com/tags/grails.

**Comment by tylerevans** [comment]
Thanks. I am currently using Grails 2.2.4.

I am fairly sure my repository is configured correctly as I'm using other plugins 
(eg: runtime 'mysql:mysql-connector-java:5.1.22')

Is there anything else I can check? How can I confirm I'm connected to the correct repo.

**Comment by graemerocher** [comment]
Check that you have the Grails central repository in your repositories:

    mavenRepo "https://repo.grails.org/grails/core/"

**Comment by graemerocher** [comment]
See this answer http://stackoverflow.com/a/23594402/259167
