### ISSUE TITLE
gradle run is missing image-resources. grails run works

### ISSUE THREAD

**Issue by anderskristian** [grails/grails-core#581]
I have placed a file  src/main/resources/public/app/assets/image/logo_order_page.png
Starting application from shell

grails run  --> can load image
(from http://localhost:8080/helloworld/app/assets/image/logo_order_page.png)

gradle run --> CANNOT load images

I have placed the directory "asset" under "app" in order NOT to conflict with the Grails ASSET system.

When I run grails run (after the gradle run) the system will download additional jars .....

Total time: 7.773 secs
Download https://repo.grails.org/grails/core/org/grails/grails-plugin-testing/3.0.0.RC3/grails-plugin-testing-3.0.0.RC3.pom
Download https://repo.grails.org/grails/core/org/grails/plugins/geb/1.0.0/geb-1.0.0.pom
Download https://repo.grails.org/grails/core/org/grails/grails-test/3.0.0.RC3/grails-test-3.0.0.RC3.pom
Download https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-test/2.4.3/groovy-test-2.4.3.pom
Download https://repo.grails.org/grails/core/org/springframework/spring-test/4.1.6.RELEASE/spring-test-4.1.6.RELEASE.pom
Download https://repo.grails.org/grails/core/org/grails/grails-plugin-testing/3.0.0.RC3/grails-plugin-testing-3.0.0.RC3.jar
Download https://repo.grails.org/grails/core/org/grails/plugins/geb/1.0.0/geb-1.0.0.jar
Download https://repo.grails.org/grails/core/org/grails/grails-test/3.0.0.RC3/grails-test-3.0.0.RC3.jar
Download https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-test/2.4.3/groovy-test-2.4.3.jar
Download https://repo.grails.org/grails/core/org/springframework/spring-test/4.1.6.RELEASE/spring-test-4.1.6.RELEASE.jar
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:bootRun
true
Grails application running at http://localhost:8080

I now see that 
gradle bootRun WORKS !!!!!!!!

**Comment by graemerocher** [comment]
You should always use `bootRun`

**Comment by anderskristian** [comment]
Chapter 5.5.2 specifies that command "run-app" is "run" in Gradle.
This could be changed to bootRun

**Comment by graemerocher** [comment]
Agreed, pull requests welcome

**Comment by anderskristian** [comment]
I will try to see if I can manage that :-)
