### ISSUE TITLE
Grails createLink (from grailsLinkGenerator) does not generate link following URLMappings with format param.

### ISSUE THREAD

**Issue by volnei** [grails/grails-core#589]
When generating a link with format param the format was not included in the url as file extension.

To reproduce
```
static mappings = {
"/$controller/$action?/$id?(.$format)?"
}
```

```
<g:createLink controller="book" action="list" params="[format:'json']"/>
```

The link expected is "/book/list.json" but link generated is "/book/list?format=json".

Ps. Would be nice if it had as attachments here.

(Grails 3.0)

**Comment by graemerocher** [comment]
Github issues doesn't support attachments, please push an example app to a your repo on github if you want.

**Comment by volnei** [comment]
Done, https://github.com/volnei/link
Just run the app and navigate to http://localhost:8080

Thank you
