### ISSUE TITLE
Index core repository

### ISSUE THREAD

**Issue by xmiquel** [grails/grails-core#590]
First of all, this is not an issue, but I think it's desirable and effordless to index this virtual repository.
From IntelliJ it's not possible to index the remote repository https://repo.grails.org/grails/core.
Googling about it, i've seen it seems to be just a matter of indexing this virtual repository in artifactory.
Thanks in advance and congratulations for this BIG release.

**Comment by graemerocher** [comment]
Do you have links to tutorials on how to index it?

**Comment by xmiquel** [comment]
Hi Graeme,

Maybe this can help.


http://www.jfrog.com/confluence/plugins/servlet/mobile#content/view/25067958





Thanks



—
Xavi

**Comment by eranbl** [comment]
Hi Graeme,

Although not much different in content , this is a more up to date link to the Artifactory Maven Indexer documentation:

http://www.jfrog.com/confluence/display/RTF/Exposing+Maven+Indexes

Eran

**Comment by graemerocher** [comment]
Looks like with Artifactory Online this can only be done via a REST call:

http://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-CalculateMavenIndex

The UI for it is not exposed.

**Comment by graemerocher** [comment]
I issues the necessary REST API calls to have the indexes created:

     Maven index refresh for repositories '[core]' has been accepted.

 it might take a while we shall see

**Comment by aremick** [comment]
Looks like this needs to be run again and possibly added to the release process?

**Comment by ejaz-ahmed** [comment]
Having same error with grails 3.1.0.M1. Probably need to repeat the steps once more

**Comment by 1uk5wa** [comment]
Hi,

I came across the same problem with grails-3.1.0. It looks like it's not working again. Thanks in advance for sorting this out.

**Comment by graemerocher** [comment]
I have reindexed the repo, it may take a while. I also added it to our build process:

https://github.com/grails/grails-core/commit/063fb21a057464c6e5a8318b60eccea5fc1e6a2f

So it should happen automatically from now. Thanks.

**Comment by 1uk5wa** [comment]
It's working now, thanks
