### ISSUE TITLE
@Transactional class annotation negates @GrailsCompileStatic and @GrailsTypeChecked

### ISSUE THREAD

**Issue by thobson** [grails/grails-core#591]
Given 
```java
@Transactional
class MyService {

  @GrailsTypeChecked // or @GrailsCompileStatic
  def doSomething() {
    String name = missingVariable
  }

  @Transactional(readOnly = true)
  def doSomethingElse() {
    int x = 1
  }
}
```
The GrailsTypeChecked // or GrailsCompileStatic annotations have no effect. It seems the Transactional class level annotation is the problem. Transactional annotations at method level only don't exhibit this behaviour

**Comment by burtbeckwith** [comment]
This was also reported here: https://stackoverflow.com/questions/29312070/grailss-transactional-will-disable-the-compilestatic-annotation

**Comment by jeffbrown** [comment]
Will get it straightened out.  Thanks for the feedback.
