### ISSUE TITLE
Inline plugin reload problem

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#592]
BootRun can not detect code changes in inline plugins, such as modifications in controllers, views, assets.

**Comment by todoubaba** [comment]
It seems that Spring-loaded 1.2.4 will resolve this problem, https://github.com/spring-projects/spring-loaded/issues/70

**Comment by graemerocher** [comment]
It may be that long term we integrate with Gradle's continuous build feature and add Spring loaded support, for watching JARs, but right now the infrastructure to support that is not there (until Gradle 2.5 and Spring Loaded 1.2.4)

In the meantime I have added support for reloading multi-project builds in the IDE (since IDEs don't package JAR files)

**Comment by todoubaba** [comment]
@graemerocher  Both Gradle 2.5 and Spring Loaded 1.2.4 are released, can this issue be fixed now?

**Comment by todoubaba** [comment]
@graemerocher Sorry for my ignorance. What do you mean "Note this is not an issue when you run a Grails project from the IDE, as an IDE like Intellij will not build the JAR files, but instead place the classes of the subprojects on the classpath directly."?
I can only run the multi-project by the commands in the Intellij's "gradle projects" panel. Running the Application.groovy in init folder results an exceptions: "Plugin [xxx] must specify a version!"

**Comment by graemerocher** [comment]
The "Plugin [xxx] must specify a version!" error is fixed in newer versions of Grails

**Comment by todoubaba** [comment]
I am working with 3.0.7, I'll try version 3.0.8.

**Comment by todoubaba** [comment]
There are many problems when run app from Application.groovy. Such as "region.factory_class" needs to be 
```
region:
    factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
```
Grails also can not resolve view in plugins. Fortunately, bootRun still working.

**Comment by longwa** [comment]
@graemerocher Is there any workaround for this issue in 3.0.9? This is pretty much a show stopper for us as we have a large multi-project build and the application takes around 3 minutes to stop and restart.

I'm starting our application with `gradle run` if that matters.

**Comment by graemerocher** [comment]
@longwa you can run the app in the IDE, but yes we need to address this problem somehow

**Comment by graemerocher** [comment]
Experimental support for this is being added to 3.0.14. You have to enable exploded mode and then define your plugins within your `build.gradle` as follows:

    grails {
        exploded = true
        plugins {
            compile ":hibernate"
            compile project(':foo')
        }
    }

That will allow reloading of classes, i18n messages and GSPs within subprojects when using `grails run-app`
