### ISSUE TITLE
Referential integrity violation when using join tables with abstract/concrete classes

### ISSUE THREAD

**Issue by jeffastorey** [grails/grails-core#593]
```
abstract class A {
   static hasMany = [ b : B ]
   static mapping = {
     tablePerHierarchy false
   }
}

 class AChild extends A {
 }

abstract class B {
   static belongsTo = A
   static mapping = {
     tablePerHierarchy false
   } 
 }

class BChild extends B {
}   
```

I have some code that does

```
A a = new AChild()
a.b << new BChild()
a.save(flush:true)
```

This works as expected

Now, when I try to do

```
b.delete(flush:true)
```

This fails because of an referential integrity violation in the join table created between A/B. It looks like the first query by GORM as part of the delete is to do a delete from the B table, not the join table, and the join has a reference back to the B table by its id, which causes the violation.

```
delete from b where id=? and version=?
```

If I setup the relationship to use a foreign key instead of a join table, no problems.

**Comment by graemerocher** [comment]
What version of Grails please?

**Comment by jeffastorey** [comment]
2.5.0

**Comment by guramritpal-jft** [comment]
@graemerocher 
@jeffbrown    
  is this problem solved ....? or not.
                                                     Thanks
                                                       teamjft

**Comment by jeffbrown** [comment]
@guramritpal-jft I don't know, but could test.  The issue is still open.  Do you see something that suggests that the issue has been fixed?  Thanks for the feedback.

**Comment by guramritpal-jft** [comment]
@jeffbrown      Sure i'm working on this issue. i'll report soon

**Comment by jameskleeh** [comment]
This still happens in 3.x. Should the delete cascade to A because of the belongs to in B @graemerocher ?
