### ISSUE TITLE
Method where (grails.gorm.DetachedCriteria) dont work in traits (v3.0.1)

### ISSUE THREAD

**Issue by marciomunhoz** [grails/grails-core#596]
https://jira.grails.org/browse/GRAILS-12128
Method where (grails.gorm.DetachedCriteria) dont work in traits

**Comment by volnei** [comment]
+1

**Comment by graemerocher** [comment]
I thought I had fixed this, but it appears not, there is a more fundamental problem in Groovy with regards to traits and the use of builders. I have reported https://issues.apache.org/jira/browse/GROOVY-7456 which describes the issue. I am looking at workarounds right now to address this.
