### ISSUE TITLE
 Could not obtain current Hibernate Session on before method of an Interceptor

### ISSUE THREAD

**Issue by rafaelfelini** [grails/grails-core#600]
Exception raised when calling any method related to gorm on a domain class, in before method of an interceptor.

```
No Session found for current thread. Stacktrace follows:
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; 
nested exception is org.hibernate.HibernateException: No Session found for current thread
```

**Comment by mgkimsal** [comment]
not quite the same, but i see issues with 'redirect' calls inside interceptors that reference 'no session found' as well.  was waiting to see if anything happened on this before submitting a sep issue.

**Comment by rafaelfelini** [comment]
Anybody has a clue of where I can look at to try to solve this issue?

**Comment by volnei** [comment]
@rafaelfelini Have you tried with a new session?
```
Obj.withNewSession {
    // todo
}
```

**Comment by rafaelfelini** [comment]
@volnei Not in my case, because I am using Hibernate Filters and in some point between interceptors and controllers Grails is creating a new Hibernate Session.
So when I reach an action my Hibernate Filters are not enabled anymore, because de Hibernate Sessions as different.

**Comment by volnei** [comment]
@rafaelfelini Please... post the full stack trace if you can.

**Comment by graemerocher** [comment]
Please upload an example to github that reproduces the problem

**Comment by rafaelfelini** [comment]
Hi @graemerocher to see the problem just clone https://github.com/rafaelfelini/example and access http://localhost:8080/index
I created one controller, one interceptor and one domain.

**Comment by zyro23** [comment]
https://github.com/grails/grails-core/blob/master/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/mvc/UrlMappingsHandlerMapping.groovy#L65 interceptor autowiring does not look like it is enforcing any ordering (esp. reg. `OpenSessionInViewInterceptor` vs. `GrailsInterceptorHandlerInterceptorAdapter`)?

**Comment by graemerocher** [comment]
Could be..

**Comment by dpilafian** [comment]
For anyone who needs a temporary (albeit ugly) workaround until 3.0.2 is released, `response.setHeader("Refresh", "0; url=/signin")` seems to do the trick.  Example at: https://github.com/center-key/bookstore/blob/master/grails-app/controllers/org/centerkey/grails/security/SecurityInterceptor.groovy

**Comment by orubel** [comment]
I hate to ask this but this doesn't look like this was tested with 'after()' and it seems chain(),redirect(),forward() don't work when return false is set in Interceptor (see #9183)
