### ISSUE TITLE
Grails 2.4.4. null value in inList constraint throws exception

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#606]
I was trying different values on inList, and found that if null is in the list, when I start the app I get a weird exception. If null is not valid for inList it would be nice to have a specific message/exception for that to help detect the issue.

| Running Grails application
| Error 2015-04-04 14:14:24,594 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener - Error initializing the application: Error cr
eating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.Bea
nCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean prop
erty 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory
': Invocation of init method failed; nested exception is java.lang.NullPointerException
Message: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.
beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while
setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with nam
e 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
Line | Method
->> 262 | run in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
| 1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
| 615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^ 744 | run in java.lang.Thread

Caused by BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while sett
ing bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 's
essionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
->> 262 | run in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
| 1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
| 615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^ 744 | run in java.lang.Thread

Caused by BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.
NullPointerException
->> 262 | run in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
| 1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
| 615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^ 744 | run in java.lang.Thread

Caused by NullPointerException: null
->> 262 | run in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
| 1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
| 615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^ 744 | run in java.lang.Thread

**Comment by jeffbrown** [comment]
The NullPointerException is probably coming from https://github.com/grails/grails-data-mapping/blob/bcfa2ae2446d48b08fbe8cfb21fbba7ca6a29b6f/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/cfg/AbstractGrailsDomainBinder.java#L3104 where the domain binder is trying to figure out what the longest string in the list is.  That of course is easy enough to fix.  What is the use case for putting null in the list?  If you use nullable:true and then only put the non-nullable values in the list, does that work?  Thanks for the feedback.

**Comment by neoecos** [comment]
I found #630 related to this issue

**Comment by graemerocher** [comment]
No feedback provided
