### ISSUE TITLE
Grails 2.5 Respond Ambiguous Method Overloading

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#611]
This is related to #610 but not really the same thing.  #610 points out that in Grails 3.0.1 a controller cannot invoke a method like `respond([name: 'Jeff'])` because that will throw a runtime exception about ambiguous method overloading.  In Grails 2.5 that method call will work but a method call like `respond([name: 'Jeff'], status: 201)` will throw the ambiguous method overloading exception.

**Comment by hussainanjar** [comment]
When is 2.5.1 getting released ? We are facing this issue too.

**Comment by jeffbrown** [comment]
Some time in June.
