### ISSUE TITLE
Grails 2.4.4: RenderCollectionJson returns empty

### ISSUE THREAD

**Issue by littleiffel** [grails/grails-core#615]
I run into this issue in Grails 2.4.4 after upgrade from 2.3.11

https://jira.grails.org/browse/GRAILS-11892

Json rendering of List gives {empty:false} JSON. When I use toArray() on collection it works fine.

However as I use this in many places chaning everything to toArray is not a solution. Is this fixed in grails 2.4.5 or grails 2.5? Or does anyone know a workaround?

**Comment by hardyrex** [comment]
Hi,
moving the call of marshallers.addAll(getPreviouslyConfiguredMarshallers(JSON.class)); in the ConvertersConfigurationInitializers method: initJsonConfiguration below the block of marshallers.add calls solve the problem for me.

cheers hardy
