### ISSUE TITLE
Grails 3.0.0: Problem using @Rollback with integration tests and Spock

### ISSUE THREAD

**Issue by eugene-kamenev** [grails/grails-core#616]
Try to create a simple integration test like this:

```groovy
@Integration
@Rollback
class FinanceControllerSpec extends Specification {
    def setup() {
    }

    def cleanup() {
    }
    
    void "maximum of two numbers"(int a, int b, int c) {
        expect:
            Math.max(a, b) == c
        where:
            a | b | c
            1 | 3 | 3
            7 | 4 | 7
            0 | 0 | 0
    }
}
```
And it will fail with null pointer exception. If you delete annotations it will work fine, also I found that this happens when you are using Spock 'where' declaration.

**Comment by jeffbrown** [comment]
I expect the `Rollback` annotation is causing the problem because there isn't a transaction running in the integration test space.  Is `Rollback` the annotation that is causing the problem?

**Comment by jeffbrown** [comment]
This looks like an incompatibility between our `TransactionTransform` and what Spock generates for `expect/where` type test methods.  Will investigate.  Thanks for the feedback.

**Comment by eugene-kamenev** [comment]
@jeffbrown How do you think, can we have a workaround for now? Integration tests are very important.

**Comment by yamkazu** [comment]
The workaround is to use `@org.springframework.transaction.annotation.Transactional` instead of `@Rollback`.

related to: https://jira.grails.org/browse/GRAILS-12114

**Comment by graemerocher** [comment]
This seems like a bug in Spock to me, or maybe it is by design, but basically what Spock generates is:

    $transactionTemplate.executeAndRollback(new MathSpec.__spock_feature_0_1_closure2(this, this, b, c, a)); 

So it is essentially instantiating a new instance of the Spec which loses all local state as far as I can tell, I'm not sure what can be done about this. We need to ask a Spock expert. Maybe @pniederw has time to comment...

**Comment by pniederw** [comment]
Specs are always instantiated by `BaseSpecRunner#createSpecInstance`, and never by generated code. My best guess is a bad interaction with `TransactionTransform`.

**Comment by graemerocher** [comment]
@pniederw What I can see in the debugger is that in `BaseSpecRunner` the `currentInstance` and `sharedInstance` fields are different objects. The `currentInstance` object has the `transactionManager` property set hence no NPE occurs, but the `sharedInstance` object does not have this. I'm kind of stumped as to why the `sharedInstance` and the `currentInstance` point to different objects as from the code in `BaseSpecRunner#createSpecInstance` it seems they should be different objects unless something is calling `SpecificationContext#setSharedInstance` from somewhere else.

**Comment by graemerocher** [comment]
Yeah a workaround to this issue is placing this code in your `setup` method:

    def setup() {
        specificationContext.sharedInstance.transactionManager = transactionManager
    }

**Comment by graemerocher** [comment]
@pniederw This is the only way I could fix it for the moment as I don't understand what is going on and why the `sharedInstance` and the `currentInstance` differ:

https://github.com/grails/grails-core/commit/1b212da2071aae9948186817df7a4853598e747f#diff-f87e8a1222b58264b3d2056e39fb6086R318

There is some special case handling for Spock in the `TransactionTransform` that ensures they are set on both instances, for the moment it will have to do I guess

**Comment by pniederw** [comment]
`sharedInstance` exists once per spec class (execution) and holds `@Shared` fields. Getters/setters for `@Shared` fields delegate to `sharedInstance`, regardless what instance the getter/setter is called on. In `setupSpec` and `cleanupSpec`, `currentInstance == sharedInstance`. In feature methods, `currentInstance != sharedInstance`. Does this help?
