### ISSUE TITLE
Logback failure - Grails 3.0.1

### ISSUE THREAD

**Issue by budjb** [grails/grails-core#618]
I'm getting the following with the standard logback config when running tests with Grails 3.0.1.

```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 2: unable to resolve class grails.util.Environment
 @ line 2, column 1.
   import grails.util.Environment
   ^

Script1.groovy: 1: unable to resolve class grails.util.BuildSettings
 @ line 1, column 1.
   import grails.util.BuildSettings
   ^

Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.encoder.PatternLayoutEncoder
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
12 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:590)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:539)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:297)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:267)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:692)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:704)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:740)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:731)
	at groovy.lang.GroovyShell$parse.call(Unknown Source)
        <snipped>
```

It seems like the classpath isn't set correctly when the logback configuration is being loaded.

**Comment by jeffbrown** [comment]
I think the problem is that we have something in the compiler process which is initializing logback, which is bad.  We shouldn't be using the logger at compile time.  We had an AST transformation which was referencing GrailsUtil and that inadvertently caused logback to be initialized.  That was fixed with https://github.com/grails/grails-core/commit/88b510fcccaac1dbdccc0f44a5a557dd82e45d5e#diff-19901bf7d1fd48bacc4ad989029b74b1.  It may be that we have another case of the same sort of thing happening.  Will investigate.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
Is there any particular type of test which triggers the problem?

**Comment by budjb** [comment]
I am able to reproduce the issue with only unit tests.  If you'd like a working example, see my project at: https://github.com/budjb/grails-rabbitmq-native/tree/grails-3.0.x.

**Comment by jeffbrown** [comment]
I see the problem now.  The part you left out of the stack trace is the important bit.  It looks like you have an artefact handler (MessageConsumerArtefactHandler) which statically initializes a logger.  Your artefact handler is engaged by the compiler so logback has to be initialized during compilation, which is bad.

**Comment by budjb** [comment]
Aha! Sorry for leaving out the good stuff. I'll go ahead and close this issue and fix the issue my code.

**Comment by budjb** [comment]
Removing the logger did get rid of the error. I create loggers all over this codebase in the same manner (they're not static members, just as this one was not). Why are these not causing the same problem?

**Comment by jeffbrown** [comment]
Because most of the code in your codebase is not executed at compile time.  Artefact handlers are.

**Comment by budjb** [comment]
That makes sense. Given that the artefact handlers are executed at compile time, what then is the preferred method to use loggers in the artefact handlers?

**Comment by jeffbrown** [comment]
I don't know.  We probably need to come up with a recommendation around that though.  In your case I don't think you were even using the logger.

**Comment by budjb** [comment]
I was not, though I was at one point.  The code should have been removed but it also should not have caused an issue, at least as far as I was aware at the time.  Thanks for looking into this!
