### ISSUE TITLE
[Feature Request] Add local plugin configuration that does not get bundled.

### ISSUE THREAD

**Issue by budjb** [grails/grails-core#621]
With Grails 2.x, plugins were able to define a set of local configuration properties that did not get exported in the plugin's distribution.  This allowed a plugin to set runtime configuration for integration and functional tests that should only apply for those use cases, but not affect applications that use the plugin.

With Grails 3.0, this is no longer possible due to ```application.yml``` and ```application.groovy``` now being bundled in the distribution and automagically merged into the application configuration.  While the impact can be minimized by putting all of the plugin configuration into the test environment, ideally plugins should have the ability to define a local configuration that had no impact on other applications.

**Comment by srimajji** [comment]
:+1:

**Comment by graemerocher** [comment]
In Grails 3.1 the `application.yml` file is no longer bundled, whilst a `plugin.yml` file is bundled

**Comment by littleben93** [comment]
Please, update the documentation (section 18 Plugin). Now plugin.yml is mentioned only in "grails-app/conf/application.yml (renamed to plugin.yml)"

I think it would be better to describe this feature wider.
