### ISSUE TITLE
DetachedCriteria projections does not support groupProperty

### ISSUE THREAD

**Issue by rstevehole** [grails/grails-core#622]
The DetachedCriteria class does not include support for the groupProperty clause in projections like the criteria builder in createCriteria does. Using the domain model from the Grails bookFlow sample, the following code executed in the Grails console fails:

    DetachedCriteria criteria = new DetachedCriteria(Order).build {
        projections {
            groupProperty("person")
            items {
                sum("price")
            }
        }
    }
    criteria.list()

This fails with an "unimplemented method" fault on groupProperty. The equivalent query using a regular criteria (through createCriteria() or withCritieria()) works as expected.

**Comment by jeffbrown** [comment]
Where is the sample from which you got that code?

**Comment by jeffbrown** [comment]
I see now.  The domain model came from the sample, not the query code.

**Comment by zyro23** [comment]
ref: https://github.com/grails/grails-data-mapping/issues/60

**Comment by Schlogen** [comment]
Done by https://github.com/grails/grails-data-mapping/commit/bba5ead6498a93ec266d77c5cffeaf03823823c0
