### ISSUE TITLE
ConcurrentLinkedHashMap --> Caffeine when Java-8 based

### ISSUE THREAD

**Issue by ben-manes** [grails/grails-core#624]
When Grails transitions to requiring Java 8 please upgrade to [Caffeine](https://github.com/ben-manes/caffeine). The performance should be relatively the same and the per-instance memory usage should be smaller. 

[ConcurrentLinkedHashMap](https://code.google.com/p/concurrentlinkedhashmap/) changes will continue to be minimal, even more so now, and driven by requests from Java 6 users unable to upgrade.

**Comment by graemerocher** [comment]
@ben-manes So is Caffeine seen as the long term replacement for ConcurrentLinkedHashMap?

**Comment by ben-manes** [comment]
Yep, and imho also Guava's cache (but since I'm no longer at Google that's only my opinion). I still support both CLHM & Guava's, though. I am pretty happy with the [performance](https://github.com/ben-manes/caffeine/wiki/Benchmarks) improvements compared to the previous implementations.

**Comment by ben-manes** [comment]
Thanks @graemerocher! I think you forgot to save the changes to `DefaultRendererRegistry` as it uses CLHM and changes whitespace only.

**Comment by graemerocher** [comment]
@ben-manes will take a look, trying to piece Grails back together for Java 11 and
