### ISSUE TITLE
Spring security: unable to resolve class

### ISSUE THREAD

**Issue by hrenpopadesh** [grails/grails-core#628]
I am trying to add spring security to my grails app.
I am using GGTS:
Groovy/Grails Tool Suite 
Version: 3.6.4.RELEASE
Build Id: 201503100339
Platform: Eclipse Luna SR1 (4.4.2)

Grails: Grails2.4.4

In my BuildConfig.groovy file I have added the following:
in repositories: mavenRepo 'http://repo.spring.io/milestone'
in plugins: compile ':spring-security-core:2.0-RC4'
		compile ":mail:1.0.7"
		compile ":jquery-ui:1.10.4"
		compile ":famfamfam:1.0.1"
		compile ":spring-security-ui:1.0-RC2"

I have created User, Role controllers via s2-quickstart successfully, but the project now have errors in:

Description	Resource	Path	Location	Type
Groovy:unable to resolve class org.springframework.security.authentication.RememberMeAuthenticationToken	DefaultSecurityConfig.groovy	/MyProject/.link_to_grails_plugins/spring-security-core-2.0-RC4/grails-app/conf	line 19	Java Problem

I have 8 similar errors with:
import org.springframework.security.authentication.RememberMeAuthenticationToken
import org.springframework.security.core.context.SecurityContextHolder
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter
import org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices
import org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices
import org.springframework.security.web.authentication.switchuser.SwitchUserFilter
import org.springframework.security.web.context.HttpSessionSecurityContextRepository 

How to fix this problem?

**Comment by burtbeckwith** [comment]
Not a bug, try http://stackoverflow.com
