### ISSUE TITLE
src/main/resources/public files becomes corrupted in task processResources

### ISSUE THREAD

**Issue by anderskristian** [grails/grails-core#629]
I have two files in my src/main/resources/public/index.html and src/main/resources/public/pg.jpg
curl http://localhost:8080/index.html > index-run.html --> WORKS FINE
curl http://localhost:8080/pg.jpg > bg-run.jpg  -> Produces a corrupted file 

ll src/main/resources/public/bg.jpg bg-run.jpg 
-rw-r--r--  1 aka  staff  35027  9 Apr 12:27 bg-run.jpg
-rw-r--r--  1 aka  staff  19437  7 Apr 09:22 src/main/resources/public/bg.jpg

The corrupted file is much bigger than the source ...

I think Grails is trying to do some encoding... 
The same problems goes on font files like glyphicons-halflings-regular.eot

$ gradle clean bootRun  --> WORKS

$ gradle clean assemble
java -jar build/libs/helloworld-0.1.war --> http get will produce corrupted files !!!!
(a tomcat deployed version will also produce corrupted files ...)
(unzipping the war and seeing the file shows a corrupt file inside war)

**Comment by anderskristian** [comment]
I can see that gradle processResources is making directory
build/resources..
Here file main/public/bg.jpg has been copied. And it is already corrupted..

**Comment by sheehan** [comment]
I ran into the same thing. Probably the issue described here: https://issues.gradle.org/browse/GRADLE-1566

**Comment by anderskristian** [comment]
Thanks Sheehan
I get it .. It is a Gradle problem. It is not a Grails problem.
That makes a lot of sense. 
We could have a documentation place with "nice add ons" to build.gradle. 
My repairPublicFiles suggestion could obviously be made much better ...
So this issue can be closed down..

**Comment by anderskristian** [comment]
As written above it is a problem in Gradle.
I close this problem and will try to make a suggestion to documentation of build.gradle "add ons"

**Comment by sheehan** [comment]
It might be that grails should be excluding those files from filtering. I'm using your workaround in the meantime.
