### ISSUE TITLE
response.sendError creates empty page

### ISSUE THREAD

**Issue by hojerst** [grails/grails-core#631]
Calling `response.sendError 404` in a controller renders an empty page instead of the "404" mapping. 

note: setting loglevel to INFO hints to BasicErrorController in spring boot which trys to render "/error" which in turn is not found.

**Comment by graemerocher** [comment]
Have you tried `render status:404` ?

**Comment by hojerst** [comment]
yes, but this results also in an empty response.
The only solution, that works is:

```groovy
render status: 404, view: '/notFound'
```
however, this defeats the purpose of a central error mapping

**Comment by hojerst** [comment]
I added an app to demonstrate this error: https://github.com/hojerst/errorpagedemo
see especially [TestController](https://github.com/hojerst/errorpagedemo/blob/master/grails-app/controllers/errorpagedemo/TestController.groovy)
