### ISSUE TITLE
Controller beforeInterceptor is not called in grails 3.0.1

### ISSUE THREAD

**Issue by smkkristensen** [grails/grails-core#635]
When making a trivial beforeInterceptor in a controller, the interceptor is not called.

Example controller in simple helloworld app:

package helloworld3

class HelloController {

    def beforeInterceptor = {
        println "*** beforeInterceptor ***"
    }

    def index() { 
        render "Hello world!!"
    }
}

When running the app with gradle bootRun and going to the http://localhost:8080/hello/index , the browser shows "Hello world!!" as expected but the debug string from the beforeInterceptor is not writen 
in the terminal running the "gradle bootRun" command.

An analog grails 2.5.0 app runs as expected and prints out from the beforeInterceptor.

**Comment by kktec** [comment]
I am also seeing this problem

**Comment by graemerocher** [comment]
With the introduction of interceptors the beforeInterceptor feature was removed, if there is enough demand to restore this feature then we will consider it

**Comment by busches** [comment]
At the very least the documentation needs to be updated to show that this was removed, as the docs stand today, before/afterInterceptor appear to be working features of Grails 3.

http://grails.github.io/grails-doc/latest/guide/theWebLayer.html#controllerInterceptors

**Comment by graemerocher** [comment]
Agreed

**Comment by anshbansal** [comment]
@graemerocher  So will the feature be re=introduced or will the documentation be updated?

**Comment by ejaz-ahmed** [comment]
>So will the feature be re-introduced or will the documentation be updated?
I think graem is needs feedback whether this feature is required or not? He agreed on the doc update. I am also curious if this feature is required or not?

**Comment by anshbansal** [comment]
@ejaz-ahmed If backward compatibility is not considered then I don't think. The interceptors now are more powerful.

**Comment by kktec** [comment]
It's not an absolutely needed feature for me but the old way has some
advantages over the new. It  can be part of a base class and selectively
applied that way. It also has access to all the conveniences a controller
has access to, making it a bit easier to use.

**Comment by hakanernam** [comment]
Personally I feel the value of this feature is limited to warrant a re-introduction, especially for much needed 3.1.0.M3 milestone. I did not miss it even after converting all "in controller" interceptors and also believe any benefit is negated by the framework becoming more complex. I had to write this several times not to offend anyone, and still did not get it right, but I really believe we need some simplification and stability unless there is a really pressing need for a new feature. More so for a comeback.

**Comment by jasenj1** [comment]
Are you kidding me!? This feature has been removed from 3.0 but it is still in the docs?! I just wasted a couple hours trying to use beforeInterceptor in a 3.0.9 app and wondering what I was doing wrong. AARRGHH!
At the minimum, fix the docs ASAP.

Unbelievable!

**Comment by jeffbrown** [comment]
> Are you kidding me!? 

No.

> At the minimum, fix the docs ASAP.

Will do.  

Thanks for the feedback.

**Comment by jeffbrown** [comment]
The docs at http://grails.github.io/grails-doc/3.0.9/guide/upgrading.html describe that before and after interceptors were removed.  I will remove the other references in the documentation that were accidentally left behind.

**Comment by jasenj1** [comment]
https://grails.github.io/grails-doc/3.0.x/ref/Controllers/beforeInterceptor.html
http://grails.github.io/grails-doc/3.0.9/ref/Controllers/beforeInterceptor.html

**Comment by jeffbrown** [comment]
@kktec 

>  It also has access to all the conveniences a controller has access to, making it a bit easier to use.

Can you cite examples of things that an interceptor might want to have access to in a controller that are not easily accessible in an interceptor?

**Comment by chocalita** [comment]
Dear @graemerocher so will the feature be re-introduced, in my case:
I was creating my traits and is a powerfull way to reuse more system logic, but I need initializing controller variables that are using most commonly, I need initialize variiables on beforeInterceptor method as on older grails versions, but it is not posible.
Please, if you can consider the implementation of such methods in the workplace again. Or if you can suggest me any solution.
Thanks

**Comment by graemerocher** [comment]
It may come back, but if it does it won't be in the same form, and will likely be an AST transform

**Comment by chocalita** [comment]
Dear @graemerocher so will the feature be re-introduced, in my case:
I was creating my traits and is a powerfull way to reuse more system logic, but I need initializing controller variables that are using most commonly, I need initialize variiables on beforeInterceptor method as on older grails versions, but it is not posible.
Please, if you can consider the implementation of such methods in the workplace again. Or if you can suggest me any solution.
Thanks

**Comment by orubel** [comment]
In defense of the 'new method' (not really new of course), Handler interceptors greatly reduce the amount of code you are generating and allow for code re-use. It's more inline with how most of the industry does things as well and keeps us from creating services where a HandlerInterceptor should be being used. :)

It helps developers understand the communication flow a bit better too.

If you need to automate, you can create Interceptors as templates (if that helps)

**Comment by kktec** [comment]
RE: 
"Can you cite examples of things that an interceptor might want to have access to in a controller that are not easily accessible in an interceptor?"

Nothing comes to mind except perhaps the controllers superclass

**Comment by orubel** [comment]
@jasenj1 I understand your frustration. This happens to all of us at one time or another. But try to understand that for the couple hours you spent, the Grails team spends 10x that and are still playing catchup from the Pivotal bail. So a little of the documentation may get behind at times.

But we are all in this together... and they will always have your back. :)

**Comment by shutyaev** [comment]
3.1.6: **beforeInterceptor** is gone from the docs, but [**afterInterceptor**](https://grails.github.io/grails-doc/3.1.6/ref/Controllers/afterInterceptor.html) remains.

**Comment by Schlogen** [comment]
We've the decided the benefits do not outweigh the costs of implementing this. I've fixed the docs for 3.1.x to remove the reference to `afterInterceptor`. Thanks for reporting that @shutyaev!

**Comment by jahidzaynal** [comment]
The simple fact that `beforeInterceptor` and `afterInterceptor` features had access to the current controller is in itself big enough for it to be re-instated! We were using `beforeInterceptor` to ensure certain controller properties were set and/or action isn't proceeded if certain checks didn't pass (these checks being methods in the controller chain). 

With standalone interceptors there is no way to get current controller and call a method on it. All I can see is `getControllerClass()` - but not the object, and if the method you want to call isn't static you're out of luck! I just cannot believe this feature is removed without an alternative way of achieving the same behaviour!

**Comment by jameskleeh** [comment]
@jahidzaynal If your controllers are prototypes then you have an argument. Otherwise given that most controllers are singletons there is little reason why those properties/methods/etc couldn't be static

**Comment by jahidzaynal** [comment]
@jameskleeh our controllers are indeed prototypes. In fact, after your comment I've done some search of controller scopes in MVC / Spring and I'm coming across stateless vs stateful controllers; never heard of such distinction before, I always assumed controllers are stateful if you think about MVC web applications. And in fact this is the case for us, we're just migrating to Grails 3.2 from 2.5 and having to set controller scopes as `prototype` to have the same behaviour (e.g. controller having a `User` property / model.
So, given that my controllers are prototypes, what is an alternative way of doing the same as `beforeInterceptor`, if any?

**Comment by chocalita** [comment]
@jahidzaynal unfortunately they removed those interceptors, on the other hand I think that Stateless is a little object oriented strategy, in that case you can use static methods, which reduces your Class to a collection of functions.
