### ISSUE TITLE
gradle certification seems wrong

### ISSUE THREAD

**Issue by becksnow** [grails/grails-core#637]
when I run 'grails':
Error initializing classpath: No subject alternative DNS name matching services.gradle.org found.
I searched it, it seems there is sth wrong with gradle certification

**Comment by linpete** [comment]
I Confirm this. Same Problem with running grails commands in ubuntu 10.04.  Only create-app is working . TLD cert for services.gradle.org is not valid (wrong site - its for code-review.gradle.org). Running direct Gradle targets is working fine.
Similar Problem when trying to get last gradle version by gvm.

**Comment by knightchou** [comment]
I use xubuntu 15.04.
vi ./gradle/wrapper/gradle-wrapper.properties
change 'distributionUrl=https\://services.gradle.org/distributions/gradle-2.3-bin.zip'
to 'distributionUrl=http://services.gradle.org/distributions/gradle-2.3-bin.zip'
and it works.
but it's inconvenient( ok, poor english, =_=|| ), I have to do this always before I run grails.
It's gradle's problem

**Comment by linpete** [comment]
Thx for the hint. This works around the prob for a given project but indeed needs to be done for every New project again.

**Comment by zyro23** [comment]
fixed by now isnt it? so this one can be closed i guess...

**Comment by linpete** [comment]
For my project migration everything is fine .
Retested it for a New project - seems to be fixed .
Everything fine - Thx !
