### ISSUE TITLE
Debugging only works if you use the tomcat plugin

### ISSUE THREAD

**Issue by ggascoigne** [grails/grails-core#638]
I've been using jetty as my development plugin. I recently upgraded from 2.4.2 up to 2.4.5 and find that the only way I can get debugging working at all is to revert to using the tomcat plugin.

`grails run-app --debug-fork`

doesn't fork, and doesn't apply debug flags to the process.  I've tested this with jetty 2.0.3 and 3.0.0.

**Comment by christopher-purr** [comment]
maybe try `--debug-jvm` (and then use remote debugging)

**Comment by graemerocher** [comment]
I imagine you have to use `-debug`, regardless this is an issue with the jetty plugin not with Grails itself
