### ISSUE TITLE
Grails v3.0.1, GrailsCompileStatic annotation on a controller, can't find request.post or request.get

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#643]
```java
[Static type checking] - No such property: post for class: javax.servlet.http.HttpServletRequest
 @ line 23, column 19.
           log.debug request.post
```

Works fine without the GrailsCompileStatic annotation or with TypeCheckingMode.SKIP

**Comment by jeffbrown** [comment]
I don't know if this is really a bug.  The `isGet()` and `isPost()` method are dynamic methods that are added at runtime.  `GrailsCompileStatic` is supposed to flag calls that can't be validated at compile time.  We can enhance the compiler extension to special case these, or maybe come up with a more sophisticated solution that interrogates extension classes like `HttpServletRequestExtension` and then dynamically dispatch those calls.

**Comment by jeffbrown** [comment]
@graemerocher What do you think?

**Comment by graemerocher** [comment]
@jeffbrown Probably we should integrate with the extension mechanism but it surprises me that Groovy doesn't do this already / by default.. should probably run it by the Groovy guys
