### ISSUE TITLE
JIRA issues need some love

### ISSUE THREAD

**Issue by noullet** [grails/grails-core#645]
Hi,

First of all, congrats for all the recent news (big releases, jobs etc.)! 

I can imagine that all these changes (along with Greach and other conferences) must be time consuming. However, I am bit worried regarding the migration from JIRA to GitHub issues.

For instance, I am coming across major problems with Grails 2.5.0 (according to the votes/watchers, I am not the only one) but there is no follow up and no way to discuss them further:
* https://jira.grails.org/browse/GRAILS-12129 (we had to switch to fork mode to start our application in dev)
* https://jira.grails.org/browse/GRAILS-12120: (we had to disable ehcache entirely to start our application)

The lack of "migration path"/news regarding open JIRA issues will lead to duplicates (e.g. https://github.com/grails/grails-core/issues/644) so I wonder if there is any migration plan? Is there is anything that we can do to help?

**Comment by jeffbrown** [comment]
#644 shouldn't really be seen as a duplicate issue, at least not in a bad way.  GitHub is the new home for issues so it makes sense for things like that to be represented here.  The migration is not fully complete.  We are still evaluating running a script that would bring all of the issues from JIRA to GitHub.

**Comment by noullet** [comment]
Thanks for the quick answer. 

I did not use the word "duplicate" with a bad connotation. Actually I was about to create similar ones but in the absence of a public statement, I just wanted to know first if it was the way to go or if anything else was planned.

Since other solutions seem to be discussed, I'll wait and see.
