### ISSUE TITLE
UrlMapping with uri does not work

### ISSUE THREAD

**Issue by bbooth** [grails/grails-core#646]
I am trying to integrate spring secuity oauth in a Grails 3.0.1 application and running into an issue with controller actions mapping with @RequestMapping attributes.  The Grails 2.x spring-security-oauth plugin adds specific UrlMappings for the oauth token endpoints provided by spring-security-oauth like so:
```
        "/oauth/authorize"(uri: "/oauth/authorize.dispatch")
        "/oauth/token"(uri: "/oauth/token.dispatch")
```

When I manually added the same mappings and hit these endpoints I get an exception that a controller name is not provided (see stacktrace below).  I then attempted to create a simple app with a test @RequestMapping and a UrlMapping entry fails in the same manner but worked in a grails 2.4.5 app.

I tried to track down the issue and it looks like the UrlMapping code has been refactored significantly in Grails 3.  I have been through the docs quite a bit and it appears this is still supported.

I am more than willing to do a pull request if someone can point me in the right direction or maybe there is a different approach I should be taking.

```
DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [null]: grails.web.mapping.exceptions.UrlMappingException: Unable to establish controller name to dispatch for [null]. Dynamic closure invocation returned null. Check your mapping file is correct, when assigning the controller name as a request parameter it cannot be an optional token!
DEBUG org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver - Resolving exception from handler [null]: grails.web.mapping.exceptions.UrlMappingException: Unable to establish controller name to dispatch for [null]. Dynamic closure invocation returned null. Check your mapping file is correct, when assigning the controller name as a request parameter it cannot be an optional token!
DEBUG org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolving exception from handler [null]: grails.web.mapping.exceptions.UrlMappingException: Unable to establish controller name to dispatch for [null]. Dynamic closure invocation returned null. Check your mapping file is correct, when assigning the controller name as a request parameter it cannot be an optional token!
```

**Comment by bbooth** [comment]
I have simplified this down even further with out dealing with @RequestMapping annotations

```
package grails3.urlmapping.uri

class WorldController {

    def index() {
        render "world"
    }
}
```

```
"/hello"(uri: "/world/index.dispatch")
```

In Grails2 I can hit /hello and get "world" rendered".  In Grails3 just an empty response, however if I hit /world I get the "world" repsonse.  I have a sample 2.5.0 project that shows it working and a 3.0.1 project that shows it not working.  With github don't really have a place to upload it.  So please advise on what you might need.  Been continuing to dig in the source to find the problem, if I get anywhere I will submit a PR.

**Comment by kastork** [comment]
I've created a small Grails 3 plugin (web-plugin profile) that provides a UrlMappings class and the mappings are not picked up when I include the plugin in a web profile app.

The docs say all you have to do is create

    grails-app/conf/MyPluginUrlMappings.groovy

in the plugin project and provide mappings as usual.  But it isn't working for me.  I verified my project contains the grails-plugin-url-mappings plugin from core, and that plugin does appear to look for mappings in `grails-app/conf/*UrlMappings.groovy`  So maybe it is a configuration thing.  If there are additional configurations required, I don't see them documented anywhere (maybe I'm blind though?)

Anyway, if the whole UrlMappings pickup simply isn't working for 3.0 plugins that might explain your situation too.

**Comment by graemerocher** [comment]
Well one thing is that the `.dispatch` extension no longer exists, have you tried removing that to see if it still works?

**Comment by graemerocher** [comment]
closing as no feedback provided
