### ISSUE TITLE
re-add readOnly dataSources to ChainedTransactionManagerPostProcessor

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#651]
see https://github.com/grails/grails-core/commit/4864b415219f77ad7e4029e128388563b2be54c4#commitcomment-10690398

after the changes for GRAILS-11104, readOnly dataSources are not any longer processed by `ChainedTransactionManagerPostProcessor`. that might seem logical because a readOnly dataSource is not supposed to commit any transaction. however, this does also affect/prevent the automatic opening of hibernate sessions by `@Transational`/`transactionManager` which leads to errors (no session etc., see linked comment).

thanks, zyro

**Comment by graemerocher** [comment]
You should wrap in `withNewSession`

**Comment by zyro23** [comment]
:( having to use `withNewSession` in a `@Transactional` service just because an additional datasource is configured read-only does still not look right to me...

**Comment by graemerocher** [comment]
Having every connection bound to the session doesn't scale either

**Comment by graemerocher** [comment]
Bound to the current thread that is
