### ISSUE TITLE
Grails 3: run-app not logging

### ISSUE THREAD

**Issue by emboss** [grails/grails-core#652]
When running `grails run-app`, the only feedback I get is `Grails application running at http://localhost:8080`. After that, it keeps hanging at `> Building 83% > :bootRun` (same as in [this issue](https://github.com/grails/grails-core/issues/641)). No log output appears, if I configure a FileAppender, the log file will not be created.

My `logback.groovy`:

```groovy
import grails.util.BuildSettings
import grails.util.Environment


// See http://logback.qos.ch/manual/groovy.html for details on configuration
appender('STDOUT', ConsoleAppender) {
    println('This doesn't appear.')
    encoder(PatternLayoutEncoder) {
        pattern = "%level %logger - %msg%n"
    }
}

root(DEBUG, ['STDOUT'])

if(Environment.current == Environment.DEVELOPMENT) {
    def targetDir = BuildSettings.TARGET_DIR
    if(targetDir) {

        appender("FULL_STACKTRACE", FileAppender) {

            file = "${targetDir}/stacktrace.log"
            append = true
            encoder(PatternLayoutEncoder) {
                pattern = "%level %logger - %msg%n"
            }
        }
        logger("StackTrace", ERROR, ['FULL_STACKTRACE'], false )
    }
}
```

Any `println` statements within the file also won't appear in the terminal.

**Comment by emboss** [comment]
Sorry, figured it out. It was because my app's package name was `grails.myapp`. Changing the application name to just `myapp` solved the issue, logging is working fine now.

**Comment by wayshall** [comment]
hi, @emboss , how do you resolve it, I don't understand.
I do it step by step with the official tutorial, and my app's name is helloworld.

**Comment by emboss** [comment]
@fotisp Sorry for the confusion, my app still hangs at `:bootRun` - that problem still remains. But my initial problem of the logger being quiet was resolved by simply renaming the app.

**Comment by crazydan** [comment]
Hi @emboss, where exactly did you change your app name. I'm having the same issue (nothing is being logged when I use command line for test-app or run-app). However, when I run things from inside my IDE (IntelliJ), logging is working properly.

The only thing I think I've done differently from Grails convention is put my classes in subpackages like net.foo.bar.

**Comment by ava305** [comment]
You can type Arrow keys to stop the running app in windows.
