### ISSUE TITLE
[Feature Request] Add ability to retrieve the GrailsApplication instance and/or Config from an application's grails-app/init/Application.groovy file.

### ISSUE THREAD

**Issue by budjb** [grails/grails-core#653]
Grails 3 added the ability for applications to use the same startup hooks as plugins have historically had (such as ```doWithSpring```).  If authors wish to inject configuration values into beans created through these mechanisms, the ```GrailsAutoConfiguration``` superclass exposes neither the ```GrailsApplication``` nor the ```Config``` properties, causing extra work to implement or forcing reliance on the use of the ```Holders``` class.

Given that Plugins and Applications have the same API contract for these startup hooks, the same functionality should be present for both.  I'm asking that the ```GrailsApplication``` and/or ```Config``` properties be exposed in the ```GrailsAutoConfiguration``` class.

**Comment by domurtag** [comment]
what's the problem with using `Holders`?

**Comment by graemerocher** [comment]
You can use:

      applicationContext.getBean(GrailsApplication)
      applicationContext.getBean(GrailsApplication).config

To retrieve both

**Comment by Schlogen** [comment]
Will be included in the next 3.2 release
