### ISSUE TITLE
Newly generated controllers not auto-reloading

### ISSUE THREAD

**Issue by mpas** [grails/grails-core#655]
When creating a new controller in a running Grails 3.0.1 application the controller is not available/reloaded. When creating the controller the console shows that the controller is generated, compiled but inaccessible until the application is restarted.

Steps:

    grails create-controller acme

**console output**

    File /Users/marco/dev/my-grails-app/grails-app/controllers/com/myapp/AcmeController.groovy changed, recompiling...

But when i try to access the controller action method via the browser i get a 404 error. The newly generated controller also does not show on the standard grails page. When i restart the application all works fine.

This happens on Grails 3.0.1 running OSX Yosemite 10.10.2 / Java 1.8.0_31-b13
On Windows 7 using Java 1.8.0_31-b13 it seems to work ok!

**Comment by graemerocher** [comment]
To clarify you are creating a new controller whilst the container is running? Or you are creating a new controller, running the application and then modifying it?

**Comment by mpas** [comment]
I am creating a new controller when the application is runnning.

Steps to reproduce:
- grails create-app acme
- cd acme
- grails run-app

Then in a new terminal window
- cd acme
- grails create-controller foo

The foo controller does not show up and i have to restart the grails app.

**Comment by graemerocher** [comment]
Probably relates to #8987

**Comment by aclement** [comment]
@graemerocher Where do you think SpringLoaded might be making a mistake here? From my point of view, spring loaded is for watching changes to classes that have already been loaded. If it is a brand new file, the grails infrastructure has to deal with compiling it and initially loading it - whilst it is loading then SpringLoaded will notice, instrument it, and from that point on will watch it.  If the controller is loaded ok and then we aren't processing updates to it correctly, that sounds like a SpringLoaded bug but if a brand new file is being added and the system isn't picking up on that, it doesn't sound like SpringLoaded.
