### ISSUE TITLE
createLink doesn't respect UrlMappings in 2.4.5/2.5.0, but works fine in 2.4.4!

### ISSUE THREAD

**Issue by bxqgit** [grails/grails-core#657]
Say we have this in **UrlMappings.groovy**:

```groovy
static mappings = {
  "/foo/$text"(controller: "book", action: "read")
}

```
And in **bookRead.gsp**:

```groovy
${createLink(controller: "book", action: "read")}
```

In 2.4.4, createLink will generate: **"/foo"**, which is expected and is ok.
But in 2.4.5/2.5.0, createLink will generate: **"/book/read"**, which causes error in app!

I had to downgrade production app to 2.4.4 cause of that, please fix asap!

**Comment by dspies** [comment]
I have a similar problem using grailsLinkGenerator

UrlMappings.groovy
```
  "/books/$id(.$format)?"(controller:'book'){
    action = [GET: 'show', PUT: 'update', POST: 'update', DELETE: 'delete']
  }
  "/books(.$format)?"(controller:'book'){
    action = [GET: 'index', PUT: 'unsupported', POST: 'save', DELETE: 'unsupported']
  }
```

LinkService.groovy
```
grailsLinkGenerator.link(resource: 'book', id: 1, absolute: true)
```

2.4.4 generates 
```
http://localhost:8080/app/books/1
```

2.4.5 & 2.5.0 generate
```
http://localhost:8080/app/books?id=1
```

**Comment by tasneem93** [comment]
did you guys find out the solution for the above for Grails 2.5.0? I am having the same issue.

**Comment by dspies** [comment]
No, for the time being I am staying on 2.4.4
