### ISSUE TITLE
Layouts not applied to views in 'web-app' directory

### ISSUE THREAD

**Issue by valerius** [grails/grails-core#660]
Similar to ticket https://jira.grails.org/browse/GRAILS-8210 , it appears that in Grails 2.4.4 - 2.5 as apposed to 2.3.8 which works, now requires that GSP's residing within the web-app directory be explicitly mentioned in UrlMappings file in order for    <meta name="layout" content="layout_name"/> to take effect.  I'm now resolving the issue by doing the following in the UrlMappings file:

```groovy
  "/path/to/file.gsp"(view:"/path/to/file")
```
To test use 'create-app' for your desired grails version and place the following in web-app dir:

```gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <title>Welcome page</title>
  <meta name="layout" content="main"/>
</head>
<body>
<h1>Test Layout</h1>
</body>
</html>
```

Since this uses the default layout included in grails ('main'), you should see the grails look&feel, but will not unless running 2.3.8 or before. I find creating routes for each GSP  in the web-app directory somewhat tedious, as I use them for documentation and about pages etc, which shouldn't have to have a controller, etc. Though if this was an intentional change, I'm sure there were good reasons, but am presently unaware of the benefits, etc. While I've found a way around it, I haven't heard mention of it yet, so thought it important to post the issue. Thanks.

**Comment by graemerocher** [comment]
The site mesh filter has been removed and integrated directly into the GSP engine that is the reason for this. We won't be fixing this issue.
