### ISSUE TITLE
can't limit HTTP methods that are supported by subclass of RestfulController

### ISSUE THREAD

**Issue by domurtag** [grails/grails-core#661]
In a Grails 2.5.0 app, I've defined the following controller:

    class UserProfileController extends RestfulController {
    
        static responseFormats = ['json']
    
        UserProfileController() {
            super(Object)
        }    
    
        def show() {
            def result = [foo: 'foo']
            respond result
        }
    }

The URL mapping for this endpoint in `UrlMappings.groovy` is

    "/userProfile"(resource: 'userProfile', includes: ['show'])

[According to the docs][1], the URL mapping should prevent this endpoint from responding to any requests other than a GET request for `/userProfile`. However, if I send a DELETE request for `/userProfile`, it attempts to fulfill this by calling the `delete` method in the parent class instead of returning a 4XX response (405 seems the most appropriate).

  [1]: http://grails.github.io/grails-doc/2.5.0/guide/single.html#restfulMappings

**Comment by graemerocher** [comment]
So I tested this and if I do:

    curl -i -X DELETE http://localhost:8080/rest-test/profile

I get 
  
	HTTP/1.1 405 Method Not Allowed
	Server: Apache-Coyote/1.1
	Allow: GET

Which seems right to me. Note that you have to remove the default mapping of 

        "/$controller/$action?/$id?(.$format)?"{
             ...
        }

Otherwise it becomes the fallback mapping and your controller is still exposed.
