### ISSUE TITLE
Grails 2.5.0: run-app fails when spring loaded agent is provided and forked mode is off

### ISSUE THREAD

**Issue by tamershahin** [grails/grails-core#662]
It's connected to this:

https://jira.grails.org/browse/GRAILS-12129

It's doing the same with Idea 14.0.x and 14.1.1.

we don't need fork mode and disabling spring loaded is a pain for development.

**Comment by noullet** [comment]
+1

**Comment by germanSancho** [comment]
+1 :)

**Comment by itel** [comment]
It seems that a bug is in IDEA not in Grails, `grails -reloading run-app` from terminal works fine, although spring loaded agent is provided.

Find one more workaround - set up Grails run/debug configuration manually:
```
Command line: -wtf run-app
VM options: -javaagent:/home/user/.gvm/grails/2.5.0/lib/org.springframework/springloaded/jars/springloaded-1.2.3.RELEASE.jar -Xverify:none -Dspringloaded.synchronize=true -Djdk.reflect.allowGetCallerClass=true -Dspringloaded=profile=grails;cacheDir=/home/user/.grails/2.5.0
```

After adding fake first argument (`-wtf`) IDEA don't add spring loaded agent and it's possible to configure it manually through vm options.

Tested environment:
```
Grails version: 2.5.0

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.10.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

Ubuntu 14.10 x86_64
```

**Comment by noullet** [comment]
Ilya, thanks for the workaround, it works for me!

However, I am able to reproduce the issue without using IntelliJ at all.

In the command line:
```bash
grails create-app testApp
cd testApp
vi grails-app/conf/BuildConfig.groovy # disable fork mode
```

Then I used a command similar to the one started by IntelliJ, this works:
```
java 
-Dtools.jar=/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/tools.jar 
-Dgrails.home=/Users/noullet/.gvm/grails/2.5.0 
-classpath "/Users/noullet/.gvm/grails/2.5.0/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.3.jar:/Users/noullet/.gvm/grails/2.5.0/dist/grails-bootstrap-2.5.0.jar" 
org.codehaus.groovy.grails.cli.support.GrailsStarter 
run-app
```

whereas this fails:
```
java 
-noverify 
-javaagent:/Users/noullet/.gvm/grails/2.5.0/lib/org.springframework/springloaded/jars/springloaded-1.2.3.RELEASE.jar 
-Dspringloaded=profile=grails 
-Dtools.jar=/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/tools.jar 
-Dgrails.home=/Users/noullet/.gvm/grails/2.5.0 
-classpath "/Users/noullet/.gvm/grails/2.5.0/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.3.jar:/Users/noullet/.gvm/grails/2.5.0/dist/grails-bootstrap-2.5.0.jar" 
org.codehaus.groovy.grails.cli.support.GrailsStarter 
run-app
```

The only difference here is:
```
-noverify 
-javaagent:/Users/noullet/.gvm/grails/2.5.0/lib/org.springframework/springloaded/jars/springloaded-1.2.3.RELEASE.jar 
-Dspringloaded=profile=grails 
```

Of course that is not how I would have started Grails normally, so maybe IntelliJ is wrong when generating this command. However, this worked fine until now so something must have been broken somewhere!

**Comment by hugoriar** [comment]
Solution that works for me:

1) Versions:
IDE: Intellij IDEA 14.1.3
JDK: jdk1.7.0_25
GRAILS: 2.5.0 

2) On BuildConfig.groovy: 
grails.reload.enabled = true
grails.project.fork = [
        test: false,
        run: false,
]

3) Originally, my code was compiled on grails 2.4.4, so I upgraded to 2.5.0. I had no problems with the version change with plugins or anything. My guess is this works because it uses later versions of spring-loaded. Steps:
3.1) set-grails-version 2.5.0
3.2) clean
3.3) delete directory work (just to be sure, I don't really know if this is good practice)
3.4) compile and/or go to number 4

4) Debug Idea with this configuration: run-app -reloading

------------------------------------------------------------------------------------------

Works perfect, no forked debug, reloading enabled, no console error after reload and all breakpoints working even after code changes!

**Comment by tamershahin** [comment]
Solution that works for me:

1) Versions:
IDE: Intellij IDEA 14.1.4
JDK: jdk1.7.0_71
GRAILS: 2.5.1

2) On BuildConfig.groovy: 
grails.project.fork = [
		run: [maxMemory: 1024, minMemory: 64, debug: false, maxPerm: 256]
]

3) On Config.groovy
grails.reload.enabled = true

4) Debug Idea with this configuration: run-app -reloading (clean or clean-all first)

**Comment by dosaki** [comment]
Sadly, none of the solutions above work for me (to run through IntelliJ)

Only running through the console works at the moment.

**Comment by theaspect** [comment]
IntelliJ IDEA 2016.1.1
JRE: 1.8.0_40-release-b132 x86_64
Grails 2.5.4

None of this worked

**Comment by MarcinOS** [comment]
IntelliJ IDEA 2016.2
JRE: 1.8.0_73
Grails 2.5.4

Have the same.

@theaspect's advice helped me, thank you!

It's still just a workaround, though...
