### ISSUE TITLE
Grails 2.5.0: Controller with Traits throws "BUG! exception in phase 'instruction selection'"

### ISSUE THREAD

**Issue by tamershahin** [grails/grails-core#663]
may be related to this:
https://jira.grails.org/browse/GRAILS-11765

no problem with Grails 2.4.x, after upgrading the compilation is failing even before instrumenting the controller:

Fatal error during compilation org.apache.tools.ant.BuildException: BUG! exception in phase 'instruction selection' in source unit '/../src/groovy/org/test/ControllerTrait.groovy' unexpected NullpointerException (Use --stacktrace to see the full trace)

**Comment by germanSancho** [comment]
Same thing here. This is a big issue that is preventing us from migrating to 2.5.0

**Comment by jeffbrown** [comment]
Can you provide any more detail about how to create the problem or create a sample app which demonstrates the problem?

**Comment by tamershahin** [comment]
here you can find a test project with the error:
https://github.com/tamershahin/traitTest

Creating the test project I realised that the problem is in Transactional annotation applied to the trait that is generating the problem.
On Grails 2.4.4 it is working fine, there are 2 thing the I'm asking myself now:
-applying the annotation to the Trait is really meaningful?
-if so, is the reported error in the stacktrace correct?

**Comment by jeffbrown** [comment]
See https://issues.apache.org/jira/browse/GROOVY-7402

**Comment by graemerocher** [comment]
See the feedback in https://issues.apache.org/jira/browse/GROOVY-7402?focusedCommentId=14567018&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14567018

Since this is a Groovy bug there is nothing we can do about it on the Grails side

**Comment by tamershahin** [comment]
Thank you Greame and Jeff!

as you wrote, it's very strange that it was working with previous version of groovy.. in any case it's not a big deal for us, we can move that specific annotation.
