### ISSUE TITLE
Grails exception handling should not unwrap user exceptions

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#666]
When user code in the controller or service layer generates an exception with a root cause, Grails is unwrapping the exception and only displaying the root cause. This is nasty behavior; Grails should only unwrap exceptions which are used internally by the framework. Unwrapping user exceptions may cause contextual information about the error to get lost.

**Comment by rmorrise** [comment]
I created a test project for this issue, but I couldn't figure out how to upload the .zip to GitHub's issue tracker. Here is a Gist instead with the relevant code:

https://gist.github.com/rmorrise/df09bdf7d06344bffa1d

**Comment by nobeans** [comment]
Are you mentioning the message at the error page?

```
  Error 500: Internal Server Error
  URI: /exceptionCausing/index
  Class: wrapped.exception. NestedException
  Message: Nested error
```

Certainly, it's the one of the nested exception. But the actual stack trace is as expected like:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - NestedException occurred when processing request: [GET] /exceptionCausing/index
Nested error. Stacktrace follows:
wrapped.exception.WrappingException: Error called nested service from wrapped service: Nested error
        at wrapped.exception.WrappingService.$tt__serviceMethod(WrappingService.groovy:14) ~[main/:na]
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:93) ~[grails-core-3.0.1.jar:3.0.1]
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90) ~[grails-core-3.0.1.jar:3.0.1]
        at wrapped.exception.ExceptionCausingController.index(ExceptionCausingController.groovy:7) ~[main/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: wrapped.exception.NestedException: Nested error
        at wrapped.exception.NestedService.$tt__serviceMethod(NestedService.groovy:9) ~[main/:na]
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:93) ~[grails-core-3.0.1.jar:3.0.1]
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90) ~[grails-core-3.0.1.jar:3.0.1]
        at wrapped.exception.WrappingService.$tt__serviceMethod(WrappingService.groovy:11) ~[main/:na]
        ... 6 common frames omitted
```

I think that the most important information in a stack trace is the root caused exception. So I'm satisfying with current behavior so far.

**Comment by rmorrise** [comment]
Are you testing with the same grails version? In 2.3.11, I only get the nested exception in the stack trace from the console log:

2015-04-23 12:41:35,449 [http-bio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - NestedException occurred when processing request: [GET] /wrapped-exception/exceptionCausing/index
Nested error. Stacktrace follows:
Message: Nested error
    Line | Method
->>    9 | $tt__serviceMethod in wrapped.exception.NestedService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     11 | $tt__serviceMethod in wrapped.exception.WrappingService
|      7 | index . . . . . .  in wrapped.exception.ExceptionCausingController
|    198 | doFilter           in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker          in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                in java.lang.Thread

The same trace is displayed at the bottom of error.gsp.

**Comment by nobeans** [comment]
Oh, sorry. I've used 3.0.1.

Now, I've tried it with 2.3.11. I got this result in console:

```
| Error 2015-04-24 02:06:36, 254 [http-bio-8080-exec-2] ERROR errors. GrailsExceptionResolver  - NestedException occurred when processing request: [GET] /wrapped.exception/exceptionCausing/index
Nested error. Stacktrace follows:
Message: Nested error
    Line | Method
->>    9 | $tt__serviceMethod in wrapped.exception. NestedService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|     11 | $tt__serviceMethod in wrapped.exception. WrappingService
|      8 | index . . . . . .  in wrapped.exception. ExceptionCausingController$$EPAhPzFI
|    198 | doFilter           in grails.plugin.cache.web.filter. PageFragmentCachingFilter
|     63 | doFilter . . . . . in grails.plugin.cache.web.filter. AbstractFilter
|   1145 | runWorker          in java.util.concurrent. ThreadPoolExecutor
|    615 | run . . . . . . .  in java.util.concurrent. ThreadPoolExecutor$Worker
^    745 | run                in java.lang. Thread
```

It seems that the wrapping exception was unwrapped. But it's just the format of customized stack trace. Actually, WrappingException is thrown. Don't worry. If you try to catch WrappingException in the controller, you can do it.

I agree that the customized stacktrace is confusable :-)

**Comment by rmorrise** [comment]
I am actually using a custom error controller in my use case. I am unable
to get the wrapping exception data from the request.exception property
because the wrapping exception is being discarded by the framework before
the error controller is invoked. It looks like I would have to implement a
custom exception resolver just to make the user exception that I threw
available to the controller. I really think it is a bug. :)

Glad it's fixed in v3. We have it in our plan to upgrade to the latest
Grails version but we are not there yet! It is not too trivial a change.

**Comment by nobeans** [comment]
OK, I get your point now. Indeed, it seems a bug.

In the constructor of GrailsWrappedRuntimeException, the WrappingException is replaced with its root caused exception, NestedException. I think that we should be able to use the original exception even in ErrorController.

**Comment by jsmucr** [comment]
Is this really fixed already? I'm experiencing unwanted exception unwrapping in Grails 2.5.2 as well.

    try {
        throw new SomeInternalException()
    } catch (Exception e) {
        throw new MyBetterException(e)
    }

The code above causes the SomeInternalException to be propagated to console and the ErrorController which is not what I want.

    try {
        throw new SomeInternalException()
    } catch (Exception e) {
        throw new MyBetterException()
    }

Not passing the cause fixes the behavior, but I don't like this approach either.
