### ISSUE TITLE
Grails 3.0.1: Upload file size limit (128000)

### ISSUE THREAD

**Issue by pentagon** [grails/grails-core#668]
When trying to upload a file got the following:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - SizeLimitExceededException occurred when processing request: [POST] /event/save
the request was rejected because its size (312052) exceeds the configured maximum (128000). Stacktrace follows:
org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (312052) exceeds the configured maximum (128000)
```

How could I change the limit? It seems the docs are missing that part ..

**Comment by zyro23** [comment]
`grails.controllers.upload.maxFileSize` and/or `grails.controllers.upload.maxRequestSize` config properties/settings.

ref:
* https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L124
* https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/config/Settings.groovy#L91 ff.

did not spot it in the docs as well. a pull-request improving that would be helpful :)

**Comment by pentagon** [comment]
thank you very much, it helped to address file size limit. but it seems upload is broken or not reflected in docs properly.

```
request.getFile('blah')
```

results in

```
No signature of method: org.grails.web.filters.HiddenHttpMethodFilter$HttpMethodRequestWrapper.getFile() is applicable for argument types: (java.lang.String) values: [assetFile]
```

i checked the same code within grails 2.5.0 and it worked correctly. perhaps i have to file a separate issue.

**Comment by zyro23** [comment]
cannot reproduce that. check https://github.com/zyro23/grails-core-668
* fresh 3.0.1 app
* defined `maxFileSize` and `maxRequestSize` in `application.yml` (see comments above)
* `grails-app/views/index.gsp` has a multipart form posting to `DummyController`
* `DummyController` shows that `request.getFile(...)` works as well as data-binding as `MultipartFile` on a command object

does that help? or are you doing anything different?

**Comment by pentagon** [comment]
i'm doing slightly different thing, i'm gonna enhance your sample  and get back with an example that's close to mine.

**Comment by pentagon** [comment]
I finally reproduced the issue. Adding method="PUT" to a form results it that behavior. I'm gonna push my take on to github.

**Comment by pentagon** [comment]
I created a pull request to demo a bug: https://github.com/zyro23/grails-core-668/pull/1
As i said before, the main difference is using 'PUT' method in a form which results in
```
No signature of method: org.grails.web.filters.HiddenHttpMethodFilter$HttpMethodRequestWrapper.getFiles() is applicable for argument types: (java.lang.String) values: [assetFiles]
```

**Comment by zyro23** [comment]
i think these are related:
* https://jira.grails.org/browse/GRAILS-11308
* https://jira.grails.org/browse/GRAILS-11067

**Comment by pentagon** [comment]
Perhaps they're related. Thanx for your help,  I think we're out of the topic for this issue and I'm gonna close it.
