### ISSUE TITLE
Dependencies of tomcat can't be excluded in Grails 3.0.1

### ISSUE THREAD

**Issue by flashing** [grails/grails-core#674]
As the document of grails 3.0.1 says in section "21 Deployment":
provided "org.springframework.boot:spring-boot-starter-tomcat"
can exclude the tomcat jar files, but this doen't work.

And also, I don't know why tomcat-jdbc-7.0.55.jar and tomcat-juli-7.0.55.jar are always in the lib directory of final war from grails 2.x, and even worse, ant-1.9.4.jar and ant related jar files should not exist in final war file.

**Comment by graemerocher** [comment]
Duplicates #8969
