### ISSUE TITLE
dateCreated / lastUpdated in a unit test remain null after saved (GRAILS-11855)

### ISSUE THREAD

**Issue by bobbywarner** [grails/grails-core#676]
Recreating an older issue here just for documentation purposes since JIRA is now read-only.  For more details about the issue, please read here: https://jira.grails.org/browse/GRAILS-11855

**Comment by bobbywarner** [comment]
This issue is fixed in g-d-m with this commit: https://github.com/grails/grails-data-mapping/commit/2d217c502175ab4693717927bc60f2a4f518b6a6

**Comment by jeffbrown** [comment]
FYI... You can tag commits with something like grails/grails-core#676 and GitHub will know that the commit relates to this issue. You can also auto-close issues using special tags in the commit message. See https://guides.github.com/features/issues/ for more info.

**Comment by bobbywarner** [comment]
This issue was not fixed in g-d-m as per my previous comments and the commit referenced has been reverted.  The issue is now fixed by adding the datastore event listeners for tests in `DomainClassUnitTestMixin`.

**Comment by bobbywarner** [comment]
Looks like this issue is present in 3.0.1 too.  So, I will merge the 2.5.x branch into 3.0.x (and 3.0.x into master) as well.

**Comment by jonnybot0** [comment]
I still seem to have this issue using the latest snapshot build (cloning grails-core, checking out the 2.5.x branch, and using ./gradlew install to build). The date created field is null on mocked domain objects in unit tests for services.

I've got 
import grails.test.mixin.domain.DomainClassUnitTestMixin
at the top of my spec, and I mock the domain objects the service requires using the @Mock([Domain1, Domain2]) syntax.

**Comment by nobeans** [comment]
It seems not to be fixed, to be still null in 3.0.2.

**Comment by nobeans** [comment]
I've confirmed by this example: https://github.com/nobeans/grails3-sample-issue676

The test with TestFor annotation works well: https://github.com/nobeans/grails3-sample-issue676/blob/master/src/test/groovy/grails3/sample/issue676/BookTestForSpec.groovy

```
@TestFor(Book)
class BookTestForSpec extends Specification {
...
```

But the test with Mock annotation failed as follows: https://github.com/nobeans/grails3-sample-issue676/blob/master/src/test/groovy/grails3/sample/issue676/BookMockSpec.groovy

```
@TestMixin(GrailsUnitTestMixin)
@Mock(Book)
class BookMockSpec extends Specification {
....
```

```
Condition not satisfied:

book.dateCreated != null
|    |           |
|    null        false
grails3.sample.issue676.Book : 1

	at grails3.sample.issue676.BookMockSpec.Mock doesn't work(BookMockSpec.groovy:17)
```

Am I wrong on how to use annotation for mocking?

**Comment by graemerocher** [comment]
No seems wrong and like a bug... thanks for the example

**Comment by graemerocher** [comment]
I had to revert @bobbywarner's original change because the changed added a new `DomainEventsListener` for each test run which was causing the regression seen in #9019

Looking at a better fix for the problem now

**Comment by nobeans** [comment]
I've confirmed it at `73dbe34` of `3.0.x` branch. But it seems not to be fixed, rather it seems worse. 

Both of test methods of the example are failed like this:

```
TestFor works well

Condition not satisfied:

book.dateCreated != null
|    |           |
|    null        false
grails3.sample.issue676. Book : 1

	at grails3.sample.issue676. BookTestForSpec. TestFor works well(BookTestForSpec.groovy:14)
```

```
Mock doesn't work

Condition not satisfied:

book.dateCreated != null
|    |           |
|    null        false
grails3.sample.issue676. Book : 1

	at grails3.sample.issue676. BookMockSpec. Mock doesn't work(BookMockSpec.groovy:17)
```

**Comment by graemerocher** [comment]
@nobeans You have to use

    compile "org.grails:grails-datastore-gorm:4.0.4.BUILD-SNAPSHOT"

**Comment by nobeans** [comment]
Oh, sorry. After I've build the latest grails-datastore-gorm and added the above line, the tests were all passed perfectly. Thank you!

**Comment by jsmucr** [comment]
Has this been backported to Grails 2.5.2? My unit tests stopped woking once I started using the dateCreated column since it's always null.
