### ISSUE TITLE
Grails 2.5: Modifying a groovy SubClass (extends a groovy base class), returns a compilation error, "...cannot override $getStaticMetaClass in [class]; attempting to assign weaker access privileges; was public"

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#682]
** I've updated the bug to be more general.  See comments below.

-----------------------------------------------------------------------------------
Looks like it's the same bug as reported here: https://github.com/grails/grails-core/issues/619

Environment:
Java 8u45

Simple to reproduce:
grails-app/controllers
```
class BaseContoller (

}

class SubController extends BaseController {

}
```

> grails run-app -https
making a change to the SubControler returns a compilation error: "...cannot override $getStaticMetaClass in [class]; attempting to assign weaker access privileges; was public"

**Comment by dacoates** [comment]
Java 8u31 and earlier does not have this problem, but Java 8u45 does.

**Comment by tcrossland** [comment]
I'm also getting this error after modifying a domain class.

**Comment by zyro23** [comment]
likely related: https://github.com/grails/grails-core/issues/619

**Comment by ikakara** [comment]
I just discovered this is a more general issue w/ groovy classes (rather than isolated to grails artefacts):

src/groovy/BaseClass.groovy
```
class BaseClass {
	
}
```

src/groovy/SubClass.groovy
```
class SubClass extends BaseClass {

}
```
Modifying the SubClass will result in compile errors

**Comment by ikakara** [comment]
I just tested w/ java classes, and the following auto-compiles fine:
src/java/JBaseClass.java
```
public class JBaseClass {
  
}
```
src/java/JSubClass.java
```
public class JSubClass extends JBaseClass {

}
```

**Comment by ikakara** [comment]
This appears to aucto-compile fine:
```
public class JSubClass extends BaseClass { // java sub class extending a groovy base class
}
```

**Comment by ikakara** [comment]
And this appears to auo-compile fine:
class SubClass extends JBaseClass { // groovy sub class extending a java base class
}

**Comment by ikakara** [comment]
FHY - creating a new groovy class (and/or modifying it) assuming it's not extending/inheriting from a groovy base class), will auto-compile(reload)

**Comment by graemerocher** [comment]
Duplicates #619
