### ISSUE TITLE
Should the second format in DateConversionHelper also use HH?

### ISSUE THREAD

**Issue by jspiewak** [grails/grails-core#685]
As an ISO8601 format, the hours should be 00-23 like the other two formats, not 1-12, right?

https://github.com/grails/grails-core/blob/master/grails-databinding/src/main/groovy/org/grails/databinding/converters/DateConversionHelper.groovy#L35

**Comment by jeffbrown** [comment]
> As an ISO8601 format, the hours should be 00-23 like the other two formats, not 1-12, right?

I think the default formats are all valid as they are written.  Applications can assign a value to `grails.databinding.dateFormats` to add support for whatever formats they like.

**Comment by jspiewak** [comment]
Well, it is certainly a valid format. But with hh and nothing to deal with am/pm, you can only represent half the hours in a day.

**Comment by jeffbrown** [comment]
I am not sure where that format came from.  It goes all the way back to https://github.com/grails/grails-core/commit/73e0b1b8a5415ee8f3ee0e0bbf680c26ff0ebd15#diff-0be2d9f9b86cc95d8becd3561ca37941R80.

**Comment by jspiewak** [comment]
That's pretty way back.

**Comment by graemerocher** [comment]
So anything to be done on this issue or can it be closed?

**Comment by jspiewak** [comment]
I don't have any context from a historical perspective. But given that the format can only represent 12 hours, it seems like something that should be fixed.

**Comment by graemerocher** [comment]
Jeff - can you take a look?

**Comment by jeffbrown** [comment]
It is a simple enough change to use 0-23 instead of 1-12.  It would be a breaking change, but it would be breaking situations that probably didn't make sense anyway and may not even exist because of that.  The workaround is simple enough and that is to define formats in `grails.databinding.dateFormats`.

I propose that we leave 3.0.x alone and make the change in 3.1.

Thoughts?

**Comment by jspiewak** [comment]
Sounds reasonable to me, thanks!

**Comment by graemerocher** [comment]
@jeffbrown Are you tackling this?

**Comment by jeffbrown** [comment]
Are we agreed that we want to change this for 3.1?

**Comment by graemerocher** [comment]
Thanks for the pull request!
