### ISSUE TITLE
Grails 3.0.1 - destroy not called in Bootstrap

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#690]
The destroy-closure is never called when shutting down grails 3.0.1. init is working as expected

**Comment by graemerocher** [comment]
Has this been reopened for a reason?

**Comment by jeffbrown** [comment]
It was a mistake on my part.

**Comment by jeffbrown** [comment]
I am not 100% sure but I think I dragged this from Backlog to Ready using the Waffle.io UI.  I may have just made a mistake but if Waffle.io is showing closed items in the Backlog list, that would be a problem.  I am not prepared to blame it on Waffle, will keep an eye on that and see if it comes up again.

**Comment by jeffbrown** [comment]
I see now that both https://github.com/grails/grails-core/issues/667 and https://github.com/grails/grails-core/issues/674 are closed and are showing up in the Backlog list in Waffle.

**Comment by jeffbrown** [comment]
https://github.com/waffleio/waffle.io/issues/1798 may be relevant, not sure.  

If there is any more discussion to be had about this, I will take it up in our development channel in Slack as the discussion doesn't really have much to do with this particular bug report.  Sorry for the trouble.

**Comment by mhuebner** [comment]
Thanks for fixing this bug!
