### ISSUE TITLE
Grails 3.0.1 - Method annotated with @PreDestroy is not executed at shutdown

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#691]
Declaring a spring bean via resources.groovy and using @PreDestroy hat no effekt. The annotated method is not executed.

**Comment by graemerocher** [comment]
How are you shutting down the application?

**Comment by graemerocher** [comment]
Seems to work fine for me

**Comment by mhuebner** [comment]
Sorry, I didn't get a notification for your comments. Subscribed now. 
Shutting down via CTRL+C or IntelliJ's "Stop"-Button.
