### ISSUE TITLE
Grails 3.0.1 CLI won't start too

### ISSUE THREAD

**Issue by magixsource** [grails/grails-core#692]
Java Version

java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) Client VM (build 24.71-b01, mixed mode, sharing)

Grails Env

| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.7.0_71

grails create-app helloworld
cd helloworld
grails
after long time build i got a error

| Error Error occurred running Grails CLI: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    org/grails/cli/interactive/completers/RegexCompletor.<init>(Ljava/lang/String;)V @73: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184d 04bd 0004 5903 2c12 1932 121b
    0000010: 2bb9 0021 0300 5359 10ff 1202 b800 272a
    0000020: 5fab 0000 0000 0043 0000 0002 aad3 b1ff
    0000030: 0000 001b 59b3 a684 0000 002e 5f5a 5903
    0000040: 32b8 002d c000 2f5f 57b7 0031 a700 225f
    0000050: 5a59 0332 121b b800 35c0 001b 5f57 b700
    0000060: 38a7 000d bb00 3a59 123c b700 3dbf 57b1
    0000070:
  Stackmap Table:
    full_frame(@60,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@79,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@100,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@110,{Object[#2],Object[#47],Object[#66]},{Object[#68]})
 (Use --stacktrace to see the full trace)

and i try use "grails -noverify"
but result is the same
My JDK version is not 7u65,7u67, 8u11 and 8u20,Is this a bug ? 

i will try it later after download a verity version JDK, But what version is OK ?

**Comment by magixsource** [comment]
Hey,I download new jdk7u80 from http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-windows-i586.exe,and it's ok now ! this issue will be close.Have a nice grails3 day.

**Comment by graemerocher** [comment]
JDK issue, closing
