### ISSUE TITLE
Grails 2.5.0: Dependency resolver incorrectly set when running in forked mode

### ISSUE THREAD

**Issue by sheehan** [grails/grails-core#693]
Related to https://jira.grails.org/browse/GRAILS-10464

I'm trying to set the update policy like:

```groovy
repositories {
    mavenLocal()
    mavenRepo('http://myrepo') {
        updatePolicy 'always'
    }
}
```

but getting this in 2.5.0 doing a run-app, with forked mode on an app with inline plugins:

> | Error WARNING: Inline plugins for [myplugin] cannot be read due to error: No signature of method: org.codehaus.groovy.grails.resolve.config.RepositoriesConfigurer.mavenRepo() is applicable for argument types: (java.lang.String, BuildConfig$_run_closure1$_closure6$_closure9) values: [http://myrepo, ...]
Possible solutions: mavenRepo(java.lang.String), mavenRepo(java.util.Map) (Use --stacktrace to see the full trace)

It works if I run it non-forked.

**Comment by graemerocher** [comment]
@bobbywarner Can this be closed?
