### ISSUE TITLE
Single pdf documentation cut.

### ISSUE THREAD

**Issue by rozpuszczalny** [grails/grails-core#695]
There is a problem in single.pdf file, right margin cuts some of text and it cannot be read well. 
![zrzut ekranu 2015-05-07 o 23 43 41](https://cloud.githubusercontent.com/assets/7627635/7526564/ef8d572e-f512-11e4-9302-f7749aa3ed9d.png)

**Comment by jeffbrown** [comment]
https://github.com/grails/grails-doc/issues/250
