### ISSUE TITLE
ServletFilter initialisation in Grails 3.x

### ISSUE THREAD

**Issue by oleg-cherednik** [grails/grails-core#696]
In latest *Grails 3.x* it's unable to use same way of adding servlet filter as it was in *Grails 2.x*.

# In Grails 2.x
#### BootStrap.groovy

    def init = {servletContext ->
        FilterRegistration.Dynamic filter = servletContext.addFilter('fiterName',
                'filterClass');
        filter.addMappingForUrlPatterns(null, false, '/*');
        filter.setInitParameter('param', 'value');
    }

# In Grails 3.x
#### BootStrap.groovy

    def init = {servletContext ->
        FilterRegistration.Dynamic filter = servletContext.addFilter('fiterName',
                'filterClass');
// **java.lang.IllegalStateException: Filters can not be added to context  as the context has been initialised**
    }

**Comment by zyro23** [comment]
any special reason you want to use servlet api directly?
spring boot ships support for registering `Filter`s as beans or you can use a `FilterRegistrationBean` (http://javadox.com/org.springframework.boot/spring-boot/1.2.3.RELEASE/org/springframework/boot/context/embedded/FilterRegistrationBean.html).

**Comment by oleg-cherednik** [comment]
I try this link, but I've not found the way to init FilterConfig parameter that comes to *javax.servlet.Filter.init(FilterConfig filterConfig)*. As you know, this parameter is set when we define the filter in web.xml. Same way I did it in previous Grails in BootStrap.groovy.

Why I need it? I use jasig cas authorization and have to set parameters to this filters. And parameters are read from external server, that's why I can't use web.xml directly (because parameters should be read from external server).

I give example:

# In Grails 2.x
#### BootStrap.groovy
class BootStrap {
    private def initAuthenticationFilter = {servletContext ->
        FilterRegistration.Dynamic filter = servletContext.addFilter('casAuthenticationFilter',
                'org.jasig.cas.client.authentication.AuthenticationFilter');
        filter.addMappingForUrlPatterns(null, false, '/*');
        filter.setInitParameter('casServerLoginUrl', ConfigUtils.readString('obsrv.cas.server'));
        filter.setInitParameter('serverName', ConfigUtils.readString('obsrv.cas.serviceUrl'));
        filter.setInitParameter('ignorePattern', '.*/is-tomcat-running|.*/assets/.*|.*/health|.*/i18n|.*/favicon\\.ico');
        filter.setInitParameter('ignoreUrlPatternType', 'REGEX');
    }

    private def initValidationFilter = {servletContext ->
        FilterRegistration.Dynamic filter = servletContext.addFilter('casValidationFilter',
                'org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter');
        filter.addMappingForUrlPatterns(null, false, '/*');
        filter.setInitParameter('casServerUrlPrefix', ConfigUtils.readString('obsrv.cas.server'));
        filter.setInitParameter('serverName', ConfigUtils.readString('obsrv.cas.serviceUrl'));
    }

    private def initAssertionFilter = {servletContext ->
        FilterRegistration.Dynamic filter = servletContext.addFilter('casAssertionThreadLocalFilter',
                'org.jasig.cas.client.util.AssertionThreadLocalFilter');
        filter.addMappingForUrlPatterns(null, false, '/*');
    }

    def init = {servletContext ->
        ConfigUtils.loadConfig 'obsrv.properties' // read properties from e.g. Amazon S3

        initAuthenticationFilter servletContext
        initValidationFilter servletContext
        initAssertionFilter servletContext
    }
}

# In Grails 3.x
#### resources.groovy
beans = {
    ConfigUtils.loadConfig 'obsrv.properties'

    //TODO think about servlet filter configuration^ main problem is to set parameters to FilterConfig

    casAuthenticationFilter(LocalAuthenticationFilter) {bean ->
        bean.constructorArgs = [
                ConfigUtils.readString('obsrv.cas.server'), // casServerLoginUrl
                ConfigUtils.readString('obsrv.cas.serviceUrl'), // serverName
                '.*/is-tomcat-running|.*/assets/.*|.*/health|.*/i18n|.*/favicon\\.ico', // ignorePattern
                'REGEX' // ignoreUrlPatternType
        ]
    }

    casValidationFilter(LocalCas20ProxyReceivingTicketValidationFilter) {bean ->
        bean.constructorArgs = [
                ConfigUtils.readString('obsrv.cas.server'), // casServerUrlPrefix
                ConfigUtils.readString('obsrv.cas.serviceUrl')  // String serverName
        ]
    }

    casAssertionThreadLocalFilter(AssertionThreadLocalFilter)
}

#### LocalAuthenticationFilter.java
public class LocalAuthenticationFilter extends AuthenticationFilter {
    private final Properties props = new Properties();

    public LocalAuthenticationFilter(String casServerLoginUrl, String serverName, String ignorePattern, String ignoreUrlPatternType) {
        props.setProperty("casServerLoginUrl", casServerLoginUrl);
        props.setProperty("serverName", serverName);
        props.setProperty("ignorePattern", ignorePattern);
        props.setProperty("ignoreUrlPatternType", ignoreUrlPatternType);
    }

    // ========== AbstractCasFilter ==========

    @Override
    protected final void initInternal(final FilterConfig filterConfig) throws ServletException {
        if (props.containsKey("serverName"))
            setServerName(props.getProperty("serverName"));

        try {
            Method method = ApplicationFilterConfig.class.getDeclaredMethod("getFilterDef");
            method.setAccessible(true);
            FilterDef filterDef = (FilterDef)method.invoke(filterConfig);

            if (props.containsKey("casServerLoginUrl"))
                filterDef.addInitParameter("casServerLoginUrl", props.getProperty("casServerLoginUrl"));
            if (props.containsKey("ignorePattern"))
                filterDef.addInitParameter("ignorePattern", props.getProperty("ignorePattern"));
            if (props.containsKey("ignoreUrlPatternType"))
                filterDef.addInitParameter("ignoreUrlPatternType", props.getProperty("ignoreUrlPatternType"));
        } catch(Exception e) {
            e.printStackTrace();
        }

        super.initInternal(filterConfig);
    }
}

#### LocalCas20ProxyReceivingTicketValidationFilter.java
public class LocalCas20ProxyReceivingTicketValidationFilter extends Cas20ProxyReceivingTicketValidationFilter {
    private final Properties props = new Properties();

    public LocalCas20ProxyReceivingTicketValidationFilter(String casServerUrlPrefix, String serverName) {
        props.setProperty("casServerUrlPrefix", casServerUrlPrefix);
        props.setProperty("serverName", serverName);
    }

    // ========== AbstractCasFilter ==========

    @Override
    protected final void initInternal(final FilterConfig filterConfig) throws ServletException {
        if (props.containsKey("serverName"))
            setServerName(props.getProperty("serverName"));

        try {
            Method method = ApplicationFilterConfig.class.getDeclaredMethod("getFilterDef");
            method.setAccessible(true);
            FilterDef filterDef = (FilterDef)method.invoke(filterConfig);

            if (props.containsKey("casServerUrlPrefix"))
                filterDef.addInitParameter("casServerUrlPrefix", props.getProperty("casServerUrlPrefix"));
        } catch(Exception e) {
            e.printStackTrace();
        }

        super.initInternal(filterConfig);
    }
}

*This my temporary version. But I want to find a way to set these parameters with more prooper way*.

Thinks for helping.

**Comment by zyro23** [comment]
looks like the `FilterRegistrationBean` methods `setInitParameters(Map<String,String>)` and/or `addInitParameter(String, String)` do just what you are looking for..

**Comment by graemerocher** [comment]
As mentioned by @zyro23 you should use `FilterRegistrationBean`
