### ISSUE TITLE
Test report summary only includes integration tests

### ISSUE THREAD

**Issue by kktec** [grails/grails-core#699]
In a 3.0.1 project that has unit tests and integration tests. the index.html summary report only shows the results of the integration tests without the unit tests. The results html for all the tests individually are available in build/reports/tests/classes but the summary should include the aggregation of the results for all tests

**Comment by nobeans** [comment]
This issue will be fixed by https://github.com/grails/grails-core/pull/617.
For the meantime, you can run `grails test-app --unit` if you want to get a report of unit tests.
