### ISSUE TITLE
Grails 3.0.1 failOnError setting in application.yml does not work

### ISSUE THREAD

**Issue by TheRiver** [grails/grails-core#705]
Setting `failOnError` to be globally true does not work:

```
grails:
    gorm:
        failOnError: true
```

With the above setting enabled, calling `.save()` on an instance of a domain class whose fields do not meet the domain class's constraints still silently fails, rather than throwing an exception. 

This might be related to issue https://github.com/grails/grails-core/issues/614, where another `application.yml` setting is being ignored.

### How to replicate
I was able to replicate this in a fresh grails project using the default h2 database and the `application.yml` file only edited to include the `failOnError` setting.

**Comment by rafaelfelini** [comment]
+1, same problem here.

**Comment by graemerocher** [comment]
So using master I edited `application.yml` and added:

    grails:
        profile: web
        gorm:
            failOnError: true        

I then modified `BootStrap.groovy` to save and entity that violates a constraint:

    def init = { servletContext ->
    	new Book(title:"").save()
    }

And the result is:

        grails.validation.ValidationException: Validation error whilst flushing entity [failonerror.Book]:
	      at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:112)

So everything appears to work as expected in master
