### ISSUE TITLE
Grails 2.5.0: Reloading of src Templates not working

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#706]
I'm not sure if this is a bug or never worked before, but it would be nice if changing around the template files grails would know to reload / regenerate scaffolding based on the latest changes. Currently if I make changes to templates I have to kill the app and restart it for them to reload.

**Comment by vonovak** [comment]
Hi,
this worked for me with 2.4.4 :)
http://stackoverflow.com/questions/11873534/automatically-reload-template-files
