### ISSUE TITLE
Grails 2.4.5: HibernateTestMixin db does not enforce all multi-column unique constraints on the same property name

### ISSUE THREAD

**Issue by jdbeutel** [grails/grails-core#707]
When two domains have a multi-column unique constraint on the same property name, only one of them is enforced by the HibernateTestMixin db.  Test case on Grails 2.4.5 defaults:

    class Bar {
        String one
        String two
        static constraints = {
            one     unique: ['two']
        }
    }

    class Foo {
        String one
        String two
        static constraints = {
            one     unique: ['two']
        }
    }

    @TestMixin(HibernateTestMixin)
    @Domain([Bar, Foo])
    class BarSpec extends Specification {

        void "test something"() {

            expect: 'one entity can be saved'
            new Bar(one: 'one', two: 'two').save(flush: true)

            when: 'trying to save a duplicate entity'
            new Bar(one: 'one', two: 'two').save(flush: true)

            then:
            thrown(DuplicateKeyException)
        }
    }

    @TestMixin(HibernateTestMixin)
    @Domain([Bar, Foo])
    class FooSpec extends Specification {

        void "test something"() {

            expect: 'one entity can be saved'
            new Foo(one: 'one', two: 'two').save(flush: true)

            when: 'trying to save a duplicate entity'
            new Foo(one: 'one', two: 'two').save(flush: true)

            then:
            thrown(DuplicateKeyException)
        }
    }

The unique constraint is enforced on only one of the two domains:

    | Compiling 2 source files....
    | Running without daemon...
    objc[4694]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
    | Running 4 unit tests...
    | Running 4 unit tests... 1 of 4
    | Failure:  test something(uniquenames245.BarSpec)
    |  Expected exception org.springframework.dao.DuplicateKeyException, but no exception was thrown
        at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:79)
        at uniquenames245.BarSpec.test something(BarSpec.groovy:25)
    | Running 4 unit tests... 2 of 4
    | Error 2015-05-15 16:57:53,055 [main] ERROR spi.SqlExceptionHelper  - Unique index or primary key violation: "UNIQUE_ONE_INDEX_1 ON PUBLIC.FOO(TWO, ONE) VALUES ( /* key:1 */ 2, 0, 'one', 'two')"; SQL statement:
    insert into foo (id, version, one, two) values (null, ?, ?, ?) [23505-176]
    | Completed 2 unit tests, 1 failed in 0m 5s
    | Tests FAILED  - view reports in /Users/jbeutel/proj/grailsSandboxes/uniqueNames245/target/test-reports
    | Error Forked Grails VM exited with error

A work-around is to use an integration test with MySQL, which does not have this problem.  In the generated schema, these unique constraints get the same name, on separate tables.  I wonder if the H2 db handles those names globally, not per table, so enforces only one of them.

My use case is a parent domain with a couple hasMany child domains.  Each child domain belongsTo the parent, with a unique constraint on the parent property and one or more child properties.  So, both child classes are declared in the test's Domain (along with the parent, and other classes).

Single-column unique constraints get a name with a hash, so don't have this problem (I assume).

**Comment by graemerocher** [comment]
Seems like an H2 problem
