### ISSUE TITLE
application.groovy config is ignored

### ISSUE THREAD

**Issue by SmirnoffYM** [grails/grails-core#712]
I've created a new grails 3.0.1 application, but replaced default *application.yml* with custom *application.groovy* config. Besides old default grails configuration (gsps, mime types and so on), there are dataSource and environments settings here:

    dataSource {
        pooled = true
        jmxExport = true
        driverClassName = 'org.postgresql.Driver'
        dialect = org.hibernate.dialect.PostgreSQL9Dialect
        username = 'postgres'
        password = '1234'
    }
    environments {
        development {
            dataSource {
                dbCreate = 'validate'
                url = 'jdbc:postgresql://localhost:5432/mydb'
            }
        }
    
        production {
            dataSource {
                dbCreate = 'validate'
                url = 'jdbc:postgresql://localhost:5432/mydb'
            }
        }
    }

But when I start the application 

    gradle clean run

grails decides to use H2 db settings for some reason.

    2015-May-19 16:59:52 INFO Dialect#<init>:145 - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect

I've tried to output grailsApplication.config properties inside the BootStrap#init() method and got this:

    dataSource.driverClassName = org.h2.Driver
    environments.development.dataSource.url = jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    environments.production.dataSource.url = jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    environments.test.dataSource.dbCreate = update

and so on. The most interesting thing is that if I use default *application.yml* with similarly changed dataSource and environments sections (db url, driver etc) - it works as expected! 
Maybe grails just ignores *application.groovy* file and/or uses some *plugin.yml* (from *org.grails.plugins:cache:3.0.1*) instead of it?

**Comment by jeffbrown** [comment]
> application.groovy config is ignored

Is it really the case that `application.groovy` is ignored, or is it just that `dataSource` properties in particular are not being respected from there?  The latter makes more sense to me than the former.  Is that what is happening?

**Comment by SmirnoffYM** [comment]
Added one line to grails section:

    my.test.property = 'TEST'

and

   notGrails {
       prop = 'TSET'
   }

to the root. These properties are not loaded too, so it seems the whole file is ignored.

**Comment by jeffbrown** [comment]
> it seems the whole file is ignored.

Thanks for the info.  We will investigate.

**Comment by jeffbrown** [comment]
See the project at https://github.com/jeffbrown/appcfg.

The `application.groovy` file at https://github.com/jeffbrown/appcfg/blob/715a16cb93adee7c77ee92fae2e8d66c01de50cb/grails-app/conf/application.groovy defines a property named `my.test.property`.  There is code in `BootStrap.groovy` which prints that value and that appears to work.  `application.groovy` also changes the default dataSource url to use a database named `myDevDb` and that also appears to work.

Do you see anything different in your application that might be relevant?

Thanks for the feedback.

**Comment by SmirnoffYM** [comment]
Your configuration works well, so it means grails doesn't ignore `application.groovy` at all. But if you remove anything from `application.yml` and put into the `application.groovy`, then `my.test.property` and modified dataSource properties (url=myDevDb) will not be available.
See how to reproduce it: https://github.com/SmirnoffYM/appcfg/commit/40c291a2c151f7abc5eed4f421c0e3ecb9b5568e

**Comment by jeffbrown** [comment]
>  But if you remove anything from application.yml and put into the application.groovy, then my.test.property and modified dataSource properties (url=myDevDb) will not be available.

I don't think that is true.  See https://github.com/jeffbrown/appcfg/commit/75b5e7f998a8a702f7ace3881f8d4e0a11182323.

**Comment by SmirnoffYM** [comment]
Woohoo, it works! Thank you! There was no bug at all, but just invalid config. Thank you again!
