### ISSUE TITLE
Grails 2.5.0: Validation of Domain objects not working correctly

### ISSUE THREAD

**Issue by dbpfindexp** [grails/grails-core#713]
Validation of blanks does not work as it throws a null validation error even if blank is specified for field where blank = true.

Example: 
```
package org.grails

class Book {
    String title
    static constraints = {
        title blank: true
    }
}
```
```
package org.grails

import grails.test.mixin.*

@TestFor(Book)
class BookTests {

    /** This does not work if title is set in constructor **/
    void testBlankTitleValidation1() {
        def book = new Book(title: '')
        def valid = book.validate()

        if (! valid) {
            println "Errors ---> ${book.errors}" // Has null field not allowed even though field set to blank
        }

        assertTrue(book.validate())
    }

    /** This seems to work if title is set after the fact **/
    void testBlankTitleValidation2() {
        def book = new Book()
        book.title = ''
        def valid = book.validate()

        if (! valid) {
            println "Errors ---> ${book.errors}" // Does not reach :)
        }

        assertTrue(book.validate())
    }
}
```

Grails 2.5.0, Oracle Java 1.8.0_31-b13, Groovy 2.4.3

**Comment by zyro23** [comment]
i think this is not about validation but data-binding. and behavior looks correct.

domain class constructors use data binding to instantiate domain objects. that means by default, empty strings are trimmed and blank strings are converted to null prior to being bound.

configurable with this config setting: `grails.databinding.convertEmptyStringsToNull = false`
(see http://grails.github.io/grails-doc/2.5.0/guide/theWebLayer.html#dataBinding)

hth, zyro

**Comment by dbpfindexp** [comment]
Has this behavior recently changed?  In Grails 2.1.1. these unit tests work fine.

**Comment by jeffbrown** [comment]
> Has this behavior recently changed? In Grails 2.1.1.

Yes.  The Grails 2.3 release notes at http://grails.github.io/grails-doc/2.3.0/guide/introduction.html#whatsNew23 state the following...

> By default all blank and empty Strings will be converted to null during data binding (configurable)

**Comment by dbpfindexp** [comment]
I added the following and still failing.

```
grails.databinding.convertEmptyStringsToNull = false
grails.databinding.trimStrings = false
```

**Comment by dbpfindexp** [comment]
@jeffbrown is there anything else that needs to be done?  I added the config params to Config.groovy and no go still same error.

**Comment by jeffbrown** [comment]
See https://github.com/jeffbrown/validatestrings/blob/c5e52b139e8f67fe27d47a16fbb8d769badf30ba/test/unit/demo/BookSpec.groovy.  That test passes.  The key is marking the class with `@TestMixin(ControllerUnitTestMixin)`.  We should look at improving things so that isn't necessary, but that is a simple enough way to make things work.  The issue isn't really a validation issue.  It is an issue with the way the `GrailsApplication` and `GrailsWebRequest` are handled in the unit test runtime.

**Comment by ttyusupov** [comment]
@jeffbrown , shouldn't `grails.databinding.convertEmptyStringsToNull` option works in unit tests without specifying `@TestMixin(ControllerUnitTestMixin)` ?
At least it should be probably specified there http://grails.github.io/grails-doc/latest/ref/Constraints/nullable.html, that it won't affect unit tests without `@TestMixin(ControllerUnitTestMixin)`

**Comment by ttyusupov** [comment]
Looks like there is already a fix for that in Grails 3.0.0+: https://github.com/grails/grails-core/commit/c4e5e9f0575668f3e6e00e6e7760eaff4833103e#diff-7d9346e0dd35e329f0f721eecd45a259R206, can it be backported to Grails 2.5?

**Comment by graemerocher** [comment]
Pull requests welcome

**Comment by topr** [comment]
@jeffbrown is there a way to make it work in controller unit test?
I've added the flag in config as well as `@TestMixin(ControllerUnitTestMixin)` on a service unit tests - here it helped. However for controller unit test it doesn't work, I'm afraid...

To be honest, that's kind of irony `ControllerUnitTestMixin` helps for non-controllers unit tests but it doesn't for an actual controller test. `@TestFor(FooController)` doesn't help either.
