### ISSUE TITLE
Meta tag in most of the generated views is not closed properly

### ISSUE THREAD

**Issue by KurtWAndrews** [grails/grails-core#717]
The following meta tag can be found in all of the .gsp files generated by grails 3.0.1

        <meta name="layout" content="main">

it should be closed like this:

        <meta name="layout" content="main" />

It is causing some issues when run from inside IntelliJ IDEA, for example, but not when run-app is used.  I'd like to take a shot at fixing this, if someone would be willing to guide me through the process.  I'm new to this.

**Comment by jeffbrown** [comment]
You can send a pull request to update files like those at https://github.com/grails3-plugins/scaffolding/tree/master/src/main/templates/scaffolding.

Some GSPs already been addressed.  https://github.com/grails/grails-profile-repository/blob/master/profiles/web/skeleton/grails-app/views/index.gsp is one, for example.

If there are others that need to be updated, pull requests are welcome.

Thanks Kurt.

**Comment by KurtWAndrews** [comment]
Jeff,

Here is the output for my

git config --list

user.name=KurtWAndrews

user.email=KurtWAndrews@users.noreply.github.com

Will this work, or do you guys need me to use my gmail account?

**Comment by jeffbrown** [comment]
Is there a reason that you want to use an address like `@users.noreply.github.com`?  We don't really care what your address is but it only makes sense to use a real email address.

**Comment by KurtWAndrews** [comment]
Jeff,

I've completed the following

1. cloned the grails3-plugins/scaffolding repository
2. imported the project into IntelliJ
3. created an issue-717 branch in github
4. made the required change to each of the four gsp files (create, edit, init, show)

I don't see any tests in this repository.  Any thoughts on how these changes could be tested?

When we get to it, Do you prefer a separate pull request for each file, or will one pull request suffice.  I won't publish the changes until we've talked about testing.

Regards,

Kurt

**Comment by jeffbrown** [comment]
> cloned the grails3-plugins/scaffolding repository

It would have been just a small bit more simple had you forked the main repo instead of cloning it, but that isn't a big deal.  As long as you eventually push your changes into a fork of your own, we can get the changes pulled in.  If you aren't sure about how all of that works I will be happy to show you this evening when I see you.

> I don't see any tests in this repository. Any thoughts on how these changes could be tested?

I would not bother with tests for something like this.

> When we get to it, Do you prefer a separate pull request for each file, or will one pull request suffice.

No.  Separate pull request for each file is just a lot of work for no benefit.  Put related changes in a single pull request.  I would put these in a single commit as well.

**Comment by KurtWAndrews** [comment]
You're right, it looks like a fork would have made things cleaner.  This change was trivial so I'll go ahead and start over.  Here are the steps just I'll take to clean up.  Can you please review so that I'm sure that I haven't messed anything up.

1. delete the issue 717 branch I created off of the master
2. delete the local clone of the scaffolding repository
3. fork the scaffolding reposity
4. clone my fork
5. make the changes and commit them to my local clone
6. publish the changes to my fork
7. create the pull request.

Sound right?

Kurt

**Comment by graemerocher** [comment]
Pull request was merged
