### ISSUE TITLE
war packaging does not exclude provided dependencies

### ISSUE THREAD

**Issue by dalibor983** [grails/grails-core#718]
I'm starting to use grails 3.0.1 and I want to build war without embedded tomcat or jetty because I want to deploy war file on application server.

All grails sommands
```
grails war
grails dev war
grails prod war
grails -Dgrails.env=dev war
grails -Dgrails.env=prod war
```
does not exclude provided dependencies from war package like this
```
provided "org.springframework.boot:spring-boot-starter-tomcat"
```

I got excluded provided dependencies only if I use gradle war task
```
gradle war
```
but the only way to control grails environment is to set java system variable "grails.env" on deployment application server

**Comment by dalibor983** [comment]
I found solution, add this in build.gradle configuration
```
springBoot {
    providedConfiguration = "provided"
}
```

**Comment by graemerocher** [comment]
Duplicate of https://github.com/grails/grails-core/issues/585

**Comment by minh-nguyen-va** [comment]
I am using Grails 3.0.1. I added both    provided "org.springframework.boot:spring-boot-starter-tomcat"
& springBoot {
    providedConfiguration = "provided"
}
 per your recommendations to build.gradle and got this "Could not find method springBoot() for arguments [build_ejfuzcw9tvej9e1bcwuehkjpf$_run_closure1@15fe77ca] on root project". 

Thanks
