### ISSUE TITLE
Grails 3.0.1: Failed to start up Grails CLI

### ISSUE THREAD

**Issue by DarlingSunlight** [grails/grails-core#719]
Benjamin@Benjamin-PC /cygdrive/d/dev/git/g3h
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.7.0_67

Benjamin@Benjamin-PC /cygdrive/d/dev/git/g3h
$ grails
| Error Error occurred running Grails CLI: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    org/grails/cli/interactive/completers/RegexCompletor.<init>(Ljava/lang/String;)V @73: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184d 04bd 0004 5903 2c12 1932 121b
    0000010: 2bb9 0021 0300 5359 10ff 1202 b800 272a
    0000020: 5fab 0000 0000 0043 0000 0002 aad3 b1ff
    0000030: 0000 001b 59b3 a684 0000 002e 5f5a 5903
    0000040: 32b8 002d c000 2f5f 57b7 0031 a700 225f
    0000050: 5a59 0332 121b b800 35c0 001b 5f57 b700
    0000060: 38a7 000d bb00 3a59 123c b700 3dbf 57b1
    0000070:
  Stackmap Table:
    full_frame(@60,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@79,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@100,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@110,{Object[#2],Object[#47],Object[#66]},{Object[#68]})
 (Use --stacktrace to see the full trace)

Benjamin@Benjamin-PC /cygdrive/d/dev/git/g3h
$ grails --stacktrace
| Error Error occurred running Grails CLI: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    org/grails/cli/interactive/completers/RegexCompletor.<init>(Ljava/lang/String;)V @73: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184d 04bd 0004 5903 2c12 1932 121b
    0000010: 2bb9 0021 0300 5359 10ff 1202 b800 272a
    0000020: 5fab 0000 0000 0043 0000 0002 aad3 b1ff
    0000030: 0000 001b 59b3 a684 0000 002e 5f5a 5903
    0000040: 32b8 002d c000 2f5f 57b7 0031 a700 225f
    0000050: 5a59 0332 121b b800 35c0 001b 5f57 b700
    0000060: 38a7 000d bb00 3a59 123c b700 3dbf 57b1
    0000070:
  Stackmap Table:
    full_frame(@60,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@79,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@100,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@110,{Object[#2],Object[#47],Object[#66]},{Object[#68]})
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    org/grails/cli/interactive/completers/RegexCompletor.<init>(Ljava/lang/String;)V @73: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184d 04bd 0004 5903 2c12 1932 121b
    0000010: 2bb9 0021 0300 5359 10ff 1202 b800 272a
    0000020: 5fab 0000 0000 0043 0000 0002 aad3 b1ff
    0000030: 0000 001b 59b3 a684 0000 002e 5f5a 5903
    0000040: 32b8 002d c000 2f5f 57b7 0031 a700 225f
    0000050: 5a59 0332 121b b800 35c0 001b 5f57 b700
    0000060: 38a7 000d bb00 3a59 123c b700 3dbf 57b1
    0000070:
  Stackmap Table:
    full_frame(@60,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@79,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@100,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@110,{Object[#2],Object[#47],Object[#66]},{Object[#68]})

        at org.grails.cli.GrailsCli.handleInteractiveMode(GrailsCli.groovy:254)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:196)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Error occurred running Grails CLI: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    org/grails/cli/interactive/completers/RegexCompletor.<init>(Ljava/lang/String;)V @73: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184d 04bd 0004 5903 2c12 1932 121b
    0000010: 2bb9 0021 0300 5359 10ff 1202 b800 272a
    0000020: 5fab 0000 0000 0043 0000 0002 aad3 b1ff
    0000030: 0000 001b 59b3 a684 0000 002e 5f5a 5903
    0000040: 32b8 002d c000 2f5f 57b7 0031 a700 225f
    0000050: 5a59 0332 121b b800 35c0 001b 5f57 b700
    0000060: 38a7 000d bb00 3a59 123c b700 3dbf 57b1
    0000070:
  Stackmap Table:
    full_frame(@60,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@79,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@100,{UninitializedThis,Object[#47],Object[#66]},{Object[#68],UninitializedThis})
    full_frame(@110,{Object[#2],Object[#47],Object[#66]},{Object[#68]})

**Comment by graemerocher** [comment]
Issue with your JDK, use a more recent JDK that doesn't have these bugs in it

**Comment by DarlingSunlight** [comment]
Ya. It works fine with jdk1.8.0_45. And the grails cli is much faster than the 2.x. Thanks you.
