### ISSUE TITLE
Grails 3.0: .gitignore

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#720]
It seems Grails doesn't generate a .gitignore file. That's not a problem, but it would be nice if such a file was generated. Would it be possible to generate such file? Or, if not: which directories should be added to a grails .gitignore file? .gradle and build?

**Comment by graemerocher** [comment]
Sure, yes .gradle and build seem like the right candidates. This should probably be a pull request to the profile repo https://github.com/grails/grails-profile-repository

**Comment by graemerocher** [comment]
Thanks

**Comment by bodiam** [comment]
You're welcome!

**Comment by biniama** [comment]
Thanks for adding this feature. Is it released in version 3.0.1? I am using 3.0.1 but this file was not present.

Is it added to all profiles or just for web?

**Comment by bodiam** [comment]
Hi @biniama , it's a for the next version of Grails, 3.0.2 probably, so it's not in 3.0.1. 

Also, it's added to the default profile, which means it's available in all profiles.

**Comment by biniama** [comment]
Thank you!
