### ISSUE TITLE
createLink does not work for namespaced controllers and generic URL mappings

### ISSUE THREAD

**Issue by tobia** [grails/grails-core#721]
If you have a default URL mapping for namespaced controllers, alongside (before) the one for non-namespaced controllers, such as:

	"/$namespace/$controller/$action?/$id?(.$format)?"()
	"/$controller/$action?/$id?(.$format)?"()

Then g:link and friends lose the "namespace" parameter somewhere along the line and create a broken link, using the non-namespaced URL mapping:

	<g:createLink namespace="myNs" controller="myCtrl" action="myAction"/>

	/app.name/myCtrl/myAction
	         ^ missing /myNs

**Comment by graemerocher** [comment]
Version of Grails?

**Comment by graemerocher** [comment]
Closing due to lack of feedback

**Comment by ncrause** [comment]
Tested and confirmed this is happening to redirect in controllers on version 2.5.2

**Comment by octaviog** [comment]
Hi, I am having this problem in Grails 3.1.6!
