### ISSUE TITLE
Grails 2.5: Compilation errors using groovy trait and @CompileStatic and @Slf4j("LOG")

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#8967]
This is probably a groovy error, but I'm filing it here.  Please feel free to move it.

There are workarounds, but I feel traits are awesome (for composition of behavior), and so are the annotations @CompileStatic and @Slf4j, and so I'd love to see this issue fixed.

Java 8u45
Grails 2.5

Easy to reproduce:
----------------------------------------
```
import org.slf4j.Logger

import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j

@Slf4j("LOG")
@CompileStatic
trait TTest {
  void test1() {
    LOG.debug("Logging test1 ...")
  }
  
  void test2() {
    //((Logger)LOG).debug("Logging test2 ...")
  }
}
```

Results in the following:
| Error Compilation error: startup failed:
..\src\groovy\TTest.groovy: 10: [Static type checking] - Cannot find matching method java.lang.Object#debug(java.lang.String). Please check if the declared type is right and if the method exists.
 @ line 10, column 5.
       LOG.debug("Logging test1 ...")
       ^

```
import org.slf4j.Logger

import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j

@Slf4j("LOG")
@CompileStatic
trait TTest {
  void test1() {
    //LOG.debug("Logging test1 ...")
  }
  
  void test2() {
    ((Logger)LOG).debug("Logging test2 ...")
  }
}
```
Results in the following error:
| Error Compilation error: startup failed:
..\src\groovy\TTest.groovy: -1: Access to TTest#LOG is forbidden @ line -1, column -1.

**Comment by ikakara** [comment]
FYI (for anyone that cares) ...

The workaround:
----------------------------------
```
import org.slf4j.Logger
import org.slf4j.LoggerFactory

import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j

//@Slf4j("LOG")
@CompileStatic
trait TTest {
  final static Logger LOG = LoggerFactory.getLogger(TTest.class)
  
  void test1() {
    LOG.debug("Logging test1 ...")
  }
  
  void test2() {
    ((Logger)LOG).debug("Logging test2 ...")
  }
}
```

**Comment by graemerocher** [comment]
Please report for the Groovy issue tracker

**Comment by allenhealthstack** [comment]
https://issues.apache.org/jira/browse/GROOVY-7439

**Comment by ikakara** [comment]
https://issues.apache.org/jira/browse/GROOVY-7439

**Comment by ntung** [comment]
I got the same issue. Was this marked resolved yet?

**Comment by carlsmartthings** [comment]
I just hit this too, any progress? It might have been intellij bonking as well. I swear it was working for a time...

**Comment by jameskleeh** [comment]
@carlsmartthings To determine if there is progress you would have to look at the groovy jira issue linked above
