### ISSUE TITLE
"gradle war" uses development environment settings

### ISSUE THREAD

**Issue by SmirnoffYM** [grails/grails-core#8968]
Hello.
I'm trying to deploy grails application to the non-embedded Tomcat 7.0.57 container, but during the startup I receive:

    INFO org.grails.plugins.datasource.DataSourceGrailsPlugin - [RuntimeConfiguration] Configuring data source for environment: DEVELOPMENT

despite [the documentation](https://grails.github.io/grails-doc/latest/ref/Command%20Line/war.html).
Build command:

    gradle clean war
But even if I explicitly declare the environment parameter

    gradle clean war -Dgrails.env=production
it still uses development configuration.

To reproduce this, just create a new application, change `compile "org.springframework.boot:spring-boot-starter-tomcat"` to `provided "org.springframework.boot:spring-boot-starter-tomcat"` in `build.gradle` as described [here](https://grails.github.io/grails-doc/latest/guide/deployment.html) and deploy it to your local Tomcat 7.

**Comment by graemerocher** [comment]
You probably need to pass -Dgrails.env=PRODUCTION to your container

**Comment by SmirnoffYM** [comment]
Thanks for your answer. It works, however I hope this is only a temporary workaround and not an official solution :)

**Comment by graemerocher** [comment]
No it is a temporary workaround

**Comment by ioannisGiak89** [comment]
Hello,

Is this still an issue? I am trying to build the WAR file using either `./grailsw` or `./gradlew` in prod and app still runs in development mode. 

I am also getting:
```
INFO 125 --- [ost-startStop-1] grails.boot.GrailsApp                    :  Application starting in environment: development
```

**Comment by niravassar** [comment]
in 3.3.8 you can create an app and test this out. I have verified that a war is created with a production environment
```
- grails create-app test-app
- cd test-app
- ./grailsw war
```

See the log here:

```
$ ./grailsw war
|Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

Total time: 3.831 secs
:compileJava NO-SOURCE
:compileGroovy
:findMainClass
:assetCompile
Processing File 2 of 26 - apple-touch-icon.png
Processing File 3 of 26 - favicon.ico
Processing File 4 of 26 - grails-cupsonly-logo-white.svg
Processing File 1 of 26 - apple-touch-icon-retina.png
Processing File 5 of 26 - grails.svg
Processing File 6 of 26 - skin/database_add.png
Processing File 7 of 26 - skin/database_delete.png
Processing File 8 of 26 - skin/database_edit.png
Processing File 9 of 26 - skin/database_save.png
Processing File 10 of 26 - skin/database_table.png
Processing File 11 of 26 - skin/exclamation.png
Processing File 12 of 26 - skin/house.png
Processing File 13 of 26 - skin/information.png
Processing File 14 of 26 - skin/shadow.jpg
Processing File 15 of 26 - skin/sorted_asc.gif
Processing File 16 of 26 - skin/sorted_desc.gif
Processing File 17 of 26 - spinner.gif
Processing File 18 of 26 - application.js
Processing File 19 of 26 - bootstrap.js
Processing File 20 of 26 - jquery-2.2.0.min.js
Processing File 21 of 26 - application.css
Processing File 22 of 26 - bootstrap.css
Processing File 23 of 26 - errors.css
Processing File 24 of 26 - grails.css
Processing File 25 of 26 - main.css
Processing File 26 of 26 - mobile.css
Finished Precompiling Assets
:buildProperties
:processResources
:classes
:compileWebappGroovyPages NO-SOURCE
:compileGroovyPages
:war
:bootRepackage


:assemble

BUILD SUCCESSFUL

Total time: 3 mins 46.625 secs
|Built application to build\libs using environment: production
```

You can also run 
``./gradlew assemble``

**Comment by niravassar** [comment]
if you would like to create a repo in GIthug and post a project that demonstrates the behavior you describe please check it out. As an alternative I can do the same. Thanks.

**Comment by ioannisGiak89** [comment]
Right! Yeah I could do that.. I am running the project in a docker container. Are you familiar with docker? I can upload instructions of how you can build and run it in the container

**Comment by niravassar** [comment]
yes, please.

Above I mean, "post a project please, and I will check it out", sorry if i typo-ed that

**Comment by ioannisGiak89** [comment]
Hello @niravassar,

Here is the link to the repo that I created https://github.com/ioannisGiak89/grails-war

Sorry for the delay, I was away.

Please feel free to ask me any questions of make any suggestions.
 
Thanks,
Ioannis
