### ISSUE TITLE
Grails 2.4.4 generated controller tests doesn't pass - all redirectedUrls are null

### ISSUE THREAD

**Issue by ppazos** [grails/grails-core#8972]
I've generated the controller and views for this domain using generate-all:

    package directory

    class Folder {

       String name
       String uid = (java.util.UUID.randomUUID() as String)

       Folder parent
       static hasMany = [folders: Folder, items: String]
       static constraints = {
          parent(nullable: true)
          name(empty: false)
       }
    }

After that, running the generated tests, all response.redirectedUrl present in the tests are null.

Is this a bug or the expected behavior?

Example:

    junit.framework.AssertionFailedError: Condition not satisfied:
    
    response.redirectedUrl == '/folder/show/1'
    |        |             |
    |        null          false
    org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@1342946
    
	at directory.FolderControllerSpec.Test the save action correctly persists an instance(FolderControllerSpec.groovy:61)

**Comment by jeffbrown** [comment]
Did you address the TODO in the unit test for the `def populateValidParams(params)` method?  You will want something like this...

    def populateValidParams(params) {
        assert params != null
        params.name = 'some valid name'
    }

Also, and this is unrelated to your problem, but you have `name(empty: false)` in your constraints.  Did you mean to use `name(blank: false)`?

**Comment by jeffbrown** [comment]
@ppazos Can you confirm that addressing the TODO in your unit test does fix the problem?

**Comment by graemerocher** [comment]
Closing due to lack of feedback
