### ISSUE TITLE
Grails generate-all cannot find domainClass

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#8976]
the `generate-all` command cannot find a domainClass by name i.e. `Quest` unless I specify the full package name with the class name, i.e. `quest.Quest`

**Comment by burtbeckwith** [comment]
That's how it's always worked, right? You could have two classes with the same name in different packages.

**Comment by graemerocher** [comment]
in 2.x we used to search the domain class names if no package was specified, so this is a slight regression

**Comment by Schlogen** [comment]
Will be included in the next 3.2 release
