### ISSUE TITLE
Copy grails.assets config from Grails configuration into `AssetCompile` config

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#8978]
I wonder if this is possible so we don't need to duplicate asset config in grails runtime vs. build time. Is it possible to extract the grails config for `grails.assets` and apply to the asset pipeline extension configuration?

**Comment by graemerocher** [comment]
It was discussed with @davydotcom and it would be better of the asset pipeline plugin allowed a configuration file to be specified and took responsibility for loading it
