### ISSUE TITLE
Criteria order by DESC not working

### ISSUE THREAD

**Issue by drziskind** [grails/grails-core#8980]
Using the order clause in a Criteria to sort by 'DESC' no longer works.

HIbernate plugin
Broken: 3.6.10.14 - 3.6.10.19 
Last working version: 3.6.10.13

Grails: 2.3.11

Steps to reproduce:
Create a new grails app
Create a simple domain

Abc.groovy
```groovy
package test

class Abc {

    String word
	
    static constraints = {
    }
	
    String toString(){
	word
    }
}
```

fill with database with test data:

Bootstrap.groovy
```Groovy
import test.Abc

class BootStrap {

    def init = { servletContext ->
		
		new Abc(word:"abc").save()
		new Abc(word:"bcd").save()
		new Abc(word:"xyz").save()
		new Abc(word:"lmn").save()
		new Abc(word:"qrs").save()
		new Abc(word:"nop").save()
		new Abc(word:"jkl").save()
		
		
		def cri = Abc.createCriteria()
		
		def results = cri.list {
			order('word',"asc")
		}
		println results
		
		def cri2 = Abc.createCriteria()
		
		def results2 = cri2.list {
			order('word',"desc")
		}
		println results2
		
		
    }
    def destroy = {
    }
}
```

```
# grails test run-app
```

Printed Lines:
```
[abc, bcd, jkl, lmn, nop, qrs, xyz]
[abc, bcd, jkl, lmn, nop, qrs, xyz]
```
this is regardless of db type, mem or mysql

**Comment by graemerocher** [comment]
I wrote a test (see link above) and verified this works fine in the latest version, in fact I would be very surprised if this was really an issue and there is likely something more subtle going on your app.
