### ISSUE TITLE
Cannot change server port using command line arguments.

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#8983]
I tried `-Dserver.port=8090` and `-Dgrails.server.port.http=8090` with `grails run-app` , but both start Grails at port 8080, only changing the application.yml works by adding:

````
server:
  port: 9090
````

But that's a bit inflexible sometimes

**Comment by zyro23** [comment]
in general it would be really very helpful if `-D` gradle command line args would be passed on as system properties to the boot/grails process. a related discussion can be found here: https://github.com/spring-projects/spring-boot/pull/592

**Comment by graemerocher** [comment]
This works fine for me with:

     $ grails run-app --port=9090

**Comment by zyro23** [comment]
ah i did see the pr from @yamkazu (https://github.com/grails/grails-core/pull/632/files) but just realized now that the cmd args are added as `PropertySource`. works for me as an alternative to system properties. thank you!

**Comment by bodiam** [comment]
Okay, I'm making a pull request for this regarding the documentation, because it's wrong in 77 places. Are system properties still supported? For example, there's a lot of documentation like:

````
Supported system properties:

* @disable.auto.recompile@ - Disables auto-recompilation of Java sources, which can be processor intensive (defaults to @false@)
* @recompile.frequency@ - Specifies how frequently (in seconds) Grails checks for changes to Java and Groovy sources in your project (defaults to 3).
* @grails.server.port.http@/@server.port@ - Specifies the HTTP port to run the server on (defaults to 8080)
* @grails.server.port.https@ - Specifies the HTTPS port to run the server on (defaults to 8443)
* @grails.server.host@/@server.host@ - Specifies the host name to run the server on (defaults to localhost)
````

Is this still applicable?

**Comment by graemerocher** [comment]
No those seem wrong / out of date now. A pull request to correct the docs would be welcome :)

**Comment by bodiam** [comment]
Sure, but would it be possible to answer my question so I can do a proper pull request?

So, are system properties still valid like this, and, if so, is there a list of supported properties, or somewhere I can look at?

**Comment by graemerocher** [comment]
Since we've moved to Spring Boot the system properties available are the same ones at Spring Boot, so anything that can be configured in application.yml can also be configured with a system property. Probably a link to http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html would suffice

**Comment by erichelgeson** [comment]
`grails run-app --port=9090` does not seem to work: 

```
$ grails -v
| Grails Version: 3.0.3
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_45
$ grails create-app test
| Application created at /Users/erichelgeson/source/gr8/test
$ cd test/
$ grails run-app --port=9090 --stacktrace
| Error Failed to start server (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '9090' with class 'java.lang.String' to class 'java.lang.Integer'
	at run-app.run(run-app.groovy:31)
	at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
	at org.grails.cli.profile.DefaultProfile.handleCommand(DefaultProfile.groovy:177)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:239)
	at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:220)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:198)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)
| Error Failed to start server
```

`SERVER_PORT= 9090 grails run-app` does work though via https://stackoverflow.com/questions/28413118/grails-3-change-default-port-for-run-app

**Comment by jeffbrown** [comment]
It looks like `--port=9090` works in 3.0.2 and not in 3.0.3.

**Comment by anshbansal** [comment]
@jeffbrown 
Same issue with stop-app

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/d91c4871ad6d5a053c6b5b2de8fcf4a162f4d150

**Comment by wholenewstrain** [comment]
Using: grails 3.0.17 from Hudson build.

cmd.exe /C E:\grails\grails-3.0.17\bin\grails.bat -Dgrails.env=test  test-app

Hudson is running on port 8080. 
Looked at: https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/test-app.groovy
And there seems to be no way to change the port for test-app.

Getting:
[Test worker] INFO o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"] 2016-06-01 16:53:46.112 
[Test worker] INFO o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"] 2016-06-01 16:53:46.127 
[Test worker] ERROR o.a.coyote.http11.Http11NioProtocol - Failed to start end point associated with ProtocolHandler 
["http-nio-8080"] java.net.BindException: Address already in use: bind at sun.nio.ch.Net.bind0(Native Method)
