### ISSUE TITLE
Grails 3.0.1 - Reloading?

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#8985]
Hi all,

A question about reloading, before I start reporting bugs: when should reloading work? Cause I notice that most often, it doesn't, but maybe this is by design. For example, when I do a `grails run-app`, and add a method to a TagLib, the code is not reloaded, or at least, the new method is not callable from the GSP. Also, when adding new code to src/groovy, the code is not compiled. There are many more cases, and I'm confused when reloading should work. 

(Right now, I assume it never works, and keep restarting my server, because that does work.)

**Comment by graemerocher** [comment]
Instead of reporting a general issue like this which seems more like discussion please report individual issues for cases of reloading that do not work and we can take a look at each

**Comment by bodiam** [comment]
Well, I wanted to prevent false positives by creating this issue. I don't know how or where to ask this otherwise.

**Comment by graemerocher** [comment]
We have a mailing list for dev discussion, feel free to start a thread
