### ISSUE TITLE
Grails 3.0.1 - Adding new tags or tag libraries at runtime doesn't work

### ISSUE THREAD

**Issue by bodiam** [grails/grails-core#8987]
When running with grails run-app, adding a new action to the taglib is not picked up by Grails.

**Comment by graemerocher** [comment]
Seems this is a limitation of Spring Loaded? The new class received by the Grails spring loaded plugin  (which implements `ReloadEventProcessorPlugin`) doesn't contain the new methods when a new closure is defined in a tag library such as:

    def myTag =  { attrs, body ->
    	out << "Hello"
    }

Hopefully @aclement can comment

**Comment by graemerocher** [comment]
Changes to existing tags do however work, so the issue is limited to adding new tags at runtime.

**Comment by aclement** [comment]
My findings so far...

Graeme mentioned that in the debugger he didn't see the new field for the tag being added when the reloadEvent is triggered in GrailsSpringLoadedPlugin.java#L36.

You can't rely necessarily on what you see in the debugger variables view when using agents like this. The class never changes shape regardless of what you do to it outside of the JVM.  What happens is that any calls you make to reflection are rewritten by the agent to return results that include data that did not exist in the original form of the class.

(Graeme, the change you show Graeme in your comment, that seems to manifest as a new field called 'myTag', not a new method - if I'm not checking the right thing let me know but you said 'missing new methods' in your comment)

So what I did was add:

    Field[] fs = clazz.getDeclaredFields();

to the start of the GrailsSpringLoadedPlugin.reloadEvent() method. I then set a breakpoint on the line after that. I knew this reflective call would be intercepted by the agent. I find as I edit my tag lib, the field 'fs' contains the new entries.  So possibly a few things at play that are causing problems but spring loaded seems to basically be working:

1) I am on JDK 180u45, possibly a different JDK level will disturb things. Not sure what you guys have been using.

2) If there is a system class making a reflective call, we might not be rewriting it and that can cause issues. It is expensive to track system classes down that use reflection so instead we have a hard coded list. If something new/different is happening in grails that is using a system class not on our list, it might be making reflective calls that are not intercepted and don't see the new results.

For me to debug further I need to know where is the line that seems to be getting the wrong results back. From my point of view everything in GrailsSpringLoadedPlugin looks ok - so which of the methods in it do you think goes down a path that makes a mistake?

**Comment by bodiam** [comment]
Hi Graeme,

I see you changed the title, but this is not my experience. I have a NPE for example in this line:

    SecurityContextHolder.context.authentication.name

Since authentication can be null for not logged in users. I changed it to this for a running application:

    SecurityContextHolder?.context?.authentication?.name  // just to be sure here

I see that the code is recompiled, but my application still gives a NPE on the same line. See attached screenshot. 

So, no, I don't see reloading of implementations happening.
![screen shot 2015-06-07 at 14 49 01](https://cloud.githubusercontent.com/assets/46468/8024020/668e86ee-0d24-11e5-846a-ed99136d760c.png)

**Comment by jeffbrown** [comment]
This isn't related to you problem but why do you do `SecurityContextHolder?.context`?  I don't think that the class reference (`SecurityContextHolder`) could ever evaluate to null.

**Comment by jeffbrown** [comment]
> I see that the code is recompiled, but my application still gives a NPE on the same line.

I don't know what might be going on in your specific example, but in general I think reloading of existing tags does work.

**Comment by bodiam** [comment]
>  I don't think that the class reference (SecurityContextHolder) could ever evaluate to null.

That was what the comment in the code example was for: `// just to be sure here`. I know it never returns null. I was just making 100% I couldn't get a NPE here, for demo purposes.

**Comment by bodiam** [comment]
> I don't know what might be going on in your specific example, but in general I think reloading of existing tags does work.

I just created a small demo project, but I cannot reproduce the problem there: just rendering a simple string, and then changing it seems to work. Weird. No idea why this case would be different.

**Comment by jeffbrown** [comment]
Your screenshot of the error report suggests that `SecurityContextHolder?.context?.authentication?.name` threw an NPE with "Cannot get property 'name' on null object".

That code really shouldn't be able to cause that.  I wonder if you hit a timing window such that the code that executed was the old code but the code used to generate the error message was the new code.

**Comment by bodiam** [comment]
I know it takes a bit of time to reload the code, so I waited longer than a minute. After that, the code was still failing. Restart -> works.

**Comment by graemerocher** [comment]
@aclement Thanks for the tip regarding not looking at the debugger, using System.out to the console worked better so it does indeed seem that this is not a Spring loaded issue after all. I'm debugging further to isolate ....

**Comment by bodiam** [comment]
Nice fix, thanks!
