### ISSUE TITLE
Resource file's location in test environment

### ISSUE THREAD

**Issue by naman90** [grails/grails-core#8988]
A FileNotFoundException is thrown while reading a file as ClassPathResource() during functional testing. I kept the file under integration-test/resources/file.json. 
It is working in Grails 2.4.4 when a file is kept under test directory.

**Comment by graemerocher** [comment]
Attach an example that reproduces the problem

**Comment by naman90** [comment]
@graemerocher : https://github.com/naman90/grails3.0.1-8988

**Comment by graemerocher** [comment]
Your example is invalid, the file should in `src/integration-test/resources`
