### ISSUE TITLE
Grails 2.4.5: Fails to load using Java 8u45 (spring loaded)

### ISSUE THREAD

**Issue by charlesw** [grails/grails-core#8992]
When trying to load grails command line on Windows 8.1 using Java 8u45 the program exits with the error message ``/Groovy/grails-2.4.5/lib/org.springframework/springloaded/jars/springloaded-1.2.3.RELEASE.jar was unexpected at this time.``

### Steps to reproduce:

1. Download Grails 2.4.5 and set GRAILS_HOME
2. From command line enter: ``grails -version``
3. The message ``/Groovy/grails-2.4.5/lib/org.springframework/springloaded/jars/springloaded-1.2.3.RELEASE.jar was unexpected at this time.`` is printed to the command line and the program exits.

I also have the same behaviour for Grails 2.5, however 3.0.1 works.

### Full Java Version info:

```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Note: I'm new to Grails\Java from .Net and not sure how to get the full exception trace, any instructions here would be appreciated.

**Comment by ikakara** [comment]
Charles - I use Grails 2.5 on Window 8.1 w/ Java (Oracle) SDK 8u45.  

Be sure you've configured the environment correctly:
> Control Panel\System and Security\System -> Advanced system settings -> Environment Variables
GRAILS_HOME =  C:\grails-2.5.0 (or wherever you have your grails folder)
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_45
// Optional - I switch between Java7 and Java8, so I need to set PermGen (for Java7); I like to see how often my app performs GC
GRAILS_OPTS = -Xms256m -Xmx2G -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -verbose:gc
// Check your path for the following
PATH = C:\ProgramData\Oracle\Java\javapath;%GRAILS_HOME%\bin;

Have you tried doing something basic, like:
> grails create-app hello
> cd hello
> grails run-app -https

**Comment by charlesw** [comment]
Thanks, you put me on the right path. I had installed Grails to C:\Program Files (x86)\Groovy\Grails-2.5.0 however moving to C:\Groovy\Grails-2.5.0 fixed it. I'm guessing that Grails\Groovy needs write access to the location or something similar which is why it wasn't working though I'm not sure why that would be the case.

**Comment by fablexis** [comment]
I know this is kinda old, but @charlesw what you did worked for me as well. So for anyone facing a similar problem (working with windows), just try to put the `grails` directory in the root of `C:/`

**Comment by sennuco** [comment]
@charlesw @fablexis  This saved my life today, thanks sooo much! I just dragged and dropped the Grails folder into the `C:/` then ran `grails` from the command prompt and it worked. I searched online for hours!
