### ISSUE TITLE
Grails 2.4.4: Oracle 12c Stream has already been closed

### ISSUE THREAD

**Issue by dorisviv** [grails/grails-core#8993]
Researching this the common answer is not to use Long or Long raw data when querying Oracle via JDBC. That does not apply here. However, the class Building contains a byte[] for an image file, which Hibernate 3 turns into a Blob. Here's what works and what does not:

        def c = Building.createCriteria()
        def result = c {
            campus {
                eq("name", "Main Campus")
            }
            order("bldgCode", "asc")
        }

This criteria query throws java.sql.SQLException: Stream has already been closed

However, this works:
        def c = Building.createCriteria()
        def result = c {
//            campus {
//                eq("name", "Main Campus")
//            }
            order("bldgCode", "asc")
        }

followed by this working:
        result.each {
            println "campus: ${it.campus.name}"
        }

Which means to me that the classes are wired up correctly and the data is there. I don't have this issue with other classes that do not have a byte[] attribute. Work-around is using HQL.

**Comment by graemerocher** [comment]
Please upload an example to github that reproduces the problem

**Comment by dorisviv** [comment]
Seems to be a network/Oracle problem. I installed Oracle locally and the criteria query works fine.

**Comment by graemerocher** [comment]
Thanks for confirming.

**Comment by dorisviv** [comment]
Unfortunately this issue is not resolved, and there are more:
1. Criteria queries generally fail on 1+ associations
2. Where queries continue to fail against Oracle with 1+ associations with "java.sql.SQLException Stream has already been closed", regardless of database being local or on the network
3. HQL queries return attributes as ArrayLists

I have a demo Grails 2.4.4 project with several integration tests that show these failures. Where on github do you want the project?

**Comment by graemerocher** [comment]
Just upload it to your personal account in a new repo

**Comment by dorisviv** [comment]
It's at https://github.com/dorisviv/demo-grails-issue-8993

Working with IntelliJ 14.1.3, Windows 7 Enterprise and JDK 1.7.0_80

**Comment by dorisviv** [comment]
I've resolved the "java.sql.SQLException Stream has already been closed". Working with IntelliJ 14.1.3, the database browser showed byte[] as Blob, but when using Oracle SQL Developer, it's actually a 'LONG RAW' - which Oracle decided it won't support any longer. Added type: org.hibernate.type.MaterializedBlobType, now it is a Blob, streaming works. I've pushed the change to https://github.com/dorisviv/demo-grails-issue-8993.

That leaves the issue of my 3 integration tests, and why HQL, Where, and Criteria queries do not always work the same way. This is really separate from the SQL exception, would you like me to close this case and open a new one?

**Comment by graemerocher** [comment]
Ideally yes

**Comment by dorisviv** [comment]
Move the query issue to https://github.com/grails/grails-core/issues/9042, since it's a separate topic.
