### ISSUE TITLE
Explicit demands cannot be used on static methods

### ISSUE THREAD

**Issue by influenza** [grails/grails-core#8995]
The ['demandExplicit'](http://grails.github.io/grails-doc/2.3.x/api/grails/test/GrailsMock.html#getDemandExplicit()) method of GrailsMock is extremely useful when the existence of a method is required but not known for sure. Unfortunately, this support was not added for static methods.

**Comment by graemerocher** [comment]
`GrailsMock` has been removed in 3.0.x and replaced with usage of Spock's mocking API, since this is not going to be evolved further in the 2.x line I'm closing this, however a pull request is welcome if you want to add the feature yourself.

**Comment by graemerocher** [comment]
The pull request was merged, thanks...
