### ISSUE TITLE
GORM constraint emailValidator does not support new domain suffixes

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#9000]
We discovered from a user that the email:true constraint incorrectly states an email is invalid when using new domain suffixes like '.productions'

**Comment by jeffbrown** [comment]
The `EmailConstraint` class currently simply delegates to the Apache `org.apache.commons.validator.routines.EmailValidator` class.  It may be that there is an updated version of that dependency that we should engage.

**Comment by davydotcom** [comment]
Looks like the EmailValidator itself is deprecated altogether

**Comment by graemerocher** [comment]
Where did you note that EmailValidator has been deprecated?

**Comment by davydotcom** [comment]
http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/EmailValidator.html
--
David Estes

On June 15, 2015 at 6:02:01 AM, graemerocher (notifications@github.com) wrote:

Where did you note that EmailValidator has been deprecated?

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/8e756ab48463c252b239e88400492ef11cf0707e

**Comment by crudolf** [comment]
Could this update also be applied to the 2.5 branch?

**Comment by PatrickHuetter** [comment]
This doesn't seem to work in grails 3.1.8. E-Mails like info@spa-mobil.online get rejected.

**Comment by matthijsbierman** [comment]
For Grails 2.5.6 you can add the following to `BuildConfig.groovy`:

```
compile( "commons-validator:commons-validator:1.4.1" ) {
    excludes 'xml-apis','commons-digester','commons-logging','commons-beanutils', 'commons-collections'
}
```
