### ISSUE TITLE
Grails 2.4.5 : Link Generation API not working in filter in production environment

### ISSUE THREAD

**Issue by rockccf** [grails/grails-core#9007]
I've written a custom filter class to intercept all the post requests to all the controllers, to validate the referral URL of the incoming requests, to see if they are originated from the same server.

There's a Link Generation API that I can call to get the server base URL. 

This will work perfectly if I'm running my grails applciation locally (development environment), I am able to retrieve the server base URL in . (http://localhost:8080/myapp) 

However, when I export it into a war file (grails war), and deploy the war file into tomcat 7, (production environment), the server base URL I retrieved in the filter class is Null.
But, I managed to retrieve the server base URL in my home controller by calling the code.
LinkGenerator grailsLinkGenerator
def index () {
println (grailsLinkGenerator.serverBaseURL)
}

Thanks.

**Comment by graemerocher** [comment]
Please provide an example with steps to reproduce

**Comment by rockccf** [comment]
### The filter class (conf/RefererFilters.groovy)

```
import org.codehaus.groovy.grails.web.mapping.LinkGenerator

class RefererFilters {
	
	LinkGenerator grailsLinkGenerator
	
	def filters = {
		
		def validRefererPrefix = "^${grailsLinkGenerator.serverBaseURL}".replace("http", "https?");
		checkReferer(controller: '*', action: '*') {
			before = {
				if (request.post) {
					def referer = request.getHeader('Referer')
					
					println ("serverURL = "+validRefererPrefix)

					return referer && referer =~ validRefererPrefix
				}
			}
		}
	}
}
```

### The home controller (controllers/HomeController.groovy)

```
import org.codehaus.groovy.grails.web.mapping.LinkGenerator

LinkGenerator grailsLinkGenerator

class HomeController {
	
	def grailsLinkGenerator
	
	def home() {
		page.title = "Home";
		
		String serverURL = grailsLinkGenerator.serverBaseURL;
		println("serverURL = "+serverURL)
		
		return [page:page]
	}
}
```

Managed to print serverURL in both HomeController and RefererFilters if it's run locally (grails run-app)
##### http://localhost:8080/myapp

In production environment (grails war and deployed the war file, using tomcat 7), only managed to print serverURL in HomeController.
##### http://www.mydomain.com/myapp
However, In Referer Filters, the serverURL is Null

Thanks.

**Comment by graemerocher** [comment]
Try move the line

     def validRefererPrefix = "^${grailsLinkGenerator.serverBaseURL}".replace("http", "https?");

Inside the filter closure, since you are defining this line in the context of filter definition, not execution Grails cannot guarantee that grailsLinkGenerator will be set at this point

**Comment by rockccf** [comment]
Great! It works.
Thanks.
