### ISSUE TITLE
Grails 2.5.0: grails wrapper doesn't point to right java version on Mac

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#9009]
On Mac my Java is stored here:
/Library/Java/JavaVirtualMachines/

Currently it only checks:
	# Set JAVA_HOME for Darwin
	if $darwin; then

		[ -z "$JAVA_HOME" -a -d "/Library/Java/Home" ] &&
			export JAVA_HOME="/Library/Java/Home"

		[ -z "$JAVA_HOME" -a -d "/System/Library/Frameworks/JavaVM.framework/Home" ] &&
			export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"

	fi

**Comment by jeffbrown** [comment]
Does the wrapper work if you have `JAVA_HOME` set properly before running `grailsw`?

**Comment by jeffbrown** [comment]
> grails wrapper doesn't point to right java version on Mac

I don't think everyone is going to agree on what "right" is.  Mine happens to be /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home.  I think that may be the default for the Oracle installer.  If there isn’t a convention like linking /Library/Java/JavaVirtualMachines/Home then I don’t think we can really provide a reasonable default.  I don’t think we should have a bunch of complexity in the start script that tries to figure it out.

Suggestions or comments?

**Comment by zaccak** [comment]
I'm using the default oracle install for Java as well on OS X 10.10.3 which is similar to yours.. except I've upgraded to Java 8.

I don't think we need to account for every possible combination, but on Darwin it seems to be pretty standard in the same location for 10.10.x

**Comment by zaccak** [comment]
It does work if I manually set my Java_home... but I thought the rational of the wrapper was to send your project anywhere and it runs with minimal effort.

**Comment by jeffbrown** [comment]
>  I thought the rational of the wrapper was to send your project anywhere and it runs with minimal effort.

It is, but we can only do so much.  If there is a reasonable default that we can use in the file to try and find `JAVA_HOME` then we will do that.  I don't know what that reasonable default would be.  In your original note you said the following:

> On Mac my Java is stored here: /Library/Java/JavaVirtualMachines/

Someone could have any number of versions below that directory.  Here is mine:

    ~ $ ls /Library/Java/JavaVirtualMachines/
    jdk1.7.0_79.jdk    jdk1.8.0_45.jdk

There was a time when the Apple JDK installer would create a symlink at a well known place and a lot of folks would use that for their JAVA_HOME.  As far as I know, modern JDK installers for OS X no longer do that.

What is it that you propose we use as default fallback for JAVA_HOME in the script?

> I don't think we need to account for every possible combination, but on Darwin it seems to be pretty standard in the same location for 10.10.x

Are you saying that on Darwin that `/Library/Java/JavaVirtualMachines/` is your JAVA_HOME?

**Comment by bobbywarner** [comment]
We should always look for Java on Mac at `/usr/bin/java` which is a symlink to `/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java`.

Oracle JDKs are installed in `/Library/Java/JavaVirtualMachines` and most Java developers will have at least two JDKs installed (7 and 8).  In your `.profile` or `.bashrc`, you should set your JAVA_HOME to the JDK you want to use like this:
```
alias java6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6 )'
alias java7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7 )'
alias java8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8 )'
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
```

With this configuration, JDK 7 will be the default in any new terminal and will be used by Grails.  Then if you want JDK 8, you will just type `java8` in your terminal and it will be the new JAVA_HOME and then subsequently used by Grails.  Hope that helps!

**Comment by jeffbrown** [comment]
I think we should probably leave this as is.  The scripts respect JAVA_HOME when it is set, which is what most folks do.  There are lots of ways to easily manage switching between java versions in your shell.  The fallback mechanism that is in the script now may be as good as any.  I don't think we should introduce a lot of complexity around this.

**Comment by sahi123** [comment]
We can use sdkman (http://sdkman.io/install.html) for switching b/w the different java and grails versions. Once you install the needed versions (http://sdkman.io/usage.html) of java. 
You can easily context switch b/w different versions using the following command : 

**sdk use java 7u79**
