### ISSUE TITLE
Grails 3.0.1: Multiple (and different) datasources

### ISSUE THREAD

**Issue by squarepegsys** [grails/grails-core#9011]
This is related to #701 -- probably the same issue.

If you have two datasources with different db  types defined in your `application.yml` it seems to fail.

I have an example project here:
https://github.com/squarepegsys/grails-multi-db

That fails when executing the Bootstrap for the second (non-H2) db. This is different than the integration test, which uses H2 for both.

The error is:

```
ERROR org.hibernate.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: drop table bar if exists
ERROR org.hibernate.tool.hbm2ddl.SchemaExport - Syntax error: Encountered "if" at line 1, column 16.
ERROR grails.boot.GrailsApp - Application startup failed
org.springframework.orm.hibernate4.HibernateSystemException: No Session found for current thread; nested exception is org.hibernate.HibernateException: No Session found for current thread
```

**Comment by graemerocher** [comment]
The cause of this one is #614
