### ISSUE TITLE
run-script command is missing in Grails 3.0

### ISSUE THREAD

**Issue by damluar** [grails/grails-core#9012]
Hello, we used `run-script` command to run our scripts in grails context. After upgrading to 3.0, the command is missing now. Why was it removed and what are the alternatives?

**Comment by graemerocher** [comment]
We'll see if we can add it back in 3.1, but note that the semantics will change because Gant was removed, the target script will have to be a plain Groovy script not a Gant one

**Comment by damluar** [comment]
Any alternative for now?

**Comment by graemerocher** [comment]
Yes you can write an `ApplicationContextCommand` see for example, the `schema-export` command:

https://github.com/grails/grails-data-mapping/blob/master/grails-plugins/hibernate/src/main/groovy/grails/plugin/hibernate/commands/SchemaExportCommand.groovy

Which is implemented in the hibernate plugin. One you have implemented you need to add the JAR which it contains to your Gradle build script classpath.

**Comment by damluar** [comment]
So  if I use gradle I have to use a multi-project build or can I implement it in the same grails project?

**Comment by graemerocher** [comment]
Right.

**Comment by damluar** [comment]
Thank you, if you don't mind 50 points on stackoverflow, you can paste your answers there:
http://stackoverflow.com/questions/30591547/run-script-alternative-in-grails-3

**Comment by Schlogen** [comment]
Done by https://github.com/grails/grails-core/pull/10056
