### ISSUE TITLE
Grails 3.0.1 - before/afterInterceptors not firing in controllers

### ISSUE THREAD

**Issue by busches** [grails/grails-core#9013]
I created a brand new grails app and controller, I had this code in the controller:

```Groovy
package test

class TestController {

    def beforeInterceptor = {
        println "Tracing action ${actionUri}"
    }

    def index() {
        println "In the index action"
        render "test"
    }

    def afterInterceptor = { model ->
        println "Tracing action ${actionUri}"
    }
}
```

Running this only prints out `In the index action`

I also tried them as actual functions instead of closures, even though the documentation says to use a closure: http://grails.github.io/grails-doc/latest/guide/theWebLayer.html#controllerInterceptors

```Groovy
def beforeInterceptor() {
    println "Tracing action ${actionUri}"
}
```
That also did not work.

I also tried modifying shared state:

```
package test

class TestController {
    
    def stuff = [:]

    def beforeInterceptor() {
        println "Tracing action ${actionUri}"
        stuff.moo = true
    }

    def index() {
        println "In the index action"
        render stuff
    }
}
```
When printed, moo is not in stuff, it is an empty hash.

Grails version info:
```
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_45
Windows 7x64
```

I'm not sure if I'm expecting the interceptors to do things they're not designed for or if I need to enable something to get them to fire, but nothing I've tried has worked.

**Comment by graemerocher** [comment]
Duplicates #635
