### ISSUE TITLE
Grails 3.0.2: too much calls beforeInsert/afterInsert/beforeUpdate/afterUpdate per save() in unit test

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9019]
I know twice (even triple) calls are not problem like #2498.

But now it's called too much times in unit test. Additionally, it's increasing per call. And the incremented count is different between using `@TestFor` and `@Mock`.

**Comment by nobeans** [comment]
Both of them are passed though their expected count are very very odd like: 
```
    void "save as create"() {
        when:
        book.save(flush: true)

        then:
        book.countBeforeValidate == 1
        book.countBeforeInsert == 11    // !!!!
        book.countAfterInsert == 11     // !!!!!
        book.countBeforeUpdate == 0
        book.countAfterUpdate == 0
    }
```

* https://github.com/nobeans/grails-issues/blob/master/grails3-issue9019/src/test/groovy/grails3/issue/BookMockSpec.groovy
* https://github.com/nobeans/grails-issues/blob/master/grails3-issue9019/src/test/groovy/grails3/issue/BookTestForSpec.groovy

**Comment by graemerocher** [comment]
Probably caused by the fix for https://github.com/grails/grails-core/commit/f03b0ae36291ec07aa8341e4670375be689fe1ca

**Comment by nobeans** [comment]
Confirmed to be fixed. The counter is just `1` for each test method. Thanks!
