### ISSUE TITLE
Grails 2.5.0: Upgrade to Spring 4.1.6.RELEASE

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#9021]
See https://github.com/spring-projects/spring-framework/releases 

Grails 2.5.0 defaults to Spring 4.1.5.RELEASE ; I've been running 4.1.6.RELEASE (822 commits) w/o any issues (that I know of).   There's a v4.2.0.RC1 which appears to have many "polish" commits.  Anyway, this issue is to let someone (that cares) know that 4.1.6.RELEASE is good (imho) w/ 2.5.0.

**Comment by allenhealthstack** [comment]
@graemerocher - you can close this bug, it appears resolved: https://github.com/grails/grails-core/blob/2.5.x/build.gradle#L43

I'd like to get 2.5.1 deployed asap :)

**Comment by ikakara** [comment]
@graemerocher - you can close this bug, it appears resolved: https://github.com/grails/grails-core/blob/2.5.x/build.gradle#L43

I'd like to get 2.5.1 deployed asap :)

**Comment by ikakara** [comment]
FYI - there's now a 4.1.7.RELEASE  (as well as 4.2.0.RC2) - I'll try 4.1.7 and report my findings.
