### ISSUE TITLE
HibernateTestMixin in 3.0

### ISSUE THREAD

**Issue by ConnorWGarvey** [grails/grails-core#9022]
[Latest documentation recommends use of HibernateTestMixin](http://grails.github.io/grails-doc/latest/guide/testing.html#unitTestingDomains), but the package referenced is for Grails 2.x.  I'd really like to have that feature!  Updated documentation would be nice.

**Comment by graemerocher** [comment]
Available by defining:

     testCompile 'org.grails:grails-datastore-test-support:4.0.4.BUILD-SNAPSHOT'

When 4.0.4 is released that will be 

     testCompile 'org.grails:grails-datastore-test-support:4.0.4.RELEASE'
