### ISSUE TITLE
Grails 3 Upgrade path - Plug-ins to migrate to Grails 3

### ISSUE THREAD

**Issue by hansgru** [grails/grails-core#9023]
As requested on the mailing list:
https://groups.google.com/forum/#!topic/grails-dev-discuss/ZwNpH1MnSGI

to track the plug-ins the users need upgraded to in order to be able to migrate to Grails 3 at all:

 - http://grails.org/plugin/spring-security-core
 - https://grails.org/plugin/spring-security-ldap
 - https://grails.org/plugin/searchable
 - https://grails.org/plugin/audit-logging
 - https://grails.org/plugin/excel-export
 - https://grails.org/plugin/twitter-bootstrap

**Comment by jeffbrown** [comment]
I am not sure how useful it will prove to be to have 1 issue here to track those 6 specific plugins.  Is the idea that this issue will remain open until those 6 in particular have been ported?

**Comment by graemerocher** [comment]
I have already created https://github.com/grails/grails-core/wiki/Grails-3-Priority-Upgrade-Plugins if we can keep the discussion to the mailing list for the moment. Thanks...

**Comment by hansgru** [comment]
The 'searchable' plug-in is however not on the WIKI list :(.
Other users asked it too.

**Comment by graemerocher** [comment]
There is a debate to be had about whether 'searchable' should be upgraded. It is based on compass which was announced as dead and deprecated years ago and the author create Elastic Search which is what people should be using going forward.
