### ISSUE TITLE
No way to install templates/files from plugin on initial install run

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9031]
When an application installs a plugins in their gradle file and runs 'bootRun' or 'run-app', that plugin will be installed (or attempt to be installed).

Previously, we could create an _Install.groovy script to create template files and upload them and update the config. This methodology has been removed and we can no longer load files on initial plugin load. I have tried doing this with 'doWithApplicationContext' but this would mean accessing the JAR and we need access to the PluginManager.

Am I not doing something right or is this an issue?

**Comment by graemerocher** [comment]
Plugins are now just another JAR dependency so yes there is no installation step. If you show me what you are trying to do I can maybe suggest another approach.

**Comment by orubel** [comment]
The furthest I could get on this was to move everything to 'doWithApplicationContext' and try to copy the files with AntBuilder:

String basedir = BuildSettings.BASE_DIR.getAbsolutePath()
basedir = basedir.substring(0,basedir.length()-2)

String pluginDir = new File(getClass().protectionDomain.codeSource.location.path).path

def ant = new AntBuilder()
ant.copy(file:"${pluginDir}/iostate/Hook.json", toFile:"${basedir}/src/iostate/Hook.json", overwrite:false)
ant.copy(file:"${pluginDir}/iostate/IOState.json", toFile:"${basedir}/src/iostate/IOState.json", overwrite:false)
...

This ALMOST WORKS! Problem is... the plugin is in a JAR. So I'm back to square one where I'm assuming I need the plugin manager. Don't want to unpack the JAR and access files. But is that the only way?

**Comment by orubel** [comment]
So is the only way to do this to traverse the JAR?

**Comment by jeffbrown** [comment]
Can you use the same approach is something like `install-templates`?

**Comment by orubel** [comment]
I thought about that but these are files that need to be installed upon plugin install so bootstrap.groovy can see them and initialize service can be run based on them. The plugins bootstrap initialization relies on several files from install being preloaded already

install-templates is not an option as thats a secondary step running with 'bootRun' or 'run-app' would have already caused an error.

**Comment by jeffbrown** [comment]
> ...is not an option as thats a secondary step; installing the plugin with 'bootRun' or 'run-app' would have already caused an error.

I don't think it is unreasonable for a plugin to require a command to be executed to get things started.  There are other plugins that do that.  Generally it is the sort of thing that only has to be done by 1 person 1 time at 1 point in the entire project's lifecycle if the thing that is being generated is a candidate for including in source code control with the rest of the project code.  For example, when folks want to customize the scaffolding templates they only install the templates once.  `s2-quickstart` is another example.

**Comment by orubel** [comment]
So what I'm looking at doing now is using 'java.util.zip.ZipFile' to access the JAR and load the files into the application. Gonna try the classic template methodology and use ant.copy to move them on over. Hopefully that will work. :)

**Comment by orubel** [comment]
A big reason why I have to do alot of this is because I'm trying to create a tool for a distributed architecture and the plugin sets up a master cache for the architecture (wherein the nodes act as slaves to the master) and starts to build this env. These files are needed for that since you are 'running the app'. 

It wouldn't be a big deal if you weren't running the app but since thats a start phase, this has to immediately start with 99.99% uptime as it's default state... not the second pass.

In similar environments where you have distributed architectures and the plugin creates the environment, this may be somehing to consider; that their needs to be an initialization phase for the plugin.

**Comment by orubel** [comment]
Ok so that did the trick. Solved.
