### ISSUE TITLE
Grails 3.0.2 application failed to start at Tomcat 7 if any controller has a String-named method

### ISSUE THREAD

**Issue by SmirnoffYM** [grails/grails-core#9034]
Create blank grails application and add a new controller like this:

```
class TestController {

    def testMethod() {
        render(contentType: "application/json") { [msg: "success"] }
    }

    def "another-test-method"() {
        render(contentType: "application/json") { [msg: "success"] }
    }
}
```

If you run the application via Spring Boot using `gradle clean bootRun`, it will work perfectly. But if you want to create war using `gradle clean war` and deploy it to Tomcat 7 (I used 7.0.57), then `java.lang.ClassFormatError: Illegal method name "another-test-method" in class TestController$$FastClassByCGLIB$$bfb641ee` will be thrown during the deployment. 

There was no such issue in previous release (3.0.1): you can change `grailsVersion` in `gradle.properties` and the application will be successfully deployed.

**Comment by graemerocher** [comment]
As the error shows that isn't really a valid method name, and at the byte code level Java doesn't like method names with hyphens in them. What is the motivation for using a method name like that?

**Comment by SmirnoffYM** [comment]
Hi, I've used such method names only for url mapping purpose, nothing more. Just wondering it stopped working with a new grails version and only with Tomcat.

**Comment by graemerocher** [comment]
If you want this it is better to set your url converter strategy to `hyphenated`

http://mrhaki.blogspot.com.es/2011/12/grails-goodness-customize-url-format.html
