### ISSUE TITLE
unable to use httpclient when integration test

### ISSUE THREAD

**Issue by kasonyang** [grails/grails-core#9036]
I create a grails app,and add a functional test.

`test-app`successful.

then add dependency(because my app needs  it)
`compile "org.apache.httpcomponents:httpclient:4.5"`

then `test-app` failure

It seems that Geb requires httpclient4.3,which conflicts with httpclint4.5.

How to deal with it?

**Comment by graemerocher** [comment]
The version of html-unit that ships with Grails is incompatible with `httpclient` 4.5, as suggested in the `build.gradle`, it is recommended to use a different driver (firefox, chrome, phantomsjs etc.):

https://github.com/grails/grails-profile-repository/blob/master/profiles/web/skeleton/build.gradle#L70

By using one of these drivers you will not have this problem.
