### ISSUE TITLE
How to get value of a domain constraint in Grails 3.0.2

### ISSUE THREAD

**Issue by langcj** [grails/grails-core#9039]
grails 3.0.2

class Lookup {
    static hasMany = [values: LookupValue]

    String realm
    String realmName
    String codeType
    String codeMinimum
    String codeMaximum
    Integer codeScale
    String valueType
    String valueMinimum
    String valueMaximum
    Integer valueScale
    String ordering
    Boolean internationalize
    Date dateCreated
    Date lastUpdated

    static mapping = {
        columns {
            realm index: "lookup_realm_idx"
        }
    }

    static constraints = {
        realm(blank: false, size: 1..100, unique: true)
        realmName(blank: true, nullable: true, size: 1..50)
        codeType(blank: false, inList: ['string', 'integer', 'decimal', 'date'])
}
}

${lookupInstance.constraints.codeType.inList}
--------------------------------------------------------------
Caused by: No such property: codeType for class: org.grails.plugins.lookups.Lookup Possible solutions: codeType

**Comment by graemerocher** [comment]
This was fixed by https://github.com/grails/grails-core/commit/dc5d180fb77d18765307b4d890f50e933942ef98

Though the property name is now `constrainedProperties` and not `constraints`, I will leave this issue open to add a note to the upgrade guide
