### ISSUE TITLE
Grails doesn't reload templates which were included by g:render

### ISSUE THREAD

**Issue by fedotxxl** [grails/grails-core#9040]
1. Run `gradle bootRun`
2. Change main `gsp` page -> check changes -> everything is ok
3. Change template included by `<g:render template=.../>` -> check changes -> grails still renders previous version

v3.0.1

**Comment by lukasjelonek** [comment]
I am facing the same problem. Is there a workaround available?

**Comment by graemerocher** [comment]
I tried to reproduce this with a simple example and was not able to. Please upload an example to Github that reproduces the issue and we can take a look

**Comment by lukasjelonek** [comment]
Tried it again with a brand new grails 3.0.2 Project and it works without problems.

Have to figure out the differences to my project that was created with grails 3.0.1.

**Comment by lukasjelonek** [comment]
Strange, now it works without problems, without the need for changes. I am very sure that it did not work for a long time. This issue can be closed from my side.

Thanks for the help.

**Comment by erichelgeson** [comment]
This is happening to me in Grails 3.0.4 app. Though when trying to create a trivial example, gsp does reload. Have any tips for debugging this further?
