### ISSUE TITLE
Grails 3.0 checkboxes doesn't work with spring-boot-security plugin

### ISSUE THREAD

**Issue by dovydasvenckus** [grails/grails-core#9041]
Few days ago I have upgraded my application from Grails 2.5.0 to Grails 3.0.1. After some time I noticed that all of my checkboxes are automcatically checked. At first I thought that was something to do with that variable is short wrapped as boolean. But later I noticed that even boolean value checkboxes are automatically ticked. 

    <g:checkbox name="test" value=${false}/>
This line of code produces checked chekbox. Any non empty string produces checked checkbox.

I couldn't reproduce this bug in new Grails 3.0.1 project. So I gues it has something to do with upgrading from 2.X to 3.X. 

Here is snipped from my code. I can't give full source code, because this project is not open source. 

Code snipped from my project:

Controller:

    def test(){
        render view: 'test', model: [radioUnit: new RadioUnit(params)]
    }

View:

    ${radioUnit.test}
    <g:form action="save">
                <fieldset class="form">
                       <label class="checkbox">
                            <g:checkBox name="test" value="${radioUnit.test}"/>
                        <i></i>
                        Test
                    </label>
            </fieldset>
            <fieldset class="buttons">
                <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            </fieldset>
        </g:form>

Result:

    <div>
        false
        <form action="/radioUnit/save" method="post">
            <fieldset class="form">
                    <label class="checkbox">
                        <input type="hidden" name="_test">
                        <input type="checkbox" name="test" checked="checked" value="false" id="test">
                        <i></i>
                        Test
                    </label>
            </fieldset>
            <fieldset class="buttons">
                <input type="submit" name="create" class="save" value="Sukurti" id="create">
            </fieldset>
        </form>
    </div>

If I submit this form. Form processing view gets http params where test=false, _false is empty.

I tried to upgrade to 3.0.2. Haven't helped.

Do anybody have any clue? I upgraded to Grails 3 using guide provided in documentation. Only thing I changed after upgrade is that I configured Spring Boot Security.

**Comment by graemerocher** [comment]
Please upload an example to Github that reproduces the problem

**Comment by dovydasvenckus** [comment]
I'm sorry I wasn't able to reproduce it. I tried creating grails 2.5 project and migrating it to grails 3.0.2. But with empty project everything works fine.

I have closed source project with this bug, so I can't share source code. 

Spring boot security plugin probably isn't the cause. Maybe some old Grails2 specific file overides behavior.

**Comment by dovydasvenckus** [comment]
Today got little time to play around and found out what caused this issue. This bug is caused by using spring-boot-security plugin. I created repository that demonstrates this bug. [Link to repo](https://github.com/dovydasvenckus/grails3-integration-spring-boot-security-bug)

@graemerocher could you reopen this issue and take a look?

**Comment by houbie** [comment]
I also have the problem. The cause is the `requestDataValueProcessor` bean that is created by spring security for CSRF protection. 
The `processFormFieldValueIfNecessary` method changes the boolean false into a String "false" and thus groovy wise true:
`value = requestDataValueProcessor.processFormFieldValue(request, name, "${value}", type)`
