### ISSUE TITLE
HQL, Criteria, and Where queries fail where HQL query works

### ISSUE THREAD

**Issue by dorisviv** [grails/grails-core#9042]
1. Criteria queries generally fail on 1+ associations
2. Where queries continue to fail against Oracle with 1+ associations with "java.sql.SQLException Stream has already been closed", regardless of database being local or on the network
3. HQL queries return attributes as ArrayLists

https://github.com/dorisviv/demo-grails-issue-8993

**Comment by jeffbrown** [comment]
> 1. Criteria queries generally fail on 1+ associations
> 2. Where queries continue to fail against Oracle with 1+ associations with "java.sql.SQLException Stream has already been closed", regardless of database being local or on the network
> 3. HQL queries return attributes as ArrayLists

Can you describe the steps required to recreate each of those scenarios in the linked application?

**Comment by dorisviv** [comment]
The project I uploaded to github contains 3 integration tests. Just run the tests?
AddressIntegrationSpec fails at line 79
BuildingIntegrationSpec fails at line 91
SpaceIntegrationSpec fails at line 114 and 155 (remove comment lines)

**Comment by jeffbrown** [comment]
> 3. HQL queries return attributes as ArrayLists

Is that a reference to the fact that `Address.executeQuery("from  Address where zip = '12345'")` returns an `ArrayList`?

**Comment by jeffbrown** [comment]
Several of the failures relate to scoping problems.  You have code like this:

    c.get {
        campus {
            eq("name", "Main Campus")
        }
    }

The problem with that is you have a local variable declared above that with the name `campus` so the runtime thinks you are trying to invoke `campus.call(...)` when you do `campus { ... }`.

**Comment by dorisviv** [comment]
I've since learned that Address.find("from Address where zip = '12345'") returns a single. record. We're down to Criteria queries having issues with the .operator and Where query multiple sort.

**Comment by dorisviv** [comment]
Oh, I didn't realized the local variable would impact a Domain attribute inside the {} of a criteria query. I changed the local variable name and it works - thank you.

**Comment by jeffbrown** [comment]
@graemerocher Do you think dotted paths like `}.order("floor.building.bldgCode", "asc")` at https://github.com/dorisviv/demo-grails-issue-8993/blob/e5d089b72b1b6360ae850b3f9bf20493064c1f97/test/integration/fims/SpaceIntegrationSpec.groovy#L111 are supposed to be supported?

**Comment by dorisviv** [comment]
I assumed, since dotted paths work for Where and HQL queries, I could use them to sort the query results?

**Comment by graemerocher** [comment]
they don't you have to use the `createAlias` method or used nested blocks in criteria
