### ISSUE TITLE
Grails 2.5.0 - JSON.use("cfg", closure) not cleared after rendering

### ISSUE THREAD

**Issue by ph4t** [grails/grails-core#9044]
After the upgrade to grails 2.5 we noticed that the config set through the JSON.use(...) call is not getting cleared after the response is rendered. It seems it "sticks" to the thread and gets used by the next request. 

We can't reliably reproduce it. It starts happening after the application is used for a while. Although we can't reproduce it, we can still prove it's happening with the following filter (executed before controller gets invoked):
```
 def filters = {
jsonConverterConfig(controller: "*", action: "*") {
            before = {
                log.debug "thread id: ${Thread.currentThread().id} . the converter is ${ConvertersConfigurationHolder.getThreadLocalConverterConfiguration(JSON.class)}"
            }
        }
}
```

When everything is working fine we see the following output:
...
thread id: 116 . the converter is null
thread id: 114 . the converter is null
...

However, sometimes the config get's persisted and get's reused by the different requests on the same thread:
...
thread id: 116 . the converter is null
thread id: 114 . the converter is org.codehaus.groovy.grails.web.converters.configuration.DefaultConverterConfiguration@3cd2d651
thread id: 108 . the converter is null
thread id: 114 . the converter is org.codehaus.groovy.grails.web.converters.configuration.DefaultConverterConfiguration@3cd2d651
...

The config should be always null because the filter will log it before the controller is invoked...

**Comment by graemerocher** [comment]
Please upload an example to Github that reproduces the problem

**Comment by ph4t** [comment]
I doubt I'll be able to create a sample project and steps to reproduce it because I don't understand what triggers this behavior. It just starts happening randomly, my guess is because of random allocation of threads to requests?

Anyways, for time being I'm using the following filter to reset the config:
```
def filters = {
        jsonConverterConfig(controller: "*", action: "*") {
            before = {
                JSON.use('default')
            }
        }
    }
```
