### ISSUE TITLE
Grails 3.0.2 "Building" progress console log on server startup is confusing

### ISSUE THREAD

**Issue by BeckyBecs** [grails/grails-core#9046]
This is just a minor issue observed in the console log when running the grails server for the first time after creating the Hello World project example as per the Getting Started guide.

- Installed Grails 3.0.2 for the first time on Mac OS X v10.10.3.
- Then, created the Hello World Example as per https://grails.github.io/grails-doc/3.0.x/guide/gettingStarted.html.
When server is started using the grails console, the console log **">Building 83% > :bootRun"** makes the server startup status confusing since the build is assumed to have been 100% completed before the server is started.  Please see the attached image.
 
![grails3-0-2-inaccurate-console-log-on-startup](https://cloud.githubusercontent.com/assets/3229907/8323578/a8bbc3b6-1a89-11e5-8e0a-9eb38896ad2d.png)

**Comment by olavgg** [comment]
This is the same as issue #641 
Will most likely be fixed for Grails 3.0.3

If you're new to Grails there are a few annoying bugs with Grails 3 and Java 8 at the moment, to get most out of your learning I would recommend Grails 2.5.0 and Java 7. It is very similar to Grails 3 and you will have no problems moving over to Grails 3 later.

Keep in mind however that upgrading a Grails 2 application to Grails 3 isn't straight forward. The best to "upgrade", is to start a new project and copy the code/classes manually. But if you're starting with a big project, jumping on Grails 3 now may good a idea, but at the moment I recommend using Java 7 for Grails 3 development.

**Comment by graemerocher** [comment]
closing as duplicate
