### ISSUE TITLE
Grails 3 Interceptor: No such property: modelAndView for class

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#9048]
I have an interceptor like this:

```java
import static org.springframework.http.HttpStatus.NOT_FOUND
import com.example.Role

class AdministrationInterceptor {

    AdministrationInterceptor(){
        match(namespace: 'administration')
    }

    boolean before() {
        if(session['role'] == Role.ADMIN){
            return true
        }
        render view: '/notFound', status: NOT_FOUND
        return false
    }

    boolean after() { true }

    void afterView() {
        // no-op
    }

}
```

When a user tries to acces with wrong role, I get the following error:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - MissingPropertyExceptionNoStack occurred when processing request: [GET] /administration/dashboard/index
No such property: modelAndView for class: com.example.AdministrationInterceptor. Stacktrace follows:
org.codehaus.groovy.runtime.metaclass.MissingPropertyExceptionNoStack: No such property: modelAndView for class: com.example.AdministrationInterceptor

```
Is this a bug? Or is it me solving this problem wrong?

**Comment by graemerocher** [comment]
Please post the full stack trace

**Comment by olavgg** [comment]
Usually I get a long stack trace, but for this error that is the full stack trace.
![selection_050](https://cloud.githubusercontent.com/assets/2189601/8334693/8736f4c6-1a99-11e5-9f3b-ebd4671812f8.png)

**Comment by graemerocher** [comment]
I will try reproduce locally but if you are able to upload an example that reproduces the issue to Github that would help

**Comment by olavgg** [comment]
I will do that, give me a few minutes

**Comment by olavgg** [comment]
example: https://github.com/olavgg/modelandviewerror

**Comment by graemerocher** [comment]
Seems the `Interceptor` trait doesn't have set/getModelAndView methods. You can workaround this problem by adding the following to your interceptor:

    /**
     * Obtains the ModelAndView for the currently executing controller
     *
     * @return The ModelAndView
     */
    ModelAndView getModelAndView() {
        request..getAttribute(GrailsApplicationAttributes.MODEL_AND_VIEW)
    }

    /**
     * Sets the ModelAndView of the current controller
     *
     * @param mav The ModelAndView
     */
    void setModelAndView(ModelAndView mav) {
        request.setAttribute(GrailsApplicationAttributes.MODEL_AND_VIEW, mav)
    }

**Comment by olavgg** [comment]
Great, thanks!

**Comment by olavgg** [comment]
@graemerocher I just tested this with the daily build. I do not get an error as before, but rendering a view like the default notFound results in blank 404 page.

**Comment by graemerocher** [comment]
@olavgg Please provide an example in a new github issue
