### ISSUE TITLE
grails.gorm.autoFlush does not work

### ISSUE THREAD

**Issue by skiwi2** [grails/grails-core#9050]
Using Grails 3.0.2 the config property `grails.gorm.autoFlush = true` does not affect the `save()` method, that is `save(flush: true)` has different behavior than `save()`.

More information about the issue can be found at http://stackoverflow.com/questions/31049594/why-is-grails-gorm-autoflush-set-to-true-not-working

**Comment by skiwi2** [comment]
The following test does pass:

```
def "grails.gorm.autoFlush is true"() {
    when: "config set"

    then: "equals true"
    Holders.grailsApplication.flatConfig["grails.gorm.autoFlush"]
}
```

**Comment by skiwi2** [comment]
To clarify further, running the following code in a controller **does** work as expected:

```
def index() {
    def email = new Random().nextInt().toString() + "test@test.com"
    def user = new User(email: email, password: "test")
    def user2 = new User(email: email, password: "test")
    def save = user.save()
    def save2 = user2.save(failOnError: false)  //TODO check if this returns false for Groovy truth, also print both saves
    println save
    println save2
    println save as boolean
    println save2 as boolean
    println user
    println user2
    println user.isAttached()
    println user2.isAttached()
    return "test"
}
```

It prints:

> businesssoftware.User : 4
null
true
false
businesssoftware.User : 4
businesssoftware.User : (unsaved)
true
false

However in the following test case:

```
package businesssoftware

import grails.test.mixin.TestFor
import grails.test.mixin.TestMixin
import grails.test.mixin.domain.DomainClassUnitTestMixin
import spock.lang.Specification

/**
 * See the API for {@link grails.test.mixin.domain.DomainClassUnitTestMixin} for usage instructions
 */
@TestFor(User)
@TestMixin(DomainClassUnitTestMixin)
class UserSpec extends Specification {
    def "save valid user"() {
        when: "user is valid"
        def user = new User(email: "test@test.com", password: "test")

        then: "user should be saved"
        user.save()
    }

    def "email should be valid"() {
        when: "email invalid"
        def user = new User(email: "invalid", password: "test")

        then: "saving should fail"
        !user.save(failOnError: false)
    }

    def "email should be unique"() {
        when: "twice same email"
        def user = new User(email: "test@test.com", password: "test")
        def usersmth = new User(email: "ff@ff.com", password: "test")
        def user2 = new User(email: "test@test.com", password: "test")

        then: "saving should fail"
        user.save()
        usersmth.save()
        //TODO grails.gorm.autoFlush does not work on user.save() for whatever reason - does work in a controller
        !user2.save(failOnError: false)
    }
}
```

It fails because `user2.save(failOnError: false)` returns `true`, rather than the expected `false` due to the violated unique email constraint.

**Comment by skiwi2** [comment]
After more investigation it turns out that even when calling `user.save(flush: false)` in the controller, the second user is not saved as it doesn't pass validation because it violates the unique email constraint.

Then why is this behavior different in the test case?

**Comment by graemerocher** [comment]
In general we try to replicate Hibernate's flush behaviour as closely as possible, but fundamentally the unit test environment operates against an in-memory map and not a real database so the behaviour can differ for certain cases. If you want to integration test your data access you are better off with an integration test.
