### ISSUE TITLE
Gradle setup for HibernateTestMixin missing

### ISSUE THREAD

**Issue by skiwi2** [grails/grails-core#9052]
Looking at the documentation of https://grails.github.io/grails-doc/latest/guide/testing.html#unitTestingDomains under "HibernateTestMixin Basics" the Groovy-style build configuration is suggested, but since Grails 3 apps are created with a Gradle-based configuration.

It is confusing to see the Groovy-style configuration and not straight forward how to translate it to a Gradle-based configuration.

As a result of this I also don't know how to use the HibernateTestMixin right now.

**Comment by graemerocher** [comment]
I have migrated these mixins to the core data project and we will do a new release with Grails 3.0.3

https://github.com/grails/grails-data-mapping/commit/9a6e067fb200ba0239ea70dd5989c4c64e46ad48
