### ISSUE TITLE
Action is called twice in single request in grails with <script src="" />

### ISSUE THREAD

**Issue by mariomatar** [grails/grails-core#9054]
Hi,

I see controller's action is called twice for each request, but second time without params.
I found the problem, in my layout I have : 

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>

By removing this lines, the problem is solve.

Have you an idea who to solve this issue ?

Grails 2.5.0
Java 8u25

Regards

**Comment by jeffbrown** [comment]
> I see controller's action is called twice for each request

Have you verified that the action really is being called twice for each request, as opposed to a second request coming in?

**Comment by jeffbrown** [comment]
The reason I ask is I can't think of any reason that having those `script` tags in your GSP might cause your actions to be called multiple times for each request, but I can think of reasons that they might cause a second request to be initiated.

Thanks for your feedback.

**Comment by mariomatar** [comment]
Hi jeffbrown

Yes I verified, for each request (click on a homepage link), I have 2 requests. I use debug mode to see.
I notice that long time ago, but now it's a problem because second call changes session variables.
I can include javascript files in my projet and not use CDN. 

I don't know how to show you that. Maybe screenshot ?
And maybe there is other things influence this behavior.

**Comment by mariomatar** [comment]
I finally found the real problem, an old facebook like integration javascript code : 

<script>
	(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1"; //ici pour changer la langue: remplacer fr par us
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
	$(document).ready(function() {
		var urlCookie = $("#urlCookie").val();
		$.get(urlCookie);
	});
</script>

now it's works fine !
