### ISSUE TITLE
GrailsExceptionResolver does not work correct with URL mapping incl. exceptions

### ISSUE THREAD

**Issue by dunkelrot** [grails/grails-core#9055]
In case you have a URL mapping like
static mappings = {
"500"(controller:'book', action:"missingPage", exception: MissingPageException)
}
and an exception is thrown, GrailsExceptionResolver will use
mv.addObject(WebUtils.EXCEPTION_ATTRIBUTE, new GrailsWrappedRuntimeException(servletContext, e));
to set the Exception as an attribute of the request, WebUtils.EXCEPTION_ATTRIBUTE is "exception".

How ever, later in 
UrlMappingsHandlerMapping.getHandlerInternal 
def exception = request.getAttribute(WebUtils.ERROR_EXCEPTION_ATTRIBUTE)
is used to get the exception from the request, WebUtils.ERROR_EXCEPTION_ATTRIBUTE is "javax.servlet.error.exception", thus the defined error handler is not found.

Note: In my case an AccessDeniedException is thrown by Spring.Security during controller method execution.

**Comment by roblouie** [comment]
Having this exact issue when throwing that same AccessDeniedException.

**Comment by graemerocher** [comment]
@roblouie @dunkelrot  Please could one of you upload an example to Github that reproduces the issue. Thank you.

**Comment by dunkelrot** [comment]
Hope this helps:
https://github.com/dunkelrot/grail-auth-exception

There are two entries in UrlMappings.groovy, one that works and one that fails.
Open URL: http://localhost:8080/auth/restricted
With the view mapping is shows a "Access Denied" message, with the controller mapping it shows the default exception handler page.
