### ISSUE TITLE
grails.gorm.default.mapping not working in application.groovy in grails 3.0.2

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9056]
I have most all of my properties in application.yml. I have only the below in my application.groovy. 

```
grails.gorm.default.mapping {
    version false
}
```

After that I started the application. But there was a `version` property created in the table. I am using the default h2 database currently.

**Comment by anshbansal** [comment]
I tried using the mapping block in the domain class. Still the database table had the version field.
```
static mapping = {
        version: false
    }
```

**Comment by todoubaba** [comment]
```
grails.gorm.default.mapping = {
    version false
   ...
}
```

**Comment by anshbansal** [comment]
That worked. But should having the incorrect default stop mappings in domain classes to also stop working?
