### ISSUE TITLE
Grails 2.5.0 gorm save method not working properly

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9064]
I was getting a domain object via a dynamic finder in a Service. Then passing a property to another method. In the other method I was again getting the object again by a dynamic finder using the passed property. The property was unique so no issues. Bad design but that was what I was doing.

I saved the domain object but it was not getting saved. I tried failOnError as well as flush but did not work. No errors but not getting saved.

I passed the domain object instead of using dynamic finder into the other method and it worked.

There should have been an exception/warning or something.

**Comment by graemerocher** [comment]
From your description it sounds like you are passing objects across transactional boundaries which of course will cause issues like this since each service method is transaction.

**Comment by anshbansal** [comment]
Actually it is the opposite. 

It was not working when I was passing Strings. When I passed domain objects then it worked.

**Comment by graemerocher** [comment]
Upload an example to Github that reproduces the problem

**Comment by anshbansal** [comment]
I can reproduce it on my local but that is with the particular client code and data. As unable to share that closing this.
