### ISSUE TITLE
Grails 2.4.3: URLMapping unit test for RESTfull service is not working

### ISSUE THREAD

**Issue by oleg-cherednik** [grails/grails-core#9065]
_UrlMappings.groovy_
```groovy
class UrlMappings {
    static mappings = {
        '/filters'(resources:'filter')
    }
}
```
_grails url-mappings-report_

HTTP Method | URI | Controller | Action
------------ | ------------- | ------------ | ------------
GET | /filters | filter | index
GET | /filters/create | filter | create
POST | /filters | filter | save
GET | /filters/${id} | filter | show
GET | /filters/${id}/edit | filter | edit
PUT | /filters/${id} | filter | update
PATCH | /filters/${id} | filter | patch
DELETE | /filters/${id} | filter | delete

_UrlMappingsSpec.groovy_
```groovy
@TestFor(UrlMappings)
@Mock([FilterController])
class UrlMappingsSpec extends Specification {
    def 'Ensure basic mapping operations for Filter uris'() {
        expect:
        assertForwardUrlMapping('/foo/666', controller: 'filter', action: 'show')
    }
}
```

**PROBLEMS**
* This test throws exception: _junit.framework.AssertionFailedError: url '/foo/666' did not match any mappings_
* This test cannot check same _uris_ with different _http method_

**SOLUTION**
I think, that problem is in _UrlMappingsUnitTestMixin.assertForwardUrlMapping(assertions, url, paramAssertions)_ implementation. This method should provide _http mehtod_ to match existed mappings (use _UrlMappingsHolder.matchAll(String uri, String httpMethod)_ instead of _UrlMappingsHolder.matchAll(String uri)_).

_UrlMappingsUnitTestMixin.groovy_
```groovy
class UrlMappingsUnitTestMixin extends ControllerUnitTestMixin {
    // ...

    // void assertForwardUrlMapping(assertions, url, paramAssertions) {
    void assertForwardUrlMapping(assertions,  httpMethod, url, paramAssertions) {
    // ...
        def mappingInfos
        if (url instanceof Integer) {
            mappingInfos = []
            def mapping = mappingsHolder.matchStatusCode(url)
            if (mapping) mappingInfos << mapping
        }
        else {
            // mappingInfos = mappingsHolder.matchAll(url)
            mappingInfos = mappingsHolder.matchAll(url, httpMethod)
        }
    // ...
    }

    // ...
}
```

And correct test should look like:
```groovy
@TestFor(UrlMappings)
@Mock([FilterController])
class UrlMappingsSpec extends Specification {
    def 'Ensure basic mapping operations for Filter uris'() {
        expected:
        assertForwardUrlMapping(httpMethod, url, controller: expectCtrl, action: expectAction) {
            id = expectId
        }

        where:
        httpMethod | url                 | expectCtrl | expectAction | expectId
        'get'      | '/filters'          | 'filter'   | 'index'
        'get'      | '/filters/create'   | 'filter'   | 'create'
        'post'     | '/filters'          | 'filter'   | 'save'
        'get'      | '/filters/666'      | 'filter'   | 'show'       | 666
        'get'      | '/filters/666/edit' | 'filter'   | 'edit'       | 666
        'put'      | '/filters/666'      | 'filter'   | 'update'     | 666
        'patch'    | '/filters/666'      | 'filter'   | 'patch'      | 666
        'delete'   | '/filters/666'      | 'filter'   | 'delete'     | 666
    }
}
```

**Grails version 2.4.3, but in last 3.0.2 it still exists**

**Comment by graemerocher** [comment]
Pull requests welcome

**Comment by oleg-cherednik** [comment]
???

**Comment by graemerocher** [comment]
I can see the amount of effort you put into the description is admirable, I just wish people put the same amount of effort into actually creating pull requests :-)

**Comment by oleg-cherednik** [comment]
Ok, little bit later I do pull request.

**Comment by joemccall86** [comment]
I'd like to work on this. Our project already sub-classes UrlUnitTestMixin, so all I need is to write a proper test for it and submit a PR. So far I can confirm it still exists in 3.0.8. I just don't want to step on any toes if you're already working, @oleg-cherednik.

**Comment by joemccall86** [comment]
Also, the JIRA issue for this is https://jira.grails.org/browse/GRAILS-10609, in case anyone searches for it.

**Comment by graemerocher** [comment]
That would be great.. thanks
