### ISSUE TITLE
Integration tests fail when using multiple datasources

### ISSUE THREAD

**Issue by roadrunner2** [grails/grails-core#9068]
When using multiple datasources, integration tests using transactions in the setupSpec will fail with an UnexpectedRollbackException. A minimal sample project is available at https://gist.github.com/d2e416f2539f51945b1d.git (base64decode and unzip - if there's a better way "attach" things, let me know).

I've debugged this and found the cause for it. In [GrailsTestTransactionInterceptor](https://github.com/grails/grails-core/blob/master/grails-test/src/main/groovy/org/grails/test/support/GrailsTestTransactionInterceptor.groovy) it builds up a list of transaction-managers, and then calls rollback on each one at the end of the test. The problem now stems from the fact that the default dataSource's transaction-manager is actually a ChainedTransactionManager, which means that in destroy() it ends up doing a rollback twice on the second datasource's transaction-manager (first indirectly via the ChainedTransactionManager, and then again via a direct call in GrailsTestTransactionInterceptor.destroy()).

I'm not sure of the correct fix, but just not adding the non-default datasources to the transactionManagers (e.g. by commenting out the [lines 49 - 53](https://github.com/grails/grails-core/blob/master/grails-test/src/main/groovy/org/grails/test/support/GrailsTestTransactionInterceptor.groovy#L49-L53)) does solve the problem in this instance.

This was encountered and debugged on grails 2.5.0.

**Comment by graemerocher** [comment]
@lhotari Do you know the correct way to handle this given your experience of `ChainedTransactionManager`
