### ISSUE TITLE
@BindUsing closure on command object's field doesn't get executed

### ISSUE THREAD

**Issue by gilinykh** [grails/grails-core#9070]
Grails 3.0.2
Having the following code in controller: 
```groovy
class TestController {

    def index() { }

    def hello(TestCommand cmd) {
        log.debug("Command received: ${cmd.dump()}")
    }
}

class TestCommand {
    @BindUsing({ obj, source ->
        source['PayerID']
    })
    String payerId

    static constraints = {
        payerId(nullable: true)
    }
}
```

And then accessing url __http://localhost:8080/test/hello?PayerID=test__
I can see that ```payerId``` is not bound.

**Comment by jeffbrown** [comment]
I don't think this is a bug.  Your request parameter is named `PayerID` and your property is named `payerId`.  The documentation for `BindUsing` at http://grails.github.io/grails-doc/3.0.2/guide/theWebLayer.html#dataBinding states the following:

    Note that data binding is only possible when the name of the request parameter matches with the field name in the class.
    
The simplest way to achieve what it looks like you are trying to achieve is to simply make the request parameter name match the property name.

**Comment by gilinykh** [comment]
Apparently you're right. I re-read the docs and realized that indeed this is not how it's supposed to work.
