### ISSUE TITLE
Add multitenancy support in GORM

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9073]
Starting from Hibernate 4, multitenancy support is built in for both separate DB and separate schema use cases. In Hibernate 5 (which is RC), they are implementing discriminator (tenantId) based support as well. Many attempts have been made on grails side to implement multitenancy but were in different direction. One such implementation is multitenant plugin which is for hibernate3. It is based on interceptors which was logical at time when there was no such support in Hibernate. Another attempt is made in gr8crm which is adding discriminator in domain classes and manually handling GORM queries with this discriminator (again a hack).

In my opinion, the right direction should be to implement this in GORM either for Hibernate4 or Hibernate5 (coming soon). Both have built in multitenancy support. Hibernate4 however lacks discriminator based support.

**Comment by graemerocher** [comment]
Yes the logical thing to do is to build on Hibernate 5's built in support when we create a Hibernate 5 version of GORM

**Comment by ejaz-ahmed** [comment]
Hibernate 5 is released but discriminator based multitenancy support is not announced in release notes and documentation is also not updated properly. Here is an ambiguous statement from [Hibernate5 docs](http://docs.jboss.org/hibernate/orm/5.0/userGuide/en-US/html_single/#d5e3197):

```
DISCRIMINATOR
Correlates to the partitioned (discriminator) approach. It is an error to attempt to open a session without a tenant identifier using this strategy. This strategy is not yet implemented in Hibernate as of 4.0 and 4.1. Its support is planned for 5.0.
```

**Comment by ejaz-ahmed** [comment]
Hibernate team dropped discriminator based multitenancy for Hibernate 5. Here is the [relevant Jira](https://hibernate.atlassian.net/browse/HHH-6054) which is still open

**Comment by ajdevries** [comment]
I'm building a Grails application for a client of mine. With multitenant support. I'm not using a plugin but build one myself. Is working quite well in Grails 3.0 using
- an interceptor
- a Hibernate filter
- and some traits

I'm relatively new to Grails and the community but could help if there is any interest in this feature.

**Comment by graemerocher** [comment]
@ajdevries Sounds like a great plugin

**Comment by ejaz-ahmed** [comment]
@ajdevries I wiill be porting a grails 2.3 application to grails 3 in upcoming weeks. Would love to see your  approach and probably we can workout to make it standalone plugin. Can you push your multitenant specific code to any separate repo with some working example?

**Comment by ajdevries** [comment]
@ejaz-ahmed I'll give it a try, maybe we could join the effort, 'll setup a public github repo @ my account.

**Comment by ionutab** [comment]
Just had a slack chat with @ejaz-ahmed . I'm willing to help with this.

**Comment by ejaz-ahmed** [comment]
I am done with spring security based tenantResolver which works with two field as well as three field (user, organization, password) authentication. Url based tenant resolver is contributed by @ionutab which is not yet integrated. Current implementation is filtering results with tenantId based dynamic finders. 
I have a trait named Multitenant which has a property called tenantId and all multitenant classes are implementing this trait.
Next task is to automate queries so that tenantId filter is automatically applied. My approach to achieve this is to add hibernate filter in a trait implemented by Multitenant classes. Right now I'm stuck with adding hibernate filter plugin in my plugin. I get ClassNotFoundException for org.grails.plugin.hibernate.filter.HibernateFilterDomainConfiguration even though I've followed all the steps mentioned here https://github.com/fingo/grails-hibernate-filter
@ajdevries how did you added hibernate filter support in grails3? Hibernate filters are working for grails2 for me but not for grails 3. After all those steps failed, I've tried adding jar to my build.gradle using following way:

```
repositories {
    flatDir {
        dirs 'libs'
    }
}


dependencies {
    compile name: 'grails-hibernate-filter-0.1.2'
}
```
I placed  grails-hibernate-filter-0.1.2.jar in libs folder of the root of my application but got same exception.

**Comment by ajdevries** [comment]
Hi @ejaz-ahmed. Here are my code sample... Didn't have the time to put things on github, and not completely satisfied with my solution so far. Still fighting with the Trait and the GORM validations. I didn't use a plugin. In hibernate4 the api for filters is changed, that's why the 'old' way isn't working. I did look at your plugin to get this working :-)

Add an alternative HibernateConfig:

``` groovy
class HibernateFilterDomainConfiguration extends GrailsAnnotationConfiguration {

	private Logger log = LoggerFactory.getLogger(getClass())
	private GrailsApplication grailsApplication
	private boolean configLocked

	@Override
	void setGrailsApplication(GrailsApplication grailsApplication) {
		super.setGrailsApplication grailsApplication
		this.grailsApplication = grailsApplication
	}

	@Override
	protected void secondPassCompile() throws MappingException {
		if (configLocked) {
			return
		}

		super.secondPassCompile()

		this.addFilterDefinition new FilterDefinition("tenant", "tenant_id = :tenant", [tenant: this.typeResolver.basic('long')])

		for (domainClass in grailsApplication.domainClasses) {
			if (domainClass.clazz in Tenantable) {
				log.debug "Enricht ${domainClass} with tenant filter"
				def entity = this.getClassMapping(domainClass.fullName)
		        entity.addFilter("tenant", "tenant_id = :tenant", false, null, null)
			}
		}
		configLocked = true
	}
}
```

Add this one the config:
```yaml
dataSource:
    pooled: true
    jmxExport: true
    dbCreate: ''
    configClass: 'app.HibernateFilterDomainConfiguration'
```

And enable filters (in an interceptor) for the specific domain entities
```groovy
class TenantInterceptor {
    def tenantService
    def sessionFactory

    TenantInterceptor() {
        matchAll()
        .excludes(uri:'/assets')
        .excludes(controller: 'auth')
    }

    boolean before() {
        // tenant selection based on url
        def name = tenantService.name(request.serverName as String)
        Tenant t = Tenant.findByName(name)
        if (t == null) {

        } else {
            sessionFactory.currentSession?.enableFilter('tenant')?.setParameter("tenant", t.id)
            log.info "Tenant with name $t selected"
            tenantService.tenantId = t.id
        }
        t != null
     }
```

Trait looks like this. But logic needs to move to the hibernate interceptor, but that's not working, like I hoped it should work. `PreInsert` event is after insert. So beforeInsert in `Tenantable` works better.

```groovy
trait Tenantable {
    def tenantService
    Tenant tenant

    def beforeInsert() {
        setupTenant()
    }
    
    def beforeUpdate() {
        setupTenant()
    }
    
    void setupTenant() {
        if (tenant == null) {
            tenant = tenantService.tenant
        }
    }
}

```
I also didn't use the Spring Security plugin, when I started this, it wasn't grails 3.0 ready. And so far the Spring Boot Security is working okay.

N.B. Keep in mind that with a `Domain.get(<id>)` the tenant filter isn't working (hibernate thing). So always use a finder i.e. `Domain.findById(<id>)`

Is there somewhere I can see your progress, maybe (when there is time :-) ) I can contribute some of this stuff.

**Comment by ejaz-ahmed** [comment]
@ajdevries thanks for the provided information. I am able to automate create, update. delete and validate operations using Gorm events only except for loading data from database. So far things are portable as nothing hibernate specific is being used. This will make it valid for NoSQL dbs as well. So I am avoiding hibernate stuff so far. Let's see if I can do so without using hibernate. I'll push my code to github in a day or two.

**Comment by ejaz-ahmed** [comment]
@graemerocher Can I get the reference to query which is triggering onLoad event in GORM?

**Comment by ejaz-ahmed** [comment]
Basic version of plugin is out. Here is repo https://github.com/ejaz-ahmed/grails-multitenant-plugin
I am facing some problems in publishing it to bintray. Will post this in slack channel.
