### ISSUE TITLE
Assets pipeline does not encode utf-8 html files properly

### ISSUE THREAD

**Issue by tony75** [grails/grails-core#9075]
Hi,

I have an angular app made of a main gsp view, and html templates loaded async by angular.
The html templates are located in the grails-app/assets/templates folder.

When I use utf8 in the gsp view, everything works. But when I use utf8 accents (e.g. 'é') in an html asset, and access it with my browser (http://localhost:8080/assets/home.html for example) the files are not utf8-encoded :

![localhost8080assetshomehome html - google chrome](https://cloud.githubusercontent.com/assets/3809685/8499482/b8fce8d4-2193-11e5-8951-96cb00e0f5a0.jpg)

The content type of the gsp returned by grails is "text/html;charset=UTF-8" while the one of the html asset is "Content-Type:text/html" : the charset seems to be ignored

**Comment by graemerocher** [comment]
Please report to https://github.com/bertramdev/asset-pipeline-core
