### ISSUE TITLE
gradle docs plugin not reading the properties from application.groovy or application.yml

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9078]
I was building quartz docs when I noticed that gradle docs command is not reading the properties from either application.yml or application.groovy. 

So basically all the below properties are not working
```
grails.doc.title - The title of the documentation
grails.doc.subtitle - The subtitle of the documentation
grails.doc.authors - The authors of the documentation
grails.doc.license - The license of the software
grails.doc.copyright - The copyright message to display
grails.doc.footer - The footer to use
```

I looked the code of grails doc command. I am not familiar with how gradle plugins are written but by looking at [PublishGuide](https://github.com/grails/grails-core/blob/master/grails-docs/src/main/groovy/grails/doc/gradle/PublishGuide.groovy) it seems that the property file has been changed to $projectRoot/resources/doc.properties. Also the mentioned properties are not being read at all.

**Comment by anshbansal** [comment]
Where is the location where the docs command is exposed? I was unable to find that. If I was looking at the correct place then I will try to send a PR for this.

**Comment by graemerocher** [comment]
Will look into this, thanks for the report
