### ISSUE TITLE
Grails 2.5.0: Upgrade to Groovy 2.4.4 (Fixes Problems With CompileStatic And Interface Methods In Abstract Subclass)

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#9079]
It appears they fixed https://issues.apache.org/jira/browse/GROOVY-7416 - Problems With CompileStatic And Interface Methods In Abstract Subclass

**Comment by graemerocher** [comment]
Groovy 2.4.4 is not out yet

**Comment by jeffbrown** [comment]
I have pushed some relevant changes to the issue_9079 branch at https://github.com/grails/grails-core/commits/issue_9079.  There were some compile errors and now at least 1 failing test after updating to Groovy 2.4.4.

**Comment by jeffbrown** [comment]
https://issues.apache.org/jira/browse/GROOVY-7509

**Comment by jeffbrown** [comment]
We should reference https://issues.apache.org/jira/browse/GROOVY-7509 and https://issues.apache.org/jira/browse/GROOVY-7505 in the Grails 2.5.1 release notes.
