### ISSUE TITLE
Grails Support for Eclipse 4.5 Mars

### ISSUE THREAD

**Issue by nagkumar** [grails/grails-core#9080]
Unable to find grails support on latst eclipse and sts 3.7 upgrade

![grailsplugin](https://cloud.githubusercontent.com/assets/332234/8507934/1269315a-2277-11e5-9456-cea37c9274b9.png)

**Comment by ejaz-ahmed** [comment]
Pivotal has stopped its support for grails.

**Comment by nagkumar** [comment]
Thank You. What is the impact of this on Groovy, Grails and Grails Support Plugin.

**Comment by jeffbrown** [comment]
The issue tracker here probably isn't the best place to carry on that discussion.  I recommend the contacting Pivotal, starting a discussion on the mailing list at https://groups.google.com/forum/#!forum/grails-dev-discuss or filing a request in the issue tracker at https://issuetracker.springsource.com/browse/STS if you wish to file a bug report or feature request for STS.
