### ISSUE TITLE
Grails 3.0.2 can't run selected test suite

### ISSUE THREAD

**Issue by dovydasvenckus** [grails/grails-core#9082]
I'm trying to run unit test without running integration tests, but I always get error.

    grails test-app unit:
    * What went wrong:
    Execution failed for task ':test'.
    No tests found for given includes: [unit:]

Can't run integration tests isolated too. 

    grails test-app integration:
    * What went wrong:
    Execution failed for task ':test'.
    > No tests found for given includes: [integration:]

**Comment by graemerocher** [comment]
They are now `-integration` and `-unit` instead of `integration:` and `unit:`

**Comment by anshbansal** [comment]
@graemerocher What about functional tests? There is a GEB plugin https://github.com/grails3-plugins/geb but they seem to be also going into integeration-tests. Will they need to be run with integeration tests?

**Comment by graemerocher** [comment]
@anshbansal Yes functional tests are just a type of integration test

**Comment by anshbansal** [comment]
@graemerocher  But wouldn't that limit plugins from introducing new test types? Like I have seen plugins introducing test-type javascript. That will not be possible now as only the two types unit and integration are allowed to be present.

**Comment by graemerocher** [comment]
@anshbansal Test execution is handled by Gradle and its infrastructure now, which only differentiates test types by task name

**Comment by tarasrng** [comment]
What is the difference between `grails test-app -integration` and `grails test-app -functional` then?
Both are running integration and functional tests.
