### ISSUE TITLE
Grails 2.4.4: withFilters is not accessing a namespaced controller

### ISSUE THREAD

**Issue by kkaminski** [grails/grails-core#9083]
Running with Grails 2.4.4, a Spock test using `withFilters` is not accessing a controller when that controller is defined to use a namespace in the filter. 

For example, define the following in a unit test:
`withFilters(controller: 'foo', namespace: 'bar', action: 'post') { controller.post() }`

then in the filter class:
` myFilter(controller: 'foo', namespace: 'bar', action: 'post')  { before = {...`

The filter will not get invoked.  However, if you remove the namespace from both places, the filter does get invoked.

**Comment by graemerocher** [comment]
filters are deprecated

**Comment by dtamm** [comment]
So and whats the replacement for filters, also in grails 2.5.x?

**Comment by graemerocher** [comment]
There is no replacement for 2.5.x, you may upgrade to 3.x or if you are concerned about this issue feel free to submit a pull request
