### ISSUE TITLE
Hibernate removes leading zeros from String value

### ISSUE THREAD

**Issue by Warpcore1701** [grails/grails-core#9085]
I have a simple domain class called "attribute" that looks like this: 

    class Attribute {
	String name
	String value
	
    static constraints = {
		name(blank:false)
		value(blank:false)
    }
	
	static mapping = {
		value type: "text"
	}
	
	String toString(){
		return this.name + " : "+ this.value 
	}
    }

When creating new objects the data is correctly stored in the database like this:

+------+---------+-------+-------+
| id   | version | name  | value |
+------+---------+-------+-------+
| 1063 |       0 | level | 001   |
+------+---------+-------+-------+

Now when trying to access the value for the name level I always get a zero trimmed value "1". Even better my toString() method also prints "level: 1" for this object. This cannot be right and the desired behaviour. Note that I also tried to force Hibernate to map value to "text" but still my leading zeros are trimmed.

I'm somewhat clueless and baffled by this. It looks like a bug to me. Is there any other way I can force my Grails appliclation to treat a value like 001 as it is, and not trying to "optimze" it by trimming leading zeros?

**Comment by jeffbrown** [comment]
> Is there any other way I can force my Grails appliclation to treat a value like 001 as it is, and not trying to "optimze" it by trimming leading zeros?

I don't know where that might be happening.  I have tried to recreate the problem and I cannot.  See https://github.com/jeffbrown/issue_9085.

Can you create a sample app which demonstrates the problematic behavior and push that to github?

Thanks for the feedback.
