### ISSUE TITLE
Grails 3.0.2 - Add ability to use system properties / command line arguments in application.yml

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#9086]
This would simplify the deployment process for container based hosting environments (like aws Beanstalk). 

Sample setup:
System property JDBC_CONNECTION_STRING ist set to " 'jdbc:mysql://localhost/my_db?useUnicode=true&characterEncoding=UTF-8&username=xxx&password=xyz'"

(This property is attached with "-DJDBC_CONNECTION_STRING=")

```
    production:
        dataSource: 
            url: ${JDBC_CONNECTION_STRING}
```

**Comment by graemerocher** [comment]
This is already possible with:

    production:
        dataSource: 
            url: '${JDBC_CONNECTION_STRING}'

**Comment by mhuebner** [comment]
Thanks for adding this to the docs! I already tried this solution as suggested:
```
ERROR grails.boot.GrailsApp - Application startup failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'grailsConfigProperties' defined in null: Could not resolve placeholder 'JDBC_CONNECTION_STRING' in string value "${JDBC_CONNECTION_STRING}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'JDBC_CONNECTION_STRING' in string value "${JDBC_CONNECTION_STRING}"
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'grailsConfigProperties' defined in null: Could not resolve placeholder 'JDBC_CONNECTION_STRING' in string value "${JDBC_CONNECTION_STRING}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'JDBC_CONNECTION_STRING' in string value "${JDBC_CONNECTION_STRING}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:211) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
```
Starting the app with param "-DJDBC_CONNECTION_STRING=jdbc:mysql://localhost"

**Comment by anshbansal** [comment]
@mhuebner It's not merged yet. I added a comment to not merge if this is not working.

**Comment by graemerocher** [comment]
How did you start the app? Grails doesn't automatically pass system properties on the command line. You will need to modify the bootRun target of your build.gradle to add system properties if you used `grails run-app`

**Comment by mhuebner** [comment]
Ok, now i see. I wasn't aware of that.
I tried to bind the System.properties but with no luck:

```
tasks.withType(org.springframework.boot.gradle.run.BootRunTask) {
    systemProperties = System.properties
}
```

This gives me the same Result (Exception)

**Comment by mhuebner** [comment]
Followup: it's working now as expected - with the following syntax:

```
run {
    systemProperties = System.properties
}
```

@graemerocher thanks for your hint! Perhaps this could be documented anywhere??

**Comment by anshbansal** [comment]
@gramerocher Suggestions? I am not sure where to add this in the docs.

**Comment by nobeans** [comment]
At the head (d380bea) of 3.0.x, the place holder couldn't be resolved. It's just ignored. Should I create new issue?

**Comment by graemerocher** [comment]
@nobeans Using the latest 3.0.x I added:

     environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: '${JDBC_CONNECTION_STRING}'

And then I changed `build.gradle` to:

      tasks.withType(org.springframework.boot.gradle.run.BootRunTask) {
          systemProperty('JDBC_CONNECTION_STRING', 'test')
      }

And it worked fine for me

**Comment by graemerocher** [comment]
@anshbansal Probably somewhere under the Configuration section http://grails.github.io/grails-doc/latest/guide/conf.html

**Comment by nobeans** [comment]
@graemerocher I tried your example. It actually worked well. But when I tried to get via `Holders.config`, it was still a expression of placeholder.

**Comment by graemerocher** [comment]
@nobeans Please raise a separate issue and I will have a look. Thanks.

**Comment by nobeans** [comment]
Sure.
