### ISSUE TITLE
Add README.md files in each grails module

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-core#9088]
Please add README.md files in each folder in grails-core. With a single line for what the folder contains. I mean a very broad description.

This request is so that new comers can at least understand the structure of grails-core. If people can understand the structure better contributing may become easier. Else grails team can revisit the contributing section of grails core and put one-liners for making it easier to understand how grails is divided into parts.

**Comment by graemerocher** [comment]
ok, will consider this

**Comment by anshbansal** [comment]
bump

**Comment by jeffbrown** [comment]
> bump

@anshbansal Please don't start doing that to every open issue that you would like addressed.

**Comment by anshbansal** [comment]
@jeffbrown Ok. Will take care.

**Comment by jeffbrown** [comment]
If you want to submit a pull request that contains the missing README.md files that contain the header and some description like "Developer notes TBD" or similar, that would be a more constructive way to contribute.  That kind of help is very much appreciated.

Thanks again.

**Comment by jeffbrown** [comment]
Some of the ones I added this morning have some useful non-obvious comments.  See https://github.com/grails/grails-core/blob/7bfe4e70a7d6ee8368e93c86db26c83076fe46a7/grails-databinding/README.md and https://github.com/grails/grails-core/blob/7bfe4e70a7d6ee8368e93c86db26c83076fe46a7/grails-compat/README.md.  Others contain little more information that is represented in the subproject name itself.  See https://github.com/grails/grails-core/blob/7bfe4e70a7d6ee8368e93c86db26c83076fe46a7/grails-bom/README.md and https://github.com/grails/grails-core/blob/7bfe4e70a7d6ee8368e93c86db26c83076fe46a7/grails-bootstrap/README.md.

None of them are particularly detailed.  These all can evolve over time of course.  Writing a real developer's guide is a large scope of work that I don't anticipate we will do but these files can provide some useful information and I expect their value will increase a bit over time.

**Comment by guramritpal-jft** [comment]
@anshbansal readme.md file has been added to almost every module .  Update..!

**Comment by anshbansal** [comment]
@guramritpal-jft By README.md files I mean not empty files containing some details. 

By the way I am curious regarding one thing. Are you taking some professional part in grails team?

**Comment by rlovtangen** [comment]
Great with these readme files. GitHub also renders README.adoc out-of-the-box, so if some of the readmes will contain more than a few lines, using asciidoc is maybe worth considering.

**Comment by jeffbrown** [comment]
@rlovtangen I don't anticipate much content that isn't well suited for Markdown.  Are you thinking of specific kinds of content that would call for asciidoc?

**Comment by rlovtangen** [comment]
No, just that I see no point in using Markdown these days, when asciidoc support is just as good.

**Comment by jeffbrown** [comment]
I really don't care if they are Markdown or Asciidoc.  I think as long as they are all the same, they all render well at GitHub and are all easily dealt with any reasonable text editor then I am fine with whatever format.

If you want to send a PR to turn them all into Asciidoc, I will apply that.  If not, that is fine too.  If we are going to make the change I would rather do it before much content evolves in them.

**Comment by rlovtangen** [comment]
No big deal for me either. Depends on what format is preferred by those who will provide the most content. Just wanted to chime in and say that GitHub renders README.adoc as well, in case that wasn't known. Seems to me that most of the GR8 community is switching to asciidoc these days.

**Comment by jeffbrown** [comment]
> Just wanted to chime in and say that GitHub renders README.adoc as well, in case that wasn't known.

Thanks for that information.

**Comment by jameskleeh** [comment]
There are README files in each module, some without content. Given how old this is, if anyone wants to create a PR to improve any one of them, feel free to do so.
