### ISSUE TITLE
Service injection not working in nested command objects

### ISSUE THREAD

**Issue by harjuto** [grails/grails-core#9091]
Service injection doesnt seem to work with nested command objects, service is null.
Grails 2.3.11

**Comment by graemerocher** [comment]
This makes sense to me, only the top level object is subject to injection and traversing all nested objects to perform injection would be a performance issue. I suggest this is a just a documentation issue.

**Comment by anshbansal** [comment]
@graemerocher Adding the documentation tag was a nice idea. That way docs improvement need can be more easily identified. Maybe if anything comes up in discussion on issues that is not documented then that issue can have this tag? Even if that is not a documentation only issue.

**Comment by graemerocher** [comment]
@anshbansal Sure I will keep that it mind. Thanks.

**Comment by nickof** [comment]
Then how do you manager to get a service in a nested command object ?

**Comment by nickof** [comment]
ok well I found a solution, you juste need to fill services attributes of nested command objects  with services injected in top level command object. You can inject it via the static constraint "validator" in the top level command object...
if it can help, the code is below :

`@Validateable
class TopLevelCommandObject {
    SpringSecurityService springSecurityService // grails inject the service

    List<NestedCommandObject> nestedCommandObjects = ListUtils.lazyList([], {new NestedCommandObjects()} as Factory)

    static constraints = {
        nestedCommandObjects      nullable: false, validator: { val, object ->
            // /!\ Grails didn't inject services in nested command object for performance reasons, only top level injection /!\
            // ==> then before calling validate on nested command objects we fill them with springSecurityService
            val.each { it.springSecurityService = object.springSecurityService }
            return val.every { it.validate() } ?: ['attributes.validation.failed']
        }
    }

}`
