### ISSUE TITLE
spring method security is not working with grails 3.0.2

### ISSUE THREAD

**Issue by akistanov** [grails/grails-core#9092]
In grails 3.0.2 project with spring-security when turn on method security adding `@EnableGlobalMethodSecurity(prePostEnabled = true)` annotation to `SecurityConfiguration` class
application failed to start with error:
`
ERROR grails.boot.GrailsApp - Application startup failed
java.lang.IllegalArgumentException: Class name [org.grails.spring.aop.autoproxy.GroovyAwareAspectJAwareAdvisorAutoProxyCreator] is not a known auto-proxy creator class
at org.springframework.aop.config.AopConfigUtils.findPriorityForClass(AopConfigUtils.java:140) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
...
`
Possible workaround is described here: https://groups.google.com/forum/#!topic/grails-dev-discuss/hr1skz1RaZo

It adds `GroovyAwareAspectJAwareAdvisorAutoProxyCreator` to `AopConfigUtils` with Java Reflection, but after this fix new error will appear:
`
ERROR grails.boot.GrailsApp - Application startup failed
...
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor' defined in class path resource [org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.access.intercept.aopalliance.MethodSecurityMetadataSourceAdvisor]: Factory method 'metaDataSourceAdvisor' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'methodSecurityMetadataSource' defined in class path resource [org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.access.method.MethodSecurityMetadataSource]: Factory method 'methodSecurityMetadataSource' threw exception; nested exception is java.lang.IllegalArgumentException: org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity is `

**Comment by graemerocher** [comment]
This was fixed by https://github.com/grails/grails-core/commit/08fb70ee3a9223f68b5acca435eee3ca76e9b8cd
