### ISSUE TITLE
Grails 3.0.3:  Could not checkout tag for Grails release, Again

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9095]
Though it has been already fixed at https://jira.grails.org/browse/GRAILS-11946, it's reproduced again at 3.0.3.

```
| Error Could not checkout tag for Grails release [3.0.3]: Ref v3.0.3 can not be resolved (Use --stacktrace to see the full trace)
```

It might be the cause that the master is behind from v3.0.3 branch in grails-profile-repository.

* http://download.eclipse.org/jgit/docs/jgit-2.0.0.201206130900-r/apidocs/org/eclipse/jgit/transport/TagOpt.html#AUTO_FOLLOW

> Automatically follow tags if we fetch the thing they point at.
This is the default behavior and tries to balance the benefit of having an annotated tag against the cost of possibly objects that are only on branches we care nothing about. Annotated tags are fetched only if we can prove that we already have (or will have when the fetch completes) the object the annotated tag peels (dereferences) to.

```
$ cd ~/.grails/repository/profiles
$ git fetch --tags
$ git show-branch --sha1-name v3.0.3 master
! [v3.0.3] Revert "Use Gradle 2.5"
 * [master] Use dependency-management 0.5.2 which is compatible with Gradle 2.5
--
+  [4c9e960] Revert "Use Gradle 2.5"
+* [44eabf8] Use dependency-management 0.5.2 which is compatible with Gradle 2.5
```

If so, it might be able to be fixed by doing fast-forward merge and push the master.

**Comment by nobeans** [comment]
You can also specify `TagOpt#FETCH_TAGS` explicitly before causing same issue.

**Comment by nobeans** [comment]
To reproduce this:

```
$ cd ~/.grails/repository/profiles
$ git tag -d v3.0.3
```

And then, use `grails` command of v3.0.3.

**Comment by graemerocher** [comment]
I think this was because I had not completely pushed to master, which I have done now. Please try again because I believe this is working.

**Comment by nobeans** [comment]
Hmmm, I tried to confirm it at another computer, but I can't say with confidence that it's fixed. It seems to work well for the first time, but the error occurs again after deleting the v3.0.3 tag. I don't know whether my method to reproduce it is wrong or this issue isn't fixed...

I think that the topic titled "Unable to create Grails 3.0.3 app" in the ML is caused by this issue.

**Comment by nobeans** [comment]
I've got it! I had missed the effect of `updateInterval` for .git/FETCH_HEAD.

Right procedures to confirm:

* Reset repository state to v3.0.2 by force.

```
cd ~/.grails/repository
git checkout master
git reset --hard 44eabf8
echo 44eabf8e8e815f1ebaf91118a13f7741579a2015 > .git/refs/remotes/origin/master
git tag -d v3.0.3
rm .git/FETCH_HEAD # If without this, your retrial after resetting within 10 minutes will be failed!
```

* Use grails command of v3.0.3 as follows:

```
grails create-app g303-test
| Application created at /private/tmp/g303-test
```

When I tried again and again, all results were OK expectedly. So I think this is already fixed.
