### ISSUE TITLE
Possible incorrect response status for empty list of  HAL resources

### ISSUE THREAD

**Issue by dane-king** [grails/grails-core#9101]
I was creating a small prototype with a domain class with one field and I get a 406 response with a hal+json accept header, but when its just a json accept header I get a 200 with an empty array for the body. Once I seed the database everything works fine. This seems a bit misleading, since the request was successfully received I just don't have any to send you back.

**Comment by graemerocher** [comment]
Please upload a sample to Github that reproduces the problem

**Comment by dane-king** [comment]
Here is the uploaded code commenting/uncommenting the seed data method in the Bootsrap.groovy reproduces the problem https://github.com/dane-king/techEval

curl -v -i -H "Accept:application/hal+json" localhost:8080/techEval/api/evaluation
curl -v -i -H "Accept:application/json" localhost:8080/techEval/api/evaluation

Not saying I necessarily disagree with the 406, it could be you can't create a self link on an empty object, but it was a bit confusing especially from the Hal examples and then getting a 200 on a json call took me a bit to figure out.

I would be happy to add to the docs or help fix, just don't know what the right fix would be

**Comment by graemerocher** [comment]
Will take a look. thanks

**Comment by graemerocher** [comment]
The error is because you need to define a HAL collection renderer for Evaluation in your Spring config:

    evaluationCollectionRenderer(HalJsonCollectionRenderer, Evaluation)
