### ISSUE TITLE
asset-pipeline does not support custom asset subdirs for plugins

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9103]
only contents of `grails-app/assets/images`, `grails-app/assets/javascripts` and `grails-app/assets/stylesheets` are copied to `META-INF/assets` when packaging a plugin jar: https://github.com/grails/grails-core/blob/v3.0.3/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy#L132

please re-add support for custom subdirectories. e.g. sth. like `grails-app/assets/vendors` often makes a lot of sense to just be able to drop-in a lib shipping js/css/etc.

thanks, zyro

**Comment by graemerocher** [comment]
Please report to asset pipeline issue tracker
