### ISSUE TITLE
Update Grails-3.0.x to Groovy-2.4.4

### ISSUE THREAD

**Issue by smartiniOnGitHub** [grails/grails-core#9104]
Hi all,
it seems that Groovy-2.4.4 is near to be released ( http://www.groovy-lang.org/mailing-lists.html#nabble-td5726098 ) and it has many fixes and improvements ( https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12318123&version=12331941 ), or better it has been tagged and seems released but up to now there aren't binaries distribution artifacts to download, probably some day is still needed to have all stuff published.
Please take this issue only as reminder, and to have it in release notes :-) .

Do you think it will be possible to use it in next Grails-3.0.x releases ?

Anyway, what do you think on setting up a Continuous Build Job to test Grails even with it, to start ensure everything works ?

Thanks a lot,
Sandro

**Comment by jeffbrown** [comment]
We had a joint build setup in our old Hudson instance that was constantly building the latest Grails code against the latest Groovy code and running all of the Grails unit tests.  That was valuable but the way we did it was a good bit more complicated than it needed to be.  I think we can setup a parameterized build in Travis that will accomplish the same thing.

**Comment by jeffbrown** [comment]
See #9107

**Comment by smartiniOnGitHub** [comment]
Hi Jeff, thank you very much for the help even on this. I hope to be able to try all the new stuff soon :-) .
Stay well. Bye

**Comment by jeffbrown** [comment]
>  I hope to be able to try all the new stuff soon

Is there something specific in Groovy 2.4.4 that you are anxious to try?

**Comment by smartiniOnGitHub** [comment]
Oh no, nothing specific, but in Groovy-2.4.4 release notes I see some interesting fix/improvements in Static Compiler, traits, and even some little change in operator casts; last, it's the first release at Apache Incubator :-) . Thanks for now. Bye

**Comment by jeffbrown** [comment]
See https://issues.apache.org/jira/browse/GROOVY-7505

**Comment by smartiniOnGitHub** [comment]
Hi Jeff, sorry for the problem now with the new Groovy release ...
I can't say if it would be better to stay with the new release (and start even for Plugin and sites authors to fix things) or if revert to Groovy-2.4.3 for all Grails-3.0.x line and update to Groovy-2.4.4 or later in Grails-3.1.x line. Personally speaking I still have little things with Grails-3.0.x so I'd go forward with the new Groovy release, but maybe other users can say what they think.
Anyway thank you very much for now, Sandro

**Comment by jeffbrown** [comment]
Groovy 2.4.4 is on our 3.0.x branch for now.  If we ship it that way, the issue will be noted in the release notes.

**Comment by smartiniOnGitHub** [comment]
Perfect (at least for me :-) ), my +1 ... Bye

**Comment by jeffbrown** [comment]
https://issues.apache.org/jira/browse/GROOVY-7509
