### ISSUE TITLE
Default integration with Git on grails create-app command

### ISSUE THREAD

**Issue by azhidkov** [grails/grails-core#9108]
Since Grails 3.0.x version doesn't have "grails integrate-with --git" command. May be it's better and more convenient to add .gitignore file by default on execution "create-app" command?

**Comment by graemerocher** [comment]
This was already done here: https://github.com/grails/grails-profile-repository/commit/c0c78e813c8d02b3136578cd6e51554d3ed9faf0

Is there something additional you need?

**Comment by azhidkov** [comment]
Thank's @graemerocher .

Yet another questions, It will contains only those two records? And in which release it will be implemented (I used 3.0.3 and it doesn't exist)?

**Comment by graemerocher** [comment]
hmm you are right, the files are not created, will look into this...

**Comment by aadrian** [comment]
@graemerocher 
further stuff that belongs in a default ```.gitignore```:
 - IDE specific files:
```
.idea
*.iml
*.ipr
*.iws
.project
.settings
.classpath
```
 - OS specific:
```
Thumbs.db
.DS_Store
```

**Comment by sergiomichels** [comment]
@graemerocher Plugins is missing this feature too, should I create a new issue?
