### ISSUE TITLE
Mongo Connections tightly coupling to specific threads

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#9114]
There is an issue with mongo threads not releasing themselves from idle threads in a tomcat threadpool on the request cycle. Typically the solution is to make sure mongo maxconnections match the maxThreads configuration. But this leaves a lot of idle open connections. Not exactly sure where in the data-mapping plugin this is happening but the common fix is to adjust the `DBTCPConnector` in the java mongo driver 2.x series like so: 

[See Here](https://github.com/davydotcom/mongo-java-driver/commit/ea47da7345d9702c1f3645f23eba6385ebf82709)

**Comment by graemerocher** [comment]
I don't believe we can change this and the change would essentially break the mongo thread pool by disabling thread pooling all together which seems a dangerous change to me.
