### ISSUE TITLE
Grails 3.0.3 deployed WAR are not creating CSS/JS includes.

### ISSUE THREAD

**Issue by dmonti** [grails/grails-core#9117]
I'm deploying an war app using Grails 3.0.3 with default asset-pipeline and even with default create-app files, so the problem occurs when the App is running on outside Tomcat8 container, and the files 'application.js' and 'application.css' aren't included in my page.

My steps are, 1, executed grails command to generate the war with:

    grails war

2, Copy the generated war inside 'myApp/build/libs/app-0.1.war' to webapps on Tomcat folder as 'ROOT.war'.

3, Start the tomcat...

4, Open the index page at localhost:8080 and script or style include tags are not in the HTML.

Those tags on main layout are supposed to include my missing JS and CSS:

    <asset:javascript src="application.js" />
    <asset:stylesheet src="application.css" />

Remember, I'm using the initial project creation with no changes at all and all works fine executing 'grails run-app'

**Comment by zyro23** [comment]
#9115 ?
