### ISSUE TITLE
Setting Grails port omits application name in link tag

### ISSUE THREAD

**Issue by PaulWaldo** [grails/grails-core#9132]
If I set `grails.server.port.http = 8080` in BuildConfig or comment it out, link tags work fine.  The tag

    <g:link action="downloadAsPdf" id="${invoice.id}">

is rendered with the URL `http://localhost:8080/Invoicer/invoice/displayAsPdf/2`. This is the correct form because it contains the app-name.  

If I then set `grails.server.port.http = 9090`, the same link tag renders with this URL `http://localhost:9090/invoice/displayAsPdf/2`. This URL does not work properly, as it does not include the app name.  

I'm able to get around this by setting `grails.serverURL = "http://localhost:9090/${appName}"` in Config.groovy, but this feels not too DRY.  Not only do I have to repeat the port here, but I also have to repeat the format of the base URL. 

Environment:
* Grails 2.4.3
* OSX
* JDK 1.7.0_67

**Comment by jameskleeh** [comment]
Cannot reproduce in `3.2.0.BUILD-SNAPSHOT`
