### ISSUE TITLE
application.groovy not loaded on startup (environment specific)

### ISSUE THREAD

**Issue by pledbrook** [grails/grails-core#9134]
I've only come across this when trying to deploy a Grails 3 fat jar app to a hosting provider. The latest failure is with [Boxfuse](https://boxfuse.com/), who make it easy to deploy to Virtual Box and then AWS.

The main characteristics of the problematic environment are:

* OpenJDK
* Linux
* Running on a VM

I suspect at least one of these or a combination of them is causing the problem. My money's on OpenJDK. Unfortunately it's not painless to get hold of the OpenJDK on Mac, so I haven't tested it outside of Vagrant.

If I get a chance to build a reproducible setup, I will. But this has cost me way too much time already.

**Comment by pledbrook** [comment]
A workaround would be really handy. I've tried to configure a data source using Spring's Java configuration, but that just messes up the transaction manager which can't find a bean called _dataSource_.

To add some colour to the mix, application.groovy is sometimes loaded in the Virtual Box instance.

**Comment by graemerocher** [comment]
the loading of `application.groovy` is handled by Spring Boot, not sure there is much we can do about this to be honest

**Comment by pledbrook** [comment]
It looks like you're right in that it's something in Spring Boot. The configuration file is being skipped, but not because of the usual 'resource not found'. Unfortunately it doesn't give a reason for skipping it, but it seems that it's something to do with what's in the file. Still trying to isolate the bit of configuration that's causing the issue.

I'll raise the issue with manually configuring the _dataSource_ bean in a separate issue.

**Comment by pledbrook** [comment]
The issue is that Spring Boot or Groovy silently ignore exceptions thrown by `application.groovy` when it's executed. This is a serious weakness.

**Comment by graemerocher** [comment]
Ugh, that is horrible yes, maybe report to https://github.com/spring-projects/spring-boot/issues

**Comment by rlovtangen** [comment]
Similar problem in Grails 2.x.
We use to add an external config file:
````
grails.config.locations = ["classpath:${appName}-config.groovy"]
````
If there is any error in this file it is silently ignored. Common error is to forget that it's a groovy-file, not a properties-file, and comment out a line with `#`

**Comment by pledbrook** [comment]
Actually, this must be a Groovy/Grails issue. The file is loaded by [GroovyConfigPropertySourceLoader](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/core/cfg/GroovyConfigPropertySourceLoader.groovy). I'm wondering whether `ConfigSlurper` is the issue here as I'm pretty sure I don't see the error logged by the property source loader.

**Comment by graemerocher** [comment]
errors are logged at the error log level in the code...

**Comment by graemerocher** [comment]
As far as I can tell there is no error handling that would swallow the error inside `ConfigSlurper`

**Comment by pledbrook** [comment]
Easily replicated with a `grails run-app`. Simply download my [bug report project](https://dl.dropboxusercontent.com/u/29802534/groovy-config-bug-report-27072015.zip) and execute `grials run-app`.

The `BootStrap` class prints out the value of a configuration option specified in _application.groovy_, but the latter throws an exception. All you see is `[:]` printed out for the config option and no error logged.

**Comment by pledbrook** [comment]
I think the issue with the JavaConfig-defined data source was down to a faulty database URL, which was the underlying cause of the exceptions in _application.groovy_ too. I failed to reproduce the transaction manager error in a fresh Grails app.

**Comment by sergiodelamoshoptimix** [comment]
I think I am experiencing this issue deploying to AWS Elastic beanstalk with Grails 3.0.5

[Bean property overrides problem fix](https://github.com/grails/grails-core/issues/9133) was working for me in production (same AWS Elastic Beanstalk project) and in development with grails 3.0.4. 

In development with 3.0.5, bean properties overrides works.However If I now deploy to AWS with 3.0.5 bean properties are not loaded. I guess application.groovy is not being loaded. However I don't see any error trace. 

This is the instance configuration:
64bit Amazon Linux 2015.03 v2.0.0 running Tomcat 8 Java 8

**Comment by graemerocher** [comment]
I will work this into 3.0.6

**Comment by sergiodelamoshoptimix** [comment]
@graemerocher thanks for changing the priority to 3.0.6

**Comment by graemerocher** [comment]
So after much debugging this seems to be a problem (or a feature?) in Boot where by any logging is disabled until the environment is prepared (after the config is loaded). See 

https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L94

Which adds a `FILTER` that blocks all logging, until `initialize` is called:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L101

I'm not sure of the exact reason for this. Nevertheless I have changed it to throw the exception instead of just logging it, which prevents server startup, which is probably more sensible anyway:

https://github.com/grails/grails-core/commit/632fbbd2f77e9f33906677704fcdd7e30e88aa48

**Comment by sergiodelamoshoptimix** [comment]
I have tested it in grails 3.0.7 and bean property overrides defined in application.groovy are working for me now. Tested in AWS with a elastic beanstalk deployment.

**Comment by pledbrook** [comment]
I'd guess at that being a feature since you really need the configuration loaded in order to configure the logging. I think throwing the exception and failing fast on startup is the correct choice, thanks.
