### ISSUE TITLE
"Well known" Filters should be ordered correctly

### ISSUE THREAD

**Issue by rwinch** [grails/grails-core#9137]
Generally, Spring Boot has sorted out most of the Filter ordering issues AFAIK. For example, Spring Session is placed before Spring Security to ensure that Spring Security is reading from the overridden `HttpSession`.

The `GrailsWebRequestFilter` seems out of place since it is before `Filter`s that decorate the `HttpServletRequest`. For example, Spring Session's `SessionRepositoryFilter` is placed after `GrailsWebRequestFilter` which means the `HttpSession` is not overridden.

I think there are likely other issues with the `Filter` ordering when running in Grails. A few additional `Filter`s that should wrap the request (thus should be *before* `GrailsWebRequestFilter)` are Spring Security's `FilterChainProxy`, `HiddenHttpMethodFilter`, `CharacterEncodingFilter`, `MultipartFilter`.

Additionally, some of these `Filter`s may be dependent on other `Filter`s being before them. For example, if someone uses Hibernate in Spring Security they would want `OpenSessionInViewFilter` registered before Spring Security. If someone is using localization, then they would want `RequestContextFilter` registered before Spring Security too (so the error messages are localized).

For these reasons, I think we need to try and come up with an improved ordering for Grails related Filters that is coordinated with Spring Boot.

Related https://github.com/spring-projects/spring-session/issues/245

**Comment by graemerocher** [comment]
@rwinch Can you point me to the code where this is handled in Spring Boot? I am having trouble tracking it own.

**Comment by rwinch** [comment]
@graemerocher It seems like this is done through an array of strategies. 

* Boot starts off with `ServletContextInitializerBeans#getOrderedBeansOfType(ListableBeanFactory,Class<T>)` retrieving all the `Filter` instances where it is sorted using `AnnotationAwareOrderComparator.INSTANCE`
* Looking through there is a number of different strategies for ensuring which Filter goes first.
  * `OrderedCharacterEncodingFilter` is used which extends `CharacterEncodingFilter` and implements `Ordered`
  * `SpringBootWebSecurityConfiguration#securityFilterChainRegistration` creates a `FilterRegistrationBean` for `springSecurityFilterChain`
  * `SessionRepositoryFilter` adds the `@Order` annotation to it. Spring Session uses the annotation vs the interface so we have no runtime dependencies on any other Spring libraries
  * `OrderedHiddenHttpMethodFilter` is new in Spring Boot 1.3.0.M1 and uses the same strategy as `OrderedCharacterEncodingFilter`

At this point framework filters typically use `Ordered` so users can easily override the default order. Unfortunately, the way you must determine your order is by looking at all the other `Filter`s.

I spoke with @dsyer and @wilkinsona offline and they said we can likely provide a constant that marks any filter before wraps the request. `Filter`s relying on the wrapped request would be after that constant.

**Comment by graemerocher** [comment]
@rwinch So we already have a default order configured:

https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L92

If we can align that around some constant that would be much better since if I change it to another hard coded value this would break in the future.

**Comment by rwinch** [comment]
@graemerocher Thanks for the reply. 

> So we already have a default order configured:

Right, but it appears to not align well with the other Filters.

> If we can align that around some constant that would be much better since if I change it to another hard coded value this would break in the future.

Agreed. I created https://github.com/spring-projects/spring-boot/issues/3613 so that there is a constant that you can refer to.

**Comment by graemerocher** [comment]
Will wait for a version of Boot that has this constant in that case

**Comment by dsyer** [comment]
spring-projects/spring-boot#3613 is fixed in master. 1.3.0.M5 should be out today.

**Comment by graemerocher** [comment]
@dsyer Great news!

**Comment by graemerocher** [comment]
@rwinch @dsyer Grails 3.1 master is now aligned to this https://github.com/grails/grails-core/commit/16ac8da3798daa77baa9afb1affdca1d21fb7e2a

Let me know if there are any other changes needed
