### ISSUE TITLE
Problem with grailsw in 2.5.1

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9144]
`grailsw` won't work in 2.5.1 because `wrapper/grails-wrapper.properties` still points to the old S3 distribution site.

In order to make the wrapper work, update that property file to look like this...

    wrapper.dist.url=https://github.com/grails/grails-core/releases/download/v2.5.1/

**Comment by allenhealthstack** [comment]
@jeffbrown - is there going to be an "emergency release" of 2.5.2  to address this issue?  If so, I'll wait to upgrade.

**Comment by ikakara** [comment]
@jeffbrown - is there going to be an "emergency release" of 2.5.2 to address this issue? If so, I'll wait to upgrade.

**Comment by graemerocher** [comment]
This works now, thanks to Trevor from Pivotal
