### ISSUE TITLE
Grails 3.0.4 resource tag: No such property: AssetPipelineConfigHolder

### ISSUE THREAD

**Issue by jwagenleitner** [grails/grails-core#9145]
Following exception is occurring when using the `resource` taglib using v3.0.4 but was working in 3.0.3:

```
Class
groovy.lang.MissingPropertyException
Message
Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error evaluating expression [resource(dir:'images',file:'springsource.png')] on line [80]: No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator
Caused by
No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator
```

Steps to reproduce:

1.  grails create-app app304
2.  cd app304
3.  added the following right after the body tag in `grails-app/views/index.gsp`

`<img src="${resource(dir:'images',file:'springsource.png')}" />`

4. grails run-app
5. open http://localhost:8080 in browser

Following the same steps in version 3.0.3 works and the springsource image is displayed on the index page as expected.

```
grails -version
| Grails Version: 3.0.4
| Groovy Version: 2.4.4
| JVM Version: 1.7.0_79
```

**Comment by davydotcom** [comment]
This appears to be working now with the asset-pipeline 3.0.6 release

**Comment by jwagenleitner** [comment]
I confirmed using asset-pipeline v3.0.6 fixes this issue for my projects.  Thanks.

**Comment by jeffbrown** [comment]
@davydotcom Is there any reason that we shouldn't change https://github.com/grails/grails-core/blob/8fdbffbec55670eefe92a918a3d4bec5cef9bda9/grails-bom/plugins.properties#L6 to 3.0.8?

**Comment by davydotcom** [comment]
not that I'm aware of

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/5c67cd22688f596cf8589958512c8b40cfa1b250
