### ISSUE TITLE
Grails 3 Sees a Many-To-Many Association Where it Should See a One-To-Many

### ISSUE THREAD

**Issue by MauiMana** [grails/grails-core#9148]
I'm working with the following environment:
- Grails 3.0.3, Groovy 2.4.3, JVM 1.8.0.31 ... all running on OSX 10.10.4

After tracing through with a debugger, Grails appears to be seeing the one-to-many self association (parent --> children) as a many-to-many. The result is that when one tries to remove an object from the 'children', grails tries to clean up the other end of the association by calling a remove() method on something that is, of course, not a collection. Not finding an applicable remove() method causes Grails to throw a MissingMethodException... I've isolated the case down to a two level inheritance model where the 'abstract' base class defines a parent/children self association. NOTE, the problem does not occur if I collapse the two classes into a single *instantiable* class. Here is the domain model:

    // CLASS 1 - Abstract Base Class
    package com.sandbox

    abstract class AbstractBaseClass {

        static hasMany = [ children: AbstractBaseClass ]

        static belongsTo = [ parent: AbstractBaseClass ]

        static constraints = {
        }
    }

    // CLASS 2 - Instantiable Sub Class
    package com.sandbox

    class IllustrationCase extends AbstractBaseClass {

        String name

        static constraints = {
        }
    }

Then, my test case where the exception occurs is as follows:

    package com.sandbox

    import grails.test.mixin.integration.Integration
    import grails.transaction.*
    import spock.lang.*

    @Integration
    @Rollback
    class IllustrationCaseSpec extends Specification {

        def setup() {
        }

        def cleanup() {
        }

        void "Deleting Nodes From a Hierarchy"() {
            given:
            // Create the various nodes
            def theParent = new IllustrationCase(
                name: "Parent Node"
            )
            def theChild1 = new IllustrationCase(
                name: "Child Node 1"
            )
            def theChild2 = new IllustrationCase(
                name: "Child Node 2"
            )
            def theChild3 = new IllustrationCase(
                name: "Child Node 3"
            )

            // Create the hierarchy structure
            theParent.addToChildren(
                theChild1
            ).addToChildren(
                theChild2
            ).addToChildren(
                theChild3
            )

            // Perform a DEEP save
            theParent.save( failOnError: true )

            // Remove a child node --- This is where the error occurs...
            IllustrationCase.get( theParent.id ).removeFromChildren( IllustrationCase.get( theChild2.id ) )

            expect:

            // Find the parent nodes...
            def targetNode = IllustrationCase.findByName( "Parent Node" )

            targetNode.children.size() == 2
            !targetNode.children.find { it.name == "Child Node 2" }

            targetNode.children.find { it.name == "Child Node 1" }
            targetNode.children.find { it.name == "Child Node 3" }
        }
    }

Executing the above test case results in the following exception being thrown...

    groovy.lang.MissingMethodException: No signature of method: com.sandbox.IllustrationCase.remove() is applicable for argument types: (com.sandbox.IllustrationCase) values: [com.sandbox.IllustrationCase : 1]
    Possible solutions: merge(com.sandbox.IllustrationCase), merge(), merge(), create(), delete(), save()
	    at org.grails.orm.hibernate.AbstractHibernateGormEnhancer.addRelationshipManagementMethods_closure5(AbstractHibernateGormEnhancer.groovy:183)
	    at com.sandbox.IllustrationCaseSpec.$tt__$spock_feature_0_0(IllustrationCaseSpec.groovy:46)
	    at com.sandbox.IllustrationCaseSpec.Deleting Nodes From a Hierarchy_closure1(IllustrationCaseSpec.groovy)
	    at groovy.lang.Closure.call(Closure.java:423)
	    at groovy.lang.Closure.call(Closure.java:439)
	    at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:67)
	    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	    at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
	    at com.sandbox.IllustrationCaseSpec.Deleting Nodes From a Hierarchy(IllustrationCaseSpec.groovy)

**Comment by MauiMana** [comment]
Tried to edit my original report but selecting 'edit' button at the top wouldn't seem to allow me to affect my original text. In any case, Although this doesn't change the occurrence of the error, I simply wanted to replace the following two lines of code with a single one (...this is where the error occurs)...

REPLACE:
        IllustrationCase.get( theChild2.id ) )
        theParent.removeFromChildren( theChild2 )
WITH:
        IllustrationCase.get( theParent.id ).removeFromChildren( IllustrationCase.get( theChild2.id ) )

**Comment by MauiMana** [comment]
Made a small update to the illustrative code. This does not change the occurrence of the error but simply corrected a small inefficiency in my example... I replaced the two lines of code that followed the 'deep' save of 'theParent' with a single line of more efficient code. Again, no change in outcome...

**Comment by graemerocher** [comment]
Since this is a circular one-to-many, there is no way for GORM to know which property you want to map the relationship by so it picks the first one and creates a circular relationship between `children` and `children`. To configure how the relationship is mapped you have to define `mappedBy`

      static mappedBy = [children: 'parent']

This gives GORM the information it needs to recognize that the association is between `children` and `parent`, not between `children` and `children`

**Comment by graemerocher** [comment]
I have made some changes to GORM to not throw the error, but the problem remains in that you have not mapped the relationship correctly

**Comment by fruwe** [comment]
hi there, I have the same problem.

```
class Author {
    static hasMany = [books: Book]
    String name
}
class Book {
    String title
}
```

Directly copied from your one-to-many manual 7.2.1.2 (https://grails.org/single-page-documentation.html) causes three tables to be created.

author, book and author_book

**Comment by zyro23** [comment]
@fruwe thats by design. unidirectional one-to-many is mapped with a join table by default. see http://grails.github.io/grails-doc/latest/guide/GORM.html#oneToMany. you can either define the backreference in `Book` or customize the `mapping` to get a fk column.

**Comment by fruwe** [comment]
@zyro23 Thank you so much for your helpful and extremely quick answer. I'll try and see what happens. Thanks again
