### ISSUE TITLE
IllegalStateException thrown when making call to service method with supports propagation followed by call to required propagation with multiple data sources

### ISSUE THREAD

**Issue by jonroler** [grails/grails-core#9149]
I have a working application that demonstrates this issue here: https://github.com/jonroler/grails-txn-supports-bug.

I have a grails application with 2 data sources.  I have a grails service class (TestService.groovy) that is annotated Transactional at the class level.  This service class has 2 methods--one method is annotated to use "supports" propagation, and the other method doesn't have any further annotations (so it will use "required").  Both methods, simply get the default DataSource and execute a simple sql select statement.  I have a controller method (TestController.index()) that first calls the service method annotated with supports propagation before calling the other service method (should run with "required" txn propagation).  The second call fails with an IllegalStateException with the message:

```
Already value [org.springframework.jdbc.datasource.ConnectionHolder@4d356d09] for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@6f8682d8] bound to thread [http-nio-8080-exec-1]
```

Here is the service class:

```
package testsupports

import org.springframework.transaction.annotation.Transactional
import org.springframework.transaction.annotation.Propagation

import javax.sql.DataSource

import groovy.sql.Sql

@Transactional
public class TestService {
  DataSource dataSource

  @Transactional(propagation=Propagation.SUPPORTS)
  public void testMethod1() {
    log.error("In testMethod1")
    Sql sql = new Sql(dataSource)
    sql.eachRow("select 1") {
      log.error(it)
    }
    sql.close()
  }

  public void testMethod2() {
    log.error("In testMethod2")
    Sql sql = new Sql(dataSource)
    sql.eachRow("select 1") {
      log.error(it)
    }
    sql.close()
  }
}
```

and here is the controller:

```
package testsupports

public class TestController {
  TestService testService

  def index() {
    testService.testMethod1()
    testService.testMethod2()
  }
}
```

I put a breakpoint in TransactionSynchronizationManager.bindResource() and TransactionSynchronizationManager.unbindResource() and found that a hibernate session and a datasource object are being bound to the thread in TransactionSynchronizationManager.bindResource() on the way into the service method annotated with supports propagation, but no calls to TransactionSynchronizationManager.unbindResource() are made when this method finishes.  When the subsequent call is made to the second service method, the IllegalStateException is raised in TransactionSynchronizationManager.bindResource() because it sees that the data source it is trying to bind to the thread is already there.  It seems like this case is legal and should work, so I think this is a grails bug.  In fact, if I remove one of the data sources, I don't get the error message--it only occurs when I add the second data source.  The type of data source doesn't seem to matter either as I've reproduces using both the default h2 driver as well as with postgres.

My test application (https://github.com/jonroler/grails-txn-supports-bug) makes this issue very easy to reproduce.  Just clone the application, run it with "grails run-app", and navigate in a browser to http://localhost:8080/test/index.  An error page should appear with the exception I described above.

This code worked fine for me with grails 2.1.0.  However, it fails with the same error in grails 2.5.0, 2.5.1, and 3.0.4.

My java version is 1.8.0_45, 64 bit, running on arch linux with "uname -a" output of:

Linux lone 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux

**Comment by graemerocher** [comment]
As per the documentation on `TransactionDefinition`:

https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/main/java/org/springframework/transaction/TransactionDefinition.java#L64

it explicitly states that `PROPAGATION_SUPPORTS` transactions should be nested within other transactions are not used directly. Your controller action is calling the transactional method directly:

     testService.testMethod1()

Without the presence of a surrounding transaction. This is not correct or allowed. Granted the error message could be better, but what is essentially happening is that `PROPAGATION_SUPPORTS` transactions do not clear the currently bound transactional objects because it is assumed a surrounding transaction will do so. Hence the error when you try invoke the next method.

**Comment by jonroler** [comment]
Thanks for the feedback.  However, I disagree with your statement that PROPAGATION_SUPPORTS transactions must be nested within other transactions.  The very first sentence of the javadoc for TransactionDefinition.PROPAGATION_SUPPORTS that you linked to (https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/main/java/org/springframework/transaction/TransactionDefinition.java#L64) states, "Support a current transaction; execute non-transactionally if none exists."  The javadoc explicitly states the behavior for PROPAGATION_SUPPORTS methods when there is no surrounding transaction, namely: "execute non-transactionally if none exists".  Based on the documentation you referenced, I simply don't understand how you can conclude that executing a PROPAGATION_SUPPORTS method outside of a surrounding transaction is "not correct or allowed".  In fact, the documentation appears to me to explicitly state the opposite: PROPAGATION_SUPPORTS methods can be executed outside of a transaction--they are just executed non-transactionally in this case.

My actual use case is I have a java class in my grails application annotated @Transactional, and it is using the default transaction propagation of PROPAGATION_REQUIRED.  This class could easily be converted to a grails service class, and I think the issues would be identical.  Most of the methods in this class require a surrounding transaction, so things work great for them.  However, there are a few methods that don't require a transaction.  All they do is a simply read from the database using mybatis (hibernate is not used in these methods).  If they are called from outside a transaction, we don't want to incur the overhead of starting a new transaction since it's not needed.  That is why we've annotated these methods with PROPAGATION_SUPPORTS.  In fact, adding the PROPAGATION_SUPPORTS annotation was done in the past as a performance optimization that really did make a significant difference for us.  That is, we had situations where these methods were  executed many times in a loop, and changing from the default of PROPAGATION_REQUIRED to PROPAGATION_SUPPORTS for these methods sped things up for us a lot, as we didn't incur the overhead of starting a transaction where we didn't need one.  On the other hand, there are other places in our code where we are calling these methods as part of a larger transaction, and we do want them to participate in the enclosing transaction in those cases.  Our usage of PROPAGATION_SUPPORTS seems to be exactly how it was intended--it allows these methods to participate in the enclosing transaction if there is one, but not to start a new transaction if there isn't one.

Our current workaround has been to move our PROPAGATION_SUPPORTS methods into a different class that isn't annotated with @Transactional at all (so no transactions).  We obviously also no longer annotate these methods with PROPAGATION_SUPPORTS since the class isn't transactional at all.  This allows these methods to participate in an enclosing transaction if there is already one started when they are called and to not start a new transaction if one hasn't been started.  We really don't like this solution, however, since the methods we're talking about here should logically belong to just one class.  Also, we haven't had to do this for just one of our classes--we have a number of classes that use PROPAGATION_SUPPORTS in this way, and we've had to break all of them apart into two classes--one class for the PROPAGATION_REQUIRED methods and one class for the PROPAGATION_SUPPORTS methods.  We feel breaking the classes into two parts like this is clunky.

Our code all worked just fine on grails 2.1.0 with its usage of PROPAGATION_SUPPORTS.  We discovered this problem only when attempting to port to grails 2.5.1/3.0.5.  I would also state that I've been using PROPAGATION_SUPPORTS in this way in applications I've worked on since the early 2000s, and it has worked the way I've stated above.  Granted, back then, it was with EJBs not spring, but the spring docs say the behavior of PROPAGATION_SUPPORTS is "analogous to the EJB transaction attribute of the same name."  I have also used PROPAGATION_SUPPORTS in spring-based (non-grails) applications since the mid-2000s, and it has also always worked for me as described above.  I suppose it's possible that I was doing things wrong all these years, misunderstood how PROPAGATION_SUPPORTS is supposed to work, and just got lucky that things seemed to work for me, but grails 2.5.1/3.0.5 is the first and only time in many years of usage that it has given me any problems.

**Comment by graemerocher** [comment]
Will probably take another look at this, but it is a minor issue because you do know that with SQL there is always a transaction, just that when you don't explicitly start one the SQL connection is in "auto-commit" mode so you may be surprised about the overhead (or lack there of) in defining transactions.

**Comment by jonroler** [comment]
In my opinion, this is first and foremost an issue of correctness.  People may want/need to use PROPAGATION_SUPPORTS in their projects for many reasons.  If you want to debate whether the PROPAGATION_SUPPORTS propagation level has any merit at all, then you can go and debate that with the Spring developers that included it in Spring or the EJB specification writers who included it in the EJB specification many years ago.  It's been around forever, and it can be very useful.  The grails documentation says that all the Spring transaction propagation levels are supported in grails, and I agree that this is how grails should work.  However, specifying transaction propagation levels on grails services is simply broken for grails projects that define multiple DataSources right now.

We have code that worked on grails 2.1.0 using PROPAGATION_SUPPORTS but now fails in the grails 2.5/3.0 series.  Somewhere between grails 2.1.0 and 2.5/3.0 this functionality was broken.

I suspect that the vast majority of grails projects only define a single DataSource.  PROPAGATION_SUPPORTS still seems to work fine for projects with one DataSource.  We happen to be in the minority where we have two DataSources defined in our grails project, and unfortunately for us, PROPAGATION_SUPPORTS is broken for this case.  However, grails projects that use multiple DataSources are supposed to be supported, right?

Yes, as I previously mentioned, the main reason we are using PROPAGATION_SUPPORTS is to avoid transaction overhead in certain cases, and yet still keep these related methods together in the same class.  From past experience, having certain methods use PROPAGATION_SUPPORTS was a big performance win for us although we didn't go so far as to determine the reason (database overheard vs. grails/gorm overhead associated with opening/closing transactions).  In my opinion, though, a discussion of whether or not we are actually getting better performance when using PROPAGATION_SUPPORTS is beside the point.  The most important point here is that the grails documentation claims that grails supports all the Spring transaction propagation levels (again, I fully support this decision), and that simply isn't true right now.  It seems like other projects are likely to encounter this problem in the future, and these other projects may have a completely different for using PROPAGATION_SUPPORTS than our project does.

**Comment by graemerocher** [comment]
So yes this should work, we will try to get round to fixing it for GORM 5 GA, and back port the fix to older branches. Otherwise it will have to wait for 5.0.1
