### ISSUE TITLE
Grails 3.0.4: render tag with plugin attributes does not work anymore

### ISSUE THREAD

**Issue by benorama** [grails/grails-core#9150]
It looks like plugin attribute for the render tag is not working since 3.0.2.

For example: this works on 3.0.1 and does not work anymore since 3.0.2
`<g:render template="/tags/init-js" plugin="facebook-sdk"/>`

It throws `Template not found for name [/tags/init-js] and path [/tags/_init-js.gsp]`

Workaround: remove the `plugin` attribute.

To reproduce the issue, first create a basic plugin:
- _grails create-plugin test-plugin_
- create a template `grails-app/views/tags/_hello.gsp` with `Hello from plugin` text
- _grails install_

Then create a basic app to use the plugin:
- _grails create-app test-app_
- add `runtime "org.grails.plugins:test-plugin:0.1-SNAPSHOT"` in _build.gradle_
- add `<g:render template="/tags/hello" template="test-plugin"/>` in `grails-app/views/index.gsp`
- render the page to throw the exception, 
- remove `template="test-plugin`and render the page to see the `Hello from plugin` text.

**Comment by graemerocher** [comment]
I have written a functional test for this and it seems to work as designed:

https://github.com/grails/grails3-functional-tests/commit/f7c334aed87f188700079f31152af04f196d12d8

If you are able to supply an example that reproduces the issue with recent versions of Grails pleas do so and we can reopen.

**Comment by ctoestreich** [comment]
I have found the issue here and logged the specifics in #9406 

@benorama Have you tried using `<g:render template="/tags/init-js" plugin="facebookSdk"/>`
