### ISSUE TITLE
Assets not loaded when deploying on tomcat

### ISSUE THREAD

**Issue by alainperry** [grails/grails-core#9151]
I've been struggling with an asset problem when deploying on tomcat for a few 3.0.x versions now, and I think this is a bug.

```
$ grails create-app assetstests
# [modify build.gradle to change tomcat dependency to "provided"]
$ grails package # (or grails war, result is the same)
$ java -jar assetstests.war # <- this is working fine
```

but when I deploy to tomcat, the grails logo is loaded correctly, but the <head> section doesn't contain the <link> tags for application.css or application.js.

**Comment by alainperry** [comment]
See also http://stackoverflow.com/questions/31399362/grails-3-0-3-with-asset-pipeline-gradle2-3-8-is-not-working-after-unzip-the-dep

**Comment by graemerocher** [comment]
@alainperry Have you tried 3.0.4? A similar issue was addressed, see #9100

**Comment by alainperry** [comment]
Yes, I tried with 3.0.3 and 3.0.4 (with a new, clean project and forcing asset-pipeline plugin to version 3.0.5). I had seen #9100 and hoped it was the same problem.

**Comment by jasonschwab** [comment]
Related? https://github.com/grails/grails-core/issues/9102

I changed my asset pipeline dependency to 3.0.1 and it works deploying as a war.

**Comment by graemerocher** [comment]
@jasonschwab @alainperry Yes it is the same, right now only asset pipeline 3.0.1 is issue very it seems. @davydotcom is working on it thankfully

**Comment by alainperry** [comment]
I confirm 3.0.1 is not affected.

**Comment by davydotcom** [comment]
Figured out the cause 3.0.6 will be out shortly its in the CI server now

**Comment by jeffbrown** [comment]
@davydotcom Do you know if this issue is fixed in 3.0.6?

**Comment by davydotcom** [comment]
Yes Graeme and I confirmed it

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/5c67cd22688f596cf8589958512c8b40cfa1b250
