### ISSUE TITLE
Inline plugin dependencies break app

### ISSUE THREAD

**Issue by topa3k** [grails/grails-core#9152]
Steps to reproduce

1. `grails create-app test251`
2. `grails create-plugin test251plugin1`
3. `grails create-plugin test251plugin2`
4. `cd test251plugin2`
5. `grails create-domain-class com.test.Test`

Project test251: BuildConfig.groovy
`grails.plugin.location.'test251plugin1' = "../test251plugin1"`

Plugin test251plugin1: BuildConfig.groovy
`grails.plugin.location.'test251plugin2' = "../test251plugin2"`

Plugin test251plugin2: Test.groovy
```
class Test {
	String test
    static constraints = {
    }
}
```

Project test251: Bootstrap.groovy
```
class BootStrap {

    def init = { servletContext ->
    	new Test(test:"test").save(failOnError:true, flush:true)
    }
    def destroy = {
    }
}

```

Now when you do `grails run-app` you'll get:
```
Error initializing the application: Method on class [com.test.Test] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
```

If only you switch grails to 2.5.0 everything works as expected.

**Comment by Luxor** [comment]
+1

**Comment by hakanernam** [comment]
This happens to me with 3.0.6 with just a plugin:

```
grails-create-plugin test306
grails create-domain-class com.test.Test
```
Test class and Bootstrap file are the same as above, except Bootstrap.groovy is in init/test306

run-app fails with:

```
ERROR grails.boot.GrailsApp - Application startup failed
java.lang.IllegalStateException: Method on class [com.test.Test] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
```
If this plugin is run as a module of a multimodule project (formerly inline plugin) this problem does not happen.

**Comment by graemerocher** [comment]
Grails does not recursively parse build configurations, to get this to work you must declare both plugins in your application `BuildConfig`:

    grails.plugin.location.'test251plugin2' = "../test251plugin2"
    grails.plugin.location.'test251plugin1' = "../test251plugin1"
