### ISSUE TITLE
Grails 3.0.4: Dynamic scaffolding causes garbled characters

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9154]
The i18n messages are garbled for `ja`, `ru`, etc. For example, `Bookリスト` means `Book List` in Japanese. But `Book???` is displayed, instead.

**Comment by nobeans** [comment]
The example to reproduce it:  https://github.com/nobeans/grails-issues/tree/master/grails3-issue9154

After `run-app`, open `http://localhost:8080/book/index?lang=ja`.

**Comment by graemerocher** [comment]
This has been fixed by https://github.com/grails/grails-core/commit/805b18e7ee764f58b93e3187164976262a76efbe

but can be worked around with the following `resources.groovy`:

	// Place your Spring DSL code here
	import org.springframework.boot.context.embedded.FilterRegistrationBean
	import org.springframework.core.Ordered
	import org.springframework.web.filter.CharacterEncodingFilter
	beans = {

	        characterEncodingFilter(FilterRegistrationBean) {
	            filter = bean(CharacterEncodingFilter) {
	                encoding = "UTF-8"
	                forceEncoding = true
	            }
	            urlPatterns = ['/*']
	            order = Ordered.HIGHEST_PRECEDENCE + 10
	        }	
	}
