### ISSUE TITLE
Grails 3.0.4: exit/Ctrl-C/Ctrl-D make the app be frozen while running app in interactive mode

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9157]
The example to reproduce it: https://github.com/nobeans/grails-issues/tree/master/grails304-sample

After `run-app`, enter `exit` command, `Ctrl-C` or `Ctrl-D`. After that, even if you type any keys, nothing happens. You must kill the process by `kill` command.

After `stop-app`, it works.

**Comment by olavgg** [comment]
Same issue here! Isn't a huge problem, but sometimes annoying.

**Comment by kschmit90** [comment]
Using powershell or cmd on Windows I have to close the terminal completely and re-open to shut down a running application. Previously, in earlier 3.0 versions, I was able to press the up arrow, or Ctrl-C to stop the app.

This is very annoying.

**Comment by graemerocher** [comment]
fixed by https://github.com/grails/grails-profile-repository/commit/2037b1f4f3004ea14f4d1b345aef2585f3edf704
