### ISSUE TITLE
Grails 3.0.4: stop-app doesn't work with spring-security

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9158]
Currently, a `stop-app` command uses the Web API of Spring Boot. (i.e. `http://localhost:8080/shutdown`.) When using spring-security, the URL is protected as default. To succeed, the `user` as a user name  and the UUID as a password which is emitted in INFO log are needed.

**Comment by nobeans** [comment]
The example to reproduce: https://github.com/nobeans/grails3-samples/tree/master/grails-sample-spring-security

```
$ grails
| Enter a command name to run. Use TAB for completion:
grails> run-app
| Running application...
Grails application running at http://localhost:8080 in environment: development
grails> stop-app
| Shutting down application...
| Error Caught exception Server returned HTTP response code: 401 for URL: http://localhost:8080/shutdown (Use --stacktrace to see the full trace)
```

**Comment by graemerocher** [comment]
Yeah not sure what can be done about this, you have to allow the /shutdown endpoint to be accessed without being secured

**Comment by nobeans** [comment]
Yeah, it's a really difficult problem.

> you have to allow the /shutdown endpoint to be accessed without being secured

I think it makes a security hole at runtime. Though, it might be good to limit it only for development environment if I could.

From another point of view, I wish that I could get the UUID password from `org.springframework.boot.autoconfigure.security.SecurityProperties.User` somehow. I'll investigate it some more.

**Comment by graemerocher** [comment]
The `/shutdown` hook already is limited to only development

**Comment by pledbrook** [comment]
Perhaps a JMX endpoint could be used?

**Comment by nobeans** [comment]
The JMX endpoint `org.springframework.boot:type=Endpoint,name=shutdownEndpoint` works with Spring Security.
However, the way of connection to the proper JMX process or port is the next problem.

Example of the script for my trial.
```
import com.sun.tools.attach.VirtualMachine
import javax.management.remote.JMXServiceURL
import javax.management.remote.JMXConnectorFactory
import javax.management.ObjectName

def getJMXLocalConnectorAddresses(applicationMainClassName) {
    final String CONNECTOR_ADDRESS = "com.sun.management.jmxremote.localConnectorAddress"

    return VirtualMachine.list()
        .findAll { it.displayName() == applicationMainClassName }
        .collect { desc ->
            VirtualMachine vm = VirtualMachine.attach(desc.id())
            try {
                def connectorAddress = vm.agentProperties.getProperty(CONNECTOR_ADDRESS)
                if (connectorAddress == null) {
                    // Trying to load agent
                    def agent = [vm.systemProperties.getProperty("java.home"), "lib", "management-agent.jar"].join(File.separator)
                    vm.loadAgent(agent)

                    connectorAddress = vm.agentProperties.getProperty(CONNECTOR_ADDRESS)
                }
                if (connectorAddress) {
                    return connectorAddress
                }
            } finally {
                vm.detach()
            }
        }.findAll { it }
}

// How to get it? How to handle same application with different port?
final applicationMainClassName = 'grails.sample.spring.security.Application'
def addresses = getJMXLocalConnectorAddresses(applicationMainClassName)
JMXServiceURL url = new JMXServiceURL(addresses[0])
def connector = JMXConnectorFactory.connect(url)

//def serverUrl = 'service:jmx:rmi:///jndi/rmi://localhost:9012/jmxrmi' // How to use the fixed port number?
//def serviceUrl = new JMXServiceURL(serverUrl)
//def connector = JMXConnectorFactory.connect(serviceUrl)

try {
    def server = connector.MBeanServerConnection

    def objectName = new ObjectName("org.springframework.boot:type=Endpoint,name=shutdownEndpoint")
    def modules = server.queryNames(objectName, null).collect { new GroovyMBean(server, it) }

    modules.each { mbean ->
        println mbean.dump()
        mbean.shutdown()
    }
} finally {
    connector.close()
}
```

**Comment by jeffbrown** [comment]
Is there a problem with configuring `/shutdown` to be anonymously accessible?

**Comment by nobeans** [comment]
If there would be the documentation for this workaround, it might be acceptable.

At least, currently, a programmer doesn't know that the `stop-app` uses the Web API of `/shutdown`. And the current error message doesn't help with a recognition of a cause and a workaround very much.

I hope that the spring-security plugin for Grails 3.x adds the configuration automatically.

**Comment by jeffbrown** [comment]
> If there would be the documentation for this workaround, it might be acceptable.

Agreed

> I hope that the spring-security plugin for Grails 3.x adds the configuration automatically.

Agreed again.  ;)

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/ad9c24326eb5af18b227b52b010fefe365f1333f
