### ISSUE TITLE
JSON null value in result of grails.converters.JSON.parse()

### ISSUE THREAD

**Issue by pstastny** [grails/grails-core#9162]
Running following code with Grails 2.5.1 fails:
```
import grails.converters.JSON
import org.codehaus.groovy.grails.web.json.JSONObject

def jsonObj = JSON.parse('{ "a": null }')
assert jsonObj.a == JSONObject.NULL
```
With Grails 2.5.0 and earlier versions it was OK.

**Comment by jeffbrown** [comment]
``JSON.parse('{ "a": null }').a` should evaluate to null.  It used to evaluate to `JSONObject.NULL` because of an implementation leak.  See #9129 and #9143.

**Comment by pstastny** [comment]
OK, I see... I was satisfied with previous implementation, it was always enough to test just the the value alone to distinguish between JavaScript  `null` and `undefined` (eg. when supporting optional updates of nullable fields). So I will probably change all involved interfaces to take JSONObject itself together with key and use something like !jsonObj.containsKey(key) to detect `undefined`, I can live with it.

The change probably makes API documentation for JSONObject and JSONObject.Null a little outdated.
