### ISSUE TITLE
Make `compileGroovyPages` take part in incremental build

### ISSUE THREAD

**Issue by pledbrook** [grails/grails-core#9165]
Imagine I run `gradle assemble` in a Grails 3 project and them immediately run again. Nothing should happen as all tasks should be up to date. However, `compileGroovyPages` isn't flagged as `UP-TO-DATE` in this scenario, which indicates to me that it has not be configured for incremental build.

This has a knock on effect since the JAR will always be rebuilt.

**Comment by pledbrook** [comment]
The issue (if [this](https://github.com/grails/grails-core/blob/master/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/web/gsp/GroovyPageCompileTask.groovy) is the underlying task) is that the task does not define any outputs, just inputs. You have to have at least output for incremental build to kick in.

**Comment by graemerocher** [comment]
@pledbrook Well the task extends from `AbstractCompile` which defines an `@OutputDirectory` so I'm not sure yet why this is not working. See https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/compile/AbstractCompile.html#getDestinationDir()

**Comment by pledbrook** [comment]
You're right. But I just noticed that `srcDir` is not marked as an input directory. Any reason for that? Adding that should get things working.

**Comment by graemerocher** [comment]
@pledbrook I will check

**Comment by graemerocher** [comment]
So if I make `srcDir` an `@InputDirectory` it still doesn't working. Turning on Gradle debugging there is this:

     Input file /Users/graemerocher/grails/apps/fresh305/build/classes/main/gsp/views.properties has changed.

The `views.properties` file is generated by Grails, I'm not sure why it is considered an "Input file"

**Comment by graemerocher** [comment]
@pledbrook I guess probably because the `classpath` is an `@Input` and the compiled classes (i.e. `build/classes/main`) are added to the class path

**Comment by pledbrook** [comment]
:+1:
