### ISSUE TITLE
Grails3 build fails without asset-pipeline

### ISSUE THREAD

**Issue by kktec** [grails/grails-core#9167]
After removing asset-pipeline for an API project, the build fails after a 'clean' while running the 'buildProperties' Gradle task, i.e. 

:buildProperties FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildProperties'.
> java.io.FileNotFoundException: C:\workspace-g3\correspondence-service\build\grails.build.info (The system cannot find the path specified)

'clean' removes the build folder. 'assetCompile', which runs before 'buildProperties', recreates the build folder.

'buildProperties' should make sure it exists as well.

**Comment by jeffbrown** [comment]
@kktec Can you clone the project at https://github.com/jeffbrown/noassetpipeline and let me know if you see the problem in that app?

**Comment by kktec** [comment]
I see the same problem on running "gradlew clean build".

**Comment by jeffbrown** [comment]
@kktec Ok... I see now.  I thought the problem was trigged by "./gradlew clean".  Now I can recreate the problem.

Thanks for the feedback.

**Comment by kktec** [comment]
I should have made that clearer that it was running the build task after the clean task.
