### ISSUE TITLE
Can't create url mapping for "/info"

### ISSUE THREAD

**Issue by bvbyd** [grails/grails-core#9168]
Grails 3.x gives `{"app":{"name":"test","grailsVersion":"3.0.4","version":"0.1"}}` response to "/info" request. Creation of any url mapping for "/info" doesn't affect the result.

**Comment by jeffbrown** [comment]
See the Customizing Endpoints notes at http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-endpoints.

If you add the following to `application.yml` that should disable the `info` end point:

    endpoints:
        info:
            enabled: false

Does that work for you?

**Comment by bvbyd** [comment]
Everything works properly. Thanks.

**Comment by guramritpal-jft** [comment]
@bvbyd  close this issue if your problem has been solved.   Thanks
