### ISSUE TITLE
Grails 2.5.1: grailsApplication not injected in DataSource.groovy

### ISSUE THREAD

**Issue by vitgou** [grails/grails-core#9171]
Hi,

The settings declared in `Config.groovy`

```
test.value1 = "one" 
test.value2 = "two"
```

are not available in `DataSource.groovy`

```
println grailsApplication.config.test.value1 
```

declared in `DataSource.groovy` gives 

```
grails run-app
| Compiling 1 source files.....
[:]
[:]
| Running Grails application
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
[:]
[:]
| Server running. Browse to http://localhost:8080/grails251
````

where `[:]` is the result of the println

**Comment by jeffbrown** [comment]
@vitgou Can you describe what types of things you want to define in `Config.groovy` and reference in `DataSource.groovy`?

**Comment by vitgou** [comment]
I'm reading environment variables to configure dynamically the production DataSource url.

Example:

In `Config.groovy`

example.database_url = System.env.EXAMPLE_URL

and in `DataSource.groovy`

```
production {
        dataSource {
            dbCreate = "update"
            pooled = true
            url = grailsApplication.config.example.database_url
```

This was working in grails 2.3.11

**Comment by jeffbrown** [comment]
Thanks for the feedback.

**Comment by erichelgeson** [comment]
@vitgou this does work as well:

```groovy

**Comment by jeffbrown** [comment]
Are you referencing the value of `example.database_url` anywhere outside of `DataSource.groovy`?

**Comment by vitgou** [comment]
@jeffbrown  no only production and development environments

**Comment by jeffbrown** [comment]
It isn't clear why you want to define settings for one config file in another config file.  That is what I am trying to clarify.

**Comment by vitgou** [comment]
All settings used for running the application are declared and gather in just one place and not scattered through several files. 
It is true that I could fetch the value from the environment directly but this behavior was working in grails 2.3.11, so I thought this was a bug.

**Comment by jeffbrown** [comment]
> All settings used for running the application are declared and gather in just one place and not scattered through several files. 

I wouldn't try to avoid having multiple config files.  Grails has multiple config files on purpose.  `Config.groovy` is a general config home.  `DataSource.groovy` is a config file for data source related stuff.  The convention is to define data source related config properties in `DataSource.groovy`.  It isn't clear why you are opposed to that.

> ...but this behavior was working in grails 2.3.11, so I thought this was a bug.

It may be a bug.  We will take a look but even if it is a bug, I would not recommend accessing `grailsApplication` in your `DataSource.groovy` for the reason you have cited.  I don't think there is a good reason to want to do that.

Thanks again for the feedback.

**Comment by jeffbrown** [comment]
@graemerocher Do you think that `grailsApplication` should be made available in `DataSource.groovy`?

**Comment by graemerocher** [comment]
So I don't believe this behaviour was documented as supported as far as I'm aware. The fact that you are reading the configuration which is still being built concerns me (ie. the line `grailsApplication.config.example.database_url`). If you want to have everything in just one file then just put the `DataSource.groovy` contents into `Config.groovy`, this avoids complicating our setup further.

**Comment by jeffbrown** [comment]
> The fact that you are reading the configuration which is still being built concerns me

I think I agree.  Defining values for one config file in another config file is suspect.

I think part of the issue is that `DataSource.groovy` may not really seem like a config file, even though it is.  I think the misperception of that is understandable, but I do think it is a misperception.

I am not in favor of encouraging folks to eliminate `DataSource.groovy`.  I think that is likely to cause confusion for developers who come along later and not really solve any problem.

My vote is to call it Not A Bug.  I think if it worked before, it accidentally worked and wasn't really a feature of the framework.
