### ISSUE TITLE
Grails 3.0.4: Command object binding not working if HTTP method="PUT"

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#9172]
Data binding seems to be not executed if HTTP method is set to "PUT" in combination with a command object:
```
 <g:hiddenField name="_method" value="PUT"/>
```
Controller action:
```
    def update(UpdateOriginCommand updateOriginCommand) {
        if (updateOriginCommand.hasErrors()) {
            respond updateOriginCommand, view: 'edit'
            return
        }

```

This code throws a NullPointerException
```
Cannot invoke method hasErrors() on null object
```

When set to POST
```
 <g:hiddenField name="_method" value="POST"/>
```

all properties are bind correctly.

**Comment by jeffbrown** [comment]
Is `UpdateOriginCommand` a domain class?

**Comment by jeffbrown** [comment]
The notes at http://grails.github.io/grails-doc/3.0.4/guide/theWebLayer.html#dataBinding include the following:

> If the command object's type is a domain class and there is no id request parameter or there is an id request parameter and its value is empty then null will be passed into the controller action unless the HTTP request method is "POST", in which case a new instance of the domain class will be created by invoking the domain class constructor. For all of the cases where the domain class instance is non-null, data binding is only performed if the HTTP request method is "POST", "PUT" or "PATCH".

Is that relevant to your scenario?

**Comment by jeffbrown** [comment]
See the project at https://github.com/jeffbrown/issue_9172.  The binding appears to be working there.

**Comment by jeffbrown** [comment]
@mhuebner Is `UpdateOriginCommand` a domain class?

**Comment by mhuebner** [comment]
@jeffbrown I was on holiday, so here is my reply: ```UpdateOriginCommand``` is a Command Object.

**Comment by jeffbrown** [comment]
@mhuebner If it is a non-domain class command object than the behavior you describe is a bug but I can't reproduce it.  Can you provide a sample app which demonstrates that behavior?  That would be helpful.

Thanks for the feedback.

**Comment by mhuebner** [comment]
@jeffbrown Sure! I will attach a demo app tommorow.

**Comment by mhuebner** [comment]
@jeffbrown Here's my demo app: https://github.com/mhuebner/grails-issue-9172
It seems to have to do with the ```id``` param. I think it is not possible to use an id property like described here: https://jira.grails.org/browse/GRAILS-6190
A solution would be to rename it to ```originId```

**Comment by jeffbrown** [comment]
That would be a bug.  The `id` request parameter should only relevant when the command object is a domain class.

Will get it straightened out.  Thanks for the feedback.

**Comment by jeffbrown** [comment]
@mhuebner 

>  Here's my demo app: https://github.com/mhuebner/grails-issue-9172

When I run that app and access the following:

    curl -X PUT -i http://localhost:8080/demo/create?name=jeff&id=42

The response rendered is "Name: jeff", as expected.  Is that what you are seeing?

**Comment by mhuebner** [comment]
@jeffbrown I'm sorry, I forgot to mention you have to call the update/edit actions. So it should be 
```curl -X PUT -i http://localhost:8080/demo/update?name=jeff&id=42```

This throws a NullPointerException:

```
1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by NullPointerException: Cannot invoke method hasErrors() on null object
-&gt;&gt;   21 | update    in DemoController.groovy
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
```

**Comment by mhuebner** [comment]
@jeffbrown I just realized that domainClass.properties does not return id or value properties of the DomainClass. This is also a problem when you try to bind data.
```
grailsWebDataBinder.bind(myCommandBean, new SimpleMapDataBindingSource(myDomainClass.properties))
```

**Comment by jeffbrown** [comment]
>  I'm sorry, I forgot to mention you have to call the update/edit actions.

@mhuebner Do you have code locally that you haven't pushed?  There are no update/edit actions at https://github.com/mhuebner/grails-issue-9172/blob/ced72be0530cbc5090963b533673d89acb54a1a5/grails-app/controllers/demo/DemoController.groovy

**Comment by jeffbrown** [comment]
The only commit currently showing up in your remote, aside from the initial commit that I made is https://github.com/mhuebner/grails-issue-9172/commit/ced72be0530cbc5090963b533673d89acb54a1a5 which is not relevant to the issue.  That makes me think you have changes that you haven't pushed yet.

**Comment by mhuebner** [comment]
Oops, here we go.

**Comment by jeffbrown** [comment]
The issue here is that the data binding mechnism is treating your `Widget` class as a domain class because `DomainClassArtefactHandler.isDomainClass(org.demo.widget.Widget)` returns true.  See https://github.com/grails/grails-core/blob/v3.0.4/grails-core/src/main/groovy/org/grails/core/artefact/DomainClassArtefactHandler.java#L163

This is a bug.

If you remove the `id` or `version` property from your `Widget` class, I think the problem will go away.

Thanks for the feedback.

**Comment by graemerocher** [comment]
@jeffbrown Since we now have the `DomainClass` trait we should probably change that check
