### ISSUE TITLE
Custom codecs don't support packages in Grails 3

### ISSUE THREAD

**Issue by iamthechad** [grails/grails-core#9176]
In my Grails 2 plugin, I have a custom codec under the package `com.megatome.grails.util`. I've discovered that I can't use packages in Grails 3, and have had to place my codec directly in the `util` folder.

Placing code in a default package is generally a frowned-upon practice. It would be nice if Grails 3 supported packages for custom codecs.

**Comment by jeffbrown** [comment]
Will look into it.  Packages should be supported but the reasons that the default package is generally frowned upon largely don't apply here in part because you should never be writing any code that has compile time dependencies on codec classes, which is when some of the problems with the default package come into play.

Will investigate and get it straightened out.  Thanks for the feedback.

**Comment by jeffbrown** [comment]
I think an exception to that might be when mocking the codec in a unit test.

In any case, I think it should be addressed so thanks again for the feedback.

**Comment by jeffbrown** [comment]
I am having trouble reproducing the problem.  See the project at https://github.com/jeffbrown/issue_9176.  That includes a unit test (https://github.com/jeffbrown/issue_9176/blob/master/src/test/groovy/demo/DemoControllerSpec.groovy) and an integration test (https://github.com/jeffbrown/issue_9176/blob/master/src/integration-test/groovy/demo/PigLatinSpec.groovy) that are both passing.

Can you provide any more details on what you are seeing?

**Comment by iamthechad** [comment]
This is Grails 3.0.1

My test class https://github.com/iamthechad/grails3-recaptcha/blob/master/src/test/groovy/URLSafeBase64CodecTests.groovy references the codec at https://github.com/iamthechad/grails3-recaptcha/blob/master/grails-app/utils/URLSafeBase64Codec.groovy. `gradle test` passes in this configuration.

If I move both classes into `com.megatome.grails`, I get this test failure:

    URLSafeBase64CodecTests > testEncode FAILED
        java.lang.NoClassDefFoundError at URLSafeBase64CodecTests.groovy:45
            Caused by: java.lang.ClassNotFoundException at URLSafeBase64CodecTests.groovy:45

**Comment by jeffbrown** [comment]
@iamthechad Does the code at https://github.com/iamthechad/grails3-recaptcha/pull/3 work for you?

**Comment by jeffbrown** [comment]
@iamthechad If you can provide code which demonstrates the problem, that will make it easier to track down.

Thanks for the feedback.

**Comment by iamthechad** [comment]
@jeffbrown The code in https://github.com/iamthechad/grails3-recaptcha/pull/3 fails for me in the exact manner as I described above, with the `NoClassDefFoundError`.

The Travis build passed because it thought there were no tests for some reason.

**Comment by jeffbrown** [comment]
@iamthechad The test appears to be passing for me.  I will look closer.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
@iamthechad The test task appears to have run for that Travis build.

> :test (Thread[main,5,main]) completed. Took 3.659 secs.

Is there evidence that no tests were actually run?  I don't see in your travis config where you are doing anything with the test reports.

Thanks for the help.

**Comment by jeffbrown** [comment]
@iamthechad 

When I run the following command:

    git clone git@github.com:jeffbrown/grails3-recaptcha.git && cd grails3-recaptcha && git checkout 07276d && ./gradlew test && cat build/test-results/TEST-com.megatome.grails.URLSafeBase64CodecTests.xml
    
This is what I am getting:

    <?xml version="1.0" encoding="UTF-8"?>
    <testsuite name="com.megatome.grails.URLSafeBase64CodecTests" tests="1" skipped="0" failures="0" errors="0" timestamp="2015-08-10T20:43:36" hostname="Jeffs-MacBook-Pro-2.local" time="0.147">
      <properties/>
      <testcase name="testEncode" classname="com.megatome.grails.URLSafeBase64CodecTests" time="0.147"/>
      <system-out><![CDATA[]]></system-out>
      <system-err><![CDATA[]]></system-err>
    </testsuite>

Is that not what you are seeing?

**Comment by jeffbrown** [comment]
@iamthechad Which operating system and which JDK are you using?

**Comment by iamthechad** [comment]
It still fails on my dev machine while passing on the CI box.
My OS is OS X 10.10.4, and JDK is 1.8.0_45. 
I just tried on another Mac with the same OS and JDK and everything works. I'm assuming I have something strange going on with my dev box. I wonder if I should remove all other Grails versions via `gvm` and start fresh.

**Comment by jeffbrown** [comment]
> I wonder if I should remove all other Grails versions via gvm and start fresh.

The number of Grails versions you have installed will not be relevant.  The only one that will matter is the one you are using.
