### ISSUE TITLE
Grails 3 throwing strange exception when using more than 14 Domain classes with @Resource annotation

### ISSUE THREAD

**Issue by akhopkar** [grails/grails-core#9177]
Grails 3 is throwing a strange exception when using REST Resources. What I have noticed is that when I have more than 14 Domain classes with the @Resource annotation it is throw a weird exception and refuses to start with the run-app command. I have checked in code to a github repo to demonstrate the problem. If you get this project and do a grails run-app it will throw an exception. I tried using JDK 7 and JDK 8 and grails 3.0.1 and grails 3.0.4.

Here is the repo that shows a sample project with this problem in action.  If you get the project and do a run-app it won't startup.

Github repo: https://github.com/akhopkar/testREST

The Exception it throws is:

ERROR grails.boot.GrailsApp - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.test.A2Controller': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!

**Comment by jeffbrown** [comment]
@akhopkar 

> I tried using JDK 7 and JDK 8 and grails 3.0.1 and grails 3.0.4.

I am not seeing the problem when I use 3.0.4.  Are you?

**Comment by jeffbrown** [comment]
@akhopkar If you apply the pull requests that I submitted to your project do you still see the error?

**Comment by akhopkar** [comment]
Jeff,

Thanks for your reply and your time.
Actually, I discovered myself that this issue goes away once I use grails
3.0.2 +.

Amarish



On Tue, Aug 11, 2015 at 12:40 AM, Jeff Scott Brown <notifications@github.com

**Comment by jeffbrown** [comment]
Great!
