### ISSUE TITLE
Joda DateTime domain fields not supported in criteria queries during unit test

### ISSUE THREAD

**Issue by zsando** [grails/grails-core#9178]
DateTime fields of Domain classes aren't recognised in criteria queries during unit tests - throws java.lang.IllegalArgumentException.

Example project: <https://github.com/zsando/grails3TestJodaTime>.

May be related to this Grails 2.3.8-era issue - [grails-11388](https://jira.grails.org/browse/GRAILS-11388)

When doing things like the following in unit tests:

````
    def "use DateTime clause in criteria query (unit)"() {
        given:
        Book b1 = new Book(pubDate: new DateTime(), author: "Harper Lee", title: "Go set a watchman")
        b1.save(failOnError: true, flush: true)
        
        when:
        def books = Book.withCriteria {
            gt 'pubDate', (new DateTime()).minusDays(10)
        }

        then:
        books
        books.size() == 1
    }
````

The above results in:
````
java.lang.IllegalArgumentException: Property [pubDate] is not a valid property of class [test.grails11388.Book]
...
````

Doing the same as an integration test works fine.

**Comment by jeffbrown** [comment]
Related to #973

**Comment by zsando** [comment]
Resolved by using [HibernateTestMixin](https://grails.github.io/grails-doc/latest/guide/single.html#unitTestingDomains) as shown in [this patch](https://github.com/zsando/grails3TestJodaTime/pull/1).
