### ISSUE TITLE
Upgrade to Reactor 3

### ISSUE THREAD

**Issue by aaloise** [grails/grails-core#9180]
Consider upgrade to Reactor 3

**Comment by jeffbrown** [comment]
Will do.

Is there anything in particular that you are looking forward to in the update?

**Comment by aaloise** [comment]
Nothing specific. Just to keep grails-plugin-events updated.

**Comment by aaloise** [comment]
Warning! Reactor Spring Components (https://github.com/reactor/reactor-spring) is deprecated due to full reactive support planned by Spring 5 - see https://spring.io/blog/2016/02/09/reactive-spring

**Comment by graemerocher** [comment]
Upgrading is likely to be a breaking API change so we will probably have to create a new plugin that replaces `grails-plugin-events` unfortunately. This time we will have to abstract Reactor to avoid breaking binary incompatible changes that seem to come with each versions of this library.

**Comment by zyro23** [comment]
please keep the reactor version grails is using aligned (or at least compatible) with the `reactor(-tcp)` version `spring-messaging` is using (if it still is with spring5..). if the reactor versions used by grails and `spring-messaging` conflict (which has happened in the past), unfortunately `spring-websocket` does not work with a real message broker (e.g. rabbbitmq/amqp). thank you!

**Comment by graemerocher** [comment]
The time to upgrade Reactor 2.5 will be at the same time of upgrading to Spring 5 which will likely bring a whole bunch of binary incompatible changes anyway (I believe they plan to drop JDK 7 support for example). So at that point we will have to align all the versions again.

**Comment by aaloise** [comment]
![capturar](https://cloud.githubusercontent.com/assets/1064972/19604323/bf51f84e-9782-11e6-978f-09ca27333448.JPG)

**Comment by graemerocher** [comment]
In the end because `reactor-bus` is dead, we implemented our own EventBus abstraction that is pluggable with implementations for RxJava 1.x, 2.x and GPars.

No Reactor 2.x or 3.x support is planned, but could be implemented by a plugin developer or third party. The non-final documentation for this new feature in 3.3 can be found here:

https://async.grails.org/latest/guide/index.html#events

So since in effect has been removed, and we won't be upgrading to Reactor 3.x this issue is redundant.

**Comment by smaldini** [comment]
Just a quick comment, we are looking at this with @lhotari for a potential third-party integration via https://github.com/reactor/reactor-addons/compare/master...lhotari:lh-routingflux. 
This will ultimately help people migrating to reactor 3 in general (reactor 2 still accounts for a large chunk of our usage). We decided to introduce backpressure in event-bus and reuse Flux like spring 5 to produce events to routes. However a processor can be used. The interesting part is that Rxjava2 and reactor3 can reuse the same facilities (not rxjava1 one which is not RS and is breaking in behavior like null handling or some non backpressured flows, or some naming aligned with reactor3).
