### ISSUE TITLE
@Secured Spring Boot annot. breaks Render tag

### ISSUE THREAD

**Issue by tmaus** [grails/grails-core#9186]
Setup:
Spring 3.0.4 (default dependencies)
build.gradle has: 
compile "org.springframework.boot:spring-boot-starter-security" on top

Prepared application for Spring Boot Security (no plugin used .. all hand made)
Everything works fine until I use the "render" tag. 

Render taglib works only for controller that is not annotated (proxied)

Render taglib does not work for proxied controller where methods are annotated like:
@Secured('ROLE_USER')

Symptom: 
Error executing tag <g:render>: null] with root cause

Reason: 
Controller with annotation is Spring-CGLib enhanced and render code (GroovyPagesTemplateRenderer:render... (line 107)) is:
MyController$$EnhancerBySpringCGLIB...@123
So GrailsConventionGroovyPageLocator:findTemplateBinding (line 259) controllerClass is null as no controller can be assigned to the proxied one

Controller without proxying is:
MyController@123 and everything works like a charm. 

Hope I did not waste your guys time

:)

**Comment by jeffbrown** [comment]
> Hope I did not waste your guys time

Not at all.

Can you create a simple sample app which demonstrates the problem and push that to GitHub?  A runnable example would be a big help.

**Comment by tmaus** [comment]
https://github.com/tmaus/grails-3-spring-boot-security-render-issue

Hope that helps
