### ISSUE TITLE
URLMappings routing even upon NON-MATCH

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9188]
URLmappings matches upon a URI sent so you can create matches like so:

    String entrypoint = (apiName)?"${apiName}_v${apiVersion}":"v${apiVersion}"

    static mappings = {
        "/$entrypoint/$controller/$action?/$id?(.$format)?"{
            controller = controller
            action = action
            parseRequest = true
        }
    }

But if this fails to match, the routing is still happening even if no other URLMappings exist. This is testable by doing a println at the method being called as well as the Interceptor before()/after() methods.

When URLMapping handle the routing, it will pass off to the Interceptor and I can see println statements in before() and after() methods. But when URLMapping is not handling it and it still get pass, it bypasses the Interceptor and goes straight to the controller/method where I println a message

A test app is available at https://github.com/orubel/testapp

Good test: curl http://localhost:8080/api_v0.1/post/show
Bad test: curl http://localhost:8080/api_vfred/post/show

**Comment by jeffbrown** [comment]
There may be a misunderstanding about how Grails' url mappings work.  The pattern can include wildcards like this:


    "/$foo/$bar/$baz"(controller: 'something', action: 'somethingElse')
    
When you define a mapping like that, the mapping will match a request to a url like `/one/two/three`.  That would result in the `somethingElse` action in the `something` controller being invoked and there will be request parameters name `foo`, `bar` and `baz` with values `one`, `two` and `three` respectively.

If you have a mapping like this:

    "/$foo/$controller/$action" {
        // ...
    }

Then a request to a url like `/one/two/three` would result in the `three` action in the `two` controller being invoked and there would be a request parameter named `foo` that has a value of `one`.

At https://github.com/orubel/testapp/blob/eecf7733625e9ab81261f369a11ce422b7256647/grails-app/controllers/UrlMappings.groovy#L14 there is a mapping that looks like this:

    "/$entrypoint/$controller/$action?/$id?(.$format)?"{
        controller = controller
        action = action
        parseRequest = true
    }
    
That will match a request to a url like `/api_vfred/post/show`.  That should result in the `show` action of the `post` controller being invoked and there will be an `entrypoint` request parameter with a value of `api_vfred`.

The way that we evaluate those property references in the url mapping is by implementing `getProperty` at https://github.com/grails/grails-core/blob/v3.0.4/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingEvaluator.java#L261.  I suppose we could look at changing that to using `propertyMissing` or similar which would allow property references like this to be used but that would be a breaking change, might have other consequences and I am not sure how widely used it would be.

Input is welcome.

Thanks for your feedback @orubel.

**Comment by jeffbrown** [comment]
I haven't tested it but I think you could probably make it work with something like this:

    class UrlMappings {

        @Value('${info.app.name}')
        String apiName
        @Value('${info.app.version}')
        String apiVersion


        static mappings = {
            String entrypoint = (apiName)?"${apiName}_v${apiVersion}":"v${apiVersion}"
            "/$entrypoint/$controller/$action?/$id?(.$format)?"{
                // I don't think any of the following 3 lines are actually doing
                // anything but that isn't relevant to the bug report here
                controller = controller
                action = action
                parseRequest = true
            }
        }
    }

**Comment by jeffbrown** [comment]
@orubel I sent you a pull request.  Please let me know if that behaves in the ways that you would like for it to behave.

**Comment by jeffbrown** [comment]
Actually, I don't think that is going to work.  I think that will have the same problem because it still requires property resolution.  I am sorry for the noise.

**Comment by jeffbrown** [comment]
Another problem with this approach is it attempts to access instance members from a static context, which the language doesn't allow.

**Comment by jeffbrown** [comment]
I am a little surprised that those `@Value` tags have any effect on anything.  Is the framework creating an instance of `UrlMappings` and initializing those properties?

**Comment by jeffbrown** [comment]
I am trying to think of some kind of option to do what you want to do.  Maybe something like this:

    import grails.util.Metadata

    class UrlMappings {

        static mappings = {
            def apiName = Metadata.current.getApplicationName()
            def apiVersion = Metadata.current.getApplicationVersion()
            def entryPoint = (apiName)?"${apiName}_v${apiVersion}":"v${apiVersion}"

            "/${entryPoint}/$controller/$action?/$id?(.$format)?"{
            }
        }
    }

I feel like there may be a more simple thing, but I think the code above may at least function.

**Comment by jeffbrown** [comment]
I think this can probably be closed as Not A Bug but I am hesitant to do that without some feedback.  I think some problems with the code in the test app are that I don't know how the instance properties would be initialized and even if they were initialized, you shouldn't be able to access their value from the static context where the mappings are defined.

Thoughts?

@graemerocher What do you think?

**Comment by orubel** [comment]
The code does work but that isn't the problem as described in the ticket. The problem is that what SHOULD NOT be mapping, is being passed through to the controller/method still.

The urlmapping is meant to filter out traffic to the controller/method so only specific uri requests get passed. Unfortunately, uri requests that do not match are making it past the URLmapping and to the controller request.

I gave a test case that passes (gets accepted through urlmapping correctly and passed to interceptor) and one that fails but still gets passed to controller

**Comment by orubel** [comment]
#6 change gave me an idea that using dynamically defined variables outside the realm are causing a 'null' in the first field which somehow causes a default match in urlmapping... but NOT in Interceptor.

So it gets passed to controller/method, bypassing the interceptor and thus throwing an error.

I think this is more an issue with a dynamic variable that needs to be set in the config prior to being used in the context of URLMapping.

I'll go ahead and close. Thanks for the help.

**Comment by jeffbrown** [comment]
> The problem is that what SHOULD NOT be mapping, is being passed through to the controller/method still.

I think I disagree with that but I am open to having it explained to me otherwise.  If you have a mapping like this:

    "/$entrypoint/$controller/$action?/$id?(.$format)?"{
    }

That is supposed to match a request like `/api_vfred/post/show`.  That is supposed to be handled by the `show` action in the `post` controller.  There should be a request parameter named `entrypoint` that has a value of `api_vfred`.  That is by design.  

Am I mistaken about that?

**Comment by jeffbrown** [comment]
@orubel Your comment appeared just as I submitted my last comment.

**Comment by jeffbrown** [comment]
> I think this is more an issue with a dynamic variable that needs to be set in the config prior to being used in the context of URLMapping.

I don't think that is correct.  I don't think anything you put in your config is going to have any effect on your URL mapping the way that you have it written.  Config is of no consequence at all there.

**Comment by orubel** [comment]
Yeah in fact, I'm gonna do a rewrite and reduce this to headers.

**Comment by orubel** [comment]
Well if $entrypoint=='api_vfred' then yes, this is a match... as I'm trying to dynamically hardcode it based on the values in the config. This worked in 2.4 but is not working here and I'm having an issue trying to get them to work.

**Comment by jeffbrown** [comment]
> This worked in 2.4 but is not working here and I'm having an issue trying to get them to work.

I think that would be a bug in 2.4.

**Comment by orubel** [comment]
ah it doesn't matter, you are 100% right and I'm going through and reducing the complexity of all of this all over again. It's gotten completely bloated with code that has needed to be stripped out as I go and other issues and it's due for a 100% rewrite. I'm glad I got another pair of eyes. Thanks again.
