### ISSUE TITLE
Custom repository defined in plugin's build config is not included in pom

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#9190]
If plugin defines custom maven repositories in its BuildConfig.
When publishing the plugins, those repositories wont be included in generated pom.xml. So all the applications using that plugin has to manually include those repositories in their buildconfig.

Now, as we are using eather / maven by default with grails.
cant this repositories be included in generated pom.xml

its really broken, a plugin should come as a package, with every thing it needs. users should not be worried about the custom repositories required by the plugin to work successfully.

However this works if the plugin is used as inline plugin. This should be consistent

**Comment by graemerocher** [comment]
it is not recommended or supported to put repos in POM. See http://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/

**Comment by snimavat** [comment]
@graemerocher then it should not work if the plugin is used as inline. The behavior should be same, isnt it ?

**Comment by graemerocher** [comment]
that is debatable, you could argue both ways. As it stands the behavior currently is that inline repositories are inherited and changing that now we represent a breaking change

**Comment by snimavat** [comment]
Yup, that would be a breaking change..

Anyway thanks for clearing this.
