### ISSUE TITLE
single page documentation as pdf - always overuns pdf page boundary on RHS

### ISSUE THREAD

**Issue by woodmawa** [grails/grails-core#9192]
every time i try and get the grails doc as PDF it always shows the about 97% but the RHS never fits the margins

i dont know why the generator cant fit to available doc width.  its frustrating - i print on PDF as ref doc to hand on desk

I end up having to cut and paste sections into word and print that - is this easily fixed?

**Comment by jeffbrown** [comment]
I think this duplicates https://github.com/grails/grails-doc/issues/250.

**Comment by woodmawa** [comment]
Jeff you have closed and referenced duplicate - but when i read that now where does it say that this has been fixed 

has the problem been addressed ?

v3.0.2 is still showing this problem
