### ISSUE TITLE
@Cacheable on controller method does not work

### ISSUE THREAD

**Issue by vkorobkov** [grails/grails-core#9193]
Hello,

I've created an empty grails 3.0.3 application in command line like:
grails create-app cache_test 

And added two classes into it: service and controller:

Service:

    package cache_test

    import grails.plugin.cache.Cacheable
    import grails.transaction.Transactional

    @Transactional
    class IndexService {

        @Cacheable(value = "service")
        def serviceMethod() {
            System.err.println("Service called")
        }
    }

controller:

    package cache_test

    import grails.plugin.cache.Cacheable

    class IndexController {

        def indexService

        @Cacheable(value = "index")
        def index() {
            System.err.println("Invoked")

            indexService.serviceMethod()

            render "Rendered"
        }
    }

So I injected service into controller and controller is calling a method in service. Both methods in service and in controller are marked as @Cacheable.

The problem is, when I do multiple HTTP response like
http://localhost:8080/index/index

Then according the logs I can see that cacheable of service class is working but caching of controller does not:
Invoked
Service called
Invoked
Invoked
Invoked

"Service called" was printed only one time however controller does log each http access. It seems like a bug to me, could you please take a look?

**Comment by jeffbrown** [comment]
This should probably be reported at https://github.com/grails3-plugins/cache/issues.

**Comment by vkorobkov** [comment]
Thanks, raised one for grails3-plugins/cache
https://github.com/grails3-plugins/cache/issues/3

**Comment by jeffbrown** [comment]
Thanks!
