### ISSUE TITLE
Documentation: Improve docs for generating links and specifying the HTTP method

### ISSUE THREAD

**Issue by PStrelchenko** [grails/grails-core#9199]
Grails 3.0.3.

For example, I want to have several actions with different methods in URLMappings like this:

```groovy
"/myLinks/$robot/example"(controller: 'qwerty', action: 'q1') 
"/myLinks/$robot/example"(controller: 'qwerty', action: 'q2', method: 'POST')
"/myLinks/$robot/example"(controller: 'qwerty', action: 'q3', method: 'PUT')
"/myLinks/$robot/example"(controller: 'qwerty', action: 'q4', method: 'DELETE')
"/myLinks/$robot/secondExample"(controller: 'qwerty', action: 'q', method: 'GET')
```
Then, I try to create links for this actions with Grails's createLink method:
```groovy
${g.createLink(controller: 'qwerty', action: 'q1', params: [robot: 'ROBOTO1'])}
${g.createLink(controller: 'qwerty', action: 'q2', params: [robot: 'ROBOTO2'])}
${g.createLink(controller: 'qwerty', action: 'q3', params: [robot: 'ROBOTO3'])}
${g.createLink(controller: 'qwerty', action: 'q4', params: [robot: 'ROBOTO4'])}
${g.createLink(controller: 'qwerty', action: 'q', params: [robot: 'ROBOTO5'])}
```
Expected result:
```groovy
/myLinks/ROBOTO1/example
/myLinks/ROBOTO2/example
/myLinks/ROBOTO3/example
/myLinks/ROBOTO4/example
/myLinks/ROBOTO5/secondExample
```
But actual result is:
```groovy
/myLinks/ROBOTO1/example 
/qwerty/q2?robot=ROBOTO2 
/qwerty/q3?robot=ROBOTO3 
/qwerty/q4?robot=ROBOTO4 
/myLinks/ROBOTO5/secondExample 
```

**Comment by jeffbrown** [comment]
Possibly related to #2212 and/or #2387.

**Comment by graemerocher** [comment]
I don't see this is as a bug, you need to specify the method in `createLink` if you have defined it i the mapping

**Comment by PStrelchenko** [comment]
Yes, it solved this problem, thanks!

But why this 'method' parameter is not described in documentation? As for junior developer, it's very important for me to have actual information about all possible arguments. In documentation for UrlMappings I saw section [Mapping to HTTP methods](https://grails.github.io/grails-doc/latest/guide/single.html#mappingHTTP), but I didn't see information about specifying 'method' parameter for ``` g.link ``` or ``` g.createLink ``` methods.

**Comment by graemerocher** [comment]
agreed the documentation could be improved here

**Comment by vonovak** [comment]
PR: https://github.com/grails/grails-doc/pull/445

**Comment by graemerocher** [comment]
Thanks
