### ISSUE TITLE
Certificate at https://repo.grails.org/grails/plugins has expired

### ISSUE THREAD

**Issue by mikedehaan** [grails/grails-core#9200]
The certificate at https://repo.grails.org/grails/plugins has expired and is failing our builds.

![image](https://cloud.githubusercontent.com/assets/1839244/9443543/363f5300-4a47-11e5-9323-d64a95d88072.png)

**Comment by jeffbrown** [comment]
We are working on getting a new cert issued now.  I the meantime you can probably make everything work by using `http` instead of `https`.  Sorry for the trouble.

**Comment by mikedehaan** [comment]
Feeling foolish here...how exactly do I do that?

I tried commenting out the grails central line in the BuildConfig.groovy and adding the repo manually, but I'm still not able to run a "dependency-report" successfully (same error as before about certificate expired).

From BuildConfig.groovy
```groovy
        //grailsCentral()
        mavenRepo  "http://repo.grails.org/grails/plugins"
```

**Comment by jeffbrown** [comment]
I think something like this should work in a Grails 2 `BuildConfig.groovy`.

    repositories {
        inherits true // Whether to inherit repository definitions from plugins

        // these 2 are temporary while we get a new cert issued...
        mavenRepo  "http://repo.grails.org/grails/plugins"
        mavenRepo  "http://repo.grails.org/grails/core"

        grailsPlugins()
        grailsHome()
        mavenLocal()
        grailsCentral()
        mavenCentral()
    }

**Comment by mikedehaan** [comment]
Perfect. That did it.

Thank you so much!

**Comment by jeffbrown** [comment]
I believe the new certificate may be in place and working.  Feedback welcome.

**Comment by homicki** [comment]
Looks good - thanks for the quick turnaround Jeff!

**Comment by mikedehaan** [comment]
Certificate is indeed in place. Thanks for the quick fix!

![image](https://cloud.githubusercontent.com/assets/1839244/9450276/60904a62-4a6d-11e5-9a01-1a00efef41b2.png)

**Comment by tedder** [comment]
confirmed it is working again in my shop.

**Comment by camilin87** [comment]
The certificate just expired again

**Comment by ilopmar** [comment]
@camilin87 There is a new issue for this. #11082
