### ISSUE TITLE
Binary resources copied incorrectly during compile

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-core#9203]
Binary files such as images and pdf files in src/main/resources is being copied to build/resources/main in corrupted and enlarged form.

To create:

1. grails create app pics
2. place a picture such as cat.jpg into src/main/resources
2. grails compile

Example:
![cat](https://cloud.githubusercontent.com/assets/1321157/9519653/296f7c16-4cc9-11e5-942b-0173f00aebb5.jpg)

which is 13KB, is copied into  build/resources/main upon compile

![cat](https://cloud.githubusercontent.com/assets/1321157/9519661/3b84f7d2-4cc9-11e5-8da6-e6e796eb1357.jpg)

which is 24 KB and is corrupted. Tested with pdf files also.

Environment:
Grails 3.0.4
OSX 10.10.5
JDK 1.8.0_45-b14

**Comment by smartiniOnGitHub** [comment]
Hi, I have a similar problem when running Grails 3.0.4 war from updated webapp runners (both latest jetty-runner-9.2.x for Java 7 and latest tomcat webapp-runner), and in page I get the following error:
ERROR org.springframework.boot.context.web.ErrorPageFilter - Cannot forward to error page for request [/assets/logo.png] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
And all images are damaged (even trying to manually get from browser url), and all other content in the page is not downloaded anymore.
I have Oracle JDK-7u80 and the error is the same in Windows 10 and Ubuntu Linux 14.04.x .
I think should be the same issue seen here, right ?
If you need another issue or more details tell me, this is blocking (I'm unable to make it run at Heroku).
Thanks a lot, Sandro

**Comment by graemerocher** [comment]
@smartiniOnGitHub Example application with steps to reproduce please

**Comment by smartiniOnGitHub** [comment]
@graemerocher Hi Graeme, just committed a sample project with all files and info (and a new issue #9215), tell me for more info or tests.
Thanks a lot for now, Sandro
