### ISSUE TITLE
forward does not handle params

### ISSUE THREAD

**Issue by tcrossland** [grails/grails-core#9204]
Not sure if this is a documentation issue or a bug... but (in Grails 2.5.1) `forward(controller: 'whatever', action: 'whatever', params: ['whatever.id': 'whatever'])` is not actually passing the `whatever.id` parameter.

As a workaround, you can modify the request params before calling `forward`, but ideally either `ForwardMethod` or the documentation for `forward` should be fixed.

**Comment by tcrossland** [comment]
After further investigation, it seems the problem is only with delimited params e.g. `forward(controller: 'a', action: 'b', params: ['c.id': 1])` and it seems that `forward(controller: 'a', action: 'b', params: ['c': 1])` works fine in this case

**Comment by orubel** [comment]
You should be able to reparse them into a nested map

**Comment by tcrossland** [comment]
Closing this issue... using `params: [whatever: 1]' instead of `params: ['whatever.id': 1]` works.
