### ISSUE TITLE
Grails scripts don't recognize fields on superclasses

### ISSUE THREAD

**Issue by spierepf** [grails/grails-core#9205]
My Grails app has a number of domain classes, but two of them are ChannelSpecification and AlarmSpecification. Since all alarms are channels but not all channels are alarms I decided to specify them as follows:

    package channeldatabase
    
    class ChannelSpecification {
        ...
        Integer visibility
        ...
    }
and

    package channeldatabase
    
    class AlarmSpecification extends ChannelSpecification {
        ...
    }
This works just as expected in most places except for Grails scripts where this sort of thing gets me an:

    | Error Error executing script GenerateTxSpecXml: No such property: visibilty for class: channeldatabase.AlarmSpecification
    Possible solutions: visibility (Use --stacktrace to see the full trace)
What am I doing wrong?

**Comment by burtbeckwith** [comment]
Could you share a small sample app showing GenerateTxSpecXml (e.g. on GitHub)?

**Comment by burtbeckwith** [comment]
As pointed out on https://stackoverflow.com/questions/32255382/grails-script-cant-find-field-of-superclass-in-a-subclass it's due to a typo.

**Comment by spierepf** [comment]
Yup. Sorry.
