### ISSUE TITLE
Why always in development environment after war.

### ISSUE THREAD

**Issue by stonelee74** [grails/grails-core#9206]
Althought I got the message "Built application to build/libs using environment: production" after run "grails war", in grails Environment.current == Environment.DEVELOPMENT.

environments:
    development:
        dataSource:
            dbCreate: update # create-drop
            url: jdbc:mysql://localhost:3306/aagdms?useUnicode=true&characterEncoding=UTF-8
            logSql: true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/aagdms?useUnicode=true&characterEncoding=UTF-8
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/aagtest?useUnicode=true&characterEncoding=UTF-8

The datasource is alway equal to "aagdms".

**Comment by stonelee74** [comment]
gradle 2.6, grails 3.0.4

**Comment by kschmit90** [comment]
Maybe look at #9043 possibly the same issue?

**Comment by stonelee74** [comment]
Thanks！
