### ISSUE TITLE
Documentation for mockCommandObject missing

### ISSUE THREAD

**Issue by kastone** [grails/grails-core#9207]
In version 2.2.5 there was an explanation for how to use mockCommandObject in a unit test.
http://grails.github.io/grails-doc/2.2.5/guide/testing.html#unitTestingControllers (Section on Testing Command Objects)

In version 2.4.0 and higher, it seems to have disappeared and skips to how to test command object in context of testing controller action instead.

If the way of testing has changed to using @TestFor instead of mockCommandObject, the documentation is confusing.

**Comment by jeffbrown** [comment]
You shouldn't need `mockForCommandObject` in 2.4.0.  What in particular is it that you are trying to test that might call for that?

**Comment by kastone** [comment]
Jeff,
The testing documentation in 2.4.0 throughout 3.0 still references mockCommandObject so it is confusing.
http://grails.github.io/grails-doc/3.0.0/guide/testing.html#unitTestingControllers
"Testing Command Objects
Special support exists for testing command object handling with the mockCommandObject method. For example consider the following action:"
However nothing after this statement shows the usage.

To answer your question:
I am forced to use the mockCommandObject for testing Web Flow command objects. For non Web Flow command objects I am not. I have uploaded a sample app zip at https://github.com/kastone/grails-webflow-sample for various Web Flow issues we have found during our 2.2.5->2.4.3 upgrade.

What is the status of the Web Flow plugin? How does the Grails team see Web Flow going forward as part of the Grails ecosystem? We are heavily invested in its use but we find it's the biggest pain point in each of our upgrades.

The relevant files in my sample app for this issue in particular are
PlanetController
PlanetFlowController

Unit tests under org.universe.research.validateable package(The following four tests show that for commands used by webflow controllers, the mockCommandObject works but the new way of unit testing in docs does not):
PlanetControllerNoValidateableCommandUsesTestForSpec(non webflow controller unit test works with latest doc suggestion)
PlanetWebflowValidateableControllerUsesMockCommandSpec(works using mockCommandObject)
PlanetWebflowValidateableControllerUsesTestForSpec(webflow controller unit test does not work with latest doc suggestion)

Thanks in advance,
Kathy

**Comment by kastone** [comment]
I am also preparing another issue to submit concerning ValueConverters not triggering for WebFlow command objects during binding. I will be referencing the same sample app... would this be grails-core or plugin issue? The binding behavior changed in core, but it is specific to Web Flow commands.

**Comment by jeffbrown** [comment]
> The testing documentation in 2.4.0 throughout 3.0 still references mockCommandObject so it is confusing.
http://grails.github.io/grails-doc/3.0.0/guide/testing.html#unitTestingControllers
"Testing Command Objects
Special support exists for testing command object handling with the mockCommandObject method. For example consider the following action:"
However nothing after this statement shows the usage.

Right.  The example shows that `mockCommandObject` isn't needed.  The description above the sample just wasn't properly updated.  That is a mistake I made at https://github.com/grails/grails-doc/commit/4c7c3e342ab06a06b6d8402e9ce8ee3c4959a383#diff-0ec9203d3d37c83b9abf623f29123e60.

> What is the status of the Web Flow plugin? How does the Grails team see Web Flow going forward as part of the Grails ecosystem?

Those questions are better suited for the mailing list at https://groups.google.com/forum/#!forum/grails-dev-discuss.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
> The testing documentation in 2.4.0 throughout 3.0 still references mockCommandObject so it is confusing.

The only reference I can find in the latest docs is the 1 that you mentioned above.  Are there others?  Because you mention "throughout" I want to make sure I am not missing some.

Thanks again for the feedback.

**Comment by kastone** [comment]
No that's the only spot I saw. Should I also post the issue I'm having where I need to use mockCommand to unit test Web Flow command objects separately here? Or on the Web Flow plugin issues?
>"To answer your question:
I am forced to use the mockCommandObject for testing Web Flow command objects. For non Web Flow command objects I am not."

**Comment by kastone** [comment]
I meant the doc versions starting at 2.4.0 through the latest docs.

**Comment by jeffbrown** [comment]
The class at https://github.com/kastone/grails-webflow-sample/blob/42d7a3cb2eeec9ff3a4eb69ff1344c3027582320/grails-app/controllers/org/universe/research/PlanetFlowNoValidateableController.groovy#L46 is not a command object class and so it will not be made validateable.  Grails core recoginizes a class as a command object class only if it is used as an argument to a controller action, which that one isn't.  The fact that it is used as an argument to a webflow step isn't relevant.  The test that you have passing at https://github.com/kastone/grails-webflow-sample/blob/42d7a3cb2eeec9ff3a4eb69ff1344c3027582320/test/unit/org/universe/research/validateable/PlanetWebflowNoValidateableControllerUsesMockCommandSpec.groovy#L13 is problematic because it is testing behavior that isn't consistent with what you are going to see at runtime.  The class will be validateable in your test, but not in the app.  Is that correct, or am I mistaken about any of that?

Thanks again for the feedback.

**Comment by jeffbrown** [comment]
I have made a change to the docs at https://github.com/grails/grails-doc/commit/a02692e7e6bcff122d6a86eef790e270a7f59260.  If you have recommendations for other doc changes, please file an issue at https://github.com/grails/grails-doc/issues or a pull request at https://github.com/grails/grails-doc/pulls.

Thanks again!

**Comment by kastone** [comment]
That makes total sense and is illuminating. Thank you! So is the WebflowPlanetCommand object used in e/blob/42d7a3cb2eeec9ff3a4eb69ff1344c3027582320/grails-app/controllers/org/universe/research/PlanetFlowController.groovy also not recognized as a command object by grails core? I had read this doc and assumed it would be. http://grails-plugins.github.io/grails-webflow-plugin/guide/dataBindingAndValidation.html (all the way at the bottom there is example)
> Like regular actions, flow actions also support the notion of guide:commandObjects by defining the first argument of the closure:

**Comment by jeffbrown** [comment]
I think the web flow plugin may be adding runtime validateability to the command object at runtime.  I would recommend a feature request to that plugin to do that at compile time instead of runtime like core does.

**Comment by jeffbrown** [comment]
If there is a reason that it needs to be added at runtime then I think it may make sense to augment the plugin docs to clarify how best to test those.

**Comment by kastone** [comment]
>The test that you have passing at https://github.com/kastone/grails-webflow-sample/blob/42d7a3cb2eeec9ff3a4eb69ff1344c3027582320/test/unit/org/universe/research/validateable/PlanetWebflowNoValidateableControllerUsesMockCommandSpec.groovy#L13 is problematic because it is testing behavior that isn't consistent with what you are going to see at runtime. The class will be validateable in your test, but not in the app. Is that correct, or am I mistaken about any of that?

The class is validateable in the running app without the @Validateable annotation which aligns with what you are saying about the Web Flow plugin making the validation behavior enabled at runtime. The plugin seems mark this as a 'commandClass' and give that object a validate method via metaclassing (in ClosureInvokingAction.groovy), despite grails-core not recognizing it as a true command object. I will bring this up as an issue over at the plugin's github issues.
Thanks for all of your help on clarifying things.

**Comment by jeffbrown** [comment]
>   I will bring this up as an issue over at the plugin's github issues. 

I think that is a good idea.

Thanks again.
