### ISSUE TITLE
Interceptor doesn't matching in prod environment

### ISSUE THREAD

**Issue by rafaelfelini** [grails/grails-core#9208]
Hi guys this issue occurs only in production environment.
The project contains 2 controllers and 2 interceptors, each one log the controller name and the interceptor name.

In dev, when accessing http://localhost:8080/first, the output is:
```
in first interceptor
first index
```

and, when accessing http://localhost:8080/second, the output is:
```
in second interceptor
second index
```

Ok, this is the expected behavior.

But, in production, hitting http://localhost:8080/first, the output is:
```
in first interceptor
in second interceptor
first index
```

and, when accessing http://localhost:8080/second, the output is:
```
in second interceptor
second index
```

Environment:
Grails 3.0.4
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Steps to reproduce:
git clone git@github.com:rafaelfelini/interceptor-issue.git
./gradlew assemble
java -Dgrails.env=prod -jar build/libs/interceptor-issue-0.1.jar 

access localhost:8080/first/
access localhost:8080/second/

**Comment by rafaelfelini** [comment]
Hi @graemerocher, I tested under 3.0.5 and 3.0.6 and the error still occurs.
Tested both versions with both commands:

```grails run-app -Dgrails.env=prod```

and

```
./gradlew assemble
java -Dgrails.env=prod -jar build/libs/interceptor-issue-0.1.jar
```

**Comment by Schlogen** [comment]
Submitted a PR https://github.com/grails/grails-core/pull/9251
