### ISSUE TITLE
Feature request - test if delete was successful

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9209]
I think it would be a good feature to easily determine if a delete was successful. The best option being that instead of returning void on `GormInstanceApi.delete`, it returned a boolean.

`return instance.delete() //Boolean`

If that would introduce overhead that is not desired, I propose that the method return a class that can be used to determine if the delete was successful

`return instance.delete().wasSuccessful()`

**Comment by graemerocher** [comment]
This is a breaking change, the way to test if a delete was successful is to flush the session and catch the exception:

     obj.delete(flush:true)
