### ISSUE TITLE
Have an issue when using grails

### ISSUE THREAD

**Issue by cbyyni** [grails/grails-core#9210]
Hi, guys:
   We encountered an issue when we develop our new program. We use the grails version 2.5.1. 
We found there have an exception existed when a request was posted to back-end. The following is the detail about this exception, Please help to check it.

groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequest#<init>.
Cannot resolve which method to invoke for [interface javax.servlet.http.HttpServletRequest, interface javax.servlet.http.HttpServletResponse, null] due to overlapping prototypes between:
	[interface javax.servlet.http.HttpServletRequest, interface javax.servlet.http.HttpServletResponse, interface javax.servlet.ServletContext]
	[interface javax.servlet.http.HttpServletRequest, interface javax.servlet.http.HttpServletResponse, interface org.codehaus.groovy.grails.web.servlet.GrailsApplicationAttributes]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1146)
	at org.eclipse.jetty.server.AsyncContextState$2.run(AsyncContextState.java:163)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by graemerocher** [comment]
@cbyyni please provide an example that reproduces the problem and upload it to github.

**Comment by cbyyni** [comment]
@graemerocher 
Hi,graemerocher 
 Thanks for your reply. This exception is raised by request occasionally. It's not a special case. So on our server log we could see them at some time.

**Comment by graemerocher** [comment]
@cbyyni Without a reproducible example there is nothing to be done. Please provide one.

**Comment by jeffbrown** [comment]
Possibly related to #610 and/or #611.
