### ISSUE TITLE
@Transational not work in Services

### ISSUE THREAD

**Issue by stonelee74** [grails/grails-core#9211]
grails 3.0.4.
In a method of a service, domain object will save after I threw an exception,
no matter whether I add @Trannsationl annotation or set transactional=true.

**Comment by gilinykh** [comment]
@stonelee74 I think it's important to use unchecked exceptions to rollback transactions (as emphasized in the guide: http://grails.github.io/grails-doc/latest/guide/services.html#declarativeTransactions)
