### ISSUE TITLE
Repository archetype-catalog.xml issue

### ISSUE THREAD

**Issue by milanwebdev** [grails/grails-core#9214]
Dear team,

we're facing some issues trying to configure the Grails core repository in our Sonatype Nexus.
In fact, trying to browse the repository URL at http://repo.grails.org/grails/core/ the file archetype-catalog.xml appears like if it were a directory instead of a file:

archetype-catalog.xml/                                            18-Aug-2014 07:46    -

In some way, the resolution of this XML file seems corrupted and not usable.
Thanks in advance for your help, cheers

**Comment by graemerocher** [comment]
I have sent an enquiry to Jfrog about this.
