### ISSUE TITLE
Problems running with jetty-runner and tomcat-webapp-runner in Grails 3.0.4

### ISSUE THREAD

**Issue by smartiniOnGitHub** [grails/grails-core#9215]
When running Grails 3.0.4 war from updated webapp runners (both latest jetty-runner-9.2.x for Java 7 and latest tomcat webapp-runner), and in page I get the following error:
ERROR org.springframework.boot.context.web.ErrorPageFilter - Cannot forward to error page for request [/assets/logo.png] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
All images are damaged (even trying to manually get from browser url), and all other content in the page is not downloaded anymore.
I have Oracle JDK-7u80 and the error is the same in Windows 10 and Ubuntu Linux 14.04.x .

This is the related issue in my test project:
https://github.com/smartiniOnGitHub/grails3-test/issues/1
all steps are written in TODO.md file in project root.

Note that this is not the same of issue 9203 (just resolved).

If you need more info or details tell me, this is blocking for me (I'm unable to make it run at Heroku).
In the meantime I'll try to deploy the Grails 3 recommended runnable jar way, and see if it works even at Heroku.

Thanks a lot, 
Sandro

**Comment by smartiniOnGitHub** [comment]
Note that running the sample project with a standard task like "gradle assemble" and then running the generated jar works but only in dev environment; if I run "gradle assemble -Dgrails.env=prod" ... all seems to work, but many things inside home page are missing (plugins list, controllers, and dynamic sections in my custom footer), like code sections is gsp pages aren't evaluated (note that I don't have errors in the console so it's not clear what happens).

**Comment by smartiniOnGitHub** [comment]
With the help of Heroku support I'm now looking at a better sample: 
https://github.com/kissaten/grails3-example
looking at mine there are some things to fix (for example using the right version compatible with Grails dependencies of both webapp runners, not trying to run grails fat jar, etc) ...so maybe some of the strange errors I have could be due to some wrong things. Anyway a check at Grails side could be good the same :-) .
Tomorrow I'll update my test project and post here an update (in another private webapp I still have some strange errors but different).
A better documentation/sample on how to use Grails 3 with webapp runners could be really good, I hope these efforts could be good at least for better understand how/what to do in the right way :-) .
Thanks for now and sorry for the noise.

**Comment by smartiniOnGitHub** [comment]
Sorry, just updated to Grails-3.0.4 the Heroku sample but still I get an exception at runtime (maybe there is something in 3.0.4 to fix).
You can find my fork here: https://github.com/smartiniOnGitHub/grails3-example
Note that original errors seem here was because I used a more recent version of webapp-runners, but even in this case I think it worth the case to see if these errors could be resolved.
Tell me if I can do some test or give more info. Bye

**Comment by graemerocher** [comment]
@smartiniOnGitHub The same exception or a different exception? Have you looked at this post where people have had success: http://davydotcom.com/blog/2015-05-31-running-grails-3-on-heroku

**Comment by smartiniOnGitHub** [comment]
@graemerocher I'm sorry but this time it's a different exception, and the article at davydotcom was one of my inspirations for the code; also note that instead my latest grails3-example is derived from a sample project that has been suggested to me by Heroku support, ticket 271566 (but they can't say me more on the new error, which seems a regression in Grails); anyway changing Grails from 3.0.1 to 3.0.3/3.0.4 gives me the error, if you want I can post here some detail.
Last, I find strange that tomcat-webapp-runner 8.x is not compatible with Grails and (even in examples and blogs it's used latest 7.0) ... there isn't a way to get the runner directly from SpringBoot and run it ?
Just for info, trying to run directly the Grails fat jar consumes a lot of ram, so don't know if this could be a good option for this kind of deploy that by default give 512 MB of ram (maybe instead use the Grails runnable war).
I'd like to help you on this, even because this is blocking for me (and probably even to others); tell me if I can do some test or help in some way.
Thanks a lot, Sandro

**Comment by smartiniOnGitHub** [comment]
A quick update, but a good news: updating to Grails 3.0.5 resolve the blocking error, now you can see the app running at https://grails3-example.herokuapp.com/
I'll be happy to update that test app (sources at GitHUB) with feedback from anyone interested.

@graemerocher I think it would be useful the same to keep this issue open to further explore if there is something to improve (or fix) for this type of deploy ... for example it I try to use the Tomcat webapp runner 8.x (aligned with Tomcat used by Grails) I get some dependency error.
Thank you very much for the help and the patience :-) . Bye, Sandro

**Comment by smartiniOnGitHub** [comment]
Hi, I'm sorry to say that even with 3.0.6 the problem is blocking (but with 3.0.5 was Ok) ... I think it should be something related to application.groovy not handled in the right way.

**Comment by graemerocher** [comment]
So I don't see any steps to reproduce in the linked example, Please provide steps on how to reproduce the problem.

**Comment by smartiniOnGitHub** [comment]
Hi Graeme, tomorrow I'll write more info on how to reproduce it. Thanks for
now. Bye
Il 22/Set/2015 12:27, "graemerocher" <notifications@github.com> ha scritto:

**Comment by smartiniOnGitHub** [comment]
@graemerocher to reproduce the error, you have to do: gradle stage
and then run the war using the desired webapp runner (at the moment is active Tomcat webapp runner, but even with Jetty runner is similar):
cd build ; java $JAVA_OPTS -Dgrails.env=prod -jar ../build/server/webapp-runner-*.jar --expand-war --port 8080 libs/*.war
(this is the command line executed at heroku, in a local environment could be simplified).
Note that with 3.0.5 even 'grails run-app' works (in Linux, but in Windows it doesn't run sorry but this could be another story), but not with other releases.

Secondary: if instead I try to use a Tomcat webapp runner 8.x (better aligned to that used in Grails 3) I get other errors.

Last, what do you think on using directly spring-boot-starter-tomcat jar to run it (maybe as an improvement for 3.0.x or maybe for 3.1) ?

Tell me if you need more info. Thank you again, Sandro

**Comment by graemerocher** [comment]
So I'm not sure what you mean by using `spring-boot-starter-tomcat` to run it. This is already possible simply by doing `java -jar build/libs/mywar-0.1.war`. What exactly do you want in addition to that?

**Comment by graemerocher** [comment]
These instructions for Spring Boot should work exactly the same with Grails http://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment-heroku.html

**Comment by smartiniOnGitHub** [comment]
Hi Graeme, sorry for the delay but I was busy ... anyway i did many tests, starting from a merge from a new webapp from Grails-3.0.8. After many tests (you can see in my commits there) I think that the real problem now is due to the presence of some settings for the production environment in application.groovy (with all others in application.yml) ... I added it because at Heroku all references to DB and other services come from an environmental variable. But with a little change (trick ? that could be useful to have in some docs) even in build.gradle that env var become visible even in application.yml, good :-) .
Anyway the problem **was** that running with 'grails run-app -Dgrails.env=prod ' , or generate the war with 'gradle stage' and then run it with 'java -Dgrails.env=prod -Dserver.port=8080 -jar libs\grails3-example-0.2.war' I got a conversion error:
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.Class<?> to type java.lang.String
        at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:176) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.grails.config.NavigableMapConfig.getProperty(NavigableMapConfig.java:199) ~[grails-core-3.0.8.jar!/:3.0.8]
        at org.grails.config.NavigableMapConfig.getProperty(NavigableMapConfig.java:177) ~[grails-core-3.0.8.jar!/:3.0.8]
...

Luckily **now** all works good ... what do you think on add some more info in Grails deployment page ? Could be useful even to others (don't mix application.yml and application.groovy, add variables in build.gradle and call from application.yml, the command-line argument to set the server port, and maybe others).
Sorry for the noise (my problems was generated by many pitfalls), and thank you very much for the help.

Side note: in a newly created test webapp with Grails-3.0.8 I think application.yml has 2 times the required info blocks.
