### ISSUE TITLE
war file fails to start due to JdbcSqlException

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-core#9216]
A newly created app (using grails-core/master) with a single controller and an interceptor fails to start when run as war.

Application runs fine when executed with "grails run-app"

Log message: (full logs included in example)
"""
Caused by: org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-187]
"""

Example app is included in 
https://github.com/hakanernam/bookstore

Environment:
grails-core/master locally installed by ./gradlew/install
Tomcat 8.0.26
JDK 1.8.0_45-b14
OSX 10.10.5

**Comment by graemerocher** [comment]
You can try the 3.0.x branch if you are after 3.0.x snapshots

**Comment by hakanernam** [comment]
Thanks, I've been watching and pulling as you merge into master while waiting for 3.0.5 release. 

I came across this issue when trying to recreate another problem, as I do not use H2. But just tried this with 3.0.4 as well (via gvm) and I still get the same error. Works normally if switched to  MySQL.
