### ISSUE TITLE
Interceptor in inline plugin prevents app start

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-core#9217]
Application fails to start with an inline plugin (submodule) with an Interceptor.

Error summary from stacktrace: (stacktrace included in repo)
""""
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'publisherInterceptor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [publisher.PublisherInterceptor]: Constructor threw exception; nested exception is java.lang.AbstractMethodError
""""

Works if the interceptor is removed from plugin.

Example app  and stacktrace included in (tag: Interceptor_in_plugin)
https://github.com/hakanernam/bookstore

Environment:
grails-core/master locally installed by ./gradlew/install (also tried 3.0.4)
Tomcat 8.0.26
JDK 1.8.0_45-b14
OSX 10.10.5

**Comment by graemerocher** [comment]
I believe this is fixed by https://github.com/grails/grails-core/commit/4386701f81d791de46d30c9c77298e2b20963c23

**Comment by hakanernam** [comment]
Unfortunately it seems to still exist with 3.0.5.

**Comment by graemerocher** [comment]
@hakanernam Running your example app with 3.0.5 works fine for me, might be your locally cached version

**Comment by hakanernam** [comment]
I cloned the repo, but same problem. My working project stopped working as well, so I will  look for some config issue. Thanks.

My last session:

$ git clone https://github.com/hakanernam/bookstore
Cloning into 'bookstore'...
remote: Counting objects: 135, done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 135 (delta 19), reused 131 (delta 15), pack-reused 0
Receiving objects: 100% (135/135), 219.38 KiB | 335.00 KiB/s, done.
Resolving deltas: 100% (19/19), done.
Checking connectivity... done.
$ cd bookstore/
| Grails Version: 3.0.5
| Groovy Version: 2.4.4
| JVM Version: 1.8.0_45
HMBP:bookstore hakan$ grails run-app

BUILD SUCCESSFUL

| Running application...
objc[67180]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
ERROR org.springframework.boot.context.embedded.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException
ERROR grails.boot.GrailsApp - Application startup failed
Exception in thread "main" org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

...

**Comment by hakanernam** [comment]
@graemerocher  Missed setting grailsVersion=3.0.5 in gradle.properties file the last time. It is all fixed now. Thanks again.
