### ISSUE TITLE
Unable to resolve class in a GSP when running grails package

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#9220]
I have an example here:
https://github.com/olavgg/gspimporterror

```
* What went wrong:
Execution failed for task ':compileGroovyPages'.
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /home/olav/projects/test-projects/gspimporterror/build/gsptmp/gsp_gspimporterror_defaultindex_gsp.groovy: 1: unable to resolve class no.olavgg.enums.OrganizationType
   @ line 1, column 1.
     import no.olavgg.enums.OrganizationType
     ^
  
  1 error

```

**Comment by olavgg** [comment]
This is for Grails 3.0.5, worked fine with Grails 3.0.4

**Comment by graemerocher** [comment]
This is a bug in the Gradle plugin, you can workaround it until 3.0.6 is out by using the 3.0.4 gradle plugin:

    dependencies {
        classpath "org.grails:grails-gradle-plugin:3.0.4"
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0'
    }

**Comment by olavgg** [comment]
Thank you for the workaround suggestion! :-)
