### ISSUE TITLE
beforeInterceptor in Controllers not called

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#9222]
While researching #9221 I also tried adding `beforeInterceptor`, which did not work:

Docs: https://grails.github.io/grails-doc/3.0.5/ref/Controllers/beforeInterceptor.html

Code: https://github.com/erichelgeson/filters/blob/master/grails-app/controllers/filters/InterceptorTestController.groovy
```groovy
class InterceptorTestController 
    def bar
    def beforeInterceptor = {
         println "Tracing action ${actionUri}"
         bar = "bar"
    }
    def index() {
      render "foo $bar"
    }
}
```
Expected: foo bar

Actual: foo null

Tested on grails 3.0.4 & 3.0.5

**Comment by graemerocher** [comment]
Duplicates #635

**Comment by erichelgeson** [comment]
Though the grails-doc PR is merged it doesnt look like the docs site has updated with the new content from https://github.com/grails/grails-doc/pull/336/files
