### ISSUE TITLE
SynchronousPromiseFactory doesn't execute closure (2.5.0)

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9229]
Normally:
```
Book.async.task {
    //This will get executed
}
```

When the PromiseFactory is set to SynchronousPromiseFactory
```
Book.async.task {
    // This will not get executed
}
```

You would have to call something on the promise for it to be executed: `get`, `then`, `onComplete`, etc.. This behavior should either be documented or, preferably, modified so it gets executed.

**Comment by Schlogen** [comment]
Here is what I'm doing as a workaround:

```
class UnitTestPromiseFactory extends SynchronousPromiseFactory {

    @Override
    def <T> Promise<T> createPromise(Closure<T>... closures) {
        Promise<T> promise = super.createPromise(closures)
        promise.get()
        return promise
    }

}
```

**Comment by graemerocher** [comment]
I reverted this change, in retrospect it is better to document this behaviour as it provides another upgrade challenge to users trying to upgrade 2.x applications whose tests were generated with `generate-async-controller`. The generated tests expect the promises to only be executed on calling `get()`, so this is essentially a breaking change we introduced in a point release, which was not appropriate and will be reverted for 3.0.8.
