### ISSUE TITLE
importing domain class in GSP causes error for war/package tasks in Grails 3.0.5

### ISSUE THREAD

**Issue by jwagenleitner** [grails/grails-core#9233]
Project that reproduces the issue is at https://github.com/jwagenleitner/gspimport305

After upgrading to Grails 3.0.5 the `war` and `package` tasks produce the following error when a GSP page contains an [import for a domain class] (https://github.com/jwagenleitner/gspimport305/blob/90e5e45dd9885de16d522b42b8cc6825cb46cfff/grails-app/views/author/index.gsp#L1).

```
> Building 50% > :compileGroovyPages > Resolving dependencies ':gspCompile' > Resolving dependencies 'detachedConfigurat
:compileGroovyPages FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovyPages'.
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  C:\Temp\gspimport305\build\gsptmp\gsp_gspimport305_authorindex_gsp.groovy: 1: unable to resolve class example.Book
 @ line 1, column 1.
     import example.Book
     ^

  1 error
```
If the `import` statement is removed and the class is fully qualified (i.e., `example.Book.count()`) the tasks succeed.  It also doesn't seem to be limited to just domain classes, but other class such as those under `src/main/groovy` also.

Environment is:

```
| Grails Version: 3.0.5
| Groovy Version: 2.4.4
| JVM Version: 1.8.0_60
```

This worked in Grails 3.0.4.

**Comment by graemerocher** [comment]
Duplicates #9220

**Comment by jeffbrown** [comment]
This is a bug and I think it is fixed but as an aside, you generally shouldn't have imports in the GSP anyway.  Referencing classes in a GSP is generally a bad idea.  Depending on the specifics, that code most often would be better served if put in a tag lib or at the controller layer.  Just my 2 cents.
