### ISSUE TITLE
Project Docs inside the .war - worked in grails 2.x

### ISSUE THREAD

**Issue by stephanstan** [grails/grails-core#9234]
in grails 2.x it was possible to deploy the project documentation inside the war

In BuildConfig.groovy:
grails.project.docs.output.dir = "web-app/docs"

I tried the same in the gradle - new world - grails 3.0.5 and was not successful

It good to see in grails 3.0.5 that the doc parameter work - cool!
---
grails:
    profile: web
    codegen:
        defaultPackage: pasdocumentation
    doc:
        title: 'PAS Documentation'
        authors: 'Stephan Stan'
    project:
      docs:
        output:
          dir: 'web-app/docs'

**Comment by zyro23** [comment]
i think you may be looking for sth like this (`build.gradle`):
```groovy
jar {
    dependsOn "docs"
    from("${buildDir}/docs") {
        into "public/docs"
    }
}

war {
    dependsOn "docs"
    from("${buildDir}/docs") {
        into "WEB-INF/classes/public/docs"
    }
}
```

**Comment by graemerocher** [comment]
As mentioned this can be done with gradle config

**Comment by stephanstan** [comment]
Cool it worked.  Just added above to build.gradle.  Only thing hold me back was fear...Learned a little about gradle sooner that I expected.

**Comment by zyro23** [comment]
well the gradle config was meant to put your docs into a jar/war build so that you do not need to have those generated files inside your project. if you really want them there, you could generate them into `src/main/resources/public/docs` (perhaps gitignoring that dir as well). the gradle part would then not be needed.

**Comment by graemerocher** [comment]
@stephanstan @zyro23's example copied the docs into `/WEB-INF` which is not public, you would have to change it to copy into the root of the WAR to make them public

**Comment by zyro23** [comment]
@graemerocher yea tried that as a first step but then it does not work as fat jar (and ofc run-app is another story again).
`WEB-INF/classes/public` works fine for a war, even if its run with `java -jar my.war` (https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L208)
