### ISSUE TITLE
Controller unit test request has different behavior than expected (2.5.0)

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9235]
In my application I was using `request.getPart("myFile")` to retrieve the uploaded data. My tests passed using `request.addFile(new GrailsMockMultipartFile("myFile", new byte[0]))`. While deployed in the production environment with tomcat or running locally, `request.getPart("myFile")` is always null.

I'm not sure what the cause of it being null is, however if that is how it would always work across all containers, it should also return null in controller unit tests.

**Comment by Schlogen** [comment]
Confirmed this is working as expected in 3.0.5

**Comment by graemerocher** [comment]
linked sample app is gone?

**Comment by Schlogen** [comment]
@graemerocher Sorry about that - it is available now

**Comment by graemerocher** [comment]
Grails 2.x is in maintenance mode and only blocking bugs and bugs reported by OCi support customers are being fixed. Please upgrade to Grails 3.x.
