### ISSUE TITLE
Delpoying Grails 3.0.5 war to Tomcat 8 does not work.

### ISSUE THREAD

**Issue by johancm** [grails/grails-core#9241]
#### Env
| Grails Version: 3.0.5
| Groovy Version: 2.4.4
| JVM Version: 1.8.0_45

#### Here are the steps I followed
 * grails create-app test
 * gradle build
 * Copy test-0.1.war from <local>/test/build/lib to <server>/apache-tomcat-8.0.26/webapps
 * Confirmed in Tomcat manager that the application is running

##### catalina.out
10-Sep-2015 09:32:37.807 INFO [localhost-startStop-3] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive <server>/apache-tomcat-8.0.26/webapps/test-0.1.war
10-Sep-2015 09:32:42.472 INFO [localhost-startStop-3] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive <server>/apache-tomcat-8.0.26/webapps/test-0.1.war has finished in 4,666 ms

##### localhost.2015-09-10.log
10-Sep-2015 09:32:42.463 INFO [localhost-startStop-3] org.apache.catalina.core.ApplicationContext.log Spring WebApplicationInitializers detected on classpath: [org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration@68263d45]

Trying to access the application by clicking the path link in Tomcat manager gives a HTTP Status 404 error.

**Comment by graemerocher** [comment]
Works fine for me, must be something with your environment

**Comment by CoreKnowledge** [comment]
I occur the same problem with 3.0.8 and 3.0.9.
@johancm was there any solution for you?

**Comment by johancm** [comment]
Unfortunately not. However, one thing to note that might be helpful is 
to remove the version number from the war filename.

Rename test-0.1.war to test.war before you copy it into the WEBAPPS folder.

**Comment by CoreKnowledge** [comment]
@johancm: I found the problem for me: On my server was java 1.7.0, after an update to 1.8.0 it worked fine.
@graemerocher: Maybe you can add this information to the documentation, that java 1.8.0 is required in combination with tomcat 8?
Thanks for your support!
