### ISSUE TITLE
Since 3.0.5, unique constraints for hasOne property doesn't work at unit test

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9242]
Example to reproduce it: https://github.com/nobeans/grails-issues/commit/2ee8088b22378298e6ab246203f78f359bb29082 (Grails 3.0.6)

* Parent: https://github.com/nobeans/grails-issues/blob/master/g306-unique-unit-test/grails-app/domain/g306/unique/Foo.groovy
* Child: https://github.com/nobeans/grails-issues/blob/master/g306-unique-unit-test/grails-app/domain/g306/unique/Bar.groovy
* Spec: https://github.com/nobeans/grails-issues/blob/master/g306-unique-unit-test/src/test/groovy/g306/unique/FooSpec.groovy

When you run `grails test-app --unit`, a test `Foo's bar should be unique, but...` of `FooSpec` is failed at 3.0.6.

When you change the grails version at `gradle.properties` to `3.0.4`, the test is passed.
With `3.0.5`, it's failed as well as 3.0.6.

Another implementation of one-to-one with `belongsTo` works well at 3.0.4, 3.0.5 and 3.0.6.

* Parent: https://github.com/nobeans/grails-issues/blob/master/g306-unique-unit-test/grails-app/domain/g306/unique/Aaa.groovy
* Child: https://github.com/nobeans/grails-issues/blob/master/g306-unique-unit-test/grails-app/domain/g306/unique/Bbb.groovy
* Spec: https://github.com/nobeans/grails-issues/blob/master/g306-unique-unit-test/src/test/groovy/g306/unique/AaaSpec.groovy

**Comment by graemerocher** [comment]
I suspect it is this change https://github.com/grails/grails-core/commit/653a693fbee66d85a961a70e5344a3a298b487fe

**Comment by graemerocher** [comment]
I have reverted the change from https://github.com/grails/grails-core/issues/9242 and since doing so didn't cause the test case provided in that pull request to regress, I don't see why the fix was necessary or supplied that way in the first place. Maybe @slaunay can comment...

**Comment by slaunay** [comment]
From what I remember, I looked at the code history that lead to the regression for the auto-timestamp properties not being populated during unit testing and that line was the one responsible for it:
```java
((AbstractMappingContext)simpleDatastore.mappingContext).setCanInitializeEntities(false) 
```
Because it fixed that issue and did not introduce regressions (at the time of my PR by using the existing unit/integration test suites), I believed it was the proper fix.
That commit was then backported to other branches later (see #578).
