### ISSUE TITLE
StackOverflowError when trying to override and invoke a core tag

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9243]
trying to override/wrap `g:form` i get a `StackOverflowError` but do not know why:

```groovy
class OverrideTagLib {

	@Autowired
	FormTagLib formTagLib
	
	def form = { attrs, body ->
		out << formTagLib.form(attrs, body)
	}
	
}
```
```
java.lang.StackOverflowError: null
 at ...OverrideTagLib$_closure1.doCall(OverrideTagLib.groovy:12)
 at ...OverrideTagLib$_closure1.doCall(OverrideTagLib.groovy:14)
 at ...OverrideTagLib$_closure1.doCall(OverrideTagLib.groovy:14)
 at ...OverrideTagLib$_closure1.doCall(OverrideTagLib.groovy:14)
```

* used grails-3.0.5 ootb
* the "offending" line is the last one (`out << formTagLib.form(attrs) { myBody }`)
* the original tag body does not contain further calls to `g:form`.
* adding `static namespace = "g"` makes no difference
* extending `FormTagLib` and calling `super.form(...)` makes no difference

sample app: https://github.com/zyro23/grails-core-9243

**Comment by Schlogen** [comment]
I'm not sure why this is getting that exception, however you certainly would want to call `out <<` as it is doing that already.

This is working for me:

```
def form = { attrs, body ->
	formTagLib.form.call(attrs, body)
}
```

**Comment by zyro23** [comment]
working for you with grails 3? how did you get hold of the `formTagLib`? i tried removing `out <<` but still see a stackoverflow..
```
java.lang.StackOverflowError
Around line 12 of grails-app\taglib\example\OverrideTagLib.groovy

9:	FormTagLib formTagLib
10:	
11:	def form = { attrs, body ->
12:		formTagLib.form(attrs, body)
13:	}
14:	
15:}
```

**Comment by Schlogen** [comment]
Your didn't copy my example. The difference is how the closure is executed. `()` vs `.call()`

**Comment by zyro23** [comment]
you are right. and thank you very much! that works. but i am, too, a bit suprised that it seems a closure defined as `Closure myClosure = { "why?" }` invoked with `myClosure()` leads to a stackoverflow? keeping this open for now. if this is intended/expected behavior, please feel free to close.

**Comment by jeffbrown** [comment]
I sent a PR at https://github.com/zyro23/grails-core-9243/pull/2 which shows another way to do this, but not sure that really solves your problem because it puts your tag in a different namespace which is fine for your own code that is calling the tag but won't affect GPS provides by plugins that won't be referencing your namespace.

**Comment by jeffbrown** [comment]
I think I see what is going on here and am not sure this is really a bug.  Maybe it is, but it is a bit of a peculiar use case.

The tag in question looks like this:

```
package example

import org.grails.plugins.web.taglib.FormTagLib
import org.springframework.beans.factory.annotation.Autowired

class OverrideTagLib {

	@Autowired
	FormTagLib formTagLib
	
	def form = { attrs, body ->
		out << formTagLib.form(attrs, body)
	}
	
}
```

I think that call to `formTagLib.form(attrs, body)` is being handled by a `methodMissing` that will attempt to find the tag that has a name that matches the method name, `form`.  It will look for that tag in the `g` namespace.  The `form` tag in the `g` namespace is the `form` tag defined above so it ends up calling itself which leads to overflowing the stack.

I haven't run it in a debugger, but I think that may be what is happening.
