### ISSUE TITLE
Cannot access domain class constraints

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-core#9245]
A new grails application, a domain class and a controller:

```
class Car {
    String brand = "Ford"
    static constraints = {
        brand(blank:false, inList:["Ford","BMW","Vw"])
    }
}

class CarController {
    def index() {
      Car car = new Car(params)
      println car.constraints.brand.inList
     
     [car:car]
   }
}
```
print statement results in groovy.lang.MissingPropertyException:

![screenshot at sep 10 16-22-50](https://cloud.githubusercontent.com/assets/1321157/9789602/c765d13e-57d9-11e5-9d8e-66f908716019.png)

This happens in gsp files and forms as well. Broke a form about 4 years old.

Env:
Grails 3.0.6
MacOS 10.10.5
JDK 1.8.0_45-b14

**Comment by graemerocher** [comment]
In 3.0.x this should be accessed with `Car.constrainedProperties`, we should have updated the upgrade notes though.

**Comment by hakanernam** [comment]
Thanks. I will attempt to add this to documentation. The exception message was really unhelpful.

**Comment by hakanernam** [comment]
I tried to adapt 'constraints' example from the docs:
```
class CarController {

    def index() {
      Car car = new Car(params)

      def constraintsMap = Car.constrainedProperties
      println constraintsMap  //prints: [:]

      for(entry in constraintsMap) {  //Nothing is printed.
         def propertyName = entry.key
         def constrainedProperty = entry.value

         println propertyname+","+constrainedProperty
      }
      render car
   }
```
But Car.constrainedProperties is an empty map.

**Comment by Schlogen** [comment]
@graemerocher I looked into this. It was empty for me as well. What's interesting is if you do `new DefaultGrailsDomainClass(Car).constrainedProperties`, it produces the expected result

**Comment by graemerocher** [comment]
Will look into it, thanks for the feedback

**Comment by graemerocher** [comment]
Pull request here https://github.com/grails/grails-core/pull/9247

**Comment by Schlogen** [comment]
Closed and re-opened PR with a different target branch https://github.com/grails/grails-core/pull/9249
