### ISSUE TITLE
Grails 3.0.6 ConversionFailedException

### ISSUE THREAD

**Issue by kwongpan** [grails/grails-core#9252]
Getting the following error when running a grails 3.0.6 project

org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type java.lang.Boolean for value '${DBM_UPDATE_ON_START:false}'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value '${DBM_UPDATE_ON_START:false}'

it was working fine when running with grails 3.0.5

my goal is to read the config value from the env variable:
https://github.com/kwongpan/g306/blob/master/grails-app%2Fconf%2Fapplication.yml#L72
https://github.com/kwongpan/g306/blob/master/build.gradle#L91-L93

**Comment by graemerocher** [comment]
duplicates #9248
