### ISSUE TITLE
In Grails 3.0.06 while in run-app mode changed code gets compiled, but the changes to do refelect when app is run

### ISSUE THREAD

**Issue by lksudha** [grails/grails-core#9261]
In 3.0.6 with run-app in dev mode and changes mode to any controller, the code get complied. how ever the changes are not reflected on the view. We have to quit from run app mode and again grail run-app for the changes to take effect. I am not sure whether this is a bug or a change in the new version

**Comment by graemerocher** [comment]
This is an issue local to your environment, check your OS permissions and ensure your app directory is writable.
