### ISSUE TITLE
MissingMethodException when using dynamic finder after upgrade to Grails 3.0.6

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#9262]
After upgrading a Grails 2.5.1 application to Grails 3.0.7 I am having troubles to get my unit tests working again. The issue seems to be reproducible by using a brand new Grails 3.x app and implement the same unit test.

There is a very simple domain called `Team`

    class Team {

       String name
       String shortName
       String image = 'noimage.jpg'

       static constraints = {
           name nullable: false, maxSize: 30, unique: true
           shortName nullable: true, maxSize: 5
           image nullable: false, maxSize: 30
       }
    }

and a corresponding unit test

    @TestMixin(HibernateTestMixin)
    @Domain([Team])
    class TeamSpec extends Specification {

       def setup() {
           new Team(name: 'Hello', shortName: 'Big').save()
       }

       void "test something"() {
           expect:"fix me"
               !Team.findByName('hello')
       }
    }

When I execute the test by using `grails test-app -unit` the test fails with the following exception.

    groovy.lang.MissingMethodException: No signature of method: static abc.Team.findByName() is applicable for argument types: (java.lang.String) values: [hello]
    at abc.TeamSpec.test something(TeamSpec.groovy:24)

The example application can be found at https://github.com/saw303/abc

**Comment by sergiomichels** [comment]
Using the ```@TestFor``` and the dynamic finder, the ```methodMissing()``` from ```GormStaticApi``` is called and the method is resolved. This is not happening when the mixin ```HibernateTestMixin``` is used.

I can see that ```HibernateGormStaticApi``` is used in the startup process, so needs more investigation to discover why the method is not called.
