### ISSUE TITLE
GroovyPagePlugin (gradle) generates invalid classpath entry

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9265]
i came across this problem when trying to use a fresh 3.0.7 app with eclipse (`gradlew cleanEclipse eclipse`). then, `.classpath` contains an invalid entry:

`Project 'my-project' is missing required library: '/path/to/my-project/gsp-classes'`

not applying `org.grails.grails-gsp` in `build.gradle` removes the problem (but gsp support as well, ofc...)

* is this a problem with the eclipse plugin or is maybe the `gsp-classes` directory location in `GroovyPagePlugin` at some point resolved relative to the project dir and not the buildDir (as i think it is meant to be)?
* however, as far as I understand this, that `gsp-classes` is only relevant when building the artefacts and not when running the exploded app in dev mode, right? if that guess is right then there is no reason at all to add that dir to the project classpath that is being picked up by the ide plugins?
* and even if it should be correct that it is added to the classpath, that should not be done if the directory is not present (e.g. after clean, when there has been no run of `jar`/`war`/etc.)

thanks, zyro

**Comment by graemerocher** [comment]
I'm not sure why this would create a problem, the plugin creates another output directory here:

https://github.com/grails/grails-core/blob/master/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/web/gsp/GroovyPagePlugin.groovy#L37

It seems that this causes an issue for Eclipse, which uses the Gradle Tooling API. Maybe @alkemist could comment, but it doesn't seem like a Grails bug?
