### ISSUE TITLE
Scaffolding Controller does not scaffold index changes

### ISSUE THREAD

**Issue by Shinigami92** [grails/grails-core#9271]
I have applied 'install-templates' to my grails 3.0.6 project and have edited in controller index method this line
```
params.max = Math.min(max ?: 25, 100)
```
to
```
params.max = Math.max(Math.min(max ?: 25, 100), 1)
```
The changes are not adopted after a new start.
I have overriden the index method in my Controllers and there it works.

**Comment by hakanernam** [comment]
Please see discussion:

https://github.com/grails/grails-core/issues/9155
