### ISSUE TITLE
Grails 3.0.7 - gradle publish - missing versions in generated pom-default.xml

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#9276]
Ok, I have to file another issue which is related to the gradle publish task. Currently I a am not able to say if this is a Gradle or a Grails issue.
The version attribute is missing in the "default" dependencies:

```
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-logging</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-autoconfigure</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.grails</groupId>
      <artifactId>grails-web-boot</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.grails</groupId>
      <artifactId>grails-dependencies</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
```
When an app or plugin is published to a maven repo and it is used as a dependency - you'll get an exception:

```
Unable to resolve version for dependency 'org.springframework.boot:spring-boot-starter-logging:jar'
...
```

**Comment by graemerocher** [comment]
This is not a bug, we provide the ability to omit dependency versions in `build.gradle` as a convenience but if you plan to publish your app / plugin you should include concrete versions

**Comment by houbie** [comment]
> we provide the ability to omit dependency versions in build.gradle as a convenience 

When you cannot publish artefacts without specifying these versions, it is only a half convenience :(
Can't this be solved by simply importing the spring-boot BOM in the grails BOM?

      <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>[1.3.3.RELEASE]</version>
            <type>pom</type>
            <scope>import</scope>
      </dependency>

**Comment by houbie** [comment]
Workaround: when you want to use the spring-boot preferred versions (from the spring-boot BOM), you can add following to your build.gradle:

    configurations {
        all { configuration ->
            if (configuration.name == 'compile') {
                configuration.incoming.afterResolve {
                    def springBootVersion = configuration.resolvedConfiguration.resolvedArtifacts.findAll {
                        it.moduleVersion.id.name == "spring-boot"
                    }.moduleVersion.id.version
    
                    def projectPom = {
                        project {
                            dependencyManagement {
                                dependencies {
                                    dependency {
                                        groupId 'org.springframework.boot'
                                        artifactId 'spring-boot-dependencies'
                                        version springBootVersion
                                        type 'pom'
                                        scope 'import'
                                    }
                                }
                            }
                        }
                    }
    
                    //install is only available when using the maven plugin
                    install {
                        repositories.mavenInstaller {
                            pom projectPom
                        }
                    }
                    uploadArchives {
                        repositories {
                            mavenDeployer {
                                pom projectPom
                            }
                        }
                    }
                }
            }
        }
    }
