### ISSUE TITLE
[version 2.5.0] 'in' operator doesn't work in unit tests

### ISSUE THREAD

**Issue by nilskuhn** [grails/grails-core#9279]
Hi all,

unfortunately the _in_ operator doesn't provide expected results in unit tests with version 2.5.0 :(

Can be reproduced by:

	grails create-app inOperatorDoesntWorkInGrails250
	cd inOperatorDoesntWorkInGrails250
	grails
	create-domain-class Author
	create-domain-class Book
	create-service BookDao

grails-app/domain/inOperatorDoesntWorkInGrails250/Author.groovy

    class Author {
        String name
        static constraints = {
        }
    }

grails-app/domain/inOperatorDoesntWorkInGrails250/Book.groovy

    import inoperatordoesntworkingrails250.Author

    class Book {
        String name
        Author author
        static constraints = {
        }
    }

grails-app/services/inoperatordoesntworkingrails250/BookDaoService.groovy

    import grails.transaction.Transactional
    import inoperatordoesntworkingrails250.Book

    @Transactional
    class BookDaoService {

        List<Book> getByAuthors(List<Author> authors) {
            return Book.where{ author in authors }.list()
        }

    }

test/unit/inoperatordoesntworkingrails250/BookDaoServiceSpec.groovy

    import grails.test.mixin.TestFor
    import spock.lang.Specification
    import inoperatordoesntworkingrails250.Author
    import inoperatordoesntworkingrails250.Book

    @TestFor(BookDaoService)
    @Mock([Author,Book])
    class BookDaoServiceSpec extends Specification {

        void "Books can be found by author."() {

            setup: "Creating authors and books."
            Author adams = new Author(name: "Douglas Adams").save(failOnError: 'true')
            Author meyerhoff = new Author(name: "Joachim Meyerhoff").save(failOnError: 'true')
            new Book(name: 'Per Anhalter durch die Galaxis', author: adams).save(failOnError: 'true')
            new Book(name: 'Wann wird es endlich wieder so, wie es nie war', author: meyerhoff).save(failOnError: 'true')

            when: "Getting books by list of authors."
            List<Book> books = service.getByAuthors([adams,meyerhoff])

            then: "The service will find them"
            books.size() == 2

        }

    }

Unfortunately _grails test-app_ provides an empty list:

    | Failure:  Books can be found by author.(inoperatordoesntworkingrails250.BookDaoServiceSpec)
    |  Condition not satisfied:
    books.size() == 2
    |     |      |
    []    0      false
            at inoperatordoesntworkingrails250.BookDaoServiceSpec.Books can be found by author.(BookDaoServiceSpec.groovy:33)
    | Completed 1 unit test, 1 failed in 0m 3s

I've just updated my project from version 2.3.7. Here the exact same service method in the same unit test provides a list with two books as expected.

    Book.list().findAll{authors.contains(it.author)}

works well, too. Criterias with _in_ operator work in production code, too. So seems to be the mocked GORM logic in unit tests that is broken in version 2.5.0.

Same error with version 2.5.1.

Regards, Nils

**Comment by graemerocher** [comment]
I wrote a test for this and it appears to be fixed in 3.x master:

https://github.com/grails/grails-core/issues/9279

**Comment by nilskuhn** [comment]
Thanks for taking over my test. 
But what does the fix in Branch 3.x of grails-data-mapping repo mean for me?
In which grails version will this be fixed?

**Comment by graemerocher** [comment]
Try Grails 2.5.1 or 2.5.2 when it is out

**Comment by nilskuhn** [comment]
I already tried with 2.5.1. Same error.
I will try 2.5.2, thanks.
