### ISSUE TITLE
show standard out and standard error during integration test - grails 3.0.7

### ISSUE THREAD

**Issue by vitgou** [grails/grails-core#9280]
Hi, 

With grails 3.0.7 I added the following configuration to the default build.gradle:

```
test {
  testLogging.showStandardStreams = true
}
```
And I created the following integration test:

```
package grails307

import grails.test.mixin.integration.Integration
import grails.transaction.*
import spock.lang.*

@Integration
@Rollback
class ExampleIntegrationSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }

    void "test something"() {
        println "Standard ouput during a test"
        expect:"fix me"
            true == false
    }
}
```

If the same println is in a `unit test` I see the standard output of the test on the console. I'm expecting to see the print on the console during the integration tests as well. Am I doing something wrong?

**Comment by graemerocher** [comment]
This works:

    integrationTest {
        testLogging {
            exceptionFormat = 'full'
            events 'failed', 'standardOut', 'standardError'
        }
    ​
        beforeTest { descriptor -> logger.quiet " -- $descriptor" }
    }
