### ISSUE TITLE
[2.4.5] Intersect no longer works if the contents of the compared Collections are Maps 

### ISSUE THREAD

**Issue by jguertin-gls** [grails/grails-core#9281]
In Grails 2.4.5, when I compare to lists with intersect, and both lists contain maps, I do not get any results, even if the contents are equivalent.  This worked correctly with Grails 2.4.4.  I am running Java 1.8.0_60 on Mac OS X.

Take this example unit test:
```
    void testIntersect() {
        def list1 = [[language: 'Java'], [language: 'Groovy'], [language: 'Scala']]
        def list2 = [[language: 'Groovy'], [language: 'JRuby'], [language: 'Java']]
        def intersection = list1.intersect(list2)

        assert list1[0] == list2[2] // proves that there should be intersecting values
        println "Intersection: $intersection"
        assert intersection == [[language: 'Groovy'], [language: 'Java']]
    }
```

The intersect call returns an empty list, resulting in the following output:
```
Intersection: []
Failure:  |
testIntersect
 |
Assertion failed: 

assert intersection == [[language: 'Groovy'], [language: 'Java']]
       |            |
       []           false
```

**Comment by lhotari** [comment]
Looks like a Groovy bug possibly caused by https://github.com/apache/incubator-groovy/commit/4a5bb22d change. Please report to https://issues.apache.org/jira/browse/GROOVY

**Comment by jguertin-gls** [comment]
You are correct, I've reported it to Groovy: https://issues.apache.org/jira/browse/GROOVY-7602
