### ISSUE TITLE
Skip to content mecanism doesn't work

### ISSUE THREAD

**Issue by bgoetzmann** [grails/grails-core#9284]
Hello, I observed that in a fresh Grails 2.5.1, "Skip to content..." mecanism that is used in scaffolding doesn't work (it's for accessibilty, see [here](http://accessibility.oit.ncsu.edu/training/accessibility-handbook/skip-to-main-content.html)).

In order to make it work, I added this in main.css:
```css
a.skip:focus, a.skip:active {
	position: relative;
	left: 0px;
}
```

And in views/templates that use it, `tabindex="-1"` must be moved from `<a class="skip" tabindex="-1" ...` to the target anchor.

So you will able to skip to content with keyboard using tabs (two tabs and the link  "Skip to content..." will appear), and then enter.

**Comment by graemerocher** [comment]
Could you send a pull request?

**Comment by bgoetzmann** [comment]
Ready to emit pull requests: one for the main.css change in grails-core, and one for grails-scaffolding plugin for .gsp files changes.

**Comment by graemerocher** [comment]
Thanks!
