### ISSUE TITLE
ForwardUrlMappingInfo and RequestForwarder have URI variable but no Setter or functionality

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9291]
RequestForwarder does not have way to implement 'URI' as set in ForwardUrlMappingInfo. This causes issue when using 'uri' in match for HandlerInterceptor and doing redirect/forward based on uri.

**Comment by orubel** [comment]
Easy fix by adding following to ForwardMappingInfo...

    void setURI(String uri) { URI = uri }
    String getURI() { URI }

and to RequestForwarder...

            if(URI) {
                def convertedURI = convert(URI.toString())
                webRequest.URI = convertedURI
            }

**Comment by jeffbrown** [comment]
`URI` is a Groovy property defined at https://github.com/grails/grails-core/blob/0b1d6a6d02f2217643a69e8314f76078dacbce32/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/ForwardUrlMappingInfo.groovy#L34.  Isn't the compiler generating a corresponding getter and setter?

**Comment by jeffbrown** [comment]
```
groovy:000> 
groovy:000> org.grails.web.mapping.ForwardUrlMappingInfo.getDeclaredMethod('setURI', [String] as Class[])
===> public void org.grails.web.mapping.ForwardUrlMappingInfo.setURI(java.lang.String)
groovy:000> 
groovy:000> org.grails.web.mapping.ForwardUrlMappingInfo.getDeclaredMethod('getURI', null)
===> public java.lang.String org.grails.web.mapping.ForwardUrlMappingInfo.getURI()
groovy:000> 
```

**Comment by orubel** [comment]
I can double check but does that still work with RequestForwarder if it isn't setting it?

**Comment by orubel** [comment]
Thanks for feedback. I'm assuming this is non-issue for ForwardUrlMappingInfo and have rewritten submitted issue for RequestForwarder not setting URI as provided by ForwardUrlMappingInfo

**Comment by orubel** [comment]
I believe this affects all versions of 3.0+

**Comment by orubel** [comment]
just got around to giving it a try and in HandlerInterceptor after() it WILL forward URI but NOT params...

forward(URI:uri, id:params.id, params:[params as Map])

Not sure if I'm doing this incorrectly

**Comment by jeffbrown** [comment]
> forward(URI:uri, id:params.id, params:[params as Map])

I don't know why you want to forward from an after interceptor.

I also don't know what the intent was behind `params:[params as Map]` but that is going to make the value of params be a List that includes a Map in it, which probably isn't what you want.

**Comment by orubel** [comment]
ah... was getting error saying it was LinkedHashMap when I sent as params:params. That seemed to fix. :)

if you are curious, sending from handlerInterceptor:after() allows for api monad. can chain api calls by sending output of one api as input to the next as long as you have auth. Fun stuff
