### ISSUE TITLE
Grails 3.0.1 - Groovy files in grails-app/conf are ignored when running app in Eclipse

### ISSUE THREAD

**Issue by provirus** [grails/grails-core#9295]
At first, I wanted to add application.groovy to dynamically configure the datasource and when running in eclipse (using a Gradle project), it was ignoring the file. I also tried to add a property and display it in Bootstrap, without success, so it was really ignored.

Then, I wanted to add some logging, so I modified logback.groovy by changing the root logger to DEBUG, but in the console, I was only seeing the INFO as usual.

Just to confirm my thoughts, I compiled the application with Gradle and ran it (all with command line).
I got all the DEBUG information, I saw my added property displayed and it used my DB configured dynamically.

**Comment by graemerocher** [comment]
The eclipse tooling is not maintained by the Grails team

**Comment by provirus** [comment]
Are you saying that the "logic" on how to build the Grails Gradle project is not in the Gradle's project org.grails:grails-gradle-plugin ?

**Comment by graemerocher** [comment]
I mean that when you run a Grails application using the `static void main` in the `Application` class in Eclipse, it is Eclipse producing the classpath and the Gradle plugin is not invoked. The bug therefore is in Eclipse

**Comment by provirus** [comment]
ok

A basic gradle project does nothing without plugins.
When I use Eclipse, it knows that it needs to compile everything in "init", "service", "views", ... but for some reason, it fails to do it for the "conf" folder.

The thing that tells Eclipse how to build is your Grails Gradle Plugin and it is successful for everything, but the "conf" folder.

So my last question would be, what is done differently for that folder (what different Gradle feature is it using that the other folders are not)? Because, yes your plugin works with Gradle, but on my side, what missing/buggy feature I should ask the eclipse gradle plugin team to build/fix?

Thanks for your help

**Comment by graemerocher** [comment]
The `conf` folder is not a source directory, it is a directory for resources (i.e. `.properties`, `.yml` files etc.) so `.groovy` files in the `conf` directory should not be compiled. All Eclipse has to do is copy these files onto the classpath to run the application. It seems to be failing to do this for `.groovy` files?

**Comment by graemerocher** [comment]
Note: This works fine with Intellij IDEA

**Comment by zyro23** [comment]
in eclipse, window --> preferences --> groovy --> compiler --> groovy script folders --> add grails-app/conf, grails-app/migrations, etc.

the fact that eclipse does not distinguish between source and resource directories is well... highly unfortunate.

**Comment by provirus** [comment]
That makes sense and at least now we have a written workaround.

IDEA has a grails plugin whereas Eclise has a grails 2 plugin.

For the fix, I dont think the eclipse gradle plugin would want to incorporate a groovy hack (since it is a change in the groovy settings). I guess we would need an eclipse grails 3 plugin at some point to fix these things.

Thanks all

**Comment by graemerocher** [comment]
This has nothing to do with IDEA having a grails plugin and Eclipse not. You can run a Grails 3 application in vanilla IDEA without the IDEA grails plugin installed and it still works. The issue is with how Eclipse regards `.groovy` sources and how it handles resource directories.
