### ISSUE TITLE
<asset:assetPathExists> Can not find a file under the operation environment of the jar

### ISSUE THREAD

**Issue by btboys** [grails/grails-core#9299]
<asset:assetPathExists> Can not find a file under the operation environment of the jar
```gsp
<asset:assetPathExists src="app/web/user/index.js">
......
</asset:assetPathExists>
```
The above code，When run in a development environment no problem。But if it is packaged into a jar in the formal environment running, this code has been to find files。

**Comment by graemerocher** [comment]
@davydotcom Is this fixed in more recent versions of asset pipeline?

**Comment by davydotcom** [comment]
i probably need to fix it  saw something about this earlier

**Comment by btboys** [comment]
Can the latest version of the repair?

**Comment by graemerocher** [comment]
Please report to the asset pipeline issue tracker
