### ISSUE TITLE
Expression in redirect of a webflow with 'uri' or 'url'

### ISSUE THREAD

**Issue by ftaiolivista** [grails/grails-core#93]
The redirect function of a webflow dosen't evaluate params in case you specify uri o url 

For example 

def myFlow = {
  ...
  end { 
     redirect(url: flow.toUrl)
  }

}

Will redirect to a bad address org.codehaus.groovy.grails.commons.metaclass.PropertyExpression@1233243

This because in FlowBuilder.groovy inside grails core the metod redirect only resolve propertyexpression
in the case of controller/action redirect. 
 

void redirect(Map args) {
        if (args.url) redirectUrl = "externalRedirect:${args.url}"
        else if (args.uri) redirectUrl = "externalRedirect:${args.uri}"
        else {
...          
                    redirectUrl = new RuntimeRedirectAction(controller:controllerName,
                    action:args.action,
                    params:params,
                    urlMapper:urlMapper)
            }
        }
    }

Why don't extend expression resolving even in the case of 'url' or 'uri'
?

**Comment by graemerocher** [comment]
Old / irrelevant

**Comment by sebastianflorica** [comment]
Stil relevant today. How do you achieve this without a workaround? I've resorted to handling the redirect via JavaScript, documenting this as a Grails limitation.

Alternatively:
The flow will continue executing past the redirect if called from an action state, so we transition to an end state that redirects to another flow action state, where the actual URI redirect can be performed, using the `permanent: true` attribute. The catch here is that you need to transition from the start state in the new flow, to an end state that renders a blank `.gsp`, to satisfy convention.

Is there a better way?
Related issue: https://github.com/grails/grails-core/issues/7975
