### ISSUE TITLE
Forwarding with URI does not allow sending of params

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9301]
am using a forward to forward uri but params are not being passed. Am checking this in handlerInterceptor:before() where they should be immediately available after forward but they are not.

forward(URI:uri, params:params)

I understand my previous submission is not a bug (Thanks Jeff). Hopefully I can find a way around this with help too.

**Comment by orubel** [comment]
I guess if I'm doing this all wrong, can documentation please be updated to show example of calling uri with params? My apologies for sending these if they are not bugs.

**Comment by bobbywarner** [comment]
@orubel Can you please create a repo with a sample app that reproduces the problem?  

In the repo, please provide a failing test-case for the desired behavior or a description in the README of how to reproduce the problem.

**Comment by orubel** [comment]
sure. will have it for you soon.

Normally I'd like to provide test case for a success/fail scenario; all I can create is fail... and a variety of fails at that for each different case since there is no documentation for URI:

forward(URI:uri,param:params)

forward(URI:uri,param:[params:params]) (I noticed they were getting assigned as params.params and thought I would attempt that)

forward(URI:uri,param:[actualparam:something,actualParam2:somethingelse])

What is proper usage  so I dont waste anyones time?

**Comment by jwagenleitner** [comment]
It works for me, given the following controller and interceptor combo

```groovy
package example

class FooController {

    def index() {
        render "FooController::index(params=${params})"
    }

    def someAction() {
        render "FooController::someAction(params=${params})"
    }
}
```

```groovy
package example

class FooInterceptor {

    boolean before() {
        if (actionName == 'someAction') {
            forward(URI: '/foo/index', params: params)
            return false
        }
        return true
    }

    boolean after() { true }

    void afterView() {
        // no-op
    }
}
```
If I navigate to `http://localhost:8080/foo/someAction?pie=apple` I get the following (expected) response:

`FooController::index(params=[pie:apple, controller:foo, format:null, action:index])`

**Comment by orubel** [comment]
How are you matching in that interceptor? I'm matching on URI AND passing based on URI. It looks like you are matching based on controller/action

**Comment by jwagenleitner** [comment]
Was just showing an example of forward passing params from within an Interceptor.  If the URI passed to forward is valid I would expect it would work similar to that.  I do think that even if the UrlMappings is different than controller/action you can still use controller/action to match in the interceptor match method and as params to forward.  Either way I wouldn't expect matching on uri to affect the call to forward.

**Comment by orubel** [comment]
I'm 100% with you. Grails 2.x handled this perfectly but Grails 3.x works a bit differently.

**Comment by orubel** [comment]
@bobbywarner  is this really 'awaiting feedback'? I thought graeme added this to 3.0.9 up above.

I'll still gladly show an example, I just wasnt sure if you saw that when adding 'awaiting feedback' and didnt want to create a blocker if this is already accepted.

**Comment by bobbywarner** [comment]
@orubel I can not reproduce this issue.  The example provided above works as expected to forward params based on URI and I can match interceptors based on URIs as well without any issues.

**Comment by orubel** [comment]
I didnt provide that example and it is missing several elements that do NOT take into consideration passed uri's. Would you like me to continue to provide a working example? Or should I open another ticket with the working example since this one is closed?

**Comment by graemerocher** [comment]
The ticket is still open, provide an example please

**Comment by orubel** [comment]
My fault, apprently it does work. Here is the example with full URI urlmapping, URI matching and URI forwarding with params.

https://github.com/orubel/batchTest/blob/master/README.md

There is no problem except me and my code.
