### ISSUE TITLE
NoSuchBeanDefinitionException: No bean named 'grailsApplication' in 3.0.8 (working in 3.0.4)

### ISSUE THREAD

**Issue by enr** [grails/grails-core#9307]
I have a multimodule project using Spring Security Core 3: https://github.com/enr/s2oauth

using Grails 3.0.4 everything was all right, upgrading to 3.0.8 (and Gradle 2.7) I have some weird message at startup:

```
WARN org.grails.spring.beans.factory.OptimizedAutowireCapableBeanFactory - Bean creation exception on FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'helloworld.UserRolePersistentClass': Cannot resolve reference to b
ean 'helloworld.UserRoleDomainClass' while setting bean property 'targetObject'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'helloworld.UserRoleDomainClass': Cannot resolve reference to bean 'grailsApplication' while
 setting bean property 'targetObject'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'grailsApplication' is defined
```

moreover, on windows, using `grails run-app` I have an exception related to Spring Loaded

```
ERROR org.springsource.loaded.agent.SpringLoadedPreProcessor - Unexpected problem transforming call sites
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_45]
```

Other relevant difference is the port from `application.groovy` to `application.yml` of the SSC configuration.

To replicate:

```
https://github.com/enr/s2oauth
cd helloworld
grails run-app
```

You should see error messages.

To see the 3.0.4 version:

```
git reset --hard b1eefa193cff469e36959b900a0b24b0a9a089ad
sdk use grails 3.0.4
grails run-app
```

Diff between current version and the version based on 3.0.4:

https://github.com/enr/s2oauth/compare/b1eefa193cff469e36959b900a0b24b0a9a089ad...HEAD

**Comment by olliefreeman** [comment]
I've been getting the same OptimizedAutowireCapableBeanFactory warning

**Comment by mohsenmadi** [comment]
Thanks for taking care of this. Any idea when to expect grails-3.0.9 please?

**Comment by graemerocher** [comment]
next week

**Comment by graemerocher** [comment]
This is fixed by https://github.com/grails/grails-core/commit/dd8695f52029b603060b212601a2bbfd703bcef2

However, note the error is only a warning and doesn't impact the running of the application ,so I have downgraded from a blocker to major
