### ISSUE TITLE
 GRAILS-7799: Subtype messages

### ISSUE THREAD

**Issue by mohsenmadi** [grails/grails-core#9309]
Running Grails 3.0.8 app from Intellij 14.1.5 using the Gradle tasks "run" or "bootRun" generates 10's of console messages like the one below for the slightest edit in the running app.

GRAILS-7799: Subtype 'com.lss.client.User_$$_jvst4ae_5' of reloadable type com.lss.client.User is not reloadable: may not see changes reloaded in this hierarchy (please comment on that jira).

**Comment by graemerocher** [comment]
@aclement Since we are unlikely to be able to fully solve all the cases of this issue, would it be possible to have a flag to disable the message? I'm not sure of what value it is anyway...

**Comment by aclement** [comment]
@graemerocher I think in the early days of putting out that message we did manage to fix a bunch of the serious causes that were real problems. Now I think a flag to control visibility is reasonable. It falls under the category of diagnostics to turn on when you are trying to find out why things aren't behaving. Maybe I'll put this behind the `-verbose` option (and stop it referring to grails 7799 !). If users are happy with system behavior then these probably don't matter, but if they think something is up just turn on verbose and this will appear amongst the other info.  Committed change to Springloaded.

**Comment by mohsenmadi** [comment]
Nice solution @aclement it will be nice that such abundant messages disappear. I don't know if they are referring to anything one should be concerned about though. 

Will the solution be in releases > 3.0.8 ?

**Comment by graemerocher** [comment]
@aclement Thanks Andy! You know when you will do the next release?

**Comment by aclement** [comment]
@graemerocher I need to do a pass over the open issues to see what else needs fitting in. I guess I already fixed your concurrent access modification problem, anything else you think is urgent?

**Comment by graemerocher** [comment]
@aclement only other one reported is

https://github.com/grails/grails-core/issues/9296

But the reporter hasn't provided an example, and they are the only ones to report a similar issue so far..

**Comment by aclement** [comment]
@graemerocher I see 9296 is now closed, so did you want a release now?
