### ISSUE TITLE
Grails dynamic scaffolding works only if Domain name is supplied

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9314]
The dynamic scaffolding static scaffold = true results in this error:
```
Error:(4, 5) Groovyc: The 'scaffold' property must refer to a domain class.
```

However this statement works fine:

```
static scaffold = DomainClass
```
I am using grails 3.1.0.M.1 but the behavior can be reproduced in 3.0.8 as well. The documentation still states that static scaffold = true is also valid. Either the docs or grails implementation requires some correction. If it is doc, I can submit a pull request.

**Comment by aphexmunky** [comment]
Think this person had a copy paste issue. I've encountered this too and the statement that works is:

`static scaffold = DomainClass`

**Comment by graemerocher** [comment]
This is a documentation issue, we won't be restoring the `scaffold = true` syntax

**Comment by jeffbrown** [comment]
If anyone is interested in putting a PR together, relevant bits may be found at https://github.com/grails/grails-doc/blob/3.0.x/src/en/guide/scaffolding.gdoc and https://github.com/grails/grails-doc/blob/3.0.x/src/en/ref/Plug-ins/scaffolding.gdoc.

**Comment by hakanernam** [comment]
@jeffbrown I modified the docs. Tried to make it meaningful. I can create a PR depending on comments.

https://github.com/hakanernam/grails-doc/commit/fe90e548821efc40c37d1bda2a82ed6d82434865

**Comment by graemerocher** [comment]
Thanks for the pull request
