### ISSUE TITLE
grails 3 - @ToString "ignored" on domain class

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9317]
using grails-3.0.8.
annotating a domain class with groovy's `@ToString` does not change the `toString()` output. still grails default.
looks like somehow the `toString()` provided by grails (https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/compiler/injection/DefaultGrailsDomainClassInjector.java#L188) takes precedence over the annotation. should be the other way around imho.
thx, zyro

**Comment by ejaz-ahmed** [comment]
Appears in grails 3.1 too.

**Comment by yancovski** [comment]
I'm using grails 3.1.4 and still have this issue, I don't want to implement toString in all domain classes to get a nice log records :)
