### ISSUE TITLE
Grails 3.0.8 fails to genereate JSON through "(null == user) as JSON" in the controller

### ISSUE THREAD

**Issue by danielsun1106** [grails/grails-core#9319]
Grails 3.0.8 fails to genereate JSON through "(null == user) as JSON" in the controller. One of workarounds is "JsonOutput.toJson(null == user)".

**Comment by Schlogen** [comment]
Can you provide example controller code?

**Comment by danielsun1106** [comment]
```
    def remoteValidate() {
        String email = params.email;

        User user = User.findByEmail(email);

        render((null == user) as JSON) // FAILED
    }
```

WORKAROUND:
```
    def remoteValidate() {
        String email = params.email;

        User user = User.findByEmail(email);

        render(JsonOutput.toJson(null == user))
    }
```

**Comment by Schlogen** [comment]
What is your desired output?

**Comment by danielsun1106** [comment]
The return value of "JsonOutput.toJson" is the correct output:

```
import groovy.json.*

println JsonOutput.toJson(true)     // yield true
println JsonOutput.toJson(false)    // yield false
```

**Comment by Schlogen** [comment]
That isn't valid JSON. Why not simply do `user.asBoolean().toString()`

**Comment by danielsun1106** [comment]
You're right, but many javascript library(including Groovy language) support these invalid json, how about trying to support too in the grails to avoid tricky errors due to the differences?

```plain
<html>
	<script type='text/javascript'  src="https://raw.githubusercontent.com/douglascrockford/JSON-js/master/json2.js"></script>
	<script type='text/javascript'>
		alert(JSON.parse(true))
	</script>
</html>
```

**Comment by graemerocher** [comment]
If still valid please report to https://github.com/grails-plugins/grails-plugin-converters/issues
