### ISSUE TITLE
each() method does not iterate properly

### ISSUE THREAD

**Issue by vm206** [grails/grails-core#9322]
I am using grails 2.4.4 and it seems the each method is erroneous (not sure if it is a grails or groovy bug). For the code:
```groovy
def xml = new XmlSlurper().parseText('''
<list>
    <item a="1">a</item>
    <item a="2">b</item>
    <item a="1">c</item>
</list>
''')

xml.'**'.findAll { it.@a=='1' }.each {
    println "hi"
}  
```
the output should be:
```groovy
hi
hi
```
but for me it is only:
```groovy 
hi
```
so printed only once. Two result items are only provided if I also print something that is changing between the iterations, eg. a variable with increasing value...

**Comment by graemerocher** [comment]
Please report the Groovy issue tracker

**Comment by vm206** [comment]
I reported to the Groovy issue tracker and we figured out that the problem is not in Groovy. Grails 2.4.4 uses Groovy 2.3.7 and the result is as expected there. Now I tried it in my Grails console and also the correct result was provided. The erroneous result is coming when I run the script in the GGTS Grails command prompt with run-script. Is it then a GGTS issue or Grails indeed? Can you please try it?
Thanks
