### ISSUE TITLE
Grails 3.0.8: multiproject build: changes in controllers/views of plugin are not properly reloaded by application

### ISSUE THREAD

**Issue by svene** [grails/grails-core#9326]
In a multiproject build with an application and a plugin changes in controllers/views of the application are properly reloaded. However changes in controllers/views of the plugin are not properly picked up.
On the console a recompile message appears which indicates that the change was detected but it does not seem to have an effect.

I created a minimal example which also contains instructions on how to reproduce it:

https://github.com/svene/grails3apps/tree/master/g3_reloading

**Comment by graemerocher** [comment]
Duplicates #592
