### ISSUE TITLE
each() method does not iterate properly #2

### ISSUE THREAD

**Issue by vm206** [grails/grails-core#9332]
(same as issue #9322, just not sure if comments are visible after issue is closed, so creating again): 
Environment: Grails 2.4.4, Groovy 2.3.7 in GGTS (Version: 3.6.4.RELEASE, Build Id: 201503100339)

```groovy

def xml = new XmlSlurper().parseText('''
<list>
    <item a="1">a</item>
    <item a="2">b</item>
    <item a="1">c</item>
</list>
''')

def i = 0

xml.'**'.findAll { it.name() == 'item' && it.@a=='1' }.each {
	println it.name()  + ":" + i;
}

println "---"

i = 0
xml.'**'.findAll { it.name() == 'item' && it.@a=='1' }.each {
	println it.name()  + ":" + i++;
}
```

this code shall produce:
```groovy
item:0
item:0
---
item:0
item:1
```

instead it produces:
```groovy
item:0
---
item:0
item:1
```
iterations producing the same output as before seem to be missed. What can be the reason? Grails modifies the groovy code generation rules? It seems that this is not a Groovy problem (https://issues.apache.org/jira/browse/GROOVY-7619)

**Comment by jwagenleitner** [comment]
Does this problem occur outside of using GGTS?

**Comment by vm206** [comment]
I just started using grails recently, not sure how to do it. I started grails in the project directory from the command line and tried to run ```dev run-script scripts\test.groovy``` where my script is but it does not find the run-script itself. I have to dig in the documentation a bit more it seems...

**Comment by jwagenleitner** [comment]
I got the following output

```
grails> dev run-script scripts\test.groovy
| Running script scripts\test.groovy ...
item:0
item:0
---
item:0
item:1
| Script scripts\test.groovy complete!
grails>
```
The content of `scripts\test.groovy` was the code you referenced above.  Tested with Grails 2.4.4 and jdk 1.7 after a fresh `grails create-app`.

**Comment by vm206** [comment]
Then can it happen that GGTS manipulates the generated code somehow? It
would be very strange. I will try the same in my environment as soon as I
figure out how. This run-script does not work for me for some reason at the
moment.

**Comment by graemerocher** [comment]
Works fine for me.
