### ISSUE TITLE
Could I get the raw html from render tag?

### ISSUE THREAD

**Issue by kasonyang** [grails/grails-core#9333]
I am trying to render another template(_b) in current template(a).
the template `a.gsp`:
```
<g:render template="b" />
```
the template `_b.gsp`
```
<something>
```
the result is
```
&lt;something&gt;
```
but what I want is
```
<something>
```
Is there any solution?

**Comment by dovydasvenckus** [comment]
What version of grails you are using?

For getting raw value you can try this.

    ${render(template: 'b')}

**Comment by kasonyang** [comment]
Grails3.0.6. It seems that is a problem of the version.It is ok when I switch to version 3.0.8
