### ISSUE TITLE
Grails 3.0.8: grails.controllers.defaultScope=prototype ignored when running in prod env

### ISSUE THREAD

**Issue by benorama** [grails/grails-core#9340]
It looks like there is some strange behavior with `grails.controllers.defaultScope`.
First of all, it seems that default scope is now `singleton` when this setting is not defined in application.yml (documentation specifies it should be `prototype` by default: https://grails.github.io/grails-doc/latest/guide/theWebLayer.html#controllersAndScopes)

I'm currently trying to set `prototype` as default scope.
```yml
grails:
    controllers:
        defaultScope: prototype
```

When running the app, it looks like:
- it is taken into account in dev env (`grails run-app`),
- it is ignored in prod env (`grails run-app -Dgrails.env=prod`) and scope is back to `singleton`?

Workaround: add `scope`static property in each controller to force scope.
```groovy
static scope = "prototype"
```

Note: I've used IntelliJ 15 in debug mode to check this: I put a break point in the controller and check the controller instance ID when calling the controller. 
In dev env, the instance ID changes at each request.
In prod env, the instance ID is always the same, unless I force the scope with `scope`static property to `prototype`.

**Comment by Schlogen** [comment]
I can verify this issue is happening. I can also verify the controller scope is getting set correctly.
`grailsApplication.mainContext.getBean('package.controller')` returns a new instance each time and `grailsApplication.mainContext.isPrototype('package.controller')` returns true.

**Comment by Schlogen** [comment]
Figured out why this is happening - will submit a PR

**Comment by benorama** [comment]
Great, thanks!

**Comment by Schlogen** [comment]
PR submitted https://github.com/grails/grails-core/pull/9346

**Comment by graemerocher** [comment]
Thanks!

**Comment by benorama** [comment]
@Schlogen I just tried with 3.0.9, but I can still reproduce the issue (in debug mode with break point in controller).
Could you confirm that it is fixed in 3.0.9? 
Thanks.

**Comment by Schlogen** [comment]
@benorama I just created a sample app from scratch that is not able to reproduce the issue. Take a look:

https://github.com/Schlogen/confirmPrototypeController

Run the app with -Dgrails.env=prod

Just go to the test controller and refresh. Notice the memory location changes

**Comment by benorama** [comment]
Indeed, sorry, when running from the CLI, it works.
I've got very strange behavior with IntelliJ 15 Preview when trying to upgrade Grails SDK version.
And I probably have another issue, I need to dig a little bit more.
Thanks.
