### ISSUE TITLE
Grails 2.5.1: create-pom uses nonexistent version of the clean plugin in the created POM

### ISSUE THREAD

**Issue by maartenvs** [grails/grails-core#9342]
The Maven POM created by:
```
> grails create-app helloworld
> cd helloworld
> grails create-pom helloworld
```
contains this plugin reference:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-clean-plugin</artifactId>
    <version>2.4.0</version>
    ...
</plugin>
```
but that version don't exist, causing Maven builds to fail.
With this POM, ```mvn clean``` gives this error:
```
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.4.0 or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:maven-clean-plugin:jar:2.4.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
The most recent version of the clean plugin for Maven 2 and 3 seems to be 2.6.1, see https://issues.apache.org/jira/browse/MCLEAN/?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel .

This is also reported in the grails-maven repository ( https://github.com/grails/grails-maven/issues/66 ), but I think it's an issue for grails-core because that contains the create-pom command.

**Comment by graemerocher** [comment]
Please report to https://github.com/grails/grails-maven/issues
