### ISSUE TITLE
Accessing grailsApplication from Quartz Job in 3.0.9 produces odd behavior

### ISSUE THREAD

**Issue by kschmit90** [grails/grails-core#9348]
Example reproducing the issue: https://github.com/kschmit90/grails309quartz

Able to get it working by declaring

```
GrailsApplication grailsApplication
```

However, any other way of injecting/accessing the grailsApplication to access the config does not work inside the quartz job.

**Comment by graemerocher** [comment]
this is a bug in the quartz plugin and should be fixed there
