### ISSUE TITLE
Grails 2.5.2 wrapper can't find distribution

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-core#9349]
The Grails 2.5.2 wrapper tries to pull down the 2.5.2 distribution from `http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.5.2.zip` but it looks like it hasn't been added there yet:
```
$ ./grailsw
Downloading http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.5.2.zip to /Users/dpcasady/.grails/wrapper/grails-2.5.2-download.zip

Exception in thread "main" java.io.FileNotFoundException: http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.5.2.zip
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at org.grails.wrapper.RemoteFileHelper.retrieve(RemoteFileHelper.java:49)
    at org.grails.wrapper.GrailsWrapper.configureGrailsInstallation(GrailsWrapper.java:137)
    at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:57)
```

Navigating to `http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.5.2.zip` displays:
```xml
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>release/GRAILS/grails-2.5.2.zip</Key>
    <RequestId>E165074157B8295D</RequestId
    <HostId>B+R5JP0H/BQl6zQ5/ZMkQ5m4uP1nBaBTaDom9c4p5T4WA9C5zKuE2gAoQkmLHtUvZuhoNKZB+No=</HostId>
</Error>

**Comment by hardyrex** [comment]
The build.properties file contains the wrong grails.version in my opinion:
grails.version=2.5.2.BUILD-SNAPSHOT. Perhaps this is the problem.

**Comment by bobbywarner** [comment]
We need to update this for the 2.5.x branch, but as a workaround, you can simply change in `wrapper/grails-wrapper.properties` the setting like this: `wrapper.dist.url=https://github.com/grails/grails-core/releases/download/v2.5.2/`

**Comment by Robert-F** [comment]
Is there any specific reason why the grails.version is set to "2.5.2.BUILD-SNAPSHOT"? Is the released 2.5.2 version not stable and ready for production use yet?

**Comment by graemerocher** [comment]
I assume you refer to the `build.properties` file, looks like this will missed, we will address this in 2.5.3.. sorry for the inconvenience

**Comment by dpcasady** [comment]
Sounds good, @bobbywarner thanks for the workaround!
