### ISSUE TITLE
inList dynamic finder operator causes exception with MySQL if passed list is empty

### ISSUE THREAD

**Issue by che-edo** [grails/grails-core#9352]
Passing an empty list to the inList operator causes a SQL syntax exception with MySQL, it works fine with h2.

MyDomain.findAllByIdInList([])

**Comment by Schlogen** [comment]
This is a hibernate issue. I've looked into it before and it doesn't seem like they have any plans to change it because there isn't any sensible default.

**Comment by dtamm** [comment]
Or just Check if the List has values in it, and Do the SQL only, if this is true... smallest workaround possible

**Comment by che-edo** [comment]
Agree with dtamm, inconsistency between dialects is really bad.

**Comment by Schlogen** [comment]
It's inevitable. Databases do things differently and no one solution is perfect. As an example, in Oracke you can't have an in clause with more than 1000 items in the list. I'm not sure what restriction, if any, exists in other databases, however you have to be aware of specific rules  for whatever database you're using.

**Comment by jameskleeh** [comment]
Here is the hibernate issue https://hibernate.atlassian.net/browse/HHH-8091

**Comment by jknudsen** [comment]
SQL Server has the same problem with InList and SQL Server InList limit is 2100.
