### ISSUE TITLE
Documentation should mention how critical setting the correct version in gradle.properties is

### ISSUE THREAD

**Issue by che-edo** [grails/grails-core#9353]
I just updated my grailsVersion value in gradle.properties from 3.0.7 to 3.0.9 and very unexpectedly I got a ton of dependency updates.

Since we no longer have a set-grails-version command I believe this setting should be updated automatically to match the current Grails version, or a warning should show on screen when mismatched, or at the very least a big fat red warning should be put somewhere very visible in the docs.

**Comment by jeffbrown** [comment]
>  I believe this setting should be updated automatically to match the current Grails version, or a warning should show on screen when mismatched

I don't like the idea that `grade.properties` should be automatically updated with whatever version of Grails is on your PATH.  It might be that the problem is the other way around and that the version on your PATH is wrong.  I think a warning/error message makes more sense.
