### ISSUE TITLE
JNDI data source settings not working as in Grails 2.x, no information on how to do it

### ISSUE THREAD

**Issue by che-edo** [grails/grails-core#9354]
Using the equivalent settings for JNDI datasources from Grails 2 doesn't work in Grails 3, there is no information on how to set JNDI up in the datasource section of the documentation.

Currently specifying a jndiName value in application.yml (prod environment datasource section) results in an exception, straight JDBC connection to the same MySQL database works alright:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.spr
ingframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property
'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'dat
aSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Cannot r
esolve reference to bean 'dataSourceLazy' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with
name 'dataSourceLazy': Cannot resolve reference to bean 'dataSourceUnproxied' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreation
Exception: Error creating bean with name 'dataSourceUnproxied': Invocation of init method failed; nested exception is javax.naming.NoInitialContextException: Need to specify class
name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial`

**Comment by graemerocher** [comment]
This is how it is done in Grails 3 with Boot: https://github.com/wilkinsona/spring-boot-sample-tomcat-jndi/blob/master/src/main/java/sample/tomcat/jndi/SampleTomcatJndiApplication.java

Unless there is massive demand I'm not sure we will provide a built in solution

**Comment by dodysw** [comment]
@graemerocher I encountered issue when using JNDI on more than 1 datasource, but war deployed to separate container (tried Tomcat 7 and JBoss EAP 6.3). Should I post a new issue or is this still related to this issue?

**Comment by dodysw** [comment]
Nevermind, it worked on Tomcat 7, just not in JBoss EAP 6.3 (JBoss AS 7). 

The thrown exception was not clear to me:
```
14:50:17,895 ERROR [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 7) Application startup failed: java.lang.IllegalArgumentException: Name must not be null
	at org.springframework.util.Assert.notNull(Assert.java:115) [spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:214) [spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:284) [spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.grails.transaction.ChainedTransactionManagerPostProcessor.resolveTransactionManagerClass(ChainedTransactionManagerPostProcessor.java:158) [grails-core-3.1.4.jar:3.1.4]
	at org.grails.transaction.ChainedTransactionManagerPostProcessor.hasJtaOrChainedTransactionManager(ChainedTransactionManagerPostProcessor.java:143) [grails-core-3.1.4.jar:3.1.4]
	at org.grails.transaction.ChainedTransactionManagerPostProcessor.postProcessBeanDefinitionRegistry(ChainedTransactionManagerPostProcessor.java:119) [grails-core-3.1.4.jar:3.1.4
...
```

But when comparing to Tomcat 7, specifically on ChainedTransactionManagerPostProcessor.resolveTransactionManagerClass(), I noticed that the transactionManagerBeanDefinition is different:

```
Tomcat (works):
transactionManagerBeanDefinition = {GenericBeanDefinition@6322} "Generic bean: class [org.grails.orm.hibernate.GrailsHibernateTransactionManager]; scope=singleton; abstract=false; lazyInit=false; autowireMode=1; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null"
 parentName = null
 beanClass = {Class@6005} "class org.grails.orm.hibernate.GrailsHibernateTransactionManager"
 scope = "singleton"
 abstractFlag = false
 lazyInit = false
 autowireMode = 1
 dependencyCheck = 0
 dependsOn = null
 autowireCandidate = true
 primary = false
 qualifiers = {LinkedHashMap@6327}  size = 0
 nonPublicAccessAllowed = true
 lenientConstructorResolution = true
 constructorArgumentValues = {ConstructorArgumentValues@6328} 
 propertyValues = {MutablePropertyValues@6329} "PropertyValues: length=2; bean property 'sessionFactory'; bean property 'dataSource'"
 methodOverrides = {MethodOverrides@6330} 
 factoryBeanName = null
 factoryMethodName = null
 initMethodName = null
 destroyMethodName = null
 enforceInitMethod = true
 enforceDestroyMethod = true
 synthetic = false
 role = 0
 description = null
 resource = null
 source = null
 attributes = {LinkedHashMap@6331}  size = 0

JBoss (doesn't work):
transactionManagerBeanDefinition = {ConfigurationClassBeanDefinitionReader$ConfigurationClassBeanDefinition@11714} "Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.transaction.jta.JndiJtaConfiguration; factoryMethodName=transactionManager; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/transaction/jta/JndiJtaConfiguration.class]"
 annotationMetadata = {AnnotationMetadataReadingVisitor@11722} 
 factoryMethodMetadata = {MethodMetadataReadingVisitor@11723} 
 allowCaching = true
 decoratedDefinition = null
 targetType = null
 isFactoryMethodUnique = true
 constructorArgumentLock = {Object@11724} 
 resolvedConstructorOrFactoryMethod = null
 resolvedFactoryMethodReturnType = null
 constructorArgumentsResolved = false
 resolvedConstructorArguments = null
 preparedConstructorArguments = null
 postProcessingLock = {Object@11725} 
 postProcessed = false
 beforeInstantiationResolved = null
 externallyManagedConfigMembers = null
 externallyManagedInitMethods = null
 externallyManagedDestroyMethods = null
 beanClass = null
 scope = ""
 abstractFlag = false
 lazyInit = false
 autowireMode = 3
 dependencyCheck = 0
 dependsOn = null
 autowireCandidate = true
 primary = false
 qualifiers = {LinkedHashMap@11727}  size = 0
 nonPublicAccessAllowed = true
 lenientConstructorResolution = false
 constructorArgumentValues = {ConstructorArgumentValues@11728} 
 propertyValues = {MutablePropertyValues@11729} "PropertyValues: length=0"
 methodOverrides = {MethodOverrides@11730} 
 factoryBeanName = "org.springframework.boot.autoconfigure.transaction.jta.JndiJtaConfiguration"
 factoryMethodName = "transactionManager"
 initMethodName = null
 destroyMethodName = "(inferred)"
 enforceInitMethod = true
 enforceDestroyMethod = true
 synthetic = false
 role = 0
 description = null
 resource = {ClassPathResource@11734} "class path resource [org/springframework/boot/autoconfigure/transaction/jta/JndiJtaConfiguration.class]"
 source = {MethodMetadataReadingVisitor@11723} 
 attributes = {LinkedHashMap@11735}  size = 1

```

For my specific case, the transactionManagerBeanDefinition on JBoss, the beanClass is null, which threw the exception.

**Comment by dodysw** [comment]
Never mind. Found a fix (by trial and error). Added 

> transactional: false

 on the second JNDI datasource in application.yml. For some reason the exception no longer thrown.

**Comment by sergiomichels** [comment]
The [Spring Boot example](https://github.com/wilkinsona/spring-boot-sample-tomcat-jndi/blob/master/src/main/java/sample/tomcat/jndi/SampleTomcatJndiApplication.java) will not work with Grails 3 (tested with 3.3.4) because data sources will be configured **before** `tomcat.enableNaming()`. I'm still trying to figure out if it's possible to shift this order...
