### ISSUE TITLE
NullPointerException if <g:link> params map contains null parameter value

### ISSUE THREAD

**Issue by pcroc** [grails/grails-core#9355]
I am rendering a link with parameters using `<g:link>`. I have some parameters that I only want in the link if they were passed to the current page. The page I am rendering is a list of items, optionally filtered by a search string, and in the link to view an item I want to pass the search term _if it is set_. I have this fragment:

``` gsp
<g:link uri="/orders/view" params="[orderId:order.id, search:params.search]">
${ order.id }
</g:link>
```

If params.search is null (because the results are not being filtered), I receive a NullPointerException:
Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/orders.gsp:95] Error executing tag <g:link>: null

A couple of things come to mind:
1. The link tag could handle null values better and not throw a NPE (is this by design?)
2. How can I create a link that can handle such optional parameters without lots of extra conditional markup/code or a custom tag?

Using Grails 3.0.8

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues
