### ISSUE TITLE
Cannot read test data provided by a unit test if a service method under test requires a new transaction

### ISSUE THREAD

**Issue by saw303** [grails/grails-core#9358]
There is a simple service called `SuperService`

    @Transactional(readOnly = true)
    class SuperService {

        @Transactional(propagation = Propagation.REQUIRES_NEW)
        def serviceMethodThatNeedsNewTransaction() {
            return Team.count()
        }

        @Transactional(propagation = Propagation.REQUIRED)
        def serviceMethodThatUsesCurrentTransaction() {
            return Team.count()
        }
    }

and a unit test that test its behaviour.

    @TestMixin(HibernateTestMixin)
    @Domain(Team)
    @TestFor(SuperService)
    class SuperServiceSpec extends Specification {

        void "A service that requires a new transaction has no access to the test data provided by the unit test"() {

            given: 'test data'
            new Team(name: 'ABC Team', shortName: 'abc', image: 'abc.png').save()

            when: 'a service requires a new transaction'
            def count = service.serviceMethodThatNeedsNewTransaction()

            then: 'it should be able to read the test data provided by the unit test (as it was in Grails 2.x)'
            count == 1
        }

        void "A service that uses the current transaction has access to the test data provided by the unit test"() {

            given:
            new Team(name: 'ABC Team', shortName: 'abc', image: 'abc.png').save()

            when:
            def count = service.serviceMethodThatUsesCurrentTransaction()

            then:
            count == 1
        }
    }

The first test fails since the service method `serviceMethodThatNeedsNewTransaction()` returns `0` instead of `1`. The second test is successful. I suspect there is something wrong when using `@Transactional(propagation = Propagation.REQUIRES_NEW)`. This used to work in Grails 2.x.

An example app including the test specification can be found at https://github.com/saw303/abc

**Comment by graemerocher** [comment]
In 2.5.x each unit test method is not wrapped in a transaction by default. This is bug. In 3.x they are. You can make the test pass by setting `transactional` to false in the test:

         static transactional = false
