### ISSUE TITLE
Asset Pipeline does not generate ETags for files in src/main/webapp

### ISSUE THREAD

**Issue by danielsun1106** [grails/grails-core#9360]
Even when running under production mode, Grails 3.0.9 does not generate ETag for artefacts(e.g. js, css, image files) and make browsers cache them . BTW, Grails 2.5.1 can cache artefacts properly.

**Comment by graemerocher** [comment]
This has to do with asset pipeline I imagine. @davydotcom you seen this behaviour anywhere?

**Comment by davydotcom** [comment]
I have not, what version of asset pipeline is being used

**Comment by graemerocher** [comment]
3.0.9 uses 3.0.8 of the asset pipeline plugin

**Comment by danielsun1106** [comment]
Thanks for your quick reply!

BTW Grails 3.0.8 can generate ETag for artefacts under "grails/assets" directory, but no ETag generated for artefacts under "src/main/webapp" directory.

**Comment by graemerocher** [comment]
Ah I see, that should be been put in the description then.

**Comment by danielsun1106** [comment]
Hi Graeme,

     When I launch Grails app through "grails prod run-app" command, no ETags are generated for artefacts under "grails/assets" directory either.

**Comment by davydotcom** [comment]
@danielsun1106 that is not the proper way to simulate a production run of grails. You must use the assembled fat jar container or war file to run in production mode properly. the asset-pipeline will still detect that the app is running in an unpackaged mode like this as `run-app` is solely used for development purposes.

**Comment by davydotcom** [comment]
Also this is correct `src/main/webapp` is considered a non asset-pipeline processed resource folder. I do not believe even grails 2.5.1 processes the web app folder either

**Comment by danielsun1106** [comment]
Hi David,
     In the grails 2.5.1 project, the only directory to place js library(such as jquery-ui which contains js, css, images under single directory and not be classified as javascripts/stylesheets/images) is "web-app". It is true that artefacts can be cached properly.

     Could you tell me how to place js library such as jquery-ui under "grails/assets" in the Grails3? Thanks in advance.

**Comment by davydotcom** [comment]
This is not true. Remember all subfolders immediately under the `assets` folder are purely for organizational purpose. They do not specifically restrict the type of file to be placed in them. You can even create your own subdirectory within `assets` named however you see fit. For example, I often make a `grails-app/assets/libs` folder and store things like this in there.

**Comment by danielsun1106** [comment]
@davydotcom Thanks for your sharing experience. When I  make a grails-app/assets/libs folder and store things as you often do, how can I access these artefacts in the gsp page? 

   When I put images in the "assets/images", the images should be accessed by the following code:
```plain
<img src="${asset.assetPath(src: 'test.jpg')}" />
```
or
```plain
<asset:image src="test.jpg"/>
```
   When I put images in the "assets/libs", how can I access these js, css and images files? Thanks in advance.

**Comment by davydotcom** [comment]
Just like you would an image. Lets say you put `test.jpg` in `grails-app/assets/libs` instead of `images`. The way you would reference that file is identical `<asset:image src="test.jpg"> the first subdirectory level is essentially flattened and should be ignored for relative urls. Its like a merged filesystem,

**Comment by danielsun1106** [comment]
It works! I'll migrate all my js lib to assets/libs. Thank you very much!

**Comment by davydotcom** [comment]
Id say we can close this ticket

**Comment by graemerocher** [comment]
Thanks @davydotcom
