### ISSUE TITLE
Improve Codecs To Use Groovy Extension Methods Instead Of EMC

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9365]

**Comment by jeffbrown** [comment]
I think all of the codecs provided by core should be refactored to use extension methods and the codecs plugin should be removed.  That will be an issue for custom codecs provided by applications or plugins.  The recommended way forward should be for custom codecs provided by plugins to also be implemented as extension methods.  The existing codec plugin can be published as a standalone plugin and pulled in by applications which want that behavior.

**Comment by graemerocher** [comment]
Alternatively we could write a transform that generated an extension for custom codecs. Simpler to the way we generate a TraitInjector

**Comment by jeffbrown** [comment]
Would that work if the codec is defined in the app (as opposed to a plugin)?

**Comment by graemerocher** [comment]
should do, as long as the extension classes on the on the class path

**Comment by jeffbrown** [comment]
Then I think that is a good idea.  Will verify and then will make it happen.

Thanks for the input.

**Comment by graemerocher** [comment]
Can this be closed @jeffbrown ?
