### ISSUE TITLE
Problem configuring MySQL DataSource on Grails 3.1.0.M2 with web-api profile.

### ISSUE THREAD

**Issue by dmonti** [grails/grails-core#9366]
My steps were:
1 - $ grails create-app myApi --profile=web-api.

2 - Configure the application.yml file with:

    dataSource:
        pooled: true
        jmxExport: true
        driverClassName: com.mysql.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        username: root
        password:

    environments:
        development:
            dataSource:
                dbCreate: update
                url: jdbc:mysql://localhost:3306/test-app

3 - On build.gradle file, replace the runtime dependency "com.h2database:h2" with "mysql:mysql-connector-java:5.1.37"

4 - Create a database called test-app

5 - Create a domain: $grails create-domain-class MyDomain

6 - Add a String attribute on MyDomain classe called name
Example:

    package myapi

    class MyDomain {
        String name
        static constraints = { }
    }

7 - Run the app: $grails run-app
Output:

>Running application...
>objc[27851]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
>Grails application running at http://localhost:8080 in environment: development

And no tables were created... anyone knows what step I'm missing in here?

OBS.: Even if I misspelled the database name, the app still running and no error happens.

**Comment by dmonti** [comment]
When I tried to save an instance of MyDomain, this exception occurs:

>ERROR org.grails.web.errors.GrailsExceptionResolver - IllegalStateException occurred when processing request: [GET] /
>Method on class [myapi.MyDomain] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
>Caused by: java.lang.IllegalStateException: Method on class [myapi.MyDomain] was used outside of a >Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at myapi.ApplicationController.index(ApplicationController.groovy:13) ~[main/:na]
	... 3 common frames omitted

**Comment by graemerocher** [comment]
that indicates you don't have the hibernate plugin configured in your dependencies

**Comment by dmonti** [comment]
By default Grails already create the **build.gradle** with this *"buildscript"* settings:
    buildscript {
        dependencies {
            classpath "org.grails.plugins:hibernate:4.3.10.7"
        }
    }

It's needed any more additional configuration?

**Comment by dmonti** [comment]
Ok! I moved the hibernate dependency to outside of *buildscript* closure as a runtime dependency, and now it's working fine!
Thanx a lot!

**Comment by burtbeckwith** [comment]
You want the dependency in the regular `dependencies` block to make it available to your app, and optionally also in the `buildscript` block so it's available to the Gradle script, e.g. so you can run scripts and commands provided by the plugin. `schema-export` is one example.
