### ISSUE TITLE
Grails is parsing date not with UTC but with local time zone

### ISSUE THREAD

**Issue by magx2** [grails/grails-core#9367]
I'm trying to bind date in Grails App. In ```application.yml``` I have ```databindings``` for default JavaScript date formats:

      grails:
        databinding:
          dateFormats:
            - "yyyy-MM-dd'T'hh:mm:ss.S'Z'"
            - "yyyy-MM-dd'T'HH:mm:ss'Z'"

In Groovy I'm creating object from params ```def entity = new Entity(params)``` and everything binds OK, but...

The problem is that I have wrong time zone in my Grails app, i.e.:

1. In AngularJS I'm creating new Date - ```Thu Oct 22 2015 00:00:00 GMT+0200 (CEST)``` (this is string representation of ```Date``` object)
1. Next I'm sending it via ```$http``` service, JSON payload looks like this: ```{ date: "2015-10-21T22:00:00.000Z", another: "another:, property: "property"  }```. 
Date looks fine right now, ```Z``` at the end means it is UTC so ```Thu Oct 22 2015 00:00:00 GMT+0200 (CEST)``` - 2 hours => ```2015-10-21T22:00:00.000Z```

1. In Grails I'm doing ```def entity = new Entity(params)``` and here is problem, ```entity.date``` is equals to ```Wed Oct 21 22:00:00 CEST 2015``` which means that Groovy/Grails parsed string ```2015-10-21T22:00:00.000Z``` as CEST time zone not UTC

So how can I force Grails to load date with proper format?

PS
Both the web browser and computer is working with CEST time zone.

I'm using Grails 3.0.4

**Comment by jeffbrown** [comment]
I think this is effectively what is happening:

```
import java.text.SimpleDateFormat

def inputString = '2015-10-21T22:00:00.000Z'
def formatString = "yyyy-MM-dd'T'hh:mm:ss.S'Z'"

def sdf = new SimpleDateFormat(formatString)
def date = sdf.parse(inputString)

println date
```

That will output something like `Wed Oct 21 22:00:00 CDT 2015`

**Comment by jeffbrown** [comment]
I think that would yield the desired result of the logic were changed to something like this:

```
import java.text.SimpleDateFormat

def inputString = '2015-10-21T22:00:00.000Z'
def formatString = "yyyy-MM-dd'T'hh:mm:ss.S'Z'"

def sdf = new SimpleDateFormat(formatString)
sdf.setTimeZone(TimeZone.getTimeZone('GMT'));
def date = sdf.parse(inputString)
```

As far as I know, there isn't a way to configure `SimpleDateFormat` to recognize the `Z` as UTC.  If the timezone offset were represented in the input String (like `-08` or `-0800` etc...) then it can be made to work.  As it is, I don't know the best way to handle this with the default binder.

**Comment by jeffbrown** [comment]
If the input string were something like `2015-10-21T22:00:00.000 GMT+00:00` then a format string like `yyyy-MM-dd'T'hh:mm:ss.S Z` would work.

**Comment by jeffbrown** [comment]
The current code that converts `String` to `Date` in the data binder is at https://github.com/grails/grails-core/blob/v3.0.9/grails-databinding/src/main/groovy/org/grails/databinding/converters/DateConversionHelper.groovy.

**Comment by magx2** [comment]
@jeffbrown 
> As far as I know, there isn't a way to configure SimpleDateFormat to recognize the Z as UTC

Time with ```Z``` should be considered as ```UTC```, see more: https://en.wikipedia.org/wiki/ISO_8601#UTC

---

So right now I should do my own ```ValueConverter``` for parsing dates?

**Comment by magx2** [comment]
According to this [1] you should change pattern ```"yyyy-MM-dd'T'hh:mm:ss'Z'"``` to ```"yyyy-MM-dd'T'hh:mm:ssX"```

Sadly this does not solves this problem, because ```X``` does not work when there are milliseconds [2]

[1] http://stackoverflow.com/a/29502282/1819402
[2] http://stackoverflow.com/a/29210140/1819402

**Comment by jeffbrown** [comment]
I thought `X` would match something like `-08` and `-0800`, not `Z`.  Am I wrong about that?

**Comment by jeffbrown** [comment]
@magx2 

> Time with Z should be considered as UTC

I understand that.  What I don't know is how to make the date formatter recognize that.  If you do, we can fix the default binder.  Without that, there are a number things we could do that a bit hacky to fix this but I would like to identify a real solution.

**Comment by jeffbrown** [comment]
@magx2 

> So right now I should do my own ValueConverter for parsing dates?

If you want to change the default binder beyond providing custom formats, that is one option.  If you register your customer converter as a bean in the application context with the name `defaultDateConverter`, that converter will be used.  If you have a good solution for a custom converter, we can use that to affect the default converter.  I don't know of a good way to deal with this for the general case without adding some special handling for `Z`.  If you do, we would welcome the input.

Thanks for the feedback.

**Comment by magx2** [comment]
Yep, just tested it. Date ```2015-10-21T22:00:00Z``` will be parsed by ```"yyyy-MM-dd'T'HH:mm:ssX"```

Problem is that in JSON date format there are milliseconds (```.S```) in the end.

My quick fix for this is new ```ValueConverter``` with this code:

	@Override
	Object convert(Object value) {
		new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX").parse((value as String).replaceAll('\\.\\d\\d\\dZ$', 'Z'))
	}

**Comment by jeffbrown** [comment]
> new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX").parse((value as String).replaceAll('\\.\\d\\d\\dZ$', 'Z'))

Right.  I am hoping to avoid having to have special handling for the `Z` in the default binder if we can manage that.

**Comment by jeffbrown** [comment]
> Problem is that in JSON date format there are milliseconds (.S) in the end.

What is wrong with `yyyy-MM-dd'T'HH:mm:ss.SSSX` to match the date you described in the original question?

**Comment by magx2** [comment]
Oh my God, I had wrong pattern! On the end there should be **3** **S** not only one.

So for binding JSON date (i.e. ```"2015-10-21T22:00:00.000Z"```) there should be this format: ```"yyyy-MM-dd'T'HH:mm:ss.SSSX"``` not ```"yyyy-MM-dd'T'HH:mm:ss.SX"```

**Comment by jeffbrown** [comment]
So you are good to go with the default binder and just providing an appropriate date format in `application.yml`?

**Comment by magx2** [comment]
No I think that this should be changed in ```DateConversionHelper```. Grails cannot bind date to local time zone when there is UTC time zone. A lot of bugs can come from this.

**Comment by jeffbrown** [comment]
> A lot of bugs can come from this.

What are examples of those?

**Comment by jeffbrown** [comment]
I should be more clear... I am looking for justification for making any change other than providing other date formats.

**Comment by jeffbrown** [comment]
I think having `yyyy-MM-dd'T'hh:mm:ss'Z'` as one of the default formats is problematic.

**Comment by jeffbrown** [comment]
I realize bugs can come from that.

**Comment by jeffbrown** [comment]
Until we can ship a release with different default formats, is there anything that doesn't work for you if you include formats in `application.yml` which are consistent with the data that you are submitting to the data binder?   (`yyyy-MM-dd'T'HH:mm:ss.SSSX`)

**Comment by magx2** [comment]
Yep right now I'm happy (after changes in ```application.yml```) :).

In new release there should be fixed date formats (as you probably know ;) )

**Comment by jeffbrown** [comment]
Great.  I am going to go ahead and close this issue.  I think the binder is behaving as designed and the issue described in the original report goes away when an appropriate binding format is defined.  As a related issue, #9368 proposes to provide defaults which will address more of the common use cases.

**Comment by Onoroco** [comment]
I confused at the same problem. And I found the formatStrings of  DateConversionHelper include version 3.3.9 is null . Is this default setting?
