### ISSUE TITLE
Improve Default Date Formats

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9368]
I think having `yyyy-MM-dd'T'hh:mm:ss.S'Z'` as a default format is problematic.

Separate but related, we probably should include in the defaults formats like `yyyy-MM-dd'T'HH:mm:ss.SSSX` in the list of defaults.

Related to #9367.

**Comment by graemerocher** [comment]
@jeffbrown Is this going into 3.1 or is it delayed until 3.2?

**Comment by jeffbrown** [comment]
@Schlogen Per our discussion this evening, would you go ahead and add whatever defaults you think is reasonable and we can include that in 3.2?
