### ISSUE TITLE
Update Gradle to 2.9

### ISSUE THREAD

**Issue by smartiniOnGitHub** [grails/grails-core#9369]
Hi all, just seen that Gradle 2.8 (released few days ago) seems to have many improvements like better aligning to a Groovy release near to that used by grails, and a great speedup, see here: https://docs.gradle.org/current/release-notes

So, what do you think on updating all Gradle related stuff (its wrapper, and all other stuff) here ?
Maybe starting from Grails-3.1.0 ...

Thanks a lot,
Sandro

**Comment by jeffbrown** [comment]
@smartiniOnGitHub I agree that we should look at updating.  Are you interested in doing some testing and submitting a pull request to https://github.com/grails/grails-profile-repository?

**Comment by smartiniOnGitHub** [comment]
Hi Jeff,
yes I can do some test, but I need some days and probably some more info
(I have a little knowledge of Grails 3 at the moment, and I have only small
webapps to test) ... anyway I can start tomorrow and ask more info if
needed.

I'll post some update soon.

Thanks for now,
Sandro
Il 23/Ott/2015 21:14, "Jeff Scott Brown" <notifications@github.com> ha
scritto:

**Comment by smartiniOnGitHub** [comment]
@jeffbrown: Hi Jeff, I started to look at changes in my fork of grails-profile-repository and changes seems simple, but how can I execute some tests with my changes (there is some document describing this) ? 
I don't see tests there so I think should be enough to run some commands in different profiles ... after having copied my changes even under related folder in my user profile, right ?

Last, after this, I should update even my fork of grails-core (there are some places where Gradle-2.7 is referenced), and do other tests, right ?

Last, do you prefer a dedicated branch or master is good for both ?

Thank you a lot ... next time I'll ask less info :-) ...

**Comment by smartiniOnGitHub** [comment]
@jeffbrown: Hi Jeff, some update after my changes: all seems ok :-) .

My environment: 
Windows 10 at 64 bit, JDK 7 Update 80 at 64 bit

grails-profile-repository:
ok

grails-core:
>gradlew install
ok

>gradlew test

org.grails.web.taglib.FormRenderingTagLibTests > testTimeZoneSelect FAILED
    junit.framework.AssertionFailedError at FormRenderingTagLibTests.groovy:24

824 tests completed, 1 failed
:grails-test-suite-web:test FAILED

>gradlew distZip
ok, but doesn't seems to generate a zip with Grails binary installation (my fault using this task ?) ...

>gradlew assemble
ok, then tried some command with generated distribution unzipped and make active in PATH.
Then play with some commands, like create-app, console, run-app, etc but not deeply, and only in my environment (Windows).

Note that inside that distribution I find gradle-tooling-api-2.6.jar, should be updated too ?
Then, in a newly created test app (but only with default profile), if I run gradlew -version I get Gradle 2.7, probably my updated profiles are not taken (even with the offline mode flag it doesn't seem to use my local profiles) ... or maybe I miss some place to update.
If I update gradle files and wrapper to 2.8 in the newly created app, then all seems to work.

Anyway I'll make pull requests now.
Note that my changes are in grails-profile-repository (there is a small change in second commit that I'm not sure is wanted, please look at it) and even in grails-core.

Tell me if all is good (I hope).

Bye,
Sandro

**Comment by smartiniOnGitHub** [comment]
Hi all, is it time now to update to Gradle 2.9 (even this time some speedup improvements and less memory usage) ? I can do another pull request (and if useful even a dedicated issue, or rename this and update) ... tell me.
Note that a little update even for grails-core ( https://github.com/grails/grails-core/pull/9383 ) has still not applied. Bye.

**Comment by graemerocher** [comment]
Yes 2.9 upgrade time

**Comment by smartiniOnGitHub** [comment]
ok, I'll do it during next days ... 

@graemerocher  do you have (or someone has, maybe to put in a wiki page) some guideline to properly test changes to grails-profile-repository (to be sure that all still is good) ? Thanks a lot..

Bye

**Comment by smartiniOnGitHub** [comment]
Done, all should be ok :-) , I tested by copying updated profiles under my user_home to overwriting existing ones, but still inside the wrapper version is the previous version, 2.8 (I think downloaded from the repository) anyway I tested it and all works, even after manually copying there related files from 2.9 . Then created a test-webapp with default and other profiles, and tried to play with some commands, all from an updated JDK 8 Update 66 at 64 bit on Windows.
You should find 2 pull requests (one for grails-profile-repository, another for grails-core).
But didn't update the gradle-tooling-api. 
Thanks for now. Bye

**Comment by graemerocher** [comment]
Thanks!

**Comment by smartiniOnGitHub** [comment]
It's a pleasure. Let's update at next Gradle release :-) ... Bye
