### ISSUE TITLE
GGTS3.6.4 can't support grails 3.0.X

### ISSUE THREAD

**Issue by hanyou** [grails/grails-core#9371]
As you regularly do with new Grails distributions is to add it in GGTS under Preferences > Groovy > Grails. But dang!…it doesn’t recognize the grails-3.0.x-directory you just unzipped a minute ago.

**Comment by ejaz-ahmed** [comment]
Grails3 is a major overhaul and rework. It is not well supported in GGTS. Import grails projects as gradle and you will have basic support.

**Comment by jeffbrown** [comment]
This isn't really a Grails issue as much as it is an issue with the tooling.
