### ISSUE TITLE
Grails Stop Responding 

### ISSUE THREAD

**Issue by arjangch** [grails/grails-core#9374]
Grails 3.0.6:  MyProject
In my project I had a Parent class that I was extending 5 child classes.

Problem:
Server stop responding. Browser spins at localhost:8080 for ever. Java uses 100% of CPU.  And when i stop the server it get this error.
- Error Failed to start server (Use --stacktrace to see the full trace)

Sometimes ctrl-c doesn't terminate Java process. It keeps continuing running at 199%. So i have to use "kill -9 "

Testing:
Deleting one of domains fixes the issue. Adding the fifth domain recreate the issue. Removing "extends Parent" from domain fixes the issue.

Solution: 
Changing tablePerHierarchy to false in Parent class, got it fixed permanently.  
- tablePerHierarchy false

**Comment by graemerocher** [comment]
Please upload an example that reproduces the issue, Looks like an infinite loop somewhere

**Comment by arjangch** [comment]
I don't think i can give you Corp. code. But i will try to create an example project.
