### ISSUE TITLE
run-app hangs if server port is configured

### ISSUE THREAD

**Issue by kdickerson** [grails/grails-core#9375]
Create a new application and configure a different server port in application.yml:

    environments:
      development:
        server:
          port: 8082

Start the server:

> grails> run-app --verbose
> | Running application...
> :compileJava UP-TO-DATE
> :compileGroovy UP-TO-DATE
> :processResources
> :classes
> :findMainClass
> :bootRun
> Grails application running at http://localhost:8082 in environment: development
> \> Building 83% > :bootRun

And it never progresses beyond that point.  To recover you have to kill the process (CTRL+C).

Grails: 3.0.8 & 3.0.9
Java: 1.7
OS: Win 7 64-bit

**Comment by anshbansal** [comment]
Isn't it just running? Have you tried opening http://localhost:8082

**Comment by kdickerson** [comment]
Yes it is running; that's not the problem.  It never returns to the prompt so you can't issue a "stop-app" command.  You have to kill the process.
