### ISSUE TITLE
Configuration: Environments block not merged from plugins

### ISSUE THREAD

**Issue by kdickerson** [grails/grails-core#9376]
Not sure if this is a bug or just undocumented behavior (undocumented as far as I could find at least).

We have several applications with common configuration that we'd like to modularize into a plugin.  We have this all working in Grails 2.x and we're trying to migrate to 3.x.

We'd like to make the configurations, per environment, once in the plugin and then have them available in each application that includes the plugin (done as an inline plugin if it makes a difference).

~~In my testing, the plugin's application.yml is merged with the application's application.yml, but the environments block is ignored.~~

It would be very helpful to us if the environments block was not ignored, but if that's intentional could it be added to the documentation?  (And, if it's intentional, any thoughts on a good workaround for what we're trying to do?)

Grails: 3.0.8 & 3.0.9
Java: 1.7
OS: Win 7 64-bit

**Comment by kdickerson** [comment]
I understand better what's happening now.  The documentation describes plugins' configs as being "merged" with the application's config.  Which led me to believe it would act similarly to the Grails 2.x line where the config blocks from plugins were literally merged together in the application.  So I could have a block defined in my common configuration plugin, which an application then adds to.

This no longer seems to be the case in Grails 3 using .yml files.  I can override entries from the plugin, but I can't reference them using YAML anchors and merge operators so I can't produce the same result.  Not showstopping, but certainly an annoying change such that now I have to care which settings are made in the common configuration plugin and which are done in the application.

Some clarity in the documentation about how the configurations are combined (presumably one is simply parsed after the other?) would help.  Also, I've seen some information that suggests the application.yml file in a plugin will be converted to plugin.yml and other information that says you need to create a separate plugin.yml if you want it available in applications.  Some clarification on this topic would also be helpful.

**Comment by jeffbrown** [comment]
Looks possibly related but not the same thing as #9189

**Comment by kdickerson** [comment]
It also seems to be the case that a `dataSource` block within `plugin.yml` will not propagate into the application's configuration.

**Comment by ctoestreich** [comment]
I think there are 2 possible solutions here.

1.  Support environment block merging from the plugin.yml files
2.  Support plugin-[environment].yml files

Either will work for us but this is a lost feature from 2.x where plugin configs (enviornment specific) could be merged manually via grails.config.locations from consuming projects.

:+1: :shipit:

**Comment by ctoestreich** [comment]
I submitted pull request with with option #2 above.

https://github.com/grails/grails-core/pull/9471

**Comment by ctoestreich** [comment]
I have created a new pull request #9491 to allow for multiple plugin environment configs via `environment:` blocks in the plugin.yml

**Comment by graemerocher** [comment]
Thanks for the pull request!

**Comment by graemerocher** [comment]
m

**Comment by bdbogjoe** [comment]
if i use plugin.groovy it will be merged as well like plugin.yml ?

**Comment by bdbogjoe** [comment]
i confirm, works fine

see : https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/plugins/AbstractGrailsPlugin.java

**Comment by appienvanveen** [comment]
Hi,

can you explain me the reason why the dataSource and hibernate properties are ignoed in a plugin.yml?

Thanks!
