### ISSUE TITLE
Multiple Exceptions when uploading file greatly over limit

### ISSUE THREAD

**Issue by KerchumA222** [grails/grails-core#9378]
When you upload a file that greatly exceeds the limit specified for file uploads the application fires the SizeLimitExceededException multiple times. When you extend the MultipartResolver of your choice to swallow the exception you end up hitting the controller repeatedly. 

It is also worth mentioning that if the file uploaded is only slightly over the limit everything works as intended.

I believe this may have to do with handling the multiple parts of the request.

I started a repo with a very simple project to better explain the issue: https://github.com/KerchumA222/grails-bigFileUploadBug

The issue is present when using the default MultipartResolver as well as CommonsMultipartResolver or an extension of either one.

**Comment by Schlogen** [comment]
I think this is related to the "maxSwallowSize" servlet parameter. 

http://stackoverflow.com/questions/31605129/spring-file-upload-with-multipart-resolver-causes-connection-reset-when-file-is

**Comment by graemerocher** [comment]
It looks like if you are deploying with Tomcat you have to configure `maxSwallowSize` as mentioned by @Schlogen 

This is how you do it in a Grails/Spring Boot application: http://stackoverflow.com/questions/32250030/setting-a-tomcat-property-using-spring-boot-application-properties

I'm not sure what else we can do about this as we won't want to add dependencies explicitly on Tomcat to Grails core. It may be worth raising an issue in the Spring Boot issue tracker to have Boot automatically align the `maxUploadSize` and Tomcat's  `maxSwallowSize`: https://github.com/spring-projects/spring-boot/issues
