### ISSUE TITLE
grails 3.0.9 create-app have error

### ISSUE THREAD

**Issue by hanyou** [grails/grails-core#9382]
grails 3.0.9

$grails create-app myproject
$cd myproject
$gradle eclipse

import project in sts IDE

but error below:

Description	
Resource	Path	Location	Type
Project 'myproject' is missing required library: '/Users/hanyou/grails/myproject/gsp-classes'	myproject

**Comment by graemerocher** [comment]
IDE issue report to https://youtrack.jetbrains.com/issues/IDEA

**Comment by hanyou** [comment]
I mkdir gsp-classes in the project root , the error disappear!
