### ISSUE TITLE
Import grails3 project to IntelliJ warning

### ISSUE THREAD

**Issue by hanyou** [grails/grails-core#9384]
![image](https://cloud.githubusercontent.com/assets/2518751/10845132/4a804990-7f40-11e5-8454-e1973df8bfd2.png)

**Comment by graemerocher** [comment]
IDE issue report to https://youtrack.jetbrains.com/issues/IDEA

**Comment by ejaz-ahmed** [comment]
@graemerocher This is not an IDE related issue according to Jetbrains. I've discussed this to them and they say that there is no repositories list due to which it is showing this popup.

**Comment by ejaz-ahmed** [comment]
To be precise, Grails repo lacks has no .index/nexus-maven-repository-index.properties and Intellij throws fileNotFound exception. Here is example from maven central repo: http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties

**Comment by graemerocher** [comment]
It is an IDE issue in that IDEA regards this as important enough to show an annoying popup. That is a UI issue that has nothing to do with Grails. Sure we could index our repositories, but that doesn't solve the general UI issue

**Comment by dovchinnikov** [comment]
@hanyou Yes this is IDEA-side related.
Just disable this notification.

**Comment by ejaz-ahmed** [comment]
@dovchinnikov Isn't it limiting Idea's capability to auto complete grails 3 maven artifacts?
