### ISSUE TITLE
IntelliJ create-controller error

### ISSUE THREAD

**Issue by hanyou** [grails/grails-core#9385]
![image](https://cloud.githubusercontent.com/assets/2518751/10845449/e3a926ee-7f42-11e5-85b7-ec3daf2b1a97.png)

![image](https://cloud.githubusercontent.com/assets/2518751/10845422/ac425c7a-7f42-11e5-85c0-4962073e97bd.png)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'grails-create-controller' not found in root project 'demo'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.671 secs
Task 'grails-create-controller' not found in root project 'demo'.
下午8:13:09: External task execution finished 'grails-create-controller -PgrailsArgs="test --non-interactive -plain-output"'.

**Comment by graemerocher** [comment]
IDE issue report to https://youtrack.jetbrains.com/issues/IDEA
