### ISSUE TITLE
Grails3 install plugins error

### ISSUE THREAD

**Issue by hanyou** [grails/grails-core#9386]
repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

compile 'org.grails.plugins:spring-security-core:3.0.0.M1'

error below
======================================================
下午8:38:13: Executing external task 'bootRun'...
:compileJava UP-TO-DATE
:compileGroovy

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.grails.plugins:spring-security-core:3.0.0.M1.
  Required by:
      demo:demo:0.1
   > No cached version of org.grails.plugins:spring-security-core:3.0.0.M1 available for offline mode.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.712 secs
No cached version of org.grails.plugins:spring-security-core:3.0.0.M1 available for offline mode.
下午8:38:15: External task execution finished 'bootRun'.

**Comment by hanyou** [comment]
with sts ide, is OK
![image](https://cloud.githubusercontent.com/assets/2518751/10846175/83176f88-7f48-11e5-8b37-86ce0889c0f4.png)

**Comment by graemerocher** [comment]
IDE issue
