### ISSUE TITLE
rlike not implemented correctly for postgresql

### ISSUE THREAD

**Issue by chriserickson** [grails/grails-core#9387]
Looking at the implementation of grails.orm.RLikeExpression::toSqlString, it is only supported for oracle, and on other systems, it falls back to just using "like".

My first assertion is that it should throw an exception, not fall back to using "like", as a regular expression patterns will likely NEVER be valid for LIKE.

Secondly, for PostGres, regular expressions are supported using the SIMILAR TO keywords.

**Comment by jeffbrown** [comment]
> Looking at the implementation of grails.orm.RLikeExpression::toSqlString, it is only supported for oracle, and on other systems, it falls back to just using "like".

I think it may also be supported on MySQL: https://github.com/grails/grails-data-mapping/blob/dc072a993763678cf7f291f11cfaa034c103f590/grails-datastore-gorm-hibernate4/src/main/groovy/grails/orm/RlikeExpression.java#L57

>  it should throw an exception, not fall back to using "like"

I think I agree with that: https://github.com/grails/grails-data-mapping/blob/dc072a993763678cf7f291f11cfaa034c103f590/grails-datastore-gorm-hibernate4/src/main/groovy/grails/orm/RlikeExpression.java#L65

**Comment by graemerocher** [comment]
Seems like it would be trivial to add http://www.postgresql.org/docs/8.3/static/functions-matching.html#FUNCTIONS-POSIX-TABLE

Would make a nice pull request ;-)

**Comment by edwardotis** [comment]
I noticed the fix is only tagged for GORM6.
Is this the correct file for me to port the fix to GORM5?

https://github.com/grails/grails-data-mapping/blob/5.x/grails-datastore-gorm-hibernate4/src/main/groovy/grails/orm/RlikeExpression.java
