### ISSUE TITLE
Content Negotiation with Named Converters in Grails 3

### ISSUE THREAD

**Issue by miffels** [grails/grails-core#9392]
Hi,

I have been trying to implement API versioning using named JSON configurations as outlined outlined [in this post](http://mrhaki.blogspot.de/2014/07/grails-goodness-using-converter-named.html). It looks like it is not working, though, since I am getting 406's when I try to query the service. I am wondering, now, if I made a mistake or things changed with Grails 3. You will find an SSCCE [here](https://github.com/miffels/catfood/tree/master/grails-hateoas), in which I applied the changes as described in the guide. Could you take a look at it, please, and tell me if things look about right?

As a side note: If I disable content negotiation and select the configuration directly via `JSON.use`, the correct renderer will be used, so I figure the configuration part of the project is alright.

Thanks,
Michael

**Comment by miffels** [comment]
So what I found so far debugging is the following:
- It does work in general, after all
- The example linked above is missing the corresponding ``JsonCollectionRenderer`` bean definitions which is required to render the index() action response
- Setting the ``mimeTypes`` property of the collection renderer in the Spring beans notation does not work for some reason, but the constructor notation does work:

```
// broken
myClassCollectionRenderer(JsonCollectionRenderer, MyClass) {
  mimeTypes = [new MediaType(...)]
  namedConfiguration = ...
}

// works
myClassCollectionRenderer(JsonCollectionRenderer, MyClass, [new MediaType(...)]) {
  namedConfiguration = ...
}
```

This is somewhat awkward since the ``JsonCollectionRenderer`` inherits from the ``JsonRenderer``, and the first example would work when defining a ``JsonRenderer``:

```
// works, too:
myClassRenderer(JsonRenderer, MyClass) {
  mimeTypes = [new MediaType(...)]
  namedConfiguration = ...
}
```

**Comment by graemerocher** [comment]
Please report to https://github.com/grails-plugins/grails-plugin-converters/issues
