### ISSUE TITLE
Grails 3.0.9: ${createLink(...)} should NOT escape & as &amp;

### ISSUE THREAD

**Issue by danielsun1106** [grails/grails-core#9396]
Hi all,

    ${createLink(...)}  should NOT escape & as &amp; in the url
```gsp
<!-- yields     /app/genImg?width=60&amp;height=30  
       so the server side can not get the height parameter -->
${createLink(controller:'app', action:'genImg', params:[width:60, height:30])} 
```

**Comment by Schlogen** [comment]
Try and wrap `createLink` with `raw()`

**Comment by danielsun1106** [comment]
Hi James, I'll try later. BTW, & escaped as & will make passing parameters fail. Could you tell me the reason Grails intends to treat links in that way? Thanks.



发自我的小米手机在 James Kleeh <notifications@github.com>，2015年11月4日 上午3:00写道：Try and wrap createLink with raw()

**Comment by kasonyang** [comment]
Did you ever update your grails?
I got the escaped html with ${render(...)} when I updated the grails verson incorrectly.

**Comment by Schlogen** [comment]
@danielsun1106 It is being escaped because all content that gets added to the HTML via `${}` gets escaped to prevent XSS. That can be configured differently, however I would strongly advise against it. The options are to use the taglibs or wrap the call with `raw`

**Comment by ntung** [comment]
> Try and wrap `createLink` with `raw()`. Is using the taglib `<g:link` not an option?

I want to confirm here for anyone might encounter this issue. Using `g:link` taglib will resolve the issue straight away.
