### ISSUE TITLE
forward does not work in Grails 3.0.9

### ISSUE THREAD

**Issue by CoreKnowledge** [grails/grails-core#9397]
forward command does not work in Grails 3.0.9

To reproduce the issue:
*1. create a new application with grails 3.0.9*
*2. create a controller like following:*
    
    class ForwardController {

        def index() { }

        def toAim() {
            forward action: 'aim'
        }

        def aim() {
        }
    }

*3. create two views like following*
**index.gsp:**

    <html>
    <head>
        <title>INDEX</title>
    </head>
    <body>
        <p>Hello INDEX</p>
        <g:link action="toAim">toAim</g:link>
    </body>
    </html>

**aim.gsp:**

    <html>
    <head>
        <title>AIM</title>
    </head>
    <body>
        <p>Hello AIM</p>
    </body>
    </html>

*4. a click on the link will end up in .../forward/toAim*

**Comment by graemerocher** [comment]
I'm confused you're forwarding to an action and expecting it to go to a JSP view?

**Comment by CoreKnowledge** [comment]
Oh, sorry. It's a .gsp view. Corresponding to the action in the controller. I change it in the issue

**Comment by graemerocher** [comment]
This works fine and we have a functional test covering this behaviour https://github.com/grails/grails3-functional-tests/blob/master/app1/src/integration-test/groovy/functionaltests/ForwardingSpec.groovy#L46

If you can come up with an example that reproduces the problem we can take another look

**Comment by CoreKnowledge** [comment]
@graemerocher 
https://www.dropbox.com/s/7urqdklrrqdcf6i/testForward.zip?dl=0
check out this example...
