### ISSUE TITLE
g:sortableColumn generates wrong links

### ISSUE THREAD

**Issue by effingen** [grails/grails-core#9400]
If the namespace is not specified there is a line of code which converts it into an empty string:
```
def namespace = attrs.namespace ? attrs.remove("namespace") : ""
```
The value of the namespace is used during generation of the link.

**Comment by orubel** [comment]
I'm not seeing anything related to sortableColumn. You need to show more code and explain your issue more thoroughly please.

**Comment by effingen** [comment]
Sorry, I went to deep. So the problem occurs when you use g:sortableColumn tag, which should generate a link. The generated link is not correct. When you look at the source of org.codehaus.groovy.grails.plugins.web.taglib.UrlMappingTagLib#sortableColumn, there is a line to get a namespace:
{code}
org.codehaus.groovy.grails.plugins.web.taglib.UrlMappingTagLib#sortableColumn
{code}
I don't specify the namespace, cause I don't need to. The code uses empty string then. All the properties of this tag are used to generate the link. In my URL mappings, all my references don't specify the namespace (namespace = null). I think that might be the problem.

Do you need to real example?

**Comment by alvarosanchez** [comment]
@effingen I've been investigating this issue, and I can't reproduce it. When using:

```html
<g:sortableColumn title="title" property="property"></g:sortableColumn>
```

The generated link is:

```html
<a href="/controller/action?sort=property&amp;order=asc">title</a>
```

What is the issue you are experiencing with the link?

**Comment by effingen** [comment]
I have an URL mapping entry like that:
`"/accounts"(resources: 'account', excludes: ['patch'])`

The links are generated like this:
`<a href="/account?sort=...`

What's the best way to reproduce it for you? Unit test, integration test, sample app?

**Comment by alvarosanchez** [comment]
I still don't see what part of the link is incorrect. If you could upload a sample app to github it will help. Thanks!

**Comment by graemerocher** [comment]
No feedback provided

**Comment by jm-stratice** [comment]
I am encountering this issue as well. I have a mapping:
`"/businessgroups"(resources: 'businessGroup')`

The URL being generated is:
`.../businessGroup/index?<params>...`

Like effingen, the mapping uses a plural form ("groups") but the generated resource and generated link are singular ("Group"). As a result, the generated link generates an error.

**Comment by jm-stratice** [comment]
Just noticed this was closed. Will create a new ticket.

**Comment by rvargas** [comment]
@jm-stratice Did you created it? I think I have this problem in 2.5.5.
