### ISSUE TITLE
JSON converter should maintain order of one-to-many relations

### ISSUE THREAD

**Issue by houbie** [grails/grails-core#9401]
When sorting a relation with
```
class Parent {
    static hasMany = [children: Child]
    static mapping = { children sort: 'name'} 
}
```
the order is lost after converting to json:
```
Parent.get(1) //children are sorted
JSON.use('deep'){
    Parent.get(1) as JSON  //children are NOT sorted
}
```

This issue has already been reported in [this JIRA](https://jira.grails.org/browse/GRAILS-8849)

**Comment by Schlogen** [comment]
`children` is a set and therefore has no order. You can change the type to `List` and with an additional column in the table, order can be kept.

**Comment by houbie** [comment]
This discussion already took place in  [this JIRA](https://jira.grails.org/browse/GRAILS-8849)
How I see this:
* Switching to List changes semantics, one typically just wants an ordered Set
* It is reasonable to expect a controller response being the same when requesting either html or json. The `static mapping` provides a convenient way to order relations, but this is broken in json
* I think the solution is as simple as replacing `new HashSet((Set) referenceObject)` with `new LinkedHashSet((Set) referenceObject)` in _org.grails.web.converters.marshaller.json.DomainClassMarshaller.java_ (the default Set implementation in groovy)

**Comment by houbie** [comment]
After looking at the coede, it seems that the same applies to the XML DomainClassMarshaller

**Comment by graemerocher** [comment]
Thanks for the pull request!
