### ISSUE TITLE
Dynamic Finders break with underscore anywhere in property name

### ISSUE THREAD

**Issue by kdickerson** [grails/grails-core#9402]
Similar to https://github.com/grails/grails-core/issues/5919 but slightly wider reach (#5919 says the problem is only with underscore as the first character).  This is a new issue in Grails 3.x; This used to work in the 1.x and 2.x lines (I'm working on migrating over existing code from 2.x to 3.x).

If a domain class property has an underscore anywhere in the name then dynamic finders will break.

    MyDomainClass.findAllByMy_propertyLike('searchTerm')

results in:
> ERROR org.grails.web.errors.GrailsExceptionResolver - QueryException occurred when processing request: [GET] /
> could not resolve property: my_propertyLike of com.example.MyDomainClass. Stacktrace follows:
> java.lang.reflect.InvocationTargetException: null
> ...

Not sure if the wider reach will result in a different resolution than the "won't fix" attached to #5919, but I thought I'd report it as it's own issue since it is slightly different.  And at least this way it's captured.

Grails: 3.0.9
Java: 1.7
OS: Win 7 64-bit

**Comment by graemerocher** [comment]
I tempted to make this a compilation error, why you would ever use underscores in property names I don't know
