### ISSUE TITLE
controller inheritance breaks added resource url mappings

### ISSUE THREAD

**Issue by houbie** [grails/grails-core#9404]
I am able to add a _revisions_ action to a controller that inherits from RevisioningRestfulController (which inherits from RestfulController) with following url mapping:
```
"/api/assets/revisions"(controller: "asset", action: "revisions")
"/api/assets"(resources: "asset")
```
When I move this action to up in the class hierarchy to RevisioningRestfulController, the action cannot be accessed anymore. Instead grails tries to look up the asset with id 'revisions' which fails.

**Comment by graemerocher** [comment]
Please provide an example uploaded to github that reproduces the issue

**Comment by houbie** [comment]
RTFM: _If a controller class extends some other class which is not defined under the grails-app/controllers/ directory, methods inherited from that class are not converted to controller actions_
Adding _@Artefact("Controller")_ to the parent controller solved the problem.
One question though: if the parent controller is not abstract, grails complains that it doesn't have a no-arg constructor. Why doesn't it complain about the _RestfulController_ class?

Sorry for the noise.
