### ISSUE TITLE
Running a specific Integration Spec with 'expect' results in nullpointer on (TransactionTemplate.java:130)

### ISSUE THREAD

**Issue by mpas** [grails/grails-core#9407]
When creating multiple test methods in an integration test, 'grails test-app' works fine but when i want to execute specific test inside the integration test and that test contains an **expect** block it fails with a nullpointer.

```
@Integration
@Rollback
class FooSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }

    void setupData(name) {
        new Foo(name: name).save(flush:true)
    }

    // works fine
    void "WhenThen"() {
        when:
        setupData('test')

        then:
        Foo.findByName('test') != null
    }

    // fail with nullpointer
    void "Expect"() {
        given:
        setupData(create_name)

        expect:
        Foo.findByName(create_name).name.equals(test_name)

        where:
        create_name | test_name
        'test'      | 'test'
    }
}
```

```
java.lang.NullPointerException
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
	at foo.BarSpec.Multiple bar(BarSpec.groovy)
```

So running the tests with 'grails test-app' works ok, but when i run a specific test containing a 'expect' block it fails.

* grails test-app [works ok]
* grails test-app -integration foo.FooSpec.Expect [fails with nullpointer]

I checked this also when running the tests in IntelliJ and this gives the same result.

Running: OSX 10.11.1 / Grails 3.0.9 / java version "1.8.0_66"

I have added a GitHub with an example:
https://github.com/mpas/grails-integrationtest-foo

**Comment by graemerocher** [comment]
I pushed a test for this https://github.com/grails/grails3-functional-tests/commit/a7618ad266a7189183576d269863d5aad0b7b768

And it seems it fails if you run the test individually in the IDE but passes of the whole spec is run. The problem is somewhere deep in Spock internal and our only recommended is that you run the spec class rather than the spec method to avoid this error
