### ISSUE TITLE
Cannot access yaml-defined properties from application.groovy

### ISSUE THREAD

**Issue by hzamir** [grails/grails-core#9408]
From application.groovy, calls to grailsApplication.config.getProperty('prop.name.here') returns [:] for values defined in application.yaml,  and some application-<profile>.yaml.

In my scenario, almost all configuration is in application.yaml,  and some application-<profile>.yaml files.  There is a very small application.groovy file as well, which attempts to read a profile-defined variable, and use it to build other values.  I understood from prior testing (incorrectly?) that the application.groovy was loading last, after the profiles.

My setup does include a scenario noted in #9189 which was addressed in 3.0.5, where there are some shared property roots between the two files, but I don't know if this has anything to do with my problem.

Example

application.yaml contains  foo: hello
application-localhost.yaml contains foo: localhost
application-domain.yaml contains foo: somename

application.groovy contains   xyz = grailsApp.config.getProperty('foo')
running with any profile, the value of xyz is [:]

**Comment by graemerocher** [comment]
This won't be supported as it isn't technically possible
