### ISSUE TITLE
GroovyPageUnitTestMixin can't render a template with another template inside it

### ISSUE THREAD

**Issue by josetristan** [grails/grails-core#9415]
I'm trying to test directly a template. This template constains another template. Test fails showing that it is finding the second template not in the directory of the first template ("tratamiento") but in a "test" directory.

org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Template not found for name [botonesAceptacion] and path [/test/_botonesAceptacion.gsp]

In _form.gsp template the code contains:

`<g:render template="botonesAceptacion"/>`

"_botonesAceptacion.gsp" is also in "tratamiento" directory.

My test:

```
def "have to return a textArea called 'estadoMercancia'  when it has a return goods"(){     
        expect: 
        renderTemplateWithModel([tipoTratamiento:TipoTratamiento.devolucion]).contains ""  " '<textarea name="estadoMercancia" cols="200" rows="5" maxlength="1000" id="estadoMercancia"></textarea>'
    }

    private renderTemplateWithModel(model = [:]) {
             render(template: '/tratamiento/form', model: model)        
    }
```

Thanks and regards.

**Comment by bobbywarner** [comment]
Closing as no example provided to reproduce the issue.

Also, the testing mixins are no longer used with modern Grails versions: https://testing.grails.org
