### ISSUE TITLE
pluginExcludes not honoured

### ISSUE THREAD

**Issue by pledbrook** [grails/grails-core#9416]
It seems that Grails 3 doesn't honour the `packageExcludes` property when packaging plugins. To demonstrate, try building the [Hibernate Filters](https://github.com/fingo/grails-hibernate-filter) plugin. It excludes the domain classes, but these are still packaged in the plugin JAR.

There's no mention of `pluginExcludes` in the migration chapter of the user guide, so I assume it's still supposed to work. To be honest I'd prefer an approach that fits better with the Grails or Gradle model. It feels hacky. These classes should really be in the test source set.

**Comment by graemerocher** [comment]
They have to be defined in `build.gradle` too. Since the build system no longer loads the plugin definition this is the only way. See for example:

https://github.com/grails-plugins/grails-cache/blob/master/build.gradle#L80

https://github.com/grails-plugins/grails-cache/blob/master/src/main/groovy/grails/plugin/cache/CacheGrailsPlugin.groovy#L73

**Comment by pledbrook** [comment]
That doesn't entirely work because the domain classes are still added to the _META-INF/grails-plugin.xml_ file. The application then complains about those missing domain classes if it has the plugin installed.

This should probably be documented in the migration guide too :smile:

**Comment by graemerocher** [comment]
As I see you need to define both in `build.gradle` and in `pluginExcludes`

**Comment by pledbrook** [comment]
So the form of the `pluginExcludes` has changed? Because it's in there, but currently set to _grails-app/domain/**_. OK, so I've checked that the value needs to be changed to _test/**_ and then it works. Thanks.

I think this should be left open as a documentation issue.

**Comment by pledbrook** [comment]
I created a [pull request](https://github.com/grails/grails-doc/pull/397) for this.

**Comment by graemerocher** [comment]
Thanks!
