### ISSUE TITLE
Redirect in controllers doesn't account for groups when using resource mappings

### ISSUE THREAD

**Issue by gregopet** [grails/grails-core#9417]
I'm using groups in my URL mappings:

```
group "/admin", {
    "/domains" (resources: 'domain')
}
```

This works well for `<g:link>`, `<g:createLink>` and `<g:form>`, but not for redirects:

```
redirect controller:'domain', action: 'index'
```

The above code will redirect to `/domains` instead of `/admin/domains`. I've also tried using `redirect resource: domain` but the effect is the same.

I'm using Grails 3.0.8 but the same happens in Grails 3.0.9

**Comment by graemerocher** [comment]
As you can see in the test for this issue https://github.com/grails/grails-core/commit/c8968f066944735f5fbf022c8654184127a85ff6

You have to specify the method if you use the `controller`, `action` form. Otherwise no match is found
