### ISSUE TITLE
Setting spring-boot-starter-tomcat to provided in Grails 3.1.0.M2 does not exclude from war

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#9419]
My War file is still getting packaged with an embedded tomcat8 therefore not allowing me to deploy this war file on a tomcat 7 instance.

**Comment by graemerocher** [comment]
So I tested this and the WAR contains two lib directories. One called `lib` and one called `lib-provided`. The latter contains the Tomcat jars but should not be loaded by the container. The former only contains `tomcat-jdbc` and `tomcat-logging` which are required to create a connection pool and should be an issue.

**Comment by graemerocher** [comment]
I also tested deploying to Tomcat 7 on JDK 7 with Grails 3.1 master and it worked fine for me.
