### ISSUE TITLE
GROM Domain Objects which have an unique field with the same field name

### ISSUE THREAD

**Issue by echopapabravo** [grails/grails-core#9421]
Upgrading from Grails 2.x to 3.x causes an hibernate error on our domain objects which have an unique field with same field name.

Please see: [github.com/echopapabravo](https://github.com/echopapabravo/grom-domain-objects-constraints-unique-same-field-name)

**Comment by echopapabravo** [comment]
Broken link above! Please see: https://github.com/echopapabravo/grom-domain-objects-unique-same-field-name

**Comment by echopapabravo** [comment]
Typo in URL, reopen issue

**Comment by echopapabravo** [comment]
Typo in URL, reopen issue

**Comment by jeffbrown** [comment]
@echopapabravo I don't follow what is going on here.  It looks like you opened it, then you asked us to reopen it, then you closed it.  Is there a bug here that needs to be addressed?
