### ISSUE TITLE
For MongoDB backed domain 'null' inserted when expecting null

### ISSUE THREAD

**Issue by aeischeid** [grails/grails-core#9422]
originally thought this was related to GORM/MongoDb plugin: https://github.com/grails/grails-data-mapping/issues/585

Gails = 2.5.2 : Mongo plugin = 3.0.3

domain (using mongo) where using maps to hold nested objects:

```groovy
class Cert {
	Map owner
	Map ownerPremises
	...
}
```

When doing setters from request.JSON I get unexpected and inconsistent results.

```groovy
cert.owner = request.JSON.owner
cert.save
return cert as JSON

-> {"owner":{"favoriteColor": null, ...}, ... }
```

but if I read from the DB later...

```groovy
def cert = cert.get(id)
return cert as JSON

-> {"owner":{"favoriteColor": "null", ... }, ... }`
```

It appears related to JSONObject.Null and how its `.equals(null) == true` but its `.toString()` returns 'null'

In Mongo the value is actually set as a sting of "null" 

I currently use a cleaner to purge the JSONObject.Null things

```groovy
	// essentially just turns nested JSONObject.Null things into java null things
	// otherwise GORM for mongo is turning them into 'null' String things 
	def static cleanJson(json) {
		if (json instanceof List) {
			json = json.collect(cleanJsonList)
		} else if (json instanceof Map) {
			json = json.collectEntries(cleanJsonMap)
		}
		return json
	}

	def static cleanJsonList = {
		if (it instanceof List) {
			it.collect(cleanJsonList)
		} else if (it instanceof Map) {
			it.collectEntries(cleanJsonMap)
		} else {
			// should be returning really real null if nullish obj
			(it.getClass() == JSONObject.Null) ? null : it
		}
	}

	def static cleanJsonMap = { key, val ->
		if (val instanceof List) {
			[key, val.collect(cleanJsonList)]
		} else if (val instanceof Map) {
			[key, val.collectEntries(cleanJsonMap)]
		} else {
			// should be returning [key: really real null if it is nullish obj]
			[key, (val.getClass() == JSONObject.Null) ? null : val]
		}
	}
```

with that I can do:
```groovy
def myCleanJson = JsonUtils.cleanJson(request.JSON)
cert.owner = myCleanJson.owner
```
And all is well. In Mongo the value is now a null not "null" which is what I would prefer.

**Comment by graemerocher** [comment]
If this is still an issue please report here https://github.com/grails/gorm-mongodb/issues

**Comment by aeischeid** [comment]
I originally reported in the data-mapping repo, but you said it was Grails not Mongo plugin so much. https://github.com/grails/grails-data-mapping/issues/585

It is still an issue as for grails 2.5.4 and mongo plugin 3.0.3. but I don't know about more recent versions.
