### ISSUE TITLE
Grails 3.0.9 - request(POST) to not mapped url, returns status 405 (method not allowed) instead of 404 (not found)

### ISSUE THREAD

**Issue by marciomunhoz** [grails/grails-core#9430]
A POST request for a URL that is not mapped returns the status 405 (method not allowed), however, when request is GET, the status 404(not found) is returned.

Example:
https://github.com/marciomunhoz/test1

To reproduce:
- clone repository or grails create-app test1 --profile=web
- grails run-app
- GET request to http://localhost:8080/ (return status 200 OK)
- POST request to http://localhost:8080/ (return status 200 OK)
- GET request to http://localhost:8080/url-not-mapped (return 404 NOT_FOUND)
- POST request to http://localhost:8080/url-not-mapped (return 405 METHOD_NOT_ALLOWED).

In previous versions of Grails (eg: 2.4.4) the POST request to not mapped url returns status 404.

**Comment by orubel** [comment]
are you running this with any authorization in front of it? That may be causing the additional error for POST.

**Comment by marciomunhoz** [comment]
no, nothing... its simple app

**Comment by orubel** [comment]
what do you mean by 'url-not-mapped'? The url has to be mapped in order to be handled by a controller. That is the only way the context knows how to direct it to a controller method.

**Comment by marciomunhoz** [comment]
When a user try to access a not mapped resource.. 
url-not-mapped is a sample, it could be anything that is not mapped

**Comment by volnei** [comment]
@orubel Yes, but the error must be 404 instead of 405

**Comment by orubel** [comment]
Ah sorry, reading through a couple of posts and this was beginning to sound similar to another. Please ignore.

**Comment by graemerocher** [comment]
I have raised https://github.com/spring-projects/spring-boot/issues/4876 since the behaviour is the same in Spring/Spring Boot. That is not to say the behaviour is correct, but rather than add hacks around the problem I would prefer to see it corrected in the source.

**Comment by igilfanov** [comment]
createLinkTo => resource :-1:  

createLinkTo works without additional add-ons.

Please go back to a usable state createLink !
