### ISSUE TITLE
ConcurrentModificationException at startup when using hyphenated urls

### ISSUE THREAD

**Issue by burtbeckwith** [grails/grails-core#9431]
This doesn't always happen - it appears to be related to the number of actions in a controller. If there are around 10 or more, a ConcurrentModificationException will happen in DefaultGrailsControllerClass.registerUrlConverter()

**Comment by burtbeckwith** [comment]
Fixed by 6c3321fd3fd2459a2a96d6665390b4846a78e10f

**Comment by rvanderwerf** [comment]
some color to this, this introduced between 3.0.4 and 3.0.5
