### ISSUE TITLE
Grails 3.0.5 - 3.0.9 Infinite Exception Loop with Error Handling in Controller and Exception in Interceptor

### ISSUE THREAD

**Issue by jasonschwab** [grails/grails-core#9434]
In a new Grails project, with an ErrorController and a URL mapping:
` "500"(controller: "error", action: "processError")`

TestController with TestInterceptor, the interceptor throws an exception.

When making the request: 
`http://localhost:8080/test/doTest`
an infinite loop occurs, always returning to the Interceptor.  

If the URL mapping is changed back to the default of `"500"(view:'/error')` it works fine.
If the ErrorController is updated to use the view rather than just render a text message, it still occurs.
Does not occur in Grails 3.0.4 and below.

Example Application: https://github.com/jasonschwab/grails-exception-loop

Not sure if this is related to https://github.com/grails/grails-core/issues/9412

**Comment by graemerocher** [comment]
Functional test https://github.com/grails/grails3-functional-tests/commit/9687c2c385990aba6cee8dae060f00df02300614

**Comment by kiloluke** [comment]
still occuring on | Grails Version: 4.0.9

**Comment by davydotcom** [comment]
I hit this just this week. If the output stream is in use it loops and causes OOM

**Comment by kiloluke** [comment]
> 
> 
> I hit this just this week. If the output stream is in use it loops and causes OOM

Also happens with file appenders
