### ISSUE TITLE
Grails 2.5.2 - mockForConstraintsTests does not execute constraints closure on a command object a 2nd time if annotated with Validateable

### ISSUE THREAD

**Issue by boardbloke** [grails/grails-core#9435]
Noticed while upgrading a 1.3.6 application to Grails 2.5.2.  Forgive the code if its not quite compiling - I'm doing it from memory - I can update with actual code this evening if that helps

I have a number of Command classes in separate source files that were annotated with @Validateable.

Some of the constraints for the command objects use static config to parametrise their behaviour thus:

```
@Validateable
class TestCommand {
  String testProperty

  static constraints = {
    testProperty (nullable: !TestCommand.isTestPropertyMandatory())
  }

  static Boolean isTestPropertyMandatory() {
    return Holders.config.testCommand?.mandatory ?: true
  }
}
```

When unit testing using a data driven Spock test I was finding that the 2nd iteration of the test was using the constrained properties built by the 1st iteration.

```
@TestMixin(GrailsUnitTestCaseMixin)
@FreshRuntime
class TestCommandSpec extends Specification {

  def "test mandatory"() {
    given:
       config.testCommand.mandatory = mandatory
       mockForConstraintsTests(TestCommand)

       def cmd = new TestCommand()
       cmd.testProperty = null

    when:
      cmd.validate()
    
    then:
       expected == cmd.errors.testProperty.code.contains('nullable')
   
    where:
      mandatory | expected
      true            | true
      false           | false
  }
}
```

Running the test fails the second iteration.  If I remove the @Validatable annotation on the command object then it works.  When I was debugging, when the code was calling the constraints closure on the 2nd iteration with a break point in the closure, it was not breaking, as though the result of the 1st iteration's call to the constraints closure was cached.

**Comment by graemerocher** [comment]
`mockForConstraintsTests` is deprecated and remove in 3.x
