### ISSUE TITLE
Grails 3.0.9 - Load sequence of URLMappings is not maintained

### ISSUE THREAD

**Issue by satshil** [grails/grails-core#9441]
I was working on a modularized project where I override URLMappings in child plugins.
While doing so I found the URLMapping holder is not considering the plugin load sequence while merging the URL mappings. 

If URLMapping merge follows the same sequence as plugin load sequence I will provide more control over the modularized project.

**Comment by graemerocher** [comment]
Upload an example to github that reproduces the issue

**Comment by satshil** [comment]
Please find attach a quick test. please rename file to .zip it contains structure of 3 plugins and an app.

Project dependencies
==================
testApp -> test-plugin-one -> test-plugin-two -> test-plugin-three

 I added following mappings

test-plugin-three       "/"(view:"/indexThree")
test-plugin-two       "/"(view:"/indexTwo")
test-plugin-one       "/"(view:"/indexOne")

If you try to run this application you can see for mapping "/" the application try to locate indexThree.
where as it should look for indexOne because plugin-one id loaded after plugin-three. I hope its explanatory.

[testURLMappings.txt](https://github.com/grails/grails-core/files/43873/testURLMappings.txt)
