### ISSUE TITLE
Invalid JSON produced for Double.NaN (Grails 2.5.3, 3.0.9)

### ISSUE THREAD

**Issue by squarejaw** [grails/grails-core#9445]
Given this controller action:

``` groovy
def index() {
    render([Double.NaN] as JSON)
}
```

Grails produces this output:

```
[NaN]
```

According to page 3 of the [JSON spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), this is invalid.

> Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not
> permitted. 

For comparsion, Groovy's JsonBuilder throws an Exception when you try to do this.

``` groovy
def builder = new groovy.json.JsonBuilder()
builder([Double.NaN])
builder as String
```

```
groovy.json.JsonException: Number NaN can't be serialized as JSON: NaN are not allowed in JSON.
```

**Comment by jameskleeh** [comment]
Closing this because the bug is with the converters API which is no longer supported
