### ISSUE TITLE
Error parsing GroovyRowResult to Domain (Grails 3.0.9)

### ISSUE THREAD

**Issue by danielsamper** [grails/grails-core#9446]
When we do a parse from GroovyRowResult class to a domain class (Cuser in the example below) only columns with the same name in database and domain are parsed. For example:

- Domain field 'name' -> Database column 'name' -> Parsed successfully
- Domain field 'photoId' -> Database column 'photo_id' -> Not parsed (null value)

        Sql sql = new Sql(dataSource)

        List<GroovyRowResult> candidates = sql.rows("{call bestCandidatesForClientSelection(?,?,?,?,?,?,?)}", [cuser.id, task.tasktype.id, task.id, task.latitude, task.longitude, 12, 5])

        candidates.each { candidate ->
            result.add(new Cuser(candidate ))
        }

**Comment by graemerocher** [comment]
The `Sql` class is part of Groovy not Grails, nothing we can do here.
