### ISSUE TITLE
No Session in Grails 3.1.0.M2 with Spring's @Rollback annotation in @Integration tests

### ISSUE THREAD

**Issue by tvinke** [grails/grails-core#9448]
Seems related to https://jira.grails.org/browse/GRAILS-12114 where there was no Hibernate Session found for current thread with Grails' own `@Rollback`, but I even can't get a Session with Spring's `@Rollback`.

The `save()` in the example on http://grails.github.io/grails-doc/latest/guide/testing.html#integrationTesting fails with `org.hibernate.HibernateException: No Session found for current thread`

```
import grails.test.mixin.integration.Integration
//import grails.transaction.Rollback
import org.springframework.test.annotation.Rollback
import spock.lang.*

@Integration
@Rollback
class SpringRollbackSpec extends Specification {

    void setup() {
         new Book(name: 'Grails in Action').save(flush: true)
         // fails! org.hibernate.HibernateException: No Session found for current thread
    }

    void "test something"() {
        
         expect:
         Book.count() == 1
    }
}
```

I'm using:

| Grails Version: 3.1.0.M2
| Groovy Version: 2.4.5
| JVM Version: 1.7.0_75

**Comment by hakanernam** [comment]
@tvinke Would these comments help?

https://github.com/grails/grails-core/issues/9304#issuecomment-149590772

https://github.com/grails/grails-core/issues/9304#issuecomment-150779931

https://github.com/grails/grails-core/issues/9304#issuecomment-150830137

**Comment by tvinke** [comment]
These seem related but the examples are using `grails.transaction.Rollback` - my problem is with `org.springframework.test.annotation.Rollback`.

Maybe related by there's also _NO actual rolling back_. I updated the example by using `withNewSession` to get past the missing Hibernate Session, but the second test method ("test counting Books again") sees the data inserted by the first.

```
import grails.test.mixin.integration.Integration
//import grails.transaction.Rollback
import org.springframework.test.annotation.Rollback
import spock.lang.*

@Integration
@Rollback
class SpringRollbackSpec extends Specification {

    void setup() {
		Book.withNewSession() {
			new Book(name: 'Grails in Action').save(flush: true)
			// without withNewSession fails! org.hibernate.HibernateException: No Session found for current thread
		}
    }

    void "test counting Books"() {
        
		expect:
		1 == Book.withNewSession() { Book.count() }
    }
	
	void "test counting Books again"() {
		
		expect:
		1 == Book.withNewSession() { Book.count() }
		// fails!
		// Condition not satisfied:
		//
		// 1 == Book.withNewSession() { Book.count() }
		//   |       |
		//   false   2
		//
		// 	at test.SpringRollbackSpec.test counting Books again(SpringRollbackSpec.groovy:28)
	}
}
```

**Comment by graemerocher** [comment]
GORM logic is not allows in the `setup` method currently. This is fixed in master, see https://github.com/grails/grails-core/commit/cc2f2ed86d18fded831242d0c8d2d1ee885fc8a5

**Comment by tvinke** [comment]
Hi Greame,

So does that mean the current Grails 3.0.9 documentation about using
Spring's
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/annotation/Rollback.html
is incorrect -- you can not use GORM in the setup() and there's no
Hibernate Session in the regular test methods as well in Grails 3.1.0.M2,
until we get to 3.1 final.

Is this a correct summary? 😄

Regards Ted
Op 30 nov. 2015 17:04 schreef "graemerocher" <notifications@github.com>:

**Comment by tvinke** [comment]
My bad, I mean until M3.

**Comment by graemerocher** [comment]
that is the correct summary
