### ISSUE TITLE
Cannot set tooltip (title attribute) to sortableColumn 

### ISSUE THREAD

**Issue by MikelisB** [grails/grails-core#9454]
Grails sortable column has 'title' attribute, but that indicates the text inside the link that is generated, not the tooltip.
So in that way tooltip for sortable column cannot be created.
Wanted result- < g:sortableColumn property="property_name" text="Short version" title="Longer version of title that should be shown as tooltip" />

**Comment by orubel** [comment]
Can't this be addressed through a taglib?

**Comment by jknudsen** [comment]
Here is what I created that allow you to have an html title which can be different for Assending and Descending order.  I started with a copy of SortableColumn back in Grails 2.  Can someone point me to where the source for SortableColumn is with Grails 3?  Maybe I can create a pull request.

package mde.ui

//import com.opensymphony.module.sitemesh.Factory
//import com.opensymphony.module.sitemesh.RequestConstants
//import grails.artefact.Artefact
//import org.apache.commons.lang.WordUtils
//import org.codehaus.groovy.grails.web.errors.ErrorsViewStackTracePrinter
//import org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver
//import org.codehaus.groovy.grails.web.mapping.ForwardUrlMappingInfo
//import org.codehaus.groovy.grails.web.metaclass.ControllerDynamicMethods
//import org.codehaus.groovy.grails.web.pages.GroovyPage
//import org.codehaus.groovy.grails.web.pages.GroovyPagesTemplateEngine
//import org.codehaus.groovy.grails.web.pages.GroovyPagesTemplateRenderer
//import org.codehaus.groovy.grails.web.servlet.GrailsApplicationAttributes
//import org.codehaus.groovy.grails.web.sitemesh.FactoryHolder
//import org.codehaus.groovy.grails.web.sitemesh.GSPSitemeshPage
//import org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
//import org.codehaus.groovy.grails.web.util.StreamCharBuffer
//import org.codehaus.groovy.grails.web.util.WebUtils
//import org.springframework.http.HttpStatus
//import org.springframework.util.StringUtils
import org.springframework.web.servlet.support.RequestContextUtils



/**
 * Tags to help rendering of views and layouts.
 *
 * @author Graeme Rocher & Joe Knudsen
 */
class MdeSortableTagLib {

    /**
     * Renders a sortable column to support sorting in list views.<br/>
     * [Adapted from the official Grails version with accessibility enhancements at MDE.]
     * Attribute title or titleKey is required. When both attributes are specified then titleKey takes precedence,
     * resulting in the title caption to be resolved against the message source. In case when the message could
     * not be resolved, the title will be used as title caption.<br/>
     *
     * Examples:<br/>
     *
     * &lt;g:sortableColumn property="title" title="Title" /&gt;<br/>
     * &lt;g:sortableColumn property="title" title="Title" style="width: 200px" /&gt;<br/>
     * &lt;g:sortableColumn property="title" titleKey="book.title" /&gt;<br/>
     * &lt;g:sortableColumn property="releaseDate" defaultOrder="desc" title="Release Date" /&gt;<br/>
     * &lt;g:sortableColumn property="releaseDate" defaultOrder="desc" title="Release Date" titleKey="book.releaseDate" /&gt;<br/>
     *
     * @emptyTag
     *
     * @attr property - name of the property relating to the field
     * @attr defaultOrder default order for the property; choose between asc (default if not provided) and desc
     * @attr title title caption for the column
     * @attr titleKey title key to use for the column, resolved against the message source
     * @attr titleAsc HTML title when order is ascending
     * @attr titleDesc HTML title when order is descending
     * @attr params a map containing request parameters
     * @attr action the name of the action to use in the link, if not specified the list action will be linked
     * @attr params A map containing URL query parameters
     * @attr class CSS class name
     */
    Closure mdeSortableColumn = { attrs ->
        def writer = out
        if (!attrs.property) {
            throwTagError("Tag [sortableColumn] is missing required attribute [property]")
        }

        if (!attrs.title && !attrs.titleKey) {
            throwTagError("Tag [sortableColumn] is missing required attribute [title] or [titleKey]")
        }

        def property = attrs.remove("property")
        def action = attrs.action ? attrs.remove("action") : (actionName ?: "list")

        def defaultOrder = attrs.remove("defaultOrder")
        if (defaultOrder != "desc") defaultOrder = "asc"

        // current sorting property and order
        def sort = params.sort
        def order = params.order

        // add sorting property and params to link params
        def linkParams = [:]
        if (params.id) linkParams.put("id", params.id)
        def paramsAttr = attrs.remove("params")
        if (paramsAttr) linkParams.putAll(paramsAttr)
        linkParams.sort = property

        // propagate "max" and "offset" standard params
        if (params.max) linkParams.max = params.max
        if (params.offset) linkParams.offset = params.offset

        // determine and add sorting order for this column to link params
        attrs.class = (attrs.class ? "${attrs.class} sortable" : "sortable")
        if (property == sort) {
            attrs.class = attrs.class + " sorted " + order
            if (order == "asc") {
                linkParams.order = "desc"
            }
            else {
                linkParams.order = "asc"
            }
        }
        else {
            linkParams.order = defaultOrder
        }

        // determine column title
        def title = attrs.remove("title")
        def titleKey = attrs.remove("titleKey")
        def mapping = attrs.remove('mapping')
        if (titleKey) {
            if (!title) title = titleKey
            def messageSource = grailsAttributes.messageSource
            def locale = RequestContextUtils.getLocale(request)
            title = messageSource.getMessage(titleKey, null, title, locale)
        }

        // Added an HTML title attribute also called tooltip that can
        // be different for Ascending and Descending ordering
        if (attrs.containsKey("titleAsc") && linkParams?.order?.equals("asc")) {
            attrs.put("title", attrs.get("titleAsc"))
        }
        if (attrs.containsKey("titleDesc") && linkParams?.order?.equals("desc")) {
            attrs.put("title", attrs.get("titleDesc"))
        }
        attrs.remove("titleDesc")
        attrs.remove("titleAsc")

        writer << "<th "
        // process remaining attributes
        attrs.each { k, v ->
            writer << "${k}=\"${v?.encodeAsHTML()}\" "
        }
        writer << '>'
        def linkAttrs = [params: linkParams]
        if (mapping) {
            linkAttrs.mapping = mapping
        } else {
            linkAttrs.action = action
        }
        writer << link(linkAttrs) {
            title
        }
        writer << '</th>'
    }
}

**Comment by jknudsen** [comment]
Created a pull request for this item support either an titleHtml or titleAsc and titleDesc above.

[https://github.com/grails/grails-core/pull/10276](pull request)

**Comment by jameskleeh** [comment]
Please file this issue in https://github.com/grails/grails-gsp
