### ISSUE TITLE
Grails war vs war.original

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-core#9456]
I am trying to remove the embedded tomcat server from Grails 3.0.9 application that I am deploying.

In build.gradle, I made this change:
`provided "org.springframework.boot:spring-boot-starter-tomcat"`

Then I am running `grails war`

The build/libs directory has 2 war files - one is .war and the other is .war.original. The .war file contains the embedded tomcat files, but the .war.original file does not. I am confused about whether the .original is the file I should be using, or if this is a bug in the compilation step. 

The tomcat file listing is as follows:
```
84236 Wed Jan 28 09:49:44 CST 2015 WEB-INF/lib/tomcat-embed-logging-log4j-7.0.55.jar
125457 Wed Oct 14 11:29:58 CDT 2015 WEB-INF/lib/tomcat-jdbc-7.0.55.jar
 38195 Wed Oct 14 11:30:02 CDT 2015 WEB-INF/lib/tomcat-juli-7.0.55.jar
  2214 Wed Dec 02 16:25:22 CST 2015 WEB-INF/lib-provided/spring-boot-starter-tomcat-1.2.6.RELEASE.jar
2812733 Wed Dec 02 16:25:22 CST 2015 WEB-INF/lib-provided/tomcat-embed-core-8.0.26.jar
238027 Wed Dec 02 16:25:22 CST 2015 WEB-INF/lib-provided/tomcat-embed-el-8.0.26.jar
 40824 Wed Dec 02 16:25:22 CST 2015 WEB-INF/lib-provided/tomcat-embed-logging-juli-8.0.26.jar
243648 Wed Dec 02 16:25:22 CST 2015 WEB-INF/lib-provided/tomcat-embed-websocket-8.0.26.jar
```

**Comment by Schlogen** [comment]
The tomcat jars being in lib-provided is by design and will allow you to deploy the war to a standalone tomcat or run it standalone. The `gradle war` task will produce the "original" war if you prefer it to not exist at all in the war file.

**Comment by marcDeSantis** [comment]
> The gradle war task will produce the "original" war if you prefer it to not exist at all in the war file.

Wouldn't it be appropriate then to update the docs to reflect the usage of `gradle war` over `grails war` in Grails 3.X?

**Comment by Schlogen** [comment]
@marcDeSantis No, given that the `grails war` produces a war file that is more flexible

**Comment by graemerocher** [comment]
I'm struggling to understand the issue, what is the problem with the tomcat jars being in `lib-provided`?

**Comment by marcDeSantis** [comment]
When I deploy a war to production, I don't want Tomcat to be embedded. [The deployment documentation page](https://grails.github.io/grails-doc/3.0.x/guide/deployment.html) specifies changing tomcat from compile to provided to disable the embedded server, and then mentions using `grails war` to create the deployable war. It is confusing that the .war file created still contains embedded tomcat jars (even with the change to provided) when using `grails war` (while .war.original does not contain the tomcat jars).

**Comment by graemerocher** [comment]
Right, but the Tomcat jars being in `lib-provided` have absolutely no impact on the deployment of your application. The only negative impact they have is a slightly larger WAR file. Doesn't seem worth making a fuss about.

**Comment by marcDeSantis** [comment]
In my particular situation, I am deploying this war to CloudFoundry with the JBP_CONFIG_TOMCAT environment variable setting to specify the tomcat context path. When the tomcat jars are included in lib-provided, the Java Buildpack recognizes that Tomcat is already installed and uses that - which does not allow it to make use of the JBP_CONFIG_TOMCAT settings. This worked fine with Grails 2.x apps, but it took me a few hours to figure out why Grails 3.x apps were behaving differently (especially after reading the deployment documentation which specifies using the provided declaration type to remove the embedded tomcat jars).

Since `gradle war` respects the dependency type, is that not the recommended approach for creating wars?

**Comment by graemerocher** [comment]
Sounds more like an issue with Cloud Foundry, which should be reported there.

**Comment by graemerocher** [comment]
Maybe @dsyer or @nebhale or a member of the Boot team could comment on this who have more knowledge of the Cloud Foundry build pack workings. But it seems like erroneous behaviour on the part of the build part IMO, as this would impact Boot applications too.

**Comment by nebhale** [comment]
The behavior you're most likely seeing is that your WAR file has a `Main-Class` declared in its manifest.  As a rule, we assume that `Main-Class` _always_ takes precedence over all other container choices.  I think your best bet for building a Spring Boot WAR without the `Main-Class` defined is get @philwebb to help out.

That being said, I wouldn't use the Buildpack to adjust the context path of your application.  Spring Boot already allows you to adjust it by setting the `server.context-path` property (or more cloud-natively `SERVER_CONTEXT_PATH` environment variable).  So struggling with modifying your WAR and setting `JBP_CONFIG_TOMCAT` is the equivalent of just `cf set-env <APP> SERVER_CONTEXT_PATH /awesome`.

**Comment by dsyer** [comment]
That's tge way Spring Boot apps work in CF when you build the war with the Boot plugin. if you want the Grails 2.x behaviour you would need to remove the Boot plugin from your build. (But as @nebhale has pointed out, it's probably better just to use the embedded container.)

**Comment by marcDeSantis** [comment]
> The behavior you're most likely seeing is that your WAR file has a Main-Class declared in its manifest. As a rule, we assume that Main-Class always takes precedence over all other container choices. I think your best bet for building a Spring Boot WAR without the Main-Class defined is get @philwebb to help out.

There is no Main-Class defined in my manifest. Only the application name and JBP_CONFIG_TOMCAT settings are there. 

Good to know regarding the SERVER_CONTEXT_PATH. I guess your recommendation would be to use embedded Tomcat for these apps even when deploying to CloudFoundry?

**Comment by nebhale** [comment]
@marcDeSantis The manifest I mean is not your Cloud Foundry manifest, but your `META-INF/MANIFEST.MF` manifest.

And yes, we consider embedded containers to be a better implementation of Cloud Native principals than external containers, even if they are provided by the platform.  This is because you can guarantee that the container is **always** configured the exact same way (and using the exact same container and version) both locally and in the cloud.

**Comment by marcDeSantis** [comment]
> @marcDeSantis The manifest I mean is not your Cloud Foundry manifest, but your META-INF/MANIFEST.MF manifest.

My manifest file is simply:
```
Manifest-Version: 1.0
```

> And yes, we consider embedded containers to be a better implementation of Cloud Native principals than external containers, even if they are provided by the platform. This is because you can guarantee that the container is always configured the exact same way (and using the exact same container and version) both locally and in the cloud.

Thank you - that is helpful.
