### ISSUE TITLE
Spock integration test with expect: and where: fail on TransactionTemplate NPE, unless there's a dummy expect: test

### ISSUE THREAD

**Issue by tvinke** [grails/grails-core#9457]
Related to [issue 9407 - _Running a specific Integration Spec with 'expect' results in nullpointer on (TransactionTemplate.java:130)_](https://github.com/grails/grails-core/issues/9407)  but somewhat different enough to warrant maybe its own issue.

TL:DR I'm getting the 
```
java.lang.NullPointerException
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
```
in a Spock integration test when there's a test using `expect:` and `where:` in a single test method in a test class. _The difference with  [issue 9407](https://github.com/grails/grails-core/issues/9407) is that it's when running the full testsuite with `gradlew check` - not just a single class._

Example (of which I put a 3.0.9 and 3.1.0.M2 example on https://github.com/tvinke/grails3-issue-spock-expect-int-test):
```
import grails.test.mixin.integration.Integration
import grails.transaction.*
import spock.lang.*

@Integration
@Rollback
class SpockWhereIntegrationSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }
		
    def "maximum of two numbers with expect and where"(int a, int b, int c) {
        expect:
        Math.max(a, b) == c

        where:
        a | b | c
        1 | 3 | 3
        7 | 4 | 7
        0 | 0 | 0
    }
}
```
The "maximum of two numbers with expect and where" test fails with
```
java.lang.NullPointerException
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
	at test.SpockWhereIntegrationSpec.maximum of two numbers with expect and where(SpockWhereIntegrationSpec.groovy)
```
Seems it's the combination of using `expect:` and `where:` together in an integration test, but only when there's just a _single method_. The weird thing is that *I can get this test to PASS* by including another test:

_Either an additional `given/when/then/where`_:
```
class SpockWhereIntegrationSpec extends Specification {
		
	// presence of this test makes last one succeed
	def "maximum of two numbers with then and where"(int a, int b, int c) {
		when: ""
				
		then:
		Math.max(a, b) == c

		where:
		a | b | c
		1 | 3 | 3
		7 | 4 | 7
		0 | 0 | 0
	}

    // now works!	
    def "maximum of two numbers with expect and where"(int a, int b, int c) { .. }
}
```

or additionally _just a dummy test with `expect`_:
```
class SpockWhereIntegrationSpec extends Specification {
		
	// presence of this test makes last one succeed
	def "just expect"() {
		expect:
		true
	}

    // now works!	
    def "maximum of two numbers with expect and where"(int a, int b, int c) { .. }
}
```

So the workaround suggested ([comment Greame](https://github.com/grails/grails-core/issues/9407#issuecomment-160164208)) of just running the whole suite (with `grails test-app` or `gradlew check`) doesn't work seem to work for me - only a dummy test case (`def "just expect"()`)  ;-)

| Grails Version: 3.0.9 and 3.1.0.M2
| Groovy Version: 2.4.5
| JVM Version: 1.7.0_75

**Comment by ortimanu** [comment]
Hi, I am getting this error when running my app in production mode and making a request to a controller that in turns uses a service for some processing. I am using Grails version 3.0.11. I have no tests or integration tests specified. What do you recommend?

**Comment by graemerocher** [comment]
Upload an example that reproduces the issue to github and raise a new issue

**Comment by ortimanu** [comment]
Hi @graemerocher! I have already solved this issue. It was a plugin issue. When I updated the plugin, the problem disappeared. Thanks!

**Comment by nileshshrestha** [comment]
@ortimanu I am getting this error. What plugin was causing it?
