### ISSUE TITLE
Surprisingly ReactorPromiseFactory takes over from GparsPromiseFactory and creating Promises fails with:  No Supplier<Dispatcher> found for name 'dispatcherGroup'

### ISSUE THREAD

**Issue by tvinke** [grails/grails-core#9458]
Surprisingly `ReactorPromiseFactory` takes over from `GparsPromiseFactory` to create Promises and fails, as soon as Reactor is configured with custom dispatcher.

Using Grails 3.0.1.M2 I started with an integration test which creates promises [as explained in the docs](http://grails.github.io/grails-doc/latest/guide/async.html#promises) and _succeeds_ as expected:
```
import grails.test.mixin.integration.Integration
import grails.transaction.*
import spock.lang.*
import static grails.async.Promises.*

@Integration
@Rollback
class AsyncSpec extends Specification {

    void "test promises"() {
    		def p1 = task { 2 * 2 }
    		def p2 = task { 4 * 4 }
    		def p3 = task { 8 * 8 }
    		expect: [4,16,64] == waitAll(p1, p2, p3)
    }
}
```

It's a bit simplified ofcourse. My real integration test code uses it to load a bunch of test data in parallel.

For some entirely different use case in my application I want to use events based on Reactor. I didn't want to use the defaults, so I configured it [as explained in the docs](http://grails.github.io/grails-doc/latest/guide/async.html#events) with a custom default dispatcher like:

```
reactor:
    dispatchers:
        default: myExecutor
        myExecutor:
            type: threadPoolExecutor
            size: 5
            backlog: 2048
```
At that moment, my integration tests started failing. _`ReactorPromiseFactory` now is taking over from `GparsPromiseFactory` to create the promises, but it fails to find a "Supplier<Dispatcher>"._ 

The exception:
```
java.lang.IllegalArgumentException: No Supplier<Dispatcher> found for name 'dispatcherGroup', it must be presentin the configuration properties or being registered programmatically through this#addCachedDispatchers(dispatcherGroup, someDispatcherSupplier)
	at reactor.Environment.getCachedDispatchers(Environment.java:650)
	at reactor.Environment.getCachedDispatchers(Environment.java:635)
	at reactor.Environment.cachedDispatcher(Environment.java:225)
	at org.grails.async.factory.reactor.ReactorPromise.<init>(ReactorPromise.groovy:41)
	at org.grails.async.factory.reactor.ReactorPromiseFactory.createPromise(ReactorPromiseFactory.groovy:55)
	at grails.async.Promises.task(Promises.java:121)
	at test.AsyncSpec.$tt__$spock_feature_0_0(AsyncSpec.groovy:24)
	at test.AsyncSpec.test promises_closure1(AsyncSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:67)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
	at test.AsyncSpec.test promises(AsyncSpec.groovy)
```
As a workaround I now have to set the (original) `GparsPromiseFactory` explicitly to get it to succeed again.
```
import grails.test.mixin.integration.Integration
import grails.transaction.*
import spock.lang.*
import grails.async.Promises
import static grails.async.Promises.*

@Integration
@Rollback
class AsyncSpec extends Specification {

    def setup() {
    		Promises.promiseFactory = new org.grails.async.factory.gpars.GparsPromiseFactory()
    }

    void "test promises"() {
    		def p1 = task { 2 * 2 }
    		def p2 = task { 4 * 4 }
    		def p3 = task { 8 * 8 }
    		expect: [4,16,64] == waitAll(p1, p2, p3)
    }
}
```
Example project: https://github.com/tvinke/grails3-issue-promises-reactor-factory

I'd rather see either the `ReactorPromiseFactory` _not fail_ when taking over the responsibility of creating promises in above use case. I'm not sure whether or not this is a bug or a feature, but certainly goes against the Principle of Least Surprise -- or am I missing something? ;-)

**Comment by graemerocher** [comment]
Reactor promises require the presence of a `dispatcherGroup` dispatcher. This configuration works:

```
reactor:
    dispatchers:
        default: myDispatcher
        myDispatcher:
            type: threadPoolExecutor
            size: 5
            backlog: 2048
        dispatcherGroup:
            type: dispatcherGroup
```

I guess this should be added to the documentation.

**Comment by tvinke** [comment]
Thx Greame.
 I'll try to add it to the documentation.

**Comment by ctoestreich** [comment]
This is still not present in the current async docs and using a task {} breaks without the presence of the dispatcherGroup config in http://docs.grails.org/latest/guide/async.html#events
