### ISSUE TITLE
Grails 3.0.10 does not find i18n keys from inline plugins

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-core#9459]
After installing 3.0.10 via sdkman and changing only several gradle.properties files, i18n keys coming from inline plugins disappeared and default values  were shown in views. If some key from plugin is added to applications's messages_xx.properties, correct value appears immediately upon refresh.

Also, many thanks for the release. Just updated and it is nice to be able to ^C and really stop the app, without having to hunt the java process to kill :-)

**Comment by hakanernam** [comment]
I wanted to mention I still have the war file from 3.0.9 and when I run it, all messages are displayed correctly.

**Comment by EdersonGarcia** [comment]
I'm testing 3.1.0.M3 and also this occurring the same problem
