### ISSUE TITLE
Grails 2.5.3: render template with explicit layout fails

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#9461]
Starting in 2.5.3, calling `render template: 'foo', layout: 'bar'` no longer works, failing with:

`ApplicationObjectSupport instance [org.codehaus.groovy.grails.web.sitemesh.GrailsLayoutView: unnamed; URL [null]] does not run in an ApplicationContext`

This is caused by a change in:

https://github.com/grails/grails-core/commit/50ce415c6

The `createContentBufferingResponse` method passes the servlet context to the buffering response but in some cases its not valid. Switching line 123 to `webRequest.getServletContext()` fixes the problem in my sample application.

**Comment by longwa** [comment]
Sample at: https://github.com/longwa/grails-9461

Browse to:
http://localhost:8080/templateLayoutBug/book/index

**Comment by demon101** [comment]
As I understand, the bug has been fixed by https://github.com/grails/grails-core/pull/9465/files
If yes, why it not listed in https://github.com/grails/grails-core/issues?q=milestone%3Agrails-2.5.4+is%3Aclosed ?

What is release date for 2.5.4?
