### ISSUE TITLE
grails 3.0.10 ignore grails.enable.native2ascii for build war

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#9464]
grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsExtension.groovy

I think because of this:
boolean native2ascii = !Os.isFamily(Os.FAMILY_WINDOWS)

On Linux, you can build. On Windows transcoding does not happen, but there is a replacement of certain special characters, which makes the text, at least in Russian is not readable.

**Comment by AlexKovynev** [comment]
I think the problem GRAILS-12013 was incorrectly resolved, unfortunately I can not yet understand where the problem is, even without transcoding the files initially break. Not all of the characters, for example, breaks down large russian letter "И".

**Comment by AlexKovynev** [comment]
I think this is it https://github.com/gradle/gradle/pull/520
But iam really don't undestand why only some character corrupted, maybe this is Windows java bug.

**Comment by AlexKovynev** [comment]
Unfortunately I can not find the cause in the absence of the possibility to disable native2ascii in Linux. Temporary solution:

gradle.taskGraph.afterTask { Task task, TaskState state ->
    if (task.name == 'processResources') {
	ant.copy(todir: 'build/resources/main', encoding: 'utf8', outputencoding: 'utf8', overwrite: true) {
    	    fileset(dir: 'grails-app/i18n')
	    filterchain {
		EscapeUnicode {
		}
	    }
	}
    }
}

I hope someday will pay attention to the problem :)

**Comment by graemerocher** [comment]
Thanks for debugging it, so what you are saying is the above ant.copy fixes the problem for you?

**Comment by AlexKovynev** [comment]
Here's what I found:
byte[] bytes = «И-диотизм».getBytes("UTF-8");
String s1251_x = new String(bytes);
 String xx = new String(s1251_x.getBytes(), "UTF-8"); 
 System.out.println("xx=" + xx + ",len=" + xx.getBytes().length);
// «xx=??-диотизм,len=10»

So yes, the problem is that when you copy with gradle the encoding is not specified explicitly.
It would be good to rewrite the copy procedure in the ant.

native2ascii I think it is right or taken from the configuration (grails.enable.native2ascii), if possible. But now is not the problem, as it turned out.

**Comment by graemerocher** [comment]
I have added an option to configure Ant to do the conversion, hopefully the problem will be fixed more generally in Gradle in the future:

```
grails {
    native2asciiAnt = true
}```

**Comment by AlexKovynev** [comment]
Can you explain. On windows native2ascii is false. How can grailsExt.native2asciiAnt?
Where can i set native2ascii?

 if (!native2ascii) {
} elseif(!grailsExt.native2asciiAnt) {
}

**Comment by graemerocher** [comment]
in our `build.gradle`. Can't recall why it is `false` in Windows, there is no native `native2ascii` process in Windows as far as I know

**Comment by AlexKovynev** [comment]
GrailsExtension.groovy
boolean native2ascii = !Os.isFamily(Os.FAMILY_WINDOWS)
Then def native2ascii = grailsExt.native2ascii

As I understand native2ascii early was in grails-app/conf/application.yml but not used.
Is it true that it is now in build.gradle?

So i need in in build.gradle?
grails
{
native2asciiAnt = true
native2ascii = false
}

**Comment by graemerocher** [comment]
yes it is now in `build.gradle`

**Comment by AlexKovynev** [comment]
Thank you, then I look forward to version 3.0.11, I hope in version 3.1.0 will also :)
