### ISSUE TITLE
Grails 3.1.0.M3 profile angular- issue where grails does not start

### ISSUE THREAD

**Issue by sapanparikh18** [grails/grails-core#9470]
Newly created a grails project with

`grails create-app StudioApp --profile=angular`

And getting the following error
>`A problem occurred evaluating root project 'StudioApp'.
> Could not find property 'warName' on root project 'StudioApp'.`

Once I add warName attribute in gradle.properties
the following error appears.
> * What went wrong:
>A problem occurred evaluating root project 'StudioApp'.
> Failed to apply plugin [id 'grails']
> Extension of type 'ProjectSourceSet' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, DefaultArtifactPublicationSet_Decorated, DefaultGrailsProject_Decorated]```

**Comment by Schlogen** [comment]
Did you add settings for creating a war file? Currently the profile doesn't have the war plugin added by default. Add `apply plugin:"war"` to your build.gradle above any grails plugins

**Comment by Schlogen** [comment]
Resolved by https://github.com/grails/grails-profile-repository/commit/2596783fbc1995ebc9c8f9dde7827839f4d0f5a6
