### ISSUE TITLE
grail 3.1.0.M2/3 profile jars not being found on Win10 Pro/64 bit

### ISSUE THREAD

**Issue by wstidolph** [grails/grails-core#9472]
With Grails 3.1.0 M2 and M3 an attempt to create an app fails, like this (this is using cygwin bash, I get similar output under CMD shell):
```
$ grails create-app g31m3 --profile=web
Resolving dependencies..
.Error
|
Error occurred running Grails CLI: src 'C:\Users\Wayne%20Stidolph\.m2\repository\org\grails\profiles\base\3.1.0.M3\base-3.1.0.M3.jar' doesn't exist. (Use --stacktrace to see the full trace)
```
That file does exist in my maven repo, exactly where grails reports it is looking. I've attached the (verbose) stacktrace.
```
$ grails create-app g31m3 --profile=rest
Resolving dependencies...
Error |
Error occurred running Grails CLI: Could not find artifact org.grails.profiles:rest:jar:3.1.0.M3 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)
```
Here's my grails info:
```
$ echo $GRAILS_HOME
c:\grails\grails-3.1.0.M3
$ which grails
/cygdrive/c/grails/grails-3.1.0.M3/bin/grails
$ grails -version
|Grails Version: 3.1.0.M3
|Groovy Version: 2.4.5
|JVM Version: 1.8.0_65
```
Grails 3.1.0.M3 is freshly unzipped on my Win10 64 system, and I've deleted all my existing ~/.grails (the C:\Users... one, and the bash ~/.grails, and ~/.sdkman/grails).

This works on grails 3.1.0.M1 on my machine.
[create-fail-stacktrace-verbose.txt](https://github.com/grails/grails-core/files/56263/create-fail-stacktrace-verbose.txt)

**Comment by dmonti** [comment]
Same here on v3.1.0.RC2

| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:web-api:jar:3.1.0.RC2 in grailsCentral (https://repo.grails.org/grails/core) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
