### ISSUE TITLE
Exception thrown during respond() is not handled with url mapping for 500

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#9473]
Having a converter for Domain class which might throw an exception, i.e.:
```
class MyDomainMarshaller {

    @javax.annotation.PostConstruct
    void registerMarshallers() {
        JSON.registerObjectMarshaller(MyDomain) { myDomain ->
            throw new RuntimeException("some exception")
        }
    }
}
```

brings problem when rendering response with controller respond method:
```
def show(Long id) {
    respond MyDomain.get(id)
}
```

This exception should result in rendering 500 defined in url mappings:
```
"500"(controller: "error", action: "index")
```

It renders 200 with following content `[`. It seems that response was partially rendered.

**Comment by AlexKovynev** [comment]
With interceptors seem to have the same problem.  At least 404 are not intercepted.

**Comment by graemerocher** [comment]
Yeah the issue here is the response has already been committed by the time the exception happens so at that point there is no going back
