### ISSUE TITLE
Tomcat throws 403 but grails doesn't show the view from the UrlMapping file

### ISSUE THREAD

**Issue by reinoutkorbee** [grails/grails-core#9477]
In Tomcat 7.0.13 a Realm is configured to retrieve users and roles from a database. The web.xml contains a security constraint and a security role. If the user has a different role then the user is not allowed to enter the site. Tomcat throws a 403 error and displays its default error page. In Grails 3.0.9 we have configured a UrlMapping like this:

403(view:"/errors/accessDenied")

but this page isn't shown in the above case, as would be expected.

If I create a controller that returns a HTTP 403 response then the accessDenied page is shown correctly.

In Tomcat, other error pages, such as for the HTTP 404 and 500 codes, are shown correctly.

In Grails 2.2.4 this used to work. After the upgrade to 3.0.9 this scenario doesn't work anymore.

**Comment by graemerocher** [comment]
Please upload an example to github with steps to reproduce.

**Comment by Civillain** [comment]
Ok, I'll try to isolate the issue



Am 11.12.2015 um 13:49 schrieb graemerocher <notifications@github.com>:

Please upload an example to github with steps to reproduce.

**Comment by Civillain** [comment]
Attached is a zip file with the necessary files.

Test Scenario:

1. Start the app and login, all works well
2. The Redirect in the UrlMapping file works as can be checked by calling
the 'ForbiddenController'
3. Stop the app server and modify the web.xml: replace the security-role
with 'xxx'
4. start again and access the app: now the tomcat HTTP403 page is displayed
and not the mapped accessDenied view

This behaviour occurs in tomcat 7.0.67 and in 8.0.30

Conclusion: if a user does not have the role as required in the security
constraint, he will see the tomcat error page and not the application
provided error page, as would be expected.

**Comment by graemerocher** [comment]
Github doesn't support ZIP attachments, you will need to upload the project to github repo (or renaming the file from `.zip` to `.txt.` might work)

**Comment by Civillain** [comment]
I am trying to upload but it is not working, I'll just copy/ paste:

tomcat-users.xml:

```javascript
<tomcat-users>
  <role rolename="manager-gui"/>
  <role rolename="role1"/>
  <user username="tomcat" password="tomcat" roles="role1,manager-gui"/>
</tomcat-users>
```

web.xml:
```javascript
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="2.5" metadata-complete="true"
	xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd">

		<!-- SECURITY CONSTRAINTS -->

	<login-config>
	    <auth-method>BASIC</auth-method>
	</login-config>

	<!-- default no access -->
	<security-constraint>
		<display-name>Allows access to all authenticated users</display-name>
		<web-resource-collection>
			<web-resource-name />
			<url-pattern>/</url-pattern>
			<url-pattern>/*</url-pattern>
		</web-resource-collection>
		<auth-constraint>
			<role-name>role1</role-name>
		</auth-constraint>
	</security-constraint>

	<security-role>
		<role-name>role1</role-name>
	</security-role>

	<!-- // SECURITY CONSTRAINTS -->

</web-app>
```

UrlMappings.groovy:

```javascript
class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
		"403"(view:'/accessDenied')
		"401"(view:'/accessDenied')
    }
}
```

ForbiddenController.groovy:

```javascript
package rko.test

class ForbiddenController {
	
	def index() {
		render(status: 403)
	}
	
}
```

accessDenied.gsp:
```javascript
<!doctype html>
<html>
    <head>
        <title>Access Denied</title>
        <meta name="layout" content="main">
        <g:if env="development"><asset:stylesheet src="errors.css"/></g:if>
    </head>
    <body>
        <ul class="errors">
            <li>Error: Access denied</li>
        </ul>
    </body>
</html>
```

**Comment by orubel** [comment]
Doesn't this need an ErrorController?

**Comment by Civillain** [comment]
Not according to the documentation: http://grails.github.io/grails-doc/3.0.x/guide/single.html#mappingToResponseCodes

And I tried with an ErrorController and the result is the same.

**Comment by graemerocher** [comment]
Related - how to configure a realm with embedded tomcat: 

http://stackoverflow.com/questions/24429315/how-to-set-custom-realm-in-embedded-tomcat-server-i-am-using-spring-boot

**Comment by AlexKovynev** [comment]
+1

**Comment by graemerocher** [comment]
The issue is due to the fact that no `<error-page>` definitions have been configured in your `web.xml`. When you fail to authenticate Tomcat will use these to decide which error URI to dispatch to, unfortunately this means that Grails is never reached when using a realm.

This is not an issue when you use Grails with an embedded container we automatically configure the `<error-page>` definitions using `UrlMappingsErrorPageCustomizer`. Unfortunately this is not possible when you deploy as a WAR file so you have to manually configure these. See http://stackoverflow.com/questions/7066192/how-to-specify-the-default-error-page-in-web-xml for example.

I should probably have a `prepare-for-war-deployment` command or something that setup a `web.xml` and configured the error pages appropriately, but currently this is not the case.

**Comment by agostonbonomi** [comment]
> The issue is due to the fact that no `<error-page>` definitions have been configured in your `web.xml`. When you fail to authenticate Tomcat will use these to decide which error URI to dispatch to, unfortunately this means that Grails is never reached when using a realm.
> 
> This is not an issue when you use Grails with an embedded container we automatically configure the `<error-page>` definitions using `UrlMappingsErrorPageCustomizer`. Unfortunately this is not possible when you deploy as a WAR file so you have to manually configure these. See http://stackoverflow.com/questions/7066192/how-to-specify-the-default-error-page-in-web-xml for example.
> 
> We should probably have a `prepare-for-war-deployment` command or something that setup a `web.xml` and configured the error pages appropriately, but currently this is not the case.

Hey @graemerocher , how can I configure a web.xml when I deploy as a war file?

**Comment by bobbywarner** [comment]
Closing as there is currently nothing to fix in `grails-core` for this issue.

If there is indeed a desire to create a `prepare-for-war-deployment` type of command or something that goes beyond what is already provided by Spring Boot, we can discuss further.
