### ISSUE TITLE
UrlMappingsGrailsPlugin fails to resolve views when using HyphenatedUrlConverter

### ISSUE THREAD

**Issue by sbglasius** [grails/grails-core#9478]
When using 

`grails.web.url.converter = 'hyphenated'` the views are not resolved right, when the action has camel case, like `importUsers`. One would expect it to resolve `importUsers.gsp` but in fact it tries to resolve `import-users.gsp`

This does not happen if the `CamelCaseUrlConverter` is used (default).

For an example that fails, see this PR:
https://github.com/jeffbrown/viewdemo/pull/1

**Comment by graemerocher** [comment]
@jeffbrown has this been applied to the 3.0.x branch yet?
