### ISSUE TITLE
Can't pass filename argument to gradle schemaExport task

### ISSUE THREAD

**Issue by reinoutkorbee** [grails/grails-core#9484]
The grails task schem-export takes several arguments, for example:

grails schema-export db/schema.sql

The matching gradle task however doesn't:

gradle schemaExport

The latter exports the schema file by default to the build directory.

**Comment by dtamm** [comment]
Seems more like a gradle issue than a grails issue to me?

**Comment by graemerocher** [comment]
This needs to be made customisable https://github.com/grails/grails-data-mapping/blob/master/grails-plugins/hibernate5/src/main/groovy/grails/plugin/hibernate/commands/SchemaExportCommand.groovy#L41

Pull requests welcome

**Comment by jameskleeh** [comment]
This can be done with `gradle schemaExport -Pargs="db/schema.sql"`

Tested with 3.2.0.BUILD-SNAPSHOT

**Comment by sedge55** [comment]
How can it be done in a Gradle Task (in build.gradle)?
