### ISSUE TITLE
grails 3.1.0.m3 - @ToString "ignored" on domain class

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9492]
seeing https://github.com/grails/grails-core/issues/9317 again in a freshly created 3.1.0.m3 app but i cannot figure out why - the check is there but somehow grails default toString() gets applied..
@Schlogen maybe you have an idea? thx!

**Comment by memorydoor** [comment]
@zyro23 @Schlogen 
 I'm using 3.1.0.RC1, seeing the @ToString not working as well.

Looked injectToStringMethod method in:
https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/compiler/injection/DefaultGrailsDomainClassInjector.java

if (!hasToString && !isEnum(classNode) && !hasToStringAnnotation) 
Seems this logic does is to add default toString when:
1, toString is not overwrite in the domain
2, the domain class is not a Enum
3, the domain class doesn't have a @ToString annotation.

My doubt is, what the logic will do when the domain class has a @ToString annotation.
Is the groovy will take care of it ?

**Comment by Schlogen** [comment]
@memorydoor @zyro23 If you can provide an example project that is reproducing the problem, that will make debugging much easier.

**Comment by Schlogen** [comment]
I was able to verify the problem is indeed happening in 3.1 RC1

**Comment by memorydoor** [comment]
@Schlogen @zyro23 , I don't know how to debug this case, so I added some print out, and my domain only has ToString annotation, and doesn't have toString method.

!hasToString:true
!isEnum(classNode):true
!hasToStringAnnotation:false
!hasToString && !isEnum(classNode) && !hasToStringAnnotation:false

But the actual value from toString is still like package.domainName : (unsaved)

Seems there is somewhere else having logic always overwriting domain's toString.

**Comment by Schlogen** [comment]
@graeme  Any idea why the test for this would pass even though it's not working in a project?

**Comment by yancovski** [comment]
Guys, we still have this problem. Is there a workaround?
