### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by driverpt** [grails/grails-core#9494]
I think it would be good to have Contributing Guidelines (Contributing.md) and enforcing it a bit.

For example, i noticed that in this [commit](https://github.com/grails/grails-core/commit/b0c5b9e039cee9822e11cbac341cfc0edd80d8ee) that it's a bit hard to see what's being implemented due to IDE Styling changes.

Another thing i notice is the Commit messages that are too long. I recommend the measures explained [here](http://chris.beams.io/posts/git-commit/). For example, 50 Character Soft limit for subject line. Wrap the body @ 72 characters.

What do you think?

**Comment by graemerocher** [comment]
Feel free to improve https://grails.org/contribute.html

Either way this is not a bug

**Comment by jeffbrown** [comment]
It is bad practice to mix widespread formatting changes in the same commit with real behavior changes.  This is just general good programming stuff, nothing to do with Grails in particular.  I don't mind our contributing guide calling it out but I don't want our contributing guide to turn into a giant manifest of how to write software.

**Comment by driverpt** [comment]
@jeffbrown, i agree with you, but since Grails is a Public Project and accepts community contributions, i just think that some guidelines should be enforced in order to maintain the consistency in the commits.
I also don't agree with a giant manifest, but just some small and simple guidelines, e.g.: Commit Message, Reformat the code in a different commit, etc...
