### ISSUE TITLE
[grails 3.1.0.M3] create-plugin web-api not possible?

### ISSUE THREAD

**Issue by schmittr** [grails/grails-core#9497]
I dunno, if this is meant to work:
```
grails create-plugin some-api --profile=web-api
```

But currently it creates an app and not a plugin. If this isn't intended to be used like that, see it as a feature request :wink:

**Comment by graemerocher** [comment]
yeah it currently isn't supported

**Comment by graemerocher** [comment]
This was added with the `rest-api-plugin` profile in 3.1.7
