### ISSUE TITLE
Getting started section of website completely broken

### ISSUE THREAD

**Issue by axelfontaine** [grails/grails-core#9503]
https://grails.org/start is a mess.

Step 1: No video in Chrome
Step 2: Wrong instructions (should be gradlew)

If this is a Grails 2.x relic please remove or fix as it is still the top hit on Google for "grails get started"

**Comment by jeffbrown** [comment]
Pull requests to https://github.com/grails-samples/grails-website/blob/4712fb5cd5281cbd21d628abf49e67a8958888be/grails-app/views/learn/gettingStarted.gsp are welcome.

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails-samples/grails-website/commit/ed16154e9fb8eda023516d59083d59cdb4422e62
