### ISSUE TITLE
grails-3.0.10 : Multiple datasources with Mongodb fails to use secondary datasource

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9504]
I can successfully use multiple datasource with RDBMS's but with mixing JPA datasources like RDBMS and NOSQL (ie Mysql and Mongodb), it is failing and defaulting to the Mongo instance for both.

https://gist.github.com/orubel/673682d4d164905e5e63

Not really a blocker for me as I can always convert back but figured this is a bit of an issue since in more advanced configs, it's useful to split resources across different systems for different purposes.

**Comment by graemerocher** [comment]
Multiple data sources are not currently supported by MongoDb, so this would be a feature request. Please raise the issue here https://github.com/grails/grails-data-mapping/issues

**Comment by orubel** [comment]
Oh cool. Thanks.
