### ISSUE TITLE
Grails 2.5.0 cannot use traits in Controllers as actions

### ISSUE THREAD

**Issue by danweller18** [grails/grails-core#9511]
I attempted a similar example found in the docs https://grails.github.io/grails-doc/2.5.0/guide/single.html#controllerExceptionHandling

and also tried http://stackoverflow.com/questions/28860972/use-a-groovy-trait-in-a-grails-controller

    import grails.web.Action
    
    trait ColumnSelectionController {
    
      @Action
      def selectColumns() {
         //Do something here
      }
    }

Both gave me errors saying 'raise a jira'

**Comment by jeffbrown** [comment]
The code at https://github.com/jeffbrown/traitexceptionhandling/commit/f9406217a689ff137c87d4dfd6130a787ef8fe94 demonstrates one way to make this work.

**Comment by danweller18** [comment]
Thank you that works! sorry for the mistake
