### ISSUE TITLE
loading system properties with 'run' in build.gradle fails

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9512]
via this example in Mr Hakis blog (http://mrhaki.blogspot.com/2015/09/grails-goodness-passing-system.html) he shows a way to load system properties in your build.gradle file.

Another way to do this was to also just put something like the following:

run {
    systemProperties = System.properties
}

test {
    systemProperties = System.properties
}

But the word 'run' is throwing an error every time in RC1

Error is as follows:

| Error Error initializing classpath: Could not find property 'run' on root project 'api-framework'. (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
groovy.lang.MissingPropertyException: Could not find property 'run' on root project 'api-framework'

Neither of these examples work and both are throwing this error.

**Comment by zyro23** [comment]
use
```groovy
bootRun {
    systemProperties = System.properties
}
```
the `run` task is not available by default anymore if you do not explicitly apply the gradle `application` plugin because the spring-boot gradle plugin does no longer apply it automatically.
* spring-projects/spring-boot#2679
* https://github.com/spring-projects/spring-boot/commit/867325095522ecd7f466ae7e95db490897e356b4

**Comment by orubel** [comment]
ah. Thank you.

**Comment by bAmrish** [comment]
I had a similar issue open on [stackoverflow](http://stackoverflow.com/questions/37976517/passing-command-line-arguments-for-grails-run-app-through-gradle-task). Found it out by trail and error. :smile: and was about to raise a PR for the fix when I found this.
