### ISSUE TITLE
Grails 3.1.0.RC1 - validate() method on Validateable class causes ALL non-static getXyz() methods without parameters to be called

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9513]
Based on example below:
```
import grails.validation.Validateable

class PrivateMethodValidateable implements Validateable {
	
        private List objects
        
        private int getObjectsCount(){
                objects.size()
        }
}

new PrivateMethodValidateable().validate()
```

This will end with NullPointerException
```
java.lang.NullPointerException: Cannot invoke method size() on null object
at PrivateMethodValidateable.getObjectsCount(Script1.groovy:9)
```

This is caused by
```
Validateable.getConstraintsMap() {
    ...
    if(!Modifier.isStatic(method.modifiers) && !method.parameterTypes) {
    ...
}
```

Is this intended functionality? We believe that only methods with `public` scope should be configured as `nullable: false`. Maybe even more - only properties which have both getter and setter?

Such functionality may have performance impact on applications where get method is used to access database or do some calculations. It is very painful to upgrade to 3 because of this change.

The workaround could be to override 
```static boolean defaultNullable() {
        false
    }``` but this will affect domain classes and method is static

We could help with PR if such change is acceptable

**Comment by orubel** [comment]
I may be not seeing it but shouldn't objects be checked for null before checking size? I don't see you setting it nor a constructor so it looks like it is always going to be NULL whiuch is why it is throwing this error.

In which case, you should have a check:

if(objects){
   objects.size()
}

Otherwise this doesn't klook like an issue as far as I can tell

**Comment by droggo** [comment]
I agree, this should be checked. But this is only example which demonstrates the problem of private methods being called. As disribed later on - this may have big impact on migrated applications.

Still important question is if validate should call any getter method in class. If this is intended, we will try to workaround it in our apps.

**Comment by droggo** [comment]
Ok, I'm sure this is a bug. Two more samples:
```
import grails.validation.Validateable

class PrivateMethodValidateable implements Validateable {
	
        private String property
        private List list
        
        private Integer getListSize(){
                list?.size()
        }
}

PrivateMethodValidateable pmv = new PrivateMethodValidateable()
pmv.validate()
```
This will throw 
```
org.springframework.beans.NotReadablePropertyException: Invalid property 'listSize' of bean class [PrivateMethodValidateable]: Bean property 'listSize' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
at grails.validation.AbstractConstraint.getPropertyValue(AbstractConstraint.java:206)
at grails.validation.AbstractConstraint.rejectValueWithDefaultMessage(AbstractConstraint.java:182)
at grails.validation.AbstractConstraint.rejectValue(AbstractConstraint.java:129)
at grails.validation.AbstractConstraint.rejectValue(AbstractConstraint.java:125)
at grails.validation.AbstractVetoingConstraint.validateWithVetoing(AbstractVetoingConstraint.java:33)
at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:967)
at grails.validation.Validateable$Trait$Helper.validate(Validateable.groovy:141)
at grails.validation.Validateable$Trait$Helper.validate(Validateable.groovy:113)
at Script1.run(Script1.groovy:15)
```

Additionally private and protected properties are not `nullable: false` by default, because groovy will not define getter for them, it means that having a private/protected method should also not cause validation, at least not by default

**Comment by droggo** [comment]
I have created a PR to address this issue - https://github.com/grails/grails-core/pull/9515
- errors are initialized even when constraintsMap is empty - NPE not thrown from validate()
- moved `if()` which checks if method is a getter to separate method - isPropertyGetter() and added new condition that method must be public
- 4 new specs

having separated this method, it is also possible to customize behaviour in project, for example extending Validateable with other trait, making new conditions for method. Something like:
```
trait ValidateableProtected implements Validateable {
    static boolean isPropertyGetter(Method method){
        !Modifier.isStatic(method.modifiers) && (Modifier.isPublic(method.modifiers) || Modifier.isProtected(method.modifiers)) &&
        !method.parameterTypes && GrailsClassUtils.isGetter(method.name, method.parameterTypes)
    }
}
```
But if this is not needed or even not wanted, maybe this method should be made private?
If you consider this PR valid I will also update docs regarding Validation. Please let me know.

**Comment by jeffbrown** [comment]
Does this problem happen in 3.0.x?

**Comment by droggo** [comment]
Yes, I just tested it for 3.0.11 and there is the same problem. I have prepared a pull request to address those issues - #9515

**Comment by jeffbrown** [comment]
Thank you.

**Comment by graemerocher** [comment]
Thanks for the pull request
