### ISSUE TITLE
Grails 3.1.0 RC1 : 'grails install' task no longer works for local plugin installation

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9514]
Per documentation (http://grails.github.io/grails-doc/3.0.x/guide/plugins.html#creatingAndInstallingPlugins), when using/testing plugins locally, we use 'grails install' to install our plugins into a local maven instance (ie .m2). 

I was just told this task has been removed (???)

I have trouble understanding the task system since it obfuscates things a bit so can someone verify this? I currently can't seem to run this command.

**Comment by zyro23** [comment]
gradle/gradlew `publishToMavenLocal`?
https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by hakanernam** [comment]
Alarmed for a while,  local installation is very important.  Tested it with newly created plugin and for me install task works. I see "publishToMavenLocal" at the end. And plugin is in ~/.m2

```
$ grails install

...

:javadocJar
:sourcesJar
:publishMavenPublicationToMavenLocal
:publishToMavenLocal
:install

BUILD SUCCESSFUL

Total time: 16.22 secs

| Grails Version: 3.1.0.RC1
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_66
```

**Comment by orubel** [comment]
my environment must be hosed somehow. Good to know its me on this. :)

**Comment by orubel** [comment]
found the issue.

if you comment out these line in build.gradle:

// Used for publishing to central repository, remove if not needed
apply from:'https://raw.githubusercontent.com/grails/grails-profile-repository/master/profiles/plugin/templates/grailsCentralPublishing.gradle'
apply from:'https://raw.githubusercontent.com/grails/grails-profile-repository/master/profiles/plugin/templates/bintrayPublishing.gradle'

the local install stops working. this is KIND of a bug in that sense but *shrug* I dunno. Definitely shouldn't do that... heh. But its a judgement call.
