### ISSUE TITLE
src/main/java cannot find packages declared in src/main/groovy

### ISSUE THREAD

**Issue by donald-jackson** [grails/grails-core#9516]
Excuse me if this is a non-issue but I wasn't having this problem on Grails 2.5.3 and I'm finally attempting to start moving plugins across.

Please see project here https://github.com/donald-jackson/grails-jaxrs . This is the Jaxrs Grails plugin which I'm refactoring into Grails 3 style.

When compiling the project it is telling me it can't find the packages located in src/main/groovy.

	grails-jaxrs/src/main/java/org/jaxrs/ProviderArtefactHandler.java:25: error: package org.grails.jaxrs does not exist
	import org.grails.jaxrs.JaxrsClasses;
	                       ^
	grails-jaxrs/src/main/java/org/jaxrs/ResourceArtefactHandler.java:21: error: package org.grails.jaxrs does not exist
	import org.grails.jaxrs.JaxrsClasses;
	                       ^
	grails-jaxrs/src/main/java/org/jaxrs/provider/JSONReader.java:20: error: package org.grails.jaxrs.support does not exist
	import org.grails.jaxrs.support.ConverterUtils;
	                               ^
	grails-jaxrs/src/main/java/org/jaxrs/provider/JSONReader.java:34: error: package org.grails.jaxrs.support does not exist
	import static org.grails.jaxrs.support.ConverterUtils.getDefaultEncoding;

Listing below

	ls -l src/main/groovy/org/grails/jaxrs/JaxrsClasses.groovy 
	-rw-r--r--  1 donald  staff  3335 Dec 24 12:08 src/main/groovy/org/grails/jaxrs/JaxrsClasses.groovy

What do I need to do to fix this?

**Comment by burtbeckwith** [comment]
If you keep all of your Groovy and Java source together in src/main/groovy everything will resolve.

**Comment by donald-jackson** [comment]
Thanks @burtbeckwith , I have updated this (and a few other fixes) and it is now compiling and passing unit tests.

Not sure if this should stay open, seems like an issue to me (albeit a low priority one)

**Comment by orubel** [comment]
This is actually covered in documentation...

src/groovy	src/main/groovy	Moved for consistency with Gradle
src/java	src/main/groovy	Moved for consistency with Gradle

https://grails.github.io/grails-doc/3.0.x/guide/upgrading.html

**Comment by donald-jackson** [comment]
@orubel apologies, 100% my mistake. Thanks for the help.
