### ISSUE TITLE
Angular profile Failure on run-app

### ISSUE THREAD

**Issue by wschaef** [grails/grails-core#9517]
Grails Version 3.1 RC1
Just create new app with angular profile and start run-app:

        >mkdir angApp
	>cd angApp
	>grails
	grails> create-app myAngApp --profile angular --features hibernate
	| Application created at A:\01_projects\angApp
	| Initializing application. Please wait...

	BUILD SUCCESSFUL

	Total time: 4.532 secs
	grails> run-app
	| Running application...
	bower angular-resource#1.4.x    ENOGIT git is not installed or not in the PATH

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':bowerComponents'.
	> Process 'command 'cmd'' finished with non-zero exit value 1

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
	| Error Failed to start server (Use --stacktrace to see the full trace)
	grails>

**Comment by Schlogen** [comment]
You need to have git on the command line to resolve the client side dependencies

**Comment by wschaef** [comment]
Thanks for the hint! 
I think it can be still an issue in some entreprises, where it is not permitted to have either git client on the machines nor download software from it. The librararies are managed by Maven repositories and are controlled by governance teams by using something like Nexus.
Is there any option to avoid use of git?

**Comment by Schlogen** [comment]
@wschaef Sorry for the late response. Essentially if using git isn't an option then you can remove the `bower-gradle` plugin as a dependency. This will mean that you will have to download your third party assets manually.
