### ISSUE TITLE
grails console: No Session found for current thread.

### ISSUE THREAD

**Issue by hnicacio** [grails/grails-core#9522]
There are a lot of issues related to "org.hibernate.HibernateException: No Session found for current thread".

Any GORM "query" in grails console returns "org.hibernate.HibernateException: No Session found for current thread".

**Comment by orubel** [comment]
Are you using Spring Security Core or Grails 3.1 RC1 or Both?? Please specify some of your setup.

**Comment by hnicacio** [comment]
Sorry for the lack of information.

grails -version
> Grails Version: 3.0.10
> Groovy Version: 2.4.5
> JVM Version: 1.7.0_79
grails create-app consoledemo
cd consoledemo/
grails create-domain-class consoledemo.Democlass
grails console
> def x = consoledemo.Democlass.list()
returns: org.hibernate.HibernateException: No Session found for current thread

I will try on last week version 3.0.11, but this has been reported since 3.0.4 on web forums. I found it when googling a possible solution.

Best regards.

**Comment by fbresani** [comment]
try simply wrapping 
consoledemo.Democlass.withTransaction {
      def x = consoledemo.Democlass.list()
}

this is working with 3.0.9

**Comment by hnicacio** [comment]
Thanks a lot. That worked in 3.0.11 also.

Wish you all a great 2016.

**Comment by mikemil** [comment]
Ran into this too  - it should really be called out in the docs in Chapter 6.
