### ISSUE TITLE
[3.1.0.RC1] and [3.0.11] If config key has . (dot) in name, it is splitted to sub-key in Grails config

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9537]
Creating `grails-app/conf/application.groovy` file with option like:
```
file.meta=[
	'Resource.xls': [description: 'Resource file', path:'/home/grails/resources/Resource.xls']
]
```
or
```
file.meta.'Resource.xls'=[description: 'Resource file', path:'/home/grails/resources/Resource.xls']
```
should return value for `grailsApplication.config.file.meta.'Resource.xls'` but this option is empty. Instead there is a value for `grailsApplication.config.file.meta.Resource.xls`

This is how value of `grailsApplication.config.file.meta` is rendered to String:
`[Resource:[xls:[description:Resource file, path:/home/grails/resources/Resource.xls]]]`

Using Groovy's ConfigSlurper directly, creates correct ConfigObject, so it seems to be some additional handling of Grails. I was not able to locate it in `grails-core` code yet.

Values set in `application.yml` are loaded correctly. For example `value.with.dot: true` will have value for `grailsApplication.config.'value.with.dot: true'`

**Comment by jeffbrown** [comment]
Is this a duplicate of #634 and #647?

**Comment by droggo** [comment]
It seems to be the same as #634 because it happens for groovy files only, but those tasks are closed and issue is still there on newest releases

**Comment by droggo** [comment]
I think it was changed because of #9270 . Currently for config
```
file.meta=[
    'Resource.xls': [description: 'Resource file', path:'/home/grails/resources/Resource.xls']
]
```
`GroovyConfigPropertySourceLoader.load(...)` will return `NavigableMapPropertySource` with two properties:
```
file.meta.Resource.xls.description
file.meta.Resource.xls.path
```
Is this later merged with config and `Resource.xls` property is lost because of flat properties in NavigableMap?

**Comment by graemerocher** [comment]
There has been some discussion about this and the current thought is that this will not be fixed, since it introduces some ambiguity around the what is the value. For example what is the value of `Resource`? `null` or a map with the key `xls`? It also adds additional memory consumption and complexity to startup times which we are already trying to cut down on

**Comment by droggo** [comment]
Thank you for the explanation. Just for those who may need this, there is a simple workaround. Using external config, if you do something like
```
void setEnvironment(Environment environment) {
    def config = new ConfigSlurper().parse(EXTERNAL_CONFIG_PATH)
    environment.propertySources.addFirst(new MapPropertySource("externalGroovyConfig", config))
}
```
in your Application.groovy, config will be loaded in 'Groovy' way and both `file.meta.Resource.xls.description` and `file.meta.'Resource.xls'.description` will be available
