### ISSUE TITLE
Potential Problem With Forwarded Params

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9539]
```
class DemoController {

    def firstAction() {
        params.foo = 'bar'
        forward action: 'secondAction'
    }

    def secondAction() {
        render "Foo: ${params.foo}"
    }
}
```

```
$ curl http://localhost:8080/demo/firstAction
Foo: null
```

It appears as if `params.foo` is not surviving the forward.

**Comment by jeffbrown** [comment]
Tested with Grails 3.0.11.

**Comment by orubel** [comment]
This also effects 3.1 RC1

**Comment by jeffbrown** [comment]
This may be a simplified version of what was described at #9525.  I am not sure.

**Comment by orubel** [comment]
Actually I guess it should be said that this doesn't work in 3.1.0 RC1 either

**Comment by orubel** [comment]
has this been accepted as a bug yet??

**Comment by orubel** [comment]
Is this being looked into. Not having params come back is a complete blocker for me.

**Comment by orubel** [comment]
Graeme or Jeff, is it possible to get this into 3.0.12? Testing forwards with params is a bit critical right now.

**Comment by orubel** [comment]
Can someone please confirm this... please.

**Comment by orubel** [comment]
Ok so I looked into this and it looks like exposeRequestAttributes resend original params in RequestForwarder

WebUtils.exposeRequestAttributes(request, (Map)model);

It's binding model to request but it also resends original request params

Possible suggestion of:

WebUtils.exposeRequestAttributes(request, (Map)model);
WebUtils.exposeRequestAttributes(request, params);

either that or concatenating model and params prior.

**Comment by graemerocher** [comment]
I don't believe this is a bug, using `forward` without specifying the `params` argument will only forward the original request parameters as present in the URL, not those that are present when mutating the `params` object. To achieve this case you must to:

```
class DemoController {

    def firstAction() {
        forward action: 'secondAction', params:[foo:'bar']
    }

    def secondAction() {
        render "Foo: ${params.foo}"
    }
}```

**Comment by orubel** [comment]
Sorry. But in ticket https://github.com/grails/grails-core/issues/9523 we talked about an issue with sending params and how adding params to forward creates a DOUBLE send of params; the original set of params associated with the request and the params you sent with 'forward(uri:uri,params:params)'

We solved by leaving out params but then this only gves us the original params associated with the request.

We are still trying our best to avoid the double send of params while being in compliance and dont know what else we can do.

Need a way to send params with changes but not getting two sets of non-unique keys in the params.

**Comment by graemerocher** [comment]
rather than params you should be using request attributes to do what you want to achieve. Mutating params if a forward is not possible at the servlet container level

**Comment by orubel** [comment]
so how does one overwrite the params from one forward to the next? For example, I can add a increment value (request.setAttribute('inc',incValue)) but once set it will show in params (AFAIK)

I also need consistent way to update and doing everything through params so that incoming requests and responses had common variable to work with

do you have suggestion on handling params in consistent manner for updating and forwarding to avoid this?

**Comment by orubel** [comment]
I see. use setAttribute to modify the original params prior to forward. Gotcha. will try and see how that works. Thanks.

**Comment by orubel** [comment]
Sorry. referenced wrong ticket. Here is correct ticket for reference https://github.com/grails/grails-core/issues/9525

for double send params. Updated to show correct issue. Jeff was very helpful with this and opened this ticket. But we found sending forward with params causes params with double the keys. Should I open a econd issue for the double send params or can you just reference the material in the original ticket?

**Comment by graemerocher** [comment]
The behaviour is somewhat undefined here. A `forward` is supposed to forward all of the origin params so in some sense it makes sense that if you add another parameter with the same key you get 2 of that parameter. However there is no way with the way current servlets work to "override" a parameter, the originals are always retained on a forward.

**Comment by orubel** [comment]
One additional problem... with every forward, not only do param changes not overwrite original params but all SENT XML and JSON must get reparsed. This creates ALOT of overhead for forwards.

As a solution, I was parsing ONCE, saving into params and forwarding params.

We can do this through attributes but as previously stated, params creates a common way to associate all request/response data so with each forward, that data is available without having to do additional parsing.

This may be a bit of work for the future but I feel the benfits created from this can be very high.

**Comment by jeffbrown** [comment]
> One additional problem... with every forward, not only do param changes not overwrite original params but all SENT XML and JSON must get reparsed. This creates ALOT of overhead for forwards.

> As a solution, I was parsing ONCE, saving into params and forwarding params.

> We can do this through attributes but as previously stated, params creates a common way to associate all request/response data so with each forward, that data is available in the same dataset without having to do additional parsing.

> This may be a bit of work for the future but I feel the benfits created from this can be very high. Definitely something to look into if you feel up to it.

This is pretty far afield from the behavior I reported at the top of this issue.  If you would like to carry on a conversation about any of the behavior you are describing, please open that up as a discussion on the mailing list.

Thanks!

**Comment by orubel** [comment]
@jeffbrown No. Just wanted to leave as a comment. Not trying to argue. Just agreeing. Wanted to add notes for future consideration if others have similar issues. This relates in fact that forward sends original request params with each forward thus params modified params are lost rather than doing detect and replace. But as you often remind me, this isn't place for discussion... only want to avoid confusion or that you may think I am trying to argue again.

This was just a 'for future consideration' and my apologies if this showed up in your mail as an alert.

My apologies also if this seemed like being argumentative. Was trying to politely agree and add notes.

Email me if you have questions.
