### ISSUE TITLE
searchable 0.6.9 and database-migration 1.4.0 don't play nice together

### ISSUE THREAD

**Issue by jbrothman** [grails/grails-core#9542]
When I started running the dbm scripts to capture the database schema changes I had made, I ended up getting a stacktrace.  After researching and trying experiments for a few hours, I found that the searchable plugin might have some issues with hibernate.  So I removed searchable from the BuildConfig.groovy, and the dbm functions all worked correctly.  Attached is the stacktrace of the episode. The workaround is to remove searchable before any db version activities, and then re-enable it for development and production.

Here's the link that clued me in that searchable might be part of the problem: http://stackoverflow.com/questions/29517584/grails-schema-export-fails-with-nullpointerexception

Details:
Command: grails dev dbm-diff test
Grails: 2.4.4
Java: 1.8.0_31 (also failed on 1.6.45)
Database: Oracle 11.2.0.2.0
Platform: Windows 10

[searchable-stacktrace.txt](https://github.com/grails/grails-core/files/83124/searchable-stacktrace.txt)

**Comment by graemerocher** [comment]
Not a Grails bug, problem in the plugins

**Comment by jbrothman** [comment]
Yes, it's clearly in the plugins, but there's no good place to report errors for them.  I end up on a Jira page, and I don't have a login which would allow me to create an issue there.  If you could point me in the right direction, I would be happy to recreate the issue in the correct forum.

**Comment by burtbeckwith** [comment]
You should switch from the searchable plugin to something server-based like Elastic Search or Solr. I summarized the problems with searchable in my SO answer here: https://stackoverflow.com/questions/33314785/grails-3-0-5-with-searchable-plugin
