### ISSUE TITLE
Cannot use "org.springframework.test.annotation.Rollback" @Rollback annotation

### ISSUE THREAD

**Issue by salex772** [grails/grails-core#9549]
error is "Error:(13, 1) Groovyc: Annotation @org.springframework.test.annotation.Rollback is not allowed on element TYPE"

**Comment by burtbeckwith** [comment]
Did you mean to use `@grails.transaction.Rollback`? `@org.springframework.test.annotation.Rollback` is annotated with `@Target({ METHOD, ANNOTATION_TYPE })`, meaning it can only be applied to a method or to another annotation to create a meta-annotation.

**Comment by salex772** [comment]
Ok, thanks, But all I want it is use integration tests without transactions and use SetupSpec() and setup() to put initial data to database. But I get "session not found" error and thought this is because of "@Rollback" annotation. I do not need Rollback.

**Comment by salex772** [comment]
Hi guys, may be some advises? How to run integration tests outside transactions (I want manage transactions inside services), do SetupSpec() once before all tests, do Setup (with DB access) before each test and Rollback only once AFTER last test in a file. I tried spring annotation, but I always get some errors. Have you got a working example? It's too long from me to make setupData() method before each test and make roll back. Because of this I have to write all test logic inside one test method.
