### ISSUE TITLE
Grails 3 takes the GORM version from camel-spring-boot

### ISSUE THREAD

**Issue by squarepegsys** [grails/grails-core#9554]
If you add `camel-spring-boot` as a dependency to your Grails 3.0.x app, the `version` property on your newly-created Domain objects will have the version of `camel-spring-boot` not `0`

See my example: https://github.com/squarepegsys/grails3-camel-woes

**Comment by atreides322** [comment]
I suspect that when Gorm tries to autowire the domain properties in org.grails.plugins.web.controllers.api.ControllersDomainBindingApi#autowire, it is picking up org.apache.camel.component.properties.PropertiesComponent, presumably injected into the Spring context by camel, and setProperties() is being invoked with that object. There is a version field in the bean and it is trying to set the GORM version with that.

**Comment by squarepegsys** [comment]
(@atreides22 is my co-worker).

`grails.gorm.autowire=false` in the config appears to make everything work, however.
