### ISSUE TITLE
Grails 3.1.0.RC1: Controllers with namespace are also available without namespace in URL

### ISSUE THREAD

**Issue by dtamm** [grails/grails-core#9556]
OS: Windows 7
Grails Version: 3.1.0.RC1

Having this controller:

```
package kmi


class TestController {

    static namespace = "api"
    
    def index() {
        render "some text"
    }
}
```

with UrlMappings.groovy

```
class UrlMappings {

    static mappings = {
        "/$namespace/$controller/$action?"()
    }
}
```

This Controller is available with namespace in the url (/helloworld/api/test/index/) and without the namespace (/helloworld/test/index/). This condition was not given in (e.g.) grails 2.5.0.

**Comment by jeffbrown** [comment]
> This Controller is available with namespace in the url (/helloworld/api/test/index/) and without the namespace (/helloworld/test/index/). 

That is not the behavior that I am seeing.  See the project at https://github.com/jeffbrown/issue9556.  That contains the url mapping pasted directly from your description.  Are you seeing the behavior when you run that app?

Thanks for the feedback.

**Comment by dtamm** [comment]
Yeah you are right! Tested it with my application again, after i did some check of the files... and then i noticed, that i have two UrlMapping.groovy (one was in another package!). So i will close this issue.
