### ISSUE TITLE
multi-column unique constraint adds additional single-column constraint

### ISSUE THREAD

**Issue by oflege** [grails/grails-core#9567]
class User {
    static constraints = {
        login unique: 'client'
    }
    String login
    String client
}

used with grails 3.1.RC1 and hibernate5:5.0.0.RC3 generates a postgresql table with the following indexes:
    "user_pkey" PRIMARY KEY, btree (id)
    "uk_cl2k0ub07joy9vlkaywfp3q11" UNIQUE CONSTRAINT, btree (login)
    "unique_login" UNIQUE CONSTRAINT, btree (client, login)

uk_cl2k0ub07joy9vlkaywfp3q11 should not be created as it prevents the use of the same login for different clients.

**Comment by graemerocher** [comment]
Duplicates https://github.com/grails/grails-data-mapping/issues/617
