### ISSUE TITLE
Adding enum to domain class with `belongsTo` makes app fail to startup

### ISSUE THREAD

**Issue by sbglasius** [grails/grails-core#9570]
If you have two domain classes:

```
class Test {
    String title
    SomeEnum someEnum
    static hasMany = [relations: Relation]
    static constraints = {
    }
}
```

and 
```
class Relation {
    String name
    static belongsTo = [test: Test]
    static constraints = {
    }
}
```

and a defined `enum`:
```
enum SomeEnum {
    VAL1,
    VAL2
}
```
Then Grails 3.0.11 fails to start the app, until the `static belongsTo` is removed from `Relation`

Example app can be found here: 
https://github.com/sbglasius/enumproblem

**Comment by zyro23** [comment]
`Grails application running at http://localhost:8080 in environment: development`...
starting just fine (at least with `gradlew bootRun` b/c of no local 3.0.11 install..) - anything special to reproduce?

**Comment by jeffbrown** [comment]
`./gradlew run` and `grails run-app` each appear to work.  I am not seeing any errors on startup.

Can you paste the error message that you are seeing and also indicate how you are running the app?

**Comment by jeffbrown** [comment]
I have tried with JDK 7 and 8 on OS X.
