### ISSUE TITLE
Data bind with nested restrictions not working

### ISSUE THREAD

**Issue by volnei** [grails/grails-core#9575]
Consider the follow code

```
class Book {
  Author author
  String title
}
```

```
class Author {
  String name
}
```

```
Book book = new Book()
book['title', 'author.id'] = request
book.save(flush: true)
```

Now, if you post accidentally or intentionally the follow JSON data 

```
{
  title: "Book 1", 
  author: {
    id: 1,
    name: 'Volnei'
  }    
}
```
The author name will be updatated... I think this could be disastrous by enabling a kind of JSON injecting.

**Comment by graemerocher** [comment]
Using the dot to exclude keys like that has never worked. In fact 'author.id' matches nothing in your `book` instance since there is no property of that name. You can write what you want by just including `title` and binding the id separately

**Comment by volnei** [comment]
Yes, I know that this never worked, its a improvement proposal. And I agree that 'author.id' does not matches any in the book instance, but I see the JSON request more like an object graph, otherwise the bind for nested properties must not be done too.

**Comment by graemerocher** [comment]
I would be concerned about the performance impact as we don't currently split keys. To make this work as you want we would have to split all the keys that contain a dot in them for the purposes of data binding, which will have an overall impact on data binding performance. Maybe @jeffbrown can comment...

**Comment by volnei** [comment]
No problem, we can live with it. But it can become something boring.
