### ISSUE TITLE
Getting Started problem

### ISSUE THREAD

**Issue by pjmoy** [grails/grails-core#9577]
(I'm not sure if this is the place to ask, if it is not, please let me know.)

I am trying to run "package helloworld", and I get:

grails> package helloworld
| Error Caught exception Could not execute build using Gradle distribution 'http
s://services.gradle.org/distributions/gradle-2.3-bin.zip'.
Problem with provided build arguments: [-helloworld].
Unknown command-line option '-h'.
Either it is not a valid build option or it is not supported in the target Gradl
e version.
Not all of the Gradle command line options are supported build arguments.
Examples of supported build arguments: '--info', '-u', '-p'.
Examples of unsupported build options: '--daemon', '-?', '-v'.
Please find more information in the javadoc for the BuildLauncher class. (Use --
stacktrace to see the full trace)

Any help would be appreciated.
Cheers,
Peter

**Comment by bobbywarner** [comment]
@pjmoy Please ask usage questions on [Slack](http://slack-signup.grails.org/) or StackOverflow.

**Comment by pjmoy** [comment]
Hi Bobby. OK, I posted a question on Stackoverflow, but, thinking about a
solution/workaround makes me think this is more than a usage question. I'm
feeding "package helloworld" to grails, and something is telling me the "h"
in "helloworld" is being treated as an invalid option (?). I could try to
find a harmless option like, say "x", and enter " package xhelloworld", but
it still looks like a bug to me.

(
http://stackoverflow.com/questions/34889884/grails-getting-started-package-helloworld
)

Cheers,
Peter
