### ISSUE TITLE
[Feature] Manually Register a Domain Class

### ISSUE THREAD

**Issue by driverpt** [grails/grails-core#9578]
Possibility of manually registering a Domain Class.

Having a class in src/main/groovy/foo/bar/SomeDomainClass.groovy

And something like

```
grailsApplication.registerDomainClass SomeDomainClass
```

**Comment by graemerocher** [comment]
The issue with this is, that it isn't simple :)

Once you have registered the domain class the application needs to be refreshed to know about it, so the Hibernate session factory needs to be rebuilt, plugins need to be informed etc. It is essentially the same as introducing reloading at runtime in production, which is problematic.

**Comment by driverpt** [comment]
@graemerocher , I'm developing a plugin that has Default Classes in case the user does not want to customize them.
I have those domain Classes on src/main/groovy because i want them to be conditionally registered (There is no need in register the domain class if the user does not want to use it).
I try to manually implement DomainClass Trait, invoke `addArtefact()` method and it says in an Exception `Cannot add Domain class [class foo.bar.SomeDomainClass]. It is not a Domain!`

**Comment by graemerocher** [comment]
a better way to do that is to have the plugin depend on another plugin that contains the domain class, the user then has the option to exclude the plugin that contains the domain via build configuration

**Comment by driverpt** [comment]
@graemerocher , How can we exclude a domain class?

**Comment by graemerocher** [comment]
you cannot, you exclude the dependency that includes the domain class

**Comment by driverpt** [comment]
I believe that it would make all the sense to Dynamically register Domain Classes
