### ISSUE TITLE
GSP Tags adding blank line in HTML

### ISSUE THREAD

**Issue by sudhanshusirohia** [grails/grails-core#9580]
If I use any existing or custom gsp tags they are adding extra blank line in HTML.

For ex:

I've created this tag 
    def alternate = {attrs, body ->
        String output = ''
        if(attrs.url) {
            output = "<link rel='next' href='${attrs.url}'/>"
        }
        out << output
    }
when I use it and if url in attrs is empty, it would still add an extra blank line in HTML.

Same behaviour is with in-built GSP tags.

**Comment by yuvalk** [comment]
happens to me too with 3.2.1
:(

**Comment by jameskleeh** [comment]
Can you point me to an example of how this is causing a problem? I think the new line gets created because that is where the tag is.

```
...
<g:someTag />
...
```

If the tag returns an empty string, the line is still there because the tag exists on a new line

I did something like `<div></div><g:someTag />` and a new line is not created.

If you can tell me why the current behavior is problematic, I will look further into it

**Comment by yuvalk** [comment]
here's a simple example from our current code, this is in a <pre> ... </pre> part :
    BWO time              : ${dataSet?.bwoTime}</g:if><g:else>  Data set is not SMS-managed</g:else>
<g:if test="${dataSet?.dataSetOrganization == 'VSAM'}">
VSAM information for data set ${dataSet?.name}
  Extents<g:each var="i" in="${ (0..<dataSet.numberOfExtents) }"><g:set var="cur_extent" value="${dataSet.volumeExtents[i*40..i*40+39]}" />
Extent ${(i+1).toString().padLeft(3)}:   Start - End CCHH: ${cur_extent[4..11]} - ${cur_extent[12..19]} ${("(" + Long.parseLong(cur_extent[20..23], 16) + " tracks)").padRight(20)} ${("Start RBA: " + Long.parseLong(cur_extent[24..31], 16)).padRight(25)} End RBA: ${Long.parseLong(cur_extent[32..39], 16)}</g:each></g:if></g:else>

this is my 'workaround' for the issue, where I keep all the tags in one line and appended to the previous line, so the screen wont look messy, 
but I would very much rather have it on it's own and not causing a new lline

I will try with a <div> if that's solves it, even though a div is also a bit awkward

**Comment by jameskleeh** [comment]
Your comment isn't formatted correctly and I'm unable to determine what you're trying to convey

**Comment by yuvalk** [comment]
I've tried to make it a bit better.
anyhow, I feel the general problem is understandable from that
I can't format my tags to look like code as they create new lines which is visible in the html..

**Comment by jameskleeh** [comment]
Unfortunately I'm still not able to understand what you're trying to convey. Can you create an extremely simple example of what the GSP looks like then what the output is and why it is not correct?

**Comment by yuvalk** [comment]
`
<pre><code>
   bla bla bla
   <g:set var="just_example" value="of a tag creating a new line"/>
   a line that should appear right after the bla bla bla without a new line
</code></pre>
`

**Comment by jameskleeh** [comment]
Right so I don't think the tag is creating a new line. I think when you hit `<Enter>` after the last `bla`, you are creating the new line. I don't think it's reasonable to expect the tag to remove the new line you created simply because it didn't return anything.

**Comment by yuvalk** [comment]
there should be some means to format the code so it will be readable.
stacking a bunch of tags next to the previous line, just so they all won't create a new line is not reasonable IMHO.

**Comment by dlehammer** [comment]
@yuvalk perhaps [Grails Goodness: Generating Raw Output with Raw Codec](http://mrhaki.blogspot.com/2013/11/grails-goodness-generating-raw-output.html) can support you use-case.
This approach should provide full control over the generated HTML :)
