### ISSUE TITLE
3.0.12 Static resources from "src\main\resources\public" is not available (plugin resources also)

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#9581]
3.0.12 and 3.1.0.RC2:(

**Comment by graemerocher** [comment]
This is this change https://github.com/grails/grails-core/commit/0b649147cf7d230e10c595fd837aadfc42f73b31

The previous behaviour can be restored via configuration https://github.com/grails/grails-core/blob/3.0.x/grails-core/src/main/groovy/grails/config/Settings.groovy#L169

Let me know if you have any questions

**Comment by AlexKovynev** [comment]
Well, it's not obvious , perhaps somewhere in the documentation can be specified.

**Comment by graemerocher** [comment]
Agreed, we should have documented this

**Comment by graemerocher** [comment]
I added a note here https://github.com/grails/grails-core/releases/tag/v3.0.12
