### ISSUE TITLE
Regex for upper case does not work in URL contraint "matches:"

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [grails/grails-core#9586]
The following URL mapping in config/UrlMappings.groovy
```groovy
class UrlMappings
{
  static mappings = {

    name fromTo: "/$from/$to/$date?" {
      controller = "myController"
      action = "show"
      constraints {
        from(matches: "^\\p{javaUpperCase}.+")
        to(matches: "^\\p{javaUpperCase}.+")
        date(matches: "^[0-9.]+")
      }
    }
  }
}
```
will not match the following URL

```
/Århus/Hambburg/02.05.2018
```
BUT it should, because the letter Å is upper case! It seems to me that the contraint "matches" does not honor the regular expression \p{javaUpperCase} found at https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html

**Comment by graemerocher** [comment]
the matches constraint just uses `java.lang.String.match` so if there is a bug, it is in your code or in the Java regex processor, which we cannot fix
