### ISSUE TITLE
EnableResourceServer does not work with grails restful url mappings

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#9587]
Since there is no response on issue https://github.com/spring-projects/spring-security-oauth/issues/678 at spring-security-oauth, I post it here too.

The resource server's url mapping is

```
    static mappings = {
        "/tests"(resources: 'test')

        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(controller: 'application', action:'index')
        "500"(view: '/application/serverError')
        "404"(view: '/application/notFound')
    }
```

I can open '/test' with access token, but it reports not found error when access '/tests' or '/tests/1'. It works fine without @EnableResourceServer.

**Comment by graemerocher** [comment]
not a grails bug

**Comment by todoubaba** [comment]
@graemerocher Could you please give some hints on this?

**Comment by todoubaba** [comment]
Never mind, it is working now.
