### ISSUE TITLE
3.0.12: Ressources from src/main/webapp are not reachable (404)

### ISSUE THREAD

**Issue by linpete** [grails/grails-core#9588]
No static ressource from src/main/webapp are reachable since 3.0.12.
In 3.0.11 it was fine.

Tested with static html content

**Comment by bobbywarner** [comment]
Please review the release notes:
https://github.com/grails/grails-core/releases/tag/v3.0.12

**Comment by linpete** [comment]
Thx for th qick reply!
You are perfectly right /static/** is working perfectly.
Sorry for not reading the releasnotes propely ...
