### ISSUE TITLE
@NotTransactional annotation causes "Could not obtain current Hibernate Session" on 3.0.12

### ISSUE THREAD

**Issue by salex772** [grails/grails-core#9592]
According to documentation: 

"Grails also provides @Transactional and @NotTransactional annotations for cases where you need more fine-grained control over transactions at a per-method level or need to specify an alternative propagation level. For example, the @NotTransactional annotation can be used to mark a particular method to be skipped when a class is annotated with @Transactional."

but when I used  @NotTransactional on method and @Transactional on service class there is the error
"Could not obtain current Hibernate Session"

**Comment by graemerocher** [comment]
And where are you using the service from? Please upload an example application that reproduces the issue

**Comment by salex772** [comment]
From quartz job.

**Comment by graemerocher** [comment]
If the service is `NotTransactional`, then clearly no transaction will be created for that method. Without a transaction there is no hibernate session, so you would have to wrap the logic in the code necessary to bind a session (for example with `withNewSession`)

**Comment by salex772** [comment]
In my case service is TRANSACTIONAL, but method is @NotTransactional
