### ISSUE TITLE
The wrong controller is called when having two controllers with the same name

### ISSUE THREAD

**Issue by cawkarrr** [grails/grails-core#9594]
We have an app that has two controllers named "PageController".

One has a namespace:

```
package admin

class PageController {

    static namespace = 'admin'

    def index() {
        render 'admin.PageController'
    }
}
```

The other does not:

```
package frontend

class PageController {

    def index() {
        render 'frontend.PageController'
    }
}
```

The UrlMappings are configured as follows:

```
"/admin/pages/$code?" {
    namespace = 'admin'
    controller = 'page'
    action = 'index'
}
"/page/$code" {
    controller = 'page'
    action = 'index'
}
```

When calling "/page/test" it prints out "admin.PageController" instead of "frontend.PageController" hence the controller with the namespace is called although the URI is configured differently in the mappings.

This used to work before 3.0.12.

I created an app to demonstrate the problem. Oddly enough the correct string is printed out sometimes. So it might be an issue of initialization order?

If the correct string is printed stop the app, clean, restart and call http://localhost:8080/page/test again.

[controllerissue-bug-report-26012016.zip](https://github.com/grails/grails-core/files/104993/controllerissue-bug-report-26012016.zip)

**Comment by mhuebner** [comment]
Indeed, a downgrade to 3.0.11 solves this problem.
