### ISSUE TITLE
Unique constraint in domain class makes it not updateable if the value is not changed

### ISSUE THREAD

**Issue by Eylen** [grails/grails-core#9596]
I'm using Grails 3.0.12 and tested also with 3.0.9. 
DB: MongoDB

I have a domain class with a unique constraint in the url field. If I just update the name for example, the new value is not stored in the database although no error is raised. If I change the url and the name, both fields are updated.
Also, if the unique constraint in the url field is removed, everything works as expected

```groovy
@Entity
@ToString(includeNames = true, includeFields = true, excludes = 'dateCreated, lastUpdated, metaClass, levels, teams, behaviours, achievements, missions, campaigns, otherLanguages')
@EqualsAndHashCode(excludes='levels, teams, behaviours, achievements, missions, company, campaigns, defaultLanguage, otherLanguages')
class Site implements Serializable{
	static mapWith = "mongo"

	ObjectId id
	String privateKey
	String publicKey
	String name
	String description
	String url
	boolean coins = false
	
	List<Level> levels = []
	List<Team> teams = []
	List<Behaviour> behaviours = []
	List<AchievementBase> achievements = []
	List<Mission> missions = []
	
	Language defaultLanguage
	List<Language> otherLanguages = []
	
    static constraints = {
		privateKey nullable:false,blank:false,maxSize:250
		publicKey nullable:false, blank:false, maxSize:250
		name nullable:false,blank:false,maxSize:100
		description nullable:true, maxSize:255
		url nullable:false, blank:false, maxSize:250, url:true, unique:'company'
		defaultLanguage nullable:false, blank:false
    }
	
	static namedQueries = {
		filter {company, filter->
			eq 'company',company
			if (filter.name){
				ilike 'name',"%${filter.name}%"
			}
			if (filter.url){
				ilike 'url',"%${filter.url}%"
			}
		}
	}
	
	static mapping = {
		levels cascade:'delete'
		teams cascade:'delete'
		behaviours cascade:'delete'
		achievements cascade:'delete'
		missions cascade:'delete'
		
		sort 'name':'asc'
	}
	
	static belongsTo = [company:Company]
	static hasOne = [defaultLanguage: Language]
	static hasMany = [levels:Level, teams:Team, behaviours:Behaviour, achievements:AchievementBase, missions:Mission, otherLanguages:Language, campaigns: Campaign]
	static embedded = ['otherLanguages','defaultLanguage']

	
}
```

This is the relevant part of the service that makes the update

```groovy
public Site updateSite(String id, Long version, String name, String description, String url, boolean genPublicKey, boolean genPrivateKey, boolean coins, defaultLanguage, otherLanguagesKeys, otherLanguages, languagesToDelete)
		throws RollbackException, NotFoundException, AlreadyModifiedException{
			
		def site
		try{
			site = Site.get(id)
		}catch (RuntimeException e){
			throw new NotFoundException()
		}
		if (!site) {
			throw new NotFoundException()
		}

		if (version != null) {
			if (site.version > version) {
				throw new AlreadyModifiedException(site)
			}
		}
		
		site.name = name
		site.description = description
		site.url = url
		site.coins = coins

		if (genPublicKey)
			site.publicKey = UUID.randomUUID().toString()
		if (genPrivateKey)
			site.privateKey = UUID.randomUUID().toString()

		if (!site.save(flush: true)) {
			throw new RollbackException(site)
		}
		return site
	}
```

**Comment by graemerocher** [comment]
Could you please upload an example that reproduces the issue to github

**Comment by Eylen** [comment]
I have followed a bit the traces into gorm and I've seen that the property $changedProperties is null when trying to mark dirty the name if the url is left unchanged, but if I print the line site.org_grails_datastore_mapping_dirty_checking_DirtyCheckable__$changedProperties it has the values that have changed.
I've tried to follow where the DirtyCheckable is applied but I can't find it...

**Comment by Eylen** [comment]
Here is a small project showing that if you change the name of the site for example it isn't updated. If the url is changed alone or with other fields, then the update is done without problems.

https://github.com/Eylen/uniqueTest/tree/master/unique-test

I think that the problem is related with using mongodb as the datastore because it doesn't seem to happen with h2 database

**Comment by graemerocher** [comment]
@Eylen thanks will check it out! You can probably work around the problem by calling `markDirty()` on the object afterwards.

**Comment by Eylen** [comment]
Great! Thanks for taking a look at it @graemerocher 
I have tried using markDirty() in the site after making the changes and before invoking save but the result is the same. I think that the problem is related to $changedProperties being null when markDirty is invoked...

**Comment by graemerocher** [comment]
that is very strange, you will then have to call `obj.trackChanges()` after loading it. This should be done automatically by GORM but for some reason isn't

**Comment by Eylen** [comment]
It's really strange because I think that trackChanges() is indeed beign invoked but when markDirty is called it's null. Maybe it's beign invoked in the incorrect class or something?

**Comment by graemerocher** [comment]
I will investigate, thanks for the feedback
