### ISSUE TITLE
Enum not accessible in gsp views

### ISSUE THREAD

**Issue by gykpro** [grails/grails-core#9598]
I created an public enum when I was using 3.0.7, and worked fine(Sorry for the Chinese chars):

```
public enum OrderStatusEnum {
    WAIT_FOR_CONFIRM("待确认"),
    INSPECTOR_ASSIGNED("待付款"),
    WAIT_FOR_SERVICE("待检测"),  
    ORDER_CLOSED("已关闭"),       	
    COMPLETED("已完成")          	

    public final String displayName
    OrderStatusEnum(String _displayName){
    	this.displayName = _displayName
    }

    String toString() { displayName } 
    String getKey() { name() }
}
```

and in gsp view: 

```
<g:if test="${!(inspectOrder.status == OrderStatusEnum.COMPLETED)}">
     <button></button>
</g:if>
```

When I tried to switch to 3.0.11, it throws error:

> Message
> Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: Cannot get property 'COMPLETED' on null object
> Caused by
> Cannot get property 'COMPLETED' on null object

If I change the gsp code to below, it works:
```
<g:if test="${!(inspectOrder.status == com.mypackagename.OrderStatusEnum.COMPLETED)}">
     <button></button>
</g:if>
```

Since it worked in 3.0.7 but fails in 3.0.11 and 3.0.12, it's a bug or a feature?

**Comment by graemerocher** [comment]
enums require an import, always. I'm not sure why it worked for you before.

**Comment by gykpro** [comment]
So pardon me if I'm being silly, and I'd like to ask: if I have some enums in a same package, I don't need to import them in controller, in the mean time I should use <% page import%> to import them in corresponding gsp view, is that right?
