### ISSUE TITLE
New Feature: Support validate method with ad-hoc constraints

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9599]
I want a `validate` method which can be applied a ad-hoc constraints closure as follows:

```
person.validate {
    name maxSize: 10
    age max: 60
}
```

It's very handy for a domain or a command object which is used for some request variations.

I've implemented the prototypes, a trait version and a patch of grails-core.

* A trait named `AdHocValidateable`:
    * https://github.com/nobeans/grails-adhoc-validateable/blob/master/src/main/groovy/grails/validation/AdHocValidateable.groovy
* A patch of grails-core's `Validateable`:
    * https://github.com/nobeans/grails-core/commit/4b615c5b0355aad693572b0911c7888cab93e50c

This is a test of `AdHocValidateable`, which expresses the my expected use-cases well.

* https://github.com/nobeans/grails-adhoc-validateable/blob/master/src/test/groovy/grails/validation/AdHocValidateableSpec.groovy

Are you interested in this feature and the patch? The patch doesn't have a test, yet. But if you have a interest, I'll try it. Or, I had better provide the `AdHocValidateable` as my third-party plugin?

**Comment by graemerocher** [comment]
Seems a nice feature to add to Grails 3.2, pull requests welcome, as for the implementation, I would only be concerned about the cloning that is happening. Since this will be very expensive, performance may be an issue. It may be that a immutable parent map and a mutable child / overriding map would be a better model for this.

**Comment by rpalcolea** [comment]
:+1: for this

**Comment by nobeans** [comment]
@graemerocher, Thank you for your comment. I'll try it.

>  It may be that a immutable parent map and a mutable child

It seems nice, but I'm afraid that there might be people using the current MUTABLE parent map to hack their validation logic or something. So I would keep the MUTABLE parent map and try to do something only in the child-side if possible.

**Comment by nobeans** [comment]
Sent PR https://github.com/grails/grails-core/pull/9605.

Please review it!

**Comment by snimavat** [comment]
+ 1 for this

**Comment by graemerocher** [comment]
@nobeans Looks good, please just sign the CLA before we merge https://www.clahub.com/agreements/grails/grails-core

**Comment by nobeans** [comment]
@graemerocher Signed to the CLA.

**Comment by graemerocher** [comment]
Believe this was merged into the 3.1.x line
