### ISSUE TITLE
Update Spring Boot to latest version

### ISSUE THREAD

**Issue by smartiniOnGitHub** [grails/grails-core#9601]
Hi all,
would it be possible to have Grails-3.1.x updated to latest Spring Boot 1.3.x release (currently 1.3.2), as seen [here](http://spring.io/blog/2016/01/22/spring-boot-1-3-2-released) ?
But attention to its new behavior of messages*.properties .

And maybe Grails-3.2.x to Spring Boot 1.4.x (currently snapshot) to start playing with it ?

Thanks. Bye

**Comment by graemerocher** [comment]
too late for 3.1 GA, but maybe in 3.1.1

**Comment by smartiniOnGitHub** [comment]
ok, thank you the same for now.
