### ISSUE TITLE
[urlmapping][grails 3.0.10] Regular Expression patterning matching for optional characters at end of string not working

### ISSUE THREAD

**Issue by sudhanshusirohia** [grails/grails-core#9606]
Grails 3.0.10
Url1: http://www.example.com/a-spid-F22794226
Url2: http://www.example.com/a-spid-F22794226-r2

"/*-spid-$PROP_ID($arbitrarystring)?" {
            namespace = "pd"
            controller = "Desktop"
            action = "show"
            constraints {
                PROP_ID (matches: /[A-Za-z][0-9]{6,9}/)
            }
        }

Url1 is successfully matching to this mapping but url2 not.

**Comment by graemerocher** [comment]
the matches constraint just uses `String.match` so if there is a bug, it is in your code

**Comment by sudhanshusirohia** [comment]
Not sure, what I am missing here but after further debugging found that mappedURI string is "/*-spid-(*)(*)?"  in DefaultUrlMappingEvaluator.java line 396 in _invoke method.

I believe it should be "/*-spid-[A-Za-z][0-9]{6,9}(*)?" as I've applied PROP_ID constraint.
