### ISSUE TITLE
Grails 3.1.0 problem with BigDecimal and german Locale 

### ISSUE THREAD

**Issue by rdmueller** [grails/grails-core#9612]
Since I can't reopen Issue #9283, I had to create a new one...

Issue #9283 had been fixed, but it seems that the working code has been reverted back. As a result, Grails 3.1.0 still contains this important issue...

thanx for your efforts...

**Comment by graemerocher** [comment]
Since the change was to the fields plugin and not to Grails itself, it is just a matter of updating to the latest fields plugin

**Comment by rdmueller** [comment]
>  it is just a matter of updating to the latest fields plugin

So, you are saying if I switch to "2.1.2-SNAPSHOT" it could be working again? I'll give it a try...

**Comment by graemerocher** [comment]
The problem also impacts Grails 3.0.13

**Comment by rdmueller** [comment]
just noticed that this problem shows up again in 3.1.16

Will now verify that it is still in the latest 3.1.19
