### ISSUE TITLE
3.1.0: newly created apps have 3.1.0.BUILD-SNAPSHOT profile dependency

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-core#9614]
Generated `build.gradle` after `create-app` contains a dependency like:

```groovy  
profile "org.grails.profiles:angular:3.1.0.BUILD-SNAPSHOT"
```

It should be created using the variable `grailsVersion` already available in the build, eg:

```groovy  
profile "org.grails.profiles:angular:$grailsVersion"
```

**Comment by graemerocher** [comment]
I can't recreate this personally. Try do `rm -rf ~/.m2/repository/org/grails/profiles` It may be you have some snapshots versions lying around.

**Comment by alvarosanchez** [comment]
You are right :)
