### ISSUE TITLE
Grails 3.0.12: interceptor with uri matcher does not intercept actuator endpoints

### ISSUE THREAD

**Issue by KevinSchuck** [grails/grails-core#9622]
When attempting to apply a Grails interceptor with a URI matcher to the management endpoints provided by Spring Boot Actuator I've noticed that those requests are not being intercepted.

I have the `management.context_path` property set to `/admin` but the URI matcher '/**' does not match `/admin/env`. It does however match any mapping that I have defined in` UrlMappings.groovy`

## Setup

In application.yml:
```
management:
  context_path: /admin
```

Here is my interceptor:
```groovy
class LoginInterceptor {

    def securityService

    int order = HIGHEST_PRECEDENCE

    LoginInterceptor() {
        match(uri: "/**")
    }

    boolean before() {
        if (!request.exception) {
            securityService.authenticateUser()
        }
        true
    }

    boolean after() { true }

    void afterView() { /* no-op */ }
}
```

How do I go about creating a Grails 3 interceptor that intercepts all URI's regardless of how the routes are defined?

Please see [this](http://stackoverflow.com/questions/35144544/how-to-apply-grails-3-interceptors-to-spring-boot-actuator-endpoints) StackOverflow post for additional information.

**Comment by graemerocher** [comment]
The solution you found at http://stackoverflow.com/questions/35144544/how-to-apply-grails-3-interceptors-to-spring-boot-actuator-endpoints is actually the correct one

I am interested to know why it doesn't work for Spring Cloud endpoints? Grails core doesn't currently depend directly on Spring Actuator so adding this as a direct dependency is not ideal.

**Comment by KevinSchuck** [comment]
The solution in the post will only work with Spring Boot Actuator endpoints since the `EndpointHandlerMappingCustomizer ` is part of that project. 

The crux of the issue here is that I would expect the Grails 3 interceptor with a URI matcher to match any URI even if it isn't defined in `UrlMappings.groovy`. I would assume this should work just like a `OncePerRequestFilter` where I can inspect `request.getRequestURI()` and filter when the pattern matches `"/**"`.

In the example I gave above, my security model is essentially broken since it doesn't intercept all requests to `"/**", just those defined in `UrlMappings.groovy`.

**Comment by graemerocher** [comment]
Spring Cloud must produce another HandlerMapping then, there may be a way to association all HandlerMapping instances with the interceptors, I will see what I can do.
