### ISSUE TITLE
Rendering JSON using render(contentType: 'application/json') gives {} in http response

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#9628]
Upgrading to Grails 3.1.0, controllers rendering JSON using this code:
```
render(contentType: 'application/json') {
   [someContent: 'test']
}
```
stopped working. Now it renders:
```
{}
```

**Comment by graemerocher** [comment]
See the upgrade guide http://grails.github.io/grails-doc/latest/guide/upgrading.html#upgrading3x

More specifically the section on "JSON Builder Groovy Alignment"

**Comment by kuceram** [comment]
I see, thanks...

> btw. relevant link to the documentation is this http://grails.github.io/grails-doc/3.1.0.RC2/guide/upgrading.html#
