### ISSUE TITLE
Grails 3.0.11 -  RestfulController actions are not avaliable when inheriting

### ISSUE THREAD

**Issue by AleksanderGrzybowski** [grails/grails-core#9629]
Hello. Documentation says:
If a controller class extends some other class which is not defined under the grails-app/controllers/ directory, methods inherited from that class are not converted to controller actions. If the intent is to expose those inherited methods as controller actions the methods may be overridden in the subclass and the subclass method may invoke the method in the super class.

My problem is that I don't know how extending RestfulController is supposed to work then - all its methods (index, save etc) are not accessible as actions.

My UrlMappings is 
```
        "/books"(resources: 'book')
```

And my sample controller is
```
class BookController extends RestfulController<Book> {

    BookController() {
        super(Book)
    }

//    @Override
//    def index(Integer max) {
//        render text: 'overriden index'
//    }
}
```

Now if I uncomment this overriden method and make GET request to :8080/books it executes my overriding method, but otherwise it returns 500. Documentation assumes that it would execute RestfulController#index but for me it doesn't.

**Comment by graemerocher** [comment]
Upload an example that reproduces the issue

**Comment by AleksanderGrzybowski** [comment]
Sorry, I am stupid :) I was using httpie for testing, and by default it sends `Accept: */*` that results in Grails content negotiation mechanisms trying to find gsp template for 'index', which of course does not exist. If I force `Accept: application/json` then it works. Thanks anyway :)
