### ISSUE TITLE
Grails3.1 build fails with rest-api profile

### ISSUE THREAD

**Issue by kktec** [grails/grails-core#9631]
With an unmodified grails3.1 app created with --profile rest-api, the build fails whether I call it via:

- gradlew build
- grails war

It fails during the **compileGsonViews** task:

```
Invalid arguments: [C:\workspace-grails3\abc_rest\grails-app\views,C:\workspace-grails3\abc_rest\build\gson-classes\main,1.8,abc_rest,C:\workspace-grails3\abc_rest\grails-app\conf\application.yml,UTF-8]

Usage: java -cp CLASSPATH grails.plugin.json.view.JsonViewCompiler [srcDir] [destDir] [targetCompatibility] [packageImports] [packageName] [configFile] [encoding]

```

Those commands both work when creating a 3.1 app without any profile designation.

**Comment by graemerocher** [comment]
Hmm looks like a Windows specific issue. Gotta love Windows

**Comment by kktec** [comment]
That figures. I always did hate the way Java specifies classpath on the CLI differently for Windows than for *NIX.

**Comment by ehsgoca** [comment]
Is there any known workaround for this issue?
As far as I understand it the parameter "packageImports" is lost when passing it to the "grails.plugin.json.view.JsonViewCompiler". Has that anything to do how Windows treats quoted whitespace on the command line?

**Comment by graemerocher** [comment]
Will look into it for 3.1.2... thanks

**Comment by kktec** [comment]
This seems to only be a problem when using rest-api profile to build an executable jar. When I add the Gradle 'war' plugin, assemble works fine, even on Windows. ;=)

**Comment by johngamarra** [comment]
@kktec Hi, could you please tell me how did you add the grails war plugin, I need to generate a war with this profile, thanks

**Comment by graemerocher** [comment]
Probably relates to #9710

**Comment by kktec** [comment]
@johngamarra
Simply apply the GRADLE war plugin and use the Gradle assemble task to generate the war. The problem I had was that without the Gradle war plugin, assemble was generating an executable jar rather than a war when used in the context of the rest-api profile.

**Comment by cavemansspa** [comment]
Was this resolved in 3.1.2? 

I tried this with 3.1.2 on a new vanilla --profile=rest-api project and `grails assemble` and `gradlew assemble` are still failing at the `compileGsonViews` task with Invalid command...

Looks like the 3.1.2 build.gradle file has the apply "war" by default:
```
...
version "0.1"
group "testrestapi"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"war"
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.plugins.views-json"
...
```

**Comment by ehsgoca** [comment]
I am also still experiencing the same problem with Grails 3.1.2 on Windows.
It seems like the parameters for "packageImports" and "packageName" are not passed to the "compileGsonViews" task.

I am attaching a log file from my vanilla test project (named "GoCaTest312").
[Grails-3.1.2-problem.txt](https://github.com/grails/grails-core/files/154716/Grails-3.1.2-problem.txt)

**Comment by graemerocher** [comment]
The fix for this was this one https://github.com/grails/grails-views/commit/a8e211f99fbf22f7f535b97e7b5890853cf33411

The change was made so it defaulted to `project.name` for the package imports if none were specified. This seem to resolve the issue for me on Windows, but it seems like the issue is still present for some.

**Comment by cavemansspa** [comment]
A `grails assemble` on a regular `grails create-app` (i.e. without the --profile=rest-api) works fine.

Are the profiles that different in how they're built?  I would think they process is very similar, what would make the --profile=rest-api task compileGsonViews problematic?

**Comment by graemerocher** [comment]
the profiles are different in that the REST profile includes JSON views, and what is failing is the task that compiles those views. In addition, it is failing only on Windows

**Comment by graemerocher** [comment]
This is probably a problem in the profile. Please replace the line

```
classpath "org.grails.plugins:views-gradle:1.0.1"
```

With

```
classpath "org.grails.plugins:views-gradle:1.0.3"
```

In your `build.gradle` file

**Comment by cavemansspa** [comment]
That did the trick.  Thank you!

```
$ grails assemble

BUILD SUCCESSFUL

Total time: 5.686 secs
:compileJava UP-TO-DATE
:compileGroovy
:findMainClass
:buildProperties
:processResources
:classes
:compileGsonViews
:war
:bootRepackage
:assemble

BUILD SUCCESSFUL

Total time: 23.75 secs
|Built application to build\libs using environment: production
```
