### ISSUE TITLE
[3.0.12] Runnable jar file does not execute BootStrap.groovy

### ISSUE THREAD

**Issue by sofiaguyang** [grails/grails-core#9633]
I created runnable archives using `grails package`. I noticed when I ran `java -Dgrails.env=prod -jar build/libs/mywar-0.1.jar` command that BootStrap.groovy was not getting executed. However, BootStrap.groovy would get executed when running the app via war file `java -Dgrails.env=prod -jar build/libs/mywar-0.1.war`.

**Comment by graemerocher** [comment]
Duplicates #9582
