### ISSUE TITLE
[Grails 2.4.5] URL matching is incorrect

### ISSUE THREAD

**Issue by vsorokin** [grails/grails-core#9634]
Assume we have following URL mapping:
```groovy
"/ccyPair"(resources: "ccyPair", includes: ['index', 'show'])
"/ccy"(resources: "ccy", includes: ['index'])
```
When `GET` request on URL `/common/ccyPair` happens, instead of going to `CcyPairController.index()`, Grails goes to `CcyController.index()` with `params = [format: 'Pair']`.

This is the log:
```
DEBUG mapping.DefaultUrlMappingsHolder  - Attempting to match URI [/common/ccyPair] with pattern [/common/ccy(.(*))?]
DEBUG mapping.DefaultUrlMappingsHolder  - Matched URI [/common/ccyPair] with pattern [/common/ccy(.(*))?], adding to posibilities
```

Looks like pattern `/common/ccy(.(*))?` should not match url `/common/ccyPair`, but it does.
The reason is that internally, pattern `/common/ccy(.(*))?` is converted to this java regexp: `'^/common/ccy\.?([^/]+)??/??$`, which, obviously, *does match* `/common/ccyPair`. (See `org.codehaus.groovy.grails.web.mapping.RegexUrlMapping`)

**Comment by graemerocher** [comment]
2.5.x is in maintenance mode

**Comment by Luxor** [comment]
I guess, If the team did not rewrite UrlMatching, the issue is applicable to all grails versions
