### ISSUE TITLE
GORM: Add support for Automatic timestamping for java.time.Instant

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#9635]
Having domain class:
```
class MyClass {
   java.time.Instant dateCreated
   java.time.Instant lastUpdated
}
```
fails when starting the app with following:
`groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.time.Instant(java.lang.Long)`

**Comment by graemerocher** [comment]
@jameskleeh this solved now?

**Comment by jameskleeh** [comment]
@graemerocher Yes, in GORM 6.0.1 https://github.com/grails/grails-data-mapping/commit/9fe8822f2d7f63925875a1863a6508386f08d76e
