### ISSUE TITLE
schema-export fails with dbCreate = validate

### ISSUE THREAD

**Issue by mkrasuski** [grails/grails-core#9642]
schema-export fails if dbCreate is set to 'validate' and there are some domain classes changes. For example we cannot generate new table definition having 'validate' in dataSource - generate-schema fails on schema validation.

**Comment by droggo** [comment]
`schema-export` now executes bootstrap and 'starts' application. The easiest way around is to create dedicated environment for export, with empty `dbCreate` and flag in bootstrap to skip execution

**Comment by mkrasuski** [comment]
Good point @droggo, and useful workaround but it could do with something more elegant.

**Comment by jeffbrown** [comment]
@droggo 

> The easiest way around is to create dedicated environment for export, with empty dbCreate and flag in bootstrap to skip execution

What is it that you are proposing be done conditionally in `BootStrap`?  Thanks for clarifying.

**Comment by droggo** [comment]
@jeffbrown unfortunatelly yes. Example code snippet:
```
def init = { servletContext ->
    if(Environment.getCurrent().name == 'schemaExport'){
        log.info 'Bootstrap will not be executed for schemaExport environment'
        return
    }
    ...
}
```
and additionally dedicated datasource configuration in `application.yml`:
```
environments:
    schemaExport:
        dataSource:
            username: user
            password: password
            ...
```

Even worse - if you have custom plugins which do something in their Bootstrap, we also had to use similar conditions there.

**Comment by jeffbrown** [comment]
@droggo I think I may have misunderstood the original report.  I didn't realize @mkrasuski  had logic in his own `BootStrap` that was causing the problem.

**Comment by droggo** [comment]
I think he doesn't. His problem is that database gets started with `validate` option for `schema-export` command and fails validation. I think for Grails 2 both database dbCreate and Bootstrap were not executed for this Grails command.

**Comment by mkrasuski** [comment]
No, I hadn't... The only thing I stated is that if someone wants to prevent db schema to be accidently modified by the app with `dbCreate = validate` and wants just manually make db changes  by generated scripts is in the trap. Of course Bootstrap code is natural problem that arises when application starts, but who says that grails as a tool must start application on schema export... Potentially everything what is needed to export schema is proper domain classes definition, not the starting app.

**Comment by jeffbrown** [comment]
@droggo 

> I think he doesn't have logic in Bootstrap or not this is causing issue.

So how does using his own environment and having conditional logic in `BootStrap` help?

**Comment by jeffbrown** [comment]
I think this problem is still going to occur, even if he does that. Am I confused about what is being suggested?

**Comment by droggo** [comment]
You can define custom datasource with `dbCreate: none` used only for `schema-export`. Then database is not validated and shema is correctly generated. If nothing is done in Bootstrap, this should be enough.

**Comment by jeffbrown** [comment]
> If nothing is done in Bootstrap, this should be enough.

@droggo Right.  I don't think the `BootStrap` stuff is relevant.

Thanks for the clarification.

**Comment by graemerocher** [comment]
I'm confused by what is the proposed solution / improvement for this issue.

**Comment by droggo** [comment]
I think https://github.com/grails/grails-core/pull/10042 is solution for this

**Comment by graemerocher** [comment]
Ok closing for 3.1.x then
