### ISSUE TITLE
Grails 3.1 Envrionments in plugin.yml not loaded

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9643]
Configuration in a plugin.yml inside of an environments key are not included as a part of the application config.

**Comment by ctoestreich** [comment]
This should have been addressed with tests in https://github.com/grails/grails-core/pull/9491

Can you like a sample project?

**Comment by Schlogen** [comment]
In your tests you are testing `YamlPropertySourceLoader`, not the usage of by `AbstractGrailsPlugin`. One difference I see is that `parseFlatKeys` is true in your tests and false in `AbstractGrailsPlugin`.

**Comment by Schlogen** [comment]
Looks like it was changed here https://github.com/Schlogen/grails-core/commit/50cf2449787809d8779d2a7b5c5dba9b7173046a#diff-617ddae95c124d2b1164caff18242aa1

**Comment by Schlogen** [comment]
@graemerocher The PR @ctoestreich submitted should have targeted 3.0.x. He should submit that PR against 3.0.x and then the merging will take care of the issue for future versions.

**Comment by ctoestreich** [comment]
https://github.com/grails/grails-core/pull/9645
