### ISSUE TITLE
Grails 3.1 with application.groovy renders pages incorrectly as war in Tomcat

### ISSUE THREAD

**Issue by hbogaards** [grails/grails-core#9647]
When I create a new Grails 3.1 application and translate the default application.yml to application.groovy and build a war which I deploy into Tomcat 8, the application renders it pages incorrectly (without all references to the JavaScript and CCS files).

See [Stackoverflow](http://stackoverflow.com/questions/35205044/grails3-with-application-groovy-shows-mangled-pages-in-tomcat) for a screenshot and more information.

Steps to reproduce:

- Unpack a Tomcat 8.0.30 and remove all default applications from webapps (to make sure they don't interfere)
- `grails create-app empty31`
- `cd empty31`
- Replace the default `application.yml` with a direct translation to groovy as `application.groovy`
- `grails war`
- `copy build\libs\empty31-0.1.war <tomcat-dir>\webapps\ROOT.war`
- Start Tomcat
- Browse to `http://localhost:8080/`

This shows a mostly white page, with the 'Welcome to Grails' in default 'Times New Roman' halfway down the page (beneath the invisible grails.svg).
If you look at the page source, all references to JavaScript and CSS are missing and the whole page is a very simplified version of the normal page

**Comment by burtbeckwith** [comment]
I looked at this briefly and saw the same thing. For some reason the equivalent config in Groovy format is causing the layout to not be applied.

**Comment by hbogaards** [comment]
What makes it so strange for me is that ‘grails run-app‘ works correctly with the same ‘application.groovy‘

**Comment by droggo** [comment]
@hbogaards a workaround should be to use original `application.yml` and `application.groovy` for custom config like `joda` you need. Both files can be used at once

**Comment by donald-jackson** [comment]
sorry @jeffbrown must have missed this - yep looks exactly the same. Also happening on Grails 3.0.x
