### ISSUE TITLE
groovy-test jar file is missing since 3.0.12

### ISSUE THREAD

**Issue by jt214** [grails/grails-core#9652]
I tried to update from 3.0.11 to 3.0.14 today, and found that tests won't execute now because the groovy-test-2.4.5.jar file is no longer part of the distribution.

Is there something I need to do differently...?   Or is this a mistake and the jar should still be there...?

**Comment by jt214** [comment]
unable to resolve class groovy.mock.interceptor.MockFor
 @ line 34, column 1.
   import groovy.mock.interceptor.MockFor
   ^

1 error

**Comment by jeffbrown** [comment]
Do you have a dependency in `build.gradle` like `testCompile 'org.grails:grails-plugin-testing'`?

**Comment by jt214** [comment]
Yes:

  testCompile "org.grails:grails-plugin-testing"

exists in build.gradle.

Everything is working fine with grails 3.0.11.   All I did was change the version number in my gradle.properties file.

Then, I downloaded the 3.0.14 distribution and noticed the difference from the 3.0.11 distribution.

**Comment by jeffbrown** [comment]
@jt214 If you can provide a sample project which demonstrates the problem, it will be easy to track down.

**Comment by jt214** [comment]
It's real easy.    Just create a new plugin and then try to use the following test:

package test;

import spock.lang.Specification
import groovy.mock.interceptor.MockFor

class MockForErrorSpec extends Specification {
}

**Comment by jeffbrown** [comment]
> It's real easy. Just create a new plugin and then try to use the following test

I didn't realize it was a plugin.  We may have a dependency problem there.  Will investigate.  Thanks for the feedback.

**Comment by jt214** [comment]
Ah, cool.   Thanks for looking into it.

**Comment by jeffbrown** [comment]
> Thanks for looking into it.

No problem.  I am not sure what changed in the dependency graph but for now you can make the problem go away by expressing `testCompile 'org.codehaus.groovy:groovy-test:2.4.5'` in `build.gradle`.

**Comment by graemerocher** [comment]
`groovy-test` mainly contains classes an utilities that are deprecated or for JUnit 3. Spock's mocking capabilities are superior to what Groovy's `MockFor` offers so there is no reason to use them. Unless there is some huge demand I'm not sure we will be adding `groovy-test` back as a dependency and declaring the dependency as above is a fine solution.
