### ISSUE TITLE
Grails 2.4.4 / 3.0.14 Command Object Intermittent Issue with nullable:true constraint not working

### ISSUE THREAD

**Issue by mitchmckenzie** [grails/grails-core#9655]
The issue is intermittent and I am unable to reproduce the problem locally. I am filling a  bug in case others are experiencing the same issue. 
**This issue was also reported by olavgg on Grails 3.0.14 : https://grails.slack.com/archives/questions/p1454960719001824  

**Facts**
1. The form that submits data to the controller using the command object below posts a json payload that will only include the fields that have values. (e.g. if address 2 is blank there will be no address 2 in the payload and thus should be null in the command object)
2. We have seen this issue once in a test environment and once in our production environment.
3. I was able to inspect the command object during a debug session in our test environment (while the issue was happening) and I can see the validation errors being returned despite the property values being null.  The nullable : true is completely ignored.
4. I inspected the byte code for the command object contained in the war file deployed on our test environment and the byte code does contain the nullable : true constraints.
5. A Tomcat restart does resolve the issue.

**Controller Method Using Command Object**

```
def save( CreateInsuredCommand cmd ) {
        if ( cmd.hasErrors() ) {
            respond cmd; return
        }
                 .... 
    }
```

**Command Object**

```
@Validateable
class CreateInsuredCommand {

    String dba
    String phone
    String email
    String physicalAddress1
    String physicalAddress2
    String physicalCity
    String physicalState
    String physicalZip


    @BindUsing ( { CreateInsuredCommand cmd, source -> cmd.physicalAddress1 = source[ 'address1' ] } )
    String address1

    @BindUsing ( { CreateInsuredCommand cmd, source -> cmd.physicalAddress2 = source[ 'address2' ] } )
    String address2

    @BindUsing ( { CreateInsuredCommand cmd, source -> cmd.physicalCity = source[ 'city' ] } )
    String city

    @BindUsing ( { CreateInsuredCommand cmd, source -> cmd.physicalState = source[ 'state' ] } )
    String state

    @BindUsing ( { CreateInsuredCommand cmd, source -> cmd.physicalZip = source[ 'zip' ] } )
    String zip

    static constraints = {
        address1 blank: false
        physicalAddress1 blank: false
        zip blank: false
        physicalZip blank: false
        city blank: false
        physicalCity blank: false
        state blank: false
        physicalState blank: false
        dba nullable: true
        address2 nullable: true
        physicalAddress2 nullable: true
        phone nullable: true
        email nullable: true, email: true
    }
}
```

*_JSON Response Payload (http status code : 422) *_

```
{"responseText":"Property [dba] of class [class com.somecompany.CreateInsuredCommand] cannot be null<br/>Property [address2] of class [class com.somecompany.CreateInsuredCommand] cannot be null<br/>Property [physicalAddress2] of class [class com.somecompany.CreateInsuredCommand] cannot be null<br/>Property [phone] of class [class com.somecompany.CreateInsuredCommand] cannot be null<br/>Property [email] of class [class com.somecompany.CreateInsuredCommand] cannot be null"} 
```

**Environment Details:**
Grails Version 2.4.4 app deployed as war file to Tomcat 8.0 RC5
Java 1.8 Update 25
Windows Server 2008 R2

**Details for the Grails 3.0 Env**
https://grails.slack.com/archives/questions/p1454966869001838

**Comment by olavgg** [comment]
I also had this problem yesterday for a simple Command object:
This was with Grails 3.0.14

```java
import grails.validation.Validateable
​
class OrderCommand implements Validateable{
​
    String token
​
    static constraints = {
        token nullable: true, blank: true
    }
}
```
For some reason it wouldn't accept null values, a restart solved this. This was in development.

**Comment by graemerocher** [comment]
Will need an example upload that reproduces the issue in order to investigate

**Comment by aletocar** [comment]
@mitchmckenzie did you ever manage to fix this? We are encountering the same issue in grails 3.2.9, but with a domain class' constraints.

**Comment by olavgg** [comment]
I've not had any problems with Grails 3.1, 3.2 nor 3.3 since I reported this.

**Comment by timo-klarshift** [comment]
We are also experiencing this from time to time in our production environments, only restart of the application is fixing this. Why has this been closed? Also its hard to submit a reproducible, because at stated the issue is intermittent.

**Comment by ntung** [comment]
I have been experiencing the same issue on both the dev and prod environments. Restarting the application doesn't work for me. Interestingly, the creating operator works well when leaving these fields null but the updating operator fails.
The application is written in Grails 2.5.5 which is very far from the state of the art.

**Comment by puneetbehl** [comment]
This is a quite old issue and also Grails 2 is EOL for quite some time now. I think the chances of getting any help with this specific problem is close to minimal. I'm not sure if there is even an option for the paid support with Grails 2 to help to upgrade.
