### ISSUE TITLE
[grails 3.1.1 ] UrlMapping with inline plugins does not work.

### ISSUE THREAD

**Issue by schmittr** [grails/grails-core#9657]
The documentation describes the possibility to bind mappings with plugins (http://grails.github.io/grails-doc/3.1.x/guide/single.html#namespacedControllers).

'''
static mappings = {
    "/accountingReports" {
        controller = "reporting"
    }
    "/humanResourceReports" {
        controller = "reporting"
        plugin = "humanResources"
    }
}
'''

As https://github.com/grails/grails-core/issues/9651 did not work, I tried a work-around with a inline plugin. 
Unfortunately I didn't succeed in setting up such an UrlMapping with the inline plugin. 
Perhaps I did something wrong, but currently I get a 404. If this is not a bug and there is something special one has to consider, it would be nice to extend the documentation.

**Comment by droggo** [comment]
Can you try with plugin UrlMappings name like `CustomPluginUrlMappings.groovy` ? I believe that if you use default name, this will be overriden by application's UrlMapping. At least it works for non-inline plugins

**Comment by schmittr** [comment]
But wouldn't this map rather to an endpoint than to a controller? I understood the documentation in the way, that there must only be a controller and not necessarily an UrlMapping. I'll try this later, but could you explain me the logic behind that requirement?

**Comment by schmittr** [comment]
As I expected:

```
Error 500: Internal Server Error

Message
    URL mapping must either provide redirect information, a controller or a view name to map to!
```

**Comment by droggo** [comment]
I think I misunderstood you question, sorry.

**Comment by schmittr** [comment]
No need to apologize, thank you for your reply anyways!

**Comment by graemerocher** [comment]
Please upload an example to github that reproduces the problem.

**Comment by schmittr** [comment]
https://github.com/schmittr/inlinePluginUrlMappings

**Comment by schmittr** [comment]
Any news on this?

**Comment by graemerocher** [comment]
it has been scheduled

**Comment by graemerocher** [comment]
The problem with example is that your plugin class names don't match the `UrlMappings`. Your plugin is called `MypluginbGrailsPlugin` whilst the mapping is `pluginb` whilst it should be `mypluginb` to match your plugin name
