### ISSUE TITLE
3.1 server.host is ignored (grails.server.host also)

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#9658]
grails -Dserver.host="172.16.0.101" run-app

Grails application running at http://localhost:8080 in environment: development

**Comment by droggo** [comment]
As a workaround, try adding
```
bootRun { 
    systemProperty 'server.address', System.getProperty('server.address')
    systemProperty 'server.port', System.getProperty('server.port')
}
```
to your `build.gradle`

**Comment by AlexKovynev** [comment]
nope:( 

java.net.BindException: Can not assign requested address

**Comment by rlovtangen** [comment]
`grails -Dserver.port=8084 run-app` don't work anymore either. Use `grails run-app --port=8084` or `grails --port=8084 run-app`
Needs update to documentation at http://grails.github.io/grails-doc/3.1.1/ref/Command%20Line/run-app.html and http://grails.github.io/grails-doc/3.1.1/guide/gettingStarted.html#runningAndDebuggingAnApplication

**Comment by graemerocher** [comment]
By design, see above

**Comment by kktec** [comment]
By default, Gradle does not pass system properties through. A workaround that allows ALL system properties to be passed through to tasks that are Java executables is:

```
tasks.withType(JavaExec) {
	systemProperties System.properties
}

```
I also do this for tests so functional tests that need to run on a different port also work.

```
tasks.withType(Test) {
	systemProperties System.properties
}

```
