### ISSUE TITLE
3.1.0 static html in run-app results in 404 error

### ISSUE THREAD

**Issue by AustinAllman** [grails/grails-core#9663]
Following the instructions from http://stackoverflow.com/a/31425934 using grails 3.1.0

`grails create-app deleteme`
`mkdir deleteme/src/main/resources `
`mkdir deleteme/src/main/resources/public`
`echo "<h1>hello world</h1>" >> deleteme/src/main/resources/public/index.html`

Changed the / action in UrlMappings.groovy to
`"/"(redirect:"/index.html")`
and did
`cd deleteme`
`grails run-app`
results in 
`Error: Page Not Found (404)`
`Path: /index.html`

Confirmed that same procedure works with grails-3.0.9 on my system

**Comment by droggo** [comment]
Check https://github.com/grails/grails-core/releases/tag/v3.0.12 and `Location of static resources`

**Comment by AustinAllman** [comment]
Thanks @droggo that resolved the issue. I've updated the stackoverflow answer and added an issue to the grails-doc to update the documentation https://github.com/grails/grails-doc/issues/432
