### ISSUE TITLE
Grails @BindingFormat does not throw any error if date is supplied in some other format.

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9667]
The solution to this problem is simpleDateFormat.setLenient(false). Here is grails console output of @jeffbrown 's investigation on slack channel.

```
groovy:000> fmt = new java.text.SimpleDateFormat('dd/MM/yyyy')
===> java.text.SimpleDateFormat@d936eac0
groovy:000> fmt.parse('1969/11/15')
===> Sat Mar 22 00:00:00 CST 21
groovy:000> fmt.lenient = false
===> false
groovy:000> fmt.parse('1969/11/15')
ERROR java.text.ParseException:
Unparseable date: "1969/11/15"
        at java_text_DateFormat$parse.call (Unknown Source)
``` 

Here is related slack discussion. https://grails.slack.com/archives/questions/p1455114212002156

**Comment by jeffbrown** [comment]
I will work up a solution for this in the next couple of days and we will include in the next `3.0.x` and `3.1.x` releases.  Thanks for the feedback.
