### ISSUE TITLE
Make grails rest api development more and more DRY and awesome

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9669]
Developing REST apis with grails is simple and straight forward. Developing production grade awesome APIs with grails is a hard way to go. Grails remains no more DRY and no more a rapid application development framework when it comes to REST except for the GORM part (and I love it most). As a reference, we can take a look at spring data rest. Grails' @Resource annotation is similar approach but can't be used in production.

What is an awesome API?
@chrislatimer from apigee gave a talk about this in springone2gx and here are his slides http://www.slideshare.net/SpringCentral/building-awesome-apis-with-grails and a video can be found here http://www.infoq.com/presentations/grails-api-2014

In this talk he describes what awesome apis are with examples from popular services. The purpose of this issue is not to demand all those out of the box as there are always needs which require customizations. I will be providing pull requests for some of these functionalities against this issue.

- 

 Pagination support:

Grails does not render pagination out of the box like total in a list and current offset, current max etc. To get a total count of a particular entity, you have to send a second request to count action of RestfulController. Spring Data Rest provides this out of the box. I've a solution for that and will provide PR against this issue.
 

- 
Include and Exclude related entities.

User should be able to include and exclude related entities from request parameter as done by Spring Data Rest.

- 
Sensible Defaults to avoid excessive use of marshallers

Almost every domain class needs two or more marshaller and most of the time the response needed is pretty standard. So some sensible defaults should be chosen to avoid excessing use of marshallers and converters.

 -
Labels for json response

Grails returns json without labels i.e for list of books it should return

```
{ "Books":[ { ...}, {....}]} 
```

To place a labe Books, alot of boiler plate is needed and then we need to register this boiler plate in spring.groovy for each domain class. Although it is not a must have feature, but others are providing it out of the box, so grails can if it does need much effort.

- 
Hal out of the box?

Even though we don't use this but it reduces some of the overhead for frontend devs (or at least my front end devs complain about it).

Fortunately all of it is possible with grails and Chris in his talk explains how to do it. After working on a large and complex project, I have a feeling that this stuff should be part of grails core and same were the remarks of Chris. This is also possible to achieve all this functionality through a plugin and I'll look into it as well.

**Comment by jeffbrown** [comment]
I spoke with @ejaz-ahmed and he is going to create separate issues.  Closing this one.
