### ISSUE TITLE
Create app fails in 2.5.3 - aspectjweaver version mismatch

### ISSUE THREAD

**Issue by rgogulakrishnan** [grails/grails-core#9670]
Grails v2.5.3 uses aspectjweaver 1.8.5 but the sdk  has 1.8.7 in its lib which makes create-app fail if its not already in my local repo.

**Comment by bobbywarner** [comment]
This is already fixed on the 2.5.x branch.  It will included in the next release (i.e. 2.5.4).

https://github.com/grails/grails-core/pull/9563

**Comment by jeffbrown** [comment]
Duplicates #9450

**Comment by rgogulakrishnan** [comment]
Thanks..
