### ISSUE TITLE
Grails should provide Labels for json response

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9674]
Grails renders collection and individual items without label. For example, if we request Books list, it simple returns array of objects which is not a valid json in strict sense (although front ends can use it without any issue). Here is response of get request to Books

```
[
{"title":"Book1},
{"title":"Book2"}
]
```

It should be like this:

```
{"Books":
[{"title":"Book1},
{"title":"Book2"}]
}
```

**Comment by ejaz-ahmed** [comment]
I have a solution for this and post it here but it has one drawback that it requires registration for each domain object.

**Comment by graemerocher** [comment]
I don't agree with the statement that an array of objects i not valid JSON, where did you come up with that conclusion?

**Comment by schmittr** [comment]
According to http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf this grails default way is correct. @ejaz-ahmed, I also don't understand assumption that the class name needs to be contained. How is your API consumed? Normally it is clear, that someurl/path/to/book/ returns a book and not a bird or a car... The URL-Design is important to guarantee an easy to understand API.

**Comment by ejaz-ahmed** [comment]
Closing it. I was wrong and opened it with less research even though I am generating these as per requirements of front end devs.

**Comment by schmittr** [comment]
Well, according to this thread I just crossed over, it might be a security-issue to not wrap an array into an object:
http://stackoverflow.com/questions/3503102/what-are-top-level-json-arrays-and-why-are-they-a-security-risk

Thus, maybe the proposed change of @ejaz-ahmed shld be considered?!

**Comment by graemerocher** [comment]
What Mozilla consider a vulnerability is the ability to redefine the `Array` object and that is what has been patched. They do not consider representing JSON as an array as a vulnerability. Also the vulnerability in question is no longer applicable to modern browsers: http://stackoverflow.com/questions/16289894/is-json-hijacking-still-an-issue-in-modern-browsers

**Comment by schmittr** [comment]
Ah, I see. Thx. :+1:
