### ISSUE TITLE
Grails should render HAL json out of the box

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9675]
As HAL is becoming more and more popular it is sort of de-facto standard, grails should use it out of the box as compared to normal json/xml response. Spring Data Rest also uses this out of the box.

**Comment by graemerocher** [comment]
Definitely some way to enable HAL as the default would be good

**Comment by jameskleeh** [comment]
This can be accomplished by simply modifying `/object/_object.gson` and changing the call `g.render` to `hal.render`. I think it would be easier to do that than to set a configuration setting.
