### ISSUE TITLE
3.1.1 Upload fail with small files

### ISSUE THREAD

**Issue by marcioaug** [grails/grails-core#9680]
When the file is less than ~120kb an exception (MalformedStreamException - stream ended unexpectedly) occurs. 

This exception is thrown when discardBodyData() is called.  (public boolean skipPreamble() in org.apache.commons.fileupload.MultipartStream)
``` groovy
@PreAuthorize("isAuthenticated()")
	def uploadAvatar() {
		if (params.file) {
```
``params.file`` is ``null`` when the exception occurs.

**Comment by graemerocher** [comment]
Upload an example that reproduces the problem please.

**Comment by marcioaug** [comment]
@graemerocher I'm sorry to inconvenience, I overrides ``multipartResolver`` to increase the maximum file size, this was the cause of the problem. 

``` groovy
beans = {
    multipartResolver(CommonsMultipartResolver) {
        maxInMemorySize = 1048576
        maxUploadSize = 1048576
    }
}
```

Follows the code if necessary:
[upload.zip](https://github.com/grails/grails-core/files/126854/upload.zip)

**Comment by janitza-jamu** [comment]
Hi there, we've got the same problem.

**Comment by graemerocher** [comment]
the default multipart resolver is no longer `CommonsMultipartResolver` it is `StandardServletMultipartResolver`, I suggest you don't override and instead use the settings present already to tweak the behaviour in `application.yml`:

* `multipart.maxFileSize` is set to 128KB, meaning total file size cannot exceed 128KB.
* `multipart.maxRequestSize` is set to 128KB, meaning total request size for a multipart/form-data cannot exceed 128KB.

**Comment by droggo** [comment]
We have the same issue. I tried setting (also with 20971520 value) in `application.yml`:
```
multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB
```
But error still shows 'configured 128KB'.

Additionally, it seems that exception `MaxUploadSizeExceededException` is not caught by Grails error handler, because instead of configured error page, default tomcat page is displayed.

Should I prepare example project?

**Comment by graemerocher** [comment]
Sure examples welcome

**Comment by graemerocher** [comment]
Sorry I got the setting names wrong. They are `grails.controllers.upload.maxRequestSize` and `grails.controllers.upload.maxFileSize`

**Comment by marcioaug** [comment]
My application.yml is:
``` yml
grails:
...
    controllers:
        defaultScope: singleton
        upload:
            maxRequestSize: 1048576
            maxFileSize: 1048576
```
It woks.

**Comment by ppazos** [comment]
Related to this, is there a way to catch the exception when the file exceeds the max size to display a friendly error to the user? @graemerocher 

Is the only way to have a global exception handler? https://mkyong.com/spring/spring-mvc-how-to-handle-max-upload-size-exceeded-exception/
