### ISSUE TITLE
Grails 3.1.1 isn't rendering 'class' property with JsonRenderer

### ISSUE THREAD

**Issue by Spadavecchia** [grails/grails-core#9687]
In resources.groovy:
``` grails
ActorRenderer(JsonRenderer, Actor) {
  includes = ['class', 'id', 'firstName']
}
```

With grails 3.1.0.M2:
GET localhost:8080/test/actor
``` javascript
[
  {
    "id": 1,
    "class": "test.Actor",             // <<  "it is not anymore in new version! We need it!"
    "firstName": "Donald"
  }
]
```

with grails 3.1.1:
GET localhost:8080/test/actor
``` javascript
[
  {
    "id": 1,
    "firstName": "Donald"
  }
]
```

**Comment by graemerocher** [comment]
Ok so the default as of 3.1.x is not to include the class which is what most people want, however it seems there is no easy way when registering the renderer to re-enable including the class. We will fix this.

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/ceee9120e25d026883fdebd9b9131a9599dfb3a3
