### ISSUE TITLE
Can't use a secondary datasource in Grails 3

### ISSUE THREAD

**Issue by squarepegsys** [grails/grails-core#9690]
This is an issue that myself and @ctwospoons ran into.

If you have multiple datasources in a Grails 3 project, you can inject and use the primary datasource (i.e. `dataSource`) but not the secondary one. You were able to do this with Grails 2.

It's somewhat similar to #701 but with a different error message.

See my additional tests in my fork of `grails3-functional-tests` that demonstrates it.
https://github.com/squarepegsys/grails3-functional-tests/tree/master/datasources

**Comment by graemerocher** [comment]
The beans names are `dataSource_NAME`, so in your case you would have to use:

```
@Autowired
@Qualifier('dataSource_secondary')
DataSource dataSource
```

Also you need to make sure you are using the appropriate transaction manager for the data source. Using a plain `@Transactional` will always default to using the default data source unless you provide a `transactionManager` property:

```
@Autowired
@Qualifier('transactionManager_secondary')
PlatformTransactionManager transactionManager
```

**Comment by squarepegsys** [comment]
I justed used the same dataSource names you used in the functional tests. See here:
https://github.com/grails/grails3-functional-tests/blob/master/datasources/grails-app/conf/application.yml

You didn't need `@Autowired` and `@Qualifier` in Grails 2 but that is a workable solution. There should be documentation on how this is supported in Grails 3.

**Comment by graemerocher** [comment]
one thing is the dataSource name, another thing is the Spring bean name, those are not the same things.

**Comment by wvetrone** [comment]
I have a similar issue.

In my application.groovy I have the following Datasources set up.

`    test {
        dataSource{
			pooled = true
			jmxExport=  true
			driverClassName= "org.h2.Driver"
			username= "sa"
			password = ""
			dbCreate = "update"
			url = "jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
        }
		workflow{
			pooled = true
			jmxExport=  true
			driverClassName= "org.h2.Driver"
			username= "sa"
			password = ""
			dbCreate = "update"
			url = "jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
        }
    }`

I receive there are no bean found when I try in my resource.groovy
`beans = {	
	groovySql(groovy.sql.Sql, ref('workflow'))
}
`

I also tried
`beans = {	
	groovySql(groovy.sql.Sql, ref('dataSource_workflow'))
}
`

I think reviewed all beans in my BootStrap and in the output I could not find WorkFlow or DataSource_Workflow
