### ISSUE TITLE
Cant apply validatable trait at run time.

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#9693]
Validatable is a groovy trait, so i would expect that i can apply the trait to a pogo at run time using ```def popgo = new Pogo as XTrait```

However when done this way, looks like it is unable to find the static constraints closure defined within the pogo.

It would be great if it is fixed. Should not be much difficult i guess.

I want to appy Validatable trait at runtime to a command object instance, because IntelliJ 14 does not support groovy traits (shows errors), and intellij 15 doesnt support grails 2.xx so cant use intellij15 either.

**Comment by droggo** [comment]
Just one remark - this may have impact on performance. Doing such things because of issues with IDE seems to be not a good choice. I didn't test it but errors should disappear if you use correct (newer) groovy version in IDE.

**Comment by snimavat** [comment]
As far as i read, intellij 14 has issue with groovy traits regardless of groovy versions. i will see if it can be solved. However it would be great if grails respect Groovy traits, atleast for command objects.

**Comment by jeffbrown** [comment]
> because IntelliJ 14 does not support groovy traits

IntelliJ 14 does support Groovy traits

> and intellij 15 doesnt support grails 2.xx

IntelliJ 15 does support Grails 2.x

**Comment by jeffbrown** [comment]
I don't anticipate that we will add support for making classes validateable at runtime, at least not in `grails-core`.  I suppose a plugin might be able to do it.

**Comment by jeffbrown** [comment]
I am going to go ahead and close this request.  This is a niche enough thing that I don't think it belongs in core.  I am not sure why one wouldn't just explicitly add `implements Validateable` to the Groovy class that defines the `constraints` closure but if there are use cases for that I don't think they are common enough to warrant including support for this in core.

Another option you have is if the command object class is defined in the same source file as a Controller which uses it as a command object, the class will automatically be made `@Validateable`.

Thanks for the feedback.

**Comment by snimavat** [comment]
> Another option you have is if the command object class is defined in the same source file as a Controller which uses it as a command object, the class will automatically be made @Validateable.

Cool, this works for me.

>IntelliJ 14 does support Groovy traits - I cant figureout how to get it work, i will do some more research.

**Comment by graemerocher** [comment]
This issue and pull request seems related https://github.com/grails/grails-core/issues/9599

**Comment by snimavat** [comment]
Here's the intellij issue which i am facing - https://youtrack.jetbrains.com/issue/IDEA-139266

**Comment by jeffbrown** [comment]
In Grails 2.5 you can also still use the `@grails.validation.Validateable` annotation.

**Comment by snimavat** [comment]
@jeffbrown - the issue is with grails 3.

**Comment by jeffbrown** [comment]
> the issue is with grails 3

@snimavat I see.  I thought you might be using Grails 2 since you mentioned "intellij 15 doesnt support grails 2.xx so cant use intellij15 either"

**Comment by jeffbrown** [comment]
> @jeffbrown if you you know how to get traits working in intellij idea 14 (14.1.4 ultimate), can you post here ? it would help others too.

@snimavat - In general traits work in IntelliJ as I expect them to.  It looks like they might have an issue with using traits that are pulled in from external dependencies.

**Comment by snimavat** [comment]
@jeffbrown I have multiple projects, few are still on 2.x.x :)
