### ISSUE TITLE
3.1.1 create-app:  dash in app name results in a wrong package statement

### ISSUE THREAD

**Issue by MLoenhardt** [grails/grails-core#9696]
grails create-app name-with-dash
UrlMapping.groovy is generated in the package name.with.dash

create-domain-class testclass creates into the same package.

In grails 2.5.3 a app name with dashes was no problem

Creating an project name-with-dash with intellij EAP 16.144.3891.8 

"C:\Program Files\Java\jdk1.8.0_66\bin\java" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -Djline.WindowsTerminal.directConsole=false -Dfile.encoding=UTF-8 -classpath "D:\grails\grails-3.1.1\dist\grails-async-3.1.1.jar;D:\grails\grails-3.1.1\dist\grails-bootstrap-...D:\grails\grails-3.1.1\lib\xalan\serializer\jars\serializer-2.7.2.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 144.2925.2\plugins\Grails\lib\grails-rt.jar" org.grails.cli.GrailsCli create-app idea-with-dash --inplace

UrlMapping.groovy is generated in the package idea-with-dash

**Comment by graemerocher** [comment]
Duplicates #9654
