### ISSUE TITLE
BinaryGrailsPlugin fails during startup on weblogic 12.1.3

### ISSUE THREAD

**Issue by yvesf** [grails/grails-core#9701]
I'm referring to this change: b0e5375911b225d87fe77218f5d28757eade9e01

The value of `isJar` is calculated by testing baseResourceString startsWith `jar:`.
For unknown reasons on weblogic it starts with `zip:` instead. Then it fails in the next line in the call to `IOUtils.findApplicationDirectoryFile` instead of taking `null` for projectDirectory. This completely blocks launching a grails application from an ear file on weblogic.

Please check if you can use `org.springframework.util.ResourceUtils#isJarURL(URL)`.
In spring3 this weblogic behaviour is documented [javadoc](http://docs.spring.io/autorepo/docs/spring-framework/3.2.6.RELEASE/javadoc-api/org/springframework/util/ResourceUtils.html#isJarURL%28java.net.URL%29), however this comment vanished somehow.

**Comment by graemerocher** [comment]
Thanks for the pull request!
