### ISSUE TITLE
bug with 3.1.1 render JSON

### ISSUE THREAD

**Issue by btboys** [grails/grails-core#9704]
```
package test2
import grails.web.mime.MimeType

class AppController {

    def test(){
        render(contentType: MimeType.JSON) {
            [ok: "名字很棒!"]
        }
    }
}
```

Does not correctly return results

**Comment by graemerocher** [comment]
See the upgrading documentation: http://grails.github.io/grails-doc/latest/guide/upgrading.html#upgrading3x

Section 'JSON Builder Groovy Alignment'
