### ISSUE TITLE
Unable to create exploded war file

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#9705]
It doesnt create exploded war even after specifying following settings in application.groovy

```
grails.project.war.exploded.dir = "../tomcat/webapps/ROOT"
grails.war.exploded=true
```

**Comment by snimavat** [comment]
Here's how i did it, may be useful to others.

in build.gradle - added a new task

```
File explodedDir = "$buildDir/../../matrishift/webapps/ROOT" as File
task explodedWar(dependsOn: war) {
    ant.unzip(src: war.archivePath, dest: explodedDir)
}
```

and then run the command ```gradle explodedWar -Pd0=grails.env=openshift```

**Comment by graemerocher** [comment]
the way you did it is correct.
