### ISSUE TITLE
UrlMappings from plugin is not excluded

### ISSUE THREAD

**Issue by rlovtangen** [grails/grails-core#9706]
Tried to change default page by adding
````
"/"(controller: 'foo')
````
to UrlMappings in an application. But it has no effect due to UrlMappings from a custom plugin.

According to the documentation, UrlMappings should be automatically excluded from plugin:
"In addition, the default UrlMappings.groovy file is excluded to avoid naming conflicts, however you are free to add a UrlMappings definition under a different name which will be included."
(http://grails.github.io/grails-doc/3.1.1/guide/plugins.html#providingBasicArtefacts)

See https://github.com/rlovtangen/grails-bug-plugin-urlmappings for reproducible example. The plugin from the example is generated by `grails create-plugin` and not altered.
Comment out inline plugin in `build.gradle`, or remove `"/"(view:"/index")` from plugin, and it works fine.

Grails 3.1.1

**Comment by houbie** [comment]
I'm having this problem on a very simple project without any custom plugins.
Tried to reproduce it with a new project, but then it works. I guess that difference is caused by the order in which jars are loaded?

**Comment by rlovtangen** [comment]
@houbie: are you using any other plugins? Maybe one of the plugins has a UrlMappings.groovy, because you get one by default when creating a plugin.

**Comment by zyro23** [comment]
hit this one too while upgrading a 2.5.x app to 3.1.1. in my case, it was the `excel-export` plugin having packaged a `UrlMappings` in the default package..

**Comment by houbie** [comment]
Indeed, the mappings from the excel export plugin (pl.touk:excel-export:2.0.1) are loaded after (and overwrite) the application's url mappings.

**Comment by graemerocher** [comment]
Seems to be related to the fix for https://github.com/grails/grails-core/issues/9441
