### ISSUE TITLE
g:select produces multiple selected options

### ISSUE THREAD

**Issue by tcrespog** [grails/grails-core#9708]
A g:select tag where the `from` attribute contains a list of Integer/Long objects and the `value` attribute contains a String object representing a single digit could produce an HTML select tag with 2 options marked as selected.
If the ASCII code of the `value` digit is contained among the numbers in `from`, then both, the option whose value is the digit per se and the option whose value is the ASCII numerical representation of the digit, will be selected.

For example, the tag:
`<g:select name="simpleSelect" from="${(1..53)}" value="4" />`
Generates this HTML code (the ASCII numerical representation of the digit 4 is 52):

```
<select name="simpleSelect" id="simpleSelect">
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4" selected="selected">4</option>
...
<option value="52" selected="selected">52</option>
<option value="53">53</option>
</select>
```

The root of this behavior is in this [case](https://github.com/grails/grails-core/blob/master/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/FormTagLib.groovy#L1054) in the body of the `select` method and the [way](https://github.com/groovy/groovy-core/blob/master/src/main/org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.java#L562) Groovy handles the truth.

I have experienced some problems using Grails due to this counterintuitive behavior. I think it could be solved and I am willing to help creating a pull request.
Thanks.

**Comment by graemerocher** [comment]
Please report GSP issues to https://github.com/grails/grails-gsp/issues
