### ISSUE TITLE
"Could not resolve view" exceptions when executing a REST-API profile app via Runnable JAR or deploying to Tomcat

### ISSUE THREAD

**Issue by freak0** [grails/grails-core#9710]
When i run the app using the `run-app` command, everything works fine, but when running the same app via a Runnable JAR (or deploying a WAR file to a TOMCAT) generates the following exceptions:

<pre>
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1226) ~[spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
...
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_72]
</pre>

[The full stacktrace is attached.](https://github.com/grails/grails-core/files/133275/fullStackTrace.txt)

I've created an example app and published it to Github in: https://github.com/freak0/sample-rest-app

**Environment:**
- Windows 7 64-bit
- Grails Version: 3.1.1
- JVM Version: 1.8.0_72

**To reproduce:**
- `grails run-app`
- Navigate in browser to http://localhost:8080/bookstore
- See that it runs properly
- `gradle assemble`
- `java -jar sample-rest-app-0.1.jar`
- Navigate in browser to http://localhost:8080/bookstore
- See that it will raise exceptions, and send `{"message":"Internal server error","error":500}` to the browser

This may be a duplicate from #9302, but the workaround there described did nothing for me... Maybe because my version of the error is happening when using GSON views, with a REST-API profile application.

**Comment by carlosnakazawa** [comment]
Same issue here

**Environment:**

- Windows 7 64 bit
- Grails: 3.1.1
- JVM: 1.8.0_73

**Comment by freak0** [comment]
Evaluating the generated JAR file, I've seen that the generated .class files for the .gson's were all in the root, with no package name as preffix (as happened with the GSPs .class files)... All but the ones in the root folder (notFound.gson and error.gson).

So I've tried the following:

In the controller I've created the following method:

<pre>
    def otherAction() {
        render(view: '/noFolderView', model: [books: Book.findAll()])
    }
</pre>

And created a noFolderView.gson on the root folder...
Doing it this way, it works via Runnable JAR. And the generated .class file got the preffix correct.

I've pushed the new method to the example project... I hope it helps.

**Comment by graemerocher** [comment]
This  may related to the other Windows problems we have had reported because it works fine on *nix systems

**Comment by freak0** [comment]
Another workaround I'm using right now:
I've created another method, like so:

`def otherApproach() {
        [books: Book.findAll()]
    }`

So, after that I created a view file named `otherApproach.gson` on the correct `bookstore` folder. It's working via `run-app` command.
Then, I've created a copy of said file with the name `bookstore_otherApproach.gson`. 
This way the file is compiled with the expected class name and in the correct folder... And so it is working with the runnable JAR as well. 

It's ugly, but is keeping the ball rolling for now...

**Comment by graemerocher** [comment]
That is interesting, that tells me that Windows is not picking up the correct relative path

**Comment by steyng** [comment]
Same issue here.

Environment:

Windows 8.1 Enterprise
Grails-3.1.2
JDK1.8.0_73

Works on Linux (Oracle Enterprise Linux 7.0, Grails-3.1.2, JDK1.8.0_73).

**Comment by angstream555** [comment]
update grails version at last 3.2.6

**Comment by upretiprabin** [comment]
I am facing the same problem, i've found that i have two views with same name (accessDenied.gsp) one inside the views directory, one inside views/logout/. Does this cause the ambiguity? For now, i have put render(view:'/logout/accessDenied') but i am not sure having duplicate views caused the issue.

Thanks,

**Comment by tircnf** [comment]
This issue is back with grails 4.0.5
