### ISSUE TITLE
Springboot starter pack for logging "org.springframework.boot:spring-boot-starter-logging" does not allow my application to start.

### ISSUE THREAD

**Issue by singhajey003** [grails/grails-core#9711]
When I run my application using `grails run-app` a long stacktrace fills up my terminal and the application shuts down. When I comment out my compile `org.springframework.boot:spring-boot-starter-logging` line in `build.gradle` then everything seems to look fine. Can anyone help me with this?

Environment:

- Ubuntu 15.04
- Grails Version: 3.1.0
- JVM Version: 1.8.0_72

[The full stacktrace is attached.](https://github.com/grails/grails-core/files/133394/stacktrace.txt)

**Comment by graemerocher** [comment]
Please ask questions on Slack or Stack Overfow
