### ISSUE TITLE
GrailsTask class not available in latest versions of grails-gradle plugin

### ISSUE THREAD

**Issue by alicehelen** [grails/grails-core#9714]
I am using version 3.0.9 of the grails gradle plugin.
org.grails:grails-gradle-plugin:3.0.9
The GrailsTask class found in the grails gradle plugin is no longer available in this version.

The package location for the GrailsTask class in previous Grails version is
org.grails.gradle.plugin.tasks.GrailsTask

Is the class moved to a different package or is it deprecated in recent plugin versions.

**Comment by graemerocher** [comment]
The 2.x version of the Gradle plugin was developed by the community and has nothing to do with the version of the Grails plugins for 3.x
