### ISSUE TITLE
Failed to find views on weblogic

### ISSUE THREAD

**Issue by yvesf** [grails/grails-core#9716]
When running under weblogic I see that the application cannot find any application views like for example the `grails-app/views/index.gsp`. Instead it falls back to the index.gsp from a grails-plugin it depends on.

The reason for this is that the grails application thinks it's not running as a deployed war file. The check in `Environment#isWarDeployed` returns the wrong result. The check inside this method is not working on weblogic because for some reasons (I didn't manage to find any documentation on this) weblogic packs everything inside the war-file `WEB-INF/classes` inside a new jar and put next to the other jars in `WEB-INF/libs`
There seem to be different variants and ways how you can deploy to weblogic. It supposed not to happen with an "exploded war". Another description of this issue can be found here: http://support.esri.com/fr/knowledgebase/techarticles/detail/33410 .

I'm going to propose an extension to the test in `isWarDeployed()` as a pull-request here. I agree that it's not nice to include weblogic specific checks inside grails (note there is already one about zip: versus jar: in ResourceUtils), however, at the moment I see no other way to deal with this.

**Comment by graemerocher** [comment]
Thanks!
