### ISSUE TITLE
Render for templates in GSON views does not honor relative pathing

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-core#9720]
Following the examples laid out [here](https://github.com/grails/grails-views#templates) to recreate nested gson template rendering it would appear that the relative path isn't recognized for g.render and the fully qualified path is required even when the template is located in the same directory as the calling gson file.

Doing this `contents g.render(template: "content", collection: managedContent.contents, var: 'content')` breaks and fails to render.  The code pictured below works however.

<img width="1334" alt="screen shot 2016-02-17 at 2 10 58 pm" src="https://cloud.githubusercontent.com/assets/691357/13123190/b642a682-d580-11e5-93b4-c517e55df439.png">

**Comment by graemerocher** [comment]
We already have some functional tests for this https://github.com/grails/grails-views/blob/master/functional-tests/src/integration-test/groovy/functional/tests/TeamSpec.groovy

It seems to work fine for me, could you upload an example that reproduces the problem? Thanks.

**Comment by ctoestreich** [comment]
Here is the [sample project](https://github.com/Grails-Plugin-Consortium/grails-gson-issue).  The issue is happening on GenericViewUriResolver on line 42 ` buf << SLASH << pathToTemplate << UNDERSCORE << templateName`  Since the template is being asked for as 

``` groovy
import org.grails.demo.Person

model {
	Person person
}

json {
    name person.name
    addresses g.render(template: 'address', collection: person.addresses, var: 'address')
}
```

this resolves correctly to _address.gson but the / is being prepended.

**Comment by ctoestreich** [comment]
I think your projects and functional tests work correctly due to having all the views at the root.

**Comment by graemerocher** [comment]
Thanks, will take a look...
