### ISSUE TITLE
Grails stats command skips integration tests

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9721]
Here is the output of grails stats command on [this repo](https://github.com/ejaz-ahmed/grails3-cascade-delete)

```
+----------------------+-------+-------+
| Name                 | Files |  LOC  |
+----------------------+-------+-------+
| Controllers          |     3 |    24 | 
| Domain Classes       |     3 |    23 | 
+----------------------+-------+-------+
| Totals               |     6 |    47 | 
+----------------------+-------+-------+
```
Even though this repo contains integration tests but they are not shown.

**Comment by ejaz-ahmed** [comment]
I've observed this issue on grails 3.0.11

**Comment by jeffbrown** [comment]
This would probably be a pretty simple PR to https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/stats.groovy.

**Comment by ejaz-ahmed** [comment]
Cool. So simple. I'll send it today.
