### ISSUE TITLE
Grails Interceptors don't work with static resources.

### ISSUE THREAD

**Issue by kefirfromperm** [grails/grails-core#9724]
I set matchAll, but interceptor didn't ire when I try to access to static image resource. So interceptors can't be replacement of filters. So interceptors have to intercept access to static resources or filters can't be deprecated.

Grails 3.1.0

**Comment by jeffbrown** [comment]
Does `match uri: '/**'` work?

**Comment by jeffbrown** [comment]
> So interceptors have to intercept access to static resources or filters can't be deprecated.

Filters have been deprecated.  If there are scenarios that interceptors aren't accounting for, the resolution to that is to fix interceptors, not to un-deprecate filters.

**Comment by kefirfromperm** [comment]
> Does `match uri: '/**'` work?

It doesn't.

**Comment by jeffbrown** [comment]
> It doesn't.

Thanks for the feedback.

**Comment by graemerocher** [comment]
Internally interceptors use the same mechanism as filters to match the request, I very much doubt filters work in Grails 3 when matching static resources but I'm happy to be proven wrong. Either way upload an example that reproduces the issue to github

**Comment by kefirfromperm** [comment]
Anyway I need a mechanism for preventing access to my static resources by a security reason.
I've made a sample. https://github.com/kefirfromperm/grails3-interceptor-sample
When I request "/" it works fine and prints to log resource URI, but when I request "/static/rio.jpg" it doesn't print to log anything.

Also Java filters work with static resources well.
