### ISSUE TITLE
Upgrade to Groovy 2.4.6

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#9725]
Ref: https://github.com/spring-projects/spring-boot/issues/4149

**Comment by graemerocher** [comment]
There are various issues with static compilation that makes me cautious about upgrading https://issues.apache.org/jira/browse/GROOVY-7763

**Comment by graemerocher** [comment]
So Groovy 2.4.6 is more strict about return types when using `CompileStatic`. It is something we will have to acknowledge in the release notes

**Comment by droggo** [comment]
Is this going to be implemented to 3.1.2? It seems we are facing PermGen issue in Groovy 2.4.5 with scripts engines

**Comment by graemerocher** [comment]
it already has been with the caveat that 2.4.6 is stricter in compilation in certain areas, so not all code will compiled with Groovy 2.4.6

**Comment by todoubaba** [comment]
Why grails 3.1.2  not been updated to spring-boot 1.3.3 to align groovy version?

**Comment by todoubaba** [comment]
Yeah, appriciate your hard work :+1:
