### ISSUE TITLE
grails 3.1.1 exploded plugin feature does not work

### ISSUE THREAD

**Issue by MilesBehind** [grails/grails-core#9727]
We inserted the following code into the build.gradle to enable auto-reloading of changed classes:
```
grails {
    exploded = true
    plugins {          
        compile project(':anotherProject')
    }
}
```

1. we tried several positions (within/above/below dependencies-block) and still do not know where to place this code in order to enable auto-reloading
2. none of the positions worked. Gradle still creates a plugin.jar, so this jar is used instead of the class files and thus changes to any of our groovy- and java-files are ignored (no output on console for compilation of files, no auto-reloading at all).

**Comment by graemerocher** [comment]
how are you running your application? You must use `grails run-app`

**Comment by MilesBehind** [comment]
Using gradle bootRun. We use bootRun because
- running application using grails run-app doesn't work with debugger in IntelliJ IDEA 15 (debugger button is disabled)
- running application using Application.groovy works with debugger but does not support auto-reloading (compile-messages are shown on console but application doesn't change)

**Comment by MilesBehind** [comment]
We tried using grails run-app and auto-reloading still didn't work.

**Comment by graemerocher** [comment]
Upload an example that reproduces the problem, it is almost certainly an issue with your build configuration

**Comment by graemerocher** [comment]
Ah sorry misread your message. The reloading is activated by `grails run-app` so is not active when using `gradle bootRun` unless you pass `grails.run.active` as `true`:

      gradle -Dgrails.run.active=true bootRun

The reason for this is to prevent the exploded mode when building a WAR or JAR file.

**Comment by MilesBehind** [comment]
Running application using:
```
gradle -Dgrails.run.active=true bootRun
```
had the same problems as before: no auto-reloading.

This is our application build.gradle:
```
import org.gradle.internal.os.OperatingSystem

buildscript {
  ext {
    grailsVersion = project.grailsVersion
  }
  repositories {
    maven { url "http://10.162.65.70:8085/nexus/content/groups/public/" }
  }
  dependencies {
    classpath "org.grails:grails-gradle-plugin:$grailsVersion"
    classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.6.7"
    classpath 'com.bertramlabs.plugins:less-asset-pipeline:2.6.7'
    classpath "org.grails.plugins:hibernate4:5.0.0"
  }
}

version "0.1"
group "bis.master"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "war"
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"
apply plugin: "asset-pipeline"

ext {
  grailsVersion = project.grailsVersion
  gradleWrapperVersion = project.gradleWrapperVersion
}

repositories {
  maven { url "http://10.162.65.70:8085/nexus/content/groups/public/" }
}

//noinspection GroovyAssignabilityCheck
configurations.all {
  resolutionStrategy {
    // cache dynamic versions for 10 minutes
    cacheDynamicVersionsFor 10*60, 'seconds'
    // don't cache changing modules at all
    cacheChangingModulesFor 0, 'seconds'
  }
}

dependencyManagement {
  imports {
    mavenBom "org.grails:grails-bom:$grailsVersion"
  }
  applyMavenExclusions false
}


dependencies {
  compile "org.springframework.boot:spring-boot-starter-logging"
  compile "org.springframework.boot:spring-boot-autoconfigure"
  compile "org.grails:grails-core"
  compile "org.springframework.boot:spring-boot-starter-actuator"
  compile "org.springframework.boot:spring-boot-starter-tomcat"
  compile "org.grails:grails-dependencies"
  compile "org.grails:grails-web-boot"
  compile "org.grails.plugins:cache"
  compile "org.grails.plugins:scaffolding"
  compile "org.grails.plugins:hibernate4"
  compile "org.hibernate:hibernate-ehcache"
//  compile project (':BIS-Grails-Plugin')
  grails {
    exploded = true
    //noinspection GroovyAssignabilityCheck
    plugins {
      compile project(':BIS-Grails-Plugin')
    }
  }
  console "org.grails:grails-console"
  profile "org.grails.profiles:web:3.1.0"
  runtime "org.grails.plugins:asset-pipeline"
  runtime "com.h2database:h2"
  testCompile "org.grails:grails-plugin-testing"
  testCompile "org.grails.plugins:geb"
  testRuntime "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
  testRuntime "net.sourceforge.htmlunit:htmlunit:2.18"
  assets 'com.bertramlabs.plugins:less-asset-pipeline:2.6.7'
  assets group: 'de.os.grails.extensions', name: 'typescript-asset-pipeline', version: '1.3-SNAPSHOT', changing: true
}


task wrapper (type: Wrapper) {
  gradleVersion = gradleWrapperVersion
}

assets {
  minifyJs = true
  minifyCss = true
  enableSourceMaps = true
  configOptions = [:]

  minifyOptions = [
    languageMode: 'ES5',
    targetLanguage: 'ES5', //Can go from ES6 to ES5 for those bleeding edgers
    optimizationLevel: 'WHITESPACE_ONLY',
    angularPass: true // Can use @ngInject annotation for Angular Apps
  ]
}

// ------ workaround for error: "Createprocess error=206; the filename or extension is too long" --------------------
if (OperatingSystem.current ().isWindows ()) {
  task pathingJar (type: Jar) {
    dependsOn configurations.runtime
    appendix = 'pathing'

    doFirst {
      //noinspection GroovyAssignabilityCheck
      manifest {
        // Build the Class-Path for absolute paths based on runtime dependencies.
        //noinspection GroovyAssignabilityCheck
        attributes "Class-Path": configurations.runtime.files.collect {
          it.toURL ().toString ().replaceFirst (/file:\/+/, '/')
        }.join (' ')
      }
    }
    // assetCompile will be execute for all Jar-type tasks
    // at least exclude the assets from pathing jar
    assetCompile.enabled = false
  }

  // This gradle task will be called by `grails run-app`.
  bootRun {
    dependsOn pathingJar
    doFirst {
      // Add the compiled app classed to the classpath of the pathing jar. Probably there is a gradle variable for them?
      classpath = files ("$buildDir/classes/main", "$buildDir/resources/main", "$projectDir/gsp-classes", pathingJar.archivePath)
    }
  }
}

```

**Comment by graemerocher** [comment]
Then you are probably running into https://github.com/grails/grails-core/issues/9637

**Comment by MilesBehind** [comment]
may be - we use windows 7 and jdk 1.7.0_79 as development environment.

**Comment by imaress** [comment]
Hi, i make this:
grails create-app appserver -profile=rest-api
grails create-plugin security -profile=rest-api
i create a settings.gradle in the same root directory with de follow:
include "appserver", "security"
then in appserver/build.gradle only can put this code under dependencies:
compile project('security') 
but changes on this plugin are ignored (like documents say), but if i put this
grails {
    exploded = true
    plugins {          
        compile project(':anotherProject')
    }
}
i receive this error:
| Running application...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':appserver'.
> Could not resolve all dependencies for configuration ':appserver:runtime'.
   > Configuration with name 'exploded' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
| Error Failed to start server (Use --stacktrace to see the full trace)

And without exploded config i receive a error too. I use grails 3.1.3 and i can't make the auto-reloading changes work with multiproject config, only inlude the plugin at compile time (inline plugin config).
I follow the official documentation on [Plugins and Multi-Project Builds](https://grails.org/single-page-documentation.html) and a [post](http://grails.io/post/138665751278/grails-3-gradle-multi-project-builds) with exploded config but doesn't work, may be i miss something but i didn't see it.
Thanks for All!!

**Comment by xpierro** [comment]
gradle -Dgrails.run.active=true bootRun worked for us !!

**Comment by jameskleeh** [comment]
@xpierro `grails run-app` accomplishes the same thing, just  FYI
