### ISSUE TITLE
Accessing dynamic scaffolding at runtime throws exception

### ISSUE THREAD

**Issue by byrond** [grails/grails-core#9729]
Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'

To reproduce: create a new Grails app, container, and domain class.  Add a String and Date field to the domain class, and configure the controller to use scaffolding (static scaffold = Hello).

This works in 3.0.14 but not in 3.1.1

**Comment by graemerocher** [comment]
This is because there templates were moved in the scaffolding plugin
