### ISSUE TITLE
grails war doesn't create war files

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-core#9736]
In Grails 3.1.1, `grails war` does not create a war file. It creates a jar file, and there is no way to modify the file extension or remove the version from the name of the file. In previous versions, you could specify the archive name via the command line, which is ideal for compilation in CI tools like Jenkins.

**Comment by graemerocher** [comment]
Add `apply:'war` to your `build.gradle` to apply the war plugin

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-profile-repository/commit/2596783fbc1995ebc9c8f9dde7827839f4d0f5a6

**Comment by marcDeSantis** [comment]
Including the gradle war plugin now allows `grails war` to create a war, but it doesn't allow you to pass gradle project properties via the command line (for specifying the war archive name). `gradle war` does allow you to pass in project properties, but it doesn't execute the `:bootRepackage` and `:assemble` tasks, and so the war it creates does not have the embedded server components.

Would it be easier to:

1. Allow `grails war` to accept project properties on the command line and pass them to gradle?
2. Allow `gradle war` to create the archive with the embedded server?

**Comment by graemerocher** [comment]
Using `gradle assemble` will create the war with the embedded server where you can pass in system properties. You can also pass system properties to `grails assemble` (`war` was renamed to `assemble` btw) using `-D` parameters. See https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/assemble.groovy#L15
