### ISSUE TITLE
Abstract Controller's methods are not controller actions in extending controller

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9739]
This is one of the cases from #9731

As discussed on Slack, in single case: `abstract class` located in `grails-app/controllers` should have public methods made controller actions in controllers extending it.

For example:
```
abstract class ParentController {
    def superAction(){ render 'Super action' }
}

class ChildController extends ParentController {}
```
Should cause that ChildController has action superAction and responds by default on `/child/superAction`

**Comment by graemerocher** [comment]
Think this is related to #9615 since abstract controllers are not enhanced at all right now
