### ISSUE TITLE
Cannot add custom build-properties to META-INF/grails.build.info

### ISSUE THREAD

**Issue by yvesf** [grails/grails-core#9740]
I wan't to add more custom properties to the build-info file.
I thought to do it like:

```
buildProperties.inputs.property('my.custom.name', 'my.custom.value')
```

This doesn't work. In `GrailsGradlePlugin#createBuildPropertiesTask(project)` the grails-gradle-plugin sets the default `buildPropertiesContents` as `buildPropertiesTask.inputs.properties`. But in the following it doesn't use the `buildPropertiesTask.inputs.properties` to generate the property file.

This could be modified by changing line: `for(me in buildPropertiesContents) {`
into `for(me in buildPropertiesTask.inputs.properties) {`

Do you agree, does it make sense to prepare this small change as pull-request?

**Comment by graemerocher** [comment]
Seems reasonable yes, pull request welcome
