### ISSUE TITLE
Take advantage of spring-boot autoconfigure jdbc connection in grails-datasource-plugin

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-core#9744]
Currently, there are a lot of hard-coded things in datasource plugin, for example default jdbc-driver is h2,  default jdbc-pool is tomcat-pool. 
Moreover, currently jdbc-driver will be h2 even if it not in classpath, and there is no simple way to configure other jdbc-pool than tomcat-pool (for example, HikariCP).

spring-boot can detect jdbc-driver based on url, pool based on classes available in classpath, and so on.

**Comment by allnightlong** [comment]
**Grails default driver hardcode:**
https://github.com/grails/grails-core/blob/master/grails-plugin-datasource/src/main/groovy/org/grails/plugins/datasource/DataSourceGrailsPlugin.groovy#L132
**spring-boot autodetect:**
https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/jdbc/DatabaseDriver.java#L230


**Default jdbc pool hardcode:**
https://github.com/grails/grails-core/blob/master/grails-plugin-datasource/src/main/groovy/org/grails/plugins/datasource/DataSourceGrailsPlugin.groovy#L193
**spring-boot autodetect:**
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceBuilder.java#L116

**Comment by graemerocher** [comment]
We cannot use Spring Boot auto configure for JDBC because it does not integrate with Grails' support for multiple data sources. We could borrow some features and try and integrate the two, but right now the plugin is needed.

**Comment by graemerocher** [comment]
Just an update, I forked these classes and adapted them to our needs with GORM https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/jdbc/DataSourceBuilder.java

It would now be possible to use this replacement and improve Grails core

**Comment by allnightlong** [comment]
I couldn't find this class (may be change of package/classname?).

Also I didn't get your multiple datasource's point.
It is possible to configure spring boot with several datasource: http://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-two-datasources

**Comment by artemik** [comment]
Is it possible now to set a custom data source (HikariCP for example)?

**Comment by graemerocher** [comment]
Yes it is

**Comment by hnatiukdm** [comment]
@graemerocher can you, please, provide an example or point to right direction to check it out?
