### ISSUE TITLE
can't exclude domain classes when packaging a binary plugin

### ISSUE THREAD

**Issue by donalmurtagh** [grails/grails-core#9748]
I'm packaging a Grails 2.5.3 plugin as a binary via `grails package-plugin --binary`. I want to exclude all domain classes (regardless of which package they're in) so I added the following to the plugin descriptor
```
def pluginExcludes = ['grails-app/domain/**']
```
But this does not exclude them, the following also does not work
```
def pluginExcludes = ['grails-app/domain/*']
```

**Comment by graemerocher** [comment]
2.5.x is in maintenance mode
