### ISSUE TITLE
[3.1.1] Forward not send original params for target method

### ISSUE THREAD

**Issue by marcioaug** [grails/grails-core#9750]
GET http://localhost:8080/books [WORKING]
GET http://localhost:8080/books/1 [WORKING]
PUT http://localhost:8080/books/1 [WORKING]

GET http://localhost:8080/index [WORKING, output: index null]
GET http://localhost:8080/index/1 [output: index null]
GET http://localhost:8080/show/1 [output: {"message":"Not Found","error":404}]
PUT http://localhost:8080/update/1 [output: {"message":"Not Found","error":404}]

It works only if change otherUpdate method to:

``` groovy
    def otherUpdate() {
        println params.id
        forward action: "update", params: [id: params.id]
    }
```

or

``` groovy
    def otherUpdate() {
        println params.id
        forward action: "update", params: params
    }
```

In Grails 2 all parameters are sent by default. Was this an intentional change or a bug?

I created this app with profile rest-api.

Example code:
[forward_example.zip](https://github.com/grails/grails-core/files/153445/forward_example.zip)

``` groovy
class UrlMappings {
        "/books"(resources: 'book')
        "/index/$id?"(controller: 'book', action: 'otherIndex')
        "/show/$id"(controller: 'book', action: 'otherShow')
        "/update/$id"(controller: 'book', action: [PUT: 'otherUpdate'])
        "500"(view: '/error')
        "404"(view: '/notFound')
    }
}
```

``` groovy
class BookController {

    def otherIndex() {
        println params.id
        forward action: "index"
    }

    def otherShow() {
        println params.id
        forward action: "show"
    }

    def otherUpdate() {
        println params.id
        forward action: "update"
    }

    def index(Long id) {
        render "index $id"
    }

    def show() {
        render "show"
    }

    def update() {
        render "update"
    }
}
```

**Comment by jdbeutel** [comment]
Incidentally, I am seeing the opposite problem on Grails 2.5.3:  the params provided to the forward() method are ignored, and only the original params are available to the target method.

**Comment by jdbeutel** [comment]
I'm wrong.  Simple params are forwarded after all, by adding them to the forwarding URL.  However, param names containing a dot (.) are skipped by WebUtils.appendEntry():  "multi-d params handled by recursion".  In any case, this seems irrelevant to the current issue.
