### ISSUE TITLE
ForkedGrailsProcess should honor the grails.reload.enabled property

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#9752]
The ForkedGrailsProcess includes the spring-loaded java agent unconditionally. For testing (or when `grails.reload.enabled` is set to false), the agent should not be loaded. The agent introduces a performance penalty which can be significant for large unit/integration test runs.

The fix is pretty simple, in ForkedGrailsProcess:55:

`boolean reloading = Environment.current.isReloadEnabled()`

**Comment by longwa** [comment]
This may only be relevant for the 2.x branch, I haven't looked at 3.x to see if the same problem exists.

**Comment by longwa** [comment]
Hmmm, I could be shooting myself in the foot here (as the author of the Guard plugin). I think it should be possible to override either on or off via the `grails.reload.enabled` property. If that property isn't set, it should default to on for DEVELOPMENT and off for anything else.

**Comment by graemerocher** [comment]
Note that 2.5.4 will likely be released tomorrow so if you want this in we will need the pull request pronto
