### ISSUE TITLE
 GRAILS-11787: hasOne are not initiated as bidirectional (OneToOne) #2919 

### ISSUE THREAD

**Issue by kapilanA** [grails/grails-core#9753]
Users

    Role
    These two tables should have bi-directional relationship for security purposes.
    so i have followed "hasOne" combination in Users table and "belongs to " in Role table.But bi-directional relationship is not happening.
    Can anyone please help in this ?
    class User
    {

    Long number
    Integer inhabitants

    static hasOne = [ role: Role]

    static constraints = {
    role nullable: true, unique: true
    }

class Role
{

  Users user
static belongsTo = [user: Users ] 
 static constraints = {
}

}

**Comment by graemerocher** [comment]
You need to provide more information and correct the formatting of your issue. What is not happening? What is the behaviour you are seeing that you believe to be erroneous?

**Comment by kapilanA** [comment]
Thanks for yours quick reply.
i have to keep the bi-directional relationship in two domains.
1. Users
2. ShiroUser

    [class User
    {
     Long number
    static hasOne = [ auth: ShiroUser]

    static constraints = {
    auth nullable: true, unique: true
    }](url)

2. ShiroUser
[class ShiroUser
{

	Users user 
	static belongsTo = [user: Users ]  // here i tried with belongsTo, without belongsTo option and all.
	static constraints = 
	{

	}

}](url)

Here when we are doing like this, the foreign key is available on ShiroUser table only. But i would like to add foreign key in Users table also.
So that i can achieve the two way access of data.
In the older version of grails 1.0.3 it was like this, so now we are upgrading it to grails 2.4.4 version.
Please help me and show some good direction to solve this problem.

Thanks & Regards
Kapilan A

**Comment by graemerocher** [comment]
`hasOne` always stores the key in the child class, if you don't want this just define a regular property:

``` 
ShiroUser auth
```

**Comment by kapilanA** [comment]
Logically Its Correct.
But if we keep only the "Shiro User auth" in Users table, we will not able to save obj.
It will give error like cyclic mapping.
Please help me to access the data from both domains.

**Comment by graemerocher** [comment]
Then you have to make one side `nullable`
