### ISSUE TITLE
Databinding fails when creating a Domain Class from a nested map outside a request context

### ISSUE THREAD

**Issue by hbogaards** [grails/grails-core#9755]
In Grails 3.1.1 and 3.1.2 creating a new Domain Class instance from a nested map fails and creates a empty instance. This is in a service method that is called from within a `task` in a controller.

``` Groovy
BindController {
    def bindService
    def add() {
        def reqMap = [:]
        request.withFormat {
            json {
                log.info "request is JSON\n${request.JSON}"
                reqMap = request.JSON as Map
            }
        }

        def author = new Author(reqMap)
        author.save()

        task {
            bindService.storeAuthor(reqMap)
        }
    }
}

BindService {
    def store(reqMap) {
        def result = Author.withTransaction { status ->
            def author = new Author(reqMap)
            if (author.hasErrors()) {
                author.errors.each {
                    log.error it
                }
            }               
        }
    }
}
```

This causes an empty Author instance with an error
`Error in object 'Author': codes []; arguments []; default message [null]`

I have a test application that demonstrates the problem, see https://github.com/hbogaards/grails3-databinding.

**Comment by hbogaards** [comment]
Diving into the data binding code I found that the cause of this is an `NullPointerException` that occurs in `org.apache.catalina.connector.Request.getServletContext()` called from `org.grails.web.mime.HttpServletRequestExtension.getMimeTypes(HttpServletRequest request)`.

My guess is that the databinding code (from `grails-web-databinding`) assumes it always has an active/valid request while binding

**Comment by graemerocher** [comment]
You are passing in the `params` object which is associated with the controllers and the request, hence the issue. I am not sure yet whether this should be regarded as a valid use case.

**Comment by hbogaards** [comment]
The code in the opening post is a bit too condensed.

What we do in our big application (and I also do in the test application), is create an nested Map from the incoming data (by parsing the JSON or XML and creating a new Map from it) and then create the Domain instance.

At another place in the application we have this:
        void setProcessed(String process, DateTime when) {
            Processed p = new Processed(processor: process, dateProcessed: when)
    }

And even this creates a `Processed` instance that is empty. Both `processor` and `dateProcessed` are `null`.

This method is called from the Service that is called from within the `task` in the Controller

**Comment by hbogaards** [comment]
Updated opening post with the code of the test application.

If this is the wrong way of doing, please point me in the right direction.
It is very counter-intuitive that the normal Groovy map-based constructor of a Domain class can fail.

We have a Service that can be called from a Quartz job and a asynchronously from a Controller.
When called from the Quartz job the map-based constructors always work as expected, when called from the Controller they fail,but not always (seems like a race-condition).

I'm going to try to catch the exception and add the stacktrace to this issue

**Comment by hbogaards** [comment]
The sanitized exception as caught by `DataBindingUtils.bindObjectToDomainInstance()`:
[grails-constructor-issue-stacktrace.txt](https://github.com/grails/grails-core/files/156453/grails-constructor-issue-stacktrace.txt)

**Comment by jeffbrown** [comment]
Are you only seeing the problem when using async?

**Comment by hbogaards** [comment]
When I remove the `task` from the Controller and call the Service direct the problem does not occur

**Comment by hbogaards** [comment]
I have been looking further into this.

And I have found 'workaround' (not sure how safe it is) by calling `request.startAsync()` before starting the `task`. This gives the `request` a slightly longer livespan (there is an `asyncTimeout`).

But I think I am also zeroing in on the cause of the bug. Actually I believe there are 2 bugs, 1 in the Grails code and 1 in the Tomcat/Catalina code.

The Tomcat bug is that after the `request` is done, it is recycled (method `recycle()` is called. This causes the clearing of most properties of the request, including the `Context`. If a caller calls the method `getServletContext()` on a recycled `request` it causes a `NullPointerException` , because this method is implemented as `getContext().getServletContext()` and `getContext()` return `null`. I believe the `getServletcontext()` method should return `null` in this situation.

The Grails bug/problem is (I think) located in the `ControllerDomainBindingApi` around here:

```Groovy
public static void initialize(Object instance, Map namedArgs) {
    GrailsDomainClass dc = getDomainClass(instance);
    if (dc == null) {
        DataBindingUtils.bindObjectToInstance(instance, namedArgs);
    }
    else {
        DataBindingUtils.bindObjectToDomainInstance(dc, instance, namedArgs);
        DataBindingUtils.assignBidirectionalAssociations(instance, namedArgs, dc);
    }
    autowire(instance);
}

private static GrailsDomainClass getDomainClass(Object instance) {
    GrailsDomainClass domainClass = GrailsMetaClassUtils.getPropertyIfExists(instance, GrailsDomainClassProperty.DOMAIN_CLASS, GrailsDomainClass.class);
    if (domainClass == null) {
        GrailsWebRequest webRequest = GrailsWebRequest.lookup();
        if (webRequest != null) {
            ApplicationContext applicationContext = webRequest.getApplicationContext();
            if(applicationContext != null) {
                GrailsApplication grailsApplication = applicationContext.containsBean(GrailsApplication.APPLICATION_ID) ?
                    applicationContext.getBean(GrailsApplication.APPLICATION_ID, GrailsApplication.class) : null;
                if (grailsApplication != null) {
                    domainClass = (GrailsDomainClass) grailsApplication.getArtefact(DomainClassArtefactHandler.TYPE, instance.getClass().getName());
                }
            }
        }
    }

    return domainClass;
}
```

What I don't understand about this code, is why the `webRequest` is needed to get the `applicationContext` (and the `grailsApplication`). Aren't there other ways to get to those?
And I would expect the `GrailsWebRequest.lookup()` too return `null` if it is called from code inside a `task`

Am I on the right track to solve this?
Or am I chasing shadows?

**Comment by hbogaards** [comment]
Would anything go wrong if I replace the `webRequest.getApplicationContext()` with `Holders.getApplicationContext()` or `Holders.findApplicationContext()` ?

**Comment by hbogaards** [comment]
Further in my investigation.

I am wondering if the `WebRequestPromiseDecorator` might be the real culprit.
It makes a new `GrailsWebRequest` with a shallow copy of the `request`, the `response`, the `servletContext` and the `applicationContext`.
But there is no guaranty the `request` and the `response` stay valid during the lifetime of the `Promise`

**Comment by hbogaards** [comment]
I see 2 solutions for this, both in the `WebRequestPromiseDecorator`, but I cannot fully grasp the full consequences of these:

First solution:
Add a call to `request.startAsync()` and call `AsyncContext.setTimeout(-1)` to prevent  timeouts.
And add a call to `AsyncContext.complete()` to the `finally`

So the `decorate` becomes:
````Groovy
@Override
def <D> Closure<D> decorate(Closure<D> c) {
    return (Closure<D>) {  args ->
        def newWebRequest = new GrailsWebRequest(webRequest.currentRequest, webRequest.currentResponse, webRequest.servletContext,webRequest.applicationContext)
        newWebRequest.addParametersFrom(webRequest.params)
        WebUtils.storeGrailsWebRequest(newWebRequest)

        AsyncContext asyncContext = newWebRequest.currentRequest.startAsync()
        asyncContext.setTimeout(-1)
        try {
            return invokeClosure(c, args)
        }
        finally {
            asyncContext.complete()
            newWebRequest.requestCompleted()
            WebUtils.storeGrailsWebRequest(webRequest)

        }
    }
}
````

Second solution:
Use the `AsyncGrailsWebRequest` instead of the normal `GrailsWebRequest`

So the `decorate` becomes
````Groovy
@Override
def <D> Closure<D> decorate(Closure<D> c) {
    return (Closure<D>) {  args ->
        def newWebRequest = new AsyncGrailsWebRequest(webRequest.currentRequest, webRequest.currentResponse, webRequest.servletContext,webRequest.applicationContext)
        newWebRequest.addParametersFrom(webRequest.params)
        WebUtils.storeGrailsWebRequest(newWebRequest)

        newWebRequest.startAsync()
        try {
            return invokeClosure(c, args)
        }
        finally {
            newWebRequest.requestCompleted()
            WebUtils.storeGrailsWebRequest(webRequest)

        }
    }
}
````

I am not sure what the possible problems are with both solutions and which is preferable.

**Comment by purpleraven** [comment]
In #10422 stack trace has been provided
