### ISSUE TITLE
"Could not resolve view" exceptions when executing a REST-API profile app via Runnable JAR or deploying to Tomcat

### ISSUE THREAD

**Issue by steyng** [grails/grails-core#9758]
Issue #9710 is still occurring in Grails-3.1.2 in the following environment:

Environment:

Windows 8.1 Enterprise
Grails-3.1.2
JDK1.8.0_73

Works on Linux (Oracle Enterprise Linux 7.0, Grails-3.1.2, JDK1.8.0_73).

On windows, the gson-classes are not being compiled correctly.  For example, I am expecting:

../build/gson-classes/main/appname_application_index_gson.class

but on windows you get

..\buikld\gson-classes\main\index_gson.class

**Comment by graemerocher** [comment]
Probably related to #9631 

Please replace the line

     classpath "org.grails.plugins:views-gradle:1.0.1"

With

      classpath "org.grails.plugins:views-gradle:1.0.3"

In your build.gradle file

**Comment by steyng** [comment]
Thank you.  That did the trick.  Working as outlined in #9631.
