### ISSUE TITLE
Multiple datasources failure in integration test with domain.datasource.gormFunction() notation

### ISSUE THREAD

**Issue by wentersjos** [grails/grails-core#9760]
It looks as if since 3.1.0 domain classes mapped to multiple datasources seem to fail in integration tests if the non-default datasource is specified, and the domain(class).datasource.gormFunction() notation is used.

Say, Book is a domain class, and it is mapped to de DEFAULT datasource and to a datasource "staven", with:

  static mapping = { datasources(['staven', 'DEFAULT']) }

then, e.g.

  Book.staven.count()
  new Book(...).staven.save()

fail with the message "No such property: staven".

It worked in 3.0.2, but fails starting with 3.1.1, and so probably, starting with 3.1.0.

I'm aware of the following bugs reported that seem tangential to this issue:

https://github.com/grails/grails-core/issues/9011
https://github.com/grails/grails-core/issues/9690

and also

https://github.com/grails/grails3-functional-tests/blob/master/datasources/src/integration-test/groovy/functionaltests/MultipleDataSourcesSpec.groovy
https://github.com/graemerocher/grails3-datasources.git

But none of these seem to address the issue where one-and-the-same domain class is mapped to two datasources at-once and the domain(class).datasource.gormFunction() notation is used.

Please see https://github.com/wentersjos/grails3-datasources.git for a sample project that shows the bug. This project was cloned from https://github.com/graemerocher/grails3-datasources.git, and then adapted. Read gradle.properties first. Then see Asi.groovy and MultipleDataSourceSpecgroovy.

**Comment by graemerocher** [comment]
Can be worked around with

```
Book.staven.saveAll(new Book(...))

```
Undecided whether we will add back support for the namespace in this way.

**Comment by hbogaards** [comment]
The `Book.staven.saveAll(new Book(...))` is not a complete replacement for `new Book(...).save(...)`, because `saveAll()` does not have the normal parameters that `save()` has, like `flush` and `failOnError`

**Comment by graemerocher** [comment]
Agreed, it is not ideal

**Comment by graemerocher** [comment]
`saveAll(..)` supports arguments in GORM 6
