### ISSUE TITLE
[3.1.3] After changes to Validateable trait Command objects cannot be properly mocked with GroovyMock

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9761]
This is a minor issue and maybe should be reported in Spock? When using GroovyMock() for Validateable object in Grails 3.1.3 it will fail on calling `validate()` method. Please see below.
```
import spock.lang.Specification
import grails.validation.Validateable

class MockingCommandSpec extends Specification {
	
	void 'ensure command is mocked properly'(){
		ErrorCommand command = GroovyMock()

		expect:
		command.validate()
	}
}

class ErrorCommand implements Validateable {}
```
This test will fail on `command.validate()` with following stacktrace:
```
java.lang.IllegalArgumentException: wrong number of arguments
	at org.spockframework.mock.runtime.GroovyMockMetaClass.doInvokeMethod(GroovyMockMetaClass.java:86)
	at org.spockframework.mock.runtime.GroovyMockMetaClass.invokeMethod(GroovyMockMetaClass.java:42)
	at error.MockingCommandSpec.ensure command is mocked properly(MockingCommandSpec.groovy:12)
```
It's probably because of validate method being now `boolean validate(Closure... adHocConstraintsClosures)`

It works fine with `Mock()` instead of `GroovyMock()`.

**Comment by jeffbrown** [comment]
There is a problem with `Validateable` but I don't think the test as written is valid anyway.  The following test doesn't have anything to do with `Validateable` and fails too:

    class ValidateableMockSpeck extends Specification {

        @Issue('grails/grails-core#9761')
        void 'ensure command is mocked properly'(){
            given:
            SomeCommand command = GroovyMock()

            expect:
            command.validate()
        }
    }

    class SomeCommand {
        boolean validate() {
            true
        }
    }

That test fails like this:

    Condition not satisfied:

    command.validate()
    |       |
    |       false
    Mock for type 'SomeCommand' named 'command'


    	at grails.validation.ValidateableMockSpeck.ensure command is mocked properly(ValidateableMockSpeck.groovy:14)
