### ISSUE TITLE
either version of grail seems to be un-downloadble in China

### ISSUE THREAD

**Issue by yshi2003** [grails/grails-core#9766]
just has no response.

**Comment by rainboyan** [comment]
Because Amazon S3 was blocked by GFW, U can download it by a ladder, or build it from the source code, [Building A Local Grails Installation](https://github.com/grails/grails-core/wiki/Building-A-Local-Grails-Installation)

**Comment by sbglasius** [comment]
Would using https://git-lfs.github.com/ be an option for people in China?

**Comment by graemerocher** [comment]
Nothing we can do about this, if someone wants to setup a mirror of the releases in China feel free
