### ISSUE TITLE
GORM 5 stores non-ID ObjectId fields as strings in MongoDB

### ISSUE THREAD

**Issue by mpashkovskiy** [grails/grails-core#9767]
1 Define an object like

> class Person{
>   ObjectId id
>   ObjectId accountId
>   String name
> }

2 Create an instance

> def p = new Person(accountId: new ObjectId(), name: 'Bob')

3 Save it

> p.save flush: true

Actual behavior: Collection person in Mongo will contain
> "_id" : ObjectId("..."),
> "accountId" : "56d952fdc25c791c1c00b053",
> name: 'Bob',
> "version" : NumberLong(0)

Expected behavior: Collection person in Mongo will contain
>  "_id" : ObjectId("..."),
> "accountId" : ObjectId("56d952fdc25c791c1c00b053"),
> "name": 'Bob',
> "version" : NumberLong(0)

**Comment by graemerocher** [comment]
This duplicates https://github.com/grails/grails-data-mapping/issues/661
