### ISSUE TITLE
Grails 3.1.2 and 3.1.3 - automatically runs all get-methods from a domain while calling domain.validate() method

### ISSUE THREAD

**Issue by sting2804** [grails/grails-core#9768]
I have a domain with a few get-methods for transient fields.
When i create an instance and run validate() method, all get-methods run. It isn't a valid behavior.
If i set Grails version to 3.1.1, the methods aren't running.
**Domain example:**
```
@AutoClone
class Patient extends DomainRestResource {

    def springSecurityService
    def personalDataService

    String codeName
    String screeningNumber
    String randomizationNumber
    String diagnosisOnAdmission

    static transients = ['arrivingOnInMinutes', 'nextVisitDateTime', 'nextVisitTime',
                         'fullName', 'lastNameAndInitials', 'dateOfBirth', 'dateOfDeath', 'gender',
                         'contacts', 'state', 'city', 'address', 'countryCode', 'additionalAddress', 'postcode', 'medicalRecordNumber']

    static belongsTo = [referrer: Referrer]

    def beforeInsert() {
        lastUpdatedBy = springSecurityService.getCurrentUser() as Employee
        lastUpdatedOn = new Date()
        codeName = codeName?.toUpperCase()
    }

    def beforeUpdate() {
        lastUpdatedBy = springSecurityService.getCurrentUser() as Employee
        lastUpdatedOn = new Date()
        codeName = codeName?.toUpperCase()
    }

    static constraints = {
        codeName size: 1..3
        /* other fields */
    }

    String getCountryCode() {
        return personalDataService.getCountryCodeForPatient(this)
    }
    String getAddress() {
        return personalDataService.getAddressForPatient(this)
    }
}
```
**running validate method:**
`patient.validate()`
**DomainRestResource.groovy**
```
abstract class DomainRestResource extends UniversalRestResource {

    @Autowired
    def connectionManager
    @Autowired
    def userActivityService
    @Autowired
    def dataSource

    protected transient int limit
    protected transient int offset
    private transient String tableName

    /*
    some logic
    */
}
```

**Comment by droggo** [comment]
This is issue: #9749 but it was fixed on 3.1.3. Are you sure you face it on newest version?

**Comment by sting2804** [comment]
Yes, i'm sure i face it on Grails 3.1.3.

**Comment by sting2804** [comment]
Guys, please, fix this issue. I cannot upgrade my work project because of this issue. Thanx

**Comment by jeffbrown** [comment]
@sting2804 I am having trouble reproducing the problem with 3.1.4.  I expect there is some specific combination of factors that must be happening in your app.  Can you provide a link to a sample 3.1.4 app which demonstrates the problem?

Thanks for the feedback.

**Comment by jeffbrown** [comment]
I thought this was fixed and the issue was accidentally left open.

**Comment by jeffbrown** [comment]
Given a domain class like this:

    package demo

    class Patient {

        String name

        static transients = ['somethingElse']

        String getSomethingElse() {
            throw new UnsupportedOperationException()
        }
    }

The following unit test passes with 3.1.1, 3.1.3 and 3.1.4.  It fails with 3.1.2.

    package demo

    import grails.test.mixin.TestFor
    import spock.lang.Specification

    @TestFor(Patient)
    class PatientSpec extends Specification {

        void "test validation"() {
            expect:
            new Patient(name: 'jeff').validate()
        }
    }

**Comment by sting2804** [comment]
Ура! Sorry for my russian emotions) on 3.1.4 everything works fine!

**Comment by sting2804** [comment]
Thank You!
