### ISSUE TITLE
Grails 3.1 Angular profile can't include multiline script tag in angular JS templates

### ISSUE THREAD

**Issue by sapanparikh18** [grails/grails-core#9772]
To reproduce this issue, do the following
1. Download the demo project from https://github.com/sapanparikh18/Grails-3.1-AngularJS.git
2. Refresh bower dependencies
3. Run project
4. Navigate to http://localhost:8080/#/user/create
5. If there are no JS errors then navigate to grails-app/assets/javascripts/myapp/user/templates/create.tpl.html
6. Add the following script at the end of the page 
```
<script>
    alert("test");
</script>
```
There will be a JS error you will get.
Now remove that script and add the following
`<script>alert("test");</script>`

Refresh the page and things will start working.
In nutshell if we add multiline script tag in ng-view then some kind of encoding/decoding is adding 'n' for every new line. This is causing issues while adding ad-hoc scripts in the page.

**Comment by KerchumA222** [comment]
Out of curiosity, why are you trying to include script tags in angular templates? Also does this bug affect markup itself or just the script tags? (I haven't tried to reproduce it yet)

**Comment by sapanparikh18** [comment]
@KerchumA222 mainly to initialize components. For instance I would prefer to put the following code there

```
$(document).ready(function() {
    $('select').material_select();
  });
            
```
I know that I can initialize this in angular controller as well but I  prefer any javascript code that refers to DOM elements outside of my controllers. Makes my angular related javascripts more independent from the views.

**Comment by KerchumA222** [comment]
Including script tags isn't the 'right' way to do things in angular. I think using a directive would be more appropriate for your situation.

**Comment by graemerocher** [comment]
Don't see how this is a Grails bug
