### ISSUE TITLE
Validation fails when setting domain object property in controller

### ISSUE THREAD

**Issue by sapanparikh18** [grails/grails-core#9773]
I am using grails angular profiles and trying to set value of a domain class field in controller
```
def save(User user) {
        if (user == null) {
            transactionStatus.setRollbackOnly()
            render status: NOT_FOUND
            return
        }
        user.firstName = "sapan"
        if (user.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond user.errors, view:'create'
            return
        }

        user.save flush:true

        respond user, [status: CREATED, view:"show"]
    }
```

See how in the above code I have set `user.firstName = "sapan"` and still the user.hasErrors() returns true plus the validation fails saying "firstName can not be null"
This is happening in multiple projects and multiple fields. I usually do to set values from session like loggedIn userId etc.

**Comment by droggo** [comment]
try changing `if (user.hasErrors()) {` to `if (!user.validate()) {`

**Comment by sapanparikh18** [comment]
@droggo you are right `if (!user.validate()) {` worked. But would that mean I would have to change all the generated code? Because in all my save/update actions I am setting loggedInUserId. Is this a real bug or a feature?

**Comment by sapanparikh18** [comment]
Taking it one step further with following action it still does not work. I think in the case of nested entities?

```
@Transactional
    def save(Opening opening) {
        if (opening == null) {
            transactionStatus.setRollbackOnly()
            render status: NOT_FOUND
            return
        }
        opening.createdBy = User.get( session.userId)
        opening.organization =  Organization.get( session.orgId)
        println opening.validate()
        opening.errors.each {println it}
        if (opening.validate()) {
            opening.save flush:true
            println "data saved--"
            respond opening, [status: CREATED, view:"show"]
        }else{

            println "validation failed"
            transactionStatus.setRollbackOnly()
            respond opening.errors, view:'create'
        }


    }
```

**Comment by droggo** [comment]
This `save()` method you have provided is from generated code? How did you modify it?

I think that in this case validation is done for user after binding from request parameters automatically. It means that user object would have firstName set if firstName was send in request and then `hasErrors()` would work fine. But if you set properties like `firstName` later in the method, which are not binded automatically, you have to do another validation, `hasErrors()` is not validating, it's just returning status of previous validation.

I don't think this is a bug, you are modifying code, and this must be done in a correct way.

**Comment by sapanparikh18** [comment]
@droggo are you saying that hasErros will not run validation again? I have done this many time in grails 2.4+
Also, the whole function is automatically generated. Only one line I have added is  user.firstName = "sapan" 

This is a very valid scenario, things like `loggedInUserId` should come from session and not form the client to be bound to the object.

**Comment by droggo** [comment]
In my understanding `hasErrors()` is not executing validation, it is just returning results of latest validation performed. 

This is documented here: http://grails.github.io/grails-doc/latest/ref/Domain%20Classes/hasErrors.html

You need to do `validate()` `save()` or execute Data Binding on element. I don't believe this was different in 2.4+

**Comment by jeffbrown** [comment]
> are you saying that hasErros will not run validation again? I have done this many time in grails 2.4+

Yes, that is correct.  `hasErrors()` does not run validation again, and never has.
