### ISSUE TITLE
Auto reloading doesn't work for inline plugins in Grails 3.1.3.

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#9775]
I've followed these instructions:
http://grails.github.io/grails-doc/3.1.3/guide/single.html#plugins
http://grails.io/post/138665751278/grails-3-gradle-multi-project-builds

This is what I've done:

$ grails create-app myapp
$ grails create-plugin myplugin

Then I've created a settings.gradle file in the parent directory with this content:

include 'myapp', 'myplugin'

So the directory structure is:

PROJECT_DIR
  - settings.gradle
  - myapp
    - build.gradle
  - myplugin
    - build.gradle

Then in build.gradle of myapp I've added:

grails {
  exploded = true
  plugins {
    compile project(':myplugin')
  }
}

In myapp I can correctly use classes of myplugin so the dependency is working
but auto reloading works only for files in myapp not for files in myplugin.

This is the application status
- Environment: development
- App profile: web
- App version: 0.1
- Grails version: 3.1.3
- Groovy version: 2.4.6
- JVM version: 1.8.0_74
- Reloading active: true

Running on Linux Mint 17.3

**Comment by donald-jackson** [comment]
This also doesn't work for me - perhaps a different issue though.

Adding exploded = true to the grails block gives me this error

```
> Could not resolve all dependencies for configuration ':SampleApp:runtime'.
   > Module version sample:Sample:0.1.1, configuration 'runtime' declares a dependency on configuration 'exploded' which is not declared in the module descriptor for org.grails.plugins:api-core:0.5
```

Another thing to consider is - I am using externalized configuration files as described here : http://grails.1312388.n4.nabble.com/Grails-3-External-config-td4658823.html - when declaring inline plugins using this new mechanism (as opposed to the dependencies block) the application.yml of the plugins presumably gets loaded AFTER the externalized configurations have been loaded - thereby overwriting them. In order to get my application to run using inline plugins in the grails {} block I had to remove datasource configurations from those inline plugins - no big deal but might be worth checking out.

**Comment by donald-jackson** [comment]
My apologies - I think the previous comment I made was my fault, but this is useful for others to know - if you are getting the error as per above, make sure the dependency plugins are running the same version as your app (or at least a version that is aware of the exploded parameter) - 3.0.15 in my case and then do a gradle assemble on those plugins.

Now that I have hot-reloading taking place I still unfortunately have a new error, but I believe its unrelated to this one so I will rather create a new issue here https://github.com/grails/grails-core/issues/9825

**Comment by donald-jackson** [comment]
Just following on my previous comment - it was working, perhaps due to some temporary config overwrite or something like that, but due to other issues I was facing I had to fully clean/refresh all my plugins/project and it has ceased functioning.

**Comment by graemerocher** [comment]
So I uploaded the following example: https://github.com/graemerocher/grails-multi-project-build-example

Which works fine for me when modifying the `FooController.groovy` provided by the plugin if I start the application with `grails run-app`.

So right now I cannot reproduce this, but feel free to upload an example that demonstrates the issue and I will be happy to re-open.

**Comment by atasc** [comment]
I've attached the project with a TestController that extends a ControllerBase in myplugin.
TestController->index() calls ControllerBase->sayHello(), the changes to ControllerBase->sayHello()
are not reloaded.
[grails-multi-project.tar.gz](https://github.com/grails/grails-core/files/213295/grails-multi-project.tar.gz)

**Comment by graemerocher** [comment]
Will take a look. Thanks

**Comment by imaress** [comment]
@graemerocher I download your project and after download some dependencies and execute run-app command it's works!!, but with my local version of grails 3.1.4 and creating a new project it doesn't. I try to work with the new rest api profile:
grails create-app my app -profile=rest-api
grails create-plugin myplugin -profile=rest-api
and no auto reloading works. I think may be some dependencies version problem. 
And your project works with inline config plugins but what about this config:
```
grails {
exploded=true
plugins {
compile project (":myplugin")
}
}
```
Thanks for all effort!!
