### ISSUE TITLE
Unable to unit test output of generated GSON views

### ISSUE THREAD

**Issue by mpas** [grails/grails-core#9778]
When trying to unit test a controller which generates JSON using GSON views the response.json / response.text contain no data also the response.status seems to be not according to the status that is in the template.

example:
```
class TestMeController {

    def index() {
        println "i am called"
    }
}
```
The view
```
response.status 201

json {
    say "hello"
}
```
```
@TestFor(TestMeController)
class TestMeControllerSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }

    void "test something"() {
        when:
        controller.index()

        then:
        println response.text
    }
}
```
response.text and response.json are always empty

**Comment by jeffbrown** [comment]
Isn't this the same behavior you would see with GSP or other view technologies supported by Grails?

**Comment by mpas** [comment]
@jeffbrown Thanks for the reply! Could be a misunderstanding on my side. This is my first go in trying to unit test controller view rendering response. I read the documentation (grails 3.x) and was under the impression that the response could be checked. This came from reading the chapter "Testing Template Rendering" and "Testing XML and JSON Responses". In those chapters I see stuff like "response.json.book == 'Great" etc..

**Comment by jeffbrown** [comment]
> This came from reading the chapter "Testing Template Rendering" and "Testing XML and JSON Responses". In those chapters I see stuff like "response.json.book == 'Great" etc..

Those examples in the user guide are testing different types of scenarios than you describe above.  Those examples are testing controller actions which explicitly invoke `render` which will populate the response.  You are testing a controller which doesn't explicitly do anything with the response, so the response is not populated.  If you want to test the full cycle you can use an integration test.

I think there are scenarios where unit testing GSON views makes sense.  We could provide an appropriate test mixing or similar to facilitate that.  I think a feature request at https://github.com/grails/grails-views/issues is a good idea.

**Comment by mpas** [comment]
After reading the documentation again, it makes sense. But example was actually triggered by a trait that i have implemented that uses the render method using a specific template. 

In that trait i capture an event and render a template. In this case the response is still empty.

```    
trait JsonErrorResponse {
    def renderException(BaseException e) {
        log.error e.toString()
        render view: "/genericErrorResponse", model: [e: e]
    }

    def handleBadRequestException(BadRequestException e) {
        renderException(e)
    }
}
```

**Comment by jeffbrown** [comment]
That is a different scenario than the one described in the initial report above.

If you look at the "Test View Rendering" section of the user guide you will see an example that looks like this:

    class SimpleController {
        def home() {
            render view: "homePage", model: [title: "Hello World"]
        }
        …
    }

And a corresponding test:

    import grails.test.mixin.TestFor
    import spock.lang.Specification
    @TestFor(SimpleController)
    class SimpleControllerSpec extends Specification {

        void 'test home'() {
            when:
            controller.home()

            then:
            view == '/simple/homePage'
            model.title == 'Hello World'
        }
    }

If something like that isn't working then I think that would be a bug.

**Comment by jeffbrown** [comment]
The idea here is that the unit test is focused on what the controller is doing, not what the framework does after the controller action has returned.

**Comment by mpas** [comment]
I am indeed mixing up stuff! Apologies for that. I mixed up the terminology between views and templates. So template rendering should be able to use response.text etc. The documentation also status that JSON response could be captured using `response.json`. But i guess this also applies to templates. This was unclear for me when reading the documentation.

The mentioned solution is indeed to use view and model. This works.

**Comment by seja145** [comment]
@jeffbrown I think their is an issue with the sample projekt. I can´t test like you shown above. Because the view/ model field is always empty.
