### ISSUE TITLE
incorrect route chosen from UrlMappings

### ISSUE THREAD

**Issue by domurtag** [grails/grails-core#9779]
In my Grails 2.5.3 app, I've defined the following routes in `UrlMappings.groovy`

```groovy
        "/api/$apiVersion/admin/reportingCohort"(controller: 'reportingCohort') {
            action = [GET: "index"]
        }
        "/api/$apiVersion/admin/reportingCohort/$id"(controller: 'reportingCohort') {
            action = [PUT: "update", DELETE: "delete"]
        }
```

I would expect that when a DELETE request is issued for `/api/v1/admin/reportingCohort/1` the `delete` action would be invoked, but instead the `index` action is called

**Comment by jeffbrown** [comment]
With the project at https://github.com/jeffbrown/issue9779 this is what I am seeing...

```
~ $ curl -X GET http://localhost:8080/issue9779/api/v1/admin/reportingCohort/
index action

~ $ 
~ $ curl -X PUT http://localhost:8080/issue9779/api/v1/admin/reportingCohort/1
update action

~ $ 
~ $ curl -X DELETE http://localhost:8080/issue9779/api/v1/admin/reportingCohort/1
delete action

~ $ 
```

**Comment by donalmurtagh** [comment]
It looks like you're bug free. I'll see if I can figure out why you're seeing different behaviour than I am. Feel free to close and I'll reopen if I can find any evidence of a Grails bug.

**Comment by orubel** [comment]
I think in this case there is some confusion with 'controller/action/id' assignment. Need to make sure controller is defined as well as id

**Comment by jeffbrown** [comment]
> Need to make sure controller is defined as well as id

@orubel I think the mapping above that is handling the `DELETE` request does have both of those.

**Comment by jeffbrown** [comment]
@donalmurtagh I will got ahead and close it.  If you narrow in on anything, please just let us know and we can revisit it.  Thanks for the feedback.
