### ISSUE TITLE
Grails 2.5.4: Compile warnings now happening on every action in all controllers.

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#9781]
I upgraded from Grails 2.4.3 to 2.5.4 and now get

| Warning The [$tt__index] action in [xxx.ActivityController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.
null

My controllers import grails.transaction.Transactional
and use the @Transactional(readOnly = true) annotation.

Most controllers are generated with no major changes for now. So it's pretty vanilla.

**Comment by jeffbrown** [comment]
Duplicates #9770
