### ISSUE TITLE
Grails 2.5.4: list-plugin-updates no longer lists updates

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#9782]
Running list-plugin-updates under 2.5.3 I can see there are updates available (for example asset plugin current version is 2.6.10 and can see 2.7.0 is available). Once upgrading to Grails 2.5.4 it shows all plugins are up to date.

**Comment by vonovak** [comment]
it seems to work fine for me

**Comment by graemerocher** [comment]
Nothing has changed in 2.5.4 related to list-plugin-updates so I would suggest this was intermittent connectivity issues

**Comment by zaccak** [comment]
I still get this issue on 2.5.5. On 2.5.3 it works great.
