### ISSUE TITLE
New Feature: Add support for Hibernate 5.1

### ISSUE THREAD

**Issue by augrtur** [grails/grails-core#9783]
Getting the following error when trying to start app under IntelliJ on Windows 2012 Server. Also getting this error when deploying as WAR on Tomcat7 under Amazon Linux.

Running under IntelliJ in CentOS7 is fine.

    ERROR org.springframework.boot.SpringApplication - Application startup failed
    Caused by:   org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.grails.orm.hibernate.cfg.CollectionType.<init>(Ljava/lang/Class;Lorg/grails/orm/hibernate/cfg/GrailsDomainBinder;)V

There is a Stackoverflow mention of this issue:

http://stackoverflow.com/questions/35287393/grails-error-org-springframework-boot-springapplication-application-startup-f

**Comment by graemerocher** [comment]
Upload an example to github with steps to reproduce please

**Comment by KapudanPasha** [comment]
Steps to re-create

1. create-app gorm-hibernate51-error
2. replace build.gradle with attached (it uses Hibernate 5.1)
3. war
4. Deploy to Tomcat 8 or 9
5. Tomcat fails to deploy with error above

Environment - Windows 7 64-bit, jdk1.8.0_71, grails-3.1.3, gradle 2.9

[build.gradle.zip](https://github.com/grails/grails-core/files/175816/build.gradle.zip)

**Comment by KapudanPasha** [comment]
Sample project here - [gorm-hibernate51-error](https://github.com/KapudanPasha/gorm-hibernate51-error)

**Comment by augrtur** [comment]
Thanks for adding that Kapudan.

Regards,

Greg

**Comment by janpenspain** [comment]
Hi gramerocher,

I have the same problem, my environment the web application runs fine under intellj and under windows and centos but when I generated the war only deploys well in ubuntu environments, showing this error in the trace tomcat, does not work or windows or centos.

Caused by: java.lang.NoSuchMethodError: org.grails.orm.hibernate.cfg.CollectionType.<init>(Ljava/lang/Class;Lorg/grails/orm/hibernate/cfg/GrailsDomainBinder;)V

I ask you please to consider, fix this bug before version 3.2 because otherwise many developers can not deploy web applications that using hibernate5 on multiple operating systems 

Thanks for you attention.

Regards,

Jose,

**Comment by AlexKovynev** [comment]
+1, Hibernate 5.0.7, Windows, WAR on Tomcat 8.0.30

**Comment by ndn2016** [comment]
Deploying Grails 3.1.6 to JBOSS EPA 6.4 having the same problem!
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: o
rg.grails.orm.hibernate.cfg.CollectionType.<init>(Ljava/lang/Class;Lorg/grails/orm/hibernate/cfg/GrailsDomainBinder;)V

Thanks & Appreciated!

Regards,
Nam

**Comment by hakanernam** [comment]
Same error here. "run-app" works.

OSX 10.11.4

| Grails Version: 3.1.6
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_77

**Comment by KapudanPasha** [comment]
run-app works but deploying a war to Tomcat 8.0.30 fails with same error as ndn2016

**Comment by ndn2016** [comment]
Any HELP! Would be APPRECIATED!
Deploying Grails 3.1.6 to JBOSS EPA 6.4 having the same problem!
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: o
 rg.grails.orm.hibernate.cfg.CollectionType.(Ljava/lang/Class;Lorg/grails/orm/hibernate/cfg/GrailsDomainBinder;)V

Reverting back to Grails 2.5.x --

Thanks & Appreciated!
Nam

**Comment by graemerocher** [comment]
@ndn2016 the error is most likely because you have not configured `jboss-web.xml` and isolated the Hibernate dependencies. See http://grails.io/post/142674392718/deploying-grails-3-to-wildfly-10

**Comment by KapudanPasha** [comment]
Is there any advice for getting this working in Tomcat?

**Comment by graemerocher** [comment]
Shouldn't be an issue on Tomcat, although make sure you have configured 5.1 correctly http://gorm.grails.org/latest/hibernate/manual/guide/gettingStarted.html#hibernateVersions

**Comment by ndn2016** [comment]
Thanks & Appreciated! -- Graemerocher
Deploying Grails 3.1.6 + hibernate5  to jboss EPA 6.4.x
Continue to have same error.
Here is my build.gradle and jboss-deployment-structure.xml
build.gradle
buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.8.2"
        classpath "org.grails.plugins:hibernate5:5.0.5"
    }
}

version "0.1"
group "eval316h5"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "war"
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"
apply plugin: "asset-pipeline"

ext {
    grailsVersion = project.grailsVersion
    gradleWrapperVersion = project.gradleWrapperVersion
}

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    provided "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"
    compile "org.grails.plugins:cache"
    compile "org.grails.plugins:scaffolding"
    compile "org.grails.plugins:hibernate5"
    compile "org.hibernate:hibernate-core:5.1.0.Final"
    compile "org.hibernate:hibernate-ehcache:5.1.0.Final"
    console "org.grails:grails-console"
    profile "org.grails.profiles:web:3.1.6"
    runtime 'javax.xml.bind:jaxb-api:2.2.12'
    runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.8.2"
    runtime "com.h2database:h2"
    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"
    testRuntime "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
    testRuntime "net.sourceforge.htmlunit:htmlunit:2.18"
}

task wrapper(type: Wrapper) {
    gradleVersion = gradleWrapperVersion
}

assets {
    minifyJs = true
    minifyCss = true
}

jboss-deployment-structure.xml
<?xml version='1.0' encoding='UTF-8'?>
<jboss-deployment-structure>
    <deployment>
        <exclusions>
            <module name="org.hibernate.validator"></module>
        </exclusions>
    </deployment>
</jboss-deployment-structure>

**Comment by ndn2016** [comment]
Continue my previous post!
here is jboss-deployment-structure.xml
<?xml version='1.0' encoding='UTF-8'?>
<jboss-deployment-structure>
<deployment>
    <exclusions>
        <module name="org.hibernate.validator"></module>
    </exclusions>
</deployment>
</jboss-deployment-structure>

**Comment by graemerocher** [comment]
Ok, thanks for the feedback I have identified the problem. It will require a new release of GORM as there is a conflict between two JARs and the reason for the issue is a different in load order.

**Comment by graemerocher** [comment]
Created #9915 to track this issue

**Comment by janpenspain** [comment]
thanks you, right now with  3.1.8 version it's working fine with deploys on windows 7
