### ISSUE TITLE
Grails 3.0.10 g.include fails in parallel

### ISSUE THREAD

**Issue by chandan22** [grails/grails-core#9787]
g.include works in sequential ,but fails(throws exception-java.lang.IllegalStateException-Cannot ask for request attribute - request is not active anymore!) when loaded in parallel.

Steps to reproduce - 

class TestController {
def widget1() {
       render "Widget 1"
   }

   def widget2() {
      render "Widget 2"
   }
}

class ManagerController {
   def loadSequential(){
       def data = [:]
       data['view1'] = g.include(action: 'widget1', controller: 'test')
       data['view2'] = g.include(action: 'widget2', controller: 'test')
       render data['view1']
       render data['view2']
   }
   def loadParallel(){
       def data = [:]
       PromiseMap pm = new PromiseMap()
       pm['view1'] = { g.include(action: 'widget1', controller: 'test') }
       pm['view2'] = { g.include(action: 'widget2', controller: 'test') }
       def result = pm.get()

       render result['view1']
       render result['view2']
   }
}

Loading loadSequential gives output but loadParallel has unpredictable behaviour. Sometimes it gives correct result but next time throws exception. Both should give the same output ie "Widget 1 Widget 2"

**Comment by graemerocher** [comment]
Since the closures are executed in parallels there is no guarantee of order, I don't see how this is a bug
