### ISSUE TITLE
CSS generated with small typo errors in grails.css (V3.1.1)

### ISSUE THREAD

**Issue by mazaltod** [grails/grails-core#9790]
Hi,

I'm just starting with Grails  and I saw  little errors in the grails.css generated : 
#content.page-1 .row article h2 {
    margin: 0;
    paddnig: 0   <--   "padding"   (typo error : twice in the file)
}

and 1 filed "height"  without value (I'm not sure it is desired or not) 
@media (max-width: 1010px) {
    .event-logo {
        height: ;
    }

Hope this help,
Thanks for your great work.
David M.

**Comment by mazaltod** [comment]
And in main.css you have this 568th line with double-quote to supress : 
    text-align:center;"
Thanks

**Comment by graemerocher** [comment]
The source for the stylesheets can be found here https://github.com/grails/grails-profile-repository/tree/master/profiles/web/skeleton/grails-app/assets/stylesheets

Feel free to send a pull request.
