### ISSUE TITLE
Template rendering with custom url converter (i.e. hyphenated) does not work

### ISSUE THREAD

**Issue by ckalan** [grails/grails-core#9791]
When using hyphenated url converter for instance, if you have a controller named "MyController", grails automatically maps url "my-controller" to this controller. And we put the views into the "my-controller" folder. This works for the view rendering but not for the template rendering.

Put "index.gsp" and "_inner.gsp" into the "my-controller" folder, and in your index.gsp use

`<g:render template="inner" />`

This does not find the "_inner.gsp" because it still looks for the "/myController/_inner.gsp" file. Although the error says grails could not find the view in folder "/my-controller/_inner.gsp"

Possibly the reason is that GrailsConventionGroovyPageLocator does not use the UrlConverter.

Workaround: putting the templates into the "myController" folder currently seems to fix it.

**Comment by ckalan** [comment]
This also affects rendering templates from the controller action using 

`render(template:'inner')`

It looks like **DefaultGroovyPagesUriService **must also be fixed.

**Comment by ckalan** [comment]
Actually, from an architectural point of view, supporting views folder name same as the controller logical name (myController in this case) may already be more appropriate and will be easier to implement because controller logical name can be accessed from anywhere, but depending on UrlConverter requires accessing the converter itself or the GrailsWebRequest to get the converted controller name.

At the end, users would not care if the folder they put the views is hyphenated or not and possibly they prefer it to be the same as the controller name.

**Comment by jeffbrown** [comment]
> This does not find the "_inner.gsp" because it still looks for the "/myController/_inner.gsp" file.

That is the intended behavior.

**Comment by ckalan** [comment]
@jeffbrown No the problem is it must look for "/my-controller/_inner.gsp". If it is the intended behavior, it must also get the main view 'index.gsp' from  "/myController/index.gsp" folder but it uses "/my-controller/index.gsp" . 

So there is an inconistency when grails locates a view and when it locates a template. If you check the classes in my comments, you will see that, at some places, "webRequest.controllerName" is used and at some places "controller.logicalPropertyName" is used. 

And when UrlConverter is a custom one, these two values may not always be the same.

**Comment by jeffbrown** [comment]
> No the problem is it must look for "/my-controller/_inner.gsp".

I don't think that is the intended behavior.

**Comment by jeffbrown** [comment]
There are places where we have unintended inconsistencies because the framework is using the controller name in places where it really shouldn't.  The intended behavior is that the url converter only relates to urls.  That should never affect the file system and if/where it does, I think that is a mistake.

**Comment by jeffbrown** [comment]
With which version of Grails are you seeing the problem?

**Comment by jeffbrown** [comment]
I can recreate a problem with 3.0.14 which demonstrates that the framework is looking for views in the hyphenated folder name, which is a bug.  I don't think the solution is to also make the template renderer do that.  I think the solution is to make the view renderer not do that.  An application shouldn't have to rename all of the view folders if a customer url converter is registered.

The customer url converters are really only useful if using the wild carded url mappings.  Best practice for real applications is not to do that anyway and instead provide mappings for all of the routes and only use wildcards for parameters.

**Comment by ckalan** [comment]
Thanks for the information. I hope the bug is fixed soon. 
Btw, I think best practice for real applications is not to force the developer to enter custom url mappings manually but Instead, the framework must allow the developer to attach his own url processing code (forward and reverse) in a simple way ( like custom routes in ASP .NET MVC ) so he is able to implement any kind of url mapping as he wishes. ASP .NET holds all the routes registered by the developer and the framework itself in a sorted order and asks each of them for a url. If one can handle it and resolve controller,action and other parameters from the url, then it becomes the route for the current request. Reverse mapping is done the same way. I think this is a great flexibility but I know that will require a lot of effort so I hope we see that in Grails in future versions.

**Comment by graemerocher** [comment]
Relates to #9803

**Comment by jameskleeh** [comment]
Grails 3.2.6 

/foo-bar/index will correctly resolve the `/fooBar/index` view.
/foo-bar/index will correctly NOT resolve the `/foo-bar/index` view.
