### ISSUE TITLE
Configuration with name 'exploded' not found

### ISSUE THREAD

**Issue by Luxor** [grails/grails-core#9792]
I've created sample multi project according to documentation
http://grails.github.io/grails-doc/3.1.3/guide/single.html#plugins

But got an error on run-app
```
$ grails run-app

BUILD SUCCESSFUL

Total time: 6.936 secs
|Running application...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':myapp'.
> Could not resolve all dependencies for configuration ':myapp:runtime'.
   > Configuration with name 'exploded' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error |
Failed to start server (Use --stacktrace to see the full trace)
```

According to docs I have to run: 
```
$ grails create-app myapp
$ grails create-app myplugin
```

If I create a plugin instead of app - *anything is ok*
```
$ grails create-app myapp
$ grails create-plugin myplugin
```

Can be app used as part of multiproject build? Or this is docs issue

I am using windows 10

Anton@DESKTOP-RDS04IT ~/dev/g3-2/myapp
$ grails --version
|Grails Version: 3.1.2
|Groovy Version: 2.4.6
|JVM Version: 1.8.0_74

Windows 10 10.0 amd64
```

**Comment by graemerocher** [comment]
I'm not sure what you are trying to achieve, you must have one app depending on another which doesn't make much sense. You can have multiple apps in a multi project build, but they shouldn't depend on each other.
