### ISSUE TITLE
Constraints on transient properties are validated twice (Grails 2.5.5)

### ISSUE THREAD

**Issue by mburak** [grails/grails-core#9802]
It looks like having a validator on a transient is evaluating the property twice on validation.

We have something like this:

```
class Attribute {
    String name
    String type

   static constraints = {
       type nullable: false, validator: { val, obj, errors -> 
          ....
       }
   }

   String getType() {
      ... 
   }
}
```

When we do:

```
Attribute attribute = new Attribute(name: 'title')
attribute.validate()
```

 it goes twice through validator.
Any idea?

**Comment by jeffbrown** [comment]
> It looks like having a validator on a transient is evaluating the property twice on validation.

Your sample doesn't include a transient property.  Is it happening for transient and only transient properties?

**Comment by mburak** [comment]
Sorry Jeff, I forgot to add it... I have:

```
static transients = ["type"]
```

**Comment by bobbywarner** [comment]
This issue does not happen with Grails 4.0.3.  The validator is only called once.

Given the `relates-to: v2.x` tag, this issue must have only happened on Grails 2.x anyway. Closing as Grails 2 is very old and no longer maintained.
