### ISSUE TITLE
Call to response.sendError in Interceptors or Filters shows blank page

### ISSUE THREAD

**Issue by yevdoJfrog** [grails/grails-core#9805]
Call to response.sendError in Interceptors or Filters cause to blank page instead of 404 error page.
Seems like render method is not getting called, when calling to response.sendError for interceptor / filter.

**Sample application:** https://github.com/alenon/Grails3TestProject
**Grails versions:** >=  3.0.11

**Steps to reproduce:** (_Reproducible 100%_)

1. Create a controller
2. Create an interceptor for this controller
3. Inside the interceptor's before method call response.sendError(404)
4. Navigate to this controller through the web browsing and url mappings

**Actual result:**
Blank page is shown, and in response code 404 in the networking tab of chrome debugger.

**Expected result:**
404 page is shown

**Comment by jeffbrown** [comment]
This is what I am seeing:

```
~ $ curl -i http://localhost:8080/admin
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application:development
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Date: Sun, 20 Mar 2016 11:38:54 GMT

Here I am
~ $ 
~ $ 
~ $ curl -i http://localhost:8080/notadmin
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
X-Application-Context: application:development
Content-Length: 0
Date: Sun, 20 Mar 2016 11:38:58 GMT
```

Is that not the expected behavior given the way that the app is written?

**Comment by yevdoJfrog** [comment]
It's, but if you will try to navigate to this URL: http://localhost:8080/notadmin through a web browser, instead of seeing the 404 (Grails default) page, you will see the blank page (and this is the issue).

Seems like no render method is called when you do response.sendError and then return false from the interceptors or filters.

This is the console output of the demo app code:
                ...
                18:47:14.13	GET /notadmin
                Controller: test   Action: testAction
                ...
                **18:47:14.14	GET /error
                Controller: test   Action: testAction**

As you can see, although the /error URI is called, it's going to the same controller and action as before sendError call. Even if you change the URL mappings (line 5) to this:
`"/$username"(controller: 'test', action: 'testAction') { constraints { validator: { it != 'error' } } }`

**Comment by jeffbrown** [comment]
Thanks for the feedback.

**Comment by yevdoJfrog** [comment]
Thank you for the fast responses.
Can you please include this bug fix at the future grails-**3.0.x** as well?

**Comment by graemerocher** [comment]
Possibly, the bug (if it is one) needs to be further verified.

**Comment by chris13524** [comment]
I'm getting a similar issue in v3.3.1. Is this actually resolved?
