### ISSUE TITLE
render view: empty reponse

### ISSUE THREAD

**Issue by bwolin** [grails/grails-core#9810]
We're porting a 2.4 application to 3.1.2 and for some reason, render view is returning empty responses. The documentation still says render supports a view argument. Nothing obvious coming up in the release notes, the issues in this git repo, stackoverflow or google.

I created a new, empty application with 1 controller, 1 view, 1 template and am attaching it to this issue. Hoping I'm doing something wrong, but I can't imagine what. Thanks.

Details:

Running it with: gradle bootRun

Issue should be able to be duplicated with curl:
$ curl localhost:8080/pristine/list
$ curl localhost:8080/pristine/template
<div> I'm the _list.gsp template</div>

_list.gsp 
<div> I'm the _list.gsp template</div>

list.gsp 
<div> I'm the list.gsp </div>

class PristineController {

    def index() { }

    def list() {
        render(view: "list")
    }

    def template() {
        render(template: "list")
    }
}

[pristine.tar.gz](https://github.com/grails/grails-core/files/182895/pristine.tar.gz)

**Comment by jeffbrown** [comment]
The `list.gsp` looks like this:

    <div> I'm the list.gsp </div>

If you change that to the following, it works:

    <html>
        <body>
            <div> I'm the list.gsp </div>
        </body>
    </html>

**Comment by bwolin** [comment]
@jeffbrown -- thanks very much for the response.

We use views for a lot of components that are delivered using ajax and templates for page parts that are rendered in loops. We didn't understand this as a design criteria for splitting between templates and views. 

Is it an undocumented requirement (or documentation that I missed) that views are fully defined HTML? It will be a lot of effort to move these and am hoping there's a workaround beyond renaming everything and rewriting the render invocations. Again, Thanks!

**Comment by graemerocher** [comment]
Templates are designed for this purpose, view should be full parseable

**Comment by orlleite** [comment]
Thanks for clarify.

I'm using view for rendering big jsons, not html. A few actions share the same view two or three times at most. They will never have <html><body> at beginning. I don't really mind to change `view:` to `template:`. But if there is a way to not put `_` underscore first letter to keep sorted the files. Or if there is a better way and I'm doing wrong with responses not-html. It will be good to know. I'm new on grails.
