### ISSUE TITLE
@Resources uri not created with create-domain-resource command

### ISSUE THREAD

**Issue by PaulWaldo** [grails/grails-core#9812]
On Grails 3.1.4, I created a new rest-api project.  I then created a domain object to be used via rest: `create-domain-resource RestTest`.  It looked like this:
```
package resttest

import grails.rest.*

@Resource(readOnly = false, formats = ['json', 'xml'])
class RestTest {

}
```
This works fine when accessing it like this: `http://localhost/restTest`.  If I start adding records and try to access individual items like this `http://localhost/restTest/1`, I get 
`{"message":"Not Found","error":404}`
 Only by adding a `uri` parameter to the Resource annotation can I look up individual items.

I propose modifying the code generator so that the URI parameter is added, possibly using the appropriately cased domain object name and pluralized.

Reference: see http://stackoverflow.com/questions/36158963/finding-a-specific-id-using-rest-in-grails/36160705#36160705

**Comment by orubel** [comment]
You can always use Boomstick API Framework. This automates and simplifies API development : https://bintray.com/nosegrind/plugins/api-framework/view#

**Comment by graemerocher** [comment]
With the improvements in the default mappings in 3.2 this change is not necessary
