### ISSUE TITLE
namedQueries. Why in SQL the limit has appeared?

### ISSUE THREAD

**Issue by igilfanov** [grails/grails-core#9818]
`class NotificationReadyQuestion {
....
static namedQueries = {
countByUserIdAndNotificationIdAndStatusAndQuestionIds{ final int userId, final Integer notificationId, final ArrayList questionIds, final short status ->

            and {

                sqlRestriction "user_id = ?", [userId]

                if (notificationId != null) {
                    sqlRestriction "notification_id = ?", [notificationId]
                }

                sqlRestriction "EXISTS(SELECT * FROM (VALUES ${'(?),'.multiply(questionIds.size()).rtrim(',')}) AS v(val) WHERE this_.question_id = v.val)", questionIds

                eq "status", status
            }

            projections{
                count("notification")
            }
        }

}
....
}`

Further I apply so:

`int completeCount = NotificationReadyQuestion.countByUserIdAndNotificationIdAndStatusAndQuestionIds(userId, notificationId, questionIds, Notification.ANSWER_COMPLETE).get()`

Result of performance:

`Hibernate: select count(this_.notification_id) as y0_ from notification.ready_question this_ where (user_id = ? and notification_id = ? and EXISTS(SELECT * FROM (VALUES (?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?)) AS v(val) WHERE this_.question_id = v.val) and this_.status=?) limit ?`

**Comment by jeffbrown** [comment]
Is it because you are calling `.get()`?

**Comment by igilfanov** [comment]
So what?  I am here not to set a limit.  And If a table has 1000 columns?  Thus unacceptable to use the following query: SELECT Count(*) FROM ...     Therefore I do not use GORM construction: `.count()`

**Comment by droggo** [comment]
@igilfanov `count(*)` is not influenced by `LIMIT` if both are used in the top level query

if you do `select count(*) from notification limit 5` you will still get real count from this table. In this case LIMIT would influence result if more than 5 rows would be returned, which will never happen unless you also have some `GROUP BY` in top level query. This should not cause any issues with your results.

**Comment by igilfanov** [comment]
Thanks for the comment.  Are you sure that the limit value is set to 0?

**Comment by droggo** [comment]
No, I expect its set to 1 because you use `get ()`. But what I'm saying is that it doesn't matter for your query
