### ISSUE TITLE
Call to render from an Interceptor fails if original requestURI is specified in URLMappings.groovy

### ISSUE THREAD

**Issue by ZacharyKlein** [grails/grails-core#9826]
When rendering a view from an Interceptor, if the request's original URI was specified in `URLMappings.groovy`, the render fails with a `NullPointerException`.

The problem appears to be that there is no controller name attribute in the request if the URL was specified via a URL mapping. In [`GroovyPagesUriSupport.getLogicalControllerName()`](https://github.com/grails/grails-core/blob/57df0a12bb03fff498d97a8ec464fbc43d04a976/grails-web-common/src/main/groovy/org/grails/web/pages/GroovyPagesUriSupport.java#L82)  , the call to `webRequest.getControllerName()` is returning null. The NPE then happens within [`DefaultGroovyPagesUriService.getLogicalControllerName()`](https://github.com/grails/grails-core/blob/0b1d6a6d02f2217643a69e8314f76078dacbce32/grails-web-common/src/main/groovy/org/grails/web/pages/DefaultGroovyPagesUriService.java#L143), because the controller `name` value is never set, and the `controllerNameCache` won't accept a null value.

**Workaround**  In my interceptor, I simply set the controller name request attribute like so: `request.setAttribute(GrailsApplicationAttributes.CONTROLLER_NAME_ATTRIBUTE, "landingPage")`

**Proposed solution** It seems to me that the logical branching within `DefaultGroovyPagesUriService.java` simply needs one more test for a value `name`. If the logic is changed to add one more check for `name == null`, and then to fall back to the call to `GrailsNameUtils.getLogicalPropertyName()`, the controller name returned is the name of the interceptor, which seems very reasonable (and works fine).

Tested in Grails 3.0.14 and 3.1.4.

**Comment by ZacharyKlein** [comment]
Sample project (comment/remove line 16 from `interceptorRender.AlphaInterceptor.groovy` to reproduce the error): https://github.com/ZacharyKlein/grails-core-issue-9826

**Comment by jeffbrown** [comment]
I am not sure if this was closed on purpose or not.  I will re-open it for now.

**Comment by ZacharyKlein** [comment]
Looking a bit close at the code in [`GroovyPagesUriSupport.getLogicalControllerName`](https://github.com/grails/grails-core/blob/57df0a12bb03fff498d97a8ec464fbc43d04a976/grails-web-common/src/main/groovy/org/grails/web/pages/GroovyPagesUriSupport.java#L89), I wonder if a better solution might simply be to add `InterceptorArtefactHandler.TYPE` to the test before trying to get the controller name off the request?

Something like: 

```
if(!simpleName.endsWith(ControllerArtefactHandler.TYPE) || !simpleName.endsWith(InterceptorArtefactHandler.TYPE)) {
    GrailsWebRequest webRequest = GrailsWebRequest.lookup();
    return webRequest != null ? webRequest.getControllerName() : null;
}
else {
    return GrailsNameUtils.getLogicalPropertyName(simpleName, ControllerArtefactHandler.TYPE);
}```

**Comment by graemerocher** [comment]
So I am trying to reproduce this with the sample app attached and cannot with 3.0.16 snapshot. What am I look for here? Both http://localhost:9090/alpha and http://localhost:9090/beta behave as expected

**Comment by ZacharyKlein** [comment]
@graemerocher That's because I've included a workaround (setting the controller name in the request attributes). I just updated the project and removed that line.  See https://github.com/ZacharyKlein/grails-core-issue-9826/commit/17e2e4dac68ac2f194a351713a04d1445b9cebd4

**Comment by graemerocher** [comment]
yeah I know, even when I remove that line with 3.0.16 snapshot I do not see the error

**Comment by ZacharyKlein** [comment]
Ah, sorry. I guess I didn't specify how to invoke the interceptor. :) It's looking for a params.alpha - if it finds one, the interceptor will render a view and return false - otherwise, it returns true.

To reproduce the error, try these urls:

AlphaController (no interceptor) http://localhost:9090/alpha 
BetaController (no interceptor) http://localhost:9090/beta
Error (should load view from views/alpha) http://localhost:9090/asdasd?alpha=true

**Comment by graemerocher** [comment]
Right, now I can reproduce it

**Comment by ZacharyKlein** [comment]
Added a link to make getting to the error more convenient: https://github.com/ZacharyKlein/grails-core-issue-9826/commit/cfbfec78a5ff99ae0359ebeae99482983effe34f
