### ISSUE TITLE
Problem running Grails 3.1.4

### ISSUE THREAD

**Issue by jpsalvadorm63** [grails/grails-core#9827]
Hello Amigos,

When trying tu run a new grails app in 3.1.4, I got this message:

"Error initializing classpath: org.grails.cli.profile.commands.script.GroovyScriptCommand (Use --stacktrace to see the full trace)"

I'm using intelliJ Idea 2016.1

NO PROBLEM when running from command line using "grails run-app" < - - -  my work around !!

(grails 3.1.4, java 1.8_45_64, windows 10)

Thanks in advance for any help

Juan

**Comment by graemerocher** [comment]
IntelliJ bug, please report to https://youtrack.jetbrains.com/oauth?state=%2Fissues%2FIDEA
