### ISSUE TITLE
Documentation on profile commands incorrect

### ISSUE THREAD

**Issue by PaulWaldo** [grails/grails-core#9828]
Documentation for Grails 3.1.4, in the section [6 Application Profiles - Reference Documentation](http://grails.github.io/grails-doc/latest/guide/profiles.html) says that there are commands named **list-profiles** and **profile-info**.  After creating a new Angular application and running grails, these commands seem to be missing.  Using tab at the grails command line shows this:
```
grails> 

assemble                     bug-report                   clean                        compile                      
console                      create-controller            create-domain-class          create-domain-resource       
create-functional-test       create-integration-test      create-interceptor           create-ng-component          
create-ng-controller         create-ng-directive          create-ng-domain             create-ng-module             
create-ng-service            create-restful-controller    create-script                create-service               
create-unit-test             dependency-report            generate-all                 generate-controller          
generate-functional-test     generate-unit-test           generate-views               gradle                       
help                         install                      list-plugins                 open                         
plugin-info                  run-app                      schema-export                shell                        
stats                        stop-app                     test-app                     url-mappings-report          
grails> list-profiles
| Error Command not found list-profiles
Did you mean: list-plugins or test or test-app?
```
Additionally, the Quick Reference makes mention of list-profiles, but the Usage section shows `grails list-plugins`

I'm not sure whether this is a bug in the documentation or in the command line subsystem.  My preference would be that the documentation is correct, as this seems like a useful feature.

**Comment by graemerocher** [comment]
They're only available when not within an application directory

**Comment by edwardotis** [comment]
That's still a bug. The error messaging is effectively incorrect and very confusing to all newcomers to grails.  This situation is the common case for new users, and should not be dismissed.

**Comment by svetozar02** [comment]
This should be clearly stated in the documentation.

**Comment by graemerocher** [comment]
Since profiles are generally used when creating an application, the commands have no practical purpose while already within an application, what are you going to do create another application nested within another application? That makes no sense.

Fair point about documentation though.

**Comment by edwardotis** [comment]
Agreed it doesn't make sense to run it. However, it would be helpful to produce an error message when the command is run inside an application root, instead of silently failing.

**Comment by graemerocher** [comment]
It doesn't silently fail, it prints `| Error Command not found list-profiles`

If it were to silently fail I would anticipate it print nothing

**Comment by svetozar02** [comment]
I would agree in theory. However in practice the first thing that popped to my mind when seeing this error is that I have wrong version of grails on my path. After verifying that that I have grails 3, my guess was that it's a grails bug. 
Although it's a low priority, it would be nice to have a more descriptive error message.

**Comment by PaulWaldo** [comment]
"Command not found" technically is not correct, as the command is known to grails.  

> list-profiles only valid outside an existing grails project 

or something to that effects seems more descriptive.  I can look into making a pull request if you agree, @graemerocher.

**Comment by graemerocher** [comment]
pull requests welcome
