### ISSUE TITLE
Date ValueConverter issue

### ISSUE THREAD

**Issue by bwolin** [grails/grails-core#9831]
My ValueConverter for Date isn't getting invoked during the data binding.

In SimpleDataBinding.groovy I can see the the conversionHelpers contains both my ValueConverter and the default DateConversionHelper. It uses find and therefore gets the first one it finds.

Is there any way to override the default? We have some I18N logic in ours that supports alternative date formats that we'd like to keep using. Thanks in advance/

```
protected convert(Class typeToConvertTo, value) {
        if (value == null || typeToConvertTo.isAssignableFrom(value?.getClass())) {
            return value
        }
        if (conversionHelpers.containsKey(typeToConvertTo)) {
            ValueConverter converter = getConverter(typeToConvertTo, value)
            if (converter) {
                return converter.convert(value)
            }
        }
...
    protected ValueConverter getConverter(Class typeToConvertTo, value) {
        def converters = conversionHelpers.get(typeToConvertTo)
        converters?.find { ValueConverter c -> c.canConvert(value) }
    }
```

**Comment by jeffbrown** [comment]
As a workaround for now, if you name your converter bean `defaultDateConverter`, I think it will work.

**Comment by bwolin** [comment]
That works -- Thanks!

**Comment by jeffbrown** [comment]
The issue is https://github.com/grails/grails-core/blob/3f24b1b7c4feba408a7a6b312033d1c6582a71a7/grails-databinding/src/main/groovy/grails/databinding/SimpleDataBinder.groovy#L759.

    protected ValueConverter getConverter(Class typeToConvertTo, value) {
        def converters = conversionHelpers.get(typeToConvertTo)
        converters?.find { ValueConverter c -> c.canConvert(value) }
    }

That is finding the first converter that can convert this value.  It just happened that this worked in 2.x and for some reason the order in the list is different now.

We need some mechanism for expressing order of preference.

**Comment by davydotcom** [comment]
I can't get any custom converters to work is this related? AttachmentValueConverter for selfie plugin is not getting enacted converting Multipart into a `com.bertramlabs.plugins.selfie.Attachment` I added debug on all of it and found that canConvert was never even called

**Comment by snimavat** [comment]
@jeffbrown how about @[Order](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/annotation/Order.html) annotation from spring -

**Comment by snimavat** [comment]
@bwolin Looks like it would just work if you put @Order annotation on your custom value converter with a low order value [see](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/annotation/Order.html) 

All value converters are registered with the data binder [here](https://github.com/snimavat/grails-core/blob/a454a0c8ac95dd364563c8b00ac79955517cdc14/grails-web-databinding/src/main/groovy/grails/web/databinding/GrailsWebDataBinder.groovy#L611-L611)

This is Autowired array type property, and if you have @Order annotation on any beans which are candidate of autowiring, spring will order them based on the annotation value with those with lower value would have higher priority. and your value converter will be picked up before the dateConversionHelper
