### ISSUE TITLE
Plugin name not correctly recognized when rendering templates

### ISSUE THREAD

**Issue by donald-jackson** [grails/grails-core#9832]
Upgrading from grails 2.5.x, the below code was in a taglib

```
out << render(template:'/genericOption/text', plugin: 'settings-core', model: [attrs: attrs]);
```

In a plugin named 'settings-core' (was working) - in Grails 3.0.x this no longer works and throws a template not found error. After some digging I can see that the gsp classes are stored as gsp_settings_core (hyphen converted to underscore) during the build phase.

In order to make this old code work now I have to change my render method to this (or remove the 'plugin:' attribute)

```
out << render(template:'/genericOption/text', plugin: 'settings_core', model: [attrs: attrs]);
```

Which does work - but semantically now my plugin name is different.

Grails 3.0.15
Java 1.8.0_77 64-bit
CentOS 7

**Comment by graemerocher** [comment]
@donald-jackson could you provide an example of this issue in a github repo please?

**Comment by Schlogen** [comment]
@ColinHarrington Is this related to the fix you were working on?

**Comment by ColinHarrington** [comment]
Possibly similar, but not exactly. I was working on the grails-views template compilation & resolution.  http://views.grails.org/latest/#_plugin_support

If this is still an issue it would likely be in the gsp/taglib area.

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback
