### ISSUE TITLE
[3.1.4] - Test - VerifyError occours when using variable of an data table inside a closure

### ISSUE THREAD

**Issue by marcioaug** [grails/grails-core#9837]
| Grails Version: 3.1.4
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_77

``` groovy
    void "Test the homepage"() {
        expect:
	
        def stuffs = [[code: 1, letter: 'a'], [code: 2, letter: 'b'], [code: 3, letter: 'c']]

        stuffs.find { it.code == code }?.letter == letter

        where:

        code | letter
        1    | 'a'
        2    | 'b'
        3    | 'c'
    }
```
It works in Grails 3.1.1, but in 3.1.4:
```
initializationError

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    functional/FunctionalTestSpecSpec.$tt__$spock_feature_1_0(Ljava/lang/Object;Ljava/lang/Object;Lorg/springframework/transaction/TransactionStatus;)V @302: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[24]) is not assignable to 'groovy/lang/Reference'
  Current Frame:
    bci: @302
    flags: { }
    locals: { 'functional/FunctionalTestSpecSpec', 'java/lang/Object', 'java/lang/Object', 'org/springframework/transaction/TransactionStatus', '[Lorg/codehaus/groovy/runtime/callsite/CallSite;', 'java/lang/Object', 'java/util/List' }
    stack: { 'org/spockframework/runtime/ValueRecorder', 'java/lang/String', integer, integer, null, 'org/spockframework/runtime/ValueRecorder', integer, 'org/spockframework/runtime/ValueRecorder', integer, 'org/codehaus/groovy/runtime/callsite/CallSite', 'org/spockframework/runtime/ValueRecorder', integer, 'java/lang/Class', 'java/lang/Object', 'java/lang/String', '[Ljava/lang/Object;', '[Ljava/lang/Object;', integer, 'org/spockframework/runtime/ValueRecorder', integer, uninitialized 295, uninitialized 295, 'functional/FunctionalTestSpecSpec', 'functional/FunctionalTestSpecSpec', 'java/lang/Object' }
  Bytecode:
    0x0000000: b800 233a 0419 0412 ee32 12f0 b900 3002
...
at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.spockframework.runtime.SpecInfoBuilder.buildFields(SpecInfoBuilder.java:98)
...

```

[example.zip](https://github.com/grails/grails-core/files/196401/example.zip)

**Comment by jeffbrown** [comment]
It looks like the problem goes away if you remove `@Rollback`.  Will investigate.  Thanks for the feedback.

**Comment by jeffbrown** [comment]
The problem appears to be related to referencing one of the `where` variables from within a closure.  The following test throws a `VerifyError`:

    // src/integration-test/groovy/demo/SomeSpec.groovy
    package demo

    import grails.test.mixin.integration.Integration
    import grails.transaction.Rollback
    import spock.lang.Specification

    @Rollback
    @Integration
    class SomeSpec extends Specification {

        void 'test something'() {
            expect:
            def someClosure = { println x }
            x + y == sum

            where:
            x | y | sum
            4 | 2 | 6
        }
    }

The test passes if I remove `@Rollback`.  The test also passes if I remove the the closure which references `x`.

**Comment by jeffbrown** [comment]
Note that the closure doesn't even have to be executed.  Just having it present is enough to trigger the problem if the closure references one of the `where` variables.
