### ISSUE TITLE
Gorm constraints the default configuration is not effective

### ISSUE THREAD

**Issue by btboys** [grails/grails-core#9838]
grails.gorm.default.constraints = {
    '*'(nullable: true, blank: true)
}

Don't take effect。
Table automatic generation of the field, or the not null

**Comment by graemerocher** [comment]
What versions of Grails? What GORM version?

**Comment by btboys** [comment]
3.1.4

**Comment by graemerocher** [comment]
Probably duplicates https://github.com/grails/grails-data-mapping/issues/671
