### ISSUE TITLE
[3.1.4] Arbitrary variables defined in URL mapping not considered for reverse mapping

### ISSUE THREAD

**Issue by sascharitter** [grails/grails-core#9840]
URL mapping

    "/about-us" {
        controller = 'page'
        action = 'index'
        code = 'about'
    }
    "/imprint" {
        controller = 'page'
        action = 'index'
        code = 'imprint'
    }

Matching of these URLs works as intended (http://localhost:8080/about-us and http://localhost:8080/imprint).

    <g:link controller="page" action="index" params="[code: 'about']">About</g:link>
    <g:link controller="page" action="index" params="[code: 'imprint']">Imprint</g:link>

However reverse mapping produces the following URLs:

> http://localhost:8080/about-us?code=about
> http://localhost:8080/about-us?code=imprint

Is this a bug or is it not possible that arbitrary variables defined in the URL mapping are considered for reverse mapping?

[reversemapping-bug-report-31032016.zip](https://github.com/grails/grails-core/files/197271/reversemapping-bug-report-31032016.zip)

**Comment by graemerocher** [comment]
This is not a bug, could be argued that it is a missing feature and a feature request, but right now the implementation does not take arbitrary variables into account
