### ISSUE TITLE
[3.1.4] Spring security 3.0.4 and Tomcat error, standalone .war functioning

### ISSUE THREAD

**Issue by Morhafalaraj** [grails/grails-core#9841]
Hey again guys, after a couple of days of debugging I managed to narrow the problem a lot. I'm having big problems with Spring Security 3.0.4 , Hibernate 4, Ehcache and Tomcat. The standalone .war file is executable, but the same .war gives me weird errors in Tomcat 7/8/9. Using: Grails 3.1.4, Java 1.8.0.66, Windows 8.1 64-bit.

Application.yml / build.gradle: http://pastebin.com/DM6HxX6A
Stacktrace: http://pastebin.com/YdqbM0Ch
Thanks

**Comment by graemerocher** [comment]
Since the stack trace is emerging from the Spring Security plugin an issue needs to be filed here https://github.com/grails-plugins/grails-spring-security-core/issues
