### ISSUE TITLE
g:createLink Documentation incomplete

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#9843]
Hi!

AFAIK `g:link` and `g:createLink` does the same except that `g:link` creates an a tag with href set and `g:createLink` generates only the URL (`g:createLink` is called by `g:link` internally). So the documentation for the attribute should be the same (except `elementId` of `g:link`), but at `g:createLink` the documentation of resource is missing.

best regards,
Andreas

**Comment by jameskleeh** [comment]
Fixed. Thanks
