### ISSUE TITLE
Dependency on Reactor 2.0.6.RELEASE is causing race condition that prevents reliable use of Grails Async

### ISSUE THREAD

**Issue by sofiaguyang** [grails/grails-core#9844]
Grails Async is unreliable because of a race condition issue in Reactor which affects versions 2.0.7.RELEASE and older. Please see: https://github.com/reactor/reactor/issues/487 

The dependency on Reactor is declared here: https://github.com/grails/grails-core/blob/master/build.gradle#L44

This should have already been fixed in a new release versioned 2.0.8 -- but I'm not sure why the release didn't push through.

**Comment by ColinHarrington** [comment]
Looks like 2.0.8.RELEASE milestone isn't closed out yet. https://github.com/reactor/reactor/milestones @smaldini Were you waiting on something for the 2.0.8.RELEASE?

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/db24a58b4f3cdc6aaebd9b5a511390b600fadefb
