### ISSUE TITLE
Grails 3.1.4 cannot copy application.yml during processResources when using nebula-release plugin

### ISSUE THREAD

**Issue by trentrosenbaum** [grails/grails-core#9852]
I have been able to use the nebula release plugin with other groovy and springboot applications with no problem, but could not use a standard setup with Grails.

Started a simple Grails 3.1.4 default application and then tried a rest-api Grails application.  Configured the nebula-release plugin to the application and then removed the version value, (to be inferred by the gradle plugin).  Initialised the git repo and built the application.  The following error was written to the console

Inferred` project: mywebapp, version: 0.1.0-dev.1.uncommitted+38aef48
:clean
:compileJava UP-TO-DATE
:compileGroovy
:processResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processResources'.
> Could not copy file '/home/myuser/development/idea-workspace/mywebapp/grails-app/conf/application.yml' to '/home/myuser/development/idea-workspace/mywebapp/build/resources/main/application.yml'.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Before the git repo was initialised the application built as expected without a version because the repo was not setup, (as expected).

The following was the entry for the buildscript

buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.7.4"
        classpath "org.grails.plugins:hibernate4:5.0.2"
        classpath 'com.netflix.nebula:nebula-release-plugin:4.0.1' 
    }
}

apply plugin: 'nebula.nebula-release'

**Comment by graemerocher** [comment]
Root cause appears to be

```
Caused by: java.lang.ClassCastException: org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion cannot be cast to java.lang.String
        at org.apache.tools.ant.filters.ReplaceTokens.read(ReplaceTokens.java:149)
        at org.apache.tools.ant.filters.BaseFilterReader.read(BaseFilterReader.java:84)
        at org.apache.tools.ant.util.ReaderInputStream.read(ReaderInputStream.java:117)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1488)
       
```
