### ISSUE TITLE
Grails 3.1.4: Interceptor matchAll().excludes using OR instead of AND

### ISSUE THREAD

**Issue by borgiani** [grails/grails-core#9853]
Hey all,

When writing an interceptor for my app, I found that by using matchAll.excludes(), it actually excludes the request from the interceptor if any of the arguments is true.

For example:
`matchAll().excludes(controller: 'test', action: 'save')`

The code above will have the interceptor ignore requests to any actions in that controller.
The issue can be found in the isExcluded method (UrlMappingMatcher.groovy:202)
It seems that method is doing an OR comparison of the arguments, where I guess it should've be doing an AND.

The only way I found around this was to use the excludes method with a custom Closure.

Thanks

**Comment by wureka** [comment]
Grails 3.0.15
JDK 1.8.77
OS: whatever

I also found the problem. My case is as below
I have a global interceptor:
`matchAll()
    .excludes(controller:'t2', action:'m1')
    .excludes(controller:'t3', action:'m2')
`
After spending a lot of time. I find that my web lets all methods in t2Controller and all methods in t3Controller pass.
However, I just wanna let t2Controller.m1() and t3Controller.m2() pass.

Currently the workaround way is, do not use global interceptor nor matchAll(), but attach an interceptor for each controller. and in each controller's interceptor, use match action:'m3'. 
For example:
`
T3Interceptor {
    T3Interceptor() {
        match action:'m2'
    }
}
`
