### ISSUE TITLE
Re-introduce scaffolding functionality lost in Grails 3

### ISSUE THREAD

**Issue by donald-jackson** [grails/grails-core#9854]
This is a feature request, essentially to try and get the scaffolding back to where it was in Grails 2.

Two missing features are:
- Scripting is no longer supported in scaffolding templates (eg: iterating through a domain class to produce a view, conditions, etc) 
- Scaffolding can only use domain classes from the current project, in Grails 2 you could use any hibernate class. This is useful for some people (like me) who logically separate their GUI from their domain classes.

Thanks

**Comment by jeffbrown** [comment]
This should be reported at https://github.com/grails3-plugins/scaffolding/issues

**Comment by sdelamo** [comment]
Filed in scaffolding https://github.com/grails3-plugins/scaffolding/issues/38
