### ISSUE TITLE
Bug in form taglib (branch 2.5.x)

### ISSUE THREAD

**Issue by effingen** [grails/grails-core#9855]
There is a small bug in org.codehaus.groovy.grails.plugins.web.taglib.FormTagLib which results in printing a form element with no space between attributes (around line 417).
```
        if (elementId) {
            writer << " id=\"${elementId}\""
        }
```
(The space character should be after the attribute, not before.)

**Comment by graemerocher** [comment]
Grails 2.x is in maintenance mode and only blocking bugs and bugs reported by OCi support customers are being fixed. Please upgrade to Grails 3.x.
