### ISSUE TITLE
[3.1.4] json-view shared view

### ISSUE THREAD

**Issue by cavemansspa** [grails/grails-core#9858]
Creating a new issue per https://github.com/grails/grails-core/issues/9673#issuecomment-208354197.

Quick summary is that accessing views outside of current view directory is not working when passing a collection.

I will update this issue with an example / reproducer.

**Comment by cavemansspa** [comment]
Here's a test repo: https://github.com/cavemansspa/TestAppRESTApiJSONViews

Trying to use views from different directory is not working.

```
import com.testappreatapijsonviews.One

model {
        One one
}

json g.render(one, [excludes: ['many']]) {
        // this works from same directory
        many tmpl.many( one.many )

        // this doesn't work
        //many tmpl.'/many/_many'( one.many )

        // this doesn't work
        // many tmpl.'../many/_many'( one.many )
}


```

**Comment by graemerocher** [comment]
The actual syntax is 

         many tmpl.'/many/many'( one.many )

Without the underscore present, this is the same as GSP, the underscore is only present in the file name. However that did reveal another bug in that the model name is taken from the method name which I will fix.

**Comment by graemerocher** [comment]
The following works with the current implementation:

```
many tmpl.'/many/many'( 'many', one.many )
```

**Comment by cavemansspa** [comment]
Okay, thanks.

Totally different issue, but one side note for consideration with this 1-to-N associations in the domain objects.  Without the `excludes` in `json g.render(one, [excludes: ['many']]) {`, I believe I was getting an infinite loop.

**Comment by graemerocher** [comment]
@cavemansspa if you can modify your example to reproduce the infinite loop I would be happy to look at it. Thanks.

**Comment by cavemansspa** [comment]
Actually it's on the `_many.gson`, I believe this demonstrates the infinite loop because the reference to `one` in the `many` domain.  Maybe that's just a documentation update to "beware of ..."?

```
//json g.render(many, [includes:['id', 'name']]) {
json g.render(many) {
        // test comment
        anotherAttr 'some additional attr ...'
}

```

**Comment by graemerocher** [comment]
@cavemansspa This will be fixed in the next release. Thanks for the report
