### ISSUE TITLE
Sorting fails when the property is part of criteria

### ISSUE THREAD

**Issue by rvachtl** [grails/grails-core#9860]
Consider traditional Parent and Child domain classes, where parent is property of child. Following is sample code with a few queries:

```
query1=Child.where{
  (name!=null)
}
query2=Child.where{
  (parent.name!=null)
}
def results
results=query1.list([max:5,sort:'parent.name']) // works
results=query2.list([max:5]) //works
results=query2.list([max:5,sort:'parent.name']) // fails
```

The last query with sorting fails on 'could not resolve property: parent.name of: Child' without obvious reason.

**Comment by Schlogen** [comment]
@rvachtl What version of Grails? Include an example project

The following works in 3.1.10:

```
class Parent {
    String name
    static hasMany = [children: Child]
    static constraints = {
    }
}
class Child {
    String name
    static belongsTo = [parent: Parent]
    static constraints = {
    }
}
        def query1=Child.where{
            (name!=null)
        }
        def query2=Child.where{
            (parent.name!=null)
        }
        def results
        query1.list([max:5,sort:'parent.name'])
        query2.list([max:5])
        query2.list([max:5,sort:'parent.name'])
```

**Comment by rvachtl** [comment]
Following is the example:
https://github.com/rvachtl/grails_issue_9860_example

Test setup:

| Grails Version: 3.1.10
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_91

**Comment by graemerocher** [comment]
Sorting the results of a where query in Hibernate requires the use of an alias. See https://github.com/grails/gorm-hibernate5/commit/1e37c4552b781f35660e15b4e777f552315dd95c#diff-b55dc532d1e0c2d43eb5c540d4e2af0eR246

Additionally, I  found a bug in this behaviour which I fixed here https://github.com/grails/grails-data-mapping/commit/8f8a02e31b7a0f689a69c197dfe04c8d4ec7f8ae
