### ISSUE TITLE
Grails 3 : Problem with MultiTenant Domain - Controller methods Show, Update 

### ISSUE THREAD

**Issue by satshil** [grails/grails-core#9861]
Scenario
---------------------
grails 3.0.10
hibernate 4

Created application with 2 datasources defines ds1 and ds2

Domain class Employee with datasources= ['ds1,'ds2']
Controller class EmployeeController with method show(Employee e){...}  ,  update(Employee)
Screens create.gsp, update.gsp

Problem Statement
---------
I am able to create the record in db using employee."ds2".save() that creates a row in Ds2 database

but when I call show, the instance of employee is null because grails don't understand from which db to fetch it :(
So I do following

`show(){
Employee e = Employee."ds2".findById(params.id)
.....
}
`
This works fine in case of show.  But in logs I can see a call to DB which returns Nohing (may be a call made to ds1 by grails internal binding)

But the real problem arise when I try to update it.

existing code update(Employee e)
...  e is null

`update(){
Employee e = Employee."ds2".findById(params.id)
e.properties = params

if(!e.isDirty()){
     e.discard()
     show()
}
e."ds2".save()`

This never sets the isDirty() as true. My code always goes to discard() but the item is saved with changes().
My guess is the session does save it before the update() event is called.

Fixes Appllied
-----------

I like to understand how I can override this default loading of objects before the event.
 I tried doing following in bootstrap but its no use

`DefaultGrailsDomainClass.metaClass.static.get = {Serializable id ->
			println ("Domain Load :::::: " + delegate + " id = " + id)
		    delegate."ds2".findById(id)
		}`

**Comment by graemerocher** [comment]
Please upload an example to github that reproduces the issue

**Comment by satshil** [comment]
[testApp.zip](https://github.com/grails/grails-core/files/216963/testApp.zip)


Please find testApp attched.

Steps to reproduce.

1. Run-app
2. Add Employee.  try to see.  using show()
3. add following code into Show() method of EmployeeController.
if(!employee){
			employee = Employee.ds2.findById(params.id)
		}
Now you able to see it.
4. The auto binded instance in show(employee) is null because system cant understand which ds?

How I can override this default loading of bean?
In my actual application I pass this datasource name at runtime as a variavle. How I propagate it to transaction?
Please let me know if you need additional details.

**Comment by satshil** [comment]
While thinking about probable solution following comes to mind.
Creating a method in controller superclass (traits) which will allow us override in controller which allow us to return required dataSource or ds_name. Which will be used to retrieve/load domains. In absence of this overridden method we can return default datasource. i.e.

from superclass /trait

`def bindingDatasource(def dsname){

      return datasource;  (//default datasource)
}
`

from Controller


`@Override
def bindingDatasource(def dsname){

      return ctx.getBean("datasource_" + dsname);  (//default datasource)
}`

This just a high level thought. There may be better solutions. I am suggesting it with very low exposure to framework. The whole idea is to passing required datasource to system (using with or without transaction).

**Comment by graemerocher** [comment]
Duplicates https://github.com/grails/grails-data-mapping/issues/668

**Comment by satshil** [comment]
I haven't tested it with new code. But from the description it dosen't looks like it will fix issue of auto binding of domain instances in controllers.

Fix should answer following questions
================================
If I have a methods show(domainInstance), update(domainInstance) in my controller. This binding of domain is done by framework using id from params and before the method is called.
How my controller know which datasource it should get the instance from? when you use specific datasource and not 'ALL'

Does the fix for grails/grails-data-mapping#668 answers this? 

Also I never faced problem saving the new instance domain both on grails 3.0.10. That's broken in 3.1.x I raised a separate defect for it #9868
