### ISSUE TITLE
Grails 3.1.4 : Multiple datasource functionality broken. domain.datasource.save() throw error

### ISSUE THREAD

**Issue by satshil** [grails/grails-core#9868]
Problem Statement
------------------
I was working on grails 3.0.10 with multiple datasources. 
I recently upgraded to grails 3.1.4

Found the functionality for multiple dataSources is broken.
When I try to save domain with dataSource.

employeeInstance.ds1.save()

Attached please find the example. testApp.zip

[testApp.zip](https://github.com/grails/grails-core/files/219520/testApp.zip)

Steps to reproduce
-------
Run attached app. code already added in bootstrap results in error.

Error:

groovy.lang.MissingPropertyException: No such property: ds1 for class: testapp.Employee

**Comment by wvetrone** [comment]
I have issues with Multi-datasources too.  It doesn't create a second bean

**Comment by satshil** [comment]
@wvetrone can you add more details to issue. That might help the team to solve yours and co related issues.

**Comment by graemerocher** [comment]
Duplicates https://github.com/grails/grails-data-mapping/issues/668
