### ISSUE TITLE
Old issues tracked in JIRA are not valid URLs

### ISSUE THREAD

**Issue by runtimee** [grails/grails-core#9869]
For the Grails community, there are a lot of links to the JIRA site, e.g. https://jira.grails.org/browse/GRAILS-10113, but none of them are available after moving everything to github, which renders thousands of documentation worthless. Or is the old JIRA site archived?

**Comment by jeffbrown** [comment]
> Or is the old JIRA site archived?

The JIRA has been shut down for a while now.  We migrated all of this issues to GitHub issues.  The old links will not work, but the information still exists here.  For example, the issue you mentioned is at https://github.com/grails/grails-core/issues/5186.  If you search GitHub issues for the old JIRA number, that should work.
