### ISSUE TITLE
Grails 3.1.15 Auto reloading doesn't work with rest-api profile plugin and multi projects 

### ISSUE THREAD

**Issue by imaress** [grails/grails-core#9871]
I try with the new release of grails 3.1.15 and auto reloading with multi projects works great with web profile in the main app and the plugin after #9775 , but making this auto reloading doesn't work:

grails  create-app mayapp -profile=rest-api
grails create-plugin myplugin -profile=rest-api

If I use for the plugin no profile option or -profile=plugin auto reloading works but because the plugin works like web plugin. With rest-api profile and this config the app don't run because exploded config doesn't exist:
```
grails {
exploded=true
plugins{
compile project(":myplugin")
}
}
```
Then rest-api profile for plugins and multi project config doesn't work.
Thanks for all effort!!

**Comment by graemerocher** [comment]
This is probably because `grails create-plugin myplugin -profile=rest-api` doesn't actually create a plugin, we should fix this bug.

It creates another application since there is no `rest-api` profile for plugins at the moment.
