### ISSUE TITLE
src/main/groovy/resources/public not reloading

### ISSUE THREAD

**Issue by csoete** [grails/grails-core#9872]
(3.1.4) Resources added without using asset plugin (via `src/main/groovy/resources/public`) do not reload on change.

Use case: 

* Angular html template files without using angular profile.
* Other resources that do not fit the asset plugin structure (without writing an explicit plugin for it).

**Comment by csoete** [comment]
Workaround of using `src/main/webapp` directory seems to work.

**Comment by sagrawal14** [comment]
@graemerocher But `src/main/webapp` only gets included in WAR packaging but not in JAR packaging so what is the alternative of this?
