### ISSUE TITLE
A REST resource mapping like "/foo"(resources:'foo') hides other mappings that start with /foo

### ISSUE THREAD

**Issue by rbfinch** [grails/grails-core#9877]
A URL resource mapping like:

```
        "/foo"(resources: 'foo')
```

prevents another mapping for a path starting with `/path` from working.  For example, with a `FooController`, a `FooBarController, and this `URLMapping.groovy`:

```groovy
package controllertest

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/foo"(resources: 'foo')
    }
}
```

both http://localhost:8080/foo and http:/localhost:8080/fooBar get mapped to `FooController`.  In fact, it appears that http://localhost:8080/foo-with-anything-after-it gets mapped to `FooController`.

Tested in Grails 3.1.4 and 3.1.5.  Sample project at https://github.com/rbfinch/ControllerTest.  Do `grails run-app` and note that both http://localhost:8080/foo and http://localhost:8080/fooBar produce the same results.

**Comment by graemerocher** [comment]
Relates to #9849
