### ISSUE TITLE
3.1.5 - Error executing tag <g:form>: Name is null

### ISSUE THREAD

**Issue by linpete** [grails/grails-core#9878]
edit-View fails rendering since 3.1.5.  
Others still working.

Trace:  
  Line | Method
->>   46 | createGroovyPageException    in C:\[...]\grails-app\views\patient\edit.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by GrailsTagException: [views/patient/edit.gsp:46] Error executing tag <g:form>: Name is null
->>   46 | doCall                       in views/patient/edit.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by NullPointerException: Name is null
->>  236 | valueOf                      in java.lang.Enum
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

^    745 | run                          in java.lang.Thread

in Grails 3.1.4 the exactly same page renders fine.
Release notes dont mentionn such stuff.

Thx for your suggestions.

[edit.gsp.zip](https://github.com/grails/grails-core/files/222353/edit.gsp.zip)

**Comment by jeffbrown** [comment]
Please link to an app which demonstrates the problem, not just the isolated GSP.

Thanks for the feedback.

**Comment by linpete** [comment]
Here you are.
Just call the index of the Patient Controller.
This should create an Domain Instance and hand it to the view.
[t315.zip](https://github.com/grails/grails-core/files/222540/t315.zip)

**Comment by NeilEcker** [comment]
Just adding that I see the same behaviour with both 3.1.5 and 3.1.6.  If I remove the resource attribute such as resource="${this.patient}" from linpete's example, the edit form renders but then of course the record won't be updated.

**Comment by linpete** [comment]
Retsted IT ans everything ist doing fine.
Migrated two Applications wirhout further issues.
Thx a lot to the whole Team!
You are doing a Great Job.
Groovy/Grails rules !
Keep it going.
