### ISSUE TITLE
3.1.4 -> 3.1.5 DB Column Mapping Migration Issue

### ISSUE THREAD

**Issue by csoete** [grails/grails-core#9881]
Just tried to switch one project from 3.1.4 to 3.1.5 and I am having problems with columns that have a custom mapping (required by database requirements because of reserved keywords no/password):

```
SampleDomain
{
    String password

	static mapping = {
		password column: '`password`'
	}
}

```
Removing the mapping fixes the bug for caching I believe but messes up the database schema creation. Switching back to 3.1.4 fixes the issue naturally.

**Comment by graemerocher** [comment]
Duplicates https://github.com/grails/grails-data-mapping/issues/702
