### ISSUE TITLE
[3.1.5]run-app fail even HelloWorld app

### ISSUE THREAD

**Issue by MMKnight** [grails/grails-core#9882]
First time:Running
Second Time: :bootRun failed
Third Time: :bootRun failed
Fourth Time: Running

Sometime I have to run it twice,thrice or a lots.

+It only worked on my first app created.
+After delete the app and create new one,run-app no longer run perfectly
+war run perfectly.

+Stacktrace

>          at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
> (ResetDeprecationLogger.java:26)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
> execute(RequestStopIfSingleUsedDaemon.java:34)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
> ardClientInput.java:74)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
> ardClientInput.java:72)
>         at org.gradle.util.Swapper.swap(Swapper.java:38)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
> wardClientInput.java:72)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(
> DaemonHealthTracker.java:47)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
> t.java:66)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
> CommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
> ild(EstablishBuildEnvironment.java:72)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
> CommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(Hin
> tGCAfterBuild.java:41)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
> run(StartBuildOrRespondWithBusy.java:50)
>         at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
> StateCoordinator.java:246)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
> onExecute(ExecutorPolicy.java:54)
>         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
> xecutorImpl.java:40)
> Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Progr
> am Files\Java\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 1
>         at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
> rmalExitValue(DefaultExecHandle.java:367)
>         at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJava
> ExecAction.java:31)
>         at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:75)
>         at org.springframework.boot.gradle.run.BootRunTask.exec(BootRunTask.java
> :63)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
> actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
> actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
> actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
> ctTask.java:585)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
> ctTask.java:568)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
> ecuteAction(ExecuteActionsTaskExecuter.java:80)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
> ecuteActions(ExecuteActionsTaskExecuter.java:61)
>         ... 70 more
> 
> | Error Failed to start server (NOTE: Stack trace has been filtered. Use --verbo
> se to see entire trace.)
> java.util.concurrent.ExecutionException: org.gradle.tooling.BuildException: Coul
> d not execute build using Gradle distribution 'https://services.gradle.org/distr
> ibutions/gradle-2.10-bin.zip'.
>         at java_util_concurrent_Future$get.call(Unknown Source)
>         at run-app.run(run-app.groovy:89)
>         at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(Gro
> ovyScriptCommand.groovy:152)
>         at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.
> groovy:452)
>         at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:372)
>         at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:345)
>         at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:274)
>         at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
> Caused by: org.gradle.tooling.BuildException: Could not execute build using Grad
> le distribution 'https://services.gradle.org/distributions/gradle-2.10-bin.zip'.
> 
>         at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(R
> esultHandlerAdapter.java:59)
>         at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerAction
> Executor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
> onExecute(ExecutorPolicy.java:54)
>         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
> xecutorImpl.java:40)
>         at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(
> BlockingResultHandler.java:46)
>         at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(Default
> BuildLauncher.java:72)
>         at org.grails.cli.gradle.GradleUtil$_runBuildWithConsoleOutput_closure5.
> doCall(GradleUtil.groovy:122)
>         at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure3.doCa
> ll(GradleUtil.groovy:102)
>         at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure3.call
> (GradleUtil.groovy)
>         at grails.io.support.SystemOutErrCapturer.withNullOutput(SystemOutErrCap
> turer.groovy:64)
>         at org.grails.cli.gradle.GradleUtil.withProjectConnection(GradleUtil.gro
> ovy:101)
>         at org.grails.cli.gradle.GradleUtil.runBuildWithConsoleOutput(GradleUtil
> .groovy:117)
>         at org.grails.cli.gradle.GradleInvoker.invokeMethod(GradleInvoker.groovy
> :50)
>         at org.grails.cli.gradle.GradleAsyncInvoker$_invokeMethod_closure2.doCal
> l(GradleAsyncInvoker.groovy:57)
>         at org.grails.cli.gradle.GradleAsyncInvoker$_invokeMethod_closure2.doCal
> l(GradleAsyncInvoker.groovy)
> Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution fail
> ed for task ':bootRun'.
>         at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultE
> xceptionAnalyser.java:74)
>         at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.tran
> sform(MultipleBuildFailuresExceptionAnalyser.java:47)
>         at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.trans
> form(StackTraceSanitizingExceptionAnalyser.java:30)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
> eLauncher.java:101)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
> eLauncher.java:93)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
> tBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
> tBuildOperationExecutor.java:62)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
> Launcher.java:93)
>         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
> cher.java:82)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
> troller.run(InProcessBuildActionExecuter.java:94)
>         at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.ru
> n(BuildModelActionRunner.java:46)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
> ctionRunner.java:35)
>         at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRu
> nner.run(SubscribableBuildActionRunner.java:58)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
> ctionRunner.java:35)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
> ssBuildActionExecuter.java:43)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
> ssBuildActionExecuter.java:28)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
> uousBuildActionExecuter.java:78)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
> uousBuildActionExecuter.java:48)
>         at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
> ild.java:52)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
> CommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
> WatchForDisconnection.java:37)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
> (ResetDeprecationLogger.java:26)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
> execute(RequestStopIfSingleUsedDaemon.java:34)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
> ardClientInput.java:74)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
> ardClientInput.java:72)
>         at org.gradle.util.Swapper.swap(Swapper.java:38)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
> wardClientInput.java:72)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(
> DaemonHealthTracker.java:47)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
> t.java:66)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
> CommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
> ild(EstablishBuildEnvironment.java:72)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
> CommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(Hin
> tGCAfterBuild.java:41)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
> DaemonCommandExecution.java:120)
>         at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
> run(StartBuildOrRespondWithBusy.java:50)
>         at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
> StateCoordinator.java:246)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
> onExecute(ExecutorPolicy.java:54)
>         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
> xecutorImpl.java:40)
> Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for tas
> k ':bootRun'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
> ecuteActions(ExecuteActionsTaskExecuter.java:69)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
> ecute(ExecuteActionsTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
> uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
> ute(SkipUpToDateTaskExecuter.java:64)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
> e(ValidatingTaskExecuter.java:58)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
> ter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
> .execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
> e(SkipOnlyIfTaskExecuter.java:53)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
> .execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
> skWorker.execute(DefaultTaskGraphExecuter.java:203)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
> skWorker.execute(DefaultTaskGraphExecuter.java:185)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
> orker.processTask(AbstractTaskPlanExecutor.java:66)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
> orker.run(AbstractTaskPlanExecutor.java:50)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
> tTaskPlanExecutor.java:25)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
> ltTaskGraphExecuter.java:110)
>         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
> ExecutionAction.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
> r.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExec
> uter.java:23)
>         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
> ter.java:43)
>         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
> ecutionAction.java:32)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
> r.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
> r.java:30)
>         at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLa
> uncher.java:154)
>         at org.gradle.internal.Factories$1.create(Factories.java:22)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
> tBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
> tBuildOperationExecutor.java:52)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
> GradleLauncher.java:151)
>         at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
> dleLauncher.java:32)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
> eLauncher.java:99)
>         ... 42 more
> Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Progr
> am Files\Java\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 1
>         at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
> rmalExitValue(DefaultExecHandle.java:367)
>         at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJava
> ExecAction.java:31)
>         at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:75)
>         at org.springframework.boot.gradle.run.BootRunTask.exec(BootRunTask.java
> :63)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
> actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
> actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
> actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
> ctTask.java:585)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
> ctTask.java:568)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
> ecuteAction(ExecuteActionsTaskExecuter.java:80)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
> ecuteActions(ExecuteActionsTaskExecuter.java:61)
>         ... 70 more
> | Error Failed to start server

**Comment by graemerocher** [comment]
This is down to your internet connection not functioning correctly or your proxy settings

**Comment by MMKnight** [comment]
> This is down to your internet connection not functioning correctly or your proxy settings

That's mean because of internet connection. I would try another day. Thank you.

**Comment by MMKnight** [comment]
Grails has to use proxy right?

**Comment by MMKnight** [comment]
+grails run-app perfect when using with minecraft.
