### ISSUE TITLE
[3.1.5] Plugin's onStartup() method not run.

### ISSUE THREAD

**Issue by budjb** [grails/grails-core#9883]
I'm using the `onStartup` method of the plugin's `Plugin` class to do some initialization, as it needs to occur around the same time as `Bootstrap` is run. During integration tests, this method is not called for my plugin. Manually registering a `GrailsApplicationLifeCycle` bean with that logic allows me to work around this, but it would be better if the plugin's `onStartup` was called without the need for an additional bean.

**Comment by budjb** [comment]
Actually I'm not seeing the `onStartup` being called at all for plugins. Going to change the title of this accordingly.

**Comment by ColinHarrington** [comment]
`onStartup()` was introduced in Grails 3 in 26e6afd36cf20e224bce7c61895495af50a88004

Plugins implement `GrailsApplicationLifeCycle` but are not currently notified since they aren't spring beans.

**Comment by budjb** [comment]
:+1: thanks!
