### ISSUE TITLE
Performance Optimization In GrailsControllerUrlMappingInfo

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-core#9886]
We are seeing consistently bad/long running performance against GrailsControllerUrlMappingInfo in instrumented code in our running application.  However the tools we are using don't offer any deeper insight into the actual issue.  Our UrlMappings files have 70 mappings in them.  This could be related to the `@Delegate`.  Any thoughts on this before I go chasing down ways to make this faster?  This accounts for a large chunk of most of our request overhead in the application.  There is a potential huge core grails bottleneck that can be freed up by optimizing this code.  I wanted to log this here so I have something to post comments to that is not lost in slack.

<img width="1352" alt="screen shot 2016-04-20 at 4 07 24 pm" src="https://cloud.githubusercontent.com/assets/691357/14690677/ce0ac880-0712-11e6-96c6-4c305af6c040.png">

<img width="1344" alt="screen shot 2016-04-20 at 3 33 46 pm" src="https://cloud.githubusercontent.com/assets/691357/14690676/ce09ae96-0712-11e6-91ff-ede69dd6c5cd.png">

**Comment by ColinHarrington** [comment]
What version of Grails?  Java? OS?

**Comment by ctoestreich** [comment]
Grails 3.1.0 - 3.1.5
Java 8u72
OS Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by ctoestreich** [comment]
@ColinHarrington Have any spare yourkit licenses laying around!? 😆

**Comment by ctoestreich** [comment]
Closing until we can isolate and pinpoint.

**Comment by sergiodelamoshoptimix** [comment]
I am seeing the same problem as well. We are using New Relic to track performance and apparently our biggest bottle neck is GrailsControllerUrlMappingInfo.

 We have around 50 entries in our UrlMapping. An example of such an entry will be:

```
group("/api") {
            "/deployments"(controller: "deployments", action: "list", method: "get")
}
```

**Comment by graemerocher** [comment]
An example on github that reproduces the issue would be good

**Comment by graemerocher** [comment]
that particular class doesn't do much, so it would have to be something else

https://github.com/grails/grails-core/blob/master/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/mvc/GrailsControllerUrlMappingInfo.groovy

**Comment by ctoestreich** [comment]
@sergiodelamoshoptimix We assume this an issue with how New Relic instruments the code.  I think the GrailsControllerUrlMappingInfo.groovy class is involded in every request to resolve the actual class that does the work and the New Relic Instrumentation stops at this class or thinks this is the actual class that is running when it appears that the class actually is delegating the work which NR must not like.  We are still looking at other tools to see if we can hammer out actual perf problems.

**Comment by sdelamo** [comment]
@graemerocher @ctoestreich Thanks for the explanation. I think you are right and New Relic is attributing most of the executing time to GrailsControllerUrlMappingInfo while the time is actually spent in Controllers and Services.

**Comment by benorama** [comment]
@sdelamo did you report the issue to NewRelic?

It looks like they officially support 1.x and 2.x version, but maybe not yet 3.x?
https://newrelic.com/java/grails

**Comment by ColinHarrington** [comment]
@sdelamo This behavior is similar to what we saw before New Relic supported Grails 1.x or 2.x.  I would guess that they have a little bit of work to do to support Grails 3

**Comment by ColinHarrington** [comment]
I've requested that they do the same for Grails 3
[Feature Request](https://discuss.newrelic.com/t/grails-3-support/37362)

**Comment by ctoestreich** [comment]
One thing that helps is to turn off Auto Naming for transactions in your New Relic account.

**Comment by ctoestreich** [comment]
[Reference](https://docs.newrelic.com/docs/agents/java-agent/instrumentation/naming-web-transactions)

Disabling component-based naming
=====

For some applications, you may want to disable component-based transaction naming. Set this value in your newrelic.yml file:
enable_auto_transaction_naming: false
Unless you implement API calls to name your transactions, disabling auto-transaction naming is very likely to cause [Metric grouping issues](https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/metric-grouping-issues).

Per their docs you may have to add back in the group mapping url stuff.  We got burned on our /search endpoint and had to add a /search/* mapping to group with the auto naming off.

**Comment by sdelamo** [comment]
Hi @ctoestreich Thanks for suggesting the disabling component-based naming. It helps indeed.

@benorama , I have upvoted the @ColinHarrington feature request. Lets see if they bring Grails 3 support on.
