### ISSUE TITLE
Upgrade To Tomcat 7.0.69

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9891]

**Comment by jeffbrown** [comment]
IMPORTANT:

We have to update https://github.com/grails/grails-core/commit/a2f19c0b92ed5d5e084529b4803ac2d18c74e5c6 once the plugin is released.  I am leaving this issue open until that is done.

**Comment by fergarri** [comment]
hello, this not work.
I try change grails version 2.5.4 to 2.5.5 so I change the line build ":tomcat:7.0.55.3" to build ":tomcat:7.0.69-SNAPSHOT" but grails not compile.
What I must do to this work?

**Comment by fergarri** [comment]
Thanks, works fine!!

**Comment by graemerocher** [comment]
@jeffbrown is this issue done? Can it be closed?

**Comment by jeffbrown** [comment]
@graemerocher I think so.  I upgraded to 7.0.70 this morning.  Is https://github.com/grails/grails-core/commit/59678b4b18c40b13c6f7fea00261de3b43d692a8 and https://github.com/grails-plugins/grails-tomcat-plugin/commit/0dfa022890c6e2847623fb850b88d781bea9f639 all that needs to happen?

**Comment by graemerocher** [comment]
yeah, was the plugin actually published?

**Comment by jeffbrown** [comment]
No.  I just pushed the commits linked above a few minutes ago.  That is all that has happened.

**Comment by jeffbrown** [comment]
Version 7.0.70 of the plugin has now been published: http://repo.grails.org/grails/plugins-releases-local/org/grails/plugins/tomcat/7.0.70/
