### ISSUE TITLE
3.0.16: Reloading is broken on Windows for inline plugins (already fixed in 3.1.x) 

### ISSUE THREAD

**Issue by flofreud** [grails/grails-core#9892]
The underlaying issue with path handling in `IOUtils` was solved by resolution for #9637 in the 3.1.x branches (see ee0c1c2025529d5ca681eb07b6095393566dc37c). The same issue is also in the 3.0.x branch and a backport would be great. 

Due to this path handling issue the `projectDirectory` property for inline plugins will always be set to `null` on Windows systems. Therefore no watchers will be defined for the inline plugins (see https://github.com/grails/grails-core/commit/7e319fa8a5d0969ad32df9776bcc39bcdaa2a555#diff-8c6f973b16bc0d66d3183ff5efca3e6aR137)

- **Operating System**: Windows 10
- **Grails Version:** Grails 3.0.16
- **JDK Version:** 8u66

**Comment by graemerocher** [comment]
Back ported the fixes https://github.com/grails/grails-core/commit/bea2c14dae79b56714552e36b6de94ba0b62b2b8
