### ISSUE TITLE
unnecessary Gorm Query on hasMany (child) objects

### ISSUE THREAD

**Issue by AjitDeswal** [grails/grails-core#9897]
Hi ,

 I have a domain name DR, Observation like :-

class DR{
     static hasMany {result: Observation}
}

class Observation{
   ......
}

I got DR list from database using gorm.
But when i hit Dr,result  it hits a query to mongo even when the persistent set of 
Observation is empty .
Please guide me because in my case i have to traverse over millions of DR objects 
which result in unnecessary query for Observation even when only few DR objects have that data.

**Comment by graemerocher** [comment]
As specified in 

https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

Issues should provide:

* Steps to reproduce
* Stacktrace (if present) provided
* Example that reproduces the problem uploaded to Github
* Full description of the issue provided

If the issue report is not submitted correctly it will be rejected.
