### ISSUE TITLE
application.groovy mode config not parseable for codegen

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#9899]
### Steps to Reproduce

1. create a grails 3.1.5 app
2. convert application.yml to application.groovy config
3. try to run a create script like create-interceptor...

### Expected Behaviour

The interceptor should be placed in the appropriate package folder

### Actual Behaviour

It is being placed as @package@ and not parsing the default package name from application.groovy

### Environment Information

- OS X
- 3.1.5
- JDK 8

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-core/pull/10075
