### ISSUE TITLE
view not found error after calling response.sendError()

### ISSUE THREAD

**Issue by burtbeckwith** [grails/grails-core#9900]
In 2.5.x it's possible to set a status code in a controller action with `response.sendError()` and this will prevent Grails from looking for a view to render:

    def someAction() {
       response.sendError 401
    }

This works in run-app in 3.1.x but fails when deployed as a WAR. Explicitly committing the response with a call to `response.flushBuffer()` works around the problem:

    def someAction() {
       response.sendError 401
       response.flushBuffer()
    }

Obviously there are other more idiomatic workarounds using `render` or `respond` but this approach should still work.

Tested with 2.5.3 and 3.1.5 and deployed to Tomcat 8.0.30

**Comment by graemerocher** [comment]
I guess to fix this we would have to wrap the response, which we don't currently do. View rendering is only aborted if you the response has been committed, hence why `flushBuffer()` works.

**Comment by burtbeckwith** [comment]
So why did it work in earlier versions?

**Comment by graemerocher** [comment]
I believe because we wrapped the response using an `HttpServletResponseWrapper` in Grails 2.x but we don't wrap the response in 3.x
