### ISSUE TITLE
Grails JSON converter accepts invalid JSON

### ISSUE THREAD

**Issue by berdario** [grails/grails-core#9907]
This would be a minor problem, but apparently there's no way to use a custom JSON decoder/converter in Grails. There are several examples of how to serialize in a custom way, but nothing about how to handle differently your request content-type:

http://grails.github.io/grails-doc/3.1.4/ref/Controllers/withFormat.html
https://grails.org/wiki/Converters%20Reference
https://github.com/pedjak/grails-marshallers

I'm sure that there's a way in Spring to change this behaviour but, even if you don't foresee people using a different converter, at least you should allow for some configuration to enable sane behavior (which should arguably be the default, but I agree that changing this now could potentially break lots of stuff)
### Steps to Reproduce

```
import grails.converters.JSON
JSON.parse("{a:a}")
```
### Expected Behaviour

Raise some exception
### Actual Behaviour

It returns `[a:a]`
### Environment Information
- **Grails Version:** 3.1.3 (we use Grails 2.5, but I checked that this hasn't changed also with a more recent version)

While I was looking into this issue, I also noticed some other inconsistencies/brittleness: `-` is parsed as `[:]`, just like other primitive literals:

```
groovy:000> JSON.parse("-")
===> [:]
groovy:000> JSON.parse("1")
===> [:]
groovy:000> JSON.parse("a")
===> [:]
groovy:000> JSON.parse("'a'")
===> [:]
```

Unlike other broken inputs:

```
groovy:000> JSON.parse("")
ERROR org.grails.web.converters.exceptions.ConverterException:
groovy:000> JSON.parse("}")
ERROR org.grails.web.converters.exceptions.ConverterException:
```

Also, floats can be roundtripped back into strings:

```
groovy:000> JSON.parse(([Float.POSITIVE_INFINITY] as JSON) as String)[0].class
===> class java.lang.String
```

For comparison, `groovy.json` either raises exception, or parse literals with the actual value you'd expect them to have (which granted: is not valid JSON either, but is still less wrong than `grails.converter.JSON`... ideally it'd take inspiration from more rigorous libraries that actually reject JSON objects/maps with non string keys)

**Comment by jameskleeh** [comment]
The converter api is deprecated. Please use JSON views
