### ISSUE TITLE
Unique Constraint on UUID data type throws an exception in unit tests only

### ISSUE THREAD

**Issue by HopefulLlama** [grails/grails-core#9911]
Given a domain object has a property of a UUID data type, which also has a unique constraint set on it, when unit tested, it will throw the exception shown below. 

`org.springframework.dao.InvalidDataAccessResourceUsageException: Cannot query [com.example.package.ExampleDomainObject] on non-existent property: uuid`

However, when manually tested through normal execution of code, the constraint and object in general behaves as expected.

I would however, also like to point out that I am currently running on an older version of Grails. I was unable to find able relevant issues raised to this.
### Steps to Reproduce
1. Define a domain object which has a unique constraint on a UUID data type.

```
package com.example.package

class ExampleDomainObject {
    UUID uuid

    static constraints {
        uuid unique: true
    }
}
```
1. Run ANY unit test which calls/interacts with that object in any way. E.g. Try instantiating or creating a new ExampleDomainObject.
2. ./grailsw test-app
### Expected Behaviour

The unit test should run fine, as it does when the code is being execute as per normal.
### Actual Behaviour

Any unit test which calls/interacts with the object with the offending UUID + unique constraint throws the exception: 

`org.springframework.dao.InvalidDataAccessResourceUsageException: Cannot query [com.example.package.ExampleDomainObject] on non-existent property: uuid`
### Environment Information
- **Operating System**: Ubuntu 14.04.4 LTS
- **Grails Version:** 2.4.3
- **JDK Version:** jdk1.7.0_79 (Oracle Java 7)

**Comment by jameskleeh** [comment]
The current behavior is due to a custom type marshaller not existing for UUID
