### ISSUE TITLE
Grails not reading config file properly but ConfigSlrper reads perfectly

### ISSUE THREAD

**Issue by AjitDeswal** [grails/grails-core#9914]
Task List

Steps to Reproduce
1) create config file (dbConfiguration):-
    grails{
		mongo  {
			host = "at3"
			port=37018
			databaseName = "dev_consus"
		}
	}
	grails.mongo.password="admin"
	grails.mongo.databaseName="test"

2) grailsApplication.config.grails.mongo

Expected Behaviour
1) grails{
		mongo  {
			host = "at3"
			port=37018
			databaseName = "test"
			password = "admin"
		}
	}

Actual Behaviour
1) grails{
		mongo  {
			host = "at3"
			port=37018
			databaseName = "dev_consus"
			password = "admin"	
		}
	}

Note:- if i use ConfigSlurper
       1)ConfigObject configObj = new ConfigSlurper().parse(new File(dbConfiguration).text)
	   2)configObj.grails.mongo
	   
	   then it show the expected result.
	   grails{
			mongo  {
				host = "at3"
				port=37018
				databaseName = "test"
				password = "admin"
			}
		}
	
Environment Information

Operating System: Windows 10
Grails Version: 2.4.4
JDK Version: 1.7
Container Version (If Applicable): Tomcat6

**Comment by graemerocher** [comment]
Grails 2.4.x is no longer a supported version and modifying the config post load is not recommended in this way in 3.x
