### ISSUE TITLE
Grails not reading config file properly but ConfigSlrper reads perfectly

### ISSUE THREAD

**Issue by AjitDeswal** [grails/grails-core#9918]
Task List

Steps to Reproduce
1) create config file (dbConfiguration):-
grails{
   mongo {
      host = "at3" 
      port=37018
      databaseName = "dev_consus"
   }
}

2) create config file (external-config) which is controlled by client:-
    grails.mongo.password="admin"
    grails.mongo.databaseName="test"

2) grailsApplication.config.grails.mongo

Expected Behaviour
1) grails{
   mongo {
      host = "at3"
      port=37018
      databaseName = "test"
      password = "admin"
   }
}

Actual Behaviour
1) grails{
        mongo {
            host = "at3"
            port=37018
            databaseName = "dev_consus"
            password = "admin"
        }
}

Note:- if i use ConfigSlurper
1)ConfigObject configObj = new ConfigSlurper().parse(new File(external-config).text)
2)merge with grails config
3)configObj.grails.mongo

   then it show the expected result.
   grails{
        mongo  {
            host = "at3"
            port=37018
            databaseName = "test"
            password = "admin"
        }
    }
Environment Information

Operating System: Windows 10
Grails Version: 2.4.4
JDK Version: 1.7
Container Version (If Applicable): Tomcat6

**Comment by graemerocher** [comment]
duplicates #9914

**Comment by AjitDeswal** [comment]
Sir , as per grails feature its provide a support of external-config which can be overriden by
client. So, as per this scenario 
grails.mongo.password="admin"
grails.mongo.databaseName="test"

these configuration are as part of external config which is done by client.

So please provide me a solution that i can tell to my client regarding this.
Because as per them they can change the host of the mongo db in external config.
If there is not any solution for this than i have to fix it definatley by some hack. 


Please help on this issue.

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
