### ISSUE TITLE
Grails 3.x not reading external-config file properly

### ISSUE THREAD

**Issue by AjitDeswal** [grails/grails-core#9920]
Task List

Steps to Reproduce
1) create config file (dbConfiguration):-

    grails{ 
        mongo {
            host = "at3" 
            port=37018
            databaseName = "dev_consus"
        }
    }

2) create config file (external-config) which is controlled by client:-

    grails.mongo.password="admin"
    grails.mongo.databaseName="test"

2) grailsApplication.config.grails.mongo

Expected Behavior

    grails{
        mongo {
            host = "at3"
            port=37018
            databaseName = "test"
            password = "admin"
        }
    }

Actual Behaviour

    grails{ 
        mongo {
            host = "at3"
            port=37018
            databaseName = "dev_consus"
            password = "admin"
        }
    }

Environment Information

Operating System: Windows 10
Grails Version: 2.4.4
JDK Version: 1.7
Container Version (If Applicable): Tomcat6

**Comment by jeffbrown** [comment]
Can you describe how you are loading up the external configs?

**Comment by graemerocher** [comment]
Upload an example that reproduces the issue to github

**Comment by AjitDeswal** [comment]
in config.groovy below is the code to load external-config file:-

if (System.getenv(MINERVA_SRV_CONFIG_LOCATION )) {
    grails.config.locations.add("file:${System.getenv(MINERVA_SRV_CONFIG_LOCATION )}")
}

**Comment by Luxor** [comment]
Would be nice to have this feature in grails 3.

**Comment by Luxor** [comment]
Btw, if load a config in application groovy. @value injects still hold old value

**Comment by Schlogen** [comment]
@AjitDeswal The title says 3.x, but the description says 2.4.4. Which is it?

**Comment by AjitDeswal** [comment]
Hi I have tried it on both grails 2.4.4 and grails 3.x

**Comment by graemerocher** [comment]
There are already several ways to externalise configuration provided by Boot all of which work with Grails. See http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
