### ISSUE TITLE
Changes in inplace plugin code in grails3.x are not reloading automatically

### ISSUE THREAD

**Issue by girisagar46** [grails/grails-core#9921]
I am upgrading a project from Grails 2.5.1 to Grails 3.1.6.

My Multi-Project Build structure in Grails 3.1.6 is as follows: 

`- Root
   |--MainProject
   |--Pugin1ForMain
   |--Plugin2ForMain
   |--settings.gradle
`

I run the MainProject using grails run-app command and whenever I change my codes in Plugin1ForMain or any other plugins, the changes are not automatically recompiled like it did in Grails2.x .

Some research led me to this blog: http://mrhaki.blogspot.com/2015/11/grails-goodness-enable-hot-reloading.html and I implemented in development environment but reloading does not work.

When I create dummy projects and plugins, the reloading works fine. Reloading issue only occurs when I start moving codes from 2.5.1 to 3.1.6 project structure.

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

**Comment by girisagar46** [comment]
Sorry Graeme, didn't knew about the ISSUE_TEMPLATE.
My real issue is auto reloading of **implace plugins** isn't working in Grails 3.1.6 as it did in Grails2.x.

# Steps to reproduce:
- clone https://github.com/girisagar46/Grails3ReloadTest
- cd to 'racetrack' folder
- change mysql password, database url (since I am using MySQL)
- Run the racetrack using `run-app` command 
- change the code of plugin (add a controller or change the existing code in **racetrackplugin**)
- the project won't recompile the changes in racetrackplugin

# Expected behaviour
- The changes in inplace plugin should reflect in the main application when app is s

# Actual Behaviour
- The changes won't recompile

# Environment Information
Operating System: Linux Ubuntu 14.04
Grails Version: 3.1.6
JDK Version: 1.8.60
Gradle Version: 2.12

# Example Application
https://github.com/girisagar46/Grails3ReloadTest

**Comment by graemerocher** [comment]
will take a look

**Comment by jeffbrown** [comment]
The steps above describe adding a new controller to the plugin.  Is it the case that adding new artifacts doesn't work but editing existing artifacts does work?

**Comment by girisagar46** [comment]
@jeffbrown Adding new artifact or editing an existing one, both doesn't seem to be working.

**Comment by graemerocher** [comment]
There are a couple of problems in the attached example that prevent the reloading from working:

a) you are using an old version of Gradle which is picked up by Grails https://github.com/girisagar46/Grails3ReloadTest/blob/master/RaceTrack/gradle/wrapper/gradle-wrapper.properties#L6

b) You have hard coded the profile version to an older version (3.1.0) instead of using 3.1.6:
https://github.com/girisagar46/Grails3ReloadTest/blob/master/RaceTrack/racetrack/build.gradle#L56

Both of these together prevent reloading working. When I updated the Gradle wrapper version to 2.13 and use the 3.1.6 `web` profile it works fine.
