### ISSUE TITLE
Incorrect request and response are used

### ISSUE THREAD

**Issue by burtbeckwith** [grails/grails-core#9924]
When GrailsDispatcherServlet was simplified for Grails 3 an important step was removed. Previously in `doDispatch()` a new `GrailsWebRequest` was [constructed and stored based on the currently bound instance](https://github.com/grails/grails-core/blob/2.5.x/grails-web/src/main/groovy/org/codehaus/groovy/grails/web/servlet/GrailsDispatcherServlet.java#L295) but using the `request` and `response` passed to the method. Since the servlet is called after the filter chain runs the request and/or response could have been proxied/wrapped with HttpServletRequestWrapper/HttpServletResponseWrapper and this ensured that the thread-local request and response that are accessed from controllers were the same instances that had been prepared and used previously during request processing.

This logic was removed and currently a single `GrailsWebRequest` is created and bound by `GrailsWebRequestFilter` but the logic in `buildRequestAttributes()` just [uses the existing bound instance if it exists](https://github.com/grails/grails-core/blob/master/grails-web-mvc/src/main/groovy/org/grails/web/servlet/mvc/GrailsDispatcherServlet.groovy#L56) rather than creating a new one. But the previous instance references the original request and response, not the updated instances.

**Comment by ctoestreich** [comment]
We are seeing instances of using request attributes polluting the global scope and causing a single named request attribute to become used in all requests.  It happens after boot and on the first request.  Could be related.  Will post code tomorrow.

**Comment by ctoestreich** [comment]
It happens very seldem but we have hit it 4 times in the last few months.

**Comment by graemerocher** [comment]
I guess the question is where are you wrapping the `request` and `response`? Wouldn't it just be easier to run whatever filter is performing the wrapping prior to `GrailsWebRequestFilter`

**Comment by graemerocher** [comment]
@burtbeckwith I don't really want to fix this as it complicates the internals and I'm not sure it is the right thing to do. The correct thing to do is for whatever plugins needs to wrap the request or response to place the filter prior to the `GrailsWebRequestFilter` which you can do by defining the order using a `FilterRegistrationBean` 

https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L105

If there is some additional reason why this is not a valid solution let me know.
