### ISSUE TITLE
updating a GORM instance from a controller does not persist changes made to the DB

### ISSUE THREAD

**Issue by jerojasro** [grails/grails-core#9927]
## Steps to reproduce

  1. Fetch an existing GORM instance/DB record from a controller method.
  1. Update one of its fields.
  1. Call the `.save()` method of the instance.

## Expected Behaviour

The modification performed should be persisted to the DB.

## Actual Behaviour

The modifications made are not persisted to the DB.

## Sample code

```groovy

class TestController {
    ...
    def increase() {
        def b = Book.get(params.id)
        b.value = b.value + 1
        b.save()  // changes don't make it to the DB, even after the request finishes, or app shutdown
        render "ID: ${b.id}. New Value: ${b.value}"
    }
}
```
## Environment Information

- **Operating System**: Debian Stretch, x86/64
- **Grails Version:** 2.5.4, 2.4.5
- **JDK Version:** 
```
      $ java -version
      java version "1.8.0_74"
      Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
      Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```
## Example Application

See https://github.com/jerojasro/grails-canary

**Comment by graemerocher** [comment]
You should be doing this work in a transaction, otherwise you must call `obj.save(flush:true)`

**Comment by jerojasro** [comment]
Thanks for the hint.

Nonetheless, it's a quite inconsistent behaviour; while in a controller method, some DB operations succeed (INSERTs), while others (UPDATEs) don't, and I can't find it such behaviour documented anywhere (if this is the intended behaviour, that is).

**Comment by graemerocher** [comment]
no transactional boundaries == inconsistent behaviour so that doesn't surprise me
