### ISSUE TITLE
StackTrace Logger doesn't work

### ISSUE THREAD

**Issue by slackboxster** [grails/grails-core#9934]
I originally posted this as a [question on StackOverflow](http://stackoverflow.com/questions/36723285/why-does-stacktrace-log-not-fill-with-logback-in-grails-3). I'm thinking (if I'm not missing something very obvious) this might actually be a bug.

Given this (simplified default) logback.groovy (and omitting the top of the file):

```
root(ERROR, ['STDOUT'])

appender("FULL_STACKTRACE", FileAppender) {
    file = "build/stacktrace.log"
    append = true
    encoder(PatternLayoutEncoder) {
        pattern = "%level %logger - %msg%n"
    }
}
logger("StackTrace", ERROR, ['FULL_STACKTRACE'], false )
```

and this Bootstrap.groovy:

```
class BootStrap {

    def init = { servletContext ->
        log.error 'this is a new error'
    }
    def destroy = {
    }
}
```

Running the grails application will not produce any output into `build/stacktrace.log`.

If you remove the StackTrace logger, and add FULL_STACKTRACE to the root logger:

```
root(ERROR, ['STDOUT', 'FULL_STACKTRACE']
```

you will get output into the stacktrace.log.

Alternatively, rename the StackTrace logger to grails.app.init.Bootstrap:

```
logger 'grails.app.init.BootStrap', ERROR, ['FULL_STACKTRACE'], false
```

and you will get output into the stacktrace.log

## My conclusions:

* The `StackTrace` logger doesn't do anything. 
* Further, only `logger`s given package / fully qualified class names result in logs being created.

But I am curious: why does the default Grails 3 logback.groovy file contain code that, to me, very obviously does nothing (and is therefore misleading)? 

I've ran those three samples in new applications and observed the above behavior with both 3.1.0.RC2, and 3.1.6.

**Comment by hamdrew** [comment]
I have noticed this behavior in v3.1.8 as well. The [Logback Groovy configuration](http://logback.qos.ch/manual/groovy.html) docs seem to want a package name for the logger name. What happens if you change the name of the logger to match the package in which you are logging the error?

**Comment by rlovtangen** [comment]
`log.error 'this is a new error'` doesn't throw an exception, and thus does not generate a stacktrace written to the logger "StackTrace". So that the StackTrace logger doesn't do anything is as expected. If you throw an exception, you will see output in stacktrace.log.

The changes in https://github.com/grails-profiles/base/commit/4a7e0d2d16cd0afe5e13e8f65b62bfbf28b05674 results in everything being written to the StackTrace logger, not only stacktraces as it used to be with earlier versions, both Grails 3 and Grails 2. So I believe this was a step in the wrong direction and should be reversed.

**Comment by slackboxster** [comment]
Is StackTrace a special name in logback (or grails) such that it has this behavior? If so, where would I find the documentation of the special names? I can look later, but I figured I would ask in case you can answer more quickly than I can search.

**Comment by rlovtangen** [comment]
Yes, it is special to Grails. Somewhere in Grails core I expect you will find som code that logs to the logger named `StackTrace`. 
You can log to this logger yourself with:

```
import org.slf4j.Logger
import org.slf4j.LoggerFactory

class BootStrap {
	
    private static Logger mylog = LoggerFactory.getLogger("StackTrace")
	
    def init = { servletContext ->
		mylog.error 'this is a new error'
    }
    def destroy = {
    }
}
```

This will end up in stacktrace.log (tested with Grails 3.1.11)

**Comment by rlovtangen** [comment]
Found it: https://github.com/grails/grails-core/blob/246b7264e8a638ada188ddba7a7a8812ba153399/grails-bootstrap/src/main/groovy/org/grails/exceptions/reporting/DefaultStackTraceFilterer.java#L106

```
public class DefaultStackTraceFilterer implements StackTraceFilterer {
    public static final String STACK_LOG_NAME = "StackTrace";
    public static final Log STACK_LOG = LogFactory.getLog(STACK_LOG_NAME);

    ...
    STACK_LOG.error(FULL_STACK_TRACE_MESSAGE, source);

```

**Comment by rlovtangen** [comment]
Didn't find any documentation about this, though.
https://github.com/grails/grails-doc/search?utf8=%E2%9C%93&q=StackTrace
