### ISSUE TITLE
Grails 3.1.6 production not working on jetty. Same on update/create on application.yml

### ISSUE THREAD

**Issue by fernandoiwamoto** [grails/grails-core#9936]
Using as comparision: grails `3.0.11` vs `3.1.6`
I was trying to deploy a single default application using only jdbc postgres and `3.1.6` fails to deploy and `3.0.11` is deployed but can't `update`, just `create-drop` on `application.yml`

### Steps to Reproduce

First create project 3.1.6 and 3.0.11 and add `runtime "org.postgresql:postgresql:9.4-1201-jdbc41"` on `build.gradle` both of them.
type: `grails prod war` or `grails war`

Put on `jetty 9.3.8.v20160314/webapps` and type `sudo service start`

### Expected Behaviour
Should be deployed 3.1.6

The 3.0.11 deployed correctly, but its only when `create-drop`, see below when is `update`.
The 3.1.6 didn't deployed, see below:

### Actual Behaviour

3.0.11 when its update:

> ERROR grails.boot.GrailsApp - Application startup failed java.lang.NullPointerException: null
>         at org.hibernate.type.descriptor.java.AbstractTypeDescriptor.extractHashCode(AbstractTypeDescriptor.java:84) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at org.hibernate.type.AbstractStandardBasicType.getHashCode(AbstractStandardBasicType.java:216) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at org.hibernate.type.AbstractStandardBasicType.getHashCode(AbstractStandardBasicType.java:220) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at org.hibernate.type.EntityType.getHashCode(EntityType.java:391) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at org.hibernate.type.ComponentType.getHashCode(ComponentType.java:258) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at org.hibernate.engine.spi.EntityKey.generateHashCode(EntityKey.java:76) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at org.hibernate.engine.spi.EntityKey.<init>(EntityKey.java:71) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
>         at 

3.1.6 trying to deploy:

> 2016-05-15 17:09:58.715:WARN:oejd.DeploymentManager:main: Unable to reach node goal: started
> java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
>         at java.util.ServiceLoader.fail(ServiceLoader.java:239)
>         at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
>         at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
>         at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
>         at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
>         at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
>         at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
>         at org.apache.tomcat.websocket.server.WsServerContainer.<clinit>(WsServerContainer.java:76)
>         at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:131)
>         at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:47)
>         at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
>         at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarte

### Environment Information

- windows7
- grails 3.0.11 / 3.1.6
- both java8_91
- jetty 9.3.8.v20160314

**Comment by graemerocher** [comment]
Tested deployment to Jetty 9.3.11.v20160721 with Grails 3.1.11 snapshot and works fine after the fixes for GSP view resolution.
