### ISSUE TITLE
GrailsWebRequest getControllerClass not scoping to namespace

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-core#9937]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1.Create 2 classes with the same name, one in a namespace. Hit endpoint for one or the other and use an interceptor. In the interceptor use `GrailsWebRequest.lookup().getControllerClass()`. The class returned is not always the one intended. It will just grab the first one by name and not take into account namespace

### Expected Behaviour

GrailsWebRequest.lookup().getControllerClass() should return the actual controller being used for the particular call

### Actual Behaviour

A controller with the same name in a different namespace is sometimes returned

### Environment Information

- **Operating System**: OS X
- **Grails Version:** 3.1.6
- **JDK Version:** 8

**Comment by Schlogen** [comment]
Will be included in 3.1.10
