### ISSUE TITLE
Domain classes with custom id generator do not use generator when Mocked while testing

### ISSUE THREAD

**Issue by gmcouto** [grails/grails-core#9938]
### Steps to Reproduce
1. create a class that implements IdentifierGenerator
2. create a Domain class that uses the custom id generator above
3. create a test-case that uses mocked domains and save them
4. run the test

### Expected Behaviour
The domain will save the instance with generated ID

### Actual Behaviour
It generates an instance without using the generator

### Environment Information
- **Operating System**: Windows 7
- **Grails Version:** 3.0.9
- **JDK Version:** 1.8 update 65

### Example Application

- TODO: I'll do it later

**Comment by graemerocher** [comment]
No example attached, either way for your case you are better off with an integration test
