### ISSUE TITLE
Scaffolded Edit-View gives incorrect feedback for an illegal update

### ISSUE THREAD

**Issue by markoschnecke** [grails/grails-core#9943]
### Steps to Reproduce

1. create an exampleDomain with a string that is not nullable
2. create a controller for that domain with static scaffold = exampleDomain
3. start the application
4. create two objects ("1" & "2")
5. edit the string in object "1" to "2"

### Expected Behaviour

The application should give an error message that the string is unique and thus can't be renamed

### Actual Behaviour

The application responds that the update was successful while the update did not actually take  place

### Environment Information

- **Operating System**: Ubuntu
- **Grails Version:** 3.1.6
- **JDK Version:** 1.7

### Example Application

See [attachment](https://github.com/grails/grails-core/files/270309/UpdateErrorExample.zip)

**Comment by jeffbrown** [comment]
> **Steps to Reproduce**
> 
> create an exampleDomain with a string that is not nullable
> create a controller for that domain with static scaffold = exampleDomain
> start the application
> create two objects ("1" & "2")
> edit the string in object "1" to "2"

> **Expected Behavior**
> 
> The application should give an error message that the string is unique and thus can't be renamed

Whey would you expect that to be considered an error?  It should be fine for 2 objects have the same value of a String property unless that property was configured with `unique: true`.

**Comment by jeffbrown** [comment]
I see now that your sample app does use `unique: true`.

**Comment by ZacharyKlein** [comment]
@jeffbrown In the sample application, looks like the `unique: true` constraint is specified.

**Comment by jeffbrown** [comment]
This should probably be reported at https://github.com/grails3-plugins/scaffolding/issues.

The problem appears to happen with the dynamic scaffolding and not the generated scaffolding.  That is worth mentioning the bug report.
