### ISSUE TITLE
How to speed up Grails test suite (currently running ~31 minutes)

### ISSUE THREAD

**Issue by jesperronn** [grails/grails-core#9946]
I took a short look at the Travis tests, and learned that one test run usually take more than half an hour.

Take this example from one of the most recent builds https://travis-ci.org/grails/grails-core/builds/131420509

Here are a few observations:

* a script `./travis-build.sh` runs a series of commands sequentially
* only java version `1.7.0_76` is tested

the test jobs are
```
./gradlew --stacktrace test -x grails-test-suite-web:test
./gradlew --stacktrace grails-test-suite-web:test
./gradlew --stacktrace --info integrationTest
```
In other words (if I am not mistaken):

1. First run all tests (but exclude grails-test-suite-web:test)
2. Then run grails-test-suite-web:test separately
3. Finally run the integrationTest phase

Between each job, the gradle daemon is stopped, which also takes time to start it up again.

I have some questions: 

* Which errors (false positives) were introduced since the gradle daemon had to be stopped?
* Why is it necessary to run ` grails-test-suite-web:test` separately?
* Is there a way to run tests in parallel (if they run in a matrix for instance like the Angular tests do it)

My first thought was to suggest splitting the tests to run them in parallel, but the build script ends by pushing artifacts. According to a discussion https://github.com/travis-ci/travis-ci/issues/1548, a deployment activity _could_ be run after all matrix jobs have run successfully. (or at least, there is a workaround for it).

There are probably also other, time consuming parts of the script, but since the output is 3455 lines, there are probably a lot of things I cannot see right now.

Comments? 

PS. Feel free to split or reference this issue from actual pull requests. I would love to see some working code examples 👍

**Comment by jeffbrown** [comment]
This is probably best served by a conversation at https://groups.google.com/forum/#!forum/grails-dev-discuss.

**Comment by graemerocher** [comment]
Many of Grails' tests are integration tests and so are longer running and since there is many of them the time adds up. As for why the Gradle daemon is stopped and the tests are split up, this is because of Travis which has limitations of memory consumption. Stopping the daemon frees up memory so that there is enough for the test cycle to complete successfully.

We can probably speed up the test run using a Travis build matrix, similar to how we do for GORM, but running tests in parallels is generally not possible due to shared static state.

**Comment by jesperronn** [comment]
Thanks for your input. Will make an attempt to speed up by running build in matrix. Will probably need some assistance and advice. 

I think that starting the three tests in a matrix, will at start the integration test at least 10 minutes earlier. So with a little luck, that could shave off the first 10 minutes.
