### ISSUE TITLE
Task war ignores grails.views.default.codec property in application.groovy in Grails 3.1.7

### ISSUE THREAD

**Issue by matveevajl** [grails/grails-core#9956]
Hello. We moved from Grails 2.4.2 to 3.1.7 and our application is deployed now on Tomcat 8.
In application.groovy there is property:

grails.views.default.codec = "none"

and it works in runtime in development mode, when application is started with grails run-app task. It works because GroovyPageParser can use Holders.config, it's not null.
And it worked later on Grails 2.4.2 for war task. And now it does not work. Gsp pages are compiled during war task, and property grails.views.default.codec = "none" in application.groovy is ignored. So now, if we want to enforce our application to work, as it was working, we need to add to every page directive <%@page defaultCodec="none" %>. 

### Steps to Reproduce

- Create a sample Grails project for version 3.1.7.
- In application.groovy set grails.views.default.codec = "none"
- Create TestController with render method

`render("template": "/testviews/test", model: ['test1' : ['name' : 'nametest', 'url': 'https://google.com']] )`
       
- Create test view with lines

`<%@ page import="grails.converters.JSON;" %>`
`<script>  var t = ${test1 as JSON} </script>`

- For the first time run grails run-app
- For the second time write grails war, then deploy and run application on tomcat

### Expected Behaviour

For both application started with grails run-app or grails war and then deploy to tomcat to see in page code 
`<script>  var t = {"name":"nametest","url":"https://google.com"} </script>` 

### Actual Behaviour

For application started with grails run-app:
`<script>  var t = {"name":"nametest","url":"https://google.com"} </script>` 

For application built with grails war and deployed to tomcat:
`<script>  var t = {&quot;name&quot;:&quot;nametest&quot;,&quot;url&quot;:&quot;https://google.com&quot;} </script>`

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.1.7
- **JDK Version:** 1.8.0_92
- **Container Version (If Applicable):** Tomcat 8.0.32

**Comment by elvanor** [comment]
I am actually very surprised that this does not work as expected, and that there is no mention of this anywhere on the Internet. It seems to me like an absolutely critical bug, that makes basically Grails 3 unusable, at least for those who want to upgrade from 2.X. It's hard to believe that we're the only one impacted by this bug???

Graeme, is there any possible workaround while waiting for a fix?
