### ISSUE TITLE
Gorm ignore column length PostgreSQL

### ISSUE THREAD

**Issue by weibemoura** [grails/grails-core#9960]
When hibernate creates tables **dbCreate = 'create-drop'** the GORM ignores the column length.
Ex:
```
class Test {
	String name
	
	static constraints = {
		name(nullable: true)
	}
	
	static mapping = {
		id(generator: 'sequence', params: [sequence: 'ids_seq'])
		table('tbl_test')
		version(false)
		cache(false)
		
		name(length: 100)
	}
}
```
When Hibernate executes SchemaExport in my bank the column is as **character varying (255) NOT NULL**, or he ignored the definition **name (length: 100)**

Environment:
Grails 3.1.7
PostgreSQL 9.5
Java 1.8.0_72

**Comment by droggo** [comment]
To limit string length shouldn't you use `maxSize` instead of `length` ?
Try `name(maxSize: 100)`

**Comment by weibemoura** [comment]
Yes, it works
I had already tested this way, the problem is I'm testing a possible migration to version 3.x and then to set **name (length: 100)** worked. Has that changed? Why in version 3.x it ignores?

**Comment by weibemoura** [comment]
Another point if I set the length in constraints instead of mapping also works.

```
static constraints = {
     name (nullable: true, length: 100)
}
static mapping = {
        id(generator: 'sequence', params: [sequence: 'ids_seq'])
        table('tbl_test')
        version(false)
        cache(false)
}
```
Graeme Rocher behavior to define column length was changed?

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/815ac25066dc74ada5c37bf451f1b200915e2583
