### ISSUE TITLE
Warning when cloning the reponsitory

### ISSUE THREAD

**Issue by gykpro** [grails/grails-core#9962]
### Steps to Reproduce

1. checkout master branch (SourceTree)

### Expected Behaviour

-

### Actual Behaviour

warning: templates not found /Users/mbasaralusrinivasa/workspace/git-scm/git-274/share/git-core/templates

### Environment Information

- **Operating System**: OSX 10.11
- **Grails Version:** 3.0.7
- **JDK Version:** 1.8.0_45

**Comment by ethman42** [comment]
So, any resolution on this? Same issue over here
