### ISSUE TITLE
Spring Endpoints Overrule Url Mappings

### ISSUE THREAD

**Issue by EpicVoyage** [grails/grails-core#9967]
Under Grails 2.1.1 - 2.5, I had an entry in `UrlMappings.groovy` for "/info". It worked great.

After upgrading to Grails 3.1.5, the entry in `UrlMappings.groovy` no longer routed to my controller action. It seems that Spring has taken over the address:

http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
http://stackoverflow.com/questions/34399972/spring-boot-actuator-cannot-disable-info-endpoint

This is what I am currently using in `application.yml` to work around the issue:

```
endpoints.enabled: false
endpoints.info.enabled: false
```

Could we either document this or disable these endpoints by default?

**Comment by sdelamo** [comment]
Spring Actuator endpoints are disabled by default since 3.1.8
