### ISSUE TITLE
3.2.0.M1 - `log.*` no longer works with non-String objects

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#9971]
### Steps to Reproduce

1. Create a fresh `3.2.0.M1` app with a controller:

 ```groovy
class LogController {
    def index() { 
        log.info "this works"
        Double notAString = 9.2
        log.info notAString
        render "OK"
    }
}
```

### Expected Behaviour

I should see the text `OK` rendered and 2 log messages

### Actual Behaviour

I see "this works" logged and then an exception:
```
ERROR org.grails.web.errors.GrailsExceptionResolver - MissingMethodException occurred when processing request: [GET] /log
No signature of method: ch.qos.logback.classic.Logger.info() is applicable for argument types: (java.lang.Double) values: [9.2]
Possible solutions: info(java.lang.String), info(java.lang.String, [Ljava.lang.Object;), info(java.lang.String, java.lang.Object), info(java.lang.String, java.lang.Throwable), info(org.slf4j.Marker, java.lang.String), info(java.lang.String, java.lang.Object, java.lang.Object). Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingMethodException: No signature of method: ch.qos.logback.classic.Logger.info() is applicable for argument types: (java.lang.Double) values: [9.2]
Possible solutions: info(java.lang.String), info(java.lang.String, [Ljava.lang.Object;), info(java.lang.String, java.lang.Object), info(java.lang.String, java.lang.Throwable), info(org.slf4j.Marker, java.lang.String), info(java.lang.String, java.lang.Object, java.lang.Object)
	at logissue.LogController.index(LogController.groovy:8)
	... 3 common frames omitted
```

**Note**: This happens for any logged class, eg: domain classes, and happens in services as well. This worked in 3.1.x and prior versions.

### Environment Information

- **Operating System**: osx 10.11.4
- **Grails Version:** 3.2.0.M1
- **JDK Version:** Oracle 1.8_66
- **Container Version (If Applicable):** embeded tomcat

**Comment by dpcasady** [comment]
This is because the default logger that is added to Grails artefacts is now an instance of SLF4J, and not JCL. Unlike JCL, none of the SLF4J logging methods take a single `Object` argument.

See <a href="http://www.slf4j.org/faq.html#string_or_object">Why don't the printing methods in the Logger interface accept message of type Object, but only messages of type String?</a> in the SLF4J FAQ.

For this to work in SLF4J you'd have to use parameterized messages:

```
class LogController {
    def index() { 
        log.info "this works"
        Double notAString = 9.2
        log.info "{}", notAString
        render "OK"
    }
}
```

**Comment by droggo** [comment]
We run into the same issue. I think quite common usage of `log.error` is to pass exception in format:
```
catch(Exception e){
    log.error e, e
}
```
which is not supported with SLF4J and would have to be changed to `log.error e.message, e` in every place in the code

**Comment by erichelgeson** [comment]
Good explanation and the rationale makes sense, but I wonder how this will affect plugins as a change, if they have any log statements will they be incompatible with grails 3.2?

**Comment by graemerocher** [comment]
it won't impact plugins, since they are pre-compiled and will continue to use Apache Commons

**Comment by erichelgeson** [comment]
The behavior is still different in 3.2.0.RC1

**Comment by graemerocher** [comment]
Will add something to the upgrade notes, nothing we can really do about this. The right thing to do is to move away from apache commons to slf4j and adding a dynamic method just to support this seems like a hack IMO

**Comment by erichelgeson** [comment]
Sounds good, just didn't want it to be missed. Thanks!
