### ISSUE TITLE
Why Jasper report Subreport doesn't get the connection inside Grails service class?

### ISSUE THREAD

**Issue by mdaynul** [grails/grails-core#9977]
A complete question is asked in http://stackoverflow.com/questions/37645533/why-jasper-report-subreport-doesnt-get-the-connection-inside-grails-service-cla
with code sample. 

I am trying to generate PDF file using Jasper report. I am using JaspersoftSoft Studio-6.2.2.final for designing the report. My application is built on Grails-3.1.7

The master-report has a subreport which displays a list of DB entries. While working in the JaspersoftSoft Studio, the preview is displayed perfectly. Also, it works fine from the controller, but not from a service class.

### Expected Behaviour

Should work from bothe service and controller class

### Actual Behaviour

Does not work from service, while from controller it works.

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.1.7
- **JDK Version:** 1.8.0_91

Apologies if I made any mistake in editing properly for this post.

**Comment by graemerocher** [comment]
Please don't post questions in the issue tracker
