### ISSUE TITLE
Grails 3.1.4 will not deploy correctly as a .war on WebLogic 12c

### ISSUE THREAD

**Issue by kossatzd** [grails/grails-core#9978]
I'm relatively new to Grails and have been developing an application locally for awhile now with little to no problems.  I'm now at a point where I need to deploy to our WebLogic 12c server and cannot get the application to startup properly.  It feels like it's just not initializing correctly on startup because I can deploy it no problems and does run, but none of the secured pages are accessible (using org.grails.plugins:spring-security-core:3.0.4) and initialization code in our BootStrap.groovy and Application.groovy files do not appear to get run.

### Steps to Reproduce

1) `grails create-app WebLogic12WithGrails314Test`
2) `cd WebLogic12WithGrails314Test`
3) `grails`
4) `create-domain-class TestDomain`
5) `generate-all *`
6) Edit TestDomain.groovy to include `String testProperty`
7) Edit BootStrap.groovy init closure with:
```
System.out.println("In BootStrap")
new TestDomain(testProperty: 'Initialized from BootStrap.groovy').save(flush: true)
```
8) Add `src/main/webapp/WEB-INF/weblogic.xml` with the following contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<wls:weblogic-web-app
		xmlns:wls="http://xmlns.oracle.com/weblogic/weblogic-web-app"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
http://java.sun.com/xml/ns/javaee/ejb-jar_3_0.xsd
http://xmlns.oracle.com/weblogic/weblogic-web-app
http://xmlns.oracle.com/weblogic/weblogic-web-app/1.4/weblogic-web-app.xsd">
	<wls:container-descriptor>
		<wls:prefer-application-packages>
			<wls:package-name>org.slf4j.*</wls:package-name>
		</wls:prefer-application-packages>
	</wls:container-descriptor>
</wls:weblogic-web-app>
```
9) Modify `build.gradle`, set `compile "org.springframework.boot:spring-boot-starter-tomcat` to provided instead of compile.
10) `war` from grails console
11) Deploy `build\libs\WebLogic12WithGrails314Test-0.1.war` to WebLogic 12c

### Expected Behaviour
There should be a message "In BootStrap" printed to the WebLogic console on startup, and there should be 1 entry when visiting the TestDomainContoller list page (inserted from BootStrap)

### Actual Behaviour
No message and the list is empty.  You can go ahead and add TestDomain entries no problem.  But the BootStrap class does not appear to get run.  This is a minimal app that demonstrates just 1 behavior I didn't expect.  Other things I've found:

- Adding more I18N resource bundles, the message codes in them do not appear to work.
- Code in Application.groovy does not get executed
- Integrating with the SpringSecurity plugin always provides an access denied message.
- unpacking that war (using `jar xvf`) and deploying it as an exploded directory, I do see my expected behavior, but I have to be able to deploy as just a war file.

### Environment Information
- **Operating System**: Windows 7 x64
- **Grails Version:** 3.1.4
- **JDK Version:** 1.7.0_60
- **WebLogic Version:** 12.1.2.0

### Example Application
I've uploaded this example application [here](https://github.com/kossatzd/WebLogic12WithGrails314Test)

**Comment by kossatzd** [comment]
Looking into this further today, using an exploded deployment does not solve all the problems.  It will run the BootStrap and the list does contain the 1 entry, but if you try to delete/update that object, you'll get a 405 (Method Not Allowed) error because the `static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]` prevents it, even though the submitted requests do have the _method=PUT/DELETE request attribute.

**Comment by graemerocher** [comment]
I fixed the `url = classLoader.getResource("../../" + BUILD_INFO_FILE)` issue.. The remaining issues sound like web logic issues
