### ISSUE TITLE
Grails option `grails.resources.pattern = '/**'` causes the "No Session found for current thread" 

### ISSUE THREAD

**Issue by alex-shamshurin** [grails/grails-core#9980]
I use interceptors to generate SEO friedly URL by adding a language code to the path, like

    http://localhost:8080/en
    http://localhost:8080/ru

and  I noticed that "before" interceptor with redirects to path with language marker may throw "hibernate session not found error". It happens if unknown path is provided in a route  instead of lang code. For example localhost/fr must return  404 error in my configuration (because of url mapping constraint), but it throws "hibernate session not found error" . This happens ONLY IF this config option exists.

     `grails.resources.pattern = '/**'` (any value)

### Steps to Reproduce

1. Add option to application.groovy

   ` grails.resources.pattern = '/**'``

2. Add  routing 

```
class UrlMappings
{

	static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

		"/$lang/$controller/$action?/$id?(.$format)?" {
			constraints {
				lang(matches: /en|ru/)
			}
		}

		"/"(view: "/index")

		"/$lang/" {
			view = '/index'
			constraints {
				lang(matches: /en|ru/)
			}
		}

		"500"(view: '/error')
		"404"(view: '/notFound')
	}
}

```

3. Add interceptor

```
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.web.servlet.support.RequestContextUtils

class LocaleInterceptor
{
	def         springSecurityService
	Logger      logger = LoggerFactory.getLogger(getClass())

	LocaleInterceptor()
	{
		matchAll().excludes(controller: ~/(logout)/)
	}

	/**
	 * Redirects to /lang_code/...
	 * @return
	 */
	boolean before() {
		if (!params?.lang) {
			String lang = RequestContextUtils.getLocale(request).language
			String uri = "/${lang}${request.getRequestURI()}"
			logger.debug('uri is: ' + uri)
			if (uri.indexOf('error') == -1) {
				redirect(uri: uri)
				return false
			}
		}

		true
	}

}
```

4. Start the app and navigate to http://localhost:8080/asdasdasd

### Expected Behaviour

404 error must be shown

### Actual Behaviour

```
Error 500: Internal Server Error
URI
/asdasd
Class
org.hibernate.HibernateException
Message
Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
Caused by
No Session found for current thread
Around line 27 of grails-app\controllers\test\LocaleInterceptor.groovy
24:			String uri = "/${lang}${request.getRequestURI()}"
25:			logger.debug('uri is: ' + uri)
26:			if (uri.indexOf('error') == -1) {
27:				redirect(uri: uri)
28:				return false
29:			}
30:		}
Trace
    Line | Method
->>  101 | redirectResponse in grails.web.mapping.ResponseRedirector
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     79 | redirect         in     ''
|    120 | redirect . . . . in grails.artefact.controller.support.ResponseRedirector$Trait$Helper
|     27 | before           in LocaleInterceptor.groovy
|   1142 | runWorker . . .  in java.util.concurrent.ThreadPoolExecutor

```

### Environment Information

- **Operating System**: win
- **Grails Version:** 3.1.8
- **JDK Version:** 1.8

### Example Application

https://github.com/salex772/redirect-issue

**Comment by zyro23** [comment]
i think i faced a related (likely the same) issue recently. wrote down some notes but did not yet get to raise a corresponding issue. hope this helps here:

* grails interceptor adapter: `MappedInterceptor` --> autowired by all `HandlerMapping`s
* osivi etc.: `HandlerInterceptor` --> only autowired by `UrlMappingsHandlerMapping`

`resourceHandlerMapping`, `webSocketHandlerMapping` are `AbstractHandlerMapping`s --> only `MappedInterceptor`s are autowired (no osivi)

that means no osivi if request is not matched by `UrlMappingsHandlerMapping` but passed through to other handlerMappings --> no session bound ...

that observation would fit to this issue: request targets `resourceHandlerMapping`, grails interceptor adapter is applied but not osivi..

`order`s for reference: `UrlMappingsHandlerMapping`: `-5`, `ResourceHandlerMapping`: int.MAX_VALUE-1, `WebSocketHandlerMapping`: int.MAX_VALUE

**Comment by graemerocher** [comment]
This is a bug in GORM, fixed by the above commit
