### ISSUE TITLE
Issues with specialization in transactional services

### ISSUE THREAD

**Issue by clessiomendes** [grails/grails-core#9989]
### Description

When implementing a specialized Grails service (inherited from another concrete service class) I'm ending up with a weird duplicated transactionManager property (one of them null) injected within the specialized service.
I went through a simple service specialization pattern understanding that all would work in a transparent way, but I started to go into trouble regarding transaction management under the spring/grails hood. Issues happen when a method from the specialized class is called and a new transaction is opened by the AOP infraestructure. 
More: http://stackoverflow.com/q/37740143/1916198 and http://stackoverflow.com/q/37716752/1916198

### Steps to Reproduce

1. Create a service (say MammalService) and annotate it with @grails.transaction.Transactional
2. Implement method mammalMethod() and annotate it with @Transactional(readonly=true)
3. Create another service (say DogService), extending from MammalService, and annotate it also with @Transactional
4. Override mammalMethod() and also annotate it with @Transactional(readonly=true)
5. From any controller class, declare the dogService and call dogService.mammalMehtod()

### Expected Behaviour

The transaction should be opened at the service method call, by the AOP mechanismo under Grails.

### Actual Behaviour

If you put a breakpoint in the controller, just beffore calling the service, you will be able to see the service instance with TWO IDENTICAL ATTRIBUTES transactionManager, one of them, null.
![image](https://cloud.githubusercontent.com/assets/3195100/15988337/a0732b86-3022-11e6-99af-c795747bcccd.png)
If you keep running from there, the AOP transaction mechanism will throw a NullPointerException, as it tries to use one of the transactionManager attributes that is null. (the stacktrace itself is hidden inside the AOP methods, and isn't printed to logs).

Also, if you remove the @Transactional from the specialized service class, but keep individual @Transactional annotations on methods, the AOP transaction mechanism enters in a loop until StackOverflowException is raised. That could be an independent bug, but I think it is directly linked to the original one.

### Environment Information

- **Operating System**: Windows and Linux
- **Grails Version:** 2.4.3 and 2.5.1 (could not test with 3.X)
- **JDK Version:** 7
- **Container Version (If Applicable):** Tried Tomcat and Jetty

### Example Application

@Transactional
public class MammalService {
  @Transactional(readonly=true)
  public mammalMethod() {
  }
}

@Transactional
public class DogService extends MammalService {
   @Transactional
   @Override
   public mammalMethod() {
   }
   @Transactional
   public dogMethod() {
       mammmalMethod()
   }
}

public class DogController {
    def dogService
    def action() {
        dogService.dogMethod()
    }
}

**Comment by graemerocher** [comment]
This is not an issue in newer versions of Grails, only in 2.5.x.. the solution is to upgrade
