### ISSUE TITLE
actuator reveiling server information 

### ISSUE THREAD

**Issue by ridea-co** [grails/grails-core#9990]
### Steps to Reproduce

1. Create a new Grails project (grails create-app --profile=web actuator)
2. gradle bootRun

### Behaviour

navigate to http://localhost:8080/env
navigate to http://localhost:8080/dump
navigate to http://localhost:8080/trace

Sensitive information are shown (Including db username, cookie id, etc, etc...).  Which leads to security issue.

### Environment Information

- **Grails Version:** 3.1.8
- **JDK Version:** 1.8.0_51

**Comment by graemerocher** [comment]
Just remove the actuator dependency from your `build.gradle` or secure the end points with Spring Security

**Comment by beckje01** [comment]
This is caused by a bug in actuator https://github.com/spring-projects/spring-boot/issues/5875 Once that is fixed Grails could add a request attribute of `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` if it isn't already.

**Comment by beckje01** [comment]
What about changing the default to turn off these endpoints?

**Comment by graemerocher** [comment]
https://github.com/grails/grails-profile-repository/commit/faee52a77163b5cd22be6645bc19704fa379edf7
