### ISSUE TITLE
Error while deploying app on tomcat

### ISSUE THREAD

**Issue by Rapso** [grails/grails-core#9993]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

http://stackoverflow.com/questions/37749820/grails-3-1-8-with-spring-security-core-using-multiple-datasources
1. create new app with web profile.
2. add spring security core plugin in build.gradle file
3. create more then one datasource, coudl be h2 memory db, but i tested it with oracle and mssql datasources
4. build war file
5. try to deploy it on tomcat

### Expected Behaviour

application shoud be deployed

### Actual Behaviour
deployment fails

### Environment Information

- **windows 8**: 
- **3.1.8:** 
- **1.8.91:** 
- **tomca 8.35:** TODO

### Example Application
stacktrace : http://pastebin.com/bT1ztRbs
http://stackoverflow.com/questions/37749820/grails-3-1-8-with-spring-security-core-using-multiple-datasources
https://bitbucket.org/trokitasnt/grailstest

**Comment by Rapso** [comment]
in https://github.com/grails/grails-core/releases/tag/v2.5.0 in section Changes in ehcache version in hibernate plugins we can see similiar problem to mine, but since its 2.5 release information i think it was fixed in grails 3. Anyway solution with setting other factory class and shared to true helps. I think it may be considered as temporary solution and there is some kind of conflict between default configuration with plugin configuration.

**Comment by graemerocher** [comment]
Changed to use the singleton factory by default. https://github.com/grails/grails-profile-repository/commit/40b65b035ba27b06c6ea974e84b34dd7bf8c1eb2
