### ISSUE TITLE
11.5 Validation and Internationalization - documentation improvement for constraint code messages

### ISSUE THREAD

**Issue by edwardotis** [grails/grails-core#9995]
Hi,

The example for Constraints and Message Codes is confusing for new users. It uses a special case example, blank, that is not the common case for writing custom messages on constraints.

The exception to the common case is that the constraint name matches the property name exactly:
Error Code: className.propertyName.blank

The common case is that the constraint name does not match the error code.
For instance, maxSize:

The following wrong, but this is how almost every new user will attempt to use custom error codes after viewing the example in the documentation.

Error Code: className.propertyName.maxSize 

This is the common case.
Error Code: className.propertyName.maxSize.exceeded
http://docs.grails.org/latest/ref/Constraints/maxSize.html

For newbies, this is frustrating because the pattern looks so clear in the documentation example with 'blank'.

Please use something other than 'blank' in the example. It's very important to highlight the common case in the example and show the user that they must do an extra look up in documentation to find the correct code.
Using maxSize or size would make it crystal clear.

Here's a stackoverflow that finally made the issue clear to me and others .

http://stackoverflow.com/a/20386620/258896

Also, I recognize that this line in the docs technically covers this issue:
"For a reference on what codes are for which constraints refer to the reference guide for each constraint."

However, using 'blank' in the only example is still quite confusing for new users.

Thanks,

Ed

**Comment by Schlogen** [comment]
@edwardotis A PR to grails-doc would be welcomed
