### ISSUE TITLE
@Autowired fails to create Bean in test environment.

### ISSUE THREAD

**Issue by naman90** [grails/grails-core#9997]
### Expected Behaviour

When configuration (grails.spring.bean.packages= ['']) is defined in application.groovy to create Bean from a specified location, it should create Bean and inject all the dependencies.

### Actual Behaviour

When configuration (grails.spring.bean.packages= ['']) is defined in application.groovy to create Bean from a specified location, then @Autowired cannot instantiate Grails Service class in those Beans. This is only happening in test environment. 

### Environment Information
Application is running successfully in development environment but fails in test environment
- **Operating System**: Windows
- **Grails Version:** 3.2.0.M1
- **JDK Version:** 1.8.0_25

### Example Application

- https://github.com/naman90/spring-autowire-error

### Steps to Reproduce

1.  Clone above repo
2.  grails test-app will fail
3.  grails run-app will run the app

**Comment by graemerocher** [comment]
With unit testing you have to use `doWithSpring` to setup the necessary beans. Otherwise use integration testing.
