### ISSUE TITLE
Regression in DomainClass.withTransaction WRT rollback on checked exception

### ISSUE THREAD

**Issue by mbezjak** [grails/grails-core#9998]
I found out about this regression yesterday but as far as I can tell, it's present since version 2.0. Of course, it was in a production setting; in a banking application. :/

Consider the following example:

```groovy
void transfer(Account fromAccount, Account toAccount) {
    Account.withTransaction {
        fromAccount.amount -= 100
        toAccount.amount += 100

        def sql = new groovy.sql.Sql(dataSource)
        sql.execute 'call procedure finalize_transfer();'
    }
}
```

Also consider that the procedure `finalize_transfer` fails for some reason (e.g. due to a lock timeout). By failing I mean it throws a `java.sql.SQLException`. What would you expect to happen to `fromAccount.amount` and `toAccount.amount`?

### Grails 1.3.7

In grails 1.3.7, the whole transaction would rollback. This is something I would expect to be the case given that we are talking about groovy here (no difference between checked and unchecked exceptions). The reason _why_ is because back in the 1.3.7 days, `withTransaction` used to just use spring's `TransactionTemplate` and it rolls back on any throwable. Relevant refs:
- https://github.com/grails/grails-core/blob/v1.3.9/src/java/org/codehaus/groovy/grails/plugins/orm/hibernate/HibernatePluginSupport.groovy#L501
- https://github.com/spring-projects/spring-framework/blob/v3.0.5.RELEASE/org.springframework.transaction/src/main/java/org/springframework/transaction/support/TransactionTemplate.java#L142

### Grails 2.5.1

In grails 2.5.1, however, the transaction does **not** rollback. The reason is because spring's `TransactionAttribute` is being used in form of `GrailsTransactionAttribute`. If we take a look at the source code of `DefaultTransactionAttribute.rollbackOn` and `TransactionTemplate`, they are not compatible with each other. Former rolls back on any unchecked exception and error; latter on any throwable. It's funny because the documentation on `rollbackOn` actually says:

> This is consistent with TransactionTemplate's default behavior.

However that is not the case (source codes differ in meaning). At least not when the code is written in groovy. Relevant refs (just follow the code):
- https://github.com/grails/grails-data-mapping/blob/v3.1.5/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/GormStaticApi.groovy#L715
- https://github.com/grails/grails-data-mapping/blob/v3.1.5/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/GormStaticApi.groovy#L815
- https://github.com/grails/grails-core/blob/v2.5.1/grails-core/src/main/groovy/org/codehaus/groovy/grails/orm/support/GrailsTransactionTemplate.groovy#L93
- https://github.com/spring-projects/spring-framework/blob/v4.1.6.RELEASE/spring-tx/src/main/java/org/springframework/transaction/support/TransactionTemplate.java#L132
- https://github.com/spring-projects/spring-framework/blob/v4.1.6.RELEASE/spring-tx/src/main/java/org/springframework/transaction/interceptor/DefaultTransactionAttribute.java#L97

### no way to override

Moreover, just by looking at the code, there is no clear way to override the behaviour (because of the use of `new` operator):

1. GormStaticApi.withTransaction: `withTransaction(new DefaultTransactionDefinition(), callable)`
2. GormStaticApi.withTransaction: `new GrailsTransactionTemplate(transactionManager, definition).execute(callable)`
3. GrailsTransactionTemplate.constructor: `new GrailsTransactionAttribute(transactionDefinition)`
4. GrailsTransactionTemplate.execute: `transactionAttribute.rollbackOn(e)`
5. DefaultTransactionAttribute.rollbackOn: `return (ex instanceof RuntimeException || ex instanceof Error);`

### rollback-on-exception

I did create a workaround in form of https://github.com/mbezjak/rollback-on-exception version `0.2` but it relies on hack - classloading priority - that I would rather want to avoid if at all possible. Anyway, if you take a look at https://github.com/mbezjak/rollback-on-exception, relevant classes are:
- https://github.com/mbezjak/rollback-on-exception/blob/0.2/src/java/org/codehaus/groovy/grails/transaction/GrailsTransactionAttribute.java (copy/paste from grails 2.5.1 + override `rollbackOn`)
- https://github.com/mbezjak/rollback-on-exception/blob/0.2/test/app/plugin-installed/grails-app/services/NotTransactionalService.groovy#L28 (test example that uses `withTransaction`)
- https://github.com/mbezjak/rollback-on-exception/blob/0.2/test/app/plugin-not-installed/test/integration/AllSpec.groovy#L77 (stuff that happens when the plugin is not installed)
- https://github.com/mbezjak/rollback-on-exception/blob/0.2/test/app/plugin-installed/test/integration/AllSpec.groovy#L77 (stuff that happens when the plugin is installed)

### alternative workaround

Another potential workaround would be to use `withTransaction` as:
```groovy
def definition = new org.codehaus.groovy.grails.transaction.GrailsTransactionAttribute() {
    @Override boolean rollbackOn(Throwable e) {
        true
    }
}
Domain.withTransaction(definition) {
    // now things with rollback on any exception
}
```

However, I would need to change hundreds of lines in my workspace (multiple projects and plugins) + remember to never ever write `DomainClass.withTransaction` again. For that reason, I wouldn't consider the above to be a valid workaround.

### note

Final note: we are here only considering `DomainClass.withTransaction` method, not services with `static transactional = true`.

Anyway, what are your thoughts on the matter?

**Comment by graemerocher** [comment]
Too big a change to go into 3.1 but will go into 3.2

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/a6aa8e69799b886b0d713ecaeef13938ea32e97b
